### ISSUE TITLE
是否可以考虑加指针和注释的用法呢

### ISSUE THREAD

**Issue by dengyingguo** [pyecharts/pyecharts#100]
如题，可视化中，指针和注释用法非常方便数据的展示，如：突出异常和重点数据。不知道是否会考虑加这个功能呢

我在公司内部力推这个包，真的很好用，也非常容易懂。

**Comment by chenjiandongx** [comment]
后续版本可以考虑考虑 不过暂时会停止更新新版本 休息一下

**Comment by chenjiandongx** [comment]
此功能不会被加入到新版本中
