### ISSUE TITLE
图表的左右两边空白过多

### ISSUE THREAD

**Issue by shshjun** [pyecharts/pyecharts#1000]
**问题**
图表的左右边空白过多， 在不显示右侧的toolbox的时候更明显。
希望图表只做图表的事。空白留给template页面处理

**运行环境（系统环境及 pyecharts 版本）**
win10+py2.7

**代码及截图**
参考了 https://blog.csdn.net/weixin_37930716/article/details/81237183
chart.py 在以下两行的下面增加第三行，从而粗暴解决了这个问题。
            backgroundColor=background_color,
            animation=self.is_animation,
            grid={ "x": 20, "x2": 20, "y": 12 }, #，新添加代码行，去除左右空白
截图略。

**Comment by hulining** [comment]
![image](https://user-images.githubusercontent.com/27631386/56104696-6577cc00-5f6b-11e9-8b43-f6fc998b4b44.png)
您是指x轴两边的留白太多了吗, 可以试试将  "is_xaxis_boundarygap" 配置置为False (pyecharts版本为0.5.x ,新版的应该是"boundary_gap"配置项)

**Comment by shshjun** [comment]
嗯，是的。看到有评论说"boundary_gap"只对category的数据有效。我的数据是value.

不过以上建议用的这种hack也挺好的。对单个应用有效。如何集成就不知道了。

**Comment by shshjun** [comment]
咦，我说的不是两个框内的空白，是说框的外边的空白太多，即x轴两端以外，而不是两端到实际图形之间的空白。
![ZCIBS0@DEN$9)SH U1AZQ{K](https://user-images.githubusercontent.com/816453/56108810-50f1fe80-5f80-11e9-9303-566e25d112c7.png)

**Comment by hulining** [comment]
> 咦，我说的不是两个框内的空白，是说框的外边的空白太多，即x轴两端以外，而不是两端到实际图形之间的空白。
> ![ZCIBS0@DEN$9)SH U1AZQ{K](https://user-images.githubusercontent.com/816453/56108810-50f1fe80-5f80-11e9-9303-566e25d112c7.png)

这个我就不清楚了, 不好意思哈

**Comment by sunhailin-Leo** [comment]
@shshjun @hulining  pycharts 1.0.0 有 Grid 图的配置了。

* Ps: @shshjun 该换 Python 3.6 + 了 😄 

```python
class GridOpts:
    def __init__(
        self,
        pos_left: Optional[str] = None,
        pos_top: Optional[str] = None,
        pos_right: Optional[str] = None,
        pos_bottom: Optional[str] = None,
        width: Optional[Numeric] = None,
        height: Optional[Numeric] = None,
    ):
        self.opts: dict = {
            "left": pos_left,
            "top": pos_top,
            "right": pos_right,
            "bottom": pos_bottom,
            "width": width,
            "height": height,
        }
```

**Comment by shshjun** [comment]
认真看了下，新的GridOpts class似乎只在 并行显示多张图 时起作用。并不解决我前面提到的问题。请sunhailin-Leo确认。

**Comment by shshjun** [comment]
幸运的是，前述办法 - 修改chart.py - 依然粗暴有效：
        self.options.update(
            series=[],
            legend=[{"data": [], "selected": dict()}],
            tooltip=opts.TooltipOpts().opts,
            grid={ "x": 20, "x2": 20, "y": 12 }, #，新添加代码行，去除左右空白
        )

**Comment by sunhailin-Leo** [comment]
@shshjun 单一的图， 套一个 Grid 也是可以用的
* 例如我要把一个 bar 图放大左下角
```python
grid = (
    Grid()
    .add(bar, grid_opts=opts.GridOpts(pos_left="10", pos_right="45%", pos_top="70%", pos_bottom="5"))
)
```

**Comment by weichen1018** [comment]
此刻我也遇到这个问题，图表两边的留白太多，而我在文档中找了半天，并没有找到如何解决图表两边留白过多的方法。
![image](https://user-images.githubusercontent.com/38155568/57291607-5a3f3880-70f2-11e9-951a-48988104e128.png)
看到您说套一个Grid，但是像饼图的话是用不了Grid的，该如何破。

**Comment by chenjiandongx** [comment]
@weichen1018 

示例代码
```python
def pie_position() -> Pie:
    c = (
        Pie()
        .add(
            "",
            [list(z) for z in zip(Faker.choose(), Faker.values())],
            center=["35%", "50%"],
        )
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Pie-调整位置"),
            legend_opts=opts.LegendOpts(pos_left="15%"),
        )
        .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
    )
    return c
```

诺，是不是好多了

![image](https://user-images.githubusercontent.com/19553554/57317851-a5297200-712b-11e9-9f06-b46698ed42cc.png)

**Comment by weichen1018** [comment]
感谢东哥
