### ISSUE TITLE
中文文档某些页面打不开

### ISSUE THREAD

**Issue by curiositer** [pyecharts/pyecharts#1001]
**问题**
中文文档，好多页面都无法打开，出现404错误

包括以下等等：
https://pyecharts.org/#/zh-cn/chart_api
https://pyecharts.org/#/zh-cn/flask

**Comment by XuSirSir** [comment]
Please use this reference document that version is 0.5.11，you used document to show 404 because its version is 1.0.0 document that is not finished yet.

**Comment by curiositer** [comment]
I hope you can solve the problem, or please give me a url about the docs.
Now I learn the pycharts from other websites, instead I want to use the official docs,thanks a lot!

regards,
John

**Comment by XuSirSir** [comment]
if you want to use pyecharts in Django or Flask, you can use this link(https://05x-docs.pyecharts.org/#/zh-cn/django),but 0.5.11 document used in 1.0.0 maybe has some mistakes. Therefore, you can combine 0.5.11 document with 1.0.0 document（https://pyecharts.org/#/zh-cn/django）.

**Comment by chenjiandongx** [comment]
404 不是因为错误，而是因为我还没写。。。。 最近太忙了，没时间写，而且写这么多文档也有点累。。。

**Comment by chenjiandongx** [comment]
@curiositer @XuSirSir 现在的情况是这样的，如果使用的是 0.5.11 版本的话，文档在 05x-docs.pyecharts.org 这个在 README 中有提到，v1.0.0 的话由于现在还未正式发布，暂时只能通过源码安装，文档在 pyecharts.org，v1.0.0 的版本还在持续的完善中，不过参考着 example 里面的示例用基本也就差不多了

**Comment by curiositer** [comment]
@chenjiandongx 哈哈，辛苦啦，要到这个网站 05x-docs.pyecharts.org就知足了，我是在想那么好用的东西却没有文档真是太可惜了，要是有时间我也搭把手，加油！！
