### ISSUE TITLE
1.0.0版本render_embed, Page中添加bar报错

### ISSUE THREAD

**Issue by Kewings** [pyecharts/pyecharts#1002]
```
from pyecharts.custom.page import Page

def echarts():
    page = Page()
    ...
    line.add_xaxis(x)
    bar.add_xaxis(x)
    bar.add_yaxis(s, t)
    line.add_yaxis(s, p, is_smooth=True)
    page.add_chart(bar)
    page.add_chart(line)
    return page.render_embed()
```

报错信息如下：
```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\xxxx\xxxx\views.py", line 17, in index
    'Echarts': echarts()
  File "D:\Projects\xxxx\xxxx\echarts.py", line 52, in TMcharts
    return page.render_embed()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyecharts-1.0.0-py3.7.egg\pyecharts\custom\page.py", line 105, in render_embed
    return Markup("<br/> ".join([chart.render_embed() for chart in self]))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyecharts-1.0.0-py3.7.egg\pyecharts\custom\page.py", line 105, in <listcomp>
    return Markup("<br/> ".join([chart.render_embed() for chart in self]))
AttributeError: 'Bar' object has no attribute 'render_embed'
```

求帮助，谢谢。

**Comment by sunhailin-Leo** [comment]
@Kewings 你确定你用的方法没错？ Page 里面没有 render_embed 的方法

**Comment by Kewings** [comment]
在custom里有个page，里面的Page有page_embed
0.5.11版本的page_embed正常的

**Comment by Kewings** [comment]
@sunhailin-Leo pyecharts里的base.py中的Base()该怎么使用，这个Base里有render_embed，我试了应该是初始化了一个div容器
求教，谢谢。

**Comment by sunhailin-Leo** [comment]
@Kewings 
* 首先，先认真确定你的 pyecharts 的版本是 1.0.0。
* 其次 1.0.0 已经没有 render_embed 的方法了。

**Comment by Kewings** [comment]
@sunhailin-Leo 

确定一定以及肯定是1.0.0版本：
`from pyecharts.custom.page import Page`
这里有Page的render_embed，但是当Page.add_chart后，Chart本身没有render_embed方法了。

这个功能在0.5.11里是正常的

**Comment by sunhailin-Leo** [comment]
@Kewings 
* 烦请再次确认版本是否为 1.0.0。
* 源码项目截图:
![image](https://user-images.githubusercontent.com/17564655/56332625-a9650e00-61c3-11e9-9408-3f109b32a5bc.png)

* Pycharm 全局截图
![image](https://user-images.githubusercontent.com/17564655/56332654-c7327300-61c3-11e9-9278-9352cefc2e8d.png)

* Page 类结构截图
![image](https://user-images.githubusercontent.com/17564655/56332704-fb0d9880-61c3-11e9-92d0-8b9e5f69253e.png)

**Comment by sunhailin-Leo** [comment]
@Kewings 
* 只有 0.5.11 项目结构才符合你贴出来的引入路径
![image](https://user-images.githubusercontent.com/17564655/56332774-40ca6100-61c4-11e9-9784-b80015d630b2.png)

* ```master``` 分支下的是 ```0.5.11```；```2019``` 分支下是 ```1.0.0```；

**Comment by Kewings** [comment]
OK, 谢谢，我回家后做下确认，代码在家里。

也有可能是当时我用源码先做过一次master分支的install，后来又切换到2019做了一次install，可能混乱了？
昨晚我还特意追踪过代码，目测跟Master的结构以及跟2019的结构混合了。。。

**Comment by Kewings** [comment]
![image](https://user-images.githubusercontent.com/29881381/56361898-1a83e000-621b-11e9-8e85-0609067d3ec3.png)
Look，我的库里真的有custom文件夹，估计是真如我所说的，先install了master分支，后又操作了2019分支，就出现这个情况，我重装下看看

**Comment by Kewings** [comment]
确定是这个情况了，0.5.11 build后build目录和dist目录保留了0.5.11的源文件，切换到2019再做编译的时候，两个版本的内容合起来了，打包egg的时候就有了两个版本的内容，交错了。

估计还是rmtree没删除干净

**Comment by Kewings** [comment]
问题解决，可以关闭了，谢谢
