### ISSUE TITLE
line位置偏移

### ISSUE THREAD

**Issue by burryxie** [pyecharts/pyecharts#1003]
**问题**
line画图的时候，得到的图形与画图数据不一致，发生位置偏移
画图数据:attr = [1,2,3,4,...,19,20]，注意是从1开始的
作图代码如下
```
    line = Line('乘距分布--'+line_name)
    line.add('工作日',attr,workday_perc,mark_line_coords=[[workday_avg_dis, 0], [workday_avg_dis, 0.1]])
    line.add('非工作日',attr,weekend_perc,mark_line_coords = [[weekend_avg_dis, 0],[weekend_avg_dis,0.1]])
    line.add('节假日',attr,holiday_perc,mark_line_coords = [[holiday_avg_dis,0],[holiday_avg_dis,0.1]])
    line.render()
```
得到的结果是
![image](https://user-images.githubusercontent.com/14790133/56177773-658ecf00-6032-11e9-90d4-fa1eace76f20.png)，结果显示是从2开始的？？
另外，我的mark_line_coords里的坐标按理来说是不相等的，但是结果里的markline是重叠在一起的？？

**运行环境（系统环境及 pyecharts 版本）**
Python 3.6
pyecharts:0.5.11

**代码及截图**

**Comment by chenjiandongx** [comment]
请确保你的 1 的点不为 nan（如果你是使用 pandas, numpy 的话）

**Comment by burryxie** [comment]
> 请确保你的 1 的点不为 nan（如果你是使用 pandas, numpy 的话）

确定不是nan啊

**Comment by chenjiandongx** [comment]
@burryxie 最好把 x 轴的数据改变为 str

**Comment by burryxie** [comment]
> @burryxie 最好把 x 轴的数据改变为 str

正解！！多谢！！
