### ISSUE TITLE
Table用不了啊

### ISSUE THREAD

**Issue by BoragoCode** [pyecharts/pyecharts#1006]
**问题**
源码中提供的Table功能用不了，怎么Table class中的Python语法有类型？

**运行环境（系统环境及 pyecharts 版本）**

mac

**代码及截图**
from pyecharts.components import Table
ImportError: No module named components

**Comment by sunhailin-Leo** [comment]
@BoragoCode Please show your code.

**Comment by BoragoCode** [comment]
Thanks，my code：
# coding=utf-8
from pyecharts.components import Table
def table_base():
    table = Table()

    headers = ["City name", "Area", "Population", "Annual Rainfall"]
    rows = [
        ["Brisbane", 5905, 1857594, 1146.4],
        ["Adelaide", 1295, 1158259, 600.5],
        ["Darwin", 112, 120900, 1714.7],
        ["Hobart", 1357, 205556, 619.5],
        ["Sydney", 2058, 4336374, 1214.8],
        ["Melbourne", 1566, 3806092, 646.9],
        ["Perth", 5386, 1554769, 869.4],
    ]
    table.add(headers, rows)

**Comment by BoragoCode** [comment]
> @BoragoCode Please show your code.

Thanks，my code：
# coding=utf-8
from pyecharts.components import Table
def table_base():
    table = Table()

    headers = ["City name", "Area", "Population", "Annual Rainfall"]
    rows = [
        ["Brisbane", 5905, 1857594, 1146.4],
        ["Adelaide", 1295, 1158259, 600.5],
        ["Darwin", 112, 120900, 1714.7],
        ["Hobart", 1357, 205556, 619.5],
        ["Sydney", 2058, 4336374, 1214.8],
        ["Melbourne", 1566, 3806092, 646.9],
        ["Perth", 5386, 1554769, 869.4],
    ]
    table.add(headers, rows)

**Comment by sunhailin-Leo** [comment]
@BoragoCode  `render` it.
