### ISSUE TITLE
Scatter3D 视觉映射无法同时设置color和size

### ISSUE THREAD

**Issue by niuzhenjiang** [pyecharts/pyecharts#1007]
Scatter3D 在画3D散点图时视觉映射无法同时设置color和size，请问有什么方法可以实现这个功能吗？
我在echarts的官网demo上面发现视觉映射是可以同时 设置的，请问pyecharts 可以设置吗？该如何设置呢？

下面是我的代码：
page = Page()# st
        data = [[random.randint(0, 100), random.randint(0, 100), random.randint(0, 100)] for _ in range(80)]
        range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
                    '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
        scatter3D = Scatter3D("3D 散点图示例", width=1200, height=600)   #设置图表的高和宽
        scatter3D.add("",data,is_visualmap=True,visual_type='color',visual_range_color=range_color) #视觉映射和颜色选择
        scatter3D.add("", data,is_visualmap=True,visual_type='size',visual_range_size = [20,50]) #视觉映射和大小选择
        page.add(scatter3D)
        page.render()

**Comment by sunhailin-Leo** [comment]
@niuzhenjiang 贴一下官网的 demo 地址和你现在代码渲染出来的截图。

**Comment by niuzhenjiang** [comment]
> @niuzhenjiang贴一下官网的demo地址和你现在代码渲染出来的截图。

[官网的demo地址：](https://echarts.baidu.com/examples/editor.html?c=scatter3d&gl=1&theme=dark)

以及我上面生成的截图：


![1555553297(1)](https://user-images.githubusercontent.com/42111602/56332242-1c6d8500-61c2-11e9-8c68-7d32ea2c648d.png)

因为我上面的代码是写了两行的，所以在执行的时候最后设置散点size的把color的给覆盖掉了，未产生效果

**Comment by sunhailin-Leo** [comment]
@niuzhenjiang 
* 我看你的代码是 0.5.11 之前的，我就没有去尝试了，你可以研究下源码，对比一下官方的示例。
* 你这个问题我在 1.0.0 版本试了一下，暂时还真的无法设置。
* 原因：
    * 暂时 Visumap Option 返回的 json 配置是 dict 模式，如果要既设置 size 又设置 color 的话，得返回一个 list 数据结构。现阶段 1.0.0 的代码暂时还无法实现，之后会作出修改。

**Comment by niuzhenjiang** [comment]
> @niuzhenjiang
> 
> * 我看你的代码是 0.5.11 之前的，我就没有去尝试了，你可以研究下源码，对比一下官方的示例。
> * 你这个问题我在 1.0.0 版本试了一下，暂时还真的无法设置。
> * 原因：
>   
>   * 暂时 Visumap Option 返回的 json 配置是 dict 模式，如果要既设置 size 又设置 color 的话，得返回一个 list 数据结构。现阶段 1.0.0 的代码暂时还无法实现，之后会作出修改。

嗯嗯，好的，我已经根据源码 修改了一下，暂时可以达到我的需求了，但是还是希望官方能够给出一个具体的解决措施，谢谢啦。
![Uploading 捕获.PNG…]()

**Comment by chenjiandongx** [comment]
@niuzhenjiang 

问题不大

![image](https://user-images.githubusercontent.com/19553554/56858278-f1e1b000-69a9-11e9-8561-34e5ef292dd7.png)

**Comment by niuzhenjiang** [comment]
> @niuzhenjiang
> 
> 我看你的代码是 0.5.11 之前的，我就没有去尝试了，你可以研究下源码，对比一下官方的示例。
> 
> 你这个问题我在 1.0.0 版本试了一下，暂时还真的无法设置。
> 
> 原因：
> 
> 暂时 Visumap Option 返回的 json 配置是 dict 模式，如果要既设置 size 又设置 color 的话，得返回一个 list 数据结构。现阶段 1.0.0 的代码暂时还无法实现，之后会作出修改。
> 嗯嗯，好的，我已经根据源码 修改了一下，暂时可以达到我的需求了，但是还是希望官方能够给出一个具体的解决措施，谢谢啦。

![捕获](https://user-images.githubusercontent.com/42111602/56858280-f5753700-69a9-11e9-9309-fc6af52dff61.PNG)

**Comment by niuzhenjiang** [comment]
> @niuzhenjiang
> 
> 问题不大
> 
> ![image](https://user-images.githubusercontent.com/19553554/56858278-f1e1b000-69a9-11e9-8561-34e5ef292dd7.png)

你这也是通过修改源码 设置获得的吗？

**Comment by chenjiandongx** [comment]
嗯，不过我大概是叫做提供 feature，不叫修改源码

**Comment by niuzhenjiang** [comment]
> 嗯，不过我大概是叫做提供 feature，不叫修改源码

那方便给出修改内容么，感谢~

**Comment by sunhailin-Leo** [comment]
@niuzhenjiang 1.0.0 的源码已经更新了，可以试试

**Comment by niuzhenjiang** [comment]
> @niuzhenjiang 1.0.0的源码已经更新了，可以试试
好的，感谢
