### ISSUE TITLE
from pyecharts import options as opt报错

### ISSUE THREAD

**Issue by hhy2589** [pyecharts/pyecharts#1008]
在3.6环境上报这个错，    from pyecharts import options as opts
ImportError: cannot import name 'options'

请问这个是什么原因，谢谢。

**Comment by Kewings** [comment]
options是1.0.0版本的功能，需要下载源码安装，记得切换到2019分支安装

**Comment by hhy2589** [comment]
> options是1.0.0版本的功能，需要下载源码安装，记得切换到2019分支安装

您好，这个源码也是在Pypi下载么？如果不是，有链接么。哈。多谢多谢

**Comment by Kewings** [comment]
首页的Readme没仔细阅读哈，在首页的基础上增加切换分支：
```
$ git clone https://github.com/pyecharts/pyecharts.git
$ cd pyecharts
$ git checkout -b 2019 origin/2019
$ pip install -r requirements.txt
$ python setup.py install
```

**Comment by sunhailin-Leo** [comment]
@hhy2589 @Kewings 现在不需要切换分支了
```bash
$ git clone https://github.com/pyecharts/pyecharts.git
$ cd pyecharts
$ pip install -r requirements.txt
$ python setup.py install
```

**Comment by hhy2589** [comment]
操作成功了，但是出现如下的问题。请问这个是什么问题，谢谢。

d:\PDP_data_analysis\pyecharts-2019>python3
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyecharts import options as opt
>>> exit()

d:\PDP_data_analysis\pyecharts-2019>cd ..

d:\PDP_data_analysis>python3 pdp_data_analysis.py
Traceback (most recent call last):
  File "pdp_data_analysis.py", line 5, in <module>
    from pyecharts import options as opts
ImportError: cannot import name 'options'

**Comment by hhy2589** [comment]
你好，按照说明安装上了但是出现如下面的问题，是否需要先卸载0.5.11版本再进行手动安装？谢谢。

d:\PDP_data_analysis\pyecharts-2019>python3
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyecharts import options as opt
>>> exit()

d:\PDP_data_analysis\pyecharts-2019>cd ..

d:\PDP_data_analysis>python3 pdp_data_analysis.py
Traceback (most recent call last):
  File "pdp_data_analysis.py", line 5, in <module>
    from pyecharts import options as opts
ImportError: cannot import name 'options'

**Comment by hhy2589** [comment]
> 你好，按照说明安装上了但是出现如下面的问题，是否需要先卸载0.5.11版本再进行手动安装？谢谢。
> 
> d:\PDP_data_analysis\pyecharts-2019>python3
> Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from pyecharts import options as opt
> > > > exit()
> 
> d:\PDP_data_analysis\pyecharts-2019>cd ..
> 
> d:\PDP_data_analysis>python3 pdp_data_analysis.py
> Traceback (most recent call last):
> File "pdp_data_analysis.py", line 5, in 
> from pyecharts import options as opts
> ImportError: cannot import name 'options'

就是通过命令行执行 from这句话没有问题，但是通过脚本执行的时候就报找不到。

**Comment by Kewings** [comment]
@hhy2589 
建议先把全部版本都卸载了，然后再重新安装1.0.0版本

如果是只保留了1.0.0版本，import应该是没问题的

**Comment by laozhongyi-0326** [comment]
options是1.0.0版本的功能，py2.7怎么用
![image](https://user-images.githubusercontent.com/34592750/68857030-d9a26a00-071c-11ea-877c-ce2299e02f95.png)怎么兼容

**Comment by sunhailin-Leo** [comment]
@laozhongyi-0326 v1.x 不兼容 Python 2.7 ，只兼容 Python 3.6 +
