### ISSUE TITLE
鼠标悬停在value上的标签可以添加更多内容吗

### ISSUE THREAD

**Issue by XuSirSir** [pyecharts/pyecharts#1009]
比如下图中的领带，添加标签显示更详细的自定义内容吗
![image](https://user-images.githubusercontent.com/37569230/56346495-c6fe9b80-61f4-11e9-8ee3-f7e381cea2b7.png)

**Comment by ly1102** [comment]
这个我之前做过，需要改js回调函数。在传入的时候，多传入一列信息，然后就用多出来的这一列信息做详细展示，现在pyecharts也有这个功能了。你可以去找一找我之前的issue或者是找一下echarts自定义显示数据的js代码，然后很容易就可以改出来了。
