### ISSUE TITLE
线下环境可以保存图片，线上环境不行，麻烦大神看看。

### ISSUE THREAD

**Issue by BoragoCode** [pyecharts/pyecharts#1010]
**问题**
服务器线下环境可以保存图片，线上不可以，报错说找不到pyecharts_environment。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.21.1

**代码及截图**
line 240, in raise_exception\n    \"No %s is found for %s\" % (self.plugin_name, key))\nException: No pyecharts_environment is found for png\n"}.

**Comment by chfw** [comment]
pip install pyecharts-snapshot

**Comment by chenjiandongx** [comment]
请问这个是什么意思

![image](https://user-images.githubusercontent.com/19553554/56783954-cb443d80-6820-11e9-916b-13cf34c677ee.png)

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！请使用新版的 snapshot-selenium 或者 snapshot-phantomjs 啦
