### ISSUE TITLE
1.0.0版本后续什么时候会实现render_embed?

### ISSUE THREAD

**Issue by Kewings** [pyecharts/pyecharts#1011]
0.5.11版本中是有该方法的
目前1.0.0版本中暂无

是否有计划？

我暂时使用重做template的方式，render给index.html以达成生成指定样式的html展示，除此之外，是否还有其他方式可以实现embed的展示呢？

谢谢。

**Comment by sunhailin-Leo** [comment]
@Kewings 发表一下个人意见哈～ only 个人意见 😄 
* 个人观点：在现在基本都是前后端分离的大环境下，还在用模版渲染的方式我觉得有点跟不上大环境的步伐了。
* 嘈点1、模版渲染在一定程度上占据了后端工程师开发时间
* 嘈点2、即使有前端工程师协助你进行模版开发，但是前端工程师还得关心你使用的模版引擎的语法。比方说 jinja2，如果用了 jinja2 的话，前端比方说用了 Vue 或者 Angular 框架，那么就得对 jinja2 的语法小心翼翼的进行处理。要么舍弃新技术用 jquery 要么就得去处理模版语法带来的兼容性问题。
     * 贴两个相关的地址：
     * Jinja2 With Angular: https://blog.csdn.net/dushu990/article/details/65631720 
     * Jinja2 With Vue.js: https://blog.csdn.net/uuihoo/article/details/80163860
* 嘈点3、模版渲染在团队开发中会拖慢整体进度，团队需要对模版的关系进行梳理。
* 嘈点4、模版渲染的项目，前端调试必须得依赖后端的服务启动，假设后端在设计一些复杂的逻辑需要长时间调试那么，前端会处于一种很尴尬的境地。虽然可以通过版本管理进行规避，但是始终不利于提升效率。
* 总结：
    * 1、如果你是个人开发，我觉得怎么顺手怎么来。（毕竟个人想法没发左右）
    * 2、如果是团队开发，尤其是初创团队的话，那么更加需要注重效率，因此前后端分离各自推各自的进度，会比项目进度依赖于模版的开发进度来的更高效。
    * 3、目前前端比较主流的 SAP模式 和 模块化开发模式下，前端需要一个专注的开发环境，因此模版渲染不利于前端团队的开发。

* 以上是我的个人观点，希望你能够理解一下～
* Ps： render_embed 的话，在 1.0.0 的版本中可能是没有计划的，如果不介意的话，你可以 clone 项目以后，根据 0.5.11 的方式，以及参考 1.0.0 的设计思想提交一份关于 render_embed 的 PR 给我们，Thx!

**Comment by Kewings** [comment]
@sunhailin-Leo 
谢谢您的解释。

我个人觉得各有利弊吧，模板渲染在于把控性更强些，我个人比较喜欢~哈哈

后续我来Try下0.5.11的render_embed往1.0.0合入的事

**Comment by lakdred** [comment]
This temporary patch may help you a little.  add render_embed back
Place this file in C:\Python37-32\Lib\site-packages\pyecharts\charts\base.py

这是一个临时修改文件，加了两个函数，本来想提PR的，想了想，算了，反正是临时的。
[base.zip](https://github.com/pyecharts/pyecharts/files/3116308/base.zip)

**Comment by chenjiandongx** [comment]
代码
![image_208](https://user-images.githubusercontent.com/19553554/56727992-6804cd80-6784-11e9-8cdb-c70ca752165c.png)
效果
![image](https://user-images.githubusercontent.com/19553554/56728005-6cc98180-6784-11e9-8b68-dfab0792d857.png)

**Comment by chenjiandongx** [comment]
https://pyecharts.org/#/zh-cn/web_flask

**Comment by shshjun** [comment]
终于有这个render_embed了。非常感谢。
报告一个bug:
当用init_opts=opts.InitOpts()指定标题或宽度时，它会同时默认js_host到https://assets.pyecharts.org/assets/
但我实际是使用本地的：
Flask(__name__, static_url_path = "", static_folder="templates")

**Comment by chfw** [comment]
再开一新的issue吧

**Comment by chenjiandongx** [comment]
@shshjun 你需要在顶部设置
```
 CurrentConfig.ONLINE_HOST  = "your_local_host" 
```

**Comment by Kewings** [comment]
多谢大佬，回去试试~
看来render_embed还是有受众的~哈哈
