### ISSUE TITLE
如何将pyecharts生成的图表导入类似gentelella的前端模板中

### ISSUE THREAD

**Issue by serchaofan** [pyecharts/pyecharts#1012]
**问题**
想请问一下，pyecharts如何与一些前端模板进行整合，类似gentelella，我在前端导入图表，并确定与gentelella的图表插入位置一致，但是无法显示，应该如何设置才能显示成功。

**运行环境（系统环境及 pyecharts 版本）**
python3.6，django2.2，pyecharts0.5.11

**代码及截图**
这是views.py的部分代码
```
def demo1(request):
    line1, line2 = getLine()
    context = dict(
        myechart1=line1.render_embed(),
        myechart2=line2.render_embed(),
    )
    return render(request, 'dashboard.html', context)
```
这是前端部分代码，插入位置与gentelella案例中图表插入的位置一致
```
  <div class="container">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Network Graph</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          {{ myechart1 }}
        </div>
      </div>
    </div>
  </div>
```
然后运行后查看网页源码能看到图表已经导入了，但是显示不了
![source-1](https://user-images.githubusercontent.com/32541818/56458084-c0b71d80-63b4-11e9-8e5c-d939f8b22909.png)
然后我将gentelella的代码复制到我的前端，能显示，但是pyecharts生成的就显示不了
![source-2](https://user-images.githubusercontent.com/32541818/56458105-fd831480-63b4-11e9-97d2-921968f6f4ef.png)
我这两天遇到这个问题后，试了很久还是没有解决，所以斗胆提一下issue。
非常感谢

**Comment by sunhailin-Leo** [comment]
@serchaofan 
* 你看一下你浏览器控制台有没报错的之类的，有的话也贴一下，谢谢 😄 

* Ps: 补一个我的吐槽链接 https://github.com/pyecharts/pyecharts/issues/1011#issuecomment-485628878

**Comment by serchaofan** [comment]
> @serchaofan
> 
> * 你看一下你浏览器控制台有没报错的之类的，有的话也贴一下，谢谢 smile
> * Ps: 补一个我的吐槽链接 [#1011 (comment)](https://github.com/pyecharts/pyecharts/issues/1011#issuecomment-485628878)

![深度截图_选择区域_20190423175014](https://user-images.githubusercontent.com/32541818/56571804-4c68be00-65f0-11e9-8610-c4a19d90d14f.png)
还真的出错了，以前没有查看过这个，那这是什么错呢

**Comment by sunhailin-Leo** [comment]
@serchaofan 你的模版有引入 echarts 的 js 包嘛？

**Comment by serchaofan** [comment]
@sunhailin-Leo
引入了。
![深度截图_选择区域_20190423175517](https://user-images.githubusercontent.com/32541818/56572114-fb0cfe80-65f0-11e9-9456-47208acf7a7b.png)

**Comment by sunhailin-Leo** [comment]
@serchaofan 你再看一下 控制台 Network 有没加载到这个 js 文件

**Comment by serchaofan** [comment]
> @serchaofan 你再看一下 控制台 Network 有没加载到这个 js 文件

@sunhailin-Leo 
加载了
![深度截图_选择区域_20190423180048](https://user-images.githubusercontent.com/32541818/56572517-ccdbee80-65f1-11e9-92f3-55918c58782f.png)

**Comment by serchaofan** [comment]
@sunhailin-Leo 
我又用chrome检查了一下，发现这个地方有波浪线，不清楚是不是错误
![深度截图_选择区域_20190423201055](https://user-images.githubusercontent.com/32541818/56580037-3c5ad980-6604-11e9-887a-d5f4660088f8.png)
我刚还以为是不是版本的错误，试过了echarts3，我还下了所有echarts的主题，还是不行

**Comment by serchaofan** [comment]
已解决。
原因在于没有把echarts的js文件在网页开头引入，必须要把js引入放在插入图表的上方，要在html的最开始引入。
![深度截图_选择区域_20190423223327](https://user-images.githubusercontent.com/32541818/56589453-d8421080-6617-11e9-8c67-06b54d529d43.png)

特别感谢@sunhailin-Leo的帮助
