### ISSUE TITLE
在flask中调用pyecharts模块导致flask无法输出日志

### ISSUE THREAD

**Issue by paopjian** [pyecharts/pyecharts#1013]
**问题**
使用pycharm新建flask项目,import pyecharts, 运行时终端不出现running on 127.0.0.1:5000
**运行环境（系统环境及 pyecharts 版本）**
pycharm
pyecharts 0.5.11

**代码及截图**
from flask import Flask
import pyecharts
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello World!'

if __name__ == '__main__':
    app.run()
![TIM截图20190422143410](https://user-images.githubusercontent.com/20377352/56487391-a2186a00-650d-11e9-8f43-2636bcc4aa60.png)

**Comment by sunhailin-Leo** [comment]
@paopjian 
* 测试环境:
   * Windows 10 专业版 x64
   * Python 版本: Python 3.5.2

* 问题反馈
    * 我自己在 Mac 下的 Windows 虚拟机里面测试没有任何问题。

* 默认模式:
![image](https://user-images.githubusercontent.com/17564655/56569385-7370c100-65eb-11e9-95f0-845227b51bed.png)

* Debug 模式:
![image](https://user-images.githubusercontent.com/17564655/56569478-a1560580-65eb-11e9-8a15-35c40744e990.png)
