### ISSUE TITLE
如何绘制一个有区县边界的省级地图（现状绘省级地图默认显示到了市的边界）

### ISSUE THREAD

**Issue by smallkoko** [pyecharts/pyecharts#1014]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
Please perfect your issue, thx.

**Comment by sunhailin-Leo** [comment]
@smallkoko 
* You can try it.
* https://github.com/echarts-maps/echarts-china-cities-js
* https://echarts-maps.github.io/echarts-geomapping-book-zh/
