### ISSUE TITLE
city_coordinates.json 广州没有白云区

### ISSUE THREAD

**Issue by kiverc** [pyecharts/pyecharts#1017]
如图 没有白云区 与贵州的白云区重叠 这种情况下能否优化?

**Comment by sunhailin-Leo** [comment]
@kiverc 这个情况和 json 的设计有关系，现阶段的话，你可以自己定义你所需要使用的 `json` 到在你画 `Geo` 图的时候  😄

**Comment by kiverc** [comment]
> @kiverc 这个情况和 json 的设计有关系，现阶段的话，你可以自己定义你所需要使用的 `json` 到在你画 `Geo` 图的时候 😄

好的 我看到有添加的入口了，另外想问下如果我调用geo图，怎么传入参数改page_title呢

**Comment by sunhailin-Leo** [comment]
@kiverc 
```python
import pyecharts.options as opts
from pyecharts.charts import Geo

Geo()
....
.set_global_opts(title_opts=opts.TitleOpts(title="你的标题"))

```

**Comment by kiverc** [comment]
> @kiverc
> 
> ```python
> import pyecharts.options as opts
> from pyecharts.charts import Geo
> 
> Geo()
> ....
> .set_global_opts(title_opts=opts.TitleOpts(title="你的标题"))
> ```
解决了 方法名写错了init一直没用  ，想改的是page的title哈哈哈  谢谢
Geo(init_opts=opts.InitOpts(width = "900px",height = "450px",page_title = "人群流向图"))

**Comment by sunhailin-Leo** [comment]
@kiverc  Ok 👌

**Comment by kiverc** [comment]
> @kiverc Ok 👌

刚还发现个疑问 ，我调用了广州的地图，修改了行政区的经纬度  但是每个经纬度的行政区label位置好像是固定的？这个能调节位置吗？
