### ISSUE TITLE
pyecharts anaconda3.7不支持吗

### ISSUE THREAD

**Issue by ZhaoJackie** [pyecharts/pyecharts#1018]
**问题**
使用pyecharts测试画图的时候显示No pyecharts_environment is found for png
是python的版本3.7不支持了吗，安装了phantomjs，添加了环境变量能正常在命令行使用。
其他电脑anaconda2.7的能够运行，怀疑是python3.7不支持？

**运行环境（系统环境及 pyecharts 版本）**
windows 平台Anaconda3.7，最新的pyecharts，pip install pyecharts安装的

**代码及截图**
from pyecharts import Funnel

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
value = [20, 40, 60, 80, 100, 120]
funnel = Funnel("漏斗图示例")
funnel.add("商品", attr, value, is_label_show=True,
           label_pos="inside", label_text_color="#fff")
funnel.render(path='01.png')

![test](https://user-images.githubusercontent.com/42666454/56562233-8ed3d000-65db-11e9-9a35-3fc5d8f95e03.png)

**Comment by sunhailin-Leo** [comment]
@ZhaoJackie 请移步看看 0.5 版本的文档

**Comment by ZhaoJackie** [comment]
@sunhailin-Leo 看了0.5版本的文档，nodejs环境和pyecharts_snapshotdou 都安装成功了，不加参数能够生成html文件，但是换成png其他格式的还是一样报错。

**Comment by sunhailin-Leo** [comment]
@ZhaoJackie 

* 请认真详细阅读文档
* 传送门: https://05x-docs.pyecharts.org/#/zh-cn/jupyter_notebook?id=%E7%A6%BB%E7%BA%BF%E6%98%BE%E7%A4%BA-html-%E4%B8%AD%E7%9A%84%E5%9B%BE%E7%89%87
