### ISSUE TITLE
修改了city_coordinates下面行政区坐标  label位置不会变动？

### ISSUE THREAD

**Issue by kiverc** [pyecharts/pyecharts#1019]
**问题**
手动更新了city_coordinates下面广州的行政区坐标，标签位置好像不会动，请问下这个是有哪里可以调的吗？

**运行环境（系统环境及 pyecharts 版本）**
python3.7  pyecharts1.0

**代码及截图**
.add_schema(maptype="广州",
    	itemstyle_opts=opts.ItemStyleOpts(color="#FDF5E6", border_color="#F08080"),label_opts=opts.LabelOpts(is_show=True))
    .add(
        "",
        [("黄埔区", 20), ("越秀区", 20), ("荔湾区", 20), ("番禺区", 20), ("白云区", 20),],
        type_=ChartType.EFFECT_SCATTER,
        color="red",
        is_selected=False
    )
<img width="465" alt="图片1" src="https://user-images.githubusercontent.com/42595176/56568408-7ff41a00-65e9-11e9-9644-b0007c4b9587.png">

**Comment by sunhailin-Leo** [comment]
@kiverc 代码尽量用代码块引用起来，并且贴上相对完整的代码。

**Comment by kiverc** [comment]
`from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.globals import ChartType, SymbolType
c = (
    Geo(init_opts=opts.InitOpts(width = "900px",height = "450px",page_title = "广州人群流向图"))
    .add_schema(maptype="广州",
    	itemstyle_opts=opts.ItemStyleOpts(color="#FDF5E6", border_color="#F08080"),label_opts=opts.LabelOpts(is_show=True))
    .add(
        "",
        [("黄埔区", 20), ("越秀区", 20), ("荔湾区", 20), ("番禺区", 20), ("白云区", 20),],
        type_=ChartType.EFFECT_SCATTER,
        color="red",
        is_selected=False
    )

    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(title_opts=opts.TitleOpts(title="广州市长租公寓人群",subtitle='周末出行偏好路线'))
)
c.render()`
code如上  我修改了city_coordinates下面广州的行政区坐标，行政区的名称位置好像跟里面的坐标不一致  修改不了位置🤣

**Comment by sunhailin-Leo** [comment]
* 阅读源码
![image](https://user-images.githubusercontent.com/17564655/56570429-86849080-65ed-11e9-9fa6-a10c22ca32f3.png)

**Comment by sunhailin-Leo** [comment]
@kiverc 可以参照项目自带的 json 格式进行自定义 😄

**Comment by kiverc** [comment]
> @kiverc 可以参照项目自带的 json 格式进行自定义 😄
我手动改的效果应该跟这个一样的？
我看了下生成的html引用的是https://assets.pyecharts.org/assets/maps/guang3_dong1_guang3_zhou1.js，所以每个行政区的名字还是按照地图包里面来的吗

**Comment by retornado** [comment]
同问题，如果改了文件里的坐标，地图里的位置还是不变，那这个不变的坐标是哪儿来的？
