### ISSUE TITLE
求一个overlap使用多个坐标的样例

### ISSUE THREAD

**Issue by raymondby** [pyecharts/pyecharts#1020]
主页说明文档感觉缺很多内容，比如我在set_global_opts的时候，想添加AxisOpts，我照着title_opts=opts.TitleOpts依样画葫芦用了axis_opts=opts.AxisOpts，可是结果是set_global_opts() got an unexpected keyword argument 'axis_opts'

**Comment by sunhailin-Leo** [comment]
@raymondby 能在 Echarts 官网的 gallery 找个 demo 给我嘛？

**Comment by raymondby** [comment]
> 
> 
> @raymondby 能在 Echarts 官网的 gallery 找个 demo 给我嘛？

这是什么神奇的要求？

**Comment by chenjiandongx** [comment]
https://github.com/pyecharts/pyecharts/blob/2019/example/overlap_example.py 可以参考这个

**Comment by chenjiandongx** [comment]
@raymondby 双 Y 轴
![image](https://user-images.githubusercontent.com/19553554/56571639-f431bc00-65ef-11e9-831d-40d196dcccc8.png)

**Comment by raymondby** [comment]
感谢！刚看了，原来是yaxis_opt，faint...我怎么就没想到呢，呵呵...
