### ISSUE TITLE
GEO应用----迁徙图中箭头拖尾效果无法去除

### ISSUE THREAD

**Issue by kiverc** [pyecharts/pyecharts#1021]
**问题**
在echarts应用中
"type": "lines",
            "name": "\u8d8a\u79c0\u533a",
            "zlevel": 4,
            "effect": {
                "show": true,
                "brushType": "stroke",
                "scale": 2.5,
                "period": 2,
                "color": "red",
                "symbol": "arrow",
                "symbolSize": 6,
                **"trailLength": 0**
            },
有trailLength参数调整拖尾的长度 ，但是目前pyecharts中没有这个这个调整的参数

**运行环境（系统环境及 pyecharts 版本）**
python3.7 pyecharts1.0

**代码及截图**

`    .add(
        "番禺区",
        [("番禺区", "天河区"), 
        ],
        type_=ChartType.LINES,
        effect_opts=opts.EffectOpts(
            symbol=SymbolType.ARROW, symbol_size=6, color="red",period=2#"trailLength": 0   //生成html后添加，去拖尾
        ),
        linestyle_opts=opts.LineStyleOpts(curve=0.2,color ='#F4A460',#线颜色
                                          type_='dotted'),symbol_size=0,color ='#B22222',#点颜色
        label_opts=opts.LabelOpts(is_show=False)
    )`

**pyecharts效果：**
![image](https://user-images.githubusercontent.com/42595176/56651307-59061880-66bb-11e9-81f6-d88639317a22.png)
**echarts设置trailLength后效果：**
![image](https://user-images.githubusercontent.com/42595176/56651420-923e8880-66bb-11e9-81f4-c6e3daa15d57.png)

**Comment by sunhailin-Leo** [comment]
@kiverc 后续会修改 😄

**Comment by kiverc** [comment]
> @kiverc 后续会修改 😄

mark😬

**Comment by sunhailin-Leo** [comment]
@kiverc 目前 dev 已经更新这个问题，你可以用 dev 分支的代码进行测试～

**Comment by sunhailin-Leo** [comment]
```shell
$ git clone https://github.com/pyecharts/pyecharts.git -b dev
$ cd pyecharts
$ python install.py
```

**Comment by sunhailin-Leo** [comment]
@
