### ISSUE TITLE
V1.0的pyecharts如何实现双y轴

### ISSUE THREAD

**Issue by weichen1018** [pyecharts/pyecharts#1025]
我最近在学习可视化数据pyecharts，目前我要实现一个直角坐标系的层叠多图，想实现双y轴，但是我在1.0的文档中并没有找到如何实现，只看到了0.5x版本的pyecharts实现双y轴,在一些技术网站上也找不到pyecharts==V1.0实现双y轴的相关的答案，，这个问题让我这两天非常纠结。希望您在百忙之中，看下我的问题，如果您能给我做出一些指导，那就太好了！
      下面是我写的代码：
![image](https://user-images.githubusercontent.com/38155568/56789748-40217280-6835-11e9-801e-107cfbd8f525.png)

**Comment by sunhailin-Leo** [comment]
@weichen1018 https://github.com/pyecharts/pyecharts-gallery/blob/master/Line/rainfall.py

**Comment by sunhailin-Leo** [comment]
@weichen1018 我这边有同步一些 Echarts 官方的图例

**Comment by weichen1018** [comment]
很高兴收到您的回复！看了您给我发的这个链接https://github.com/pyecharts/pyecharts-gallery/blob/master/Line/rainfall.py ，但是我看的不是很明白，因为里面有很多的参数，看的有点懵。
下面是要做成的效果图和我做的图：
![image](https://user-images.githubusercontent.com/38155568/56796101-6e5a7e80-6844-11e9-8e62-ff77bb3579cf.png)
![image](https://user-images.githubusercontent.com/38155568/56796118-74e8f600-6844-11e9-8471-ed2eb8766e5d.png)
这是我的代码：
def bar_base() -> Bar:
    x = list1
    y = list2
    z = list3
    bar = (
        Bar(init_opts=opts.InitOpts(theme=ThemeType.CHALK))
            .add_xaxis(x)
            .add_yaxis('出院收入', y)
            .set_global_opts(title_opts=opts.TitleOpts(title="单病种出院收入"),
                             datazoom_opts=[opts.DataZoomOpts()],
                             toolbox_opts=opts.ToolboxOpts(),
                             yaxis_opts=opts.AxisOpts(name="收入(万元)", name_location="center", name_gap=50)
            )
    )
    line = (
        Line(init_opts=opts.InitOpts(theme=ThemeType.MACARONS))
            .add_xaxis(x)
            # .add_yaxis("同比增长率", y)
            .add_yaxis(series_name="环比增长率",
                       y_axis=z,
                       # yaxis_index=1,
                       )
            .extend_axis(
                yaxis=opts.AxisOpts(
                    name="同环比",
                    name_location="start",
                    type_="value",
                    max_=1500,
                    is_inverse=True,
                    axislabel_opts=opts.AxisTickOpts(is_show=True),
                    splitline_opts=opts.SplitLineOpts(is_show=True),
                )
            )
            .set_global_opts()
    )
    bar.overlap(line)
    return bar

要怎么改，才能达到效果图那样有两个y轴

**Comment by chenjiandongx** [comment]
https://pyecharts.org/#/zh-cn/rectangular_charts?id=overlap%EF%BC%9A%E5%B1%82%E5%8F%A0%E5%A4%9A%E5%9B%BE

**Comment by weichen1018** [comment]
看到了   非常感谢   之前可能我眼瞎了

**Comment by chenjiandongx** [comment]
@weichen1018 我下午刚补的 放心 你眼睛没有问题

**Comment by qlsun** [comment]
请问 K线图支持双坐标轴吗？两个不同的指数叠加
