### ISSUE TITLE
1.0版本的居中属性是哪个？热点图的数据是list类型吗？

### ISSUE THREAD

**Issue by edbea** [pyecharts/pyecharts#1026]
1.0版本的居中属性是哪个？热点图的数据是list类型吗？

**Comment by edbea** [comment]
1另外，怎么回退到0.5版本？？网上很多例子都是基于0.5版本的

**Comment by sunhailin-Leo** [comment]
@edbea 回退的卸载就好了，重新装

**Comment by sunhailin-Leo** [comment]
@edbea 居中的话你指的的是什么？
* 你可以参考下我的复刻的例子 https://github.com/pyecharts/pyecharts-gallery/blob/master/Heatmap/heatmap_on_cartesian.py
* 数据类型基本都是 list
