### ISSUE TITLE
如何在地图上画柱状图

### ISSUE THREAD

**Issue by jameslahm** [pyecharts/pyecharts#1028]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by jameslahm** [comment]
map可以画区域性地图，geo可以画点状或线型地图，请问一下有什么办法可以在地图上画柱状图来表示当前地点的对应值呢

**Comment by sunhailin-Leo** [comment]
@jameslahm 你这个问题很有意思 😄 
* 我在 Echarts 官方的 Gallery 里头见到过，但是以现阶段的 pyecharts 暂时难以实现如此骚的操作～ 
* Ps：如果你看到并看完那个 Gallery 以后，结合 pyecharts 的源码，你可以考虑提供一下你的 PR 和 test 😄
