### ISSUE TITLE
如何显示line的横纵坐标名称

### ISSUE THREAD

**Issue by xiegegege** [pyecharts/pyecharts#1032]
**问题**
请问怎么配置LINE横纵坐标的标签名称，比如横轴表示‘时间’，纵轴表示‘降雨量’，怎么显示在图形上

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@xiegegege 说明一下你的版本，以及你现在的代码

**Comment by xiegegege** [comment]
我现在的版本是1.0.0 ,现在代码是：
line = (
                Line()
                .add_xaxis(step1)
                .add_yaxis("Loss1", loss1)
                .add_yaxis("Loss2", loss2)
                .set_global_opts(title_opts=opts.TitleOpts(title=args.name))
                )
line.render(path=args.name+'.html')

**Comment by sunhailin-Leo** [comment]
@xiegegege 
* 可以参考下我的 gallery ： https://github.com/pyecharts/pyecharts-gallery/blob/master/Line/rainfall.py
* 实际上的配置是 `opts.AxisOpts` 的 `name` 参数

**Comment by vincent1rookie** [comment]
opts.AxisOpts 中 如何指定name的字体大小，即如何设定坐标轴的名称字体大小？

**Comment by wangqlpython** [comment]
ctrl+b进去看





---原始邮件---
发件人: "vincent1rookie"<notifications@github.com&gt;
发送时间: 2020年2月20日(周四) 晚上8:34
收件人: "pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [pyecharts/pyecharts] 如何显示line的横纵坐标名称 (#1032)



opts.AxisOpts 中 如何指定name的字体大小，即如何设定坐标轴的名称字体大小？
