### ISSUE TITLE
pyecharts_environment

### ISSUE THREAD

**Issue by BoragoCode** [pyecharts/pyecharts#1034]
**问题**
I want to change the color of gauge，how can i do？
我想改变Gauge的颜色，请问我应该怎么做啊？项目急用这个能力。

**运行环境（系统环境及 pyecharts 版本）**
python 3.6
pyecharts 1.0

**代码及截图**
![image](https://user-images.githubusercontent.com/19904582/56874174-c8d52400-6a6a-11e9-9a20-f49b8d7d2df2.png)

**Comment by sunhailin-Leo** [comment]
@BoragoCode 给你个 Echarts 官方的示例，你去修改一下生成的 html 或者 json

* [传送门](https://gallery.echartsjs.com/editor.html?c=xH1vxib94f)

**Comment by sunhailin-Leo** [comment]
@BoragoCode 
* 你可以尝试在代码那里往 axisLine 的 linestyle 的 color 属性传入一个像我给你的官方 Gallery 的数组。

**Comment by sunhailin-Leo** [comment]
@BoragoCode 
![image](https://user-images.githubusercontent.com/17564655/56874419-55ccad00-6a6c-11e9-8039-1c9de84ba860.png)
* 暂时忍耐一下编译器的 type hints 的报错提示.
```python
#!/usr/bin/env python
# coding=utf-8
from __future__ import unicode_literals

import pyecharts.options as opts
from pyecharts.charts import Gauge

(
    Gauge(init_opts=opts.InitOpts(width="1600px", height="800px"))
    .add(series_name="业务指标", data_pair=[["完成率", 55.5]])
    .set_global_opts(
        legend_opts=opts.LegendOpts(is_show=False),
        tooltip_opts=opts.TooltipOpts(is_show=True, formatter="{a} <br/>{b} : {c}%"),
    )
    .set_series_opts(
        axisline_opts=opts.AxisLineOpts(
            linestyle_opts=opts.LineStyleOpts(
                color=[
                    [0.3, '#67e0e3'],
                    [0.7, '#37a2da'],
                    [1, '#fd666d']
                ],
                width=30
            )
        )
    )
    .render("gauge_1.html")
)
```
* 最终结果
![image](https://user-images.githubusercontent.com/17564655/56874453-8dd3f000-6a6c-11e9-8e1a-b50349fd970f.png)
