### ISSUE TITLE
Geo中地图上圆点上方数值能否显示一些自定义的数值

### ISSUE THREAD

**Issue by wangzw19** [pyecharts/pyecharts#1039]
label_formatter按照回调函数写总是只能显示value值，name值等，为什么不能显示针对每个城市的自定义的一些介绍，很是困扰

from pyecharts import Geo, Style
import pandas as pd

# 导入excel表举例
df = pd.read_excel('D:\工作文件\情报体系建立\数据汇总\仓储数据\\01.xlsx'）
# 导入自定义的地点经纬度
geo_cities_coords = {df.iloc[i]['市']: [df.iloc[i]['经度'], df.iloc[i]['纬度']]
                     for i in range(len(df))}  # 根据文件大小生成字典
attr = list(df['市'])  # 字典的每个键值
value = list(df['mean'])  # 散点的颜色就是和这个相关的
shichang = list(df['介绍']) #  我想在标签里显示这个值

style = Style(title_color="#fff", title_pos="left",
              width=1500, height=600, background_color="#404a59")
def geo_formatter(params):
    return params.name + ' : ' + params.value[2]
def label_formatter(params):
    return params.name + ' : ' + params.value[2]
# 可视化
geo = Geo('全国主要城市仓储价格行情', **style.init_style)
geo.add("高台库", attr, value, visual_range=[15, 45], symbol_size=4,
        type="effectScatter",effect_scale=5,
        visual_text_color="#fff",
        tooltip_formatter=geo_formatter,
        label_formatter=label_formatter,
        is_visualmap=True,
        maptype='china',
        visual_split_number=3,
        geo_cities_coords=geo_cities_coords)
geo.render('全国主要城市仓储价格行情.html')

**Comment by lleeoov** [comment]
发现类似的问题，是不是现在只能用JS写回调函数？

**Comment by sunhailin-Leo** [comment]
@wangzw19 
* 自定义显示的话基本上都需要写一个 js 去实现。
* 现阶段 1.0.0 版本在 formatter 部分支持写入 js 语句，也欢迎使用 1.0.0。
