### ISSUE TITLE
Geo地图中不同系列，同一城市，标签提示框内容覆盖问题

### ISSUE THREAD

**Issue by wangzw19** [pyecharts/pyecharts#1040]
我想建立一个每个城市的高标库和平库的介绍，但是根据下面的代码，同时显示的时候，最后平库的tooltip_formatter把高标库的tooltip_formatter覆盖了，求怎么解决这个问题

from pyecharts import Geo, Style
import pandas as pd

# 导入excel表举例
df = pd.read_excel('D:\工作文件\情报体系建立\数据汇总\仓储数据\\01.xlsx')
cf = pd.read_excel('D:\工作文件\情报体系建立\数据汇总\仓储数据\\02.xlsx')
print(df.head(5))

# 导入自定义的地点经纬度
geo_cities_coords = {df.iloc[i]['市']: [df.iloc[i]['经度'], df.iloc[i]['纬度']]
                     for i in range(len(df))}  # 根据文件大小生成字典
attr = list(df['市'])  # 字典的每个键值
value = list(map(int,cf['mean']))  # 把列表内容转化为整数
shichang = list(df['市场价'])
style = Style(title_color="#fff", title_pos="left",
              width=1500, height=600, background_color="#404a59")
def geo_formatter(params):
    return params.seriesName+' : '+"<br>"+params.name + ' : ' + params.value[2]
    # return params.name + ' : ' + params.value[2]<br>
def label_formatter(params):
    return params.name + ' : ' + params.value[2]
# 可视化
geo = Geo('全国主要城市仓储价格行情', **style.init_style)

geo.add("高台库", attr, value, visual_range=[15, 45], symbol_size=4,
        type="effectScatter",effect_scale=5,
        visual_text_color="#fff",
        tooltip_formatter=geo_formatter,
        label_formatter=label_formatter,
        is_visualmap=True,
        maptype='china',
        visual_split_number=3,
        geo_cities_coords=geo_cities_coords)
geo_cities_coords = {cf.iloc[i]['市']: [cf.iloc[i]['经度'], cf.iloc[i]['纬度']]
                     for i in range(len(cf))}  # 根据文件大小生成字典
attr = list(cf['市'])  # 字典的每个键值
value = list(map(int,cf['mean']))  # 把列表内容转化为整数
print(value)
def geo_formatter(params):
    return params.seriesName+' : '+"<br>"+params.name + ' : ' + params.value[2]
    # return params.name + ' : ' + params.value[2]<br>
def label_formatter(params):
    return params.name + ' : ' + params.value[2]
geo.add("平库", attr, value, visual_range=[15, 45], symbol_size=4,
        type="effectScatter",effect_scale=5,
        visual_text_color="#fff",
        tooltip_formatter=geo_formatter,
        label_formatter=label_formatter,
        is_visualmap=True,
        maptype='china',
        visual_split_number=3,
        geo_cities_coords=geo_cities_coords)
geo.render('全国主要城市仓储价格行情.html')

**Comment by sunhailin-Leo** [comment]
@wangzw19 覆盖的情况能否截个图?

**Comment by wangzw19** [comment]
截图如下，高标库和平库同时显示时，点击城市只显示平库，不显示高台库

**Comment by wangzw19** [comment]
截图如附件

**Comment by wangzw19** [comment]
不知道怎么放置截图，就是这段代码中，平库的系列和高台库的 很多经纬度城市本身是重合的，导致一起显示的时候只显示平库不显示高台库
