### ISSUE TITLE
1.0版本  x轴上的分类名显示不全

### ISSUE THREAD

**Issue by weichen1018** [pyecharts/pyecharts#1041]
直角坐标系图表，x轴上的分类名过长，我想倾斜显示，但是我在1.0的文档中没找到，求解。
![image](https://user-images.githubusercontent.com/38155568/56950379-eb009c00-6b67-11e9-915d-a539ff75ca49.png)
下面这个是想要现实的效果图：
![image](https://user-images.githubusercontent.com/38155568/56950389-f5229a80-6b67-11e9-93d5-2503180ebc7c.png)

**Comment by sunhailin-Leo** [comment]
@weichen1018 
[传送门](https://pyecharts.org/#/zh-cn/series_options?id=labelopts%EF%BC%9A%E6%A0%87%E7%AD%BE%E9%85%8D%E7%BD%AE%E9%A1%B9)

**Comment by chenjiandongx** [comment]
@weichen1018 

> Bar-旋转 X 轴标签

```python
def bar_rorate_xaxis_label() -> Bar:
    c = (
        Bar()
        .add_xaxis(
            [
                "名字很长的X轴标签1",
                "名字很长的X轴标签2",
                "名字很长的X轴标签3",
                "名字很长的X轴标签4",
                "名字很长的X轴标签5",
                "名字很长的X轴标签6",
            ]
        )
        .add_yaxis("商家A", [10, 20, 30, 40, 50, 40])
        .add_yaxis("商家B", [20, 10, 40, 30, 40, 50])
        .set_global_opts(
            xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=-15)),
            title_opts=opts.TitleOpts(title="Bar-旋转X轴标签", subtitle="解决标签名字过长的问题"),
        )
    )
    return c
```
![](https://user-images.githubusercontent.com/19553554/56972171-16ea4480-6b9d-11e9-834c-b8eb4357808c.png)

**Comment by weichen1018** [comment]
已收到，非常感谢。
