### ISSUE TITLE
table.render()出现错误, 但是直接render_notebook()运行良好

### ISSUE THREAD

**Issue by wuzhe1234** [pyecharts/pyecharts#1044]
**问题**
table.render()出现错误, 但是直接render_notebook()运行良好

**运行环境（系统环境及 pyecharts 版本）**
win10
python 3.7.3
jupyter notebook
pyecharts 1.0.0

**代码及截图**

from pyecharts.components import Table

table = Table()

headers = ["City name", "Area", "Population", "Annual Rainfall"]
rows = [
    ["Brisbane", 5905, 1857594, 1146.4],
    ["Adelaide", 1295, 1158259, 600.5],
    ["Darwin", 112, 120900, 1714.7],
    ["Hobart", 1357, 205556, 619.5],
    ["Sydney", 2058, 4336374, 1214.8],
    ["Melbourne", 1566, 3806092, 646.9],
    ["Perth", 5386, 1554769, 869.4],
]
table.add(headers, rows)
table.render()

AttributeError                            Traceback (most recent call last)
<ipython-input-11-d69d8ad8d196> in <module>
     14 ]
     15 table.add(headers, rows)
---> 16 table.render()
     17 

~\Miniconda3\envs\full_anaconda\lib\site-packages\pyecharts\components\table.py in render(self, path, template_name, env)
     43     ) -> str:
     44         RenderEngine(env).render_chart_to_file(
---> 45             chart=self, path=path, template_name=template_name
     46         )
     47         return os.path.abspath(path)

~\Miniconda3\envs\full_anaconda\lib\site-packages\pyecharts\render\engine.py in render_chart_to_file(self, template_name, chart, path)
     43         """
     44         tpl = self.env.get_template(template_name)
---> 45         html = tpl.render(chart=self.generate_js_link(chart))
     46         write_utf8_html_file(path, self._reg_replace(html))
     47 

~\Miniconda3\envs\full_anaconda\lib\site-packages\pyecharts\render\engine.py in generate_js_link(chart)
     20             chart.js_host = CurrentConfig.ONLINE_HOST
     21         links = []
---> 22         for dep in chart.js_dependencies.items:
     23             # TODO: if?
     24             if dep in FILENAMES:

AttributeError: 'Table' object has no attribute 'js_dependencies'

**Comment by pinckCat** [comment]
出现了同样的问题，希望的到解决
