### ISSUE TITLE
在timeline 中使用 geo时，颜色被改变

### ISSUE THREAD

**Issue by oukasinn** [pyecharts/pyecharts#1045]
**问题**
geo中修改了color，但将geo添加到timeline时，color都被回复成默认色了。
请问在timeline中怎样指定颜色？（怎样保持在geo中设定的颜色不被改变？）

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@oukasinn 如果可以的话，能贴一个 example 嘛？ 😄

**Comment by sunhailin-Leo** [comment]
@oukasinn 这个问题，我今天试了一下，的确会出现这个问题，我们会在后续版本进行修复～ 😄

**Comment by sunhailin-Leo** [comment]
@oukasinn 你可以再新版本中再尝试一次 😄
