### ISSUE TITLE
Geo 中没有itemstyle 参数

### ISSUE THREAD

**Issue by oukasinn** [pyecharts/pyecharts#1046]
**问题**
1.0 版本的文档中写geo有itemstyle参数，而实际 Geo 中没有。

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@oukasinn 
* Echarts 官方文档里面有：https://www.echartsjs.com/option.html#geo.itemStyle
* Pyecharts 源码也有：
![image](https://user-images.githubusercontent.com/17564655/57021231-2f6e6380-6c5e-11e9-930e-738822df4569.png)
