### ISSUE TITLE
title 和 subtitle 换行

### ISSUE THREAD

**Issue by shshjun** [pyecharts/pyecharts#1048]
**问题**
title 和 subtitle 换行, 用\n 或 <br/>都无效
（注：之前.5x版本\n是可以的）

**运行环境（系统环境及 pyecharts 版本）**
win10+py3.7.3 pyecharts1.0 

**代码及截图**
title_opts=opts.TitleOpts(title="my\n<br/>title", subtitle = "my\n<br/>subtitle", pos_left='5%', pos_top='10%')
![image](https://user-images.githubusercontent.com/816453/57080463-27c5c200-6d25-11e9-8c5d-0b9f90fedc8b.png)

**Comment by shshjun** [comment]
title="my\n < b r / >title"
< b r / >在上面被吃掉了。不过截图可以看到。

**Comment by chenjiandongx** [comment]
换行符无效这个是我的问题 在 1.1.0 版本中已经被修复

如果着急使用的话可以 clone dev 分支进行源码安装

**Comment by chenjiandongx** [comment]
#1113
