### ISSUE TITLE
有下划线时，class 和 dicts 有区别

### ISSUE THREAD

**Issue by shshjun** [pyecharts/pyecharts#1050]
**问题**
有下划线时，class 和 dicts 有区别

**运行环境（系统环境及 pyecharts 版本）**

win10+py3.7+pe1.0

**代码及截图**
ex1: 
label_opts={"is_show":True} # 设置is_show不工作
vs
label_opts=opts.LabelOpts(is_show=True)

ex2:
linestyle_opts={"width":3,"opacity":0.3,"type_":"dotted"} # 设置type_不工作
vs
linestyle_opts=opts.LineStyleOpts(width=3,opacity=0.3,type_="dotted")

**Comment by shshjun** [comment]
注意到以下splitline_opts 用的dict却又是工作的。
xaxis_opts=opts.AxisOpts(type_="value", splitline_opts={"is_show":True})

**Comment by sunhailin-Leo** [comment]
@shshjun 你这种情况是在画什么图才会出现的？

**Comment by shshjun** [comment]
目前我只用了line() 和 scatter()。数据xtype="value"。最后由flask 输出。


line0 =  (Line(init_opts=opts.InitOpts(
				 page_title='my test _'
				, width="%dpx"%(1800)
				, height="%dpx"%(900)
				, bg_color = bg_color
				, js_host="/"
				)
			  )
		  )

line0.add_xaxis(dtlist).add_yaxis(None
				  ,datalist #以下为对比：
				  ,label_opts={"is_show":True,"color":'blue',"position":"left"}
				  #,label_opts=opts.LabelOpts(is_show=True,color='blue',position="left")
				  ,linestyle_opts={"width":3.0,"opacity":0.3,"type_":linetype,"color":linecolor}
				  #,linestyle_opts=opts.LineStyleOpts(width=3.0,opacity=0.3,type_=linetype,color=linecolor)
				  )
line0.set_global_opts(
		title_opts=opts.TitleOpts(title=pe_title, subtitle = pe_subtitle, pos_left='5%', pos_top='10%'
			, title_textstyle_opts=opts.TextStyleOpts(color="black",font_size=12)
			, subtitle_textstyle_opts=opts.TextStyleOpts(color="black",font_size=12)
			)
		,xaxis_opts=opts.AxisOpts(type_="value", max_=xmax, min_=xmin,interval=240,splitline_opts={"is_show":True})
		,yaxis_opts=opts.AxisOpts(max_=ymax, min_=ymin,splitline_opts={"is_show":True})
		,datazoom_opts=[opts.DataZoomOpts(range_start=initialzoom,range_end=100)]
		,toolbox_opts=opts.ToolboxOpts(is_show=False)
		)
es=scatter()
# some scatter code
line0.overlap(es)
return Markup(line0.render_embed( ))

**Comment by sunhailin-Leo** [comment]
@shshjun 主要情况就是设置 `class` 的时候可以生效，然后设置为 `dict` 不生效？

**Comment by shshjun** [comment]
同时我问下：之前在legends上鼠标放在某个系列的图例上时，该系列会突出，并_同时_显示label文字。
现在V1.0只突出系列，但_不_显示label文字。请问有办法显示label文字吗?
当然默认是不显示的。

**Comment by shshjun** [comment]
是的。class是没有问题的。
我发现这个问题是因为我有一10来个系列要显示，分别用不同type和width显示。然后我注意到type_不起作用，都是实线。改成class后就可以是虚线或点划线了。

**Comment by sunhailin-Leo** [comment]
@shshjun `class` 和 `dict` 这个问题的话，你看源码就明白了～ 你在 `dict` 设置 `type_` 是没用的因为如果你是 `dict` 类型 `pyecharts` 会直接走到渲染层面, Echarts 的没有 `type_` 这个参数 😄 ~
所以你要设置 `type`  的话应该是  `linestyle_opts={"width":3,"opacity":0.3,"type":"dotted"} `
设置 `show` 应该是  `xaxis_opts=opts.AxisOpts(type_="value", splitline_opts={"show":True})`

**Comment by sunhailin-Leo** [comment]
@shshjun `class` 层面是基于 Python 语言的一些风格最终转化到 `json` 格式的数据满足 Echarts 的渲染配置。 如果直接 `dict` 相当于直接去操作 `json` 数据，两者存在参数命名上的不同

**Comment by sunhailin-Leo** [comment]
@shshjun 你说的那个 legends 的问题，能给个图例嘛？你自己的画的，或者 Echarts 官方的示例里面 https://echarts.baidu.com/examples/

**Comment by shshjun** [comment]
> @shshjun 你说的那个 legends 的问题，能给个图例嘛？你自己的画的，或者 Echarts 官方的示例里面 https://echarts.baidu.com/examples/
好吧。不过v0.5.11是我描述和那个现象，我觉得刚好适合我用。
我看到echarts.min.js有更新。可能baidu已经改了这个行为。我自己再看看吧。

**Comment by sunhailin-Leo** [comment]
@shshjun 
* 你可以试试 1.0.0 的情况 😆 
* 或者你可以去 pyecharts 的画廊里头 [pyecharts-gallery](https://github.com/pyecharts/pyecharts-gallery) 看一下。
* 亦或者你也可以去 Echarts 的示例里头找一下，有可能使一些潜在配置设置的问题。
* 不过目前基本上的一些设置都基本齐全，除了一些图的特有配置或者一些文字的高光和阴影效果目前还没加入进去以外，基本上其他的配置都有了或者正在路上(有的在 `dev` 的分支里头哈哈) 💯 
* 欢迎继续支持 `pyecharts` thx~

**Comment by shshjun** [comment]
这是我py2.7+pe0.5.11的截图。参考以下示例 -- 
鼠标没有放在任何图例上：
![%PM726YV0} QV@S_`X6O TT](https://user-images.githubusercontent.com/816453/57122533-79675e80-6db0-11e9-8087-358c0f70d133.png)
鼠标放在B15图例上：
![Z ~FZZ 1NNFQ%}RHH8VR2YO](https://user-images.githubusercontent.com/816453/57122554-8d12c500-6db0-11e9-9f33-55bcff3050c5.png)

**Comment by chenjiandongx** [comment]
@shshjun 在 pyecharts 1.0.0 新版本中，class 和 dict 不完全等价

下划线参数是因为参数名与 Python 内置类型/关键字 重复了，比如 type，max，min，此时在 class 中我就把他们写成了 type_, max_, min_ 。但是如果要使用 dict 来传参的话，还是应该使用 {“type”: "xx", "min": 1, "max": 100}
