### ISSUE TITLE
example folder as site-packages\example

### ISSUE THREAD

**Issue by shshjun** [pyecharts/pyecharts#1054]
**问题**
python37\lib\site-packages\example\* 
这个目录里面的确全是pe的示例。不过这个位置site-packages\example\是确认过的吗? 还是希望是site-packages\pyecharts-example\

**运行环境（系统环境及 pyecharts 版本）**
win10+py3.7+pe1.0

**代码及截图**
D:\Downloads\pyecharts-dev>pip uninstall pyecharts
Uninstalling pyecharts-1.0.0:
  Would remove:
    d:\apps\python37\lib\site-packages\example\*
    d:\apps\python37\lib\site-packages\pyecharts-1.0.0.dist-info\*
    d:\apps\python37\lib\site-packages\pyecharts\*
Proceed (y/n)? y

**Comment by chenjiandongx** [comment]
example 是在源码安装的时候用的

```shell
$ git clone https://github.com/pyecharts/pyecharts.git
$ cd pyecharts/example
$ python bar_example
```
