### ISSUE TITLE
pyecharts/render/snapshot.py", line 27     **kwargs,  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ly1102** [pyecharts/pyecharts#1056]
python3.5,pyecharts最新版运行
```python3
from example.commons import Faker
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.globals import ChartType, SymbolType


def geo_base() -> Geo:
    c = (
        Geo()
        .add_schema(maptype="china")
        .add("geo", [list(z) for z in zip(Faker.provinces, Faker.values())])
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(),
            title_opts=opts.TitleOpts(title="Geo-基本示例"),
        )
    )
    return c
```
报错
>Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-47-a222f87e9ea7>", line 1, in <module>
    from example.commons import Faker

  File "/usr/local/lib/python3.5/dist-packages/example/commons.py", line 5, in <module>
    from pyecharts.render import make_snapshot

  File "/usr/local/lib/python3.5/dist-packages/pyecharts/render/__init__.py", line 1, in <module>
    from .snapshot import make_snapshot

  File "/usr/local/lib/python3.5/dist-packages/pyecharts/render/snapshot.py", line 27
    **kwargs,
            ^
SyntaxError: invalid syntax

```python3
def make_snapshot(
    engine: Any,
    file_name: str,
    output_name: str,
    delay: float = 2,
    pixel_ratio: int = 2,
    is_remove_html: bool = False,
    **kwargs,
):
    logger.info("Generating file ...")
    file_type = output_name.split(".")[-1]

    content = engine.make_snapshot(file_name, file_type, delay, pixel_ratio, **kwargs)
```

**Comment by chfw** [comment]
请用python 3.6+

**Comment by fanwz** [comment]
用的python 3.5 也同样报错
```
  File "/usr/local/lib/python3.5/dist-packages/pyecharts/charts/basic_charts/bar.py", line 36
    ):
    ^
SyntaxError: invalid syntax
```

**Comment by ly1102** [comment]
@fanwz 因为最新版 pyecharts只支持Python3.6+。所以要么使用0.5.11的pyecharts，要么升级Python。
