### ISSUE TITLE
V1.0.0的回调函数还会自动翻译吗

### ISSUE THREAD

**Issue by lleeoov** [pyecharts/pyecharts#1059]
**问题**
改用V1.0.0后，原本用Python写的回调函数不起作用了？

**运行环境（系统环境及 pyecharts 版本）**
Python 3.6.5
Pyecharts V1.0.0

**代码及截图**
V0.5.11
![0 5 11](https://user-images.githubusercontent.com/50125435/57180297-caaf4500-6eb9-11e9-98d1-81ccbda5e3fb.jpg)

V1.0.0
![1 0 0](https://user-images.githubusercontent.com/50125435/57180299-d569da00-6eb9-11e9-87e1-5ac1c4baadb5.jpg)

**Comment by chfw** [comment]
@chenjiandongx ， 你怎么看？

**Comment by chenjiandongx** [comment]
```python
label_opts=opts.LabelOpts(formatter="""function(params) { tt={'xx': 'xx'}; return tt[params.seriesName][params.name]""")
```

**Comment by chenjiandongx** [comment]
现在并不会翻译，新版本直接接受原始 js 函数 以字符串的形式
