### ISSUE TITLE
新版本 图片渲染失败

### ISSUE THREAD

**Issue by tony-tian** [pyecharts/pyecharts#1066]
**问题**
渲染图片时失败，phantomjs已经正常安装

**运行环境（系统环境及 pyecharts 版本）**
MacOS X
pyecharts 1.0

**代码及截图**
from pyecharts.charts import Bar
from pyecharts import options as opts
from pyecharts.render import make_snapshot
from snapshot_phantomjs import snapshot
def bar_chart() -> Bar:
    c = (
        Bar()
        .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
        .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
        .reversal_axis()
        .set_series_opts(label_opts=opts.LabelOpts(position="right"))
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-测试渲染图片"))
    )
    return c

make_snapshot(snapshot, bar_chart().render(), "bar0.png")

![屏幕快照 2019-05-05 下午3 46 26](https://user-images.githubusercontent.com/30079431/57190465-01826b00-6f4d-11e9-87d4-51ddb77739fb.png)

**Comment by chenjiandongx** [comment]
@tony-tian 每次执行都失败吗

**Comment by tony-tian** [comment]
对，目前没有成功过

**Comment by chenjiandongx** [comment]
@tony-tian 能否尝试使用 snapshot-selenium

**Comment by tony-tian** [comment]
snapshot-selenium 需要安装chromedriver 暂时还没有弄好...

**Comment by chenjiandongx** [comment]
那是用正常的 render 能够渲染出的 html 能够正常显示图表吗

**Comment by tony-tian** [comment]
使用render_notebook 可以正常显示，render生成的html也可以正常显示，仅在渲染导出部分失败

**Comment by chenjiandongx** [comment]
把 delay 参数设置大一点试试看

**Comment by tony-tian** [comment]
尝试了，没有解决问题

**Comment by chenjiandongx** [comment]
@tony-tian 那你还是尝试使用 snapshot-selenium 目前排查不了问题

**Comment by tony-tian** [comment]
使用snapshot-selenium渲染成功。如需要排查snapshot_phantomjs失败原因，愿意积极配合。

**Comment by chfw** [comment]
能把 bar.render() 生成的 html 打个包放这么？@tony-tian

**Comment by chenjiandongx** [comment]
@tony-tian @chfw 我觉得应该是 echarts.min.js 没加载成功的原因

**Comment by zzzbit** [comment]
遇到同样的问题，有谁解决了么。

**Comment by sunhailin-Leo** [comment]
@zzzbit @tony-tian 可以尝试使用 snapshot-pyppeteer

**Comment by jacobicao** [comment]
遇到同样问题

**Comment by sunhailin-Leo** [comment]
> 遇到同样问题

有问题，重新开 issue，并附上截图和代码
