### ISSUE TITLE
标签内容格式器里换行无效

### ISSUE THREAD

**Issue by lleeoov** [pyecharts/pyecharts#1067]
**问题**
标签内容格式器里换行无效

**运行环境（系统环境及 pyecharts 版本）**
Python 3.6.5
Pyecharts 1.0.0

**代码及截图**
![2019-05-05_160909](https://user-images.githubusercontent.com/50125435/57190711-380db500-6f50-11e9-84f8-ff6ef50c2480.jpg)

**Comment by chenjiandongx** [comment]
#1048 换行符问题已修复 急用的话可以使用 dev 进行源码安装

**Comment by chenjiandongx** [comment]
#1113
