### ISSUE TITLE
line图 背景颜色能否调整？

### ISSUE THREAD

**Issue by kiverc** [pyecharts/pyecharts#1068]
**问题**
Line图 init_opts设置里面的bg_color没有生效 ，是写法的问题吗？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts1.0
mac os

**代码及截图**
`df = pd.read_excel('/Users/apple/Desktop/visual_data.xlsx', sheet_name='行业渗透率')
c = (
    Line(init_opts = opts.InitOpts(width = "1100px",height = "500px",page_title = "渗透率",bg_color="#46C5B2"))#46C5B2
    .add_xaxis([str(x) for x in df['date']])  # X轴要文本格式
    .add_yaxis("pene", [round(x,4) for x in df['pene_new']], is_symbol_show=True, is_smooth=True, markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(type_="average")]))
    .set_series_opts(label_opts=opts.LabelOpts(is_show=True), linestyle_opts=opts.LineStyleOpts(width=2))
    .set_global_opts(title_opts=opts.TitleOpts(title="渗透率"),datazoom_opts=[opts.DataZoomOpts()]))
c.render()`

**Comment by chenjiandongx** [comment]
执行下面命令 然后再试试

```shell
$ git clone https://github.com/pyecharts/pyecharts.git -b dev
$ cd pyecharts
$ python install.py
```

**Comment by kiverc** [comment]
> ```shell
> python install.py
> ```

可以了~这个是版本问题，新版本已经修复了吗😝

**Comment by chenjiandongx** [comment]
@kiverc 嗯 新版本已经修复

**Comment by kiverc** [comment]
> @kiverc 嗯 新版本已经修复

好的
