### ISSUE TITLE
1.0的pyecharts如何实现仪表盘和饼图并行 （左右布局）

### ISSUE THREAD

**Issue by weichen1018** [pyecharts/pyecharts#1069]
请问如何实现仪表盘和饼图并行，左右布局的那种。我自己尝试着用grid，但是执行的时候会报错，说类型错误，获取不到x轴。
下面是我的代码：
def grid_horizontal() -> Grid:
    list1 = ["住院","其他","门诊"]
    list2 = [30,90,10]
    pie = (
        Pie(init_opts=opts.InitOpts(theme=ThemeType.CHALK, width="400"))
        .add(
            "药费占比",
            [list(z) for z in zip(list1, list2)],
            center=["25%", "50%"],
            label_opts=opts.LabelOpts(is_show=True,position="inside",formatter="{b}: {d}"),
        )
        .set_global_opts(title_opts=opts.TitleOpts(title="药费占比",pos_left="21.5%"),
                         legend_opts=opts.LegendOpts(is_show=False),
                         toolbox_opts=opts.ToolboxOpts(pos_left="30%"),
                         )
        # .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
    )

    gauge = (
        Gauge()
        .add("", [("完成率", 66.6)])
        .set_global_opts(title_opts=opts.TitleOpts(title="Gauge-基本示例"))
    )
    grid = (
        Grid()
        .add(gauge, grid_opts=opts.GridOpts(pos_left="55%"))
        .add(pie, grid_opts=opts.GridOpts(pos_right="55%"))
    )
    return grid

下面是要实现的效果图：
![image](https://user-images.githubusercontent.com/38155568/57191347-195eec80-6f57-11e9-91d6-aa9ea78e251d.png)

**Comment by sunhailin-Leo** [comment]
@weichen1018 
* 这个问题目前是暂时无法解决(除了手动修改生成的 html)
* 这个问题之后会进行尝试解决，目前 `Grid` 只适用于直接坐标系的图 `RectChart`

**Comment by weichen1018** [comment]
好的   感谢您的解答

**Comment by chenjiandongx** [comment]
可以使用 V1.2.0 的 Page Layout 功能
