### ISSUE TITLE
请问，柱形图中柱子的宽度怎么设置？

### ISSUE THREAD

**Issue by MiguelCoco** [pyecharts/pyecharts#1070]
**问题**
请问，柱形图中柱子的宽度怎么设置？

**运行环境（系统环境及 pyecharts 版本）**
win10
0.5.11

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@MiguelCoco 
* 目前还没有这个设置，不过如果需要的话可以手动改一下生成的 html 文件。
* 配置文档如下：
https://www.echartsjs.com/option.html#series-bar.barWidth

**Comment by chenjiandongx** [comment]
@MiguelCoco 使用 category_gap 参数
```python
def bar_base() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values(), category_gap="70%")
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"))
    )
    return c
```
![image](https://user-images.githubusercontent.com/19553554/57195474-a456db80-6f85-11e9-91dd-e5f0e2d38731.png)

**Comment by MiguelCoco** [comment]
@chenjiandongx @sunhailin-Leo 非常感谢解答，看起来只能使用1.x版本了
