### ISSUE TITLE
重启Notebook文件后图片消失

### ISSUE THREAD

**Issue by henrychow94** [pyecharts/pyecharts#1071]
jupyter notebook中用pyecharts画的图，在关闭该notebook并重新打开之后，显示空白，并不会像matplot画的图那样一直在

此问题如何解决呢？

**Comment by chfw** [comment]
这个要看在什么情况下打开。没有网络时打开，肯定空白

**Comment by henrychow94** [comment]
> 这个要看在什么情况下打开。没有网络时打开，肯定空白

打开时都有网络的（BTW这还跟网络有关系吗？）

**Comment by chfw** [comment]
Echarts.js 是在网上

**Comment by chenjiandongx** [comment]
@henrychow94 在网络状况良好的情况下一般是能够渲染出图的 可能需要稍等几秒钟而已 你用的是 pyecharts 哪个版本

**Comment by henrychow94** [comment]
> @henrychow94 在网络状况良好的情况下一般是能够渲染出图的 可能需要稍等几秒钟而已 你用的是 pyecharts 哪个版本

我用的是0.5.11，联网状态下也是重启不能显示

**Comment by chenjiandongx** [comment]
请使用 V1 版本啦 旧版本已不再维护

**Comment by chfw** [comment]
https://05x-docs.pyecharts.org/#/zh-cn/faq
