### ISSUE TITLE
Line图如何隐藏Y轴坐标系？

### ISSUE THREAD

**Issue by kiverc** [pyecharts/pyecharts#1074]
**问题**
用的Line图，然后创建了图表 想把Y轴隐藏掉 ，这个1.0能实现吗？
是写在哪个位置？还有想问下X轴的颜色是怎么调？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.0
macos

**代码及截图**
`c = (
    Line(init_opts=opts.InitOpts(width="900px", height="450px",
                                 page_title="行业渗透率", bg_color="#46C5B2"))
    .add_xaxis([str(x) for x in df['date']])  # X轴要文本格式
    .add_yaxis("pene", [round(x, 4) for x in df['pene_new']],
               is_symbol_show=True,
               is_smooth=True,
               color ="yellow",
               yaxis_index="0",
               #is_selected='True',
               #symbol ="circle",
               #markpoint_opts=opts.MarkPointOpts(color="yellow"),
               markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(type_="average"),]))
    .set_series_opts(
                     label_opts=opts.LabelOpts(is_show=True, color="white"),
                     linestyle_opts=opts.LineStyleOpts(width=2, color="yellow"))
    .set_global_opts(title_opts=opts.TitleOpts(title="某行业渗透率", pos_left='auto',title_textstyle_opts=opts.TextStyleOpts(color="white")),
                     datazoom_opts=[opts.DataZoomOpts()],
                     legend_opts=opts.LegendOpts(orient='vertical',pos_right='10%')))
c.render_notebook()
`
![image](https://user-images.githubusercontent.com/42595176/57192313-a313b780-6f61-11e9-97cb-a078d68b9d4f.png)

**Comment by sunhailin-Leo** [comment]
@kiverc 
* 隐藏 Y 轴： 你试试 `opts.AxisOpts(is_show=False)`
* X 轴的颜色: 
```python
opts.AxisOpts(
    axisline_opts=opts.AxisLineOpts(
        linestyle_opts=opts.LineStyleOpts(color="red")
   )
)
```

**Comment by sunhailin-Leo** [comment]
* 附赠 Echarts 的官方文档 : https://www.echartsjs.com/option.html#yAxis.axisLine.lineStyle

**Comment by kiverc** [comment]
> @kiverc
> 
> * 隐藏 Y 轴： 你试试 `opts.AxisOpts(is_show=False)`
> * X 轴的颜色:
> 
> ```python
> opts.AxisOpts(
>     axisline_opts=opts.AxisLineOpts(
>         linestyle_opts=opts.LineStyleOpts(color="red")
>    )
> )
> ```

.add_yaxis里面Y轴的没有这个参数设置呢，global也没有呢

**Comment by chenjiandongx** [comment]
@kiverc 

```python
def bar_base() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .add_yaxis("商家B", Faker.values())
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"),
            yaxis_opts=opts.AxisOpts(is_show=False),
        )
    )
    return c
```

**Comment by chenjiandongx** [comment]
@kiverc 下回不要这么贴代码 这格式没人会看

![image](https://user-images.githubusercontent.com/19553554/57195436-05ca7a80-6f85-11e9-873f-518b1b4012ce.png)

**Comment by kiverc** [comment]
> @kiverc
> 
> ```python
> def bar_base() -> Bar:
>     c = (
>         Bar()
>         .add_xaxis(Faker.choose())
>         .add_yaxis("商家A", Faker.values())
>         .add_yaxis("商家B", Faker.values())
>         .set_global_opts(
>             title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"),
>             yaxis_opts=opts.AxisOpts(is_show=False),
>         )
>     )
>     return c
> ```
好的
