### ISSUE TITLE
未来版本将会支持和更新的列表 (Future Version Support & Update List)

### ISSUE THREAD

**Issue by sunhailin-Leo** [pyecharts/pyecharts#1082]
### 中文
* 支持和更新的列表:
  * ~~**解决 Overlap + Grid 的图例复合问题**~~ v1.2.0 更新
      * ~~https://github.com/pyecharts/pyecharts/issues/1118~~ v1.2.0 更新
  * ~~支持在图中配置 Graphic 原生图形元素组件。[官方文档](https://www.echartsjs.com/option.html#graphic) 👏~~ v1.2.0 更新
      * ~~https://github.com/pyecharts/pyecharts/issues/991  --->  PR: https://github.com/pyecharts/pyecharts/pull/1162~~ v1.2.0 更新
  * 支持 SingleAxis 单轴的数据视图。
  * ~~支持 brush 区域选择组件。~~
  * ~~支持 Echarts 的 animation 的相关配置。~~
  * ~~支持 Echarts 的 GL 中的 globe 配置。~~

### English
* Support & Update List:
  * ~~**Fix Overlap + Grid Chart display error**~~ Updated at v1.2.0
  * ~~Support to configure Echarts Graphic component.[Official Document](https://www.echartsjs.com/option.html#graphic) 👏~~ Updated at v1.2.0
     * ~~https://github.com/pyecharts/pyecharts/issues/991  --->  PR: https://github.com/pyecharts/pyecharts/pull/1162~~ Updated at v1.2.0
  * Support SingleAxis configuration.
  * ~~Support brush area selection component.~~
  * ~~Support Echarts animation configuration.~~
  * ~~Support Echarts GL globe configuration.~~

---

* 欢迎补充一些期望加入的功能在评论区中 
* Welcome to add some expected features in the comments section

**Comment by alwaysberay** [comment]
> ### 中文
> * 支持和更新的列表:
>   
>   * ~**解决 Overlap + Grid 的图例复合问题**~ v1.2.0 更新
>     
>     * ~#1118~ v1.2.0 更新
>   * ~支持在图中配置 Graphic 原生图形元素组件。[官方文档](https://www.echartsjs.com/option.html#graphic) clap~ v1.2.0 更新
>     
>     * ~#991  --->  PR: #1162~ v1.2.0 更新
>   * 支持 SingleAxis 单轴的数据视图。
>   * ~支持 brush 区域选择组件。~
>   * ~支持 Echarts 的 animation 的相关配置。~
>   * ~支持 Echarts 的 GL 中的 globe 配置。~
> 
> ### English
> * Support & Update List:
>   
>   * ~**Fix Overlap + Grid Chart display error**~ Updated at v1.2.0
>   * ~Support to configure Echarts Graphic component.[Official Document](https://www.echartsjs.com/option.html#graphic) clap~ Updated at v1.2.0
>     
>     * ~#991  --->  PR: #1162~ Updated at v1.2.0
>   * Support SingleAxis configuration.
>   * ~Support brush area selection component.~
>   * ~Support Echarts animation configuration.~
>   * ~Support Echarts GL globe configuration.~
> 
> * 欢迎补充一些期望加入的功能在评论区中
> * Welcome to add some expected features in the comments section

这条啥时候实现？ --- 支持 SingleAxis 单轴的数据视图。
