### ISSUE TITLE
echarts is not defined

### ISSUE THREAD

**Issue by tuobabing** [pyecharts/pyecharts#1087]
**问题**

安装完 pyecharts ，按照文档在jupyternotebook 上输入bar相关代码，执行顺利图出不来
F12看到说echarts is not defined

**运行环境（系统环境及 pyecharts 版本）**
win7 64位  anaconda 64
pyecharts 版本 1.00

**代码及截图**

**Comment by tuobabing** [comment]
离线环境

**Comment by sunhailin-Leo** [comment]
@tuobabing 离线环境肯定出不来额，默认是在线加载 js 依赖的

**Comment by tuobabing** [comment]
离线环境真的很需要考虑啊。。。。

**Comment by sunhailin-Leo** [comment]
@tuobabing 能看文档不？https://pyecharts.org/#/zh-cn/assets_host

**Comment by tuobabing** [comment]
多谢，刚才在Google是否需要多安装一个pkg

**Comment by chfw** [comment]
文档说了离线怎么用
