### ISSUE TITLE
0.5x版本 jinja2 错误

### ISSUE THREAD

**Issue by PeterJaq** [pyecharts/pyecharts#1088]
flask jinja2 + pyecharts 0.5.1

在 页面中增加 jinja2 代码 用来渲染page
{{ echarts_js_dependencies(page) }}

错误提示：
jinja2.exceptions.UndefinedError: 'echarts_js_dependencies' is undefined
、

**Comment by sunhailin-Leo** [comment]
@PeterJaq What Problem？

**Comment by PeterJaq** [comment]
这是我的 jinja2的代码文件。
{% extends "base.html" %}

{% block content %}

{{ echarts_js_dependencies(page) }}

 <div style="width:1800px">
{% for chart in page %}
 <div style="float:left">
    {{ echarts_container(chart) }}
</div>
{% endfor %}
</div>
{{ echarts_js_content(*page) }}

{% endblock %}

这是我的flask的render代码：

return render_template('statistics.html', page=page）
