### ISSUE TITLE
pyecharts 交流群

### ISSUE THREAD

**Issue by chenjiandongx** [pyecharts/pyecharts#1091]
* 目前暂时不再提供二维码入群的功能（防广告，营销号）
* 需要参与交流群的可以通过加入 Discord 讨论进行讨论。https://discord.gg/rrYAyxfmbu

**有问题请先仔细阅读一遍文档 [pyecharts.org](https://pyecharts.org)**

**Comment by JR-Hub** [comment]
![image](https://user-images.githubusercontent.com/10087048/57432856-8df09e80-7269-11e9-9c17-8388b38d2a43.png)
福建莆田定位错误？

**Comment by chenjiandongx** [comment]
@JR-Hub 有问题另提 issue 不要在本 issue 下面讨论问题

**Comment by JR-Hub** [comment]
不好意思，对github还不是特别懂，谢谢了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 陈键冬 <notifications@github.com>
发送时间: Thursday, May 9, 2019 4:38:45 PM
收件人: pyecharts/pyecharts
抄送: JR-Hub; Mention
主题: Re: [pyecharts/pyecharts] pyecharts 交流群 (#1091)


@JR-Hub<https://github.com/JR-Hub> 有问题另提 issue 不要在本 issue 下面讨论问题

―

**Comment by suker413** [comment]
已经过期了

**Comment by kingmo888** [comment]
又过期啦。

**Comment by chenjiandongx** [comment]
2019-05-16 已更新

**Comment by ZhangYangDev** [comment]
又过期啦

**Comment by Chinese-boy** [comment]
@chenjiandongx

**Comment by gengyilong** [comment]
怎么入伙

**Comment by andrew-sn** [comment]
想入群，我的微信是opsn_bi，有好心人拉下我吗？我想咨询的是，在pyecharts有类似于bootstrap-multiselect这样的插件吗？我的图标标签过多。

**Comment by r41350** [comment]
python3.7 import issue:

first, execute--> pip install pyecharts
and then using " from pyecharts.charts import Bar ", error as following
"
ImportError: cannot import name 'Bar' from 'pyecharts.charts' (C:\Users\Administrator\Anaconda3\lib\site-packages\pyecharts\charts\__init__.py)
"

**Comment by Anthony-Duan** [comment]
想加入群 能否给个码

**Comment by chenjiandongx** [comment]
@Chinese-boy @gengyilong @andrew-sn @Anthony-Duan 

2019-06-01 已更新二维码

**Comment by nealchenzhang** [comment]
刚好昨天错过。。小白求加群

**Comment by chenjiandongx** [comment]
2019-06-11 已更新

**Comment by InsertMone** [comment]
@chenjiandongx 刚好错过....大佬麻烦更新下二维码

**Comment by chenjiandongx** [comment]
2019-06-21 已更新

**Comment by zrz090602010** [comment]
@chenjiandongx

**Comment by zrz090602010** [comment]
@chenjiandongx 大佬晚上好

**Comment by chenjiandongx** [comment]
2019-06-29 已更新

**Comment by scanfyu** [comment]
已超过100人，微信号Krieger

**Comment by MatthewZou9419** [comment]
@chenjiandongx

**Comment by remindstam** [comment]
过期了啊  remindstam求拉

**Comment by chenjiandongx** [comment]
2019-07-12 已更新

**Comment by MatthewZou9419** [comment]
@chenjiandongx 人满啦

**Comment by lofty77** [comment]
人满啦

**Comment by chenjiandongx** [comment]
2019-07-13 已更新

**Comment by wenshi11019** [comment]
没看到二维码的？

**Comment by chenjiandongx** [comment]
2019-07-20 更新

**Comment by xubosong** [comment]
二维码过期啦~

**Comment by chenjiandongx** [comment]
@xubosong 二维码已更新 2019-08-27

**Comment by ariallyp** [comment]
麻烦更新下二维码，想加群 @chenjiandongx

**Comment by ariallyp** [comment]
@chenjiandongx 麻烦更新下二维码，已经过期了。

**Comment by chenjiandongx** [comment]
已更新

**Comment by DongTau** [comment]
@chenjiandongx 二维码过期啦

**Comment by chenjiandongx** [comment]
2019-09-17 已更新

**Comment by sunrisehang** [comment]
能邀请一下我吗，我的微信号：hang3310217

**Comment by kinslyzhu** [comment]
超过100人加不进去了。。。

**Comment by chenjiandongx** [comment]
2019-09-23 已更新

**Comment by mengsongouyang** [comment]
@chenjiandongx 请问可以更新二维码吗？谢谢！

**Comment by chenjiandongx** [comment]
2019-10-09 已更新

**Comment by Roman996363785** [comment]
请问可以再更新一下二维码吗？谢谢！

**Comment by chenjiandongx** [comment]
@Roman996363785 2019-10-18 已更新

**Comment by luosuo10** [comment]
@chenjiandongx 二维码失效啦~ 麻烦更新一下。

**Comment by littlewhitelyw** [comment]
文档挂掉了？

**Comment by Jokertion** [comment]
二维码失效咯，麻烦更新下~ @chenjiandongx

**Comment by chenjiandongx** [comment]
2019-11-01 已更新

**Comment by charujing** [comment]
@chenjiandongx 二维码失效，麻烦您更新下，谢谢

**Comment by songxunyu** [comment]
@chenjiandongx 二维码失效，麻烦您更新下，谢谢

**Comment by chenjiandongx** [comment]
2019-11-08  已更新

**Comment by Lisazzx** [comment]
我想问下，为啥不能对page进行tab

**Comment by luzwales** [comment]
二维码失效了，更新下

**Comment by chenjiandongx** [comment]
2019-11-20 已更新

**Comment by yhzhang1** [comment]
二维码失效了，更新下

**Comment by li904775857** [comment]
二维码失效了  更新下

**Comment by RaoTianlong** [comment]
@chenjiandongx 二维码失效了，求更新

**Comment by PyYourDaYe** [comment]
@chenjiandongx 二维码失效，麻烦您更新下，谢谢

**Comment by vv4304** [comment]
失效了 建议换成QQ群 @chenjiandongx

**Comment by chenjiandongx** [comment]
@sunhailin-Leo 以后这个任务就交给你了

**Comment by kopes18** [comment]
有qq群吗 好多问题

**Comment by Yuxiaoy1** [comment]
直接扫码提示群成员超过100人，需要邀请才能入群了

**Comment by 1015zhc** [comment]
二维码，失效了，求更新。

**Comment by 0gfy0** [comment]
二维码失效了，求更新

**Comment by sunhailin-Leo** [comment]
> 有qq群吗 好多问题

Re-check this issue.

**Comment by sunhailin-Leo** [comment]
> 二维码，失效了，求更新。

Re-check this issue.

**Comment by sunhailin-Leo** [comment]
> 二维码失效了，求更新

Re-check this issue.
