### ISSUE TITLE
1.0版本地图只显示南海

### ISSUE THREAD

**Issue by bernkastle** [pyecharts/pyecharts#1096]
**问题**
1.0版本，地图官网示例只显示南海
不论是否安装地图包，都显示一样的地图

**运行环境（系统环境及 pyecharts 版本）**
jupyterlab
pyecharts: v1.0

**代码及截图**
![image](https://user-images.githubusercontent.com/11273397/57436269-f2aff700-7271-11e9-99fa-a8d539884733.png)

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/57442273-36106280-727e-11e9-86b4-88671a904629.png)

**Comment by bernkastle** [comment]
@chenjiandongx  

现在可以显示了，非常感谢！！
