### ISSUE TITLE
1.0版本 Line不显示提示框和工具箱

### ISSUE THREAD

**Issue by dachoume** [pyecharts/pyecharts#1097]
**问题**
1.0版本 Line不显示提示框和工具箱

**运行环境（系统环境及 pyecharts 版本）**
python3.6，pyecharts1.0.0

**代码及截图**
line = (
        Line()
        .add_xaxis(['1', '2', '3', '4', '5'])
        .add_yaxis('a', [1, 2, 3, 4, 5])
        .set_global_opts(title_opts=opts.TitleOpts(title='test'))
        .set_global_opts(toolbox_opts=opts.ToolboxOpts(is_show=True))
        .set_global_opts(tooltip_opts=opts.TooltipOpts(is_show=True))
    )
    line.render('111.html')
<img width="1103" alt="屏幕快照 2019-05-09 下午4 26 13" src="https://user-images.githubusercontent.com/26477998/57438736-2e998b00-7277-11e9-81b1-221ac5a5edd2.png">

**Comment by dachoume** [comment]
title也没有显示

**Comment by dachoume** [comment]
line = (
        Line()
            .add_xaxis(['1', '2', '3', '4', '5'])
            .add_yaxis('a', [1, 2, 3, 4, 5], is_symbol_show=False)
            .set_global_opts(title_opts=opts.TitleOpts(title='test'), )
            .set_global_opts(tooltip_opts=opts.TooltipOpts(is_show=True, trigger='axis', axis_pointer_type='cross'))
    )
    line.render('111.html')
多加了几个配置，提示出来了。
但是title还是没出现

**Comment by dachoume** [comment]
<img width="1104" alt="屏幕快照 2019-05-09 下午4 53 30" src="https://user-images.githubusercontent.com/26477998/57440661-fd22be80-727a-11e9-8224-9aed9a825cd2.png">

**Comment by chenjiandongx** [comment]
执行一次 set_global_opts 就好啦，参数放一起不就行了 为什么要分多次

**Comment by dachoume** [comment]
> 执行一次 set_global_opts 就好啦，参数放一起不就行了 为什么要分多次

多谢👍
