### ISSUE TITLE
pyecharts 的日历图支持 %Y-%m格式的数据吗？

### ISSUE THREAD

**Issue by helixg** [pyecharts/pyecharts#1100]
**问题**
demo中的calander图片是%y-%m-%d格式的，但我希望每一个方格代表一个月，输入的数据是%Y-%m格式的，请问pyecharts是否支持呢？

**运行环境（系统环境及 pyecharts 版本）**
data = 
[[' 2001-07', 74],
 [' 2000-04', 57],
 [' 1999-12', 52],
 [' 2001-02', 50],
 [' 1999-02', 44],
 [' 1999-07', 43],
 [' 1999-06', 37],
 [' 1999-08', 36],
 [' 2000-12', 35],
 [' 2000-01', 34],
 [' 1999-09', 31],
 [' 2000-03', 31],
 [' 1999-03', 28]]

**代码及截图**
import datetime
import random

from pyecharts import options as opts
from pyecharts.charts import Calendar

```
def calendar_base() -> Calendar:
    data

    c = (
        Calendar()
        .add("",data, calendar_opts=opts.CalendarOpts(range_=['1998-04', '2001-12']))
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Calendar"),
            visualmap_opts=opts.VisualMapOpts(
                max_=74,
                min_=1,
                orient="horizontal",
                is_piecewise=True,
                pos_top="230px",
                pos_left="100px",
            ),
        )
    )
    return c
```

**Comment by sunhailin-Leo** [comment]
@helixg 顾名思义 日历图 。 以 日 为单位
