### ISSUE TITLE
pyecharts与pyecharts_snapshot 结合使用出现问题，html转化为pdf出错

### ISSUE THREAD

**Issue by Fitsh** [pyecharts/pyecharts#1105]
问题：pyecharts与pyecharts_snapshot 结合使用出现下面的问题，html转化为pdf出错
           1可视化.py:14: RuntimeWarning: coroutine 'make_a_snapshot' was never awaited make_a_snapshot("1.html", "1.pdf")

**运行环境（系统环境及 pyecharts 版本）**
win10，pycharm，python3.7，pyecharts为1.0版本

**代码及截图**

import pyecharts
from pyecharts_snapshot.main import make_a_snapshot # 快照，截图
import os
import time

bar = pyecharts.charts.Bar()
bar.add_xaxis(["湖南", "山东", "湖北"])
bar.add_yaxis("对比", [4, 5, 6])
bar.set_global_opts(title_opts=pyecharts.options.TitleOpts(title="这是一个图表"))
bar.render("1.html")  # 保存到文件-查看数据
mydata = bar.render_embed()  # 内置的js

make_a_snapshot("1.html", "1.pdf")

**Comment by chfw** [comment]
Pyecharts-snapshot 0.2.0 不再支持 make_a_snapshot了。请用前一版。

需要更多信息的话 看pyecharts 文档和 pyecharts-snapshot 自述说明
