### ISSUE TITLE
python setup.py install 安装时出错，需要在文件头声明编码方式

### ISSUE THREAD

**Issue by brightgems** [pyecharts/pyecharts#1116]
**问题**
python setup.py install 安装时出错，需要在文件头声明编码方式

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@brightgems issue 格式!

**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
