### ISSUE TITLE
请问pyecharts在同一张图中可以通过拖拽实现时间维度自动缩放吗?怎么实现?

### ISSUE THREAD

**Issue by monkeyshichi** [pyecharts/pyecharts#1117]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chenjiandongx** [comment]
可以试试 将 x 轴的 type_ 设置为 `time`，然后加上 dataZoom

**Comment by monkeyshichi** [comment]
> 可以试试 将 x 轴的 type_ 设置为 `time`，然后加上 dataZoom

Ok,Thanks
