### ISSUE TITLE
堆积面积图时使用toolbox会导致y轴显示不正确

### ISSUE THREAD

**Issue by ccpic** [pyecharts/pyecharts#1120]
**问题**
堆积面积图时使用toolbox会导致y轴显示不正确

**运行环境（系统环境及 pyecharts 版本）**
Windows
pyecharts 1.10

**代码及截图**
如图，假设堆积面积图global opts加了toolbox is show
![微信截图_20190516141308](https://user-images.githubusercontent.com/38186647/57830544-0664db80-77e5-11e9-8e3a-24ccf74bfd0a.png)

渲染后图表y轴最大值错误（错误设置为第一个series的近似值，而不是总量的近似值），经测试如没有toolbox则显示正确
![微信截图_20190516141411](https://user-images.githubusercontent.com/38186647/57830620-3b712e00-77e5-11e9-8b0e-a627146da33d.png)

**Comment by ccpic** [comment]
发现可以暂时通过手动设置yaxis option max_=df.sum(axis=1).max()解决

**Comment by sunhailin-Leo** [comment]
@ccpic 
```python
toolbox=opts.Toolbox(
    feature=opts.ToolBoxFeatureOpts(data_zoom={"show": True, "yAxisIndex": 1})
)
```
* 这样也可以~ 之前讨论群有人问过这个问题

**Comment by sunhailin-Leo** [comment]
@ccpic 问题核心只是 `toolbox` 的 `Y` 轴索引而已
