### ISSUE TITLE
Line3D折线图怎样设置不同系列的颜色，以及设置每个数据点的symbol

### ISSUE THREAD

**Issue by gaojie-shumei** [pyecharts/pyecharts#1122]
**问题**
Line3D折线图怎样设置不同系列的颜色，以及设置每个数据点的symbol

**运行环境（系统环境及 pyecharts 版本）**
win10   pyecharts 1.1.0

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@gaojie-shumei 
* Echarts 关于 Line3D 的 demo 只有一个，目前也找不到 demo 去解决你这个问题。
* 先 Closed 掉，后续有 demo 了再 re-open.
