### ISSUE TITLE
x轴数据多一些，怎么显示

### ISSUE THREAD

**Issue by Flyerison** [pyecharts/pyecharts#1129]
截图 我就不放了 
X轴数据10个就不能显示全了，有什么方法可以显示出来
xaxis_opts=opts.AxisOpts(name_rotate=30, interval=0))
找了一些方法  在新版本上貌似不起作用？？

**Comment by sunhailin-Leo** [comment]
@Flyerison 
* emmm，你不放图那怎么知道问题在哪？（纯靠脑补？）
* 一些方法？有哪些？

**Comment by zxc-7** [comment]
我也出现了这个问题，怎么解决的？

**Comment by zxc-7** [comment]
能加个QQ好友嘛？847312005

**Comment by Flyerison** [comment]
![BE35E726-916B-4992-9EDD-3810C3C6FABA](https://user-images.githubusercontent.com/28044926/58604862-7b95dd80-82c8-11e9-98a2-e56044e3e21c.png)
觉得描述已经够了   没找到方法  准备版本回退了

**Comment by chenjiandongx** [comment]
建议旋转坐标轴标签

![image](https://user-images.githubusercontent.com/19553554/58606843-ca934100-82cf-11e9-8894-8cf9b1cca855.png)

![](https://user-images.githubusercontent.com/19553554/56972171-16ea4480-6b9d-11e9-834c-b8eb4357808c.png)
