### ISSUE TITLE
V1.1地图只显示南海，没有其他边界轮廓

### ISSUE THREAD

**Issue by 276077345** [pyecharts/pyecharts#1138]
**问题**
V1.1地图只显示南海，没有其他边界轮廓,使用v0.55能正常显示，重新安装v1.1无法显示

**运行环境（系统环境及 pyecharts 版本）**
WIN10
pycharm
pyecharts V1.1
已安装：
echarts-china-cities-pypkg         0.0.9
echarts-china-provinces-pypkg      0.0.3
echarts-countries-pypkg            0.1.6
pyecharts                          1.1.0

**代码及截图**
![微信截图_20190523130320](https://user-images.githubusercontent.com/27173912/58226999-a7124880-7d5b-11e9-99f6-f319a3cc6bc3.png)
![微信截图_20190523130412](https://user-images.githubusercontent.com/27173912/58227000-a7124880-7d5b-11e9-9e91-fc6497532e21.png)
![微信截图_20190523130536](https://user-images.githubusercontent.com/27173912/58227001-a7aadf00-7d5b-11e9-82d6-70c422cada29.png)
![微信截图_20190523130639](https://user-images.githubusercontent.com/27173912/58227003-a7aadf00-7d5b-11e9-8bb4-3a9825820541.png)

**Comment by 276077345** [comment]
![微信截图_20190523131004](https://user-images.githubusercontent.com/27173912/58227110-1851fb80-7d5c-11e9-8e7f-08067a7be2a0.png)

**Comment by 276077345** [comment]
from flask import Flask, render_template
from example.commons import Faker
from pyecharts import options as opts
from pyecharts.charts import Geo

app = Flask(__name__, static_folder="templates")


def geo_base() -> Geo:
    c = (
        Geo()
        .add_schema(maptype="china")
        .add("geo", [list(z) for z in zip(Faker.provinces, Faker.values())])
        .set_series_opts(label_opts=opts.LabelOpts(is_show=True))
        .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(),
            title_opts=opts.TitleOpts(title="Geo-基本示例"),
        )
    )
    return c

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/geoChart")
def get_geo_chart():
    c = geo_base()
    return c.dump_options()

if __name__ == "__main__":
    app.run()
    app.debug = True

**Comment by 276077345** [comment]
使用如下才能正常显示
@app.route("/")
def index():
    c = geo_base()
    return Markup(c.render_embed())

**Comment by 276077345** [comment]
手动添加了JS才正常。
<script type="text/javascript" src="/templates/maps/china.js"></script>
有什么更好的解决办法吗

**Comment by chenjiandongx** [comment]
使用 jinja2 模板

**Comment by 276077345** [comment]
{% for jsfile_name in script_list %}
        <script src="{{ host }}/{{ jsfile_name }}.js"></script>
    {% endfor %}
加了这个也无法使用，可以指导一下吗，谢谢了。

**Comment by 276077345** [comment]
> 使用 jinja2 模板

{% for jsfile_name in script_list %}
    <script src="{{ host }}/{{ jsfile_name }}.js"></script>
{% endfor %}
加了这个也无法使用，可以指导一下吗，谢谢了。

**Comment by 276077345** [comment]
> 使用 jinja2 模板

from pyecharts.globals import CurrentConfig
CurrentConfig.ONLINE_HOST = "http://127.0.0.1:8000/assets/"

这个也启动设置了

**Comment by chenjiandongx** [comment]
把你的完整模板贴出来

**Comment by 276077345** [comment]
> 把你的完整模板贴出来

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Awesome-pyecharts</title>
    <script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% for jsfile_name in script_list %}
        <script src="{{ host }}/{{ jsfile_name }}.js"></script>
    {% endfor %}
    
    
</head>
<body>


<div class="container-fluid">
    <h1 style=" text-align:center">全国地图</h1>
    <h5 id="myDiv" style=" text-align:center"></h5>
    </div>
	<div class="row">
    <div class="col-md-8" id="timeline_bar" style="width:800px; height:600px;"></div>
    <div class="col-md-4">
        <div class="row">
        <div class="col-md-12" id="provinceChart" style="width:600px; height:300px;"></div>
        </div>
        <div class="row">
        <div class="col-md-12" id="barChart" style="width:600px; height:300px;"></div>
        </div>
	</div>
</div>


<script>
    $(
        function () {
            var chart = echarts.init(document.getElementById('timeline_bar'), 'white', {renderer: 'canvas'});
            $.ajax({
                type: "GET",
                url: "http://127.0.0.1:5000/timeline_bar",
                dataType: 'json',
                success: function (result) {
                    console.log(result);
                    chart.setOption(result);
                }
            });
            chart.on('click', function (params) {
            if (params.value == 1) {
                var newchart = echarts.init(document.getElementById('provinceChart'), 'white', {renderer: 'canvas'});
                console.log(params.name);
                console.log(params.value);
            $.ajax({
                type: "GET",
                url: "http://127.0.0.1:5000/provinceChart",
                dataType: 'json',
                success: function (result) {
                    newchart.setOption(result);
               }
           });
           $.ajax({
                type: "POST",
                url: "http://127.0.0.1:5000/1",
                dataType: 'json',
                data : {name: params.name},
                datatype:"json",
                success: function (data) {
                    console.log(data);
                    $("#myDiv").css("background-color","yellow");
                    $("#myDiv").html(data.msg);
              }

           });
           }
            })
})
</script>
<script>
    $(
        function () {
            var chart = echarts.init(document.getElementById('barChart'), 'white', {renderer: 'canvas'});
            $.ajax({
                type: "GET",
                url: "http://127.0.0.1:5000/barChart",
                dataType: 'json',
                success: function (result) {
                    console.log(result);
                    chart.setOption(result);
                }
            })});

</script>
</body>
</html>

**Comment by 276077345** [comment]
![截图6](https://user-images.githubusercontent.com/27173912/58304634-ae068d00-7e27-11e9-91d0-23f0e50e2cb4.png)
![截图5](https://user-images.githubusercontent.com/27173912/58304635-ae068d00-7e27-11e9-84da-2f67442b5c5f.png)
![截图4](https://user-images.githubusercontent.com/27173912/58304636-ae9f2380-7e27-11e9-993d-03edcbed9ae3.png)
![截图3](https://user-images.githubusercontent.com/27173912/58304637-ae9f2380-7e27-11e9-9361-2825cdecc273.png)
![截图2](https://user-images.githubusercontent.com/27173912/58304638-af37ba00-7e27-11e9-823c-b6a72c005958.png)
![截图1](https://user-images.githubusercontent.com/27173912/58304639-af37ba00-7e27-11e9-9815-fa814e91c462.png)

**Comment by 276077345** [comment]
![截图1](https://user-images.githubusercontent.com/27173912/58304711-f8880980-7e27-11e9-9347-96476c483928.png)
![截图4](https://user-images.githubusercontent.com/27173912/58304715-faea6380-7e27-11e9-931e-f672cd3cb4bb.png)
![截图5](https://user-images.githubusercontent.com/27173912/58304717-fd4cbd80-7e27-11e9-83a1-6ce77a8b3b00.png)
![截图6](https://user-images.githubusercontent.com/27173912/58304718-ff168100-7e27-11e9-8979-26c378e15d1b.png)

**Comment by 276077345** [comment]
> 把你的完整模板贴出来



> 把你的完整模板贴出来

![截图2](https://user-images.githubusercontent.com/27173912/58315529-4c085080-7e44-11e9-97cb-56bb241fb670.png)
![截图4](https://user-images.githubusercontent.com/27173912/58315531-4dd21400-7e44-11e9-8237-4446a60881cc.png)
![截图5](https://user-images.githubusercontent.com/27173912/58315532-4f9bd780-7e44-11e9-894f-73e5a2ba6e72.png)
![截图6](https://user-images.githubusercontent.com/27173912/58315537-51659b00-7e44-11e9-8da7-81cfaeb82297.png)

**Comment by 276077345** [comment]
> 把你的完整模板贴出来

@chenjiandongx 麻烦你了，研究了好久也不行
![截图2](https://user-images.githubusercontent.com/27173912/58315812-cf29a680-7e44-11e9-80a1-9809b857492e.png)
![截图4](https://user-images.githubusercontent.com/27173912/58315818-d0f36a00-7e44-11e9-9626-561bef83e6ce.png)
![1](https://user-images.githubusercontent.com/27173912/58315822-d2bd2d80-7e44-11e9-973f-e8e549fbe7fa.png)
![截图6](https://user-images.githubusercontent.com/27173912/58315829-d51f8780-7e44-11e9-9b33-39af72a0c115.png)

**Comment by 276077345** [comment]
使用 render_embed 可以正常引入

**Comment by chenjiandongx** [comment]
看起来这种情况下你需要自己提供渲染所需要的 js 文件
