### ISSUE TITLE
“Grid-多 Y 轴示例”这一小节存在错误

### ISSUE THREAD

**Issue by fhhan** [pyecharts/pyecharts#1139]
代码存在错误，平均温度的坐标未对应温度的坐标轴。
希望开发者能够更正。

ps：请问 yaxis_index 与 extend_axis 的对应关系，目前看上去好像有点乱。。。也许是因为代码的错误，没看出来二者怎么对应的。

谢谢！

**Comment by fhhan** [comment]
我的理解是，yaxis_index=0 对应着 set_global_opts，即默认的 y 轴，然后yaxis_index=1，2，3....对用第 1，2，3...个extend_axis。

但我这样试了后，画出来图还是有问题的，不知道yaxis_index 与 extend_axis 有没有先后顺序。

希望开发者给出正确的 code，我再试试。

**Comment by chenjiandongx** [comment]
https://github.com/pyecharts/pyecharts/issues/1119

**Comment by nealchenzhang** [comment]
@fhhan yaxis_index 与 extend_axis 的对应关系你这边有解决了嘛？我这边也遇到同样的问题。。
