### ISSUE TITLE
折线图可否使用[x1,y1]这种坐标点来控制折点

### ISSUE THREAD

**Issue by calyearn** [pyecharts/pyecharts#1141]
试用了is_connect_nones这个功能，很实用，但是在实际应用中往往存在横跨多个横坐标的情况，比如横轴是时间类的数值，这样就出现了大量的None，处理起来比较麻烦，所以请问您。。。现在可以使用类似data：[[x1,y1],[x2,y2]]这种通过横纵坐标来直接控制折线图的折点这种方法吗？在文档和实例中都没有发现这种方法。真的很期待。或者是我看的有遗漏的地方，希望您能指出，真的万分感谢您的开源奉献。望您回复，谢谢。

python3.7/pyecharts1.1

**Comment by chenjiandongx** [comment]
你可以是 d = [[x1,y1],[x2,y2]], 然后在 X 轴传 [x[0] for x in d],Y 轴传 [x[1] for x in d]

是这个意思？

**Comment by calyearn** [comment]
啊 我才看到 太不好意思了。。。对的 就是您说的这个意思

**Comment by calyearn** [comment]
> 你可以是 d = [[x1,y1],[x2,y2]], 然后在 X 轴传 [x[0] for x in d],Y 轴传 [x[1] for x in d]
> 
> 是这个意思？
是的  就是您这个意思 我才看到 太抱歉了。。。

**Comment by sunhailin-Leo** [comment]
@calyearn 
* Why not ?, Please check it and try it.
![image](https://user-images.githubusercontent.com/17564655/71862466-ef3c7a80-3134-11ea-9e53-d9a01ace4e81.png)
```python
from pyecharts.charts import Line
from pyecharts import options as opts

d = [[1, 10], [2, 20], [3, 30]]

c = (
    Line()
    .add_xaxis([x[0] for x in d])
    .add_yaxis("数据项", [x[1] for x in d])
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Line-Example"),
        xaxis_opts=opts.AxisOpts(type_="value"),
        yaxis_opts=opts.AxisOpts(type_="value"),
    )
    .render()
)
```
