### ISSUE TITLE
MarkPointOpts对不同的标记点进行设置

### ISSUE THREAD

**Issue by foolcage** [pyecharts/pyecharts#1144]
**问题**

- MarkPointOpts中设置data，只看到设置MarkPointItem列表的例子，dict的格式是怎么样的？ 

- MarkPointOpts里面可以设置symbol和symbol_size，MarkPointItem也可以设置，似乎只有一个起效？MarkPointItem设置不了颜色，想显示不同颜色可以做到吗？

嗯，就是想对不同的MarkPointItem进行设置。。

**运行环境（系统环境及 pyecharts 版本）**
mac pro
py 3.6
pyecharts 1.1.0

**Comment by sunhailin-Leo** [comment]
@foolcage 
* `dict` 的格式可以根据 `Echarts` 官方进行设计，目前 `pyecharts` 还没有完全覆盖 `Echarts` 的所有配置(https://www.echartsjs.com/option.html#series-line.markPoint.data)

**Comment by foolcage** [comment]
@sunhailin-Leo 
看起来按dict把ItemStyleOpts设置进去也没有效果?

**Comment by chenjiandongx** [comment]
可调整 MarkPoint Symbol 大小
```
def line_markpoint() -> Line:
    from pyecharts.globals import SymbolType
    c = (
        Line()
        .add_xaxis(Faker.choose())
        .add_yaxis(
            "商家A",
            Faker.values(),
            markpoint_opts=opts.MarkPointOpts(data=[opts.MarkPointItem(type_="min", symbol=SymbolType.ARROW)]),
        )
        .add_yaxis(
            "商家B",
            Faker.values(),
            markpoint_opts=opts.MarkPointOpts(data=[opts.MarkPointItem(type_="max", symbol=SymbolType.DIAMOND)]),
        )
        .set_global_opts(title_opts=opts.TitleOpts(title="Line-MarkPoint"))
    )
    return c
```

**Comment by foolcage** [comment]
@chenjiandongx 
多谢,dict就完全按照echarts的json结构来弄了.

**Comment by NorthBig** [comment]
> * https://www.echartsjs.com/option.html#series-line.markPoint.data

恩，我也是正在琢磨这个问题。如果是data类型是opts.markpointitem，只能是一个坐标也就是一个点。data类型是序列比如dict的话，不起作用，哪怕我把数据格式变成字典，跟例子一模一样都不行。所以，另外的办法就是做：做散点图，只能主图overlap叠加！好像这挺有用的，并且散点图的数据X轴不用跟主图X轴一样的，即空值不用摆在X的列表里面。
