### ISSUE TITLE
通过CMD中Python -m pydoc的帮助文档查询显示Line实例对象中的add_yaxis函数没有itemstyle_opts参数，但是中文帮助文档中有这个参数

### ISSUE THREAD

**Issue by zxc-7** [pyecharts/pyecharts#1147]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@zxc-7 认真看看？[Line 图文档](https://pyecharts.org/#/zh-cn/rectangular_charts?id=line%EF%BC%9A%E6%8A%98%E7%BA%BF%E9%9D%A2%E7%A7%AF%E5%9B%BE)
