### ISSUE TITLE
mark_point传进去的name不能正常显示

### ISSUE THREAD

**Issue by liuhuanshuo** [pyecharts/pyecharts#1148]
比如官方的demo中
`from pyecharts import Line

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 10, 100]
v2 = [55, 60, 16, 20, 15, 80]

line = Line("折线图示例")
line.add(
    "商家A",
    attr,
    v1,
    mark_point=["average", {"coord": ["裤子", 10], "name": "这是我想要的第一个标记点"}],
)
line.add(
    "商家B",
    attr,
    v2,
    is_smooth=True,
    mark_point=[{"coord": ["袜子", 80], "name": "这是我想要的第二个标记点"}]
)
line.render('shili.html')`

但是不会显示“这是我想要的第二个标记点文字”

![image](https://user-images.githubusercontent.com/36214014/58542669-961c7800-8230-11e9-9dcb-2e8f24533be5.png)

只会显示衬衫两个字
好像不管怎么样设置name或者不设置name字段显示的都是横坐标名字
查看的源码里面确实显示可以传入name字段
![image](https://user-images.githubusercontent.com/36214014/58542893-f14e6a80-8230-11e9-83a7-0851784b4d3d.png)

**Comment by chenjiandongx** [comment]
0.5.x 的版本开发团队已不再维护 有问题的话需要自行解决
