### ISSUE TITLE
极坐标坐标轴在数据下方显示不出来

### ISSUE THREAD

**Issue by roy668899** [pyecharts/pyecharts#1151]
**问题**
极坐标坐标轴在数据下方显示不出来，尤其是柱状堆叠图，看不到类标签
请问有解决方法吗？在文档中没有找到

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![图片](https://user-images.githubusercontent.com/51205455/58643907-cea47a80-8332-11e9-9f33-55d73f1f2cb3.png)

**Comment by roy668899** [comment]
用的v1版本pyecharts

**Comment by roy668899** [comment]
对了，文档里也是这样的lol
![图片](https://user-images.githubusercontent.com/51205455/58644483-edefd780-8333-11e9-981a-5dbbcb567880.png)

**Comment by chenjiandongx** [comment]
```python
.add_schema(radiusaxis_opts=opts.RadiusAxisOpts(data=Faker.week, type_="category", z=10) -< 设置 z=10
```

**Comment by roy668899** [comment]
感谢感谢 @chenjiandongx
