### ISSUE TITLE
新版地图不显示地图数字

### ISSUE THREAD

**Issue by skenoy** [pyecharts/pyecharts#1154]
**问题**
新版地图不显示地图数据

> "data": [
                {
                    "name": "\u4e0a\u6d77",
                    "value": null
                },
                {
                    "name": "\u5e7f\u4e1c",
                    "value": null
                },
      .......

**运行环境（系统环境及 pyecharts 版本）**
windows
python 3.7
pycharm
pyehcarts 1.1

**代码及截图**
`from pyecharts.charts import Map
from pyecharts import options as opts
m = Map()
m.add("", [list(z) for z in zip(list(dist.index), list(dist.values))], 'china')\
    .set_global_opts(visualmap_opts=opts.VisualMapOpts(max_=800,range_color=["lightskyblue", "yellow", "orangered"]))
m.render('aaa.html')`

`[list(z) for z in zip(list(dist.index), list(dist.values))]`
这样是有结果的
> [['上海', 751],
 ['广东', 618],
 ['江苏', 591],
 ['浙江', 579]]

**Comment by skenoy** [comment]
> from pyecharts.charts import Map
from pyecharts import options as opts
m = Map()
m.add("", [list(z) for z in zip(list(dist.index), list(dist.values))], 'china')\
    .set_global_opts(visualmap_opts=opts.VisualMapOpts(max_=800,range_color=["lightskyblue", "yellow", "orangered"]))
m.render('shenghuiHM.html')

**Comment by sunhailin-Leo** [comment]
可以尝试新版本的代码。如果依旧出现该问题，请重新提 issue 并附上你的代码，thx～

**Comment by wqwangchn** [comment]
同样的问题，1.6.2版本。依旧出现该问题

**Comment by sunhailin-Leo** [comment]
@wqwangchn 
* Show my your code
