### ISSUE TITLE
折线图堆叠时markpoint无法跟随stack一起堆叠

### ISSUE THREAD

**Issue by roy668899** [pyecharts/pyecharts#1156]
**问题**
折线图堆叠时markpoint无法跟随stack一起堆叠，仍然停留在未堆叠时的位置。
是否有解决方法呢？

**运行环境（系统环境及 pyecharts 版本）**
V1

**代码及截图**
![图片](https://user-images.githubusercontent.com/51205455/58688267-95155300-83b6-11e9-8527-3f02d5d1461a.png)
![图片](https://user-images.githubusercontent.com/51205455/58688287-a199ab80-83b6-11e9-871b-f800d5ba82db.png)

**Comment by roy668899** [comment]
btw:
文档中有一些小错误
![图片](https://user-images.githubusercontent.com/51205455/58689220-01915180-83b9-11e9-8ca3-55ff62549f83.png)

**Comment by chenjiandongx** [comment]
1. 你的需求目前无法实现
2. 文档已修复
