### ISSUE TITLE
Gauge 无法设置 Label

### ISSUE THREAD

**Issue by chenjiandongx** [pyecharts/pyecharts#1157]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by CaoChensy** [comment]
Pyecharts==1.1.0

<img width="1076" alt="屏幕快照 2019-05-31 17 03 36" src="https://user-images.githubusercontent.com/31162834/58694774-67d0a100-83c6-11e9-9949-fa378313c817.png">

**Comment by chenjiandongx** [comment]
#1158
