### ISSUE TITLE
'DataZoomOpts' object is not iterable

### ISSUE THREAD

**Issue by refraction-ray** [pyecharts/pyecharts#1161]
**问题**
`line.set_global_opts(datazoom_opts=DataZoomOpts(is_show=True, type_="slider"))` 会报错 

```
--> 151             for dz in datazoom_opts:
    152                 if not dz:
    153                     continue
TypeError: 'DataZoomOpts' object is not iterable
```
改为 `line.set_global_opts(datazoom_opts=[DataZoomOpts(is_show=True, type_="slider")])` 即可正常运行（也即用 list 包起来）。
但其他 global option 则
`line.set_global_opts(title_opts=TitleOpts(title="My title"))` 即可正常运行，也即参数不需要是 iterable。相反在 title opts 参数上包了 list 反而渲染的图片不显示标题。所以 datazoom opts 要求 iterable 应该不是 feature，是个 bug？

**运行环境（系统环境及 pyecharts 版本）**

MacOS 10.14 + Python 3.6.3 + Pyecharts 1.1.0 (`git checkout v1.1.0` instead of pip install)

**Comment by sunhailin-Leo** [comment]
@refraction-ray 你这个问题..., 能看 Type Hints 吗？

**Comment by sunhailin-Leo** [comment]
![image](https://user-images.githubusercontent.com/17564655/58743489-014e9000-8465-11e9-86f1-b1f9d09f8486.png)

**Comment by refraction-ray** [comment]
> @refraction-ray 你这个问题..., 能看 Type Hints 吗？

抱歉 刚看到，只有这个选项是 sequence，不知道这个 feature 的场景是

**Comment by sunhailin-Leo** [comment]
@refraction-ray 了解一下 [PEP 484](https://www.python.org/dev/peps/pep-0484/) 以及 Type Hints 的 Sequence

**Comment by refraction-ray** [comment]
> @refraction-ray 了解一下 [PEP 484](https://www.python.org/dev/peps/pep-0484/) 以及 Type Hints 的 Sequence

我当然知道 type hints... 我是想了解这里为什么只有这个选项可以接受多组配置，其可能的场景是什么。还有就是似乎现在文档里没有提到 set global option 有些选项的指定是 sequence of object 而非单个 object?

**Comment by sunhailin-Leo** [comment]
@refraction-ray 这个理解很简单，最基本的直角坐标系的图有几个轴？ X /  Y 对吧～那么这就有两种可能的，所以你有可能需要配置两个 DataZoom～ （其他的以此类推）

**Comment by chenjiandongx** [comment]
@refraction-ray 你的疑惑我理解，我已经修复了这个问题，下个版本开始允许传入

```
datazoom_opts=DataZoomOpts(is_show=True, type_="slider")
# 或者 
datazoom_opts=[DataZoomOpts(is_show=True, type_="slider")]
```
