### ISSUE TITLE
PYECHARTS1.0.0版如何设置LEGEND,因为我的图例较多,我想让它能竖着排在图的右边,最好能够滚动

### ISSUE THREAD

**Issue by helaoding** [pyecharts/pyecharts#1167]
**问题**
PYECHARTS1.0.0版如何设置LEGEND,因为我的图例较多,我想让它能竖着排在图的右边,最好能够滚动

**运行环境（系统环境及 pyecharts 版本）**

pyecharts1.0.0版

**代码及截图**

**Comment by helaoding** [comment]
PYECHARTS1.0.0版如何设置LEGEND,因为我的图例较多,我想让它能竖着排在图的右边,最好能够滚动

**Comment by sunhailin-Leo** [comment]
@helaoding `LegendOpts` 设置 `type` 为 `scroll`，`orient` 设置为 `vertical`, 剩下就是设置位置了。

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/58845102-78c23080-86ac-11e9-940e-2edbff7ad827.png)
