### ISSUE TITLE
生成table类型的html需要带echarts.min.js，否则snapshot-selenium保存图片报错

### ISSUE THREAD

**Issue by aosie** [pyecharts/pyecharts#1170]
**问题**
步骤：
1： 使用pyecharts生成table类型的html
2：使用snapshot_selenium模块生成图片
报错：
selenium.common.exceptions.JavascriptException: Message: javascript error: echarts is not defined
原因：
snapshot_selenium/snapshot.py中 必须要指定运行echarts.js。SNAPSHOT_JS中含用 var mychart = echarts.getInstanceByDom(ele);

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

![snapshot](https://user-images.githubusercontent.com/28146761/58947477-98e01580-87ba-11e9-9987-5a498bed6e5e.jpg)

**Comment by chfw** [comment]
有道理

**Comment by chenjiandongx** [comment]
Table、Image 类目前并不支持 snapshot!

**Comment by aosie** [comment]
了解，thx

**Comment by ly20119** [comment]
> Table、Image 类目前并不支持 snapshot!

请问Table和Image有计划支持snapshot吗？会在什么时候呢？目前使用的1.5版本，好像还是不支持的。

**Comment by wyxsky** [comment]
请问Table和Image有计划支持snapshot吗？会在什么时候呢？目前使用的1.81版本，好像还是不支持的。
