### ISSUE TITLE
新版本如何设置图背景的大小

### ISSUE THREAD

**Issue by liangmengmeng1993** [pyecharts/pyecharts#1171]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@liangmengmeng1993 
* 目前版本可以在画图的后面插入图片了，也有相关的 example 了。
* 背景图随画布大小变化而变化的，分为水平重复，垂直重复和不重复三个模式。
* 具体的配置：https://echarts.baidu.com/option.html#backgroundColor
* 具体的示例：https://github.com/pyecharts/pyecharts/blob/master/example/bar_example.py#L43
