### ISSUE TITLE
如何在柱状图的柱子上显示标签

### ISSUE THREAD

**Issue by lemonNoNioi** [pyecharts/pyecharts#1178]
**问题**
当柱状图的x轴标签过长时，文档建议将标签旋转一定的角度，但有时标签实在太长无法正常显示；
考虑到可以将x轴y轴翻转，然后在横向的柱子上显示标签，不知道如何实现，有大佬能指点一下吗。
类似如下效果：
[https://i.bmp.ovh/imgs/2019/06/a8fa6057def5888e.png](https://i.bmp.ovh/imgs/2019/06/a8fa6057def5888e.png)

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@lemonNoNioi 
![image](https://user-images.githubusercontent.com/17564655/60799552-f0044c00-a1a5-11e9-83c5-dff654f03804.png)

**Comment by sunhailin-Leo** [comment]
* 部分代码
```python
def bar_reversal_axis() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .reversal_axis()
        .set_series_opts(label_opts=opts.LabelOpts(position="insideRight", formatter="{b}"))
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-翻转 XY 轴"))
    )
    return c
```

**Comment by lemonNoNioi** [comment]
> * 部分代码
> 
> ```python
> def bar_reversal_axis() -> Bar:
>     c = (
>         Bar()
>         .add_xaxis(Faker.choose())
>         .add_yaxis("商家A", Faker.values())
>         .reversal_axis()
>         .set_series_opts(label_opts=opts.LabelOpts(position="insideRight", formatter="{b}"))
>         .set_global_opts(title_opts=opts.TitleOpts(title="Bar-翻转 XY 轴"))
>     )
>     return c
> ```

是这样，非常感谢！
