### ISSUE TITLE
安装没有问题，import 出错

### ISSUE THREAD

**Issue by sherry9393** [pyecharts/pyecharts#1182]
**代码及截图**

![image](https://user-images.githubusercontent.com/41997508/59182534-9a378680-8b9c-11e9-807b-36c3528639a4.png)
![image](https://user-images.githubusercontent.com/41997508/59182621-ca7f2500-8b9c-11e9-9996-a561e9fb2f6f.png)

**Comment by chfw** [comment]
请用一python 3.6以上版本
