### ISSUE TITLE
堆叠柱状图中修改y轴范围的问题

### ISSUE THREAD

**Issue by CapAllen** [pyecharts/pyecharts#1183]
**问题**
目的：绘制堆叠柱状图，并缩小Y轴取值范围

数据示例：
![图片](https://user-images.githubusercontent.com/35265537/59185057-16809880-8ba2-11e9-94b8-338a6717ad0c.png)

代码：
```python
def bar_stack0(counts, title, rotate=60):
    attr = [index for index in counts.index]
    v1 = [value[0] for value in counts.values]
    v2 = [value[1] for value in counts.values]
    yaxis_min=v1[-1] - 50,
    yaxis_max=v1[0] + v2[0] + 50
    c = (
        Bar()
        .add_xaxis(attr)
        .add_yaxis("", v1,stack='afaf')
        .add_yaxis("", v2,stack='afaf')
        .set_series_opts(label_opts=opts.LabelOpts(is_show=True))
        .set_global_opts(title_opts=opts.TitleOpts(title=title),
                         xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=rotate,font_size=8)),
                        yaxis_opts=opts.AxisOpts(splitline_opts=opts.SplitLineOpts(is_show=True),min_=yaxis_min,max_=yaxis_max))
    )
    return c
```

结果：
![图片](https://user-images.githubusercontent.com/35265537/59185099-30ba7680-8ba2-11e9-8814-d1ee8b596a46.png)

之后我又尝试了几个`min_`值，
`min_=50`的时候
![图片](https://user-images.githubusercontent.com/35265537/59185429-05845700-8ba3-11e9-8b3d-3fb3d0698ddb.png)

`min_=100`的时候
![图片](https://user-images.githubusercontent.com/35265537/59185454-13d27300-8ba3-11e9-9ede-ae37b55997f7.png)

发现在修改y轴取值范围后，堆叠图中上面的柱子（范围在600-610）的取值范围变为了(`610 - min_`,`600`)，emmmm，求助各位大佬哇！

**运行环境（系统环境及 pyecharts 版本）**
Windows7
pyecharts1.1.0

**Comment by sunhailin-Leo** [comment]
可以尝试新版本的代码。如果依旧出现该问题，请重新提 issue 并附上你的代码，thx～
