### ISSUE TITLE
MarkLineItem 的 name 选项不生效

### ISSUE THREAD

**Issue by yonah27** [pyecharts/pyecharts#1187]
** MarkLineItem 的 name 选项不生效**

**运行环境（系统环境及 pyecharts 版本）**
MacOS + python3.7 + pycharts1.2.0

**代码及截图**

Line()
        .add_xaxis(x_list)
        .add_yaxis(
            'price', 
            y__list, 
            is_symbol_show=False,
            linestyle_opts={'width':4},
            markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(type_="average",name="均值")]),
        )
![image](https://user-images.githubusercontent.com/1853192/59282962-5c218c00-8c9c-11e9-893a-72f6a9f89489.png)

**Comment by yonah27** [comment]
看官方的例子，好像name参数也没有生效？？？
![image](https://user-images.githubusercontent.com/1853192/59283419-1dd89c80-8c9d-11e9-9832-db41f6ff3945.png)

**Comment by sunhailin-Leo** [comment]
@yonah27 你是要显示 name 的字嘛？
![image](https://user-images.githubusercontent.com/17564655/59825696-55170f80-9367-11e9-946a-f0f109e7e694.png)

* 把 LabelOpts 的 is_show 设成 True 就好了

**Comment by yonah27** [comment]
> @yonah27 你是要显示 name 的字嘛？
> ![image](https://user-images.githubusercontent.com/17564655/59825696-55170f80-9367-11e9-946a-f0f109e7e694.png)
> 
> * 把 LabelOpts 的 is_show 设成 True 就好了

在我的代码里面，我是在 .add_yaxis 里面设置了 markline_opts。再加一个label_opts，没能生效。
