### ISSUE TITLE
官方文档案例中一处代码错误，Flask前后端分离部分

### ISSUE THREAD

**Issue by dongzide** [pyecharts/pyecharts#1189]
https://pyecharts.org/#/zh-cn/web_flask?id=step-4-%E7%BC%96%E5%86%99-flask-%E5%92%8C-pyecharts-%E4%BB%A3%E7%A0%81%E6%B8%B2%E6%9F%93%E5%9B%BE%E8%A1%A8

`@app.route("barChart")`这句需改为`@app.route("/barChart")`，否则报错 `ValueError: urls must start with a leading slash`

所有库都是最新版本

**Comment by chenjiandongx** [comment]
#1208
