### ISSUE TITLE
官方文档的百度地图示例在notebook下无法显示

### ISSUE THREAD

**Issue by dongzide** [pyecharts/pyecharts#1191]
**问题**
官方文档代码位置：https://pyecharts.org/#/zh-cn/geography_charts?id=demo-2
根据官方文档代码执行百度地图示例，同样代码生成静态HTML文件正常显示，在jupyter notebook内则显示空白

具体描述：
如果baidu ak为随便写的错误值则HTML和notebook都可正常显示图像，只是会提示ak错误
但我把ak改为申请的 浏览器端 ak，notebook就不显示图像了

代码：

```python
import json
import os

from example.commons import Collector, Faker
from pyecharts import options as opts
from pyecharts.charts import BMap, Page
from pyecharts.globals import BMapType

BAIDU_AK = "aaa"  # 错误值可显示，改为正确的 浏览器端 ak，则notebook不显示图像

def bmap_base() -> BMap:
    c = (
        BMap()
        .add_schema(
            baidu_ak=BAIDU_AK,
            center=[120.13066322374, 30.240018034923],
        )
        .add(
            "bmap",
            [list(z) for z in zip(Faker.provinces, Faker.values())],
            label_opts=opts.LabelOpts(formatter="{b}"),
        )
        .set_global_opts(title_opts=opts.TitleOpts(title="BMap-基本示例"))
    )
    return c

bmap_base().render_notebook()
```

**运行环境（系统环境及 pyecharts 版本）**
python 3.6
pyecharts 1.1.0
jupyter notebook 5.7.8

**Comment by chenjiandongx** [comment]
python 3.7
pyecharts 1.2.0
jupyter notebook 5.7.4

测试没问题

**Comment by dongzide** [comment]
@chenjiandongx ,你的baidu ak 是 浏览器端 ak 吗？用我代码里的瞎写ak，是能正常显示的，但执行时会弹窗提示ak不对，如果用申请的 百度 ak 则在notebook下无法正常显示

**Comment by chenjiandongx** [comment]
嗯 是浏览器端

**Comment by dongzide** [comment]
@chenjiandongx 我找到bug的原因了，
如果我在notebook中第一次运行此代码时，使用了错误的 ak，如 服务端ak，此时notebook会输出空白，然后无论我再怎么做页面也无法恢复正常了，包括重启notebook内核，改用正确的 浏览器端ak，都不行。

必须把notebook网页关闭一下，再次打开（不用关闭内核只是关闭页面），显示才会正常。

推测这个问题产生的原因和网页的浏览器客户端HTML缓存有关，执行Python代码后，错误的js代码会一直存在无法被正确值替换，于是一次错误后，除非重新打开（刷新）notebook网页，否则不会加载正确的pyecharts前端代码。

一个比较诡异的错误，不确定算不算bug，估计很难改，放这里供大家参考

**Comment by chfw** [comment]
@dongzide , notebook 有个讨厌的习惯，就是 cache 你现在的 notebook 。 如果你输入了一个错误的渲染，想刷新就必须，重启 notebook，然后重新开另外一个 notebook ，把你的代码拷贝过去，一定能成功。

或者，去拿杯咖啡，等 10 分钟，再继续。

**Comment by PandelNJU** [comment]
@dongzide 我用vscode的jupyter也遇到了这个问题，重启或者重开也没解决...
