### ISSUE TITLE
pyecharts生成的图表HTML能否插入PPT中？尝试了一些方法都不行，据说官方有插件

### ISSUE THREAD

**Issue by dongzide** [pyecharts/pyecharts#1193]
pyecharts生成的动态图表HTML，想插入PPT中，尝试了很多方法

* 使用PPT的应用商店插件动态载入网页
    * 缺点：只支持https访问的网页，pass
* 修改注册表在PPT中插入网页浏览器加载项，然后加载网页
    * 缺点：需要给插入控件写vb代码，写了后执行老报错，解决不了（而且据说就算成功PPT的浏览器是基于IE的，Echarts使用有问题）
* PPT插入Flash，Flash载入网页
    * 缺点：同样需要修改注册表才能用，太麻烦放弃

我查Echarts官方说有PPT插件可以直接将图表插入PPT：见网页描述

https://vis.baidu.com/

可搜了半天也没找到这个PPT插件在哪儿，有高人知晓么？

**Comment by sunhailin-Leo** [comment]
@dongzide  PPT 插件这个东西我好早之前就看到 Echarts 那里有了，不过至今都没有。 pyecharts 肯定也是不支持的目前，因此只能等到 Echarts 出了 PPT 的插件才能进行开发。 😄

**Comment by sunhailin-Leo** [comment]
@dongzide 目前的解决办法只有添加本地的超链接

**Comment by jesoonluo** [comment]
为啥是html插入ppt而不是图片插入ppt，这需求有点奇怪

**Comment by luzwales** [comment]
我昨天试了，能用PPT用插入控件microsoft web brownser可以，但是插入后显示提示Javacript错误，pyechart图不能完全显示，能看到坐标轴，看不到具体数。不知道咋回事

**Comment by luzwales** [comment]
> 为啥是html插入ppt而不是图片插入ppt，这需求有点奇怪

图片是PNG格式，是死的，我们的Echart要求有交互性，动态的，图片能做到？

**Comment by chenjiandongx** [comment]
我觉得还是放弃这个想法吧，毕竟这不是不是 Echarts 官方的需求点。
