### ISSUE TITLE
报告官方文档错误，百度地图的demo代码没有载入外部库

### ISSUE THREAD

**Issue by dongzide** [pyecharts/pyecharts#1194]
https://pyecharts.org/#/zh-cn/geography_charts?id=demo-2

官网文档别的demo都有import载入对应资源，但百度地图的demo没有import入外部资源，导致代码执行错误。建议修改

**Comment by sunhailin-Leo** [comment]
可以尝试新版本的代码。如果依旧出现该问题，请重新提 issue 并附上你的代码，thx～
