### ISSUE TITLE
文档FLASK对接部分DEMO运行报错

### ISSUE THREAD

**Issue by zeagkit** [pyecharts/pyecharts#1195]
**问题**
https://pyecharts.org/#/zh-cn/web_flask?id=step-2-%E6%B8%B2%E6%9F%93%E5%9B%BE%E8%A1%A8

其中
@app.route("/")
def index():
    c = bar_base()
    return Markup(c.render_embed())
运行报错：
'Bar' object has no attribute 'render_embed'
了解到1.0.0版本应该是已经取消了c.render_embed()这个接口，建议修改。

**运行环境（系统环境及 pyecharts 版本）**
版本：1.0.0

**Comment by chenjiandongx** [comment]
#1208
