### ISSUE TITLE
添加自定义坐标出问题

### ISSUE THREAD

**Issue by fengguangbin** [pyecharts/pyecharts#1196]
**问题**
在使用add_coordinate方法 添加的自定义坐标之后，导致每个坐标的纬度都会显示出来到标签上，然后用label_opts=opts.LabelOpts(is_show=False)来关闭标签的输出，也没作用。在查看echarts的官网后，发现echarts上有formatter='{a}'这么一个参数控制显示的标签，但是在多次修改之后还是没有效果，希望能给一点间解。

**运行环境（系统环境及 pyecharts 版本）**
Windows == 7
![微信图片_20190614173530](https://user-images.githubusercontent.com/29656382/59499944-0979e700-8ecb-11e9-925a-d2acad2fb9b6.png)

Python == 3.7.0
pyecharts == 1.2.0

**代码及截图**
![微信图片_20190614173530](https://user-images.githubusercontent.com/29656382/59499955-0f6fc800-8ecb-11e9-8a27-73d47b43f0fd.png)

**Comment by swuecho** [comment]
https://github.com/ecomfe/vue-echarts/pull/349/files

js 里面

```
 label: {
        normal: {
          formatter: '{b}',
          position: 'right',
          show: false
        },
```

如果想不显示，试试 `normal =  {show: False}`
想显示，改formatter的格式。

之前前段画图的时候遇到这么个bug， tooltip 默认显示纬度。

**Comment by fengguangbin** [comment]
@swuecho 好的，谢谢你给的建议，我尝试下在输出的html文件中修改js。

**Comment by chfw** [comment]
```
        .add(
            "",
            [("Place A", 55), ("Place B", 66)],
            type_=ChartType.EFFECT_SCATTER,
            color="red",
            label_opts=opts.LabelOpts(formatter="{b}") # <---------------<<
        )
```
