### ISSUE TITLE
Django中使用JSCode的问题

### ISSUE THREAD

**Issue by Zhang0513** [pyecharts/pyecharts#1198]
**问题**
Django前后端分离的时候，想使用jscode。

function getData(url,chart) {
    $.ajax({
        type: "GET",
        url:url,
        dataType: 'json',
        success: function (result) {
            chart.setOption(result.data);
        }
    });
}

但是，这里接受的是json，传递到 chart.setOption(result.data);内部的时候变成"function (xx){xxx}"，是字符串，不是函数，请问这有解决方法吗？
简单的说：json键值对为str对str，但是我想要的是str对function。否则无法实现函数功能的。
ps:
   chart.setOption(result.data); 在这一步之前，我们需要手动设置 将str转成function

**运行环境（系统环境及 pyecharts 版本）**

- 

**代码及截图**

**Comment by saebaxp** [comment]
我也遇到过同样问题。
通过如下手段解决：
1. 去掉dataType: 'json',
2. success这样写：
                success: function (result) {
                    var re_obj = (new Function("return " + result))();
                    chart.setOption(re_obj);
                }
其实原因就是出在有function 的情况下，dump_options()出来的字符串无法成功被转换成json.
这里通过直接把它做成object而不经过json就解决了这个问题。

吐槽一下，这么多年了json居然还没法优雅的接受非基本类型。。。

另， 建议pyecharts官方文档的<Flask 前后端分离>Step 3的地方相应更新一下。
要不大家都得先踩坑。

**Comment by saebaxp** [comment]
另外，你说的[内部的时候变成"function (xx){xxx}"]，恐怕是因为在python里传js function时没有用
utils.JsCode()转换吧。

应该用这样的形式：
tooltips="""function (params){
return something;
}"""

Bar3D(...)
.set_global_opts(
    tooltip_opts=opts.TooltipOpts(formatter=utils.JsCode(tooltips)),
)

**Comment by Zhang0513** [comment]
> 
> 
> 另外，你说的[内部的时候变成"function (xx){xxx}"]，恐怕是因为在python里传js function时没有用
> utils.JsCode()转换吧。
> 
> 应该用这样的形式：
> tooltips="""function (params){
> return something;
> }"""
> 
> Bar3D(...)
> .set_global_opts(
> tooltip_opts=opts.TooltipOpts(formatter=utils.JsCode(tooltips)),
> )
简单的说明一下：
1.jscode在render方式中是可行的，在django是不可行的。原因很简单，django前后端分离，使用json传递数据，键值对是 str:str，并不是str:function，所以和用不用jscode转无关的。
2.想要实现功能，success: function (result) {} 要在这里面做二次处理，也就是（可百度-->“js str转function”)或者直接看@sunhailin-Leo 给出的方式。
3.jscode其实只是将字符串前后包裹了标识符。本质还是str。
4.我提这个问题，本来目的是为了让大家知道这个情况，看看有没有完美的解决方法，现在最好的解决方式是二次转换。
5.你提供的方式：
‘去掉dataType: 'json',
success这样写：xxx’
我这边没有成功 QAQ

![TIM图片20190703160525](https://user-images.githubusercontent.com/42483329/60574589-6838cf00-9dac-11e9-8491-a7deeec2d98b.jpg)

**Comment by saebaxp** [comment]
是我写的太简化了。。。

我用的是Flask前后端分离。

后端：
在Flask的app.py里生成chart的时候，用utils.JsCode(tooltips)包装formatter，
这样dump_options()出来的是含有str:function形式的“疑似”json字串，
然后直接返回这个字串，注意这里不要做任何json转换，因为带有str:function形式的根本就不是json

前端：
$.ajax里不要指定dataType: 'json'， 因为我们要的就是上面后端传过来的原始的含有str:function的字串。（这里如果指定了dataType: 'json'， 会因为转换json失败根本就进不了success: function）
在success: function里把这个字串直接转为object：
var re_obj = (new Function("return " + result))();
然后就可以chart.setOption(re_obj);

总之，后端前端不要和json发生任何关系（就不会变成str:str形式的），就没有必要做二次处理了。
我觉得这是最简洁的办法了，没有任何多余处理。

当然我这是基于Flask，不知道django里是否必须经过json这一步。

**Comment by Zhang0513** [comment]
> 总之，后端前端不要和json发生任何关系（就不会变成str:str形式的了），就没有必要做二次处理了。
> 我觉得这是最简洁的办法了，没有任何多余处理。
> 
> 当然我这是基于Flask，不知道django里是否必须经过json这一步。

刚刚我看了flask的demo使用方法。再step4中是这样写的。
`
@app.route("/barChart")
def get_bar_chart():
    c = bar_base()
    return c.dump_options()
`
你可以看一下django的demo中Step 3: 编写 Django 和 pyecharts 代码渲染图表。
`class ChartView(APIView):
    def get(self, request, *args, **kwargs):
        return JsonResponse(json.loads(bar_base()))
`
感觉是有区别的。
ps:
 再1.21版中，你flask使用jscode会异常吗，会报jsonerror？

**Comment by saebaxp** [comment]
1.2.1版，后端直接返回utils.JsCode(tooltips)包装后的带str:function的“疑似”json字串时，
前端$.ajax如果指定dataType: 'json'，像这样:
                dataType: 'json',
                success: function (result) {
                    var re_obj = (new Function("return " + result))();
                    chart.setOption(re_obj);
                },
                error: function(XMLHttpRequest, textStatus, errorThrown){
                    console.log("Error: "+errorThrown.message);
                }
会在控制台输出：
Error: JSON Parse error: Unexpected identifier "function"

在Django里，如果不用JsonResponse包装而是像下面这样直接返回dump_options()的结果会怎么样？
class ChartView(APIView):
    def get(self, request, *args, **kwargs):
        return bar_base()

**Comment by Zhang0513** [comment]
> 或者是HttpResponse(bar_base())?
> 反正就是让它传回原始的字串，而不是经过json


1. django中不能直接返回dump_options()，因为没有封装HttpResponse，会返回500的状态码。

2.使用HttpResponse(bar_base())，
```
$.ajax({
        type: "GET",
        url: url,
       dataType: 'json',
        success: function (result) {
            console.log(typeof (result)); // 输出string
            console.log(result);//{ "color": [  "#c23531",......}
           chart.setOption(result);
        }
    });

```
使用了jscode 就会出现，不使用jscode就不会出现下面的异常。

TypeError: cannot use 'in' operator to search for '' in '{
    "color": [...' echarts.min.js:22:313198

3.有个不成熟的想法，
 return HttpResponse(bar_base(),content_type="text/plain")能不当作script传递
.ajax {
  dataType: 'script',
？？？？
}
4.再研究研究吧。挺有意思的。-.-

**Comment by saebaxp** [comment]
早上有点时间现学了下django，一样的思路，成功实现了。
只贴和官方demo中不一样的地方。

后端：
def bar_base() -> Bar:
    tooltips = """function (param){
    return 'aaa';
    }
    """
    c = (
        Bar()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [randrange(0, 100) for _ in range(6)])
        .add_yaxis("商家B", [randrange(0, 100) for _ in range(6)])
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"),
            tooltip_opts=opts.TooltipOpts(formatter=utils.JsCode(tooltips)),   #这里一定要用JsCode包装
            )
        .dump_options()
    )
    return c

class ChartView(APIView):
    def get(self, request, *args, **kwargs):
        # return JsonResponse(json.loads(bar_base())) #一定不要用Json
        return HttpResponse(bar_base())   #用Http直接传

前端：
            $.ajax({
                type: "GET",
                url: "http://127.0.0.1:8000/demo/bar",
                //dataType: 'json',      //一定不要指定json！！！！
                success: function (result) {
                    var re_obj = (new Function("return " + result))();   //把传来的字串直接转成object
                    chart.setOption(re_obj);    //用object来setoption
                    //chart.setOption(result.data);   //不要用这个
                }
            });

**Comment by Zhang0513** [comment]
> 或者是HttpResponse(bar_base())?
> 反正就是让它传回原始的字串，而不是经过json


1. django中不能直接返回dump_options()，因为没有封装HttpResponse，会返回500的状态码。

2.使用HttpResponse(bar_base())，
```
$.ajax({
        type: "GET",
        url: url,
       dataType: 'json',
        success: function (result) {
            console.log(typeof (result)); // 输出string
            console.log(result);//{ "color": [  "#c23531",......}
           chart.setOption(result);
        }
    });

```
使用了jscode 就会出现，不使用jscode就不会出现下面的异常。

TypeError: cannot use 'in' operator to search for '' in '{
    "color": [...' echarts.min.js:22:313198

3.有个不成熟的想法，
 return HttpResponse(bar_base(),content_type="text/plain")能不当作script传递
.ajax {
  dataType: 'script',
？？？？
}
4.再研究研究吧。挺有意思的。-.-

**Comment by Zhang0513** [comment]
> 
> 早上有点时间现学了下django，一样的思路，成功实现了。
> 只贴和官方demo中不一样的地方。
> 
非通用方法
简单粗暴，就是要注意带jscode和不带jscode写法有区别。

**Comment by saebaxp** [comment]
粗暴是粗暴了些 😄 

非通用是指什么？有什么潜在的风险吗？请指教。

还有，‘带jscode和不带jscode写法有区别’具体是指什么地方的区别？

**Comment by Zhang0513** [comment]
> 
> 
> 粗暴是粗暴了些 😄
> 
> 非通用是指什么？有什么潜在的风险吗？请指教。
> 
> 还有，‘带jscode和不带jscode写法有区别’具体是指什么地方的区别？

路子太野，不够优雅。
其实初衷想的是有没有办法，ajax不做二次转换，直接一步倒位。

我所谓的：‘带jscode和不带jscode写法有区别’是指。
1.要么不使用demo中的JsonResponse 全部直接使用HttpResponse。
```
def response_as_json(data):
    json_str = json.dumps(data)// 去掉
    response = HttpResponse(
        json_str,
        content_type="application/json", //直接使用的化 这里使用了默认的类型
    )
    response["Access-Control-Allow-Origin"] = "*"
    return response
```
2.不带jscode 可以使用JsonResponse 或者HttpResponse，带了jscode 就必须使用HttpResponse。这是一道选择题。

不够优雅😄
url: "http://127.0.0.1:8000/demo/bar",
直接再浏览器中查看， HttpResponse没有JsonResponse 好看。应该是一个字符串，一个obj吧？？HttpResponse就是一坨，不直观。

我也不是专业的，所以有什么风险我就不知道了。没经验。我是搞c++的😄

**Comment by saebaxp** [comment]
> 不够优雅😄

没错， 就是这个优雅。。。
我也是最近从使用pyecharts才开始接触现代javascript的,非常震惊于json和带function的js object notation之间竟然没法直接优雅的转换。
后来才知道这是json的定义决定的，因为它就是用于描述“数据”的一个结构。带了function的js object notation本来就不是json，不管他们长得多像。。。
而在这里一定要用json来传递option 的话，就只能把 function转成str先传过来，再二次处理根据key:value找到function再把他转换回去。这种补丁对洁癖的我简直没法忍啊。。。😄
一气之下，我不用json不就完了！😄😄😄

我有限的理解里，用http传过来的字串在前端直接转object有一定的安全风险。但是仔细想想，按json传过来之后再二次处理，其实也是有本质上同样的风险的。而且都可以用同样的过滤来解决。
不知道有没有高人能指点一下有没有其他的风险。

> HttpResponse就是一坨，不直观。

完全同意😄

**Comment by LuhengStat** [comment]
@saebaxp @Zhang0513 Thanks. Using your idea, the problem has finally been solved. Great.

**Comment by an-orange-cat** [comment]
请问上面提到的问题，官方有正式的解决方法吗？
我现在也遇到了，例如 `formatter=JsCode("funtion(x) {console.log(x); return x;}"),`，但网页上只是将其作为字符串打印出来。
麻烦了~谢谢~

**Comment by Zhang0513** [comment]
很抱歉，我不是官方，我当时遇到了这个问题，就提出来了。发自我的iPhone------------------ 原始邮件 ------------------发件人: orangecat  ***@***.***>发送时间: 2023年12月5日 16:30收件人: pyecharts/pyecharts ***@***.***>抄送: Zhang0513 ***@***.***>, Mention ***@***.***>主题: Re: [pyecharts/pyecharts] Django中使用JSCode的问题 (#1198)
请问上面提到的问题，官方有正式的解决方法吗？
我现在也遇到了，例如 formatter=JsCode("funtion(x) {console.log(x); return x;}"),，但网页上只是将其作为字符串打印出来。
麻烦了谢谢

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pyecharts/pyecharts/issues/1198#issuecomment-1840255886",
"url": "https://github.com/pyecharts/pyecharts/issues/1198#issuecomment-1840255886",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Zhang0513** [comment]
时间太久了，我当时也是纯技术学习。不知道现在是什么版本了，有没有解决。前几天我的代码删除了。好像是是可以把字符串转成func，当时isuue 里面应该有发自我的iPhone------------------ 原始邮件 ------------------发件人: orangecat  ***@***.***>发送时间: 2023年12月5日 16:30收件人: pyecharts/pyecharts ***@***.***>抄送: Zhang0513 ***@***.***>, Mention ***@***.***>主题: Re: [pyecharts/pyecharts] Django中使用JSCode的问题 (#1198)
请问上面提到的问题，官方有正式的解决方法吗？
我现在也遇到了，例如 formatter=JsCode("funtion(x) {console.log(x); return x;}"),，但网页上只是将其作为字符串打印出来。
麻烦了谢谢

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pyecharts/pyecharts/issues/1198#issuecomment-1840255886",
"url": "https://github.com/pyecharts/pyecharts/issues/1198#issuecomment-1840255886",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
