### ISSUE TITLE
flask DEMO中，有一处需要加斜杠才能成功运行

### ISSUE THREAD

**Issue by yhf2lj** [pyecharts/pyecharts#1199]
你好，此处flask DEMO中，有一处需要加斜杠才能成功运行
![屏幕快照 2019-06-16 上午8 55 48](https://user-images.githubusercontent.com/22277238/59557771-13a7fc80-9015-11e9-9607-28043923a96a.png)

**Comment by CapAllen** [comment]
我也尝试了下Demo，但网页不显示柱状图。。。。想请教下，是不是还需要安装其他什么库？
![图片](https://user-images.githubusercontent.com/35265537/59672488-29bee400-91f2-11e9-922f-5058122b830a.png)
柱状图的json是可以加载进来的，但就是没图。。。

**Comment by sunhailin-Leo** [comment]
@yhf2lj 的确是文档里头漏了一个斜杠 😄

**Comment by CapAllen** [comment]
把localhost改成了127.0.0.1就好了:smile: 我有毒
![图片](https://user-images.githubusercontent.com/35265537/59674752-891ef300-91f6-11e9-8f44-28fec61e0b1b.png)
