### ISSUE TITLE
Bmap应该如何使用pandas格式的数据

### ISSUE THREAD

**Issue by wlh329387589** [pyecharts/pyecharts#1202]
**问题**
使用pandas导入一个带经纬度的文件，想在Bmap上显示，运行时一直提示：
cannot unpack non-iterable NoneType object。
查了一下感觉应该是pyecharts不支持pandas的数据类型，
因为没看懂如何调用的经纬度，所以不知道该如何传入正确的数据类型。
baiduditu=baiduditu1.to_dict('list') 试了一下转换为字典格式也不行呢。
想问一下，应该如何呈现？

**运行环境（系统环境及 pyecharts 版本）**
python 3.7
pyecharts 1.1.0
jupyter notebook 5.7.8

**代码及截图**
BAIDU_AK = "*******************************" 
baidumap=BMap()
baidumap.add_schema(
            baidu_ak=BAIDU_AK,
            center=[117.084366, 36.846801],
        )
baidumap.add(
            "bmap",
            [list(z) for z in zip(list(df['grid_no']),list(df['bili']))],type_ = 'effectScatter',
            label_opts=opts.LabelOpts(formatter="{b}"),
        )
baidumap.set_global_opts(title_opts=opts.TitleOpts(title="aaaaa"))
baidumap.render('aaa.html')

**Comment by sunhailin-Leo** [comment]
@wlh329387589 转换成 python 的基本数据结构就可以了。具体参考 pandas 的使用文档。
