### ISSUE TITLE
Grid中同步缩放多个对象的问题

### ISSUE THREAD

**Issue by luckfu** [pyecharts/pyecharts#1204]
我正在把以前0.5x版本中使用的K线图迁移到1.x版本下，之前的版本dataZoom可以设置xAxisIndex，使用统一的缩放条缩放多个对象，1.x版本中应该怎么设置呢？
grid = (
        Grid()
        .add(c, grid_opts=opts.GridOpts(pos_top="10%",pos_bottom="30%"))
        .add(v,grid_opts=opts.GridOpts(pos_top="70%",pos_bottom="15%"))
        
    )
grid.render_notebook()
![20190618170318](https://user-images.githubusercontent.com/1396910/59673671-465c1b80-91f4-11e9-8f9a-ab87c2788424.png)

![20190618170334](https://user-images.githubusercontent.com/1396910/59673853-9aff9680-91f4-11e9-94b5-b2486d49fe63.png)

**Comment by chenjiandongx** [comment]
在第一个图表上设置即可，或者你对 `grid.options` 进行 hack,

```v0.5.x: self._option <==> v1.0.x: self.options```

**Comment by luckfu** [comment]
> 在第一个图表上设置即可，或者你对 `grid.options` 进行 hack,
> 
> `v0.5.x: self._option <==> v1.0.x: self.options`

grid.options['dataZoom'][0].opts['xAxisIndex']=[0,1]
问题已解决，谢谢！
