### ISSUE TITLE
用户调查 - 你都用哪些图例和你对他们的重视度 (1-10)

### ISSUE THREAD

**Issue by chfw** [pyecharts/pyecharts#1206]
* 不曾使用：0（或直接忽略）
* 偶尔使用：1
* 经常使用：2-9
* 重度用户：10

```
{
 'Bar': 0,
 'Box Plot': 0,
 'Calendar': 0,
 'EffectScatter': 0,
 'Funnel': 0,
 'Gauge': 0,
 'Geo Chart': 0,
 'Graph': 0,
 'HeatMap': 0,
 'Candle Line': 0,
 'Liquid': 0,
 'Map': 0,
 'Parallel': 0,
 'Pictorial Bar': 0,
 'Pie': 0,
 'Polar': 0,
 'Radar': 0,
 'Sankey': 0,
 'Scatter Chart': 0,
 'Sunburst': 0,
 'Theme River': 0,
 'Tree': 0,
 'Tree Map': 0,
 'Word Cloud': 0,
 '3D Bar': 0,
 'Line': 0,
 '3D Line': 0,
 'Scatter 3D': 0,
 'Surface 3D': 0
}
```

**Comment by chfw** [comment]
这是我的：

```
{
 'Bar': 5,
 'Geo Chart': 10,
 'HeatMap': 8,
 'Candle Line': 1,
 'Map': 10,
 'Line': 2
}
```

**Comment by erikgqp8645** [comment]
这是我的：

{
 'Kline': 10,
 'Line': 10,
 'Overlap': 8,
 'Grid': 8,
}
主要用于做金融分析

**Comment by luckfu** [comment]
这是我的：

{
'Kline': 10,
'Line': 10,
'Overlap': 8,
'Grid': 8,
}
主要用于做金融分析

**Comment by TeddyXue** [comment]
{'Bar': 1,
 'Box Plot': 1,
 'Calendar': 0,
 'EffectScatter': 0,
 'Funnel': 0,
 'Gauge': 0,
 'Geo Chart': 0,
 'Graph': 0,
 'HeatMap': 0,
 'Candle Line': 0,
 'Liquid': 0,
 'Map': 0,
 'Parallel': 0,
 'Pictorial Bar': 0,
 'Pie': 5,
 'Polar': 0,
 'Radar': 0,
 'Sankey': 5,
 'Scatter Chart': 0,
 'Sunburst': 0,
 'Theme River': 0,
 'Tree': 9,
 'Tree Map': 0,
 'Word Cloud': 0,
 '3D Bar': 0,
 'Line': 5,
 '3D Line': 0,
 'Scatter 3D': 0,
 'Surface 3D': 0}

**Comment by Hourout** [comment]
{'Gauge': 10,
 'Radar': 10,
 'Line': 10}

**Comment by 77KMwrPl** [comment]
{
 'Bar': 5,
 
 'Candle Line': 10,
 'Line': 2
}

**Comment by BlankerL** [comment]
{
 'Map': 10,
}

**Comment by wenshi11019** [comment]
{
'Bar': 5,
'Line': 2
}
