### ISSUE TITLE
新版本不能像旧版本通过render("render.jpeg")输出图片文件

### ISSUE THREAD

**Issue by lhr1208** [pyecharts/pyecharts#1209]
**问题**
新版本不能像旧版本通过render("render.jpeg")输出图片文件

**运行环境（系统环境及 pyecharts 版本）**
V1.2.1

**代码及截图**
输出的jpeg打开之后，显示“无效图片”

**Comment by chfw** [comment]
看文档。用法变更了。

**Comment by chenjiandongx** [comment]
https://pyecharts.org/#/zh-cn/render_images
