### ISSUE TITLE
[v1.2.1] 无法通过dict方式初始化任一Chart

### ISSUE THREAD

**Issue by Yikun** [pyecharts/pyecharts#1210]
**问题**
[文档](https://pyecharts.org/#/zh-cn/parameters)[1]中，提到了可以通过多种方式进行初始化，
```Python
c = Bar(init_opts=opts.InitOpts(width="620px", height="420px"))
c = Bar(dict(width="620px", height="420px"))
c = Bar({"width": "620px", "height": "420px"})
```
但似乎目前仅支持init_opts的方式。
异常如下：
```
> Bar({"width":"100%", "height":"300px"})

  File "venv\lib\site-packages\pyecharts\charts\chart.py", line 143, in __init__
    super().__init__(init_opts=init_opts)
  File "venv\lib\site-packages\pyecharts\charts\chart.py", line 21, in __init__
    if init_opts.opts.get("theme") == ThemeType.WHITE:
AttributeError: 'dict' object has no attribute 'opts'
```

是因为

https://github.com/pyecharts/pyecharts/blob/4367827/pyecharts/charts/chart.py#L21

这行的问题。通过dict初始化的时候，不会有opts。似乎我们需要在这之前做一个dict到opts的转换？

[1] https://pyecharts.org/#/zh-cn/parameters

**运行环境（系统环境及 pyecharts 版本）**
1.2.1

**Comment by chfw** [comment]
Bar(Init_ops={})

**Comment by chfw** [comment]
阑尾

**Comment by Yikun** [comment]
@chfw 我明白可以通过init_ops方式初始化，但是似乎dict方式也希望支持，所以，如果不希望支持的话，可以fix下文档。

**Comment by chfw** [comment]
我也希望你 dict 可以被支持 @chenjiandongx
