### ISSUE TITLE
希望加上以市为基本单位的中国地图

### ISSUE THREAD

**Issue by xuhaer** [pyecharts/pyecharts#1218]
**问题**
目前已经有 [中国城市](https://echarts-maps.github.io/echarts-china-cities-js/)的基本数据，但无以市为基本单位的中国地图。在 [Map-VisualMap（连续型）的官方文档](https://pyecharts.org/#/zh-cn/geography_charts?id=map：地图) 中希望以市为显示基本单位。

**Comment by chfw** [comment]
![Screenshot 2019-07-03 at 01 44 14](https://user-images.githubusercontent.com/4280312/60555315-13597200-9d34-11e9-8bc7-c86b67ed3e9e.png)

**Comment by chfw** [comment]
预览：
https://echarts-maps.github.io/echarts-countries-js/preview.html

使用方法：
https://github.com/pyecharts/pyecharts/blob/master/example/echarts_china_counties_js_example.py
