### ISSUE TITLE
形参的名字　在哪里找？　新版看似统一了，但是很难找

### ISSUE THREAD

**Issue by Rockyzsu** [pyecharts/pyecharts#1219]
以前用的旧版很好用，可是新版用了所谓的链式调用，好多参数不知道怎么找，看完文档也只能用文档上那几个参数，其他的参数名怎么找？　

比如ｘ坐标旋转３０度这种，我也是经过其他人的代码里面找到，像这样的形参axislabel_opts名字，哪里有具体的列表说明吗？

**Comment by Rockyzsu** [comment]
搞了半天，还是用回了matplotlib

**Comment by sunhailin-Leo** [comment]
@Rockyzsu 请详细阅读官方文档

**Comment by sunhailin-Leo** [comment]
不读文档你怎么知道参数有什么呢？

**Comment by Rockyzsu** [comment]
我读了２遍，对着ｄｅｍｏ找参数，这种文档不是很友好。

**Comment by sunhailin-Leo** [comment]
那你觉得什么文档友好？

**Comment by sunhailin-Leo** [comment]
* 我不清楚你的不友好地方在哪里
![image](https://user-images.githubusercontent.com/17564655/60415946-350d0900-9c0f-11e9-83fa-0e9302136479.png)

**Comment by sunhailin-Leo** [comment]
* 配置项条目清晰
![image](https://user-images.githubusercontent.com/17564655/60416018-638ae400-9c0f-11e9-9205-f0d051cbbc25.png)
![image](https://user-images.githubusercontent.com/17564655/60416038-70a7d300-9c0f-11e9-93b8-00a218be2dea.png)

**Comment by sunhailin-Leo** [comment]
* 如果你觉得文档不友好，那么请你给出一个你觉得友好的文档模式给我们。

**Comment by Rockyzsu** [comment]
上面的方法我用了，不起作用。

最后起作用的是
xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=55))

这个函数里面的　axislabel_opts　形参名字。

    # 坐标轴标签配置项，参考 `series_options.LabelOpts`
    axislabel_opts: Union[LabelOpts, dict, None] = None,

第一个，没有直接的解释，要去参考其他函数，你们文档很多地方都是这样的。这个看描述，怎么可以知道里面会放个旋转的　？

非抬杠，只是写出自己的使用感受，毕竟看了一个早上文档。

**Comment by Rockyzsu** [comment]
还有我要一个类似月　plt.ylim([10,20]) 这样功能的，也是找不到直接的用法。　找了其他人和ｉｓｓｕｅ上的，貌似用max_,min_　也不知道用在哪里

**Comment by sunhailin-Leo** [comment]
> 上面的方法我用了，不起作用。
> 
> 最后起作用的是
> xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=55))
> 
> 这个函数里面的　axislabel_opts　形参名字。
> 
> ```
> # 坐标轴标签配置项，参考 `series_options.LabelOpts`
> axislabel_opts: Union[LabelOpts, dict, None] = None,
> ```
> 
> 第一个，没有直接的解释，要去参考其他函数，你们文档很多地方都是这样的。这个看描述，怎么可以知道里面会放个旋转的　？
> 
> 非抬杠，只是写出自己的使用感受，毕竟看了一个早上文档。

* 回答一：
    * 如果不去参考其他函数，你有考虑过如果 `LabelOpts` 里面的参数有几十个，那么每个关于跟 LabelOpts 的有关的配置都要贴上一大堆解释，你觉得你愿意看长篇大论般的文档嘛？

* 回答二：
    * 首先我们的项目的 api 跟 matplotlib 有很大的分别，所以你拿 matplotlib 来做比较没有太多的意义。你应该先将你需要用到的图的有关配置以及 Demo 仔细看完，如果再有不清楚的可以提 issue 进行提问。

**Comment by swuecho** [comment]
> 还有我要一个类似月　plt.ylim([10,20]) 这样功能的，也是找不到直接的用法。　找了其他人和ｉｓｓｕｅ上的，貌似用max_,min_　也不知道用在哪里

倒是搞一个支持matplotlib api 的版本， 同样基于 echarts

**Comment by sunhailin-Leo** [comment]
@swuecho 怎么说？

**Comment by swuecho** [comment]
> @swuecho 怎么说？

就是用matplotlib 的api，然后生产echarts 的config，在前端展示，这个对matplotlib的重度用户有吸引力

**Comment by sunhailin-Leo** [comment]
> > @swuecho 怎么说？
> 
> 就是用matplotlib 的api，然后生产echarts 的config，在前端展示，这个对matplotlib的重度用户有吸引力

* 我们的项目是 based on Echarts 的，而且我们的 api 设计是 unique 的，为什么要弄出 matplotlib like 的模式？
* 换言之如果有 seaborn 的重度用户，或者其他画图库的重度用户，我们难道也要去兼容其他画图库的 api 么？

**Comment by swuecho** [comment]
> > > @swuecho 怎么说？
> > 
> > 
> > 就是用matplotlib 的api，然后生产echarts 的config，在前端展示，这个对matplotlib的重度用户有吸引力
> 
> * 我们的项目是 based on Echarts 的，而且我们的 api 设计是 unique 的，为什么要弄出 matplotlib like 的模式？
> * 换言之如果有 seaborn 的重度用户，或者其他画图库的重度用户，我们难道也要去兼容其他画图库的 api 么？

是的。 我回复的是比较想用matplotlib的那个人。。。

**Comment by sunhailin-Leo** [comment]
@swuecho 
* 关于 api 设计这个问题，我觉得既然版本 1.x 版本已经发了挺长一段时间了，如果再改 api 的话，相信很多用户又得重新学习的。
* 补充多一点，如果 matplotlib 用户开发能力强的话，我觉得他们完全可以基于 pyecharts 再封装一层对于他们自己觉得来说易用的 api （Like kennethreitz 😄 ）

**Comment by swuecho** [comment]
> @swuecho
> 
> * 关于 api 设计这个问题，我觉得既然版本 1.x 版本已经发了挺长一段时间了，如果再改 api 的话，相信很多用户又得重新学习的。
> * 补充多一点，如果 matplotlib 用户开发能力强的话，我觉得他们完全可以基于 pyecharts 再封装一层对于他们自己觉得来说易用的 api （Like kennethreitz 😄 ）

是的，肯定没人希望在这个项目上加一套api。

**Comment by chenjiandongx** [comment]
@swuecho 入乡随俗

**Comment by chfw** [comment]
错过一个很有意思的讨论。我倒是觉得，大家可以加入我们一起改：改文档。

matplotlib 在学术界很久了，api 已经定型，社区文化也比较健全。pyecharts 才不到两岁，还处成长期。

**Comment by Rockyzsu** [comment]
closed this issue
