### ISSUE TITLE
Rotating label names in graph_npm_dependencies graph with layout='none'

### ISSUE THREAD

**Issue by EngineerReversed** [pyecharts/pyecharts#1220]
I want to display a large graph which is almost a tree but contains closed loops. So, I don't want labels to overlap with each other. In tree, we have the option of rotating label, but it is not working in graph. There are parameters like `is_rotate_label ` but they seem to have no effect.
Even using `opts.LabelOpts` seems to have no effect.

Can you tell me how to rotate labels in Graph?

I am using 
```
ubuntu:16.04
pyecharts==1.2.1
```

**Comment by sunhailin-Leo** [comment]
@EngineerReversed 
* The layout option have 3 options:
    * 'none' No any layout, use x, y provided in node as the position of node.
    * 'circular' Adopt circular layout
    * 'force' Adopt force-directed layout

**Comment by EngineerReversed** [comment]
I appreciate your reply but I have already tried the above three options. My requirement is to display pathways interconnected to each other. You can think of them like a flowchart. As the number of pathways increase, it starts getting messy. So, I want to rotate node labels so that they won't overlap with each other. The rotate option seems to be working in `Tree` but doesn't work in graph.

PS: I can plot my flowchart as a tree but the there are loops.
