### ISSUE TITLE
正则表达式导致JSONDecodeError

### ISSUE THREAD

**Issue by Zhang0513** [pyecharts/pyecharts#1221]
**问题**
1.21版本dump_options()
`    def dump_options(self) -> str:
        return utils.replace_placeholder(
            json.dumps(self.get_options(), indent=4, default=default)
        )

def replace_placeholder(html: str) -> str:
    return re.sub('"?--x_x--0_0--"?', '', html)
`
如果我在代码中使用jscode或者强行插入字符--x_x--0_0--，会导致dump_options()输出的时候少掉一个"。详细看截图。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.2

**代码及截图**

![TIM图片20190702104752](https://user-images.githubusercontent.com/42483329/60479005-e024cd80-9cb6-11e9-8916-8923f36d0e77.png)

**Comment by chenjiandongx** [comment]
不是很明白什么叫 **强行插入字符--x_x--0_0--**

**Comment by Zhang0513** [comment]
> 
> 
> 不是很明白什么叫 **强行插入字符--x_x--0_0--**

假设我使用了这个字符串（--x_x--0_0--）。
你看下面的aa 前后("")引号已经消失了。就会发生异常！

ps：
为什么说假设我使用了。
因为jscode 前后就是追了这个字符串。我这里只是简单替换了一下。

**Comment by chenjiandongx** [comment]
给个实际需求的 demo 我，总感觉不太对劲

**Comment by Zhang0513** [comment]
> 
> 
> 给个实际需求的 demo 我，总感觉不太对劲

在django试试JsCode，就知道了。
`
itemstyle_opts=opts.ItemStyleOpts(
                     color=JsCode(
                         "function (params){alert('hello world');}")
                 )
`
不需要什么实际的代码。
