### ISSUE TITLE
Bar图调用add_yaxis时，如果传递的第二参数为表达式赋值，则会渲染失败

### ISSUE THREAD

**Issue by ranyaxiong** [pyecharts/pyecharts#1224]
**问题**
Bar图调用add_yaxis，传递yaxis_data参数时，如果变量为表达式赋值，则会导致渲染失败
如图：
![bar图bug](https://user-images.githubusercontent.com/12514368/60504933-3153b200-9cf5-11e9-9391-b0fb81f8a8eb.jpg)
![Bar图bug1](https://user-images.githubusercontent.com/12514368/60504941-37499300-9cf5-11e9-93d5-e50d04885076.jpg)

其中episode_title=episode_title1， episode_comments_number=episode_comments_number1
参数为episode_comments_number时渲染失败，为episode_comments_number1时渲染成功
请问这是什么问题

**运行环境（系统环境及 pyecharts [版本）**]
window10 anaconda pyecharts1.0 Python3.7

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@ranyaxiong 检查一下你的数据类型

**Comment by ranyaxiong** [comment]
> @ranyaxiong 检查一下你的数据类型

谢回复。我检查了下，确实是数据类型导致的，episode_comments_number列表里的元素为numpy int64类型，把它转为int类型后可以正常渲染。但我在pycharts0.5版本里使用是没问题的，可能是1.0版本不支持numpy int类型了
