### ISSUE TITLE
Geo 使用json添加坐标时file name too long

### ISSUE THREAD

**Issue by frederickkkk123** [pyecharts/pyecharts#1225]
python 中将dic通过json.dumps转换为json，然后使用add_coordinate_json新增多个坐标点。然而返回[Errno 36] File name too long: 
![屏幕快照 2019-07-03 下午4 39 48](https://user-images.githubusercontent.com/24794992/60577381-d5029800-9db1-11e9-818f-34bd2ca24f87.png)
![屏幕快照 2019-07-03 下午4 40 01](https://user-images.githubusercontent.com/24794992/60577382-d59b2e80-9db1-11e9-80d3-fc1bde80ecf2.png)

**Comment by chfw** [comment]
city_json file name itself not the file content please!
