### ISSUE TITLE
在notebook中使用render_notebook()无法渲染出图片

### ISSUE THREAD

**Issue by scanfyu** [pyecharts/pyecharts#1226]
**问题**
在notebook中使用render_notebook()无法渲染出图片，直接使用.render()可以渲染出html且显示正常。

**运行环境（系统环境及 pyecharts 版本）**
Windows7
python3.7.3
pyecharts1.2.1

**代码及截图**
![render_notebook](https://user-images.githubusercontent.com/3198940/60581720-f8314580-9db9-11e9-944d-c12efdefc612.png)

**Comment by chenjiandongx** [comment]
Jupyter Notebook 还是 JupyterLab?

**Comment by scanfyu** [comment]
Jupyter Notebook

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 陈键冬 <notifications@github.com>
发送时间: Wednesday, July 3, 2019 9:53:09 PM
收件人: pyecharts/pyecharts
抄送: Sunny; Author
主题: Re: [pyecharts/pyecharts] 在notebook中使用render_notebook()无法渲染出图片 (#1226)


Jupyter Notebook 还是 JupyterLab?

―

**Comment by chfw** [comment]
1. make sure you are online
2. restart your notebook server
3. copy and paste your code to a notebook with a different title
4. run it

**Comment by maxl0926** [comment]
jupyter notebook可以显示但是比较麻烦
先要设置好，然后在第一次出图的时候要load_javascript
`from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_NOTEBOOK
%config InlineBackend.figure_format = 'svg'
%matplotlib inline`
`bar.load_javascript()
bar.render_notebook()`
