### ISSUE TITLE
jupyter lab无法用render_notebook()渲染图片，显示空白

### ISSUE THREAD

**Issue by maxl0926** [pyecharts/pyecharts#1228]
问题
在jupyter lab中使用render_notebook()无法渲染出图片，直接使用.render()可以生成网页且正常显示

运行环境（系统环境及 pyecharts 版本）
Windows 7
fire fox游览器
python 3.7.3
pyecharts 1.2.1
jupyter lab 1.0.0
![火狐截图_2019-07-05T14-10-06 736Z](https://user-images.githubusercontent.com/52432841/60728372-b7c8f780-9f72-11e9-96f9-b69894b6e24d.png)

**Comment by sunhailin-Leo** [comment]
@maxl0926 Please check your browser console.

**Comment by ifcheung2012** [comment]
我也是这个问题 重装N遍 都不行  issue里的方法都试遍了

**Comment by songxunyu** [comment]
> 我也是这个问题重装N遍都不行issue里的方法都试遍了
> ![图片](https://user-images.githubusercontent.com/2020778/61626056-cb809780-acae-11e9-82f8-21e2829bdf17.png)

我也是这个问题！各种办法试了都不行
