### ISSUE TITLE
是否可以保存为矢量图，例如pdf格式的。

### ISSUE THREAD

**Issue by ZhengHui-Z** [pyecharts/pyecharts#1229]
**问题**
是否可以保存为矢量图，这样将极大方便科研工作者。
非常感谢作者作出的贡献，已请咖啡！

**Comment by chfw** [comment]
这个库可以，https://github.com/pyecharts/pyecharts-snapshot

**Comment by ZhengHui-Z** [comment]
> 这个库可以，https://github.com/pyecharts/pyecharts-snapshot

感谢
