### ISSUE TITLE
请教一下如何多chart联动

### ISSUE THREAD

**Issue by darcy-wu** [pyecharts/pyecharts#1230]
**问题**
请教一下如何多chart联动，能够同时缩放，同时选中，echarts例子如下：
[多chart联动](https://echarts.baidu.com/echarts2/doc/example/mix8.html#)

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@darcy-wu da
* 链接的 demo 是 echart 2.x 的，麻烦你找个 4.x 的再贴出来。

**Comment by darcy-wu** [comment]
找了个新的例子，请看 
[例子](https://echarts.baidu.com/examples/editor.html?c=candlestick-brush)

**Comment by sunhailin-Leo** [comment]
* 倒是实现了，过程有点复杂
![image](https://user-images.githubusercontent.com/17564655/60867510-9f502a00-a25d-11e9-9111-62bf3bda5cc5.png)

**Comment by sunhailin-Leo** [comment]
类似的 issue: https://github.com/pyecharts/pyecharts/issues/1232
