### ISSUE TITLE
坐标轴指示器能否同时指示多张图

### ISSUE THREAD

**Issue by MatthewZou9419** [pyecharts/pyecharts#1232]
**问题**
用grid添加的多张图目前还不能同时指示。
比如下图中，我想把指示器扩展到第2张图，应该如何设置？
![Screenshot from 2019-07-09 09-35-51](https://user-images.githubusercontent.com/31568280/60853146-60a27b80-a22d-11e9-8fc2-cd07c50f5b0c.png)
类似这种
![Screenshot from 2019-07-09 09-47-34](https://user-images.githubusercontent.com/31568280/60853475-d6f3ad80-a22e-11e9-8b73-7a13a3cc2189.png)

**运行环境（系统环境及 pyecharts 版本）**
linux  python3.6  pyecharts1.2.1

**代码及截图**
`    def _get_kline_given_data(cls, _kline_data, _attr, _axis_num):
        kline = Kline()
        kline.add_xaxis(_attr)
        kline.add_yaxis('kline', _kline_data)
        kline.set_global_opts(
            datazoom_opts=[
                opts.DataZoomOpts(
                    type_='inside', range_start=0, range_end=100, xaxis_index=list(range(_axis_num))
                )
            ],
            tooltip_opts=opts.TooltipOpts(
                axis_pointer_type='cross',
                trigger='axis'
            ),
            legend_opts=opts.LegendOpts(pos_left='10%')
        )
        return kline`

**Comment by erikgqp8645** [comment]
请问大佬，你这个问题解决没。我也碰到这样的问题哈。求赐教。

**Comment by sunhailin-Leo** [comment]
我不是 link 一个进度了吗？你可以去看看
