### ISSUE TITLE
让折线图的每个折点都显示数值

### ISSUE THREAD

**Issue by remindstam** [pyecharts/pyecharts#1235]
**问题**
求问如何让折线图的每个折点都显示数值

**运行环境（系统环境及 pyecharts 版本）**
win10  1.2.1

**代码及截图**
![image](https://user-images.githubusercontent.com/44601204/60875429-6cf9f900-a26c-11e9-8c55-b448eec66d4f.png)

**Comment by sunhailin-Leo** [comment]
@remindstam 据我所知 echarts Line 图倒是没这个算法。如果要实现的话，我觉得你得用自己的算法判断折点，然后生成一个 MarkPoint 的列表

**Comment by remindstam** [comment]
> @remindstam 据我所知 echarts Line 图倒是没这个算法。如果要实现的话，我觉得你得用自己的算法判断折点，然后生成一个 MarkPoint 的列表



但是我搜了echarts是可以实现的，具体方法是在 series中添加
itemStyle : { normal: {label : {show: true}}}
但是我不知道在这个pyecharts里头如何实现

**Comment by sunhailin-Leo** [comment]
@remindstam 你说的那个是显示所有的点的 label。我以为你是要显示所有拐点的数值

**Comment by remindstam** [comment]
> @remindstam 你说的那个是显示所有的点的 label。我以为你是要显示所有拐点的数值

请问这个要如何实现呢？

**Comment by sunhailin-Leo** [comment]
@remindstam 哪种？

**Comment by remindstam** [comment]
> @remindstam 哪种？

显示所有的点的 label

**Comment by sunhailin-Leo** [comment]
@remindstam https://pyecharts.org/#/zh-cn/rectangular_charts?id=line%ef%bc%9a%e6%8a%98%e7%ba%bf%e9%9d%a2%e7%a7%af%e5%9b%be

**Comment by remindstam** [comment]
> https://pyecharts.org/#/zh-cn/rectangular_charts?id=line%ef%bc%9a%e6%8a%98%e7%ba%bf%e9%9d%a2%e7%a7%af%e5%9b%be

不行，这个链接定位不到位置啊。 请问是在哪一部分里头 我去找找

**Comment by sunhailin-Leo** [comment]
@remindstam 认真看看文档行吗？

**Comment by remindstam** [comment]
> @remindstam 认真看看文档行吗？

就是找不到才来这请教啊

**Comment by sunhailin-Leo** [comment]
@remindstam 
* Line 和 LabelOpts。能把 Line 图的配置看完和 demo 看完，以及 LabelOpts 参数看完嘛？
* 左上角还有搜索功能，我觉得不会找不到吧？
