### ISSUE TITLE
时间线轮播多图不显示图片

### ISSUE THREAD

**Issue by Zhanchenhaha** [pyecharts/pyecharts#1237]
**问题**

<pyecharts.charts.composite_charts.timeline.Timeline at 0x4e0f9b0>

**运行环境（系统环境及 pyecharts 版本）**
windows 7 
python 3.6
pyecharts 1.2.1

**代码及截图**

from example.commons import Faker
from pyecharts import options as opts
from pyecharts.charts import Bar, Page, Pie, Timeline, Map

tl = Timeline()
for i in range(2015, 2020):
     map0 = (
            Map()
            .add(
                "商家A", [list(z) for z in zip(Faker.provinces, Faker.values())], "china"
            )
            .set_global_opts(
                title_opts=opts.TitleOpts(title="Map-{}年某些数据".format(i)),
                visualmap_opts=opts.VisualMapOpts(max_=200),
            )
    )
tl.add(map0, "{}年".format(i))
tl

**Comment by sunhailin-Leo** [comment]
@Zhanchenhaha 
几个问题哈:
* 第一：查一下 markdown 怎么优雅的放代码。
* 第二：你的编译器是 Pycharm 还是 Jupyter 我们也不知道。
* 第三：截图麻烦给一下。

**Comment by Zhanchenhaha** [comment]
@sunhailin-Leo 
```python
from example.commons import Faker
from pyecharts import options as opts
from pyecharts.charts import Bar, Page, Pie, Timeline, Map

tl = Timeline()
for i in range(2015, 2020):
map0 = (
Map()
.add(
"商家A", [list(z) for z in zip(Faker.provinces, Faker.values())], "china"
)
.set_global_opts(
title_opts=opts.TitleOpts(title="Map-{}年某些数据".format(i)),
visualmap_opts=opts.VisualMapOpts(max_=200),
)
)
tl.add(map0, "{}年".format(i))
tl
```

编译器为 jypyter notebook

  
![image](https://user-images.githubusercontent.com/22406470/60979472-600d0080-a365-11e9-8902-763e9f3dab2c.png)

**Comment by sunhailin-Leo** [comment]
@Zhanchenhaha 
对比一下 demo 看看你少了什么。
https://pyecharts.org/#/zh-cn/quickstart?id=jupyter-notebook
