### ISSUE TITLE
如何在scatter中加入extra_data显示在图中

### ISSUE THREAD

**Issue by MatthewZou9419** [pyecharts/pyecharts#1238]
**问题**
在老版本的Scatter中有extra_data参数，但新版本中没看到，请问如何加上去并显示在图中。
![Screenshot from 2019-07-11 10-29-42](https://user-images.githubusercontent.com/31568280/61018001-d3475e80-a3c7-11e9-950f-d90e64635738.png)
另外，我用grid添加了几个图，如何写jscode可以将所有信息都显示在一个框内？
![Screenshot from 2019-07-11 10-29-59](https://user-images.githubusercontent.com/31568280/61018058-0689ed80-a3c8-11e9-92b2-674634408c33.png)

**运行环境（系统环境及 pyecharts 版本）**
linux python3.6 pyecharts1.2.1

**代码及截图**

    def _get_kline_given_data(cls, _kline_data, _attr, _axis_num):
        kline = Kline()
        kline.add_xaxis(_attr)
        kline.add_yaxis('kline', _kline_data)
        kline.set_global_opts(
            datazoom_opts=[
                opts.DataZoomOpts(
                    type_='inside', range_start=0, range_end=100, xaxis_index=list(range(_axis_num))
                )
            ],
            tooltip_opts=opts.TooltipOpts(
                axis_pointer_type='cross',
                trigger='axis',
                # formatter=utils.JsCode(kline_tooltip_formatter)
            ),
            axispointer_opts=opts.AxisPointerOpts(
                is_show=True,
                link=[{"xAxisIndex": "all"}]
            ),
            legend_opts=opts.LegendOpts(pos_left='10%'),
            yaxis_opts=opts.AxisOpts(
                splitline_opts=opts.SplitLineOpts(
                    is_show=True,
                    linestyle_opts=opts.LineStyleOpts(
                        opacity=0.5
                    )
                ),
                min_='dataMin',
                max_='dataMax'
            ),
            xaxis_opts=opts.AxisOpts(
                splitline_opts=opts.SplitLineOpts(
                    is_show=True,
                    linestyle_opts=opts.LineStyleOpts(
                        opacity=0.5
                    )
                )
            )
        )
        return kline

    def _get_line(_data, _attr, _name):
        if _name == 'capital':
            c = 'blue'
        elif _name == 'benchmark':
            c = 'red'
        else:
            c = 'green'

        line = Line()
        line.add_xaxis(_attr)
        line.add_yaxis(
            _name,
            _data,
            xaxis_index=2,
            label_opts=opts.LabelOpts(is_show=False),
            is_symbol_show=False,
            linestyle_opts=opts.LineStyleOpts(width=2, color=c)
        )
        line.set_global_opts(
            yaxis_opts=opts.AxisOpts(
                splitline_opts=opts.SplitLineOpts(
                    is_show=True,
                    linestyle_opts=opts.LineStyleOpts(
                        opacity=0.5
                    )
                ),
                min_='dataMin',
                max_='dataMax'
            ),
            xaxis_opts=opts.AxisOpts(
                splitline_opts=opts.SplitLineOpts(
                    is_show=True,
                    linestyle_opts=opts.LineStyleOpts(
                        opacity=0.5
                    )
                )
            )
        )
        return line

    def _get_bar(cls, _data, _attr, _name):
        bar = Bar()
        bar.add_xaxis(_attr)
        bar.add_yaxis(
            _name,
            _data,
            xaxis_index=1,
            label_opts=opts.LabelOpts(is_show=False)
        )
        bar.set_global_opts(
            legend_opts=opts.LegendOpts(pos_left='25%'),
            yaxis_opts=opts.AxisOpts(
                splitline_opts=opts.SplitLineOpts(
                    is_show=True,
                    linestyle_opts=opts.LineStyleOpts(
                        opacity=0.5
                    )
                ),
                min_='dataMin',
                max_='dataMax'
            ),
            xaxis_opts=opts.AxisOpts(
                splitline_opts=opts.SplitLineOpts(
                    is_show=True,
                    linestyle_opts=opts.LineStyleOpts(
                        opacity=0.5
                    )
                )
            )
        )
        return bar

    def _get_scatter(_open_orders, _close_orders):
        scatter = Scatter()
        attr_open = [timestamp_local_datetime(x[0]) for x in _open_orders] if len(_open_orders) > 0 else []
        value_open = [x[1] for x in _open_orders] if len(_open_orders) > 0 else []
        extra_open = [x[2:] for x in _open_orders] if len(_open_orders) > 0 else []
        scatter.add_xaxis(attr_open)
        scatter.add_yaxis(
            'open_order',
            value_open,
            label_opts=opts.LabelOpts(is_show=False),
            extra_data=extra_open
        )
        attr_close = [timestamp_local_datetime(x[0]) for x in _close_orders] if len(_close_orders) > 0 else []
        value_close = [x[1] for x in _close_orders] if len(_close_orders) > 0 else []
        extra_close = [x[2:] for x in _close_orders]
        scatter.add_xaxis(attr_close)
        scatter.add_yaxis(
            'close_order',
            value_close,
            label_opts=opts.LabelOpts(is_show=False),
            extra_data=extra_close
        )
        return scatter

    grid = Grid()
    kline = cls._get_kline_given_data(kline_data, attr, axis_num)
    cap_line = cls._get_line(capital, attr, 'capital')
    scatter = cls._get_scatter(open_orders, close_orders)
    vol_bar = cls._get_bar(vol_data, attr, 'volume')
    dd_line = cls._get_line(list(dd), attr, 'drawdown')
    bm_line = cls._get_line(bm, attr, 'benchmark')
    kline.overlap(scatter)
    cap_line.overlap(bm_line)
    cap_line.overlap(dd_line)
    grid.add(
        kline,
        grid_opts=opts.GridOpts(
            pos_top='%d%%' % (cls.gap / height * 100),
            height='%dpx' % (cls.kline_h - cls.gap)
        )
    )
    grid.add(
        vol_bar,
        grid_opts=opts.GridOpts(
            pos_top='%d%%' % (cls.kline_h / height * 100),
            height='%dpx' % (cls.vol_h - cls.gap)
        )
    )
    grid.add(
        cap_line,
        grid_opts=opts.GridOpts(
            pos_top='%d%%' % ((cls.kline_h + cls.vol_h) / height * 100),
            height='%dpx' % (cls.capital_h - cls.gap)
        )
    )

**Comment by sunhailin-Leo** [comment]
@MatthewZou9419 
* First: 你的代码再处理一下，看的很乱。去看一下 Markdown 怎么贴代码的。
* Second: 你第一个问题我没看明白。
* Third: 你说的那个信息显示在一个框的话，你可以在 ToolTipOpts 中的 format 写 JSCode。但是这么做是会覆盖掉默认的多图的 ToolTip 的，我昨天的那个 pr 里头曾经试过那么写，后来我就删掉了。你可以尝试一下。
![](https://user-images.githubusercontent.com/17564655/61019215-ee1bd200-a3cb-11e9-8add-06894310e21a.png)

**Comment by MatthewZou9419** [comment]
@sunhailin-Leo 
嗯嗯，谢谢提醒。extra_data就是说鼠标放在一个点上的时候希望显示更多的内容，比如不只是这个点的值，还包括一些字符串内容，通过传入extra_data，画图的时候只画横纵坐标的值，其他的就显示在框内，在老版本有这个参数，但新版本没有了。

关于ToolTip，我尝试写过JSCode，但都不能同时将多个图的信息显示在一个框内，只能单独显示kline的或者bar的。
