### ISSUE TITLE
跪求各位大佬增加筛选框功能

### ISSUE THREAD

**Issue by Aidenhsu** [pyecharts/pyecharts#1239]
**问题**
没有找到像altair那样可以直接添加的全局筛选框；对于数百个城市的数据，统一画在一起再去图表上筛选是非常不方便的，希望各位大大增加个筛选功能。

**Comment by sunhailin-Leo** [comment]
@Aidenhsu 大概是个什么东西？或者你可以看看 Echarts 本身有没有这个组件。
