### ISSUE TITLE
仪表盘的第三个示例-分割段数-报错

### ISSUE THREAD

**Issue by bebetterst** [pyecharts/pyecharts#1240]
**问题**
文档里的代码运行的时候，提示：TypeError: add() got an unexpected keyword argument 'split_number'，将split_number这一行注释掉后，会提示：add() got an unexpected keyword argument 'label_opts'

**运行环境（系统环境及 pyecharts 版本）**
win10 64位+ jupyter notebook + python 3.7.1+pyecharts 1.2.0

**代码及截图**
def gauge_splitnum_label() -> Gauge:
    c = (
        Gauge()
        .add(
            '业务指标',
            [('完成率',55.5)],
            split_number = 5,
            axisline_opts = opts.AxisLineOpts(
                linestyle_opts = opts.LineStyleOpts(
                    color = [(0.3,'#67e0e3'),(0.7,'#37a2da'),(1,'#fd666d')],width=30
                )
            ),
            label_opts=opts.LabelOpts(formatter ='{value}'),
        )
        .set_global_opts(
            title_opts = opts.TitleOpts(title = 'Gauge-分割段数-Label'),
            legend_opts = opts.LegendOpts(is_show =False),
        )            
    )
    return c
gauge_splitnum_label().render_notebook()

![image](https://user-images.githubusercontent.com/38149502/61110723-7e384500-a4ba-11e9-8b3c-b14ade45b344.png)

**Comment by chenjiandongx** [comment]
请确认 pyecharts 版本为最新的 v1.2.1
