### ISSUE TITLE
DataZoomOpts的type能否增加“both”类型？

### ISSUE THREAD

**Issue by ZhouQW2019** [pyecharts/pyecharts#1243]
**问题**
DataZoomOpts的type能否增加“both”类型？1.2.1文档里面只有"slider", "inside"，而0.5版本里面有三种类型，在折线图里方便缩放，同时能兼顾看到折线的整体趋势

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
现在 Echarts 4 的文档里头没有 both 这个参数了。

**Comment by chenjiandongx** [comment]
你可以往 DataZoomOpts 设置两个，一个是 slider 一个是 inside
