### ISSUE TITLE
Map下无法修改无数据部分的地图颜色

### ISSUE THREAD

**Issue by BlankerL** [pyecharts/pyecharts#1248]
**问题**
Map下无法修改无数据部分的地图颜色

**运行环境（系统环境及 pyecharts 版本）**
Windows 10
pyecharts>=1.2.0
echarts-countries-pypkg>=0.1.6

**代码及截图**
![image](https://user-images.githubusercontent.com/24969376/61181076-b2933900-a653-11e9-8379-ad76be93b652.png)
即上图灰色区域，是否能够调整颜色呢？
因为部分情况下有数据的区域颜色接近无数据区域。

**Comment by chfw** [comment]
地图名字和数据序列名字错位了

**Comment by chfw** [comment]
请参照这里的解决方案：https://github.com/pyecharts/geopython-2019-talk/blob/master/population.ipynb

**Comment by chfw** [comment]
哦，灰色部分啊！我看看

**Comment by BlankerL** [comment]
> 哦，灰色部分啊！我看看

感谢！按照[官方文档](https://pyecharts.org/#/zh-cn/geography_charts?id=map%ef%bc%9a%e5%9c%b0%e5%9b%be)使用[ItemStyleOpts：图元样式配置项](https://pyecharts.org/#/zh-cn/series_options?id=itemstyleopts%ef%bc%9a%e5%9b%be%e5%85%83%e6%a0%b7%e5%bc%8f%e9%85%8d%e7%bd%ae%e9%a1%b9)，在网页的json中可以看到color已经添加成功，但是似乎并不会作用于生成出的地图。

**Comment by BlankerL** [comment]
感谢！So efficient!
