### ISSUE TITLE
Bmap中heatmap无法显示

### ISSUE THREAD

**Issue by cgh1989106** [pyecharts/pyecharts#1249]
**问题**
Bmap中heatmap无法显示，地图类型改为scatter后可正常显示

**运行环境（系统环境及 pyecharts 版本）**
win10+pyecharts1.3

**代码及截图**
![image](https://user-images.githubusercontent.com/38932255/61183165-2c392000-a670-11e9-9658-b9b7e95af4f3.png)
![image](https://user-images.githubusercontent.com/38932255/61183177-4ecb3900-a670-11e9-981f-37347e499a95.png)

**Comment by chenjiandongx** [comment]
https://github.com/pyecharts/pyecharts/pull/1321
