### ISSUE TITLE
怎么画自定义的mark_line

### ISSUE THREAD

**Issue by Xialichong** [pyecharts/pyecharts#1251]
**问题**
小白一个。。想在hist中画上自定义值的mark_line，而不是 平均值和最大值这种，请问用哪个函数？？

此外，我找过官方文档，但是感觉和我网站上看到的案例是两种写法。
案例上，我可以直接定义bar=Bar()，然后bar.add就行了。

为什么官方文档需要def...，原谅我比较菜，看不懂 T.T

此外，官方交流群的二维码过期了，想加

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Xialichong 
* 你认为的 MarkLine 是如何？ 提供一份 example 或者 Echarts 的图也好。
* 群二维码已更新～

**Comment by Xialichong** [comment]
手头没图，就是平行于x轴的一条线，类似average，max这种，但是我可以定义它的y值

感谢

LeoSun <notifications@github.com> 于2019年7月15日周一 下午10:45写道：

**Comment by chenjiandongx** [comment]
@Xialichong 

![image](https://user-images.githubusercontent.com/19553554/61442670-a15f6a80-a97a-11e9-85fe-1a775f595bb9.png)

**Comment by Xialichong** [comment]
感谢东哥，这份文档我看到过，一定要写成这样吗，有没有
BAR().add(x, mark_line=....)这种形式的

纯菜鸡，这种写法不太会写……
