### ISSUE TITLE
1.3.0 is still not working on JupyterLab

### ISSUE THREAD

**Issue by yinchuandong** [pyecharts/pyecharts#1255]
**问题**
not displaying charts on JupyterLab, but the same code is working for JupyterNotebook

**运行环境（系统环境及 pyecharts 版本）**
System: macos 10.14.3
Python: Python 3.6.5 :: Anaconda,
pyecharts==1.3.0
jupyterlab:
![image](https://user-images.githubusercontent.com/3993196/61215483-5c56f080-a74e-11e9-8504-a757b082798b.png)

**代码及截图**

![image](https://user-images.githubusercontent.com/3993196/61215511-742e7480-a74e-11e9-92be-dbc3b3d73aab.png)

source code:
``` python
import random

class Faker:
    clothes = ["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"]
    drinks = ["可乐", "雪碧", "橙汁", "绿茶", "奶茶", "百威", "青岛"]
    phones = ["小米", "三星", "华为", "苹果", "魅族", "VIVO", "OPPO"]
    fruits = ["草莓", "芒果", "葡萄", "雪梨", "西瓜", "柠檬", "车厘子"]
    animal = ["河马", "蟒蛇", "老虎", "大象", "兔子", "熊猫", "狮子"]
    cars = ["宝马", "法拉利", "奔驰", "奥迪", "大众", "丰田", "特斯拉"]
    dogs = ["哈士奇", "萨摩耶", "泰迪", "金毛", "牧羊犬", "吉娃娃", "柯基"]
    week = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"]
    week_en = "Saturday Friday Thursday Wednesday Tuesday Monday Sunday".split()
    clock = (
        "12a 1a 2a 3a 4a 5a 6a 7a 8a 9a 10a 11a 12p "
        "1p 2p 3p 4p 5p 6p 7p 8p 9p 10p 11p".split()
    )
    visual_color = [
        "#313695",
        "#4575b4",
        "#74add1",
        "#abd9e9",
        "#e0f3f8",
        "#ffffbf",
        "#fee090",
        "#fdae61",
        "#f46d43",
        "#d73027",
        "#a50026",
    ]
    months = ["{}月".format(i) for i in range(1, 13)]
    provinces = ["广东", "北京", "上海", "江西", "湖南", "浙江", "江苏"]
    guangdong_city = ["汕头市", "汕尾市", "揭阳市", "阳江市", "肇庆市", "广州市", "惠州市"]
    country = [
        "China",
        "Canada",
        "Brazil",
        "Russia",
        "United States",
        "Africa",
        "Germany",
    ]
    days_attrs = ["{}天".format(i) for i in range(30)]
    days_values = [random.randint(1, 30) for _ in range(30)]

    @staticmethod
    def choose() -> list:
        return random.choice(
            [
                Faker.clothes,
                Faker.drinks,
                Faker.phones,
                Faker.fruits,
                Faker.animal,
                Faker.dogs,
                Faker.week,
            ]
        )

    @staticmethod
    def values(start: int = 20, end: int = 150) -> list:
        return [random.randint(start, end) for _ in range(7)]

    @staticmethod
    def rand_color():
        return random.choice(
            [
                "#c23531",
                "#2f4554",
                "#61a0a8",
                "#d48265",
                "#749f83",
                "#ca8622",
                "#bda29a",
                "#6e7074",
                "#546570",
                "#c4ccd3",
                "#f05b72",
                "#444693",
                "#726930",
                "#b2d235",
                "#6d8346",
                "#ac6767",
                "#1d953f",
                "#6950a1",
            ]
        )

pie = pie_base()
pie.load_javascript()
# pie.render_notebook()
# pie.render()


pie.render_notebook()

```

**Comment by yinchuandong** [comment]
I really appreciate the contribution of pyecharts, but pls make sure it has been fully tested before releasing. I find many bugs in your most recent documents, which shouldn't happen if you test it.

**Comment by sunhailin-Leo** [comment]
@yinchuandong Can you show me your browser console pls ? Maybe the problem is about your network.

**Comment by sunhailin-Leo** [comment]
* First, If you using version `1.3.0`; i suggest you update the version, because we found a bug 5 hours before. * 
* Second, pyecharts will load some `js scripts` before render. Maybe your browser or your network cannot load the `js` immediately. (You can check it. :😃)
* Last, I saw in your comments that you found a lot of bugs in our documentation. Can you point it？Or maybe you can help us to optimize it. Thank u so much. 😃

**Comment by chenjiandongx** [comment]
@yinchuandong 

IS **JUPYTER_LAB**,NOT **JUPYTER_NOTEBOOK**

![image](https://user-images.githubusercontent.com/19553554/61225223-bb1e6900-a752-11e9-9462-36f4f8f1b9bb.png)

**Comment by yinchuandong** [comment]
@chenjiandongx Thanks for your quick reply, it's working right now on jupyterlab==1.0.2. I actually used **Notebook. JUPYTER_LAB** on jupyterlab==0.35.0 but it was not working. Then I changed to **Notebook.JUPYTER_NOTEBOOK** but it was not working as well. I tried to upgrade my jupyterlab version but forgot to update the code. It's my fault.  But can you pls elaborate the jupyterlab version issue into README.md?  since I'm not aware of this issue before. BTW, plotly also has the jupyterlab version issue. But they elaborated it and users will be aware of this issus, see [https://github.com/plotly/plotly.py#jupyterlab-support-python-35](https://github.com/plotly/plotly.py#jupyterlab-support-python-35).

In terms of the bugs I mentioned before, I can only remember one at this moment.
Here `Faker.choose()` should be `Faker().choose()` since `choose` is not a static function in `Faker`
![image](https://user-images.githubusercontent.com/3993196/61226935-b5cb1980-a766-11e9-918b-bbe9157eefbe.png)

![image](https://user-images.githubusercontent.com/3993196/61227060-ead76c00-a766-11e9-8fbc-3037ef0db68c.png)

**Comment by sunhailin-Leo** [comment]
@yinchuandong 
* Please read source code. https://github.com/pyecharts/pyecharts/blob/master/example/commons.py#L101
* Have any others bugs or errors?

```python
class _Faker:
    def choose(self):
        pass


Faker = _Faker()
```

**Comment by yinchuandong** [comment]
> @yinchuandong
> 
> * Please read source code. https://github.com/pyecharts/pyecharts/blob/master/example/commons.py#L101
> * Have any others bugs or errors?
> 
> ```python
> class _Faker:
>     def choose(self):
>         pass
> 
> 
> Faker = _Faker()
> ```

Thanks @sunhailin-Leo , can you also pls update the official documents? [https://pyecharts.org/#/zh-cn/demo_data?id=faker](https://pyecharts.org/#/zh-cn/demo_data?id=faker). It's a little bit confusing. BTW, it would be much better if you can provide jupyter files in /examples since most pyecharts users are coming from data science background. Just make things easier

**Comment by sunhailin-Leo** [comment]
> > @yinchuandong
> > 
> > * Please read source code. https://github.com/pyecharts/pyecharts/blob/master/example/commons.py#L101
> > * Have any others bugs or errors?
> > 
> > ```python
> > class _Faker:
> >     def choose(self):
> >         pass
> > 
> > 
> > Faker = _Faker()
> > ```
> 
> Thanks @sunhailin-Leo , can you also pls update the official documents? https://pyecharts.org/#/zh-cn/demo_data?id=faker. It's a little bit confusing. BTW, it would be much better if you can provide jupyter files in /examples since most pyecharts users are coming from data science background. Just make things easier

* Hah，Maybe you can make a `PR` about `add some examples for jupyter`.
* We are accept your suggestion. But the most important thing is we also welcome more developer can join us, make `pyecharts` better and better. :smile:

**Comment by yinchuandong** [comment]
> > > @yinchuandong
> > > 
> > > * Please read source code. https://github.com/pyecharts/pyecharts/blob/master/example/commons.py#L101
> > > * Have any others bugs or errors?
> > > 
> > > ```python
> > > class _Faker:
> > >     def choose(self):
> > >         pass
> > > 
> > > 
> > > Faker = _Faker()
> > > ```
> > 
> > 
> > Thanks @sunhailin-Leo , can you also pls update the official documents? https://pyecharts.org/#/zh-cn/demo_data?id=faker. It's a little bit confusing. BTW, it would be much better if you can provide jupyter files in /examples since most pyecharts users are coming from data science background. Just make things easier
> 
> * Hah，Maybe you can make a `PR` about `add some examples for jupyter`.
> * We are accept your suggestion. But the most important thing is we also welcome more developer can join us, make `pyecharts` better and better. 😄

Thanks. I'm more than happy to add some examples and create a more detailed README file when I have time. I have recommended pyecharts to most of my friends and they all love it! One limitation is that the comments and documentations in python code are Chinese, which is not user-friendly to foreign people. In spite of this, they still like it and try to migrate from Plotly to pyecharts. Really hope you can consider writing English documentations in python source code.

**Comment by chenjiandongx** [comment]
we hope there are more developers can help us to maintain documents. PR always welcome
