### ISSUE TITLE
Map下能否分段过渡颜色

### ISSUE THREAD

**Issue by BlankerL** [pyecharts/pyecharts#1256]
**问题**
根据[VisualMapOpts](https://pyecharts.org/#/zh-cn/global_options?id=visualmapopts%ef%bc%9a%e8%a7%86%e8%a7%89%e6%98%a0%e5%b0%84%e9%85%8d%e7%bd%ae%e9%a1%b9)Map下能够设定piece每段对应的max、min以及color，但是color只能够指定颜色，而无法指定range_color，请问能否增加功能指定range_color？

**运行环境（系统环境及 pyecharts 版本）**
Windows 10
pyecharts >= 1.3.1

**代码及截图**
![image](https://user-images.githubusercontent.com/24969376/61235930-486cb800-a769-11e9-9b8f-b63b7694adc2.png)
该区域的颜色为
```python3
range_color = ['#BB5E00', '#FFBB77', '#84C1FF', '#004B97']
```
中间会经过一段灰色区域，如果能够指定为

```python3
pieces = {
    {'min': 40, 'max': 50, 'range_color': ['#BB5E00', '#FFBB77']},
    {'min': 50, 'max': 60, 'range_color': ['#84C1FF', '#004B97']}
}
```
则颜色可以分为两段，不需要经过灰色区域（颜色直接在间断点跳跃，而不是渐变）

不知道是否能够增加此功能？

**Comment by chfw** [comment]
试试这个 pyecharts-extras: ChoroplethMap

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts-extras

**Comment by chfw** [comment]
version 0.3 可以用。请参照 examples.

**Comment by BlankerL** [comment]
> version 0.3 可以用。请参照 examples.

似乎只能为某一个tag添加legend以及颜色，而不能针对某个区间所有内容都填充渐变色。

**Comment by BlankerL** [comment]
> version 0.3 可以用。请参照 examples.

examples中添加颜色的是字符串型的，而连续型的数值填充颜色时使用的是渐变色。

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts-extras/blob/master/pyecharts_extras/choropleth_map.py#L41

**Comment by chfw** [comment]
你需要自己的visualmap

**Comment by BlankerL** [comment]
> 你需要自己的visualmap

ChoroplethMap是给字符型的值（如'A', 'B'）指定颜色。

我希望实现的功能是给连续型的值（如[40, 60]区间）指定颜色，其中：[40, 50]映射为渐变色['#BB5E00', '#FFBB77']，[50, 60]映射为渐变色['#84C1FF', '#004B97']。

我将数据导入ChoroplethMap，似乎没有可行的方案能实现这个功能，在导入ChoroplethMap之后，需要参数choropleth_legend，但是我并不需要将每一个数值都设定为一个单独的legend，而使用ChoroplethMap之后，VisualMap功能和Map下的VisualMap并无区别。

**Comment by chenjiandongx** [comment]
是否是这个

![image_1](https://user-images.githubusercontent.com/19553554/61308395-c17c1600-a822-11e9-861a-77947847e53b.png)

**Comment by BlankerL** [comment]
> 是否是这个
> 
> ![image_1](https://user-images.githubusercontent.com/19553554/61308395-c17c1600-a822-11e9-861a-77947847e53b.png)

希望能够实现的功能是，在分段型的基础上，每一个区间的颜色是渐变色，而不是指定的某一种颜色。

**Comment by chenjiandongx** [comment]
@BlankerL 明白 不过目前好像还没看过 Echarts 有这个功能

**Comment by canvas-J** [comment]
当我给“Map-VisualMap（分段型）”设置自定义颜色时，参数pieces设置如下（我的数据是连续型的，需要分段，为了更好看，我想设置些自定义颜色）

`            visualmap_opts=opts.VisualMapOpts(is_piecewise=True,
                 pieces=[
                     {"min": "15", "max": "28", "label": "15%-28%", "color": '#bee1e5'},
                     {"min": "29", "max": "42", "label": "29%-42%", "color": "#9dd6f4"},
                     {"min": "43", "max": "56", "label": "43%-56%", "color": "#deeac2"},
                     {"min": "57", "max": "70", "label": "57%-70%", "color": "#fedbc7"},
                     {"min": "71", "max": "85", "label": "71%-85%", "color": "#f7ba8e"},
                 ],
             )`

出了小问题：1、图例的颜色都是灰色的，没有像默认配色时和地图区域颜色对应；
2、然后我根据文档尝试修改了这个设置：

`legend_opts=opts.LegendOpts(is_show=False, pos_right=0), # 竟然修改并且只修改了标题`

这两点算是Bug嘛，还是有设置我还没摸熟？

**Comment by wjdiadijai** [comment]
非常赞同，或者是否渐变色能否设置为指数单位，比如10/100/1000这样
