### ISSUE TITLE
timeline bug

### ISSUE THREAD

**Issue by 276077345** [pyecharts/pyecharts#1257]
**问题**
timeline里面的图加graphic_opts无效

**运行环境（系统环境及 pyecharts 版本）**
win10，pyecharts 1.0.0

**Comment by sunhailin-Leo** [comment]
@276077345 
* 你可以再看看其他配置有没有问题。

**Comment by sunhailin-Leo** [comment]
@276077345 
* New PR already fix this bug. https://github.com/pyecharts/pyecharts/pull/1260
