### ISSUE TITLE
Scatter y轴数据无法正常显示

### ISSUE THREAD

**Issue by pinckCat** [pyecharts/pyecharts#1258]
**问题**
scatter y轴坐标无正常显示，.add_yaxis()方法中data = itertools.chain的锅

**运行环境（系统环境及 pyecharts 版本）**
win10 python3.6 pyecharts 1.2

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@pinckCat 什么意思？

**Comment by pinckCat** [comment]
![image](https://user-images.githubusercontent.com/26075333/61510582-176cdb80-aa26-11e9-8d1d-2a8444fe4698.png)

Scatter.py 中的add_yaxis 方法，当y轴数据为['9.00001', '12.999321']类似这种数据，scatter图y轴只显示对应数据的第一位的值——[9, 1]

**Comment by sunhailin-Leo** [comment]
@pinckCat y 轴的 type 设置成 value 了么？
