### ISSUE TITLE
page.render bug

### ISSUE THREAD

**Issue by pinckCat** [pyecharts/pyecharts#1259]
**问题**
page.render 方法没有返回生成图表html地址导致使用make_snapshot方法报错

**运行环境（系统环境及 pyecharts 版本）**
win10 python3.6 pyecharts1.2

**代码及截图**

**Comment by sunhailin-Leo** [comment]
* 这是啥？
![image](https://user-images.githubusercontent.com/17564655/61356894-d64fbc80-a8a9-11e9-8ee2-cdba294a7f4d.png)

**Comment by pinckCat** [comment]
page.py
![image](https://user-images.githubusercontent.com/26075333/61358345-b241aa80-a8ac-11e9-9734-2c3c90283064.png)

**Comment by sunhailin-Leo** [comment]
* 如果你急着用的话，就先改一下源码。
* 这可能是当时忘记加了

**Comment by pinckCat** [comment]
> * 如果你急着用的话，就先改一下源码。
> * 这可能是当时忘记加了

好的，感谢回复

**Comment by chenjiandongx** [comment]
#1291
