### ISSUE TITLE
x轴数据显示不全

### ISSUE THREAD

**Issue by weix0409** [pyecharts/pyecharts#1262]
**问题**
如图，x轴划分的比较多，后面一部分数据不显示，大佬们帮忙看看

**运行环境（系统环境及 pyecharts 版本）**
pycharm2018.3，window10 64专业版，pyecharts1.3.1，python3.7.0

**代码及截图**
![image](https://user-images.githubusercontent.com/53069993/61510584-176cdb80-aa26-11e9-8cae-d312e245dfe5.png)
![image](https://user-images.githubusercontent.com/53069993/61510595-218eda00-aa26-11e9-885e-f9424b4fa5f9.png)
![image](https://user-images.githubusercontent.com/53069993/61510667-716da100-aa26-11e9-8a22-9864c3ec1abd.png)

**Comment by sunhailin-Leo** [comment]
@weix0409 你的 x 轴的 type 是 category 还是 value？

**Comment by weix0409** [comment]
明白了，您一提点，我去看了下自己传的参数，是直接从数据库返回的查询结果，具体类型是装着小tuple的tuple，处理了一下果然正常了，谢谢了
 






------------------ 原始邮件 ------------------
发件人: "LeoSun"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 中午1:23
收件人: "pyecharts/pyecharts"<pyecharts@noreply.github.com>;
抄送: "劳资最烦起昵称了"<943520640@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [pyecharts/pyecharts] x轴数据显示不全 (#1262)




@weix0409 你的 x 轴的 type 是 category 还是 value？
