### ISSUE TITLE
数据断点 tooltips显示过多

### ISSUE THREAD

**Issue by RoyWinchester** [pyecharts/pyecharts#1263]
**问题**

用excel转的数据，中间有些数据分时间段显示的，比如从x轴从1月1日开始，但是数据从9月1日才开始有数据。
如果把空数据删除的话，会从X轴[0]开始分配；
如果不把空数据删除，append(None)的话，就会变成[日期,null]
想要自己append((日期，数据))进行绑定，编译结束后会变成(x轴日期(日期，数据))

**运行环境（系统环境及 pyecharts 版本）**

Windows系统
github首页给出的pyecharts版本

**代码及截图**
![505374f0fd47728c85bba1063b23dc1](https://user-images.githubusercontent.com/22544675/61577002-292cac80-ab14-11e9-96e1-d77429dec5c4.png)
![7ea54fcd0071959aa7887e2573193eb](https://user-images.githubusercontent.com/22544675/61577003-2b8f0680-ab14-11e9-844e-37d349c61e6b.png)
![d4e7e59f6072667345ca4773d168e7d](https://user-images.githubusercontent.com/22544675/61577007-3184e780-ab14-11e9-9645-d41fddbc47ea.jpg)

**Comment by sunhailin-Leo** [comment]
@RoyWinchester 可以尝试 tooltip 的 formatter。如果数据为 null 则显示其他内容或者不显示。
