### ISSUE TITLE
pyecharts.charts.Geo.add_coordinate 后 render 时，value 显示为自定义地点的经度

### ISSUE THREAD

**Issue by billchenchina** [pyecharts/pyecharts#1265]
**问题**

`pyecharts.charts.Geo.add_coordinate` 后 render 时，value 显示为自定义地点的经度

**运行环境（系统环境及 pyecharts 版本）**

Ubuntu 18.04.2 LTS
Python 3.6.7
pyecharts 1.3.1

**代码及截图**
```python
from example.commons import Faker
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.globals import GeoType

mymap = Geo()
mymap.add_schema(maptype="china")
mymap.add_coordinate("天安门", 116.3886342, 39.9087306)
mymap.add("王小明", [("天安门", 100)])
mymap.render("/usr/share/nginx/html/render.html")
```
预期输出：
```
王小明
天安门：100
```
实际输出：
![image](https://user-images.githubusercontent.com/7758042/61630947-a21a3880-acbb-11e9-88ce-a9aaf8b006cc.png)

看了下，和 #1196 有些类似

**Comment by billchenchina** [comment]
也可能是我理解有问题，请问一下文档中`Geo.add` 中 `data_pair: Sequence` 这一项具体是做什么的？

**Comment by sunhailin-Leo** [comment]
@billchenchina 传入数据的

**Comment by sunhailin-Leo** [comment]
@billchenchina 如果要实现自定义显示的话，使用 tooltip 的 formatter 编写 js 的回调函数进行自定义。

**Comment by chfw** [comment]
```
g.add("", [("London", 0), ("Bazel", 0)],
    type_=ChartType.EFFECT_SCATTER, color="red",
    label_opts=opts.LabelOpts(formatter="{b}")) # <--- 加这一个设置选项
```

具体用法：
https://github.com/pyecharts/geopython-2019-talk/blob/master/flying-plane.ipynb
