### ISSUE TITLE
jupyter lab 0.35.4 下 render_notebook()无法显示echarts结果图  ，但可以render()

### ISSUE THREAD

**Issue by ifcheung2012** [pyecharts/pyecharts#1266]
**问题**
jupyter lab 0.35.4 下 render_notebook()无法显示echarts结果图  ，但可以render()
我也是这个问题 重装N遍 都不行；
 issue里关于render_notebook()的解决方法都试遍了，也不行。

**运行环境（系统环境及 pyecharts 版本）**
python 3.7.3
pyecharts 1.3.1
windows 10
chrome 75.0.3770.142（正式版本） （64 位）
anaconda 1.9.7
jupyter lab 0.35.4

**代码及截图**
  
![image](https://user-images.githubusercontent.com/2020778/61626056-cb809780-acae-11e9-82f8-21e2829bdf17.png)

**Comment by sunhailin-Leo** [comment]
@ifcheung2012 
* 1、有修改 CurrentConfig 么？
* 2、确保你的网络状况可以连接。
* 3、出现 `echarts is not defined` 的情况基本上都是 js 未加载成功

**Comment by ifcheung2012** [comment]
> @ifcheung2012
> 
> * 1、有修改 CurrentConfig 么？
> * 2、确保你的网络状况可以连接。
> * 3、出现 `echarts is not defined` 的情况基本上都是 js 未加载成功

from pyecharts.charts import Bar

from pyecharts.globals import CurrentConfig,NotebookType
from pyecharts import options as opts

CurrentConfig.NOTEBOOK_TYPE=NotebookType.JUPYTER_LAB
# V1 版本开始支持链式调用
bar = (
    Bar()
    .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
    .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
    .set_global_opts(title_opts=opts.TitleOpts(title="某商场销售情况"))
)

bar.render_notebook()

使用的 是示例代码

**Comment by ifcheung2012** [comment]
![image](https://user-images.githubusercontent.com/2020778/61681794-8f4a4700-ad41-11e9-8150-132c837106ec.png)

**Comment by sunhailin-Leo** [comment]
@ifcheung2012 
* 加一个 `bar.load_javascript()` 看看？

**Comment by ifcheung2012** [comment]
> @ifcheung2012
> 
> * 加一个 `bar.load_javascript()` 看看？
> * 你的 jupyter lab 是本地还是服务器的？

![image](https://user-images.githubusercontent.com/2020778/61684703-df7ad680-ad4c-11e9-9693-c2eb2ad355d4.png)
![image](https://user-images.githubusercontent.com/2020778/61684751-046f4980-ad4d-11e9-89cd-feef574609d5.png)

是本地的 win10下单机安装 不是服务器安装客户端访问的模式

**Comment by sunhailin-Leo** [comment]
@ifcheung2012 你浏览器能打开这个链接嘛？https://assets.pyecharts.org/assets/echarts.min.js

**Comment by sunhailin-Leo** [comment]
@ifcheung2012 你先 load_javascript 然后，在 render_notebook() 分开

**Comment by ifcheung2012** [comment]
> @ifcheung2012 你先 load_javascript 然后，在 render_notebook() 分开

可以打开链接：
    
![image](https://user-images.githubusercontent.com/2020778/61685297-e86ca780-ad4e-11e9-8efe-39dddcf5a043.png)

load_javascript():

![image](https://user-images.githubusercontent.com/2020778/61685286-e0ad0300-ad4e-11e9-8059-259e4a7f06ee.png)

**Comment by sunhailin-Leo** [comment]
> > @ifcheung2012 你先 load_javascript 然后，在 render_notebook() 分开
> 
> 可以打开链接：
> 
> ![image](https://user-images.githubusercontent.com/2020778/61685297-e86ca780-ad4e-11e9-8efe-39dddcf5a043.png)
> 
> load_javascript():
> 
> ![image](https://user-images.githubusercontent.com/2020778/61685286-e0ad0300-ad4e-11e9-8059-259e4a7f06ee.png)

然后 render_notebook() 呢？

**Comment by ifcheung2012** [comment]
> > > @ifcheung2012 你先 load_javascript 然后，在 render_notebook() 分开
> > 
> > 
> > 可以打开链接：
> > ![image](https://user-images.githubusercontent.com/2020778/61685297-e86ca780-ad4e-11e9-8efe-39dddcf5a043.png)
> > load_javascript():
> > ![image](https://user-images.githubusercontent.com/2020778/61685286-e0ad0300-ad4e-11e9-8059-259e4a7f06ee.png)
> 
> 然后 render_notebook() 呢？

非常感谢  ！

**Comment by yinchuandong** [comment]
@sunhailin-Leo 这个问题你们有打算解决吗？非常的confusing，对用户太不友好了。我理想中的pyecharts应该是 一套代码在各个环境中都可以run, 不需要手动的去配置环境。你们已经做了99%的工作了，希望能把最后的1%做好。

**Comment by sunhailin-Leo** [comment]
@yinchuandong 我只能说，我们也判断不了你的编译器是什么。

**Comment by sunhailin-Leo** [comment]
@yinchuandong 而且我们也没有去要求手动配置环境吧？只不过是在渲染前需要补一行 `load_javascript` 以及指定一下当前 notebook 的类型是什么而已。

**Comment by yinchuandong** [comment]
> @yinchuandong 而且我们也没有去要求手动配置环境吧？只不过是在渲染前需要补一行 `load_javascript` 以及指定一下当前 notebook 的类型是什么而已。

从作者的角度上看当然非常容易，但是希望能从用户的角度上想一下。我身边三四个朋友，每一个人刚开始用pyecharts的时候都遇到过各种问题，需要去查issues。另外 `load_javascript`需要和`render_notebook`在不同block才能work, 否则就显示不了。这个点并没有在readme上提示用户，正常编程思维都不会觉得在同一个block会有什么问题。另外我不明白为何要手动的调用`load_javascript`， 如果真的要调用，也应该是在import的时候就自动调用吧，用`bar.load_javascript`并不是一个很优雅的方式，因为只需要调用一次就可以了。针对user-friendly这一点，真心希望你们可以参考下Plotly, 可能遇到的常见的问题都写下来了， 比如说jupyter Lab 的支持 [https://github.com/plotly/plotly.py#jupyterlab-support-python-35](https://github.com/plotly/plotly.py#jupyterlab-support-python-35).

**Comment by sunhailin-Leo** [comment]
@yinchuandong 
* 1、在遇到问题之前，有认真看过文档嘛？
* 2、如果你不明白 `load_javascript` 是干什么的，不应该去看看背后的实现方式嘛？
* 3、问题我们自然有收集。对于 notebook 的支持，我们在 README.md 以及文档里面都有提到。
    * 除了 jupyter notebook 和 jupyter lab 之外，我们还支持 nteract 和 zeppelin。

**Comment by chenjiandongx** [comment]
@yinchuandong 

我在这里解释一下原因吧

jupyterLab 对运行 js 的支持并不是那么友好，jupyter notebook 相比下就好多了。

在 notebook 我可以直接在 html 中直接 import 运行 pyecharts 所需要的 .js 文件（利用 requireJs），所以 notebook 用户不用关心资源引用问题，直接 render_notebook 即可。

但是这问题在 jupterLab 中就变得复杂了，如果需要运行 js 需要自己写扩展插件，或者在代码中强行嵌套导入语句。所以 load_javascript() 中其实是生成一段 js 代码写入到 cell 中。

Q: 为什么 `load_javascript` 和 `render_notebook` 需要在不同的 block?
A: 这是 notebook 的内联机制，其实本质上我们是返回了带有 `_html_`, `_javascript_` 对象的 class。notebook 会自动去调用这些方案，类似于 `magic_function`。

Q：为什么是基于 chart 而不是 global 层的？
A:  因为我们希望资源是按需引入的，pyecharts 总共有 400+ 的 .js 资源文件，而基础的图（如 bar）只需要导入 echarts.js 即可，但其他图有自己需要额外引用的资源。所以似乎也就没有必要为在全局引入 10M+ 的 js。

Q: 文档缺失？
A: 我们的责任，为此表示道歉，我们在尽量维护和完善文档，但毕竟个人精力还是有限，也希望有更多的开发者能够帮助我们来完成这件事情。

**Comment by yinchuandong** [comment]
@chenjiandongx 谢谢回答！其实我所有的问题都来自于实际使用中，虽然没有实际统计过，但是可能只有10%的人会愿意遇到问题的时候提出issue。尤其是从plotly迁移过来的人。其实plotly能满足绝大部分需求，只是没有pyecharts的动画好看，所以很多人在刚开始使用pyecharts遇到了问题，就自然而然的会觉得pyecharts不成熟，因此放弃使用pyecharts。这样一来其实缺失了很多用户。我也是最近才知道pyecharts是个人项目， 所以非常感激作者的贡献。我本人也是非常喜欢pyecharts的，所以希望pyecharts能变得更好用，而不是让把问题留给用户。

针对jupyter lab这一点的支持上，我个人觉得Plotly的解决方案还是不错的，直接 install extension. 这样一来，代码层面就可以保持一致了。 另外，plotly 提供offline 版本，这点其实真的很重要，尤其是针对国外的用户。我自己确实是没时间参与到pyecharts的开发中，我只能从用户的角度提供一些反馈。希望能对pyecharts未来的开发有帮助, 谢谢！
![image](https://user-images.githubusercontent.com/3993196/62273371-c080f080-b480-11e9-8802-b9e54d7d240c.png)

**Comment by chenjiandongx** [comment]
@yinchuandong 

以前我们用的也是插件机制，不过后来发先这种方式不太好

1. 管理不太方便，升级经常出现问题
2. 需要权限，部分开发者可能没有将插件安装到系统全局的权限

后来我们改用了动态引用资源的方式，目前是支持 offline 的。参考 https://pyecharts.org/#/zh-cn/assets_host

**Comment by Kimmy040** [comment]
> > > @ifcheung2012 你先 load_javascript 然后，在 render_notebook() 分开
> > 
> > 
> > 可以打开链接：
> > ![image](https://user-images.githubusercontent.com/2020778/61685297-e86ca780-ad4e-11e9-8efe-39dddcf5a043.png)
> > load_javascript():
> > ![image](https://user-images.githubusercontent.com/2020778/61685286-e0ad0300-ad4e-11e9-8059-259e4a7f06ee.png)
> 
> 然后 render_notebook() 呢？

hi，我试了load_javascript()，但依旧render_notebook()无显示。可以帮忙看下嘛？
![Uploading 截屏2024-03-15 12.10.29.png…]()

**Comment by mnjun9527** [comment]
我也遇到同样的问题，而且不是一台电脑，我几台电脑都是这样， 并且百度搜索的方法  和这些楼层的方法都没能解决这个问题，真是要命![Uploading 456.png…]()

**Comment by mnjun9527** [comment]
@sunhailin-Leo  大佬救救我吧

**Comment by mnjun9527** [comment]
![123](https://github.com/pyecharts/pyecharts/assets/165643276/b856022d-24ad-417a-8e81-9c94bd585617)
![456](https://github.com/pyecharts/pyecharts/assets/165643276/1cdf5259-9511-4ebb-bc07-1dc217f23bc3)

**Comment by mnjun9527** [comment]
@chenjiandongx  作者大佬 打扰求助了    我是jupyter notebook环境
