### ISSUE TITLE
HTML组件Table无法与其他图表组合到Page输出render 

### ISSUE THREAD

**Issue by linyhuan** [pyecharts/pyecharts#1267]
**问题**

> HTML组件Table无法与其他图表组合到Page输出render，报错：'Table' object has no attribute 'dump_options' 

**运行环境（系统环境及 pyecharts 版本）**

win10
Python 3.6.8
pyecharts 1.3.1

**代码及截图**

 `
from pyecharts.components import Table
from pyecharts.options import ComponentTitleOpts
from pyecharts.charts import Bar,Page

def table_base() -> Table:
    table = Table()

    headers = ["City name", "Area", "Population", "Annual Rainfall"]
    rows = [
        ["Brisbane", 5905, 1857594, 1146.4],
        ["Adelaide", 1295, 1158259, 600.5],
    ]
    table.add(headers, rows).set_global_opts(
        title_opts=ComponentTitleOpts(title="Table-我是主标题", subtitle="我是副标题支持换行哦")
    )
    return table

def bar_base() ->Bar:

    bar = Bar()
    bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    # render 会生成本地 HTML 文件，默认会在当前目录生成 render.html 文件
    # 也可以传入路径参数，如 bar.render("mycharts.html")
    return bar

if __name__ == '__main__':
    page=Page()
    page.add(table_base(),bar_base())
    page.render()
`

报错：
`
    Traceback (most recent call last):
      File "D:/admin/python/venv/test.py", line 30, in <module>
        page.render()
      File "C:\Program Files\Python36\lib\site-packages\pyecharts\charts\composite_charts\page.py", line 73, in render
        self._prepare_render()
      File "C:\Program Files\Python36\lib\site-packages\pyecharts\charts\composite_charts\page.py", line 63, in _prepare_render
        c.json_contents = c.dump_options()
    AttributeError: 'Table' object has no attribute 'dump_options'
`

**Comment by sunhailin-Leo** [comment]
@linyhuan 
* 目前是无法组合。

**Comment by linyhuan** [comment]
我自己找到了组合的方法：

`
#!coding=utf-8

import os
import re

def add_table(page,table,path='render.html'):
    '''
    :param page: 已经添加有图表的page，也可以基础图表或者grid
    :param table: 需要添加的table
    :param path: 输出的文件名
    :return: None
    '''
    table_file=table.render('my_table.html')  ## 保存table文件
    f = open(table_file, mode='r', encoding='utf-8')    ##读取table文件html
    table_html = f.read()
    f.close()
    os.remove(table_file)   ##删除文件
    table_body=re.search('<body>\n([\S\s]*?)\n</body>',table_html).group(1)  ##获取table body标签内的html
    page_html=page.render_embed()   ##page的html
    page_new=page_html.replace('</body>', table_body + '\n</body>')  ## 在page 后加入table body
    with open(path, "w", encoding='utf-8') as f:  ##输出html
        f.write(str(page_new))
        f.close()
`
##example：
if name == 'main':
   bar=bar_base()
   table=table_base()
   add_table(bar,table)

**Comment by kevin-zsj** [comment]
> @linyhuan
> 
> * 目前是无法组合。

同样需要此功能。

**Comment by gavingu1128** [comment]
请问有参数可以设置table的行高列宽吗

**Comment by sailf** [comment]
> 请问有参数可以设置table的行高列宽吗

同问 以及设置table的css样式

**Comment by chenjiandongx** [comment]
新版本已提供该功能

**Comment by wzkzs** [comment]
> 新版本 v1.5.0 已提供该功能

没有提供，还是会报错

**Comment by LZC6244** [comment]
> > 新版本 v1.5.0 已提供该功能
> 
> 没有提供，还是会报错

+1
