### ISSUE TITLE
jupyter notebook无法显示图表

### ISSUE THREAD

**Issue by imwaco** [pyecharts/pyecharts#1268]
**问题**
jupyter notebook无法显示图表；
已经试过各种重装的方法，但不知为什么在jupyter扩展里找不到跟pyecharts相关的；
不知道是不是因为这个原因导致的无法显示图表？

**运行环境（系统环境及 pyecharts 版本）**
1、Mac OS
2、pyecharts 1.3
3、jupyter 1.0

**代码及截图**

![image](https://user-images.githubusercontent.com/4379284/61847303-c6089480-aedc-11e9-9a57-2a0e808e7431.png)

```
from pyecharts import options as opts
from pyecharts.charts import Bar,Line,Page
from pyecharts.globals import ThemeType

def get_exception_daily_line():
exception_daily = exception.get_exception_daily()
exception_daily_line = Line()

exception_daily_line.width = '1600px'
exception_daily_line.height = '600px'
exception_daily_line.set_global_opts(
        title_opts=opts.TitleOpts(title="xxx占比图"),
        yaxis_opts=opts.AxisOpts(name="xxx比例"),
        xaxis_opts=opts.AxisOpts(name="date"),
        datazoom_opts = opts.DataZoomOpts())
exception_daily_line.set_series_opts(
    markarea_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(type_="average", name="平均值")]))
exception_daily_line.add_xaxis(list(exception_daily.index))
exception_daily_line.add_yaxis('6',list(((exception_daily.exception_all/exception_daily.vm_daily)*100).round(2).values),is_selected=True,is_smooth=True,
                    markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(type_="average")])                        )
exception_daily_line.add_yaxis('1',list(((exception_daily.exception_pic/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)
exception_daily_line.add_yaxis('2',list(((exception_daily.exception_camera/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)
exception_daily_line.add_yaxis('3',list(((exception_daily.exception_trading/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)
exception_daily_line.add_yaxis('4',list(((exception_daily.exception_face/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)
exception_daily_line.add_yaxis('5',list(((exception_daily.exception_others/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)

print('1-----------------------------')
exception_daily_line.render_notebook()
exception_daily_line
page = Page()
page.add(exception_daily_line)
page.render_notebook()
print('2-----------------------------')
get_exception_daily_line()
```
--------
尝试了各种调用方法都不能在notebook中显示。。但在pycharm中实际上是可以正常显示图表的。

**Comment by imwaco** [comment]
补充下是，代码放在其pycharm里的时候是可以正常生成图表的。

‪‎‭‫‬‭‏‍‮‬⁠‌‪‫‏​‎‫‭‭‎‏‎‎from pyecharts import options as opts
from pyecharts.charts import Bar,Line,Page
from pyecharts.globals import ThemeType

def get_exception_daily_line():
    exception_daily = exception.get_exception_daily()
    exception_daily_line = Line()
    
    exception_daily_line.width = '1600px'
    exception_daily_line.height = '600px'
    exception_daily_line.set_global_opts(
            title_opts=opts.TitleOpts(title="xxx占比图"),
            yaxis_opts=opts.AxisOpts(name="xxx比例"),
            xaxis_opts=opts.AxisOpts(name="date"),
            datazoom_opts = opts.DataZoomOpts())
    exception_daily_line.set_series_opts(
        markarea_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(type_="average", name="平均值")]))
    exception_daily_line.add_xaxis(list(exception_daily.index))
    exception_daily_line.add_yaxis('6',list(((exception_daily.exception_all/exception_daily.vm_daily)*100).round(2).values),is_selected=True,is_smooth=True,
                        markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(type_="average")])                        )
    exception_daily_line.add_yaxis('1',list(((exception_daily.exception_pic/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)
    exception_daily_line.add_yaxis('2',list(((exception_daily.exception_camera/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)
    exception_daily_line.add_yaxis('3',list(((exception_daily.exception_trading/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)
    exception_daily_line.add_yaxis('4',list(((exception_daily.exception_face/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)
    exception_daily_line.add_yaxis('5',list(((exception_daily.exception_others/exception_daily.vm_daily)*100).round(2).values),is_selected=False,is_smooth=True)
    
    print('1-----------------------------')
    exception_daily_line.render_notebook()
    exception_daily_line
    page = Page()
    page.add(exception_daily_line)
    page.render_notebook()
    print('2-----------------------------')
    
get_exception_daily_line()

**Comment by sunhailin-Leo** [comment]
@imwaco 
* 1、看下你的 jupyter notebook 在浏览器控制台有没有出现什么异常。
* 2、MarkDown 贴代码能排个版吗？

**Comment by imwaco** [comment]
> @imwaco
> 
> * 1、看下你的 jupyter notebook 在浏览器控制台有没有出现什么异常。
> * 2、MarkDown 贴代码能排个版吗？

react-dom.production.min.js
控制台提示这个文件404了。

![image](https://user-images.githubusercontent.com/4379284/61853954-a2027e80-aeef-11e9-91ff-322499e0140e.png)

其他的没看到有特别的异常。

**Comment by sunhailin-Leo** [comment]
@imwaco https://pyecharts.org/#/zh-cn/quickstart?id=jupyter-notebook 运行一下这个 demo 试试

**Comment by sunhailin-Leo** [comment]
@imwaco 画图的时候控制台有没有显示 类似 `echarts is not defined` 这种错？

**Comment by chfw** [comment]
1 有没有网络？
2 重启Jupiter 并等10分钟再看看
3 开一个新的notebook 运行一下

**Comment by imwaco** [comment]
> @imwaco 画图的时候控制台有没有显示 类似 `echarts is not defined` 这种错？

嗯，demo可以运行，没有其他的报错。

现在找到问题了，函数调用的时候，需要return返回结果才能正常显示。
