### ISSUE TITLE
转换地图相关数据为json时报格式错误

### ISSUE THREAD

**Issue by wuyajun2016** [pyecharts/pyecharts#1269]
**问题**
为啥使用地图时候，转换成json文件会报错，见截图

**运行环境（系统环境及 pyecharts 版本）**
windows+python3.6.5+pyecharts1.3.1

**代码及截图**
![image](https://user-images.githubusercontent.com/19677714/61856869-94e88e00-aef5-11e9-9ee6-91b5e8fb67e7.png)

**Comment by sunhailin-Leo** [comment]
@wuyajun2016 定位下问题？

**Comment by wuyajun2016** [comment]
@sunhailin-Leo 我把demo返回的json文件解析了下，有个地方json格式不对啊
![image](https://user-images.githubusercontent.com/19677714/61918983-315a7100-af86-11e9-9824-abdd682eda58.png)

**Comment by wuyajun2016** [comment]
找到文档了https://pyecharts.org/#/zh-cn/faq
