### ISSUE TITLE
柱状图存在多个y轴，指定不同颜色时，颜色会显示错位

### ISSUE THREAD

**Issue by idauno** [pyecharts/pyecharts#1270]
**问题**
柱状图存在多个y轴，指定不同颜色时，颜色会显示错位

**运行环境（系统环境及 pyecharts 版本）**
jupyternotebook 最新版pyecharts

**代码及截图**
.add_xaxis(xaxis_data=category)
    .add_yaxis(series_name='红色柱',
               is_selected = True,
               yaxis_data = red_bar, 
               color = 'RGB(207,0,15)',
               #红色
               label_opts= opts.LabelOpts(is_show = False))
    .add_yaxis(series_name= '蓝色柱',
               color = '#5a95bc',
               #蓝色
               yaxis_data=blue_bar, 
               label_opts= opts.LabelOpts(is_show = False))
    .add_yaxis(series_name= '蓝色柱2',
               color = '#5a95bc',
               #蓝色
               yaxis_data=blue_bar, 
               label_opts= opts.LabelOpts(is_show = False))

![image](https://user-images.githubusercontent.com/48389668/61865203-6672af00-af05-11e9-99a3-479e1302ea8f.png)

**Comment by sunhailin-Leo** [comment]
@idauno 
* 建议这样设置（如下）
![image](https://user-images.githubusercontent.com/17564655/61865540-fa447b00-af05-11e9-8d49-830028e06c79.png)
![image](https://user-images.githubusercontent.com/17564655/61865569-04667980-af06-11e9-92c6-4e514b1d6e44.png)
