### ISSUE TITLE
在指定横坐标添加数据

### ISSUE THREAD

**Issue by TiAmoPlus** [pyecharts/pyecharts#1274]
**问题**
我这里是想使用pandas数据，在pyecharts上做数据显示
数据有两组，横坐标是类别，比如示例代码的衣服的类别，毛衣，外套
但是两组的数据长度是不一样的，也就是比如有一组数据是没有毛衣的。
我看到数据的添加都是根据list添加的。
所以数据会错位。我就想能不能自己在指定位置添加数据的

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@TiAmoPlus 给个图描述一下，有点抽象

**Comment by sunhailin-Leo** [comment]
可以尝试新版本的代码。如果依旧出现该问题，请重新提 issue 并附上你的代码，thx～
