### ISSUE TITLE
使用Timeline播放多张直方图时，x轴固定为最后一张表的数据

### ISSUE THREAD

**Issue by notalkusecode** [pyecharts/pyecharts#1275]
**问题**
使用Timeline播放多张直方图时，x轴固定为最后一张表的数据

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
from example.commons import Faker
from pyecharts import options as opts
from pyecharts.charts import Bar, Timeline
tl = Timeline()
for i in range(2015, 2020):
    x = Faker.choose()
    print(i,x)
    bar = (
        Bar()
        .add_xaxis(x)
        .add_yaxis("商家A", Faker.values())
        .add_yaxis("商家B", Faker.values())
        .set_global_opts(title_opts=opts.TitleOpts("某商店{}年营业额".format(i)))
    )
    tl.add(bar, "{}年".format(i))
tl.render_notebook()
![图片](https://user-images.githubusercontent.com/35050970/62278368-84e32800-b47a-11e9-9c4e-dff722a091bc.png)

**Comment by sunhailin-Leo** [comment]
@notalkusecode 这个问题，是因为 timeline add 的时候没有将 xAxis 的相关配置更新过去。

**Comment by sunhailin-Leo** [comment]
如果需要急着用的可以先改源码。
修改地方: `timeline.py` line 75, 加上一行 `"xAxis": chart.options.get("xAxis"),`
![image](https://user-images.githubusercontent.com/17564655/62279923-924de180-b47d-11e9-84c9-f556f213fa13.png)

**Comment by notalkusecode** [comment]
> 
> 
> 如果需要急着用的可以先改源码。
> 修改地方: `timeline.py` line 75, 加上一行 `"xAxis": chart.options.get("xAxis"),`
> ![image](https://user-images.githubusercontent.com/17564655/62279923-924de180-b47d-11e9-84c9-f556f213fa13.png)

谢谢大佬

**Comment by chenjiandongx** [comment]
@sunhailin-Leo Waiting for a new PR.
