### ISSUE TITLE
Scatter plots incorrectly when xaxis < 1

### ISSUE THREAD

**Issue by joejoejoe1215** [pyecharts/pyecharts#1276]
**问题**
If the number for xaxis are small float ( possibly < 1, but I didn't test ), it will not plot correctly. Plz see screenshot below for details.

**运行环境（系统环境及 pyecharts 版本）**
python 3.6.7
pyecharts            1.3.1
centOS 7

**代码及截图**
```python
from example.commons import Faker
from pyecharts import options as opts
from pyecharts.charts import Scatter

(
	Scatter()
	.add_xaxis([i for i in range(0, 10)])
	.add_yaxis('y' ,[i * 10 for i in range (0, 10)])
	.set_global_opts(title_opts=opts.TitleOpts(title="Correct"))
).render('correct.html')

(
	Scatter()
	.add_xaxis([i / 10 for i in range(0, 10)])
	.add_yaxis('y' ,[i * 10 for i in range (0, 10)])
	.set_global_opts(title_opts=opts.TitleOpts(title="Wrong"))
).render('wrong.html')
```

![image](https://user-images.githubusercontent.com/20712769/62323140-9c1f1700-b474-11e9-85c3-e7657bb56aed.png)
![image](https://user-images.githubusercontent.com/20712769/62323156-a17c6180-b474-11e9-9357-f3824f100211.png)

**Comment by sunhailin-Leo** [comment]
@joejoejoe1215 
* Not a bug, just your configuration is wrong. You should make sure your `xaxis_opts` type is `value` not `category` (category is default value on `xaxis_opts.type_`)
![image](https://user-images.githubusercontent.com/17564655/62355145-03a29880-b541-11e9-9826-57c7d274e910.png)
![image](https://user-images.githubusercontent.com/17564655/62355152-08ffe300-b541-11e9-93e1-a6b08dd7baff.png)

**Comment by sunhailin-Leo** [comment]
* For convenient, i put the example code here:
```python
from pyecharts import options as opts
from pyecharts.charts import Scatter

(
   Scatter()
   .add_xaxis([i / 10 for i in range(0, 10)])
   .add_yaxis("y", [i * 10 for i in range(0, 10)])
   .set_global_opts(
        title_opts=opts.TitleOpts(title="Scatter-Base Example"),
        xaxis_opts=opts.AxisOpts(type_="value")
   )
)
```
