### ISSUE TITLE
官方文档中关于Django的使用中给出的index.html，后两个例子里ajax的函数名明明已经改为fetchData，但在调用时依然使用了getData

### ISSUE THREAD

**Issue by oldpiao** [pyecharts/pyecharts#1277]
<script>
        var chart = echarts.init(document.getElementById('bar'), 'white', {renderer: 'canvas'});

        $(
            function () {
                getData(chart);
                setInterval(fetchData, 2000);
            }
        );

        function fetchData() {
            $.ajax({
                type: "GET",
                url: "http://127.0.0.1:8000/demo2/bar",
                dataType: 'json',
                success: function (result) {
                    chart.setOption(result.data);
                }
            });
        }
    </script>

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chenjiandongx** [comment]
Fixed
