### ISSUE TITLE
请问可以实现标签每隔一个或两个显示标签嘛？

### ISSUE THREAD

**Issue by xiaohao890809** [pyecharts/pyecharts#1278]
**问题**
请问可以实现标签每隔一个或两个显示标签吗，有时候标签数字太多，挤在一起很难看？

**Comment by sunhailin-Leo** [comment]
@xiaohao890809 有具体的图或例子说明嘛？

**Comment by sunhailin-Leo** [comment]
* 如果有例子的话，请重新提 issue，并最好附上例子的图或者代码，thx～
