### ISSUE TITLE
graph 关系图表中，没有EffectOpts 配置

### ISSUE THREAD

**Issue by Alpaca-H** [pyecharts/pyecharts#1279]
在使用过程中发现graph图标中仅如下配置
![TIM截图20190811154717](https://user-images.githubusercontent.com/30536937/62831297-52da7e80-bc4f-11e9-9363-6717715a4957.png)
而在官方demo中graph是可以使用effectopts配置的，即动态涟漪
![Z LRKO94M在使用过程中发现graph图标中仅如下配置
![TIM截图20190811154717](https://user-images.githubusercontent.com/30536937/62831297-52da7e80-bc4f-11e9-9363-6717715a4957.png)
而在官方demo中graph是可以使用effectopts配置的，即动态涟漪
8Z_)Z4@7LU%M](https://user-images.githubusercontent.com/30536937/62831308-89b09480-bc4f-11e9-9bfa-0b71a15f986d.png)

请问在下一个版本中进行添加更新

**Comment by sunhailin-Leo** [comment]
@Alpaca-H 
* 你应该看清楚它这幅是 Graph + Lines 而不是单一 Graph

**Comment by Alpaca-H** [comment]
![image](https://user-images.githubusercontent.com/30536937/62862345-1b93cc80-bd38-11e9-870f-b86990b5e83a.png)
关系图与lines存在于pyecharts中，同样的箭头符号也可用使用symbol调出来，但的确不存在effectopts
