### ISSUE TITLE
无法使用自己构建的主题

### ISSUE THREAD

**Issue by FengHu1** [pyecharts/pyecharts#1280]
python:3.6.8 , notebook:jupyter lab , ubuntu18.04 , pyecharts:1.3.1

1.设置自带主题能成功：
from pyecharts.globals import ThemeType
line = (Line(init_opts=opts.InitOpts(theme=ThemeType.DARK)))

2.设置自己构建的主题失败：
terminal:
$cd pyecharts-assets
$python -m http.server

jupyter lab:
from pyecharts.globals import CurrentConfig
CurrentConfig.ONLINE_HOST = "http://127.0.0.1:8000/assets/"
from pyecharts.datasets import register_files
register_files({"HANDSOMESTYLE": ["themes/HANDSOME", "js"]})

line = (
    Line(init_opts=opts.InitOpts(width = "1500px",height = "720px",theme="HANDSOMESTYLE")))

此时显示初始主题。

请问是什么原因呢？和使用jupyter lab 有关吗？

**Comment by chenjiandongx** [comment]
正常 render 成 HTML 有问题吗
