### ISSUE TITLE
求一份Tornado的示例

### ISSUE THREAD

**Issue by Macile** [pyecharts/pyecharts#1282]
参考着文档里的其它三个web框架demo，但是就是搞不出来Tornado的示例了。求一份demo或者代码呗

**Comment by sunhailin-Leo** [comment]
@Macile 
* tornado 的话，后续会考虑给出 demo 的，不过可能目前暂时无法提供。

**Comment by Macile** [comment]
好的，多谢

**Comment by sunhailin-Leo** [comment]
* 2019-08-12 Updated

* Tornado Code
```python
import tornado.web
import tornado.ioloop
import tornado.httpserver

from pyecharts.charts import Bar
from pyecharts import options as opts


def bar_base() -> str:
    c = (
        Bar()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
        .add_yaxis("商家B", [15, 25, 16, 55, 48, 8])
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"))
    )
    return c.dump_options()


def set_default_header(self):
    # 后面的*可以换成ip地址，意为允许访问的地址
    self.set_header("Access-Control-Allow-Origin", "*")
    self.set_header("Access-Control-Allow-Headers", "x-requested-with")
    self.set_header("Access-Control-Allow-Methods", "POST, GET, PUT, DELETE")
    self.set_header("Content-Type", "application/json; charset=UTF-8")


class BarChart(tornado.web.RequestHandler):
    def data_received(self, chunk):
        pass

    def get(self):
        set_default_header(self)
        chart_result = bar_base()
        # 返回结果
        self.write(chart_result)
        self.finish()


class PageHandler(tornado.web.RequestHandler):
    def data_received(self, chunk):
        pass

    def get(self):
        self.render("index.html")


def make_app():
    return tornado.web.Application([
        (r"/", PageHandler),
        (r"/getBarChart", BarChart),
    ])


if __name__ == "__main__":
    port = 8889
    app = make_app()
    sockets = tornado.netutil.bind_sockets(port)
    http_server = tornado.httpserver.HTTPServer(app)
    http_server.add_sockets(sockets)
    print("Server Start Running!\nHost: {} Port: {}".format("127.0.0.1", port))
    tornado.ioloop.IOLoop.instance().start()
```

* HTML Code
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Awesome-pyecharts</title>
    <script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
</head>
<body>
    <div id="bar" style="width:1000px; height:600px;"></div>
    <script>
        $(
            function () {
                var chart = echarts.init(document.getElementById('bar'), 'white', {renderer: 'canvas'});
                $.ajax({
                    type: "GET",
                    url: "http://127.0.0.1:8889/getBarChart",
                    dataType: 'json',
                    success: function (result) {
                        chart.setOption(result);
                    }
                });
            }
        )
    </script>
</body>
</html>
```

**Comment by Macile** [comment]
，膜拜大佬。我就是群里的那个。
------------------ 原始邮件 ------------------
发件人: "LeoSun"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 晚上9:47
收件人: "pyecharts/pyecharts"<pyecharts@noreply.github.com>;
抄送: "铁甲小宝卡布达"<1446491417@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [pyecharts/pyecharts] 求一份Tornado的示例 (#1282)



 
 
2019-08-12 Updated
 
 
 
Tornado Code
 
  import tornado.web import tornado.ioloop import tornado.httpserver from pyecharts.charts import Bar from pyecharts import options as opts def bar_base() -> str:     c = (         Bar()         .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])         .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])         .add_yaxis("商家B", [15, 25, 16, 55, 48, 8])         .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"))     )     return c.dump_options() def set_default_header(self):     # 后面的*可以换成ip地址，意为允许访问的地址     self.set_header("Access-Control-Allow-Origin", "*")     self.set_header("Access-Control-Allow-Headers", "x-requested-with")     self.set_header("Access-Control-Allow-Methods", "POST, GET, PUT, DELETE")     self.set_header("Content-Type", "application/json; charset=UTF-8") class BarChart(tornado.web.RequestHandler):     def data_received(self, chunk):         pass     def get(self):         set_default_header(self)         chart_result = bar_base()         # 返回结果         self.write(chart_result)         self.finish() class PageHandler(tornado.web.RequestHandler):     def data_received(self, chunk):         pass     def get(self):         self.render("index.html") def make_app():     return tornado.web.Application([         (r"/", PageHandler),         (r"/getBarChart", BarChart),     ]) if __name__ == "__main__":     port = 8889     app = make_app()     sockets = tornado.netutil.bind_sockets(port)     http_server = tornado.httpserver.HTTPServer(app)     http_server.add_sockets(sockets)     print("Server Start Running!\nHost: {} Port: {}".format("127.0.0.1", port))     tornado.ioloop.IOLoop.instance().start()
  
HTML Code
  <!DOCTYPE html> <html> <head>     <meta charset="UTF-8">     <title>Awesome-pyecharts</title>     <script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>     <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script> </head> <body>     <div id="bar" style="width:1000px; height:600px;"></div>     <script>         $(             function () {                 var chart = echarts.init(document.getElementById('bar'), 'white', {renderer: 'canvas'});                 $.ajax({                     type: "GET",                     url: "http://127.0.0.1:8889/getBarChart",                     dataType: 'json',                     success: function (result) {                         chart.setOption(result);                     }                 });             }         )     </script> </body> </html>
