### ISSUE TITLE
Grid左右显示两张图时，无法同时添加DataZoom

### ISSUE THREAD

**Issue by ttinch** [pyecharts/pyecharts#1284]
**问题**
Grid左右显示两张图时，无法同时添加DataZoom
**运行环境（win7及 pyecharts 1.3.1）**
**代码及截图**
from pyecharts.charts import Bar, Grid
from pyecharts import options as opts
from example.commons import Faker

c1 = (
    Bar()
        .add_xaxis(Faker.days_attrs)
        .add_yaxis("商家A", Faker.days_values)
        .set_global_opts(
        title_opts=opts.TitleOpts(title="Bar-DataZoom1"),
        legend_opts=opts.LegendOpts(pos_left="20%"),
        datazoom_opts=opts.DataZoomOpts(pos_left="5%"),
    )
)
c2 = (
    Bar()
        .add_xaxis(Faker.days_attrs)
        .add_yaxis("商家B", Faker.days_values)
        .set_global_opts(
        title_opts=opts.TitleOpts(title="Bar-DataZoom2", pos_right="5%"),
        legend_opts=opts.LegendOpts(pos_right="20%"),
        datazoom_opts=opts.DataZoomOpts(pos_right="5%"),
    )
)
grid = (
    Grid(init_opts=opts.InitOpts(width='1000px'))
    .add(c1, grid_opts=opts.GridOpts(pos_right="55%"))
    .add(c2, grid_opts=opts.GridOpts(pos_left="55%"))
)
grid.render()

![image](https://user-images.githubusercontent.com/25173640/62930295-b7800f80-bdee-11e9-84e4-0dabc3aa79c1.png)

**Comment by sunhailin-Leo** [comment]
@ttinch 
* 这样子就可以了

```python
from pyecharts.charts import Bar, Grid
from pyecharts import options as opts
from example.commons import Faker

c1 = (
    Bar()
    .add_xaxis(Faker.days_attrs)
    .add_yaxis("商家A", Faker.days_values)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Bar-DataZoom1"),
        legend_opts=opts.LegendOpts(pos_left="20%"),
        datazoom_opts=[
            opts.DataZoomOpts(pos_left="5%", xaxis_index=0),
            opts.DataZoomOpts(pos_right="5%", xaxis_index=1)
        ],
    )
)
c2 = (
    Bar()
    .add_xaxis(Faker.days_attrs)
    .add_yaxis("商家B", Faker.days_values)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Bar-DataZoom2", pos_right="5%"),
        legend_opts=opts.LegendOpts(pos_right="20%"),
    )
)
grid = (
    Grid(init_opts=opts.InitOpts(width='1000px'))
    .add(c1, grid_opts=opts.GridOpts(pos_right="55%"))
    .add(c2, grid_opts=opts.GridOpts(pos_left="55%"))
)
grid.render("two_grid.html")

```

**Comment by sunhailin-Leo** [comment]
目前版本的还 Grid 中 多个 datazoom 都在第一张图里头去配，用列表的形式。

**Comment by zygcch** [comment]
这个有更新吗？Grid中只在第一个图里面配datazoom有点不方便，如果我需要第二个或者第三个启用datazoom就无法实现了。

**Comment by sunhailin-Leo** [comment]
> 这个有更新吗？Grid中只在第一个图里面配datazoom有点不方便，如果我需要第二个或者第三个启用datazoom就无法实现了。

你这种需求就没必要用 Grid 了，用 Page 也可以，没必要卡在一个布局模式上
