### ISSUE TITLE
pycharm2019.2下的notebook无法出图

### ISSUE THREAD

**Issue by heijigaoke** [pyecharts/pyecharts#1289]
**问题**
pycharm2019.2下的notebook使用pyecharts1.3.1无法出图,同样的代码去jupyter notebook下可以出图

**运行环境（系统环境及 pyecharts 版本）**
pycharm2019.2
pyecharts1.3.1

**代码及截图**
就是官方例子，不存在代码问题

**Comment by chenjiandongx** [comment]
我们不对 pycharm 的 notebook 环境做兼容性测试。

**Comment by charmby** [comment]
同样的问题！！！有什么解决办法吗？

**Comment by huweihuab** [comment]
同求指导。

> **问题** pycharm2019.2下的notebook使用pyecharts1.3.1无法出图,同样的代码去jupyter notebook下可以出图
> 
> **运行环境（系统环境及 pyecharts 版本）** pycharm2019.2 pyecharts1.3.1
> 
> **代码及截图** 就是官方例子，不存在代码问题
