### ISSUE TITLE
如何在v1.00+的版本中调用事件

### ISSUE THREAD

**Issue by HerbertLiuCN** [pyecharts/pyecharts#1292]
**问题**

我想请教一个关于Geo图问题：
简单讲是：我尝试用brushselect事件取调取bursh选中的数据，但是系统报错没有找到“geo.on"

具体陈述问题：
原本，想到使用这个方法来源于三个途径：
1. 原echarts里面有一个实例（https://www.echartsjs.com/gallery/editor.html?c=scatter-map-brush）第582行就是采用了事件调用数据的方法
2. pyecharts0.5版日志里面记录了事件在pyecharts.echarts.events里调取，但是目前貌似没有这个路径了

希望想前辈们请教的是：
1. 我只在base.py里面看到了有”on“的定义，但没找到events的列表，不知道开发组的前辈们能否指点一下如何调用events？
2. 如果这个方法目前不可行，还有没有方法调取brushu选中的数据，来复现示例里面的效果？
3. 如果events被”支持原生javascript“覆盖了，能不能请前辈们指教，可以去哪里找相关学习方法或示例？因为实在是不会javascript…

**运行环境（系统环境及 pyecharts 版本）**

win10+python3.6+pyecharts1.3.1+pycharm1.3

**代码及截图**

![image](https://user-images.githubusercontent.com/47863325/63210305-19a68080-c11f-11e9-8dce-bbf191595544.png)

**Comment by chenjiandongx** [comment]
目前 add_js_funcs 支持传入原生的 JS 代码，因为调用事件本身已经属于用于自定义的操作逻辑，必须使用 JS 来实现。所以，多学习一下 JS 吧。
