### ISSUE TITLE
没有网络安装使用时，打开html文件为空白

### ISSUE THREAD

**Issue by Dengnj** [pyecharts/pyecharts#1294]
**问题**

没有网络安装使用时，图标不显示打开html文件为空白

**运行环境（系统环境及 pyecharts 版本）**
win7
python3.6
pyechart1.4.0

**代码及截图**
![image](https://user-images.githubusercontent.com/25758944/63249734-a460ba00-c29c-11e9-8a03-507dbae8321a.png)

![image](https://user-images.githubusercontent.com/25758944/63249888-f99ccb80-c29c-11e9-9819-034ef8afc1cb.png)

按照官网操作后仍无效果
https://pyecharts.org/#/zh-cn/faq
Q: 如何离线使用 pyecharts？

**Comment by chfw** [comment]
需要更改 host name

**Comment by Dengnj** [comment]
> 需要更改 host name
是这样该么，有没有具体的code或样例
https://blog.csdn.net/zltalma/article/details/89452782

**Comment by sunhailin-Leo** [comment]
@Dengnj https://pyecharts.org/#/zh-cn/assets_host

**Comment by Dengnj** [comment]
@Dengnj https://pyecharts.org/#/zh-cn/assets_host 

搞定了
