### ISSUE TITLE
bar_stack堆叠图添加toolbox_opts，结果柱状图超出容器的高度

### ISSUE THREAD

**Issue by DongdongGui** [pyecharts/pyecharts#1297]
**问题**
bar_stack堆叠图添加toolbox_opts，结果柱状图超出容器的高度

**运行环境（系统环境及 pyecharts 版本）**
windows7  Python3.7  pyecharts #v1.4.0

**代码及截图**
from example.commons import Collector, Faker
from pyecharts import options as opts
from pyecharts.charts import Bar, Page
from pyecharts.commons.utils import JsCode
from pyecharts.globals import ThemeType

def bar_stack0() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values(), stack="stack1")
        .add_yaxis("商家B", Faker.values(), stack="stack1")
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-堆叠数据（全部）"),
                         toolbox_opts=opts.ToolboxOpts()
                         )
    )
    return c

bar_stack0().render()

![微信图片_20190822090309](https://user-images.githubusercontent.com/51312083/63478273-c5ebbc80-c4bb-11e9-9e89-9ee9fee2c527.png)

**Comment by chenjiandongx** [comment]
把 toolbox_opts 注释了看看

**Comment by DongdongGui** [comment]
注释了toolbox_opts，就不会超出容器，但是我想添加toolbox_opts，有没有解决办法

**Comment by laixiaoqiang-1** [comment]
这应该是个bug吧；我也是发现这种情况了，只要不用toolbox_opts就行；不知道多会能解决掉

**Comment by laixiaoqiang-1** [comment]
我解决掉了，具体看#1392。说实话，我没明白原理；
