### ISSUE TITLE
timeline t添加graphic_opts无效

### ISSUE THREAD

**Issue by DongdongGui** [pyecharts/pyecharts#1298]
**问题**
timeline t添加graphic_opts无效

**运行环境（系统环境及 pyecharts 版本）**
window7 Python3.7 pyecharts v1.4.0

**代码及截图**
from example.commons import Collector, Faker
from pyecharts import options as opts
from pyecharts.charts import Bar, Map, Page, Pie, Timeline
from pyecharts.commons.utils import JsCode

def timeline_bar() -> Timeline:
    x = Faker.choose()
    tl = Timeline()
    for i in range(2015, 2020):
        bar = (
            Bar()
            .add_xaxis(x)
            .add_yaxis("商家A", Faker.values())
            .add_yaxis("商家B", Faker.values())
            .set_global_opts(title_opts=opts.TitleOpts("某商店{}年营业额".format(i)))
        )
        tl.add(bar, "{}年".format(i))
    tl.add_schema(
        graphic_opts=[
            opts.GraphicGroup(
                graphic_item=opts.GraphicItem(
                    rotation=JsCode("Math.PI / 4"),
                    bounding="raw",
                    right=110,
                    bottom=110,
                    z=100,
                ),
                children=[
                    opts.GraphicRect(
                        graphic_item=opts.GraphicItem(
                            left="center", top="center", z=100
                        ),
                        graphic_shape_opts=opts.GraphicShapeOpts(
                            width=400, height=50
                        ),
                        graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                            fill="rgba(0,0,0,0.3)"
                        ),
                    ),
                    opts.GraphicText(
                        graphic_item=opts.GraphicItem(
                            left="center", top="center", z=100
                        ),
                        graphic_textstyle_opts=opts.GraphicTextStyleOpts(
                            text="pyecharts bar chart",
                            font="bold 26px Microsoft YaHei",
                            graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                                fill="#fff"
                            ),
                        ),
                    ),
                ],
            )
        ],
    )
    return tl

timeline_bar().render()

![微信图片_20190822091016](https://user-images.githubusercontent.com/51312083/63478699-5a0a5380-c4bd-11e9-826a-12ffdbbdd988.png)

**Comment by sunhailin-Leo** [comment]
@DongdongGui 
* 下一版将修复这个问题：
* 目前的示例图：
![image](https://user-images.githubusercontent.com/17564655/71703979-a45bf380-2e12-11ea-9115-50457b77f911.png)
![image](https://user-images.githubusercontent.com/17564655/71703998-ba69b400-2e12-11ea-85c2-bc378afd4044.png)
![image](https://user-images.githubusercontent.com/17564655/71703987-b047b580-2e12-11ea-919e-8344ec45deed.png)
![image](https://user-images.githubusercontent.com/17564655/71703999-c0f82b80-2e12-11ea-9458-4eb5c93b8922.png)
![image](https://user-images.githubusercontent.com/17564655/71704021-dc633680-2e12-11ea-8057-9dcdd11172a2.png)

**Comment by sunhailin-Leo** [comment]
@DongdongGui 1.6.1 Fix it! 🚀
