### ISSUE TITLE
How do I set x,y,z axis label name rather than just x,y,z

### ISSUE THREAD

**Issue by ywzhang188** [pyecharts/pyecharts#1300]
import random
from example.commons import Collector, Faker
from pyecharts import options as opts
from pyecharts.charts import Page, Scatter3D
C = Collector()
@C.funcs
def scatter3d_base() -> Scatter3D:
    data = test2
    c = (
        Scatter3D()
        .add("", data, xaxis3d_name='test',yaxis3d_name="fast",zaxis3d_name="maxdd")
        .set_global_opts(
            title_opts=opts.TitleOpts("Scatter3D-基本示例"),
            visualmap_opts=opts.VisualMapOpts(range_color=Faker.visual_color),
        )
    )
    return c
Page().add(*[fn() for fn, _ in C.charts]).render()

# I tried things above, but gave me traceback
Traceback (most recent call last):
  File "D:\anaconda3\envs\tensor-flow\lib\site-packages\IPython\core\interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-bfb27b36d3c0>", line 18, in <module>
    Page().add(*[fn() for fn, _ in C.charts]).render()
  File "<ipython-input-4-bfb27b36d3c0>", line 18, in <listcomp>
    Page().add(*[fn() for fn, _ in C.charts]).render()
  File "<ipython-input-3-6802b3cf7cf1>", line 10, in scatter3d_base
    .add("", data, xaxis3d_name='test' )
TypeError: add() got an unexpected keyword argument 'xaxis3d_name'

**Comment by chenjiandongx** [comment]
```python
.add("", data, xaxis3d_opts=opts.Axis3DOpts(name="my axis name"))
```

**Comment by ywzhang188** [comment]
> ```python
> .add("", data, xaxis3d_opts=opts.Axis3DOpts(name="my axis name"))
> ```

This works! thank you!
