### ISSUE TITLE
关于flask文档中的一些改进建议

### ISSUE THREAD

**Issue by highwindmx** [pyecharts/pyecharts#1301]
文档 -- Web 框架整合 -- Flask -- Flask 前后端分离:

url: "http://127.0.0.1:5000/barChart", 是不是可以写成 {{ url_for('get_bar_chart')|tojson }}

另外前面复制template 然后改static目录，为啥不直接把模版复制到static下呢？

**Comment by ZORfree** [comment]
官方文档 写的 的确是一团糟

**Comment by chfw** [comment]
嗯 我们接受大家发pull request

**Comment by sunhailin-Leo** [comment]
@highwindmx 
* URL 那块那样写可以让一些不是很清楚 `jinja2` 的开发者更好的理解
* 复制目录的问题，我觉得问题不大

**Comment by sunhailin-Leo** [comment]
@ZORfree 能具体给出哪里一团糟嘛？
