### ISSUE TITLE
请问一下表格没有办法转成图片或者pdf吗

### ISSUE THREAD

**Issue by jerurry** [pyecharts/pyecharts#1305]
**问题**
表格转成图片或者pdf时报错

**运行环境（系统环境及 pyecharts 版本）**
win10 +pyecharts 1.4.0

**代码及截图**
![image](https://user-images.githubusercontent.com/20988976/63757542-d69d9780-c8ec-11e9-9ded-72bf71d24e6e.png)

**Comment by Hanzy1996** [comment]
同问能不能生成PDF？里面是矢量图，文字可以复制的那种。

**Comment by chenjiandongx** [comment]
Table 不是 Echarts 的标准图表，目前暂不支持该需求。

**Comment by chenjiandongx** [comment]
Table 不是 Echarts 的标准图表，目前暂不支持该需求。
