### ISSUE TITLE
Page中添加多个图形，生成PDF或者图片后，生成的文件中只有第一个图

### ISSUE THREAD

**Issue by jerurry** [pyecharts/pyecharts#1307]
**问题**
Page中添加多个图形，生成PDF或者图片后，生成的文件中只有第一个图

**运行环境（系统环境及 pyecharts 版本）**
win10+pyecharts 1.4.0

**代码及截图**
![image](https://user-images.githubusercontent.com/20988976/63759097-84aa4100-c8ef-11e9-92a2-b568309ac3a1.png)
![image](https://user-images.githubusercontent.com/20988976/63759118-8d027c00-c8ef-11e9-91ad-4c673af2e9bb.png)

**Comment by ronething** [comment]
请问解决了吗 遇到同样的问题。

**Comment by jerurry** [comment]
> 请问解决了吗 遇到同样的问题。
想了个别的办法，不生成page了，先生成多个图片，然后把图片都添加到自己的html模板中，生成html后，再把html转化成PDF，这样的话还能自己控制页面的布局。

**Comment by ronething** [comment]
最终是要生成 pdf 的话 为何不使用 reportlab 之类的，还是说 html 转 pdf 效果也很好？

**Comment by jerurry** [comment]
因为项目展示有UI的设计图，所以先用html做了个模板，html调整样式的话比较简单，然后按设计图调整了一下样式，转出来的pdf基本上和html差不多

**Comment by chfw** [comment]
当前的局限是只能生成一张图。你们可以是用https://github.com/chfw/echarts-scrappeteer, 它能生成所有的图片。
