### ISSUE TITLE
axis_opts不能使用min和max变量

### ISSUE THREAD

**Issue by 361way** [pyecharts/pyecharts#1310]
**问题**
axis_opts y轴min_ max_无法使用变量min和max，使用后y轴指标不输出。可以使用min_ = 26这样的格式。

**运行环境（系统环境及 pyecharts 版本）**
centos7 + mincoda3 + 最新pyecharts 

**代码及截图**
`yaxis_opts=opts.AxisOpts(
    type_="value",
    #min_=26, 
    #max_="max",
    min_="min", 
    #max_="max",
    axistick_opts=opts.AxisTickOpts(is_show=True),
    splitline_opts=opts.SplitLineOpts(is_show=True),
),`

图片：
![](https://image-static.segmentfault.com/112/783/1127830292-5b0bc6f3bfdcc)
从https://segmentfault.com/q/1010000015064443 看到的解决方法，需要升级echarts.min.js

**Comment by chenjiandongx** [comment]
使用 `dataMax`, `dataMin`
