### ISSUE TITLE
折线图在X轴坐标为非0开始的或非连续时会少数据。

### ISSUE THREAD

**Issue by hiqishen** [pyecharts/pyecharts#1312]
**问题**
折线图在X轴坐标为非0开始的或非连续时会出现少数据的错误，字符串时正常。

**运行环境（系统环境及 pyecharts 版本）**
python=3.6
pyecharts=1.4.0

**代码及截图**
`from pyecharts.charts import Line

def line_base() -> Line:
    c = (
        Line()
        .add_xaxis([2, 3, 4,5])
        .add_yaxis("A", [100,200,300,400])
    )
    return c

line_base().render()`
结果如图：
![image](https://user-images.githubusercontent.com/45146003/63917370-168b8880-ca6d-11e9-9930-f0120e2aadea.png)

猜测应该是这种情况下Y轴在对应X轴时用了索引导致的。自己尝试的两种解决方法：①int也统一使用名称对应X轴，②生成html时判断X轴类型，如果是int型，html对应的Y轴data里的X坐标为对应长度的从0开始的连续int。。只是能力有限没有折腾出来。。

**Comment by sunhailin-Leo** [comment]
@hiqishen 在 `axisOpts` 中可以设置 X，Y 轴的 `type_` 属性为 `value`（默认是 `category`）
