### ISSUE TITLE
请求新增一个图形种类

### ISSUE THREAD

**Issue by IianWang** [pyecharts/pyecharts#1320]
**问题**
我是一名数据分析师，也是pyecharts的忠实用户，不过我在可视化结果是遇到了点麻烦，
我想要一个环状且能够绘制分布曲线的直方图。具体效果如下图所示：
第二张手绘的想表示出某个账户在24小时之内交易的分布，之所以没使用正常的直方图是因为一天的24个小时均为连续的，半夜12点过后紧接着就是第二天的0点，故我要观察该账户的交易行为也需要把直方图制成时钟类型方便观察。最后附带一个分布曲线。非常感谢团队的付出与维护，期待你们的回复。

**运行环境（系统环境及 pyecharts 版本）**
python3.6
pyecharts 0.5.9

**代码及截图**
![image](https://user-images.githubusercontent.com/40428181/64085276-5fd92200-cd64-11e9-8ba4-4c0f389cc2b2.png)

![608e89523ab425a03eda4576266b4a7](https://user-images.githubusercontent.com/40428181/64085445-58fedf00-cd65-11e9-83d4-a5a613cd98d2.jpg)

**Comment by chenjiandongx** [comment]
这种是不是类似于旭日图，https://pyecharts.org/#/zh-cn/basic_charts?id=sunburst%ef%bc%9a%e6%97%ad%e6%97%a5%e5%9b%be

**Comment by IianWang** [comment]
> 这种是不是类似于旭日图，https://pyecharts.org/#/zh-cn/basic_charts?id=sunburst%ef%bc%9a%e6%97%ad%e6%97%a5%e5%9b%be

感谢你的回复，恐怕旭日图不是我想要的效果，与它相似的玫瑰图我也有看过，遗憾都不合适。我的想法是把直方图绘制在圆环的边缘，进而根据棱柱的分布与走向，在棱柱上方绘制一条分布曲线。通过观察棱柱的密度与曲线的变化进而推测该用户的交易偏好时间与时间段活跃度。
PS:第一幅图是我在网上找的，它没有包含分布曲线，具体请参照第二张手绘的图。

**Comment by chenjiandongx** [comment]
目前 Echarts 没有类型的图形实现，所以 pyecharts 也无能为力。
