### ISSUE TITLE
1.5版本import失败

### ISSUE THREAD

**Issue by Godkillme** [pyecharts/pyecharts#1322]
OS：Win10
Python：3.7.4
问题：
通过pip安装了最新的1.5版本，使用的import方法如下：
`from pyecharts.charts import Bar`
提示错误如下：
`ModuleNotFoundError
No module named 'pyecharts.charts'; 'pyecharts' is not a package`
但是，pip list的确已经安装上了，而且在`site-packages`目录下也能看到pyecharts，虚拟环境也没问题。我在网上找了发现很多人也有类似的问题，无法import，但都没有发现能解决问题的方案。请问该如何解决？谢谢

**Comment by Godkillme** [comment]
犯了低级错误了，大家遇到此问题先查看py文件名是否和包名一致，否则会引起这样的错误……

**Comment by swuecho** [comment]
> 犯了低级错误了，大家遇到此问题先查看py文件名是否和包名一致，否则会引起这样的错误……

我觉得是 python 第一大坑， 至少应该给个提示。
