### ISSUE TITLE
你好请问下离线安装的文档有没有,还有就是本地js所需要的文件去哪里下载啊

### ISSUE THREAD

**Issue by feixia5712** [pyecharts/pyecharts#1323]
你好请问下离线安装的文档有没有,还有就是本地js所需要的文件去哪里下载啊

https://assets.pyecharts.org/assets这个网址貌似没有呢

**Comment by chenjiandongx** [comment]
1. 没有离线文档
2. https://github.com/pyecharts/pyecharts-assets

**Comment by chfw** [comment]
1. git clone https://github.com/pyecharts/website
2. python3 -m http.server

http://localhost:8000/
