### ISSUE TITLE
Polar-AngleAxis圈上的数字该如何去除？

### ISSUE THREAD

**Issue by Godkillme** [pyecharts/pyecharts#1325]
如下图，Polar-AngleAxis图表的圈上的0，1，2等等这些数字如何让它不显示，试了很多配置项都没有成功。谢谢！

![1](https://user-images.githubusercontent.com/33575502/64417734-386bb780-d0cc-11e9-8ab1-5a9f4553d1b6.jpg)

**Comment by chenjiandongx** [comment]
```python
def polar_scatter0() -> Polar:
    data = [(i, random.randint(1, 100)) for i in range(101)]
    c = (
        Polar()
        .add("", data, type_="scatter", label_opts=opts.LabelOpts(is_show=False)) # is_show=False
        .set_global_opts(title_opts=opts.TitleOpts(title="Polar-Scatter0"))
    )
    return c
```

**Comment by Godkillme** [comment]
> ```python
> def polar_scatter0() -> Polar:
>     data = [(i, random.randint(1, 100)) for i in range(101)]
>     c = (
>         Polar()
>         .add("", data, type_="scatter", label_opts=opts.LabelOpts(is_show=False)) # is_show=False
>         .set_global_opts(title_opts=opts.TitleOpts(title="Polar-Scatter0"))
>     )
>     return c
> ```
