### ISSUE TITLE
Import Overlap错误

### ISSUE THREAD

**Issue by HuoXiaoDa** [pyecharts/pyecharts#1326]
**问题**
你好，我安装了0.5.10版本的pyecharts,但是不能import overlap，请问这个是什么原因呢？我先后试了0.5.5和最新的版本都有这个问题

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![image](https://user-images.githubusercontent.com/54879699/64421852-280c0a80-d0d5-11e9-8fec-dd74f0df9048.png)

**Comment by szdblaa** [comment]
https://pyecharts.org/#/zh-cn/rectangular_charts?id=overlap%ef%bc%9a%e5%b1%82%e5%8f%a0%e5%a4%9a%e5%9b%be

**Comment by sunhailin-Leo** [comment]
@HuoXiaoDa 
* 确认你使用的版本是 `0.5.10`
* 确认你使用的代码是是 `0.5.X` 风格的
