### ISSUE TITLE
Grid 多圖聯動問題

### ISSUE THREAD

**Issue by Xiezhihaa** [pyecharts/pyecharts#1327]
**问题**
抱歉打擾，在你們組合圖表 Grid 多圖聯動範例中，我想請問該怎麼讓交易量的 bar 隨著收盤價情況改變顏色，我模仿你們的代碼，但無法呈現出顏色變化

另外範例中 visualmap_opts=opts.VisualMapOpts(is_show=False...）中，PyCharm 跳出沒有 is_show，我特別去查 global_options.py 裡對 VisualMapOpts 的描述裡也真沒有 is_show，感謝你在繁忙中抽空閱讀並回答我的問題，謝謝你

**运行环境（系统环境及 pyecharts 版本）**
PyCharm
python 3.7
macOS Mojave 10.14.6

**代码及截图**
https://github.com/Xiezhihaa/Stock_K_line_and_Volume/blob/master/venv/python.py

**Comment by sunhailin-Leo** [comment]
* https://github.com/pyecharts/pyecharts-gallery
* https://github.com/pyecharts/pyecharts-gallery/blob/master/Candlestick/professional_kline_chart.py
