### ISSUE TITLE
Pycharts not showing plots

### ISSUE THREAD

**Issue by HuoXiaoDa** [pyecharts/pyecharts#1328]
**问题**
你好，Pyecharts 总是不能显示绘图，这个是不是我directory设置的问题呢？可以帮我解决一下么，谢谢

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
from pyecharts import Bar,Line,Overlap
#overlap将多张图表整合到一个画板上
#绘制柱状图
hero = ['鲁班','妲己','程咬金','后裔']
death_times = [1200,600,90,1000]

myBar = Bar("simpletest英雄死亡次数")
myBar.add("",hero,death_times)
myBar
![image](https://user-images.githubusercontent.com/54879699/64469185-5682f780-d160-11e9-8f02-75eba3c5a7af.png)

**Comment by wendaomudong** [comment]
同样的问题，V0.5.x可以正常显示，V1.5.0不能直接显示图片
请教怎么处理～

**Comment by wendaomudong** [comment]
> **问题**
> 你好，Pyecharts 总是不能显示绘图，这个是不是我directory设置的问题呢？可以帮我解决一下么，谢谢
> 
> **运行环境（系统环境及 pyecharts 版本）**
> 
> **代码及截图**
> from pyecharts import Bar,Line,Overlap
> #overlap将多张图表整合到一个画板上
> #绘制柱状图
> hero = ['鲁班','妲己','程咬金','后裔']
> death_times = [1200,600,90,1000]
> 
> myBar = Bar("simpletest英雄死亡次数")
> myBar.add("",hero,death_times)
> myBar
> ![image](https://user-images.githubusercontent.com/54879699/64469185-5682f780-d160-11e9-8f02-75eba3c5a7af.png)

在jupyternotebook里，myBar.render_notebook()可以显示。具体参考文档：
https://pyecharts.org/#/zh-cn/notebook
