### ISSUE TITLE
堆积图两个stack的颜色颠倒

### ISSUE THREAD

**Issue by szdblaa** [pyecharts/pyecharts#1330]
**问题**
堆积图两个stack的颜色颠倒

**运行环境（系统环境及 pyecharts 版本）**
mac anaconda1.9.7 python3.7 pyecharts1.5.0

**代码及截图**

#此处有bug,未还款应显示为green,已还款应显示为red,实际显示颜色颠倒
duiji = (
        Bar()
        .add_xaxis(list(df['dt']))
        .add_yaxis('未还款',list(df['nopayment_c']),color='#ccffb3',#green
                   stack="stack2")
        .add_yaxis('已还款',list(df['actualpayment_c']),color='#ff4c4c',#red
                   stack="stack2")
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-堆叠数据（全部）"))
    ).render()

![image](https://user-images.githubusercontent.com/16127265/64684140-236d9a80-d4b7-11e9-95d0-9e92c92c9ea8.png)

**Comment by sunhailin-Leo** [comment]
@szdblaa 用 `set_colors(colors=["#ccffb3", "#ff4c4c"])` 保证顺序一致
