### ISSUE TITLE
双x轴，实现类目分组pyecharts可以弄出来吗？

### ISSUE THREAD

**Issue by kylink** [pyecharts/pyecharts#1335]
双x轴是可以的，但我想实现类目分类，比如第一条x轴是“北京、上海、广州、深圳、成都、南京”，第二条x轴在下方，分类成“一线城市、二线城市”

类似下图：
![QQ截图20190912160340](https://user-images.githubusercontent.com/3875846/64765569-f2549f00-d576-11e9-803e-cc4e6c27291c.png)

也像下面第二张图上“企业”和“普通客户”这样：
![QQ截图20190912155813](https://user-images.githubusercontent.com/3875846/64765478-c5a08780-d576-11e9-8a69-05acefde7e18.png)

求教

**Comment by sunhailin-Leo** [comment]
@kylink echarts 目前还不支持这种设置
