### ISSUE TITLE
scatter散点图不显示

### ISSUE THREAD

**Issue by jinxinglu** [pyecharts/pyecharts#1336]
**问题**
散点图的值不能显示，见截图

**运行环境（系统环境及 pyecharts 版本）**
MAC
pyecharts 1.5.0

**代码及截图**
from pyecharts.charts import Scatter

x = [5,6,7]
y = [3,4,5]

ss = Scatter()
ss.add_xaxis(x)
ss.add_yaxis('test', y)
ss.render_notebook()

<img width="803" alt="Screen Shot 2019-09-12 at 5 53 03 PM" src="https://user-images.githubusercontent.com/26435943/64774141-34391180-d586-11e9-9626-c44a8aabdeb0.png">

**Comment by sunhailin-Leo** [comment]
@jinxinglu 指定一下 x， y 轴的数据格式
![image](https://user-images.githubusercontent.com/17564655/66538245-227f6580-eb56-11e9-88de-6c6b91cfe4dc.png)
```python
from pyecharts.charts import Scatter
from pyecharts import options as opts

x = [5, 6, 7]
y = [3, 4, 5]

ss = Scatter()
ss.add_xaxis(x)
ss.add_yaxis('test', y)
ss.set_global_opts(
    xaxis_opts=opts.AxisOpts(type_="value")
)
ss.render("t_5.html")
```

**Comment by qingqiuzhang** [comment]
指定了还是不行，基本上网上说过的方法都尝试了，不管怎么样就是不显示
