### ISSUE TITLE
怎么改变x轴和y轴的颜色

### ISSUE THREAD

**Issue by Lcmolin** [pyecharts/pyecharts#1337]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by szdblaa** [comment]
.set_global_opts(
               xaxis_opts=opts.AxisOpts(axisline_opts=
                                        opts.AxisLineOpts(
                                                linestyle_opts=opts.LineStyleOpts(color='#e9e9e9'),font_family='Microsoft YaHei'
                                                          )
                                        ),
               yaxis_opts=opts.AxisOpts(axisline_opts=
                                        opts.AxisLineOpts(
                                                linestyle_opts=opts.LineStyleOpts(color='#ff6c37'),font_family='Microsoft YaHei'
                                                          )
                                        )
)

**Comment by Lcmolin** [comment]
> .set_global_opts（
> xaxis_opts = opts.AxisOpts（axisline_opts =
> opts.AxisLineOpts（linestyle_opts
> = opts.LineStyleOpts（color ='＃e9e9e9'），font_family ='Microsoft YaHei'
> ）
> ），
> yaxis_opts = opts.AxisOpts（axisline_opts =
> opts.AxisLineOpts（
> linestyle_opts = opts.LineStyleOpts（color ='＃ff6c37'），font_family ='Microsoft YaHei'
> ）
> ）
> ）

**Comment by Lcmolin** [comment]
> .set_global_opts（
> xaxis_opts = opts.AxisOpts（axisline_opts =
> opts.AxisLineOpts（linestyle_opts
> = opts.LineStyleOpts（color ='＃e9e9e9'），font_family ='Microsoft YaHei'
> ）
> ），
> yaxis_opts = opts.AxisOpts（axisline_opts =
> opts.AxisLineOpts（
> linestyle_opts = opts.LineStyleOpts（color ='＃ff6c37'），font_family ='Microsoft YaHei'
> ）
> ）
> ）

这个使用没有效果，我使用的是dump_options_with_quotes()函数，前后台分离的项目中，没有效果
