### ISSUE TITLE
建议pyecharts的0.x版本和1.x版本能够打包成两个package

### ISSUE THREAD

**Issue by jinxinglu** [pyecharts/pyecharts#1338]
现在pip install pyecharts直接pip安装1.x版本的pyecharts, 但是感觉bug比较多且编码习惯和0.x版本很不一样，但有时还是想同时导入两个版本来使用不同的功能，所以这里希望楼主能不能发布个0.x版本的专用package,这样后面import的时候就方便很多，可以同时导入，比如：

import pyecharts # 1.x版本
import pyecharts_v0 # 0.x版本

谢谢楼主

**Comment by chenjiandongx** [comment]
你应该考虑的是使用 virtualenv 或者其他版本工具来管理你的代码，而不是要求开发者提供两个不同的包。

**Comment by jinxinglu** [comment]
👌，学习了，谢谢
