### ISSUE TITLE
在绘制地图时如何才能使用自己给定的经纬度，而不是用省市标签？

### ISSUE THREAD

**Issue by DQinYuan** [pyecharts/pyecharts#1339]
**使用自己给定的经纬度值绘制地图**

**运行环境（系统环境及 pyecharts 版本）**

python 3.6
pyecharts 1.5.0

**代码及截图**

想要绘制自己给定的几个经纬度点，比如(27.777, 111.985), (27.677, 110.985)等等，而不是使用内置的标签经纬度（示例中使用的都是内置的省市标签），要怎么写呢？

**Comment by udbird** [comment]
data = []
for name, val, lon,lat in points:
    geo.add_coordinate(name, lon, lat)
    data.append((name, val))
attr, value = geo.cast(data)
其他都相同

**Comment by udbird** [comment]
`
data = []
for name, val, lon,lat in points:
    geo.add_coordinate(name, lon, lat)
    data.append((name, val))
attr, value = geo.cast(data)
`
其他都相同

**Comment by udbird** [comment]
data = []
for name, val, lon,lat in points:
    geo.add_coordinate(name, lon, lat)
    data.append((name, val))
attr, value = geo.cast(data)

其他都相同

**Comment by udbird** [comment]
data = []
for name, val, lon,lat in points:
    geo.add_coordinate(name, lon, lat)
    data.append((name, val))
attr, value = geo.cast(data)

其他都相同
