### ISSUE TITLE
区域选择组件是否支持自动计算

### ISSUE THREAD

**Issue by williamfzc** [pyecharts/pyecharts#1342]
**问题**

[区域选择组件](https://pyecharts.org/#/zh-cn/global_options?id=brushopts%ef%bc%9a%e5%8c%ba%e5%9f%9f%e9%80%89%e6%8b%a9%e7%bb%84%e4%bb%b6%e9%85%8d%e7%bd%ae%e9%a1%b9)是个很高效的东西，不知道有没有办法可以直接在圈选区域后对一些数据进行计算呢？

![image](https://user-images.githubusercontent.com/13421694/64958038-cad83c00-d8c0-11e9-9891-601296aaa4e5.png)

例如，选取x轴的一部分，并自动计算出这部分的长度。

谢谢！

**运行环境（系统环境及 pyecharts 版本）**

None

**代码及截图**

None

**Comment by sunhailin-Leo** [comment]
@williamfzc 得自定义 js，这个目前没有办法计算
