### ISSUE TITLE
如何在生成具有目录的html???

### ISSUE THREAD

**Issue by DongTau** [pyecharts/pyecharts#1344]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by DongTau** [comment]
用pyecharts生成的page中有很多个图，想着有个索引目录应该会方便很多，各位，应该怎么生成呢？我太难了

**Comment by swuecho** [comment]
https://element.eleme.io/#/zh-CN/component/tree 用这个如何？

**Comment by sunhailin-Leo** [comment]
@DongTau 这种高度自定义的事情。。 pyecharts 。暂时没法搞～
* 方案：你可以写一个 jinja2 的模版，去继承画出的图（一切目录设计在你的 jinja2 模板中完成）
