### ISSUE TITLE
视觉映射配置项(VisualMapOpts) 颜色显示问题

### ISSUE THREAD

**Issue by shengrl2007** [pyecharts/pyecharts#1345]
**问题**
视觉映射配置项(VisualMapOpts) 颜色显示问题，VisualMapOpts分段显示后，最大值的区间段颜色一致显示的是灰色。麻烦看下
![分段](https://user-images.githubusercontent.com/20402027/65019128-31ab3300-d95d-11e9-9507-bebdf654add6.png)

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.0.0版本

**代码及截图**
visualmap_opts=opts.VisualMapOpts(max_="25",is_piecewise=True,pos_left="25%",pos_top="65%")

**Comment by sunhailin-Leo** [comment]
@shengrl2007 
* 最好能给段代码上来～
