### ISSUE TITLE
怎么才能修改图例大小和造型？

### ISSUE THREAD

**Issue by planzq** [pyecharts/pyecharts#1347]
**问题**

怎么才能修改图例大小和造型？

**运行环境（系统环境及 pyecharts 版本）**
python 3.6.7
pyecharts 1.5.0

**代码及截图**

![微信图片编辑_20190918155056](https://user-images.githubusercontent.com/7350956/65128632-63d79600-da2c-11e9-923e-0326ee6f24b9.jpg)

**Comment by sunhailin-Leo** [comment]
@planzq 这个后期考虑会加入配置，目前我们的 LegendOpts 支持的配置比较少～

**Comment by sunhailin-Leo** [comment]
@planzq 
* 新版本已经加入相关配置 `https://github.com/pyecharts/pyecharts/pull/1404`
* New Version Release is coming~
