### ISSUE TITLE
在geo中绘制线

### ISSUE THREAD

**Issue by udbird** [pyecharts/pyecharts#1348]
问题：pyecharts是否支持Geo中绘制线，在文档中只看到一句：

> Geographic coorinate system component.Geographic coorinate system component is used to draw maps, which also supports scatter series, and **_line series_**.

但是没看到具体的示例

我翻echarts的文档，看到是支持的，不知道pyecharts是否提供相应的接口，如何实现？

**Comment by sunhailin-Leo** [comment]
* 看 demo：
https://pyecharts.org/#/zh-cn/geography_charts?id=geo%ef%bc%9a%e5%9c%b0%e7%90%86%e5%9d%90%e6%a0%87%e7%b3%bb
