### ISSUE TITLE
数字格式不支持numpy.int64

### ISSUE THREAD

**Issue by kinslyzhu** [pyecharts/pyecharts#1351]
pyecharts = 1.5.0
python = 3.7

我使用pandas 读取了Excel中的数据，内容如下

data_pair = [['China', 1561],
 ['Japan', 1481],
 ['Mexico', 1188],
 ['Korea South', 753],
 ['Hong Kong', 423],
 ['Philippines', 286],
 ['Canada', 233],
 ['Australia', 216],
 ['Colombia', 128],
 ['Russia', 87],
 ['Others', 1077],
 ['Total Foreign', 7433],
 ['United States', 473],
 ['Total', 7906]]

发现这里面数字的格式是numpy.int64 就无法画图，使用int（x）函数后才可以画图，请问这个是bug么？

**Comment by DallasAutumn** [comment]
https://pyecharts.org/#/zh-cn/data_format
不是bug，为了保持轻量化和通用性，没有加入自动转换功能
