### ISSUE TITLE
如何让3D散点图同时显示多种symbol？如何改变3D散点图坐标轴颜色？

### ISSUE THREAD

**Issue by hechaos** [pyecharts/pyecharts#1353]
**问题**
1. 如何让3D散点图同时显示多种symbol？
想在3D散点图中使用多种symbol显示不同类型指标，代码如下

![1569246020194](https://user-images.githubusercontent.com/3692854/65430624-cd9bd980-de4a-11e9-889c-bd244392c5ef.jpg)

效果如下，
<img width="1200" alt="WX20190923-214424@2x" src="https://user-images.githubusercontent.com/3692854/65431282-cb864a80-de4b-11e9-8259-713cff4fc889.png">

2. 如何改变3D散点图坐标轴颜色？
初始化InitOpts的时,使用bg_color="black"，所以想更改坐标轴颜色
使用过xaxis_line_color，但是并没有起作用

**运行环境（系统环境及 pyecharts 版本）**
MacOS
python 3.7
pyecharts 1.5.1

谢谢🙏

**Comment by sunhailin-Leo** [comment]
@hechaos 
如果可以的话贴一下完整的代码

**Comment by sunhailin-Leo** [comment]
@hechaos 
* x 轴的颜色，通过 `AxisLineOpts` 设置
