### ISSUE TITLE
展示图显示为空

### ISSUE THREAD

**Issue by 645187919** [pyecharts/pyecharts#1355]
**问题**
当x轴为数字类型的变量时多种图无法正常显示，目前已知有折线图和散点图，但是柱状图可以正常显示

**运行环境（系统环境及 pyecharts 版本）**
win64
最新版本

**代码及截图**
from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.charts import Scatter

def scatter_base() -> Scatter:
    c = (
        Scatter()
            .add_xaxis([201506, 201508, 201509, 201510, 201511, 201512])
            .add_yaxis("商家A", [1, 104, 334, 1942, 2019, 2041])
            .set_global_opts(title_opts=opts.TitleOpts(title="Scatter-基本示例"))
    )
    return c

scatter_base().render()
![image](https://user-images.githubusercontent.com/20920182/65689761-4647a380-e0a0-11e9-8f88-4f4e7e9cb7f7.png)

**Comment by JunjieYuan** [comment]
pyechart 1.5.0 复现成功，OS：Linux。

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/65736215-df140880-e10c-11e9-86c1-67277951e5b0.png)

请指定 X 轴类型为 "value"
