### ISSUE TITLE
如何在关系图中的link上自定义标签

### ISSUE THREAD

**Issue by JinkunHan** [pyecharts/pyecharts#1357]
def graph_base() -> Graph:
    Category = []
    for i in range(len(city)):
        # print(dataset[i][1])
        # print(dataset[i][2])
        Category.append(opts.GraphCategory(name=city[i]))
    nodes = []
    for i in range(len(city)):
        print(city)
        nodes.append(opts.GraphNode(name=city[i],symbol_size=10))
    # nodes = [
    #     opts.GraphNode(name="结点1", symbol_size=10),
    #     opts.GraphNode(name="结点2", symbol_size=20),
    #     opts.GraphNode(name="结点3", symbol_size=30),
    #     opts.GraphNode(name="结点4", symbol_size=40),
    #     opts.GraphNode(name="结点5", symbol_size=50),
    # ]

    links =[]
    for i in range(len(dataset)):
        # print(dataset[i][1])
        # print(dataset[i][2])
        links.append(opts.GraphLink(source=dataset[i][1], target=dataset[i][2]))

    # links = [
    #     opts.GraphLink(source="结点1", target="结点2"),
    #     opts.GraphLink(source="结点2", target="结点3"),
    #     opts.GraphLink(source="结点3", target="结点4"),
    #     opts.GraphLink(source="结点4", target="结点5"),
    #     opts.GraphLink(source="结点5", target="结点1"),
    # ]
    c = (
        Graph()
        .add("", nodes, links, repulsion=80000)
        .set_global_opts(title_opts=opts.TitleOpts(title="Graph-基本示例"))
    )
    return c
graph_base().render()

我的代码是这样的，我想在link上加标签，比如点击某一个link，显示“从北京到上海，航班B589，时长5小时”。

**Comment by sunhailin-Leo** [comment]
@JinkunHan 稍微把你的代码贴好一点

**Comment by opengit** [comment]
@sunhailin-Leo @JinkunHan 楼主的意思是不是在关系图的线条上加上数值等信息？图中箭头指向的线，如果能显示数值，则可以表示 关系强度等信息。。。
![image](https://user-images.githubusercontent.com/12468408/69493309-4ae5d800-0ee8-11ea-82f8-45c3fd4b9971.png)

**Comment by unstory** [comment]
请问楼主的问题解决了吗？我也有相同的问题，看文档没有找到相应的参数

**Comment by opengit** [comment]
@unstory 没有，正因为没有找到，因此刚刚换成python networkx来画图了。。。

**Comment by unstory** [comment]
> @unstory 没有，正因为没有找到，因此刚刚换成python networkx来画图了。。。

networkx要调的参数太多了，可以考虑一下d3.js

**Comment by opengit** [comment]
> > @unstory 没有，正因为没有找到，因此刚刚换成python networkx来画图了。。。
> 
> networkx要调的参数太多了，可以考虑一下d3.js

谢谢推荐，有机会尝试一下。

**Comment by sunhailin-Leo** [comment]
@JinkunHan @opengit @unstory 
* https://github.com/pyecharts/pyecharts/issues/1468

**Comment by JinkunHan** [comment]
> @JinkunHan @opengit @unstory
> 
> * 下一版将支持 Edge 配置: #1468

非常感谢您的回答
