### ISSUE TITLE
词云图自定义 Shape

### ISSUE THREAD

**Issue by 100gle** [pyecharts/pyecharts#1358]
Pyecharts 词云图的`shape`参数好像仅支持有限的几个形状，不知道是否以后会考虑添加能够自定义形状的功能呢？

**Comment by sunhailin-Leo** [comment]
@100gle 词云图我们也是引入 echarts 的 wordcloud.js 的，至于 echarts 什么时候支持的话，我们也会相对应支持的

**Comment by sunhailin-Leo** [comment]
@100gle 
* 等待新版本的发布后，参考文档进行使用
