### ISSUE TITLE
How to add a Page to the Tab?

### ISSUE THREAD

**Issue by yulincoder** [pyecharts/pyecharts#1359]
I use the latest version of pyecharts and how do I add the Page to the Tab? In other words, I want to put multiple charts in a single Tab item.
Thanks.

**Comment by chenjiandongx** [comment]
目前不打算支持这个行为

Page 和 Tab 的为同级组件类型，暂不考虑相互组合。

**Comment by Jiannan28** [comment]
如果能把page加到tab中应该是个很有用的feature，现在tab里边只能放一个图感觉有点局限，希望作者考虑～

**Comment by youjianguo** [comment]
现在可以了吗？tab和page结合使用

**Comment by tank2737** [comment]
> 现在可以了吗？tab和page结合使用

同问这个问题，目前这么用还是会报错
jinja2.exceptions.UndefinedError: 'pyecharts.charts.composite_charts.page.Page object' has no attribute 'width'

**Comment by Alokia** [comment]
2021年9月了，为啥这个还不支持

**Comment by jegb** [comment]
left a comment on the reverse case, but that the [use case](https://github.com/pyecharts/pyecharts/issues/1941#issuecomment-1478917487) is relevant here.

**Comment by Charmve** [comment]
https://gallery.pyecharts.org/#/Tab/tab_base

这里有一个case，显示支持。但我pyecharts 2.0.5不太行。

![image](https://github.com/pyecharts/pyecharts/assets/29084184/14db9fa1-f72e-4c0c-b2d4-206e3568b575)

报错：
- inja2.exceptions.UndefinedError: 'pyecharts.charts.composite_charts.tab.Tab object' has no attribute 'render_options'
- inja2.exceptions.UndefinedError: 'pyecharts.charts.composite_charts.page.Page object' has no attribute 'render_options'
