### ISSUE TITLE
设置GridOpts width没有改变显示区域的宽度

### ISSUE THREAD

**Issue by andyesi** [pyecharts/pyecharts#1360]
**问题**
在1.5.1版本中，使用GridOpts设置width=1300，然后render到html。
打开html页面，发现grid的区域大小变成1300了，但是显示区域还是900px，导致数据展示不全。

**运行环境（系统环境及 pyecharts 版本）**
macos 10.14.6
pyecharts: 1.5.1

**代码及截图**
html源码：<div id="78dd19a9c13347cc94b1229cf0c0b953" class="chart-container" style="width:900px; height:500px;"></div>

**Comment by sunhailin-Leo** [comment]
@andyesi 要把 InitOpts 里面的最外层画布扩展了先
