### ISSUE TITLE
使用flask渲染example里面的示例代码，在浏览器中每次刷新图形都会重复出现

### ISSUE THREAD

**Issue by strangeboss** [pyecharts/pyecharts#1361]
**问题**
使用flask渲染example里面的示例代码，在浏览器中每次刷新图形都会重复出现，而且刷新几次，就会重复出现几个图形

**运行环境（系统环境及 pyecharts 版本）**
win10
pyecharts  1.5.1
flask  1.1.1
python 3.6

**代码及截图**
**这是example里面的bar3d示例**
![bar3d_example部分](https://user-images.githubusercontent.com/31651545/66034567-0d924900-e53c-11e9-86c6-a2ab1e76bbf8.PNG)
**这是flask里渲染的部分代码**
![flask部分](https://user-images.githubusercontent.com/31651545/66034750-67930e80-e53c-11e9-9932-222a30a76611.PNG)
**这是在浏览器里刷新两次之后的结果**
![浏览器页面图](https://user-images.githubusercontent.com/31651545/66034788-7bd70b80-e53c-11e9-9f2e-68d9873935d5.jpg)
**实验刷新了很多遍，会出现很多图**
![刷新5次后](https://user-images.githubusercontent.com/31651545/66035127-294a1f00-e53d-11e9-8580-2160d2042750.PNG)

是否有小伙伴遇到同样问题？？

**Comment by sunhailin-Leo** [comment]
@strangeboss 得看看你的前端代码

**Comment by sunhailin-Leo** [comment]
@strangeboss 问题还是否出现？

**Comment by strangeboss** [comment]
已解决，谢谢！











在 2019-11-23 20:53:31，"LeoSun" <notifications@github.com> 写道：

@strangeboss 问题还是否出现？
