### ISSUE TITLE
新建markline时，使用coord参数绘制自定义的markline失败

### ISSUE THREAD

**Issue by qihaiqianqiu** [pyecharts/pyecharts#1362]
**问题**  
想绘制一条自定义起点和终点的markline，在生成item的时候给coord参数赋值，会导致render不出图像

**运行环境（系统环境及 pyecharts 版本）**  
MAC  python3.7 pyecharts 1.5.1

**代码及截图**
from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.charts import Scatter

def bar_markline_type() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-MarkLine（指定类型）"),
            xaxis_opts = opts.AxisOpts(type_ = "value"))
        .set_series_opts(
            label_opts=opts.LabelOpts(is_show=False),
            markline_opts=opts.MarkLineOpts(
                data=[
                    opts.MarkLineItem(coord = [[3,6],[5,6]])
                ]
            )
        )
    )
    return c

bar_markline_type().render()
返回的图片只有一个坐标系，没有内容。
如果把coord参数去掉，换成别的生成markline的方式，都是没问题的，真心请教各位大神了，谢谢！

**Comment by qihaiqianqiu** [comment]
代码第三行笔误了，import的应该是Bar，但是不影响这个问题的存在

**Comment by sunhailin-Leo** [comment]
@qihaiqianqiu 
```python
def bar_markline_custom() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .add_yaxis("商家B", Faker.values())
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-MarkLine（自定义）"))
        .set_series_opts(
            label_opts=opts.LabelOpts(is_show=False),
            markline_opts=opts.MarkLineOpts(
                data=[opts.MarkLineItem(y=50, name="yAxis=50")]
            ),
        )
    )
    return c
```

**Comment by sevenzero** [comment]
@sunhailin-Leo 我也遇到这个疑问，文档中MarkLineItem()中coord解释说是“起点或终点的坐标，坐标格式视系列的坐标系而定，可以是直角坐标系上的 x, y，也可以是极坐标系上的 radius, angle。”，示例中却没有给出用法，我采用coord=[3,4]或者coord=[[2,3],[5,3]]的定义都会出现render不出图像，只有坐标系的情况，请问该如何正确自定义markline的起止点？

**Comment by LanceLi1991** [comment]
`import pymysql
import pandas as pd
import pyecharts.options as opts
import numpy as np
from pyecharts.charts import Scatter


conn= pymysql.connect(host='localhost',user='root',passwd='',db='china_daas')
sql= "select * from wx_total_by_holiday where CID='2c918088596311390159d35fa1ef13bf'"
df = pd.read_sql(sql,conn)

CX_date= list(df['date'])
CX_num= np.array((df['total']))

print(CX_date[0])

c = (
    Scatter(init_opts=opts.InitOpts(page_title="节假日查询量分析散点图"))
    .add_xaxis(CX_date)
    .add_yaxis("",CX_num ,
               symbol_size=5,
               label_opts=opts.LabelOpts(is_show=False),
               markline_opts=opts.MarkLineOpts(
                   data=[[opts.MarkLineItem(coord= [CX_date[0], 41099],symbol='none'),opts.MarkLineItem(coord= [CX_date[114], 41099],symbol='none')]],
                   symbol="none",
                   linestyle_opts=opts.LineStyleOpts(type_="dashed"))
               )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="节假日查询分析",subtitle="深圳前海征信中心股份有限公司",subtitle_textstyle_opts= opts.TextStyleOpts(color="blue",font_size=14)),
        visualmap_opts=opts.VisualMapOpts(max_=25000),
    )
    .render("节假日查询分析.html")
)`

我做的是个散点图，coord实际上定位的是点不是线，所以你要自己画markline需要定位两个点，一个起点一个终点就可以了
![image](https://user-images.githubusercontent.com/62918808/77978360-7ebc8880-7334-11ea-995d-2956621fc469.png)

**Comment by LanceLi1991** [comment]
[`import pymysql
import pandas as pd
import pyecharts.options as opts
import numpy as np
from pyecharts.charts import Scatter


conn= pymysql.connect(host='localhost',user='root',passwd='',db='china_daas')
sql= "select * from wx_total_by_holiday where CID='2c918088596311390159d35fa1ef13bf'"
df = pd.read_sql(sql,conn)

CX_date= list(df['date'])
CX_num= np.array((df['total']))

print(CX_date[0])

c = (
    Scatter(init_opts=opts.InitOpts(page_title="节假日查询量分析散点图"))
    .add_xaxis(CX_date)
    .add_yaxis("",CX_num ,
               symbol_size=5,
               label_opts=opts.LabelOpts(is_show=False),
               markline_opts=opts.MarkLineOpts(
                   data=[[opts.MarkLineItem(coord= [CX_date[0], 41099],symbol='none'),opts.MarkLineItem(coord= [CX_date[114], 41099],symbol='none')]],
                   symbol="none",
                   linestyle_opts=opts.LineStyleOpts(type_="dashed"))
               )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="节假日查询分析",subtitle="深圳前海征信中心股份有限公司",subtitle_textstyle_opts= opts.TextStyleOpts(color="blue",font_size=14)),
        visualmap_opts=opts.VisualMapOpts(max_=25000),
    )
    .render("节假日查询分析.html")
)`]
