### ISSUE TITLE
使用geo地理图表，抛出TypeError: cannot unpack non-iterable NoneType object的异常

### ISSUE THREAD

**Issue by voeth** [pyecharts/pyecharts#1363]
![image](https://user-images.githubusercontent.com/34185176/66265711-61a77100-e84d-11e9-81ef-2dcbbdd9ce12.png)

![image](https://user-images.githubusercontent.com/34185176/66265715-7421aa80-e84d-11e9-8c7f-a538e2bd5915.png)

为什么用list来作为地图的数据会报错，但是用generator就正常呢？官方文档的demo也是用list的

**Comment by chfw** [comment]
根本原因是有地区不存在

**Comment by chenjiandongx** [comment]
建议使用最新版本的 pyecharts, 最新版为地理位置做了模糊匹配。

**Comment by tjuarch** [comment]
**问题**
我也遇到这样的问题，返回“cannot unpack non-iterable NoneType object”这样的错误。
我也知道根本原因是由于有的地址在Geo.get_coordinate()中不存在，返回“None”。

**环境**
windows10， vscode1.42.0， Python3.7.1, pyecharts 1.6.2

**具体描述**
地址数据集是这样的：
[['宝坻区', 31], ['河东区', 10], ['河北区', 10], ['和平区', 6], ['外地来津', 6], ['宁河区', 4], ['西青区', 4], ['东丽区', 4], ['河西区', 4], ['南开区', 3], ['滨海新区', 3], ['红桥区', 2], ['津南区', 1], ['北辰区', 1], ['武清区', 1]]
其中“外地来津”和“宁河区”是返回“None”的。

查看源码后发现，这个数据是由Geo类的_feed_data()调用，源码如下：
    def _feed_data(self, data_pair: types.Sequence, type_: str) -> types.Sequence:
        result = []
        for n, v in data_pair:
            if type_ == ChartType.LINES:
                f, t = self.get_coordinate(n), self.get_coordinate(v)
                result.append({"name": "{}->{}".format(n, v), "coords": [f, t]})
            **else:
                lng, lat = self.get_coordinate(n) # <-------这里
                result.append({"name": n, "value": [lng, lat, v]})**
        return result

**建议能不能在那个else分支中加入类似模糊匹配的功能，使得万一数据中有不符合要求的地址，不至于使程序崩溃，谢谢！**
