### ISSUE TITLE
移动光标到图例为什么不显示数据标签？

### ISSUE THREAD

**Issue by slsongge** [pyecharts/pyecharts#1364]
**问题**
您好，我绘制普通的直角坐标系图的时候，移动光标到图例为什么不显示数据标签？
我使用了is_show=False，不知道是不是因为这个导致的？
最终的需求：就像v0.5版本的pyecharts似的，绘图之后没有数据标签，当光标放到图例时出现数据标签即可。
谢谢！

**运行环境（系统环境及 pyecharts 版本）**
python 3.7.3
pyecharts 1.5.1

**代码及截图**
```
import warnings
import numpy as np
import pandas as pd

from pyecharts.charts import Bar, Line
from pyecharts import options as opts

warnings.filterwarnings('ignore')


def bar_line():
    bar = (
        Bar(init_opts=opts.InitOpts(width="1000px", height="400px"))
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("商品名", [5, 20, 36, 10, 75, 90], color="#1f77b4")
        .extend_axis(yaxis=opts.AxisOpts(axislabel_opts=opts.LabelOpts(formatter="{value} %")))  # 拓展纵轴
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(
            title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"),                         # 标题
            toolbox_opts=opts.ToolboxOpts(),                                                     # 工具箱
            datazoom_opts=opts.DataZoomOpts(range_start=0,range_end=100)                         # 横轴缩放
        )
    )
    
    line = (
        Line()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("折线一", [0.1, 0.2, 0.3, 0.4, 0.5, 0.6], yaxis_index=1, 
                   linestyle_opts=opts.LineStyleOpts(color="#2ca02c", width=3),
                   itemstyle_opts=opts.ItemStyleOpts(color="#2ca02c"))
        .add_yaxis("折线二", [0.1, 0.15, 0.2, 0.25, 0.3, 0.35], yaxis_index=1,
                   linestyle_opts=opts.LineStyleOpts(color="#ff7f0e", width=3),
                   itemstyle_opts=opts.ItemStyleOpts(color="#ff7f0e"))
    )
    
    bar.overlap(line)
    return bar

bar_line().render_notebook()

```

![image](https://user-images.githubusercontent.com/36298417/66288203-e1474580-e90a-11e9-80e9-38ce1a8032a6.png)

![image](https://user-images.githubusercontent.com/36298417/66288258-10f64d80-e90b-11e9-9304-dc40419fe02c.png)

**Comment by slsongge** [comment]
@chenjiandongx

**Comment by chenjiandongx** [comment]
@slsongge 

用你的代码生成的图表

![image](https://user-images.githubusercontent.com/19553554/66295930-02b22c80-e91f-11e9-9a9a-bbe475b9b544.png)

**Comment by slsongge** [comment]
> @slsongge
> 
> 用你的代码生成的图表
> 
嗯嗯，对的，画出来是上图的样子。但是我想要的效果就是：将光标放在图例“商品名”时，每个柱子上面显示出相应的数据标签。

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/66311846-099e6680-e942-11e9-8eba-480ba051f354.png)

柱子上面有标签

**Comment by slsongge** [comment]
@chenjiandongx 哥，不是这个意思。我想实现的是将光标放到“红色箭头”指向的位置，然后下面的所有的柱子都会显示出数据标签。

![image](https://user-images.githubusercontent.com/36298417/66312543-76fec700-e943-11e9-8c1f-47ac39bac074.png)

**Comment by slsongge** [comment]
@chenjiandongx 冬哥，你可以参考一下你们的这个文档
https://05x-docs.pyecharts.org/#/zh-cn/charts_base?id=line%ef%bc%88%e6%8a%98%e7%ba%bf%e9%9d%a2%e7%a7%af%e5%9b%be%ef%bc%89

![image](https://user-images.githubusercontent.com/36298417/66312848-f096b500-e943-11e9-97e1-7b94e2389ea5.png)

**Comment by chenjiandongx** [comment]
哦 确实是 我也不知道 可能是 Echarts 版本的原因

**Comment by slsongge** [comment]
> 哦 确实是 我也不知道 可能是 Echarts 版本的原因

真是非常感谢您回复我的邮件哈，谢谢！
目前不是因为我代码中参数设置的问题吧？如果确实是Echart版本的问题的话，我这边能实现我的需求吗？

**Comment by chenjiandongx** [comment]
https://www.bootcdn.cn/echarts/

你可以替换其他 Echarts 版本试试

**Comment by slsongge** [comment]
@chenjiandongx 我这边就是直接用pip install pyechats下载的pyecharts，我是得单独下载Echarts吗？不太理解您的意思。

**Comment by chenjiandongx** [comment]
你可以先尝试替换生成 HTML 的 srcipt 标签，改用其他的 Echarts 版本试试

**Comment by slsongge** [comment]
好的，老哥，回头我研究一下，因为没有接触过html，谢谢您！

**Comment by slsongge** [comment]
@chenjiandongx 建冬哥，打扰一下哈，经过上面的沟通，这个问题我还是没能够解决，在您这边能实现：光标放到图例上面，图里面会显示数据标签吗？

**Comment by sunhailin-Leo** [comment]
@slsongge 
* 你的意思是要把光标放到 legend 上，然后每个数据项的黑色的那个数据标签框全部都显示出来么？

**Comment by slsongge** [comment]
> * 你的意思是要把光标放到 legend 上，然后每个数据项的黑色的那个数据标签框全部都显示出来么？

对的，如果不把广标放到legend上，则不显示数据标签。
之所以有这个需求，是因为我的图里面涉及到了“1个柱状图+4个折线图”。如果数据标签都显示出来的话，图就会变得很乱。

上一版本（0.5X）的pyecharts是可以实现这个功能的，新版的则不行。

谢谢！

**Comment by slsongge** [comment]
@sunhailin-Leo 我的回复内容见上一条消息，辛苦您~

**Comment by sunhailin-Leo** [comment]
@slsongge 
* 黑框是 Tooltip 组件，只会在鼠标移动到相对应的数据项的点上才会展现。
* 我看你回复的意思貌似说的不是黑色的那个框吧？

**Comment by slsongge** [comment]
@sunhailin-Leo  
* 确实不是那个黑框，我理解错您的意思了。
我重新描述一下我的问题哈，如下图。第一个图绿框里面的折线图没有显示数据标签，但是当光标放到legend（最高气温）上面的时候，绿框中的折线图显示出了数据标签。
![image](https://user-images.githubusercontent.com/36298417/72398840-4ec30780-377f-11ea-929b-f5458c29e36c.png)
上图链接（折线面积图的最后一个示例）：https://05x-docs.pyecharts.org/#/zh-cn/charts_base?id=line%EF%BC%88%E6%8A%98%E7%BA%BF%E9%9D%A2%E7%A7%AF%E5%9B%BE%EF%BC%89

注：这是0.5x版本所支持的功能，目前我使用的1.5.2版本的却不支持。
谢谢！

**Comment by sunhailin-Leo** [comment]
@slsongge 
* 这个只能换版本了
* Echarts 大概是为大数据展示优化才去掉这个功能的。
    * 假如你有上百万数据，突然鼠标划过那个 `legend`，估计能卡的你半死

**Comment by JiaxiangBU** [comment]
@slsongge 看了下你们之前的问题，这里你先降版本安装。
见 https://github.com/pyecharts/pyecharts/releases/tag/v0.5.11
这里我看到这里从`v0.5.11`就跳到`v1.0.0`了，应该做了大的改动。

在 pypi 上查看到对应的版本
https://pypi.org/project/pyecharts/#history
`0.5.x` 最新到 https://pypi.org/project/pyecharts/0.5.11/

```bash
pip install pyecharts==0.5.11
```

你测试下。
