### ISSUE TITLE
pyecharts_v1 版本有没有类型version0.5.x版本的 render_container_and_echarts_code函数()

### ISSUE THREAD

**Issue by linfanli** [pyecharts/pyecharts#1365]
**问题**
Pyecharts V0.5.x版本有生成html格式的函数 render_container_and_echarts_code
Pyecharts V1 版本有没有类似的函数

**运行环境（系统环境及 pyecharts 版本）**

Windows7  pyecharts **代码及截图**

**Comment by sunhailin-Leo** [comment]
@linfanli 你是要 `html` 源码嘛？目前 v1 高层 api 有 `render` `render_embed` `render_notebook`

**Comment by linfanli** [comment]
怎么直接CLOSE？

我使用python出html报告，想把 pyecharts 嵌到html中
v0.5.x是支持的，脚本如下；我想问V1有没有相关的功能

不是API

`# pyecharts 图表对象化传参
from pyecharts.engine import create_default_environment
env = create_default_environment("html")
html = env.render_container_and_echarts_code(bar)`

另外有什么变通的方法实现 render_container_and_echarts_code函数的功能

**Comment by sunhailin-Leo** [comment]
@linfanli 
* 你有看我第一句说的问题嘛？我问你是不是需要返回 `html` 源码？
* `from pyecharts.render.engine import RenderEngine`里面有些更底层的方法，高层的 API 都是基于这个类实现的。

**Comment by chenjiandongx** [comment]
@linfanli 你是否是想获取包裹 Echarts 图表 `<div>` 标签的内容？

**Comment by linfanli** [comment]
@sunhailin-Leo 大佬，不懂你说的hmtl源是什么意思(我只是一个数据分析 人员，不是后台开发)

需要的是 通过render_container_and_echarts_code函数 输出hmtl能识别的字符串
我只是想知道V1支持不支持render_container_and_echarts_code， 如果 不支持就用老版


@chenjiandongx  还是你懂我，具体使用场景如下
此处是ender_container_and_echarts_code输出字符串 替换下面的

<html>
<body>  
{{ pyechart_output_str }}
 </body>
</html>

**Comment by linfanli** [comment]
`<html>
<body>
{{ pyechart_output_str }}
 <body>
<html>
`

**Comment by linfanli** [comment]
![image](https://user-images.githubusercontent.com/16367420/66542309-d7208380-eb64-11e9-8e01-55660472ca86.png)

**Comment by linfanli** [comment]
![image](https://user-images.githubusercontent.com/16367420/66542394-0931e580-eb65-11e9-9784-a532288ea598.png)

**Comment by linfanli** [comment]
@sunhailin-Leo @chenjiandongx  不知道我现在把问题说清楚了嘛，麻烦你们2位大佬了

**Comment by chenjiandongx** [comment]
@linfanli 试试下面的代码

```python
from jinja2 import Template
from pyecharts.charts import Bar

tmpl_str = '''
    <div id="{{ c.chart_id }}" class="chart-container" style="width:{{ c.width }}; height:{{ c.height }};"></div>
    <script>
        var chart_{{ c.chart_id }} = echarts.init(
            document.getElementById('{{ c.chart_id }}'), '{{ c.theme }}', {renderer: '{{ c.renderer }}'});
        {% for js in c.js_functions.items %}
            {{ js }}
        {% endfor %}
        var option_{{ c.chart_id }} = {{ c.json_contents }};
        chart_{{ c.chart_id }}.setOption(option_{{ c.chart_id }});
        {% if c._is_geo_chart %}
            var bmap = chart_{{ c.chart_id }}.getModel().getComponent('bmap').getBMap();
            {% if c.bmap_js_functions %}
                {% for fn in c.bmap_js_functions.items %}
                    {{ fn }}
                {% endfor %}
            {% endif %}
        {% endif %}
    </script>
'''


tmpl = Template(tmpl_str)
bar = Bar()
bar.add_xaxis(["A", "B"]).add_yaxis("series", [1, 2])
bar._prepare_render()

html = tmpl.render(c=bar)
print(html)

```

**Comment by chenjiandongx** [comment]
@linfanli 

v1 版本没有类似的方法是因为我在重构的时候将这部分逻辑直接下沉到 Templates 层，直接使用 jinja2 的 macro 特性，不再使用 context 技术。

**Comment by linfanli** [comment]
@chenjiandongx @sunhailin-Leo 多谢，我明白了
