### ISSUE TITLE
设置数据颜色params.dataIndex值为null

### ISSUE THREAD

**Issue by JR--Chen** [pyecharts/pyecharts#1368]
**问题**
设置数据颜色时，读取的params.dataIndex时值为null

**运行环境（系统环境及 pyecharts 版本）**
pyecharts  1.5.1
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Session info: headless chrome=77.0.3865.90
Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a)
platform=Windows NT 10.0.18362 x86_64

**代码及截图**
![image](https://user-images.githubusercontent.com/10894217/66561691-81f86800-eb8c-11e9-93b4-cd64580320a6.png)

trace
![image](https://user-images.githubusercontent.com/10894217/66561750-a5bbae00-eb8c-11e9-9653-85d4d3dc50ce.png)

**Comment by sunhailin-Leo** [comment]
@JR--Chen 
* 你 `title` 那里是配置是个什么情况？
