### ISSUE TITLE
ImportError: cannot import name 'Line' from 'pyecharts' (/Users/xx/anaconda3/lib/python3.7/site-packages/pyecharts/__init__.py)

### ISSUE THREAD

**Issue by tianke0711** [pyecharts/pyecharts#1369]
**问题**

pip install pyecharts

and 

from pyecharts import Line, Grid

errors:

`ImportError: cannot import name 'Line' from 'pyecharts' (/Users/xx/anaconda3/lib/python3.7/site-packages/pyecharts/__init__.py)
`
**运行环境（系统环境及 pyecharts 版本）**
Mac Mojave

pyecharts==1.5.1

**代码及截图**

**Comment by hjysmi** [comment]
请如下这样使用
from pyecharts.charts import Line,Grid
