### ISSUE TITLE
想咨询下DataZoomOpts中的type_共有几种类型以及查询方式

### ISSUE THREAD

**Issue by hjysmi** [pyecharts/pyecharts#1370]
**问题**
想咨询下DataZoomOpts中的type_共有几种类型，分别是哪些？源码中没有查找到相关种类。配到类似的问题，如何查询呢。是否可以设计个枚举类型呢。想了解下，谢谢

**运行环境（系统环境及 pyecharts 版本）**
python: 3.7.4
pyecharts: 1.5.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@hjysmi 
* 文档是个好东西，你却没有认真看。
https://pyecharts.org/#/zh-cn/global_options?id=datazoomopts%ef%bc%9a%e5%8c%ba%e5%9f%9f%e7%bc%a9%e6%94%be%e9%85%8d%e7%bd%ae%e9%a1%b9
* 文档写的很明确，两种配置～
