### ISSUE TITLE
无法使用str格式的时间序列作为x轴，或者如何正确使用时间序列？

### ISSUE THREAD

**Issue by Raibows** [pyecharts/pyecharts#1373]
**问题**
Line图x轴无法正确表示时间，无论我传递的是datetime类型或是str格式(%d-%H-%M-%S)或是(%d/%H/%M/%S)，图表中x轴均为一片空白。在文档中找到的格式是(%d/%H/%M/%S)，已经设置``xaxis_opts=opts.AxisOpts(type_="time")``

**运行环境（系统环境及 pyecharts 版本）**
win10, 1903Pro
python 3.7.4
pyecharts 1.5.1

**代码及截图**
```
def line_base() -> Line:
    length = volt_count.query.count()
    num = 0 if length < 10 else length - 10
    info = volt_count.query.filter(volt_count.sequence >= (num + 1))
    info = list(info)
    line = (
        Line()
        .add_xaxis([info[i].time.strftime("%d-%H-%M-%S") for i in range(len(info))])
        .add_yaxis(
            series_name="",
            y_axis=[info[i].count for i in range(len(info))],
            is_smooth=False,
            label_opts=opts.LabelOpts(is_show=False),
        )
        .set_global_opts(
            title_opts=opts.TitleOpts(title="动态计数"),
            xaxis_opts=opts.AxisOpts(type_="time"),
            yaxis_opts=opts.AxisOpts(type_="value"),
        )
    )
    return line
@main.route("/lineDynamicData")
def update_line_data():
    last_volt_count = volt_count.query.order_by(volt_count.time.desc()).all()
    last_volt_count = last_volt_count[-1]
    idx = last_volt_count.time
    idx = idx.strftime("%d-%H-%M-%S")
    print(idx, type(idx))
    value = last_volt_count.count
    return jsonify({"name": idx, "value": value})

```
使用的是推荐的Flask定时增量更新图表，仅更改了数据传递部分。  
idx的值是str的时间序列，count是int数值，  
我希望x轴为idx， y轴为count  
现状如下图所示，x轴无法正确表达
![image](https://user-images.githubusercontent.com/37944786/66755438-87c2b600-eeca-11e9-8b56-484644c6b33c.png)

**Comment by Raibows** [comment]
实际上我想使用flask定时增量更新，并且以x轴为递增的时间序列，我尝试了各种办法，发现似乎只有type=“value”时才会正常工作，其他情况要么x轴空白，要么无法动态更新，请问有解决方法吗？

**Comment by Raibows** [comment]
去了echarts官网发现了示例，要求年份必须是xxxx（4位），格式为“%Y-%m-%d %H-%M-%S”

**Comment by AlvinTangGit** [comment]
```.add_xaxis([info[i].time for i in range(len(info))])```
```xaxis_opts=opts.AxisOpts(type_="time")```的话，直接传datetime格式进X轴数据就可以了

**Comment by shuaiguoer** [comment]
> `.add_xaxis([info[i].time for i in range(len(info))])`
> `xaxis_opts=opts.AxisOpts(type_="time")`的话，直接传datetime格式进X轴数据就可以了

请问可以具体说明一下吗？

**Comment by shuaiguoer** [comment]
> 实际上我想使用flask定时增量更新，并且以x轴为递增的时间序列，我尝试了各种办法，发现似乎只有type=“value”时才会正常工作，其他情况要么x轴空白，要么无法动态更新，请问有解决方法吗？

我也遇到了相同的问题，请问您解决了吗？

**Comment by shuaiguoer** [comment]
> 去了echarts官网发现了示例，要求年份必须是xxxx（4位），格式为“%Y-%m-%d %H-%M-%S”

测试X轴还是空白，请教如何修改

**Comment by Raibows** [comment]
> > 去了echarts官网发现了示例，要求年份必须是xxxx（4位），格式为“%Y-%m-%d %H-%M-%S”
> 
> 测试X轴还是空白，请教如何修改

@shuaiguoer 您好，已经解决，x轴时间序列设置为time即可，相关代码如下
```
def line_base() -> Line:
    info = list(info)
    line = (
        Line()
        .add_xaxis([info[i].time.strftime("%Y/%m/%d %H:%M:%S") for i in range(len(info))])
        .add_yaxis(
            series_name="",
            y_axis=[info[i].count for i in range(len(info))],
            is_smooth=False,
            label_opts=opts.LabelOpts(is_show=False),
        )
        .set_global_opts(
            title_opts=opts.TitleOpts(title="动态计数"),
            xaxis_opts=opts.AxisOpts(type_="time"),
            yaxis_opts=opts.AxisOpts(type_="value"),
        )
    )
    return line
```

**Comment by shuaiguoer** [comment]
@Raibows 您好，我已经设置了type_="time"，但是X轴还是显示错误！(显示的时间好像是1970年)，请您帮我检查一下，多谢了
以下是我的部分代码：

`def line_base() -> Line:
    line = (
        Line()
        .add_xaxis([])
        .add_yaxis(
            series_name="",
            y_axis=[],
            is_smooth=True,
            label_opts=opts.LabelOpts(is_show=False),
        )
        .set_global_opts(
            title_opts=opts.TitleOpts(title="动态数据"),
            xaxis_opts=opts.AxisOpts(type_="time"),
            yaxis_opts=opts.AxisOpts(type_="value"),
            datazoom_opts=opts.DataZoomOpts(
                is_show=True,
                type_="slider",
                is_realtime=True,
                range_start=80,
                range_end=100,
                start_value=None,
                end_value=None,
                orient="horizontal",
                is_zoom_lock=False,
                filter_mode="filter"
            )
        )
    )
    return line


@app.route("/")
def index():
    return render_template("test2.html")


@app.route("/lineChart")
def get_line_chart():
    c = line_base()
    return c.dump_options_with_quotes()


@app.route("/lineDynamicData")
def update_line_data():
    now = int(time.time())
    # # 内存信息
    mem = psutil.virtual_memory()
    # # 系统已经使用内存
    mem_use = int(mem.used / 1024 / 1024)
    print(mem_use)
    return jsonify({"name": now, "value": mem_use})
`

**Comment by Raibows** [comment]
> @Raibows 您好，我已经设置了type_="time"，但是X轴还是显示错误！(显示的时间好像是1970年)，请您帮我检查一下，多谢了
> 以下是我的部分代码：
> 
> `def line_base() -> Line:
> line = (
> Line()
> .add_xaxis([])
> .add_yaxis(
> series_name="",
> y_axis=[],
> is_smooth=True,
> label_opts=opts.LabelOpts(is_show=False),
> )
> .set_global_opts(
> title_opts=opts.TitleOpts(title="动态数据"),
> xaxis_opts=opts.AxisOpts(type_="time"),
> yaxis_opts=opts.AxisOpts(type_="value"),
> datazoom_opts=opts.DataZoomOpts(
> is_show=True,
> type_="slider",
> is_realtime=True,
> range_start=80,
> range_end=100,
> start_value=None,
> end_value=None,
> orient="horizontal",
> is_zoom_lock=False,
> filter_mode="filter"
> )
> )
> )
> return line
> 
> @app.route("/")
> def index():
> return render_template("test2.html")
> 
> @app.route("/lineChart")
> def get_line_chart():
> c = line_base()
> return c.dump_options_with_quotes()
> 
> @app.route("/lineDynamicData")
> def update_line_data():
> now = int(time.time())
> # # 内存信息
> mem = psutil.virtual_memory()
> # # 系统已经使用内存
> mem_use = int(mem.used / 1024 / 1024)
> print(mem_use)
> return jsonify({"name": now, "value": mem_use})
> `

检查下时间的格式，应该为``%Y/%m/%d %H:%M:%S``这样的格式

**Comment by shuaiguoer** [comment]
@Raibows 谢谢，我刚发现是因为我使用了区域缩放控件后导致的，去掉区域缩放后，按照您的提示修改后就可以成功显示了，遗憾的是目前无法进行区域缩放了
