### ISSUE TITLE
柱状图展示中-数据平均值显示异常

### ISSUE THREAD

**Issue by jinquanhealsci** [pyecharts/pyecharts#1375]
**问题**
柱状图展示中-数据平均值显示异常

**运行环境（系统环境及 pyecharts 版本）**
Windows系统10 Anaconda3  jupyter
pyecharts version 1.5.1

**代码及截图**
from pyecharts.charts import Bar
from pyecharts import options as opts
from pyecharts.globals import ThemeType
bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 70, 75, 90])
bar.set_series_opts(itemstyle_opts={"color": '#9932CC'},
                    label_opts=opts.LabelOpts(is_show=False),
                    markpoint_opts=opts.MarkPointOpts(
                        data=[
                            opts.MarkPointItem(type_="max", name="最大值"),
                            opts.MarkPointItem(type_="min", name="最小值"),
                            opts.MarkPointItem(type_="average", name="平均值"),
                        ]
                    ),                   
                   )
bar.render_notebook()
![image](https://user-images.githubusercontent.com/27465081/66900879-316f8780-f030-11e9-8262-177fdef51e67.png)

根据数据[5, 70, 75, 90]计算得出平均值为60，图片中显示为70.

**Comment by jinquanhealsci** [comment]
补充:
 from pyecharts.charts import Bar
from pyecharts import options as opts
from pyecharts.globals import ThemeType
bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 70, 75, 90])
bar.set_series_opts(itemstyle_opts={"color": '#9932CC'},
                    label_opts=opts.LabelOpts(is_show=False),
                    markpoint_opts=opts.MarkPointOpts(
                        data=[
                            opts.MarkPointItem(type_="max", name="最大值"),
                            opts.MarkPointItem(type_="min", name="最小值"),
                            opts.MarkPointItem(type_="average", name="平均值"),
                        ]
                    ),
                    markline_opts=opts.MarkLineOpts(
                        data=[
                            opts.MarkLineItem(type_="min", name="最小值"),
                            opts.MarkLineItem(type_="max", name="最大值"),
                            opts.MarkLineItem(type_="average", name="平均值"),
                        ]
                    ),                    
)
bar.render_notebook()
![image](https://user-images.githubusercontent.com/27465081/66902890-0c7d1380-f034-11e9-83e4-531ed5d4993c.png)
横线表示则是正常。

**Comment by chenjiandongx** [comment]
标记点应该是 标注在最接近平均值的柱状上，不会标记到具体的点。
