### ISSUE TITLE
x轴type_使用’time‘，横轴强制从1970-1-1日开始，如何解决？

### ISSUE THREAD

**Issue by unlimitnight0** [pyecharts/pyecharts#1376]
代码：
            .set_global_opts(
                xaxis_opts=opts.AxisOpts(
                    type_='time'
                ),
            )
结果：
预期：x轴起始点为时间序列最小值
实际：x轴起始为从1970-1-1，导致图线显示不出来

**Comment by sunhailin-Leo** [comment]
@unlimitnight0 请贴一下完整的代码～大部分是因为数据问题。格式化成 `YYYY-MM-DD hh:mm:ss`
