### ISSUE TITLE
Bar的title可以在page里面检索

### ISSUE THREAD

**Issue by Dengnj** [pyecharts/pyecharts#1377]
**问题**
Bar的title可以在page里面检索，打开HTML文件后可以通过检索title定位到图标， 在Table的里面可以实现

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Dengnj 这个目前暂时无法实现的，如果有解决办法的话，请根据 pyecharts 的开发约定，进行代码提交 thx～

**Comment by Dengnj** [comment]
开发好了一个临时版本，供大家参考吧
pip install git+https://github.com/Dengnj/pyecharts-retrievableTitle.git
