### ISSUE TITLE
直角坐标，折线图，label fomatter{c}展示的是横纵坐标，应该展示纵坐标

### ISSUE THREAD

**Issue by dagong10** [pyecharts/pyecharts#1378]
**问题**
折线图，label使用{c}%展示，结果输出的是横纵坐标+%

**运行环境（系统环境及 pyecharts 版本）**
windows7 jupyterlab , pyecharts 1.5.1

**代码及截图**
![Uploading 微信图片_20191017161756.png…]()

import pyecharts.options as opts
from pyecharts.faker import  Faker
from pyecharts.charts import Line
from pyecharts.render import make_snapshot
from snapshot_phantomjs import snapshot

from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB

def line_smooth() -> Line:
    c = (
        Line()
        .add_xaxis(['2019-10-10', '2019-10-11', '2019-10-12', '2019-10-13', '2019-10-14', '2019-10-15', '2019-10-16'])
        .add_yaxis("商家A", [0.5653, 0.5307, 0.5029, 0.4837, 0.4303, 0.4801, 0.5649], 
                   is_smooth=True,
                   label_opts=opts.LabelOpts(formatter='{c}%'))
        .set_global_opts(title_opts=opts.TitleOpts(title="Line-smooth"))
    )
    return c

liquid= line_smooth()
liquid.load_javascript()
liquid.render_notebook()

**Comment by sunhailin-Leo** [comment]
@dagong10 图片挂了～ `{c}` 这个有点奇怪现在，不过你可以用 `{@[n]}` 这个进行尝试（设置 n 的值）
* 可以参考链接：https://github.com/pyecharts/pyecharts/issues/1398
