### ISSUE TITLE
add_yaxis 传入的yaxis_data 类型和值都相同，但是自己生成的可以画出图，从数据库获取的画不出图

### ISSUE THREAD

**Issue by zeiZeit** [pyecharts/pyecharts#1379]
**问题**

add_yaxis 传入的yaxis_data 类型和值都相同，但是自己生成的可以画出图，从数据库获取的画不出图

**运行环境（系统环境及 pyecharts 版本）**

win10,pycharm, pyecharts-1.5.1

**代码及截图**

![image](https://user-images.githubusercontent.com/25477272/67000808-11f95d00-f10b-11e9-86c6-b9235050c71c.png)

输出：
![image](https://user-images.githubusercontent.com/25477272/67000550-9d262300-f10a-11e9-8a33-7b70fed2c7d4.png)

当传入的值是v1时：
![image](https://user-images.githubusercontent.com/25477272/67000604-b7600100-f10a-11e9-888a-6ef7cc833e95.png)

当传入的值时v2时：
![image](https://user-images.githubusercontent.com/25477272/67000892-335a4900-f10b-11e9-8ea0-db0ec23c30db.png)

求解这个玄学问题

**Comment by zeiZeit** [comment]
哇，找到原因了：https://github.com/pyecharts/pyecharts/issues/1224
麻烦后边更新一下对int64的支持可以吗

**Comment by chenjiandongx** [comment]
可以考虑
