### ISSUE TITLE
Bar图x轴type_设为“time”会强制把yaxis的数据排序

### ISSUE THREAD

**Issue by mitchellwind** [pyecharts/pyecharts#1380]
**运行环境（系统环境及 pyecharts 版本）**
mac 10.14.6
python 3.7
pyecharts 1.5.1

**代码及截图**
* 如下图，Bar的Xaxis的type_设为‘time’就会把y原先的[5, 2, 3, 4, 1]自动排序；
![image](https://user-images.githubusercontent.com/26807833/67049194-f22b5e80-f135-11e9-837e-1f54d83c87a0.png)
* 即使把x换成python自带日期也不行：
![image](https://user-images.githubusercontent.com/26807833/67049355-53ebc880-f136-11e9-8bf1-7c2c00d8f549.png)
![image](https://user-images.githubusercontent.com/26807833/67049364-5c440380-f136-11e9-89e7-52d02b253157.png)
* 但如果是Line就没有这个问题：
![image](https://user-images.githubusercontent.com/26807833/67049430-7f6eb300-f136-11e9-83b6-a6e4884f8954.png)

**Comment by sunhailin-Leo** [comment]
* Bar 图的把 x 轴设置成 `category`

**Comment by sunhailin-Leo** [comment]
```python
from pyecharts import options as opts
from pyecharts.charts import Bar


(
    Bar()
    .add_xaxis(xaxis_data=["2005-1-1 8:00:00", "2005-2-1 8:00:00", "2005-3-1 8:00:00", "2005-4-1 8:00:00", "2005-5-1 8:00:00"])
    .add_yaxis("数据", yaxis_data=[5, 2, 3, 4, 1])
    .set_global_opts(
        xaxis_opts=opts.AxisOpts(type_="category"),
    )
    .render()
)

```
