### ISSUE TITLE
请问生成的图表在HTML中如何才能居中显示呢？目前生成的图表都是在左上角显示，这个应该如何设置呢？

### ISSUE THREAD

**Issue by Roman996363785** [pyecharts/pyecharts#1381]
**问题**
请问生成的图表在HTML中如何才能居中显示呢？目前生成的图表都是在左上角显示，这个应该如何设置呢？

**运行环境（系统环境及 pyecharts 版本）**

1.5.1

**代码及截图**

**Comment by chenjiandongx** [comment]
可以使用 SimplePageLayout  布局

https://pyecharts.org/#/zh-cn/composite_charts?id=page%ef%bc%9a%e9%a1%ba%e5%ba%8f%e5%a4%9a%e5%9b%be
