### ISSUE TITLE
是否支持echart中的legend的selected属性？

### ISSUE THREAD

**Issue by cq561835468** [pyecharts/pyecharts#1385]
**问题**
是否支持echart中的legend的selected属性？
我在api文档中没找到，可以限制只展现类别的属性

**运行环境（系统环境及 pyecharts 版本）**
version：1.5.1
系统：Win10

**代码及截图**
    legend: {
        type: 'scroll',
        orient: 'vertical',
        right: 10,
        top: 20,
        bottom: 20,
        selected: {"name":True}
    },

**Comment by chenjiandongx** [comment]
bar.add_yaxis(is_selected=False)
