### ISSUE TITLE
如何在IPythonNotebook的函数中渲染pyecharts图表？

### ISSUE THREAD

**Issue by TaylorScut** [pyecharts/pyecharts#1387]
**问题**
如果单独在命令行输入 render_notebook 是可以渲染图表的，但是在一个函数内部调用render_notebook就无法显示了。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.5 
python 3.7 

**代码及截图**
，比如：
from pyecharts.charts import Bar
bar = (
        Bar()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    )
bar.render_notebook()
![image](https://user-images.githubusercontent.com/9932139/67633906-cd32aa80-f8f0-11e9-823c-25769bb262be.png)

但是如果将 render_notebook 写入到一个函数中，却无法渲染pyecharts 
from pyecharts.charts import Bar

def plot_demo_bar():
    bar = (
        Bar()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    )
    bar.render()
    
plot_demo_bar()
![image](https://user-images.githubusercontent.com/9932139/67633917-f4897780-f8f0-11e9-8830-ecec09687545.png)
并没有结果显示。

如果是pyecharts 0.5 的版本，可以通过
from IPython.display import display 方法来实现，但是1.0 以后的版本不行了

**Comment by icecoldv4** [comment]
解决了么？现在也是这个问题，同时输出几个图的时候只会画出最后一个

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
> **问题**
> 如果单独在命令行输入 render_notebook 是可以渲染图表的，但是在一个函数内部调用render_notebook就无法显示了。
> 
> **运行环境（系统环境及 pyecharts 版本）**
> pyecharts 1.5
> python 3.7
> 
> **代码及截图**
> ，比如：
> from pyecharts.charts import Bar
> bar = (
> Bar()
> .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
> .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
> )
> bar.render_notebook()
> ![image](https://user-images.githubusercontent.com/9932139/67633906-cd32aa80-f8f0-11e9-823c-25769bb262be.png)
> 
> 但是如果将 render_notebook 写入到一个函数中，却无法渲染pyecharts
> from pyecharts.charts import Bar
> 
> def plot_demo_bar():
> bar = (
> Bar()
> .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
> .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
> )
> bar.render()
> 
> plot_demo_bar()
> ![image](https://user-images.githubusercontent.com/9932139/67633917-f4897780-f8f0-11e9-8830-ecec09687545.png)
> 并没有结果显示。
> 
> 如果是pyecharts 0.5 的版本，可以通过
> from IPython.display import display 方法来实现，但是1.0 以后的版本不行了

![img](https://user-images.githubusercontent.com/54145886/68636975-3bee4580-0538-11ea-8fbb-231c0b577813.png)

**在 pyecharts 中，使用 render 方法渲染会生成 html 文件并返回该 html 的路径，而 render_notebook 方法则是返回渲染后的 html 结果**

### 你遇到的问题解决方法：

- 在notebook 中使用了错误的渲染方式 render()，应该要使用 render_notebook()
- 没有使用 return 语句将渲染后的结果返回

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
> 解决了么？现在也是这个问题，同时输出几个图的时候只会画出最后一个

你遇到的问题参考我上面的回复，再参考下述代码应该可以解决（你先暂时这么解决，我之后再抽空看看 pyecharts 中有没有处理多图在 notebook 中渲染）
```python
from IPython.core.display import display


def gen_bar_line():
    bar = (
    Bar()
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    )
    line = (
    Line()
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    )
    render_result = [bar.render_notebook(), line.render_notebook()]
    return render_result

for chart_html in gen_bar_line():
    display(chart_html)
```

**Comment by TaylorScut** [comment]
我的实际需求是通过ipywidgets中的交互空间去修改相关参数，然后实现动态作图，因此需要在函数内部渲染才可以去实现。

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
> 我的实际需求是通过ipywidgets中的交互空间去修改相关参数，然后实现动态作图，因此需要在函数内部渲染才可以去实现。

```python
from IPython.core.display import display
from pyecharts.charts import Bar


def plot_demo_bar():
    bar = (
    Bar()
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    )
    display(bar.render_notebook())


plot_demo_bar()
```

这样子不可以吗？
