### ISSUE TITLE
setup.py无法正常运行

### ISSUE THREAD

**Issue by lajictw** [pyecharts/pyecharts#1388]
**问题**

linux环境下运行setup.py在以下几行报错，使得安装无法正常进行

**运行环境（系统环境及 pyecharts 版本）**
系统环境 linux kail 4.18.0
于2019年10月27日git clone后所得

**代码及截图**

![image](https://user-images.githubusercontent.com/40271784/67634151-492df200-f8f3-11e9-98ec-d31adee7bcb3.png)

**Comment by sunhailin-Leo** [comment]
@lajictw 具体贴一下异常信息

**Comment by lajictw** [comment]
噢...已经可以了，在前面加上用utf8编码打开就好了，一开始加成gbk了
