### ISSUE TITLE
runpy.py出错

### ISSUE THREAD

**Issue by CCCcheitinaJiang** [pyecharts/pyecharts#1390]
问题
win 10环境下安装pyecharts显示runpy.py出错，导致无法正常安装

运行环境（系统环境及 pyecharts 版本）
系统环境 win10
python 3.7.3

代码及截图
![new iussue](https://user-images.githubusercontent.com/49723337/67635412-cc564480-f901-11e9-8c5c-69c1fe971aba.png)

**Comment by sunhailin-Leo** [comment]
@CCCcheitinaJiang 这个具体是个什么问题？
我这边在 Windows / Mac / Linux 上测试过都没有问题～

**Comment by CCCcheitinaJiang** [comment]
我重新装了python好像就没有这个问题了 当时也不知道是怎么回事。谢谢您






------------------ 原始邮件 ------------------
发件人: LeoSun <notifications@github.com&gt;
发送时间: 2019年11月6日 22:47
收件人: pyecharts/pyecharts <pyecharts@noreply.github.com&gt;
抄送: CCCcheitinaJiang <1203429186@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[pyecharts/pyecharts] runpy.py出错 (#1390)




@CCCcheitinaJiang 这个具体是个什么问题？
 我这边在 Windows / Mac / Linux 上测试过都没有问题～
