### ISSUE TITLE
pyecharts：1.5.1，InitOpts，修改width、height报错

### ISSUE THREAD

**Issue by xray2008** [pyecharts/pyecharts#1391]
**问题**
InitOpts，修改width、height报错

**运行环境（系统环境及 pyecharts 版本）**
win10，pyecharts：1.5.1

**代码及截图**

代码
line.set_global_opts( init_opts=opts.InitOpts(width='500px', height='300px'))

报错：
line 77, in make_png1
    init_opts=opts.InitOpts(width='500px', height='300px')
TypeError: set_global_opts() got an unexpected keyword argument 'init_opts'

**Comment by chenjiandongx** [comment]
Line(init_opts=opts.InitOpts(width='500px', height='300px'))
