### ISSUE TITLE
from example.commons import Faker报错，ModuleNotFoundError: No module named 'example.commons'，请问examp

### ISSUE THREAD

**Issue by g1982117** [pyecharts/pyecharts#1393]
我是直接从https://pypi.org/project/pyecharts/#files 下载pyecharts-1.5.1-py3-none-any.whl ，然后本地化安装的pyecharts，请问哪里安装错了，谢谢各位大神。

**Comment by chfw** [comment]
Git clone 本项目

**Comment by g1982117** [comment]
from pyecharts.faker import Faker
from example.commons import Faker
改了import后就OK了，DEMO好像代码有问题

**Comment by sunhailin-Leo** [comment]
@g1982117 哪里有问题？贴一下代码

**Comment by g1982117** [comment]
@sunhailin-Leo 通过这个解决了from pyecharts.faker import Faker，应该是0.5版本和1.0版本的区别
