### ISSUE TITLE
vscode 中使用 jupyter 时，用 pyecharts 生成的图表空白

### ISSUE THREAD

**Issue by PyGroot** [pyecharts/pyecharts#1394]
运行环境：
vscode 1.39.2
jupyter 1.0.0
notebook 6.0.1
pyecharts 1.5.1

bar.render_notebook() 生成的图表在 vscode 中不显示，jupyter notebook 的网页中显示正常

**Comment by sunhailin-Leo** [comment]
vscode 的问题，如果有加微信群的话，应该也解释过。因为 VSCode 的渲染机制我们看不到，所以不保证在 VSCode 的 jupyter notebook 能渲染出来

**Comment by rockcitystore** [comment]
关闭vscode 插件Jupyter Notebook Renderers 可以正常工作了
