### ISSUE TITLE
请问地理坐标里面的geo()的add能够添加类似于铁路的轨迹吗？

### ISSUE THREAD

**Issue by g1982117** [pyecharts/pyecharts#1395]
目前add中的数据项案例中只能添加点和两点的连线，能否添加轨迹型的连线（如在china视图下添加某一条高铁线路走向）。谢谢！！！！

def add(
    # 系列名称，用于 tooltip 的显示，legend 的图例筛选。
    series_name: str,

    # 数据项 (坐标点名称，坐标点值)
    data_pair: Sequence,   目前只有两种1种点：（name,value），1种两点连线。
 [("广州", "上海"), ("广州", "北京"), ("广州", "杭州"), ("广州", "重庆")]

**Comment by sunhailin-Leo** [comment]
@g1982117 你可以先去 echarts 的示例或者 gallery 中找一下有没有类似的 demo。如果有的话，可以贴到这～
