### ISSUE TITLE
词云每次生成结果不一样，有部分会不显示

### ISSUE THREAD

**Issue by douzs** [pyecharts/pyecharts#1396]
**问题**

词云每次生成结果不一样，有部分会不显示

**运行环境（系统环境及 pyecharts 版本）**
python3.7.4

**代码及截图**

from snapshot_selenium import snapshot as driver
from pyecharts import options as opts
from pyecharts.charts import WordCloud
#from pyecharts.globals import SymbolType
from pyecharts.render import make_snapshot
from pyecharts.globals import ThemeType

words = [
("红旗渠(软红)",23688),
("红塔山(软经典)",158878),
("金圣(滕王阁.紫光)",1257),
("玉溪(硬)",1019),
("云烟(硬苁蓉)",1752),
("黄鹤楼(硬嘉禧缘)",1065),
("黄鹤楼(硬银紫)",3356),
("中南海(金8mg)",2514),
("钻石(荷花)",2977),
("钻石(西柏坡)",1300),
("钻石（硬珍品）",1862),
("泰山(宏图)",4566),
("七匹狼(纯境)2",1168),
("黄鹤楼(天下名楼)",9780),
("兰州(硬精品)",2372),
("黄金叶(金满堂)",29122),
("钻石(软绿)",1164),
("钻石(硬玫瑰紫)",42067),
("钻石（金石）(张家口)",3097),
("钻石（绿石2代）",39520),
("哈德门(金典)",4235),
("红河(小熊猫世纪风)",48172),
("长白山(软红)",4790),
("娇子(X)",3023),
("庐山(精品)",4922),
("庐山(新)",12785),
("七匹狼(白)",1574),
("白沙(精品二代)(石家庄)",10569),
("红梅(软黄)",18558),
("红山茶(软)",1930),
("红塔山(细支传奇)2",2454),
("金圣(硬滕王阁)",1799),
("云烟(软珍品)",18603),
("中华(软)",3008),
("钻石(红石2代)",65125),
("钻石(银玉兰)",11088),
("钻石(硬特醇)",176702),
("芙蓉王(硬)",5008),
("芙蓉王(硬细支)",3415),
("哈德门(纯香)",5845),
("哈尔滨(老巴夺)",3258),
("南京(炫赫门)",20788),
("黄鹤楼(硬金砂)",2302),
("钻石(平安)",32347),
("钻石(细支荷花)",2980),
("贵烟(跨越)",1992),
("好猫(细支长乐)",3646),
("大前门(短支)",1275),
("黄山(新一品)",35483),
("红金龙(硬蓝爱你)",3681),
("黄鹤楼(软雪之景)",2145),
("利群(新版)",95779),
("新石家庄(软)(石家庄)",27264),
("新石家庄(软)(张家口)",21333),
("人民大会堂(硬红细支)2",1315),
("黄金叶(爱尚)",2158),
("钻石(金玉兰)2",2307),
("钻石(软红)",44144),
("都宝(新)",7455),
("泰山(心悦)",2157),
("天子(金)",1219),
("黄山(印象一品)",2990),
("黄山(硬记忆)2",1109),
("牡丹(软)",2013),
("555(金?锐)",1055),
("白沙(绿和)(石家庄)",9742),
("金圣（软红）",4967),
("云烟(细支云龙)",4422),
("真龙(凌云)",1354),
("人民大会堂(硬红)",1338),
("黄金叶(小目标)",2450),
("中华(硬)",7158),
("中南海(特高)",2365),
("钻石(鸿运)",115802),
("长白山(蓝尚)",1190),
("大前门(软)",1403),
("泰山(红将军)",8578),
("白沙(硬)(石家庄)",53470),
("白沙(硬天天向上细支)",2320),
("红梅(软顺)",50000),
("红旗渠(雪茄)",19311),
("红双喜(硬)(上海)",1142),
("黄鹤楼(软蓝)",5811),
("玉溪(软)",15734),
("玉溪(细支清香世家)",2548),
("云烟(红)",30957),
("钻石(硬蓝)",25414),
("钻石(硬迎宾)",15103),
("娇子(格调细支)",2127),
("金桥(软混)",1699),
("南京(十二钗烤烟)",1453),
("七匹狼(红)",2229),
("红塔山(新时代)",4888),
("利群(蓝天)",7522),
("云烟(紫)",73888),
("黄金叶(喜满堂)",14262),
("黄山(记忆)",1249),
("黄山(软大壹品)",1686),
("双喜(莲香)",13246),
("钻石(经典纯和)",4410),
("钻石(细支尚风)",14686),
("钻石(细支心世界)2",4600),
("钻石(硬红)",82587),
("红河(A7)",1314),
("长白山(777)",13672),
("长白山(红)",6708),
("苏烟(五星红杉树)",2374),
("南京(红)",13504),
("七匹狼(豪情)",25433),
]

def wordcloud_base() -> WordCloud:
    c = (
        WordCloud(init_opts=opts.InitOpts(theme=ThemeType.LIGHT,width="1024px",height="968px"))
        .add(
            "",
            data_pair=words,
            word_size_range=[6, 500],
            shape="circle",
            tooltip_opts=opts.TooltipOpts(is_show=True)
            )
        .set_global_opts(
            title_opts=opts.TitleOpts(title="WordCloud-基本示例"),

            )
        
    )
    return c
    
wordcloud_base().render()
#make_snapshot(driver, wordcloud_base().render(), "bar.png")

生成的html网页，为什么每次刷新结果都会变？

![1](https://user-images.githubusercontent.com/50008362/67929709-e7260300-fbf8-11e9-9d94-9fa896f88365.jpg)
![2](https://user-images.githubusercontent.com/50008362/67929735-f6a54c00-fbf8-11e9-96b2-e347cfff487e.jpg)
![3](https://user-images.githubusercontent.com/50008362/67929741-fe64f080-fbf8-11e9-9687-ed0e66da541b.jpg)

**Comment by sunhailin-Leo** [comment]
@douzs 那个是 echarts-wordcloud 的效果，这个具体我们也没有参数设置它不变，可以看一下 echarts-wordcloud 的开源项目有没有有关的配置，然后回复我们一下。 thx～
