### ISSUE TITLE
v1.5.1 无法使用自制主题

### ISSUE THREAD

**Issue by onomas** [pyecharts/pyecharts#1397]
**问题**
为什么使用自制主题时候无法显示制作主题的效果？

**运行环境（系统环境及 pyecharts 版本）**
macos Sierra 10.12
python 3.7
pyecharts 1.5.1

**代码及截图**

已经按教程指示，启用pyecharts-assets服务，也验证过访问文件没有问题
除了自制主题完全无法加载以外，自带主题也是没有动画效果的
后台显示主题js文件已加载，但页面并没有显示出主题的颜色和线条配置
求指点，是哪一个环节没有做好或者出错了，不胜感激。

CurrentConfig.ONLINE_HOST = "http://127.0.0.1:8000/assets/"
register_files({"mytheme": ["themes/mytheme", "js"]})

def charts_demo(request):
    dt = [
        '2019-09-01', '2019-09-02', '2019-09-03', '2019-09-04',
        '2019-09-05', '2019-09-06', '2019-09-07',
        '2019-09-08', '2019-09-09', '2019-09-10',
    ]
    last = [random.randint(1, 100) for i in range(10)]
    now = [random.randint(1, 100) for i in range(10)]
    c = Line(init_opts=opts.InitOpts(theme='mytheme'))
    c.add_xaxis(dt)
    c.add_yaxis("今年", now)
    c.add_yaxis("去年", last)
    c.set_global_opts(
        title_opts=opts.TitleOpts(title="title"),
        toolbox_opts=opts.ToolboxOpts(),
    )
    return HttpResponse(c.render_embed())

实际效果：
![image](https://user-images.githubusercontent.com/30553508/68016789-41de5e00-fcd0-11e9-8c8c-f7020258743d.png)

主题制作效果：
![image](https://user-images.githubusercontent.com/30553508/68017110-ee204480-fcd0-11e9-9657-8d4f579b2513.png)

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
问题原因：既然题主已经给主题命名为了 `mytheme.js`，那么 `echarts `注册的主题名称 (`... echarts.registerTheme('xxx', ...`)，和你在 pyecharts 渲染好的 render.html 中使用的主题名称 (`... document.getElementById('334385b2c66a46aa8b9b4d1d2b781310'), 'mytheme', {renderer: 'canvas'}); ...`) 不一致

解决方法：**在 mytheme.js 中找到 `echarts.registerTheme` ，将其中注册的主题名称更改为 `mytheme`，保存且启动 `http `服务后，重新刷新页面即可**

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
解决方法2：**重新在 echarts 官网[构建主题](https://echarts.baidu.com/theme-builder/)，在下载时，确保下图中圈出的主题名称与保存文件名一致**
![issue#1397](https://user-images.githubusercontent.com/54145886/68727833-7a4f3780-0600-11ea-8a73-121e47665ad5.png)
