### ISSUE TITLE
bug：Line的label_opts=opts.LabelOpts(formatter='{c}w') 画出来的{c}是数组，正确的应该是数值

### ISSUE THREAD

**Issue by xray2008** [pyecharts/pyecharts#1398]
**问题**
bug：Line的label_opts=opts.LabelOpts(formatter='{c}w') 画出来的{c}是数组（正确的应该是数值，而不是数组）
相反：Bar用这个属性就是正确的

**运行环境（系统环境及 pyecharts 版本）**
OS：win10 
pyecharts：1.5.1

**代码及截图**
    line.add_yaxis(scene_list2[1], count_list2, label_opts=opts.LabelOpts(formatter='{c}w'))

![image](https://user-images.githubusercontent.com/15886483/68083667-46d51600-fe66-11e9-85ca-cf0efe203fec.png)

**Comment by sunhailin-Leo** [comment]
@xray2008 随便举了个例子，见下面示例

**Comment by sunhailin-Leo** [comment]
![image](https://user-images.githubusercontent.com/17564655/68310480-0b974900-00eb-11ea-861f-d0d94c9a5b48.png)

**Comment by sunhailin-Leo** [comment]
```python
from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.charts import Line


def line_smooth() -> Line:
    c = (
        Line()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家B", Faker.values(), is_smooth=True, label_opts=opts.LabelOpts(formatter="{@[1]} w"))
        .set_global_opts(title_opts=opts.TitleOpts(title="Line-smooth"))
        .render()
    )
    return c


if __name__ == '__main__':
    line_smooth()

```

**Comment by sunhailin-Leo** [comment]
![image](https://user-images.githubusercontent.com/17564655/68310650-56b15c00-00eb-11ea-8aa6-8d45dec9956d.png)
https://www.echartsjs.com/zh/option.html#series-line.label.formatter

**Comment by xray2008** [comment]
get it！thanks
