### ISSUE TITLE
Scatter3D里面怎么设置每个类的点一个颜色?

### ISSUE THREAD

**Issue by celina0321** [pyecharts/pyecharts#1400]
**问题**
Scatter3D里面怎么设置每个类的点一个颜色?
我使用了三个add将三个类的点加到图中

**运行环境（系统环境及 pyecharts 版本）**
ubuntu18.04
0.1.9.4

**代码及截图**
`[page = Page()
    # range_color = ['#72a93f', '#e57c27', '#368dc4']
    scatter3D = Scatter3D("3D", width=1200, height=600) 
    scatter3D.add("a", a, xaxis3d_min=-2.5, xaxis3d_max=2.5, yaxis3d_min=-0.1, yaxis3d_max=0.1)
    scatter3D.add("b", b, xaxis3d_min=-2.5, xaxis3d_max=2.5, yaxis3d_min=-0.1, yaxis3d_max=0.1) 
    scatter3D.add("c", c, xaxis3d_min=-2.5, xaxis3d_max=2.5, yaxis3d_min=-0.1, yaxis3d_max=0.1) 
    page.add(scatter3D)
    page.render('test.html')
](url)`

**Comment by sunhailin-Leo** [comment]
@celina0321 稍微把代码贴完整点

**Comment by sunhailin-Leo** [comment]
```python
import random

from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.charts import Scatter3D


def scatter3d_base() -> Scatter3D:
    data = [
        [random.randint(0, 100), random.randint(0, 100), random.randint(0, 100)]
        for _ in range(80)
    ]
    c = (
        Scatter3D()
        .add("", data)
        .set_global_opts(
            title_opts=opts.TitleOpts("Scatter3D-基本示例"),
            visualmap_opts=opts.VisualMapOpts(range_color=Faker.visual_color, is_piecewise=True),
        )
        .render()
    )
    return c


if __name__ == '__main__':
    scatter3d_base()
```

**Comment by sunhailin-Leo** [comment]
![image](https://user-images.githubusercontent.com/17564655/68309972-3cc34980-00ea-11ea-8e02-6f65c763e90b.png)

**Comment by celina0321** [comment]
@sunhailin-Leo 感谢,已经解决了

**Comment by Rogersjk** [comment]
> @sunhailin-Leo 感谢,已经解决了

请问一下怎么解决的呀，我也有这个需求
