### ISSUE TITLE
关于一个叠图的一列数据，能否在label处显示一个百分比呢？

### ISSUE THREAD

**Issue by xiaomaoaichiyu** [pyecharts/pyecharts#1403]
**问题**
我现在有一个柱形图；是一个叠图；
然后每一列有两个数据，一个是完成的，一个是未完成的，二者叠加共同构成一列，我想在label显示其中之一占用二者之和的百分数，怎么做呢？
希望实现的效果是label显示对应的数据占每一列的百分比（help！！

**运行环境（系统环境及 pyecharts 版本）**
anaconda python3.7.3  
pyecharts 1.5.1

**代码及截图**
from pyecharts.charts import Bar
from pyecharts import options as opts
from pyecharts.globals import ThemeType

def getBar() -> Bar:
    list1 = [1, 2, 3, 4, 5]
    list2 = [12, 23, 33, 3, 33]
    list3 = [3, 21, 5, 52, 43]

    c = (
        Bar(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
        .add_xaxis(list1)
        .add_yaxis('完成', list2, stack='stack1')
        .add_yaxis('未完成', list3, stack='stack1')
        .set_series_opts(label_opts=opts.LabelOpts(position='right'))
    )
    return c

![image](https://user-images.githubusercontent.com/40788520/68528617-1858ae80-0330-11ea-9b66-6d2deda8ec09.png)

**Comment by sunhailin-Leo** [comment]
@xiaomaoaichiyu 
![image](https://user-images.githubusercontent.com/17564655/68543746-53251a00-03f6-11ea-9124-4cd72e61ff96.png)

**Comment by sunhailin-Leo** [comment]
* New demo Code
```python
from pyecharts.commons.utils import JsCode

from pyecharts.charts import Bar
from pyecharts import options as opts
from pyecharts.globals import ThemeType


def stack_bar_percent():
    list1 = [1, 2, 3, 4, 5]
    list2 = [
        {"value": 12, "percent": 12 / (12 + 3)},
        {"value": 23, "percent": 23 / (23 + 21)},
        {"value": 33, "percent": 33 / (33 + 5)},
        {"value": 3, "percent": 3 / (3 + 52)},
        {"value": 33, "percent": 33 / (33 + 43)},
    ]

    list3 = [
        {"value": 3, "percent": 3 / (12 + 3)},
        {"value": 21, "percent": 21 / (23 + 21)},
        {"value": 5, "percent": 5 / (33 + 5)},
        {"value": 52, "percent": 52 / (3 + 52)},
        {"value": 43, "percent": 43 / (33 + 43)},
    ]

    (
        Bar(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
        .add_xaxis(list1)
        .add_yaxis("product1", list2, stack="stack1", category_gap="50%")
        .add_yaxis("product2", list3, stack="stack1", category_gap="50%")
        .set_series_opts(
            label_opts=opts.LabelOpts(
                position="right",
                formatter=JsCode(
                    "function(x) {console.log(x); return Number(x.data.percent * 100).toFixed() + '%' ;}"
                ),
            )
        )
        .render("stack_bar_percent.html")
    )


if __name__ == "__main__":
    stack_bar_percent()
```

**Comment by xiaomaoaichiyu** [comment]
Thx. this help a lot!
