### ISSUE TITLE
Timeline组合Sankey图，实际只显示最有一个时间点的桑基图

### ISSUE THREAD

**Issue by motimace** [pyecharts/pyecharts#1407]
**问题**
使用Timeline组合Sankey图，只显示最后一个时间点的桑基图
（测试散点图没问题，可以随时间变化）
**运行环境（系统环境及 pyecharts 版本）**
windows 10
Python 3.7.3
pyecharts 1.5.1
**代码及截图**
from pyecharts import options as opts
from pyecharts.charts import Sankey, Timeline
from pyecharts.globals import ThemeType
data = {2004:[1,2], 2005:[10,20], 2006:[6,3]}
tl = Timeline()
for year in range(2004, 2007):
    water = data[year]
    nodes = [{'name': 'class1'}, {'name': 'class2'}, {'name': 'class3'},]
    links = [
        {"source": "class1", "target": "class2", "value": water[0]},
        {"source": "class2", "target": "class3", "value": water[1]},
        ]
    sankey = Sankey(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
    sankey.add("", nodes, links,
           linestyle_opt=opts.LineStyleOpts(opacity=0.2, curve=0.5, color="source"),
           label_opts=opts.LabelOpts(position="right"))
    tl.add(sankey, "{}".format(year))
tl.render()

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
![issue#1407](https://user-images.githubusercontent.com/54145886/68682007-63c4c400-059f-11ea-8e8a-e03a396cca1e.png)


- 问题原因：`render` 方法打印出了渲染后的 html 文件路径，打印了三次，由于文件名称一致，因此每次生成的文件都覆盖了上一次的文件。
- 解决方法：见 [`render` 方法 `path` 参数注释](https://github.com/pyecharts/pyecharts/blob/854347fe1b4e3c74a3ad1f2608dbf9c125c0d620/pyecharts/render/engine.py#L48)，可知我们在调用 render 方法时可以通过传入不同的 ` path` 来生成不同的目标 html 文件

**Comment by sunhailin-Leo** [comment]
@ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu 
* timeline 不是你那样用的

**Comment by sunhailin-Leo** [comment]
@motimace 
* 目前我在 echarts 的 gallery 里面也没有找到 Sankey + Timeline 的 demo，如果有的话你可以提供一下。
* 目前我用了你的代码的确也无法实现。应该和 echarts 的处理逻辑有关系。
* 按理来说下面的代码应该是可以实现的（提供代码尽量按照 markdown 贴代码的方式）
```python
from pyecharts import options as opts
from pyecharts.charts import Sankey, Timeline
from pyecharts.globals import ThemeType

data = {2004: [1, 2], 2005: [10, 20], 2006: [6, 3]}
nodes = [{"name": "class1"}, {"name": "class2"}, {"name": "class3"}]


tl = Timeline()
for year in range(2004, 2007):
    water = data[year]
    links = [
        {"source": "class1", "target": "class2", "value": water[0]},
        {"source": "class2", "target": "class3", "value": water[1]},
    ]
    s = (
        Sankey(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
        .add(
            "{} 年数据".format(year),
            nodes,
            links,
            linestyle_opt=opts.LineStyleOpts(opacity=0.2, curve=0.5, color="source"),
            label_opts=opts.LabelOpts(position="right"),
        )
        .set_global_opts(title_opts=opts.TitleOpts(title="{} 年".format(year)))
    )
    tl.add(s, "{}".format(year))
tl.render("issue-1407.html")
```

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
> @ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu
> 
> * `timeline` 不是你那样用的
> * 在 `timeline` 使用场景下 `render` 应当处在 `for` 循环之外

哦哦，不好意思，我刚接触 echarts 和 pyecharts，搞错了，请多海涵。

**Comment by motimace** [comment]
多谢提醒，粘贴的时候没注意。

**Comment by sunhailin-Leo** [comment]
@ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu @motimace 
* 你们可以试试用 echarts 的代码，如果可以的话贴一份给我复刻，如果不可以的话可以去 echarts 那边提个 issue。
* 不过感觉桑基图结合时间轴这个场景挺少见的 😄

**Comment by motimace** [comment]
option = {
    baseOption: {
        timeline: {
            axisType: 'category',
            autoPlay: true,
            // currentIndex: 2,
            playInterval: 2000,
            tooltip: {},
            data: ['1', '2', '3'],
        },
    },
    options: [
        {
            series:{
                type: 'sankey',
                layout: 'none',
                focusNodeAdjacency: 'allEdges',
                data: [{
                    name: 'a'
                }, {
                    name: 'b'
                }, {
                    name: 'c'
                }],
                links: [{
                    source: 'a',
                    target: 'b',
                    value: 5
                }, {
                    source: 'a',
                    target: 'c',
                    value: 3
                }]
            }
        },
        {
            series:{
                type: 'sankey',
                layout: 'none',
                focusNodeAdjacency: 'allEdges',
                data: [{
                    name: 'A'
                }, {
                    name: 'B'
                }, {
                    name: 'C'
                }],
                links: [{
                    source: 'A',
                    target: 'C',
                    value: 5
                }, {
                    source: 'B',
                    target: 'C',
                    value: 10
                }]
                },
        },
        {
            series: {
                type: 'sankey',
                layout: 'none',
                focusNodeAdjacency: 'allEdges',
                data: [{
                    name: 'x',
                }, {
                    name: 'y'
                }, {
                    name: 'z'
                }, {
                    name: 'w'
                }],
                links: [{
                    source: 'x',
                    target: 'y',
                    value: 2
                }, {
                    source: 'y',
                    target: 'z',
                    value: 4
                }, {
                    source: 'y',
                    target: 'w',
                    value: 5
                }]
            }
        }
        ]
};

**Comment by motimace** [comment]
`option = {
    baseOption: {
        timeline: {
            axisType: 'category',
            autoPlay: true,
            // currentIndex: 2,
            playInterval: 2000,
            tooltip: {},
            data: ['1', '2', '3'],
        },
    },
    options: [
        {
            series:{
                type: 'sankey',
                layout: 'none',
                focusNodeAdjacency: 'allEdges',
                data: [{
                    name: 'a'
                }, {
                    name: 'b'
                }, {
                    name: 'c'
                }],
                links: [{
                    source: 'a',
                    target: 'b',
                    value: 5
                }, {
                    source: 'a',
                    target: 'c',
                    value: 3
                }]
            }
        },
        {
            series:{
                type: 'sankey',
                layout: 'none',
                focusNodeAdjacency: 'allEdges',
                data: [{
                    name: 'A'
                }, {
                    name: 'B'
                }, {
                    name: 'C'
                }],
                links: [{
                    source: 'A',
                    target: 'C',
                    value: 5
                }, {
                    source: 'B',
                    target: 'C',
                    value: 10
                }]
                },
        },
        {
            series: {
                type: 'sankey',
                layout: 'none',
                focusNodeAdjacency: 'allEdges',
                data: [{
                    name: 'x',
                }, {
                    name: 'y'
                }, {
                    name: 'z'
                }, {
                    name: 'w'
                }],
                links: [{
                    source: 'x',
                    target: 'y',
                    value: 2
                }, {
                    source: 'y',
                    target: 'z',
                    value: 4
                }, {
                    source: 'y',
                    target: 'w',
                    value: 5
                }]
            }
        }
        ]
};`

**Comment by motimace** [comment]
我测试了echarts是可以的。

```javascript
option = {
    baseOption: {
        timeline: {
            axisType: 'category',
            autoPlay: true,
            // currentIndex: 2,
            playInterval: 2000,
            tooltip: {},
            data: ['1', '2', '3'],
        },
    },
    options: [
        {
            series:{
                type: 'sankey',
                layout: 'none',
                focusNodeAdjacency: 'allEdges',
                data: [{
                    name: 'a'
                }, {
                    name: 'b'
                }, {
                    name: 'c'
                }],
                links: [{
                    source: 'a',
                    target: 'b',
                    value: 5
                }, {
                    source: 'a',
                    target: 'c',
                    value: 3
                }]
            }
        },
        {
            series:{
                type: 'sankey',
                layout: 'none',
                focusNodeAdjacency: 'allEdges',
                data: [{
                    name: 'A'
                }, {
                    name: 'B'
                }, {
                    name: 'C'
                }],
                links: [{
                    source: 'A',
                    target: 'C',
                    value: 5
                }, {
                    source: 'B',
                    target: 'C',
                    value: 10
                }]
                },
        },
        {
            series: {
                type: 'sankey',
                layout: 'none',
                focusNodeAdjacency: 'allEdges',
                data: [{
                    name: 'x',
                }, {
                    name: 'y'
                }, {
                    name: 'z'
                }, {
                    name: 'w'
                }],
                links: [{
                    source: 'x',
                    target: 'y',
                    value: 2
                }, {
                    source: 'y',
                    target: 'z',
                    value: 4
                }, {
                    source: 'y',
                    target: 'w',
                    value: 5
                }]
            }
        }
        ]
};
```
