### ISSUE TITLE
jupyter nootbook

### ISSUE THREAD

**Issue by zhentaoCoding** [pyecharts/pyecharts#1413]
在jupyter nootbook怎么显示空白

**运行环境（系统环境及 pyecharts 版本）**
pyecharts-1.5.1

**代码及截图**

![image](https://user-images.githubusercontent.com/5669444/68837137-e4e29f00-06f6-11ea-8115-19b65fb727ce.png)

**Comment by sunhailin-Leo** [comment]
@zhentaoCoding 
* 先看浏览器控制台有没出现异常
