### ISSUE TITLE
饼图

### ISSUE THREAD

**Issue by zhentaoCoding** [pyecharts/pyecharts#1414]
饼图怎样以百分比显示

**Comment by sunhailin-Leo** [comment]
![image](https://user-images.githubusercontent.com/17564655/68839264-4f95d980-06fb-11ea-9fba-324f83beb58f.png)
![image](https://user-images.githubusercontent.com/17564655/68839275-56bce780-06fb-11ea-90a9-4f7cf2cde423.png)
