### ISSUE TITLE
pyecharts show empty in vscode jupyter

### ISSUE THREAD

**Issue by veridone** [pyecharts/pyecharts#1416]
**问题**
I use pip to install pyecharts, and it's version is 1.5.1
It work well in web browser with Jupyter notebook
but in vscode with Jupyter it show nothing
I try other python plot library and it can work
so I think pyecharts can fix the show error in vscode

**运行环境（系统环境及 pyecharts 版本）**
python 3.6.4 in CentOS
visual studio code insiders (version 1.41.0)
pyecharts 1.5.1
jupyter 1.0.0

**代码及截图**
![11](https://user-images.githubusercontent.com/6941942/68993913-f4f5ac80-08b7-11ea-9e03-c7f5d515add4.JPG)
![70C7E962-0109-4220-9087-26ABFC70C57D](https://user-images.githubusercontent.com/6941942/68993971-47cf6400-08b8-11ea-9908-694d7976933e.JPG)
same code, but show empty 
I use plotly, and it works well
![90693058-ACFB-4215-853F-8EFEF2E5F4B8](https://user-images.githubusercontent.com/6941942/68994013-d17f3180-08b8-11ea-9fca-95671ade4d94.JPG)

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
- 相关 issue：https://github.com/pyecharts/pyecharts/issues/1394#issuecomment-550339214
- 解决方法：https://pyecharts.org/#/zh-cn/notebook?id=jupyter-lab

```python
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB

from pyecharts.faker import Faker
from pyecharts.charts import Pie

pie = (
    Pie()
    .add("", [list(z) for z in zip(Faker.choose(), Faker.values())])
)
pie.load_javascript()
```
```python
pie.render_notebook()
```

**Comment by veridone** [comment]
It WORKS, Thanks！
![7A340957-A4ED-4EB8-9BD7-37790D0DB703](https://user-images.githubusercontent.com/6941942/69713781-19ffe000-1140-11ea-91bc-3960ae684ef1.JPG)

**Comment by ArmyCAC** [comment]
met the same Question, still not work!
![image](https://user-images.githubusercontent.com/14289215/71348931-a3bc9500-25a8-11ea-9132-f206d862a9ad.png)

**Comment by anrgct** [comment]
很奇怪，我一开始运行都是空白的，然后在命令行用`jupyter notebook`启动了一次调出来echarts，再用vscode打开ipynb就可以了

**Comment by anrgct** [comment]
> 很奇怪，我一开始运行都是空白的，然后在命令行用`jupyter notebook`启动了一次调出来echarts，再用vscode打开ipynb就可以了

我突然想到，可能是生成的静态资源echarts.min.js加载太慢了，所以空白卡住，等加载了一次以后就好了

**Comment by rockcitystore** [comment]
关闭vscode 插件Jupyter Notebook Renderers 可以正常工作了
