### ISSUE TITLE
cannot import name 'Scatter' from 'pyecharts'

### ISSUE THREAD

**Issue by summerstington** [pyecharts/pyecharts#1417]
<!--
### 提 issue 注意事项
cannot import name 'Scatter' from 'pyecharts' (/Applications/anaconda3/lib/python3.7/site-packages/pyecharts/__init__.py)
 
![image](https://user-images.githubusercontent.com/35098915/69012707-bcd39400-09b3-11ea-827d-07287e958b38.png)

**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
试试像示例代码中这样 `import` 呢？https://github.com/pyecharts/pyecharts/blob/42717ac1a5be330586bba45196cce1ed961fef54/example/scatter_example.py#L2

**Comment by sunhailin-Leo** [comment]
@summerstington pyecharts.org
