### ISSUE TITLE
Grid上下布局双Bar图(DataZoomOpts：区域缩放配置项),下图显示异常

### ISSUE THREAD

**Issue by linfanli** [pyecharts/pyecharts#1418]
**问题**

Grid上下布局双Bar图(DataZoomOpts：区域缩放配置项),下图显示异常

**运行环境（系统环境及 pyecharts 版本）**
python v3.7.3
pyecharts v1.5.1   v1.6.0

**代码及截图**
`#####################################
#####################################

from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.charts import Bar, Grid

# 上图BAR1
def bar_datazoom_slider() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.days_attrs)
        .add_yaxis("商家A", Faker.days_values,stack="stack1")
        .add_yaxis("商家B", Faker.days_values,stack="stack1")
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Grid-上下布局(上图)"),
            datazoom_opts=[opts.DataZoomOpts()],
        )
    )
    return c
bar1 = bar_datazoom_slider()
bar1.render_notebook()

# 下图Bar2
def bar_datazoom_slider2() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.days_attrs)
        .add_yaxis("商家C", Faker.days_values,stack="stack1")
        .add_yaxis("商家D", Faker.days_values,stack="stack1")
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Grid-上下布局(下图)"),
            datazoom_opts=[opts.DataZoomOpts()],
        )
    )
    return c
bar2 = bar_datazoom_slider2()
bar2.render_notebook()

# Grid-上下布局
grid_chart = Grid()
grid_chart.add(
    bar1,
    grid_opts=opts.GridOpts(pos_left="10%", pos_right="8%", height="50%"),
)
grid_chart.add(
    bar2,
    grid_opts=opts.GridOpts(
        pos_left="10%", pos_right="8%", pos_top="70%", height="16%"
    ),
)
grid_chart.render_notebook()

`
<img width="1030" alt="屏幕快照 2019-11-18 下午11 03 32" src="https://user-images.githubusercontent.com/16367420/69063653-da5a3980-0a57-11ea-82b9-f7c463112212.png">

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
@linfanli 

1. 你的Grid-上下布局(下图)的两个 stack 参数**换一个名称**，不要和Grid-上下布局(上图)一样；
2. 参考 https://github.com/pyecharts/pyecharts/blob/42717ac1a5be330586bba45196cce1ed961fef54/example/grid_example.py#L25 给你的两个 `Bar `图增加 `title_opts `和 `legend_opts `的 `pos_top `或 `pos_bottom `参数

最后，提问之前多去看看 echarts、pyecharts 的文档或者仓库示例

**Comment by linfanli** [comment]
@ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu 文档看了多次，还是没完全理解参数的意思

1. stack 参数换一个名称 ，
2. 设置xaxis_index=[0, 1]

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
```python
bar1 = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values(), stack="stack1")
    .add_yaxis("商家B", Faker.values(), stack="stack1")
    .set_global_opts(title_opts=opts.TitleOpts(title="Grid-Bar"))
)
bar2 = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values(), stack="stack2")
    .add_yaxis("商家B", Faker.values(), stack="stack2")
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Grid-Line", pos_top="48%"),
        legend_opts=opts.LegendOpts(pos_top="48%"),
    )
)

grid = (
    Grid()
    .add(bar1, grid_opts=opts.GridOpts(pos_bottom="60%"))
    .add(bar2, grid_opts=opts.GridOpts(pos_top="60%"))
)
grid.render_notebook()
```
