### ISSUE TITLE
pyinstaller 无法打包pyecharts

### ISSUE THREAD

**Issue by panguxiaoshen** [pyecharts/pyecharts#1419]
安装的是都最新版本，python=3.6，生成的exe运行直接崩溃

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
[pyinstaller wiki](https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages) 未对 pyecharts 支持

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
当前版本（version is 1.6.0），主要需要引入的**资源**有模板 (pyecharts/render/templates) 和数据集 (pyecharts/datasets)。如果使用 pyinstaller 打包，则需要在打包时指定这些外部资源，将其和源码（及依赖）一起打包到生成的程序中。

具体操作如下：

1. 由于每个人的环境不一致，我们手动将需要的**资源**放到写好的 python 源码同目录。如下方所示：
```bash
|   showmychart.py  # python 源码
|   
+---datasets  # 资源 datasets
|       city_coordinates.json
|       countries_regions_db.json
|       map_filename.json
|       __init__.py
|       
\---templates  # 资源 templates
        components.html
        macro
        nb_components.html
        nb_jupyter_globe.html
        nb_jupyter_lab.html
        nb_jupyter_lab_tab.html
        nb_jupyter_notebook.html
        nb_jupyter_notebook_tab.html
        nb_nteract.html
        simple_chart.html
        simple_globe.html
        simple_page.html
        simple_tab.html
```
2. 打包
    * windows 使用 `pyinstaller  --add-data=".\datasets;pyecharts\datasets\." --add-data=".\templates;pyecharts\render\templates\." -F showmychart.py` 即可生成需要的 exe 程序（linux 也是类似的）

**Comment by screamsyk** [comment]
实在是打包有问题，我是放弃了使用 pyecharts，反正原理是写几个 echarts 图表的 html 模板，再读取后，替换一些对应的内容，从而生成对应的 html。干脆就自己实现了

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
是的，是因为本地静态资源无法正确打包导致的。你自己实现应该也是很快的

**Comment by chenjiandongx** [comment]
本团队不打算深入这块功能的开发

**Comment by jasongao93** [comment]
你好，我按照您的步骤添加了文件，并且也--add -data了，但还是同样的问题。下图是我放的文件夹，和我输入的语句，不知道是哪里错了吗？
![image](https://user-images.githubusercontent.com/99384161/153358366-7c9bb166-eec3-486d-8e92-ce77c7dfe1ef.png)
![image](https://user-images.githubusercontent.com/99384161/153358714-44f9767d-6446-4059-be1a-dd2a7b96cfe2.png)
![image](https://user-images.githubusercontent.com/99384161/153358844-2c312493-6951-4b24-ab6f-0c0261010753.png)

**Comment by screamsyk** [comment]
您好！邮件已收到，我会尽快查看与回复

**Comment by Leekaka97** [comment]
感谢 pyecharts团队，问题已经成功解决

**Comment by screamsyk** [comment]
您好！邮件已收到，我会尽快查看与回复

**Comment by timepasser69** [comment]
Thank you very much. it solved my issues. even though I have to translate back and forth... but the 

> @panguxiaoshen
> 
> 当前版本（version is 1.6.0），主要需要引入的**资源**有模板 (`pyecharts/render/templates`) 和数据集 (`pyecharts/datasets`)。如果使用 `pyinstaller` 打包，则需要在打包时**指定这些外部资源** (比如在命令行中使用 `--add-data` 参数)，将其和源码（及依赖）一起打包到生成的程序中。
> 
> 具体操作如下：
> 
> 1. 由于每个人的环境不一致，我们手动将需要的**资源**放到写好的 `python` 源码同目录。如下方所示：
> 
> ```shell
> |   showmychart.py  # python 源码
> |   
> +---datasets  # 资源 datasets
> |       city_coordinates.json
> |       countries_regions_db.json
> |       map_filename.json
> |       __init__.py
> |       
> \---templates  # 资源 templates
>         components.html
>         macro
>         nb_components.html
>         nb_jupyter_globe.html
>         nb_jupyter_lab.html
>         nb_jupyter_lab_tab.html
>         nb_jupyter_notebook.html
>         nb_jupyter_notebook_tab.html
>         nb_nteract.html
>         simple_chart.html
>         simple_globe.html
>         simple_page.html
>         simple_tab.html
> ```
> 
> 2. 打包
>    
>    * `windows` 使用 `pyinstaller  --add-data=".\datasets;pyecharts\datasets\." --add-data=".\templates;pyecharts\render\templates\." -F -w showmychart.py` 即可生成需要的 `exe` 程序（`linux` 也是类似的）
> 3. 执行程序
>    
>    * 进入生成的 dist 目录，执行生成的程序
>      ![issue1419](https://user-images.githubusercontent.com/54145886/69488729-48638e00-0ea8-11ea-8f84-6d2013fc176d.gif)
>            
>              [
>                
>                  ![issue1419](https://user-images.githubusercontent.com/54145886/69488729-48638e00-0ea8-11ea-8f84-6d2013fc176d.gif)
>                
>              ](https://user-images.githubusercontent.com/54145886/69488729-48638e00-0ea8-11ea-8f84-6d2013fc176d.gif)
>              
>              
>                
>                  
>                    
>                  
>                  
>                    
>                    
>                  
>                
>                [
>                  
>                    
>                  
>                ](https://user-images.githubusercontent.com/54145886/69488729-48638e00-0ea8-11ea-8f84-6d2013fc176d.gif)

Thank you very much. It solved my problem. Although i had to translate back and forth. but the screenshot helped. I cant thank you enough, sir.

**Comment by screamsyk** [comment]
您好！邮件已收到，我会尽快查看与回复

**Comment by Bassia777** [comment]
我这里有个好办法，你直接吧在pycharm里面打好包的pyecharts放到你的exe路径下面，也不用你打包搞资源什么的了
![image](https://github.com/pyecharts/pyecharts/assets/69617405/d649706c-1fd7-49fb-8282-e86ce386ca6d)

**Comment by screamsyk** [comment]
您好！邮件已收到，我会尽快查看与回复
