### ISSUE TITLE
横坐标太长，名称旋转角度也无法显示

### ISSUE THREAD

**Issue by clsteam** [pyecharts/pyecharts#1420]
**问题**
横坐标太长，名称旋转角度也无法显示
- 每一个bar都有一个名称，旋转角度太小，就不能完全显示所有的名称（echart自动省略）
- 旋转角度太大，名称高度就大了，就显示不全

**运行环境（系统环境及 pyecharts 版本）**
windows 10
python 3.7
pyecharts 1.5.1

**代码及截图**
1. rotate=-45
```
def multibar_qtl() -> Bar:
    # QTL
    character = QTL.objects.distinct("transcript_id").values_list("character_minor")
    data_pair = Counter(map(itemgetter(0), character)).items()
    bar = (
        Bar()
            .add_xaxis(list(map(itemgetter(0), data_pair)))
            .add_yaxis("Transcript Number of QTL character", list(map(itemgetter(1), data_pair)))
            .set_colors("#F88C8C")
            .set_global_opts(
                xaxis_opts=opts.AxisOpts(
                    axislabel_opts=opts.LabelOpts(rotate=-45),
                    ),
                yaxis_opts=opts.AxisOpts(name="transcript number"),
                title_opts=opts.TitleOpts(title="", subtitle=""),
                legend_opts=opts.LegendOpts(is_show=False),
        )
    ).dump_options_with_quotes()
    return bar
```
![image](https://user-images.githubusercontent.com/20498839/69303076-9aad7080-0c56-11ea-9d63-1284d8393574.png)
2. rotate=-15
```
代码同上，只修改rotate为-15
```
![image](https://user-images.githubusercontent.com/20498839/69303126-bb75c600-0c56-11ea-9a07-de6ad90b87fb.png)

**参考过前文**
#484 (x轴名称过长，调整文字方向后显示高度不足), 可能是自己没搞懂，现在Overlap也不知道从哪导入
#560 (横坐标显示问题)

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
GridOpts 可以设置边距的值与图的宽高，其中 pos_left 设置据左边界的距离，pos_right, pos_top, pos_bottom 与之类似；height 设置图的高度（height 参数应该可以满足你的需求），width 与其反之。不完整示例如下：

```python
from pyecharts import options as opts
from pyecharts.charts import Bar, Grid
...
g = Grid()
bar = gen_bar()
g.add(bar, grid_opts=opts.GridOpts(pos_top="20%", pos_bottom="20%", pos_left="20%", pos_right="20%", height="20%", width="80%"))
g.render_notebook()
```

可以试试把你的 bar 放入 Grid 的实例中，并设置图的高度，你会开心的~

**Comment by sunhailin-Leo** [comment]
> GridOpts 可以设置边距的值与图的宽高，其中 pos_left 设置据左边界的距离，pos_right, pos_top, pos_bottom 与之类似；height 设置图的高度（height 参数应该可以满足你的需求），width 与其反之。不完整示例如下：
> 
> ```python
> from pyecharts import options as opts
> from pyecharts.charts import Bar, Grid
> ...
> g = Grid()
> bar = gen_bar()
> g.add(bar, grid_opts=opts.GridOpts(pos_top="20%", pos_bottom="20%", pos_left="20%", pos_right="20%", height="20%", width="80%"))
> g.render_notebook()
> ```
> 
> 可以试试把你的 bar 放入 Grid 的实例中，并设置图的高度，你会开心的~

**Comment by clsteam** [comment]
好的，谢谢，忘记及时回复，抱歉
