### ISSUE TITLE
怎么设定增加options?按照官方文件怎么实现不了

### ISSUE THREAD

**Issue by luzwales** [pyecharts/pyecharts#1421]
![image](https://user-images.githubusercontent.com/56030373/69316770-824c4e80-0c74-11ea-8deb-3e33dcabbc35.png)

**问题**
怎么在options中增加设定，下面 legend_opts，看官方文件  legend_opts有很多其他设定，就是is_show能够实现图例能开关，其他设定怎么弄？我想讲图例靠右 pos_right=20可以吗》
    下面为官方文件
    # 图例组件离容器右侧的距离。
    # right 的值可以是像 20 这样的具体像素值，可以是像 '20%' 这样相对于容器高宽的百分比。
    pos_right: Union[str, Numeric, None] = None,

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
def bar_toolbox() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .add_yaxis("商家B", Faker.values())
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Bar-显示 ToolBox"),
            toolbox_opts=opts.ToolboxOpts(),                #显示tool box(查看数据)
            legend_opts=opts.LegendOpts(is_show=False，pos_right=20),     #是否显示图例
            #opts.LegendOpts(pos_right=20),     
        )
    )
    return c

bar_toolbox().render_notebook()

  **File "<ipython-input-70-8dfd7653b80a>", line 10
    legend_opts=opts.LegendOpts(is_show=False，pos_right=20),     #是否显示图例
                                                      ^
SyntaxError: invalid character in identifier**

![image](https://user-images.githubusercontent.com/56030373/69316770-824c4e80-0c74-11ea-8deb-3e33dcabbc35.png)

**Comment by sunhailin-Leo** [comment]
@luzwales 
* 确定一下你的 ipython 使用 Python 编译器的版本
* `SyntaxError` 是语法错误

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
@luzwales

语法错误：`False` 后面使用了中文逗号，更改为英文即可
