### ISSUE TITLE
前后端分离无法显示主题

### ISSUE THREAD

**Issue by 0x587** [pyecharts/pyecharts#1424]
**问题**
前端ajax获取后端图标时图标的主题未显示。

**运行环境（系统环境及 pyecharts 版本）**

win10 19013 pyecharts 1.5.1

**代码及截图**
前端：

>   
                      <script>
                            $(
                                function () {
                                    var chart = echarts.init(
                                        document.getElementById('bar'), {renderer: 'canvas'});
                                    $.ajax({
                                        type: "GET",
                                        url: "/charts/history_grade_chart/1805",
                                        dataType: 'json',
                                        success: function (result) {
                                            chart.setOption(result);
                                        }
                                    });
                                    $(window).resize(function () {
                                        chart.resize();
                                    });
                                }
                            )
                        </script>
后端：

> @app.route('/charts/history_grade_chart/<int:class_index>')
def history_grade_chart(class_index: int):
    return class_history_grade(
        class_index).dump_options_with_quotes()

后端代码的class_history_grade()返回的是一个Timeline对象，其中是使用VINTAGE主题的图标。
**后端使用render_embed()渲染效果**
![捕获](https://user-images.githubusercontent.com/40025941/69478223-1c55f780-0e2b-11ea-8d72-e05e15aeeb25.PNG)
**前端ajax请求效果**
![捕获1](https://user-images.githubusercontent.com/40025941/69478234-3b548980-0e2b-11ea-9fb8-fba236dfc42c.PNG)

**Comment by sunhailin-Leo** [comment]
@0x587 前后端分离返回的是 json 配置，主题配置是 js 代码改变的，因此不会显示。
