### ISSUE TITLE
from example.commons import Faker 失效

### ISSUE THREAD

**Issue by pblh123** [pyecharts/pyecharts#1425]
**问题**
from example.commons import Faker失效
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-c8d5ed854d28> in <module>
      1 #from example.commons import Faker
----> 2 from example.commons import Faker
      3 from pyecharts import options as opts
      4 from pyecharts.charts import Geo
      5 from pyecharts.globals import ChartType, SymbolType

ModuleNotFoundError: No module named 'example.commons'

**运行环境（系统环境及 pyecharts 版本）**
import pyecharts

print(pyecharts.__version__)

1.6.0
**代码及截图**

from example.commons import Faker失效
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-c8d5ed854d28> in <module>
      1 #from example.commons import Faker
----> 2 from example.commons import Faker
      3 from pyecharts import options as opts
      4 from pyecharts.charts import Geo
      5 from pyecharts.globals import ChartType, SymbolType

ModuleNotFoundError: No module named 'example.commons'

**Comment by ayuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu** [comment]
请阅读 Add: new faker #1324，并尝试使用 `from pyecharts.faker import Faker` 来导入 Faker 类
