### ISSUE TITLE
Bmap的heatmap能否用timeline()实现随时间动态变化？

### ISSUE THREAD

**Issue by exitxingling** [pyecharts/pyecharts#1430]
**问题**
想利用timeline使得Bmap实现的heatmap随时间动态变化，但是显示出来只有基本地图，没有热力图层的信息。

**运行环境（系统环境及 pyecharts 版本）**
python3.6+ pyecharts1.6.0

**代码及截图**

![image](https://user-images.githubusercontent.com/30145356/69617437-2e29db80-1073-11ea-8a4a-b84b23c00b39.png)

**Comment by sunhailin-Leo** [comment]
@exitxingling 
* 1.6.2 版本修复这个问题

**Comment by sunhailin-Leo** [comment]
* 稍后请安装最新版本 pyecharts 1.6.2 版本，进行体验
