### ISSUE TITLE
地图中，是否可以指定实际的辐射半径，来等比例的在地图中画圈

### ISSUE THREAD

**Issue by dwy927** [pyecharts/pyecharts#1434]
**问题**

您好，现在想在地面上画圈。我想输入实际的精度和维度以及圆的地面物理的实际半径。能不能在地图Geo 中画出对应比例尺的散点。

现在已有的接口中，只找到了symbol_size的接口，但我怎么把物理实际的半径，通过对应的比例尺，来设symbol_size的参数。

想请问有没有类似Geo-半径的接口；或者怎么用合适的比例尺，如果物理半径*k = symbol_size，这个 k 应该是多少？

非常感谢

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@dwy927 `JsCode 回调函数可能能帮到你`
