### ISSUE TITLE
the function "Scatter3D()"  is Unable to read data correctly，图像与数据显示不同

### ISSUE THREAD

**Issue by SilenceSengoku** [pyecharts/pyecharts#1435]
**问题**
我已确认3D散点图的add、Axis3DOpts and Grid3DOpts
但我目前得出的结都指向 Scatter3D() 有bug。这包括你们在
_https://pyecharts.org/#/zh-cn/3d_charts?id=scatter3d%ef%bc%9a3d%e6%95%a3%e7%82%b9%e5%9b%be_
的demo和示例代码。
主要问题是 三维图像x，y 按数据顺序而不是按照数值映射。
只有高度（深度）完成正确映射。
我曾反复确认了输入数据，
最后只能认为是 接口（API）除了问题。
我第一次提交issue ，不太会上传截图。
但 /pyecharts.org的 Scatter3D() demo 和示例你们也可以运行看一下。
从顶部往下看不该是对角线。  

期望维护者能给予回复反馈。
谢谢！
我很希望得到一个
pyecharts 渲染的3d html 页面
再次感谢愿意帮助我的人

**运行环境（系统环境及 pyecharts 版本）**
我的环境为
python version 3.6.5
pyecharts version 1.5.1

**代码及截图**

![Uploading isolationforest2.PNG…]()
![Uploading isolationforest3.PNG…]()

**Comment by sunhailin-Leo** [comment]
@SilenceSengoku 
* 你可以看一下 [echarts](https://www.echartsjs.com/examples/zh/index.html) 和 [pyecharts-gallery](https://gallery.pyecharts.org) 的demo
* 关于你这个映射问题，可能还需要进一步的截图和数据展示才能定位，希望你这边能够完整提供一下，thx~

**Comment by SilenceSengoku** [comment]
![Isolationforest](https://user-images.githubusercontent.com/34516910/70034140-abad9880-15eb-11ea-8aa5-b21714bcf9de.PNG)
图为 截图，是可视化 render出的 图像，第一张图可见 高度映射正常，但第二张图，是一个y=x的对角线图像，我认为这是不该出现的情况

**Comment by SilenceSengoku** [comment]
![Uploading isolationforest3.PNG…]()

**Comment by sunhailin-Leo** [comment]
@SilenceSengoku 
* 需要一份代码进行调试

**Comment by SilenceSengoku** [comment]
`from pyecharts import options as opts
from pyecharts.charts import Scatter3D
import pandas as pd

dataset = pd.read_csv(r'C:\Users\Administrator\PycharmProjects\Isolation Forest'
                       r'\optimization\Iso_list.csv', engine='python')

minscore = min(dataset['IsoFst_Score'])
maxscore = max(dataset['IsoFst_Score'])
print(minscore)
print(maxscore)


data = [list(z)
        for z in zip(dataset['x'],dataset['y'],dataset['IsoFst_Score'])]

c = Scatter3D().add("feature", data ,
                    grid3d_opts = opts.Grid3DOpts(width=200, height=200, depth=200),
                    #Axis3DOpts = opts.Axis3DOpts

                    #opts(boxWidth=dataset['x'],boxHeight = dataset['y'],boxDepth = ['IsoFst_Score'])
                    ).set_global_opts(title_opts=opts.TitleOpts("Scatter3D-Isolation Forest"),
                                      visualmap_opts=opts.VisualMapOpts(range_color=[ '#FF0000','#313695'],
                                                              min_=minscore,max_ = maxscore))

c.render("Html\Isolation_Forest_feather.html")`
我是这样写的。

**Comment by SilenceSengoku** [comment]
`c = Scatter3D().add("feature", data ,
                    grid3d_opts = opts.Grid3DOpts(width=200, height=200, depth=200),
                    #Axis3DOpts = opts.Axis3DOpts

                    #opts(boxWidth=dataset['x'],boxHeight = dataset['y'],boxDepth = ['IsoFst_Score'])
                    ).set_global_opts(title_opts=opts.TitleOpts("Scatter3D-Isolation Forest"),
                                      visualmap_opts=opts.VisualMapOpts(range_color=[ '#FF0000','#313695'],
                                                              min_=minscore,max_ = maxscore))
`

**Comment by SilenceSengoku** [comment]
`c = Scatter3D().add("feature", data ,
                    grid3d_opts = opts.Grid3DOpts(width=200, height=200, depth=200),
                    ).set_global_opts(title_opts=opts.TitleOpts("Scatter3D-Isolation Forest"),
                                      visualmap_opts=opts.VisualMapOpts(range_color=[ '#FF0000','#313695'],
                                                              min_=minscore,max_ = maxscore))
`

**Comment by SilenceSengoku** [comment]
`c = Scatter3D().add("feature", data ,`
``

**Comment by SilenceSengoku** [comment]
```
c = Scatter3D().add("feature", data ,
                    grid3d_opts = opts.Grid3DOpts(width=200, height=200, depth=200),
                    #Axis3DOpts = opts.Axis3DOpts

                    #opts(boxWidth=dataset['x'],boxHeight = dataset['y'],boxDepth = ['IsoFst_Score'])
                    ).set_global_opts(title_opts=opts.TitleOpts("Scatter3D-Isolation Forest"),
                                      visualmap_opts=opts.VisualMapOpts(range_color=[ '#FF0000','#313695'],
                                                              min_=minscore,max_ = maxscore))

```

**Comment by SilenceSengoku** [comment]
`
from pyecharts import options as opts
from pyecharts.charts import Scatter3D
import pandas as pd

dataset = pd.read_csv(r'C:\Users\Administrator\PycharmProjects\Isolation Forest'
                       r'\optimization\Iso_list.csv', engine='python')

minscore = min(dataset['IsoFst_Score'])
maxscore = max(dataset['IsoFst_Score'])
print(minscore)
print(maxscore)


data = [list(z)
        for z in zip(dataset['x'],dataset['y'],dataset['IsoFst_Score'])]

c = Scatter3D().add("feature", data ,
                    grid3d_opts = opts.Grid3DOpts(width=200, height=200, depth=200),
                    #Axis3DOpts = opts.Axis3DOpts

                    #opts(boxWidth=dataset['x'],boxHeight = dataset['y'],boxDepth = ['IsoFst_Score'])
                    ).set_global_opts(title_opts=opts.TitleOpts("Scatter3D-Isolation Forest"),
                                      visualmap_opts=opts.VisualMapOpts(range_color=[ '#FF0000','#313695'],
                                                              min_=minscore,max_ = maxscore))

c.render("Html\Isolation_Forest_feather.html")
`

**Comment by SilenceSengoku** [comment]
`from pyecharts import options as opts
from pyecharts.charts import Scatter3D
import pandas as pd

dataset = pd.read_csv(r'C:\Users\Administrator\PycharmProjects\Isolation Forest'
                       r'\optimization\Iso_list.csv', engine='python')

minscore = min(dataset['IsoFst_Score'])
maxscore = max(dataset['IsoFst_Score'])
print(minscore)
print(maxscore)


data = [list(z)
        for z in zip(dataset['x'],dataset['y'],dataset['IsoFst_Score'])]

c = Scatter3D().add("feature", data ,
                    grid3d_opts = opts.Grid3DOpts(width=200, height=200, depth=200),
                    #Axis3DOpts = opts.Axis3DOpts

                    #opts(boxWidth=dataset['x'],boxHeight = dataset['y'],boxDepth = ['IsoFst_Score'])
                    ).set_global_opts(title_opts=opts.TitleOpts("Scatter3D-Isolation Forest"),
                                      visualmap_opts=opts.VisualMapOpts(range_color=[ '#FF0000','#313695'],
                                                              min_=minscore,max_ = maxscore))

c.render("Html\Isolation_Forest_feather.html")`

**Comment by SilenceSengoku** [comment]
`from pyecharts import options as opts
from pyecharts.charts import Scatter3D
import pandas as pd`

`dataset = pd.read_csv(r'C:\Users\Administrator\PycharmProjects\Isolation Forest'
                       r'\optimization\Iso_list.csv', engine='python')`

`minscore = min(dataset['IsoFst_Score'])
maxscore = max(dataset['IsoFst_Score'])
print(minscore)
print(maxscore)`

`data = [list(z)
        for z in zip(dataset['x'],dataset['y'],dataset['IsoFst_Score'])]`

`c = Scatter3D().add("feature", data ,
                    grid3d_opts = opts.Grid3DOpts(width=200, height=200, depth=200),
                    #Axis3DOpts = opts.Axis3DOpts

                    #opts(boxWidth=dataset['x'],boxHeight = dataset['y'],boxDepth = ['IsoFst_Score'])
                    ).set_global_opts(title_opts=opts.TitleOpts("Scatter3D-Isolation Forest"),
                                      visualmap_opts=opts.VisualMapOpts(range_color=[ '#FF0000','#313695'],
                                                              min_=minscore,max_ = maxscore))`

`c.render("Html\Isolation_Forest_feather.html")`

**Comment by SilenceSengoku** [comment]
> 
> 
> @sunhailin-Leo 
> 我已上传，链接如下，包括代码，和渲染页面以及 数据集
>  [链接](https://github.com/SilenceSengoku/testpyecharts )
