### ISSUE TITLE
不显示折线图上的数据标签？

### ISSUE THREAD

**Issue by haliluyaya** [pyecharts/pyecharts#1438]
**问题**
不显示折线图上的数据标签。
由于数据较多，全部显示数据不利于图形观看，希望不显示数据标签，当鼠标指针指到图形才显示数据。

**运行环境（系统环境及 pyecharts 版本）**
windows，python3.7， pyecharts1.6

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@haliluyaya 
* https://pyecharts.org/#/zh-cn/series_options?id=labelopts%ef%bc%9a%e6%a0%87%e7%ad%be%e9%85%8d%e7%bd%ae%e9%a1%b9
