### ISSUE TITLE
请问散点图的X轴不能是数据吗？

### ISSUE THREAD

**Issue by luoyudong593** [pyecharts/pyecharts#1439]
感觉pyecharts的散点图跟echarts以及ploty的散点图不太一样，无法像（x，y）这样绘制散点，看了add_xaxis没有看到类似参数。
c = (
        Scatter()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .set_global_opts(title_opts=opts.TitleOpts(title="Scatter-基本示例"))
    )

**Comment by sunhailin-Leo** [comment]
@luoyudong593 
* http://gallery.pyecharts.org/#/Scatter/basic_scatter_chart

**Comment by luoyudong593** [comment]
谢谢大佬。
