### ISSUE TITLE
热力图数据标签显示问题（除了显示Y轴的值，能否也显示出Y轴的标签名呢）

### ISSUE THREAD

**Issue by luoyudong593** [pyecharts/pyecharts#1440]
不好意思，我看了文档以及历史的issues都没有找到相关功能。
**问题**
鼠标悬停显示数据的时候，能否将所处Y轴的标签也展示出来呢？例如：7a:周四：25
![1f342dd479059dd5e839b1480e1ce7d](https://user-images.githubusercontent.com/54063226/70109671-95551a80-1687-11ea-84e6-e57cd95e6737.png)

**运行环境（系统环境及 pyecharts 版本）**
win10/python3.6/pyecharts1.5.1

**Comment by luoyudong593** [comment]
@chenjiandongx 大佬，有这个功能嘛，如有打扰深感抱歉。

**Comment by luoyudong593** [comment]
我在set_global_opts中添加如下代码
.set_global_opts(
            tooltip_opts=opts.TooltipOpts(formatter='{c}'),
        )
![1575441227(1)](https://user-images.githubusercontent.com/54063226/70118581-50d77800-16a3-11ea-8613-6850f9a7b8c0.jpg)
只显示了该点所在位置，X、Y轴的标签都没有显示出来

**Comment by sunhailin-Leo** [comment]
* 已解决!~
![image](https://user-images.githubusercontent.com/17564655/70124611-26d88280-16b0-11ea-8e1c-41c9cd22de8e.png)

```python
def heatmap_base() -> HeatMap:
    x = Faker.clock
    y = Faker.week
    value = [[x[i], y[j], random.randint(0, 50)] for i in range(24) for j in range(7)]
    c = (
        HeatMap()
        .add_xaxis(x)
        .add_yaxis("series0", y, value)
        .set_global_opts(
            title_opts=opts.TitleOpts(title="HeatMap-基本示例"),
            visualmap_opts=opts.VisualMapOpts(),
            tooltip_opts=opts.TooltipOpts(
                is_show=True,
                formatter=JsCode("function(x) {return x.data[1] + ':' + x.data[0] + ':' + x.data[2];}"),
            )
        )
    )
    return c
```

**Comment by luoyudong593** [comment]
非常感谢~
