### ISSUE TITLE
柱状图的提示框自定义内容如何调用python的函数

### ISSUE THREAD

**Issue by li904775857** [pyecharts/pyecharts#1442]
.add_yaxis("销售推广", 
                   [i['sales_get_the_total'] for i in all_active_info], 
                   stack="stack1", 
                   color="#3fc4e5",
                   itemstyle_opts=opts.ItemStyleOpts(color='#22d67f'),
                   tooltip_opts=opts.TooltipOpts(is_show=True, formatter=JsCode("""function(params) 
                                                            {return '销售推广领取量：'+params['data'];}"""))
                  )

这个自定义提示框内容的formatter如何调用python的函数，还是只可以调用js?
麻烦回答一下，谢谢

**Comment by sunhailin-Leo** [comment]
@li904775857 `javascript` or `string formatter`(like `\n`, `\t` etc)

**Comment by li904775857** [comment]
不可以调用python的函数是吗？

**Comment by sunhailin-Leo** [comment]
> 不可以调用python的函数是吗？

* 渲染前结果是字符串就可以

**Comment by li904775857** [comment]
例如  我写了个函数
def fun(params):
    return '500'
然后调用这个函数
tooltip_opts=opts.TooltipOpts(is_show=True, formatter=fun)
这种的有什么解决方案吧

**Comment by sunhailin-Leo** [comment]
@li904775857 
* Can u try it first ???

```python
tooltip_opts=opts.TooltipOpts(is_show=True, formatter=fun())
```

**Comment by li904775857** [comment]
可以吧 params这个参数的这些参数传过去吗
{
    #    componentType: 'series',
    #    // 系列类型
    #    seriesType: string,
    #    // 系列在传入的 option.series 中的 index
    #    seriesIndex: number,
    #    // 系列名称
    #    seriesName: string,
    #    // 数据名，类目名
    #    name: string,
    #    // 数据在传入的 data 数组中的 index
    #    dataIndex: number,
    #    // 传入的原始数据项
    #    data: Object,
    #    // 传入的数据值
    #    value: number|Array,
    #    // 数据图形的颜色
    #    color: string,
    # }
