### ISSUE TITLE
自定义提示框内容的formatter这个参数调用python函数，如何传递params内的参数？

### ISSUE THREAD

**Issue by li904775857** [pyecharts/pyecharts#1443]
自定义提示框内容的formatter这个参数调用python函数，如何传递params内的参数？

python 3.6+pyecharts1.6

```
def fun(params):
    return params.value+'good'


tooltip_opts=opts.TooltipOpts(is_show=True, formatter=fun())
```

# (params: Object|Array) => string
    # 参数 params 是 formatter 需要的单个数据集。格式如下：
    # {
    #    componentType: 'series',
    #    // 系列类型
    #    seriesType: string,
    #    // 系列在传入的 option.series 中的 index
    #    seriesIndex: number,
    #    // 系列名称
    #    seriesName: string,
    #    // 数据名，类目名
    #    name: string,
    #    // 数据在传入的 data 数组中的 index
    #    dataIndex: number,
    #    // 传入的原始数据项
    #    data: Object,
    #    // 传入的数据值
    #    value: number|Array,
    #    // 数据图形的颜色
    #    color: string,
    # }

想要将这些参数传递到fun函数中，有什么办法吗？

**Comment by sunhailin-Leo** [comment]
@li904775857 
* Can u try it first？What callback function u want？
* the function params explanation is `echarts` default callback result, not function params.
* U just tell us what style or function u want. ok?

**Comment by li904775857** [comment]
想要的结果是根据x轴的值展示不同的内容

**Comment by sunhailin-Leo** [comment]
@li904775857 
* `Python` function is not suit for u, u just code some `javascript` function.
* Like this
```javascript
function (x) {
   if (x.data[0] == 10) {return x + 10;}
   else if (x.data[0] == 20) {return x + 20;}
   ...
}
```

**Comment by li904775857** [comment]
但是 要展示的数据是python的内容，js内没办法调用python的变量

**Comment by li904775857** [comment]
例如：
数据是这样的
all_active_name = ['立减15','立减20']
all_active_info = [{'id': 2, 'active_id': 1, 'active_name': '立减15', 'total_num': 10000, 'get_the_total': '5813'},{'id': 3, 'active_id': 2, 'active_name': '立减20', 'total_num': 20000, 'get_the_total': '3580'}]

bar = (
    Bar()
        .add_xaxis(all_active_name)
        .add_yaxis("get_the_total",
                   [i['get_the_total'] for i in all_active_info], 
                   stack="stack1",
                   itemstyle_opts=opts.ItemStyleOpts(color='#3fc4e5'),
                   tooltip_opts=opts.TooltipOpts(is_show=True)
                  )

        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-堆叠数据（部分）"))
)

bar.render_notebook()


我需要提示框内展示all_active_info内的total_num,应该如何展示，我查了一天资料，并没有相关的，所以才到这里来提问，麻烦了

**Comment by li904775857** [comment]
请问有什么解决办法吗？

**Comment by sunhailin-Leo** [comment]
@li904775857 
* `add_js_funcs()`
