### ISSUE TITLE
渐变柱状图代码无法运行

### ISSUE THREAD

**Issue by Grit-L** [pyecharts/pyecharts#1445]
**问题**

渐变柱状图代码无法运行
def bar_border_radius():
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values(), category_gap="60%")
        .set_series_opts(itemstyle_opts={
            "normal": {
                "color": JsCode("""new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                    offset: 0,
                    color: 'rgba(0, 244, 255, 1)'
                }, {
                    offset: 1,
                    color: 'rgba(0, 77, 167, 1)'
                }], false)"""),
                "barBorderRadius": [30, 30, 30, 30],
                "shadowColor": 'rgb(0, 160, 221)',
            }})
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-渐变圆柱"))
    )
    return c

**运行环境（系统环境及 pyecharts 版本）**
v1.6
python 3.7

**代码及截图**
![image](https://user-images.githubusercontent.com/53365793/70368458-a8652600-18e5-11ea-8f4e-a08fbe660821.png)

**Comment by sunhailin-Leo** [comment]
Reference：https://github.com/pyecharts/pyecharts/issues/1447
