### ISSUE TITLE
渐变圆柱图x轴显示不完整

### ISSUE THREAD

**Issue by JJEFFFFF** [pyecharts/pyecharts#1447]
**问题**
在用自己的数据集画渐变圆柱图时，我的x轴用了15个刻度标签，成图只能显示8个，想知道V1版本类似V0.5的xaxis_interval和xaxis_force_interval怎么用，我感觉应该是这里的问题。

**运行环境（系统环境及 pyecharts 版本）**
Python 3.7.3
pyecharts 1.5.1

**代码及截图**

def bar_border_radius() -> Bar:
    c = (
        Bar()
        .add_xaxis(service_words)
        .add_yaxis("Service", service_words_count, category_gap="60%")
        .set_series_opts(itemstyle_opts={
            "normal": {
                "color": JsCode("""new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                    offset: 0,
                    color: 'rgba(0, 244, 255, 1)'
                }, {
                    offset: 1,
                    color: 'rgba(0, 77, 167, 1)'
                }], false)"""),
                "barBorderRadius": [30, 30, 30, 30],
                "shadowColor": 'rgb(0, 160, 221)',
            }})
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-渐变圆柱"))
        .render_notebook()
    )
    return c

bar_border_radius()
<img width="868" alt="截屏2019-12-08下午7 23 02" src="https://user-images.githubusercontent.com/42923074/70399231-29104900-19f0-11ea-8570-f8d645df8bb8.png">

**Comment by sunhailin-Leo** [comment]
@JJEFFFFF 
对于这种长的标签我个人有以下几点建议：
* 1、可以考虑 x，y 轴交换 + Grid 图，让标签显示完整
* 2、不交换的情况：设置 x 轴标签的倾斜角度，或者将图的宽度变宽

**Comment by Grit-L** [comment]
报这个错误要咋决绝 ： NameError: name 'JsCode' is not defined

**Comment by sunhailin-Leo** [comment]
@Grit-L `from pyecharts.commons.utils import JsCode`
