### ISSUE TITLE
Timeline 中 Bar 图如何显示工具箱？

### ISSUE THREAD

**Issue by VXenomac** [pyecharts/pyecharts#1448]
**问题**

在 Timeline 时间线轮播多图中添加 Bar 柱状图，给 Bar 柱状图设置set_global_opts(toolbox_opts=opts.ToolboxOpts()) 无法显示工具箱。

**运行环境（系统环境及 pyecharts 版本）**

系统环境：macOS Catalina
pyecharts 版本：1.6.0
python 版本：3.7.4

**代码及截图**

```
tl = Timeline()
for i in range(5):
    bar = Bar()
    ....
    bar.set_global_opts(toolbox_opts=opts.ToolboxOpts())
    tl.add(bar, '{}'.format(i))
```

**Comment by sunhailin-Leo** [comment]
@VXenomac 
* 目前这版本没有把 toolbox 的配置在 add 的方法内添加（个人感觉意义不大）
* 你可以阐述下你在 timeline 下使用 toolbox 的场景。

**Comment by VXenomac** [comment]
@sunhailin-Leo 

- 感谢回复。
- 目前使用 Timeline 的场景主要聚焦于不同日期情况下，对 Excel 表格内不同种类的数据做统计，对单日的数据可能有保存图片作对比的需求。虽然可以使用截图的形式实现，但如果有原生的 Toolbox 就更方便一些。
