### ISSUE TITLE
画折线图 双Y轴不显示

### ISSUE THREAD

**Issue by luochaoyang112** [pyecharts/pyecharts#1450]
![360截图-202428000](https://user-images.githubusercontent.com/57590171/70848408-e21cca80-1eab-11ea-9546-5ad9c6e3c1a5.jpg)

不添加yaxis_index=1则显示正常

**Comment by luochaoyang112** [comment]
看了一下 生成出来的 html 发现 在使用yaxis_index这个参数的时候 只添加了serials 跟 legend 并没有修改yAxis数组, 所以导致显示空白的问题

**Comment by sunhailin-Leo** [comment]
@luochaoyang112 
* 看 demo：http://gallery.pyecharts.org/#/Bar/multiple_y_axes
