### ISSUE TITLE
树图Class Tree()和Class TreeItem()

### ISSUE THREAD

**Issue by Eternal-Br** [pyecharts/pyecharts#1452]
**问题**
树图Class TreeItem()类该如何使用（配合Tree()类使用吗）？它和Class Tree()的区别和联系是什么？
望指正.

**Comment by sunhailin-Leo** [comment]
@Eternal-Br 
* 我觉得你应该先看文档

**Comment by Eternal-Br** [comment]
> @Eternal-Br
> 
> * 我觉得你应该先看文档

看了文档，这个里面没有写。

**Comment by sunhailin-Leo** [comment]
![image](https://user-images.githubusercontent.com/17564655/71062872-83ef3080-21a6-11ea-9a8c-b07d321866f8.png)
![image](https://user-images.githubusercontent.com/17564655/71062879-894c7b00-21a6-11ea-8d0c-9a4dc73ca118.png)
![image](https://user-images.githubusercontent.com/17564655/71062895-92d5e300-21a6-11ea-9076-ed7543c36ba0.png)
* 我觉得你应该是不理解什么是 `type hints`

**Comment by Eternal-Br** [comment]
> ![image](https://user-images.githubusercontent.com/17564655/71062872-83ef3080-21a6-11ea-9a8c-b07d321866f8.png)
> ![image](https://user-images.githubusercontent.com/17564655/71062879-894c7b00-21a6-11ea-8d0c-9a4dc73ca118.png)
> ![image](https://user-images.githubusercontent.com/17564655/71062895-92d5e300-21a6-11ea-9076-ed7543c36ba0.png)
> 
> * 我觉得你应该是不理解什么是 `type hints`

谢谢您。
