### ISSUE TITLE
pyecharts  如何实现一个时间线  控制多个不同的图形？

### ISSUE THREAD

**Issue by fanrongqitiancai** [pyecharts/pyecharts#1453]
**问题**
pyecharts  如何实现一个时间线  控制多个不同的图形？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
示例里显示，pyecharts  可以实现一个时间线控制一个图表，我想 实现 一个时间线控制多个图表。这些图表时间是相同的。但是数据内容不同。比如：第一个图显示降雨随时间的变化。第二图显示温度随时间的变化。这两个图都有一个共同的变量 时间。但是，我想在不同的图表里显示。降雨在bar里显示，温度在pie里显示。点击时间线，温度和降雨同时变化。如何实现。谢谢。谢谢。

**Comment by sunhailin-Leo** [comment]
@fanrongqitiancai 
* 大概是这个意思？ http://gallery.pyecharts.org/#/Geo_Map_BMap/china_gdp_from_1980

**Comment by fanrongqitiancai** [comment]
> @fanrongqitiancai
> 
> * 大概是这个意思？ http://gallery.pyecharts.org/#/Geo_Map_BMap/china_gdp_from_1980
谢谢你。

差不多是这个效果，不过，我希望侧边的
![image](https://user-images.githubusercontent.com/9015263/71140364-02ea7480-224c-11ea-8058-bf35c5aab45a.png)
变成时间轴。

**Comment by sunhailin-Leo** [comment]
@fanrongqitiancai 
1、你这截图这个是 visualMap 的拖动条。
2、我给的 demo 的 timeline 也是在侧边的。
