### ISSUE TITLE
请问conda安装命令是什么？

### ISSUE THREAD

**Issue by Max-Yong** [pyecharts/pyecharts#1455]
**问题**
1. conda安装命令？

**运行环境（系统环境及 pyecharts 版本）**
1. python == 2.7.15

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Max-Yong 
* python 2.7 只能使用 pyecharts 0.5.x 的版本
* conda 安装的话可以尝试 `conda install pyecharts`

**Comment by clsteam** [comment]
1>conda自带pip，环境变量加上conda的bin文件夹
2>pip install pyecharts
3>如果上面第二步不行的话，就自行下载低版本pyecharts 0.5.x 的压缩包，解压pip install setup.py进行安装！
@Max-Yong
