### ISSUE TITLE
怎么保存为pdf矢量图啊？pyecharts-snapshot已经不支持了

### ISSUE THREAD

**Issue by clsteam** [pyecharts/pyecharts#1456]
**问题**

怎么保存为pdf矢量图啊？pyecharts-snapshot已经不支持了

**运行环境（系统环境及 pyecharts 版本）**

python3.7（x64），pyecharts 1.6.0，win10

**代码及截图**

**Comment by chfw** [comment]
请看文档先。现在还支持 PDF。

你需要装 snapshot-phamtonjs, 然后自己装 pillow, 就和以前一样了。

多一个选择就是 snapshot-selenium.

**Comment by chfw** [comment]
pyecharts-snapshot 改为只支持命令行了。

**Comment by clsteam** [comment]
@chfw 谢谢，我已经在命令行成功运行了snapshot。
1>`snapshot render.html pdf`
但是生成的pdf图像好像是矢量图，但是标签文字好像并不是。。。放大后模糊了
2>按照您所说的第二种方法。我windows安装了phamtonjs（并不知道怎么用），不知道接下来干啥

--原谅我的无知。。
谢谢！

**Comment by clsteam** [comment]
还有我生成的图片被裁减了咋办？显示不完全？
![image](https://user-images.githubusercontent.com/20498839/71241362-60fb8280-2346-11ea-93cc-6505b16ff951.png)
在网页上显示正常啊！下面是在网页中的显示
![image](https://user-images.githubusercontent.com/20498839/71241433-8d170380-2346-11ea-8336-b482fa781a3b.png)
我应该怎么去调参数呢？

**Comment by chfw** [comment]
调宽

**Comment by clsteam** [comment]
好的，感谢
