### ISSUE TITLE
x轴type设置成value后，data会被自动排序

### ISSUE THREAD

**Issue by benz1113** [pyecharts/pyecharts#1458]
### x轴type设置成value后，data会被自动排序

`x = [500, 300, 800]`
`y = [700, 200, 400]`
`bar = Bar()`
`bar.add_xaxis(x) `
`bar.add_yaxis("", y, category_gap="95%")`
`bar.set_global_opts(`
`    xaxis_opts=opts.AxisOpts(`
`        type_="value"`
`    )`
`)`

输出如下：
[https://s2.ax1x.com/2019/12/20/QXIZm6.png](url)

请问是我使用方法不对吗？还是说有配置选项没设对？

**Comment by sunhailin-Leo** [comment]
@benz1113 
![image](https://user-images.githubusercontent.com/17564655/71305393-3a088380-240e-11ea-8b82-2a9bfde15005.png)
* 理解一下 `value` 连续型数据 的意思
