### ISSUE TITLE
PYecharts能不能做一个级联的菜单目录 当把可视化项目部署到网站的时候 用户可以切换想要查看不同对象的可视化结果？

### ISSUE THREAD

**Issue by suncg1985** [pyecharts/pyecharts#1460]
问题如标题 谢谢！

**Comment by sunhailin-Leo** [comment]
@suncg1985 
* 这个需求 `pyecharts` 现在不会实现，以后也不会实现。
* 这个需求属于用户自定义的操作，而且领域属于前端，`pyecharts` 不会过于干涉到前端的操作
