### ISSUE TITLE
如何在Map中改变城市坐标？

### ISSUE THREAD

**Issue by mrbeann** [pyecharts/pyecharts#1461]
由于坐标重合，所以想改一下城市的坐标，直接使用类似于`pyecharts.datasets.register_coords({'江西': [100,100]})`似乎无法对画图起作用。请问应该怎么修改呢？

**Comment by sunhailin-Leo** [comment]
@mrbeann 
* register_coords 只能修改 Geo 出图点的位置
* 控制地图上地名的位置是在地图包里面的
![image](https://user-images.githubusercontent.com/17564655/75807247-fc39bb00-5dbf-11ea-861e-acebd0e2b640.png)
![image](https://user-images.githubusercontent.com/17564655/75807288-0eb3f480-5dc0-11ea-9f4f-8b373f58c0f8.png)
