### ISSUE TITLE
Geo和Map如何定义maptype为外国的城市或者省份

### ISSUE THREAD

**Issue by Heterotherm** [pyecharts/pyecharts#1462]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chfw** [comment]
理论上和中国城市，省份没有区别。问题是，没有对应的地图包。需求决定供应。

以下是专门提供开源地图的项目组：

https://github.com/echarts-maps

**Comment by chfw** [comment]
@Heterotherm  你需要哪个国家的城市地图？

**Comment by CharlesPikachu** [comment]
可以给的如何制作这样的文件的教程，以及制作好后如何使用的教程么~有需要的人做好某地区的json文件之后也可以提交上来，给有类似需求的人用~

**Comment by chfw** [comment]
https://echarts-maps.github.io/echarts-geomapping-book-zh/
