### ISSUE TITLE
如何在Django 中使用 page 组合图表？

### ISSUE THREAD

**Issue by punnpkin** [pyecharts/pyecharts#1463]
**问题**
如何在Django 中使用 page 组合图表
没找着转 JSON 的方法

**运行环境（系统环境及 pyecharts 版本）**
win10
pyecharts 1.5.1
Django                             2.2.7

**Comment by sunhailin-Leo** [comment]
@punnpkin 
* 如果用了 Web 框架，不建议用 Page
