### ISSUE TITLE
在VScode里面尝试使用Pyecharts进行画图，无法正常渲染图表，一片空白

### ISSUE THREAD

**Issue by ArmyCAC** [pyecharts/pyecharts#1465]
**问题**
使用render_notebook()时一片空白，无法正常渲染。

**运行环境（系统环境及 pyecharts 版本）**
操作系统：win10
开发环境：
  VScode 版本: 1.41.1 (system setup)
  Python：3.7.1 64-bit
  pyecharts：1.6.0
  Jupyter Notebook：5.7.4
  ipython：7.2.0

**代码及截图**
![image](https://user-images.githubusercontent.com/14289215/71612832-e0f2d980-2bdd-11ea-832e-8f8bdca618d2.png)

**Comment by sunhailin-Leo** [comment]
@ArmyCAC VSCode 的 jupyter 环境我们没办法调试，我们只能确保原版的 jupyter notebook 能够进行渲染

**Comment by LeonardoTan** [comment]
遇到同样的问题，希望能够解决，毕竟vs code应该不算是个少数派的编辑器了。

> #1416 
这个解决方案，也试了还是不行，初步估计是echarts的js引入问题，默认的js引用地址太慢。

**Comment by rockcitystore** [comment]
关闭vscode 插件Jupyter Notebook Renderers 可以正常工作了

**Comment by yihaodong1** [comment]
参考https://github.com/pyecharts/pyecharts-assets

**Comment by cherushui** [comment]
@rockcitystore 关闭Jupyter Notebook Renderers插件好使！感谢

**Comment by jim-2018** [comment]
turn off Jupyter Notebook Renderers is really worked !!!!!
