### ISSUE TITLE
请问标题与数据重叠该怎么办

### ISSUE THREAD

**Issue by StevenTang1998** [pyecharts/pyecharts#1466]
**问题**
标题与柱状图的柱子重叠在一起了
**运行环境（系统环境及 pyecharts 版本）**
Ubuntu 16.04 pyecharts 1.6.0
**代码及截图**
```
c = (
        Bar(init_opts=opts.InitOpts(height='750px',width='1500px'))
        .add_xaxis(X)
        .add_yaxis("", count)
        .reversal_axis()
        .set_global_opts(title_opts=opts.TitleOpts(title=("全中国",subtitle="每个柱的数字代表该注册资本范围内企业的数量\na\n,pos_left='center',title_textstyle_opts=opts.TextStyleOpts(font_size=30),subtitle_textstyle_opts=opts.TextStyleOpts(font_size=20)),datazoom_opts=opts.DataZoomOpts(orient="vertical"))
    )
```
![微信截图_20200101152715](https://user-images.githubusercontent.com/37647985/71639133-a6577280-2cab-11ea-87d2-caf0adf80054.png)

**Comment by sunhailin-Leo** [comment]
@StevenTang1998 可以调整一下字号

**Comment by sunhailin-Leo** [comment]
@StevenTang1998 
后续会新增参数：
* `itemGap` 的参数，用于调整标题和副标题的间隔
* `padding` 的参数，用于调整标题内边距

**Comment by StevenTang1998** [comment]
希望可以增加标题组件和坐标轴组件的间距的选项，使得标题可以和坐标轴的距离自定义

**Comment by sunhailin-Leo** [comment]
@StevenTang1998 试试新版的参数

**Comment by LeiyuanMa** [comment]
> 希望可以增加标题组件和坐标轴组件的间距的选项，使得标题可以和坐标轴的距离自定义

新版的什么参数呢？

**Comment by LeiyuanMa** [comment]
> @StevenTang1998 试试新版的参数

请问下是什么参数呢？
