### ISSUE TITLE
新增 Graph 图对 Edge Label 的配置

### ISSUE THREAD

**Issue by sunhailin-Leo** [pyecharts/pyecharts#1468]
* RT
* 效果如下：
![image](https://user-images.githubusercontent.com/17564655/71702982-4d075480-2e0d-11ea-8470-c6f25da764dc.png)

**Comment by opengit** [comment]
awesome job~

**Comment by opengit** [comment]
已经更新了吗

**Comment by sunhailin-Leo** [comment]
@opengit 1.6.1 已经发布了～可以去试试

**Comment by lfc07** [comment]
@sunhailin-Leo 请教一下，对于有向图，该怎样设置edge_symbol? 现在比如edge_symbol='arrow', 边两端都有箭头
