### ISSUE TITLE
v1.6.1 正式发布啦

### ISSUE THREAD

**Issue by sunhailin-Leo** [pyecharts/pyecharts#1471]
* 2020 第一版 🚀 

***Add***
* [pr#1470](https://github.com/pyecharts/pyecharts/pull/1470) 通过 CI 和 Appveyor 的测试，支持 **Python 3.8**
* [pr#1469](https://github.com/pyecharts/pyecharts/pull/1469) 更新 `Graph` 图配置 `Edge` 的 `Option`。
* [pr#1469](https://github.com/pyecharts/pyecharts/pull/1469) 更新 `Line` 图的 `zlevel` 和 `z` 的参数配置
* [pr#1469](https://github.com/pyecharts/pyecharts/pull/1469) 更新 `TitleOpts` 支持一些 `Padding` 和 `Gap` 的配置

***Fixed***
* [pr#1469](https://github.com/pyecharts/pyecharts/pull/1469) 修复 `Timeline` 添加 `GraphicOpts` 无法使用的问题

***Updated***
* [pr#1412](https://github.com/pyecharts/pyecharts/pull/1412) 更新非关键字传参，导致 `delay` 和 `pixel_ratio` 参数作用错位

**Comment by dataAbel** [comment]
更新1.6版本后，层叠多图中柱状图和折线图重叠的部分，柱状图会覆盖折线图。请问如何调成折线图显示在最顶层。

**Comment by sunhailin-Leo** [comment]
@dataAbel 
* Line 图的 zlevel 和 z 参数

**Comment by dataAbel** [comment]
> @dataAbel
> 
> * Line 图的 zlevel 和 z 参数

多谢。

**Comment by sunhailin-Leo** [comment]
@dataAbel 以后有问题直接开 issue
