### ISSUE TITLE
Table与Grid不兼容

### ISSUE THREAD

**Issue by TimCloudland** [pyecharts/pyecharts#1472]
**问题**
Table无options属性，与Grid不兼容；
Table与Page兼容

**运行环境（系统环境及 pyecharts 版本）**
Win10+python3.6+pyecharts1.6

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@TimCloudland 
* Table 就是一个单独的组件和 Grid 的渲染方式不一样
