### ISSUE TITLE
Gague仪表盘radius尺寸设置问题

### ISSUE THREAD

**Issue by lpwm** [pyecharts/pyecharts#1473]
**问题**

**创建Gauge仪表盘时没有找到可以设置`radius`半径大小属性的地方.**

echarts.js里面可以这样设置的:
>series-gauge. radius = '75%'

文档中关于pyecharts.charts.Gauge唯一的`add`方法参数说明中只有对标题文本,数据项标签,提示框,图元样式的配置([文档](https://pyecharts.org/#/zh-cn/basic_charts?id=gauge%ef%bc%9a%e4%bb%aa%e8%a1%a8%e7%9b%98))

想要调整仪表盘半径大小应该怎么操作呢?望指教~感谢!

**运行环境（系统环境及 pyecharts 版本）**

Windows10 1909
Python 3.7.6
pyecharts 1.6.0

**代码及截图**

```py
# df是pandas中的DataFrame对象
zs = (
            Gauge()
                .add(series_name="", data_pair=[("增速", df['增速'])], min_=-100, max_=100)
        )
```

**Comment by sunhailin-Leo** [comment]
@lpwm 
* 这个参数的确是缺失了，下一版进行更新
* 目前的解决方案如下:
![image](https://user-images.githubusercontent.com/17564655/71764166-2a656080-2f1f-11ea-837e-e38fd055b353.png)

**Comment by lpwm** [comment]
好嘞~感谢回复中的解决方案,期待下个版本的更新啦!

**Comment by sunhailin-Leo** [comment]
* 稍后请安装最新版本 pyecharts 1.6.2 版本，进行体验
