### ISSUE TITLE
Candlestick 蜡烛图问题

### ISSUE THREAD

**Issue by cutekevin7** [pyecharts/pyecharts#1475]
**问题**
A。基本上炒股票的童鞋必修课是蜡烛图，而蜡烛图常规都是用 OHLC，分别表示
O - open 开盘价
H - high 最高价 （没有人会翻译成 highest）
L - low 最低价 （同上没有lowest）
C- close 收盘价

问题来了，百度的E charts， 包括pyecharts都是用的 
OCHL，这个很不科学，不符合金融圈的习惯啊。
英文版还翻译成 highest， lowest（无力吐槽）

B。蜡烛图无关颜色，但对于实体和空心的柱体是有定义的，
开盘价 高于 收盘价  = 实心
收盘价 高于 开盘价 = 空心
虽然自己能修改颜色，空心transparecy无力改。。。

**运行环境（系统环境及 pyecharts 版本）**
0.x & 1.x 都一样，貌似百度的echarts就是这样的问题。

**代码及截图**

![](https://user-images.githubusercontent.com/19553554/55603546-bfbfa280-579d-11e9-9bc7-fac4cd49ba59.png)

**解决方案**
1.每次强制修改 echarts.min.js
2. 每次强制改tooltip format
问题来了，每次升级都要修改，太痛苦啦。。。。

求楼主发发慈悲，修订下，或者联系下百度echarts，拨乱反正。

**Comment by sunhailin-Leo** [comment]
@cutekevin7 
* 这个我建议你去 echarts 的仓库去提问 [Echarts](https://github.com/apache/incubator-echarts)

**Comment by sunhailin-Leo** [comment]
@cutekevin7 
* 关于 OCLH 的问题，我觉得这个用 `TooltipOpts` 去 `format` 不会很痛苦吧？
* 关于实心和空心柱体这个问题，我看了一下其他的 K 线图，貌似都是实心的。

**Comment by cutekevin7** [comment]
> @cutekevin7
> 
> * 关于 OCLH 的问题，我觉得这个用 `TooltipOpts` 去 `format` 不会很痛苦吧？
format 还好，对应的还要修改echarts.min.js, 这个查找可不容易。我个人没啥问题，不知道其他小伙伴如何？
> * 关于实心和空心柱体这个问题，我看了一下其他的 K 线图，貌似都是实心的。
这个可以接受。。。。习惯就好

**Comment by cutekevin7** [comment]
> @cutekevin7
> 
> * 这个我建议你去 echarts 的仓库去提问 [Echarts](https://github.com/apache/incubator-echarts)

感谢你几时跟进，但我们不能超越百度吗？

**Comment by sunhailin-Leo** [comment]
@cutekevin7 
* 为啥要修改 echarts.min.js ?
* 我们是基于 echarts 渲染的。你指的超越是哪方面的？

**Comment by cutekevin7** [comment]
> @cutekevin7
> 
> * 为啥要修改 echarts.min.js ?
tooltip format 只是显示时修改了先后顺序，但是涉及到数据处理对应的array错乱了啊，
所以要修订相应feed数据的array顺序，否则渲染后的蜡烛图H和C错位，出来的图完全是错的。

> * 我们是基于 echarts 渲染的。你指的超越是哪方面的？
好吧，继承echarts也不为过。但是百度的英文这只能呵呵了，
中文最高价，但没有直译highest的，在一些特殊图表中会出现W或者M型蜡烛图，
此时会出现higher-high，和higher-low。

**Comment by cutekevin7** [comment]
anyway，感谢团队给我们带来迄今为止，个人认为好用的pyecharts....

**Comment by cutekevin7** [comment]
> > @cutekevin7
> > 
> > * 这个我建议你去 echarts 的仓库去提问 [Echarts](https://github.com/apache/incubator-echarts)
> 
> 感谢你几时跟进，但我们不能超越百度吗？

已经提交给echarts

**Comment by cutekevin7** [comment]
H54HHHH

**Comment by sunhailin-Leo** [comment]
@cutekevin7 
Temporarily close this issue until `echarts` have some change or answer with your issue https://github.com/apache/incubator-echarts/issues/11990 .
