### ISSUE TITLE
Scatter 的symbol不能rotate

### ISSUE THREAD

**Issue by cutekevin7** [pyecharts/pyecharts#1476]
**问题**
Scatter 的symbol不能旋转，老版本有的。。箭头不能转起来了。。。

**运行环境（系统环境及 pyecharts 版本）**
1.x pyecharts

**代码及截图**

**Comment by sunhailin-Leo** [comment]
* missing configuration

**Comment by cutekevin7** [comment]
> * missing configuration

thanks

**Comment by sunhailin-Leo** [comment]
* 稍后请安装最新版本 pyecharts 1.6.2 版本，进行体验

**Comment by cutekevin7** [comment]
Thx
