### ISSUE TITLE
关于使用pyechart渲染图片问题

### ISSUE THREAD

**Issue by 1015zhc** [pyecharts/pyecharts#1478]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by 1015zhc** [comment]
使用的是snapshot_phantomjs方法进行图片渲染图片太大：
1.通过调整像素比pixel_ratio可以调节图片大小。
2.当pixel_ratio调整到1时，生成的图片大小在1.7Mb左右，当pixel_ratio调至更小时，图片变的模糊。
3.以上渲染的是png格式。当渲染jpeg时，发现生成的图片黑底，感官较差，有渲染不同格式图片的参数设置参考吗。

**Comment by sunhailin-Leo** [comment]
* 黑底的话可以试试设置图的 `bg_color`
* 关于其他的话，你可以对比下另外两个 snapshot 的插件

**Comment by 1015zhc** [comment]
在这里设置颜色不起作用：
 make_snapshot(snapshot, grid.render(), "D:/data/test/bar000.png",  pixel_ratio=1)
而且在什么都没更改的情况下，只修改渲染的图片配型，底色发生了变化，这不对啊。

**Comment by sunhailin-Leo** [comment]
@1015zhc 
* 你确定不起作用？我在我这边测试没有任何问题。
* png 默认是透明底，jpeg 是黑色

**Comment by sunhailin-Leo** [comment]
```python
from snapshot_pyppeteer import snapshot

from pyecharts.charts import Bar
from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.render import make_snapshot


def bar_base():
    c = (
        Bar(init_opts=opts.InitOpts(bg_color="#ADD8E6"))
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .add_yaxis("商家B", Faker.values())
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"))
    )
    make_snapshot(snapshot, c.render(), "bar.jpeg")


if __name__ == "__main__":
    bar_base()
```
![image](https://user-images.githubusercontent.com/17564655/71874215-4a359800-315c-11ea-9348-74ac80a95070.png)

**Comment by 1015zhc** [comment]
可以了，非常感谢。
