### ISSUE TITLE
没找到Polar中的特殊标记线功能

### ISSUE THREAD

**Issue by 0gfy0** [pyecharts/pyecharts#1479]
我看到直角坐标系中有MarkLineItem标记线来标记特殊坐标，但Polar中没找到类似功能的类，我有一些特殊角度值的数据想在图表中标记画线，没找到极坐标系中实现根据AngleAxis数据画线的类。请问有人知道吗？谢谢！

**Comment by sunhailin-Leo** [comment]
@0gfy0 
* 你可以去 [这里](https://gallery.echartsjs.com/explore.html#components=polar~sort=rank~timeframe=all~author=all) 看看有没有你想要的 demo，然后再贴个链接回复我

**Comment by sunhailin-Leo** [comment]
@0gfy0 有找到吗？
