### ISSUE TITLE
关系图中双向关系非常不容易切换，请问有解决办法吗

### ISSUE THREAD

**Issue by Max-Yong** [pyecharts/pyecharts#1481]
**描述**
如下图 推荐车型指向立即选车，值为16654，而我同样设置了立即选车到推荐车型，
我将edge_symbol=['circle', 'arrow'],但存在一个问题，就是当我想看反向的关系时，需要鼠标点中circle(在第二张图中我放大了circle)，但很难选中circle，因为当鼠标靠近节点时，节点会变大，这样就会把circle盖住。我尝试过将is_focusnode: bool = False，但这样效果会非常不好。请问有其他解决办法吗，比如把双向的值都在线上显示出来。
![image](https://user-images.githubusercontent.com/34307395/72055533-f9fa3980-3305-11ea-97c6-a85284c4d38f.png)
![image](https://user-images.githubusercontent.com/34307395/72055826-75f48180-3306-11ea-91d0-e0eb182967fd.png)

**问题**
如描述所述。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts==1.6.1

**代码及截图**
```python
c = (
        Graph(init_opts=opts.InitOpts(width='1000px',height='600px'))
        .add(
            "",
            nodes=nodes,
            links = links,
            categories=categories,
            layout='circular',
            is_rotate_label=True,
            edge_symbol=['circle', 'arrow'],
            linestyle_opts=opts.LineStyleOpts(color="source",curve=0.3,width=2),
            label_opts=opts.LabelOpts(position='right'),
            edge_label=opts.LabelOpts(
            is_show=True,
            formatter="{c}",
#             formatter="{b} 的数据 {c}",
            position="middle"
            ),
        )
        .set_global_opts(
            title_opts=opts.TitleOpts(title='Graph_Events'),
            legend_opts=opts.LegendOpts(
                    orient='vertical',pos_left='2%',pos_top="20%"
                ),
        )
    )
```

**Comment by sunhailin-Leo** [comment]
@Max-Yong 
* 这个貌似目前也没啥配置能够修改
https://www.echartsjs.com/zh/option.html#series-graph.type
