### ISSUE TITLE
雷达图如何显示轴线

### ISSUE THREAD

**Issue by sunjiahao4018** [pyecharts/pyecharts#1482]
**问题**
请问如何绘制带有轴线雷达图，类似于https://gallery.echartsjs.com/editor.html?c=xKsGWbPZZd

**运行环境（系统环境及 pyecharts 版本）**
python3.6  pyecharts1.6.0

**代码及截图**

![image](https://user-images.githubusercontent.com/23587414/72062456-cf62ad80-3312-11ea-9675-a1060cc094d1.png)

**Comment by sunhailin-Leo** [comment]
@sunjiahao4018 Waiting for next version!

**Comment by sunhailin-Leo** [comment]
* 稍后请安装最新版本 pyecharts 1.6.2 版本，进行体验

**Comment by sunjiahao4018** [comment]
非常感谢您
