### ISSUE TITLE
双y轴0刻度对齐

### ISSUE THREAD

**Issue by linfanli** [pyecharts/pyecharts#1484]
**问题**

双Y轴来显示时， 左侧Y轴的数据有负数， 而右侧Y轴的数据没有负数 ， 从而导致了两个Y轴的X轴不在一个水平线上，0轴无法对齐的问题，官方文档设置双Y轴的max, min 属性，但没有具体的参数

**运行环境（系统环境及 pyecharts 版本）**
 

> pyecharts 1.5.1

**代码及截图**

> 代码如下， 突然不能插入截图了

`

	v1 = [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, -32.6, -20.0, -6.4, -3.3]
	# v2 = [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
	v3 = [2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]

	def overlap_bar_line() -> Bar:
		bar = (
			Bar()
			.add_xaxis(Faker.months)
			.add_yaxis("降雨量", v1, color="#5793f3",)
			.extend_axis(
				yaxis=opts.AxisOpts(
					name="温度",
	#                 min= v1.min()/(v1.max()-v1.min()),
					axislabel_opts=opts.LabelOpts(formatter="{value} °C"), 
					axisline_opts=opts.AxisLineOpts(
						linestyle_opts=opts.LineStyleOpts(color="#d14a61")
					)
	#                 ,interval=5
				)
			)
			.set_series_opts(label_opts=opts.LabelOpts(is_show=False))
			.set_global_opts(
				title_opts=opts.TitleOpts(title="Overlap-bar+line（双 Y 轴）"),
				yaxis_opts=opts.AxisOpts(
					name="降雨量",
					axisline_opts=opts.AxisLineOpts(
						linestyle_opts=opts.LineStyleOpts(color="#5793f3")
					),
					axislabel_opts=opts.LabelOpts(formatter="{value} ml")
				),
			)
		)

		line = Line()
		line.add_xaxis(Faker.months)
		line.add_yaxis("badrate", v3, yaxis_index=1, color="#d14a61",)
		bar.overlap(line)
		return bar
		
	overlap_bar_line().render_notebook()
`

以人肉设置

> min_= -25/3,

参数(但是批量的图表，人肉不现实)

`

	v1 = [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, -32.6, -20.0, -6.4, -3.3]
	# v2 = [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
	v3 = [2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]

	def overlap_bar_line() -> Bar:
		bar = (
			Bar()
			.add_xaxis(Faker.months)
			.add_yaxis("降雨量", v1, color="#5793f3",)
			.extend_axis(
				yaxis=opts.AxisOpts(
					name="温度",
					min_= -25/3,
					axislabel_opts=opts.LabelOpts(formatter="{value} °C"), 
					axisline_opts=opts.AxisLineOpts(
						linestyle_opts=opts.LineStyleOpts(color="#d14a61")
					)
	#                 ,interval=5
				)
			)
			.set_series_opts(label_opts=opts.LabelOpts(is_show=False))
			.set_global_opts(
				title_opts=opts.TitleOpts(title="Overlap-bar+line（双 Y 轴）"),
				yaxis_opts=opts.AxisOpts(
					name="降雨量",
					axisline_opts=opts.AxisLineOpts(
						linestyle_opts=opts.LineStyleOpts(color="#5793f3")
					),
					axislabel_opts=opts.LabelOpts(formatter="{value} ml")
				),
			)
		)

		line = Line()
		line.add_xaxis(Faker.months)
		line.add_yaxis("badrate", v3, yaxis_index=1, color="#d14a61",)
		bar.overlap(line)
		return bar
		
	overlap_bar_line().render_notebook()
`

**Comment by sunhailin-Leo** [comment]
@linfanli 
* 先把代码和截图贴好。。

**Comment by linfanli** [comment]
Pictrue

**Comment by linfanli** [comment]
> @linfanli
> 
> * 先把代码和截图贴好。。

如下所示：上图是通过人肉设置min_实现Y轴0刻度对齐

下图是不齐的情况，有没有什么参数可以实现Y轴0刻度对齐

**Comment by linfanli** [comment]
@sunhailin-Leo 
代码和截图已经粘好，有空帮忙看下，谢谢

**Comment by sunhailin-Leo** [comment]
@linfanli 
* 一般双轴数据中有正负值都会出现这个问题，不应该刻意去让 0 刻度对齐

**Comment by linfanli** [comment]
> @linfanli
> 
> * 一般双轴数据中有正负值都会出现这个问题，不应该刻意去让 0 刻度对齐
好的，多谢

目前ECHART也存在不齐的情况，期待后续有一键式设置功能

**Comment by linfanli** [comment]
> @linfanli
> 
> * 一般双轴数据中有正负值都会出现这个问题，不应该刻意去让 0 刻度对齐

@sunhailin-Leo 
目前ECHART也存在类似的情况，

期待后续pyecharts有一键式设置功能解决0刻度不齐的问题

**Comment by linfanli** [comment]
@chenjiandongx 

关于双轴图0刻度不齐的问题，有什么好的建议解决吗

**Comment by sunhailin-Leo** [comment]
@linfanli 
* 我们也是跟随着 Echarts 的 js 进行渲染的，所以我们也没办法能摸到 js 源码去解决这个问题。只能寄希望于 Echarts 解决这个问题，或者新增配置。
