### ISSUE TITLE
只看到web整合，pyqt5里怎么用？

### ISSUE THREAD

**Issue by leochan007** [pyecharts/pyecharts#1487]
是否只能生成html 然后webengineview去加载？ 感觉这个效率也太低了 那还不如直接嵌入原生js 然后页面和后台交互？

**Comment by sunjiahao4018** [comment]
可以保存到html里，在使用QWebEngineView加载html

**Comment by leochan007** [comment]
这我不是说了吗 效率太低了吧 请问 还有无更高效的方法、?

**Comment by sunhailin-Leo** [comment]
@leochan007 
* pyinstaller 打包，从后台加载数据，现画

**Comment by leochan007** [comment]
@sunhailin-Leo 大概明白意思了 前后端分离 那等于我后台用python做或者其他任何语言 前端和python其实无关 用electron js都行吧
