### ISSUE TITLE
jupyter notebook导出html无法显示图片

### ISSUE THREAD

**Issue by tina3005** [pyecharts/pyecharts#1488]
**问题**
这个问题我看之前也有朋友提交，但是我还是没有找到解决方案，重新提交一个，希望能得到解决，谢谢各位大神！

**运行环境（系统环境及 pyecharts 版本）**
python 3.7
pyecharts 0.1.6

**代码及截图**
'''
from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.charts import Bar, Tab, Pie, Line,Page
from pyecharts.components import Table

def bar_base() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .add_yaxis("商家B", Faker.values(), is_selected=False)
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"))
    )
    return c

def line_base() -> Line:
    c = (
        Line()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .add_yaxis("商家B", Faker.values())
        .set_global_opts(title_opts=opts.TitleOpts(title="Line-基本示例"))
    )
    return c

def table_base() -> Table:
    table = Table()

    headers = ["City name", "Area", "Population", "Annual Rainfall"]
    rows = [
        ["Brisbane", 5905, 1857594, 1146.4],
        ["Adelaide", 1295, 1158259, 600.5],
        ["Darwin", 112, 120900, 1714.7],
        ["Hobart", 1357, 205556, 619.5],
        ["Sydney", 2058, 4336374, 1214.8],
        ["Melbourne", 1566, 3806092, 646.9],
        ["Perth", 5386, 1554769, 869.4],
    ]
    table.add(headers, rows).set_global_opts(
        title_opts=opts.ComponentTitleOpts(title="Table")
    )
    return table

tab = Tab()
tab.add(bar_base(), "bar-example")
tab.add(line_base(), "line-example")
tab.add(table_base(), "table-example")

tab.render_notebook()
'''
![image](https://user-images.githubusercontent.com/47514855/72166771-d4078e80-3404-11ea-95db-b38d95cde7e5.png)

**Comment by sunhailin-Leo** [comment]
@tina3005 
* 先把代码和截图贴好了～

**Comment by sunhailin-Leo** [comment]
@tina3005 
* 建议不要在 notebook 使用子函数
* 实测没问题 👌 
![image](https://user-images.githubusercontent.com/17564655/72239444-0ccd8080-361c-11ea-8c21-bef0fb52f99e.png)
![image](https://user-images.githubusercontent.com/17564655/72239463-1b1b9c80-361c-11ea-8c84-8d1841d02d46.png)

**Comment by tina3005** [comment]
谢谢解答，找到原因了，因为我是离线环境，一些js打不开所以导致出来的html是空白的。在html里面改成本地的就好了。
![图片](https://user-images.githubusercontent.com/47514855/72311064-77cf9380-36be-11ea-89bc-deb190e375f6.png)

**Comment by XXH-Whale** [comment]
@tina3005 我的是联网环境也是这个问题 要怎么解决呢
![批注 2020-03-03 223207](https://user-images.githubusercontent.com/57614420/75786463-4d39b700-5da0-11ea-9660-fa48b9cdeb95.png)
