### ISSUE TITLE
如何修改页面背景颜色

### ISSUE THREAD

**Issue by kopes18** [pyecharts/pyecharts#1489]
图表的主题修改了，但是页面的背景如何修改？

![image](https://user-images.githubusercontent.com/2020442/72206495-a1739980-34c9-11ea-9a0a-45ad52342361.png)

**Comment by sunhailin-Leo** [comment]
@kopes18 后面白色的背景是浏览器的

**Comment by kopes18** [comment]
。。不是啊 这个就是html网页背景 在网页文件里面可以定义的 @sunhailin-Leo
