### ISSUE TITLE
日历图的月份星期标签怎么改成中文

### ISSUE THREAD

**Issue by YEONyan** [pyecharts/pyecharts#1490]
**问题**
1.0的版本好像都是默认为英文的，我在monthlabel_opts尝试改成中文的dict，但还是显示英文的，请问应该怎么修改，请指教，非常感谢

**运行环境（系统环境及 pyecharts 版本）**
系统环境：win7
pyecharts版本：1.6.1

**代码及截图**
![image](https://user-images.githubusercontent.com/37471666/72228483-f86c9200-35e1-11ea-8f2f-edd7576a04ab.png)

![image](https://user-images.githubusercontent.com/37471666/72228507-19cd7e00-35e2-11ea-9854-1717a127eb51.png)

**Comment by sunhailin-Leo** [comment]
@YEONyan 
* Next Version Preview
![image](https://user-images.githubusercontent.com/17564655/72230969-bea48700-35f3-11ea-8893-d99032608f93.png)

**Comment by YEONyan** [comment]
好的，谢谢

**Comment by sunhailin-Leo** [comment]
@YEONyan 先不用 Close，等发版了我会 Close 掉的
