### ISSUE TITLE
bar.overlap(line)显示错误

### ISSUE THREAD

**Issue by DongdongGui** [pyecharts/pyecharts#1492]
**问题**
bar.overlap(line)显示错误，bar图将line图遮掩住，没办法显示line图

**运行环境（系统环境及 pyecharts 版本）**
版本：V1.6.2
Python3.7
Linux

**代码及截图**
from pyecharts.charts import Line, Bar
def overlap_line_scatter() -> Bar:
    bar = (
        Bar()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    )
    line = (
        Line()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [1, 2, 3, 5, 7, 9])
    )
    bar.overlap(line)
    return bar

overlap_line_scatter().render_notebook()
![image](https://user-images.githubusercontent.com/51312083/72309113-00e3cc00-36b9-11ea-9caa-c75ceb56c46f.png)

**Comment by DongdongGui** [comment]
我实际业务图，就不给出代码了，仅给出截图
![image](https://user-images.githubusercontent.com/51312083/72309195-4dc7a280-36b9-11ea-87c6-92ad97010553.png)

**Comment by sunhailin-Leo** [comment]
@DongdongGui 
![image](https://user-images.githubusercontent.com/17564655/72398051-a57b1200-377c-11ea-9f20-234543116c71.png)
![image](https://user-images.githubusercontent.com/17564655/72398014-87151680-377c-11ea-96a9-a4193ece00da.png)
