### ISSUE TITLE
Bar柱状图无法正常显示

### ISSUE THREAD

**Issue by Simon-max2020** [pyecharts/pyecharts#1493]
**问题**
我运行之后，没有柱状图，只显示了图例和title

**运行环境（系统环境及 pyecharts 版本）**
jupyter和pyecharts 1.6.2

**代码及截图**
attr = ['中国台湾', '中国大陆', '中国香港', '伊朗', '加拿大', '印度', '巴西', '德国', '意大利', '新西兰', '日本', '法国', '波兰', '泰国', '澳大利亚', '瑞士', '美国', '英国', '西德', '西班牙', '阿联酋', '韩国']
value = [2, 8, 14, 1, 2, 1, 1, 6, 7, 3, 11, 10, 1, 1, 2, 3, 52, 14, 1, 3, 1, 8]

from pyecharts.charts.basic_charts.bar import Bar
from pyecharts import options as opts
bar = (
        Bar()
        .add_xaxis(attr)
        .add_yaxis('数量',value)
        .set_global_opts(title_opts=opts.TitleOpts(title="电影国家分析"))
)
bar.render_notebook()

![image](https://user-images.githubusercontent.com/59411099/72312722-f1b64b80-36c3-11ea-9195-af1b61d1713c.png)

**Comment by sunhailin-Leo** [comment]
@Simon-max2020 
![image](https://user-images.githubusercontent.com/17564655/72397480-fab62400-377a-11ea-92c7-3f814777f0c1.png)
![image](https://user-images.githubusercontent.com/17564655/72397492-030e5f00-377b-11ea-9a65-f7e733aa76c8.png)
