### ISSUE TITLE
自定义柱子宽度，马赛克图

### ISSUE THREAD

**Issue by tina3005** [pyecharts/pyecharts#1494]
**问题**
柱状图可以自定义每个柱子的宽度么？
可以实现mosaic plot一样的图么？
如下：
**代码及截图**
![图片](https://user-images.githubusercontent.com/47514855/72323915-ca23ab00-36e4-11ea-96bf-9cc87069b063.png)

**Comment by sunhailin-Leo** [comment]
@tina3005 
* 柱状图每个柱子宽度都是一致的
* 这种图在 Echarts 里面还真没见过

**Comment by tina3005** [comment]
谢谢，可以考虑加这样的功能~ 这个对分类场景还蛮有用
