### ISSUE TITLE
Image 无法render_notebook()显示,但是render()在html中可以显示

### ISSUE THREAD

**Issue by tina3005** [pyecharts/pyecharts#1495]
**问题**
Image 无法render_notebook()显示,但是render()在html中可以显示

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.6.1
python 3.6.5

**代码及截图**
```python
from pyecharts.components import Image
from pyecharts.options import ComponentTitleOpts


def image_base() -> Image:
    image = Image()

    img_src = "a.png"
    image.add(
        src=img_src,
#         style_opts={"width": "200px", "height": "200px", "style": "margin-top: 20px"},
    ).set_global_opts(
        title_opts=ComponentTitleOpts(title="Image-基本示例")
    )
    return image
image_base().render_notebook()
```
![图片](https://user-images.githubusercontent.com/47514855/72338469-7b373f00-36ff-11ea-9f0d-8f57f4b3f561.png)

**Comment by sunhailin-Leo** [comment]
@tina3005 
![image](https://user-images.githubusercontent.com/17564655/72397972-5cc35900-377c-11ea-872e-8afff96f8d6c.png)

**Comment by tina3005** [comment]
谢谢，一模一样的代码，我跑出来还是空的，render才有，很奇怪，不知道哪里出问题了，其他图render_notebook()都没有问题

**Comment by tina3005** [comment]
> 
> 
> @tina3005
> ![image](https://user-images.githubusercontent.com/17564655/72397972-5cc35900-377c-11ea-872e-8afff96f8d6c.png)

找到原因了，原来是我的jupyter 有太多output内容了，导致这个出不来，我把所有的output都clear后就可以显示了！

**Comment by XXH-Whale** [comment]
大佬咋解决的   我的win10  python3.8 pyecharts1.7也是这个问题
![批注 2020-03-03 223207](https://user-images.githubusercontent.com/57614420/75786105-bf5dcc00-5d9f-11ea-83ef-e7e61109138c.png)
