### ISSUE TITLE
可否改变提示框顺序，以及多图不同坐标轴的十字光标同步？

### ISSUE THREAD

**Issue by UtorYeung** [pyecharts/pyecharts#1496]
**问题**
1.多子图环境下，提示框顺序呈现倒序排序，光标所在子图会被排序在最下方。
鼠标指向第1个子图时，提示框排序为[第3子图, 第2子图, 第1子图]
鼠标指向第2个子图时，提示框排序为[第3子图, 第1子图, 第2子图]
鼠标指向第3个子图时，提示框排序为[第1子图, 第2子图, 第3子图]

期望：按顺序排序，光标所在子图会被排序在最上方。即：
鼠标指向第1个子图时，提示框排序为[第1子图, 第2子图, 第3子图]
鼠标指向第2个子图时，提示框排序为[第2子图, 第1子图, 第3子图]
鼠标指向第3个子图时，提示框排序为[第3子图, 第1子图, 第2子图]

2.多子图环境下，当X轴有共同值，但两者长度不同时，十字光标同步时间点不同。
第1、第2子图的X轴时间为2018.01-2019.10
第3子图的X轴时间为2018.08-2019.11
其中2018.08-2019.10的时段在三个子图中为共有X轴时段，但是光标同步显示时，在共有时段显示不同步。
（多子图同步，是按X轴的index同步的，还是按X轴的values同步的？）

**运行环境（系统环境及 pyecharts 版本）**
windows10 + pyecharts1.6.0

**代码及截图**
![搜狗截图20200115143828](https://user-images.githubusercontent.com/44016591/72411783-b5a7e700-37a6-11ea-9ee8-eb4cec556ec0.jpg)

**Comment by sunhailin-Leo** [comment]
@UtorYeung 
* 共用 X 轴才能同步

**Comment by UtorYeung** [comment]
> @UtorYeung
> 
> * 共用 X 轴才能同步

好的谢谢

**Comment by UtorYeung** [comment]
> @UtorYeung
> 
> * 共用 X 轴才能同步

emm，那关于第一个问题，提示框的顺序是否可以改变的？

**Comment by sunhailin-Leo** [comment]
* 估计的倒腾一下 tooltip 的 formatter
