### ISSUE TITLE
有啥办法能解决sunburst图里data pair不能直接传入参数的问题

### ISSUE THREAD

**Issue by maxl0926** [pyecharts/pyecharts#1498]
sunburst图里data pair里的内容不能使用参数，只能直接输入值，有大神能解决一下麽，不然每次做图手输参数好麻烦

**Comment by sunhailin-Leo** [comment]
@maxl0926 
* 可以自己封装 json 数据
![image](https://user-images.githubusercontent.com/17564655/72486276-5cdb5b80-3845-11ea-95a6-6042390df3b3.png)
![image](https://user-images.githubusercontent.com/17564655/72486280-65339680-3845-11ea-8ecc-b5e65efdabe4.png)
