### ISSUE TITLE
kline和volume连动的颜色问题

### ISSUE THREAD

**Issue by leochan007** [pyecharts/pyecharts#1499]
kline本身可以通过设置color color0 再涨跌时候 用不同的颜色，
请问如何根据价格 volume显示不同的颜色？ c >= o 红色，c < o 绿色

**Comment by leochan007** [comment]
add_yaxis时候增加了color=calculate_color(data), 但是不起作用 颜色的list 我看到已经生成了

**Comment by sunhailin-Leo** [comment]
@leochan007 
* 需要自己写 JsCode 进行控制
