### ISSUE TITLE
grid里垂直放3张图就没法连动了 

### ISSUE THREAD

**Issue by leochan007** [pyecharts/pyecharts#1500]
任意2张都可以
选项都一样
xaxis_opts=opts.AxisOpts(
                type_="category",

category实际就是日期 数据来自于同一个dataframe不同的列而已

**Comment by sunhailin-Leo** [comment]
* Demo： http://gallery.pyecharts.org/#/Candlestick/professional_kline_chart
* 把 Line 474 - 478 的注释解开，然后运行试试
