### ISSUE TITLE
tab和page同一页面混合

### ISSUE THREAD

**Issue by ruisunyc** [pyecharts/pyecharts#1501]
**问题**
在使用组合图标中，如何在多个选项卡图中添加顺序图，选项卡add方法只支持charts，不支持page，

**运行环境（系统环境及 pyecharts 版本）**

linux 1.6

**代码及截图**
如支持下面的格式
tab = Tab()
page.add(Bar(), Bar())
tab.add(page, 'x')

**Comment by forestlight1999** [comment]
er, 我今天也遇到了这个问题，在某个tab中尝试嵌套复杂的layout图形，add page不起作用

**Comment by sunhailin-Leo** [comment]
Same as https://github.com/pyecharts/pyecharts/issues/1441
