### ISSUE TITLE
引用register_url("https://echarts-maps.github.io/echarts-china-counties-js/")后不能在Jupyter notebook中显示地图

### ISSUE THREAD

**Issue by LCBProgHome** [pyecharts/pyecharts#1505]
**问题**
引用register_url("https://echarts-maps.github.io/echarts-china-counties-js/")后不能在Jupyter notebook中显示地图，但在本地网页显示正常。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.6.2

**代码及截图**
from pyecharts import options as opts
from pyecharts.charts import Map
from pyecharts.datasets import register_url
register_url("https://echarts-maps.github.io/echarts-china-counties-js/")
data_pair=[['临海市',45],['温岭市',32],['三门县',12],['玉环县',25],['椒江区',34]]
map = (
        Map()
        .add('',data_pair,'台州')
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(
            title_opts=opts.TitleOpts(title="台州市地图示例"),
            visualmap_opts=opts.VisualMapOpts(max_=50,is_piecewise=True))
    )
#map.render() 正常
map.render_notebook()#不会显示

**Comment by sunhailin-Leo** [comment]
@LCBProgHome 
* 实测没问题
![image](https://user-images.githubusercontent.com/17564655/73593776-b4b2db80-4542-11ea-92cc-ecbe4a85b74a.png)
