### ISSUE TITLE
山东省行政区划分

### ISSUE THREAD

**Issue by Shoutai** [pyecharts/pyecharts#1506]
**问题**
2019年，山东省的莱芜市被济南市合并后，不存在莱芜市了。但在1.6.2版本中没有更新。请问哪个版本有更新后的山东省地图？

**运行环境（系统环境及 pyecharts 版本）**
macOS pyecharts 1.6.2

**代码及截图**
<img width="465" alt="Screen Shot 2020-01-31 at 13 52 45" src="https://user-images.githubusercontent.com/22286522/73515643-05d2aa80-4431-11ea-857e-39f7e667239f.png">

**Comment by sunhailin-Leo** [comment]
@Shoutai 这个需要去看 Echarts 的地图库有没有更新山东省的地图 json 数据

**Comment by Shoutai** [comment]
Echarts 不再提供国内地图数据的更新了 关于山东省的地图 有什么建议吗？

**Comment by Shoutai** [comment]
已经找到最新的js和json文件，请问mac上的原始文件在哪里，一直没找到

**Comment by sunhailin-Leo** [comment]
@Shoutai 
* 可以提供一下新的 js 和 json 文件么？（或者代码把两个文件提交到 https://github.com/pyecharts/pyecharts-assets 的仓库中）
* 本地没有原始文件，js 和 json 通过 cdn 上加载的

**Comment by Shoutai** [comment]
已通过163邮箱发给你的qq邮箱了

**Comment by Shoutai** [comment]
> @Shoutai
> 
> * 可以提供一下新的 js 和 json 文件么？（或者代码把两个文件提交到 https://github.com/pyecharts/pyecharts-assets 的仓库中）
> * 本地没有原始文件，js 和 json 通过 cdn 上加载的

已通过163邮箱发给你的qq邮箱了

**Comment by Shoutai** [comment]
@sunhailin-Leo
已通过163邮箱发给你的qq邮箱了
