### ISSUE TITLE
数据重新加载，原数据依然存在图表上

### ISSUE THREAD

**Issue by Godkillme** [pyecharts/pyecharts#1507]
**问题**

数据重新加载，原数据依然存在图表上。如下图，返回的JSON数据只有一个“5”，但是生成的图表残留了上一次加载的数据“2.4”。请问该如何解决？

**运行环境（系统环境及 pyecharts 版本）**

环境：flask
pyecharts：1.6.2

**代码及截图**
<img width="666" alt="截屏2020-02-0120 07 10" src="https://user-images.githubusercontent.com/33575502/73591976-0c941700-4530-11ea-960e-c574f6b82969.png">

**Comment by Godkillme** [comment]
setOption加true已解决

**Comment by lianyouli** [comment]
@Godkillme 请问pyecharts 如何设置setOption 加true呢，谢谢

**Comment by Godkillme** [comment]
> @Godkillme 请问pyecharts 如何设置setOption 加true呢，谢谢

类似于：
``` js
    <script>
        function dist_scatter() {
            var chart = echarts.init(document.getElementById('chart-scatter'), 'white', {renderer: 'canvas'});
            $.ajax({
                type: 'GET',
                url: '/api/dist/scatter',
                dataType: 'json',
                success: function (result) {
                    chart.setOption(result, true);  //加上true表示不合并配置，防止前次数据残留
                }
            });
        }
    </script>
```
