### ISSUE TITLE
请问BMap发生错位如何解决？

### ISSUE THREAD

**Issue by yeureka** [pyecharts/pyecharts#1508]
**问题**
BMap渲染后位置错位，在原位置下方，拖动几下能回到正确位置，请问如何解决这个问题？

**运行环境（系统环境及 pyecharts 版本）**
系统环境：macos catalina
pyecharts 版本：1.6.2
**代码及截图**
代码：
1. BMap 基本示例
2. 
```
page = Page(layout=Page.DraggablePageLayout)
page.add(bmap_base())
page.render()
```
3. 截图
错误情况
<img width="553" alt="error" src="https://user-images.githubusercontent.com/31445879/73719042-206e9180-4759-11ea-9e92-e87667810f5b.png">

拖拽几次后正常
<img width="592" alt="right" src="https://user-images.githubusercontent.com/31445879/73719044-23698200-4759-11ea-9f87-d8146b78fbb5.png">

**Comment by sunhailin-Leo** [comment]
@yeureka 
* 你这样子说没法判断出问题在哪。
* 推测：
    * html 的问题

**Comment by yeureka** [comment]
@sunhailin-Leo 

是官方的 BMap 基本示例，全部代码如下。
macos下chrome、safari均显示错位，windows下chrome、IE、edge均显示错位。
现在不知道怎么排查这个错误。
```
from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.charts import BMap, Page
BAIDU_AK = "my_appid"

def bmap_base() -> BMap:
    c = (
        BMap()
        .add_schema(
            baidu_ak=BAIDU_AK,
            center=[120.13066322374, 30.240018034923],
        )
        .add(
            "bmap",
            [list(z) for z in zip(Faker.provinces, Faker.values())],
            label_opts=opts.LabelOpts(formatter="{b}"),
        )
        .set_global_opts(title_opts=opts.TitleOpts(title="BMap-基本示例"))
    )
    c.chart_id = "chart_id"
    return c

page = Page(layout=Page.DraggablePageLayout)
page.add(bmap_base())
page.render()
```

**Comment by sunhailin-Leo** [comment]
@yeureka 
* 这个问题应该和 layout 的 draggable 实现的 js 有关系
