### ISSUE TITLE
增加toolbox_opts后，行为不一样

### ISSUE THREAD

**Issue by nmweizi** [pyecharts/pyecharts#1509]
![image](https://user-images.githubusercontent.com/1232444/73723689-a0e6bf80-4764-11ea-8c5c-91fb9e4529f9.png)

![image](https://user-images.githubusercontent.com/1232444/73720189-57927200-475c-11ea-94a6-365874e7ac1e.png)

- 不用toolbox_opts
取消疫情确诊显示（按钮），y轴自动变化
![image](https://user-images.githubusercontent.com/1232444/73720272-80b30280-475c-11ea-9fc1-d5b83f2640a5.png)

-用toolbox_opts
取消疫情确诊显示，y轴**不发生**变化

![image](https://user-images.githubusercontent.com/1232444/73720343-af30dd80-475c-11ea-909d-f0d2537aa689.png)

**Comment by nmweizi** [comment]
x = ['20200124',
 '20200125',
 '20200126',
 '20200127',
 '20200128',
 '20200129',
 '20200130',
 '20200131',
 '20200201',
 '20200202',
 '20200203',
 '20200204']
city_confirmedCount=[549, 761, 1058, 1423, 2714, 3554, 4586, 5806, 7153, 9074, 11177, 13522]
city_suspectedCount=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
city_curedCount=[31, 32, 42, 47, 50, 57, 60, 119, 133, 232, 300, 300]
city_deadCount=[24, 40, 52, 76, 100, 125, 162, 204, 249, 294, 350, 414]
def line_base() -> Line:
    c = (
        Line(init_opts=opts.InitOpts(theme=ThemeType.DARK,width = "900px",),)
        .add_xaxis(x)
        .add_yaxis("疫情确诊", city_confirmedCount,is_smooth=True)
        .add_yaxis("疫情疑似", city_suspectedCount,is_smooth=True)
        .add_yaxis("治愈", city_curedCount,is_smooth=True)
        .add_yaxis("死亡", city_deadCount,is_smooth=True)
        .set_global_opts(title_opts=opts.TitleOpts(title="疫情"),
                        toolbox_opts=opts.ToolboxOpts(is_show = True),   # 这行取消就行为不一样
        )
    )
    return c
line = line_base()
line.render_notebook()

**Comment by sunhailin-Leo** [comment]
@nmweizi 
```python
.set_global_opts(
            title_opts=opts.TitleOpts(title="疫情"),
            toolbox_opts=opts.ToolboxOpts(
                is_show=True,
                feature=opts.ToolBoxFeatureOpts(data_zoom={"yAxisIndex": "none"})
            ),
        )
```
* 原因请见: https://www.echartsjs.com/zh/option.html#toolbox.feature.dataZoom.yAxisIndex

**Comment by nmweizi** [comment]
感谢！
