### ISSUE TITLE
如何可以做到关系图的关系按顺序排列呢？

### ISSUE THREAD

**Issue by CholoeMoretz** [pyecharts/pyecharts#1510]
**问题**

关系图产生的是随机顺序的图像，但是我想要关系图按照前后的顺序进行连接，像链表一样比如一个时间节点连接另一个时间接点，同时做到不乱序，请问有什么办法可以做到呢？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@CholoeMoretz 具体说明一下

**Comment by CholoeMoretz** [comment]
> @CholoeMoretz 具体说明一下

你好，我的意思是指，类似于演进图一样，把关系图按照一定顺序进行排列，而非是原本里实现的在画布上标签的位置是随机的，我想要我的关系图呈现一定顺序，比如从左到右进行连接。同时两个节点之间的边长可以进行调节。

**Comment by sunhailin-Leo** [comment]
@CholoeMoretz 
* 你可以试着让数据按着你的顺序放到 Graph 图中。
