### ISSUE TITLE
柱状图如何做到在y轴为字符串

### ISSUE THREAD

**Issue by yukinoxita** [pyecharts/pyecharts#1513]
![image](https://user-images.githubusercontent.com/42521245/74079187-fa096880-4a6e-11ea-878a-beb5c8359abb.png)
文档中的
![image](https://user-images.githubusercontent.com/42521245/74079212-3046e800-4a6f-11ea-92e5-7899e83d173a.png)
本人运行后。
pyecharts版本：0.5.11

**Comment by sunhailin-Leo** [comment]
@yukinoxita 
* 具体描述下你的问题

**Comment by yukinoxita** [comment]
y轴做不到出现像：袜子，衬衫这样的字符串，只会出现1，2，3

**Comment by sunhailin-Leo** [comment]
@yukinoxita 
* 用新版本的吧，旧版本的因为 echarts 曾经改过 js 所以会出现那种情况。
![image](https://user-images.githubusercontent.com/17564655/75008919-46639800-54b4-11ea-869f-5e54e505557d.png)
