### ISSUE TITLE
BMAP API

### ISSUE THREAD

**Issue by aka-achea** [pyecharts/pyecharts#1514]
**问题**
BMap.py, engine.py 使用http的百度地图API，导致地图加载时被chromeblock
改成https后问题解决

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 2.6.1
chrome 73

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@aka-achea 
* 有在其他电脑上试过么？
* 我这边 Mac 的 Chrome 没有被 block
