### ISSUE TITLE
地图问题

### ISSUE THREAD

**Issue by sleepyyoung** [pyecharts/pyecharts#1515]
**问题**

如何在世界地图中显示中国的省份？网上也没有找到什么有效的方法...

**运行环境（系统环境及 pyecharts 版本）**
win10
pyecharts : 1.6.2

**Comment by sunhailin-Leo** [comment]
@sleepyyoung 这个暂时没啥好办法

**Comment by sunhailin-Leo** [comment]
@sleepyyoung 
* 这样子？
![image](https://user-images.githubusercontent.com/17564655/75454033-c192e580-59af-11ea-9bc1-741561b7546a.png)

**Comment by sleepyyoung** [comment]
> @sleepyyoung
> 
> * 这样子？
>   ![image](https://user-images.githubusercontent.com/17564655/75454033-c192e580-59af-11ea-9bc1-741561b7546a.png)

嗯嗯是！请问你是怎么实现的？

**Comment by sleepyyoung** [comment]
嗯嗯是！请问大佬是怎么实现的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LeoSun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月27日(星期四) 晚上10:26
收件人:&nbsp;"pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;;
抄送:&nbsp;"LEE"<1696589321@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] 地图问题 (#1515)




@sleepyyoung
  
这样子？

**Comment by sunhailin-Leo** [comment]
@sleepyyoung 
* 替换了个 js 文件

**Comment by sleepyyoung** [comment]
我之前也在网上找过一个js文件但是不会用...大佬可以把你用的文件分享给我嘛顺便教教我...（我QQ:1696589321)要不我加你也行...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LeoSun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 中午1:24
收件人:&nbsp;"pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;;
抄送:&nbsp;"LEE"<1696589321@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] 地图问题 (#1515)




@sleepyyoung
  
替换了个 js 文件

**Comment by Gavingx** [comment]
画地图map的时候，出来的html文件打开为什么所有的省份颜色都没有了？

**Comment by sunhailin-Leo** [comment]
* Waiting for the new version.

**Comment by sleepyyoung** [comment]
beautiful!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LeoSun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上10:49
收件人:&nbsp;"pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;;
抄送:&nbsp;"LEE"<1696589321@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] 地图问题 (#1515)





 
Closed #1515.
