### ISSUE TITLE
Sankey 桑基图显示不全的问题

### ISSUE THREAD

**Issue by lyt719** [pyecharts/pyecharts#1520]
**问题**
Sankey 桑基图显示不全,可能是数据太大下面感觉有一半没展示出来
如果设置init_opts的width，height就会导致显示不出来，请问有什么办法吗

**运行环境（系统环境及 pyecharts 版本）**
最新pyecharts

**代码及截图**
sankey = (
            Sankey()
                .add("",nodes,links,
                linestyle_opt=opts.LineStyleOpts(opacity=0.2, curve=0.5, color="source"),
                label_opts=opts.LabelOpts(position="right"),
            )
        )
![image](https://user-images.githubusercontent.com/58416622/74213215-3806c680-4cd3-11ea-8e47-11c1f58d5c2c.png)

**Comment by sunhailin-Leo** [comment]
@lyt719 
* 你的 `init_opts` 怎么设置的？

**Comment by lyt719** [comment]
> @lyt719
> 
> * 你的 `init_opts` 怎么设置的？

都是默认的，没有设置

**Comment by sunhailin-Leo** [comment]
@lyt719 
* 我是看你说设置 `init_opts` 宽和高图就显示不了？

**Comment by sunhailin-Leo** [comment]
@lyt719 
* 可以试试调整 `node_gap`
