### ISSUE TITLE
层叠多图重叠问题

### ISSUE THREAD

**Issue by timm-zz** [pyecharts/pyecharts#1521]
**问题**
您好，我有两个问题
1.层叠多图时，打开生成的网页只显示柱状图，折线图要在工具箱中data view中刷新后才显示
2.折线图显示后，柱状图挡住了折线图（应该时折线图在柱状图前面

**运行环境（系统环境及 pyecharts 版本）**
python3.8 win10 pyecharts1.6.2

**代码及截图**
![1](https://user-images.githubusercontent.com/59356874/74653802-e8893480-51c3-11ea-8fe4-b73f0c6231e1.png)
![02](https://user-images.githubusercontent.com/59356874/74653808-ecb55200-51c3-11ea-9470-16bf300cf71b.png)

**Comment by lpwm** [comment]
我今天也发现了这个问题,但是印象里面之前好像是正常显示的,折线图在柱状图的上一层

```py
# 本期柱状图
bq_bar = (
	Bar(init_opts=options)
		.add_xaxis(df.index.values.tolist())
		.add_yaxis('本期', df['本期'].values.tolist())
		.extend_axis(  # 扩展额外的Y轴用来显示百分比
		yaxis=opts.AxisOpts(
			axislabel_opts=opts.LabelOpts(formatter="{value} %")
		)
	)
)
# 本期增速折线图
bq_line = (
	Line()
		.add_xaxis(df.index.values.tolist())
		.add_yaxis('增速', df['增速'].values.tolist(), yaxis_index=1,
				   markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(y=0, symbol_size=0)]))
	# 添加y=0的markline辅助线
)

bq_bar.overlap(bq_line)  # 叠加增速折线图
bq_bar.set_global_opts(tooltip_opts=tool_opt)  # 添加鼠标悬浮提示框
```

**Comment by timm-zz** [comment]
> 我今天也发现了这个问题,但是印象里面之前好像是正常显示的,折线图在柱状图的上一层
> 
> ```python
> # 本期柱状图
> bq_bar = (
> 	Bar(init_opts=options)
> 		.add_xaxis(df.index.values.tolist())
> 		.add_yaxis('本期', df['本期'].values.tolist())
> 		.extend_axis(  # 扩展额外的Y轴用来显示百分比
> 		yaxis=opts.AxisOpts(
> 			axislabel_opts=opts.LabelOpts(formatter="{value} %")
> 		)
> 	)
> )
> # 本期增速折线图
> bq_line = (
> 	Line()
> 		.add_xaxis(df.index.values.tolist())
> 		.add_yaxis('增速', df['增速'].values.tolist(), yaxis_index=1,
> 				   markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(y=0, symbol_size=0)]))
> 	# 添加y=0的markline辅助线
> )
> 
> bq_bar.overlap(bq_line)  # 叠加增速折线图
> bq_bar.set_global_opts(tooltip_opts=tool_opt)  # 添加鼠标悬浮提示框
> ```

我用了pyecharts的中文文档里的demo，显示的图像也是错误的，折线图在下层

**Comment by lpwm** [comment]
试出来个折中的方法,将bar的颜色改成透明的

```py
# 柱状图(颜色)样式
item_style = opts.ItemStyleOpts(
	color="#009688",
	opacity=.8
)
# 本期柱状图
bq_bar = (
	Bar(init_opts=options)
		.add_xaxis(df.index.values.tolist())
		.add_yaxis('本期', df['本期'].values.tolist(), itemstyle_opts=item_style)
		.extend_axis(  # 扩展额外的Y轴用来显示百分比
		yaxis=opts.AxisOpts(
			axislabel_opts=opts.LabelOpts(formatter="{value} %")
		)
	)
)
```

**Comment by lpwm** [comment]
又试了下用原生的`echarts.js`写了遍,显示是正常的,咬咬牙准备把前后端彻底分离了,python写接口给前端传json吧

**Comment by sunhailin-Leo** [comment]
@lpwm @timm-zz 
* 有参数可以设置 `line` 的 `z轴` 层数
![image](https://user-images.githubusercontent.com/17564655/75007711-eb7c7180-54b0-11ea-8837-16f92b520c82.png)

**Comment by timm-zz** [comment]
> 试出来个折中的方法,将bar的颜色改成透明的
> 
> ```python
> # 柱状图(颜色)样式
> item_style = opts.ItemStyleOpts(
> 	color="#009688",
> 	opacity=.8
> )
> # 本期柱状图
> bq_bar = (
> 	Bar(init_opts=options)
> 		.add_xaxis(df.index.values.tolist())
> 		.add_yaxis('本期', df['本期'].values.tolist(), itemstyle_opts=item_style)
> 		.extend_axis(  # 扩展额外的Y轴用来显示百分比
> 		yaxis=opts.AxisOpts(
> 			axislabel_opts=opts.LabelOpts(formatter="{value} %")
> 		)
> 	)
> )
> ```

感谢👌

**Comment by timm-zz** [comment]
> @lpwm @timm-zz
> 
> * 有参数可以设置 `line` 的 `z轴` 层数
>   ![image](https://user-images.githubusercontent.com/17564655/75007711-eb7c7180-54b0-11ea-8837-16f92b520c82.png)

嗯嗯，我去试试，谢谢了😃

**Comment by lpwm** [comment]
@sunhailin-Leo 谢谢~ 已经开始入坑Vue了,有点香...
