### ISSUE TITLE
Grid两个Pie平行显示出错

### ISSUE THREAD

**Issue by kencin** [pyecharts/pyecharts#1522]
**问题**
运用grid的平行视图，两个Pie无法平行显示

**运行环境（系统环境及 pyecharts 版本）**
Python3.6
pyecharts 1.6.2

**代码及截图**
`from pyecharts.charts import Grid, Scatter, Line, Pie
from pyecharts.faker import Faker
from pyecharts import options as opts

def grid_horizontal() -> Grid:
    c = (
        Pie()
            .add("", [list(z) for z in zip(Faker.choose(), Faker.values())])
            .set_global_opts(title_opts=opts.TitleOpts(title="Pie-基本示例"))
            .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
    )
    c2 = (
        Pie()
            .add("", [list(z) for z in zip(Faker.choose(), Faker.values())])
            .set_global_opts(title_opts=opts.TitleOpts(title="Pie-基本示例"))
            .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
    )

    grid = (
        Grid()
        .add(c, grid_opts=opts.GridOpts(pos_left="55%"))
        .add(c2, grid_opts=opts.GridOpts(pos_right="55%"))
    )
    return grid

grid_horizontal().render("test.html")`

![2020-02-17 21-05-12屏幕截图](https://user-images.githubusercontent.com/17043404/74656516-37859880-51c9-11ea-9a91-f98583408579.png)

**Comment by sunhailin-Leo** [comment]
@kencin 
* 设置饼图的 `center` 参数
![image](https://user-images.githubusercontent.com/17564655/75007812-34342a80-54b1-11ea-988e-55e1bc206c12.png)

**Comment by anxingle** [comment]
所以  为什么饼图平行及垂直显示总是出错啊？  能不能给个示例啊！
