### ISSUE TITLE
世界地图问题

### ISSUE THREAD

**Issue by JuntingYu1996** [pyecharts/pyecharts#1526]
**问题**

请问有没有方法让生成的世界地图在左右平移时具有周期连续性？

**运行环境（系统环境及 pyecharts 版本）**
mac os 10.15 & Linux Ubuntu 18.04

pycharts 1.6.2

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@JuntingYu1996 这个暂时没见到 Echarts 有这方面的参数设置，无法实现
