### ISSUE TITLE
所有3D图无法在notebook显示，其他图正常

### ISSUE THREAD

**Issue by zzzqc123** [pyecharts/pyecharts#1529]
**问题**
除了3D图显示空白，其他图正常

**运行环境（系统环境及 pyecharts 版本）**
win10 64;
1.6.2

**代码及截图**
import random
from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.charts import Bar3D

def bar3d_base() -> Bar3D:
    data = [(i, j, random.randint(0, 12)) for i in range(6) for j in range(24)]
    c = (
        Bar3D()
        .add(
            "",
            [[d[1], d[0], d[2]] for d in data],
            xaxis3d_opts=opts.Axis3DOpts(Faker.clock, type_="category"),
            yaxis3d_opts=opts.Axis3DOpts(Faker.week_en, type_="category"),
            zaxis3d_opts=opts.Axis3DOpts(type_="value"),
        )
        .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(max_=20),
            title_opts=opts.TitleOpts(title="Bar3D-基本示例"),
        )
    )
    return c.render_notebook()
bar3d_base()
# 代码为文档里的demo代码

**Comment by zzzqc123** [comment]
求大神指点，我前些天画3D图一切都正常，我也没改过代码，今天在运行时一片空白。在jupyternotebook里运行的

**Comment by sunhailin-Leo** [comment]
@zzzqc123 现在应该可以了，你刷新下浏览器缓存。

**Comment by zzzqc123** [comment]
> @zzzqc123 现在应该可以了，你刷新下浏览器缓存。

刚刚确实可以了，貌似现在又不可以了？

**Comment by zzzqc123** [comment]
> @zzzqc123 现在应该可以了，你刷新下浏览器缓存。

可以了  没问题了  谢谢大佬
