### ISSUE TITLE
Map地图的标签显示问题

### ISSUE THREAD

**Issue by Owen1998** [pyecharts/pyecharts#1532]
**问题**
如何在Map中，只显示指定城市的标签，而其他地区的不显示？
想要的效果如下：
![Snipaste_2020-02-28_16-10-14](https://user-images.githubusercontent.com/43293989/75522383-d40b2e80-5a44-11ea-9369-d377f5b8e3a9.png)

**运行环境（系统环境及 pyecharts 版本）**

win10系统 pyecharts1.6.2

**代码及截图**

japan_geo =[['Nagano',12]]
map = Map()
map.set_global_opts(
        title_opts=opts.TitleOpts(title="日本地图"),
        visualmap_opts=opts.VisualMapOpts(max_=30, is_piecewise=False)
        )
map.add(
         "日本地图",japan_geo , maptype='日本',
        label_opts=opts.LabelOpts(is_show=True, formatter="{b}")
    )
map.render("日本.html")

目前生成的效果：
![Snipaste_2020-02-28_16-10-48](https://user-images.githubusercontent.com/43293989/75522456-fef58280-5a44-11ea-9ad4-d74a2ea59eef.png)

想要实现的效果：
![Snipaste_2020-02-28_16-10-14](https://user-images.githubusercontent.com/43293989/75522473-087eea80-5a45-11ea-8ea8-0a443eef4409.png)

**Comment by Owen1998** [comment]
已经解决。

**Comment by Reveyer** [comment]
您好，请问您是怎么解决这个问题的？
