### ISSUE TITLE
四川省攀枝花市地图边界问题

### ISSUE THREAD

**Issue by XiaohanYa** [pyecharts/pyecharts#1533]
**问题**
最近在绘制四川省市级地图时，我发现攀枝花市的范围内多画了一条边界，似乎是把米易县单独划分出去了，这个与现行行政区划分不一致，不知应该如何检查、修改四川省攀枝花市的地图边界文件？谢谢。

**运行环境（系统环境及 pyecharts 版本）**
macOS, pyecharts: 1.6.2

**代码及截图**
<img width="590" alt="Screen Shot 2020-03-01 at 9 21 46 PM" src="https://user-images.githubusercontent.com/26055429/75626605-c059f680-5c03-11ea-84ce-7855001c292a.png">
<img width="1002" alt="Screen Shot 2020-03-01 at 9 21 07 PM" src="https://user-images.githubusercontent.com/26055429/75626607-c51eaa80-5c03-11ea-82db-b8f3aeaec094.png">

**Comment by sunhailin-Leo** [comment]
@XiaohanYa 
* 这个具体得去修改一下 攀枝花市 的地图的 js 源码

**Comment by sunhailin-Leo** [comment]
@XiaohanYa 
* 给你两个链接参考下 😄 
* https://github.com/echarts-maps/echarts-china-cities-js
* https://echarts-maps.github.io/echarts-geomapping-book-zh/

**Comment by XiaohanYa** [comment]
@sunhailin-Leo 谢谢:D

**Comment by chfw** [comment]
fixed:

![Screenshot 2020-03-15 at 22 55 08](https://user-images.githubusercontent.com/4280312/76712420-b1e60180-6710-11ea-9957-120bc01d1b25.png)

**Comment by chfw** [comment]
https://echarts-maps.github.io/echarts-china-provinces-js/preview.html
