### ISSUE TITLE
地图热力图的效果能否用pyecharts设置

### ISSUE THREAD

**Issue by PyYourDaYe** [pyecharts/pyecharts#1535]
**问题**
每次做完热力图都需要用vim修改html中的个别参数，非常不方便，我希望的是在用pycharts写代码时直接就可以设置参数："pointSize"、"blurSize"等；

求大神帮助！！！！！！

**运行环境（系统环境及 pyecharts 版本）**
mac+python3.7+pyecharts1.62

**代码及截图**
<img width="464" alt="热力" src="https://user-images.githubusercontent.com/38445458/75757820-0337dd80-5d6e-11ea-8e4f-11cb6dfd38c6.png">
<img width="369" alt="vim" src="https://user-images.githubusercontent.com/38445458/75757847-10ed6300-5d6e-11ea-95d0-c26268b2a181.png">

**Comment by sunhailin-Leo** [comment]
@PyYourDaYe 
* 源码 BMap 有这个参数
![image](https://user-images.githubusercontent.com/17564655/75788186-d520c080-5da2-11ea-943c-889231f538bc.png)
![image](https://user-images.githubusercontent.com/17564655/75788264-f1246200-5da2-11ea-974d-12778d616ac9.png)

**Comment by sunhailin-Leo** [comment]
@PyYourDaYe 
* 源码 BMap 有这个参数
![image](https://user-images.githubusercontent.com/17564655/75788186-d520c080-5da2-11ea-943c-889231f538bc.png)
![image](https://user-images.githubusercontent.com/17564655/75788264-f1246200-5da2-11ea-974d-12778d616ac9.png)

**Comment by PyYourDaYe** [comment]
> @PyYourDaYe
> 
> * 源码 BMap 有这个参数
>   ![image](https://user-images.githubusercontent.com/17564655/75788186-d520c080-5da2-11ea-943c-889231f538bc.png)
>   ![image](https://user-images.githubusercontent.com/17564655/75788264-f1246200-5da2-11ea-974d-12778d616ac9.png)

啊啊啊啊，好丢脸，我是看着官方文档做的，没想到源码会有这个参数；
太感谢了！！！！
