### ISSUE TITLE
请问如何自定义图例的颜色？（不是更换主题）

### ISSUE THREAD

**Issue by PyYourDaYe** [pyecharts/pyecharts#1537]
**问题**
在作graph关系图时，因为业务的需要，要求按颜色分类。但找了好久没找到怎么自定义图例的颜色，虽然可以根据官方案例修改每个节点的颜色，但还是直接对图例进行设置会更加方便和符合要求；

求教大神们！非常感谢！

**运行环境（系统环境及 pyecharts 版本）**
mac + python3.7 + pyecharts1.62

**代码及截图**
![image](https://user-images.githubusercontent.com/38445458/75871104-005ceb80-5e47-11ea-9f41-6e6f5f326f1b.png)

**Comment by sunhailin-Leo** [comment]
@PyYourDaYe 
* 通过 `set_colors` 的 api 去修改 `legend` 的颜色
![image](https://user-images.githubusercontent.com/17564655/75941899-e1546d00-5ecb-11ea-8297-9496403f221c.png)
![image](https://user-images.githubusercontent.com/17564655/75941902-e5808a80-5ecb-11ea-9520-f6c53eb57a39.png)

**Comment by sunhailin-Leo** [comment]
@PyYourDaYe 
* 在默认情况下图的颜色会跟随全局 color 的颜色列表进行填充，如果自定义了则根据自定义的颜色进行填充（Echarts 的逻辑）
* Legend 的颜色就是默认跟随全局的 color 的，但 Legend 没有配置 active 颜色的参数，只有配置 inactive 颜色的参数
* Echarts 对应 Legend 的参数列表：https://www.echartsjs.com/zh/option.html#legend

**Comment by PyYourDaYe** [comment]
> @PyYourDaYe
> 
> * 通过 `set_colors` 的 api 去修改 `legend` 的颜色
>   ![image](https://user-images.githubusercontent.com/17564655/75941899-e1546d00-5ecb-11ea-8297-9496403f221c.png)
>   ![image](https://user-images.githubusercontent.com/17564655/75941902-e5808a80-5ecb-11ea-9520-f6c53eb57a39.png)

哇哦，隐藏的宝藏很多啊，悔恨自己研究不透源码；
虽然不能灵活根据分组名称自定义颜色，但这个代码也解决了我的问题，灰常感谢！！！
