### ISSUE TITLE
圆饼图 legend显示不全

### ISSUE THREAD

**Issue by lzw-all-in** [pyecharts/pyecharts#1538]
Hi, 您好，legend为什么显示不全呢？

![1583399965519](https://user-images.githubusercontent.com/34850455/75967002-1da4bf00-5f06-11ea-8dcf-5756aad737b3.jpg)

```
def plot_pie_chat(col, index, value) -> Pie:
    c = (
        Pie()
        .add("", [[idx, int(val)] for idx, val in zip(index, value)])
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Pie-Radius"),
            legend_opts=opts.LegendOpts(
                orient="vertical", pos_top="15%", pos_left="2%"
            ),
        )
        .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
    )
    return c.render_notebook()
```

**Comment by sunhailin-Leo** [comment]
@lzw-all-in 
* 我这没有任何问题（检查下你的数据吧）
![image](https://user-images.githubusercontent.com/17564655/75967627-0fa36e00-5f07-11ea-879c-ddf65fc9daeb.png)
![image](https://user-images.githubusercontent.com/17564655/75967647-15994f00-5f07-11ea-8058-cb22228243bf.png)

**Comment by lzw-all-in** [comment]
@sunhailin-Leo  Sorry我也刚刚反应过来是数据的问题，抱歉添麻烦了

**Comment by lzw-all-in** [comment]
@sunhailin-Leo  你好我接着调试了一下，所以是因为legend不能是0吗？
![image](https://user-images.githubusercontent.com/34850455/75969181-82154d80-5f09-11ea-9faa-f67d9ad09fb8.png)

**Comment by sunhailin-Leo** [comment]
@lzw-all-in 
* 建议你先看看 demo

**Comment by kun-g** [comment]
legend 为什么不能是0，转成字符串确实就没问题了
