### ISSUE TITLE
请问可以实现类似于d3.js-Line chart-Threshold encoding 的功能吗？

### ISSUE THREAD

**Issue by perfumescent** [pyecharts/pyecharts#1539]
**问题**
请问可以实现类似于Threshold line chart的功能吗？
看了半天文档，感觉画不出来下图里按y-axis threshold将折现分成几块区域的效果，头要炸了，请问有什么解决办法嘛？
<img width="731" alt="微信图片_20200305193153" src="https://user-images.githubusercontent.com/31856209/75977726-fe169200-5f17-11ea-8b9c-411927c0ba9b.png">
这是d3.js库里的demo，链接是https://observablehq.com/@d3/threshold-encoding
**运行环境（系统环境及 pyecharts 版本）**
python3.7
pyecharts1.7

**代码及截图**

**Comment by chenjiandongx** [comment]
这种我还真没见过。。。

@sunhailin-Leo 你见过吗？

**Comment by sunhailin-Leo** [comment]
@chenjiandongx 
* 我大概理解他的意思。。不过在 echarts 里面弄暂时弄不出来

@perfumescent 
* Echarts 的 Line 图的 LineStyle 的 Color 属性不支持用 function 回调，所以没法通过数值大小改变线的颜色。我想这和渲染引擎有关系。:thinking:

**Comment by sunhailin-Leo** [comment]
@perfumescent 
* 补充个 Echarts 的参数文档给你
* https://www.echartsjs.com/zh/option.html#series-line.lineStyle.color

**Comment by perfumescent** [comment]
> @chenjiandongx
> 
> * 我大概理解他的意思。。不过在 echarts 里面弄暂时弄不出来
> 
> @perfumescent
> 
> * Echarts 的 Line 图的 LineStyle 的 Color 属性不支持用 function 回调，所以没法通过数值大小改变线的颜色。我想这和渲染引擎有关系。🤔

echart里有这个
https://www.echartsjs.com/examples/zh/editor.html?c=line-aqi
这个可以嘛

**Comment by sunhailin-Leo** [comment]
@perfumescent 
* 对喔，我忘了哈哈～ 给 `visualMap` 用上 `is_show = False`就好了
* pyecharts 的 demo：http://gallery.pyecharts.org/#/Line/beijing_aqi

**Comment by perfumescent** [comment]
哇 居然有
太棒了，感谢感谢，mua（づ￣3￣）づ╭❤～
