### ISSUE TITLE
请问要做到图表大小随浏览器变化而自适应变化有什么方法吗

### ISSUE THREAD

**Issue by weridolin** [pyecharts/pyecharts#1540]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@weridolin 
* 方案：
    * 修改模版
    * 修改生成的 html 文件

**Comment by shadoweason** [comment]
修改xxx\site-packages\pyecharts\render\templates\macro文件么

**Comment by wangjiahong666** [comment]
> @weridolin
> 
> * 方案：
>   
>   * 修改模版
>   * 修改生成的 html 文件

@sunhailin-Leo 请问修改生成的html文件应该是什么思路呢？
