### ISSUE TITLE
DataZoomOpts放缩时，如何使线的形状不发生变化

### ISSUE THREAD

**Issue by perfumescent** [pyecharts/pyecharts#1541]
**问题**
纵轴放缩时，折线形状会发生局部的变化

下面这是最开始的正确图像
<img width="638" alt="1" src="https://user-images.githubusercontent.com/31856209/76157737-166cf380-6148-11ea-8489-6dec7043ca40.png">

***

进行y轴放大后，图中圈起来的部分较图一发生了变化，折线和阶梯线的形状都被改变了
<img width="666" alt="2" src="https://user-images.githubusercontent.com/31856209/76157743-2d134a80-6148-11ea-9a98-2a3719154edd.png">

***

继续放大，形状继续被改变
<img width="681" alt="3" src="https://user-images.githubusercontent.com/31856209/76157774-88ddd380-6148-11ea-930f-323543af1b57.png">

**运行环境（系统环境及 pyecharts 版本）**
python3.7
pyecharts1.7

**代码及截图**

[render.zip](https://github.com/pyecharts/pyecharts/files/4302917/render.zip)
这是渲染的网页文件

**Comment by sunhailin-Leo** [comment]
@perfumescent 
* 可以尝试修改一下 line 的 is_smooth 参数, 进行调整
