### ISSUE TITLE
page渲染的html图表怎么居中

### ISSUE THREAD

**Issue by limmyforget** [pyecharts/pyecharts#1542]
新版本page渲染的html图表默认是靠左的，怎么设置居中

**Comment by sunhailin-Leo** [comment]
@limmyforget 
* 这个问题，目前可以去修改一下生成的 html 里面，最外层的 div，将元素布局设置为居中即可。
* 后续可以考虑加入 `InitOpts` 作为参数进行配置。但目前即将要发布的版本不会有该项功能。

**Comment by limmyforget** [comment]
thank you!
