### ISSUE TITLE
关于pycharts如何添加区域地图的问题

### ISSUE THREAD

**Issue by jaywjl** [pyecharts/pyecharts#1543]
pyecharts，Geo()地图中，geo.add_coordinate('工业园区', 120.756504, 31.334674)可以添加点的数据，但是原始苏州地图中姑苏区的边界是包含了姑苏区和工业园区，不能更改，所以希望把姑苏区划分为姑苏区和工业园区，谢谢

**Comment by sunhailin-Leo** [comment]
@jaywjl 这个问题是地图包的问题，这块暂时除了自己做一个新的地图包之外，没有别的好办法了。

**Comment by jaywjl** [comment]
我看过你们的源码，所以就是不知道你们能不能帮我把地图坐标的加密方式或者说我给你们坐标，你们帮忙加密一下，给出类似别的区的数据。
也不知道我理解的对不对，方法可行不可行
WJL


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LeoSun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 上午9:35
收件人:&nbsp;"pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;;
抄送:&nbsp;"咕嘟幽藍"<309371137@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] 关于pycharts如何添加区域地图的问题 (#1543)




@jaywjl 这个问题是地图包的问题，这块暂时除了自己做一个新的地图包之外，没有别的好办法了。

**Comment by sunhailin-Leo** [comment]
@jaywjl 
* 看过源码的应该知道地图的文件是通过对应地图的 js 进行加载的。并没有什么加密方式。
* 唯一的做法我已经说了，需要自己去制作一个新的地图包。
* 参考回复：
    * https://github.com/pyecharts/pyecharts/issues/1533

**Comment by jaywjl** [comment]
好的，我先去看看，不明白的再来请教。

WJL


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LeoSun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 上午10:06
收件人:&nbsp;"pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;;
抄送:&nbsp;"咕嘟幽藍"<309371137@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] 关于pycharts如何添加区域地图的问题 (#1543)




@jaywjl
  
看过源码的应该知道地图的文件是通过对应地图的 js 进行加载的。并没有什么加密方式。
 
唯一的做法我已经说了，需要自己去制作一个新的地图包。
 
参考回复：  
#1533

**Comment by jaywjl** [comment]
这是js文件，就是这些坐标，导致我不能自己做地图（PS：我不知道如果把一个正常的坐标点，转换成你们这种格式）
WJL


&nbsp;




------------------ 原始邮件 ------------------
发件人:&nbsp;"LeoSun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 上午10:06
收件人:&nbsp;"pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;;
抄送:&nbsp;"咕嘟幽藍"<309371137@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] 关于pycharts如何添加区域地图的问题 (#1543)




@jaywjl
  
看过源码的应该知道地图的文件是通过对应地图的 js 进行加载的。并没有什么加密方式。
 
唯一的做法我已经说了，需要自己去制作一个新的地图包。
 
参考回复：  
#1533

**Comment by chfw** [comment]
地图编码方式和DIY指南：https://echarts-maps.github.io/echarts-geomapping-book-zh/tools/mapmaker/#geojson_1
