### ISSUE TITLE
请问Kline里怎么增量更新数据呢 

### ISSUE THREAD

**Issue by answerMA** [pyecharts/pyecharts#1544]
**问题**

在django的前后端分离中，在kline_base下 将xaxis_opts=opts.axisOpts(_type='value)
就无法正常显示，但是将-type设置成为 category K线可以正常显示
请问如果在_type=category下 怎么实现增量更新 

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.7
django 2.2

**代码及截图**

def kline_base() -> Kline:
    kline = (
        Kline()
        .add_xaxis(["2017/7/{}".format(i + 1) for i in range(31)])
        .add_yaxis(series_name='',
                   y_axis=kdata,
                   )
        .set_global_opts(
                        title_opts=opts.TitleOpts(title="Kline动态数据"),
                        xaxis_opts=opts.AxisOpts(is_scale=True,
                                                type_="value"
                                                ),

**Comment by answerMA** [comment]
'category': 类目轴，适用于离散的类目数据，为该类型时必须通过 data 设置类目数据。

不是很明白 这个data在哪设置 
和下面的ajax有什么关系 
success: function (result) {
                    var options = result.data;
                    old_data.push([options.name, options.value, options.data]);
                    chart.setOption({
                        series: [{
                            data: old_data
                        }]
                    });

麻烦了

**Comment by sunhailin-Leo** [comment]
@answerMA 
* 先看明白基础的前后端分离示例。
