### ISSUE TITLE
Pyecharts为什么改这么多啦

### ISSUE THREAD

**Issue by 4timespassedCET4** [pyecharts/pyecharts#1545]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
好久没用，为什么Pyecharts变得跟以前完全不一样了，对新手太不友好了，老是报错，以前常用的字段在里面也不见了 。。。。

**Comment by chenjiandongx** [comment]
一开始我也是这么觉得的，改的东西太多了。不过后来慢慢的就习惯了。

可以看看最新的官方文档：https://pyecharts.org
