### ISSUE TITLE
flask+pyecharts前端地图显示不全

### ISSUE THREAD

**Issue by sph116** [pyecharts/pyecharts#1546]
问题：按照文档的flask+pyecharts代码 前端显示地图 显示不全
环境：py3.7 pyecharts1.7 flask1.11
![image](https://user-images.githubusercontent.com/50892459/76400256-fabd5380-63ba-11ea-8e24-100c8c9d90d9.png)

**Comment by sunhailin-Leo** [comment]
@sph116 
* 请贴一下代码和浏览器控制台的截图，谢谢
* 一张截图，谁也无法回答你的问题。

**Comment by sph116** [comment]
> @sph116
> 
> * 请贴一下代码和浏览器控制台的截图，谢谢
> * 一张截图，谁也无法回答你的问题。

好的 谢谢指正
**返回html**
![image](https://user-images.githubusercontent.com/50892459/76403010-39eda380-63bf-11ea-886a-6bb2a4763186.png)
**源码（按照文档示例）**
`from random import randrange
from flask import Flask, render_template
from pyecharts import options as opts
from pyecharts.charts import Bar, Geo
from pyecharts.faker import Faker
from pyecharts import options as opts


app = Flask(__name__, static_folder="templates")


def bar_base() -> Bar:
    c = (
        Bar()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [randrange(0, 100) for _ in range(6)])
        .add_yaxis("商家B", [randrange(0, 100) for _ in range(6)])
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"))
    )
    return c

def geo_visualmap_piecewise() -> Geo:
    c = (
        Geo()
            .add_schema(maptype="china")
            .add("geo", [list(z) for z in zip(Faker.provinces, Faker.values())])
            .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
            .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(),
            title_opts=opts.TitleOpts(title="Geo-基本示例"),
        )
    )
    return c



@app.route("/")
def index():
    return render_template("index.html")


@app.route("/barChart")
def get_bar_chart():
    c = geo_visualmap_piecewise()
    return c.dump_options_with_quotes()


if __name__ == "__main__":
    app.run()`

**Comment by sph116** [comment]
> @sph116
> 
> * 请贴一下代码和浏览器控制台的截图，谢谢
> * 一张截图，谁也无法回答你的问题。

好的，不好意思，谢谢指正
**返回html:**
![image](https://user-images.githubusercontent.com/50892459/76403758-5b02c400-63c0-11ea-8cb2-0d175174b6bb.png)

**后端**

`app = Flask(__name__, static_folder="templates")




def geo_visualmap_piecewise() -> Geo:
    c = (
        Geo()
            .add_schema(maptype="china")
            .add("geo", [list(z) for z in zip(Faker.provinces, Faker.values())])
            .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
            .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(),
            title_opts=opts.TitleOpts(title="Geo-基本示例"),
        )
    )
    return c



@app.route("/")
def index():
    return render_template("index.html")


@app.route("/barChart")
def get_bar_chart():
    c = geo_visualmap_piecewise()
    return c.dump_options_with_quotes()


if __name__ == "__main__":
    app.run()`

**Comment by sunhailin-Leo** [comment]
@sph116 
* 在模版补上 `<script type="text/javascript" src="https://assets.pyecharts.org/assets/maps/china.js"></script>`
* 地图系列的，建议先生成 html 以后看一下 head 标签的 script 的地址

**Comment by sph116** [comment]
> @sph116
> 
> * 在模版补上 `<script type="text/javascript" src="https://assets.pyecharts.org/assets/maps/china.js"></script>`
> * 地图系列的，建议先生成 html 以后看一下 head 标签的 script 的地址

好的 问题解决了 谢谢回复！！
