### ISSUE TITLE
BMap 官方示例的大 Bug！！！！

### ISSUE THREAD

**Issue by RiverGao** [pyecharts/pyecharts#1548]
如题，我按照 pyecharts gallery 提供的 BMap 示例(空气质量）实现我的一个地图可视化。

![image](https://user-images.githubusercontent.com/56507857/76529223-f709f980-64ac-11ea-8245-3f61a610b6a5.png)

看起来很顺利，但我发现数据都是小数，而我的数据全是整数。看三亚：

![image](https://user-images.githubusercontent.com/56507857/76529306-11dc6e00-64ad-11ea-841e-dc39cf772402.png)

这个神秘的数字是怎么来的？？于是我看了 gallery 里面的生成图，竟然发现：

![image](https://user-images.githubusercontent.com/56507857/76529139-d477e080-64ac-11ea-91db-99709d41505a.png)

实际上所有点的值都是一样的，而我并没有抄官方示例的 data。那么这个18.xxxx 到底是怎么来的呢？我发现：
`"柳州": [109.4, 24.33],
    "三亚": [109.511909, 18.252847],
    "自贡": [104.778442, 29.33903],`
所以这个小数其实是三亚的纬度！其他所有的点也都是一样的，就不截图了。
这就说明传入的数据格式有误。我认为关键在于 BMap.add 中的这一行：
`data_pair=convert_data()`

    def convert_data():

    res = []

    for i in range(len(data)):

        geo_coord = geoCoordMap[data[i][0]] # 根据城市名找到坐标

        geo_coord.append(data[i][1])

        res.append([data[i][0], geo_coord, data[i][1]])

    return res

应该是这里的 res 格式有误，导致 data_pair 接受的参数不正确。
由于官方文档写得太过模糊：

    # 数据项 (坐标点名称，坐标点值)

    data_pair: Sequence

所以我并不知道应该怎么写才是正确的。

另外，ECharts 的官方示例也有这个问题[https://www.echartsjs.com/examples/zh/editor.html?c=map-polygon](url)

希望得到指导

**Comment by sunhailin-Leo** [comment]
@RiverGao 
* It's not really a bug !
* You can `JSCode` to custom the `label` or `tooltip`
