### ISSUE TITLE
双折线图（Line），overlap为一个图表时，第二个折线图使用索引为1的Y轴(yaxis_index=1)，图表无法正常渲染

### ISSUE THREAD

**Issue by lawis** [pyecharts/pyecharts#1549]
**问题**
当将两个Line类型图表通过overlap聚合成一个图表后，并配置第二个图表使用第二个Y轴时，渲染后生成html文件，打开后无图表显示。

Chrome报错如下
<img width="502" alt="Chrome报错截图" src="https://user-images.githubusercontent.com/2128773/76586859-1b9dba00-651d-11ea-9b73-c1b884592028.png">

经过检查html，发现在html中的js脚本中，"yAxis"中只存在一个Y轴对象，所以 yaxis_index 大于等于1后，无法找到对应的Y轴对象。
<img width="448" alt="yAxis" src="https://user-images.githubusercontent.com/2128773/76587069-b8605780-651d-11ea-89cc-ac24cee498d5.png">

**运行环境（系统环境及 pyecharts 版本）**
MacOS 10.15.3  
Python 3.7.6 
pyecharts 1.7.0

**代码及截图**

测试代码如下
```
from pyecharts import options as opts
from pyecharts.charts import Line

chartXInfo = ["1月","2月","3月","4月","5月","6月"]
chartY1Info = [423,343,1235,122,3321,432,1151]
chartY2Info = [543,435,2344,453,564,876,854]
chartY3Info = [12.3,42.4,53.4,65.4,12.1,54.3]
chartY4Info = [87.2,67.5,76.5,76.5,86.4,35.4]

line1 = (
	Line()
	.add_xaxis(chartXInfo)
	.add_yaxis("计划开课数量",chartY1Info)
	.add_yaxis("实际开课数量",chartY2Info)
)
line2 = (
	Line()
	.add_xaxis(chartXInfo)
	.add_yaxis("开课率",chartY3Info,yaxis_index=1)
	.add_yaxis("选课率",chartY4Info,yaxis_index=1)
)

line1.overlap(line2)
line1.render("planCourseCountByDateRange.html")
```

**Comment by sunhailin-Leo** [comment]
@lawis 
* 所以你想表达什么？
* 你是想要两根 Y 轴嘛？

**Comment by sunhailin-Leo** [comment]
@lawis 
![image](https://user-images.githubusercontent.com/17564655/76587478-fa3dcd80-651e-11ea-824c-1adf252862d6.png)
* 难道你想让 Echarts 给你忽略这个错误？

**Comment by lawis** [comment]
> @lawis
> 
> * 所以你想表达什么？
> * 你是想要两根 Y 轴嘛？

对，当需要双Y轴时，会出现这个问题。

**Comment by lawis** [comment]
> @lawis
> ![image](https://user-images.githubusercontent.com/17564655/76587478-fa3dcd80-651e-11ea-824c-1adf252862d6.png)
> 
> * 难道你想让 Echarts 给你忽略这个错误？

个人认为这个错误是pyecharts生成html代码时导致的，并不像echart的bug

**Comment by sunhailin-Leo** [comment]
@lawis 
* 认真看文档和例子
![image](https://user-images.githubusercontent.com/17564655/76587932-81d80c00-6520-11ea-82c1-e01f255799ea.png)
http://gallery.pyecharts.org/#/Overlap/overlap_bar_line

**Comment by sunhailin-Leo** [comment]
> > @lawis
> > ![image](https://user-images.githubusercontent.com/17564655/76587478-fa3dcd80-651e-11ea-824c-1adf252862d6.png)
> > 
> > * 难道你想让 Echarts 给你忽略这个错误？
> 
> 个人认为这个错误是pyecharts生成html代码时导致的，并不像echart的bug

* 搞清楚 pyecharts 和 echarts 的关系

**Comment by lawis** [comment]
> @lawis
> 
> * 认真看文档和例子
>   ![image](https://user-images.githubusercontent.com/17564655/76587932-81d80c00-6520-11ea-82c1-e01f255799ea.png)
>   http://gallery.pyecharts.org/#/Overlap/overlap_bar_line

首先感谢您，pyecharts 的文档写的非常好，很详细。通过文档可以很容易的掌握pyecharts的使用方法。

只是在文档中提到的关于overlap的方法是 Bar.overlap(Line)。在文档描述的情况下，我也测试了，确实显示正常，并且yAxis中确实有两个Y轴对象数据。

而我的情况是需要 在一个 Line对象中 overlap了另外一个 Line 对象，这种情况，yAxis中就只有一个Y轴对象了。

我理解pyecharts是对echarts的python封装，对用户开发python语言的API，并最后生成对应的js代码，以便渲染图标。但很遗憾，确实没有认真了解过pyecharts生成echart js代码的内部机制，不确定生成yAxis这个对象的逻辑是pyecharts负责还是echarts库自己处理。谢谢您的回复

**Comment by sunhailin-Leo** [comment]
@lawis 
* 1、既然有了 Bar-Overlap-Line，变通一下 Line-Overlap-Line 也是一样的
![image](https://user-images.githubusercontent.com/17564655/76590632-bd76d400-6528-11ea-9140-d1305829d8d1.png)
* 2、既然不确定的，那是不是应该看看源码了解一下呢？
