### ISSUE TITLE
折线图x轴不能为数字list.不然画不出来

### ISSUE THREAD

**Issue by Bowser1704** [pyecharts/pyecharts#1551]
**问题**
折线图是,如果x轴传入的是数字list,折线就画不出来.不知道是不是bug

**运行环境（系统环境及 pyecharts 版本）**
python3.6.9 ubuntu18.04  pyecarts 1.7.1 chrome80

**代码及截图**
```python3
    # n = [100, 200, 500, 1000, 2000, 3000], 会显示不出来.
    n = ["100", "200", "500", "1000", "2000", "3000"]
    l = Line(init_opts=opts.InitOpts(width="1200px", height="800px")).add_xaxis(
        xaxis_data=n
    )
```
![image](https://user-images.githubusercontent.com/43539191/76677561-a7414480-660a-11ea-9208-50cda0150ce3.png)
![image](https://user-images.githubusercontent.com/43539191/76677568-c17b2280-660a-11ea-889a-4ece68a3664e.png)

**Comment by sunhailin-Leo** [comment]
@Bowser1704 
`set_global_opts(xaxis_opts=opts.AxisOpts(type_="value"))`
