### ISSUE TITLE
字体大小设置后显示不出来，是否有BUG？

### ISSUE THREAD

**Issue by wulaoshi** [pyecharts/pyecharts#1552]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@wulaoshi 
* Any snapshot or code？

**Comment by wulaoshi** [comment]
> @wulaoshi
> 
> * Any snapshot or code？
这是柱状图的一部分全局变量设置，想改变字体大小，我是这样写的
bar.set_global_opts(title_opts=opts.TitleOpts(title="患者年龄与性别分布"),
                    toolbox_opts=opts.ToolboxOpts(),
                    xaxis_opts=opts.AxisOpts(name="年龄"),
                    yaxis_opts=opts.AxisOpts(name="患者数"),
                    graphic_opts=opts.GraphicTextStyleOpts(font='italic bolder 16px cursive'),
                    )

**Comment by sunhailin-Leo** [comment]
@wulaoshi 
* Please read the document first.

**Comment by wulaoshi** [comment]
> @wulaoshi
> 
> * Please read the document first.

我在文档里搜索，与字体大小相关的就找到这个，也没找到相关例程。请问大佬我该怎么改？

**Comment by sunhailin-Leo** [comment]
@wulaoshi 
* Read the document again and more carefully, please.
