### ISSUE TITLE
在vscode的jupyter环境中，图片无法渲染

### ISSUE THREAD

**Issue by starwingChen** [pyecharts/pyecharts#1553]
不管是用notebook还是lab的配置代码都无法渲染，请问这个是bug还是没有适配？
**运行环境：**

- windows 10

- pyechart 1.7

**代码及截图**

![image](https://user-images.githubusercontent.com/44251923/76731239-e6e96700-6797-11ea-9577-d82a5ab78269.png)

**Comment by sunhailin-Leo** [comment]
@starwingChen 
![image](https://user-images.githubusercontent.com/17564655/76813019-9c1c2d80-6831-11ea-8314-60445bdb35c2.png)

**Comment by starwingChen** [comment]
还是不行。请问这是完整的代码吗？

**Comment by sunhailin-Leo** [comment]
> 还是不行。请问这是完整的代码吗？

Yes, it is.

**Comment by rockcitystore** [comment]
关闭vscode 插件Jupyter Notebook Renderers 可以正常工作了
