### ISSUE TITLE
使用name_map参数后，地图数据不显示

### ISSUE THREAD

**Issue by isaacgeng** [pyecharts/pyecharts#1554]
**问题**
如代码所示，如果使用了name_map参数，地图上分省的数据就不再显示。

**运行环境（系统环境及 pyecharts 版本）**
Win10.
Python 3.7.4
Virtual Env with packages:(
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
colorama==0.4.1
decorator==4.4.0
defusedxml==0.6.0
echarts-china-provinces-pypkg==0.0.3
entrypoints==0.3
ipykernel==5.1.2
ipython==7.7.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.14.1
Jinja2==2.10.1
jsonschema==3.0.2
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
llvmlite==0.29.0
lml==0.0.9
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.6.0
nbformat==4.4.0
notebook==6.0.0
numba==0.45.1
numpy==1.17.0
pandas==1.0.1
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
prettytable==0.7.2
prometheus-client==0.7.1
prompt-toolkit==2.0.9
**pyecharts==1.7.1**
pyecharts-jupyter-installer==0.0.3
Pygments==2.4.2
pyrsistent==0.15.4
pyshp==2.1.0
python-dateutil==2.8.0
pytz==2019.2
pywinpty==0.5.5
pyzmq==18.1.0
qtconsole==4.5.2
scipy==1.3.1
Send2Trash==1.5.0
simplejson==3.17.0
six==1.12.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1
xlrd==1.2.0
)

**代码及截图**

from pyecharts import options as opts
from pyecharts.charts import Geo, Page
from pyecharts.globals import ChartType, SymbolType
from pyecharts.charts import Map
from pyecharts.faker import Collector,Faker

import pandas as pd
C = Collector()
ENGLISH_PROVINCE_NAMES = {
        "广东": "guangdong",
        "安徽": "anhui",
        "福建": "fujian",
        "甘肃": "gansu",
        "广西": "guangxi",
        "贵州": "guizhou",
        "海南": "hainan",
        "河北": "hebei",
        "黑龙江": "heilongjiang",
        "河南": "henan",
        "湖北": "hubei",
        "湖南": "hunan",
        "江苏": "jiangsu",
        "江西": "jiangxi",
        "吉林": "jilin",
        "辽宁": "liaoning",
        "内蒙古": "neimenggu",
        "宁夏": "ningxia",
        "青海": "qinghai",
        "山东": "shandong",
        "山西": "shanxi",
        "陕西": "shaanxi",
        "四川": "sichuan",
        "台湾": "taiwan",
        "新疆": "xinjiang",
        "西藏": "Tibet",
        "云南": "yunnan",
        "浙江": "zhejiang",
        "重庆": "ChongQing",
        "香港": "HongKong",
        "澳门": "Macao",
        "南海诸岛": "South China Sea Islands",
        "北京": "Beijing",
        "天津": "Tianjin",
        "上海": "Shanghai"
    }
@C.funcs
def map_base() -> Map:
    c = (
        Map()
        .add("商家A", [list(z) for z in zip(Faker.provinces, Faker.values())], "china", name_map=ENGLISH_PROVINCE_NAMES)
        .set_global_opts(title_opts=opts.TitleOpts(title="Map-基本示例"))
    )
    return c
Page().add(*[fn() for fn, _ in C.charts]).render("map2.html")

![捕获](https://user-images.githubusercontent.com/17245249/76818032-801f8880-683f-11ea-9867-3ef35d374b09.PNG)

**Comment by sunhailin-Leo** [comment]
@isaacgeng 
* 你都用了 `name_map` 了，`Faker` 里面的数据找不到相对应的省份名称了。

**Comment by isaacgeng** [comment]
@sunhailin-Leo 谢谢回复，但是我实际用的代码没有用到faker，因为数据是私有的没办法贴过来。代码如下：
from pyecharts import options as opts
from pyecharts.charts import Geo, Page
from pyecharts.globals import ChartType, SymbolType
from pyecharts.charts import Map
from pyecharts.faker import Collector


import pandas as pd
C = Collector()
ENGLISH_PROVINCE_NAMES = {
        "广东": "guangdong",
        "安徽": "anhui",
        "福建": "fujian",
        "甘肃": "gansu",
        "广西": "guangxi",
        "贵州": "guizhou",
        "海南": "hainan",
        "河北": "hebei",
        "黑龙江": "heilongjiang",
        "河南": "henan",
        "湖北": "hubei",
        "湖南": "hunan",
        "江苏": "jiangsu",
        "江西": "jiangxi",
        "吉林": "jilin",
        "辽宁": "liaoning",
        "内蒙古": "neimenggu",
        "宁夏": "ningxia",
        "青海": "qinghai",
        "山东": "shandong",
        "山西": "shanxi",
        "陕西": "shaanxi",
        "四川": "sichuan",
        "台湾": "taiwan",
        "新疆": "xinjiang",
        "西藏": "Tibet",
        "云南": "yunnan",
        "浙江": "zhejiang",
        "重庆": "ChongQing",
        "香港": "HongKong",
        "澳门": "Macao",
        "南海诸岛": "South China Sea Islands",
        "北京": "Beijing",
        "天津": "Tianjin",
        "上海": "Shanghai"
    }
pvcName = pd.DataFrame.from_dict(ENGLISH_PROVINCE_NAMES,orient='index')
pvcName.reset_index(level=0, inplace=True)
pvcName.rename(columns={'index':"Chinese",0:"English"}, inplace=True)
pvcName['English'] = pvcName["English"].str.capitalize()

demo = pd.read_stata('demographic.dta')
demo = demo.loc[demo['year']==2017,['province','broadband_penetration']]
demo['broadband_penetration'] = demo['broadband_penetration']*100
total = pd.merge(pvcName,demo,left_on='English',right_on='province',how='outer',indicator=True)

data = [list(z) for z in zip(total.Chinese,total.broadband_penetration)]
c = (
    Map()
    .add("Broadband Penetration Rate", data, "china", name_map=ENGLISH_PROVINCE_NAMES)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Provincial Broadband Penetration \nRate in China"), visualmap_opts=opts.VisualMapOpts()
    )
    .render("map_guangdong.html")
)
结果如下：
![image](https://user-images.githubusercontent.com/17245249/77227290-2e1d9080-6bba-11ea-8115-741a822475d4.png)

**Comment by sunhailin-Leo** [comment]
@isaacgeng 
* `name_map` 会影像数据映射的

**Comment by sunhailin-Leo** [comment]
@isaacgeng 
* 这看上去是个问题，下个版本想办法解决下

**Comment by sunhailin-Leo** [comment]
@isaacgeng 
```python
from pyecharts import options as opts
from pyecharts.charts import Map
from pyecharts.faker import Faker

ENGLISH_PROVINCE_NAMES = {
    "广东": "guangdong",
    "安徽": "anhui",
    "福建": "fujian",
    "甘肃": "gansu",
    "广西": "guangxi",
    "贵州": "guizhou",
    "海南": "hainan",
    "河北": "hebei",
    "黑龙江": "heilongjiang",
    "河南": "henan",
    "湖北": "hubei",
    "湖南": "hunan",
    "江苏": "jiangsu",
    "江西": "jiangxi",
    "吉林": "jilin",
    "辽宁": "liaoning",
    "内蒙古": "neimenggu",
    "宁夏": "ningxia",
    "青海": "qinghai",
    "山东": "shandong",
    "山西": "shanxi",
    "陕西": "shaanxi",
    "四川": "sichuan",
    "台湾": "taiwan",
    "新疆": "xinjiang",
    "西藏": "Tibet",
    "云南": "yunnan",
    "浙江": "zhejiang",
    "重庆": "ChongQing",
    "香港": "HongKong",
    "澳门": "Macao",
    "南海诸岛": "South China Sea Islands",
    "北京": "Beijing",
    "天津": "Tianjin",
    "上海": "Shanghai"
}

c = (
    Map()
    .add(
        series_name="商家A",
        data_pair=[[ENGLISH_PROVINCE_NAMES[z[0]], z[1]] for z in zip(Faker.provinces, Faker.values())],
        maptype="china",
        name_map=ENGLISH_PROVINCE_NAMES)
    .set_global_opts(title_opts=opts.TitleOpts(title="Map-基本示例"))
    .render("name_map_example.html")
)
```
![image](https://user-images.githubusercontent.com/17564655/77274258-7c34b000-6cf0-11ea-9ac5-04f9ae408f9c.png)
