### ISSUE TITLE
PictorialBar缺少encode参数，另外是否能提供js注入功能

### ISSUE THREAD

**Issue by leohazy** [pyecharts/pyecharts#1555]
**问题**
1‘PictorialBar缺少encode参数，
2.另外是否能提供js注入功能
就是，是否能在生成html文件的时候，把自定义的js函数也一块写入到script里面，因为有时候某些参数，并没有提供相应的js方法，用户可以自己加入js来完成。
比如，设置水印
            "backgroundColor": {
                "type": "pattern",
                "image": x(),
                "repeat": "repeat",
            }
function x() {
    var waterMarkText = "test";
    var canvas = document.createElement('canvas');
    var ctx = canvas.getContext('2d');
    canvas.width = canvas.height = 100;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.globalAlpha = 0.08;
    ctx.font = '25px Microsoft Yahei';
    ctx.translate(50, 50);
    ctx.rotate(-Math.PI / 4);
    ctx.fillText(waterMarkText, 0, 0);
    return canvas
};
这里面的背景颜色我可以用dict定义，但是image这个我需要js函数来完成，不能通过jscode（）转换，直接完成，就需要在script里面注入js函数。
这个功能也很好实现，就是在生成的时候，同步写入就好了
3.各个函数是否能提供一个参数，用于接受自定义的配置信息
就是，echarts有一些参数在pyecharts里面还没有，用户可以通过传入str的方式写入。这比直接去改html文件要方便多啦！
这样就比较方便用户自行扩展功能啦
虽然pyecharts可以通过直接传入dict的方法来实现这个，但是有时候已经用了pyecharts的参数，这时候如果突然要加一些pyecharts没有实现的，就得全部重写为dict，就很麻烦！
这个功能应该也比较好实现，就是在同步写入对应的dict字符串就好了，不用去解析。
*运行环境（系统环境及 pyecharts 版本）**

1.7.0

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@leohazy 
* 1、`encode`后续可以加上去
* 2、`js`注入这个方法早就有了，`add_js_func()`
* 3、`**kwargs` 这个问题还是需要在斟酌一下，毕竟破坏了可读性。

**Comment by sunhailin-Leo** [comment]
`add_js_func` 这个函数在 demo 里面我有用过，不过在文档里面我把他作为彩蛋并没有提供相对应的说明。你可以 demo 搜索一下这函数涉及的 demo，你就明白了。

**Comment by leohazy** [comment]
> `add_js_func` 这个函数在 demo 里面我有用过，不过在文档里面我把他作为彩蛋并没有提供相对应的说明。你可以 demo 搜索一下这函数涉及的 demo，你就明白了。

嗯嗯！！我去试试，谢谢！我觉得这个库真的挺好，辛苦啦！
针对第3条我的想法是增加一个参数，用于接受用户的dict，应该不需要定义可变参数。
比如 mydict={"inverse": false,
                "offset": 0,
                "splitNumber": 5,
                "minInterval": 0,}
然后后续生成的时候，直接把这个当作str写入配置项就行了，不用解析。
----配置项----
"inverse": false,
                "offset": 0,
                "splitNumber": 5,
                "minInterval": 0,
-------配置项-------

**Comment by sunhailin-Leo** [comment]
@leohazy 
* 你是这么想的，但是其他开发者未必这么用的。所以说 **kwargs 这个参数是否加入到配置项中还是需要斟酌的。

**Comment by leohazy** [comment]
@sunhailin-Leo 嗯嗯，看看有没有什么合适的方法！

**Comment by sunhailin-Leo** [comment]
@leohazy 
* 就是我说的那个 **kwargs 额，加上去是好，但是会破坏一定的可读性

**Comment by leohazy** [comment]
@sunhailin-Leo  嗯嗯，我觉得应该还好把，很多库都是有可变参数的。而初级用户也不会用到这个，应该不至于混淆。

**Comment by sunhailin-Leo** [comment]
* Waiting for the new version.
