### ISSUE TITLE
line 折线从第二个x坐标画起

### ISSUE THREAD

**Issue by MingChaoXu** [pyecharts/pyecharts#1556]
**问题**

各位大神，为什么我的折线图会从x=2开始画起，这样的话我实际上y轴有10个数据，但是图里面只显示了9个

**运行环境（系统环境及 pyecharts 版本）**

pyecharts=1.7.0
python=3.6

**代码及截图**

![image](https://user-images.githubusercontent.com/8822286/76951569-d4f9f680-6946-11ea-960e-cb696a7d907b.png)

import json
import argparse
import numpy as np
import random
# import matplotlib.pyplot as plt
from pyecharts.faker import Faker
from pyecharts import options as opts
from pyecharts.charts import Line, Grid, Page
from pyecharts.commons.utils import JsCode
from pyecharts.render import make_snapshot
from snapshot_selenium import snapshot

def main():

    pt_x = [0.420, 0.192, 0.186, 0.143, 0.154,
            0.128, 0.134, 0.153, 0.133, 0.117]

    pt_y = [186, 388, 581, 784, 974, 1168, 1367, 1567, 1765, 1942]

    # import pdb
    # pdb.set_trace()
    x_1 = list(range(1, len(pt_x)+1))

    line1 = Line() \
        .add_xaxis(x_1).add_yaxis("fpr@recall0.99", pt_x, color='red', is_smooth=True) \
        .set_global_opts(
        title_opts=opts.TitleOpts(title="fpr-percent Statistics"),
        datazoom_opts=[
            opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside")],
    )
    line2 = Line() \
        .add_xaxis(x_1) \
        .add_yaxis("num", pt_y, color='cyan', is_smooth=True) \
        .set_global_opts(
        title_opts=opts.TitleOpts(title="num-percent Statistics"),
        datazoom_opts=[
            opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside")],
    )
    page = Page()
    page.add(line1, line2)
    page.render(path='./data_growth.html')

    # make_snapshot(snapshot, page.render(), "validate.png")

if __name__ == '__main__':
    main()

**Comment by sunhailin-Leo** [comment]
@MingChaoXu 
* 设置一下 X 和 Y 轴的 `type_` 为 `value`
