### ISSUE TITLE
page可不可以增加添加html文本的功能

### ISSUE THREAD

**Issue by limmyforget** [pyecharts/pyecharts#1557]
有时候想给grid添加一个标题，查看了下好像没用对应的方法，那就想Page可不可以随时添加html文本呢？比如说在向page添加grid之前可以先添加一个"<H2>标题<\h2>"，这样也方便随时对图表进行文字说明

**Comment by sunhailin-Leo** [comment]
@limmyforget 
* 文档和 demo 都有说明怎么加标题的 http://gallery.pyecharts.org/#/Grid/README
