### ISSUE TITLE
视觉映射最大/小值不能设置为浮点数，设置了也会自动取整。

### ISSUE THREAD

**Issue by isaacgeng** [pyecharts/pyecharts#1558]
**问题**
视觉映射最大/小值不能设置为浮点数，设置了也会自动取整。

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
from pyecharts.charts import bar
from pyecharts import options as opts
   ...: 
   ...: bar = Bar()
   ...: bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
   ...: bar.add_yaxis("商家A", [5.5, 20, 36, 10, 75, 90.8])
   ...: bar.set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
**
   ...: bar.set_global_opts(visualmap_opts=opts.VisualMapOpts(max_=90.25555, min_ = 4.4444))
**
   ...: bar.render()
![image](https://user-images.githubusercontent.com/17245249/77227158-0a0d7f80-6bb9-11ea-83ec-16cc0b670e99.png)

**Comment by sunhailin-Leo** [comment]
@isaacgeng 
* VisualMap 漏了个精度参数，下个版本加上。
* https://www.echartsjs.com/zh/option.html#visualMap-continuous.precision

**Comment by sunhailin-Leo** [comment]
@isaacgeng 
* Waiting for the new version.
