### ISSUE TITLE
Grid 情况下无法使用GraphicText在任意位置添加文字

### ISSUE THREAD

**Issue by SeanFeng91** [pyecharts/pyecharts#1560]
**问题**
参考官方示例：https://github.com/pyecharts/pyecharts/pull/1175/commits/692a55fe3ae0406b9921802d05d1bcc981c8b12a
对单独图表可以插入文字。
对于grid多图情况，graphicText无法显示

**运行环境（系统环境及 pyecharts 版本）**
Mac+pyecharts 最新版本

**代码及截图**
`from pyecharts import options as opts
from pyecharts.charts import Bar, Grid, Line
from pyecharts.faker import Faker

bar = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(title_opts=opts.TitleOpts(title="Grid-Bar"))
)
line = (
    Line()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Grid-Line", pos_top="48%"),
        legend_opts=opts.LegendOpts(pos_top="48%"),
        graphic_opts=[
                        opts.GraphicGroup(
                            graphic_item=opts.GraphicItem(
                                    # 控制整体的位置
                                    left="10%",
                                    top="10%",
                                ),
                            children=[
                                    # opts.GraphicText控制文字的显示
                                    opts.GraphicText(
                                        graphic_item=opts.GraphicItem(left="left",top="100",z=100,),
                                        graphic_textstyle_opts=opts.GraphicTextStyleOpts(
                                            # 可以通过jsCode添加js代码，也可以直接用字符串
                                            text="text_TotalSell",
                                            font="140px",
                                            graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                                                fill="#333"))
                                    ),
                                    opts.GraphicText(
                                        graphic_item=opts.GraphicItem(left="left",top="90",z=100,),
                                        graphic_textstyle_opts=opts.GraphicTextStyleOpts(
                                            # 可以通过jsCode添加js代码，也可以直接用字符串
                                            text="yes",
                                            font="14px Microsoft YaHei",
                                            graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                                                fill="#333"))
                                    )]
                            )
                            ]
    )
)

grid = (
    Grid()
    .add(bar, grid_opts=opts.GridOpts(pos_bottom="60%"))
    .add(line, grid_opts=opts.GridOpts(pos_top="60%"))
    .render("grid_vertical.html")
)
`

**Comment by sunhailin-Leo** [comment]
@SeanFeng91 
* 要放在第一个图那里

```python
from pyecharts import options as opts
from pyecharts.charts import Grid, Line, Scatter
from pyecharts.commons.utils import JsCode
from pyecharts.faker import Faker

scatter = (
    Scatter()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Grid-Scatter"),
        legend_opts=opts.LegendOpts(pos_left="20%"),
        graphic_opts=[
            opts.GraphicGroup(
                graphic_item=opts.GraphicItem(
                    rotation=JsCode("Math.PI / 4"),
                    bounding="raw",
                    right=110,
                    bottom=110,
                    z=100,
                ),
                children=[
                    opts.GraphicRect(
                        graphic_item=opts.GraphicItem(left="center", top="center", z=100),
                        graphic_shape_opts=opts.GraphicShapeOpts(width=400, height=50),
                        graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                            fill="rgba(0,0,0,0.3)"
                        ),
                    ),
                    opts.GraphicText(
                        graphic_item=opts.GraphicItem(left="center", top="center", z=100),
                        graphic_textstyle_opts=opts.GraphicTextStyleOpts(
                            text="pyecharts bar chart",
                            font="bold 26px Microsoft YaHei",
                            graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(fill="#fff"),
                        ),
                    ),
                ],
            )
        ],
    )
)
line = (
    Line()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Grid-Line", pos_right="5%"),
        legend_opts=opts.LegendOpts(pos_right="20%"),
    )
)

grid = (
    Grid()
    .add(scatter, grid_opts=opts.GridOpts(pos_left="55%"))
    .add(line, grid_opts=opts.GridOpts(pos_right="55%"))
    .render("grid_horizontal.html")
)
```
![image](https://user-images.githubusercontent.com/17564655/77495257-fc8b1a80-6e82-11ea-837f-367c36901fe1.png)
