### ISSUE TITLE
没有找到china-cities类型的地图

### ISSUE THREAD

**Issue by cmd23333** [pyecharts/pyecharts#1561]
**问题**
https://gallery.pyecharts.org/#/Map/map_china_cities
这段代码无法实现。

**运行环境（系统环境及 pyecharts 版本）**
Python3.7 
pyecharts1.71

**代码及截图**
D:\Python\Lib\site-packages\pyecharts\datasets\map_filename.json
打开之后没有“china-cities”关键字
无法做出市级的中国地图。

**Comment by sunhailin-Leo** [comment]
@cmd23333 
* 确认你的版本是 1.7.1
https://github.com/pyecharts/pyecharts/blob/master/pyecharts/datasets/map_filename.json#L24
