### ISSUE TITLE
所有 Charts 的 data 参数逻辑优化(Enhance)

### ISSUE THREAD

**Issue by sunhailin-Leo** [pyecharts/pyecharts#1562]
## 决定（Decision）：
* 自目前版本 1.7.1 之后，到 1.9.0 之前兼容，旧版数据填写格式以及新版数据填写格式。

* 新版数据填写格式：
    * 通过各图的 Item 进行配置，例如 Bar 图对应的 BarItem，Line 图对应的 LineItem。
    * 目前有部分图已经有其对应的 ChartItem ，在 1.9.0 之后将会不再兼容旧版的数据填写格式。

* 在 1.9.0 更新之前，默认情况下会收到这样的 Warning（如下图），但可以通过全局变量进行关闭，具体更新请等待 1.7.1 之后版本的更新说明文档。
![image](https://user-images.githubusercontent.com/17564655/78321412-71a2d200-759e-11ea-8bf4-b9ce430a563c.png)

**Comment by leohazy** [comment]
确实啊。。。我发现每个方法data的写入竟然都有点不一样。。。echarts里面还有dimension

**Comment by leohazy** [comment]
> 确实啊。。。我发现每个方法data的写入竟然都有点不一样。。。echarts里面还有dimension

原来还有add_dataset方法。。。。
