### ISSUE TITLE
line类型中data的写入方法有bug

### ISSUE THREAD

**Issue by leohazy** [pyecharts/pyecharts#1564]
**问题**

line方法中，data的写入为
data = [list(z) for z in zip(self._xaxis_data, y_axis)]
而在scatter中，data的写入为
if len(y_axis) > 0 and isinstance(y_axis[0], types.Sequence):
            data = [
                list(itertools.chain(list([x]), y))
                for x, y in zip(self._xaxis_data, y_axis)
            ]
        elif self.options.get("dataset") is not None:
            data = None
        else:
            data = [list(z) for z in zip(self._xaxis_data, y_axis)]
也就是说，line的yaxis无法接受嵌套list类型，但是scatter这种写法加了判断的，建议将line中的写法改为scatter的写入方式。要不然，line方法无法识别嵌套list，比如[list(z) for z in zip(x,y)]这种，就无法识别。

**运行环境（系统环境及 pyecharts 版本）**
1.7.1

**代码及截图**

**Comment by leohazy** [comment]
在看https://gallery.pyecharts.org/#/Map/china_gdp_from_1993_to_2018示例的时候，发现，如果y_axis[0]是str类型，也会出错，所以类型识别，是不是改为list？？？
if len(y_axis) > 0 and isinstance(y_axis[0], types.List):

**Comment by sunhailin-Leo** [comment]
*I don't know what you're talking about❓
