### ISSUE TITLE
用Geo如何导出美国地图

### ISSUE THREAD

**Issue by SkinnyPancake** [pyecharts/pyecharts#1565]
**问题**
你好，我想用Geo的方式导出美国地图，但是命令一直报错如下（使用Map的方式并没有问题）。

当前地点: ('Ohio', 100) 坐标不存在, 错误原因: cannot unpack non-iterable NoneType object

谢谢你的帮助！

**运行环境（系统环境及 pyecharts 版本）**

jupyter notebook，pyecharts version: 1.7.0

**代码及截图**

c = (
    Geo(init_opts = opts.InitOpts(width = '1500px', height = '1000px'),)
    .add_schema(maptype = "美国")
    .add(
        "infection",
        [["Ohio", 100]],
        type_=ChartType.EFFECT_SCATTER,
        symbol_size = 30,
        point_size = 30,
    )
    .set_series_opts(label_opts = opts.LabelOpts(is_show = False))
    .set_global_opts(
        legend_opts = opts.LegendOpts(textstyle_opts = opts.TextStyleOpts(font_size = 30)),
        title_opts = opts.TitleOpts(title = "US", 
                                   title_textstyle_opts = opts.TextStyleOpts(font_size = 40),
                                   subtitle_textstyle_opts = opts.TextStyleOpts(font_size = 25)))
)
c.render()

<img width="1124" alt="Screen Shot 2020-03-27 at 6 15 34 PM" src="https://user-images.githubusercontent.com/30631082/77804937-1c733780-7057-11ea-8547-43ef4e54678c.png">
<img width="1112" alt="Screen Shot 2020-03-27 at 6 15 52 PM" src="https://user-images.githubusercontent.com/30631082/77804939-1f6e2800-7057-11ea-95f3-69e6702ef5fd.png">

**Comment by leohazy** [comment]
没有美国地图吧，已经有地图的，地图列表在https://github.com/pyecharts/pyecharts/blob/master/pyecharts/datasets/map_filename.json。
可以使用echarts的地图js，
另外，地图也没有相关坐标，可以自己添加，用 .add_coordinate方法，如果很多的话还有个json导入，具体的你可以看下官方教程。

try:
    register_url("https://echarts-maps.github.io/echarts-countries-js/")
except Exception:
    import ssl

    ssl._create_default_https_context = ssl._create_unverified_context
    register_url("https://echarts-maps.github.io/echarts-countries-js/")

geo = (
    Geo()
    .add_schema(maptype="美国")
    .add_coordinate('Ohio',-82.884126,40.425196)
    .add(
        "infection",
        [["Ohio", 100]],
        type_=ChartType.EFFECT_SCATTER,
        symbol_size=30,
        point_size=30,
    )
    .set_series_opts(label_opts = opts.LabelOpts(is_show = False))
    .set_global_opts(
    legend_opts = opts.LegendOpts(textstyle_opts = opts.TextStyleOpts(font_size = 30)),
    title_opts = opts.TitleOpts(title = "US",
    title_textstyle_opts = opts.TextStyleOpts(font_size = 40),
    subtitle_textstyle_opts = opts.TextStyleOpts(font_size = 25)))
    .render()

)

**Comment by leohazy** [comment]
![image](https://user-images.githubusercontent.com/6706396/77813488-f9429980-70e3-11ea-9c49-88b8e68fe024.png)

**Comment by SkinnyPancake** [comment]
谢谢！这个方法可以解决我的问题！

只是还有一个小小的疑惑哦：我是仿照Map()的方法套用到Geo()上面，用Map()的时候能画出来，Geo()却不行，不知道是什么原因哦？

register_url("https://echarts-maps.github.io/echarts-countries-js/")
c = (
    Map()
    .add("infection", [["Ohio", 100]], "美国")
    .set_series_opts(
        label_opts = opts.LabelOpts(is_show = False))
    .set_global_opts(title_opts=opts.TitleOpts(title="US"))
    .render()
)

<img width="838" alt="Screen Shot 2020-03-27 at 11 14 16 PM" src="https://user-images.githubusercontent.com/30631082/77813684-ddf27280-7080-11ea-936c-3c051a693399.png">

**Comment by leohazy** [comment]
我的网络不是很好，echarts的地图库我要加载很久。关于geo和map类型，其实我也有点疑惑，还没去研究，我一般用的geo。在echarts上，geo的定义是地理坐标系组件，用于地图的绘制，支持在地理坐标系上绘制散点图，线集。map的则是在series-map，是一种基本类型，地图主要用于地理区域数据的可视化，配合 visualMap 组件用于展示不同区域的人口分布密度等数据。
我也不太清楚pyecharts为什么会有两种类型，得看源码是怎么实现的
画不出来，是因为没有相关坐标点的映射
具体的得看下pyecharts是怎么实现的，这个以后再研究吧，现在能用就先用着啦。。。

**Comment by leohazy** [comment]
> 谢谢！这个方法可以解决我的问题！
> 
> 只是还有一个小小的疑惑哦：我是仿照Map()的方法套用到Geo()上面，用Map()的时候能画出来，Geo()却不行，不知道是什么原因哦？
> 
> register_url("https://echarts-maps.github.io/echarts-countries-js/")
> c = (
> Map()
> .add("infection", [["Ohio", 100]], "美国")
> .set_series_opts(
> label_opts = opts.LabelOpts(is_show = False))
> .set_global_opts(title_opts=opts.TitleOpts(title="US"))
> .render()
> )
> 
> <img alt="Screen Shot 2020-03-27 at 11 14 16 PM" width="838" src="https://user-images.githubusercontent.com/30631082/77813684-ddf27280-7080-11ea-936c-3c051a693399.png">

我的网络不是很好，echarts的地图库我要加载很久。关于geo和map类型，其实我也有点疑惑，还没去研究，我一般用的geo。在echarts上，geo的定义是地理坐标系组件，用于地图的绘制，支持在地理坐标系上绘制散点图，线集。map的则是在series-map，是一种基本类型，地图主要用于地理区域数据的可视化，配合 visualMap 组件用于展示不同区域的人口分布密度等数据。
我也不太清楚pyecharts为什么会有两种类型，得看源码是怎么实现的
画不出来，是因为没有相关坐标点的映射
具体的得看下pyecharts是怎么实现的，这个以后再研究吧，现在能用就先用着啦。。。

**Comment by leohazy** [comment]
我刚才看了下map中data = [{"name": n, "value": v} for n, v in data_pair]，也就是直接写入的
而在geo中，lng, lat = self.get_coordinate(n)，它会从对应的json库中读入，而目前的json中没有ohio的坐标，自然是找不到了。
但是，地图都已经画出来了，其实已经有每个州的坐标了，我感觉这应该算bug，是写入方法的问题

**Comment by SkinnyPancake** [comment]
嗯嗯，make sense！这样解释的很清楚！我再用Geo()画美国地图的时候，就先手动添加经纬度坐标好了。谢谢！！！🌸🙏

**Comment by leohazy** [comment]
> 嗯嗯，make sense！这样解释的很清楚！我再用Geo()画美国地图的时候，就先手动添加经纬度坐标好了。谢谢！！！🌸🙏
不客气，我分享一个我的配色给你
from pyecharts import options as opts
from pyecharts.charts import Geo,Map
from pyecharts.datasets import register_url
from pyecharts.globals import ChartType
from pyecharts.commons.utils import JsCode

try:
    register_url("https://echarts-maps.github.io/echarts-countries-js/")
except Exception:
    import ssl

    ssl._create_default_https_context = ssl._create_unverified_context
    register_url("https://echarts-maps.github.io/echarts-countries-js/")

geo = (
    Geo( init_opts=opts.InitOpts(
                width="1200px", height="900px", page_title='美国疫情', bg_color="#333333"
            ))
    .add_schema(maptype="美国",
                itemstyle_opts={
                "normal": {
                    "color": JsCode(
                        """new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                    offset: 0,
                    color: 'rgba(147, 235, 248, .2)'
                }, {
                    offset: 0.5,
                    color: 'rgba(147, 235, 248, 0)'
                },
                {
                    offset: 1,
                    color: 'rgba(147, 235, 248, .2)'
                }], false)"""
                    ),
                    "shadowColor": "rgba(128, 217, 248, 1)",
                    "shadowOffsetX": -2,
                    "shadowOffsetY": 2,
                    "shadowBlur": 10,
                    "borderColor": "rgba(147, 235, 248, 1)",
                },
            },
            emphasis_itemstyle_opts=opts.ItemStyleOpts(color="#67E0E3"),
            label_opts=opts.LabelOpts(is_show=False, position="inside", color="#fff"),)
    .add_coordinate('Ohio',-82.884126,40.425196)
    .add(
        "infection",
        [["Ohio", 100]],
        type_=ChartType.EFFECT_SCATTER,
        symbol_size=30,
        point_size=30,
    )
    .set_series_opts(label_opts = opts.LabelOpts(is_show = False))
    .set_global_opts(
    legend_opts = opts.LegendOpts(textstyle_opts = opts.TextStyleOpts(font_size = 30,color="#fff")),
    title_opts = opts.TitleOpts(title = "US",
    title_textstyle_opts = opts.TextStyleOpts(font_size = 40,color="#fff"),
    subtitle_textstyle_opts = opts.TextStyleOpts(font_size = 25)))
    .render()

)
![image](https://user-images.githubusercontent.com/6706396/77814702-93a7da80-70ee-11ea-96b3-9256574857c2.png)

**Comment by SkinnyPancake** [comment]
回复晚了！谢谢！！！
