### ISSUE TITLE
请问可以为TooltipOpts 添加position吗？

### ISSUE THREAD

**Issue by Johannnnn506** [pyecharts/pyecharts#1566]
**问题**
echarts上好像是有的，请问方便实现吗？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
tooltip: {
          trigger: 'axis',
          // 相对位置
          position: ['50%', '30%']
        },

**Comment by sunhailin-Leo** [comment]
@Johannnnn506 
* Got it, we will add this option in next version. Thx~

**Comment by Johannnnn506** [comment]
@sunhailin-Leo 
THX! You are the best!

**Comment by chengzhaoan** [comment]
我也要用这个地方，关系图上用

**Comment by chengzhaoan** [comment]
我如果在series_options.py 添加 TooltipOpts标签，还要改那些地方 
 data: [{
                name: '节点1',
                x: 300,
                y: 300,
                symbolSize: 1,
                tooltip:{
                    formatter:'fasdfas<br />哈哈哈'
                }
            }, 
实现这种

**Comment by chengzhaoan** [comment]
> 我如果在series_options.py 添加 TooltipOpts标签，还要改那些地方
> data: [{
> name: '节点1',
> x: 300,
> y: 300,
> symbolSize: 1,
> tooltip:{
> formatter:'fasdfas
> 哈哈哈'
> }
> },
> 实现这种
不要用类结构，直接给字典，就翻译成对应js 了

**Comment by sunhailin-Leo** [comment]
* Waiting for the new version.
