### ISSUE TITLE
Bmap下生成Lines的问题

### ISSUE THREAD

**Issue by CoderPhotographer** [pyecharts/pyecharts#1567]
**问题**
我想用Bmap生成线图，在测试过程中，我发现Lines图不能生成，换为Geo类后，又可以生成Lines图了，不知道什么情况，所以来Github请求帮助，想实现的效果类似：`https://gallery.echartsjs.com/editor.html?c=xB1a5uJTR`

**运行环境（系统环境及 pyecharts 版本）**
python 3.6
pyecharts  1.7

**代码及截图**
Bmap下截图,只有SCATTER效果
![Bmap](https://user-images.githubusercontent.com/62455172/77931265-8b15f680-72de-11ea-86e1-a31475e3d224.png)
Geo下截图,有SCATTER效果和Lines效果
![Geo](https://user-images.githubusercontent.com/62455172/77931659-05467b00-72df-11ea-9535-336ae6a1526f.png)
代码如下
```
from pyecharts import options as opts
from pyecharts.charts import BMap,Geo
from pyecharts.globals import ChartType

c = (
    BMap() ## Bmap图表，Geo代码相同，只是把Bmap()换为Geo()
    .add_schema(baidu_ak='',center=[120.13066322374, 30.240018034923], )
    .add(
        "",
        data_pair=[("广州", 55), ("北京", 1000), ("杭州", 77), ("重庆", 88)],
        type_= ChartType.EFFECT_SCATTER,

    )
    .add(
        "",
        [("广州", "上海"), ("广州", "北京"), ("广州", "杭州"), ("广州", "重庆")],
        type_=ChartType.LINES,
        is_polyline=True
    )

    .set_global_opts(
        title_opts=opts.TitleOpts(title=""), visualmap_opts=opts.VisualMapOpts()
    )
    .render("demo.html")
)
```

**Comment by sunhailin-Leo** [comment]
@CoderPhotographer 
* 看 BMap Demo: http://gallery.pyecharts.org/#/BMap/README

**Comment by wuaibo** [comment]
你好，请问你解决这个问题了吗？

**Comment by Adam-lxd** [comment]
@wuaibo 不好意思，很久之前的问题了，我已经忘记了，现在也没写这方面的了。你可以参考上方回答看看是否可以解决

> 看 BMap Demo: http://gallery.pyecharts.org/#/BMap/README
