### ISSUE TITLE
numpy.ndarray类型经过list()转换后无法显示数据

### ISSUE THREAD

**Issue by ZJU-lznb** [pyecharts/pyecharts#1568]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

1.7.1
python 3.7

[1, 2, 2, 1, 1, 5, 2, 4, 5, 13, 26, 62, 88, 79]
<class 'numpy.ndarray'>
[1, 2, 2, 1, 1, 5, 2, 4, 5, 13, 26, 62, 88, 79]
<class 'list'>
直接使用list强制类型转换后仍旧无法显示数据，
经过ai_c_list = [int(i)for i in ai_c_list]
类型转换后方可显示数据。

**Comment by sunhailin-Leo** [comment]
@ZJU-lznb 
* 你是 `ndarray.tolist()` 还是 `list(<ndarray>)` ？
