### ISSUE TITLE
Page + Flask is not allowed due to with `dump_options_with_quotes` function

### ISSUE THREAD

**Issue by xiandong79** [pyecharts/pyecharts#1569]
**问题**
Page + Flask is not allowed
我的目的是能够在前端展示 Page， 目前根据教程我可以展示 Line，然后Line.dump_options_with_quotes() 返回给前端进行展示。

可是当我有 Page, 其中包含多个 Line Object，但是 Page 没有这个 dump_options_with_quotes()  函数

**Comment by sunhailin-Leo** [comment]
@xiandong79 
* Page 只是我们的排版，并不是每个图的 `json`.
* 你需要自行在页面上进行排版
