### ISSUE TITLE
请问如何动态展示Geo上面的散点（动态添加散点时）

### ISSUE THREAD

**Issue by Wang-Zm** [pyecharts/pyecharts#1570]
**问题**
我想一边向 **Geo** 对象里面添加散点，一边直接在网页上展现出来添加的点。但是似乎需要手动刷新才行，我在文档中没有发现相关问题的解决办法

**运行环境（系统环境及 pyecharts 版本）**
win10
Version: 0.5.11

**代码及截图**
```
attr2,value2=geo.cast(data2)
for i in range(len(attr2)):
    geo.add("",[attr2[i]],[value2[i]],type='scatter',is_random=True,is_visualmap=True)
    geo.render()
    time.sleep(3)
```

**Comment by sunhailin-Leo** [comment]
@Wang-Zm 
* pyecharts 生成静态页面，不做动态的事情。
* 要动态的图需要加上 web 框架
