### ISSUE TITLE
怎么样嵌套图表？

### ISSUE THREAD

**Issue by kklllh** [pyecharts/pyecharts#1571]
**问题**
请问一下，怎么样进行图表的嵌套？目前的需求是底图使用Map，每个省份上有一个饼图或者柱状图，代表着省内的数据情况。数据什么的都要，但是没能找到叠加图的方式。请大佬们指点，有demo什么的都行，谢谢！

**Comment by sunhailin-Leo** [comment]
@kklllh 
* Look at the demo: http://gallery.pyecharts.org/#/
