### ISSUE TITLE
请问Geo的LINE类型，如何搭配VisualMapOpts使用，做到不同值，连线不同颜色？

### ISSUE THREAD

**Issue by Ideasminer** [pyecharts/pyecharts#1574]
GeoType.LINE的情况下，传入值为起始点的别名。没有values
但是想传入values，并且希望根据values的大小，连线颜色改变，并搭配VisualMapOts使用。
请问当前pyecharts有无办法解决这个需求？
谢谢！

**Comment by sunhailin-Leo** [comment]
@Heterotherm 
* 不是太理解你的意思
