### ISSUE TITLE
如何给k线添加测量的功能

### ISSUE THREAD

**Issue by xuzizhenhello** [pyecharts/pyecharts#1575]
k线工具里的矩形选择的功能比较鸡肋，金融里用到测量尺的时候比较多
怎么实现像tradingview的这种测量尺的功能 
![celiang](https://user-images.githubusercontent.com/62193715/78527829-87b7c900-7810-11ea-88c9-82e1a1f6f7dd.png)

**Comment by sunhailin-Leo** [comment]
@xuzizhenhello 
* 这个目前在 Echarts 里面没有，所以我们也没啥办法。
