### ISSUE TITLE
grid显示bar和geo问题

### ISSUE THREAD

**Issue by snoopy-zc** [pyecharts/pyecharts#1576]
**问题**

在grid中同时添加bar和geo（热力图）组件时，
按先geo后bar的顺序会报错，按先bar后geo的顺序能够正常添加。
最后结果页面中，geo的所有颜色标记消失（热力图无显示），查看html源码，缺少visualMap属性

但是同时添加两个geo热力图，显示正常。

**运行环境（系统环境及 pyecharts 版本）**
Python 3.6.2 :: Anaconda custom (64-bit)
pyecharts 1.7.1 or latest

**代码及截图**
如https://github.com/pyecharts/pyecharts-gallery/blob/master/Grid/grid_geo_bar.md

**Comment by sunhailin-Leo** [comment]
@snoopy-zc 
* Grid 是先加直角坐标系的图，再加非直角坐标系的（目前的规则如此）
