### ISSUE TITLE
api的参数名和文档不一致，且不同图之间的参数名也参差不齐

### ISSUE THREAD

**Issue by dacapoday** [pyecharts/pyecharts#1579]
版本为1.7.1

Bar的 add_yaxis函数的参数中，文档上是 yaxis，而代码里是 yaxis_data。
Line的 add_yaxis函数的参数中，文档上是 yaxis，而代码里是 yaxis。
而对于 add_xaxis函数的参数，又是xaxis_data。

这个 _data 后缀飘忽不定啊？
且存在不一致的情况，能否仔细检测一遍，统一一下命名逻辑。

**Comment by sunhailin-Leo** [comment]
@dacapoday 
* First, Please pay attention to the way you talk.
* Second, We knew that and we will fix it.
