### ISSUE TITLE
如何实现把仪表盘、水球图数据随着折线图上光标的移动而变化？

### ISSUE THREAD

**Issue by theorycao** [pyecharts/pyecharts#1581]
1、如果我需要实现多图联动数据，而其中一些图形是水球图、仪表盘、图表这种没有x轴的图像，应该如何实现？

2、另外如果需要在跟随Line()数据移动的时候，显示一些非数据化的文字状态量的变化，比如“打开”、“关闭”；或者“灯亮”、“灯灭”这种，应该如何操作？

**Comment by sunhailin-Leo** [comment]
@theorycao 
* 水球图目前 Echarts 已经作为一个非常规图形，要联动比较复杂。
* 仪表盘作为独立的图形组件，联动的意义不大；不过硬是要联动的，自行写 js 去触发数据选中事件和更新事件
* 图表？Table？跟上一点的操作类似。

**Comment by theorycao** [comment]
> @theorycao
> 
> * 水球图目前 Echarts 已经作为一个非常规图形，要联动比较复杂。
> * 仪表盘作为独立的图形组件，联动的意义不大；不过硬是要联动的，自行写 js 去触发数据选中事件和更新事件
> * 图表？Table？跟上一点的操作类似。

您好，再问一下，如何获得鼠标在Line()曲线是划过时候的X轴值？

**Comment by theorycao** [comment]
@sunhailin-Leo 您好，请问如何取得鼠标在Line()曲线上的X轴数值？
