### ISSUE TITLE
怎么让pyecharts柱状图的每个柱子显示不同的颜色？

### ISSUE THREAD

**Issue by qichikimochi** [pyecharts/pyecharts#1582]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@qichikimochi 这个目前看来，除了用 JsCode 去控制，也没什么好办法...毕竟在 Echarts 里面柱子的颜色和 Legend 是默认绑定的。
