### ISSUE TITLE
请教geo_lines_background案例有关设置使用问题？

### ISSUE THREAD

**Issue by xmxmxmxm2011** [pyecharts/pyecharts#1585]
geo_lines_background案例中，有关设置的疑问。
一、type_=ChartType.LINES,默认线条的端点是箭头，在add 中设置symbol="",也无法见效，即使在linestyle_opt中设置opts.LineStyleOpts(width=0)也还是有箭头符号。
二、type_=ChartType.EFFECT_SCATTER,默认scale=2.5，即使修改scale为其他数值也无法见效。
三、将几个geo_lines_background加入到Timeline中，Timeline的init_opts中设置背景颜色bg_color无法生效。
四、想设置渐变色，但网上找不到python的语句。通过jscode()使用echarts上的语法也无法实现。
五、render 能否导出为可以动的图片（*.gif）?如果可以的话，需要import 什么库呢，之前查了网上的方法，导出的只是不会动的图片。
以上问题，请老师拨冗不吝指教。谢谢

**Comment by sunhailin-Leo** [comment]
@xmxmxmxm2011 
* 1、`symbol` 需要 `SymbolType 的类型
![image](https://user-images.githubusercontent.com/17564655/79072870-ff588d00-7d15-11ea-9c5a-941e2ab93cbc.png)
![image](https://user-images.githubusercontent.com/17564655/79072908-19926b00-7d16-11ea-83ae-67c28c19148e.png)
* 2、暂时无解
* 3、`color` 到的确没有，不过可以设置 `theme`
* 4、渐变色你是怎么设置的？
* 5、render 无法导出 gif，需要自行录屏。

**Comment by xmxmxmxm2011** [comment]
谢谢。第一个问题，我其实是指红色那个箭头，不是effect 的那个蓝色箭头。我后来用 symbol=JsCode(("['none','']"))，解决了。
