### ISSUE TITLE
bar图overlap的时候，带datazoom_opts参数就无法正常出图

### ISSUE THREAD

**Issue by dehiker** [pyecharts/pyecharts#1586]
**问题**
bar图overlap的时候，带datazoom_opts参数就无法正常出图。

类似问题在[add_xaxis所用的字符串中含有空格/&/-等字符时，overlap后无法正常显示](https://github.com/pyecharts/pyecharts/issues/1261)提过，但issue被关闭了，只能新开一个提问。

**运行环境（系统环境及 pyecharts 版本）**
CentOS Linux release 7.6.1810 (Core)
pyecharts==1.7.1

**代码及截图**
* 带datazoom_opts参数时，无法正常出图：
```
import pandas as pd

from pyecharts.charts import Bar, Page, Line
from pyecharts import options as opts

data = pd.Series([1, 3, 4, 2])
idx = [str(i) for i in data.index]

# 初始化
obj = Bar() \
    .set_global_opts(datazoom_opts=[opts.DataZoomOpts(range_start=0, range_end=100),
                                    opts.DataZoomOpts(type_='inside')],
                     xaxis_opts=opts.AxisOpts(type_='category', axislabel_opts=opts.LabelOpts(rotate=30)))
# 画bar图
o = Bar() \
        .add_xaxis(idx) \
        .add_yaxis(str(data.name), data.tolist())

# 叠加
obj.overlap(o)

obj.render_notebook()
```
![err_with-datazoom_opts](https://user-images.githubusercontent.com/1631480/79040289-17e37d00-7c1a-11ea-8a7b-b9ee0101a187.png)

* 不设datazoom_opts参数时，能正常出图：
```
import pandas as pd

from pyecharts.charts import Bar, Page, Line
from pyecharts import options as opts

data = pd.Series([1, 3, 4, 2])
idx = [str(i) for i in data.index]

# 初始化
obj = Bar() \
    .set_global_opts(#datazoom_opts=[opts.DataZoomOpts(range_start=0, range_end=100),
                     #               opts.DataZoomOpts(type_='inside')],
                     xaxis_opts=opts.AxisOpts(type_='category', axislabel_opts=opts.LabelOpts(rotate=30)))
# 画bar图
o = Bar() \
        .add_xaxis(idx) \
        .add_yaxis(str(data.name), data.tolist())

# 叠加
obj.overlap(o)

obj.render_notebook()
```
![bar_no-datazoom_opts](https://user-images.githubusercontent.com/1631480/79040300-20d44e80-7c1a-11ea-8b1e-83eb107473a4.png)

**Comment by sunhailin-Leo** [comment]
@dehiker 
```python
from pyecharts import options as opts
from pyecharts.charts import Bar, Line
from pyecharts.faker import Faker

v1 = [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3]
v2 = [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
v3 = [2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]

bar = (
    Bar()
    .add_xaxis(Faker.months)
    .add_yaxis("蒸发量", v1)
    .add_yaxis("降水量", v2)
    .extend_axis(
        yaxis=opts.AxisOpts(
            axislabel_opts=opts.LabelOpts(formatter="{value} °C"), interval=5
        )
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Overlap-bar+line-dataZoom"),
        yaxis_opts=opts.AxisOpts(
            axislabel_opts=opts.LabelOpts(formatter="{value} ml")
        ),
        datazoom_opts=[
            opts.DataZoomOpts(range_start=0, range_end=100)
        ]
    )
)

line = Line().add_xaxis(Faker.months).add_yaxis("平均温度", v3, yaxis_index=1)
bar.overlap(line)

bar.render("t_11.html")
```
![image](https://user-images.githubusercontent.com/17564655/79072717-177bdc80-7d15-11ea-83e9-f4d73cb89892.png)

**Comment by qichikimochi** [comment]
pyecharts/pyecharts你好

  非常感谢     




zhc@djtu.edu.cn
 
发件人： LeoSun
发送时间： 2020-04-12 23:28
收件人： pyecharts/pyecharts
抄送： Subscribed
主题： Re: [pyecharts/pyecharts] bar图overlap的时候，带datazoom_opts参数就无法正常出图 (#1586)
@dehiker
from pyecharts import options as opts
from pyecharts.charts import Bar, Line
from pyecharts.faker import Faker
v1 = [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3]
v2 = [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
v3 = [2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]
bar = (
    Bar()
    .add_xaxis(Faker.months)
    .add_yaxis("蒸发量", v1)
    .add_yaxis("降水量", v2)
    .extend_axis(
        yaxis=opts.AxisOpts(
            axislabel_opts=opts.LabelOpts(formatter="{value} °C"), interval=5
        )
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Overlap-bar+line-dataZoom"),
        yaxis_opts=opts.AxisOpts(
            axislabel_opts=opts.LabelOpts(formatter="{value} ml")
        ),
        datazoom_opts=[
            opts.DataZoomOpts(range_start=0, range_end=100)
        ]
    )
)
line = Line().add_xaxis(Faker.months).add_yaxis("平均温度", v3, yaxis_index=1)
bar.overlap(line)
bar.render("t_11.html")
