### ISSUE TITLE
是否有pyecharts所使用的世界国家名称列表

### ISSUE THREAD

**Issue by PenguinSmith** [pyecharts/pyecharts#1587]
**问题**
绘制世界地图时常常会碰到数据集里的国家名称和pyecharts国家名称有差别的问题，导致pyecharts无法对应到正确的国家（例：Cape Verde/Cabo Verde; America/USA; Plurinational State of Bolivia/ Bolivia）.
试图去文档和源代码中找完整的国家名称列表但没有找到。
可否提供类似的名称列表？可能会常常用到

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.7.1

**Comment by chfw** [comment]
https://github.com/echarts-maps/echarts-countries-js 自诉文件有列表

**Comment by PenguinSmith** [comment]
> https://github.com/echarts-maps/echarts-countries-js 自诉文件有列表

此前我也找到了这份列表，但这个列表也是不完全适用于pyecharts的
e.g. 中非 Central African Republic无法识别，Central Africal Rep. 可以

最终使用Pyecharts时我结合了
1） https://github.com/echarts-maps/echarts-countries-js 
2） https://www.cnblogs.com/Irvingcode/p/12656728.html
两份表格的国家名称
