### ISSUE TITLE
Graph中如何给每个GraphLink分别设置不同长度？

### ISSUE THREAD

**Issue by Index-Out-Of-Range** [pyecharts/pyecharts#1588]
**问题**
我在用Graph的时候没找到怎么给每条边分别设置长度

**运行环境（系统环境及 pyecharts 版本）**
python3.6, pyecharts 1.7

**代码及截图**
代码如下：
 ```
    for i in range(len(sorted_id)):
        nodes_data.append({'name': int(sorted_id[i]),
                           'symbol': 'rect',
                           'symbolSize': 25,
                           'itemStyle': {'normal': {'color': '#f47920'}},
                            'draggable': True,
                           })
        links_data.append(opts.GraphLink(
            source=str(input_id),
            target=str(sorted_id[i]),
            value=round(float(sorted_scores[i]), 6),
            linestyle_opts=opts.LineStyleOpts(type_='dashed')
        ))
    c = (
        Graph().add("", nodes_data, links_data, repulsion=300)
            .set_global_opts(title_opts=opts.TitleOpts(title="Predition Result"))
            .render("graph.html")
    )
```
实现效果如下：
![image](https://user-images.githubusercontent.com/45255704/79049193-9687ec80-7c11-11ea-915f-9f5c1e8a236c.png)

可以看到节点之间边的长度是随机的，我想自己设置这个长度应该怎么做？

在官方文档中，有提到

> 边的两个节点之间的距离，这个距离也会受 repulsion。
    支持设置成数组表达边长的范围，此时不同大小的值会线性映射到不同的长度。值越小则长度越长。
    edge_length: Numeric = 50,

但我并没有明白它的具体用法。

**Comment by sunhailin-Leo** [comment]
@Index-Out-Of-Range 
* 你可以参考下 Echarts 的官方文档看看。https://www.echartsjs.com/zh/option.html#series-graph.force
* 这个具体我也没去深究过怎么设置。
