### ISSUE TITLE
用pyecharts生成的html打不开，打开很慢！

### ISSUE THREAD

**Issue by solomsk** [pyecharts/pyecharts#1590]
**问题**
用pyecharts生成的html打不开，打开很慢！
官网pyecharts.org打开也很慢，是不是服务出问题了？
还有，我发邮件申请加微信群好多天了，还没回复我，看到帮忙处理下，谢谢！

**运行环境（系统环境及 pyecharts 版本）**
MacOS 10.14.6
python 3.6.8
pyecharts  1.7.1

**代码及截图**
空白页面

**Comment by solomsk** [comment]
之前也遇到过几次了。。

**Comment by DongdongGui** [comment]
应该是资源挂载的问题，你可以把资源挂载在本地，或者挂载在自己的服务器上
