### ISSUE TITLE
组合图表Page加上layout=Page.DraggablePageLayout参数后，Table无法实现高度的伸缩

### ISSUE THREAD

**Issue by solomsk** [pyecharts/pyecharts#1591]
**问题**
组合图表Page加上layout=Page.DraggablePageLayout参数后，Table(这里说的Table，是指pyecharts的图表类型->HTML组件->Table表格)无法实现高度的伸缩，只能实现宽度的伸缩。而其他图表（饼图、折线图、柱形图等）都可以实现宽度和高度的伸缩。
官网中给的示例代码：
http://gallery.pyecharts.org/#/Page/page_draggable_layout
最下面的Table也是无法伸缩的。

**运行环境（系统环境及 pyecharts 版本）**
MacOS 10.14.6
python 3.6.8
pyecharts 1.7.1

**代码及截图**

无

**Comment by chenjiandongx** [comment]
因为 table 本身就不是 Echarts 所提供的内置图表类型之一，而是我们自己提供定制的。所以 table 并不是所有的行为都会符合预期。

这是一个新的需求，想不想实现就取决于 @sunhailin-Leo 。it's your turn now.

**Comment by sunhailin-Leo** [comment]
@solomsk 
* Table 目前默认的样式使用纯 css + html 实现的。加入宽高伸缩需要引入其他的 css；且当用户不使用默认的 css 样式时，即使默认样式实现了宽高伸缩，也无法生效
