### ISSUE TITLE
Bmap下SCATTER类型根据value显示不同大小

### ISSUE THREAD

**Issue by CoderPhotographer** [pyecharts/pyecharts#1592]
**问题**
#### 我尝试用label_opts显示数据名和数据值，显示出来的数据值部分类似：经度,纬度,我输入的value，图二所示。我的目的是：显示数据值部分只有我输入的value(没有经纬度)。之后我查看了官方文档的对这部分的描述，好像是用“{@[n]}”来表示n维的值，我又尝试修改formatter部分但是一直没做出来，所以来发issue求帮助。

感谢开发者们的解答~

**运行环境（系统环境及 pyecharts 版本）**
windows10 
Python 3.7.7
pycharts 1.7.1

**代码及截图**
[![JEkN5V.png](https://s1.ax1x.com/2020/04/16/JEkN5V.png)](https://imgchr.com/i/JEkN5V)
####       图一

![JEVmU1.png](https://s1.ax1x.com/2020/04/16/JEVmU1.png)
#### 问题部分的代码
```python
            .add(
            type_=ChartType.SCATTER,
            series_name="",
            data_pair=[['上海',5],['浙江',50]],
            effect_opts=opts.EffectOpts(),
            label_opts=opts.LabelOpts(formatter="{b}:{c}", is_show=True, color='#ECECE9', position='top'),
            itemstyle_opts=opts.ItemStyleOpts(color='#E58456',),
            tooltip_opts=opts.TooltipOpts(formatter="{b}:{c}")
            )
```

**Comment by sunhailin-Leo** [comment]
@CoderPhotographer 
* 建议使用 JsCode
