### ISSUE TITLE
使用timeline+geo做散点图的时候，后面年份新增的点也会在前面的年份地图上显示出来，前面的年份并没有加入新的点

### ISSUE THREAD

**Issue by ifwind** [pyecharts/pyecharts#1593]
**问题**

使用timeline+geo做散点图的时候，后面年份新增的点也会在前面的年份地图上显示出来，前面的年份并没有加入新的点，是我漏了设置什么参数吗？

**运行环境（系统环境及 pyecharts 版本）**

py3.7,
pyecharts 1.6.2
**代码及截图**
![image](https://user-images.githubusercontent.com/46741827/79521516-f48e5700-808b-11ea-9b01-7782e3069b30.png)
    groups=group_classes.groupby('label')
    # 加入特定点坐标
    c = (
        Geo()
        .add_schema(maptype="云南"))
    for i in range(len(group_classes)):
        name=group_classes['name'][i]
        c.add_coordinate(name, jd_dicts['baidu_long'][name], jd_dicts['baidu_lat'][name])
        # c.add("", [(name, node['value'])],
        #       type_=ChartType.SCATTER, symbol_size=node['value'])
    for label in groups.groups.keys():
        group=groups.get_group(label)
        (
         c.add("area"+str(label), [[name,int(label)] for name in group['name'].values.tolist()],symbol_size=7)
            .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
            .set_global_opts(
                title_opts=opts.TitleOpts(title=year_,) #visualmap_opts=opts.VisualMapOpts(max_=len(cluster_centers_indices)), )
            )   
        )
    timeline.add(c, str(year_) + "年")

**Comment by sunhailin-Leo** [comment]
@ifwind 
* 贴一下完整的代码
* 根据你局部的代码来看，你的 timeline 貌似使用的方式有问题

**Comment by ifwind** [comment]
> @ifwind
> 
> * 贴一下完整的代码
> * 根据你局部的代码来看，你的 timeline 貌似使用的方式有问题
```
timeline = Timeline(init_opts=opts.InitOpts(width="900px", height="700px"))
timeline.add_schema(pos_left="50", pos_right="50px", pos_bottom="0px")
groups=group_classes.groupby('label')
#     # 加入特定点坐标
c = (
    Geo()
    .add_schema(maptype="云南"))
for i in range(len(jd_dicts)):
    name=jd_dicts.index[i]
    c.add_coordinate(name, jd_dicts['baidu_long'][name], jd_dicts['baidu_lat'][name])

for label in groups.groups.keys():
    group=groups.get_group(label)
    (
      c.add("area"+str(label), [[name,int(label)] for name in group['name'].values.tolist()],symbol_size=7)
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(
            title_opts=opts.TitleOpts(title=year_,) #visualmap_opts=opts.VisualMapOpts(max_=len(cluster_centers_indices)), )
        )   
    )
timeline.add(c, str(year_) + "年")
timeline.render(r"cluster.html")
```
![image](https://user-images.githubusercontent.com/46741827/79692223-91bcdb80-8296-11ea-9875-ce7abc0244ee.png)

数据示例：
	name	label
0	地点1	25
1	地点2	22
2	地点3	20

	name	baidu_long	baidu_lat
0	地点1	100.804208	22.014181
1	地点2	103.8975149	27.7540214
2	地点3	100.9725698	22.83097919
