### ISSUE TITLE
多个数据使用同一坐标，能不能做到根据选中的数据设置坐标轴的范围

### ISSUE THREAD

**Issue by shadoweason** [pyecharts/pyecharts#1594]
**问题**

有很多组数据组成的折线图，但y轴的坐标范围是按做大的数据范围来展示的，如果只选择都是小数据的一组时，数据曲线不好分析

**运行环境（系统环境及 pyecharts 版本）**

python 3.7 ，  pycharts 1.7.1

**代码及截图**

![123](https://user-images.githubusercontent.com/49584731/79551060-be70c780-80cb-11ea-8260-0d79425c2eed.jpg)

**Comment by shadoweason** [comment]
是不是没有该功能的，目前的做法是设置datazoom_opts来手动调整范围，勉强达到要求但不够智能
![1E4A1A63-1307-4ee4-A12F-813E056B7872](https://user-images.githubusercontent.com/49584731/79628569-9e491300-8174-11ea-857f-d49f55dd81c3.png)

**Comment by sunhailin-Leo** [comment]
@shadoweason 
* 你或许应该去跟 Echarts 提 issue，而不是 pyecharts
