### ISSUE TITLE
小问题：设置副标题，用参数时时subtitle，但是字典格式就是subtext了？

### ISSUE THREAD

**Issue by lietouleon** [pyecharts/pyecharts#1595]
**用参数和用字典时的名字是特意区分的吗？**
新人上手，用字典的时候写“subtitle”死活无效，后来发现和传参方式不同，
字典方式里的副标题是“subtext”

**运行环境**
python3.7

**代码及截图**
效果是一样的
![601587128658_ pic_hd](https://user-images.githubusercontent.com/10094578/79572286-43210d00-80ef-11ea-8f30-394971092922.jpg)

**Comment by chenjiandongx** [comment]
在 Echarts 中是定义 text/subtext，但我在接口中为了语义更加明确，使用了 title/subtitle。
