### ISSUE TITLE
菜鸟问个奇怪的失败例子

### ISSUE THREAD

**Issue by crazyiori2003** [pyecharts/pyecharts#1596]
win7 64位 ，python 3.78，jupyter notebook下出现的，求教各位老师
nodes和links来自一个pandas的Dataframe统计的结果
用如下代码，画出来是个空的，打开html文件看value结果都是null
``` python
pic_test = (
    Sankey()
    .add('',
         nodes,
         links,
         linestyle_opt=opts.LineStyleOpts(
             opacity=0.3, curve=0.5, color='source'),
         label_opts=opts.LabelOpts(position='right'),
         node_gap=30,
         )
    .set_global_opts(title_opts=opts.TitleOpts(title='学员特征'))
)
pic_test.render('./桑基图测试.html')
```
然后我一模一样把links的实际内容，复制一遍赋值给links结果就是正确的了。
还有，如果不复制下面代码结果也是正确的
``` python
tmp=pd.DataFrame(links)
links2 = []
for i in tmp.values:
    dic = {}
    dic['source'] = i[0]
    dic['target'] = i[1]
    dic['value'] = i[2]
    links2.append(dic)
pic_test = (
    Sankey()
    .add('',
         nodes,
         links2,
         linestyle_opt=opts.LineStyleOpts(
             opacity=0.3, curve=0.5, color='source'),
         label_opts=opts.LabelOpts(position='right'),
         node_gap=30,
         )
    .set_global_opts(title_opts=opts.TitleOpts(title='学员特征'))
)
```
我试了下`links==links2`，结果显示是`True`，这到底是什么原因啊，为什么明明两个是相同，一个就能正确出来，一个就html文件里的value全是null，折腾我好几天了，求教各位老师

**Comment by chenjiandongx** [comment]
to_list() 应该可以解决问题，因为 pandas/numpy 使用的整型和浮点型不属于 Python 的内置数据类型，Json 序列化的时候会出现问题。

**Comment by crazyiori2003** [comment]
> to_list() 应该可以解决问题，因为 pandas/numpy 使用的整型和浮点型不属于 Python 的内置数据类型，Json 序列化的时候会出现问题。

我之前那个links也是list啊，不是numpy的，里面也是list里面dict

**Comment by sunhailin-Leo** [comment]
@crazyiori2003 
* 认真检查一下你的数据类型，用 type 函数去看一下

**Comment by crazyiori2003** [comment]
> @crazyiori2003
> 
> * 认真检查一下你的数据类型，用 type 函数去看一下

确认过的了报错那个也是list的，list里面也看了，是dict的

**Comment by crazyiori2003** [comment]
明明是list的就是不管用，我把这个list转成Dataframe再转回list就能用了。。。。。
