### ISSUE TITLE
怎么将多个图例分开放在两侧

### ISSUE THREAD

**Issue by shadoweason** [pyecharts/pyecharts#1597]
**问题**
目前两个y轴分别绑定多组数据，想讲两个轴绑定的数据的图例分别放在两个y轴两侧

**运行环境（系统环境及 pyecharts 版本）**
python3.7 pyechart1.7

**代码及截图**
![image](https://user-images.githubusercontent.com/49584731/79632440-b9764b80-8191-11ea-9865-7a94798ddcc4.png)

# 设置部分代码
            self.type.add_xaxis(range(1, self.line+1))
            # 添加 y轴 多个数据
            for key, values in self.pos_dict.items():
                if key in self.y2_axis:
                    self.type.extend_axis(
                        yaxis=opts.AxisOpts(type_="value",
                        name=self.y2_axis,
                        # min_=35,
                        # max_=40,
                        position="right",
                        # axislabel_opts=opts.LabelOpts(formatter="{value} °C")
                        ))
                    self.type.add_yaxis(key, values, yaxis_index=1)
                else:
                    self.type.add_yaxis(key, values, is_selected=False)  # 添加数据项，默认不显示

            # 属性设置
            self.type.set_global_opts(
                legend_opts=opts.LegendOpts(type_='scroll', item_width=8, orient="vertical", pos_left="93%", pos_top="5%",legend_icon="roundRect"),
                # title_opts=opts.TitleOpts(title="柱状图", subtitle="电机参数信息"),  # 标题
                tooltip_opts=opts.TooltipOpts(trigger="axis", axis_pointer_type="cross"),   # 交叉指向工具
                toolbox_opts=opts.ToolboxOpts(is_show=True,  pos_left="30%", pos_top="5%"),  # 工具栏
                yaxis_opts=opts.AxisOpts(axislabel_opts=opts.AxisLineOpts(symbol="allow")),
                xaxis_opts=opts.AxisOpts(type_="category"),
                datazoom_opts =[opts.DataZoomOpts(yaxis_index=0, orient="vertical", pos_left="5%", pos_top="50%", pos_bottom="5%", range_start=-1000, range_end=1000),
                                opts.DataZoomOpts(yaxis_index=1, orient="vertical", pos_left="93%", pos_top="35%", pos_bottom="5%", range_start=-10000, range_end=10000)]
            )
            self.type.set_series_opts(
                label_opts=opts.LabelOpts(is_show=False, position="bottom"),  # 标签
                # areastyle_opts=opts.AreaStyleOpts(),
                axisline_opts = opts.AxisLineOpts(symbol="bottom"),
                linestyle_opts=opts.LineStyleOpts(width=2), # 线宽
            )

**Comment by sunhailin-Leo** [comment]
@shadoweason 
* 这个 Echarts 还不支持，暂时没办法

**Comment by shadoweason** [comment]
看了源码确实不支持，参照datazoom_opts修改源码实现了该功能
