### ISSUE TITLE
Table功能询问

### ISSUE THREAD

**Issue by SeanFeng91** [pyecharts/pyecharts#1598]
**问题**
在使用表格过程中有以下需求，不知是否可以实现：

1. Table目前可以与Tab,Page兼容，但Grid是不是仍然不可以？
2. Table目前是鼠标移动到某一行高亮，怎样不启用该功能？
3. 可是设置单独单元格颜色、文字粗细等等？

**运行环境（系统环境及 pyecharts 版本）**
mac+最新pyecharts

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@SeanFeng91 
* Table 属于 pyecharts 的衍生物，并非为 echarts 的可视化图，因此暂时不兼容。
* 高亮是默认的 CSS 样式配置
* 暂时没办法做到单独设置
