### ISSUE TITLE
Please enable use of PyeCharts in HoloViews Panel to create awesome analytics apps in Python

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyecharts/pyecharts#1599]
### What problem does this feature solve?

I am a user of [Panel](https://panel.holoviz.org/) which is a framework for creating awesome analytics apps in Python.

I think ECharts and PyeCharts are awesome too and would like to be able to use it with Panel.

#### Solution

Contribute an ECharts and PyeCharts pane to Panel.

### What does the proposed API look like?

Well I've actually already developed and contributed it in this Pull Request. https://github.com/holoviz/panel/pull/1286/

Would just like to let you know that you can very soon use PyeCharts with Panel in Python to create awesome analytics apps. 

Very useful for domain experts like analysts, engineers and scientists as well as data engineers and data scientists.

![echarts](https://user-images.githubusercontent.com/42288570/79696969-3bdd3900-8280-11ea-9208-dca690442514.gif)

**Comment by sunhailin-Leo** [comment]
@MarcSkovMadsen 
* I think this is a wonderful API for us!
* We will consider adding this feature to the next version, but not the next one. Because it's a very breakthrough feature.

**Comment by MarcSkovMadsen** [comment]
Ahh. You actually think differently than me.

I think it will just be a part of Panel. You don't need to put it in PyeCharts.

But its awesome that you like it.

**Comment by sunhailin-Leo** [comment]
@MarcSkovMadsen 
* Because of, `pyecharts` also have a render mode to single HTML file, so I think to add a parameter when render the charts with the Panel.
