### ISSUE TITLE
使用pyecharts_counties问题，关于外国地图

### ISSUE THREAD

**Issue by liruiyuan2018** [pyecharts/pyecharts#1600]
**问题**

已经pip安装了echarts_countries 地图，想调用一个国家的地图，maptype随便这个没有的国家名字也不报错，不知道需要在哪里生命是外国地图？

**运行环境（系统环境及 pyecharts 版本）**

python 3.7
pyecharts .1.7.1
我是想用摩洛哥的地图
**代码及截图**

![20200419_223054](https://user-images.githubusercontent.com/36436082/79729988-bb4e2500-82df-11ea-8800-9a1a54770c6f.jpg)
![20200419_223110_001](https://user-images.githubusercontent.com/36436082/79729993-bdb07f00-82df-11ea-88ad-492332b7ccc3.jpg)
![mmexport1587335743533](https://user-images.githubusercontent.com/36436082/79729995-be491580-82df-11ea-9e0b-0450329c8f82.jpg)
![mmexport1587335787670](https://user-images.githubusercontent.com/36436082/79730004-c012d900-82df-11ea-9c1a-2113473eaf9a.jpg)
![20200419_223953](https://user-images.githubusercontent.com/36436082/79730008-c1440600-82df-11ea-907c-9ca3fb2f6dcb.jpg)

补充：我后来参考了这个问题：https://github.com/pyecharts/pyecharts/issues/1565
不太明白，我下载了echarts coutries的摩洛哥地图，不能直接用吗？只能使用map_filename.json里面定义的？有没有办法扩展这个map_filename.json文件呢？

**Comment by liruiyuan2018** [comment]
发现1.x已经不支持地图插件了

**Comment by chfw** [comment]
详情请参照：https://github.com/echarts-maps/echarts-countries-js。

如果需要扩展 map_filename.json， 请发 PR 到 https://github.com/pyecharts/pyecharts

注明 echarts-countries-js 非 echarts 官方项目。
