### ISSUE TITLE
如何正确画出直方图？

### ISSUE THREAD

**Issue by Crispinli** [pyecharts/pyecharts#1603]
**问题**

如何正确画出直方图：每个区间对应一个值？

**运行环境（系统环境及 pyecharts 版本）**

macos-python36
pyecharts==1.7.1

**代码及截图**

![image](https://user-images.githubusercontent.com/45169900/80097436-df3e8e80-859d-11ea-9065-29aa9ef9f902.png)

**求帮助**

**Comment by sunhailin-Leo** [comment]
@Crispinli 
* http://gallery.pyecharts.org/#/Bar/bar_histogram_color

**Comment by Crispinli** [comment]
> @Crispinli
> 
> * http://gallery.pyecharts.org/#/Bar/bar_histogram_color

如果是统计每个数值区间中满足条件的数据条数呢？
