### ISSUE TITLE
issues about rendering the charts

### ISSUE THREAD

**Issue by ChicoXYC** [pyecharts/pyecharts#1604]
**问题**
When plotting pie charts, if I pass ```[list(z) for z in zip( crisis.index, crisis['CRISIS'].values)]``` into the function, the chart cannot display correctly, but when I just paste the value of ```[list(z) for z in zip( crisis.index, crisis['CRISIS'].values)]``` directly, it works. Is there anything I am missing?

**运行环境（系统环境及 pyecharts 版本）**
Python 3.6.4
pyecharts==1.7.1
pyecharts-javascripthon==0.0.6
pyecharts-jupyter-installer==0.0.3
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
jupyter-echarts-pypkg==0.1.1

**代码及截图**
## not work
![image](https://user-images.githubusercontent.com/37010763/80193546-934a2300-864b-11ea-9d93-c36fc9f29a8d.png)
## work
![image](https://user-images.githubusercontent.com/37010763/80193599-b1178800-864b-11ea-8be0-e3c41b577666.png)

**Comment by sunhailin-Leo** [comment]
@ChicoXYC 
* Check your data again, or you can use Pycharm to run it again.

**Comment by chfw** [comment]
Please use ‘tolist()’ After index and value

**Comment by chenjiandongx** [comment]
https://pyecharts.org/#/zh-cn/data_format

**Comment by ChicoXYC** [comment]
> Please use ‘tolist()’ After index and value

This works, thanks!
