### ISSUE TITLE
TooltipOpts与legend不一致问题

### ISSUE THREAD

**Issue by wendaomudong** [pyecharts/pyecharts#1605]
**问题**
hi，请教问题，两条折线图，legends一个是圆圈一个是三角，提示框都是圆圈，颜色是一致的，但是形状不一样，这个可以调整吗？看了历史的issues，好像可以在add_yaxis中通过tooltip_opts进行修改，但是没有找到相关case。
谢谢，pyecharts很好用！！！

**运行环境（系统环境及 pyecharts 版本）**
python 3.7.0
pyecharts 1.6.2

**代码及截图**
```
demo = [1,2,3,4,5]
line1 = (
    Line().add_xaxis(
        xaxis_data=demo)
    .add_yaxis(
            "A",
            [i+1 for i in demo],
            is_symbol_show=True,
            label_opts=opts.LabelOpts(is_show=False)).
    add_yaxis(
        "B",
        [i+3 for i in demo],
        is_symbol_show=True,
        label_opts=opts.LabelOpts(is_show=False),
        symbol=
        "triangle"  #设置点的形状'circle', 'rect', 'roundRect', 'triangle', 'diamond', 'pin', 'arrow', 'none'"rect"
    )
    .set_colors(colors=["black", "red"]).set_global_opts(
        legend_opts=opts.LegendOpts(pos_right="10%",
                                    pos_top="20%",
                                    orient="vertical")  # 设置图例
        ,tooltip_opts=opts.TooltipOpts(trigger='axis',
                                      axis_pointer_type='cross')))
line1.render_notebook()
```

![image](https://user-images.githubusercontent.com/27725327/80307281-9a636380-87fa-11ea-8f6a-3aa5ee8bd1d1.png)

**Comment by wendaomudong** [comment]
![image](https://user-images.githubusercontent.com/27725327/80307403-76ece880-87fb-11ea-93d5-39c24dc2b878.png)

**Comment by sunhailin-Leo** [comment]
@wendaomudong 
* 哪里不一致？
* 提示框里面的圆点是提示颜色，和颜色无关。

**Comment by wendaomudong** [comment]
> @wendaomudong
> 
> * 哪里不一致？
> * 提示框里面的圆点是提示颜色，和颜色无关。
之前是颜色不一致，后来通过` .set_colors(colors=["black", "red"])`搞定了
想问的是提示框里的圆点是否可以和图例保持统一，以我发的图片为例，希望提示框里的也是圆圈和三角形。
谢谢回复~

**Comment by wendaomudong** [comment]
@sunhailin-Leo
