### ISSUE TITLE
表格组件Table-如果表格数据量太大，如何做分页显示？

### ISSUE THREAD

**Issue by jience** [pyecharts/pyecharts#1608]
**问题**
表格组件Table-如果表格数据量太大，如何做分页显示？

**运行环境（系统环境及 pyecharts 版本）**
python 3.6
pyecharts==1.7.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@jience 
* 目前暂时没考虑分页插件的问题

**Comment by allwell997** [comment]
表格的全球参数在哪里啊？

**Comment by allwell997** [comment]
比如行距，框的颜色等

**Comment by sunhailin-Leo** [comment]
@allwell997 
* 目前表格的样式都是通过内置的 css 去设置，没有提供上层的 api 进行配置
