### ISSUE TITLE
保存很麻烦

### ISSUE THREAD

**Issue by metheway** [pyecharts/pyecharts#1609]
**问题**
难以保存，一定装selenium包才能保存图片。然后要装chromedriver并配置。本来只是用这个工具画图的，但是这样单独为保存添加个依赖很麻烦

**运行环境（系统环境及 pyecharts 版本）**
macos 10.12.6

pyecharts最新版本
最新版本

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@metheway 
* 觉得麻烦的可以用 ToolBoxOpts
* Ps: 你有什么觉得不麻烦的方式推荐下？

**Comment by chfw** [comment]
保存图片还有一个snapshot-pupeteeer,试过没有？
