### ISSUE TITLE
生成的图表如何能够实现图表大小随着浏览器宽高缩放而自动调节呢?

### ISSUE THREAD

**Issue by RSF45355382** [pyecharts/pyecharts#1611]
**问题**
生成的图表如何能够实现图表大小随着浏览器宽高缩放而自动调节呢?

**运行环境（系统环境及 pyecharts 版本）**
windows 10

**代码及截图**
使用InitOpts(width='Auto',height='Auto')
或者InitOpts(width='0px',height='0px')
均不能实现功能

**Comment by sunhailin-Leo** [comment]
https://github.com/pyecharts/pyecharts/pull/1602
