### ISSUE TITLE
GRID 组件中背景颜色参数无效

### ISSUE THREAD

**Issue by leohazy** [pyecharts/pyecharts#1614]
**问题**
GRID 组件中背景颜色参数无效
Grid(init_opts=opts.InitOpts(bg_color='#333333'))
bg_color参数无法设置背景颜色，theme可用。

**运行环境（系统环境及 pyecharts 版本）**
1.7.1

**代码及截图**
from pyecharts import options as opts
from pyecharts.charts import Bar, Grid, Line
from pyecharts.faker import Faker

bar = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(title_opts=opts.TitleOpts(title="Grid-Bar"))
)
line = (
    Line()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Grid-Line", pos_top="48%"),
        legend_opts=opts.LegendOpts(pos_top="48%"),
    )
)

grid = (
    Grid(init_opts=opts.InitOpts(bg_color='#333333'))
    .add(bar, grid_opts=opts.GridOpts(pos_bottom="60%"))
    .add(line, grid_opts=opts.GridOpts(pos_top="60%"))
    .render("grid_vertical.html")
)

**Comment by sunhailin-Leo** [comment]
@leohazy 
* 目前折衷的解决办法就是在 Grid 的子图里面设置颜色

**Comment by suzhenxiang** [comment]
@sunhailin-Leo Grid 的子图里怎么设置？

**Comment by suzhenxiang** [comment]
@sunhailin-Leo ok,got it ,thanks
