### ISSUE TITLE
Timeline Stacked Bar数据残留

### ISSUE THREAD

**Issue by lianyouli** [pyecharts/pyecharts#1617]
**问题**
将Stacked Bar加入Timeline中，有些数据是其他Stacked Bar残留过来的。即Legend中显示是正确的，但是Bar中有不属于它自己的数据。

**运行环境（系统环境及 pyecharts 版本）**
Python 3.7.3
Pyecharts 1.7.0

**代码及截图**
<img width="908" alt="image" src="https://user-images.githubusercontent.com/38270502/81497949-863c5d80-92f4-11ea-9647-6ae4dc6baa98.png">

```python
from pyecharts import options as opts
from pyecharts.charts import Bar, Timeline
from pyecharts.faker import Faker
import random

x = Faker.choose()
tl = Timeline()

for i in range(2010, 2014):	
	bar = Bar(init_opts=opts.InitOpts(chart_id=str(i)))
	bar.add_xaxis(x)
	for j in range(0, random.randint(2, 5)):
		y_data = Faker.values()
		print(i, j, y_data, sum(y_data))
		bar.add_yaxis("商家" + str(j), y_data, stack="AAA", category_gap="50%")

	bar.set_global_opts(title_opts=opts.TitleOpts("某商店{}年营业额".format(i)))
	tl.add(bar, "{}年".format(i))
    
tl.render("timeline_bar5.html")
```

**Comment by lianyouli** [comment]
出现此问题时，print显示的数据：
2010 0 [55, 115, 106, 110, 41, 115, 54] 596
2010 1 [29, 28, 67, 110, 33, 121, 70] 458
2010 2 [100, 56, 90, 24, 81, 35, 53] 439
2010 3 [58, 65, 96, 53, 30, 59, 96] 457
2011 0 [52, 55, 136, 134, 108, 113, 34] 632
2011 1 [120, 86, 88, 74, 121, 90, 134] 713
2012 0 [47, 67, 132, 112, 133, 88, 91] 670
2012 1 [89, 77, 87, 104, 46, 36, 102] 541
2012 2 [123, 111, 36, 135, 144, 66, 56] 671
2012 3 [20, 131, 30, 67, 105, 39, 87] 479
2013 0 [45, 71, 80, 135, 80, 44, 69] 524
2013 1 [44, 129, 136, 35, 101, 56, 108] 609
2013 2 [132, 147, 65, 77, 24, 23, 28] 496
2013 3 [142, 70, 125, 70, 106, 22, 74] 609
2013 4 [150, 110, 136, 77, 146, 105, 123] 847

以及对应的问题gif录屏
![timeline_bar_issue](https://user-images.githubusercontent.com/38270502/81498253-6f970600-92f6-11ea-9279-0c18b36f4e2d.gif)

**Comment by sunhailin-Leo** [comment]
* Same as https://github.com/pyecharts/pyecharts/issues/1606
