### ISSUE TITLE
文本组件或指标卡组件显示方案求助

### ISSUE THREAD

**Issue by mathdogggg** [pyecharts/pyecharts#1618]
**问题**
新手求问，pyecharts是否支持文本组件或者指标卡组件显示方案，查阅gallery和文档，暂未找到可行的方案，还请各位大佬点拨一下。

**运行环境（系统环境及 pyecharts 版本）**
python3.7

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@mathdogggg 
* Echarts 里面叫什么？

**Comment by mathdogggg** [comment]
> @mathdogggg
> 
> * Echarts 里面叫什么？

好像没有官方的样例，有看到一个社区例子，链接：https://gallery.echartsjs.com/editor.html?c=xS13jKRESe

**Comment by sunhailin-Leo** [comment]
@mathdogggg 
* Graphic 组件有， 文档有 demo

**Comment by mathdogggg** [comment]
> @mathdogggg
> 
> * Graphic 组件有， 文档有 demo

在gallery里找到graphic组件了，我再研究一下具体的用法，感谢！
