### ISSUE TITLE
y轴数据没有自动减少数据点的显示

### ISSUE THREAD

**Issue by kopes18** [pyecharts/pyecharts#1619]
**问题**
如下两张图，配置参数相同，is_symbol_show 都是 True，为什么第二张图数据点没有抽样展示？

**代码及截图**
![image](https://user-images.githubusercontent.com/2020442/81666328-79df0e80-9474-11ea-855c-b916188e2f38.png)

**Comment by sunhailin-Leo** [comment]
@kopes18 
* 上下两张图的数据都是一样的吗？

**Comment by kopes18** [comment]
> @kopes18
> 
> * 上下两张图的数据都是一样的吗？

数据不一样，我记得如果数据多的时候点不会全部显示出来。

**Comment by hdzys** [comment]
我与你遇到的问题一样，不知道什么情况，啊哈哈
