### ISSUE TITLE
fork并修改了pyecharts然后支持了Python3.5

### ISSUE THREAD

**Issue by sailist** [pyecharts/pyecharts#1622]
**问题**

因我用的服务器无权限没法升级，所以fork了一下把不支持3.5的语法修改了一下，[fork后repo链接](https://github.com/sailist/pyecharts)。因为大部分都是类型提示，所以到主分支肯定不行，所以另上传了一个库叫pyechart35。没有测试，语法特性修改后，暂时没发现运行时错误。

安装的话使用：pip install pyechart35

更改的只有库名，内部使用理论上和原repo相同。

或许可以给使用Python3.5环境的朋友提供一些帮助。: )

**运行环境（系统环境及 pyecharts 版本）**

Python3.5+（修改版本1.7.1）

**Comment by sunhailin-Leo** [comment]
@sailist 
* Type hints 本身就是对开发者友好的东西，去掉了没有任何的好处。
* 始终建议升级到 Python 3.6 以上版本

**Comment by sailist** [comment]
是的...临时折中的法子，过两年等我有服务器权限我肯定要升级的
