### ISSUE TITLE
Tab功能是否支持折叠后下拉选项

### ISSUE THREAD

**Issue by RangerinDarkWoods** [pyecharts/pyecharts#1626]
Tab或timeline功能是否支持折叠后下拉选项后展示不同图表（比如K线图下拉选择叠加若干个技术指标），若不支持，后续是否可以实现？个人如果要做的话该怎么做，难度如何？

**Comment by sunhailin-Leo** [comment]
I'm not sure what the features are you describing.

**Comment by RangerinDarkWoods** [comment]
> I'm not sure what the features are you describing.
> @RangerinDarkWoods

Just like [this:](http://quote.eastmoney.com/sh600276.html)
https://user-images.githubusercontent.com/65518441/82396681-1b6fec80-9a81-11ea-9aad-c2f1df418513.png

**Comment by sunhailin-Leo** [comment]
@RangerinDarkWoods 
* That is the frontend should be developed, not us.
