### ISSUE TITLE
水球图

### ISSUE THREAD

**Issue by leohazy** [pyecharts/pyecharts#1627]
**问题**
现在的版本是否无法绘制这个图，https://gallery.echartsjs.com/editor.html?c=xtnmUAK2r

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

https://gallery.echartsjs.com/editor.html?c=xtnmUAK2r
![image](https://user-images.githubusercontent.com/6706396/82402525-2cbff580-9a8f-11ea-8803-446dfa10ba51.png)

**Comment by leohazy** [comment]
主要是水球图的backgroundStyle，outline等属性没有

**Comment by sunhailin-Leo** [comment]
@leohazy 
* Got it！

**Comment by sunhailin-Leo** [comment]
* Please Update New Version, thx
