### ISSUE TITLE
china-cities 地图缺少南海诸岛

### ISSUE THREAD

**Issue by jasonshike** [pyecharts/pyecharts#1633]
**问题**
china-cities 地图缺少南海诸岛

**运行环境（系统环境及 pyecharts 版本）**
Windows 10
pyecharts 1.7.1

**代码及截图**
![image](https://user-images.githubusercontent.com/38620881/83134888-97b89e80-a117-11ea-8cfe-9a2bffa2aa45.png)

**Comment by sunhailin-Leo** [comment]
这个地图的 js 文件也是网上找别做好的，要加南海诸岛得通过 mapbox 去重新 diy 一下。这方面暂时没办法搞定
