### ISSUE TITLE
仪表图添加两个指针, 但是图中间总是会显示第一个指针的名称, 如何取消这个显示 ?

### ISSUE THREAD

**Issue by iamczy** [pyecharts/pyecharts#1634]
![image](https://user-images.githubusercontent.com/32157786/83474317-4b29e600-a4be-11ea-9166-f253f2c2c6e5.png)
如何取消"语文"这两个字呢 ? 
谢谢啦 ~

**Comment by iamczy** [comment]
两根指针就有烦

**Comment by sunhailin-Leo** [comment]
@iamczy 
* 现在版本还不支持修改 detail 和 center 的 `offsetCenter` 参数。
* 下个版本更新～

**Comment by sunhailin-Leo** [comment]
* Please Update New Version, thx
