### ISSUE TITLE
在jupyter-lab v2.1.4 其他主题情况下， chalk 等主题失效

### ISSUE THREAD

**Issue by WuQianyong** [pyecharts/pyecharts#1635]
**问题**
在jupyter-lab  的  jupyterlab-solarized-dark 主题下，除了dark 主题生效，但其他主题 可能没有生效，例如 chalk。

这是原色没有加主题的效果
![image](https://user-images.githubusercontent.com/12892724/83752363-0018fa00-a69b-11ea-909e-82e3bf634fd4.png)

这是加了 light 主题效果
![image](https://user-images.githubusercontent.com/12892724/83752439-22127c80-a69b-11ea-8179-e0d2cc6b0f4b.png)

这是加了 dark 主题效果
![image](https://user-images.githubusercontent.com/12892724/83752547-48d0b300-a69b-11ea-9f87-1581465703eb.png)

这是加 chalk 主题
![image](https://user-images.githubusercontent.com/12892724/83752592-5ab25600-a69b-11ea-8627-c524e244b668.png)

可以看出 除了dark 和原始的效果不一样，其他主题可能没有生效

**运行环境（系统环境及 pyecharts 版本）**
mac os 10.14.6
pyecharts v1.7.1
jupyter-lab v2.1.4 
jupyterlab-server v1.1.5

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@WuQianyong 
* 部分主题的背景色默认都是透明的。
* 需要有背景色可以自行使用 background 参数或去 Echarts 自行定制主题
