### ISSUE TITLE
标题中嵌入的跳转链接失效

### ISSUE THREAD

**Issue by leohazy** [pyecharts/pyecharts#1639]
**问题**
标题中嵌入的跳转链接无法跳转了，我检查过自己的代码以及生成的html文件，链接都是存在并且语法正确的，目前链接都会跳转到undefine。 我在官网找了两个有跳转链接的示例，也无法打开跳转链接了，但是原链接实际上是可以访问的。
看到更新了版本，我进行了更新之后仍然不行。
猜测是否是更新了js的缘故？

**运行环境（系统环境及 pyecharts 版本）**
1.7.1
1.8.0

**代码及截图**
http://gallery.pyecharts.org/#/BMap/air_quality_baidu_map?id=pyecharts-%e4%bb%a3%e7%a0%81-%e6%95%88%e6%9e%9c
http://gallery.pyecharts.org/#/Map/population_density_of_HongKong_v2?id=pyecharts-%e4%bb%a3%e7%a0%81-%e6%95%88%e6%9e%9c

**Comment by sunhailin-Leo** [comment]
@leohazy
* show me your code

**Comment by leohazy** [comment]
> @leohazy
> 
> * show me your code
那两个官方示例的链接你可以打开试试，
![image](https://user-images.githubusercontent.com/6706396/83990497-77d97400-a97c-11ea-8296-f3887f9ab1b1.png)
链接：http://gallery.pyecharts.org/#/Map/population_density_of_HongKong_v2?id=pyecharts-%e4%bb%a3%e7%a0%81-%e6%95%88%e6%9e%9c
图示的文字处超链接应该是可以打开的，现在无法访问

**Comment by leohazy** [comment]
![image](https://user-images.githubusercontent.com/6706396/83990572-b96a1f00-a97c-11ea-8da2-699d44606632.png)
yi ji以及这一个的小标题超链接，http://www.pm25.in，是可以打开的
http://gallery.pyecharts.org/#/BMap/air_quality_baidu_map?id=pyecharts-%e4%bb%a3%e7%a0%81-%e6%95%88%e6%9e%9c

**Comment by leohazy** [comment]
另外发现pie图应该有labelLine参数，但是set_series_opts中没有

**Comment by sunhailin-Leo** [comment]
@leohazy
* 我这边测试没问题，不清楚你的浏览器出现了什么问题。

**Comment by sunhailin-Leo** [comment]
@leohazy 
* labelLine 参数还没加

**Comment by sunhailin-Leo** [comment]
@leohazy 
* undefined 的问题，建议你弄到本地进行测试
