### ISSUE TITLE
多Y轴图表extend_axis和yaxis_index是怎么个对应关系，没看懂

### ISSUE THREAD

**Issue by mjb0331** [pyecharts/pyecharts#1643]
多坐标轴的对应关系到底是怎么样子的，看了半天也没看懂。逻辑有些混乱啊
extend_axis和yaxis_index到底是怎么对应的？

**Comment by sunhailin-Leo** [comment]
@mjb0331 
* 实在不理解的，去看一下 【pyecharts 浅入浅出】 的知乎专栏 ，里面有一篇文章讲了这个对应关系。
