### ISSUE TITLE
PictorialBar 和 Timeline 使用Bug

### ISSUE THREAD

**Issue by 295603331** [pyecharts/pyecharts#1645]
**问题**
使用 PictorialBar 和 Timeline时，显示有Bug
当构造排序列表时，两个list 排序在同一位置时，

不会刷新 Label显示
比如
x_Data_1 = ['A','B','C','D']
x_Data_2 = ['A','C','D','B']
y_Data_1 = [1,2,3,4]
y_Data_2 = [3,3,2,1]

x_Data_1[0] 和 x_Data_2[0] 位置均为 A
y_Data_1[0]=1
y_Data_2[0]=3

只要这个排序位置不动，就不会刷新显示

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.8.1
python 3.7.6
Win10 1909 
Chrome 80.0.3970.5
**代码及截图**

from pyecharts.charts import PictorialBar,Timeline
from pyecharts.globals import SymbolType

x_Data_1 = ['A','B','C','D']

x_Data_2 = ['A','C','D','B']

x_Data_3 = ['A','B','D','C']

y_Data_1 = [1,2,3,4]

y_Data_2 = [3,3,2,1]

y_Data_3 = [2,2,1,2]

tl = Timeline(
    init_opts=opts.InitOpts()
    )

for titleStr,x_data,y_data in zip(
    ['1','2','3'],
    [x_Data_1,x_Data_2,x_Data_3],
    [y_Data_1,y_Data_2,y_Data_3]
):

    PicBar = PictorialBar()

    PicBar.add_xaxis(
        xaxis_data = x_data
    )

    PicBar.add_yaxis(
        series_name='任务完成率',
        y_axis = y_data,
            symbol_size=18,
            symbol_repeat="fixed",
            symbol_offset=[0, 0],
            is_symbol_clip=True,
            symbol=SymbolType.ROUND_RECT        
        )
    PicBar.reversal_axis()
    tl.add(PicBar,'{}'.format(titleStr))

tl.render(r'D:\dd.html')

**Comment by sunhailin-Leo** [comment]
@295603331 
* 把你的代码重新 Format 一下，使其满足 markdown 的最佳展现形式。

**Comment by sunhailin-Leo** [comment]
@295603331 
* 我这边测试没有问题
```python
from random import randint

from pyecharts import options as opts
from pyecharts.charts import PictorialBar, Timeline
from pyecharts.globals import SymbolType

location = ["山西", "四川", "西藏", "北京", "上海", "内蒙古", "云南", "黑龙江", "广东", "福建"]


tl = Timeline()
for i in range(2015, 2020):
    pb = (
        PictorialBar()
        .add_xaxis(location)
        .add_yaxis(
            "",
            [randint(10, 300) for _ in range(10)],
            label_opts=opts.LabelOpts(is_show=False),
            symbol_size=18,
            symbol_repeat="fixed",
            symbol_offset=[0, 0],
            is_symbol_clip=True,
            symbol=SymbolType.ROUND_RECT,
        )
        .reversal_axis()
            .set_global_opts(
            title_opts=opts.TitleOpts(title="PictorialBar-各省份人口数量（虚假数据）"),
            xaxis_opts=opts.AxisOpts(is_show=False),
            yaxis_opts=opts.AxisOpts(
                axistick_opts=opts.AxisTickOpts(is_show=False),
                axisline_opts=opts.AxisLineOpts(
                    linestyle_opts=opts.LineStyleOpts(opacity=0)
                ),
            ),
        )
    )
    tl.add(pb, "{}年".format(i))
tl.render("timeline_pictorialbar.html")
```

**Comment by 295603331** [comment]
试试将label_opts设置为True，显示的label翻页不会变化
label_opts=opts.LabelOpts(is_show=True,position='inside')
<pre>
from random import randint

from pyecharts import options as opts
from pyecharts.charts import PictorialBar, Timeline
from pyecharts.globals import SymbolType

location = ["山西", "四川", "西藏", "北京", "上海", "内蒙古", "云南", "黑龙江", "广东", "福建"]


tl = Timeline()
for i in range(2015, 2020):
    pb = (
        PictorialBar()
        .add_xaxis(location)
        .add_yaxis(
            "",
            [randint(10, 300) for _ in range(10)],
            label_opts=opts.LabelOpts(is_show=True,position='inside'),
            symbol_size=18,
            symbol_repeat="fixed",
            symbol_offset=[0, 0],
            is_symbol_clip=True,
            symbol=SymbolType.ROUND_RECT,
        )
        .reversal_axis()
            .set_global_opts(
            title_opts=opts.TitleOpts(title="PictorialBar-各省份人口数量（虚假数据）"),
            xaxis_opts=opts.AxisOpts(is_show=False),
            yaxis_opts=opts.AxisOpts(
                axistick_opts=opts.AxisTickOpts(is_show=False),
                axisline_opts=opts.AxisLineOpts(
                    linestyle_opts=opts.LineStyleOpts(opacity=0)
                ),
            ),
        )
    )
    tl.add(pb, "{}年".format(i))
tl.render(r"D:\timeline_pictorialbar.html")
</pre>

**Comment by 295603331** [comment]
@sunhailin-Leo 

条形图长度已变化，但是label显示没变

![tab1](https://user-images.githubusercontent.com/50265417/86592982-fb5fa280-bfc6-11ea-96c1-8745a872bd5e.png)
![tab2](https://user-images.githubusercontent.com/50265417/86592988-fdc1fc80-bfc6-11ea-87bc-9ebad45a5a4c.png)

**Comment by sunhailin-Leo** [comment]
@295603331 
* Echarts Bug: https://github.com/apache/incubator-echarts/issues/11584

**Comment by 295603331** [comment]
@sunhailin-Leo 
了解了 感谢
