### ISSUE TITLE
我半年前用pyecharts做的东西，现在要全部重写了。。。。。少来点大的改动啊。。。

### ISSUE THREAD

**Issue by lemonlife2333** [pyecharts/pyecharts#1646]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@lemonlife2333 
* 半年前跟现在的版本除了少部分参数，名字修改了；大部分都是新增参数，不理解你全部重写是什么意思。

**Comment by lemonlife2333** [comment]
我记得以前我当初写的时候，实例化的时候可以直接传title这些参数，现在是需要调ops里的对应设置写了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LeoSun"<notifications@github.com&gt;; 
发送时间: 2020年6月18日(星期四) 凌晨2:23
收件人: "pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;; 
抄送: "."<316003993@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [pyecharts/pyecharts] 我半年前用pyecharts做的东西，现在要全部重写了。。。。。少来点大的改动啊。。。 (#1646)





 
@lemonlife2333
  
半年前跟现在的版本除了少部分参数，名字修改了；大部分都是新增参数，不理解你全部重写是什么意思。
