### ISSUE TITLE
无法通过image://URL的形式修改node的symbol

### ISSUE THREAD

**Issue by 4thfever** [pyecharts/pyecharts#1650]
**问题**
我试图用外加的image来替换原本的node的symbol，但是没有成功，修改symbol的代码如下：

```
node_symbol='image://svg/transformer.png'
node = opts.GraphNode(
                    name = ‘123’,
                    value = 123,
                    symbol = node_symbol,
                    symbol_size = 20
                )
```

图片使用Flask从本地生成URL的：

```
@app.route("/svg/<path:path>")
def return_svg(path):
    return '<img src=' + url_for('static',filename=path) + '>'
```

**运行环境（系统环境及 pyecharts 版本）**
Python 3.7
pyecharts 1.8.1

**代码及截图**
图一：红圈处是应当有但是没有symbol的图像
<img width="280" alt="err1" src="https://user-images.githubusercontent.com/19970391/85518885-5098cd00-b633-11ea-8742-32ff0951b948.png">
图二：在chrome-F12-network的preview中看不到预加载的图像
<img width="490" alt="err2" src="https://user-images.githubusercontent.com/19970391/85518790-36f78580-b633-11ea-85ad-3d727a152928.png">
图三：双击url打开，可以看到加载出来的图像
<img width="317" alt="err3" src="https://user-images.githubusercontent.com/19970391/85518799-38c14900-b633-11ea-85ae-1cef22cd600e.png">

全部的详细代码存在了我的github仓库中：https://github.com/4thfever/AIDispatch

期待解答，同时感谢提供了pyecharts这种工具，谢谢 ：）

**Comment by sunhailin-Leo** [comment]
@4thfever 
* 应该考虑是否与静态资源路径层级有关。

**Comment by 4thfever** [comment]
请问是否有用到类似功能的样例？我在gallery里没有搜到

**Comment by sunhailin-Leo** [comment]
@4thfever 
* Try this : `node_symbol=JsCode('image://svg/transformer.png')`

**Comment by 4thfever** [comment]
找到问题了，是Flask建立图片url的问题。非常感谢回复！
资助了一杯咖啡钱，钱不多只能喝杯瑞幸，见谅
