### ISSUE TITLE
TreeMap.add和官网配置不一样，没有levels属性

### ISSUE THREAD

**Issue by CalvinJulo** [pyecharts/pyecharts#1651]
**问题**
pyecharts官网中的treemap案例无法实现，在设置过程中发现treemap的配置和教程写得不一样。请问新的配置教程在哪里？特别是levels的配置

**运行环境（系统环境及 pyecharts 版本）**

Mac，Python 3.6.2，Pyecharts 1.7.0

**代码及截图**
![image](https://user-images.githubusercontent.com/21016236/85918393-f6974200-b894-11ea-884b-1f5ec87af8bf.png)

**Comment by sunhailin-Leo** [comment]
@CalvinJulo 
* Doc is here： https://pyecharts.org/#/zh-cn/tree_charts?id=treemap%ef%bc%9a%e7%9f%a9%e5%bd%a2%e6%a0%91%e5%9b%be
![image](https://user-images.githubusercontent.com/17564655/86526059-b30a8c80-bec1-11ea-8ef0-fb59d035eec1.png)
