### ISSUE TITLE
pyecharts.charts.Graph 画不出节点自己对自己的关系的线

### ISSUE THREAD

**Issue by jacobicao** [pyecharts/pyecharts#1654]
**问题**
pyecharts.charts.Graph 画不出节点自己对自己的关系的线。
edge = [["a","b"],["a","a"]]

**运行环境（系统环境及 pyecharts 版本）**
win7专业版
Python 3.7.3
pyecharts 1.6.2

**代码及截图**

**Comment by sunhailin-Leo** [comment]
![image](https://user-images.githubusercontent.com/17564655/86578136-e75b7700-bfad-11ea-89b3-0d1499c199d6.png)
![image](https://user-images.githubusercontent.com/17564655/86578159-f3dfcf80-bfad-11ea-9006-693faa0a1a09.png)

**Comment by jacobicao** [comment]
我意思是，节点1能有一个线，转个弯，指向自己。
