### ISSUE TITLE
在network的图里面如何实现鼠标点击某一个节点，实现跳转到一个页面（html link）的功能？

### ISSUE THREAD

**Issue by shenwanxiang** [pyecharts/pyecharts#1655]
**问题**
我希望在我的network图中， hover是出现节点属性（这个可以实现），然后如果点击，就跳转到一个网站 比如 “www.baidu.com”

**运行环境（系统环境及 pyecharts 版本）**

Ubuntu 18.04
pyecharts==1.8.1

**代码及截图**
![image](https://user-images.githubusercontent.com/21102929/86375727-a9620880-bcb8-11ea-998d-5793575d1175.png)

代码如下
```
from pyecharts import options as opts
from pyecharts.charts import Graph

nodes = [
    {"name": "Physicochemical Property", "symbolSize": 100},
    {"name": "<a href='www.baidu.com'>Absorption</a>", "symbolSize": 100},  #"name": "Camel3942", "symbolSize": 5, "draggable": "False", "value": 1, "category": "Camel3942","label": {"normal": {"show": "True"}
    {"name": "Distribution", "symbolSize": 100},
    {"name": "Metabolism", "symbolSize": 100},
    {"name": "Excretion", "symbolSize": 100},
    {"name": "Toxicity", "symbolSize": 100},
    {"name": "Activity", "symbolSize": 100},]



links = []
for i in nodes:
    for j in nodes[:3]:
        links.append({"source": i.get("name"), "target": j.get("name")})

    

g = Graph(init_opts=opts.InitOpts(width="1000px", height="600px"))

g.add("", nodes, links, repulsion=8000)
g.set_global_opts(title_opts=opts.TitleOpts(title="Graph-基本示例"))
g.render("graph_base.html")
```

**Comment by shenwanxiang** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Awesome-pyecharts</title>
            <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>

</head>
<body>
    <div id="e20516edeb4746ef8872aaa1d402f232" class="chart-container" style="width:1000px; height:600px;"></div>
    <script>
        var chart_e20516edeb4746ef8872aaa1d402f232 = echarts.init(
            document.getElementById('e20516edeb4746ef8872aaa1d402f232'), 'white', {renderer: 'canvas'});
        var option_e20516edeb4746ef8872aaa1d402f232 = {
    "animation": true,
    "animationThreshold": 2000,
    "animationDuration": 1000,
    "animationEasing": "cubicOut",
    "animationDelay": 0,
    "animationDurationUpdate": 300,
    "animationEasingUpdate": "cubicOut",
    "animationDelayUpdate": 0,
    "color": [
        "#c23531",
        "#2f4554",
        "#61a0a8",
        "#d48265",
        "#749f83",
        "#ca8622",
        "#bda29a",
        "#6e7074",
        "#546570",
        "#c4ccd3",
        "#f05b72",
        "#ef5b9c",
        "#f47920",
        "#905a3d",
        "#fab27b",
        "#2a5caa",
        "#444693",
        "#726930",
        "#b2d235",
        "#6d8346",
        "#ac6767",
        "#1d953f",
        "#6950a1",
        "#918597"
    ],
    "series": [
        {
            "type": "graph",
            "layout": "force",
            "symbolSize": 10,
            "circular": {
                "rotateLabel": false
            },
            "force": {
                "repulsion": 8000,
                "edgeLength": 50,
                "gravity": 0.2
            },
            "label": {
                "show": true,
                "position": "top",
                "margin": 8
            },
            "lineStyle": {
                "show": true,
                "width": 1,
                "opacity": 1,
                "curveness": 0,
                "type": "solid"
            },
            "roam": true,
            "draggable": false,
            "focusNodeAdjacency": true,
            "data": [
                {
                    "name": "Physicochemical Property",
                    "symbolSize": 100
                },
                {
                    "name": "<a href='www.baidu.com'>Absorption</a>",
                    "symbolSize": 100
                },
                {
                    "name": "Distribution",
                    "symbolSize": 100
                },
                {
                    "name": "Metabolism",
                    "symbolSize": 100
                },
                {
                    "name": "Excretion",
                    "symbolSize": 100
                },
                {
                    "name": "Toxicity",
                    "symbolSize": 100
                },
                {
                    "name": "Activity",
                    "symbolSize": 100
                }
            ],
            "edgeLabel": {
                "show": false,
                "position": "top",
                "margin": 8
            },
            "edgeSymbol": [
                null,
                null
            ],
            "edgeSymbolSize": 10,
            "links": [
                {
                    "source": "Physicochemical Property",
                    "target": "Physicochemical Property"
                },
                {
                    "source": "Physicochemical Property",
                    "target": "<a href='www.baidu.com'>Absorption</a>"
                },
                {
                    "source": "Physicochemical Property",
                    "target": "Distribution"
                },
                {
                    "source": "<a href='www.baidu.com'>Absorption</a>",
                    "target": "Physicochemical Property"
                },
                {
                    "source": "<a href='www.baidu.com'>Absorption</a>",
                    "target": "<a href='www.baidu.com'>Absorption</a>"
                },
                {
                    "source": "<a href='www.baidu.com'>Absorption</a>",
                    "target": "Distribution"
                },
                {
                    "source": "Distribution",
                    "target": "Physicochemical Property"
                },
                {
                    "source": "Distribution",
                    "target": "<a href='www.baidu.com'>Absorption</a>"
                },
                {
                    "source": "Distribution",
                    "target": "Distribution"
                },
                {
                    "source": "Metabolism",
                    "target": "Physicochemical Property"
                },
                {
                    "source": "Metabolism",
                    "target": "<a href='www.baidu.com'>Absorption</a>"
                },
                {
                    "source": "Metabolism",
                    "target": "Distribution"
                },
                {
                    "source": "Excretion",
                    "target": "Physicochemical Property"
                },
                {
                    "source": "Excretion",
                    "target": "<a href='www.baidu.com'>Absorption</a>"
                },
                {
                    "source": "Excretion",
                    "target": "Distribution"
                },
                {
                    "source": "Toxicity",
                    "target": "Physicochemical Property"
                },
                {
                    "source": "Toxicity",
                    "target": "<a href='www.baidu.com'>Absorption</a>"
                },
                {
                    "source": "Toxicity",
                    "target": "Distribution"
                },
                {
                    "source": "Activity",
                    "target": "Physicochemical Property"
                },
                {
                    "source": "Activity",
                    "target": "<a href='www.baidu.com'>Absorption</a>"
                },
                {
                    "source": "Activity",
                    "target": "Distribution"
                }
            ]
        }
    ],
    "legend": [
        {
            "data": [],
            "selected": {},
            "show": true,
            "padding": 5,
            "itemGap": 10,
            "itemWidth": 25,
            "itemHeight": 14
        }
    ],
    "tooltip": {
        "show": true,
        "trigger": "item",
        "triggerOn": "mousemove|click",
        "axisPointer": {
            "type": "line"
        },
        "showContent": true,
        "alwaysShowContent": false,
        "showDelay": 0,
        "hideDelay": 100,
        "textStyle": {
            "fontSize": 14
        },
        "borderWidth": 0,
        "padding": 5
    },
    "title": [
        {
            "text": "Graph-\u57fa\u672c\u793a\u4f8b",
            "padding": 5,
            "itemGap": 10
        }
    ]
};
        chart_e20516edeb4746ef8872aaa1d402f232.setOption(option_e20516edeb4746ef8872aaa1d402f232);
    </script>
</body>
</html>

**Comment by jacobicao** [comment]
非常有用的功能，期望看到解决方案~

**Comment by shenwanxiang** [comment]
> 非常有用的功能，期望看到解决方案~

我用js实现了，但是怎么区分 鼠标点击 和鼠标飘过 这两个事件：

如果我做两次 set_global_opts， 则第二个会覆盖第一个


```
from pyecharts import options as opts
from pyecharts.charts import Graph
from pyecharts.commons.utils import JsCode

nodes = [
    {"name": "Physicochemical Property", "symbolSize": 100, 'sites': '123', 'value': ['http://www.baidu.com', 'properties, click me for more details']},
    {"name": "Absorption", "symbolSize": 100},  #"name": "Camel3942", "symbolSize": 5, "draggable": "False", "value": 1, "category": "Camel3942","label": {"normal": {"show": "True"}
    {"name": "Distribution", "symbolSize": 100},
    {"name": "Metabolism", "symbolSize": 100},
    {"name": "Excretion", "symbolSize": 100},
    {"name": "Toxicity", "symbolSize": 100},
    {"name": "Activity", "symbolSize": 100},]



links = []
for i in nodes:
    for j in nodes[:3]:
        links.append({"source": i.get("name"), "target": j.get("name")})

    

g = Graph(init_opts=opts.InitOpts(width='150%', height='150%'))

g.add("", nodes, links, repulsion=10000)
g.set_global_opts(title_opts=opts.TitleOpts(title="Graph-基本示例"),
                 
             
                tooltip_opts=opts.TooltipOpts(
                                is_show=True,
                                trigger_on = 'click',
                                formatter= JsCode( 
                                    """function (params) {
                                       
                                       window.location.href = params.value[0];
                                   }"""
                                
                                ))) 



g.set_global_opts( tooltip_opts=opts.TooltipOpts(
                                is_show=True,
                                trigger_on = 'mousemove',
                                formatter= JsCode( 
                                    """function (params) {
                                       return params.name;
                                   }"""
                                
                                ))) 




g.render("graph_base.html")

```

**Comment by sunhailin-Leo** [comment]
@shenwanxiang @jacobicao 
```python
from pyecharts import options as opts
from pyecharts.charts import Graph
from pyecharts.commons.utils import JsCode

nodes = [
    {"name": "Physicochemical Property", "symbolSize": 100, "url": "https://www.baidu.com"},
    {"name": "Absorption", "symbolSize": 100},
    {"name": "Distribution", "symbolSize": 100},
    {"name": "Metabolism", "symbolSize": 100},
    {"name": "Excretion", "symbolSize": 100},
    {"name": "Toxicity", "symbolSize": 100},
    {"name": "Activity", "symbolSize": 100},
]


links = []
for i in nodes:
    for j in nodes[:3]:
        links.append({"source": i.get("name"), "target": j.get("name")})


(
    Graph(init_opts=opts.InitOpts(width="1000px", height="600px"))
    .add("", nodes, links, repulsion=8000)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Graph-基本示例"),
        tooltip_opts=opts.TooltipOpts(
            is_show=True,
            trigger_on="click",
            formatter=JsCode("""
            function(params) {
                window.open(params.data.url);
                return params.name;
            }
            """)
        )
    )
    .render("graph_click.html")
)
```
