### ISSUE TITLE
ThemeRiver不会不能add到page里面吧。。报错了

### ISSUE THREAD

**Issue by SeepenL** [pyecharts/pyecharts#1656]
TR的代码用的就是gallery中的源代码，我把部分数据换成自己的了，想先看看效果，结果page这步报错了。。

报错信息：
    page_1.add(c3)
  File "C:\Users\Lzp\AppData\Local\Programs\Python\Python36\lib\site-packages\pyecharts\charts\composite_charts\page.py", line 71, in add
    for d in c.js_dependencies.items:
AttributeError: type object 'ThemeRiver' has no attribute 'js_dependencies'

**Comment by SeepenL** [comment]
啊，不好意思，我传参时传错了。。改了就好了。
没事了，感谢作者开发的强大工具。

**Comment by hevnet** [comment]
请问 遇到同样的问题 能否详细指导一下呢

**Comment by SeepenL** [comment]
我当时是犯了一个低级错误。。函数传参时直接传的是ThemeRiver类型而不是其实例。具体可参考我的这篇博文，可能会有帮助
https://blog.csdn.net/qq_39496504/article/details/107110718

hevnet <notifications@github.com> 于2020年7月7日周二 下午3:26写道：
