### ISSUE TITLE
前后端分离下由于 json 数据类型的问题使用 JSCode 进行画图的可能性

### ISSUE THREAD

**Issue by sorphwer** [pyecharts/pyecharts#1658]
开发者们您好，在pyecharts文档中http://pyecharts.org/#/zh-cn/web_flask 有以下说明：

>注: 目前由于 json 数据类型的问题，无法将 pyecharts 中的 JSCode 类型的数据转换成 json 数据格式返回到前端页面中使用。因此在使用前后端分离的情况下尽量避免使用 JSCode 进行画图。

部分类型的图均默认使用`JsCode`类进行画图(如`Bio`图)，在http://pyecharts.org/#/zh-cn/javascript 已写的很清楚，因此在使用返回的ajax绘制echarts的时候 `tooltips.formatter`会将JsCode字符串化，导致图中会直接显示代码。

我理解此情况是由于语言特性决定的，但在此提出一种不很优雅的解决方法，即通过JavaScript，在接收到Ajax回应后的success操作中覆写`tooltips.formatter`的值使其从字符串变成正确的可执行函数：

```JavaScript
eval('result.tooltip.formatter='+result.tooltip.formatter);
```

希望将其更新于文档与其示例中，以提供一种可行的解决方案。当然更期待pyecharts后续更新中考虑原生解决此问题。

测试使用的环境：Flask 1.1.2 + pyecharts 1.8.1 ，可以正常使用。

参考：https://echarts.apache.org/zh/option.html#tooltip.formatter

**Comment by sunhailin-Leo** [comment]
@sorphwer 
* 移步：https://pyecharts.org/#/zh-cn/faq
