### ISSUE TITLE
tab选项卡太多，能不能设置显示一行，进行翻页显示

### ISSUE THREAD

**Issue by zpf4934** [pyecharts/pyecharts#1659]
**问题**
tab选项卡比较多，默认是多行显示，导致占据页面空间较大，能不能设置只显示一行，如果一行无法全部显示可以进行翻页显示

**运行环境（系统环境及 pyecharts 版本）**
macOS
python3.7
pyecharts1.8.1

**代码及截图**
![image](https://user-images.githubusercontent.com/20162142/86529753-cc253480-bee5-11ea-99d7-68366706de6e.png)

**Comment by sunhailin-Leo** [comment]
@zpf4934 
* 这个问题涉及到前端的问题，目前没有继续开发优化的进度。
