### ISSUE TITLE
提问：散点图中可以在一个X标签上显示多个不同Y值吗的点?

### ISSUE THREAD

**Issue by yglpyn8888** [pyecharts/pyecharts#1662]
**问题**
我看echarts 是可以实现 一个X值 对应多个不同Y值的点显示
https://echarts.apache.org/examples/zh/editor.html?c=scatter-effect 这个例子就是
pyecharts中我试了显示不出来

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.8

**代码及截图**
from pyecharts import options as opts
from pyecharts.charts import Scatter
from pyecharts.commons.utils import JsCode
from pyecharts.faker import Faker
print(Faker.choose())
print([list(z) for z in zip(Faker.values(), Faker.choose())])
c = (
    Scatter()
    .add_xaxis(['0601', '0602', '0603', '0604'])
    .add_yaxis(

        "商家A",
        # [list(z) for z in zip(Faker.values(), Faker.choose())],
        [[137, '0601'], [51, '0602'], [29, '0603'],[39, '0603'], [75, '0604']],
        label_opts=opts.LabelOpts(
            position='inside',
            color='black',
            formatter=JsCode(
                "function(params){ "
                "if (params.value[1]>=40 && params.value[1]<=80) {"
                "return 'X'} else {return 'O'}}"
            )
        ),
        symbol_size=0.01
    )
    .set_global_opts(

        title_opts=opts.TitleOpts(title="Scatter-多维度数据"),
        tooltip_opts=opts.TooltipOpts(
            formatter=JsCode(
                "function (params) {return params.name + ' : ' + params.value[2];}"
            )
        ),
        visualmap_opts=opts.VisualMapOpts(
            type_="color", max_=150, min_=20, dimension=1
        ),
    )
    .render("scatter_multi_dimension.html")
)

![image](https://user-images.githubusercontent.com/48742492/87215382-ac1fc600-c368-11ea-8a0b-dd3f7667bda1.png)

**Comment by yglpyn8888** [comment]
为啥图没显示，，，不过代码很简单，能表达我什么意思

**Comment by chfw** [comment]
我也遇到这样的问题。我的解决方案是再 add_yaxis()。
比如：

data = [(x,y), (x,y1)]

我拆开

data1 = [(x,y)]
data2 = [(x,y1)]

然后分别 add_yaxis()

**Comment by chfw** [comment]
参考： https://github.com/pyecharts/pyecharts-extras#1-time-series-event
