### ISSUE TITLE
可能是BUG的问题：Kline图和line同属直角坐标系，但两者无法overlap

### ISSUE THREAD

**Issue by yglpyn8888** [pyecharts/pyecharts#1664]
**问题**
Kline图和bar/line同属直角坐标系，但两者无法overlap ，第二张图设置yaxis_index=1直接图出不来，去掉这个参数，画出的图y轴只有一个不满足需要。

**运行环境（系统环境及 pyecharts 版本）**

pyecharts1.8.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@yglpyn8888 
* http://gallery.pyecharts.org/#/Candlestick/professional_kline_brush
