### ISSUE TITLE
关于画图的一些问题

### ISSUE THREAD

**Issue by Vineyard-w** [pyecharts/pyecharts#1665]
**运行环境（系统环境及 pyecharts 版本）**
win10
![image](https://user-images.githubusercontent.com/33095707/87381151-99a2c800-c5c6-11ea-876b-f0b879964e9d.png)

**问题：**
有这样一份简单的数据：
![image](https://user-images.githubusercontent.com/33095707/87379595-39f6ed80-c5c3-11ea-913d-0f463f17d4d9.png)
显然"**月份**"这一字段的数据是连续的int型数据，如果直接使用如下代码运行：
```python
from pyecharts.charts import Line
import pyecharts.options as opts
x = list(train_data["月份"])
y1 = list(train_data["注册人数"])
y2 = list(train_data["激活人数"])
line = (Line()
        .add_xaxis(x)
        .add_yaxis("注册人数",y1,symbol = "arrow",symbol_size = 15,is_smooth = True)
        .add_yaxis("激活人数",y2)
        .set_global_opts(title_opts=opts.TitleOpts(title="注册人数&激活人数",subtitle ="我是副标题")))
line.render_notebook()
```

**运行结果如下：**

![image](https://user-images.githubusercontent.com/33095707/87380426-0a48e500-c5c5-11ea-80a2-1d5d7f608398.png)
从结果看出：折线图的最左端不是从1开始，而是从2开始，相当于索引值的第二个值，不得不做一些处理才能显示出想要的结果；

**以下是更改后的代码：**
```python
# 第一种：从数据上更改
from pyecharts.charts import Line
import pyecharts.options as opts
x = [str(i) for i in train_data["月份"]]
y1 = list(train_data["注册人数"])
y2 = list(train_data["激活人数"])
line = (Line()
        .add_xaxis(x)
        .add_yaxis("注册人数",y1,symbol = "arrow",symbol_size = 15,is_smooth = True)
        .add_yaxis("激活人数",y2)
        .set_global_opts(title_opts=opts.TitleOpts(title="注册人数&激活人数",subtitle ="我是")))
line.render_notebook()
# 第二种：从配置上更改
from pyecharts.charts import Line
import pyecharts.options as opts
x = list(train_data["月份"])
y1 = list(train_data["注册人数"])
y2 = list(train_data["激活人数"])
line = (Line()
        .add_xaxis(x)
        .add_yaxis("注册人数",y1,symbol = "arrow",symbol_size = 15,is_smooth = True)
        .add_yaxis("激活人数",y2)
        .set_global_opts(
            xaxis_opts=opts.AxisOpts(type_='value'),
            title_opts=opts.TitleOpts(title="注册人数&激活人数",subtitle ="我是")))
line.render_notebook()
```

**显示结果分别如下：**

第一种修改方式：
![image](https://user-images.githubusercontent.com/33095707/87380870-fa7dd080-c5c5-11ea-881d-465a46ca9b16.png)
第二种修改方式：
![image](https://user-images.githubusercontent.com/33095707/87380914-12edeb00-c5c6-11ea-9f10-4880ad3bcb52.png)

显然最想要的是第一种结果，同样的数据使用其他图表，在不修改数据类型以及配置的情况下，绘制出来就是第一种结果，当我想要尝试更改源代码时，识别字段的数据类型，根据类型自动设置x轴，然后源代码逻辑太复杂没办法改。。。

同样的问题除了Line()还有Scatter(), EffectScatter()等，请问是否有其他更便捷的解决方案？

**Comment by sunhailin-Leo** [comment]
@Vineyard-w 
* 最便捷的办法就是修改配置
