### ISSUE TITLE
能否提供将图表生成base64的功能

### ISSUE THREAD

**Issue by guoyue01** [pyecharts/pyecharts#1667]
**问题**
我看到echarts中有将图表生成图片的方式中，可以返回base64然后再做解析生成图片
希望pyecharts也可以提供对应的返回base64的方法

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@guoyue01 
* Echarts 是动态图，base64 不能满足
