### ISSUE TITLE
将pyechatrs与Django结合使用有时无法正常渲染，而是会将数据打印展示出来

### ISSUE THREAD

**Issue by XiangtingLee** [pyecharts/pyecharts#1668]
**问题**
将pyechatrs与Django结合使用有时无法正常渲染，而是会将数据打印展示出来。
多次刷新页面后可能会恢复正常渲染

**运行环境（系统环境及 pyecharts 版本）**
centos7 x64
python 3.7.0
pyechatrs 1.7.1

**代码及截图**

**views.py**
PYECHARTS_INIT_OPTS = opts.InitOpts(width="100%", height="100%", theme=ThemeType.MACARONS)
def _word_cloud():
    ……
    word_cloud = WordCloud(init_opts=PYECHARTS_INIT_OPTS)
    word_cloud.add(series_name="词云统计", data_pair=render_data) #**这里的render_data已经处理为图3中的json格式**
    return word_cloud.render_embed() #**在这里返回的应该是图1中的渲染代码**

**template.html**
{{ render.word_cloud | safe }} #**在此处渲染，render.word_cloud应为图1红框代码**

正常页面效果
![image](https://user-images.githubusercontent.com/26403302/88193468-48eb3900-cc70-11ea-8816-55a427feec7f.png)
正常页面源码
![image](https://user-images.githubusercontent.com/26403302/88193386-2eb15b00-cc70-11ea-95b0-b16c48a8588a.png)

问题页面效果
![image](https://user-images.githubusercontent.com/26403302/88193581-68826180-cc70-11ea-967c-5e9cb8a7479b.png)
问题页面源码
![image](https://user-images.githubusercontent.com/26403302/88193646-7b953180-cc70-11ea-97ad-5219eda54178.png)

**Comment by sunhailin-Leo** [comment]
@XiangtingLee 
* 不太清楚你的描述

**Comment by XiangtingLee** [comment]
我希望把问题图中的数据以词云的方式可视化展示出来，但是在实际的页面中可能会直接将这些数据打印在指定的渲染容器内，而不是在容器内正常渲染词云图

**Comment by sunhailin-Leo** [comment]
@XiangtingLee 
* 应该不会只输出词云内容的，而是输出整个 `json`.
* WordCloud 有单元测试，如果会只输出词云内容的话，单元测试会出错的

**Comment by XiangtingLee** [comment]
> @XiangtingLee
> 
> * 应该不会只输出词云内容的，而是输出整个 `json`.
> * WordCloud 有单元测试，如果会只输出词云内容的话，单元测试会出错的

是的，有时会输出整个渲染的json data，开始我以为是数据量过大，但是后来减少数据量后还是会有这种情况发生。
那么请问这种情况我该如何避免呢？

**Comment by sunhailin-Leo** [comment]
> > @XiangtingLee
> > 
> > * 应该不会只输出词云内容的，而是输出整个 `json`.
> > * WordCloud 有单元测试，如果会只输出词云内容的话，单元测试会出错的
> 
> 是的，有时会输出整个渲染的json data，开始我以为是数据量过大，但是后来减少数据量后还是会有这种情况发生。
> 那么请问这种情况我该如何避免呢？

没遇到这种问题

**Comment by XiangtingLee** [comment]
> > > @XiangtingLee
> > > 
> > > * 应该不会只输出词云内容的，而是输出整个 `json`.
> > > * WordCloud 有单元测试，如果会只输出词云内容的话，单元测试会出错的
> > 
> > 
> > 是的，有时会输出整个渲染的json data，开始我以为是数据量过大，但是后来减少数据量后还是会有这种情况发生。
> > 那么请问这种情况我该如何避免呢？
> 
> 没遇到这种问题

这个问题好像不止会发生在WordCloud上面，我是在单页面内渲染了多个类型的图表(WordCloud，Map，Bar，Pie，Line，Scatter and Funnel)，如果出现问题，这几种图表都会同时表现出来。

奇怪的是，这种情况只会在使用Nginx+uWSGI部署Django时出现，且多在项目启动或重启时发生。而在使用Django自带的WSGI Server启动时从来没有出现过。
