### ISSUE TITLE
 如何再v1.8.1里调用import pyecharts.echarts.events as events

### ISSUE THREAD

**Issue by Chou-Hua** [pyecharts/pyecharts#1671]
**问题** :

我想要利用click event 来呈现另一个bar图，例如现在有 Bar1的图，我点击Bar1的一条长方图，可以跳出另一个Bar2图。
有找到 import pyecharts.echarts.events as events 这个可以调用javascript来实现，但v1.8.1似乎没有此function请问有其他解决方法吗?

**运行环境（系统环境及 pyecharts 版本）** : win10 / python 3.7 / pyecharts v1.8.1

**Comment by sunhailin-Leo** [comment]
@Chou-Hua 
* 你这个方法是以前的版本的，现在没有这个方法了

**Comment by Chou-Hua** [comment]
那新版本有类似的方法吗?

**Comment by JackDapid** [comment]
@Chou-Hua and @sunhailin-Leo .on (events) is really a powerful method of echarts - having a support for it again in pyecharts would be grreat - any plans for that or could I support re-implementing it again?
