### ISSUE TITLE
如何实现横向坐标轴长度自适应屏幕宽度？去除坐标轴外留白

### ISSUE THREAD

**Issue by lonbaw** [pyecharts/pyecharts#1672]
**问题**
如何实现横向坐标轴长度自适应屏幕宽度？
目前图表占浏览器窗口的50%左右，怎么占用100%，去除两边留白？

**运行环境（系统环境及 pyecharts 版本）**

pyecharts                 1.7.1

**代码及截图**
![image](https://user-images.githubusercontent.com/26515610/88451008-f4b9a200-ce85-11ea-98ff-bd1ef1d2de1a.png)

**Comment by sunhailin-Leo** [comment]
@lonbaw 
* 宽度设置百分比
