### ISSUE TITLE
希望每张图都能有独自的VisualMapOpts

### ISSUE THREAD

**Issue by hongsefb** [pyecharts/pyecharts#1673]
**问题**
我使用Grid进行多张图的整合，但是我想要每个图有不同的VisualMapOpts，有不同的视觉映射配置，而不是只能通过set_global_opts设置全局单一的视觉映射配置，比如我第一张热力图就想要从小到大是0-4，第二张热力图我想要0-3的视觉映射，第三张那个北京市的地图我想要0-31的视觉映射，因为其中数据的最大值为31

**运行环境（系统环境及 pyecharts 版本）**
Windows是10.0.19041 (Win10 2004)
python=3.7.7
pyecharts=1.7.1

**代码及截图**
![image](https://user-images.githubusercontent.com/29223722/88454017-cdbb9a00-ce9e-11ea-81fa-027ed7fcd623.png)

**Comment by sunhailin-Leo** [comment]
@hongsefb 
* 这个问题或许你应该去 Echarts 提，暂时好像没见到 Echarts 可以提供你所描述的配置
