### ISSUE TITLE
关于全局设置中缺失的属性

### ISSUE THREAD

**Issue by greatathrun** [pyecharts/pyecharts#1674]
**问题**
在bar的全局设置的方法中，并没有axistick这一参数的设置。但是我直接在self.options中的字典中直接设置关于axistick的相关属性是可行的。比如：
```
c.options["xAxis"][0]['axisTick'] = {"alignWithLabel":True}
```

**运行环境（系统环境及 pyecharts 版本）**
py = 3.7
pyecharts = 1.8.1

**代码及截图**

**Comment by jamfs** [comment]
我在Django中使用PYECHART 有个报错，请问你有遇到过这个问题么？感谢！
pyecharts = 1.8.1
Django Version: | 3.0
Python Version: | 3.7.5
TypeError
报错：set_global_opts() got an unexpected keyword argument 'Legend_opts'
但是实际上是有Legend_opts'的。
![image](https://user-images.githubusercontent.com/44485092/88883479-0aa0db80-d267-11ea-936d-8d41c6cb221f.png)

**Comment by sunhailin-Leo** [comment]
@greatathrun 
* 认真看看 AxisOpts 里面有没有这个配置

**Comment by sunhailin-Leo** [comment]
@jamfs 
* `set_global_opts() got an unexpected keyword argument 'Legend_opts'` 认真看看你贴的报错提示

**Comment by greatathrun** [comment]
> 我在Django中使用PYECHART 有个报错，请问你有遇到过这个问题么？感谢！
> pyecharts = 1.8.1
> Django Version: | 3.0
> Python Version: | 3.7.5
> TypeError
> 报错：set_global_opts() got an unexpected keyword argument 'Legend_opts'
> 但是实际上是有Legend_opts'的。
> ![image](https://user-images.githubusercontent.com/44485092/88883479-0aa0db80-d267-11ea-936d-8d41c6cb221f.png)

你直接在options里设置legend相关属性看看。

**Comment by jamfs** [comment]
非常感谢您的回复。报错提全局配置中没有Legend_opts这个关键字，但是我查全局配置这个类是有的。

或许是我调用方式不对？
def barc(request):
    bar = (
        Bar()
            .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
            .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
            .set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"),
                             Legend_opts=opts.LegendOpts(pos_top='right')
                             )
        # 或者直接使用字典参数
        # .set_global_opts(title_opts={"text": "主标题", "subtext": "副标题"})
    )

    return HttpResponse(bar.render())





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LeoSun"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午2:35
收件人: "pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;; 
抄送: "m0n"<jianjixs@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [pyecharts/pyecharts] 关于全局设置中缺失的属性 (#1674)





 
@jamfs
  
set_global_opts() got an unexpected keyword argument 'Legend_opts' 认真看看你贴的报错提示

**Comment by sunhailin-Leo** [comment]
@jamfs 
* 为什么是 `Legend_opts` 而不是 `legend_opts`？

**Comment by jamfs** [comment]
感谢你的回复。我直接在options里设置是可以生效的。但是调用的时候会报上面的错。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "greatathrun"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午2:40
收件人: "pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;; 
抄送: "m0n"<jianjixs@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [pyecharts/pyecharts] 关于全局设置中缺失的属性 (#1674)





  
我在Django中使用PYECHART 有个报错，请问你有遇到过这个问题么？感谢！
 pyecharts = 1.8.1
 Django Version: | 3.0
 Python Version: | 3.7.5
 TypeError
 报错：set_global_opts() got an unexpected keyword argument 'Legend_opts'
 但是实际上是有Legend_opts'的。
 
  
你直接在options里设置legend相关属性看看。

**Comment by jamfs** [comment]
非常感谢您，原来是大小写的问题。我太粗心了。向您学习




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LeoSun"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午2:49
收件人: "pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;; 
抄送: "m0n"<jianjixs@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [pyecharts/pyecharts] 关于全局设置中缺失的属性 (#1674)





 
@jamfs
  
为什么是 Legend_opts 而不是 legend_opts？

**Comment by greatathrun** [comment]
了解了

> @greatathrun
> 
> * 认真看看 AxisOpts 里面有没有这个配置

非常感谢你的提醒，重新看了一下源码，报错的原因是 ：我直接在.set_global_opts()方法里设置AxisTickOpts()相关的样式。但是实际上关于AxisTickOpts的相关设置是在.set_global_opts()下的xais_opts参数里传入opts.AxisTickOpts的相关样式
