### ISSUE TITLE
运行警告： 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置

### ISSUE THREAD

**Issue by xiagongjin** [pyecharts/pyecharts#1675]
```
PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)
```
用文档中的demo，会提示这个警告。
查了很多地方，没有学会怎么消除这个警告。
demo中的代码：
```from pyecharts.charts import Bar

bar = (
    Bar()
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
)
bar.render()
```
我按装的1.8.1。
初学者，希望能得到您的帮助，谢谢

**Comment by sunhailin-Leo** [comment]
@xiagongjin 
* 请仔细阅读官网 ChangeLog

**Comment by xiagongjin** [comment]
看到文档中有提到这个更新，但是没找到消除警告的办法。
[https://github.com/pyecharts/pyecharts/pull/1578](https://github.com/pyecharts/pyecharts/pull/1578)
[https://github.com/pyecharts/pyecharts/issues/1562](https://github.com/pyecharts/pyecharts/issues/1562)
请问哪里可以找到介绍  ChartItem 的文档

**Comment by ly1102** [comment]
> 看到文档中有提到这个更新，但是没找到消除警告的办法。
> #1578
> #1562
> 请问哪里可以找到介绍 ChartItem 的文档

@xiagongjin 你找到办法了吗？我也看了代码，但是还是看不懂这个逻辑。因为我要写一个长期支持的项目，不想等更新了，用户又让我重新来写。。。
很久没用pyecharts了，没想到变化这么大了，比以前要复杂挺多了。

**Comment by fujiangyese** [comment]
> > 看到文档中有提到这个更新，但是没找到消除警告的办法。
> > #1578
> > #1562
> > 请问哪里可以找到介绍 ChartItem 的文档
> 
> @xiagongjin 你找到办法了吗？我也看了代码，但是还是看不懂这个逻辑。因为我要写一个长期支持的项目，不想等更新了，用户又让我重新来写。。。
> 很久没用pyecharts了，没想到变化这么大了，比以前要复杂挺多了。

可以去到pyecharts库下面的globals.py文件，找到_WarningControl类，将ShowWarning设置为False即可
<img width="647" alt="解决" src="https://user-images.githubusercontent.com/33179602/93763287-c23ce300-fc43-11ea-8db4-5848476f0d6b.png">

**Comment by Lathezero** [comment]
> > > 看到文档中有提到这个更新，但是没找到消除警告的办法。
> > > #1578
> > > #1562
> > > 请问哪里可以找到介绍 ChartItem 的文档
> > 
> > 
> > @xiagongjin 你找到办法了吗？我也看了代码，但是还是看不懂这个逻辑。因为我要写一个长期支持的项目，不想等更新了，用户又让我重新来写。。。
> > 很久没用pyecharts了，没想到变化这么大了，比以前要复杂挺多了。
> 
> 可以去到pyecharts库下面的globals.py文件，找到_WarningControl类，将ShowWarning设置为False即可 <img alt="解决" width="44" height="21" src="https://camo.githubusercontent.com/f2bdc23116d59d69e243af0194169ad54ee759b99953de1e4a0ab28240b2d288/68747470733a2f2f646463646e2e6a642e636f6d2f6464696d672f6a66732f74312f3132323135332f32352f31333139342f35333233362f35663638393430624533306663336234652f343733613166316364636264643463352e706e67">



> ```
> PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
>   super().__init__(init_opts=init_opts)
> ```
> 
> 用文档中的demo，会提示这个警告。 查了很多地方，没有学会怎么消除这个警告。 demo中的代码：
> 
> ```
> 
> bar = (
>     Bar()
>     .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
>     .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
> )
> bar.render()
> ```
> 
> 我按装的1.8.1。 初学者，希望能得到您的帮助，谢谢

应该是没有设置主标题
