### ISSUE TITLE
提问: 可以再产生的Bar图中，点击长柱条后，再弹出另外的Bar图吗?

### ISSUE THREAD

**Issue by Chou-Hua** [pyecharts/pyecharts#1676]
**问题**

目前统计用户使用的浏览器的名称，想在统计的BAR条上，点击该名称后，弹出该浏览器名称的各版本使用人数。
有法子能例如点击统计chrome的长柱图，弹出chrome的各版本统计。

**运行环境（系统环境及 pyecharts 版本）**
windows10 / v1.8.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Chou-Hua 
* 目前需要自行实现 js 方法
