### ISSUE TITLE
https://assets.pyecharts.org/assets/echarts.min.js 不能访问，导致调用pyecharts 建立的网站图表不能渲染

### ISSUE THREAD

**Issue by wangjiahong666** [pyecharts/pyecharts#1683]
**问题**
pyecharts.org 网站不能访问，调用pyecharts 建立的网站图表不能渲染（html里面的script调用了https://assets.pyecharts.org/assets/echarts.min.js）

**Comment by wangjiahong666** [comment]
![image](https://user-images.githubusercontent.com/14320144/90424360-ab482580-e0c6-11ea-9da4-6cfda0bd6f89.png)

**Comment by pramitchoudhary** [comment]
Was trying a few stuff, facing this error as well. Any solutions?

**Comment by wangjiahong666** [comment]
@pramitchoudhary when did this start to happen to you?

**Comment by SkinnyPancake** [comment]
I'm not sure whether it is the same error but I got

`JavascriptException: Message: javascript error: echarts is not defined
  (Session info: headless chrome=84.0.4147.125)
`

today and I feel like that is also due to the fact that the js file cannot be downloaded from the online CDN...

**Comment by pramitchoudhary** [comment]
@wangjiahong666 
Just a while back, is there a way allow the user to pass an alternate `js` path?

**Comment by chips-ahoy1101** [comment]
Hello @wangjiahong666 , I got `GET https://assets.pyecharts.org/assets/echarts.min.js net::ERR_NAME_NOT_RESOLVED` error today as well. And the pyecharts.org website has been down since `Mon Aug 17 19:32:07 UTC 2020`.

**Comment by pramitchoudhary** [comment]
```
from pyecharts.globals import CurrentConfig
default_host = CurrentConfig.ONLINE_HOST
print(default_host)
custom_host = "https://cdnjs.cloudflare.com/ajax/libs/echarts/4.8.0/"
CurrentConfig.ONLINE_HOST = custom_host
```
Above worked for me.

**Comment by Johannnnn506** [comment]
> ```
> from pyecharts.globals import CurrentConfig
> default_host = CurrentConfig.ONLINE_HOST
> print(default_host)
> custom_host = "https://cdnjs.cloudflare.com/ajax/libs/echarts/4.8.0/"
> CurrentConfig.ONLINE_HOST = custom_host
> ```
> 
> Above worked for me, hopefully, helpful for others.

Totally helpful, THX!

**Comment by SkinnyPancake** [comment]
> ```
> from pyecharts.globals import CurrentConfig
> default_host = CurrentConfig.ONLINE_HOST
> print(default_host)
> custom_host = "https://cdnjs.cloudflare.com/ajax/libs/echarts/4.8.0/"
> CurrentConfig.ONLINE_HOST = custom_host
> ```
> 
> Above worked for me, hopefully, helpful for others.

It works like magic for a non-Map type object! Thanks a lot!
However, I still cannot get a Map type object rendered. Only the color bar is shown.

**Comment by yuzhang66** [comment]
Met the same issue, download https://github.com/pyecharts/pyecharts-assets, and use it locally will help.

**Comment by kelanj** [comment]
> ```
> from pyecharts.globals import CurrentConfig
> default_host = CurrentConfig.ONLINE_HOST
> print(default_host)
> custom_host = "https://cdnjs.cloudflare.com/ajax/libs/echarts/4.8.0/"
> CurrentConfig.ONLINE_HOST = custom_host
> ```
> 
> Above worked for me, hopefully, helpful for others.

Amazing!! Thanks a lot!!

**Comment by chenjiandongx** [comment]
The pyecharts.org is being maintained hence it may be unstable temporarily.

**Comment by transfercai** [comment]
awesome!

**Comment by chenjiandongx** [comment]
All the pyecharts related domain, including

* https://pyecharts.org
* https://assets.pyecharts.org
* https://gallery.pyecharts.org
* https://05x-docs.pyecharts.org

have been deployed in the new server, please visit them again if it is still unreachable :)

**Comment by Waym1ng** [comment]
I think this link can help you.
https://pyecharts.org/#/zh-cn/assets_host
