### ISSUE TITLE
反选折线图

### ISSUE THREAD

**Issue by z8772083** [pyecharts/pyecharts#1684]
如何只显示选中的Legend Opts 趋势图，非选中的隐藏，现状是刚好反过来的。

**Comment by sunhailin-Leo** [comment]
@z8772083 
* 不太明白那你的描述，最好配上截图和代码

**Comment by IsanHu** [comment]
意思应该是：多个lengend的情况，能够一键选中某一个legend显示，隐藏其他的。  反选操作

**Comment by IsanHu** [comment]
@sunhailin-Leo 不知道有没有这样的设置
