### ISSUE TITLE
折线图生成的html，数据显示很密集，看不清楚

### ISSUE THREAD

**Issue by hdzys** [pyecharts/pyecharts#1686]
折线图生成报表时，html数据显示得太密集，看不清楚数据

![image](https://user-images.githubusercontent.com/45445106/90616833-8677bd80-e240-11ea-9c30-9a28d05acf5d.png)

![image](https://user-images.githubusercontent.com/45445106/90616367-efab0100-e23f-11ea-8363-d5be148c77af.png)
不知道什么原因，请指教！

**Comment by sunhailin-Leo** [comment]
@hdzys 
* 设置 `label_opts.is_show` 为 `false` 即可

**Comment by hdzys** [comment]
不好意思，我主要想表达的是：数据都是每2秒插入的一条数据，这个报表把没个数据的值都显示了，但大多数的报表是隔了好几个数据才显示一个值，如（隔了2分钟显示一个值）：
![image](https://user-images.githubusercontent.com/45445106/91275951-6b163080-e7b3-11ea-8866-2e34da1d0d3a.png)

**Comment by sunhailin-Leo** [comment]
@hdzys 
* 那你这种场景建议分开限时

**Comment by hdzys** [comment]
问题是：我从csv文件读取的数据，这些数据都是每两秒插入一条的，有时候生成的报表，每一条数据的值都显示了，如第一个图，但大多数生成报表呢，如后边这副图，间隔了2分钟才显示一个值，看起来就不是那么乱，也比较清晰。
或者我想知道怎么设置x坐标间隔一个值才显示y坐标的值么，比如每隔一定时间（5分钟，10分钟）才显示一个值。
不好意思打扰了，非常感谢！

**Comment by sunhailin-Leo** [comment]
@hdzys 
* 按照固定的间隔插入值就可以了

**Comment by hdzys** [comment]
好的，谢谢。

**Comment by Doraying1230** [comment]
你好，想问下你这个机器指标的横坐标的时间是如何设置的

**Comment by hdzys** [comment]
excel里插入的，生成报表时候直接读取即可~

**Comment by Doraying1230** [comment]
> excel里插入的，生成报表时候直接读取即可~

所有数据的时间作为横坐标的值吗
