### ISSUE TITLE
Legend显示问题

### ISSUE THREAD

**Issue by yuesun420** [pyecharts/pyecharts#1692]
**问题**
调整opts.ItemStyleOpts中的参数后，导致legend颜色关联失败

**运行环境（系统环境及 pyecharts 版本）**
windows，pyecharts version=1.8.1

**代码及截图**
            mline.add_yaxis(linelabel,y_data,symbol='circle',symbol_size=6,is_smooth=True,
                linestyle_opts=opts.LineStyleOpts(color=color_range[i],width=2,type_=type_range[i%3]),
                label_opts=opts.LabelOpts(is_show=False),
                markpoint_opts=opts.MarkPointOpts(
                    data=[opts.MarkPointItem(type_="max",symbol ='pin',symbol_size=60,
                        itemstyle_opts=opts.ItemStyleOpts(color=color_range[i],opacity=0.8))],
                    label_opts=opts.LabelOpts(position="inside",color='white',
                        margin=2,font_size=10)))
![image](https://user-images.githubusercontent.com/36052383/91357086-ae29d100-e7be-11ea-8271-17538e9d15a7.png)

![image](https://user-images.githubusercontent.com/36052383/91357150-cb5e9f80-e7be-11ea-8c57-7fc403b62662.png)
            mline.add_yaxis(linelabel,y_data,symbol='circle',symbol_size=6,is_smooth=True,
                linestyle_opts=opts.LineStyleOpts(color=color_range[i],width=2,type_=type_range[i%3]),
                itemstyle_opts=opts.ItemStyleOpts(border_width=1.5,border_color=color_range[i],color='white'),
                label_opts=opts.LabelOpts(is_show=False),
                markpoint_opts=opts.MarkPointOpts(
                    data=[opts.MarkPointItem(type_="max",symbol ='pin',symbol_size=60,
                        itemstyle_opts=opts.ItemStyleOpts(color=color_range[i],opacity=0.8))],
                    label_opts=opts.LabelOpts(position="inside",color='white',
                        margin=2,font_size=10)))

**Comment by sunhailin-Leo** [comment]
@yuesun420 
* 先把代码格式化一下，没有缩进看不到太明白你的代码
