### ISSUE TITLE
使用graph作图时,nodes中的symbolSize参数无效，画出的图所有节点大小一致，且节点颜色均默认为红色

### ISSUE THREAD

**Issue by NealWood** [pyecharts/pyecharts#1695]
**环境windows10, python3.7,pyecharts1.8.1**

**画出的图如下：**

![Image_20200831163711](https://user-images.githubusercontent.com/43162041/91700301-469dc800-eba8-11ea-80db-5f777b110586.png)

**nodes的symbolSize参数如下：**

![Image_20200831163831](https://user-images.githubusercontent.com/43162041/91700440-777dfd00-eba8-11ea-9c78-aa6813bd4884.png)

**问题**：虽然nodes的symbolSize不一致，但是nodes大小相同，且颜色均默认为红色，请问怎样能画出类似于官网范例中不同颜色不同节点大小的图？

**官网范例：**

![Image_20200831164247](https://user-images.githubusercontent.com/43162041/91700837-0723ab80-eba9-11ea-97d5-4593bab191f4.png)

感谢解答！

**Comment by sunhailin-Leo** [comment]
@NealWood 
* Demo: https://gallery.pyecharts.org/#/Graph/graph_weibo
* DemoFile: https://github.com/pyecharts/pyecharts-gallery/blob/master/Graph/weibo.json
