### ISSUE TITLE
地理图Geo，画类似于航线图，如何输入数据值

### ISSUE THREAD

**Issue by Karl-Zhuo** [pyecharts/pyecharts#1697]
**问题**
似乎旧版本有geolines可以实现，但现在没这个模块了https://github.com/pyecharts/pyecharts/issues/565
如何在1.X版本中的地理线图中输入数值，并且在tooltip中显示？
直接插入如下数值
data_guangzhou = [
    ["广州", "上海", 10],
    ["广州", "北京", 20],
]
显示ValueError: too many values to unpack (expected 2)

**运行环境（系统环境及 pyecharts 版本）**
Windows 10
pyecharts                          1.7.1

**代码及截图**
![image](https://user-images.githubusercontent.com/40227013/91791091-ced1ab00-ec44-11ea-8722-18130fab0f12.png)

**Comment by sunhailin-Leo** [comment]
@Karl-Zhuo 
* 看一下新版本的文档

**Comment by Esdsnqxz** [comment]
您好，我最近遇到相同的问题，请问您解决了嘛？
