### ISSUE TITLE
SankeyGraph中layoutIteration未生效

### ISSUE THREAD

**Issue by hazeccc** [pyecharts/pyecharts#1701]
**问题**
SankeyGraph中layoutIteration参数未生效

**运行环境（系统环境及 pyecharts 版本）**
pyecharts版本1.8.1，python版本3.6.7

**问题描述**
echarts会按照links的重叠来优化节点布局，目前用layoutIteration参数来控制迭代次数，缺省值为32，
但因此无法手动通过传入的nodes和links的顺序来控制结果的节点顺序。

目前使用pyecharts的Sankey类中add函数的layoutIteration设为0传入后，渲染得到的html该参数的外部值为0，但仍按照加载的静态echarts.min.js文件中的缺省值32进行渲染。

手动将js文件中的该值设为0后，节点顺序才是传入的nodes的顺序。
设置该值为0后，无论pyecharts中传入的参数值为多少，都不会触发节点布局的优化
静态文件内容：
```js
defaultOption:{
	zlevel:0,
	z:2,
	coordinateSystem:"view",
	layout:null,
	left:"5%",
	top:"5%",
	right:"20%",
	bottom:"5%",
	orient:"horizontal",
	nodeWidth:20,
	nodeGap:8,
	draggable:!0,
	focusNodeAdjacency:!1,
	layoutIterations:32,  //仅可通过设置此处为0来固定节点顺序
	label:{
		show:!0,
		position:"right",
		color:"#000",
		fontSize:12
	},
	levels:[],
	nodeAlign:"justify",
	itemStyle:{
		borderWidth:1,
		borderColor:"#333"
	},
	lineStyle:{
		color:"#314656",
		opacity:.2,
		curveness:.5
	},
	emphasis:{
		label:{show:!0},
		lineStyle:{opacity:.5}
	},
	animationEasing:"linear",
	animationDuration:1e3
}
```

**Comment by KB4EVER** [comment]
请问这个设置为什么有很大的滞后性 我更改这个参数为0要过大半天才能实现不优化节点顺序呢

**Comment by sunhailin-Leo** [comment]
@KB4EVER 这个问题应该追溯到 Echarts 本身对于优化节点的实现逻辑

**Comment by MasonMa-sy** [comment]
I find that the Sankey Graph html file generated by pyechart has a parameter **"layoutIteration"**.
This parameter should be **"layoutIterations"** to work.
An `s` is missing here

**Comment by Wingswang728** [comment]
请问echarts.min.js文件在哪里呀，是按pyecharts的时候就有吗

**Comment by liujialiangim** [comment]
> I find that the Sankey Graph html file generated by pyechart has a parameter **"layoutIteration"**. This parameter should be **"layoutIterations"** to work. An `s` is missing here

works. 需要修改 `/miniconda3/lib/python3.7/site-packages/pyecharts/charts/basic_charts/sankey.py`: 
- 将关于32的最小值约束注释掉
- layoutIteration -> layoutIterations
然后重启就完事

**Comment by wuhanlt** [comment]
这个问题还没完全修复啊！
