### ISSUE TITLE
多个不同x轴数值的数据如何轻松的绘制在一张图上

### ISSUE THREAD

**Issue by csfreebird** [pyecharts/pyecharts#1702]
**问题**
x1 = [0,1,2] 
y1 = [22, 24, 26]
x2 = [2, 3, 4, 5]
y2 = [27.5, 21, 33, 28]

现在希望绘制的图形x轴上的数值依次为: [0, 1, 2, 3, 4, 5]
y1, y2 分别绘制成两条折线

如何做到呢?

**Comment by sunhailin-Leo** [comment]
@csfreebird 
* x 轴固定长度，y 轴在需空缺的地方将数据设置为 0

**Comment by csfreebird** [comment]
设置为0? 
很多场景下, 0值是有意义的, 这个方案完全不对.

**Comment by MochiXu** [comment]
请问这个问题现在有解决方案吗
@csfreebird 
@sunhailin-Leo
