### ISSUE TITLE
Scatter使用ScatterItem时，若它和其他图形overlap，那么X轴无法正确的自动对应【bug】【help wanted】

### ISSUE THREAD

**Issue by zx9229** [pyecharts/pyecharts#1703]
**问题**
我画了一个Line，X轴数据较多，
我画了一个Scatter，X轴数据较少，
Scatter的X轴数据，均能在Line里面找到，
我将Scatter图形overlap到Line上，
如果为Scatter使用了ScatterItem，那么X轴无法正确的自动对应。

**运行环境（系统环境及 pyecharts 版本）**
系统环境：Win7 SP1
pyecharts版本：1.8.1

**代码及截图**
```python
import pyecharts

def load_data_Close():
    close_data = [('2020-09-02', 4843.89), ('2020-09-03', 4817.1),
                  ('2020-09-04', 4770.22), ('2020-09-07', 4669.37), ('2020-09-08', 4694.39)]
    return close_data

def load_data_Trade():
    close_data = load_data_Close()
    trade_date = [close_data[i] for i in range(len(close_data)) if i % 2 == 0]
    return trade_date

def get_charts_Line(close_data):
    list_dataX = [i[0] for i in close_data]
    list_dataY = [i[1] for i in close_data]
    line = pyecharts.charts.Line().add_xaxis(xaxis_data=list_dataX).add_yaxis(
        series_name="Line_收盘价",
        y_axis=list_dataY,
        label_opts=pyecharts.options.LabelOpts(is_show=False),
    )
    return line

def get_charts_Scatter(trade_data):
    list_dataX = [i[0] for i in trade_data]
    list_dataY1 = [i[1] for i in trade_data]
    list_dataY2 = [pyecharts.options.ScatterItem(value=i) for i in list_dataY1]
    # 如果y_axis的数据是普通类型（非dict非ScatterItem，比如本例中的数字），
    # 那么X轴是能自动对应的，
    # 如果y_axis的数据是ScatterItem，那么X轴就没法自动对应了，
    show_bug = True  # 请为该变量设置 True 或 False 并观察不同的html文件的展示情况
    list_dataY = list_dataY2 if show_bug else list_dataY1
    # 开发者可以生成两个不同的html文件，然后用BeyondCompare对比一下，或许就发现原因了
    # 作为用户，我想根据不同的条件，让某些点显示特殊的颜色，所以需要使用ScatterItem，
    scatter = pyecharts.charts.Scatter().add_xaxis(
        xaxis_data=list_dataX).add_yaxis(
            series_name='Scatter_成交',
            y_axis=list_dataY,
            label_opts=pyecharts.options.LabelOpts(is_show=False),
    )
    return scatter

if __name__ == '__main__':
    print('pyecharts.__version__ = {}'.format(pyecharts.__version__))
    pyecharts.globals._WarningControl.ShowWarning = False
    close_data = load_data_Close()
    trade_date = load_data_Trade()
    charts_line = get_charts_Line(close_data)
    charts_scatter = get_charts_Scatter(trade_date)
    charts_line.overlap(charts_scatter)
    charts_line.render(__file__ + '.html')
    exit(0)
```
![BUG_ScatterItem](https://user-images.githubusercontent.com/20023224/92469462-6d42ab00-f207-11ea-925e-26bb6d341c3d.png)

**Comment by MeredithChai** [comment]
U can use the scatter color with the "itemstyle_opts" option. Click [here](https://pyecharts.org/#/zh-cn/series_options?id=itemstyleopts%ef%bc%9a%e5%9b%be%e5%85%83%e6%a0%b7%e5%bc%8f%e9%85%8d%e7%bd%ae%e9%a1%b9) to learn more.

**Comment by zx9229** [comment]
> U can use the scatter color with the "itemstyle_opts" option. Click [here](https://pyecharts.org/#/zh-cn/series_options?id=itemstyleopts%ef%bc%9a%e5%9b%be%e5%85%83%e6%a0%b7%e5%bc%8f%e9%85%8d%e7%bd%ae%e9%a1%b9) to learn more.

我想表达的意思是：
如果我使用ScatterItem进行自定义定制的话，我将Scatter和Line进行overlap的时候，在图形上面，同一个y值，其x值对应失败了。
What I want to express is:
If I use ScatterItem for custom customization, when I overlap Scatter and Line, on the graph, the same y value, the x value corresponding to the same fails.
或者，如果Scatter图形使用ScatterItem，如果你能将Scatter和Line进行overlap的时候，其x对应在正确的位置上，如果方便的话，能帮忙提供一下代码吗？
Or, if Scatter graphics use ScatterItem, if you can overlap Scatter and Line, the x corresponds to the correct position. If it is convenient, can you help provide the code?

**Comment by MeredithChai** [comment]
> > U can use the scatter color with the "itemstyle_opts" option. Click [here](https://pyecharts.org/#/zh-cn/series_options?id=itemstyleopts%ef%bc%9a%e5%9b%be%e5%85%83%e6%a0%b7%e5%bc%8f%e9%85%8d%e7%bd%ae%e9%a1%b9) to learn more.
> 
> 我想表达的意思是：
> 如果我使用ScatterItem进行自定义定制的话，我将Scatter和Line进行overlap的时候，在图形上面，同一个y值，其x值对应失败了。
> What I want to express is:
> If I use ScatterItem for custom customization, when I overlap Scatter and Line, on the graph, the same y value, the x value corresponding to the same fails.
> 或者，如果Scatter图形使用ScatterItem，如果你能将Scatter和Line进行overlap的时候，其x对应在正确的位置上，如果方便的话，能帮忙提供一下代码吗？
> Or, if Scatter graphics use ScatterItem, if you can overlap Scatter and Line, the x corresponds to the correct position. If it is convenient, can you help provide the code?

.....这个机翻就很灵性，还有你本来意思难道不就是要调整颜色吗？中间插空的直接overlap本身就有问题：你x轴数目又不对应。解决思路有很多，一种scatter中间插空跟line的x轴对应对齐，另一种你可以试试直接找line的itemstyle_opts图元样式修改其形状大小颜色。
