### ISSUE TITLE
请问能否像matplotlib库那样，直接保存画的图片呢？

### ISSUE THREAD

**Issue by chaojidaxingxin** [pyecharts/pyecharts#1704]
**问题**

之前采用make_snapshot的方式，但这样效率太低，不满足实际工作需求，在截图到到本地的过程非常耗时，已设置不延时生成图片，但速度还是较慢，不知道各位大佬能否提供点思路吗，十分感谢！感谢作者提供优秀的画图库！

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by csfreebird** [comment]
可以. 我在ubuntu上试验成功.

   先安装库
   #+begin_src bash
   pip install snapshot-selenium
   #+end_src
   下载chrome driver的linux程序，复制到/usr/bin/目录下
    
   #+begin_src python
   from pyecharts import options as opts
   from pyecharts.charts import Bar
   from pyecharts.render import make_snapshot
    
   from snapshot_selenium import snapshot
    
   def bar_chart() -> Bar:
       c = (
           Bar()
           .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
           .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
           .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
           .reversal_axis()
           .set_series_opts(label_opts=opts.LabelOpts(position="right"))
           .set_global_opts(title_opts=opts.TitleOpts(title="Bar-测试渲染图片"))
       )
       return c
   make_snapshot(snapshot, bar_chart().render(), "./imgs/bar0.png")
   #+end_src

**Comment by chaojidaxingxin** [comment]
> 下载chrome driver的linux程序，复制到/usr/bin/目录下

感谢您耐心的回答，是我没表达清楚，我采用过这种 snapshot_phantomjs 保存图片，虽然能实现保存图片的功能，但是耗时严重，批量保存图片的时间过长，有其他的解决方案吗？或者说snapshot_selenium等其他两种保存方式，能提高保存速度吗？

**Comment by sunhailin-Leo** [comment]
@chaojidaxingxin 
* 没有别的办法，因为需要加载 Echarts 的 js 文件
* `pyecharts` 和 `matplotlib` 有本质上的区别

**Comment by chfw** [comment]
估计现在你用的是一图一个文件。

你可以尝试一个文件有多个图片（M值，你需要自己测试），然后抓图的时候等待足够长时间（T)，再用 [echarts-scappeteer](https://github.com/chfw/echarts-scrappeteer)试试看。是不是总的时间(sum(T))会变短。
