### ISSUE TITLE
能否增加c.add_schema(maptype="china")中maptype 如 华北，东北，长三角，这样的区域类型，或者多个省份地图自由组合的功能。谢谢！

### ISSUE THREAD

**Issue by mabuge** [pyecharts/pyecharts#1706]
**问题**

能否增加c.add_schema(maptype="china")中maptype 如 华北，东北，长三角，这样的区域类型，或者多个省份地图自由组合的功能。谢谢！

**运行环境（系统环境及 pyecharts 版本）**

ubuntu pyecharts1.1.1

**代码及截图**

**Comment by chfw** [comment]
with latest pyecharts:

```
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.datasets import register_url

register_url("https://echarts-maps.github.io/echarts-china-misc-js/")

g = (
    Geo()
    .add_schema(maptype="华北")
    .set_global_opts(title_opts=opts.TitleOpts(title="华北地区"))
)
g.render()

```

<img width="566" alt="Screenshot 2020-09-15 at 11 28 15" src="https://user-images.githubusercontent.com/4280312/93199669-8d61f500-f746-11ea-9d78-51cafcc580ab.png">

**Comment by chfw** [comment]
```
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.datasets import register_url

register_url("https://echarts-maps.github.io/echarts-china-misc-js/")

g = (
    Geo()
    .add_schema(maptype="台港澳")
    .set_global_opts(title_opts=opts.TitleOpts(title="台港澳三地"))
)
g.render()
```


<img width="530" alt="Screenshot 2020-09-15 at 11 30 30" src="https://user-images.githubusercontent.com/4280312/93199883-e762ba80-f746-11ea-88e3-495876d7edca.png">

**Comment by RenBaixiao** [comment]
我最近在做世界地图的标注，想问一下单独做欧洲或是美洲啊，该如何实现？目前看来也要借助第三方的js库，这两天学习过程中发现github上不少这样的专门为echarts制作的js库，请问有所有相关库的链接目录吗？

**Comment by chfw** [comment]
我有个攻略：https://echarts-maps.github.io/echarts-geomapping-book-zh/

**Comment by chfw** [comment]
你可以参考瑞士地图的做法。

**Comment by RenBaixiao** [comment]
@chfw 学到了，感谢，膜拜大佬
