### ISSUE TITLE
服气，二十个小时没解决下来，救个命好吧：echarts is not defined

### ISSUE THREAD

**Issue by nlpjoe** [pyecharts/pyecharts#1709]
**问题**
echarts is not defined

**运行环境（系统环境及 pyecharts 版本）**
notebook                6.1.4
pyecharts               1.8.1

**代码及截图**

![image](https://user-images.githubusercontent.com/9483969/93667993-4a907c00-fabc-11ea-9534-fe175c83f1f9.png)
![image](https://user-images.githubusercontent.com/9483969/93668010-6d229500-fabc-11ea-8cad-6170716af457.png)

**Comment by chfw** [comment]
试试自己提供 assets

**Comment by nlpjoe** [comment]
ok.就这样吧

**Comment by xliang10** [comment]
1. 检查网络问题(如果是网络问题，可以改成引用本地文件，参考 https://pyecharts.org/#/zh-cn/assets_host)
2. 检查chrome driver版本
3. 有时候卸载重装snapshot_selenium(`pip uninstall snapshot-selenium; pip install snapshot-selenium`)能解决问题，但原因未了解

**Comment by Abbyyan** [comment]
请问这里是如何解决的呢？之前一直运行没有问题的，突然就报了这个错

selenium.common.exceptions.JavascriptException: Message: javascript error: echarts is not defined
  (Session info: headless chrome=88.0.4324.150)
（代码没改，环境没有动，怀疑人生中，，，）

**Comment by Seanhom** [comment]
> 

我也遇到了这个问题，搞两天都没解决，请问这个问题你之前是如何解决的呢？
