### ISSUE TITLE
想根据一个列表生成多条markline

### ISSUE THREAD

**Issue by 808bass808** [pyecharts/pyecharts#1710]
**问题**
想根据一个列表的数据生成多条markline

**运行环境（系统环境及 pyecharts 版本）**
windows python3.8.3  pyecharts-1.8.1

**代码及截图**
有一个数据集（df_case）长这样
![image](https://user-images.githubusercontent.com/71600644/93715319-33748b80-fb9b-11ea-86c6-e0b4e7b3a180.png)
**想根据数据集里面的数据自动生成多条参考线markline，这里的循环怎么写？，**
**现在只会手动写多条opts.MarkLineItem data**

line.set_series_opts(
        label_opts=opts.LabelOpts(is_show=True),
        markline_opts=opts.MarkLineOpts(
            data=[
                opts.MarkLineItem(y=df_case['date'][0], name=df_case['case'][0])
                opts.MarkLineItem(y=df_case['date'][1], name=df_case['case'][1])
            ],
            symbol_size=[20,10],
            linestyle_opts=opts.LineStyleOpts(color='red',width=1)
        ),
    )

**Comment by MeredithChai** [comment]
Your data obj:
```python
data=[
opts.MarkLineItem(y=df_case['date'][0], name=df_case['case'][0])
opts.MarkLineItem(y=df_case['date'][1], name=df_case['case'][1])
],
```
is just a **list**. You can just create it by a [list comprehensions](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions) like:
```python
data=[opts.MarkLineItem(y=row.date, name=row.case) for row in df_case.itertuples()]
```
