### ISSUE TITLE
jupyterlab导出为html图表无法显示

### ISSUE THREAD

**Issue by Loveforkeeps** [pyecharts/pyecharts#1711]
**问题**
貌似是同jupyterlab导出时附加的js产生冲突导致的，手动添加js在以下前图表会显示正常，但是toc就无法使用了
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

**运行环境（系统环境及 pyecharts 版本）**
MacOS Chrome 
pyecharts==1.7.1
Python 3.8.3

**代码及截图**
<img width="2554" alt="image" src="https://user-images.githubusercontent.com/11980462/93738618-d3242f00-fc18-11ea-8402-5497e6254b6b.png">

jupyterlab中显示正常
<img width="999" alt="image" src="https://user-images.githubusercontent.com/11980462/93738645-e20ae180-fc18-11ea-9ced-8235f78780d5.png">

**Comment by nlpjoe** [comment]
host改成这个：
```
CurrentConfig.ONLINE_HOST = "https://cdn.kesci.com/lib/pyecharts_assets/"
```

**Comment by Loveforkeeps** [comment]
不行没有效果，还是一样，不是echats加载的问题，还是js冲突的问题
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/11980462/95649878-885c4f80-0b12-11eb-8140-6700414f49c6.png">
