### ISSUE TITLE
关于定时增量更新图表

### ISSUE THREAD

**Issue by 8188** [pyecharts/pyecharts#1712]
看了官网flask（其他框架也类似）定时增量更新图表的[例子](https://pyecharts.org/#/zh-cn/web_flask?id=%E5%AE%9A%E6%97%B6%E5%A2%9E%E9%87%8F%E6%9B%B4%E6%96%B0%E5%9B%BE%E8%A1%A8)，想请问如何实现多个数据的定时增量和把X轴变为时间轴且只展示最新一段时间的方法。

**Comment by sunhailin-Leo** [comment]
那就多个数据的话不在同一张图就使用多个接口的方式，如果是同一张图或修改时间轴的话需要自行封装数据

**Comment by 8188** [comment]
谢谢回答，多个接口可行，不知如何自行封装，还有只展示一段时间而不是让x轴一直增加
