### ISSUE TITLE
数据地图MAP，地名标签重叠在一起，如何调整位置？

### ISSUE THREAD

**Issue by Patrick7kai** [pyecharts/pyecharts#1713]
**问题**
![image](https://user-images.githubusercontent.com/71744914/93962963-90846300-fd8e-11ea-83ee-37c926c60d7b.png)

**运行环境（系统环境及 pyecharts 版本）**
python3.7
pyecharts 1.7.1

**代码及截图**

**Comment by retornado** [comment]
遇到同样的问题，希望可以调整标签的坐标

**Comment by sunhailin-Leo** [comment]
@Patrick7kai 
* 这个问题目前只能去自定义地图数据标签的中心坐标
