### ISSUE TITLE
关于折线图中添加标尺的问题

### ISSUE THREAD

**Issue by yf-web** [pyecharts/pyecharts#1714]
在坐标系中手动添加横向或纵向的标尺（就是一根线），标尺与折线的交点处显示当前点的横纵坐标值。这个目前有可能实现吗？或者实现起来难度如何？又或者有没有其他的python可视化库支持这类操作？谢谢！

**Comment by sunhailin-Leo** [comment]
@yf-web 如果 Echarts 有的话，我们也会相对应支持的
