### ISSUE TITLE
用循环+pyecharts画出来的分类散点图，X轴标签重复且只显示最后一次循环结果的X标签

### ISSUE THREAD

**Issue by 808bass808** [pyecharts/pyecharts#1715]
**问题**
想通过循环来将不同case的数据画在一张散点图上，但发现有几个问题，
1）X轴标签只显示最后一次循环结果的X，无法显示所有的X，
2）X轴标签重复

**运行环境（系统环境及 pyecharts 版本）**
windows python3.8.3 pyecharts-1.8.1

**代码及截图**
代码如下：
scatter=Scatter()
scatter.init_opts=opts.InitOpts(width="1600px",height="400px") #创建地图，调整地图大小
for cat, d in df_data.groupby('case'):
    scatter.add_xaxis(d['action'].values.tolist())
    scatter.add_yaxis(cat, d['date'].tolist())
scatter.set_global_opts(tooltip_opts=opts.TooltipOpts(is_show=True),
        xaxis_opts=opts.AxisOpts(name = '主要路径',axislabel_opts=opts.LabelOpts(rotate=45),),
        yaxis_opts=opts.AxisOpts(type_ = 'time'))

scatter.render() #直接jupyter中显示
scatter.render_notebook()
出来的结果：
![image](https://user-images.githubusercontent.com/71600644/94361140-b68a6a00-00e4-11eb-9eb4-b48f510c1f54.png)

原始数据
![image](https://user-images.githubusercontent.com/71600644/94361148-c7d37680-00e4-11eb-82bb-a84972a88537.png)

**Comment by 808bass808** [comment]
参照https://github.com/pyecharts/pyecharts-extras#1-time-series-event
用 xaxis_opts=DateAxisOpts(axis_data=all_dates)解决了

**Comment by 1570709908** [comment]
想请教一下，如果x轴是普通整数，用for循环添加X轴多次后，只显示最后一次的应该使用什么库或者方法呢
