### ISSUE TITLE
含numpy数据的可视化，tolist()造成的问题

### ISSUE THREAD

**Issue by gamersover** [pyecharts/pyecharts#1716]
**问题**
发现有个关于numpy支持的很奇怪问题，画图的时候发现有些时候numpy数据需要tolist()才会正常显示，但有些时候加了tolist()又不正常了

**运行环境（系统环境及 pyecharts 版本）**
win10 vscode+jupyter pyecharts==1.8.1

**代码及截图**
* x，y2变量都没有tolist()，显示正常
```python
x = np.linspace(-2*np.pi, 2*np.pi, 100)
y2 = np.sin(x)
line = (
    Scatter(init_opts=opts.InitOpts(theme=ThemeType.DARK))
    .add_xaxis(x)
    .add_yaxis("", y2, label_opts=opts.LabelOpts(is_show=False))
    )
line.render_notebook()
```
![屏幕截图 2020-09-27 162542](https://user-images.githubusercontent.com/26238198/94360189-26e1bd00-00de-11eb-8fb5-a5dbffde5676.jpg)

* 使用tolist()后，显示不正常
```python
x = np.linspace(-2*np.pi, 2*np.pi, 100)
x = x.tolist()  # tolist()
y2 = np.sin(x)
y2 = y2.tolist() # tolist()
line = (
    Scatter(init_opts=opts.InitOpts(theme=ThemeType.DARK))
    .add_xaxis(x)
    .add_yaxis("", y2, label_opts=opts.LabelOpts(is_show=False))
    )
line.render_notebook()
```
![屏幕截图 2020-09-27 162736](https://user-images.githubusercontent.com/26238198/94360225-65777780-00de-11eb-9c91-4cb879c5d595.jpg)

但是下面却是相反的，加了tolist()才能正常显示
* 没有使用tolist()，显示空白
```python
x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 4])
line = (
    Scatter(init_opts=opts.InitOpts(theme=ThemeType.DARK))
    .add_xaxis(x)
    .add_yaxis("", y, label_opts=opts.LabelOpts(is_show=False))
    )
line.render_notebook()
```
![屏幕截图 2020-09-27 162931](https://user-images.githubusercontent.com/26238198/94360265-a5d6f580-00de-11eb-9171-f864fbb2d55a.jpg)

* 使用tolist()，虽然可以显示，但是好像错位了 :joy:
```python
x = np.array([1, 2, 3, 4])
x = x.tolist()  # tolist()
y = np.array([1, 2, 3, 4])
y = y.tolist() # tolist()
line = (
    Scatter(init_opts=opts.InitOpts(theme=ThemeType.DARK))
    .add_xaxis(x)
    .add_yaxis("", y, label_opts=opts.LabelOpts(is_show=False))
    )
line.render_notebook()
```
![屏幕截图 2020-09-27 163220](https://user-images.githubusercontent.com/26238198/94360334-08c88c80-00df-11eb-8d31-5c77a1fee00d.jpg)

**Comment by hazeccc** [comment]
手动把坐标轴的type_属性指定成'value'试试，不然经常会有各种奇奇怪怪的bug

**Comment by gamersover** [comment]
谢谢:smile:，发现加`type_='value'`的确没这个问题了
