### ISSUE TITLE
PieItem是否可用？

### ISSUE THREAD

**Issue by Akemi-Madoka** [pyecharts/pyecharts#1718]
**问题**
使用PieItem作为数据绘制饼状图时，发现is_selected不生效，并且legend不显示。
查看源码pie.py时发现，判断数据格式为PieItem时，就跳过了所有legend生成。
请问这是故意为之吗？
如果我要使用pie并且让部分数据初始隐藏，除了修改源码有其他办法吗？

**运行环境（系统环境及 pyecharts 版本）**
pycharts版本：1.8.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Akemi-Madoka 
* PieItem 属于试验性功能，暂时还不能使用
