### ISSUE TITLE
pyecharts有没有点击跳转这种功能的实现

### ISSUE THREAD

**Issue by yiguanxian** [pyecharts/pyecharts#1723]
如题

**Comment by yiguanxian** [comment]
如题

**Comment by MeredithChai** [comment]
这种功能应该是需要自行实现的吧...

写js回调函数。你代码实现处把跳转对象传过去，需要自己定义clickEvent与触发交互的控件这样子

**Comment by yiguanxian** [comment]
能提供一个示例吗？我不会js，所以才选用pyecharts来实现的，给个示例也方便我查相关的实现，感谢！！！

**Comment by yiguanxian** [comment]
> 这种功能应该是需要自行实现的吧...
> 
> 写js回调函数。你代码实现处把跳转对象传过去，需要自己定义clickEvent与触发交互的控件这样子

能提供一个示例吗？我不会js，所以才选用pyecharts来实现的，给个示例也方便我查相关的实现，感谢！！！

**Comment by MeredithChai** [comment]
> > 这种功能应该是需要自行实现的吧...
> > 写js回调函数。你代码实现处把跳转对象传过去，需要自己定义clickEvent与触发交互的控件这样子
> 
> 能提供一个示例吗？我不会js，所以才选用pyecharts来实现的，给个示例也方便我查相关的实现，感谢！！！

应该没有pyecharts的，不过[这里](https://echarts.apache.org/zh/api.html#events)有echarts的说明，[这个](https://echarts.apache.org/zh/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA)是详细描述跟小示例。

**Comment by jiaoleixin** [comment]
点击跳转网页吗？可以在title_link里写url实现点击标题跳转。
