### ISSUE TITLE
坐标轴格式（上下标设置、科学计数法）

### ISSUE THREAD

**Issue by MasterYinYin** [pyecharts/pyecharts#1727]
**问题**
是否有可能在使用Line画折线图时，对坐标轴名字的字符串设置上下标，
以及对于value类型的轴设置用科学计数法显示？

**运行环境（系统环境及 pyecharts 版本）**
ubuntu18.04
pyecharts0.5.11

**代码及截图**
（1）上下标设置xaxis_name= V (cm^3)，
其中cm^3是单位，能否添加代码设置字符上标？
（2）科学计数法，有些值过大，如100000000000000，
有没有可能添加代码，使之显示成1.0，在坐标后面添加一个e14?

**Comment by sunhailin-Leo** [comment]
@MasterYinYin 你这个需求得 Echarts 支持才可以

**Comment by TigerHall** [comment]
老哥解决这个问题了没？，还是说直接对着html改😂
