### ISSUE TITLE
pyecharts图表如何更改属性进行自适应浏览器放大缩小

### ISSUE THREAD

**Issue by deletehacker** [pyecharts/pyecharts#1730]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@deletehacker 自行修改模版通过 js 或者 css 进行自适应的配置。目前宽度和高度支持百分比

**Comment by chanajianyu** [comment]
具体如何做2尼
