### ISSUE TITLE
关系图默认放在页面中间，如何使其出现在页面偏上的位置？

### ISSUE THREAD

**Issue by strawberrylunar** [pyecharts/pyecharts#1731]
**问题**
我生成的图是从上到下的一个比较长的图，默认放在页面中间，导致上面很大一块是空白的（调节过画布的大小，似乎没有什么用）。所以是否有其他方法，使其出现在页面偏上的位置？
我查找资料过程中了解到，pyecharts饼图可以通过一个center参数调节图的位置，关系图似乎没有这个参数，求解

**运行环境（系统环境及 pyecharts 版本）**
pyecharts1.8.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@strawberrylunar 可以套一个 Grid 试试看，如果不行的话。再回复～
