### ISSUE TITLE
如何为散点图的每一个(x,y)点添加文字信息

### ISSUE THREAD

**Issue by yangyueren** [pyecharts/pyecharts#1733]
**问题**
x = [90,85,88,89,80]
y = [93,84,86,97,64]

label1 = ['小明‘, '小军‘, '小蓝‘, '小百‘, '小洪‘]
label2 = ['1班‘, '3班‘, '6班‘, '9班‘, '1班‘]

x是语文成绩，y是数学成绩，我希望以x为x轴，y为y轴，绘制散点图，每个点附加label1和lable2的信息，当鼠标点击这个点时会显示对应的labl1和label2的信息，比如点击到(90,93)这个点时，会显示 (小明, 1班) 这样的一个文字框。

我看了官方文档，不太明白如何实现，可否给予一些提示？

**运行环境（系统环境及 pyecharts 版本）**
1.7

**代码及截图**

**Comment by shuaiguoer** [comment]
请问你说的是 图标提示框吗？

**Comment by yangyueren** [comment]
> 请问你说的是 图标提示框吗？

是的，但是我没有找到如何自定义图标提示框里的数据。

**Comment by MeredithChai** [comment]
一种方式是事先把label1, 2要组合显示出来的字符串提前组装好（这里先记为label0吧），然后通过[add_dataset](https://gallery.pyecharts.org/#/Dataset/dataset_bar_1?id=pyecharts-%e4%bb%a3%e7%a0%81-%e6%95%88%e6%9e%9c)方式加载数据。再在.add里声明encode映射，用JsCode()配置set_series_opts里的tooltip_opts的formatter（其实就是写js代码）。这里具体可以参考作者的[这篇](https://zhuanlan.zhihu.com/p/133533187)整理。
