### ISSUE TITLE
建议对set_global_opts函数做如下修改

### ISSUE THREAD

**Issue by youncyb** [pyecharts/pyecharts#1736]
**问题**
两个Bar图在同一行时，可能会导致部分Y轴上的标签显示不完全，这时可以使用grid 选项使整体图形右移一部分，但翻看API后，发现只能用grid布局才能对图形进行移动，如果采用page布局，那么将无法细微修改图形的位置。 
    
**如果可以通过设置全局的options，设置grid选项，那么将可以灵活的修改图形布局**。     

**修改部分如下**：

<img width="1081" alt="图片" src="https://user-images.githubusercontent.com/33374470/97269950-4993fc80-1869-11eb-817f-32edf7f961b6.png">

**运行环境（系统环境及 pyecharts 版本）**
Python 3.7.8

pyecharts                    1.8.1

**代码及截图**
下图中，左侧的是未添加grid，右侧是添加了grid的，两个bar都是`Bar(width='50%')`
<img width="1557" alt="图片" src="https://user-images.githubusercontent.com/33374470/97270302-e8205d80-1869-11eb-84b2-a14728a966c3.png">

**Comment by sunhailin-Leo** [comment]
@youncyb 但是这么做会和 Grid 布局的图有冲突 🤔

**Comment by youncyb** [comment]
@sunhailin-Leo  我单单实验了一下在set_global_opts先设置 pos_left，然后再用grid布局设置，然后grid布局会覆盖之前的设置，其实这应该不算冲突，如果要用grid布局的，就不用在set_global_opts设置。
