### ISSUE TITLE
如何实现X轴的多行标签

### ISSUE THREAD

**Issue by moonlighf** [pyecharts/pyecharts#1741]
**问题**

如何实现X轴的多行标签

**运行环境（系统环境及 pyecharts 版本）**
pyecharts版本：1.8

**代码及截图**

![image](https://user-images.githubusercontent.com/26102415/98788638-28700600-243c-11eb-9198-073f2ea357df.png)

**Comment by sunhailin-Leo** [comment]
@moonlighf  Echarts 目前暂时不支持
