### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by whuhit** [pyecharts/pyecharts#1742]
**问题**
我运行别人1.5.1版本的示例代码，在1.9下报错。请问下，同样是1.几的大版本下，小版本不同代码也不兼容吗？

**运行环境（系统环境及 pyecharts 版本）**

python3.8 pyecharts1.9.0

**代码及截图**

![image](https://user-images.githubusercontent.com/22534064/98886408-fa87d180-24ce-11eb-8d3b-1f7ddda7bbca.png)

**Comment by sunhailin-Leo** [comment]
@whuhit 
* 为什么 Bar 的第一个参数是字符串？这个 init_opts 的参数从 1.x 版本开始就已经改变了，并不是小版本更新带来的差异
