### ISSUE TITLE
标签显示不全

### ISSUE THREAD

**Issue by whuhit** [pyecharts/pyecharts#1743]
**问题**
x轴上标签很长，但是只能显示出来固定长度的一部分，显示不全

**运行环境（系统环境及 pyecharts 版本）**
python3.8 pyecharts1.9.0

**代码及截图**
![image](https://user-images.githubusercontent.com/22534064/98890806-c5cc4800-24d7-11eb-9771-515d2a74ffd8.png)

**Comment by whuhit** [comment]
`
from pyecharts.charts import Bar
from pyecharts import options as opts



bar = Bar()
bar.add_xaxis(["羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "雪纺衫衬衫衬衫衬衫",
               "裤子衬衫衬衫衬衫衬衫", "高衬衫衬衫衬衫跟鞋", "袜子衬衫衬衫衬衫衬衫衬衫"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
bar.set_global_opts(xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=90,vertical_align='middle',margin=5)))
bar.render_notebook()
`

**Comment by whuhit** [comment]
`from pyecharts.charts import Bar
from pyecharts import options as opts



bar = Bar()
bar.add_xaxis(["羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "雪纺衫衬衫衬衫衬衫",
               "裤子衬衫衬衫衬衫衬衫", "高衬衫衬衫衬衫跟鞋", "袜子衬衫衬衫衬衫衬衫衬衫"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
bar.set_global_opts(xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=90,vertical_align='middle',margin=5)))
bar.render_notebook()`

**Comment by whuhit** [comment]
`
from pyecharts.charts import Bar
from pyecharts import options as opts



bar = Bar()
bar.add_xaxis(["羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "雪纺衫衬衫衬衫衬衫",
               "裤子衬衫衬衫衬衫衬衫", "高衬衫衬衫衬衫跟鞋", "袜子衬衫衬衫衬衫衬衫衬衫"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
bar.set_global_opts(xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=90,vertical_align='middle',margin=5)))
bar.render_notebook()
`

**Comment by whuhit** [comment]
`
from pyecharts.charts import Bar
from pyecharts import options as opts



bar = Bar()
bar.add_xaxis(["羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "雪纺衫衬衫衬衫衬衫",
               "裤子衬衫衬衫衬衫衬衫", "高衬衫衬衫衬衫跟鞋", "袜子衬衫衬衫衬衫衬衫衬衫"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
bar.set_global_opts(xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=90)))
bar.render_notebook()
`

**Comment by vincent8877** [comment]
hi,whuhit：
我昨天也遇到同样的问题了，可以使用Grid来解决，完整代码如下：




from pyecharts.charts import Bar,Grid
from pyecharts import options as opts


# gird解决x轴文字太长显示不下的问题
grid = Grid()

bar = Bar()
bar.add_xaxis(["羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "雪纺衫衬衫衬衫衬衫",
"裤子衬衫衬衫衬衫衬衫", "高衬衫衬衫衬衫跟鞋", "袜子衬衫衬衫衬衫衬衫衬衫"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
bar.set_global_opts(xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=90)))

grid.add(bar, grid_opts=opts.GridOpts(pos_bottom="35%"))
grid.render_notebook()
grid.render("test.html")  #输出到网页

**Comment by whuhit** [comment]
> hi,whuhit：
> 我昨天也遇到同样的问题了，可以使用Grid来解决，完整代码如下：
> 
> from pyecharts.charts import Bar,Grid
> from pyecharts import options as opts
> 
> grid = Grid()
> 
> bar = Bar()
> bar.add_xaxis(["羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "羊毛衫衬衫衬衫衬衫衬衫衬衫衬衫", "雪纺衫衬衫衬衫衬衫",
> "裤子衬衫衬衫衬衫衬衫", "高衬衫衬衫衬衫跟鞋", "袜子衬衫衬衫衬衫衬衫衬衫"])
> bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
> bar.set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
> bar.set_global_opts(xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=90)))
> 
> grid.add(bar, grid_opts=opts.GridOpts(pos_bottom="35%"))
> grid.render_notebook()
> grid.render("test.html")

/::D  it works,非常感谢

**Comment by zhouxiang93123** [comment]
确实有用
