### ISSUE TITLE
关于overlap问题

### ISSUE THREAD

**Issue by Fyyyyy158** [pyecharts/pyecharts#1744]
**问题**

当使用Bar.overlap(line)的时候，如果Line的轴和左边差不多，会导致折线和Bar产生重合问题，但是折线是呈现在Bar图层下面，会导致折线的标签显示不完全，被挡在Bar后面，而且折线好多配置设置之后，并不会发生更改，eg：颜色

我把折线设置颜色后，并不会发生更改，只要两个bar的颜色自定义之后，折线的颜色就是一直是红色。
能否把折线显示在图层前面呢？

下面图如果更改右侧轴，折线数据将完全显示不了，有人可以帮忙解决下吗？

**运行环境（系统环境及 pyecharts 版本）**

Python 3.7 
pyecharts 1.9.0

**代码及截图**

    v1 = [1.51,1.22,1.38,1.37,1.33,1.62,1.47,1.66,1.13,1.26]
    v2 = [1.51,1.22,1.38,1.37,1.33,1.62,1.47,1.64,1.13,1.26]
    v3 = [2.13,1.6,1.25,1.45,1.34,1.83,1.31,1.68,1.18,1.19]
    x = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
    def get_overlap(v1,v2,v3,x):
        bar = (
            Bar(init_opts=opts.InitOpts(width='900px',height='400px', bg_color='#F5F5F5'))
            .add_xaxis(x)
            .add_yaxis(
                'Bar1',
                v2,
                color='#f0a787'
            )
            .add_yaxis(
                'Bar2',
                v3,
                color='#20B2AA'
            )
            .extend_axis(
                yaxis=opts.AxisOpts(
                    name = 'Ratio',
                    min_=0,
                    max_=2.5,
                    axislabel_opts=opts.LabelOpts(formatter='{value}')
                    )
                )
            .set_series_opts(
                label_opts=opts.LabelOpts(is_show=True,color='black')
            )
            .set_global_opts(
                title_opts=opts.TitleOpts(title='Overlap', subtitle='Test'),
                xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=0,font_size=16)),
                tooltip_opts=opts.TooltipOpts(trigger='axis', axis_pointer_type='cross')
            )
        )

        line = (
            Line(init_opts=opts.InitOpts())
            .add_xaxis(x)
            .add_yaxis(
                'Line',
                v1,
                linestyle_opts=opts.LineStyleOpts( width=3,type_="solid"),
                yaxis_index=1,
                color='blue'
            )
            .set_series_opts(
                label_opts=opts.LabelOpts(is_show=True)
            )
        )

        bar.overlap(line)
        return bar.render_notebook()

![image](https://user-images.githubusercontent.com/58002385/98902165-1f407100-24f0-11eb-938d-4fd12c4da8a1.png)

**Comment by sunhailin-Leo** [comment]
@Fyyyyy158 
* Q: 折线显示在图层前面
* A: 有参数 `z` 和 `z_level` 可以设置
