### ISSUE TITLE
散点图的symbol形状有哪些

### ISSUE THREAD

**Issue by q35486** [pyecharts/pyecharts#1745]
from pyecharts import options as opts
from pyecharts.charts import Bar,Scatter
import numpy as np
x=np.linspace(0,10,30)
y1=np.sin(x)
y2=np.cos(x)
scatter=Scatter()
scatter.add_xaxis(xaxis_data=x)
scatter.add_yaxis(series_name='y=sin(x)',y_axis=y1,
                 label_opts=opts.LabelOpts(is_show=False),#设置数据是否展示
                 symbol_size=30,#控制散点图点的大小
                 symbol=?????,#散点形状
                 )
scatter.render_notebook()
scatter.render("a.html")

**Comment by MeredithChai** [comment]
[这里](https://pyecharts.org/#/zh-cn/rectangular_charts?id=scatter%ef%bc%9a%e6%95%a3%e7%82%b9%e5%9b%be)写的清清楚楚明明白白。
