### ISSUE TITLE
散点图如何使用自定义符号作为点

### ISSUE THREAD

**Issue by q35486** [pyecharts/pyecharts#1746]
想使用自定义符号作为点的形状

**Comment by sunhailin-Leo** [comment]
@q35486 文档有写明白，如何自定义

**Comment by q35486** [comment]
> @ q35486文档有写明白，如何自定义

???我自己没有写过怎么自定义啊

**Comment by q35486** [comment]
> @ q35486文档有写明白，如何自定义

我的意思是使用@#这种自定义的符号作为点的形状

**Comment by sunhailin-Leo** [comment]
@q35486 我的意思是：文档里面有说明如何使用自定义形状
