### ISSUE TITLE
如何箱图添加任意固定值标记线非最大最小平均值

### ISSUE THREAD

**Issue by artherwhy** [pyecharts/pyecharts#175]
默认标记线只能选最大最小平均值，我想添加其他固定值标记先

![default](https://user-images.githubusercontent.com/31639566/30322649-c9e91092-97ec-11e7-86a9-2ff757df08e7.PNG)

**Comment by artherwhy** [comment]
font{
        line-height: 1.7;
    }


    
好的谢谢



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.7;
        }
    

    
        font{
            line-height: 1.5;
        }
    

    
        font{
            line-height: 1.5;
        }
    
张宁宇邮 箱：zhangningyu@jiuqi.com.cn 



                



    在2017年9月12日 19:20，chenjiandongx<notifications@github.com> 写道： 


目前标记线和标记点都只能是 最大值/最小值/平均値，后续版本可以考虑自定义

**Comment by artherwhy** [comment]
font{
        line-height: 1.7;
    }


    
如何调配色方案，有没有代码？



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.7;
        }
    

    
        font{
            line-height: 1.5;
        }
    

    
        font{
            line-height: 1.5;
        }
    
张宁宇手 机：18610067074邮 箱：zhangningyu@jiuqi.com.cn 



                



    在2017年9月12日 19:20，chenjiandongx<notifications@github.com> 写道： 


目前标记线和标记点都只能是 最大值/最小值/平均値，后续版本可以考虑自定义

**Comment by artherwhy** [comment]
font{
        line-height: 1.7;
    }


    
箱图，箱体的颜色可以调吗？有没有代码？



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.7;
        }
    

    
        font{
            line-height: 1.5;
        }
    

    
        font{
            line-height: 1.5;
        }
    
张宁宇北京久其软件股份有限公司 大数据研究院公司地址：北京海淀区文慧园路甲12号手 机：18610067074邮 箱：zhangningyu@jiuqi.com.cn 



                



    在2017年9月12日 19:20，chenjiandongx<notifications@github.com> 写道： 


目前标记线和标记点都只能是 最大值/最小值/平均値，后续版本可以考虑自定义

**Comment by chenjiandongx** [comment]
label_color
