### ISSUE TITLE
大佬，新版本怎么取消事件处理函数了？

### ISSUE THREAD

**Issue by caotao0918** [pyecharts/pyecharts#1752]
**问题**

大佬，新版本怎么取消事件处理函数了？

**运行环境（系统环境及 pyecharts 版本）**

V1.7.0

**代码及截图**

**使用 JavaScript 事件处理函数**
**Echarts 本身提供了 api/events 事件处理函数，主要通过 on 方式实现。**

pyecharts 根据官方提供的 events 列表，提供了如下全局事件名变量。位于 pyecharts.echarts.events 模块中。

**Comment by caotao0918** [comment]
上面那个是老版本就有的，怎么新版本没有了呢？

**Comment by Kimichenren** [comment]
同问，请问大佬你是怎么解决这个问题的？感谢！

**Comment by sunhailin-Leo** [comment]
@caotao0918 目前版本已经取消了，后续版本再考虑是否引入，毕竟涉及的影响点有点多
