### ISSUE TITLE
Echarts 5.X 版本兼容

### ISSUE THREAD

**Issue by sunhailin-Leo** [pyecharts/pyecharts#1754]
* Echarts 5.0 版本更新说明: https://github.com/apache/incubator-echarts/releases/tag/5.0.0
* pyecharts 后续也会兼容最新版 - developing 🔨

**Comment by sunhailin-Leo** [comment]
* Trace Branch: [update-echarts5-config](https://github.com/pyecharts/pyecharts/tree/update-echarts5-config)

**Comment by austingg** [comment]
any roadmap for pyecharts support echarts 5.0 ?

**Comment by sunhailin-Leo** [comment]
@austingg Coming soon.
