### ISSUE TITLE
jupyterlab显示空白

### ISSUE THREAD

**Issue by kerwinxu** [pyecharts/pyecharts#1756]
**问题**

**运行环境（系统环境及 pyecharts 版本）**
jupyterlab : 2.2.6
jupyter-echarts-pypkg              0.1.5
pyecharts                          1.9.0
pyecharts-jupyter-installer        0.0.3
pyecharts-snapshot                 0.2.0

**代码及截图**

%config InlineBackend.figure_format = 'svg'
%matplotlib inline
import numpy as np
import pandas as pd
import os
import datetime
from pyecharts.charts import Line # 折线图
from pyecharts.charts import Bar # 柱状图
from pyecharts.charts import Pie # 饼状图 
from pyecharts.charts import Grid
from pyecharts import options as opts 
from pyecharts.render import make_snapshot # 导出图片
from snapshot_selenium import snapshot

from pyecharts.globals import CurrentConfig ,NotebookType
CurrentConfig.NotebookType = NotebookType.JUPYTER_LAB
CurrentConfig.ONLINE_HOST

from pyecharts.faker import Faker

bar = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(title_opts=opts.TitleOpts(title="Grid-Bar"))
)
line = (
    Line()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Grid-Line", pos_top="48%"),
        legend_opts=opts.LegendOpts(pos_top="48%"),
    )
)

grid = (
    Grid()
    .add(bar, grid_opts=opts.GridOpts(pos_bottom="60%"))
    .add(line, grid_opts=opts.GridOpts(pos_top="60%"))
)
grid.render()

grid.load_javascript()

grid.render_notebook()

**Comment by sunhailin-Leo** [comment]
@kerwinxu 
* Demo: https://pyecharts.org/#/zh-cn/notebook?id=jupyter-lab
