### ISSUE TITLE
隐藏没有数据的国家或者给这些国家画斜线

### ISSUE THREAD

**Issue by Brucewuzhang** [pyecharts/pyecharts#1759]
**问题**
我想画世界地图的数据，但是只有50个国家的数据。我现在想只在地图上显示这50个国家，或者把其他国家从地图上划去，有什么办法可以做到吗。多谢。我想这么做是因为我只会要打印出来，只能用黑白的。

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Brucewuzhang 
* 暂时无解
