### ISSUE TITLE
heatmap中如何在“图表范围内”加底图（地图）

### ISSUE THREAD

**Issue by alexxfxiao** [pyecharts/pyecharts#1760]
**问题**
底图的设置一般是走bg_color，且add_js_funcs里new Image()..
但是如果想设置这个地图的相对位置和大小（例如将底图向右偏移100px，），
让地图在【有热力图的范围内】显示，此时底图其实就是地图，例如游戏内的地图。
应该怎么做呢？
尝试了js的几个参数，都无效。。

**运行环境（系统环境及 pyecharts 版本）**
python3.9，pyecharts最新版本，win64

**代码及截图**

import random

from pyecharts import options as opts
from pyecharts.charts import HeatMap
from pyecharts.faker import Faker
from pyecharts.commons.utils import JsCode
from pyecharts.components import Image
from pyecharts.options import ComponentTitleOpts

def getnum(i,j):
    if random.randint(0,100)<90:
        return 0
    else:
        return random.randint(0,100)
entitynum = []
for i in range(75):
    for j in range(75):
        k = getnum(i,j)
        entitynum.append([i,j,k])

entitynum = [[d[1], d[0], d[2] or "-"] for d in entitynum]

svrinstid = [[i, j, (int(i/25)+1)*10] for i in range(75) for j in range(75)]
xrange = [i for i in range(75)]
zrange = [i for i in range(75)]

c = (
    HeatMap(
        init_opts=opts.InitOpts(width="1200px", height="800px", theme="light",
            bg_color={"type": "pattern", "image": JsCode("img"), "repeat":"no-repeat"}, ))
        #, bg_color="rgb(80,163,186)"))
    .add_xaxis(xrange)
    .add_yaxis("entitynum", zrange, entitynum)
    .add_yaxis("svrinstid", zrange, svrinstid)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="HeatMap-基本示例", title_textstyle_opts=opts.TextStyleOpts(color="white")),
        visualmap_opts=opts.VisualMapOpts(),
        datazoom_opts =opts.DataZoomOpts(True, "inside"),
        tooltip_opts=opts.TooltipOpts(formatter="{a}---{c}"),
        toolbox_opts=opts.ToolboxOpts(),
    )
)
c.add_js_funcs(
    """   
    var img = new Image();    
    
    img.onload = function() {
        alert(this.width + 'x' + this.height);
    }
    img.src = 'bigworldmap.png'; 
    """
)
c.render("heatmap_base.html")

![image](https://user-images.githubusercontent.com/8385013/102065358-6abda600-3e33-11eb-8168-931076bae31b.png)

**Comment by sunhailin-Leo** [comment]
@alexxfxiao 
* 目前看上去是没有办法的，除非用 canvas 加图层。具体的操作，也很难给出

**Comment by dofine** [comment]
https://www.isqqw.com/echartsdetail?id=19010  是不是可以参考这个实现呢？
