### ISSUE TITLE
opts.BarItem的用法能给个例子吗？

### ISSUE THREAD

**Issue by qichikimochi** [pyecharts/pyecharts#1761]
**问题**
opts.BarItem的用法能给个例子吗？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@qichikimochi 
* 目前先看着仓库 `test` 目录的 test_bar 中的 BarItem 的代码使用，也可以参照源码的 type hints 使用
