### ISSUE TITLE
请问怎么安装0.4.1版本的pyecharts呢？

### ISSUE THREAD

**Issue by guosijia** [pyecharts/pyecharts#1763]
您好，之前我们的项目中用到了0.4.1版本的pyecharts，现在要迁移，发现通过pip install的方式安装不了0.4.1的包，有什么办法安装之前版本的包吗//？

➜  ~ pip3 install pyecharts==0.4.1
Collecting pyecharts==0.4.1
  Downloading https://files.pythonhosted.org/packages/ea/db/e7a14152f5d44d11694f3acbaf55b4f6d40434e646a88fc89d29ea1d73eb/pyecharts-0.4.1.tar.gz (107kB)
     |████████████████████████████████| 112kB 1.1MB/s
Requirement already satisfied: pillow in /usr/local/lib/python3.7/site-packages (from pyecharts==0.4.1) (7.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/site-packages (from pyecharts==0.4.1) (2.10)
Requirement already satisfied: future in /usr/local/lib/python3.7/site-packages (from pyecharts==0.4.1) (0.18.2)
ERROR: Could not find a version that satisfies the requirement jupyter-echarts-pypkg==0.1.0 (from pyecharts==0.4.1) (from versions: 0.1.1, 0.1.2, 0.1.4, 0.1.5)
ERROR: No matching distribution found for jupyter-echarts-pypkg==0.1.0 (from pyecharts==0.4.1)

**Comment by sunhailin-Leo** [comment]
@guosijia 
`pip3 install pyecharts==0.4.1`
