### ISSUE TITLE
grid 画三张Scatter图，但是数据量较大，显示不完全

### ISSUE THREAD

**Issue by xlyy** [pyecharts/pyecharts#1764]
**问题**
grid 联动三张Scatter图，但是数据量较大，显示不完全

**运行环境（系统环境及 pyecharts 版本）**

win10，pyecharts 1.8.1

**代码及截图**

scatter = (Scatter(init_opts=opts.InitOpts(
            animation_opts=opts.AnimationOpts(animation=False)))
        .set_colors(colors)
        .set_global_opts(
        xaxis_opts=opts.AxisOpts(
            type_="value", splitline_opts=opts.SplitLineOpts(is_show=True)
        ),
        yaxis_opts=opts.AxisOpts(
            type_="value",
            axistick_opts=opts.AxisTickOpts(is_show=False),
            splitline_opts=opts.SplitLineOpts(is_show=True),
        ),
        toolbox_opts=opts.ToolboxOpts(),
        datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside", xaxis_index=[0, 1, 2])],
        legend_opts=opts.LegendOpts(type_="scroll", pos_left="legft", pos_top="15%", orient="vertical"
                                    , is_show=True))
    )
    for i in data_final['type'].unique():
        data_i = data_final[data_final['type'] == i]
        marker = MARKER_MAP.get(i, '_')
        rotate = ROTATE_SIZE.get(i, 0)
        size = SIZE_MAP.get(i, 10)
        _scatter = (Scatter()
            .add_xaxis(list(data_i['index']))
            .add_yaxis(io, list(data_i[col]), label_opts=opts.LabelOpts(is_show=False),
                       symbol=marker, symbol_rotate=rotate, symbol_size=size)
        )
        scatter.overlap(_scatter)
grid = (
        Grid(init_opts=opts.InitOpts(animation_opts=opts.AnimationOpts(animation=False)))  # page_title设置网页标题
        .add(latency, grid_opts=opts.GridOpts(pos_top="1%", height="25%"))
        .add(Ba, grid_opts=opts.GridOpts(pos_top="33%", height="25%"))
        .add(size, grid_opts=opts.GridOpts(pos_top="66%", height="25%"))
    )
![image](https://user-images.githubusercontent.com/17964006/102861527-ca870300-446a-11eb-8913-603b63919d07.png)

**Comment by sunhailin-Leo** [comment]
@xlyy
* 这个属于数据范畴的问题，建议从数据分布入手

**Comment by xlyy** [comment]
> @xlyy
> 
> * 这个属于数据范畴的问题，建议从数据分布入手

这个不是数据问题啊，我把数据量变少，整个数据就有了，不是数据分布问题啊

**Comment by sunhailin-Leo** [comment]
@xlyy 
* 麻烦，详细描述一下你的问题。`数据量较大，显示不完全` 这个描述不够具体

**Comment by xlyy** [comment]
> @xlyy
> 
> * 麻烦，详细描述一下你的问题。`数据量较大，显示不完全` 这个描述不够具体

我这幅图，用grid联动三幅图，每一幅图有大概十几种类型，我用了overlap将每种类型的scatter的点叠加上去，所以导致数据量很大，现在出现的情况是，如果我在x轴用datazoom拉全部数据，就会出现第一张图只能显示一个类型，第二张图完全无法显示的情况，如果我用datazoom将范围调小到一定程度，才会显示正常
