### ISSUE TITLE
grid 画三张Scatter图，但是数据量较大，显示不完全，非数据分布问题

### ISSUE THREAD

**Issue by xlyy** [pyecharts/pyecharts#1765]
**问题**
grid 联动三张Scatter图，但是数据量较大，显示不完全，不是数据分布问题，因为当我将zoomdata调小后可以显示全部，应该是数据量过多，scatter显示不出来，关闭了动画也没有用

**运行环境（系统环境及 pyecharts 版本）**
win10，pyecharts 1.8.1

**代码及截图**
scatter = (Scatter(init_opts=opts.InitOpts(
animation_opts=opts.AnimationOpts(animation=False)))
.set_colors(colors)
.set_global_opts(
xaxis_opts=opts.AxisOpts(
type_="value", splitline_opts=opts.SplitLineOpts(is_show=True)
),
yaxis_opts=opts.AxisOpts(
type_="value",
axistick_opts=opts.AxisTickOpts(is_show=False),
splitline_opts=opts.SplitLineOpts(is_show=True),
),
toolbox_opts=opts.ToolboxOpts(),
datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside", xaxis_index=[0, 1, 2])],
legend_opts=opts.LegendOpts(type_="scroll", pos_left="legft", pos_top="15%", orient="vertical"
, is_show=True))
)
for i in data_final['type'].unique():
data_i = data_final[data_final['type'] == i]
marker = MARKER_MAP.get(i, '_')
rotate = ROTATE_SIZE.get(i, 0)
size = SIZE_MAP.get(i, 10)
_scatter = (Scatter()
.add_xaxis(list(data_i['index']))
.add_yaxis(io, list(data_i[col]), label_opts=opts.LabelOpts(is_show=False),
symbol=marker, symbol_rotate=rotate, symbol_size=size)
)
scatter.overlap(_scatter)
grid = (
Grid(init_opts=opts.InitOpts(animation_opts=opts.AnimationOpts(animation=False))) # page_title设置网页标题
.add(latency, grid_opts=opts.GridOpts(pos_top="1%", height="25%"))
.add(Ba, grid_opts=opts.GridOpts(pos_top="33%", height="25%"))
.add(size, grid_opts=opts.GridOpts(pos_top="66%", height="25%"))
)
![image](https://user-images.githubusercontent.com/17964006/102864833-c8737300-446f-11eb-88d7-22076f9e8e9b.png)

**Comment by sunhailin-Leo** [comment]
@xlyy 
* 你是想描述哪张图显示不完全？第二张图？

**Comment by xlyy** [comment]
> @xlyy
> 
> * 你是想描述哪张图显示不完全？第二张图？

是的，我就想描述第二张图没有办法显示，但是如果我用datazoom将范围调小到一定程度，就会显示正常，我这幅图，用grid联动三幅图，每一幅图有大概十几种类型，我用了overlap将每种类型的scatter的点叠加上去，所以导致数据量很大，如果我在datazoom范围比较大，就会显示不出来

**Comment by sunhailin-Leo** [comment]
@xlyy 
* 能截个图看一下显示出来的结果？

**Comment by xlyy** [comment]
@sunhailin-Leo 


![截图](https://user-images.githubusercontent.com/17964006/102971146-c4108e00-4533-11eb-8d3c-31cfcc294418.JPG)

**Comment by sunhailin-Leo** [comment]
@xlyy 
* 如果把 datazoom 去掉能显示嘛？

**Comment by xlyy** [comment]
@sunhailin-Leo 
不能，感觉一直在加载，但我已经设置 关闭了动画animation_opts=opts.AnimationOpts(animation=False)
