### ISSUE TITLE
Geo()&Map()使用问题

### ISSUE THREAD

**Issue by jiaoleixin** [pyecharts/pyecharts#1769]
您好！
之前提问过关于Geo和Map的使用问题，略有所懂，感谢！
请问我想要在Map增加轨迹线是否可以实现？即能否可以将下面两图叠加显示：

![屏幕截图 2020-12-24 153209](https://user-images.githubusercontent.com/50431207/103071682-136fc080-45ff-11eb-8507-154bc9c27100.png)
![屏幕截图 2020-12-24 154053](https://user-images.githubusercontent.com/50431207/103071698-1f5b8280-45ff-11eb-9f17-1ddd9b7323ba.png)

#1762

**Comment by jiaoleixin** [comment]
我注意到在官方文档里写明：
    # Geo 图类型，有 scatter, effectScatter, heatmap, lines 4 种，建议使用：
    # from pyecharts.globals import GeoType
    # GeoType.GeoType.EFFECT_SCATTER，GeoType.HEATMAP，GeoType.LINES
是在geo坐标系里只能使用这四种图形吗？

**Comment by jiaoleixin** [comment]
有没有曲线救国的法子啊😢

**Comment by jiaoleixin** [comment]
By the way, 在使用Geo()绘图后想使用TimeLine控件集成多个图，当设置type_=ChartType.HEATMAP时发现无法正常显示。
求解？
我才用的pyecharts版本为1.9.0

**Comment by sunhailin-Leo** [comment]
> 我注意到在官方文档里写明：
> # Geo 图类型，有 scatter, effectScatter, heatmap, lines 4 种，建议使用：
> # from pyecharts.globals import GeoType
> # GeoType.GeoType.EFFECT_SCATTER，GeoType.HEATMAP，GeoType.LINES
> 是在geo坐标系里只能使用这四种图形吗？

* 目前是的

**Comment by jiaoleixin** [comment]
好吧，谢谢。😵
