### ISSUE TITLE
折线图如何让legend标签居右且双排显示？

### ISSUE THREAD

**Issue by dbsxdbsx** [pyecharts/pyecharts#1770]
python:3.7
pyechart:1.9.0

由于我的折线图有很多标签，所有我想把它放在右边显示，但目前这种做法只能显示n行1列，多余的就直接被截断了：
```
    line1.set_global_opts(
        title_opts=opts.TitleOpts(title="对数轴示例", pos_left="center"),
        legend_opts=opts.LegendOpts(orient='horizontal', pos_right="right"),
....
)
```

**Comment by sunhailin-Leo** [comment]
@dbsxdbsx 
* 可以把 legend 设置成滚动模式

**Comment by dbsxdbsx** [comment]
@sunhailin-Leo ,如何设成滚动模式？

**Comment by sunhailin-Leo** [comment]
@dbsxdbsx 
* 文档一目了然：https://pyecharts.org/#/zh-cn/global_options?id=legendopts%ef%bc%9a%e5%9b%be%e4%be%8b%e9%85%8d%e7%bd%ae%e9%a1%b9
