### ISSUE TITLE
官方示例markpoint显示不了，x，y值有问题

### ISSUE THREAD

**Issue by liuweidong88** [pyecharts/pyecharts#1771]
**问题**

官方示例markpoint显示不了，x，y值有问题。看了下源码应该是xAxis=1,yAxis=1.5这样才能显示。 x=1, y=-1.5是显示不出来这个markpoint的

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
 markpoint_opts=opts.MarkPointOpts(
            data=[opts.MarkPointItem(value=-2, name="周最低", x=1, y=-1.5)]
        ),

**Comment by sunhailin-Leo** [comment]
@liuweidong88 
* 还有另外两个参数可以试试
