### ISSUE TITLE
visualmap_opts使用问题

### ISSUE THREAD

**Issue by jiaoleixin** [pyecharts/pyecharts#1772]
您好！我在使用set_global_opts(visualmap_opts)来设置热力图的颜色显示时，由于使用global_opts导致所有图的颜色都映射成热力图的颜色。能否保持饼图自己之前的颜色而不影响热力图的显示？
绘制效果如下图所示：
![image](https://user-images.githubusercontent.com/50431207/103183239-fb908900-48eb-11eb-870f-350281f5ab9d.png)

**Comment by sunhailin-Leo** [comment]
@jiaoleixin 
* 如果可以的话，贴一下代码

**Comment by jiaoleixin** [comment]
def COVID_TimePath() -> Timeline:
    t = Timeline(init_opts=opts.InitOpts(width='98vw', height="92vh", theme='dark'))
    for time, grp in data:
        start, ending = Points(grp).points_list()
        COVIDTimePath = (
            Geo()
                #  .add_schema(baidu_ak="ILFKGtfnpZj6VhGXoDKlf8UfEXVyAyfv", center=[99, 38], zoom=7)  # 视点中心：武汉
                .add_schema(
                maptype="china",
                itemstyle_opts=opts.ItemStyleOpts(color="#2f4f4f", border_color="#50aa51"),
                # layout_center=['100%', '40%'],
                layout_size=0.7
            )
                .add(
                "出发地",
                start,
                type_=ChartType.EFFECT_SCATTER,
                color="red",
                symbol_size=7,
                # formatter为标签内容格式器{a}：系列名;{b}：数据名;{c}：数值数组也可以是回调函数
                label_opts=opts.LabelOpts(formatter=JsCode(
                                                                   """function(params) {
                        if ('value' in params.data) {
                            return params.data.value[2] + ': ' + params.data.value[0];
                        }
                    }"""
                ))
            )
                .add(
                "终止地",
                ending,
                type_=ChartType.EFFECT_SCATTER,
                color="cyan",
                symbol_size=7,
                label_opts=opts.LabelOpts(formatter='{b}:{c}')
            )
                .add(
                "geo",
                [list(z) for z in zip(Faker.provinces, Faker.values())],
                type_=ChartType.HEATMAP,
            )

                .add(
                '患者迁徙路线路线',
                Lines(grp).lines_list(),
                type_='lines',
                symbol_size=7,
                effect_opts=opts.EffectOpts(symbol=SymbolType.ARROW, symbol_size=4, color="#ffd700"),
                linestyle_opts=opts.LineStyleOpts(curve=0.4, opacity=0.8, color='#ff73b3'),  # ,type_='dashed'
            )
                .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
                .set_global_opts(title_opts=opts.TitleOpts(title=str(time) + "患者迁移时空轨迹图",
                                                           subtitle='--By 可视化研究株式会社',
                                                           title_textstyle_opts=opts.TextStyleOpts(
                                                               font_size=25, color="rgba(255,255,255, 0.9)"), ),
                                 toolbox_opts=opts.ToolboxOpts(),
                                 tooltip_opts=opts.TooltipOpts(is_show=True),
                                 visualmap_opts=opts.VisualMapOpts(
                                     is_calculable=True,
                                     pos_left="15",
                                     pos_top="bottom",
                                     range_text=["High", "Low"],
                                     range_color=["lightskyblue", "yellow", "orangered"],
                                     # textstyle_opts=opts.TextStyleOpts(color="#ddd"),
                                     min_=30,
                                     max_=150
                                 )
                                 )
        )

        COVID_Pie = (
            Pie()
                .add(
                "患者迁徙交通方式",
                list(pd.value_counts(grp['交通工具']).to_dict().items()),
                radius=["10%", "20%"],
                center=["12%", "78%"],
                rosetype="radius",
                # radius：扇区圆心角展现数据的百分比，半径展现数据的大小
                # label_opts=opts.LabelOpts(is_show=False)
            )
                .set_global_opts(
                legend_opts=opts.LegendOpts(is_show=False),
                toolbox_opts=opts.ToolboxOpts(),
                tooltip_opts=opts.TooltipOpts(is_show=True, formatter="{b} {d}%"),
                datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside")]
            )
        )
        COVID_Grid = (
            Grid()
               # .add(COVID_Bar, grid_opts=opts.GridOpts(pos_top="65%", pos_left="80%"))
                .add(COVIDTimePath, grid_opts=opts.GridOpts())
                .add(COVID_Pie, grid_opts=opts.GridOpts(pos_top="50%", pos_right="80%"))
                .add(COVID_Liquid1, grid_opts=opts.GridOpts(pos_top="50%", pos_right="80%")).add(COVID_Liquid2, grid_opts=opts.GridOpts(pos_top="50%", pos_right="80%"))
        )
        t.add(COVID_Grid, time)
    return t

代码如上，visualmap只在Geo()里写了，但是在global_opts中。导致饼图的颜色也映射成热力图的颜色，甚至可以通过色带控制图上所有图形的展示....
By the way，在Liquid()中并未看到控制水球图大小，波浪的参数，center参数似乎只能改变水球的位置，怎样把水球图变小？救救孩子~😥

**Comment by sunhailin-Leo** [comment]
@jiaoleixin 
* 麻烦把 markdown 代码格式修改一下。
* Liquid 的 API 比较少：https://github.com/ecomfe/echarts-liquidfill

**Comment by MeredithChai** [comment]
@jiaoleixin 

grid绘制是会有这样的问题。生成的html代码当中可以发现，先设置的global_opts会覆盖全局的配置，而后者会失语。

**Comment by jiaoleixin** [comment]
@MeredithChai 
对啊，我确实理解到了global_opts会覆盖全局配置，grid“组合”图表其实还只是一个界面，所以虽然其中的每个图表可以写global_opts，但会引起覆盖。
我尝试使用page来组合图表，之前未作尝试是因为其割裂图面整体配置，我需要一张“地图”作为底图。
而page应该更像Tableau 中的仪表板。
谢谢！

**Comment by jiaoleixin** [comment]
@sunhailin-Leo 
我注意到了echarts.js中Liquid 提供的API，但并未在pyecharts中发现对应的参数接口。是我没发现吗。。。😅
https://github.com/ecomfe/echarts-liquidfill中的功能pyecarts均有实现？

**Comment by sunhailin-Leo** [comment]
@jiaoleixin 
* 你说的 `水球图大小，波浪的参数` 这个在 liquid 里面有嘛？

**Comment by jiaoleixin** [comment]
@sunhailin-Leo 
有的嗷~，您看：https://github.com/ecomfe/echarts-liquidfill#api
![屏幕截图 2021-01-16 194518](https://user-images.githubusercontent.com/50431207/104811014-9f0df300-5833-11eb-8b17-89757d4e2e46.png)
由于没能找到pyecharts的liquid相关接口，我选择了曲线救国方式，将渲染后的html文件直接修改。实验成功！！！
不管怎样，我已经写完数据可视化大作业了！🎉🎉🎉感谢pyecharts团队，Respect！
![屏幕截图 2021-01-16 194235](https://user-images.githubusercontent.com/50431207/104811102-2eb3a180-5834-11eb-83f8-57f41bd9b9cb.png)

**Comment by sunhailin-Leo** [comment]
@jiaoleixin 
* 👍  如果可以的话，可以分享一下你的代码嘛？我会贴在 gallery 中。当然，你给 pyecharts-gallery 仓库提 MR 也是可以的。
