### ISSUE TITLE
树形图TreeItem的节点样式设置无效

### ISSUE THREAD

**Issue by xpzhang** [pyecharts/pyecharts#1773]
**问题**
我想给树形图中某些节点设置不同的标签样式，或者不同的Symbol，
我看TreeItem中有个label_opts参数，我尝试把其中一个节点的标签颜色改成红色，但是写进data里以后似乎没有起到作用，不知道是不是写的方式不对？

**运行环境（系统环境及 pyecharts 版本）**

MacOS 11.0
python3.6.7
pyecharts 1.9.0

**代码及截图**

（插入代码显示的格式怎么调都调不好，抱歉）

`data = [
    {
        "children": [
            {"name": "B"},
            {
                "children": [{"children": [{"name": "I"}], "name": "E"}, {"name": "F"}],
                "name": "C",
            },
            {
                "children": [
                    {"children": [{"name": "J","value":999,"label_opts":{"is_show":True,"color":"red"}}, {"name": "K"}], "name": "G"},
                    {"name": "H"},
                ],
                "name": "D",
            },
        ],
        "name": "A",
    }
]`

`c = (
    Tree(init_opts=opts.InitOpts(width="1400px", height="800px"))
    .add(
        series_name="",
        data=data,
        pos_top="8%",
        pos_bottom="8%",
        layout="radial",
        #symbol="emptyCircle",
        initial_tree_depth=2,
        symbol_size=5,
        #label_opts=opts.LabelOpts()
        # label_opts=opts.LabelOpts(
        #     is_show = True,
        #     color = 'red',
        #     )
        #leaves_label_opts=[data]
    )
    .set_global_opts(
        tooltip_opts=opts.TooltipOpts(trigger="item", trigger_on="mousemove")
    )

)
c.render("tree.html")`

**Comment by sunhailin-Leo** [comment]
@xpzhang 
* 如果用 RGB 编码呢？比如 `#fff` 这种？

**Comment by xpzhang** [comment]
@sunhailin-Leo 
试了一下也不行，不仅是color，似乎 font_size 和 is_show = False 设置了也不起作用

**Comment by sunhailin-Leo** [comment]
@xpzhang 
* 试一下 TreeItem

**Comment by Syuukakou** [comment]
```
plot_data = {"name": "Root", "children": []}
# plot_data = opts.TreeItem({"name": hash_code, "children": []})
# create data
time_dict = {}
for item in reversed(origin_data["Sangfor"]):
    time_dict = {"name": item[0], "children": [time_dict]}
plot_data["children"].append({"name":"TimeZone", "children":[time_dict]})
for v in origin_data:
    results = {}
    for item in reversed(origin_data[v]):
        results= opts.TreeItem(
            name=item[1],
            label_opts=opts.LabelOpts(
                formatter='{label|%s}' % item[1],
                rich={
                    "label": {
                        'color':colors[item[1]],
                        'fontSize':5
                        }
                }
            ),
            children=[results],
        )

    plot_data["children"].append(opts.TreeItem(
        name=v,
        label_opts=opts.LabelOpts(
            formatter='{v|%s}' % v, 
            rich={ # colors[v]
                "v": {
                    'color':colors[v]
                }
            }
        ),
        children=[results],
    ))
```
