### ISSUE TITLE
Event handling examples in the doc seems outdated

### ISSUE THREAD

**Issue by pramitchoudhary** [pyecharts/pyecharts#1774]
The examples mentioned here seems to be out of sync, https://pyecharts.org/#/en-us/advanced?id=javascript-event-handlers.

Will it be possible to add a few examples of event handling in the gallery https://github.com/pyecharts/pyecharts-gallery ?

Also, https://github.com/pyecharts/pyecharts-javascripthon is not maintained anymore right?
I tried following previous conversations that it's supposed to be part of the main library itself. Is that correct?

**Comment by sunhailin-Leo** [comment]
@pramitchoudhary 
* Event Handling was the old version api for 0.5.x.
* Version 1.x is remove the event handling api, instead of using `JsCode`, but `JsCode` function is still improving now.
