### ISSUE TITLE
dataset和grid一起使用的时候，grid显示同一个图

### ISSUE THREAD

**Issue by vincent8877** [pyecharts/pyecharts#1775]
**问题**
两个scatter，均使用dataset
完了之后使用grid组合在一起。
问题是，两个图组合在一起之后，显示的是同一个图。

**运行环境（系统环境及 pyecharts 版本）**
win10，pyecharts1.9.0

**代码及截图**

`from pyecharts.charts import Grid, Scatter
from pyecharts import options as opts

scatter1 = (
    Scatter()
    .add_dataset(source=[['x_1', 'y_1'], ['1', 1]])
    .add_yaxis(
        series_name='',
        y_axis=[],
        encode={'x': 'x_1', 'y': 'y_1'},
    )
)

scatter2 = (
    Scatter()
    .add_dataset(source=[['x_2', 'y_2'], ['2', 2], ['3', 3]])
    .add_yaxis(
        series_name='',
        y_axis=[],
        encode={'x': 'x_2', 'y': 'y_2'},
    )
)

grid = (Grid(init_opts=opts.InitOpts(width="1890px", height='500px')))
grid.add(scatter1, grid_opts=opts.GridOpts(pos_left='10%', pos_right='60%'))
grid.add(scatter2, grid_opts=opts.GridOpts(pos_left='50%', pos_right='20%'))
grid.render('grid.html')`

![Snipaste_2020-12-30_17-20-41](https://user-images.githubusercontent.com/40603468/103342155-bcb52b80-4ac3-11eb-9611-75c0b978a59e.png)

同样的数据，不使用dataset，直接scatter之后再grid，就没有问题。
`from pyecharts.charts import Grid, Scatter
from pyecharts import options as opts

scatter1 = (
    Scatter()
    .add_xaxis(['1'])
    .add_yaxis(
        series_name='',
        y_axis=[1],
    )
)

scatter2 = (
    Scatter()
    .add_xaxis(['2', '3'])
    .add_yaxis(
        series_name='',
        y_axis=[2, 3],
    )
)

grid = (Grid(init_opts=opts.InitOpts(width="1890px", height='500px')))
grid.add(scatter1, grid_opts=opts.GridOpts(pos_left='10%', pos_right='60%'))
grid.add(scatter2, grid_opts=opts.GridOpts(pos_left='50%', pos_right='20%'))
grid.render('grid.html')`
![Snipaste_2020-12-30_17-22-24](https://user-images.githubusercontent.com/40603468/103342199-df474480-4ac3-11eb-8425-c3a8ce9cef1c.png)

**Comment by MeredithChai** [comment]
@vincent8877 

看一下第二次调用`add_dataset`之后，原始的dataset数据是不是直接被覆盖了。

btw, markdown的代码格式调一下，用“```”前后括起来切preview标签确认下格式吧...

给你个示例：

<b>代码</b>
![image](https://user-images.githubusercontent.com/37883510/103405057-bc369680-4b90-11eb-92e3-9caf5521f067.png)
<b>效果</b>
```python
import numpy as np
```
