### ISSUE TITLE
前后端分离渲染的图表怎么做到页面实时自适应

### ISSUE THREAD

**Issue by sjk7524068** [pyecharts/pyecharts#1776]
**问题**

前后端分离渲染的图表在页面拉伸时还是保持着原来canvas的大小，不能做到自适应，只能再刷新一次达到适应页面的需求

**运行环境（系统环境及 pyecharts 版本）**
python: 3.6.5
pyecharts: 1.7.0

**代码及截图**

### 第一次加载
![image](https://user-images.githubusercontent.com/26033252/103616258-08a21d80-4f67-11eb-802e-d4824e8d33bb.png)

### 放大页面后
![image](https://user-images.githubusercontent.com/26033252/103616372-49019b80-4f67-11eb-9b47-57cb9be56ed4.png)

请问有什么好的解决方案吗？

**Comment by sunhailin-Leo** [comment]
@sjk7524068 这个是前端的问题了，这个只能找前端的同学去咨询了
