### ISSUE TITLE
Django框架整合——定时更新图表的getDynamicData()方法该什么时候调用？

### ISSUE THREAD

**Issue by vebys** [pyecharts/pyecharts#1778]
**问题**
Web 框架整合——Django——定时增量更新图表——index.html页面中的  getDynamicData()  js函数该什么时候调用的呢？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![image](https://user-images.githubusercontent.com/28820071/104084776-17e5db80-5285-11eb-9c69-8381c7a0ff4d.png)

**Comment by sunhailin-Leo** [comment]
@vebys 
* https://pyecharts.org/#/zh-cn/web_flask?id=%e5%ae%9a%e6%97%b6%e5%a2%9e%e9%87%8f%e6%9b%b4%e6%96%b0%e5%9b%be%e8%a1%a8
* 参考一下 Flask
