### ISSUE TITLE
树状图的显示文本可以复制文本吗？或通过ctrl+f查找出文本

### ISSUE THREAD

**Issue by luojieio** [pyecharts/pyecharts#1779]
**问题**
树状图的显示文本可以复制文本吗？或通过ctrl+f查找出文本

**运行环境（系统环境及 pyecharts 版本）**
python3.6+ 
Pyecharts 1.9

**代码及截图**
from pyecharts import options as opts
from pyecharts.charts import Tree

top_domain="www.aa.com"

data = [
    {
        "name": top_domain,
        "children": [
            {
                "name": "10.0.0.1",
                "children":[
                    {"name":"192.168.0.1",
                    "children":[
                        {"name":"192.168.0.10"},
                        {"name":"192.168.0.10",
                        "children":[
                            {"name":"192.168.0.11",
                            "children":[
                                {"name":"192.168.0.222"}
                            ]}
                        ]
                        
                        },
                    ]
                    
                    },
                    {"name":"192.168.0.2"}
                ]
            },

            {"name": "10.0.0.2",
            "children":[
                {"name":"192.168.0.3"},
                {"name":"192.168.0.4"}
            ]
            },

            {"name": "10.0.0.3",
            "children":[
                {"name":"192.168.0.5"}
            ]
            },
            
            {"name": "xxxxx",
            "children":[]
            }

        ],        
    }
]

c = (
    Tree(init_opts=opts.InitOpts(width="1500px",page_title="拓扑图"))
    .add("", data,symbol_size=20,collapse_interval=5,)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="aa",title_link="http://www.aa.com"),
        )
    .render("tree_base.html")
)

**Comment by sunhailin-Leo** [comment]
@luojieio 
* Echarts 把标签话画在图里了，不能通过 ctrl + f 找
