### ISSUE TITLE
Map类画地图，数据对应地区无法更改字体大小

### ISSUE THREAD

**Issue by kouyichi** [pyecharts/pyecharts#1780]
**问题**
图中有数据部分的字体大小无法更改，只能更改其余部分地区的字体大小。
查看生成的html文件也一样，要么数据地区没有了鼠标滑动显示标签的效果，要么就不能改字体大小

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
c = (
    Map()
    .add("世界地图", [['China',91.5],['India',16]], "world",emphasis_label_opts=opts.LabelOpts(font_size=50))
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Map-世界地图"),
        visualmap_opts=opts.VisualMapOpts(max_=200),
        tooltip_opts=opts.TooltipOpts(textstyle_opts=opts.TextStyleOpts(font_size=50))
    )
    .render("map_world2.html")
)
![image](https://user-images.githubusercontent.com/12020793/104132083-27187680-53b6-11eb-884d-44e6182c9679.png)

**Comment by sunhailin-Leo** [comment]
@kouyichi 
* 是要改哪里的字体？

**Comment by kouyichi** [comment]
棕色的chain
