### ISSUE TITLE
Color control in Sankey nodes

### ISSUE THREAD

**Issue by wangxing7714436** [pyecharts/pyecharts#1782]
**问题**
No detail color control example,  itemstyleOpts color control dose not apply to nodes, it either applies globally or applies to only few nodes, and no explicit pattern found.

**运行环境（系统环境及 pyecharts 版本）**
Win 10 64-bit, Python 3.7.6 with latest pyecharts    VS code with  jupyter notebook

**代码及截图**
from pyecharts import options as opts
from pyecharts.charts import Sankey

colors = '#ff00ff',
    #'#99ff00',
    #'#FFC125',
    #'#BDBDBD',
    #'#cc00cc',
    #'#FF3030',
    #'#FF1493',
    #'#ADFF2F',
    #'#96CDCD',
    #'#607B8B',
    #'#292929',
    #'#00FF7F'

#color_dict = {'202012流动性':'#F53D00',}
c = (
    Sankey()
    #.set_colors(colors)
    
    .add(
        "sankey",
        #itemstyle_opts = opts.ItemStyleOpts(color=["#99ff00"]),
    nodes = [
    #2020 nodes
    {"name": "202012流动性"},   #流动性及其他 #FF6633  0
    {"name": "202012定存、协存"}, #配置 #66FF33  1
    {"name": "202012利率债AFS自营"}, #功能 #33CCFF  2
    {"name": "202012利率债AFS委外"}, #收益 #F53D00   3
    {"name": "202012利率债HTM自营"}, # 配置 #66FF33  4
    {"name": "202012信用债自营"}, #配置 #66FF33  5 
    {"name": "202012信用债委外"}, #收益 #F53D00  6
    {"name": "202012资本补充债"}, #收益 #F53D00  7
    {"name": "202012纯债债基/资管产品"}, #配置 #66FF33  8
    {"name": "202012二级债基/资管产品"}, #收益 #F53D00   9
    {"name": "202012摊余成本债基/资管产品"}, #配置 #66FF33  10
     #2021 nodes
    {"name": "202112其他资产"}, #流动性及其他 #FF6633  11
    {"name": "202112流动性"}, #流动性及其他 #FF6633   12
    {"name": "202112定存、协存"}, #配置 #66FF33        13
    {"name": "202112利率债AFS自营"}, #功能 #33CCFF    14
    {"name": "202112利率债AFS委外"}, #收益 #F53D00    15
    {"name": "202112利率债HTM自营"}, #配置 #66FF33    16
    {"name": "202112信用债自营"}, #配置 #66FF33       17
    {"name": "202112信用债委外"}, #收益 #F53D00       18
    {"name": "202112资本补充债"}, #收益 #F53D00       19
    {"name": "202112纯债债基/资管产品"}, #配置 #66FF33  20
    {"name": "202112二级债基/资管产品"}, #F53D00      21
    {"name": "202112摊余成本债基/资管产品"}, #配置 #66FF33   22
    
    # {"name": "信用债自营"},
    #配置、功能、收益节点
    #{"name": "202012固收配置类资产"},
    #{"name": "202012固收功能类资产"},
    #{"name": "202012固收收益类资产"},
    #{"name": "202112固收配置类资产"},
    #{"name": "202112固收功能类资产"},
    #{"name": "202112固收收益类资产"},
],
       links = [
    #{"source": "202012流动性", "target": "202112流动性","value": 118.67},
    {"source": "202012流动性", "target": "202112流动性","value": 118.67},
    #固收资产分类-功能类
    {"source": "202012利率债AFS自营", "target": "202112利率债AFS自营","value": 157.20},
    #固收资产分类-配置类
    {"source": "202012定存、协存", "target": "202112定存、协存","value": 60.91},
    {"source": "202012利率债HTM自营", "target": "202112利率债HTM自营","value": 71.78},
    {"source": "202012纯债债基/资管产品收益", "target": "202112纯债债基/资管产品","value": 37.66},
    {"source": "202012摊余成本债基/资管产品", "target": "202112摊余成本债基/资管产品","value": 0.00},
    {"source": "202012信用债自营", "target": "202112信用债自营","value": 99.91},
    #固收资产分类-收益类
    {"source": "202012利率债AFS委外", "target": "202112利率债AFS委外","value": 59.28},
    {"source": "202012资本补充债", "target": "202112资本补充债","value": 13.57},
    {"source": "202012信用债委外", "target": "202112信用债委外","value": 45.68},
    {"source": "202012二级债基/资管产品", "target": "202112二级债基/资管产品","value": 39.40},
    #{"source": "202012摊余成本债基/资管产品", "target": "202112摊余成本债基/资管产品","value": 0},

    #固收资产分类-功能类-变动
    {"source": "202012流动性", "target": "202112其他资产","value": 21.38},
    {"source": "202012流动性", "target": "202112利率债AFS自营","value": 55.82},

    #固收资产分类-配置类-变动
    {"source": "202012纯债债基/资管产品", "target": "202112定存、协存","value": 20.00},
    {"source": "202012纯债债基/资管产品", "target": "202112利率债HTM自营","value": 12.17},

    #固收资产分类-收益类-变动
    {"source": "202012纯债债基/资管产品", "target": "202112利率债AFS委外","value": 2.72},
    {"source": "202012纯债债基/资管产品", "target": "202112资本补充债","value": 21.31},
    {"source": "202012纯债债基/资管产品", "target": "202112信用债委外","value": 38.26},
    {"source": "202012纯债债基/资管产品", "target": "202112摊余成本债基/资管产品","value": 38.92},
    {"source": "202012二级债基/资管产品", "target": "202112信用债委外","value": 57.84},
    {"source": "202012纯债债基/资管产品", "target": "202112纯债债基/资管产品","value": 37.66},
    {"source": "202012纯债债基/资管产品", "target": "202112信用债自营","value": 27.69},
    {"source": "202012流动性", "target": "202112信用债自营","value": 5.00},

    
    #2020明细到固收资产分类
    #{"source": "202012流动性", "target": "202112流动性","value": 118.67},
    #{"source": "202012流动性", "target": "202112流动性","value": 118.67},
    #{"source": "202112流动性", "value": 15},
    #{"source": "category3", "target": "category4", "value": 20},
    #{"source": "category5", "target": "category6", "value": 25},
],

        #itemstyle_opts=opts.LineStyleOpts(color,[FF6633]),
        linestyle_opt=opts.LineStyleOpts(opacity=0.2, curve=0.4, color="source"),
        label_opts=opts.LabelOpts(position="right"),
        #itemstyle_opts = opts.ItemStyleOpts(color=["#99ff00"])
        
    )
   
    #.set_global_opts(title_opts=opts.TitleOpts(title="Sankey-基本示例"))
    #.render("1.png")
   
)
c.render_notebook()

**Comment by sunhailin-Leo** [comment]
@wangxing7714436 
* Where is your snapshot?
* Please re-format your code. thx.😅
