### ISSUE TITLE
boxplot箱型图是否支持boxwidth图元宽度控制

### ISSUE THREAD

**Issue by vincent8877** [pyecharts/pyecharts#1785]
echarts是支持的：
[issue](https://github.com/apache/echarts/issues/8888)
[code](https://echarts.apache.org/zh/option.html#series-boxplot.boxWidth)
pyecharts里我没找到在哪里添加这个参数。
麻烦看一下，谢谢

**Comment by sunhailin-Leo** [comment]
@vincent8877 
* 这个参数还真么加 😂
* 下个版本加进去👍
