### ISSUE TITLE
表格组件table 无法通过 make_snapshot 转换为图片

### ISSUE THREAD

**Issue by yesterday-cell** [pyecharts/pyecharts#1788]
table = Table()
headers = ["City name", "Area", "Population", "Annual Rainfall"]
rows = [
    ["Brisbane", 5905, 1857594, 1146.4],
    ["Adelaide", 1295, 1158259, 600.5],
    ["Darwin", 112, 120900, 1714.7],
    ["Hobart", 1357, 205556, 619.5],
    ["Sydney", 2058, 4336374, 1214.8],
    ["Melbourne", 1566, 3806092, 646.9],
    ["Perth", 5386, 1554769, 869.4],
]
table.add(headers, rows)
table.set_global_opts(
    title_opts=ComponentTitleOpts(title="Table-基本示例", subtitle="我是副标题支持换行哦")
)
table.render("table_base.html")

使用make_snapshot(snapshot, table.render(), photoname)
无法转换图片 报错：
selenium.common.exceptions.JavascriptException: Message: javascript error: echarts is not defined
  (Session info: headless chrome=84.0.4147.135)

**Comment by sunhailin-Leo** [comment]
@yesterday-cell 
* `HTML` 不支持将原生标签转换为图片

**Comment by yesterday-cell** [comment]
这个表格table的不行，但是其他的柱状图都好好的，是要怎么处理呢，大神

**Comment by yesterday-cell** [comment]
感觉像是make_snapshot 不支持 这个 table

**Comment by yesterday-cell** [comment]
####pyechart
from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.render import make_snapshot
from snapshot_selenium import snapshot

from pyecharts.components import Table
from pyecharts.options import ComponentTitleOpts

**Comment by sunhailin-Leo** [comment]
@yesterday-cell 
* 不支持转换 HTML 标签的东西，make_snapshot 只针对 canvas 或者 svg 这类的图

**Comment by yesterday-cell** [comment]
那如果想转换这个table的 html为图片,有没有其他方法转换

**Comment by sunhailin-Leo** [comment]
@yesterday-cell 
* 找截图工具

**Comment by yesterday-cell** [comment]
老师有推荐的么

**Comment by sunhailin-Leo** [comment]
> 老师有推荐的么

自己找吧

**Comment by Nicolasking007** [comment]
我也遇到了 有解决方案吗

**Comment by sun7451** [comment]
我也遇到了，爬了下楼，看关于这个问题，至少有三个issue，为啥没解决，都关闭了呢？不解决问题，一直在的呢
