### ISSUE TITLE
ImportError: cannot import name 'Map' from 'pyecharts' (D:\Anaconda\lib\site-packages\pyecharts\__init__.py)

### ISSUE THREAD

**Issue by DylanDenali** [pyecharts/pyecharts#1789]
Traceback (most recent call last):
  File "D:/SpiderProgram/info_analysis/hotmap_China.py", line 1, in <module>
    from pyecharts import Map
ImportError: cannot import name 'Map' from 'pyecharts' (D:\Anaconda\lib\site-packages\pyecharts\__init__.py)

**Comment by sunhailin-Leo** [comment]
@DylanDenali 
* This import method is an old version, you can read the README.md using new version.
