### ISSUE TITLE
请教一个问题，使用Geo或者Map绘制的全国地图，放大后怎么显示下一级的地图（地级市地图），缩小后再显示为省级的。 就是放大后能够显示下一级地图的功能。目前是无论怎么放大都显示不出地级市来。

### ISSUE THREAD

**Issue by matthew2013** [pyecharts/pyecharts#1791]
**问题**
请教一个问题，使用Geo或者Map绘制的全国地图，放大后怎么显示下一级的地图（地级市地图），缩小后再显示为省级的。
就是放大后能够显示下一级地图的功能。目前是无论怎么放大都显示不出地级市来。

**运行环境（系统环境及 pyecharts 版本）**
win10，pyecharts1.9

**代码及截图**
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.globals import ChartType, SymbolType

c = (
    Geo()
    .add_schema(
        maptype="china",
        itemstyle_opts=opts.ItemStyleOpts(color="#323c48", border_color="#111"),
    )
    .add(
        "",
        [("广州", 55), ("北京", 66), ("杭州", 77), ("重庆", 88)],
        type_=ChartType.EFFECT_SCATTER,
        color="white",
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(title_opts=opts.TitleOpts(title="Geo-Lines-background"))
    .render("geo_lines_background.html")
)

![image](https://user-images.githubusercontent.com/13148796/106577206-0d172180-6579-11eb-81fc-8f123929c9a6.png)

**Comment by sunhailin-Leo** [comment]
@matthew2013 
* `Echarts` 也没这功能😅
