### ISSUE TITLE
HTML模板使用本地echarts渲染空白

### ISSUE THREAD

**Issue by phoenixor** [pyecharts/pyecharts#1793]
**问题**
按照文档使用Flask框架，HTML模板中在线jquery和echarts改成本地，文件都从官方下载，放在项目根目录assets文件夹下，导入路径没问题，但是渲染页面是空白

**运行环境（系统环境及 pyecharts 版本）**
都是最新版

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@phoenixor 
* 贴一下关键代码吧，这样子描述很抽象

**Comment by austingg** [comment]
用chrome的开发者工具console里看下输出的错误。 @phoenixor
