### ISSUE TITLE
Toolbox在1.7.1的版本后无法正常使用

### ISSUE THREAD

**Issue by AndersonBY** [pyecharts/pyecharts#1794]
**问题**
Toolbox在1.7.1版本以后无法使用，控制台会报错
经测试需要将生成的HTML中的：
"xAxisIndex": false,
"yAxisIndex": false,
删除才可以正常使用

代码为官方示例：
```python
from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.faker import Faker

c = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Bar-显示 ToolBox"),
        toolbox_opts=opts.ToolboxOpts(),
        legend_opts=opts.LegendOpts(is_show=False),
    )
    .render("bar_toolbox.html")
)
```

**运行环境（系统环境及 pyecharts 版本）**
Windows10, Pyecharts1.9.0

**代码及截图**
![image](https://user-images.githubusercontent.com/3096131/106862476-27303b80-6702-11eb-8733-649e273d45c5.png)

**Comment by sunhailin-Leo** [comment]
@AndersonBY 
* 具体是那个部分的功能不能正常使用？

**Comment by AndersonBY** [comment]
@sunhailin-Leo 涉及到拖动选中区域的几个都用不了

**Comment by sunhailin-Leo** [comment]
@AndersonBY 
* Ok
