### ISSUE TITLE
示例中的几个Bmap,拖拽后图表与地图偏离

### ISSUE THREAD

**Issue by 1von** [pyecharts/pyecharts#1795]
**问题**

1、示例中的几个Bmap,拖拽后图表与地图偏离；
2、在jupyter notbook 里面绘制后，鼠标拖拽也有一定的延迟渲染
请问下怎么解决，谢谢

**运行环境（系统环境及 pyecharts 版本）**

https://gallery.pyecharts.org/#/BMap/bmap_base

**代码及截图**

![微信截图_20210205110536](https://user-images.githubusercontent.com/17869602/106984412-80e84280-67a2-11eb-9dbf-14a63e08d6b2.png)

![微信截图_20210205111227](https://user-images.githubusercontent.com/17869602/106984754-226f9400-67a3-11eb-9a51-2431c8978e73.png)

**Comment by sunhailin-Leo** [comment]
@1von 
* 1、漂移的问题可能和没有 key 有关系
* 2、渲染延迟的问题，这个因素很多，BMap 本身很吃浏览器性能，待后续更新 Echarts 5.0 之后再观察
