### ISSUE TITLE
opts.TooltipOpts( 部分功能无法实现)

### ISSUE THREAD

**Issue by ghost** [pyecharts/pyecharts#1796]
**运行环境（系统环境及 pyecharts 版本）**
pyecharts  1.90
python 3.7.3
win10
-->

**问题**

opts.TooltipOpts中  hide_delay ， is_always_show_content失效
                                    标签加大延长时间失效，  移出可触发提示框区域后一定时间后隐藏 失效

**代码及截图**
from pyecharts import options as opts
from pyecharts.charts import Grid, Liquid
from pyecharts.commons.utils import JsCode
from pyecharts.render import make_snapshot
from snapshot_selenium import snapshot

timer = 1
t = 12
named = ' 电池 '
flag = ' OK!'
strflag = str(timer) + named+ str(t) + flag
l1 =( 
Liquid()
    .add("有害垃圾", [0.6], center=["30%", "25%"],tooltip_opts=opts.TooltipOpts(
        trigger_on = "click",
        is_always_show_content = False,  #无功能
        position = ['38%','27%'],
        hide_delay = 10000,  #无功能
        textstyle_opts = opts.TextStyleOpts(font_size=20)
         ))
    .set_global_opts(title_opts=opts.TitleOpts(title=strflag),
    )
)
    
l3 = (Liquid().add(
    "厨余垃圾",[0.1], center=["30%", "75%"],
    label_opts=opts.LabelOpts(
        font_size=50,
        formatter=JsCode(
            """function (param) {
                    return (Math.floor(param.value * 10000) / 100) + '%';
                }"""
        ),
        position="inside",
                            )  
).set_global_opts(
                    graphic_opts = [ 
                        opts.GraphicGroup(
                        #is_diff_children_by_name= True,
                        graphic_item=opts.GraphicItem(
                            rotation=JsCode("-Math.PI / 4"),
                            bounding="raw",
                            left=70,
                            bottom=70,
                            z=8,  
                            is_progressive=True
                                         ),                                       
                        children = [
                            opts.GraphicRect(
                                graphic_item=opts.GraphicItem(left="center", top="center", z=8),
                                graphic_shape_opts=opts.GraphicShapeOpts(  #pos_x=0.1, pos_y= 0.1, 
                                                                        width=400, height=50),
                                graphic_basicstyle_opts=opts.GraphicBasicStyleOpts( 
                                                    fill="rgba(0,0,0,0.3)"
                                                            )
                                 ),            
                            opts.GraphicText(
                                graphic_item=opts.GraphicItem(left="center", top="center", z=8),
                                graphic_textstyle_opts=opts.GraphicTextStyleOpts(
                                            #pos_x=0.1, pos_y= 0.1,
                                            text="有害垃圾",
                                            font="bold 26px Microsoft YaHei",
                                             graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(fill="#fff"),
                                                                            )
                                             )                                         
                                    ]
                                )           
                                ] 

                    )
    )
grid = (Grid(opts.InitOpts(width='1200px', height="800px"))
        .add(l1, grid_opts=opts.GridOpts()).add(l3, grid_opts=opts.GridOpts()) 
        )
    
grid.render("multiple_liquid.html")

![G$WGAOUW7GOJOL0 I(01_UW](https://user-images.githubusercontent.com/65141538/107232628-95576400-6a5c-11eb-88b2-6fe3487a7a5f.png)

更改图示位置程序输出不同结果

**代码截图**
![H8 PTOM{HRR1D SYI%XYNBJ](https://user-images.githubusercontent.com/65141538/107233121-2fb7a780-6a5d-11eb-8505-947aaa763cf2.png)

**Comment by sunhailin-Leo** [comment]
@n1753355088 
* 先把你的代码格式化一下😅

**Comment by n1753355088** [comment]
`from pyecharts import options as opts
from pyecharts.charts import Grid, Liquid
from pyecharts.commons.utils import JsCode
from pyecharts.render import make_snapshot

# 使用 snapshot-selenium 渲染图片
from snapshot_selenium import snapshot

timer = 1
t = 12
named = " 电池 "
flag = " OK!"
strflag = str(timer) + named + str(t) + flag
l1 = (
    Liquid()
    .add(
        "有害垃圾",
        [0.6],
        center=["30%", "25%"],
        tooltip_opts=opts.TooltipOpts(
            trigger_on="click",
            is_always_show_content=False,  # 无功能
            position=["38%", "27%"],
            hide_delay=10000,  # 无功能
            textstyle_opts=opts.TextStyleOpts(font_size=20),
        ),
    )
    .set_global_opts(title_opts=opts.TitleOpts(title=strflag),)
)

l3 = (
    Liquid()
    .add(
        "厨余垃圾",
        [0.1],
        center=["30%", "75%"],
        label_opts=opts.LabelOpts(
            font_size=50,
            formatter=JsCode(
                """function (param) {
                    return (Math.floor(param.value * 10000) / 100) + '%';
                }"""
            ),
            position="inside",
        ),
    )
    .set_global_opts(
        graphic_opts=[
            opts.GraphicGroup(
                # is_diff_children_by_name= True,
                graphic_item=opts.GraphicItem(
                    rotation=JsCode("-Math.PI / 4"),
                    bounding="raw",
                    left=70,
                    bottom=70,
                    z=8,
                    is_progressive=True,
                ),
                children=[
                    opts.GraphicRect(
                        graphic_item=opts.GraphicItem(left="center", top="center", z=8),
                        graphic_shape_opts=opts.GraphicShapeOpts(  # pos_x=0.1, pos_y= 0.1,
                            width=400, height=50
                        ),
                        graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                            fill="rgba(0,0,0,0.3)"
                        ),
                    ),
                    opts.GraphicText(
                        graphic_item=opts.GraphicItem(left="center", top="center", z=8),
                        graphic_textstyle_opts=opts.GraphicTextStyleOpts(
                            # pos_x=0.1, pos_y= 0.1,
                            text="有害垃圾",
                            font="bold 26px Microsoft YaHei",
                            graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                                fill="#fff"
                            ),
                        ),
                    ),
                ],
            )
        ]
    )
)
grid = (
    Grid(opts.InitOpts(width="1200px", height="800px"))
    .add(l1, grid_opts=opts.GridOpts())
    .add(l3, grid_opts=opts.GridOpts())
)

grid.render("multiple_liquid.html")
`

**Comment by n1753355088** [comment]
```
from pyecharts import options as opts
from pyecharts.charts import Grid, Liquid
from pyecharts.commons.utils import JsCode
from pyecharts.render import make_snapshot
from snapshot_selenium import snapshot

timer = 1
t = 12
named = " 电池 "
flag = " OK!"
strflag = str(timer) + named + str(t) + flag
l1 = (
    Liquid()
    .add(
        "有害垃圾",
        [0.6],
        center=["30%", "25%"],
        tooltip_opts=opts.TooltipOpts(
            trigger_on="click",
            is_always_show_content=False,  # 无功能
            position=["38%", "27%"],
            hide_delay=10000,  # 无功能
            textstyle_opts=opts.TextStyleOpts(font_size=20),
        ),
    )
    .set_global_opts(title_opts=opts.TitleOpts(title=strflag),)
)

l3 = (
    Liquid()
    .add(
        "厨余垃圾",
        [0.1],
        center=["30%", "75%"],
        label_opts=opts.LabelOpts(
            font_size=50,
            formatter=JsCode(
                """function (param) {
                    return (Math.floor(param.value * 10000) / 100) + '%';
                }"""
            ),
            position="inside",
        ),
    )
    .set_global_opts(
        graphic_opts=[
            opts.GraphicGroup(
                # is_diff_children_by_name= True,
                graphic_item=opts.GraphicItem(
                    rotation=JsCode("-Math.PI / 4"),
                    bounding="raw",
                    left=70,
                    bottom=70,
                    z=8,
                    is_progressive=True,
                ),
                children=[
                    opts.GraphicRect(
                        graphic_item=opts.GraphicItem(left="center", top="center", z=8),
                        graphic_shape_opts=opts.GraphicShapeOpts(  # pos_x=0.1, pos_y= 0.1,
                            width=400, height=50
                        ),
                        graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                            fill="rgba(0,0,0,0.3)"
                        ),
                    ),
                    opts.GraphicText(
                        graphic_item=opts.GraphicItem(left="center", top="center", z=8),
                        graphic_textstyle_opts=opts.GraphicTextStyleOpts(
                            # pos_x=0.1, pos_y= 0.1,
                            text="有害垃圾",
                            font="bold 26px Microsoft YaHei",
                            graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                                fill="#fff"
                            ),
                        ),
                    ),
                ],
            )
        ]
    )
)
grid = (
    Grid(opts.InitOpts(width="1200px", height="800px"))
    .add(l1, grid_opts=opts.GridOpts())
    .add(l3, grid_opts=opts.GridOpts())
)
grid.render("multiple_liquid.html")
```

**Comment by n1753355088** [comment]
```ruby
from pyecharts import options as opts
from pyecharts.charts import Grid, Liquid
from pyecharts.commons.utils import JsCode
from pyecharts.render import make_snapshot
from snapshot_selenium import snapshot

timer = 1
t = 12
named = " 电池 "
flag = " OK!"
strflag = str(timer) + named + str(t) + flag
l1 = (
    Liquid()
    .add(
        "有害垃圾",
        [0.6],
        center=["30%", "25%"],
        tooltip_opts=opts.TooltipOpts(
            trigger_on="click",
            is_always_show_content=False,  # 无功能
            position=["38%", "27%"],
            hide_delay=10000,  # 无功能
            textstyle_opts=opts.TextStyleOpts(font_size=20),
        ),
    )
    .set_global_opts(title_opts=opts.TitleOpts(title=strflag),)
)

l3 = (
    Liquid()
    .add(
        "厨余垃圾",
        [0.1],
        center=["30%", "75%"],
        label_opts=opts.LabelOpts(
            font_size=50,
            formatter=JsCode(
                """function (param) {
                    return (Math.floor(param.value * 10000) / 100) + '%';
                }"""
            ),
            position="inside",
        ),
    )
    .set_global_opts(
        graphic_opts=[
            opts.GraphicGroup(
                # is_diff_children_by_name= True,
                graphic_item=opts.GraphicItem(
                    rotation=JsCode("-Math.PI / 4"),
                    bounding="raw",
                    left=70,
                    bottom=70,
                    z=8,
                    is_progressive=True,
                ),
                children=[
                    opts.GraphicRect(
                        graphic_item=opts.GraphicItem(left="center", top="center", z=8),
                        graphic_shape_opts=opts.GraphicShapeOpts(  # pos_x=0.1, pos_y= 0.1,
                            width=400, height=50
                        ),
                        graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                            fill="rgba(0,0,0,0.3)"
                        ),
                    ),
                    opts.GraphicText(
                        graphic_item=opts.GraphicItem(left="center", top="center", z=8),
                        graphic_textstyle_opts=opts.GraphicTextStyleOpts(
                            # pos_x=0.1, pos_y= 0.1,
                            text="有害垃圾",
                            font="bold 26px Microsoft YaHei",
                            graphic_basicstyle_opts=opts.GraphicBasicStyleOpts(
                                fill="#fff"
                            ),
                        ),
                    ),
                ],
            )
        ]
    )
)
grid = (
    Grid(opts.InitOpts(width="1200px", height="800px"))
    .add(l1, grid_opts=opts.GridOpts())
    .add(l3, grid_opts=opts.GridOpts())
)
grid.render("multiple_liquid.html")
```

**Comment by n1753355088** [comment]
> @n1753355088
> 
> * 先把你的代码格式化一下😅

改了...

**Comment by sunhailin-Leo** [comment]
@n1753355088 
* 回到问题上来😂
* 我刚试了下的确不行，或者你试试其他类型的图是否有这个问题。有可能是水球图的问题，因为水球图不属于 Echarts 的核心图范畴。

**Comment by n1753355088** [comment]
> @n1753355088
> 
> * 回到问题上来😂
> * 我刚试了下的确不行，或者你试试其他类型的图是否有这个问题。有可能是水球图的问题，因为水球图不属于 Echarts 的核心图范畴。

好的

**Comment by n1753355088** [comment]
> @n1753355088
> 
> * 回到问题上来😂
> * 我刚试了下的确不行，或者你试试其他类型的图是否有这个问题。有可能是水球图的问题，因为水球图不属于 Echarts 的核心图范畴。

饼图在Grid 并行多图下也无法实现 ① opts.TooltipOpts中 hide_delay ， is_always_show_content失效
                                                        ②opts.GraphicText 文本框 改变调用顺序不显示问题

**Comment by sunhailin-Leo** [comment]
> > @n1753355088
> > 
> > * 回到问题上来😂
> > * 我刚试了下的确不行，或者你试试其他类型的图是否有这个问题。有可能是水球图的问题，因为水球图不属于 Echarts 的核心图范畴。
> 
> 饼图在Grid 并行多图下也无法实现 ① opts.TooltipOpts中 hide_delay ， is_always_show_content失效
> ②opts.GraphicText 文本框 改变调用顺序不显示问题

单个图呢？

**Comment by n1753355088** [comment]
> > > @n1753355088
> > > 
> > > * 回到问题上来😂
> > > * 我刚试了下的确不行，或者你试试其他类型的图是否有这个问题。有可能是水球图的问题，因为水球图不属于 Echarts 的核心图范畴。
> > 
> > 
> > 饼图在Grid 并行多图下也无法实现 ① opts.TooltipOpts中 hide_delay ， is_always_show_content失效
> > ②opts.GraphicText 文本框 改变调用顺序不显示问题
> 
> 单个图呢？

也不行...

**Comment by sunhailin-Leo** [comment]
> > > > @n1753355088
> > > > 
> > > > * 回到问题上来😂
> > > > * 我刚试了下的确不行，或者你试试其他类型的图是否有这个问题。有可能是水球图的问题，因为水球图不属于 Echarts 的核心图范畴。
> > > 
> > > 
> > > 饼图在Grid 并行多图下也无法实现 ① opts.TooltipOpts中 hide_delay ， is_always_show_content失效
> > > ②opts.GraphicText 文本框 改变调用顺序不显示问题
> > 
> > 
> > 单个图呢？
> 
> 也不行...

那看来是 Echarts 本身的问题了，我们只是配置的搬运工🐶
