### ISSUE TITLE
单独render geo数据没有问题，一旦结合grid，添加bar，line，geo的数据就变成不可更改的浮点数了，这是一个bug吧？

### ISSUE THREAD

**Issue by huangbin415** [pyecharts/pyecharts#1798]
**问题**
In this example, there is no problem with Render Geo data alone. Once combined with Grid, add Bar, Line, and Geo data, it becomes an immutable floating point number. Is this a bug?
这个示例，单独render geo数据没有问题，一旦结合grid，添加bar，line，geo的数据就变成不可更改的浮点数了，这是一个bug吧？

**运行环境（系统环境及 pyecharts 版本）**
win10 pyecharts 1.9.0

**代码及截图**
比如北京  地图上的数据为39.90403   无法改变了，如果单独render GEO ，数据显示没问题
官网上的grid示例，也是同样的问题

**Comment by sunhailin-Leo** [comment]
@huangbin415 
* Where is your question content?

**Comment by huangbin415** [comment]
单独render, geo地图数据没有问题，一旦结合grid，一张图同时添加bar，line，geo的数据就变成不可更改的浮点数了, 无论数据源是多少，例如北京 39.90403
