### ISSUE TITLE
bar翻转之后标签太长显示不全怎么解决

### ISSUE THREAD

**Issue by Fyyyyy158** [pyecharts/pyecharts#1799]
**问题**

像这种情况怎么解决呢?可以将整个图形右移一点吗？还是通过什么方法？

**运行环境（系统环境及 pyecharts 版本）**

v1.9

**代码及截图**

 `
 
<img width="489" alt="bar翻转" src="https://user-images.githubusercontent.com/58002385/108466985-7ad48480-72bf-11eb-8438-62ff4288e23c.png">

    Bar(init_opts=opts.InitOpts(width='800px', height='600px'))
    .add_xaxis(list())
    .add_yaxis(
        '微博热度',
        list()
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(),
        xaxis_opts=opts.AxisOpts(
            axislabel_opts=opts.LabelOpts(color='#33a3dc'),
            axisline_opts=opts.LineStyleOpts(color='blue'),
        ),
        yaxis_opts=opts.AxisOpts(
            axislabel_opts=opts.LabelOpts(
                color='#33a3dc',
            ),
            axisline_opts=opts.LineStyleOpts(
                color='blue',
            ),
        )
    )
    .set_series_opts(
        label_opts=opts.LabelOpts(position='right', color='#ff1435')
    )
    .reversal_axis()
`

**Comment by sunhailin-Leo** [comment]
@Fyyyyy158 
* 套一层 `Grid`
