### ISSUE TITLE
单独render, geo地图数据没有问题，一旦结合grid，一张图同时添加bar，line，geo的数据就变成不可更改的浮点数了, 

### ISSUE THREAD

**Issue by huangbin415** [pyecharts/pyecharts#1800]
**问题**
单独render, geo地图数据没有问题，一旦结合grid，一张图同时添加bar，line，geo的数据就变成不可更改的浮点数了, 无论数据源是多少，例如北京 一直是 39.90403

**运行环境（系统环境及 pyecharts 版本）**
win10   pyecharts 1.9.0

**代码及截图**
data = [('山东', 230), ('北京', 191), ('上海', 182), ('福建', 159), ('陕西', 116),]
geo = (
        Geo()
            .add_schema(maptype="china", )
            .add("", data, type_=ChartType.EFFECT_SCATTER, )  
            .set_series_opts(label_opts=opts.LabelOpts(is_show=True))
            .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(),
            title_opts=opts.TitleOpts(title="数据地图"),
        )
    )

正常:   北京：191
grid = (
    Grid()
    .add(geo, grid_opts=opts.GridOpts(pos_left="60%"))
    .render("grid_geo_bar.html")
)

有问题：  北京：39.90403
grid = (
    Grid()
    .add(bar, grid_opts=opts.GridOpts(pos_top="50%", pos_right="75%"))
    .add(geo, grid_opts=opts.GridOpts(pos_left="60%"))
    .render("grid_geo_bar.html")
)

**Comment by sunhailin-Leo** [comment]
@huangbin415 
* 把你的代码格式化好先

**Comment by huangbin415** [comment]
@sunhailin-leo
你们grid的demo里面的geo数据也是同样的问题，北京:39.90403
https://gallery.pyecharts.org/#/Grid/grid_geo_bar

from pyecharts import options as opts
from pyecharts.charts import Bar, Geo, Grid
from pyecharts.faker import Faker

bar = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(legend_opts=opts.LegendOpts(pos_left="20%"))
)
geo = (
    Geo()
    .add_schema(maptype="china")
    .add("geo", [list(z) for z in zip(Faker.provinces, Faker.values())])
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(),
        title_opts=opts.TitleOpts(title="Grid-Geo-Bar"),
    )
)

grid = (
    Grid()
    .add(bar, grid_opts=opts.GridOpts(pos_top="50%", pos_right="75%"))
    .add(geo, grid_opts=opts.GridOpts(pos_left="60%"))
    .render("grid_geo_bar.html")
)

**Comment by sunhailin-Leo** [comment]
@sunhailin-Leo 
* 那个不是 bug，是 tooltip 里面的问题，用 JsCode 把 value 返回就好了

**Comment by huangbin415** [comment]
大佬，python刚接触，您说的   “ 用 JsCode 把 value 返回”
没有接触过JsCode， 从哪里把value返回给哪里
可以给个小样吗？十分感谢

**Comment by huangbin415** [comment]
@sunhailin-Leo
大佬，python刚接触，您说的 “ 用 JsCode 把 value 返回”
没有接触过JsCode， 从哪里把value返回给哪里
可以给个小样吗？十分感谢

**Comment by sunhailin-Leo** [comment]
> 大佬，python刚接触，您说的 “ 用 JsCode 把 value 返回”
> 没有接触过JsCode， 从哪里把value返回给哪里
> 可以给个小样吗？十分感谢

https://gallery.pyecharts.org/#/Boxplot/multiple_categories

**Comment by huangbin415** [comment]
@sunhailin-Leo   按照您给的案例添加如下代码，有文字显示，但是没有数值，数值提示 undefined，请大佬指点，或者您亲测一下，万分感谢！

![捕获](https://user-images.githubusercontent.com/59212727/108618451-5a403200-7459-11eb-922e-0fdc99bcb7c7.JPG)


data = [('山东', 230), ('北京', 191), ('上海', 182), ('福建', 159), ('陕西', 116),]
geo = (
        Geo()
            .add_schema(maptype="china", )
            .add("", data1, type_=ChartType.EFFECT_SCATTER,
                 tooltip_opts=opts.TooltipOpts(
                     formatter=JsCode(
                         """function(param) { return [
                                       'name:'+ param.data[1],
                                       'num:'+ param.data[0],
                                 ].join('<br/>') }"""
                                             )
                                         ),

                 )  # [list(z) for z in zip(Faker.provinces, Faker.values())],
            .set_series_opts(label_opts=opts.LabelOpts(is_show=True))
            .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(),
            title_opts=opts.TitleOpts(title="数据地图"),
            #tooltip_opts=opts.TooltipOpts(trigger="item", axis_pointer_type="shadow"),
        )
    )

**Comment by huangbin415** [comment]
@sunhailin-Leo 

找到原因了，问题已解决，感谢大佬！
