### ISSUE TITLE
修改MarkPointItem字体颜色

### ISSUE THREAD

**Issue by LipidAnalysis** [pyecharts/pyecharts#1803]
**问题**
想实现如下图matplotlib所示的效果
![matplotlib_annotation](https://user-images.githubusercontent.com/38528225/108697404-c5fbcb00-753d-11eb-823e-519abd772f46.png)

但只能实现如下的效果
![pyecharts_annotation](https://user-images.githubusercontent.com/38528225/108697671-1f63fa00-753e-11eb-9e4d-2fcb71f29baf.png)

现在pyecharts标记点背景颜色是红色，字体是黑色，想把背景颜色置为透明，字体颜色制成黑色，并修改字体大小
尝试方案： 
1 确定标注点：line.add_yaxis(markpoint_opts = opts.MarkPointOpts(data = [opts.MarkPointItem]))，
2 标注点背景颜色置为透明： opts.MarkPointItem(itemstyle_opts = options.ItemSytleOpts(opacity = 0))，
3 现在问题是：如果把标记点的背景颜色设置成透明，字体颜色还是白色就什么都看不到了，想知道标注点的字体颜色和大小在哪里设置？

**运行环境（系统环境及 pyecharts 版本）**
系统环境： Windows 10
pyecharts版本： 1.9.0

**代码及截图**
```
from pyecharts.charts import Line, Page
from pyecharts import options
import numpy
import matplotlib.pyplot as plt

x = numpy.random.random(30)
x = numpy.sort(x)
y = numpy.random.random(30)
plt.plot(x, y)
markpoint_where = numpy.r_[True, y[1:] > y[:-1]] & numpy.r_[y[:-1] > y[1:], True]
markpoint_list = []
for index_markpoint in range(len(markpoint_where)):
    if markpoint_where[index_markpoint]:
        markpoint_list.append(options.MarkPointItem(
            coord = [x[index_markpoint], y[index_markpoint]], 
            value = str(round(x[index_markpoint], 2)),
            itemstyle_opts = options.ItemStyleOpts(
                opacity = 1,
                #opacity = 0,
            )
        ))
        plt.annotate(str(round(x[index_markpoint], 2)),xy =(x[index_markpoint], y[index_markpoint]))

plt.show()
line = (
    Line()
    .add_xaxis(x)
    .add_yaxis(
        "xic",
        y,
        is_symbol_show = False,
        markpoint_opts = options.MarkPointOpts(data = markpoint_list),
    )
    .render("render.html")
)
```

**Comment by LipidAnalysis** [comment]
已解决，通过在line.overlap(scatter)即可实现

**Comment by Charmve** [comment]
@LipidAnalysis 能把scatter 这部分代码也发一下吗 谢谢
