### ISSUE TITLE
Bug:  在源代码 class Line(RectChart): def add_yaxis 函数， 发生在双x轴时

### ISSUE THREAD

**Issue by shfengcj** [pyecharts/pyecharts#1806]
在源代码 class Line(RectChart): def add_yaxis 函数中：

> 代码：/pyecharts/charts/basic_charts/line.py

        if all([isinstance(d, opts.LineItem) for d in y_axis]):
            data = y_axis
        else:
            # 合并 x 和 y 轴数据，避免当 X 轴的类型设置为 'value' 的时候，
            # X、Y 轴均显示 Y 轴数据
            # data = [list(z) for z in zip(self._xaxis_data, y_axis)]   ######### 当绘制双x轴时，这个语句会出现问题，只合并第一个x轴
            # 建议采用：
            if xaxis_index is not None:
                data = [list(z) for z in zip(self.options["xAxis"][xaxis_index]["data"], y_axis)]
            else:
                data = [list(z) for z in zip(self._xaxis_data, y_axis)]

**Comment by sunhailin-Leo** [comment]
@shfengcj 
* Show me your reason, please.

**Comment by shfengcj** [comment]
When you add a second x-axis like this:

>  Line()
>         .add_xaxis(xaxis_data=ttc['no'].values.tolist())
>         .extend_axis(xaxis_data=ddc['no'].values.tolist(), .....

the add_xaxis will call 

>     def add_xaxis(self, xaxis_data: Sequence):
>         self.options["xAxis"][0].update(data=xaxis_data)
>         self._xaxis_data = xaxis_data
>         return self

here, self._xaxis_data = xaxis_data takes the first x-axis data as self._xaxis_data, then  .extend_axis function adds another x-axis by calling:

>   def extend_axis(
>         self,
>         xaxis_data: Sequence = None,
>         xaxis: types.Axis = None,
>         yaxis: types.Axis = None,
>     ):
>         if xaxis is not None:
>             if isinstance(xaxis, opts.AxisOpts):
>                 xaxis = xaxis.opts
>             xaxis.update(data=xaxis_data)
>             self.options["xAxis"].append(xaxis)
>         if yaxis is not None:
>             if isinstance(yaxis, opts.AxisOpts):
>                 yaxis = yaxis.opts
>             self.options["yAxis"].append(yaxis)
>         return self

now we have two x-axis but the self._xaxis_data is always refer to the first x-axis data.  Then, we need to add y-axis by calling : 
the add_yaxis function, in which it calls

> data = [list(z) for z in zip(self._xaxis_data, y_axis)]

remember that the self._xaxis_data refers two the first x-axis data, if the y-axis corresponds to the second x-axis data it will be wrong. 

You can try plot two lines:  Line1:  (x1, y1) , Line2:  (x2, y2) and the length of x1 data is smaller than  x2 data, you will plot (x1,y2) for the second line.  

e.g. 
x1: 1,2,3,4,5,6 , y1: 5,3,4,5,6  (with six points )
x2: 1,2,3,4,5,6,7,8, y2: 3,4,5,3,2,1,5,8 (with eight points)
you will get only six points for the second line.  

That's what I want to report. The solution could be 

>  data = [list(z) for z in zip(self.options["xAxis"][xaxis_index]["data"], y_axis)]

which will choice the wright x-axis data for y-axis corresponds to the setting of y-axis when you call the add_yaxis function with parameter xaxis_index.

**Comment by sunhailin-Leo** [comment]
@shfengcj 
* Show me your example with full code( After markdown format).

**Comment by shfengcj** [comment]
Your pyecharts project is really useful  so I reported and explained this bug very clearly with a simple example above. However, to deal with this bug is not my responsibility and I am sorry  that I have no time to write full-code as you required.

**Comment by sunhailin-Leo** [comment]
@shfengcj 
* Do you think your description is clear enough? No snapshot, no full example code. We think your issue is useless !
