### ISSUE TITLE
使用dict类型的数据绘制Line时无显示

### ISSUE THREAD

**Issue by hbhuyt** [pyecharts/pyecharts#1807]
**问题**
折线图Line使用字典数据时无显示

**运行环境（系统环境及 pyecharts 版本）**
在python3.7（64位）pyechart 1.8.1和1.9版本下测试

**代码及截图**
以下代码从pyecharts-gallery-master\Bar\stack_bar_percent.py简单修改Bar为Line生成

from pyecharts import options as opts
from pyecharts.charts import Line
from pyecharts.commons.utils import JsCode
from pyecharts.globals import ThemeType

list2 = [
    {"value": 12, "percent": 12 / (12 + 3)},
    {"value": 23, "percent": 23 / (23 + 21)},
    {"value": 33, "percent": 33 / (33 + 5)},
    {"value": 3, "percent": 3 / (3 + 52)},
    {"value": 33, "percent": 33 / (33 + 43)},
]

list3 = [
    {"value": 3, "percent": 3 / (12 + 3)},
    {"value": 21, "percent": 21 / (23 + 21)},
    {"value": 5, "percent": 5 / (33 + 5)},
    {"value": 52, "percent": 52 / (3 + 52)},
    {"value": 43, "percent": 43 / (33 + 43)},
]

c = (
    Line(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
    .add_xaxis([1, 2, 3, 4, 5])
    .add_yaxis("product1", list2, stack="stack1")
    .add_yaxis("product2", list3, stack="stack1")
    .set_series_opts(
        label_opts=opts.LabelOpts(
            position="right",
            formatter=JsCode(
                "function(x){return Number(x.data.percent * 100).toFixed(2) + '%';}"
            ),
        )
    )
    .render("stack_line_percent.html")
)

对比stack_bar_percent.py 和以上代码生成的html，可以发现在Line折线图时
生成数据部分如下
            "data": [
                [
                    1,
                    {
                        "value": 12,
                        "percent": 0.8
                    }
                ],
                [
                    2,
                    {
                        "value": 23,
                        "percent": 0.5227272727272727
                    }
                ],
                [
                    3,
                    {
                        "value": 33,
                        "percent": 0.868421052631579
                    }
                ],
                [
                    4,
                    {
                        "value": 3,
                        "percent": 0.05454545454545454
                    }
                ],
                [
                    5,
                    {
                        "value": 33,
                        "percent": 0.4342105263157895
                    }
                ]
            ],
如果将其修改为以下，则可以正常显示两条折线。
            "data": [
                
                    {
                        "value": 12,
                        "percent": 0.8
                    }
                ,
                
                    {
                        "value": 23,
                        "percent": 0.5227272727272727
                    }
                ,

                    {
                        "value": 33,
                        "percent": 0.868421052631579
                    }
                ,
                    {
                        "value": 3,
                        "percent": 0.05454545454545454
                    }
                ,
                    {
                        "value": 33,
                        "percent": 0.4342105263157895
                    }

            ],

**Comment by hbhuyt** [comment]
看了一下pyechart源代码，尝试自己解决。
修改pyecharts/pyecharts/charts/basic_charts/bar.py 第51行

line49            # 合并 x 和 y 轴数据，避免当 X 轴的类型设置为 'value' 的时候，
line50            # X、Y 轴均显示 Y 轴数据
line51            # data = [list(z) for z in zip(self._xaxis_data, y_axis)]
直接改为 data=y_axis解决问题。

**Comment by sunhailin-Leo** [comment]
@hbhuyt 
* 为什么要用 `dict` 来画图？

**Comment by ajfg93** [comment]
> 看了一下pyechart源代码，尝试自己解决。 修改pyecharts/pyecharts/charts/basic_charts/line.py 第51行
> 
> line49 # 合并 x 和 y 轴数据，避免当 X 轴的类型设置为 'value' 的时候， line50 # X、Y 轴均显示 Y 轴数据 line51 data = [list(z) for z in zip(self._xaxis_data, y_axis)] 直接改为 data=y_axis解决问题。

awesome！ 非常需要这个，十分感谢！

**Comment by ajfg93** [comment]
> @hbhuyt
> 
> * 为什么要用 `dict` 来画图？

因为我想在Tooltip上展示一些metadata（老板给我的需求），所以我的数据源是a list of dicts。

![image](https://user-images.githubusercontent.com/13542534/142186082-40eb9357-fbcd-4413-ae7d-58c5bcedddf9.png)
