### ISSUE TITLE
pyecharts能否生成复合饼图（子母图）

### ISSUE THREAD

**Issue by YiqinXu** [pyecharts/pyecharts#1808]
刚开始学习使用pyecharts，请问pyecharts能否生成复合饼图（子母图）
比如：

![image](https://user-images.githubusercontent.com/44312441/109921180-68623e00-7cf6-11eb-9f07-1c7bcf728edf.png)

另外，pyecharts能不能支持在linux环境下（无图形界面以及浏览器driver）生成图片，

谢谢！

**Comment by sunhailin-Leo** [comment]
@YiqinXu 
* 1、子母图倒没有，不过可以根据数据自行生成多饼图
* 2、可以用 `https://github.com/pyecharts/snapshot-pyppeteer` 这个在 docker 环境中生成
