### ISSUE TITLE
图像设置颜色bug@YiqinXu

### ISSUE THREAD

**Issue by YiqinXu** [pyecharts/pyecharts#1809]
@YiqinXu 
* 1、子母图倒没有，不过可以根据数据自行生成多饼图
* 2、可以用 `https://github.com/pyecharts/snapshot-pyppeteer` 这个在 docker 环境中生成

_Originally posted by @sunhailin-Leo in https://github.com/pyecharts/pyecharts/issues/1808#issuecomment-791083366_

您好，
我自己尝试通过把折线图和饼图结合的方式，来绘制子母图。

但是我发现使用overlap方法后，后面的颜色设置会把前面的颜色设置变为无效，这种情况应该怎么解决呢？

例如：
![image](https://user-images.githubusercontent.com/44312441/110087043-1a206e00-7dce-11eb-90bd-f5ae3865c9b7.png)

代码如下：
from pyecharts import options as opts
from pyecharts.charts import Pie,Line

data = [['A',60],['B',30],['C',30],['D',20],['E',10]]
c = (
    Pie()
    .add("", data,center=["30%", "50%"],radius=100,)
    .add("", data,center=["65%", "50%"],radius=60,)
    .set_colors(["blue", "green", "yellow", "red", "pink"])
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
)
line1 = (
    Line()
    .add_xaxis([25,68])
    .add_xaxis([25,68])
    .add_yaxis("",[77,66],color="black",label_opts=opts.LabelOpts(is_show=False))
    .add_yaxis("",[23,34],color="black",label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(legend_opts=opts.LegendOpts(is_show=False))
    .set_global_opts(xaxis_opts=opts.AxisOpts(is_show=True,type_='value',min_=0,max_=100)
                    ,yaxis_opts=opts.AxisOpts(is_show=True,type_='value',min_=0,max_=100))
)
line1.overlap(c)
line1.render_notebook()

谢谢

**Comment by sunhailin-Leo** [comment]
@YiqinXu 
* 单独设置饼图的颜色。Echarts 的颜色和系列名`series_name`绑定的

**Comment by YiqinXu** [comment]
单独设置饼图的颜色是什么意思，能否举个例子呢，
十分感谢！
