### ISSUE TITLE
如何使提示框在生成图片时显示？

### ISSUE THREAD

**Issue by RedElectricity** [pyecharts/pyecharts#1810]
**问题**
如何使提示框在生成图片时显示？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.90
python 3.7.3
win server 2019

**代码及截图**
`line.set_global_opts(title_opts=opts.TitleOpts("B5查询",subtitle=f"用户名:{datai['content']['name']} PTT:{datai['content']['rating'] / 100:.2f}"),tooltip_opts=opts.TooltipOpts(is_show=True,trigger_on='none',is_always_show_content=True,border_width=2,axis_pointer_type='cross'))`

**Comment by RedElectricity** [comment]
![image](https://user-images.githubusercontent.com/75127571/110243223-6cab8700-7f94-11eb-80c1-b4fbae0d1816.png)

**Comment by RedElectricity** [comment]
![Uploading 1654723334-1136327638-DA1094E338913B94101D2A5EEFBC1E71.png…]()

**Comment by RedElectricity** [comment]
<img width="900" alt="1654723334-1136327638-DA1094E338913B94101D2A5EEFBC1E71" src="https://user-images.githubusercontent.com/75127571/110243320-c2802f00-7f94-11eb-99c5-668877e5b5c0.png">

**Comment by RedElectricity** [comment]
或者，如何自定义标签？

**Comment by sunhailin-Leo** [comment]
@RedElectricity 
* 自定义标签的话 Pie 的 Demo 中有使用富文本的方式进行设置。https://gallery.pyecharts.org/#/Pie/pie_rich_label

**Comment by RedElectricity** [comment]
那折线图可以自定义吗
