### ISSUE TITLE
pyecharts饼图支持调整startangle吗

### ISSUE THREAD

**Issue by YiqinXu** [pyecharts/pyecharts#1811]
您好，

饼图暂时不支持设置startangle吗？如果支持的话，应该调用什么方法呢，我在手册中暂时没发现相关的方法。

谢谢

**Comment by sunhailin-Leo** [comment]
@YiqinXu 
* 暂时没加这个配置进去

**Comment by sunhailin-Leo** [comment]
@YiqinXu 
* 如果需要的话可以自行加到源码里面（参考如下）。
![image](https://user-images.githubusercontent.com/17564655/110426800-a938c900-80e1-11eb-8c07-c88b9d089444.png)

**Comment by YiqinXu** [comment]
解决了，设置以后可以了，谢谢！
