### ISSUE TITLE
How to convert the resulting image into a binary stream

### ISSUE THREAD

**Issue by Deep-sea-boy** [pyecharts/pyecharts#1812]
How to convert the resulting image into a binary stream？
I don't want a html result

`
from pyecharts import options as opts
from pyecharts.charts import Pie
from io import BytesIO

buffer = BytesIO()
pie = (
    Pie()
        .add("", [list(z) for z in zip(["aa", "bb", "cc", "dd", "ee", "ff"], [11, 12, 13, 10, 10, 10])])
        .set_global_opts(title_opts=opts.TitleOpts(title="sample"))
        .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
)

pie.render('pie.html')
# todo
buffer.write()  
`

**Comment by sunhailin-Leo** [comment]
@Deep-sea-boy 
* Maybe you can use `snapshot` to convert. (`snapshot-pyppeteer`, `snapshot-selenium` or `snapshot-phantomjs`).
* After using snapshot to render static image, you can convert image object to binary stream.
