### ISSUE TITLE
平行坐标系中如何为每一组参数生成不同的颜色，最好是渐变的？

### ISSUE THREAD

**Issue by szhang963** [pyecharts/pyecharts#1813]
**问题**

如题，我看了文档，以及源码，尝试了很多方法，最多只有为整个图加渐变，不能实现每条曲线不同的颜色，想问问如何实现这个？感谢

**运行环境（系统环境及 pyecharts 版本）**

win10  1.9

**Comment by sunhailin-Leo** [comment]
@szhang963 
* 得使用一些 echarts 本身的 api 去做渐变了。用 pyecharts 实现起来有点难度。
