### ISSUE TITLE
Map3D地图中如何修改某个省份的颜色

### ISSUE THREAD

**Issue by qianxingdu** [pyecharts/pyecharts#1815]
**问题**
请问 Map3D 中，绘制中国地图时，如何单独修改其中某个省份的颜色，谢谢！

**运行环境（系统环境及 pyecharts 版本）**
运行环境：pyecharts 1.9.0

**代码及截图**

![image](https://user-images.githubusercontent.com/59285048/111438141-dff48c00-873e-11eb-8a71-0f50d276d3c5.png)

**Comment by sunhailin-Leo** [comment]
@qianxingdu 
* 这个的话可能目前暂时无法实现。（毕竟用这个 Map3D 的人比较少）

**Comment by sunhailin-Leo** [comment]
@qianxingdu 
* 如果你解决了这个问题的话，可以与我们分享一下。 😄
