### ISSUE TITLE
pyecharts 可以嵌到 pyqt5 中吗？

### ISSUE THREAD

**Issue by lyl1836** [pyecharts/pyecharts#1816]
pyecharts是很棒！为国人点赞！

我正用 pyqt5 开发一个可视化的生产排程工具，需要一个可视化的图表展现工具。

要求：
1、在 pyqt5 上指定参数，如：数据源、时间范围、表式样之类的；
2、根据第一条制定的相关数据，画出图表，并显示在 pyqt5 相应的组件中。

请问：pyecharts 可以嵌在 pyqt5 的应用中吗？

**Comment by sunhailin-Leo** [comment]
@lyl1836 
* 可以参考这个：https://github.com/pyecharts/pyecharts/issues/1698
