### ISSUE TITLE
我这全部盖住了要怎么配置？

### ISSUE THREAD

**Issue by slin1972** [pyecharts/pyecharts#1818]
![image](https://user-images.githubusercontent.com/7867412/112087996-f892f500-8bc9-11eb-9058-77c7ecce4335.png)

**Comment by slin1972** [comment]
上面的各指标   盖住了下面的图表，并且标题也覆盖了指标

**Comment by sunhailin-Leo** [comment]
@slin1972 
* 用垂直布局吧
