### ISSUE TITLE
如何动态的更新数据

### ISSUE THREAD

**Issue by liudonghua123** [pyecharts/pyecharts#1819]
**问题**
例如有一个柱状图，y坐标初始有商家A信息，之后我想在原图基础上添加商家B信息，但目前不知道是我实现的方式有问题，实现不了

**运行环境（系统环境及 pyecharts 版本）** Windows, notebook, 1.9.0

**代码及截图**

```python
from pyecharts import options as opts
from pyecharts.charts import Bar
from time import sleep

bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.render_notebook()

# try to update the bar chart later
sleep(3)
bar.add_yaxis("商家B", [15, 10, 26, 20, 35, 30])
# bar.render_notebook()
```

**Comment by liudonghua123** [comment]
我大概想实现的就是类似于 https://www.w3cschool.cn/echarts_tutorial/echarts_tutorial-m16h28xk.html, https://echarts.apache.org/examples/en/editor.html?c=doc-example/tutorial-async 这里的效果，可以动态添加、修改数据

原生 js 实现起来非常简单，但可能 pycharts 是转换成静态的 js 代码的，所以可能很难实现。

js 类似功能的代码示例

```js
function fetchData(cb) {
    // 通过 setTimeout 模拟异步加载
    setInterval(function () {
        console.info('setTimeout')
        cb({
            categories: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"],
            data: [Math.floor(Math.random()*30), Math.floor(Math.random()*30), Math.floor(Math.random()*30), Math.floor(Math.random()*30), Math.floor(Math.random()*30), Math.floor(Math.random()*30)]
        });
    }, 1000);
}

// 初始 option
option = {
    title: {
        text: '异步数据加载示例'
    },
    tooltip: {},
    legend: {
        data:['销量']
    },
    xAxis: {
        data: []
    },
    yAxis: {},
    series: [{
        name: '销量',
        type: 'bar',
        data: []
    }]
};

fetchData(function (data) {
    console.info(`got new data `, data)
    myChart.setOption({
        xAxis: {
            data: data.categories
        },
        series: [{
            // 根据名字对应到相应的系列
            name: '销量',
            data: data.data
        }]
    });
});
```

**Comment by liudonghua123** [comment]
目前我实现的方式还是需要 javascript 去更新数据，参考 https://nbviewer.jupyter.org/gist/liudonghua123/01c19fcd981b867a07c38aee25107eb8

**Comment by HQDragon** [comment]
是不是基于interact可以做到呢？参考ipywidget和ipympl

**Comment by liudonghua123** [comment]
@HQDragon, 即使使用[interact](https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html#Using-Interact), [ipympl](https://github.com/matplotlib/ipympl/blob/master/examples/ipympl.ipynb)，应该也很难配合 pyecharts 实现动态更新数据，因为当你调用 render_notebook 的时候，就是一锤子买卖，生成了静态的html内容然后渲染，无法于python生成的数据进行交互；目前我能想到的方法就是 https://nbviewer.jupyter.org/gist/liudonghua123/01c19fcd981b867a07c38aee25107eb8 这里的，核心是需要先禁用require.js（这块确实花了不少时间，网上能找到的教程都是使用require.js），因为需要全局graph对象以便于后面进行修改，然后python传递数据到js，js重新渲染图，或者写一个js更新图的函数，在python中调用此函数。

如果有更好的方式可以大家讨论一下~

**Comment by sunhailin-Leo** [comment]
@liudonghua123 
* 通过 web 框架 + js 会比较好实现。
* notebook 本身就是偏静态展示的产物，为什么要把动态的需求放到静态产物身上？

**Comment by HQDragon** [comment]
@liudonghua123 如果目前迫切有需求，建议你使用plotly或者参考plotly的figurewidget手动实现。尽管render_notebook是一锤子买卖，但是可以在ipywidget中刷新这个锤子，并且每次都重新砸锤子更新html。

@sunhailin-Leo 数据的动态更新在某些领域是极其有效的,其中动态更新分为已知全部桢数据但通过动画化显示annimation、数据在未来更新通过函数改变图表，尤其是涉及对比的时候。还是可以计划将其作为pyecharts的某一个大版本feature的

**Comment by sunhailin-Leo** [comment]
@HQDragon 
* 我只会建议你通过 `web` 服务的方式提供展示，而不是使用 `notebook`
