### ISSUE TITLE
echarts.min.js静态资源太慢的问题

### ISSUE THREAD

**Issue by anrgct** [pyecharts/pyecharts#1822]
我用vscode运行jupyter，使用render_notebook生成的cell是空白的，很奇怪，后面不知道怎么回事又好了。
我突然想到可能是https://assets.pyecharts.org/assets/echarts.min.js 太慢了，导致空白卡住了，然后加载过一次以后就不会再请求了，所以就好了，建议把这个静态资源换成cdn的。

**Comment by sunhailin-Leo** [comment]
@anrgct 
* 资源有 CDN，但是 VSCODE 没有缓存
