### ISSUE TITLE
如何自定义geo提示框，同时显示不同的数值

### ISSUE THREAD

**Issue by xinjinwu** [pyecharts/pyecharts#1823]
Tooltip中回调函数只能显示name和一个value，能不能针对每个城市自定义显示其他数值

**Comment by sunhailin-Leo** [comment]
@xinjinwu 
* 传 `value` 的时候可以传列表，在回调函数中自行解析或者自行写 js 的逻辑展示数据，通过 `add_js_func` 传入全局变量。
