### ISSUE TITLE
桑基图无法改别节点的显示顺序，设置了layout_iterations=0也无法按照传入data的顺序显示。

### ISSUE THREAD

**Issue by chenshuai17** [pyecharts/pyecharts#1824]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@chenshuai17 
* 补充一下示例和代码，谢谢。

**Comment by wuhanlt** [comment]
有前人大神答复过，需要修改sankey.py的源码，将下面两句注释掉，否则改成0也没用，并把 layoutIteration 后面加一个 s
    if layout_iterations < 32:
        layout_iterations = 32
