### ISSUE TITLE
flask前后端分离内容不显示的问题

### ISSUE THREAD

**Issue by youthmyth** [pyecharts/pyecharts#1826]
不知道有人遇到过这个问题么，flask前后端分离内容不显示，左右看没看出问题。
最后发现是html页面的url设置故障。

所有的示例文件中都显示
`$.ajax({   
           url: "http://127.0.0.1:5000/barChart",
  }`
但最后成功的是省略写法
`$.ajax({
            url: "/barChart",
  }`

难道因为改成0.0.0.0的服务器地址的原因？毕竟这是一份基础示例，调试了整整一天，很好奇没有其他人遇到过么？

仅供参考。

**Comment by sunhailin-Leo** [comment]
@youthmyth 
* 省略写法是你的前后端同域下的可以使用，跨域得指定地址。
