### ISSUE TITLE
折线图的numerical axis功能是否有实现思路？

### ISSUE THREAD

**Issue by zszzlmt** [pyecharts/pyecharts#1832]
**问题**

hello，我注意到折线图pyecharts是仅支持xy轴类别为category，而原生的echarts是支持numerical的。之前因为有这方面需要，一直是python代码中拼接html字符串来实现numerical的html输出。
但最近希望生成numerical的图片，这样可能就涉及python通过PhantomJS等调用js命令来生成。想问下pyecharts这边有没有更好的办法，比如从哪里入手实现这个功能，限制主要在哪里。如果可以的话，希望能提供大致思路，我去试试实现。
感谢！

**运行环境（系统环境及 pyecharts 版本）**

无

**代码及截图**

无

**Comment by sunhailin-Leo** [comment]
@zszzlmt 
* 轴类别还有 `value`

**Comment by zszzlmt** [comment]
> @zszzlmt
> 
> * 轴类别还有 `value`

感谢，我这就尝试下！
