### ISSUE TITLE
Table表格组件，是否支持增加a标签

### ISSUE THREAD

**Issue by wangyue0101** [pyecharts/pyecharts#1836]
**问题**

**运行环境（系统环境及 pyecharts 版本）**
WIN 10,
python 3.8
pyecharts 1.9

**代码及截图**
![image](https://user-images.githubusercontent.com/6122973/114807080-605aeb00-9dd8-11eb-8cbb-8751e0edbfc3.png)
请问Table组件中的某个td支持新增a标签的类型吗，或者Table组件的主副标题支持link也可以，我在Table的标题配置ComponentTitleOpts中未找到支持跳转的配置，希望可以增加这个功能

**Comment by sunhailin-Leo** [comment]
@wangyue0101 
* Table 内部内容暂时不会支持 a 标签的。涉及的样式问题特别多，如果要
