### ISSUE TITLE
Heatmap大小无法调整

### ISSUE THREAD

**Issue by JaydenGao-gjd** [pyecharts/pyecharts#1837]
**问题**

Heatmap的画布大小修改后无效果，我用的HeatMap(init_opts=opts.InitOpts(width="5000px", height='500px'))，调整后一直是下图的效果。

**运行环境（系统环境及 pyecharts 版本）**
Pycharm + pyecharts1.9.0

**代码及截图**

![image](https://user-images.githubusercontent.com/56961646/115144848-717a5500-a081-11eb-9a49-977f921a90f8.png)

![image](https://user-images.githubusercontent.com/56961646/115144873-94a50480-a081-11eb-93cc-5a6ff4e2ac52.png)

**Comment by sunhailin-Leo** [comment]
@JaydenGao-gjd 
* InitOpts 是改画布的，不是改 HeatMap 的
