### ISSUE TITLE
中国城市级别的3Dmap

### ISSUE THREAD

**Issue by Yuchen971** [pyecharts/pyecharts#1838]
**问题**
请问是否有中国城市级别的3D map base？ 
我把maptype="china-cities" 结果不渲染。

**运行环境（系统环境及 pyecharts 版本）**
jupyter lab
最新的pyecharts

**Comment by sunhailin-Leo** [comment]
@Yuchen971 
* Map3D 本身支持的很有限，需要 3D 的中国地图资源

**Comment by Yuchen971** [comment]
谢谢！
