### ISSUE TITLE
时间线不显示图表

### ISSUE THREAD

**Issue by kxtv77** [pyecharts/pyecharts#1839]
**问题**
想要给日历图加上timeline组件，但是加上之后日历图不显示。
同样的代码把timeline组件换成tab就没有问题。

**运行环境（系统环境及 pyecharts 版本）**
Win 10
pyecharts 版本：1.9.0

**代码及截图**
![image](https://user-images.githubusercontent.com/57525472/115968939-2c976800-a532-11eb-9277-df9a624af784.png)

**Comment by sunhailin-Leo** [comment]
@kxtv77 
* 能发一下代码和数据源给我嘛？我帮你测试下

**Comment by quhanxi** [comment]
我也是显示不了图表。单个的日历图是可以正常显示的，但是配合Timeline就不显示了
<img width="695" alt="calendar-time" src="https://github.com/pyecharts/pyecharts/assets/118235418/a6fee006-177d-4cdc-950f-0f48dd5d1398">

**Comment by cinyan10** [comment]
> 我也是显示不了图表。单个的日历图是可以正常显示的，但是配合Timeline就不显示了 <img alt="calendar-time" width="695" src="https://private-user-images.githubusercontent.com/118235418/300168004-a6fee006-177d-4cdc-950f-0f48dd5d1398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODYwNDAsIm5iZiI6MTcxNTA4NTc0MCwicGF0aCI6Ii8xMTgyMzU0MTgvMzAwMTY4MDA0LWE2ZmVlMDA2LTE3N2QtNGNkYy05NTBmLTBmNDhkZDVkMTM5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxMjQyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmY5MTJiYzUyYTJjNzY5YmM5MzU5MjU2YTZlOWNiNGIzNzg1ZjcwNjBjNGJiMTdjYzBmNDU1Y2RhMmJmNjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FjU6mf6Sw3z_vufeXgsbXM0PFhHvumKALWPb8hzH_eE">

我也是

**Comment by quhanxi** [comment]
您好，lty已收到来信，将尽快给你回复。

**Comment by honeyjerry** [comment]
请问解决了吗？我也是遇到了同样的问题

**Comment by quhanxi** [comment]
您好，lty已收到来信，将尽快给你回复。

**Comment by quhanxi** [comment]
没有，我放弃了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月25日(周六) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pyecharts/pyecharts] 时间线不显示图表 (#1839)




 
请问解决了吗？我也是遇到了同样的问题

**Comment by sunhailin-Leo** [comment]
> 请问解决了吗？我也是遇到了同样的问题

* 有问题重新提 issue，并附上代码
