### ISSUE TITLE
散点图，根据不同类型区分颜色

### ISSUE THREAD

**Issue by KevinHooSCUT** [pyecharts/pyecharts#1841]
**问题**
房价举例
X轴为面积、Y轴为房价，画出散点图，但需要根据房型对散点进行颜色区分，比如一室两厅标黄色、两室两厅标蓝色。

**运行环境（系统环境及 pyecharts 版本）**
win7 + pyecharts  1.9

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@KevinHooSCUT 
* 可以尝试使用 ScatterItem 进行数据配置
