### ISSUE TITLE
set DataZoomOpts in Boxplot with vertical mode, and boxplot disappear when zoom

### ISSUE THREAD

**Issue by JisongXie** [pyecharts/pyecharts#1843]
**Problem**

I set DataZoomOpts in Boxplot with vertical mode. However, when I zoom the plot, the box disappears.

**Environment**
I use it in docker. In Dockerfile, I install miniconda to set python environment. 
```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
/bin/bash Miniconda3-latest-Linux-x86_64.sh -f -b -p $CONDA_DIR

pip install pyecharts
```

**Code and Figure**

My code is as follow,
```
boxplot = Boxplot()
boxplot.add_xaxis([“price”])
boxplot.add_yaxis("value", boxplot.prepare_data(y_data))
boxplot.set_global_opts(
        title_opts=opts.TitleOpts(title="price"),
        datazoom_opts=[opts.DataZoomOpts(range_start=0, range_end=100, orient="vertical"), 
                       opts.DataZoomOpts(type_="inside", range_start=0, range_end=100, orient="vertical")],
        toolbox_opts=opts.ToolboxOpts(),
    )
```
![image](https://user-images.githubusercontent.com/28192557/116523458-d5660e80-a908-11eb-9c77-43b9e0b50435.png)
![image](https://user-images.githubusercontent.com/28192557/116523595-f9c1eb00-a908-11eb-949c-7c7c453c3389.png)

**Comment by sunhailin-Leo** [comment]
@JisongXie 
* Try `Horizontal`

**Comment by JisongXie** [comment]
@sunhailin-Leo 
Hi, thank you for your suggestions! However, when I use the `reversal_axis()` and try `Horizontal`, it fails again.
My value is such long-tailed that the box plotted will be shown at the bottom, so I want to zoom it. 
![image](https://user-images.githubusercontent.com/28192557/117610538-8172e980-b194-11eb-80da-88ccba1f0433.png)
![image](https://user-images.githubusercontent.com/28192557/117610608-9f404e80-b194-11eb-8dae-f3f0e9f148f0.png)

**Comment by sunhailin-Leo** [comment]
@JisongXie 
* If remove `reversal_axis()` is ok?

**Comment by JisongXie** [comment]
I only show one feature in one plot, and the value of it is so long-tailed that the box plotted will be shown at the bottom. Thus I want to zoom it. It's helpless when I use horizontal without reversal_axis. 
![image](https://user-images.githubusercontent.com/28192557/117611912-e3345300-b196-11eb-9e04-0a56671d8d83.png)
![image](https://user-images.githubusercontent.com/28192557/117611954-fcd59a80-b196-11eb-99cc-30d0e60722aa.png)

**Comment by sunhailin-Leo** [comment]
@JisongXie 
* Maybe this is the echarts problem. You can see this example in Echarts 5.X, https://echarts.apache.org/examples/zh/editor.html?c=data-transform-aggregate

**Comment by JisongXie** [comment]
@sunhailin-Leo 
Pycharts is the python warpper of echarts. Box in this example also disappear when it zooms out of the axis. Indeed a echarts problem. Thank you!
