### ISSUE TITLE
多个bar在一个grid中时，如何对每个bar添加区域缩放配置？

### ISSUE THREAD

**Issue by wangyue0101** [pyecharts/pyecharts#1846]
**问题**

![image](https://user-images.githubusercontent.com/6122973/117530973-b48d6f80-b012-11eb-96c6-9674829947b7.png)
grid添加多个bar时，可以给每个bar加“区域缩放配置（DataZoomOpts）吗”，我现在给两个bar都加了缩放配置，但是缩放控制只对第一个bar图有效，第二个图无法控制缩放

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by wangyue0101** [comment]
或者如何将同一个页面上的两个bar隔离开，各自配置各自的东西

**Comment by sunhailin-Leo** [comment]
@wangyue0101
* 用 Page 添加两个 Bar 图即可
