### ISSUE TITLE
如何调整饼图(玫瑰图)的标签和饼图之间的距离

### ISSUE THREAD

**Issue by Azure1210** [pyecharts/pyecharts#1849]
**问题**
如何调整饼图的标签和饼图之间的距离?

再做这个之前已经通过PieLabelLineOpts: 饼图标签的视觉引导线样式，将标签视觉引导线去掉了，
通过LabelOpts：标签配置项已经调整了关于标签角度等信息，距离这块改了参数，但是并不能达到预期的效果。

**运行环境（系统环境及 pyecharts 版本）**

pyecharts版本：'1.9.0'
本地Python环境：3.8.8

**代码及截图**
`
from pyecharts.charts import Pie
from pyecharts import options as opts

data_p = [['广东', 346], ['台湾', 345], ['香港', 245], ['上海', 163], ['北京', 140], ['山东', 113], ['陕西', 75], ['河北', 10]]
p = (Pie()
    .add("",[[i[0],i[1]] for i in data_p],
        radius=["10%", "80%"],
        center=["50%", "55%"],
        rosetype="area",
         label_line_opts=opts.PieLabelLineOpts(is_show=False)
        )
    .set_global_opts(
                     legend_opts=opts.LegendOpts(is_show=False),
                     visualmap_opts=opts.VisualMapOpts(
                is_calculable=True,
                is_show=False,
                dimension=0,
                pos_left="10",
                pos_top="top",
                range_text=["High", "Low"],
                range_color=["#66bb54", '#bcd613',"#de7a00", '#ef0101',"#a40102"],
                textstyle_opts=opts.TextStyleOpts(color="#ddd"),max_=140,min_=1
            ),
            
                    )
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b} {c}",position='top',rotate=[10],
                                               interval=1,color='#343434',distance=10,
                                              horizontal_align='center',vertical_align='insideTop',margin=2))
    )
p.render_notebook()
`
![aaa](https://user-images.githubusercontent.com/41717746/118442754-9532c880-b71d-11eb-8d1f-06cf04d01cec.jpg)

**Comment by sunhailin-Leo** [comment]
@Azure1210 
* Echarts 默认都是等距的。如果要实现的话估计得通过对应的配置的 js 回调函数实现。
