### ISSUE TITLE
按照BMap示例Bmap-Air_quality_baidu_map，只修改了坐标和数据，抛出异常说坐标不存在

### ISSUE THREAD

**Issue by 627992512** [pyecharts/pyecharts#1851]
**问题**
我按照BMap的示例Bmap-Air_quality_baidu_map，将坐标和数据改成了我们学校用来测试，只修改了坐标和数据，抛出异常说坐标不存在

**运行环境（系统环境及 pyecharts 版本）**
python3.8
pyecharts1.9.0

**代码及截图**
代码:
from pyecharts import options as opts
from pyecharts.charts import BMap
data = [
    ["主楼", 5740000],
    ["东配楼", 710400],
    ["西配楼", 80900],
    ["体育楼", 47025],
    ["水力楼", 148200],
    ["电力楼", 264760],
    ["锅炉房", 711590],
    ["教学1楼", 9840],
    ["教学4楼", 66880],
    ["教学5楼", 47520],
    ["教学6楼", 14400],
    ["教学8楼", 10720],
    ["教学9楼", 135900],
    ["教学10楼", 64330],
    ["学生公寓3号楼", 0],
    ["学生公寓4号楼", 0],
    ["学生公寓5号楼", 200240],
    ["学生公寓6号楼", 38280],
    ["学生公寓7号楼", 117680],
    ["学生公寓8号楼", 153680],
    ["学生公寓9号楼", 195280],
    ["学生公寓10号楼", 308300],
    ["学生公寓11号楼", 112680],
    ["学生公寓12号楼", 156360],
    ["千佛山校区图书馆", 244240],
    ["舜园餐厅", 107750],
    ["西苑餐厅", 26000],
]
geoCoordMap = {
    "主楼": [117.035258,36.65743],
    "东配楼": [117.036084,36.656895],
    "西配楼": [117.034449,36.656768],
    "体育楼": [117.035118,36.652624],
    "水力楼": [117.037422,36.652798],
    "电力楼": [117.036924,36.657025],
    "锅炉房": [117.033173,36.656877],
    "教学1楼": [117.037054,36.65603],
    "教学4楼": [117.033654,36.65578],
    "教学5楼": [117.036919,36.656565],
    "教学6楼": [117.036484,36.655382],
    "教学8楼": [117.033636,36.656359],
    "教学9楼": [117.036166,36.65207],
    "教学10楼": [117.035235,36.652052],
    "千佛山校区图书馆": [117.035644,36.65274],
    "学生公寓3号楼": [117.036358,36.658914],
    "学生公寓4号楼": [117.036385,36.658505],
    "学生公寓5号楼": [117.03312,36.658277],
    "学生公寓6号楼": [117.035729,36.658813],
    "学生公寓7号楼": [117.033124,36.6582845],
    "学生公寓8号楼": [117.033155,36.657937],
    "学生公寓9号楼": [117.0332,36.657546],
    "学生公寓10号楼": [117.03409,36.658299],
    "学生公寓11号楼": [117.033155,36.657937],
    "学生公寓12号楼": [117.034045,36.65751],
    "西苑餐厅": [117.033456,36.657159],
    "舜园餐厅": [117.036699,36.657524],
}
def convert_data():
    res = []
    for i in range(len(data)):
        geo_coord = geoCoordMap[data[i][0]]
        geo_coord.append(data[i][1])
        res.append([data[i][0], geo_coord])
    return res
(
    BMap(init_opts=opts.InitOpts(width="1400px", height="800px"))
    .add(
        type_="effectScatter",
        series_name="pm2.5",
        data_pair=convert_data(),
        symbol_size=10,
        effect_opts=opts.EffectOpts(),
        label_opts=opts.LabelOpts(formatter="{b}", position="right", is_show=False),
        itemstyle_opts=opts.ItemStyleOpts(color="purple"),
    )
    .add_schema(
        baidu_ak="我申请了，实测ak是可用的",
        center=[117.034848,36.656719],
        zoom=19,
        is_roam=True,map_style={
            "styleJson": [
                {
                    "featureType": "water",
                    "elementType": "all",
                    "stylers": {"color": "#044161"},
                },
                {
                    "featureType": "land",
                    "elementType": "all",
                    "stylers": {"color": "#004981"},
                },
                {
                    "featureType": "boundary",
                    "elementType": "geometry",
                    "stylers": {"color": "#064f85"},
                },
                {
                    "featureType": "railway",
                    "elementType": "all",
                    "stylers": {"visibility": "off"},
                },
                {
                    "featureType": "highway",
                    "elementType": "geometry",
                    "stylers": {"color": "#004981"},
                },
                {
                    "featureType": "highway",
                    "elementType": "geometry.fill",
                    "stylers": {"color": "#005b96", "lightness": 1},
                },
                {
                    "featureType": "highway",
                    "elementType": "labels",
                    "stylers": {"visibility": "off"},
                },
                {
                    "featureType": "arterial",
                    "elementType": "geometry",
                    "stylers": {"color": "#004981"},
                },
                {
                    "featureType": "arterial",
                    "elementType": "geometry.fill",
                    "stylers": {"color": "#00508b"},
                },
                {
                    "featureType": "poi",
                    "elementType": "all",
                    "stylers": {"visibility": "off"},
                },
                {
                    "featureType": "green",
                    "elementType": "all",
                    "stylers": {"color": "#056197", "visibility": "off"},
                },
                {
                    "featureType": "subway",
                    "elementType": "all",
                    "stylers": {"visibility": "off"},
                },
                {
                    "featureType": "manmade",
                    "elementType": "all",
                    "stylers": {"visibility": "off"},
                },
                {
                    "featureType": "local",
                    "elementType": "all",
                    "stylers": {"visibility": "off"},
                },
                {
                    "featureType": "arterial",
                    "elementType": "labels",
                    "stylers": {"visibility": "off"},
                },
                {
                    "featureType": "boundary",
                    "elementType": "geometry.fill",
                    "stylers": {"color": "#029fd4"},
                },
                {
                    "featureType": "building",
                    "elementType": "all",
                    "stylers": {"color": "#1a5787"},
                },
                {
                    "featureType": "label",
                    "elementType": "all",
                    "stylers": {"visibility": "off"},
                },
            ]
        },
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(
            title="全国主要城市空气质量",
            subtitle="data from PM25.in",
            subtitle_link="http://www.pm25.in",
            pos_left="center",
            title_textstyle_opts=opts.TextStyleOpts(color="#fff"),
        ),
        tooltip_opts=opts.TooltipOpts(trigger="item"),
    )
    .render_notebook()
)

抛出的异常：
![image](https://user-images.githubusercontent.com/57834276/118624741-ff219f80-b7fb-11eb-8235-6086f132a893.png)

NonexistentCoordinatesException: 当前地点: ('主楼', [117.035258, 36.65743, 5740000]) 坐标不存在, 错误原因: cannot unpack non-iterable NoneType object

请问一下这个坐标有什么讲究吗？

**Comment by sunhailin-Leo** [comment]
@627992512 
* 列表长度为 2
