### ISSUE TITLE
BMap在散点图中不显示地点对应各项数据，而显示地点纬度

### ISSUE THREAD

**Issue by 1-z-1** [pyecharts/pyecharts#1852]
**问题**
pyecharts 在使用BMap添加自定义坐标点add_coordinate传入名称以及经纬度三个参数之后，在后面进行add的时候，选择各类散点图都会使，data_pair传递的参数输出在图中显示为纬度，而不正确显示data_pair传递的参数。

此问题在官方示例中也存在。示例：（Bmap - Air_quality_baidu_map）
图中的散点并未显示，data中的pm2.5指数，而显示的是各点地图纬度。

**运行环境（系统环境及 pyecharts 版本）**
python 3.9.5
pyecharts 1.9.0

**代码及截图**

官方示例

**Comment by sunhailin-Leo** [comment]
@1-z-1 
* 可以通过 jsFunc 调整回调函数的返回值
