### ISSUE TITLE
Jupyterhub pyecharts 显示空白

### ISSUE THREAD

**Issue by EnchoC** [pyecharts/pyecharts#1853]
**问题**
`pie.render_notebook()`显示空白

**运行环境（系统环境及 pyecharts 版本）**
Ubuntu 20.04.2 LTS
Jupyterlab 3.0.14
Jupyterhub  未知
pyecharts 1.9.0

**代码及截图**
```python
from pyecharts.charts import *
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB
CurrentConfig.ONLINE_HOST="https://cdn.kesci.com/lib/pyecharts_assets/"
cate = ['Apple', 'Huawei', 'Xiaomi', 'Oppo', 'Vivo', 'Meizu']
data = [123, 153, 89, 107, 98, 23]

pie = (Pie()
       .add('', [list(z) for z in zip(cate, data)])
       )

pie.load_javascript();

pie.render_notebook()

```
![image](https://user-images.githubusercontent.com/28055454/119079089-029a6e00-ba2a-11eb-92ec-4a3fa850993b.png)
`Uncaught ReferenceError: echarts is not defined`

**Comment by sunhailin-Leo** [comment]
@EnchoC 
* `load_javascript` 要分开 cell

**Comment by EnchoC** [comment]
我运行的时候是分开的，贴出来没有分开而已。。

**Comment by EnchoC** [comment]
> @EnchoC
> 
> * `load_javascript` 要分开 cell

我运行的时候是分开的，贴出来没有分开而已。。
