### ISSUE TITLE
Timeline允许用户设置默认选中的时间轴点

### ISSUE THREAD

**Issue by featherain80** [pyecharts/pyecharts#1854]
Timeline组件在用户禁用自动播放的功能下能否允许用户自定义默认选中的时间轴点？我查了下Timeline的选项设置，没找到这个功能。
如下图：在不自动播放的情况下，默认选中的是2015，但是我想要自定义默认为2018.

![image](https://user-images.githubusercontent.com/84707327/119321862-aba5ca80-bcaf-11eb-82e9-ce92a71a075f.png)

**Comment by sunhailin-Leo** [comment]
@featherain80 
* Echarts 目前没看到有设置默认值的配置
