### ISSUE TITLE
绘制折线图时x轴数据和y轴并不一一对应

### ISSUE THREAD

**Issue by jias7** [pyecharts/pyecharts#1855]
**问题**
  本来是想绘制双Y轴，一个Bar和一个Line图。但发现Bar图正常显示而overlap后line一直不显示，气急败坏下随便输入一些数据想看line是否还能正常显示，却发现传入的x_data和y_data完全不对应

**运行环境（系统环境及 pyecharts 版本）**
WIndows10
1.9.0

**代码及截图**
![微信截图_20210525025229](https://user-images.githubusercontent.com/75573800/119394549-e2f29680-bd04-11eb-88b3-b5f5b85fa158.png)
不对应的测试数据，没有从x=1开始绘制，最后一个数据点也被吞了
![微信截图_20210525025253](https://user-images.githubusercontent.com/75573800/119394658-0584af80-bd05-11eb-8817-68e55d43ebf7.png)
![微信截图_20210525025302](https://user-images.githubusercontent.com/75573800/119394662-06b5dc80-bd05-11eb-9db5-e638681ae524.png)
这是想要绘制的overlap图，只有折线图不显示，不知道是不是和这个问题有关（附上数据）

**Comment by sunhailin-Leo** [comment]
@jias7 
* x 轴的轴类型设置成 category 试试
