### ISSUE TITLE
使用Overlap叠加Bar和Line时必须要使用刷新数据才会显示Line的图表

### ISSUE THREAD

**Issue by jias7** [pyecharts/pyecharts#1856]
**问题**
  使用Overlap进行图表重叠时，在bar中叠加line会导致刚渲染出的图表没有折线图（图1）；而在点击数据视图中的“刷新”后折线图又被正常渲染出来了（图2）。由于绘制的图表用于参加比赛，同时还需要生成图表的图片；以及源代码也要提交。所以请问：
  1、是否有办法在第一次渲染时将折线图成功渲染？
  2、如果没办法，除了手动截屏以外，是否有办法生成含折线图的图片？

**运行环境（系统环境及 pyecharts 版本）**
WIn 10
1.9

**代码及截图**
![1](https://user-images.githubusercontent.com/75573800/119663023-945c0e00-be64-11eb-9767-8a5879ef0af1.png)
![2](https://user-images.githubusercontent.com/75573800/119663044-97ef9500-be64-11eb-8cef-853d7ff116ea.png)
![3](https://user-images.githubusercontent.com/75573800/119663056-9a51ef00-be64-11eb-83fd-633841f374fd.png)

**Comment by sunhailin-Leo** [comment]
@jias7 jupyter 以 cell 为单位运行代码的，没法做到实时更新的
