### ISSUE TITLE
有没有大佬知道折线图怎么加粗选中的折线条？

### ISSUE THREAD

**Issue by Marsh999** [pyecharts/pyecharts#1857]
**问题**
线条很多时候看不清是那条线，需要个加粗选中线条的功能，看了文档和问答都没有找到...求大佬帮忙~

**运行环境（系统环境及 pyecharts 版本）**
python 3.6
pyechart 1.71

**代码及截图**
![image](https://user-images.githubusercontent.com/36720207/120110125-d97d8a00-c15b-11eb-9ba2-bb6359411693.png)

**Comment by sunhailin-Leo** [comment]
@Marsh999 line_width

**Comment by Marsh999** [comment]
line_width只能改变某条线固定的线宽吧，我想实现的效果是鼠标移动到某条线上的时候，这条线会加粗，鼠标移开的时候，这条线会自动恢复到以前的粗细。

**Comment by Marsh999** [comment]
> @Marsh999 line_width

line_width只能改变某条线固定的线宽吧，我想实现的效果是鼠标移动到某条线上的时候，这条线会加粗，鼠标移开的时候，这条线会自动恢复到以前的粗细。

**Comment by sunhailin-Leo** [comment]
@Marsh999 这个得写 js 了，通过 js 事件动态修改参数。你即使换 Echarts 也没有配置项给你这么设置的，也需要用 js

**Comment by Marsh999** [comment]
> @Marsh999 这个得写 js 了，通过 js 事件动态修改参数。你即使换 Echarts 也没有配置项给你这么设置的，也需要用 js

我找到了实现这个功能的js语句（https://blog.csdn.net/hezhixiang/article/details/104157504），我水平有限不会写入pyecharts，请问您知道怎么把这个语句写入func pyecharts.Base.add_js_funcs里么？谢谢~
