### ISSUE TITLE
Timeline加载了图表数量不一致的Grid造成Timeline.render后一片空白

### ISSUE THREAD

**Issue by featherain80** [pyecharts/pyecharts#1860]
我有4个grid，其中1个grid有4个柱状图，其它3个grid有3个柱状图。将这4个grid加载到timeline之后，timeline只显示一片空白。
如果我确保4个grid都同时拥有4个柱状图或3个柱状图之后，timeline才能正常显示。
这是个bug吗？

**Comment by sunhailin-Leo** [comment]
@featherain80 
* 你这个描述并看不出什么问题。
