### ISSUE TITLE
pyecharts是否支持在表格上下方添加文本对表格内容进行阐述？

### ISSUE THREAD

**Issue by chenyinghong** [pyecharts/pyecharts#1861]
pyecharts是否支持在绘制表格上方或下放添加一个表格内容描述或数据文字分析的文本框，类似于一个describtion内容？（直接显示，非hover出现）
如果有，能否说明一下如何使用，如果没有是否可以考虑后续添加？

**Comment by chenyinghong** [comment]
![image](https://user-images.githubusercontent.com/39793402/120737235-45773e00-c520-11eb-8aa5-9c43ec46f78e.png)
类似效果如下

**Comment by chenyinghong** [comment]
> pyecharts是否支持在绘制表格上方或下放添加一个表格内容描述或数据文字分析的文本框，类似于一个describtion内容？（直接显示，非hover出现）
> 如果有，能否说明一下如何使用，如果没有是否可以考虑后续添加？
![image](https://user-images.githubusercontent.com/39793402/120737289-6770c080-c520-11eb-83e7-1baf289dbba0.png)
类似效果如上图

**Comment by sunhailin-Leo** [comment]
@chenyinghong 建议自行写 js 放到 html 上
