### ISSUE TITLE
官网挂了吗？访问不了

### ISSUE THREAD

**Issue by defp** [pyecharts/pyecharts#1866]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by h9052300** [comment]
好像是的~我也進不去，圖都掛了

**Comment by jamfs** [comment]
官网昨天就有问题了。不稳定。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyecharts/pyecharts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 中午1:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[pyecharts/pyecharts] 官网挂了吗？访问不了 (#1866)





 
问题
 
运行环境（系统环境及 pyecharts 版本）
 
代码及截图

**Comment by sunhailin-Leo** [comment]
访问量太大了。。处理中。。
