### ISSUE TITLE
时间轴Timeline加载20张标签不同的极坐标图后显示的标签固定不变了，都显示成了最后一张极坐标图的标签。

### ISSUE THREAD

**Issue by nkwindforce** [pyecharts/pyecharts#1871]
**问题**
时间轴Timeline加载20张标签不同的极坐标图后显示的标签固定不变了，都显示成了最后一张极坐标图的标签。
而单独生成的极坐标图的标签都是不同的，参见代码和截图。

**运行环境（系统环境及 pyecharts 版本）**
python3.7
pyecharts 1.9.0

**代码及截图**
代码
import numpy as np
import random
import pandas as pd
from pyecharts import options as opts
from pyecharts.charts import Polar
from pyecharts.faker import Faker

rules_plot=pd.read_excel("rules_plot.xlsx")
pgSize=10
rowNum = len(rules_plot)
tl = Timeline(init_opts=opts.InitOpts(theme='walden',width="600px",height="650px",chart_id=1))
polar_cur = np.nan
for i, row in rules_plot.iterrows():
-----data_dot =[(np.nan,np.nan) for j in range(pgSize)]
-----pgID = round(i/pgSize)
-----pgEnd = min((pgID+1)*pgSize,rowNum)
-----if i%pgSize==0:            
--------rule_desc=[rules_plot["antecedents_new"].iloc[j] for j in range(i,pgEnd)]
--------data_line =[(rules_plot["confidence"].iloc[j],j%pgSize) for j in range(i,pgEnd)]        
--------polar = (
---------- Polar(init_opts=opts.InitOpts(theme='walden'))
----------.add_schema(angleaxis_opts=opts.AngleAxisOpts(data=rule_desc,boundary_gap=False, start_angle=0
-------------------------------,axisline_opts=opts.AxisLineOpts(is_show=True)))
----------.add(series_name="", data=data_line, label_opts=opts.LabelOpts(is_show=False)) 
----------.set_global_opts(title_opts=opts.TitleOpts(title="规则雷达",pos_left="center"))
-------- )
--------for  j in range(i,pgEnd):
-----------data_dot[j%pgSize]=(rules_plot["confidence"].iloc[j],j%pgSize)   
-----------polar.add("", data_dot,type_="scatter",label_opts=opts.LabelOpts(is_show=False),symbol_size =round(row["support_cnt_std"]*30),)
--------tl.add(polar,"{}页".format(pgID))
--------polar.render("radar_"+str(pgID)+".html")
         
tl.render_notebook()

截图
Timeline最后一页
![image](https://user-images.githubusercontent.com/57579062/122660372-97bc8e00-d1b3-11eb-96f1-78ccfbe22fc2.png)
TimeLine第一页
![image](https://user-images.githubusercontent.com/57579062/122660384-bd499780-d1b3-11eb-897e-8b5964953b47.png)

单独保存的极坐标图
第一页
![image](https://user-images.githubusercontent.com/57579062/122660395-d94d3900-d1b3-11eb-870a-81ed6458c443.png)
第二页
![image](https://user-images.githubusercontent.com/57579062/122660410-ebc77280-d1b3-11eb-834c-f8391b850a9d.png)
最后一页
![image](https://user-images.githubusercontent.com/57579062/122660423-00a40600-d1b4-11eb-8766-005e2b256258.png)

**Comment by sunhailin-Leo** [comment]
@nkwindforce 
* Wait for the new version
