### ISSUE TITLE
请问pyechart支持自己注册地图吗

### ISSUE THREAD

**Issue by kuyewuyuan** [pyecharts/pyecharts#1873]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@kuyewuyuan 
* 需要将 pyecharts 的静态库拉下来 https://github.com/pyecharts/pyecharts-assets 做改造

**Comment by kuyewuyuan** [comment]
请问您会做相应的改造技术教程吗？我其实需要了解如何根据geojson如何生成对应的js文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyecharts/pyecharts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 下午3:52
***@***.***&gt;;
抄送:&nbsp;"白云鹏 15级 重庆交通大学研究生 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] 请问pyechart支持自己注册地图吗 (#1873)





 
@kuyewuyuan
  
需要将 pyecharts 的静态库拉下来 https://github.com/pyecharts/pyecharts-assets 做改造

**Comment by chfw** [comment]
请参照这个文档： https://echarts-maps.github.io/echarts-geomapping-book-zh/

**Comment by kuyewuyuan** [comment]
非常感谢，我尝试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月1日(星期四) 凌晨4:18
收件人: ***@***.***&gt;; 
抄送: "白云鹏 15级 重庆交通大学研究生 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pyecharts/pyecharts] 请问pyechart支持自己注册地图吗 (#1873)





 
请参照这个文档： https://echarts-maps.github.io/echarts-geomapping-book-zh/
