### ISSUE TITLE
Gauge中，图例与数据重叠

### ISSUE THREAD

**Issue by cwjcw** [pyecharts/pyecharts#1875]
**问题**
使用Gague时，图例与数字重合
[](url)

**运行环境（Windows10，python版本3.9.5 ,  pyecharts 1.9.0）**
[](url)

**代码及截图**

`from pyecharts.charts import Gauge

gauge = (
    Gauge()
    .add(
        series_name='test', 
        data_pair=[('ABC',20)],        
    )
)
gauge.render_notebook()
`
![1624507651(1)](https://user-images.githubusercontent.com/45133410/123201194-c785d180-d4e4-11eb-8743-554f938c249d.png)

**Comment by sunhailin-Leo** [comment]
@cwjcw 
* 后续会修复的；
* Related to https://github.com/pyecharts/pyecharts/issues/1805

**Comment by cjydayang** [comment]
@sunhailin-Leo 请教一下使用2.0.0版本要怎么修改pyecharts-assets支持 echarts 5？
Gague里面的文字和数字样式没了
![image](https://user-images.githubusercontent.com/24446099/141630114-318706b1-40be-470a-bf90-a5ad56adb793.png)
