### ISSUE TITLE
如何在省级地图中绘制出区县级行政单位

### ISSUE THREAD

**Issue by 369631947** [pyecharts/pyecharts#1876]
**问题**
如何在省级地图上绘制出区县级行政单位，目前省级只能默认画出市级行政单位。尝试通过多个add拼接市级地图的形式实现，但是地图都重叠在一起，且难以对齐。是否有好的解决方案？

**运行环境（系统环境及 pyecharts 版本）**
python3.8.8+pyecharts1.9.0+win10

**代码及截图**
![image](https://user-images.githubusercontent.com/7064221/123501873-8c1d0b80-d67a-11eb-9f19-352607b587b3.png)

**Comment by sunhailin-Leo** [comment]
@369631947 
* 需要自行定义县级市的地址
