### ISSUE TITLE
请问一下各位大佬这个Demo的代码在哪里

### ISSUE THREAD

**Issue by lywly** [pyecharts/pyecharts#1880]
![Geo-lines](https://user-images.githubusercontent.com/19553554/35082102-fd8d884a-fc52-11e7-9e40-5f94098d4493.gif)

万分感谢！

**Comment by SWHL** [comment]
- 你这个是`pyecharts==0.5.x`下的
- 具体代码链接：https://05x-docs.pyecharts.org/#/zh-cn/charts_base

**Comment by lywly** [comment]
非常感谢回答。 这个Demo在轨迹中使用了geo_effect_symbol="plane", 那么在最新版中还提供plane这个小图标吗，找了好久只看到了circle等4个 在2021年07月09日 08:43，SWHL 写道： 你这个是pyecharts==0.5.x下的 具体代码链接：https://05x-docs.pyecharts.org/#/zh-cn/charts_base — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SWHL** [comment]
- 根据[文档](https://pyecharts.org/#/zh-cn/series_options?id=effectopts%ef%bc%9a%e6%b6%9f%e6%bc%aa%e7%89%b9%e6%95%88%e9%85%8d%e7%bd%ae%e9%a1%b9)的说明，是没有这个图标了，但是可以自定义
>  可以通过 'image://url' 设置为图片，其中 URL 为图片的链接，或者 dataURI。

- 可以多看看文档，里面说的很清楚了

**Comment by lywly** [comment]
好的，非常感谢

**Comment by lywly** [comment]
再推荐一个网站：
[阿里巴巴矢量图标库](https://www.iconfont.cn/)
下载png格式的图标就可以实现这个功能了
