### ISSUE TITLE
pyecharts无法正常显示

### ISSUE THREAD

**Issue by pjgao** [pyecharts/pyecharts#1883]
```python
import pyecharts.options as opts
from pyecharts.charts import Line

l = Line()

l.add_xaxis([8, 9, 10, 11, 12, 14, 15, 16, 17])
l.add_yaxis('', [1, 19, 14, 9, 5, 9, 7, 13, 12])
l.set_global_opts(
    xaxis_opts=opts.AxisOpts(boundary_gap=False, type_='value'),
)
l.render_notebook()
```
显示的图像与x轴不对齐
![image](https://user-images.githubusercontent.com/22350313/125947621-310fc523-ff25-4d11-8d4f-13ff0f537672.png)

环境：
系统： WSL ubuntu 20.04
工具：jupyter notebook
python version: 3.9.1
pyecharts version: Version: 1.9.0

**Comment by sunhailin-Leo** [comment]
@pjgao 
* 你设置的 xaxis 的第一个值是 8 ，而且 X 轴的类型为 value
