### ISSUE TITLE
使用overlap叠加bar和line，bar的颜色会失效，是跟line的visualmap_opts变绿的，如何保持bar的颜色是红色的，不是跟line的visualmap_opts有所变化？

### ISSUE THREAD

**Issue by xiaopinwei** [pyecharts/pyecharts#1884]
**问题**
使用overlap叠加bar和line，bar的颜色会失效，是跟line的visualmap_opts变绿的，这不是想要的效果，如何保持bar的颜色是红色的，不要跟line的visualmap_opts有所变化？

**运行环境（系统环境及 pyecharts 版本）**
Windows10
pycharts1.9

**代码及截图**

```
# overlap将多张图表整合到一个画板上
# 绘制柱状图


from pyecharts.charts import Kline, Line, Bar, Grid
from pyecharts import options as opts

hero = ['鲁班', '妲己', '程咬金', '后裔']
death_times = [1200, 600, 90, 1000]

kline = (Bar().add_xaxis(hero).add_yaxis(
    series_name='王者荣耀胜利次数', y_axis=death_times))
kline.render_notebook()
```

![image](https://user-images.githubusercontent.com/40836918/126043582-209c3f69-ed38-4a03-8280-1449a804dcb2.png)

```
#绘制折线图
hero2 = ['鲁班','妲己','程咬金','后裔']
hurts = [2000,1200,3500,3000]
line2 = Line()
line2.add_xaxis(hero2)
line2.add_yaxis('"六神装伤害输出"',y_axis=hurts)
line2.set_global_opts(
    visualmap_opts=opts.VisualMapOpts(
        is_show=True,
        is_piecewise=True,  # 颜色分段
        pieces=[{'gt':2000,'lte': 3500, 'color': 'red'},
                        {'gt': 0, 'lte': 2000, 'color': 'green'}],)
                )
line2.render_notebook()
```

![image](https://user-images.githubusercontent.com/40836918/126043596-423b6354-7ab0-405b-aff7-2c42e83c4a87.png)

```
# 结合不同类型图表叠加画在同张图上
line2.overlap(kline)
line2.render_notebook()

```

![image](https://user-images.githubusercontent.com/40836918/126043628-33c92c63-ff9b-40c7-b53e-eb06097adebd.png)

bar和line能否按照自己的图表上色，该如何实现？

**Comment by fg0521** [comment]
在 VisualMapOpts中添加series_index参数，可以添加列表形式，列表中表明需要作用的元件的下标，例如你的line是第二个元件，则series_index=[2]即可只作用于line上，默认为作用于全部元件！（可以查看官方文档：https://pyecharts.org/#/zh-cn/global_options）
