### ISSUE TITLE
如何设置双Y轴的刻度从数据的最小值开始，而不是从0开始

### ISSUE THREAD

**Issue by wangdong2222** [pyecharts/pyecharts#1885]
**问题**
问题：pyecharts设置双Y轴，如何设置两条Y轴的最小刻度为两个列表的最小值？
现状：目前我通过参数min_='dataMin'只能设置左边的Y轴的刻度从最小值开始，但右边的Y轴通过这个参数不起作用，右边的Y轴最小值始终从0开始，另外右边Y轴的说明也没显示

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 版本1.9，
python 版本3.6
运行系统：centos (notebook)

**代码及截图**

代码如下：

def draw_double_y_local(pd_data, file_name, col_left, col_right, width_='1000px', height_='600px'):
    """ 双y轴特征图"""
    if pd_data.empty:print("pandas what you want to draw is null.")  
    start = str(pd_data.index[0])
    end   = str(pd_data.index[-1]) 
    print(start+"~~"+end)
    
    #左边Y轴
    left_chart = (
        Line(init_opts=opts.InitOpts(width=width_, height=height_))
        .add_xaxis(pd_data.index.tolist())
        .extend_axis(yaxis=opts.AxisOpts())
        .add_yaxis(col_left, pd_data[col_left].tolist(), label_opts = opts.LabelOpts(is_show=False), yaxis_index=0, color='blue')
        .set_global_opts(
            title_opts=opts.TitleOpts(
                title = file_name,  #主标题
                #subtitle = file_name,  #副标题
                ),
            legend_opts=opts.LegendOpts(pos_top="4%"),
            yaxis_opts=opts.AxisOpts(min_='dataMin',name='主风管压力',name_location='middle',name_gap=50),
            )
        )

    #右边Y轴
    right_chart = (
        Line()
        .add_xaxis(pd_data.index.tolist())
        .add_yaxis(col_right, pd_data[col_right].tolist(), label_opts = opts.LabelOpts(is_show=False), yaxis_index=1, color='blue')
        .set_global_opts(
            legend_opts=opts.LegendOpts(pos_top="4%"),
            #这里的min_='dataMin',name='空簧压力'没起作用
            yaxis_opts=opts.AxisOpts(min_='dataMin',name='空簧压力',name_location='middle',name_gap=50),
            )
        )
    
    left_chart.overlap(right_chart)
    return left_chart

截图：
上述函数运行的结果如下：
![image](https://user-images.githubusercontent.com/8604388/126425670-8ff378ef-cff3-4df9-b008-8cd142d31ef8.png)

即右边的Y轴坐标轴是从0开始的，我想让它从传入列表的最小值开始，如何做到？
跪求高人指导

**Comment by sunhailin-Leo** [comment]
@wangdong2222
