### ISSUE TITLE
wordcloud 不显示值最大的词

### ISSUE THREAD

**Issue by coderwhisky** [pyecharts/pyecharts#1887]
**问题**
最大值对应的词始终没有显示出来

**代码及截图**
代码段：
![image](https://user-images.githubusercontent.com/4336001/127999070-ff4adf34-ab4c-4c90-8aa3-00b0954ece4c.png)
展示截图：
![image](https://user-images.githubusercontent.com/4336001/127998941-0f19dc78-884c-4a6a-9e1c-2e34774d3b05.png)

**Comment by coderwhisky** [comment]
当我有好几个值一样，且等于最大值时，前边几个都显示不出来
![image](https://user-images.githubusercontent.com/4336001/128000299-3feb3087-346e-4cb7-91e9-3a1b0162da3a.png)

**Comment by sunhailin-Leo** [comment]
@coderwhisky 
* 试下把 value 改为整形
