### ISSUE TITLE
两个TreeMap放进Grid后，TreeMap重叠在一起

### ISSUE THREAD

**Issue by featherain80** [pyecharts/pyecharts#1889]
将两个TreeMap放进同一个Grid时，出现了重叠现象，即使设置了合理的pos_right和pos_left参数。

代码如下：
`dataDic = {
    'children':[{'name':'树图',
               'value':100,
               'children':[
                   {'name':'子项目1',
               'value':100,
               'children':[]},
                   {'name':'子项目2',
               'value':100,
               'children':[]}
               ]}]
}

treeMapList = []
for i in [1,2]:
    vTreeMap = TreeMap()
    vTreeMap.add(
        series_name=str(i),
        data=dataDic["children"],
        visual_min=300,
        leaf_depth=1,
        label_opts=opts.LabelOpts(position="inside",font_size = 10),
    )
    vTreeMap.set_global_opts(
        legend_opts=opts.LegendOpts(is_show=False),
        title_opts=opts.TitleOpts(
            title=str(i),
        ),
    )
    treeMapList.append(vTreeMap)
vGrid = Grid()
vGrid.add(treeMapList[0], grid_opts=opts.GridOpts(pos_right='53%'))
vGrid.add(treeMapList[1], grid_opts=opts.GridOpts(pos_left='53%'))
vGrid.render_notebook()`

**Comment by sunhailin-Leo** [comment]
@featherain80 
* 截图看一下。

**Comment by featherain80** [comment]
@sunhailin-Leo 
这个截图就是通过上面的代码生成的图。生成后我点进去，然后我进行几次缩放拖动后，它就会像图里这样两个图层错开，就能看到这其实有两个treemap重叠在了一起。
![image](https://user-images.githubusercontent.com/84707327/128653259-c369d130-2d52-470e-9e09-3e87660b6b5a.png)

**Comment by sunhailin-Leo** [comment]
@featherain80 这个有可能是 Echarts 不兼容

**Comment by featherain80** [comment]
@sunhailin-Leo 那是需要从你们开发那一侧去修复，还是在我们用户侧有什么办法能解决这个问题？

**Comment by sunhailin-Leo** [comment]
@featherain80 
* 我们相对于 Echarts 也只是用户，我们也无能为力目前
* 你可以使用 Page，放多个 TreeMap 进行展示
