### ISSUE TITLE
table中如何进行反转义？

### ISSUE THREAD

**Issue by tank2737** [pyecharts/pyecharts#1895]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@tank2737 不太清楚你的问题是什么意思？

**Comment by sqljohn** [comment]
应该是问 table为什么不支持 dump_options_with_quotes()？
参照Flask 前后端分离的例子， 最后都要用dump_options_with_quotes()返回Json给前端. 但table不支持，要如何处理？

    return c.dump_options_with_quotes()
AttributeError: 'Table' object has no attribute 'dump_options_with_quotes'
