### ISSUE TITLE
问题反馈：堆叠柱状图颜色显示错误

### ISSUE THREAD

**Issue by wuhaiwqy** [pyecharts/pyecharts#1896]
**运行环境（系统环境及 pyecharts 版本）**
Python：3.9
pyecharts：1.9.0

**问题**
目的：已知今日数量和变化量，希望将今日数量用柱状图表示出来，并显示与昨日相比变化的部分。附件test.csv中，vol列表示今日数量，chg表示与昨日相比变化的部分。
目前想到的处理方式：对于今日减少的，用今日数量与减少数量堆叠，对于今日增加的，用昨日数量与增加数量堆叠（但这样鼠标悬停时，显示的数量是昨日数量，还是希望显示今日数量，目前不知道怎么做）。
发现设置堆叠柱状图时，各部分颜色显示不对，有错位现象。

**代码及截图**
代码：
`import pandas as pd
from pyecharts.charts import Bar

data = pd.read_csv("test.csv")
data["base_vol"] = data["chg"].map(lambda x: -x if x > 0 else 0) + data["vol"]

bar = (
    Bar()
    .add_xaxis(xaxis_data=data["item"].tolist())
    .add_yaxis(
        series_name="Position Vol",
        y_axis=data["base_vol"].tolist(),
        color="LightSeaGreen",
        stack="vol"
    )
    .add_yaxis(
        series_name="Increased",
        y_axis=data["chg"].map(lambda x: x if x > 0 else 0).tolist(),
        color="red",
        stack="vol"
    )
    .add_yaxis(
        series_name="Dcreased",
        y_axis=data["chg"].map(lambda x: -x if x < 0 else 0).tolist(),
        color="green",
        stack="vol"
    )
)
bar.render()
`
结果如附件，各部分颜色不正确。
望一并提供该场景的解决方案，即怎样在今日数量的基础上显示与昨日的变化量，且对于今日增加的，提示的数字是今日的数量。
[test.csv](https://github.com/pyecharts/pyecharts/files/7111775/test.csv)
![render](https://user-images.githubusercontent.com/23043232/132130652-6d5f6d8f-03fc-4a54-b9e0-d7e9158a26fd.png)

**Comment by sunhailin-Leo** [comment]
@wuhaiwqy 
* 等这个 PR 结束后再次尝试一下。https://github.com/pyecharts/pyecharts/pull/1978

**Comment by pythonfa** [comment]
草泥马发自我的荣耀手机-------- 原始邮件 --------发件人： wuhaiwqy ***@***.***>日期： 2021年9月5日周日 22:33收件人： pyecharts/pyecharts ***@***.***>抄送： Subscribed ***@***.***>主    题： [pyecharts/pyecharts] 问题反馈：堆叠柱状图颜色显示错误 (#1896)
运行环境（系统环境及 pyecharts 版本）
Python：3.9
pyecharts：1.9.0
问题
目的：已知今日数量和变化量，希望将今日数量用柱状图表示出来，并显示与昨日相比变化的部分。附件test.csv中，vol列表示今日数量，chg表示与昨日相比变化的部分。
目前没想到的处理方式：对于今日减少的，用今日数量与减少数量堆叠，对于今日增加的，用昨日数量与增加数量堆叠（但这样鼠标悬停时，显示的数量是昨日数量，还是希望显示今日数量，目前不知道怎么做）。
发现设置堆叠柱状图时，各部分颜色显示不对，有错位现象。
代码及截图
代码：
`import pandas as pd
from pyecharts.charts import Bar
data = pd.read_csv("test.csv")
data["base_vol"] = data["chg"].map(lambda x: -x if x > 0 else 0) + data["vol"]
bar = (
Bar()
.add_xaxis(xaxis_data=data["item"].tolist())
.add_yaxis(
series_name="Position Vol",
y_axis=data["base_vol"].tolist(),
color="LightSeaGreen",
stack="vol"
)
.add_yaxis(
series_name="Increased",
y_axis=data["chg"].map(lambda x: x if x > 0 else 0).tolist(),
color="red",
stack="vol"
)
.add_yaxis(
series_name="Dcreased",
y_axis=data["chg"].map(lambda x: -x if x < 0 else 0).tolist(),
color="green",
stack="vol"
)
)
bar.render()
`
结果如附件，各部分颜色不正确。
望一并提供该场景的解决方案，即怎样在今日数量的基础上显示与昨日的变化量，且对于今日增加的，提示的数字是今日的数量。
test.csv
