### ISSUE TITLE
求教：为什么charts.Line.add_yaxis()中的lineStyle_opts参数可以使用“ShadowOffsetX”属性？

### ISSUE THREAD

**Issue by smthvitas** [pyecharts/pyecharts#1897]
**问题**

如下代码可以正常运行，且能够产生阴影效果。
但我看了下Options.LineStyleOpts及其父类的定义，并没有找到对
"ShadowBlur"、"ShadowColor”、"ShadowOffsetX"、"ShadowOffsetY"的支持。
文档里边似乎也没有写。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.9

**代码及截图**
line = (charts.Line(init_opts=options.InitOpts(theme=globals.ThemeType.MACARONS))
    .add_xaxis(df4.index.to_list())
    .add_yaxis('基金', 
        df4['基金'].round(1),
        markpoint_opts=options.MarkPointOpts(
            data=[
                options.MarkPointItem(type_="max", name="最大值",symbol='pin'),
                options.MarkPointItem(type_="min", name="最小值",symbol_size=50),
            ]
        ),
        markline_opts=options.MarkLineOpts(
            data=[options.MarkLineItem(type_="average", name="平均值")]
        ),
        label_opts = options.LabelOpts(is_show=False),
        # splitLine_opts = options.SplitLineOpts(is_show=True),
        symbol_size = 4,
        # is_step = True,
        **linestyle_opts = {
            'shadowBlur':2,
            'shadowColor':'rgba(0,0,0,0.1)',
            'shadowOffsetX': 3,
            'shadowOffsetY': 4,**
            'width': 2,
            # 'curve': 10
            'opacity': 0.8
        }
    )

)

**Comment by sunhailin-Leo** [comment]
@smthvitas 
* 我们的配置是支持用类定义或者字典定义的。因此你这么传参数没毛病。

**Comment by sunhailin-Leo** [comment]
@smthvitas 
* 你可以认为文档没写，不过源码里面针对对象都是各种 get 和 update 的方法。这在 Python 很明显就是一个 dict 的数据类型
