### ISSUE TITLE
服务器环境浏览器50版使用本地js、css 渲染的html使用90高版本的浏览器浏览显示空白

### ISSUE THREAD

**Issue by shchliu** [pyecharts/pyecharts#1898]
**问题**
目前使用pyecharts1.9版本，使用服务器环境浏览器50版使用本地js、css
渲染的html使用90高版本的浏览器浏览显示空白，请问如何解决？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts1.9、谷歌浏览器低版本50.0.2661，高版本90.0
echarts.min.js和bootstrap.min.css均为从官网下载的最新版本。

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@shchliu 有 90 版本浏览器控制台报错的截图嘛？

**Comment by shchliu** [comment]
90版本控制台报错截图
![90版本报错截图](https://user-images.githubusercontent.com/54017976/133089710-fca65677-3774-4873-bc9f-03ab9dbe216f.png)

**Comment by sunhailin-Leo** [comment]
@shchliu 
* Network 那栏的报错有吗？
* 或者你换个版本的浏览器会有问题吗？我这边本地用 92 的没出现过这种问题

**Comment by shchliu** [comment]
Network栏没有报错信息
我是在内网用50版本的浏览器使用下载到本地的js生成的html，50版本的可以正常浏览，也没有报错信息。内网暂时只有谷歌50和90两个版本的浏览器，其他版本的浏览器安装不上。
<img width="605" alt="network页面" src="https://user-images.githubusercontent.com/54017976/133180966-93071646-102f-4ff6-a670-ff88ee2d047c.png">

**Comment by sunhailin-Leo** [comment]
@sunhailin-Leo 
* 点一下 All，不要选择 Others

**Comment by shchliu** [comment]
Network all页面没有报错
<img width="603" alt="NetWork-all页面" src="https://user-images.githubusercontent.com/54017976/133182037-2277430f-eed5-4915-921a-0a35a4ad12bb.png">

**Comment by sunhailin-Leo** [comment]
@shchliu 
* 那你只能确认一下你的 js 和 css 能不能被 90 这个浏览器访问到了。
* 我这边使用不同的电脑都没有这个问题。
