### ISSUE TITLE
组合图表Grid嵌套的问题

### ISSUE THREAD

**Issue by ZYQ-FEIYUE** [pyecharts/pyecharts#1900]
![image](https://user-images.githubusercontent.com/44333258/133952740-8a3abe05-950a-4d6b-af09-9b0e4eb07a41.png)
我想Grid嵌套使用，但是嵌套后无法使用，没有图像出来

**Comment by sunhailin-Leo** [comment]
@ZYQ-FEIYUE 
* 为什么想要尝试嵌套...

**Comment by ZYQ-FEIYUE** [comment]
因为一个数据源生成的图片有4张，有多种同样类型的数据源，这样嵌套方便一点

**Comment by sunhailin-Leo** [comment]
@ZYQ-FEIYUE 
* Echarts 不支持这种方式
