### ISSUE TITLE
TreeMap：矩形树图当中的矩形节点，颜色的深浅只能通过 value、id和 index 来改变吗？

### ISSUE THREAD

**Issue by HyperSimon** [pyecharts/pyecharts#1902]
**问题**

矩形树图当中的矩形节点，颜色的深浅只能通过 value、id和 index 来改变吗？

**运行环境（系统环境及 pyecharts 版本）**

比如在股票数据可视化当中，value 通常为改股票的市值，而颜色的深浅并不是根据这个 value 来的，请问这种情况该如何处理？

![氢电公敌 2021-09-09 19 39 18](https://user-images.githubusercontent.com/9377192/134673789-3a8404b0-a787-4573-a524-d86d9712c0c8.jpeg)

上面为实例图

**Comment by Serendipithub** [comment]
你这是issue吗? 在issue发干什么?

**Comment by sunhailin-Leo** [comment]
@HyperSimon 
* 修改控制颜色深浅回调函数。
