### ISSUE TITLE
如何隐藏DataZoom滑动块两边的文字？

### ISSUE THREAD

**Issue by fishgit03** [pyecharts/pyecharts#1917]
**问题**
通过什么设置，可以隐藏DataZoom滑动块两边的文字？

**运行环境（系统环境及 pyecharts 版本）**
win10，pyecharts-1.8.1

**代码及截图**
![image](https://user-images.githubusercontent.com/56946425/138660108-6e0bfcf0-5b02-4f13-9b89-77133a3d3cb3.png)

**Comment by sunhailin-Leo** [comment]
@fishgit03 
* showDetail: false 可以隐藏，不过目前 pyecharts 的 datazoom 没有加入这个参数，因此无法隐藏。

**Comment by sunhailin-Leo** [comment]
@fishgit03 
* branch dev is fix this issue. https://github.com/pyecharts/pyecharts/pull/1934

**Comment by fishgit03** [comment]
@sunhailin-Leo 收到了，谢谢
