### ISSUE TITLE
jupyter notebook/lab 保存ipynb文件时，保存不了图像，这是不是正常现象啊

### ISSUE THREAD

**Issue by freemedom** [pyecharts/pyecharts#1919]
**问题**
jupyter notebook/lab 保存ipynb文件时，保存不了图像

**运行环境（系统环境及 pyecharts 版本）**
win
pyecharts最新版

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@freemedom 
* 因为 pyecharts 渲染出来的是 HTML 代码而已，不是图像，因此 jupyter 保存不了也是正常的，建议导出图片或者保存 html 文件
