### ISSUE TITLE
使用overlap后，叠加的图的标签填充失效

### ISSUE THREAD

**Issue by lixiaoshuang79** [pyecharts/pyecharts#1921]
**问题**
使用overlap后，叠加的图的标签填充失效

**运行环境（系统环境及 pyecharts 版本）**
1.9.1

**代码及截图**
代码是gallery复制过来的，链接是：https://gallery.pyecharts.org/#/Grid/grid_multi_yaxis
想要的效果就是只显示数值＋℃，比如25℃
![image](https://user-images.githubusercontent.com/63501244/139782694-7c981d3b-897e-482e-8b63-05c67389948a.png)
因为在 trigger 为 'axis' 的时候，会有多个系列的数据，所以：
![image](https://user-images.githubusercontent.com/63501244/139782912-3e8d1c27-373f-42e5-b3a3-e99d09d29d92.png)

**Comment by sunhailin-Leo** [comment]
@lixiaoshuang79 
* `label_opts=opts.LabelOpts(is_show=True, formatter=JsCode("function(x) { return x.data[1] + '°C';}")),`
