### ISSUE TITLE
关于yaxis_opts修改成对数坐标之后柱状堆叠图的问题

### ISSUE THREAD

**Issue by zhengtf0963** [pyecharts/pyecharts#1922]
pyecharts 1.9.0 python 3.9.0 

代码如下：
`
import random
from pyecharts.render import make_snapshot
from snapshot_selenium import snapshot

import pyecharts.options as opts
from pyecharts.charts import Bar

y_value2 = [2.8925, 3.1744, 3.3368]
y_value3 = [23055.625, 23052.817, 20946.159]
y4 = [233.856, 239.126, 234.941]
y5 = [12.171, 11.15, 12.911]
y6 = [7.8926, 8.1984, 7.6752]
y7 = [479.1, 479.3, 480]
y8 = [11.764, 12.652, 11.879]
y9 = [22228.1, 22241.2, 20129.8]
y10 = [24.968, 23.774, 27.996]

# y11 = [233.856, 239.126, 234.941]
# y12 = [12.171/y4[0], 11.15/y4[1], 12.911/y4[2]]
# y13 = [7.8926/(y4[0]+y5[0]), 8.1984/(y4[1]+y5[1]), 7.6752/(y4[2]+y5[2])]
# y14 = [479.1/(y4[0]+y5[0]+y6[0]), 479.3/(y4[1]+y5[1]+y6[1]), 478.8/(y4[2]+y5[2]+y6[2])]
# y15 = [11.764/(y4[0]+y5[0]+y6[0]), 12.652/(y4[0]+y5[0]+y6[0]), 11.879/(y4[0]+y5[0]+y6[0])]
# y16 = [22228.1, 22241.2, 20129.8]
# y17 = [24.968, 23.774, 27.996]

goods = ['AES_ECB_128', 'AES_CBC_128', 'AES_CTR_128']
# goods = ['Q1_Select', 'Q2_Select', 'Q3_Select']

bar = (
    Bar()
    .add_xaxis(goods)
    .add_yaxis("Plain", y_value2, gap='10%', category_gap="50%", bar_width=20, color="gray", bar_min_height=5) # y轴设置
    .add_yaxis("Total", y_value3, gap='10%', category_gap="50%", bar_width=20, color="#ffcc66") # y轴设置
    .add_yaxis('Prepare_tee_session', y4, stack='stack1', gap='10%', category_gap="50%", bar_width=20, color="black", is_large=1)
    .add_yaxis('WS(S-N)', y5, stack='stack1', gap='10%', category_gap="50%", color="#749f83", bar_min_height=0.25)
    .add_yaxis('Basic Query(BQ)', y6, stack='stack1', gap='10%', category_gap="50%", color="#d48265", bar_min_height=0.25)
    .add_yaxis('Integrity Verification(IV)', y7, stack='stack1', gap='10%', category_gap="50%", color="#61a0a8")
    .add_yaxis('WS(N-S)', y8, stack='stack1', gap='10%', category_gap="50%", color="#2f4554", bar_min_height=0.25)
    .add_yaxis('Data Decryption(DD)', y9, stack='stack1', gap='10%', category_gap="50%", color="black")
    .add_yaxis('Terminate_tee_session', y10, stack='stack1', gap='10%', category_gap="50%", color="#c23531")
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False),
                     font='Calibri',
                     # markline_opts=opts.MarkLineOpts(
                     #     data=[opts.MarkLineItem(name='1', y=23055),
                     #           opts.MarkLineItem(type_="min", name="最小值"),
                     #           opts.MarkLineItem(type_="max", name="最大值")
                     #         # opts.MarkLineItem(type_='average', name='平均值'),
                     #     ]
                     # )
)
    .set_global_opts(
                    # 标题设置
                    title_opts=opts.TitleOpts(title='GPS Select excution times', pos_left='25', title_textstyle_opts=opts.TextStyleOpts(font_family='Calibri', font_size=16)),
                     # xaxis_opts=opts.AxisOpts(name='品类'),
                     # 修改坐标轴
                     yaxis_opts=opts.AxisOpts(type_='log', split_number=8, boundary_gap=['50%','80%'], name='Excution time（ms）',  splitline_opts=opts.SplitLineOpts(is_show=True), axislabel_opts=opts.LabelOpts(font_family='Calibri')),
                     xaxis_opts=opts.AxisOpts(name='SQL', split_number=10, name_gap=5, axislabel_opts=opts.LabelOpts(font_family='Calibri')),
                     # 修改图例
                     legend_opts=opts.LegendOpts(type_="plain", is_show=True, orient="horizontal", legend_icon="circle", pos_left="150", pos_top='20', item_width=8, item_height=8, align="auto", textstyle_opts=opts.TextStyleOpts(font_size=12, font_family='Calibri')),
                     # 坐标轴线设置
                     # axis_opts=opts.AxisLineOpts(is_show=True)
                     #修改字体
                     # graphic_opts=opts.GraphicTextStyleOpts(font='""'),
                     # 工具栏设置
                     # toolbox_opts=opts.ToolboxOpts(is_show=True)
         )

    # .set_global_opts()

)

# make_snapshot(snapshot, bar.render(), "bar0.png")
# make_snapshot(snapshot, bar.render(), "bar.png")
bar.render('select_test_柱状堆叠图select.html')
`
截图如下：
![1636031061(1)](https://user-images.githubusercontent.com/55044986/140318363-dfd8622b-b2d8-40bb-825b-010ee62c1a21.jpg)

出现堆叠图和对数坐标没对齐的原因，其他都好着，有知道这是什么原因吗？

**Comment by sunhailin-Leo** [comment]
@zhengtf0963 
* 1、如果不使用对数坐标呢？
* 2、把图画成 Line 图试试？
