### ISSUE TITLE
ModuleNotFoundError: No module named 'pyecharts.events'

### ISSUE THREAD

**Issue by bawinogr** [pyecharts/pyecharts#1923]
A seemingly identical issue was raised a while back.  When I run the example code:   
#!/usr/bin/env python
# coding=utf-8
from __future__ import unicode_literals

import pyecharts.echarts.events as events
from pyecharts import Bar
from pyecharts_javascripthon.dom import alert

def on_click():
    alert("点击事件触发")

def test_mouse_click():
    bar = Bar("我的第一个图表", "这里是副标题")
    bar.add(
        "服装", ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"], [5, 20, 36, 10, 75, 90]
    )
    bar.on(events.MOUSE_CLICK, on_click)
    bar.render()

I have run several version of pyecharts 0.5.x and above, and nothing solves the problem.

**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@bawinogr 
* 0.5.x was no longer maintained, so you can update to 1.x version.

**Comment by bawinogr** [comment]
This doesn't work either.  I tried most of the more recent versions as well
as 1.9, and they also can't find pyecharts.events.
