### ISSUE TITLE
折线图使用reversal_axis后x轴消失

### ISSUE THREAD

**Issue by lixiaoshuang79** [pyecharts/pyecharts#1924]
**问题**

折线图使用reversal_axis后x轴消失

**运行环境（系统环境及 pyecharts 版本）**

Macos12.01
pyecharts1.9.0

**代码及截图**

<img width="1095" alt="F4B79651-538F-4722-BE87-8785E22F9A96" src="https://user-images.githubusercontent.com/63501244/140589151-172bb34f-41e1-4554-928f-8892ee00ff18.png">

**Comment by sunhailin-Leo** [comment]
@lixiaoshuang79 
* 没太理解 Line 图要 reversal 的意义

**Comment by lixiaoshuang79** [comment]
![B8451554-B084-47C0-B4ED-C73431051D9A](https://user-images.githubusercontent.com/63501244/140679475-d753c142-1b02-4cdb-95b2-1c8050c28b11.jpeg)
 想实现这种效果~

**Comment by sunhailin-Leo** [comment]
@lixiaoshuang79 
![image](https://user-images.githubusercontent.com/17564655/140680582-aee70374-8f62-4048-9f4c-0571e238c06d.png)
![image](https://user-images.githubusercontent.com/17564655/140680606-d04fe4bd-edd9-46fb-90a3-0a7d781584ca.png)
