### ISSUE TITLE
直方图的color 用JScode进行动态控制，但似乎用dump_options_with_quotes返回后，JSCode对象被变成了字符串，

### ISSUE THREAD

**Issue by algoqt** [pyecharts/pyecharts#1925]
**问题**

股票的volume直方图的color 用JScode进行动态控制，但似乎用dump_options_with_quotes返回后，JSCode对象被变成了字符串，导致无法执行对于的js代码

**代码及截图**

![Uploading image.png…]()

**Comment by sunhailin-Leo** [comment]
@algoqt 
* https://pyecharts.org/#/zh-cn/faq
