### ISSUE TITLE
python 3.10 不兼容

### ISSUE THREAD

**Issue by swuecho** [pyecharts/pyecharts#1927]
**问题**

venv/lib/python3.10/site-packages/pyecharts/__init__.py:1: in <module>
4s
43	    from pyecharts import charts, commons, components, datasets, options, render, scaffold
4s
44	.venv/lib/python3.10/site-packages/pyecharts/charts/__init__.py:2: in <module>
4s
45	    from ..charts.basic_charts.bar import Bar
4s
46	.venv/lib/python3.10/site-packages/pyecharts/charts/basic_charts/bar.py:3: in <module>
4s
47	    from ...charts.chart import RectChart
4s
48	.venv/lib/python3.10/site-packages/pyecharts/charts/chart.py:3: in <module>
4s
49	    from ..charts.base import Base
4s
50	.venv/lib/python3.10/site-packages/pyecharts/charts/base.py:13: in <module>
4s
51	    from ..render import engine
4s
52	.venv/lib/python3.10/site-packages/pyecharts/render/engine.py:2: in <module>
4s
53	    from collections import Iterable
4s
54	E   ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

**Comment by swuecho** [comment]
https://github.com/Kozea/pygal/pull/484/files

**Comment by XksA-me** [comment]
将 site-packages/pyecharts/render/engine.py中第二行代码 from collections import Iterable 改为 from collections.abc import Iterable 即可。

**Comment by swuecho** [comment]
是的

https://github.com/pyecharts/pyecharts/pull/1928/files

**Comment by swuecho** [comment]
能否发布个新版本？1.9.1 ？

**Comment by chenjiandongx** [comment]
@sunhailin-Leo 可以考虑发个小版本

**Comment by sunhailin-Leo** [comment]
@swuecho @sunhailin-Leo 
* 晚些时候我发一个 1.9.2 的版本兼容一下 Python 3.10

**Comment by sunhailin-Leo** [comment]
@swuecho 
* Fix it and try it.
* https://github.com/pyecharts/pyecharts/releases/tag/v1.9.1

**Comment by swuecho** [comment]
多谢！已经可以正常使用了。
