### ISSUE TITLE
pyecharts1.0.0中的Table表格如何加上滚动条

### ISSUE THREAD

**Issue by stevenlvkai** [pyecharts/pyecharts#1935]
**问题**
如何给Table加上滚动条,因为我的行数较多,我想让它能够滚动，只展示部分行。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts1.0.0版

**代码及截图**

**Comment by stevenlvkai** [comment]
输入以下代码后
`from pyecharts.components import Table
from pyecharts.options import ComponentTitleOpts


table = Table()

headers = ["City name", "Area", "Population", "Annual Rainfall"]
rows = [
    ["Brisbane", 5905, 1857594, 1146.4],
    ["Adelaide", 1295, 1158259, 600.5],
    ["Darwin", 112, 120900, 1714.7],
    ["Hobart", 1357, 205556, 619.5],
    ["Sydney", 2058, 4336374, 1214.8],
    ["Melbourne", 1566, 3806092, 646.9],
    ["Perth", 5386, 1554769, 869.4],
]
table.add(headers, rows)
table.set_global_opts(
    title_opts=ComponentTitleOpts(title="Table-基本示例", subtitle="我是副标题支持换行哦")
)
table.render("table_base.html")`

再查看生成的HTML代码会出现一段
`<body>

        <style>
            .fl-table {
                margin: 20px;
                border-radius: 5px;
                font-size: 12px;
                border: none;
                border-collapse: collapse;
                max-width: 100%;
                white-space: nowrap;
                word-break: keep-all;

            }

            .fl-table th {
                text-align: left;
                font-size: 20px;
            }

            .fl-table tr {
                display: table-row;
                vertical-align: inherit;
                border-color: inherit;
            }

            .fl-table tr:hover td {
                background: #00d1b2;
                color: #F8F8F8;
            }

            .fl-table td, .fl-table th {
                border-style: none;
                border-top: 1px solid #dbdbdb;
                border-left: 1px solid #dbdbdb;
                border-bottom: 3px solid #dbdbdb;
                border-right: 1px solid #dbdbdb;
                padding: .5em .55em;
                font-size: 15px;
            }

            .fl-table td {
                border-style: none;
                font-size: 15px;
                vertical-align: center;
                border-bottom: 1px solid #dbdbdb;
                border-left: 1px solid #dbdbdb;
                border-right: 1px solid #dbdbdb;
                height: 30px;
            }

            .fl-table tr:nth-child(even) {
                background: #F8F8F8;
            }
        </style>`

我发现只要在
`            .fl-table {
                margin: 20px;
                border-radius: 5px;
                font-size: 12px;
                border: none;
                border-collapse: collapse;
                max-width: 100%;
                white-space: nowrap;
                word-break: keep-all;
            }`
里面再添加几个参数
`
display:block;
height:100px;
width:200px;
overflow:scroll;`
就可以出现滚动条了。
所以能不能在表格控件的add函数里面再加几个参数用来控制滚动条呢？

**Comment by sunhailin-Leo** [comment]
@stevenlvkai 
* 这个 add 函数并没必要增加参数去控制滚动条，如果需要实现的话可以自行修改源码的 macro 模版
