### ISSUE TITLE
请问对于叠加图，如何对每张图设置不同的提示框？

### ISSUE THREAD

**Issue by Kryto614** [pyecharts/pyecharts#1938]
https://gallery.pyecharts.org/#/Candlestick/professional_kline_chart
这是官方的K线图案例，我希望K线数据放在一个提示框，跟着鼠标移动，均线数据固定显示在左上角，请问可以实现吗？

**Comment by sunhailin-Leo** [comment]
@Kryto614 
* 尝试给 tooltip 加一个 position 的配置哈。
![image](https://user-images.githubusercontent.com/17564655/143169376-fc151719-739e-4290-9841-3ca31348735b.png)

**Comment by Kryto614** [comment]
> 

我加了position，不过所有数据还是堆在一个框的，有没有办法把K线数据和均线数据分成2个框呢？

**Comment by sunhailin-Leo** [comment]
@Kryto614 
* 拆分的目前没看到 Echarts 有实现。可能最简单的方式就是分离两个图。各自展示

**Comment by Kryto614** [comment]
@sunhailin-Leo 
谢谢回复~那就先堆一个框吧
