### ISSUE TITLE
Boxplot中preparedata不能处理一维数组

### ISSUE THREAD

**Issue by csho** [pyecharts/pyecharts#1939]
**问题**
Boxplot中preparedata不能处理一维数组

**运行环境（系统环境及 pyecharts 版本）**
ubuntu

**代码及截图**
array_non0_std = df7_nonzero_hostcount_std.toPandas()['non0_hosts_std'].values #一维向量，内含大量float数据
x_axis = ['标准差']
bar1 = Boxplot()
bar1.add_xaxis(x_axis)
bar1.add_yaxis('x轴',bar1.prepare_data(array_non0_std))
bar1.set_global_opts(title_opts=opts.TitleOpts(title="箱型图"))
bar1.render_notebook()
print(bar1.prepare_data(array_non0_std))

结果为空图。单独运行bar1.prepare_data返回 [ ] (空数组)

**Comment by csho** [comment]
解决方法是将待分析的数组用reshape转成二维数组，
`np.array(array_non0_std).reshape(1,len(array_non0_std))`

**Comment by sunhailin-Leo** [comment]
@csho 
![image](https://user-images.githubusercontent.com/17564655/143169169-c9e61b26-6cb7-4ad0-a716-729343155c04.png)
