### ISSUE TITLE
如何显示地图的比例尺和南北

### ISSUE THREAD

**Issue by wangrongwei** [pyecharts/pyecharts#1940]
**问题**

使用Map显示china数据时，需要显示地图的比例尺以及南北，这个在一般论文作图中都是需要的，但是似乎Map没有提供这种功能？

**运行环境（系统环境及 pyecharts 版本）**

Mac

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@wangrongwei 
* 这个目前也没有办法。Echarts 没有相对应的配置，我们也无能为力。😔

**Comment by sunhailin-Leo** [comment]
@wangrongwei 
* 建议你可以去 Echarts 仓库那边提个 issue 哈～
