### ISSUE TITLE
请考虑添加在Page中使用Tab的功能。How to add Tab into Page ?

### ISSUE THREAD

**Issue by ganxy1028** [pyecharts/pyecharts#1941]
当前 Page 和 Tab 不能联用还是有很多影响啊，在大页面里有tab这个应该是很常见的用法吧
目前连用会报错
'pyecharts.charts.composite_charts.tab.Tab object' has no attribute 'width'
如果直接改代码在 Tab 类里加上 self.width = '400px' 之类的是不出图的。
希望官方可以支持这个用法

**Comment by sunhailin-Leo** [comment]
@ganxy1028 
* 1、目前为止没有任何一个理由有说服力让我们去做 Page + Tab 的功能。
* 2、直接改代码不出图的问题是什么？

**Comment by ganxy1028** [comment]
@sunhailin-Leo 

1. Page + Tab 的用途很多呀。无非就是降低单个图表的信息量而已。整个Page是完整的报告，而 Tab 通常是最基础的数据化的主图。Tab 可能有好几个分类，而主图之后的图是大量的分析图标。比如做投资分析，分为绝对收益和相对收益；做增长分析，分同比和环比，等等之类的。这些分析内部本来就有多个分项目的折线图、条形图之类的，已经使得图内的信息量很大了；同时多种分类之间又不可比；并且整页的内容规划也不适合直接把多种分类的表一一列出来。所以就一个 Tab 来分类画图了。主图之后是各种单项具体分析，这种的信息密度就没这么大，就可以直接一个图表靠颜色来分类了。用 Tab 和很多时候用 TimeLine 是一个理由而已，只不过分类的不是靠时间。
2. 直接改代码不出图就是说我已经自己尝试了改 Tab 和 Page 的代码来让它们融合，但是解决不了，所以来求助官方。

**Comment by sunhailin-Leo** [comment]
@ganxy1028 
* 目前 Page + Tab 不实现的原因：不希望这种前端模块成为 pyecharts 未来的需求，只要这个“口子”开了，若干的前端模块需求就会产生，对于这个项目的维护是一种恶性循环。

**Comment by qianhangkang** [comment]
what  a pity 。 如果能支持就好了，同样遇到相同问题，暂时只能变成两个页面了

**Comment by wuxiaoyizz** [comment]
遇见同类问题，如果能在page中使用tab就好了

**Comment by linlhw** [comment]
遇见同类问题，如果能在page中使用tab就好了

**Comment by jegb** [comment]
One use case: 
I managed to get Page to play with a chart and a table underneath. (after long struggle with grid component not allowing it).
Finally, wanted to plug that page under a tab and encountered the 'width' error.
Any chance to support either (allow grid under tabs that support tables as one item on the grid) or allow the page to be plugged to one tab.

Thanks for the great work btw!
