### ISSUE TITLE
import pyecharts 报错ImportError: cannot import name '_dukpy'

### ISSUE THREAD

**Issue by rufushuachen** [pyecharts/pyecharts#1942]
**问题**

import pyecharts 报错ImportError: cannot import name '_dukpy'

**运行环境（系统环境及 pyecharts 版本）**
pyecharts                   0.5.10
pyecharts-javascripthon     0.0.6
pyecharts-jupyter-installer 0.0.3
pyecharts-snapshot          0.2.0
python           3.6.1

**代码及截图**
#coding=utf-8
from __future__ import unicode_literals
from pyecharts import Bar

bar = Bar("我的第一个图表", "这里是副标题")
bar.add("服装", ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"], [5, 20, 36, 10, 75, 90])

bar.render()    # 生成本地 HTML 文件

##################################
报错
  File "C:\Users\rufus\.conda\envs\rufus\lib\site-packages\dukpy\evaljs.py", line 7, in <module>
    from . import _dukpy
ImportError: cannot import name '_dukpy'

**Comment by rufushuachen** [comment]
请问这种导入包报错，可能是什么原因？谢谢！

**Comment by sunhailin-Leo** [comment]
@rufushuachen 
* 报错与 pyecharts 无关。
* 报错提示很明显：
```text
File "C:\Users\rufus.conda\envs\rufus\lib\site-packages\dukpy\evaljs.py", line 7, in
from . import _dukpy
ImportError: cannot import name '_dukpy'
```
