### ISSUE TITLE
将XY轴翻转后，x轴标签从字符变成了数字，请问如何解决？

### ISSUE THREAD

**Issue by rufushuachen** [pyecharts/pyecharts#1943]
**问题**
将XY轴翻转后，y轴标签（1到12月）从字符变成了数字，请问如何解决？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts                   0.5.11
Python       3.6.2

**代码及截图**
from pyecharts import Bar 

attr = ['衬衫','羊毛衫','雪纺纱','裤子','高跟鞋','袜子']
v1 = [5,20,36,10,75,90]
v2 = [10,25,8,60,20,80]
bar = Bar('X轴和Y轴交换')
bar.add('商家',attr,v1)
bar.add('商家B',attr,v2,is_convert=True)
bar

<img width="624" alt="XY翻转" src="https://user-images.githubusercontent.com/55791016/143809062-5d36371a-954c-409f-8d51-671c7f985719.PNG">

**Comment by sunhailin-Leo** [comment]
@rufushuachen 
![image](https://user-images.githubusercontent.com/17564655/144781382-6cde0e27-2954-4a54-a4a8-06423707b0b1.png)
![image](https://user-images.githubusercontent.com/17564655/144781399-61128734-0ada-4e40-9ea9-8a6ccfcb2056.png)
