### ISSUE TITLE
请问print_echarts_options()是最新版本是没了吗，最新版本有没有相应的函数呢？

### ISSUE THREAD

**Issue by freemedom** [pyecharts/pyecharts#1944]

**Comment by freemedom** [comment]
搜了搜源码，的确是没了，试了一下，可以用
import pprint
pprint.pprint(bar.options)

**Comment by freemedom** [comment]
照着以前的print_echarts_options()的源码，json序列化，似乎不行，不知道为什么

**Comment by sunhailin-Leo** [comment]
@freemedom 
* 你的版本应该是 0.5.x 的，建议你先看一下 1.x 的文档先。
* 两个版本互相不兼容的。
