### ISSUE TITLE
使用Grid组合多个河流图（ThemeRiver）时报错

### ISSUE THREAD

**Issue by shiniantianlang** [pyecharts/pyecharts#1945]
**问题**
使用Grid组合多个河流图（ThemeRiver）时报错

**运行环境（系统环境及 pyecharts 版本）**
系统环境：windows 10
pyecharts: 1.1.0

**代码及截图**
![image](https://user-images.githubusercontent.com/11689550/144352253-2c1fb989-ae97-4669-b1bb-db9ccdf7b7f1.png)

![image](https://user-images.githubusercontent.com/11689550/144352278-46086ea8-44ff-46ec-9780-e2abf1dfd423.png)

**Comment by sunhailin-Leo** [comment]
@shiniantianlang 
* 尝试过 1.9.X 版本的会出现同样的问题吗？

**Comment by sunhailin-Leo** [comment]
@shiniantianlang 
* ThemeRiver 与 Grid 结合不会像你那样子报错。
* 但是没有满足预期的样子，因为 Echarts 目前没有给 ThemeRiver 做 Grid 分块展示的
