### ISSUE TITLE
使用 TimeLine 之后组图的 toolbox 就不可用了

### ISSUE THREAD

**Issue by ganxy1028** [pyecharts/pyecharts#1946]
如题，使用 TimeLine 之后组图的 toolbox 就不可用了，图中没有 toolbox 组件了

**Comment by sunhailin-Leo** [comment]
@ganxy1028 
* 目前是没有支持。。当时考虑这个组件在 timeline 出现的意义不大所以没有加进去。

**Comment by sunhailin-Leo** [comment]
@ganxy1028 
* Wait for the new version
