### ISSUE TITLE
Tree 能否terminal node对齐？

### ISSUE THREAD

**Issue by williamjin1992** [pyecharts/pyecharts#1947]
**问题**
用Tree生成的树状图，在最终节点（叶片节点）能够可以对齐，例如在从左到右的布局中，让所有最终节点右对齐。
虽然可以更改json文件的结构达到这样的目的，但更改json文件较为繁琐，能够通过选项设置？

**代码及截图**
例如图中，BFH为最终的叶片节点，布局为从左到右，能够实现让BFH节点右对齐？
![image](https://user-images.githubusercontent.com/29701725/144439046-2be40be1-eb29-4130-ac87-a50ab1677159.png)

**Comment by sunhailin-Leo** [comment]
@williamjin1992 
* 你需要的布局目前来看 echarts 也没有配置可以修改。目前没有办法能够实现哈
