### ISSUE TITLE
dump_options_with_quotes()的运行时间较长是否有方法可以加速？

### ISSUE THREAD

**Issue by alpha-deng** [pyecharts/pyecharts#1948]
**问题**
c.dump_options_with_quotes()的运行时间较长是否有方法可以加速？

**运行环境（系统环境及 pyecharts 版本）**
windows 10

**代码及截图**
import numpy as np
from pyecharts.charts import Line
from pyecharts import options as opts
import json
from time import *
import unittest

def bar_base(Data, test_num,time_list, channel_id):
    c = (
        Line()
        .add_xaxis(list(map(lambda x, y: str(int(y)) + '.'+str(x), test_num,time_list)))
        .add_yaxis("通道"+str(channel_id), Data.tolist(), #is_smooth=True,np.around(Data,3).tolist()

                   markline_opts=opts.MarkLineOpts(
                       data=[opts.MarkLineItem(type_="max"), opts.MarkLineItem(type_="min")])
                   )
        .set_global_opts(title_opts=opts.TitleOpts(title="可视化网络数据"),
                         tooltip_opts=opts.TooltipOpts(is_show=True, trigger='axis'),
                         toolbox_opts=opts.ToolboxOpts(is_show=True, item_gap=15),
                         xaxis_opts=opts.AxisOpts(
            axistick_opts=opts.AxisTickOpts(is_align_with_label=True),
            is_scale=False,
            boundary_gap=False,
        )
        ).set_series_opts(
            label_opts=opts.LabelOpts(is_show=False),
        )
    )
    return c

Fs = 16000
point = np.arange(Fs)
test_num = (point).tolist()
channel_id = 0
time_list = np.ones(Fs) 
Data = np.arange(Fs)

t0 = time()

class TestMathFunc(unittest.TestCase):

    def setUp(self):
        print("do something before test.Prepare environment.")

    def tearDown(self):
        print("do something after test.Clean up.")

    def test_one(self):
        """Test bar_base"""
        print('bar_base')   
        time_0 = time()
        c = bar_base(Data, test_num,time_list, channel_id)
        d = c.dump_options_with_quotes()
        print('test time:',time()-time_0)
        print('bar_base-finish')

   

if __name__ == '__main__':
    unittest.main(verbosity=2)

**Comment by sunhailin-Leo** [comment]
@alpha-deng 
* `dump_options_with_quotes` 这个函数本质上是将 `dict` 对象转换为 `json`，目前 `pyecharts` 使用的 `json` 转换库是 `simplejson`，如果觉得慢的目前解决的方式就是给 json 打 monkey patch。
