### ISSUE TITLE
能否添加一个 add_coordinate_dict() 函数

### ISSUE THREAD

**Issue by DataShare-duo** [pyecharts/pyecharts#1949]
数据处理时都是用pandas，可以直接生成固定的dict，能否直接添加个从字典导入这些自定义坐标，就不用再写个json文件，然后再读取呢

**Comment by sunhailin-Leo** [comment]
@duo66 
* 没太理解这个使用场景，可以详细描述下吗？

**Comment by duo66** [comment]
@sunhailin-Leo 

1. 背景
最近在做百度地图热力图可视化时，需要批量添加poi名称对应的经度、维度信息，数据是用pandas载入，poi名称、经度、维度不同的列，用pandas可以直接构造出一个自定义地点dict `{'poi名称':[经度,维度],.......}`，这样可以批量导入自定义地点

2. 需求
查找了相关文档，pyecharts只提供了从json文件批量导入的方法，这样的话有点太麻烦，需要先把构造的自定义地点dict 写入一个json文件，然后再载入，有点绕
