### ISSUE TITLE
Bar3D做图Y轴的间隔问题

### ISSUE THREAD

**Issue by shenjingmao** [pyecharts/pyecharts#1953]
**问题**
我的数据源是一个dataframe41列的数字变化，第一列是日期，后面是不同种类的按日期变化的数值。原来的数据类似：
```
Date        A    B    C    D.....
2021-11-1   35  45  22   11
2021-11-2   49  32  25   18
```
....

现在转换成：[['2021-11-1', 0, 35], ['2021-11-2', 0, 49]....]这样子。

我已经按照bar3D对数据的要求进行了转换成list。在使用Bar3D做图后，因为Y轴（其实我觉得pyechart应该把底部平面立体延伸的叫做Z轴）的数量比较多，有40个，所以Y轴的标签字体都挤到一起了，看不清楚。请问如何实现这样的要求？

1、更改Y轴字体的大小？
2、更改Y轴各个数据之间的间距？

我是个python的初学者，我已经花了很长时间阅读pyechart的文档，但说实话pyechart的文档对初学者很不友好，我根本看不懂。比如我知道需要通过设置全局参数来更改一些东西，但是文档中并没有一个简单的例子告诉我怎么写，我已经看了Bar3D的3个例程，但搞不明白全局配置项里面的每一项应该按什么格式加到什么位置？我又看了一些其它的例程，都有没有一个比较全的全局配置项写法的。所以只好在这里求助。

**运行环境（系统环境及 pyecharts 版本）**
Windows 7 /64位
Python 3.7.9
Pandas 1.2.6
Pyechart 1.9.1

**代码及截图**

```
import pandas as pd
from pyecharts import options as opts
from pyecharts.charts import Bar3D

data = pd.read_csv("i:df.csv")
Cataname = data.columns.values.tolist()[1:40]
Final_List = []
i = 0

for name in Cataname:
    Cata_List = pd.concat([data['Date'], pd.Series([i]*len(data)), data[name]], axis=1).values.tolist()
    i += 1
    Final_List += Cata_List

(
    Bar3D(init_opts=opts.InitOpts(width="1280px", height="1024px"))
    .add(
        series_name="",
        data=Final_List,
        yaxis3d_opts=opts.Axis3DOpts(type_="category", data=Cataname, interval=1),
    )
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(
            max_=30000000,
            range_color=[
                "#313695",
                "#4575b4",
                "#74add1",
                "#abd9e9",
                "#e0f3f8",
                "#ffffbf",
                "#fee090",
                "#fdae61",
                "#f46d43",
                "#d73027",
                "#a50026",
            ],
        )
    )
    .render("catalog.html")
)

```

**Comment by sunhailin-Leo** [comment]
@shenjingmao 
* 示例地址：https://gallery.pyecharts.org/#/Bar3D/bar3d_base
* 文档中对应的地址：https://pyecharts.org/#/zh-cn/demo_data
* 对于初学者来说每一个可视化项目都是有门槛的，我觉得你应该先沉住气来看细节。

**Comment by shenjingmao** [comment]
无语，我已经说过我看了很久文档了，但是看不懂所以才发问。作为开发者回答我的问题的时间可能比你回这个帖子还容易，结果是这种态度。

删了，以后和这个库说byebye.

**Comment by sunhailin-Leo** [comment]
@shenjingmao 
* 首先，示例也给你了，文档地址也给你了，但凡谦虚的人也会去再次发问，而不是像你这样的人心态浮躁。
* 其次，如果你仅仅是想要我们帮你写一份完整代码的话，我们告诉你是不可能的，我们这里拒绝伸手党。
* Ps：像你这样浮躁的心态，任何的库你都不可能看懂的。

**Comment by swuecho** [comment]
个人感觉pyecharts 是用的库中最友好的。

**Comment by swuecho** [comment]
提醒一下提问者，开发者没有义务回答你的问题，任何回答都是对你的馈赠（favor），把心态放正就好了。
