### ISSUE TITLE
绘图后不显示

### ISSUE THREAD

**Issue by yangllty** [pyecharts/pyecharts#1955]
**问题**
有个需求想画个动态图，不用jupyter，写了个脚本，传了两个list，x为一列int类型数据，y为一列float类型数据，画一个线形图，结果没图

**python 3.7**
**pyecharts 1.9.1**

**代码及截图**
```
    line=Line()
    line.add_xaxis(steps[1500:])
    line.add_yaxis('loss',losses[1500:])
    line.render(out_path)
```

![Snipaste_2021-12-09_16-24-35](https://user-images.githubusercontent.com/95836638/145360533-59a81f3f-3187-470d-a6fd-288940308255.png)

**Comment by waterthon** [comment]
我也是这
![0H`EFTTI`W@QLKBPD`871EG](https://user-images.githubusercontent.com/64770566/145671560-677d0a85-9688-4110-9a7f-ba57cdda1696.png)
样

**Comment by huanghh90** [comment]
可能需要设置x 轴为category ?
set_global_opts(xaxis_opts=opts.AxisOpts(type_="category"))

**Comment by sunhailin-Leo** [comment]
@yangllty @waterthon 
* 需要转换为 Python 的原生类型。如果是 pandas 的 Series 的话是无法出图的。

**Comment by actprophet** [comment]
请问这个问题怎么解决的？
