### ISSUE TITLE
将Geo添加到Grid以后，Geo的颜色将会以经度来绘制

### ISSUE THREAD

**Issue by xRay2016** [pyecharts/pyecharts#1956]
**问题**
单独绘制Geo的结果正常，但是如果将Geo添加到Grid以后，Geo点颜色将会以点的经度为准显示。经过Debug后发现是grid最后的VisualMap只有一个，不同的chart需要可视化的维度可能不一致，比如Geo需要可视化的dimension=2，但Bar需要可视化的dimension=0

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.9.1
python  3.6.11

**代码及截图**
截图如下，所有的点都是橙色的，因为颜色值都是以经度为基准显示的
![微信图片_20211209200711](https://user-images.githubusercontent.com/32756719/145393654-4f5eaa07-1fd7-4825-af8e-ce030352117b.png)

```
grid_chart = (
      Grid()
      .add(
          bar,grid_opts=opts.GridOpts(
              pos_left="10", pos_right="35%", pos_top="70%", pos_bottom="5"
          ),
      )
      .add(geo, grid_opts=opts.GridOpts())
  )
```

**Comment by sunhailin-Leo** [comment]
@xRay2016 
* 参考下：https://gallery.pyecharts.org/#/Map/china_gdp_from_1980
