### ISSUE TITLE
Kline与Bar坐标轴对不齐

### ISSUE THREAD

**Issue by casparwl** [pyecharts/pyecharts#1958]
**问题**
Kline绘制K线叠加成交量，坐标轴对不齐。以pyecharts的示例为例，在坐标上，Kline与Bar的中轴线错位了，感觉像是Kline和Bar的宽度不一致导致的。请问这是个问题还是有什么设置方法。谢谢

**运行环境（系统环境及 pyecharts 版本）**
以pyecharts的示例为例，链接如下：
https://gallery.pyecharts.org/#/Candlestick/professional_kline_brush

**代码及截图**
![image](https://user-images.githubusercontent.com/32586634/145669411-cb210201-7b5a-4017-8de4-604a820b8abb.png)

**Comment by sunhailin-Leo** [comment]
@casparwl 
* bar 图配置有柱状宽度的配置
