### ISSUE TITLE
line中如何设置数值格式为小数点后n位？

### ISSUE THREAD

**Issue by charlietsao** [pyecharts/pyecharts#1961]
**问题**
使用pandas计算得到的数值，小数点后位数过多，如何限制为n位呢？

**运行环境（系统环境及 pyecharts 版本）**
windows10
pyecharts==1.9.0

**代码及截图**

![image](https://user-images.githubusercontent.com/59471937/146939784-e10c7194-db28-4799-8ceb-9aa694b98638.png)

**Comment by sunhailin-Leo** [comment]
@charlietsao 
* Python 内置了 `round` 函数。。
