### ISSUE TITLE
render生成图片，会产生临时的tmp*.html文件。文件名字的命名是或在多进程下安全

### ISSUE THREAD

**Issue by fangyuandoit** [pyecharts/pyecharts#1962]
**问题**
pyechars+phantomjs 生成图片会在tmp目录下生成一个临时的html文件。这个文件名的命名方式是否在多进程下是否安全的？？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts==0.5.11

**代码及截图**
调用render方法后：
会产生一个临时的tmp文件的路径
/python3.6/site-packages/pyecharts_snapshot/environment.py 的33行代码 tmp_file_handle, tmp_file_path = mkstemp(suffix=".html") 
调用了python3.6的tempfile的方法

/usr/lib/python3.6/tempfile.py 的399行代码
file = _os.path.join(dir, pre + name + suf)

name来自于 /usr/lib/python3.6/tempfile.py  的299行 代码
  letters = [choose(c) for dummy in range(8)]

文档显示  Multiple  threads can safely use the same instance at the same time.是线程安全的。
                   但是在多进程下是否可能发生名字相同的情况？？

**Comment by sunhailin-Leo** [comment]
@fangyuandoit 
* 1、那您的测试结果如何呢？
* Ps: 这个问题与 `tempfile.mkstemp` 的内部实现有关。
    * `dir` 参数会根据随机模版生成目录（大可不必担心多进程下会相同，毕竟那个概率低的有点可怕）
    * `prefix` 的就是默认值: `tmp`
