### ISSUE TITLE
Tab能否进行前后端分离

### ISSUE THREAD

**Issue by AllanWu36** [pyecharts/pyecharts#1963]
**问题**
在django中使用tab前后端分离时，发现tab没有dump_options_with_quotes方法

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

def bar_datazoom_slider() -> Bar:
    c = (
        Bar()
        .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋"])
        .add_yaxis("商家A", [randrange(-100, 100) for _ in range(5)])
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Bar-DataZoom（slider-水平）"),
            datazoom_opts=[opts.DataZoomOpts()],
        )
    )
    return c

def tab_base():
    tab =Tab()
    tab.add(bar_datazoom_slider(), "bar_test")
    tab.dump_options_with_quotes()
    return tab

def tab(request):
    return JsonResponse(json.loads(tab_base()))

**Comment by sunhailin-Leo** [comment]
@AllanWu36 
* emm...既然都前后端分离了，为啥不前端做 `Tab`，后端返回 `Tab` 内的 `json` 呢？

**Comment by AllanWu36** [comment]
> @AllanWu36
> 
> * emm...既然都前后端分离了，为啥不前端做 `Tab`，后端返回 `Tab` 内的 `json` 呢？

尝试了一下，用的前端bootstrap的模板tab，然后发现只能渲染出active的那一个tab页，其他的都不显示，我基本不懂前端，不知道会是哪里的问题？

代码:
```html
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                         ......
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content tabcontent-border p-15" id="myTabContent">
                        <div role="tabpanel" class="tab-pane fade show active" id="home5" aria-labelledby="home-tab">
							<div id="custom—chart1" style="height: 300px;"></div>
						</div>
                        <div class="tab-pane fade" id="profile5" role="tabpanel" aria-labelledby="profile-tab">
							<div id="custom—chart2" style="height: 300px;"></div>
						</div>
                        <div class="tab-pane fade" id="dropdown1" role="tabpanel" aria-labelledby="dropdown1-tab">
							<div id="custom—chart3" style="height: 300px;"></div>
						</div>
                        <div class="tab-pane fade" id="dropdown2" role="tabpanel" aria-labelledby="dropdown2-tab">
							<div id="custom—chart4" style="height: 300px;"></div>
                        </div>
```

在上面4个chart里，只有class="tab-pane fade show active"内的chart正确显示了，其余几个都没有显示，确认是发起了4次请求，也正常获取了数据，但就是只渲染成功一张图

**Comment by AllanWu36** [comment]
今天找了一下网上的方案，发现可以解决了
https://www.codeleading.com/article/68742139708/
