### ISSUE TITLE
生成图片时因无法加载js报错

### ISSUE THREAD

**Issue by cnkaile** [pyecharts/pyecharts#1964]
图画好之后，使用snapshot_phantomjs生成图片， phantomjs安装完毕。 执行时报错：ReferenceError: Can't find variable: echarts\n\n  file:////root/discount_img_task/render.html:12 in global code\nReferenceError: Can't find variable: echarts\n\n  undefined:1\nnull\n
    这个是phantomjs可能没有下载或者加载 https://assets.pyecharts.org/assets/echarts.min.js，这个现在有解决方案吗？

**Comment by februaryfang** [comment]
请问这个问题您解决了吗？
