### ISSUE TITLE
pdf和svg格式

### ISSUE THREAD

**Issue by wubaosheng** [pyecharts/pyecharts#1965]
**问题**

pyecharts是一个很好的包，我很喜欢这里的的图形可视化，我觉得唯一的缺点就是html格式转化为pdf或者svg格式，很麻烦，而且各种报错（悲哀），如果能把这个问题解决了那就太好了。google浏览器的版本就很麻烦，Google浏览器的版本更新的太快，pyecharts就不兼容。

**运行环境（系统环境及 pyecharts 版本）**

win10 python3.8.10

**代码及截图**
![image](https://user-images.githubusercontent.com/50618480/147469006-10bdd3fc-b9ed-434a-a5d0-a466595b9b28.png)

**Comment by sunhailin-Leo** [comment]
@wubaosheng 
* 你说的这个问题也没啥版本。毕竟 Echarts 本身也没有转换的方式。目前的转换只是通过 js 懒加载的方式形成快照。
