### ISSUE TITLE
文档里 django前后端分离 用了rest_framework

### ISSUE THREAD

**Issue by tanshujiang** [pyecharts/pyecharts#1968]
**问题**
django前后端分离适配文档里用了rest_framework，这个应该是另一个自己写的app？

**运行环境（系统环境及 pyecharts 版本）**
python3.7 pyecharts1.9.1

**代码及截图**
![image](https://user-images.githubusercontent.com/22319177/148175188-f46d9cd7-3e6d-4bec-b8dd-091325ea4246.png)

**Comment by kinegratii** [comment]
rest_framework 是第三方库，官方文档参见 https://www.django-rest-framework.org/

安装命令 pip install djangorestframework
