### ISSUE TITLE
不等宽间隔

### ISSUE THREAD

**Issue by xxx975** [pyecharts/pyecharts#1969]
**问题**
y轴是否可以设置不等宽间隔

**运行环境（系统环境及 pyecharts 版本）**
1.9.1

**代码及截图**
yaxis_opts=opts.AxisOpts(type_="value",
                                 min_=min(y_seq) * 0.9,  # 左轴最小值
                                 max_=y_left_max,  # 左轴最大值
                                 # interval=1000,  # 间隔
                                 splitline_opts=opts.SplitLineOpts(is_show=True))
                                 )

**Comment by sunhailin-Leo** [comment]
@xxx975 
* 目前 Echarts 没有办法设置
