### ISSUE TITLE
多项数据选择及展示问题

### ISSUE THREAD

**Issue by z8772083** [pyecharts/pyecharts#1970]
**问题**
如何只显示选择的数据；
目前是点击某个选项，就会自动隐藏，如何设置只显示所选的图标数据呢？
如下图：点击product2 ，就只显示product2的图表

**运行环境（系统环境及 pyecharts 版本）**
pyecharts：1.9.0

**代码及截图**
![image](https://user-images.githubusercontent.com/18564603/148736684-419e6b93-4b39-4c15-b128-34762aeed036.png)

**Comment by sunhailin-Leo** [comment]
@z8772083 
* LegendOpts 有 selected 参数
```python
selected: {
    // 选中'系列1'
    '系列1': true,
    // 不选中'系列2'
    '系列2': false
}
```
