### ISSUE TITLE
对数轴，刻度间距问题

### ISSUE THREAD

**Issue by weijfquant** [pyecharts/pyecharts#1974]
**问题**
AxisOpts如果是对数轴，刻度间距默认是10倍，不能调整，在echarts中有logBase参数，在pyecharts中没有logBase参数，在pyecharts中如何实现调整logBase的效果。

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@weijfquant 
* Wait for the new version
