### ISSUE TITLE
图例列表项数据太多 显示异常

### ISSUE THREAD

**Issue by z8772083** [pyecharts/pyecharts#1975]
**问题**
图例列表项太多，和标题重叠了。
按照文档配置，也不生效。

legend_opts=opts.LegendOpts(type_='scroll')

**运行环境（系统环境及 pyecharts 版本）**
python3.6
pycharts 1.9.0
centos 7

**代码及截图**
![image](https://user-images.githubusercontent.com/18564603/149893731-5075140b-8d94-4235-afd5-45fa0122e1c1.png)

**Comment by sunhailin-Leo** [comment]
@z8772083 
* 滚动要垂直布局
