### ISSUE TITLE
treemap 数据未负时如何处理

### ISSUE THREAD

**Issue by casdu-zhk** [pyecharts/pyecharts#1976]
**问题**
treemap 数据有正负时，该如何通过正负去设置不同颜色

**运行环境（系统环境及 pyecharts 版本）**
python3.8

**代码及截图**
![image](https://user-images.githubusercontent.com/6999400/151098775-f0514bc0-a985-4d60-8c3f-f5490f868cb3.png)
想实现如上图所示效果

**Comment by sunhailin-Leo** [comment]
@casdu-zhk 
* 用 TreeItem ，然后给 ItemStyle 插入 JsCode 写自定义 js 去控制颜色
