### ISSUE TITLE
能否在柱状图中自定义图例所绑定的柱子

### ISSUE THREAD

**Issue by xiaosagemisery** [pyecharts/pyecharts#1979]
软件版本：1.9.0
系统版本：Ubuntu 18.04

现在只能根据Series名称自动生成图例，能否手动选择一个图例可以绑定多个series呢？比如某些series属于同一个类别的，即可通过图例切换只查看某些类别的多个柱子。
未搜索到相关问题，麻烦解答，谢谢

**Comment by sunhailin-Leo** [comment]
@xiaosagemisery 
* BarItem
