### ISSUE TITLE
树型图-节点文字太长重叠

### ISSUE THREAD

**Issue by Anita1683147070** [pyecharts/pyecharts#1981]
**问题**
树型图的节点如果是一句话或者小段文字，就会和别的节点的字重叠，该怎么解决？

谢谢解答

**运行环境（系统环境及 pyecharts 版本）**
pyecharts==1.9.1
win10

**代码及截图**
![重叠1](https://user-images.githubusercontent.com/39512152/153384738-e82e356d-54cf-4b10-bec2-42dae04d96b1.png)
![重叠2](https://user-images.githubusercontent.com/39512152/153384760-39346220-b602-4d09-8588-07158213b517.png)

**Comment by sunhailin-Leo** [comment]
@Anita1683147070 
* 修改 label 的样式，不过这个问题 Echarts 官方更多会建议你去减少描述
