### ISSUE TITLE
图对象占画布的比例能否调整或设置？

### ISSUE THREAD

**Issue by mikewang68** [pyecharts/pyecharts#1982]
**问题**
生成股票分时走势图，规定了画布的大小是600×300px，但是生成的图例没有占满画布，四周空隙比较大，能否调整设置？

**运行环境（系统环境及 pyecharts 版本）**
manjaro + python3.10 ，chorme ， pyechart最新版本

**代码及截图**

![1644581617(1)](https://user-images.githubusercontent.com/45821213/153589760-e7c4a780-521e-4583-917c-16239797ee65.png)

**Comment by sunhailin-Leo** [comment]
@mikewang68 
* 用 Grid 的去修改上下左右的边距

**Comment by mikewang68** [comment]
谢谢，已经解决，万分感谢！
