### ISSUE TITLE
保存图片分辨率

### ISSUE THREAD

**Issue by Xiecenyao** [pyecharts/pyecharts#1987]
设置了`"pixel_ratio": 3` 仍十分模糊

**Comment by sunhailin-Leo** [comment]
@Xiecenyao 什么格式的？

**Comment by Xiecenyao** [comment]
> 



> @Xiecenyao 什么格式的？
png，其他几种格式也都有试过

**Comment by sunhailin-Leo** [comment]
@Xiecenyao 
* 具体模糊到什么程度？
* 设置下画图的像素试试
