### ISSUE TITLE
日历图 不支持 scatter 类型

### ISSUE THREAD

**Issue by 4516756** [pyecharts/pyecharts#1990]
**问题**

日历图 不支持 scatter 类型  ，只支持热图

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@4516756 
* 目前还不支持，后面会考虑迭代加进去

**Comment by sunhailin-Leo** [comment]
@4516756 
* Wait for the new version

**Comment by Achuan-2** [comment]
想问问怎么用scatter类型的日历呀
