### ISSUE TITLE
能把Brush的开闭属性添加上吗 Can we add the property 'is_show' for ToolBoxFeatureBrushOpts?

### ISSUE THREAD

**Issue by 2000mdc** [pyecharts/pyecharts#1992]
**问题**
找不到不显示工具箱选框组件的属性设置。
这个能与其他的工具箱特性的选择开关属性设置保持一致吗？
Can't find the  property 'is_show' for ToolBoxFeatureBrushOpts.
All of the ToolBoxFeatures get the property 'is_show' except the ToolBoxFeatureBrushOpts.
Is it better to keep it consistent with other features?

**运行环境（系统环境及 pyecharts 版本）**
system: window 7 sp1
python: 3.8.12
jupyter notebook: 6.4.8
pyecharts: 1.9.1

**代码及截图**
from pyecharts.charts import Bar
from pyecharts import options as opts
from pyecharts.globals import ThemeType

bar = Bar(init_opts=opts.InitOpts(theme=ThemeType.VINTAGE))
bar.set_global_opts(
    title_opts=(
        opts.TitleOpts(
            title='Key Smartphone players sales in Feb.2022',
            subtitle='Key e-commerce distribution channles sales'
        )
    ),
    toolbox_opts=(
        opts.ToolboxOpts(
            is_show=True,
            feature=opts.ToolBoxFeatureOpts(
                data_zoom=opts.ToolBoxFeatureDataZoomOpts(is_show=False),
                brush=opts.ToolBoxFeatureBrushOpts(is_show=False)
            )
        )
    ),
    legend_opts=(
        opts.LegendOpts(pos_top='95%')
    )
)
bar.add_xaxis(['APPLE', 'HUAWEI', 'HONOR', 'MI', 'RED MI', 'VIVO', 'IQOO', 'OPPO', '1+', 'REALME', 'MEIZU'])
bar.add_yaxis('ChannelA',[3654, 2351, 1241, 3142, 1051, 2341, 231, 3214, 598, 668, 324])
bar.add_yaxis('ChannelB',[2957, 1874, 852, 2571, 2234, 2239, 553, 2564, 982, 258, 125])
bar.add_yaxis('ChannelC',[3241, 1963, 532, 1893, 1657, 2135, 895, 2742, 235, 367, 267])
bar.render_notebook()

**Comment by sunhailin-Leo** [comment]
@2000mdc 
* Echarts 没有提供。
* https://echarts.apache.org/zh/option.html#toolbox.feature.brush

**Comment by 2000mdc** [comment]
> @2000mdc
> 
> * Echarts 没有提供。
> * https://echarts.apache.org/zh/option.html#toolbox.feature.brush

好的。谢谢您的答复。
