### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'title_pos'

### ISSUE THREAD

**Issue by Siddarth2709** [pyecharts/pyecharts#1993]
from pyecharts.charts import Pie

genres = ['Pop','Rock','Indiepop','Modern rock','Garage rock','permanent wave','sheffield indie','electropop','alt z']
data = [40, 25,21 ,18 ,15 ,15,15,10,9,8,8,1]

pie = Pie("The Most Used Genres", title_pos='center')
pie.add(" ",genres,data,radius=[40, 75], label_text_color=None, is_label_show=True,
            legend_orient='vertical', legend_pos='left')

pie.render()

**Comment by Siddarth2709** [comment]
After Recent Update to Pyecharts ,I am Getting this error in line (4) regarding tilte_pos ="center", 
Can anybody please help me.

**Comment by sunhailin-Leo** [comment]
@Siddarth2709 
```python
pie = Pie()
pie.add(" ",genres,data,radius=[40, 75], label_text_color=None, is_label_show=True,
legend_orient='vertical', legend_pos='left')
pie.set_global_opts(title_opts=opts.TitleOpts(title="The Most Used Genres", pos_left='center'))
```
