### ISSUE TITLE
Bar 在使用add_set后，无法在timeline里面显示

### ISSUE THREAD

**Issue by royyoung388** [pyecharts/pyecharts#1994]
**问题**
单独使用Bar，然后用add_dataset记载数据，能正常使用
但是如果加上Timeline会变成一片空白

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.8.1
python 3.9.7
windows 11

**代码及截图**
![image](https://user-images.githubusercontent.com/22541557/160031621-bbeb48e7-84ac-4692-9408-c880155ef22f.png)
![image](https://user-images.githubusercontent.com/22541557/160031668-a3e95ce3-8405-4359-b7e6-1e579aa8ff65.png)

**Comment by sunhailin-Leo** [comment]
@royyoung388 
* dataset 模式暂时还没支持 timeline 的组合。

**Comment by sunhailin-Leo** [comment]
@royyoung388 
* Wait for the new version
