### ISSUE TITLE
如何修改parallel画图中每个y坐标轴的名称字体的大小，以及刻度字体的大小

### ISSUE THREAD

**Issue by Winter-Z-T** [pyecharts/pyecharts#1995]
**问题**
按照我的代码，发现修改之后没有变化，只有图例发生了相应的改变

**运行环境（系统环境及 pyecharts 版本）**
python3.9
pyecharts1.9.1

**代码及截图**
Parallel()
        # .set_series_opts()
        .add_schema(
        [
            opts.ParallelAxisOpts(dim=0, name='OAT2', min_=0, max_=1),
            opts.ParallelAxisOpts(dim=1, name='RCT', min_=0, max_=1),
            opts.ParallelAxisOpts(dim=2, name='SCT', min_=0, max_=1),
            opts.ParallelAxisOpts(dim=3, name='HT', min_=0, max_=1),
            opts.ParallelAxisOpts(dim=4, name='ST', min_=0, max_=1),
            opts.ParallelAxisOpts(dim=5, name='OAT1', min_=0, max_=1)
        ]
                    )
        .add("Q=0.81", data1, linestyle_opts=opts.LineStyleOpts(width=3, opacity=1, color="#e71f19"))
        .add("Q=0.39", data2, linestyle_opts=opts.LineStyleOpts(width=3, opacity=1, color="#16499d"))
        .set_global_opts(
                          legend_opts=opts.LegendOpts(is_show=True,
                                                      textstyle_opts=opts.TextStyleOpts(font_size=20)
                                                      ),
                         yaxis_opts=opts.AxisOpts(
                                                   is_show=True,
                                                   is_scale=True,
                                                   name_textstyle_opts=opts.TextStyleOpts(font_size=20),
                                                    axislabel_opts=opts.LabelOpts(font_size=20)
                                                  ),
                         xaxis_opts=opts.AxisOpts(
                                                    is_show=True,
                                                    # name_textstyle_opts=opts.TextStyleOpts(font_size=20)
                                                  )
                         )
        .set_series_opts(
                        axisline_opts=opts.AxisLineOpts(linestyle_opts=opts.LineStyleOpts())

                        )

**Comment by sunhailin-Leo** [comment]
@Winter-Z-T 
![image](https://user-images.githubusercontent.com/17564655/160752621-022e2a5e-6a6c-44c3-afe0-a7b3da23e8ee.png)

**Comment by Winter-Z-T** [comment]
> @Winter-Z-T ![image](https://user-images.githubusercontent.com/17564655/160752621-022e2a5e-6a6c-44c3-afe0-a7b3da23e8ee.png)

是我的pyecharts版本和您的不一样吗，这里我并没有后面axisline, axistick, axislabel这三个
<img width="583" alt="image" src="https://user-images.githubusercontent.com/59812208/160759582-e933485b-127d-426b-8200-7bb9a9d3b4af.png">

**Comment by sunhailin-Leo** [comment]
@Winter-Z-T 
* 升级下 🐶

**Comment by Winter-Z-T** [comment]
@sunhailin-Leo 不好意思，您的意思是升级pyecharts版本吗？我看最新的就是1.9.1版本，可我还是不存在这三个

**Comment by sunhailin-Leo** [comment]
@Winter-Z-T 
* 那应该是在 dev 分支上了。目前的话还没发布，等后续更新之后试试。

**Comment by Winter-Z-T** [comment]
@sunhailin-Leo 好的，感谢您的回复！
