### ISSUE TITLE
旭日图中数据无法按原始数据顺序进行排序

### ISSUE THREAD

**Issue by buruquzibi** [pyecharts/pyecharts#1998]
**问题**
旭日图中数据无法按原始数据顺序进行排序，sort_="null"后，旭日图中的顺序，仍是按照降序进行排列，发现pyecharts-gallery中的Sunburst - Drink_flavors中也存在同样的问题，即使设置了sort_="null"后，旭日图中的数据仍是按照降序进行排列，不是按照输入的数据中的数据顺序进行排列。
谢谢开发人员的辛苦努力！

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@buruquzibi 
* 试一下 sort_ = JsCode("null")

**Comment by buruquzibi** [comment]
已解决，感谢！
