### ISSUE TITLE
旭日图中添加图例后无显示

### ISSUE THREAD

**Issue by buruquzibi** [pyecharts/pyecharts#2002]
**问题**
旭日图中添加图例后无显示

**运行环境（系统环境及 pyecharts 版本）**
win 11
python 3.9
pyecharts 1.9.1

**代码及截图**
![image](https://user-images.githubusercontent.com/49910441/161073621-0c05a20c-5484-4d19-87af-395a2caaf6cd.png)

然后发现生成的图中无图例显示，发现生成的html文件中，legend里的data无数据
![image](https://user-images.githubusercontent.com/49910441/161072946-8d851ef4-20ce-4691-aa4f-6793f0fc53b5.png)

谢谢开发者！

**Comment by sunhailin-Leo** [comment]
@buruquzibi 
* 为什么想要 sunburst 的 legend 中的 data 有数据？sunburst 的数据都存在于 series 中。不太理解你问的问题

**Comment by buruquzibi** [comment]
是我理解错了，就是发现sunburst里想做出图例但是做不出来，谢谢！
