### ISSUE TITLE
add Gauge into Grid

### ISSUE THREAD

**Issue by fergie21** [pyecharts/pyecharts#2003]
Hello,
I am trying to add two Gauges into a Grid, but without success (they appear one over other)
Is this possible?

Regards!

**Comment by sunhailin-Leo** [comment]
@fergie21 
* Out repo miss a configuration ==> `center`.(It can change the gauge center point position on the painting)

**Comment by sunhailin-Leo** [comment]
* When add it. Like below... 
![image](https://user-images.githubusercontent.com/17564655/161910183-3d5d3575-d70d-4e74-9cf6-dcf7dbfcba34.png)

**Comment by sunhailin-Leo** [comment]
* Expected the new version.(Coming soon...)
