### ISSUE TITLE
现在支持保存成可以编辑的pdf格式了吗？

### ISSUE THREAD

**Issue by wjdiadijai** [pyecharts/pyecharts#2005]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by wjdiadijai** [comment]
感觉还是有一些内容是需要后期去调整的，但是目前暂时没有找到可以讲html格式的内容转换成pdf的好方法

**Comment by sunhailin-Leo** [comment]
@wjdiadijai 
* 你说的这个 可编辑的 pdf。。估计你得问 Echarts 了。。
