### ISSUE TITLE
请问大神有计划支持Bar Race吗？感觉很酷！

### ISSUE THREAD

**Issue by huangxin168** [pyecharts/pyecharts#2010]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@huangxin168 
* 已支持，但需要自行使用 `add_js_funcs` 控制 race 时间

**Comment by huangxin168** [comment]
> 

请问有文档指导如何使用race功能吗？

**Comment by sunhailin-Leo** [comment]
@huangxin168 
* 上面已经说的很明白了，用 `add_js_funcs`。去添加 setInterval 和 setTimeout 的 js 函数。 
* bar race 的本质还是动态渲染。https://echarts.apache.org/examples/zh/editor.html?c=bar-race
* 文档以前有过与 web 框架配置的动态渲染。https://pyecharts.org/#/zh-cn/web_flask?id=%e5%ae%9a%e6%97%b6%e5%a2%9e%e9%87%8f%e6%9b%b4%e6%96%b0%e5%9b%be%e8%a1%a8

**Comment by huangxin168** [comment]
> @huangxin168
> 
> * 上面已经说的很明白了，用 `add_js_funcs`。去添加 setInterval 和 setTimeout 的 js 函数。
> * bar race 的本质还是动态渲染。https://echarts.apache.org/examples/zh/editor.html?c=bar-race
> * 文档以前有过与 web 框架配置的动态渲染。https://pyecharts.org/#/zh-cn/web_flask?id=%e5%ae%9a%e6%97%b6%e5%a2%9e%e9%87%8f%e6%9b%b4%e6%96%b0%e5%9b%be%e8%a1%a8

明白了，感谢！
