### ISSUE TITLE
grid下集成k线和Line 的颜色设置失效

### ISSUE THREAD

**Issue by 116205035** [pyecharts/pyecharts#2011]
**问题**
使用grid 集成 k线和line的时候，line 设置的不同颜色区域失效了，单独使用line 一切正常。 

**运行环境（系统环境及 pyecharts 版本）**
当前版本标识为 0.8.24@20220418
python 3.9

**代码及截图**
![image](https://user-images.githubusercontent.com/10265076/164908985-e3fffea9-be1c-42c7-ba35-5c60c83d533a.png)

**Comment by 116205035** [comment]
分开设置了红绿两种颜色，合在一起后只有一种颜色，且是k线的颜色，而不是我设置的颜色

**Comment by 00319733** [comment]
请问解决了吗？我也遇到类似的问题
