### ISSUE TITLE
 baroverlap(line) 绘制组合图，标签值显示不对。

### ISSUE THREAD

**Issue by zzbb188** [pyecharts/pyecharts#2014]
我使用 bar.overlap(line)绘制组合图(折线和柱状图)，设置line.set_series_opts(label_opts=opts.LabelOpts(font_size=10, formatter="{c}%"))时，所显示的标签值会把x轴对应的刻度值带上，我期望的效果为：18%，得到了：2022-01-01,18%

**Comment by sunhailin-Leo** [comment]
@zzbb188 
* 给 formatter 一个 JsCode 的回调函数即可
