### ISSUE TITLE
pyecharts的地图绘制maptype="china-cities"与maptype="china"所呈现的地图的尺寸不一致

### ISSUE THREAD

**Issue by skyknoow** [pyecharts/pyecharts#2015]
**问题**

绘制中国地图 时，`maptype="china-cities"`与`maptype="china"`所呈现的地图的尺寸不一致，导致在`maptype="china-cities"`下，我的满足四至点范围的点集无法正确的打点在地图上，而`maptype="china"`下却可以正确打点（点集完全覆盖地图）。
我的四至点经纬常量如下：
const ( // 中国地理位置四至点来自https://baike.baidu.com/item/%E4%B8%AD%E5%9B%BD%E5%9C%B0%E7%90%86%E4%BD%8D%E7%BD%AE%E5%9B%9B%E8%87%B3%E7%82%B9/8988584
lngMin = 73. + 40./60. // 最西端     lngMax = 135. + 5./60. // 最东端    latMin = 3. + 52./60.  // 最南端    latMax = 53. + 37./60. // 最北端  
)

**运行环境（系统环境及 pyecharts 版本）**
pyechars版本为1.9.1

**代码及截图**

下图为maptype="china-cities"时的绘图情况
![FindGrowth-6-5-alpha-热力图](https://user-images.githubusercontent.com/67677288/166144467-5c786dc5-bf5e-4868-a652-f5685872b042.png)

下图为maptype="china"时的绘图情况
![FindGrowth-12-10-alpha-热力图](https://user-images.githubusercontent.com/67677288/166144496-5958951d-f221-4442-97e5-f58317596e4a.png)

上面这两个图的矩形栅格是我的满足四至点限制的点集

**Comment by sunhailin-Leo** [comment]
@skyknoow 
* 这个目前不清楚为什么。估计与 china-cities 的 geo_json 有关。

**Comment by skyknoow** [comment]
> 

好吧，我也这么觉得。希望pyecharts尽快修正吧，保持一致性还是有必要的。

**Comment by skyknoow** [comment]
> 

我也这么觉得，期待下个版本解决下，持图的一致性还是必要的。

**Comment by sunhailin-Leo** [comment]
@skyknoow 
* 框选`四至点`的代码还在嘛？我这边想测试一下

**Comment by sunhailin-Leo** [comment]
@skyknoow 
* https://github.com/pyecharts/pyecharts-assets/commit/2f5b8942e70ce179ac7740e1db9858ebbaf78694
* 已更新 `china-cities.js` 可以再试试，如果还有问题的话，请 reopen issue。
