### ISSUE TITLE
pyecharts在x，y轴同时添加datazoom

### ISSUE THREAD

**Issue by FLFLE** [pyecharts/pyecharts#2017]
**问题**
现版本pycharts中是否有像v0.5中的datazoom_type=‘both’一样能让datazoom同时作用于x和y轴的参数？

**运行环境（系统环境及 pyecharts 版本）**

windows11
python3.7
pyecharts 1.9.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@FLFLE 
* 需要自行添加。1.x 版本以后 DataZoomOpts 支持列表形式。
