### ISSUE TITLE
地图绘制散点必须传入地名的问题

### ISSUE THREAD

**Issue by rufeng-h** [pyecharts/pyecharts#2019]
**问题**

echarts中，百度地图绘制散点图可以仅传入坐标数据，但是pyecharts中地名和坐标都需要。希望可以做到传入坐标可以直接绘制

**运行环境（系统环境及 pyecharts 版本）**

Python3.8.2 pyecharts1.9.1

**代码及截图**
对于geo和bmap，都报同样的错
![image](https://user-images.githubusercontent.com/59313130/168629013-539f60d7-2142-451c-98e4-ab8e6cf68201.png)

pyecharts文档
![image](https://user-images.githubusercontent.com/59313130/168626615-21e26dc0-a6f0-4501-8978-05a08944457a.png)

**Comment by sunhailin-Leo** [comment]
@rufeng-h 
* BMap 依赖百度地图的经纬度信息。
* Geo 和 Map 本身的图层没有包含经纬度信息
