### ISSUE TITLE
GeoLines 在最新的版本里面不支持了吗？

### ISSUE THREAD

**Issue by Wapiti08** [pyecharts/pyecharts#2020]
**问题**
Geolines 不能够从pyecharts or pyecharts.charts中导入：

**运行环境（系统环境及 pyecharts 版本）**
pyecharts == 1.9.1
python == 3.8

**代码及截图**
```
cannot import name 'GeoLines' from 'pyecharts' (c:...\Python\Python38\lib\site-packages\pyecharts\__init__.py)
```

**Comment by sunhailin-Leo** [comment]
@Wapiti08 
* Geo 叠加 Lines
