### ISSUE TITLE
pyecharts 1.7.1 折线图渲染后的数据不对

### ISSUE THREAD

**Issue by karlzheng** [pyecharts/pyecharts#2021]
**问题**
pyecharts 1.7.1 在Python 3.9.10上，折线图渲染后的数据不对:
代码在：
https://github.com/karlzheng/kquant/blob/master/161005/fgth.py

折线图渲染后的html文件，在：
https://github.com/karlzheng/kquant/blob/master/161005/fgth.html

出错的地方：
s399106['Close']['2021-02-10'] 的数据为： 12302.7，
但在折线图中渲染出来的数据为1万零几，导致显示不正确。

麻烦修正。
感谢！

**运行环境（系统环境及 pyecharts 版本）**
macbook pro M1 , macOS 12.3.1 
pyecharts 1.7.1 
Python 3.9.10 

**代码及截图**

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/2570701/169686676-850136cd-5ccd-4472-849c-6da606166c91.png">

**Comment by karlzheng** [comment]
@chfw @chenjiandongx 请看一下，谢谢

**Comment by liaorongling** [comment]
我也是一样的环境，折线图，但是是不一样的错误，仅仅使用x=[1,2,3,4]， y=[1,2,3,4]，错误是折线图出现了错位

**Comment by sunhailin-Leo** [comment]
@karlzheng @liaorongling 
* 试下最新版本的是否还有这样的问题。（暂时先 close issue 哈）
