### ISSUE TITLE
pyechart的grid合并上中下三图，如何确保这三图不相关，每个图的图标单选不影响其它图

### ISSUE THREAD

**Issue by lizhiqiangmy** [pyecharts/pyecharts#2023]
**问题**
我们在使用pyechart作图时，作了三个图，其中每个图又是使用overlap叠加而成的，最后使用grid将这三个图按照上中下排列。目前的问题是：1. 我们的上图包含3三个显示图标，我们想对后两个显示图标设置成（single）互斥单选功能，也即永远只显示其中一个，目前我们无法实现，请求帮助解决。2. 我们的下图也包含了多个图标，目前使用了（single）选项，可以实现双击切换，只显示其中一个。但是如果我们点击上图图标让其被选中显示时，会影响下图图表显示，也即排斥下图使得下图选中的退出，不显示任何一个图标内容。

**运行环境（系统环境及 pyecharts 版本）**
ubuntu系统，pyechart是最近的版本

**代码及截图**
![image](https://user-images.githubusercontent.com/87459360/170850375-edff5288-7b2e-451a-9092-99d9dcf89a25.png)
![image](https://user-images.githubusercontent.com/87459360/170850509-df981de7-31fe-45f4-a2ee-1859a38c234f.png)

**Comment by sunhailin-Leo** [comment]
@lizhiqiangmy 
* 可以试试修改 legend 的 selectedMode 哈
