### ISSUE TITLE
您好，pyecharts 1.9.1 Map 的 symbol 参数不能修改 【标记图形形状】，请教有那些参数可以选择？

### ISSUE THREAD

**Issue by hkfalcon** [pyecharts/pyecharts#2026]
**问题**

您好，pyecharts 1.91 Map 的 symbol 参数不能修改 【标记图形形状】，请教有那些参数可以选择？

**运行环境（系统环境及 pyecharts 版本）**

Win10+Python3.74+pyecharts 1.9.1

**代码及截图**

```
# -*- coding: UTF-8 -*-

from pyecharts.charts import Map
from pyecharts import options as opts

data = [('China', 0.7), ('Canada', 0.01),('United States', 0.01)]

test = Map()

test.add("",
         data,
         maptype="world",
         label_opts=opts.LabelOpts(is_show=False),
         selected_mode=True,
         tooltip_opts=opts.TooltipOpts(is_show_content=False), 
         symbol='triangle',
         is_map_symbol_show=True
        )

test.set_global_opts(title_opts=opts.TitleOpts(title="Test"),visualmap_opts=opts.VisualMapOpts(is_show=False))
test.render("Test.html")
test.render_notebook()
```

![image](https://user-images.githubusercontent.com/38371281/171048833-a79e3d83-6837-44e1-b36b-dbce1054e0e7.png)

![image](https://user-images.githubusercontent.com/38371281/171079487-29c94816-d504-4d5c-8444-d8eb74ba4e1e.png)

**Comment by cicue** [comment]
应该是还没有开发

**Comment by dennyz80** [comment]
symbol 可以使用图片生成base64的json格式
在代码中使用
`with open("symbol.json", "r", encoding="utf-8") as f:
    symbols = json.load(f)`
就可以自定义标记图形了
