### ISSUE TITLE
示例代码参数不对及“错别字”问题

### ISSUE THREAD

**Issue by GhostZey** [pyecharts/pyecharts#2027]
**问题**
问题一：在你们官方的gallery中有这样一份K线图示例代码：https://gallery.pyecharts.org/#/Candlestick/professional_kline_chart
下载下来是无法运行的，因为其中的add_yaxis()方法的正确的参数应为y_axis，但代码中亦有出现yaxis_data（可能是版本更迭参数名的改动没有及时修改？），导致代码无法运行，全部yaxis_data修改为y_axis后可正常运行。
问题二：代码中的成交量英文单词应为：Volume，而不是Volumn。可以直接搜索修改。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts版本1.9.1。

**代码及截图**
在IDE中直接搜索上述错误参数名（yaxis_data）即可，错误似乎是两处，改为”y_axis“后可运行。

**Comment by sunhailin-Leo** [comment]
@GhostZey 
* gallery 的 issue 不需要提在主 repo 上。
