### ISSUE TITLE
求助：柱状图堆叠时，数据量较少的项不容易看见

### ISSUE THREAD

**Issue by yifei325325** [pyecharts/pyecharts#2028]
各位开发者大佬们你们好，
在使用pyecharts 的时候，我遇到这样的问题：
我的需要是有多组数据进行堆叠显示，当有些数据项数据比较少的话，在同样y轴比例尺下，该组数据就几乎看不见了，不知道有没有方法可以在堆叠的各组数据中添加空白区域分割，或者有什么更好的办法？
我的项目样例：
passed 的数据占大多数，而failed 占少数，这样会导致failed几乎看不见。
![image](https://user-images.githubusercontent.com/9191218/172580713-92f17fed-53e4-41c1-bcf3-e64d455bbe8d.png)
我的预期：
![image](https://user-images.githubusercontent.com/9191218/172581011-57d6cccf-b610-49b2-9762-45a43f3543e5.png)

非常感谢！！！

**Comment by sunhailin-Leo** [comment]
@yifei325325 
* Echarts 那边目前也没有 图2 的空白分割。
* 数据极差较大建议用饼图或者，多列柱状图展示。
