### ISSUE TITLE
New Feature Requirement!

### ISSUE THREAD

**Issue by Wapiti08** [pyecharts/pyecharts#2029]
Is there a way to achieve performance like this with pyecharts?

https://echarts.apache.org/zh/option-gl.html#series-lines3D

**Comment by sunhailin-Leo** [comment]
@Wapiti08 dev branch had already added this feature.

**Comment by Wapiti08** [comment]
Thanks a lot

**Comment by Wapiti08** [comment]
Is that possible to give me some instructions on that? I have checked the dev and did not find relative examples.

**Comment by Wapiti08** [comment]
> Is that possible to give me some instructions on that? I have checked the dev and did not find relative examples.

I found that in Lines3D. No worries.
