### ISSUE TITLE
Toolbox上的datazoom(区域放大)功能不能用(v1.9.1)是新版本的bug

### ISSUE THREAD

**Issue by Tryiton123** [pyecharts/pyecharts#2031]
**问题**

Toolbox上的datazoom(区域放大)，能显示在Chart上面， 但是不能框选放大。
我试着安装之前的版本1.1.0，这个功能就可以用了。

**运行环境（系统环境及 pyecharts 版本）**
python3.8
pyecharts 1.9.1
Windows 11 
![image](https://user-images.githubusercontent.com/107338738/173219187-89f06543-bf0c-4108-abbd-a18fcf989dd7.png)

**代码及截图**

import pyecharts.options as opts
from pyecharts.charts import Line
from pyecharts.faker import Faker

c = (
    Line()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(title_opts=opts.TitleOpts(title="Line-基本示例"),
                     toolbox_opts=opts.ToolboxOpts(is_show=True))
    .render("line_base.html")
)

![image](https://user-images.githubusercontent.com/107338738/173219340-01521951-bf45-4b65-9634-10171bf0c2c2.png)

**Comment by sunhailin-Leo** [comment]
2.X 会修复此功能～
