### ISSUE TITLE
BMap三维地图无法显示

### ISSUE THREAD

**Issue by ahustr** [pyecharts/pyecharts#2034]
**代码及截图**
![image](https://user-images.githubusercontent.com/55874332/174543428-6ba2351d-5c4c-4b5c-ae17-a11fb1d8e488.png)

**Comment by sunhailin-Leo** [comment]
@ahustr 
* 你有自己申请百度的 key 嘛？

**Comment by ahustr** [comment]
有的

**Comment by ahustr** [comment]
其他两种都可以显示

**Comment by ahustr** [comment]
from pyecharts import options as opts
from pyecharts.charts import BMap
from pyecharts.globals import GeoType

example_data = [{"coords":[[-66,72],[-169,72],[-169,25],[-66,25],[-66,72]],
 "lineStyle":{"normal":{"color":"rgba(223,90,90,1)"}}}]


c = (
    BMap()
        .add_schema(baidu_ak="ak",
                center=[-117.5, 48.5],
                #is_roam= True,
                #zoom = 1)
                    )
    .add(
        series_name="Map",
        #is_polyline=True,
        data_pair=example_data,
        is_large=True,
        type_ = GeoType.LINES,
        linestyle_opts=opts.LineStyleOpts(opacity=0.2, width=5),
        label_opts=opts.LabelOpts(formatter="{b}"),
    )
    .add_control_panel(
        maptype_control_opts=opts.BMapTypeControlOpts(
            type_=0
        )
    )
    #.set_global_opts(title_opts=opts.TitleOpts(title="BMap-基本示例"))
    .render("bmap_base.html")
)

**Comment by sunhailin-Leo** [comment]
@ahustr 
* 看下浏览器控制台有没什么报错提示？
