### ISSUE TITLE
请问如何将制作的动态图保存为gif文件呢？

### ISSUE THREAD

**Issue by zlove-summer** [pyecharts/pyecharts#2037]
**问题**
请问如何将制作的动态图保存为gif文件呢？ 使用以下代码，保存的gif是不会动的

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![image](https://user-images.githubusercontent.com/81303574/175505543-4ef57668-6f6b-4950-8082-3f11e69f4989.png)

**Comment by sunhailin-Leo** [comment]
@zlove-summer 
* 暂时没办法。
