### ISSUE TITLE
Overlap import not working

### ISSUE THREAD

**Issue by MichaelC1999** [pyecharts/pyecharts#2039]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

Attempting to import Overlap from pyecharts returns an error. I have installed 1.9.1 and used the class as explained in the documentation. Looked through the package source code and see no reference to this class even though it is present in the documentation.

**Comment by sunhailin-Leo** [comment]
@MichaelC1999 
* Try this
* https://gallery.pyecharts.org/#/Overlap/overlap_bar_line
