### ISSUE TITLE
Geo中等数据大小Jupyter显示崩溃，同时生成Html文件过大Bug🐞

### ISSUE THREAD

**Issue by antecede** [pyecharts/pyecharts#2042]
**问题**
Geo中等数据大小 (才50万个数据点)Jupyter中便无法显示，同时生成Html文件过大 (160MB)。
后期可否提供支持大数据的显示优化以及保存文件的大小优化。或者当数据量过大时，提供直接保存为静态矢量图 (pdf)的方式 (非make_snapshot方式，对于大数据这种方式还是过于鸡肋了)？

**运行环境（系统环境及 pyecharts 版本）**
```
CentOS Linux release 7.5.1804 (Core)
Python 3.9.13
pyecharts                         1.9.1
```

**代码及截图**
![1656928406938](https://user-images.githubusercontent.com/46232487/177130584-fa13ed67-9f16-4383-bebc-1f7fba38d1dc.png)
![image](https://user-images.githubusercontent.com/46232487/177130974-173e2e63-b657-441c-9482-cdf76996c69d.png)

**Comment by sunhailin-Leo** [comment]
@antecede 
* 这么大的数据量你给谁都没法不崩溃吧？浏览器也有自己的存储空间的。

**Comment by antecede** [comment]
> @antecede
> 
> * 这么大的数据量你给谁都没法不崩溃吧？浏览器也有自己的存储空间的。
@sunhailin-Leo PB级才能称之为大数据吧。kepler.gl可以完美流畅地渲染，而且生成地HTML才10MB

**Comment by sunhailin-Leo** [comment]
@antecede 
* Echarts 底层用的 canvas，kepler 用的是 canvas 3d，两个东西都不是一码事。

**Comment by antecede** [comment]
> * canvas 3d



> @antecede
> 
> * Echarts 底层用的 canvas，kepler 用的是 canvas 3d，两个东西都不是一码事。

哦哦，了解了，多谢指教😊
