### ISSUE TITLE
Is  there a plan to support gl

### ISSUE THREAD

**Issue by v-wx-v** [pyecharts/pyecharts#2043]
**问题**

Is  there a plan to support gl

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by wybert** [comment]
> 

我发现在知乎上有[个帖子可以间接](https://zhuanlan.zhihu.com/p/355050353)的解决问题。
当然如果能够直接支持会更好。

**Comment by sunhailin-Leo** [comment]
@v-wx-v @wybert 
* I will try it, but it will take a long time.

**Comment by sunhailin-Leo** [comment]
在 2.0 以后
* 基于 Geo 的图支持 scatterGL, flowGL, linesGL
* 单独的图已经实现 GraphGL

**Comment by wybert** [comment]
> 在 2.0 以后
> 
> * 基于 Geo 的图支持 scatterGL, flowGL, linesGL
> * 单独的图已经实现 GraphGL

AWESOME
