### ISSUE TITLE
使用render_notebook 去渲染graph或者 geo 都是空白

### ISSUE THREAD

**Issue by FoSuCloud** [pyecharts/pyecharts#2045]
绘制bar和Calendar没问题
from pyecharts import options as opts
from pyecharts.charts import EffectScatter
from pyecharts.faker import Faker
from pyecharts.globals import SymbolType

c = (
    EffectScatter()
    .add_xaxis(Faker.choose())
    .add_yaxis("", Faker.values(), symbol=SymbolType.ARROW)
    .set_global_opts(title_opts=opts.TitleOpts(title="EffectScatter-不同Symbol"))
    .render_notebook()
)

**问题**
使用render_notebook 去渲染graph或者 geo 都是空白

**运行环境（系统环境及 pyecharts 版本）**
pyecharts==1.9.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@FoSuCloud 
* 你在什么编辑器下渲染的？

**Comment by FoSuCloud** [comment]
> @FoSuCloud
> 
> * 你在什么编辑器下渲染的？

jupyterlab。没有返回数据

**Comment by sunhailin-Leo** [comment]
@FoSuCloud 
* https://pyecharts.org/#/zh-cn/notebook?id=jupyter-lab

**Comment by XstormLeigh** [comment]
啥方法都试过了，DATASPELL就是不出图！

from pyecharts.charts import Bar,HeatMap
from pyecharts import options as opts
from pyecharts.globals import ThemeType
from pyecharts.globals import CurrentConfig, NotebookType, OnlineHostType
CurrentConfig.ONLINE_HOST = OnlineHostType.NOTEBOOK_HOST
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB
