### ISSUE TITLE
dev分支中的词云没有彩色

### ISSUE THREAD

**Issue by StevenTang1998** [pyecharts/pyecharts#2047]
使用gallery中的代码：https://gallery.pyecharts.org/#/WordCloud/wordcloud_custom_font_style

master分支中的代码正常显示
dev分支中的词云没有彩色，且字体也没有变化

**Comment by sunhailin-Leo** [comment]
@StevenTang1998 
* Echarts 5 适配导致没有颜色。dev 分支中已经修复了
