### ISSUE TITLE
Candlestick/professional_kline_chart 无法注释k线，成交量和macd任何一个

### ISSUE THREAD

**Issue by xswby** [pyecharts/pyecharts#2048]
**问题**
Candlestick/professional_kline_chart 我想注释成交量的区域，发现缺少
# Volumn 柱状图
    grid_chart.add(
        bar_1,
        grid_opts=opts.GridOpts(
            pos_left="3%", pos_right="1%", pos_top="71%", height="10%"
        ),
    )
我发运行

**运行环境（系统环境及 pyecharts 版本）**
macos 12.4
pyecharts 1.9.1

**代码及截图**
<img width="560" alt="image" src="https://user-images.githubusercontent.com/34242457/182552261-ac37387d-615c-40de-82d8-6068d66ab0e9.png">

其他代码未动，仅注释这段，其他的macd图形，我也尝试zhu注释也不行

**Comment by sunhailin-Leo** [comment]
@xswby 
* 这块测试过没有问题的，检查下你的代码
