### ISSUE TITLE
两个table是否可以叠加

### ISSUE THREAD

**Issue by luoxigod** [pyecharts/pyecharts#2052]
**问题**
不同类型的图表我可以使用overlap叠加，那么两个table能否叠加（一个靠左显示，一个靠右显示，不影响阅读）。如果可以的话具体代码怎么做。这种主要是用来显示数据以及对应的环比/同比用的，比如最近一个月的销量以及对比去年同期的比率，分成两个表阅读性啥的也不好。

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@luoxigod 
* Table 只是一个实验性的功能，用于展示数据。如果需要定制化功能的话，还需自行去使用 HTML 的 Table 组件
