### ISSUE TITLE
可否支持在PowerBI上渲染，即可交互的图表，而不是图片

### ISSUE THREAD

**Issue by wakakaaaa** [pyecharts/pyecharts#2055]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@wakakaaaa 
* “巨硬”系列的东西都没法插入 HTML。曾经 Echarts 想做插件，结果腰斩了。。。所以支持不了哈。
