### ISSUE TITLE
散点图 x轴标签相同 会显示重复的x轴标签

### ISSUE THREAD

**Issue by chaohong123** [pyecharts/pyecharts#2056]
pyecharts版本：1.9.1
python:3.7

**问题**
Scatter散点图 如果同一个x轴标签想画多个数值 会显示重复的x轴。

<img width="306" alt="截屏2022-09-03 15 51 01" src="https://user-images.githubusercontent.com/51693075/188261545-e9c3654c-7587-425d-a5cf-1e478d4f17b5.png">

**代码及截图**

<img width="800" alt="截屏2022-09-03 15 51 14" src="https://user-images.githubusercontent.com/51693075/188261536-07fdf061-b1f4-4570-afbb-e33a0a131d02.png">

    scatter = (
        Scatter(init_opts=opts.InitOpts(width= '300px', height='300px'))
            .add_xaxis(['0','0','0','1','1','1'])
            .add_yaxis('y',[1,2,3,4,5,6])
            .set_global_opts(
            title_opts=opts.TitleOpts(title=""),
            xaxis_opts=opts.AxisOpts(splitline_opts=opts.SplitLineOpts(is_show=True)),
            yaxis_opts=opts.AxisOpts(splitline_opts=opts.SplitLineOpts(is_show=True)),
        )

            .render("./scatter.html")
    )

**Comment by sunhailin-Leo** [comment]
@chaohong123 
* x 轴的类型是 category 就会这样，改成 value 就好了，然后你的 x 轴数据都用数值
