### ISSUE TITLE
一个Grid里面无法添加多个DataZoom

### ISSUE THREAD

**Issue by zygcch** [pyecharts/pyecharts#2057]
**问题**
一个Grid里面无法添加多个DataZoom, 只有第一个bar可以缩放，其他的bar都无法缩放。
参考了issue#1284，那种方式无法解决所有场景的需求：当我添加第一个bar到grid的时候，我并不清楚这个grid里面后续将会添加多少个bar，所以没办法在第一个bar那里传入准确的DataZoomOpts list

是否可以考虑一下，把后续的bar的DataZoomOpt，自动添加到第一个bar的DataZoomOpt list里面？

**运行环境（系统环境及 pyecharts 版本）**

pyecharts.__version__
1.9.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@zygcch 
* Echarts 添加配置都是有明确的指向性。
* 对于 issue 提出的"自动添加" 是不会考虑的，因为这种需求并不是 bug 带来的
