### ISSUE TITLE
折线图自定义提示框显示多余“，“

### ISSUE THREAD

**Issue by qinian222** [pyecharts/pyecharts#2058]
**问题**
1 折线图使用自定义提示框配置时，内容显示总是 横坐标数据，纵坐标数值  ，多余一个","符号

**运行环境（系统环境及 pyecharts 版本）**
Python 3.7
pyecharts 1.9.1

**代码及截图**
from django.http import HttpResponse
from pyecharts.charts import Line
from pyecharts import options as opts
from pyecharts.commons.utils import JsCode
from pyecharts.faker import Faker

def index(requests):
    data_x = ['20200306', '20200307', '20200308', '20200309', '20200310', '20200311', '20200312']
    data_y = ['18.51%', '17.11%', '18.67%', '16.61%', '16.74%', '17.55%', '17.18%']
    data_y_0 = [float(x.strip('%')) for x in data_y]

    line = (
        Line()
            .add_xaxis(data_x)
            .add_yaxis("带宽利用率", data_y_0,
                       label_opts=opts.LabelOpts(formatter=JsCode("function (params) {return params.value[1] + '%'}")))
            .set_global_opts(title_opts=opts.TitleOpts(title=""),
                             legend_opts=opts.LegendOpts(pos_left="30%"),
                             tooltip_opts=opts.TooltipOpts(trigger="axis",formatter="{c}%"))

    )
    return HttpResponse(line.render_embed())
![image](https://user-images.githubusercontent.com/59074146/190049263-cc2a33cd-0f78-4ef1-b00f-25ac0c67d2b6.png)

**Comment by qinian222** [comment]
有没有大佬提供下解决思路

**Comment by qinian222** [comment]
提示框配置：
formatter="{a}"  时 显示折线series_name
formatter="{b}"  时显示横坐标数值
formatter="{c}"  时会显示横坐标,纵坐标数值  ，能只显示纵坐标数值吗？

**Comment by sunhailin-Leo** [comment]
@qinian222 
* 用 formatter 去格式化。
