### ISSUE TITLE
使用字典形式初始化参数时，animationOpts无法使用字典配置

### ISSUE THREAD

**Issue by dennyz80** [pyecharts/pyecharts#2059]
**问题**
使用字典形式初始化参数时，animationOpts无法使用字典配置，渲染时会提示
self.options.update(_opts.get("animationOpts", AnimationOpts()).opts) AttributeError: 'dict' object has no attribute 'opts' 

**运行环境（系统环境及 pyecharts 版本）**
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
pyecharts1.9.1

**代码及截图**

```
def theme_default() -> Bar:
    c = (
        Bar({
                'width': '800px',
                'heigh': '600px',
                'animationOpts':
                        {
                            'animation': True,
                            'animationEasing': 'elasticOut'
                        }
            })
            # Bar(init_opts=opts.InitOpts(theme=ThemeType.WHITE))
            # 等价于 Bar(init_opts=opts.InitOpts(theme=ThemeType.WHITE))
            .add_xaxis(Faker.choose())
            .add_yaxis("商家A", Faker.values())
            .add_yaxis("商家B", Faker.values())
            .add_yaxis("商家C", Faker.values())
            .add_yaxis("商家D", Faker.values())
            .set_global_opts(title_opts=opts.TitleOpts("Theme-default"))
    )
    return c


c = theme_default()
c.render('test.html')
```

**当前的解决方法**
pyecharts\charts\base.py中
将原始代码
`self.options.update(_opts.get("animationOpts", AnimationOpts()).opts)`
更改为
`self.options.update(_opts.get("animationOpts", AnimationOpts().opts)) if isinstance(_opts.get("animationOpts", AnimationOpts()),dict) else self.options.update(_opts.get("animationOpts", AnimationOpts()).opts)`

**Comment by sunhailin-Leo** [comment]
@dennyz80 如果可以的话，可以提个 `pr` 到 `dev` 分枝上
