### ISSUE TITLE
屏幕自适应 要怎么设置 或者 修改代码

### ISSUE THREAD

**Issue by dontworrywearetogether** [pyecharts/pyecharts#2060]
**问题**
做了 一个 DraggablePageLayout 布局 的页面 
但是 在不同的 屏幕上 大小显示不完全， 可以设置么？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.9

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@dontworrywearetogether 修改渲染模版
