### ISSUE TITLE
画堆叠柱状图时，无法给某个数据点设置base/offset, 只能从默认的0开始，麻烦解决，谢谢

### ISSUE THREAD

**Issue by ncu1121zhb** [pyecharts/pyecharts#2062]
**问题**
如标题所述，在画柱状图时，无法给数据点设置base或offset，默认都是从0开始的，这在画很多图的时候无法达到想要的效果
具体的例子和需要实现的意图，详见**代码及截图**

**运行环境（系统环境及 pyecharts 版本）**
柱状图中无法给每个数据点设置base或offset, 只能从默认的0开始显示柱图
Window10 + Pyecharts 1.9.1

**代码及截图**

假设数据为：
x = ['Mon', 'Tue', 'Wed', 'Thu']
y = {'Alpha':[60, 85, 115, 40]
        'Bravo':[31, 129, 50, 60]}

需要实现的stack bar chart 效果图如下:
![image](https://user-images.githubusercontent.com/78291739/192079812-f052a450-8655-4614-b792-40da07d5d55e.png)

**Comment by sunhailin-Leo** [comment]
@ncu1121zhb 
* 目前没看到 Echarts 有相关的功能可以实现哈。
