### ISSUE TITLE
BMAP 生成svg图片出错

### ISSUE THREAD

**Issue by Chrisable** [pyecharts/pyecharts#2063]
from pyecharts.render import make_snapshot
from snapshot_selenium import snapshot
from pyecharts import options as opts
from pyecharts.charts import BMap
from pyecharts.faker import Faker

c = (
    BMap(opts.InitOpts(renderer='svg'))
    .add_schema(baidu_ak="x", center=[120.13066322374, 30.240018034923])
    .add(
        "bmap",
        [list(z) for z in zip(Faker.provinces, Faker.values())],
        type_="heatmap",
        label_opts=opts.LabelOpts(formatter="{b}"),
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="BMap-热力图"), visualmap_opts=opts.VisualMapOpts()
    )
    .render("graph/bmap_heatmap.html")
)

make_snapshot(snapshot, c.render(), "graph/bmap_base.svg")

生成出来的svg为空

**Comment by sunhailin-Leo** [comment]
@Chrisable 
* BMap 的底层是百度地图，用 SVG 没办法生成出来。可以试试用 jpeg
