### ISSUE TITLE
world_china_provinces不显示，但别的地图可以

### ISSUE THREAD

**Issue by DaiDai-Dad** [pyecharts/pyecharts#2064]
**问题**
world_china_provinces不显示，但别的地图可以

**运行环境（系统环境及 pyecharts 版本）**
win10
python3.7.13
pyecharts1.9.1

**代码及截图**
在使用本地assets资源的情况下：
CurrentConfig.ONLINE_HOST ='static/pyecharts-assets/assets/'

def world_map(request):
    world = (
        Geo()
        .add_schema(maptype="world", center=[120,38])
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(), title_opts=opts.TitleOpts(title="世界地图")
        )
        .render(Path.cwd()/"index/templates/index_world.html")
    )

    return render(request, 'index_world.html', {})
上述代码可正常运行，结果如下：
![image](https://user-images.githubusercontent.com/110294065/193416277-a4042532-f01e-425c-81f5-cae2d909f0bc.png)

将maptypeg改为world_china_provinces
页面是空白，浏览器按F12查看network发现world_china_provinces.js已成功加载了：

如果去掉本地化的代码，链接官方assets资源，world_map方法里依然用maptype="world_china_provinces"，依然无法正确显示

附上生成的index_world.html

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Awesome-pyecharts</title>
            <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
        <script type="text/javascript" src="https://assets.pyecharts.org/assets/maps/world_china_provinces.js"></script>

</head>
<body>
    <div id="dc85c3ccd0d843c5a093c6e82aaa1e43" class="chart-container" style="width:900px; height:500px;"></div>
    <script>
        var chart_dc85c3ccd0d843c5a093c6e82aaa1e43 = echarts.init(
            document.getElementById('dc85c3ccd0d843c5a093c6e82aaa1e43'), 'white', {renderer: 'canvas'});
        var option_dc85c3ccd0d843c5a093c6e82aaa1e43 = {
    "animation": true,
    "animationThreshold": 2000,
    "animationDuration": 1000,
    "animationEasing": "cubicOut",
    "animationDelay": 0,
    "animationDurationUpdate": 300,
    "animationEasingUpdate": "cubicOut",
    "animationDelayUpdate": 0,
    "color": [
        "#c23531",
        "#2f4554",
        "#61a0a8",
        "#d48265",
        "#749f83",
        "#ca8622",
        "#bda29a",
        "#6e7074",
        "#546570",
        "#c4ccd3",
        "#f05b72",
        "#ef5b9c",
        "#f47920",
        "#905a3d",
        "#fab27b",
        "#2a5caa",
        "#444693",
        "#726930",
        "#b2d235",
        "#6d8346",
        "#ac6767",
        "#1d953f",
        "#6950a1",
        "#918597"
    ],
    "series": [],
    "legend": [
        {
            "data": [],
            "selected": {},
            "show": true,
            "padding": 5,
            "itemGap": 10,
            "itemWidth": 25,
            "itemHeight": 14
        }
    ],
    "tooltip": {
        "show": true,
        "trigger": "item",
        "triggerOn": "mousemove|click",
        "axisPointer": {
            "type": "line"
        },
        "showContent": true,
        "alwaysShowContent": false,
        "showDelay": 0,
        "hideDelay": 100,
        "formatter": function (params) {        return params.name + ' : ' + params.value[2];    },
        "textStyle": {
            "fontSize": 14
        },
        "borderWidth": 0,
        "padding": 5
    },
    "title": [
        {
            "text": "\u4e16\u754c\u5730\u56fe",
            "padding": 5,
            "itemGap": 10
        }
    ],
    "visualMap": {
        "show": true,
        "type": "continuous",
        "min": 0,
        "max": 100,
        "inRange": {
            "color": [
                "#50a3ba",
                "#eac763",
                "#d94e5d"
            ]
        },
        "calculable": true,
        "inverse": false,
        "splitNumber": 5,
        "orient": "vertical",
        "showLabel": true,
        "itemWidth": 20,
        "itemHeight": 140,
        "borderWidth": 0
    },
    "geo": {
        "map": "world_china_provinces",
        "center": [
            120,
            38
        ],
        "roam": true,
        "aspectScale": 0.75,
        "nameProperty": "name",
        "selectedMode": false,
        "emphasis": {}
    }
};
        chart_dc85c3ccd0d843c5a093c6e82aaa1e43.setOption(option_dc85c3ccd0d843c5a093c6e82aaa1e43);
    </script>
</body>
</html>

**Comment by DaiDai-Dad** [comment]
补充图片
将maptypeg改为world_china_provinces后的效果：js文件已加载，但页面是空白
![无标题](https://user-images.githubusercontent.com/110294065/193417238-d5421705-9024-4895-b6be-2c81c9472324.png)

**Comment by sunhailin-Leo** [comment]
@DaiDai-Dad 
* Fixed...
