### ISSUE TITLE
English language documentation for version >=1.0.0

### ISSUE THREAD

**Issue by GregorySwart** [pyecharts/pyecharts#2065]
**Is there any English language documentation for newer versions of the package?**

I've been using pyecharts and so far it's very useful but I'm having some difficulties making more complex charts, and the documentation that I have found on both [https://pyecharts.org](https://pyecharts.org/#/en-us/charts_base) and [pyecharts.readthedocs.io](https://pyecharts.readthedocs.io/projects/pyecharts-en/zh/latest/en-us/charts_base/) are for an outdated version (I think 0.5.11).

Is there any documentation for the latest version (1.9.1)?

**Comment by sudheer82** [comment]
Only Chinese Language [docs](https://pyecharts.org/#/zh-cn/)seem updated (not up to date though!). English version doc is way behind. It will be great if someone can take it up by raising a PR

**Comment by sunhailin-Leo** [comment]
@sudheer82 @GregorySwart I will be fixed it ASAP

**Comment by stevearama11** [comment]
agree.  looking forward to updated docs.  thanks for pyecharts

**Comment by sunhailin-Leo** [comment]
@GregorySwart @sudheer82 @stevearama11 
* I will update the document when `pyecharts` 2.0 is publish. 
* https://github.com/pyecharts/website/commit/1b2f72f27f2c456e0150415f368c4bcf71a1b3b1
