### ISSUE TITLE
这种echarts图可以用pyecharts实现吗？

### ISSUE THREAD

**Issue by adxrgh** [pyecharts/pyecharts#2066]
**问题**
https://echarts.apache.org/examples/en/editor.html?c=treemap-visual&lang=js

如链接所示

**Comment by adxrgh** [comment]
找了一圈，没有发现可以单独配置颜色作为单独变量的设置，有没有那位好心人解释一下？

**Comment by sunhailin-Leo** [comment]
@adxrgh 
* 有 TreeItem 可以对数据进行单独配置哈
