### ISSUE TITLE
增加地图底图选项

### ISSUE THREAD

**Issue by wybert** [pyecharts/pyecharts#2068]
可不可以增加添加瓦片地图的选项，比如 [leaflet](https://github.com/gnijuohz/echarts-leaflet)，另外还有自定义瓦片如天地图

**Comment by sunhailin-Leo** [comment]
@wybert 
* 这个得需要 Echarts 支持哈

**Comment by wybert** [comment]
@sunhailin-Leo I opened an issue on Eharts side, see [here](https://github.com/apache/echarts/issues/18321)
