### ISSUE TITLE
Value 的string如何换行？

### ISSUE THREAD

**Issue by qingguee** [pyecharts/pyecharts#2073]
**问题**
我用的是 [GraphNode](https://pyecharts.org/#/zh-cn/basic_charts?id=graphnode%ef%bc%9a%e5%85%b3%e7%b3%bb%e5%9b%be%e7%9a%84%e8%8a%82%e7%82%b9%e6%95%b0%e6%8d%ae%e9%a1%b9)
    node= {
                "name": svc,
                "symbolSize": gs_symb_size,
                "value": ["""zzzz \n <br/> xxxx"""]
    }
    nodes.append(node)

在鼠标移动到node上，value不会换行。

    # 数据项值。
    value: Union[str, Sequence, None] = None,
这里好像只能用list 才能工作，而每次只会显示第一个iterm
请大神救救。我就是打算鼠标移动到node上面后，value可以显示 一些kpi 数据，这不能换行太难了。
**运行环境（系统环境及 pyecharts 版本）**
$ pip show pyecharts
Name: pyecharts
Version: 1.9.1
Summary: Python options, make charting easier
Home-page: https://github.com/pyecharts/pyecharts

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@qingguee 
![image](https://user-images.githubusercontent.com/17564655/209117939-15e4ac9b-871b-41b2-b570-4d58f485053c.png)
```python
nodes = [
    opts.GraphNode(name="结点1", symbol_size=10, value=["aaa", "bbb"]),
    opts.GraphNode(name="结点2", symbol_size=20),
    opts.GraphNode(name="结点3", symbol_size=30),
    opts.GraphNode(name="结点4", symbol_size=40),
    opts.GraphNode(name="结点5", symbol_size=50),
]
links = [
    opts.GraphLink(source="结点1", target="结点2"),
    opts.GraphLink(source="结点2", target="结点3"),
    opts.GraphLink(source="结点3", target="结点4"),
    opts.GraphLink(source="结点4", target="结点5"),
    opts.GraphLink(source="结点5", target="结点1"),
]
c = (
    Graph()
    .add("", nodes, links, repulsion=4000)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Graph-GraphNode-GraphLink"),
        tooltip_opts=opts.TooltipOpts(formatter=JsCode("""
        function(params) {
            if (params.data.value != null) {
                return params.name + '-->' + params.data.value[0] + '<br/>' + params.data.value[1];
            } else {
                return params.name;
            }
        }
        """)),
    )
)
```
