### ISSUE TITLE
Geo不能在世界地图画线

### ISSUE THREAD

**Issue by chongwar** [pyecharts/pyecharts#2074]
**问题**
使用Geo不能绘制出线，maptype为“china”正常，改为‘world’后无法绘制
**运行环境（系统环境及 pyecharts 版本）**
windows 10
pyecharts=1.9.1
python=3.8
**代码及截图**
world = (
        Geo()
        .add_schema(maptype="world")
        .add("test",
             [("China", "Canada"),],
             type_=ChartType.LINES,
             effect_opts=opts.EffectOpts(
                 symbol=SymbolType.ARROW, symbol_size=6, color="blue"
             ),
             linestyle_opts=opts.LineStyleOpts(curve=0.2),
             )
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(), title_opts=opts.TitleOpts(title="世界地图")
        )
        .render("index_world.html")
    )
网页为空白

**Comment by DaiDai-Dad** [comment]
#2064 你的问题解决了吗？我的和你的正相反

**Comment by donkeyEEE** [comment]
我也发现了同样的问题
