### ISSUE TITLE
世界地图相关问题

### ISSUE THREAD

**Issue by Billy-102** [pyecharts/pyecharts#2082]
**问题**
请问世界地图有没有以中国为中心的版本？（目前看好像只有以欧洲为中心的版本）

**运行环境（系统环境及 pyecharts 版本）**
系统环境：Windows11
pyecharts版本：1.9.1

**代码及截图**
此问题不需要截图

**Comment by sunhailin-Leo** [comment]
@Billy-102 
* 目前暂时没有哈
