### ISSUE TITLE
MapGlobe 渲染时无法呈现3D

### ISSUE THREAD

**Issue by lisisiejid** [pyecharts/pyecharts#2083]
作者你好，我在使用flask的render_embed进行渲染的时候，原本的全球3D地图变成平面图
![image](https://user-images.githubusercontent.com/48905666/201956532-45bab4ca-fd45-4fb2-9133-bb161d1ba106.png)

单独生成html文件则正常

代码如下：
app.py
@app.route('/index')
def hello_world():
    earthmapcharts = earth3D.get3Dearth()
    return Markup(earthmapcharts.render_embed())

earth3D.py
`
import pyecharts.options as opts
from pyecharts.charts import MapGlobe
from pyecharts.faker import POPULATION

def get3Dearth():
    data = [x for _, x in POPULATION[1:]]
    low, high = min(data), max(data)
    c = (
        MapGlobe()
        .add_schema()
        .add(
            maptype="world",
            series_name="World Population",
            data_pair=POPULATION[1:],
            is_map_symbol_show=False,
            label_opts=opts.LabelOpts(is_show=True),
        )
        .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(
                background_color='#1b1f23',
                min_=low,
                max_=high,
                range_text=["max", "min"],
                is_calculable=True,
                range_color=['#2894FF', '#0072E3', '#005AB5','#0000E3'],
            )
        )
    )
    return c

**Comment by sunhailin-Leo** [comment]
@lisisiejid 
* 看下是不是你 flask 的页面少引用了 js 资源
