### ISSUE TITLE
在pycharm中创建ipynb使用pyecharts render_notebook()无法显示图片

### ISSUE THREAD

**Issue by MJ-Heree** [pyecharts/pyecharts#2086]
**问题**
在pycharm中创建ipynb使用pyecharts render_notebook()无法显示图片

**运行环境（系统环境及 pyecharts 版本）py3.8 pyecharts1.7

**代码及截图**
# 只需要在顶部声明 CurrentConfig.ONLINE_HOST 即可
from pyecharts.globals import CurrentConfig, OnlineHostType

# OnlineHostType.NOTEBOOK_HOST 默认值为 http://localhost:8888/nbextensions/assets/
CurrentConfig.ONLINE_HOST = OnlineHostType.NOTEBOOK_HOST
from pyecharts.charts import Bar
bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
# render 会生成本地 HTML 文件，默认会在当前目录生成 render.html 文件
# 也可以传入路径参数，如 bar.render("mycharts.html")
bar.render_notebook()

![36664acbcf1d968fb418d9c0ccd2d98](https://user-images.githubusercontent.com/78643386/202367696-3425d70b-e0bd-4dd7-b1c0-54735155f727.png)

**Comment by sunhailin-Leo** [comment]
> 你好~ 我照着你的建议做了一遍，pycharm中还是不显示欸，之后我去看了一下NOTEBOOK_HOST，显示404 : Not Found 请问是不是跟这个有关系呀？

* 确认你的 NOTEBOOK_HOST 可以正常访问即可

**Comment by HonestKevin** [comment]
![image](https://github.com/pyecharts/pyecharts/assets/17979874/b5300bea-f58e-471a-9356-7082bd2da4f4)
运行完成后 依然输出内容是纯黑，无内容
