### ISSUE TITLE
1.9.1版本的 tab 多图是否能放到page中

### ISSUE THREAD

**Issue by linghao830** [pyecharts/pyecharts#2087]
AttributeError: 'Tab' object has no attribute 'chart_id'，当把tab 放到page时就报这个错误，应该怎么处理

**代码及截图**

![bc94ed5c36a0543d8c9d82bca4a379c](https://user-images.githubusercontent.com/83353887/202635512-f1e47c06-4c0c-4c8d-9fd0-8f382342b0d3.jpg)

**Comment by sunhailin-Leo** [comment]
@linghao830 现在暂时不支持，后续在 2.0 中会考虑添加
