### ISSUE TITLE
通过page把四张图片放在一个html里，并且调整了四张图在html的布局，这个html可以保存为一张图片吗？

### ISSUE THREAD

**Issue by jiangcute** [pyecharts/pyecharts#2088]
文档中和以前的issue，都没有发现这个case
是当前最新的pyechart版本，windows运行环境

我用的是pyechart,目前是只能一张一张的分别保存为图片，四张合在一起的html无法保存为一张图片，现在的需求是能把四张图片布局在一起，作为一张图片保存下来

**Comment by sunhailin-Leo** [comment]
@jiangcute 
* 除了 snapshot 之外没有特别的好的办法，除非 Echarts 有插件支持

**Comment by douloveppt** [comment]
老哥你怎么解决的，我现在也遇到这个问题了
