### ISSUE TITLE
请问下多个子图之间如何可以联动，共同缩放横轴(X轴)

### ISSUE THREAD

**Issue by YJCITA** [pyecharts/pyecharts#2089]
**问题**
请问下多个子图之间如何可以联动，共同缩放横轴
如下如代码，通过page添加多个charts，如何能让多个同共同缩放X轴

**运行环境（系统环境及 pyecharts 版本）**
ubuntu 2004
pyecharts 1.7.0

**代码及截图**

for key, sub_axis in axis.items():
      if len(sub_axis[0]):
          line = self.build_line(
              key, sub_axis[0], sub_axis[1], key, '')
          charts.append(line)

  page = Page(layout=Page.SimplePageLayout).add(*charts)
  page.render(filename)

![image](https://user-images.githubusercontent.com/12579690/203092242-19e1b20e-64f1-45e4-9560-9216a2aa10b6.png)

**Comment by sunhailin-Leo** [comment]
@YJCITA 
* 只能用 Grid 去联动。Page 是放多个图的，多个图在 HTML 里面是独立的，而 Grid 不是。

**Comment by YJCITA** [comment]
> @YJCITA
> 
> * 只能用 Grid 去联动。Page 是放多个图的，多个图在 HTML 里面是独立的，而 Grid 不是。

非常感谢 我试试
