### ISSUE TITLE
相关echarts项目推荐

### ISSUE THREAD

**Issue by WheatMaThink** [pyecharts/pyecharts#2090]
https://github.com/epi2me-labs/ezcharts

各位胸台：搜索到一个Echarts相关项目，感觉不错。
大家可以看看上述网址，此项目的实现方法比较贴近echarts直接实现，也不会有版本更新等问题，不过是一个初期项目相对API等没有那么规范。（一个自动生成的类_model.py有13M多，稍微修改去掉注释到4M多）

为pyecharts改进提供一些思路。

**Comment by sunhailin-Leo** [comment]
@WheatMaThink 
* Echarts 版本更新很多时候影响的都是 api 参数。所以你提到的这个项目也一样会有版本更新的问题。

**Comment by WheatMaThink** [comment]
@sunhailin-Leo 

看上面那个项目通过generate-model.py语句直接生成 option 的json-schema，即可以很快的更新版本。
