### ISSUE TITLE
雷达图左侧的空白区域很大，怎么才能让图形左移动一些，让左侧空白减少呢

### ISSUE THREAD

**Issue by nankaimy** [pyecharts/pyecharts#2091]
import random
from pyecharts import options as opts
from pyecharts.charts import Page, Radar
def radar_simple() -> Radar:
    c = (
        Radar()
        .add_schema(
            # 各项的max_值可以不同
            schema=[
                opts.RadarIndicatorItem(name='计算几何学', max_=100),
                opts.RadarIndicatorItem(name='动态规划', max_=100),
                opts.RadarIndicatorItem(name='图论', max_=100),
                opts.RadarIndicatorItem(name='搜索', max_=100),
                opts.RadarIndicatorItem(name='模拟', max_=100),
                opts.RadarIndicatorItem(name='数论', max_=100),
            ]
        )
        .add('旺神', [[random.randint(10, 101) for _ in range(6)]],           
             color='red',           
             areastyle_opts = opts.AreaStyleOpts(  #设置填充的属性
                 opacity = 0.5,                  
                 color='red'                     
         ),)
        .add('蔡队', [[random.randint(10, 101) for _ in range(6)]],
             color='blue',
             areastyle_opts = opts.AreaStyleOpts(
                 opacity = 0.5,#透明度
                 color='blue'
         ),)
        .set_series_opts(label_opts=opts.LabelOpts(is_show=True))
        .set_global_opts(title_opts=opts.TitleOpts(title='雷达图示例-ACM集训队队员能力'))
    )
    return c
radar_simple().render('雷达图.html')

雷达图左侧的空白区域很大，怎么才能让图形左移动一些，让左侧空白减少呢

散点图左侧的空白就小很多

**Comment by sunhailin-Leo** [comment]
@nankaimy 
* add_schema 里面有一个 center 参数
* https://pyecharts.org/#/zh-cn/basic_charts?id=radar%ef%bc%9a%e9%9b%b7%e8%be%be%e5%9b%be
