### ISSUE TITLE
page 问题

### ISSUE THREAD

**Issue by steveyangbab** [pyecharts/pyecharts#2093]
为什么page里面移动图完了，save config点击不能正常下载JSON文件，点击没有响应，看了html返回的问题说是IFRAME沙河问题，找了很多地方还是没有找到，找到问题点都有解决

**Comment by sunhailin-Leo** [comment]
> 为什么page里面移动图完了，save config点击不能正常下载JSON文件，点击没有响应，看了html返回的问题说是IFRAME沙河问题，找了很多地方还是没有找到，找到问题点都有解决

* 能提供下浏览器控制台的错误信息吗？文字描述复现。
