### ISSUE TITLE
Make available on conda-forge

### ISSUE THREAD

**Issue by maximlt** [pyecharts/pyecharts#2096]
Hi all, thanks for this great library and sorry for writing in English (I hope it's fine).

I'd be nice to have `pyecharts` available on conda-forge. Adding what is called a *recipe* to conda-forge is [pretty well documented](https://conda-forge.org/#add_recipe). That would ultimately make `pyecharts` directly available to conda users.

**Comment by sunhailin-Leo** [comment]
@maximlt 
* For now, I think you can use `pip install` in `conda` environment. 
* I don't know much about `conda-forge`, and I don't know the difference between it and `Anaconda`.
* By the way, I will take a look for `conda-forge`, but probably not so soon.

**Comment by maximlt** [comment]
> I don't know much about conda-forge, and I don't know the difference between it and Anaconda.

The difference is quite big. Anaconda is a company, it created the tool `conda` to manage environments and dependencies. `conda` can install packages from *channels*. Anaconda maintains a channel called *default*. The community of `conda` users, i.e. in bulk that's the scientific/datascience Python community as `conda` is making installing their packages much easier compared to `pip`, has developed its own community-managed channel called *conda-forge*. While Anaconda controls what is on the *default* channel, it doesn't control what is on *conda-forge* and you as a maintainer of a Python library can decide to submit your project to *conda-forge*.

**Comment by FHU-yezi** [comment]
For short, once we updated our library to conda-force, user can run `conda install pynecone-io` to download it.

**Comment by sunhailin-Leo** [comment]
@maximlt @FHU-yezi 
* Thx, I will take a look for `conda-forge`.

**Comment by wybert** [comment]
I would suggest using [grayskull](https://github.com/conda/grayskull) to generate the conda-forge recipe quickly.

**Comment by sunhailin-Leo** [comment]
Waiting for pull requests [pull-requests#23709](https://github.com/conda-forge/staged-recipes/pull/23709)
