### ISSUE TITLE
图形x轴坐标数据显示问题，只能显示到20220509，后面的不再显示

### ISSUE THREAD

**Issue by yorklee914** [pyecharts/pyecharts#2103]
**问题**
使用pyecharts画折线图、k线图等等，碰到一个 共性问题，
x轴日期最多只显示到20220509日，后面的就不再显示，
不过数据是元不止到20220509的。
数据来自我本地的mysql数据库，里面有当前证券截至20221212日的行情数据

**运行环境（系统环境及 pyecharts 版本）**
操作系统 windows 10
python 3.8.8
pyecharts 1.9.1

**代码及截图**

截图：

![image](https://user-images.githubusercontent.com/121247559/209176754-2743bf2b-b39f-40f8-9543-19ad3460cb3f.png)

代码如下：

import sqlalchemy as sqlal
import pymysql
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
from pyecharts import options as opts
from pyecharts.globals import CurrentConfig, NotebookType
    
import requests
from typing import List, Union
from pyecharts.charts import Bar, Grid, Line

#from pyecharts import Line,configure

CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_NOTEBOOK
CurrentConfig.ONLINE_HOST='https://assets.pyecharts.org/assets/'

engine = create_engine('mysql+pymysql://root:111111@localhost:3306/python?charset=utf8')

begin_date='20210101'
end_date='20221230'
seccode='000001.SZ'

sql = '''
SELECT
        substr(t.ts_code,1,6) sec_code,
        t.open,
        t.high,
        t.low,
        t.close,
        t.vol,
        t.amount,
        t.change,
        t.pct_chg,
        trade_date

    FROM python.daily t
    WHERE 1=1
     and TRADE_DATE >= '{}'
     and TRADE_DATE <= '{}'
               and t.ts_code ='{}'
               
               AND SUBSTR(t.ts_code,1,1) IN ('0','3', '6') 
               ORDER BY sec_code, TRADE_DATE'''.format(begin_date, end_date, seccode)

close_price_df = pd.read_sql(sql, engine)
close_price_df.columns = [str(x).upper() for x in close_price_df.columns.tolist()]

close_price_df['DAT']=close_price_df['TRADE_DATE']
close_price_df.set_index('TRADE_DATE', inplace=True)
close_price_df = close_price_df.sort_values(by = 'TRADE_DATE', ascending = True)

close_price_df_x=close_price_df['DAT']
dates=list(close_price_df.index)
#close_price_df_x.values.tolist()

close_price_df_y=close_price_df['CLOSE']
datac=close_price_df_y.values.tolist()
close_price_df_o=close_price_df['OPEN']
datao=close_price_df_o.values.tolist()

close_price_df_y=close_price_df['AMOUNT']*0.0001
close_price_df_y=close_price_df_y.round(2)
dataa=close_price_df_y.values.tolist()

line = (
    Line()
    .add_xaxis(xaxis_data=dates)
    .add_yaxis("商家A", datac, is_smooth=True)
    .add_yaxis("商家B", datao, is_smooth=True)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Line-smooth"),
        xaxis_opts=opts.AxisOpts(
                type_ = 'category',  # str 坐标轴类型。可选 'value' 'category' 'time' 'log'
                name = '日期',  # str 坐标轴名称。
                interval = 30,  # 
                max_ = '20221212',  # 
                
                )
        )
    
    #.render("line_smooth.html")
)

line.render_notebook() #.render("basic_area_chart.html") #

**Comment by yorklee914** [comment]
@chenjiandongx @chfw @kinegratii @sunhailin-Leo 大佬帮忙看下

**Comment by sunhailin-Leo** [comment]
@yorklee914 
* 我这边测试没有遇到你这种情况哈
