### ISSUE TITLE
在组合导出geo和bar的时候geo不显示设置好的内容而是显示地理坐标

### ISSUE THREAD

**Issue by perfectimagine** [pyecharts/pyecharts#2105]
**问题**
在组合导出geo和bar的时候geo不显示设置好的内容而是显示地理坐标，但是单独把geo代码拿出来就可以正常运行

**运行环境（系统环境及 pyecharts 版本）**
Python3.7
pyecharts1.91

**代码及截图**

- import requests
from pyecharts.charts import Bar,Geo,Grid
from pyecharts import options as opts
#数据爬取部
url = 'https://jiaotong.baidu.com/trafficindex/city/list'
response = requests.get(url=url)
trafficindex_data = response.json()
#使用json提取有用数据
citynames = [i['cityname'] for i in trafficindex_data['data']['list']]  #提取城市名称
indexes = [float(i['index']) for i in trafficindex_data['data']['list']]  # 提取拥堵指数
speed = [i['speed'] for i in trafficindex_data['data']['list']]
#绘制柱状图
bar =(
Bar()
.add_xaxis(xaxis_data=citynames)
.add_yaxis(series_name='行驶速度',y_axis=speed)
.set_global_opts(datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_='inside')],
    title_opts=opts.TitleOpts(title='平均行驶速度',pos_left='3%',pos_top='40%',title_textstyle_opts=opts.TextStyleOpts(
        font_style='normal',font_size=12)),
                    legend_opts=opts.LegendOpts(
                            type_='scroll',
                            is_show=True,
                            pos_left='15%',
                            pos_top='40%'
                    )
                 ))
geo = (
    Geo()
    .add_schema(maptype='china')  #加入中国地图
    .add('中国各城市交通拥堵指数',[list(z) for z in zip(citynames,indexes)],type_='effectScatter')   #设置地图类型并进行数据处理
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))   #去掉省市标识
    .set_global_opts(visualmap_opts=opts.VisualMapOpts(is_piecewise=True,max_=2.5,
        pieces=[{'min':1.0,'max':1.5,'label':'畅通','color':'#16CE95'},
                {'min':1.5,'max':2.0,'label':'缓慢','color':'#F79D06'},
                {'min':2.0,'max':2.5,'label':'拥堵','color':'#D80304'}],)))
grid = (
    Grid()
    .add(bar, grid_opts=opts.GridOpts(pos_top="50%", pos_right="75%"))
    .add(geo, grid_opts=opts.GridOpts(pos_left="60%"))
    .render("中国各城市道路交通图.html"))
<img width="1280" alt="2022-12-24 (13)" src="https://user-images.githubusercontent.com/121346450/209438802-fed47917-5b8f-41ab-be50-6cc38be63db5.png">
<img width="1280" alt="2022-12-24 (14)" src="https://user-images.githubusercontent.com/121346450/209438808-4a07b558-3a7f-4b96-bd69-87b11a4a3e87.png">

**Comment by sunhailin-Leo** [comment]
@perfectimagine 
* 没太理解你问的问题。

**Comment by perfectimagine** [comment]
> 

就是说上面代码里面的geo单独拿出来运行时是下面那张图，但是把geo和bar结合起来之后就变成上面的图了，中国地图上面的显示变了

**Comment by sunhailin-Leo** [comment]
@perfectimagine 
* 那你的期望是什么？

**Comment by perfectimagine** [comment]
> 

我想要让第一张图的柱状图和第二张图结合

**Comment by sunhailin-Leo** [comment]
@perfectimagine 
* 目前好像是有点问题，我会在 2.X 修复这个问题哈～

**Comment by perfectimagine** [comment]
> @perfectimagine
> 
> * 目前好像是有点问题，我会在 2.X 修复这个问题哈～

我曹，大佬（膜拜)

**Comment by sunhailin-Leo** [comment]
![image](https://user-images.githubusercontent.com/17564655/209495662-85fd6cbb-8de7-4b39-9f2e-01aa65b22e02.png)

* dev 分支: https://github.com/pyecharts/pyecharts/pull/2104/commits/8444a997e0389b947b4ea95cb7067fe750b0ac25

**Comment by sunhailin-Leo** [comment]
@perfectimagine 
* 等 2.X 发布了这个问题就解决了～

**Comment by perfectimagine** [comment]
> ![image](https://user-images.githubusercontent.com/17564655/209495662-85fd6cbb-8de7-4b39-9f2e-01aa65b22e02.png)
> 
> * dev 分支: [8444a99](https://github.com/pyecharts/pyecharts/commit/8444a997e0389b947b4ea95cb7067fe750b0ac25)

大佬，你这图怎么弄得，能把源码给我看看不？我期末报告要交了但是我的代码弄不出来

**Comment by sunhailin-Leo** [comment]
@perfectimagine 
* 你可以看下我在 `dev` 分支刚提的代码，你可以去修改下 `grid.py`
```python
import requests
from pyecharts.charts import Bar, Geo, Grid
from pyecharts import options as opts
from pyecharts.commons.utils import JsCode

# 数据爬取部
url = "https://jiaotong.baidu.com/trafficindex/city/list"
response = requests.get(url=url)
trafficindex_data = response.json()
# 使用json提取有用数据
citynames = [i["cityname"] for i in trafficindex_data["data"]["list"]]  # 提取城市名称
indexes = [float(i["index"]) for i in trafficindex_data["data"]["list"]]  # 提取拥堵指数
speed = [i["speed"] for i in trafficindex_data["data"]["list"]]
# 绘制柱状图
bar = (
    Bar()
    .add_xaxis(xaxis_data=citynames)
    .add_yaxis(series_name="行驶速度", y_axis=speed)
    .set_global_opts(
        datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside")],
        title_opts=opts.TitleOpts(
            title="平均行驶速度",
            pos_left="3%",
            pos_top="40%",
            title_textstyle_opts=opts.TextStyleOpts(font_style="normal", font_size=12),
        ),
        legend_opts=opts.LegendOpts(
            type_="scroll", is_show=True, pos_left="15%", pos_top="40%"
        ),
    )
)
geo = (
    Geo()
    .add_schema(maptype="china")  # 加入中国地图
    .add(
        "中国各城市交通拥堵指数", [list(z) for z in zip(citynames, indexes)], type_="effectScatter"
    )  # 设置地图类型并进行数据处理
    .set_series_opts(
        label_opts=opts.LabelOpts(is_show=False),
        tooltip_opts=opts.TooltipOpts(
            is_show=True,
            formatter=JsCode("""
            function(params) {return params.data.name + ' ' + params.data.value[2];}
            """),
        ),
    )  # 去掉省市标识
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(
            is_piecewise=True,
            max_=2.5,
            pieces=[
                {"min": 1.0, "max": 1.5, "label": "畅通", "color": "#16CE95"},
                {"min": 1.5, "max": 2.0, "label": "缓慢", "color": "#F79D06"},
                {"min": 2.0, "max": 2.5, "label": "拥堵", "color": "#D80304"},
            ],
            series_index=1,
        ),
    )
)
grid = (
    Grid()
    .add(bar, grid_opts=opts.GridOpts(pos_top="50%", pos_right="75%"))
    .add(geo, grid_opts=opts.GridOpts(pos_left="60%"))
    .render()
)
```

**Comment by perfectimagine** [comment]
> @perfectimagine
> 
> * 等 2.X 发布了这个问题就解决了～

哦哦，还有柱状图也有bug，城市名称显示有时候对不上柱状图，其实如果数据太密集的话可以设定一个显示范围，比如在5个柱状图以下才显示名称，或者通过字体大小和柱状图的比例来调

**Comment by perfectimagine** [comment]
> @perfectimagine
> 
> * 你可以看下我在 `dev` 分支刚提的代码，你可以去修改下 `grid.py`
> * 然后画图的代码在下面，我稍微做了一点修改
> 
> ```python
> import requests
> from pyecharts.charts import Bar, Geo, Grid
> from pyecharts import options as opts
> from pyecharts.commons.utils import JsCode
> 
> # 数据爬取部
> url = "https://jiaotong.baidu.com/trafficindex/city/list"
> response = requests.get(url=url)
> trafficindex_data = response.json()
> # 使用json提取有用数据
> citynames = [i["cityname"] for i in trafficindex_data["data"]["list"]]  # 提取城市名称
> indexes = [float(i["index"]) for i in trafficindex_data["data"]["list"]]  # 提取拥堵指数
> speed = [i["speed"] for i in trafficindex_data["data"]["list"]]
> # 绘制柱状图
> bar = (
>     Bar()
>     .add_xaxis(xaxis_data=citynames)
>     .add_yaxis(series_name="行驶速度", y_axis=speed)
>     .set_global_opts(
>         datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside")],
>         title_opts=opts.TitleOpts(
>             title="平均行驶速度",
>             pos_left="3%",
>             pos_top="40%",
>             title_textstyle_opts=opts.TextStyleOpts(font_style="normal", font_size=12),
>         ),
>         legend_opts=opts.LegendOpts(
>             type_="scroll", is_show=True, pos_left="15%", pos_top="40%"
>         ),
>     )
> )
> geo = (
>     Geo()
>     .add_schema(maptype="china")  # 加入中国地图
>     .add(
>         "中国各城市交通拥堵指数", [list(z) for z in zip(citynames, indexes)], type_="effectScatter"
>     )  # 设置地图类型并进行数据处理
>     .set_series_opts(
>         label_opts=opts.LabelOpts(is_show=False),
>         tooltip_opts=opts.TooltipOpts(
>             is_show=True,
>             formatter=JsCode("""
>             function(params) {return params.data.name + ' ' + params.data.value[2];}
>             """),
>         ),
>     )  # 去掉省市标识
>     .set_global_opts(
>         visualmap_opts=opts.VisualMapOpts(
>             is_piecewise=True,
>             max_=2.5,
>             pieces=[
>                 {"min": 1.0, "max": 1.5, "label": "畅通", "color": "#16CE95"},
>                 {"min": 1.5, "max": 2.0, "label": "缓慢", "color": "#F79D06"},
>                 {"min": 2.0, "max": 2.5, "label": "拥堵", "color": "#D80304"},
>             ],
>             series_index=1,
>         ),
>     )
> )
> grid = (
>     Grid()
>     .add(bar, grid_opts=opts.GridOpts(pos_top="50%", pos_right="75%"))
>     .add(geo, grid_opts=opts.GridOpts(pos_left="60%"))
>     .render()
> )
> ```

谢谢大佬

**Comment by sunhailin-Leo** [comment]
> > @perfectimagine
> > 
> > * 等 2.X 发布了这个问题就解决了～
> 
> 哦哦，还有柱状图也有bug，城市名称显示有时候对不上柱状图，其实如果数据太密集的话可以设定一个显示范围，比如在5个柱状图以下才显示名称，或者通过字体大小和柱状图的比例来调

* 这个我看是因为数据太密集了，你可以调整 `Grid` 的 `InitOpts` 把画布调大一些.

**Comment by perfectimagine** [comment]
> > > @perfectimagine
> > > 
> > > * 等 2.X 发布了这个问题就解决了～
> > 
> > 
> > 哦哦，还有柱状图也有bug，城市名称显示有时候对不上柱状图，其实如果数据太密集的话可以设定一个显示范围，比如在5个柱状图以下才显示名称，或者通过字体大小和柱状图的比例来调
> 
> * 这个我看是因为数据太密集了，你可以调整 `Grid` 的 `InitOpts` 把画布调大一些.

好的，谢谢
