### ISSUE TITLE
请问pyecharts有支持event，鼠标点击事件的功能吗?

### ISSUE THREAD

**Issue by netaudio** [pyecharts/pyecharts#2108]
**问题**

请问pyecharts有支持event，鼠标点击事件的功能吗

**运行环境（系统环境及 pyecharts 版本）**
windows  python3.10  pyecharts1.9.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@netaudio 
* 目前版本有 `add_js_funcs` 函数传入自己写好的 js 函数

**Comment by netaudio** [comment]
> 

我是在qtpyside2里面使用，不是在web里面用，可以调用add_js_funcs吗？

**Comment by sunhailin-Leo** [comment]
@netaudio 
* `Echarts` 本身是 web 页面渲染的而且 `Echarts` 所有的事件都是通过 `js` 操作的。你用 QT 的控件也操作不到额

**Comment by netaudio** [comment]
我再qtpyside2里面通过QGraphicsView，可以正常显示echart，但是想获取鼠标在bar上的滑动事件，我测试add_js_funcs("alert('hello world')")，是可以弹出alert窗口的，就是不知道怎么获取bar上的mouse move事件？

**Comment by sunhailin-Leo** [comment]
@netaudio 
* https://echarts.apache.org/zh/api.html#events
* `chart.on` 的 `chart` 需要配置 `initOpts` 的 `chart_id` 自定义下，否则 `pyecharts` 默认会以 `chart_<UUID>` 的模式生成 `chart` 对象。
* 自定义完 `chart_id` 以后，`chart.on` 变成 `chart_<你自定义的 ID>.on`，剩下的操作参考 `Echarts` 的 `events` 的文档，先用 `HTML` 模式调试，最后你再放到 `QT` 里面去。

**Comment by netaudio** [comment]
@sunhailin-Leo
感谢!
