### ISSUE TITLE
PyEcharts V2.0.0 预计什么时候发布？

### ISSUE THREAD

**Issue by jindaxiang** [pyecharts/pyecharts#2109]
PyEcharts V2.0.0 预计什么时候发布？

**Comment by sunhailin-Leo** [comment]
@jindaxiang 
* 预计在元旦假期后发布

**Comment by sunhailin-Leo** [comment]
@jindaxiang 
* 关注 issue [issue#1865](https://github.com/pyecharts/pyecharts/issues/1865) 的变化
* 以及 pr [pr#2104](https://github.com/pyecharts/pyecharts/pull/2104) 的变化。合并到 `master` 后会第一时间发布到 PyPI 的
