### ISSUE TITLE
Grid可以并排画一个饼图一个折线图吗？

### ISSUE THREAD

**Issue by veridone** [pyecharts/pyecharts#2113]
代码:
from pyecharts import options as opts
from pyecharts.charts import Grid, Line
from pyecharts.faker import Faker

pie = (
    Pie()
    .add("", [list(z) for z in zip(Faker.choose(), Faker.values())])
    .set_global_opts(title_opts=opts.TitleOpts(title="Pie-基本示例"))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
)

line = (
    Line()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
)

grid = (
    Grid()
    .add(pie, grid_opts=opts.GridOpts(pos_left="55%"))
    .add(line, grid_opts=opts.GridOpts(pos_right="55%"))
)

报错：
AttributeError                            Traceback (most recent call last)
<ipython-input-111-57042ac1e6f8> in <module>
     34     Grid()
     35     .add(pie, grid_opts=opts.GridOpts(pos_left="55%"))
---> 36     .add(line, grid_opts=opts.GridOpts(pos_right="55%"))
     37 )
     38 grid.load_javascript() #加载echarts.js

~/python3.6/site-packages/pyecharts/charts/composite_charts/grid.py in add(self, chart, grid_opts, grid_index, is_control_axis_index)
     74             self.options.get("legend").extend(chart.options.get("legend"))
     75             if isinstance(chart, RectChart):
---> 76                 self.options.get("xAxis").extend(chart.options.get("xAxis"))
     77                 self.options.get("yAxis").extend(chart.options.get("yAxis"))
     78 

AttributeError: 'NoneType' object has no attribute 'extend'

**Comment by sunhailin-Leo** [comment]
@veridone 
* 试试先 `add line` 呢？

**Comment by anxingle** [comment]
> @veridone
> 
> * 试试先 `add line` 呢？

这是为什么呢？
