### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by LOLCATATONIA** [pyecharts/pyecharts#2114]
Hello... please excuse my lack of Chinese :) I hope to learn someday.

I cannot get any of the https://github.com/pyecharts/pyecharts/tree/master/pyecharts/charts/basic_charts examples to work?

These begin with

> from ... import options as opts
> from ... import types
> from ...charts.chart import Chart
> from ...globals import ChartType

and running them results in "ImportError: attempted relative import with no known parent package"

What am I doing wrong?

**Comment by sunhailin-Leo** [comment]
@LOLCATATONIA 
* https://gallery.pyecharts.org/#/Bar/bar_base

**Comment by LOLCATATONIA** [comment]
Sorry for reopening this. 

With the following code:
https://raw.githubusercontent.com/pyecharts/pyecharts/master/pyecharts/charts/basic_charts/sunburst.py

I change the imports from:

> from ... import options as opts
> from ... import types
> from ...charts.chart import Chart
> from ...globals import ChartType

to:

> from pyecharts import options as opts
> from pyecharts import types
> from pyecharts.charts.chart import Chart
> from pyecharts.globals import ChartType

This results in the following error:

> File ...\pyecharts\charts\basic_charts\calendar.py", line 1, in <module>
    from ... import options as opts
ImportError: attempted relative import with no known parent package

I am not sure why running sunburst.py results in an error with reference to calendar.py :) 

but it does.

changing the import statements in calendar.py from:

> from ... import options as opts
> from ... import types
> from ...charts.chart import Chart
> from ...globals import ChartType

to 

> from pyecharts import options as opts
> from pyecharts import types
> from pyecharts.charts.chart import Chart
> from pyecharts.globals import ChartType

rerunning sunburst.py results in error:

> ImportError: cannot import name 'BaseGraphic' from partially initialized module 'pyecharts.options.charts_options' (most likely due to a circular import) (...\Python\Python310\site-packages\pyecharts\options\charts_options.py)

What am I doing wrong?
