### ISSUE TITLE
cannot use pages inside tabs?

### ISSUE THREAD

**Issue by stevearama11** [pyecharts/pyecharts#2115]
I don't seem to be able to use pages inside tabs.
Create a function to return the page abc.

`
tab = Tab()
tab.add(abc, "abc')
tab.render('tab.html')
`
return this error - which is not returned except when using tab.
jinja2.exceptions.UndefinedError: 'pyecharts.charts.composite_charts.page.Page object' has no attribute 'width'

**Comment by sunhailin-Leo** [comment]
@stevearama11 
* `Tab` and `Page` is `pyecharts` custom components. 
* This feature is not currently available, because it will affect the style of the rendering.
