### ISSUE TITLE
pyecharts 2.0.1 导致1.9功能失效？

### ISSUE THREAD

**Issue by PeikaiLi** [pyecharts/pyecharts#2116]
**问题**
'VisualMapOpts' object has no attribute 'extend'

**运行环境（系统环境及 pyecharts 版本）**
系统环境python 3.9
pyecharts 2.0.1 报错
pyecharts 1.9 正常

**代码及截图**

<img width="883" alt="截屏2023-01-23 10 14 18" src="https://user-images.githubusercontent.com/79044615/213955326-49003fe7-db3b-4500-b4fd-048b6673e98f.png">

**Comment by sunhailin-Leo** [comment]
@PeikaiLi 
* 能提供一下尽可能完整的代码截图嘛？

**Comment by Ricardo0114** [comment]
@sunhailin-Leo 你好，我碰到了相同的问题，排查出的原因是Grid添加Heatmap

**问题**
'VisualMapOpts' object has no attribute 'extend'

**运行环境（系统环境及 pyecharts 版本）**
系统环境python 3.9
pyecharts 2.0.1 报错

**代码及截图**
![image](https://user-images.githubusercontent.com/47024990/215975285-c3c413a1-26e4-499e-b794-c7f167b19310.png)

**Comment by sunhailin-Leo** [comment]
@Ricardo0114 
* Heatmap 这个之前 1.9 可以嘛？

**Comment by Ricardo0114** [comment]
> @Ricardo0114
> 
> * Heatmap 这个之前 1.9 可以嘛？

是可以的

**Comment by sunhailin-Leo** [comment]
@PeikaiLi @Ricardo0114 
* 下一版修复哈～

**Comment by Ricardo0114** [comment]
@sunhailin-Leo 好的，辛苦了！

**Comment by PeikaiLi** [comment]
> @PeikaiLi 
> 
> * 能提供一下尽可能完整的代码截图嘛？

不好意思，刚刚看到，既然已经有人回复了，我就不贴截图了，期待解决

**Comment by bucongfan** [comment]
我碰到了相同的问题，但是我发现如果在grid中先加入一个bar或者box（我猜测是有axis的图），再加入heatmap就不会报错。但是heatmap的visualmap会错误的映射给前面的图，目前我没解决这个问题，不知道是否是轴索引的问题？

**Comment by fweiger** [comment]
在Windows 11上碰到这个问题，卸载到1.9才能使用，不知道具体啥问题。mac明天看下，好像mac没有这个问题

**Comment by Mount565** [comment]
> @PeikaiLi
> 
> * 能提供一下尽可能完整的代码截图嘛？

完整代码在这里：https://gallery.pyecharts.org/#/Candlestick/professional_kline_brush
在2.0.1版本跑一下就发现了。
这是一个严重bug, VisualMapOpts 是个dict类型，没有extend方法，要改成sequence ?
我只想学个皮毛，完成我的任务就好，谁知遇到了这个问题，害得我翻了半天源码！
