### ISSUE TITLE
legend icon color doesn't change with add_yaxis argument

### ISSUE THREAD

**Issue by stevearama11** [pyecharts/pyecharts#2117]
hello.

`
    line = (
        Line(init_opts=opts.InitOpts(width=CHART_WIDTH, height=CHART_HEIGHT, renderer='svg'))
        .add_xaxis(xaxis)
        .add_yaxis(str(YEARS[6]), year6, is_symbol_show=False, linestyle_opts=opts.LineStyleOpts(type_='dashed', width=2, color='green'))
        .add_yaxis(str(YEARS[5]), year5, is_symbol_show=False, linestyle_opts=opts.LineStyleOpts(width=2))
        .add_yaxis(str(YEARS[4]), year4, is_symbol_show=False)
        .add_yaxis(str(YEARS[3]), year3, is_symbol_show=False)
        .add_yaxis(str(YEARS[2]), year2, is_symbol_show=False)
        .add_yaxis(str(YEARS[1]), year1, is_symbol_show=False)
        .add_yaxis(str(YEARS[0]), year0, is_symbol_show=False)

`
legend_opts=opts.LegendOpts(pos_bottom='5%', legend_icon='circle'),  

the first yaxis is changing the color to green, but the legend doesn't change.

**Comment by sunhailin-Leo** [comment]
@stevearama11 
* At version 2.0.1 it work.
![image](https://user-images.githubusercontent.com/17564655/219993295-81352569-3bd8-48df-8862-68785498fbdb.png)
<img width="898" alt="image" src="https://user-images.githubusercontent.com/17564655/219993335-5590bcf3-78b7-47d8-9fd1-805f7d141998.png">
