### ISSUE TITLE
bar overlap 横坐标无效：不是按坐标值 对齐，而是按长度

### ISSUE THREAD

**Issue by algoqt** [pyecharts/pyecharts#2119]
几个图overlap的时候，如果横坐标 长度不一样，则
bar overlap 横坐标无效：不是按坐标值 对齐，而是按长度
line overlap 就没问题

`from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB
   
from pyecharts import options as opts
from pyecharts.charts import Bar, Line
from pyecharts.faker import Faker

v1 = [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3]
v2 = [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
v3 = [2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]

bar = (
    Bar()
    .add_xaxis(Faker.months)
    .add_yaxis("蒸发量", v1)
    .extend_axis(
        yaxis=opts.AxisOpts(
            axislabel_opts=opts.LabelOpts(formatter="{value} °C"), interval=5
        )
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Overlap-bar+line"),
        yaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(formatter="{value} ml")),
    )
)

print("蒸发量2:",Faker.months[10:],v2[10:])
bar2 = Bar().add_xaxis(Faker.months[10:]).add_yaxis("蒸发量2", v2[10:])
line = Line().add_xaxis(Faker.months[10:]).add_yaxis("平均温度", v3[10:], yaxis_index=1)

bar.overlap(bar2)  # bar 11月、12月位置不对
\# bar3 = Bar().add_xaxis(Faker.months).add_yaxis("蒸发量3", [None for x in v2[0:10]] + v2[10:])
\# bar.overlap(bar3)

bar.overlap(line)   # line 11月、12月位置ok
bar.load_javascript()
bar.render_notebook()`
![image](https://user-images.githubusercontent.com/93410715/215657973-1e0580f8-c7bf-4ed9-8aa7-1f1236017abd.png)

**Comment by sunhailin-Leo** [comment]
@algoqt 
* 柱状图没有数据的部分，可以通过空值去填充哈。
