### ISSUE TITLE
多个不同长度的 x 轴如何放到一张 Line() 内?

### ISSUE THREAD

**Issue by MochiXu** [pyecharts/pyecharts#2122]
参考 [issue](https://github.com/pyecharts/pyecharts/issues/1702)
这个 issue 被关闭了，但问题没解决

**Comment by sunhailin-Leo** [comment]
@MochiXu 
* 这种意思？
![image](https://user-images.githubusercontent.com/17564655/216294987-8300b2b3-d7af-4315-b2d0-f374cb05d0a5.png)

**Comment by sunhailin-Leo** [comment]
@MochiXu 
* 首先，把多个 X 轴长度中，最小端和最大端确定下来。
* 其次，在 Y 轴数据对应的时候，让对应 Y 轴没有值的部分设置为 `None （Python），Js 是 null`
