### ISSUE TITLE
grid在组合scatter3D时总是居中，而不是并列

### ISSUE THREAD

**Issue by bucongfan** [pyecharts/pyecharts#2123]
**问题**
我在使用grid组合scatter和pie图的时候发现合并后不会显示。
pie图我已经知道可以通过center=[]来调整位置，使之居左或右。
请问scatter3D有没有对应的参数

**运行环境（系统环境及 pyecharts 版本）**
2.0.1

**代码及截图**
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/51685446/216801569-60ca8e7b-d86a-4e74-b384-84e3d731e758.png">

**Comment by bucongfan** [comment]
我发现Grid3DOpts里有参数能够调节位置，但是调节后貌似还是无法组合。

**Comment by sunhailin-Leo** [comment]
@bucongfan 
* Grid 现在没有对 3D 做适配哈。。后面可以考虑增加下。

**Comment by sunhailin-Leo** [comment]
@bucongfan 
* 这块目前只能等 Echarts 那边给 3D 图加 center 参数才有可能实现哈。。目前是没有办法的。

**Comment by bucongfan** [comment]
好吧，thanks
