### ISSUE TITLE
折线图y轴类目轴x轴数值轴，ToolBox的数据图表内没法显示全部数据

### ISSUE THREAD

**Issue by pshta0** [pyecharts/pyecharts#2126]
**问题**

我把折线图的y轴设成类目轴x轴设成数值轴，ToolBox的数据视图
内没法显示全部数据，看起来是把y轴当成了x轴，然后每个类目只能对应一个x的坐标 ，最终只能得到和类目数相同数量的数据，但期望是获得所有数据
html文件：后缀改成了txt
[23_02_10___15_23_05_render.txt](https://github.com/pyecharts/pyecharts/files/10704693/23_02_10___15_23_05_render.txt)

**运行环境（系统环境及 pyecharts 版本）**
Python3.7.4
pyecharts 2.0.1

**代码及截图**

       if explain_dic:
            yaxis_type = 'category'
            scale_flag = False        
            for msd in toolConfig.ALL_SIGNAL[signal_index][1:]:
                try:
                    y_value = explain_dic[str(msd['value'])]
                    y_value_list.append(y_value)
                    signal_len = len(y_value)
                    max_signal_len = max(max_signal_len,signal_len)
                except:
                    y_value_list.append(float(msd['value']))      
            marklineOpts=False
            formatterOpts = "{c}"
            fontSize = 20 - int(max_signal_len*0.5) if 20 - int(max_signal_len*0.4)>10 else 10
            magin = 0
        else:
            yaxis_type = 'value' 
            scale_flag = True
            for msd in toolConfig.ALL_SIGNAL[signal_index][1:]:
                y_value_list.append(float(msd['value']))
            marklineOpts=opts.MarkLineOpts(
                            data=[opts.MarkLineItem(
                            type_="average", name="Average")]
                        )
            formatterOpts = "{c}"
            fontSize = 20
            magin = 5

        c = (
            Line()
            .add_xaxis(xaxis_data=x_value_list)
            .add_yaxis(series_name=toolConfig.ALL_SIGNAL[signal_index][0],
                       y_axis=y_value_list,
                       is_step=True,
                       markpoint_opts=opts.MarkPointOpts(
                                            data=[
                                                opts.MarkPointItem(type_="max", name="Max"),
                                                opts.MarkPointItem(type_="min", name="Min"),
                                            ]
                        ),
                        markline_opts=marklineOpts ,
                        label_opts=opts.LabelOpts(is_show=False,position='insideRight',rotate=20),
                        
                        
            )
            .set_global_opts(title_opts=opts.TitleOpts(title=toolConfig.ALL_SIGNAL[signal_index][0]),
                             toolbox_opts=opts.ToolboxOpts(
                                 is_show=True),  
                             xaxis_opts=opts.AxisOpts(
                                 type_='value', is_scale=True,min_interval=1,name=xaxis_name,name_location='end'),
                             yaxis_opts=opts.AxisOpts(
                                 type_=yaxis_type, is_scale=scale_flag,min_interval=1,boundary_gap=False,
                                 axistick_opts=opts.AxisTickOpts(is_show= True,is_inside=True),
                                 axislabel_opts=opts.LabelOpts(is_show=True,position='insideRight',
                                                                rotate=0,font_size=fontSize,margin=magin,font_weight='bolder'
                                 )
                             ),
                             tooltip_opts=opts.TooltipOpts(
                                 is_show=True, trigger="item", formatter=formatterOpts),
                             datazoom_opts=[opts.DataZoomOpts(is_realtime=True,
                                                              is_show=True,
                                                              range_start=0,
                                                              range_end=100)]
            )
        )
        
        return c

**Comment by sunhailin-Leo** [comment]
@pshta0 
* 能用截图说明一下吗？

**Comment by pshta0** [comment]
![图片](https://user-images.githubusercontent.com/122964169/219989764-ca617204-2da6-4537-94d7-65682b1ba5e7.png)
![图片](https://user-images.githubusercontent.com/122964169/219989799-3f4ebe09-cac2-47c9-8cea-f5b36393600c.png)

如图，数据视图中只显示了y轴每个类目的首个横坐标 @sunhailin-Leo

**Comment by sunhailin-Leo** [comment]
@pshta0 
* 你的数据是连续的嘛？

**Comment by pshta0** [comment]
是离散的，比如timestamp 940.5 ,940.61,940.723 @sunhailin-Leo
