### ISSUE TITLE
TooltipOpts：提示框配置项 是否能进行 rich 富文本编辑?

### ISSUE THREAD

**Issue by dontworrywearetogether** [pyecharts/pyecharts#2128]
**问题**
官方文档里 formatter  后没有 rich 的属性
在代码中添加了 rich 属性也会直接报错
所以 如果对这个 文本标签 格式化后 要怎么 修改其样式?

**运行环境（系统环境及 pyecharts 版本）**
win 10 
pyecharts                     1.9.1

**代码及截图**
tooltip_opts = opts.TooltipOpts(trigger="axis", trigger_on="mousemove", axis_pointer_type="cross",
                                       #formatter="{b}\n{hr|}{a1}:{c1}\n{a0}:{c0}%\n",
                                       ),
        

 如果 添加 rich 报错
TypeError: __init__() got an unexpected keyword argument 'rich'

**Comment by sunhailin-Leo** [comment]
@dontworrywearetogether 
* Echarts 的官方配置就没有 rich 🐶
