### ISSUE TITLE
[Discuss]渲染图片优化

### ISSUE THREAD

**Issue by CyberQin** [pyecharts/pyecharts#2129]
**问题**
近期阅读echarts官方手册，echarts现已推出ssr离屏渲染手段，新增了renderToSVGString方法，pyecharts是否可以以该api方式渲染图片，不再需要make_snapshot.。
 
如果renderToSVGString方法仅能在ssr配置下使用，则使用相同的数据生成ssr配置项，渲染即可。

**运行环境（系统环境及 pyecharts 版本）**

**下面是echarts官方示例代码**
https://echarts.apache.org/handbook/zh/how-to/cross-platform/server

```javascript
const echarts = require('echarts');
// 在 SSR 模式下第一个参数不需要再传入 DOM 对象
const chart = echarts.init(null, null, {
  renderer: 'svg', // 必须使用 SVG 模式
  ssr: true, // 开启 SSR
  width: 400, // 需要指明高和宽
  height: 300
});

// 像正常使用一样 setOption
chart.setOption({
  //...
});

// 输出字符串
const svgStr = chart.renderToSVGString();
```

**Comment by sunhailin-Leo** [comment]
@HQDragon 
* 这块主要是 Echarts 给 Js 生态的后端使用的。

**Comment by HQDragon** [comment]
昨天拜读了一下源码，renderEngine，pyecharts和js互操作那一块还没读明白。
echarts这个函数我在自己团队的项目试了一下，前端这边把封装成js函数就可以运行。
我原本设想是不修改既有的render代码，只是新增一个函数，把option复制一遍并修改成ssr模式，然后通过pyecharts跟js互操作得到返回的字符串，再由python生成一张图片。这样在render_notebook和save_as_image就是两个独立的函数了。

**Comment by sunhailin-Leo** [comment]
@HQDragon 
* 第一，`renderEngine`: `pyecharts `的渲染逻辑就是把 `json` 通过 `jinja2` 模版渲染成 `html` 文件或者 `python` 字符串。
* 第二：问题其实还是在于如何执行 js 函数嘛🐶。现有的 `pyecharts` 的源码不涉及任何 js 引擎的依赖，比如： `PyExecJs `。
* 要修改的话，不会在 `pyecharts` 的主代码库里进行修改。需要添加一个 snapshot 的扩展，比如：`https://github.com/pyecharts/snapshot-pyppeteer`
