### ISSUE TITLE
flask如何结合ajax with jquery无刷新更新echarts?

### ISSUE THREAD

**Issue by enalpha** [pyecharts/pyecharts#213]
你好，请问如何结合ajax实现无刷新更新数据？ 因为在制作热力图的时候发现，每次输入数据和生产charts都在不同页面，不是很直观。想知道能不能实现ajax+flask+echarts显示？

**Comment by worry45678** [comment]
可以直接参考echarts的文档
http://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0

**Comment by enalpha** [comment]
可能要花时间研究研究。Thanks.

**Comment by chfw** [comment]
我认为pyecharts 可以为ajax留一个接口
