### ISSUE TITLE
如何设置让折线图Y轴不从0值开始

### ISSUE THREAD

**Issue by xzzcx** [pyecharts/pyecharts#2135]
如何设置让折线图Y轴不从0值开始。比如Y轴范围为80-100，折线图基准线从70开始。

**Comment by sunhailin-Leo** [comment]
https://pyecharts.org/#/zh-cn/global_options?id=axisopts%ef%bc%9a%e5%9d%90%e6%a0%87%e8%bd%b4%e9%85%8d%e7%bd%ae%e9%a1%b9
