### ISSUE TITLE
lineplot display error when using floats as the X value

### ISSUE THREAD

**Issue by bucongfan** [pyecharts/pyecharts#2136]
**问题**
当X轴的数据是float类型的时候，lineplot显示错误
x=[0.05, 0.1, 0.2, 0.25, 0.3, 0.4, 0.45, 0.5, 0.55, 0.65, 0.7, 0.8, 0.85, 0.9, 1.0]
y=[1443, 416, 259, 120, 84, 86, 61, 63, 64, 97, 114, 74, 213, 366, 2505]

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
```python
x=[0.05, 0.1, 0.2, 0.25, 0.3, 0.4, 0.45, 0.5, 0.55, 0.65, 0.7, 0.8, 0.85, 0.9, 1.0]
y=[1443, 416, 259, 120, 84, 86, 61, 63, 64, 97, 114, 74, 213, 366, 2505]
lineplot = Line().add_xaxis(xaxis_data=x,)
lineplot.add_yaxis('', y_axis=y, is_smooth=True)
```
<img width="794" alt="image" src="https://user-images.githubusercontent.com/51685446/221219499-822c3487-7687-4b67-a0c1-cccddab3078a.png">

转为str后运行正常
<img width="800" alt="image" src="https://user-images.githubusercontent.com/51685446/221218903-ebf6c305-1381-4e2b-86f0-5041f44eccf9.png">

**Comment by sunhailin-Leo** [comment]
@bucongfan 
* https://pyecharts.org/#/zh-cn/global_options?id=axisopts%ef%bc%9a%e5%9d%90%e6%a0%87%e8%bd%b4%e9%85%8d%e7%bd%ae%e9%a1%b9 
* 调整 `type_` 参数
