### ISSUE TITLE
Add basemap options

### ISSUE THREAD

**Issue by wybert** [pyecharts/pyecharts#2138]
Hi. I am creating another feature request for adding a base map function to pyEcharts.

It should support any XYZ-based tile.  See [xyzservices](https://xyzservices.readthedocs.io/en/stable/) project.
See [the issue in Echarts](https://github.com/apache/echarts/issues/18321) for a woking example for Echarts.

**Comment by sunhailin-Leo** [comment]
@wybert 
* Please wait for Echarts update, then you can reopen this issue again.

**Comment by wybert** [comment]
Hi, I think [the demo](https://codepen.io/helgasoft/pen/GRGqZeR) mentioned by [helgasoft](https://github.com/helgasoft) is clear about how to implement the base map
