### ISSUE TITLE
affter dataZoom added into echart, it resports on the console of browser

### ISSUE THREAD

**Issue by TaucherLoong** [pyecharts/pyecharts#2140]
Uncaught TypeError: o[0].toFixed is not a function
    QA https://assets.pyecharts.org/assets/echarts.min.js:19
    reset https://assets.pyecharts.org/assets/echarts.min.js:19
    overallReset https://assets.pyecharts.org/assets/echarts.min.js:19
    eachTargetAxis https://assets.pyecharts.org/assets/echarts.min.js:19
    E https://assets.pyecharts.org/assets/echarts.min.js:19
    eachTargetAxis https://assets.pyecharts.org/assets/echarts.min.js:19
    jA https://assets.pyecharts.org/assets/echarts.min.js:19
    E https://assets.pyecharts.org/assets/echarts.min.js:19
    jA https://assets.pyecharts.org/assets/echarts.min.js:19
    eachTargetAxis https://assets.pyecharts.org/assets/echarts.min.js:19
    overallReset https://assets.pyecharts.org/assets/echarts.min.js:19
    E https://assets.pyecharts.org/assets/echarts.min.js:19
    eachComponent https://assets.pyecharts.org/assets/echarts.min.js:19
    overallReset https://assets.pyecharts.org/assets/echarts.min.js:19
    Fc https://assets.pyecharts.org/assets/echarts.min.js:19
    a https://assets.pyecharts.org/assets/echarts.min.js:19
    perform https://assets.pyecharts.org/assets/echarts.min.js:19
    Vc https://assets.pyecharts.org/assets/echarts.min.js:19
    E https://assets.pyecharts.org/assets/echarts.min.js:19
    Vc https://assets.pyecharts.org/assets/echarts.min.js:19
    performDataProcessorTasks https://assets.pyecharts.org/assets/echarts.min.js:19
    update https://assets.pyecharts.org/assets/echarts.min.js:19
    setOption https://assets.pyecharts.org/assets/echarts.min.js:19
    success http://192.168.50.142:8000/index/:51
    jQuery 6
    fetchData http://192.168.50.142:8000/index/:25
    <anonymous> http://192.168.50.142:8000/index/:19
    jQuery 13

**运行环境（系统环境及 pyecharts 版本）**
python 3.6.9 pyecharts 2.0.2

**代码及截图**
def line_test() -> Line:
 
    
      t_list,p_list=quote_p.get_times_points()

    
   
    
    
    top=max(p_list)
    botm=min(p_list)
    topceil=math.ceil(top*10)/10
    botmfloor=math.floor(botm*10)/10
    # jscode=JsCode(formatterCode)
    line = (
            Line()
            .add_xaxis(
            t_list,
            )
            .add_yaxis(
            series_name="实时行情",
            y_axis=p_list,
            is_smooth=False,
            label_opts=opts.LabelOpts(is_show=False),
             )
            .set_global_opts(
            title_opts=opts.TitleOpts(title="瑞德智能"),
            xaxis_opts=opts.AxisOpts(type_="value",min_=str(0*60*60),max_=str(4*60*60+1800),
                                    axislabel_opts=opts.LabelOpts(formatter=  '{value}s' )
            ),
            datazoom_opts=opts.DataZoomOpts(type_='slider'),
            yaxis_opts=opts.AxisOpts(type_="value",min_=str(botmfloor),max_=str(topceil))
           
        )
            .dump_options_with_quotes()
    )
    print(line)
    return line

**Comment by sunhailin-Leo** [comment]
@TaucherLoong 
* 麻烦格式化一下代码...

**Comment by TaucherLoong** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Awesome-pyecharts</title>
    <script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>

</head>
<body>
    <div id="line_rect" style="width:1600px; height:800px;"></div>
    <script>
        var chart = echarts.init(document.getElementById('line_rect'), 'white', {renderer: 'canvas'});
        var old_data = [];
        var globalhour=0;
        var options=null;
        $(
            function () {
                fetchData(chart);
                setInterval(getDynamicData, 20000);
            }
        );

        function fetchData() {
            $.ajax({
                type: "GET",
                url: "http://192.168.50.142:8000/line",
                dataType: "json",
                success: function (result) {
                    
                    var nineoclock=9*60*60;
                    var halfhour=1800
                    var hour=0;
                    var minute=0;
                    var second=0;
                    options = result.data;
                    console.log(options)
                    options.xAxis[0].axisLabel.formatter=function(value){
                        tseconds=nineoclock+value+halfhour;
                        if(tseconds>=11*60*60+1800)
                            tseconds+=60*60+1800;
                        hour=parseInt(tseconds/(60*60));
                        leftseconds=tseconds%3600;
                        minute=parseInt(leftseconds/60);
                        leftseconds=leftseconds%60;
                        second=leftseconds;
                        
                        return hour.toString()+":"+minute.toString()+":"+second.toString();
                    }
                    options.series[0].symbolSize=2;
                    chart.setOption(options);
                    old_data = chart.getOption().series[0].data;
                }
            });
        }

        function getDynamicData() {
            $.ajax({
                type: "GET",
                url: "http://192.168.50.142:8000/lineUpdate",
                dataType: 'json',
                success: function (result) {
                    var opt_data= result.data;
                    console.log(opt_data.scale);
                    console.log(opt_data.value);
                    if (opt_data.value != 0)
                        old_data.push([opt_data.scale, opt_data.value]);
                    yceil=opt_data.ymax;
                    yfloor=opt_data.ymin;
                    if (options==null)
                        options =chart.getOption();
                    options.yAxis.min=yfloor;
                    options.yAxis.max=yceil;
                    options.series[0].data=old_data;
                    options.series[0].symbolSize=2;
                    // console.log(old_data)
                    chart.setOption(options
                        // yAxis:[{
                            // type:'value',
                            // min: yfloor,
                            // max: yceil,
                            // }],
                        // series: [{
                            // data: old_data
                        // }]
                    );
                    console.log(old_data);
                }
            });
        }

    </script>
</body>
</html>

**Comment by TaucherLoong** [comment]
另外，ajax动态更新，在xAxis.type_='category'时，不更新，refresh 后才有改变

**Comment by sunhailin-Leo** [comment]
@TaucherLoong 
* 报错的信息跟画图的代码没啥关系吧？堆栈打的是你的 js 函数的问题。

**Comment by sunhailin-Leo** [comment]
@TaucherLoong 
* ajax 的那个试试 `chart.setOption(options, true)`
