### ISSUE TITLE
使用MarkLineItem添加参考线的问题

### ISSUE THREAD

**Issue by pshta0** [pyecharts/pyecharts#2148]
**问题**
我正在完成一个功能，往线图添加x轴及y轴上的参考线。
遇到的问题：
1、查看文档，我似乎应该写入参数例如ycoord=15来往y=15上添加水平参考线，但实际上这么做会遇到报错，而y=15可以生效。
![image](https://user-images.githubusercontent.com/122964169/226508485-797e166c-7723-45cd-ad0a-59f3149fdc86.png)

2、当我写入name参数时，我的线图里并没有体现标注name的信息
![image](https://user-images.githubusercontent.com/122964169/226508536-87026e87-851e-4d33-8bc6-a5d24af76e6f.png)
![image](https://user-images.githubusercontent.com/122964169/226508688-cdb3c191-79a8-48fb-babc-42f3d6249593.png)

3、当我想往x轴添加竖直的参考线，在xaxis里面使用markline_opts时找不到该参数，尝试在yaxis添加时也并没有生效。在文档中没有找到相关参考或者例子，请问需要怎么做？
![image](https://user-images.githubusercontent.com/122964169/226509227-56869766-6786-4e0b-827b-1e90a2b5d2b5.png)

**运行环境（系统环境及 pyecharts 版本）**
Windows Python3.74 32bits + pyecharts 2.0.2

**代码及截图**
![image](https://user-images.githubusercontent.com/122964169/226508223-0ff0d1ca-e129-4e9d-9bf4-201509de3f16.png)

**Comment by sunhailin-Leo** [comment]
@pshta0 
* x 轴只能是 `value` 或者 `time` 类型的，`category` 目前 Echarts 还没兼容
* `.set_series_opts(markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(x=1)]))`

**Comment by sunhailin-Leo** [comment]
@pshta0 
* 如果没有其他问题，我就关闭 issue 了；有原问题再 reopen，如果是新的，请另开一个。
