### ISSUE TITLE
Table 组件在深色背景下会很丑陋，偶数行如果能改成类似灰度半透明覆盖的方式就好了

### ISSUE THREAD

**Issue by ganx1028** [pyecharts/pyecharts#2149]
**问题**
Table 组件在深色背景下会很丑陋，目前使用的灰色块，偶数行如果能改成类似灰度半透明覆盖的方式就好了

**运行环境（系统环境及 pyecharts 版本）**
visual studio code + jupyter notebook, python 3.8.10, pyecharts 2.02

**代码及截图**

![image](https://user-images.githubusercontent.com/125536701/227092311-1e687418-4669-457a-9304-a569a2d5cad0.png)

**Comment by sunhailin-Leo** [comment]
@ganx1028 
* Table 组件的默认配色不会随系统的配色而改变（未来也不会新增这个 feature）。
* Table 组件提供了基本的 `css` 样式的配置设置参数。（如果觉得看的丑的话，请自行设置，或者用前后端分离的方式去让前端实现 table 的展示）。

**Comment by ganx1028** [comment]
Table 并不需要随系统配色改变，只需要将css样式改为半透明即可
比如我的这个方案
```
.fl-table tr:hover td {
    background: #00d1b240;
    color: inherit;
}
```
```
.fl-table tr:nth-child(even) {
    background: #c0c0c020;
}
```
这样个人感觉似乎就能比官方的效果好看一点
![dark无选中](https://user-images.githubusercontent.com/125536701/227122401-3b51c739-5fa8-47f4-9e97-2f4c0de67b6b.png)
![dark选中](https://user-images.githubusercontent.com/125536701/227122436-02aa57cb-637d-4ce6-9c70-6b6f13982c57.png)
![light无选中](https://user-images.githubusercontent.com/125536701/227122547-f14ec25c-f007-454d-bd58-54f56fb22ea6.png)
![light选中](https://user-images.githubusercontent.com/125536701/227122728-348a990c-96a3-4b9c-9e33-7b136ef17c1d.png)
