### ISSUE TITLE
Table 组件是否可以支持非header行的字体加粗?

### ISSUE THREAD

**Issue by zygcch** [pyecharts/pyecharts#2150]
**问题**
Table 组件是否可以支持非header行的字体加粗?

**运行环境（系统环境及 pyecharts 版本）**

pyecharts 1.5

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@zygcch 
* 暂时没有这个考虑哈。`Table` 组件只是 `pyecharts` 提供的一个 Demo 组件，并不是核心。
* 因此展示表格的工作应该交由更专业的前端去实现哈～
