### ISSUE TITLE
关于使用Grid同时渲染Geo和Map时，报错、无图像的问题。

### ISSUE THREAD

**Issue by TTSArrows** [pyecharts/pyecharts#2153]
**问题**
使用Grid同时渲染Geo和Map时，出现一些问题。代码如下：
![image](https://user-images.githubusercontent.com/49108659/227201598-9127d684-ca8a-4d47-8be6-219943c867df.png)
1. Geo或者Map中的add_js_funcs()函数不再生效，必须把add_js_funcs()这个函数在Grid里面调用才行。
2. #2116 中提及的'VisualMapOpts' object has no attribute 'extend'问题，出现新的错误："VisualMapOpts" object is not iterable。经分析，可能是由于这个原因：list.extend([something])，使用extend函数时，参数必须是一个list。或者直接使用list.append(something)。

**运行环境（系统环境及 pyecharts 版本）**
WIN11,pyecharts=2.02。

**代码及截图**
![image](https://user-images.githubusercontent.com/49108659/227202407-905218d2-671f-44f5-bf03-c8c8e32105a7.png)
![image](https://user-images.githubusercontent.com/49108659/227202466-aba1c937-e39e-4c6f-91a1-ed1940a0115f.png)
![image](https://user-images.githubusercontent.com/49108659/227202727-e983e0ba-e8e9-4bd8-938c-4ff1e637936f.png)

**Comment by sunhailin-Leo** [comment]
@TTSArrows 
* Q1： `add_js_funcs` 并不是 `Geo` 或者 `Map` 特有的函数。因此有嵌套关系的时候，理应在最外层去调用。
* Q2：`version 2.0.2` 已经修复了。

**Comment by TTSArrows** [comment]
> @TTSArrows
> 
> * Q1： `add_js_funcs` 并不是 `Geo` 或者 `Map` 特有的函数。因此有嵌套关系的时候，理应在最外层去调用。
> * Q2：`version 2.0.2` 已经修复了。

感谢作者对于两个疑问的解答！
但是对于Q2，我再次确认了目前安装的版本，确为2.0.2。运行如下代码时，的确会报错。
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.charts import Map
from pyecharts.charts import Grid
from pyecharts.faker import Faker
from pyecharts.globals import ChartType


data_pair = [list(z) for z in zip(Faker.provinces, Faker.values())]
color_list = ["#070093", "#1c3fbf", "#1482e5", "#70b4eb", "#b4e0f3", "#ffffff"]
geo_chart = (
    Geo()
    .add_schema(
        maptype="china"
    )
    .add(
        "geo",
        data_pair=data_pair,
        type_=ChartType.SCATTER,
    )
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(
        ),
    )
    # .render('output/echarts/geo.html')
)
map_chart = (
    Map()
    .add('LCOH', data_pair=data_pair, maptype='china')
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(
        ),
    )
    # .render('output/echarts/map.html')
)
gird_chart = (
    Grid(init_opts=opts.InitOpts())
    .add(map_chart, grid_opts=opts.GridOpts())
    .add(geo_chart, grid_opts=opts.GridOpts())
    .render('output/echarts/grid.html')
)
self.options.get("visualMap").extend(visual_map)
TypeError: 'VisualMapOpts' object is not iterable
![image](https://user-images.githubusercontent.com/49108659/227445120-7397e63c-8844-4e00-bb61-82692eafa750.png)
