### ISSUE TITLE
请问Graph中add函数的 edge_label参数如何赋值呢？

### ISSUE THREAD

**Issue by JAMIE-W** [pyecharts/pyecharts#2154]
**问题**
对应的是源码里的这个位置：
Graph 图节点边的 Label 配置（即在边上显示数据或标注的配置）
“ edge_label: types.Label = None,”

没有看到对应的使用示例，对赋值的方法和数据类型不清楚。另外，是否可以赋值自定义的边标签名呢？谢谢！

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@JAMIE-W 
* `types.Label` 这个提示已经很明显了。
