### ISSUE TITLE
Save Config 无法生成chart_config.json配置文件

### ISSUE THREAD

**Issue by Boundless666** [pyecharts/pyecharts#2156]
**问题**
使用Page.DraggablePageLayout时 点击Save Config无效 没有生成对应的chart_config.json文件

**运行环境（系统环境及 pyecharts 版本）**
Ubuntu 20.04 LTS
Jupyter 6.5.2
Python 3.8
pyecharts 2.0.2

**代码及截图**
使用的官网教程代码 唯一的改动就是输出目录
![image](https://user-images.githubusercontent.com/52664034/227994902-e944da27-f391-4c09-b39e-d130d48d1128.png)

运行f12查看
![image-20230327235614244](https://user-images.githubusercontent.com/52664034/227996446-ae1aac9a-bffe-403a-bb43-eae31324183a.png)

**Comment by sunhailin-Leo** [comment]
@Boundless666 
* 说下你的浏览器版本。。

**Comment by Boundless666** [comment]
尝试过Edge、Chrome、Firefox
Edge版本:  **111.0.1661.54** 
Chrome: **111.0.5563.147**
Firefox: **111.0.5563.147**

考虑过插件问题
在Chrome里面关闭所有插件运行依旧无效
![image](https://user-images.githubusercontent.com/52664034/228105060-73670157-9609-4249-ae20-ff138162a534.png)

**Comment by sunhailin-Leo** [comment]
@Boundless666 
* 我这边用相同的 chrome 测试过没有问题。
* 你的 html 文件是在本地用浏览器打开，还是用 jupyter notebook 里面打开的？

**Comment by Boundless666** [comment]
> @Boundless666
> 
> * 我这边用相同的 chrome 测试过没有问题。
> * 你的 html 文件是在本地用浏览器打开，还是用 jupyter notebook 里面打开的？

在本地用浏览器打开的

**Comment by sunhailin-Leo** [comment]
@Boundless666 
* 你确定不是在 jupyter 里面去打开 html 文件的？
    * 我在 jupyter 里面新建一个 html 文件，查看元素的时候就能发现 jupyter 会通过 iframe 的模式去渲染 html 文件。

**Comment by sunhailin-Leo** [comment]
@Boundless666 
* 锅还是 jupyter 背🐶。。。
