### ISSUE TITLE
TooltipOpts：提示框配置项添加 valueFormatter

### ISSUE THREAD

**Issue by zbjdonald** [pyecharts/pyecharts#2160]
**问题**
echarts 5.3 版本后好像有 valueFormatter 这个 feature [add valueFormatter in tooltip by pissang · Pull Request #16332 · apache/echarts](https://github.com/apache/echarts/pull/16332)，原来的 formatter 自己写 js 右面对不齐，这个 valueFormatter 好像可以解决这个问题。

**Comment by sunhailin-Leo** [comment]
@zbjdonald 
* 已经有了

**Comment by sunhailin-Leo** [comment]
@zbjdonald 
* 1、为何不能用于 global 的参数？
    * `set_global_opts` 里面有 `tooltip_opts` 用于控制全局的 `ToolTip`, 与 series 的区别在控制的范围不同。
* 2、本身这个配置就是 2.X 以后才支持的（1.X 对应的是 Echarts 4），`valueFormatter`  需要 Echarts 5.3 以后的版本。
* 3、不给的例子的原因是因为这个参数需要的是 js 回调函数字符串。（有使用门槛）
    * 类似 `JsFunc / JsCode` 类型的参数本身使用就需要开发者有一定的 js debug 基础而非 0 基础小白。

**Comment by zbjdonald** [comment]
您看一下我发的 [issues](https://github.com/apache/echarts/pull/16332#issuecomment) 后面部分的讨论。自己在 `formatter` 里面写 js 生成 html，tooltip 多条数据时的样式不好控（例如左右对齐），所以echarts开了新的 valueFormatter 功能，只针对单值 value。

**Comment by sunhailin-Leo** [comment]
@zbjdonald 
* 看完 echarts 的 issue 后也并没有发现跟现在这个 issue 有啥关联哈，也不太清楚您想表述什么。
* Echarts 的 Line Series 的内部有 tooltip 配置，全局也有的。
    * Line：https://echarts.apache.org/zh/option.html#series-line.tooltip.valueFormatter
    * Global：https://echarts.apache.org/zh/option.html#tooltip

**Comment by zbjdonald** [comment]
set_global_opts 里面的 valueFormatter 用不了，issues 里面说了只针对单值，您可以试试。

**Comment by sunhailin-Leo** [comment]
@zbjdonald 
* 不是不能用，只是回调函数的输入很简单。`(value: number | string) => string`
![image](https://user-images.githubusercontent.com/17564655/228766784-10df9f55-51c4-41aa-ac76-bb563d1d343f.png)

**Comment by zbjdonald** [comment]
您再加几条线试试，我也学习一下😂。

**Comment by sunhailin-Leo** [comment]
> 您再加几条线试试，我也学习一下😂。

![image](https://user-images.githubusercontent.com/17564655/228769254-d6fa35a7-e37c-4c0d-958a-04576604f69c.png)

**Comment by zbjdonald** [comment]
大佬牛逼👍
