### ISSUE TITLE
关于全局配置项中的LegendOpts图例配置项，无法设置selector参数

### ISSUE THREAD

**Issue by kwokstar** [pyecharts/pyecharts#2161]
文档说LegendOpts是可以设置selector参数来加入全选的按钮的，但实际使用却提示没有定义的，请教是什么问题？
![1](https://user-images.githubusercontent.com/77526277/228729112-dd03e034-e8a8-4a78-bef8-113fda31bab0.png)

代码：
`
Line()
.add_yaxis(
    series_name="something",
    y_axis=list_y
)
.set_global_opts(
    tooltip_opts=opts.TooltipOpts(trigger='axis'),
    legend_opts=opts.LegendOpts(pos_right='50px',orient='vertical',selector=True),
)
`

pyecharts版本：2.0.2

错误提示：
![2](https://user-images.githubusercontent.com/77526277/228729153-8d432cb1-4c80-4b8e-94a8-dee38b3e903e.png)

**Comment by sunhailin-Leo** [comment]
@kwokstar 
* 请确认下你的版本是不是用的最新的版本。
* unit test 和 example 运行都没有上述的错误描述

**Comment by kwokstar** [comment]
问题已解决，确实是版本控制问题，感谢答复。
