### ISSUE TITLE
can not save images

### ISSUE THREAD

**Issue by ru-zheng** [pyecharts/pyecharts#2162]
Hello, I had some problem when run following codes:
#-------------------------------------------------------------------------
from snapshot_selenium import snapshot as driver

from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.render import make_snapshot

def bar_chart() -> Bar:
    c = (
        Bar()
        .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
        .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
        .reversal_axis()
        .set_series_opts(label_opts=opts.LabelOpts(position="right"))
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-测试渲染图片"))
    )
    return c

make_snapshot(driver, bar_chart().render(), "bar.png")
#----------------------------------------------------------------------------------------
However, results show that:
Traceback (most recent call last):
  File "C:\Users\r\Desktop\111.py", line 44, in <module>
    make_snapshot(driver, bar_chart().render(), "bar.png")
  File "D:\python3.9.10\lib\site-packages\pyecharts\render\snapshot.py", line 32, in make_snapshot
    content = engine.make_snapshot(
  File "D:\python3.9.10\lib\site-packages\snapshot_selenium\snapshot.py", line 35, in make_snapshot
    driver = get_chrome_driver()
  File "D:\python3.9.10\lib\site-packages\snapshot_selenium\snapshot.py", line 67, in get_chrome_driver
    return webdriver.Chrome(options=options)
TypeError: __init__() got an unexpected keyword argument 'options'

I do know how to solve this problem,can you help me?

**Comment by sunhailin-Leo** [comment]
@ru-zheng 
* Check your selenium version?
