### ISSUE TITLE
heatmap渲染逻辑的可选

### ISSUE THREAD

**Issue by user-et** [pyecharts/pyecharts#2163]
**问题**
目前的热力图渲染和点密度及值大小两者相关联，然后使用累计加和的方式来渲染最终的结果。
当图表有缩放时，会整块渲染成一个颜色。
![image](https://user-images.githubusercontent.com/129383064/228801953-63c680ff-fa64-40b1-ba6f-e814084d49da.png)
![image](https://user-images.githubusercontent.com/129383064/228802023-0bb4b8ac-8bb0-4243-aabf-5f598aff943b.png)

是否可以增加一个参数，使热力图的渲染可以以自选的方式(如平均)来处理渲染结果

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by user-et** [comment]
谢谢，我再翻阅下echarts

**Comment by sunhailin-Leo** [comment]
> 谢谢，我再翻阅下echarts

后续有进展的话，可以在这个 issue 继续回复哈
