### ISSUE TITLE
关于Line图无法使用dataset数据及encode的问题。

### ISSUE THREAD

**Issue by yinssl** [pyecharts/pyecharts#2165]
@Bar图可以使用dataset及encode，但是使用Line图则发生错误（1.71版本说明Line可以使用dataset）。另外想实现的是Line图x轴类型设置为time，但是也无法正常显示。望各位指教。

![捕获](https://user-images.githubusercontent.com/48947900/229746495-26d8f15a-ce22-4f6c-b584-54f4aded2838.PNG)
![捕获](https://user-images.githubusercontent.com/48947900/229746640-f05ad42f-25d8-48ab-8f02-07843f2f4431.PNG)

**Comment by sunhailin-Leo** [comment]
@yinssl 
* Line 图这部分还没兼容。下一个版本会兼容

**Comment by yinssl** [comment]
原来如此，谢谢。

**Comment by yinssl** [comment]
@sunhailin-Leo 弱弱问一句，下个版本什么时候出。。

**Comment by sunhailin-Leo** [comment]
@yinssl 
* 这周末之前。（打工人需求多🐶）

**Comment by yinssl** [comment]
@sunhailin-Leo 加油~~干巴爹。
