### ISSUE TITLE
关于pandas数据传入Line图无法显示折线（已经转换了类型）

### ISSUE THREAD

**Issue by Dadeibayo** [pyecharts/pyecharts#2166]
**问题**
将数据纯如到pandas的dataframe中，然后储存为csv文件，读出来后，转换了类型了，可在画图时折线始终不能显示
在每一步我打印了数据类型，最后显示是“int”了，但还是不行
尝试直接把数据传入新建的列表传入也不行（对应里面的att_list1）

**运行环境（系统环境及 pyecharts 版本）**

Version: 2.0.2
使用系统：win10
python3.9

**代码及截图**
df = pd.DataFrame(columns=["Season", "Three-Point Attempts", "Three-Point Makes"])

for data in three_att_list:
    season = data.find_elements(By.XPATH, "./tr/td[1]")
    three_attempt = data.find_elements(By.XPATH, "./tr/td[22]")
    three_get = data.find_elements(By.XPATH, "./tr/td[21]")
    for att, get, per_season in zip(three_attempt, three_get, season):
        att1 = att.get_attribute("textContent")
        get1 = get.get_attribute("textContent")
        per_season1 = per_season.get_attribute("textContent")
        # print(att1, get1, per_season1)
        df = pd.concat([df, pd.DataFrame({"Season": [per_season1], "Three-Point Attempts": [att1],  "Three-Point Makes": [get1]})])

df.to_csv("nba_data.csv", index=False)
#
# # 从CSV文件中读取数据
df = pd.read_csv("nba_data.csv")

print(df)
print(df.columns)
print(df.values)
print(df["Three-Point Attempts"])

season_list = [int(i) for i in df['Season'].tolist()]
att_list = [int(i) for i in df['Three-Point Attempts'].tolist()]
make_list = [int(i) for i in df['Three-Point Makes'].tolist()]
att_list1 = [380, 342, 121, 600, 615, 646, 886, 789, 501, 810, 49, 801, 750, 622]
make_list1 = [166, 151, 55, 272, 261, 286, 402, 324, 212, 354, 12, 337, 285, 265]
# 将数据翻转
season_list.reverse()
att_list.reverse()
make_list.reverse()

print(type(season_list))
print(type(season_list[0]))
print(season_list)
print(type(att_list))
print(type(att_list[0]))
print(att_list)
print(type(make_list))
print(type(make_list[0]))
print(make_list)

# 关闭 ChromeDriver
web.quit()

# 画折线图
line_chart = (
    Line(
        init_opts=opts.InitOpts(theme=ThemeType.ESSOS)
    )
    .add_xaxis(season_list)
    .add_yaxis("Three-Point Attempts", att_list1)
    .add_yaxis("Three-Point Makes", make_list1)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Stephen Curry's Career Three-Point Data"),
        xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=45)),
        yaxis_opts=opts.AxisOpts(min_interval=100, interval=200),
        tooltip_opts=opts.TooltipOpts(trigger="axis", axis_pointer_type="cross")
    )
)

line_chart.render("curry_data.html")

![屏幕截图 2023-04-05 152808](https://user-images.githubusercontent.com/95181378/230011492-d103abcf-f5ac-44be-84e4-f77fe859e261.jpg)
![image](https://user-images.githubusercontent.com/95181378/230011660-fe73c39c-26df-4db8-b348-489d5bc9bf48.png)

**Comment by sunhailin-Leo** [comment]
@Dadeibayo 
* `xaxis_opts` 加一个 `type_ = "value"` 试试？

**Comment by Dadeibayo** [comment]
> @Dadeibayo
> 
> * `xaxis_opts` 加一个  试试？`type_ = "value"`

加完这个后画出来是这样的，而且x轴数据也显示不对了
![image](https://user-images.githubusercontent.com/95181378/230273264-423d6aba-318b-49db-844b-7684c9e39be0.png)

**Comment by sunhailin-Leo** [comment]
@Dadeibayo 
把 `x` 轴的内容改为 `str`，然后把 `type_` 设为 `category`
