### ISSUE TITLE
关于使用Grid同时渲染词云图和地图，子图像重叠的问题

### ISSUE THREAD

**Issue by kouyitian** [pyecharts/pyecharts#2167]
**问题**
使用Grid同时渲染词云图和地图，将两个图像并排放置，渲染出的子图像出现重叠的问题

**运行环境（系统环境及 pyecharts 版本）**
Python3.9，pyechart2.0.2

**代码及截图**
代码：
from pyecharts.charts import WordCloud, Map, Geo, Grid
from pyecharts import options as opts

word_cloud = WordCloud()
word_cloud.add("", [("Python", 50), ("Java", 40), ("JavaScript", 30), ("HTML", 20), ("CSS", 10)])

map_chart = Map()
map_chart.add("", [("北京", 100), ("上海", 200), ("广州", 300), ("深圳", 400), ("杭州", 500)], "china")

grid = Grid(init_opts=opts.InitOpts(width='1000px', height='600px'))
grid.add(word_cloud, grid_opts=opts.GridOpts(pos_left='5%', pos_right='50%', pos_top='5%', pos_bottom='50%'))
grid.add(map_chart, grid_opts=opts.GridOpts(pos_left='50%', pos_right='5%', pos_top='5%', pos_bottom='50%'))

grid.render('my_grid.html')

![图片](https://user-images.githubusercontent.com/76258028/230272805-fdd5b477-9476-47e8-ae34-fe09b86523e7.png)
渲染效果：
![图片](https://user-images.githubusercontent.com/76258028/230272953-b877878c-e3a2-4d70-a138-908fae7ad284.png)

**Comment by sunhailin-Leo** [comment]
@kouyitian 
* WordCloud 内部也有上下左右的配置，试一下修改一下

**Comment by sunhailin-Leo** [comment]
@kouyitian 
* 下一个版本我给 Map 也加上【上下左右】的配置。然后也可以试试。
