### ISSUE TITLE
绘制饼图时，字体都为黑色怎么回事

### ISSUE THREAD

**Issue by Gaia-Wu** [pyecharts/pyecharts#2168]
**问题**
当我使用pyecharts绘制饼图时，字体不与对应的图例颜色同步，但我并没有设置其他东西

**运行环境（系统环境及 pyecharts 版本）**
系统是Mac Apple
python=3.9.13
pyecharts=2.0.3

**代码及截图**
代码：
<img width="493" alt="截屏2023-04-10 11 30 19" src="https://user-images.githubusercontent.com/94101986/230819987-4a57ccb8-0f65-4252-90bc-e5e1110643b1.png">

结果图：
<img width="744" alt="image" src="https://user-images.githubusercontent.com/94101986/230819929-72fa5ccd-7135-45c8-b8dd-6abff352abd6.png">

**Comment by sunhailin-Leo** [comment]
@Gaia-Wu 
* 原本的字体不都是黑色的嘛？

**Comment by sunhailin-Leo** [comment]
https://echarts.apache.org/examples/zh/index.html#chart-type-pie

**Comment by Gaia-Wu** [comment]
> 



> @Gaia-Wu
> 
> * 原本的字体不都是黑色的嘛？

是版本更新了嘛？我看别人的是有对应颜色的，如：
<img width="751" alt="截屏2023-04-10 13 42 34" src="https://user-images.githubusercontent.com/94101986/230834824-4953bb5e-7561-4695-bf77-900fe979a865.png">

**Comment by sunhailin-Leo** [comment]
@Gaia-Wu 
* 别人画图的配置你有看嘛？官方默认示例字体都是黑色。

**Comment by fatdanny77** [comment]
@Gaia-Wu    试试下段：
```
label_opts=opts.LabelOpts(
    color = 'auto',
)
```
