### ISSUE TITLE
in version 2.0   'is_selected' option in add_yaxis() is deleted ?

### ISSUE THREAD

**Issue by mickey3721** [pyecharts/pyecharts#2169]
**问题**
in version <2.0 there is an option 'is_seleted' in add_yaxis(), to show or hide yaxis data 
but after upgrade 2.x no more 'is_selected' in add_yaxis
show: 
TypeError: Line.add_yaxis() got an unexpected keyword argument 'is_selected'

**运行环境（系统环境及 pyecharts 版本）**
python 3.11 + pyecharts 2.03

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@mickey3721 
* Please use `LegendOpts.selected_map` instead of `is_selected`.
* As the previous use of `is_selected` caused some configuration conflicts, subsequent versions have been configured using `LegendOpts`.

**Comment by sunhailin-Leo** [comment]
To correct this, the new configuration has been used since version 2.0.3.

**Comment by mickey3721** [comment]
Thanks！problem solved.

发自我的 iPhone

在 2023年4月10日，14:41，LeoSun ***@***.***> 写道：

﻿

@mickey3721<https://github.com/mickey3721>

  *   Please use LegendOpts.selected_map instead of is_selected.
  *   As the previous use of is_selected caused some configuration conflicts, subsequent versions have been configured using LegendOpts.

**Comment by sunhailin-Leo** [comment]
@mickey3721 
* Update release doc. https://github.com/pyecharts/pyecharts/releases/tag/v2.0.3
