### ISSUE TITLE
china 地图，给整个china entity添加数据

### ISSUE THREAD

**Issue by yzq986** [pyecharts/pyecharts#2171]
**问题**
我试用了map里的china.js, china-cities.js都不能只高亮全国，有办法能够只显示中国地图，但不要省级吗？或者有办法在整个国家上增加数据吗？
比如china.js，可以增加{"广东省":2}, {"china": 20}，这样

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@yzq986 
* 只能通过自定义 `geojson` 的方式写入。
* `geojson` 自行构造获取哈

![image](https://user-images.githubusercontent.com/17564655/232233409-89c34058-32e0-405e-91a6-2a5496c5b3d0.png)
