### ISSUE TITLE
dataZoom type_=both 网页打开空白

### ISSUE THREAD

**Issue by F1F88** [pyecharts/pyecharts#2173]
**问题**

datazoom_opts的type_="both"时，生成的网页打开空白。 同时浏览器控制台报错：`Component dataZoom.both is used but not imported.`

type="slider"和type="inside"时，显示正常。

**运行环境（系统环境及 pyecharts 版本）**

Windows 11 22H2 (22621.1413)

Python 3.9.16

pyecharts 2.0.3

**代码及截图**

代码：

    from pyecharts.charts import Bar
    from pyecharts import options as opts
    
    chart = (
        Bar()
        .set_global_opts(
            datazoom_opts=opts.DataZoomOpts(
                type_="both"
            )
        )
        .add_xaxis(xaxis_data=[i for i in range(1, 10)])
        .add_yaxis("Y", [i*2 for i in range(1, 10)])
    )
    
    chart.render("./test.html")

截图：

![Img_20230415_145430](https://user-images.githubusercontent.com/66011476/232193864-776afe52-b0fa-47cd-95af-ef75db4afedb.jpg)

**Comment by sunhailin-Leo** [comment]
@F1F88 
* 哪来的 `both` 配置？
* 而且 Echarts 也没有这个参数额。。

**Comment by F1F88** [comment]
![Img_20230416_021211](https://user-images.githubusercontent.com/66011476/232246359-dd4576da-dbf9-418d-b252-44edb32456ad.jpg)

**Comment by sunhailin-Leo** [comment]
@F1F88 
![image](https://user-images.githubusercontent.com/17564655/232246568-7dfd7a9d-538b-43ab-adc1-82a2951fa213.png)

**Comment by F1F88** [comment]
抱歉，浏览器搜索第一个是0.5版本的，我还以为那个是正确的。。
