### ISSUE TITLE
在Line图中用dataset添加多个add_yaxis时，图表展示错误

### ISSUE THREAD

**Issue by pshta0** [pyecharts/pyecharts#2174]
**问题**

在Line图中用dataset添加多个add_yaxis时，折线位于图表中的位置错误，看起来取的是首个yaxis，如下图。
试了Scatter图却是正常的。

**运行环境（系统环境及 pyecharts 版本）**
windows 3.8.10 64bit
pyecharts 2.0.3

**代码及截图**

        ....
            
        max_len_summary = max(len_summary)
        source = [[] for i in range(max_len_summary)]

        for i,ss in enumerate(source):
            for idx in range(len(signal_index_list)):
                if i<len(value_summary[f'x{idx}']):
                    ss.extend([value_summary[f'x{idx}'][i], value_summary[f'y{idx}'][i][0], value_summary[f'y{idx}'][i][1]])
                else:
                    ss.extend([None] * 3)

        curr_chart.add_dataset(
            dimensions = dimensions
            ,source= source
        )

        for idx, signal_index in enumerate(signal_index_list):
            if chart_type == 'scatter':
                curr_chart.add_yaxis(series_name=toolConfig.ALL_SIGNAL[signal_index][0],
                                    y_axis=[],
                                    encode={"x": f"x_{idx}", "y": f"y_{idx}", "tooltip": [3*idx, 3*idx+1,3*idx+2]},
                                    markline_opts=opts.MarkLineOpts(
                                        data=self.get_referenceline_config()
                                    ),
                                    label_opts=opts.LabelOpts(
                                        is_show=False, position='insideRight', rotate=20)
                                    ,
                                    symbol_size=symbol_size,
                )
            elif chart_type == 'line':
                curr_chart.add_yaxis(series_name=toolConfig.ALL_SIGNAL[signal_index][0],
                                    y_axis=[],
                                    encode={"x": f"x{idx}", "y": f"y{idx}", "tooltip": [3*idx, 3*idx+1,3*idx+2]},
                                    #is_step=True,
                                    markline_opts=opts.MarkLineOpts(
                                        data=self.get_referenceline_config()
                                    ),
                                    label_opts=opts.LabelOpts(
                                        is_show=False, position='insideRight', rotate=20
                                    ),
                                    sampling=self.get_sampling_config(),
                )
            
        if 1:       
            curr_chart.set_global_opts(
                toolbox_opts=opts.ToolboxOpts(
                    is_show=True),
                xaxis_opts=opts.AxisOpts(
                    type_='value', min_interval=1, name= 'TimeStamp/SeqNum', name_location='end'),
                yaxis_opts=opts.AxisOpts(
                    type_= 'value', boundary_gap=False,
                    axistick_opts=opts.AxisTickOpts(
                        is_show=True, is_inside=True),
                    axislabel_opts=opts.LabelOpts(is_show=True, position='insideRight',
                                                rotate=0, font_size= 10, font_weight='bolder'
                                                )
                ),
                # tooltip_opts=opts.TooltipOpts(
                #     is_show=True, trigger="item", formatter='{a}<br>: <br>{c}'),
                datazoom_opts=[opts.DataZoomOpts(is_realtime=False,
                                                is_show=True,
                                                range_start=0,
                                                range_end=100,
                                                pos_bottom=2
                                                )
                ],
                # visualmap_opts=(
                #     None if maxy <= 0 else opts.VisualMapOpts(type_='size',max_= maxy, min_= miny)
                # )
            )
![image](https://user-images.githubusercontent.com/122964169/232648770-964b5091-2c51-4c33-be5e-f2777edccb46.png)
![image](https://user-images.githubusercontent.com/122964169/232648846-23a9639f-05ec-443b-af05-6d18d384f071.png)

**Comment by sunhailin-Leo** [comment]
@pshta0 
* 具体是啥展示错误？然后你期望的效果是啥样的？

**Comment by pshta0** [comment]
> @pshta0
> 
> * 具体是啥展示错误？然后你期望的效果是啥样的？

有多个yaxis时，Line图点所对应的刻度是错误的。Scatter对应的刻度是正确的，可以看我贴的图。

**Comment by sunhailin-Leo** [comment]
@pshta0 
* 相同的数据？

其他问题：
* 1、为啥离散数据会用 `Line` 去画图？
* 2、你还是没有回答我你的期望？然后你的贴图和你的 `Legend` 我也看不太出。

**Comment by pshta0** [comment]
> @pshta0
> 
> * 相同的数据？
> 
> 其他问题：
> 
> * 1、为啥离散数据会用 `Line` 去画图？
> * 2、你还是没有回答我你的期望？然后你的贴图和你的 `Legend` 我也看不太出。

1、我不太清楚什么的数据最合适的画法是什么，用Line去画是参照了一些软件上的展示效果。
2、我的期望是，Line图中的每个点的所对应的Y轴和X轴的刻度是正确的。但是看我展示的图片，当点y值是1000时，所对应的Y轴刻度是1
3、这个问题的原因我刚刚找到了，在encode={"x": f"x{idx}", "y": f"y{idx}", "tooltip": [3*idx, 3*idx+1,3*idx+2]},中，x{idx}和y{idx}在diaemons是不存在的。应该是encode={"x": f"x_{idx}", "y": f"y_{idx}", "tooltip": [3*idx, 3*idx+1,3*idx+2]}。但是对于为什么点的tooltip是正确的，刻度是错误的，仍然感到有些疑惑

**Comment by sunhailin-Leo** [comment]
> > @pshta0
> > 
> > * 相同的数据？
> > 
> > 其他问题：
> > 
> > * 1、为啥离散数据会用 `Line` 去画图？
> > * 2、你还是没有回答我你的期望？然后你的贴图和你的 `Legend` 我也看不太出。
> 
> 1、我不太清楚什么的数据最合适的画法是什么，用Line去画是参照了一些软件上的展示效果。 2、我的期望是，Line图中的每个点的所对应的Y轴和X轴的刻度是正确的。但是看我展示的图片，当点y值是1000时，所对应的Y轴刻度是1 3、这个问题的原因我刚刚找到了，在encode={"x": f"x{idx}", "y": f"y{idx}", "tooltip": [3_idx, 3_idx+1,3_idx+2]},中，x{idx}和y{idx}在diaemons是不存在的。应该是encode={"x": f"x_{idx}", "y": f"y_{idx}", "tooltip": [3_idx, 3_idx+1,3_idx+2]}。但是对于为什么点的tooltip是正确的，刻度是错误的，仍然感到有些疑惑

* 如果用 `Line` 展示离散值的话有一个 `is_connect_nones` 参数，你可以试试。
