### ISSUE TITLE
新版本Line.add_yaxis() got an unexpected keyword argument 'is_selected' 上一个版本正常

### ISSUE THREAD

**Issue by PeikaiLi** [pyecharts/pyecharts#2175]
*
![image](https://user-images.githubusercontent.com/79044615/233318656-3f684ccb-947f-4fa4-b0d7-a70cbb090348.png)

*运行环境（系统环境及 pyecharts 版本）**
···
pip show pyecharts
Name: pyecharts
Version: 2.0.3
Summary: Python options, make charting easier
Home-page: https://github.com/pyecharts/pyecharts
Author: chenjiandongx
Author-email: chenjiandongx@qq.com
License: MIT
Location: /Users/peikaili/opt/anaconda3/envs/peikai/lib/python3.10/site-packages
Requires: jinja2, prettytable, simplejson
···

**Comment by PeikaiLi** [comment]
2.0.2 是正常的

**Comment by sunhailin-Leo** [comment]
@PeikaiLi 
* https://github.com/pyecharts/pyecharts/releases/tag/v2.0.3

**Comment by PeikaiLi** [comment]
> @PeikaiLi
> 
> * https://github.com/pyecharts/pyecharts/releases/tag/v2.0.3

Thanks
