### ISSUE TITLE
主题河流图不支持修改x轴字体大小

### ISSUE THREAD

**Issue by zhijuyingfeng** [pyecharts/pyecharts#2176]
**问题**
主题河流图不支持修改x轴字体大小。运行[官网](https://gallery.pyecharts.org/#/ThemeRiver/theme_river)提供的河流图Demo，并尝试通过`set_global_opts`修改x轴字体，发现无法生效，x轴字体大小未发生改变。

The ThemeRiver doesn't support customizing config of x axis. Run the ThemeRiver  demo offered by [offical site](https://gallery.pyecharts.org/#/ThemeRiver/theme_river), then try to change font of  the label of x axis, but it doesn't work. The font size of x axis label remains unchanged. 

**运行环境（系统环境及 pyecharts 版本）**
OS: Linux fedora 6.2.10-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr  6 23:30:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Python: 3.11.2
Pyecharts:  2.0.3

**代码及截图**
``` python
(
    ThemeRiver()
    .add(
        series_name=x_data,
        data=y_data,
        singleaxis_opts=opts.SingleAxisOpts(
            pos_top="50", pos_bottom="50", type_="time"
        ),
    )
    .set_global_opts(
        tooltip_opts=opts.TooltipOpts(trigger="axis", axis_pointer_type="line"),
        xaxis_opts=opts.AxisOpts(
            axislabel_opts=opts.LabelOpts(
                font_size=34
            )
        )
    )
    .render("theme_river.html")
)
```

**可能原因**
``` python
# chart.py

    def set_global_opts(
        self,
        ...
        xaxis_opts: types.Axis = None,
        yaxis_opts: types.Axis = None,
        ...
    ):
        ...

        if xaxis_opts and self.options.get("xAxis", None):
            if isinstance(xaxis_opts, opts.AxisOpts):
                xaxis_opts = xaxis_opts.opts

            # 此处self.options["xAxis"]为None
            self.options["xAxis"][0].update(xaxis_opts)

        if yaxis_opts and self.options.get("yAxis", None):
            if isinstance(yaxis_opts, opts.AxisOpts):
                yaxis_opts = yaxis_opts.opts
            self.options["yAxis"][0].update(yaxis_opts)

        return self

```

**Comment by sunhailin-Leo** [comment]
@zhijuyingfeng 
* 具体指的是哪一块？截图说明一下

**Comment by zhijuyingfeng** [comment]
横轴标签的字体大小 ![image](https://user-images.githubusercontent.com/27205697/234035740-28ec7f55-5001-4ea4-82ae-646761d53114.png)

**Comment by zhijuyingfeng** [comment]
> @zhijuyingfeng
> 
> * 具体指的是哪一块？截图说明一下

![image](https://user-images.githubusercontent.com/27205697/234035904-7b3178d1-de40-4ec1-a2f1-f6d58edfa527.png)

**Comment by sunhailin-Leo** [comment]
@zhijuyingfeng 
* `ThemeRiver` 得通过 `SingleAxisOpts` 去修改，而不是 `xaxis_opts`.
* 现在 `SingleAxisOpts` 这块没有相关的配置，下个版本会加上哈～
