### ISSUE TITLE
图片无法在jupyter中输出

### ISSUE THREAD

**Issue by MJ-Heree** [pyecharts/pyecharts#2177]
**问题**
你好，pyecharts在jupyter中 没有输出

**运行环境（系统环境及 pyecharts 版本）**
windows10
python 3.8

pyecharts 2.0.3

**代码及截图**
# 只需要在顶部声明 CurrentConfig.ONLINE_HOST 即可
from pyecharts.globals import CurrentConfig

CurrentConfig.ONLINE_HOST = "http://127.0.0.1:8000/assets/"

# 接下来所有图形的静态资源文件都会来自刚启动的服务器

from pyecharts.charts import Bar
from pyecharts import options as opts
from pyecharts.faker import Faker
from pyecharts.globals import ThemeType
c = (
    Bar()
    .add_xaxis(Faker.days_attrs)
    .add_yaxis("商家A", Faker.days_values)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Bar-DataZoom（slider-水平）"),
        datazoom_opts=opts.DataZoomOpts(),
    ).render_notebook()
)

![image](https://user-images.githubusercontent.com/78643386/233842450-e22390d8-6148-4601-8902-924164388e76.png)

**Comment by sunhailin-Leo** [comment]
@MJ-Heree 
* 吧 `render_notobook` 的调用拆出来调用呢？另起一行 `c.render_notebook()`
