### ISSUE TITLE
Change tooltip from Chinese to English/other languages

### ISSUE THREAD

**Issue by pythondatascrape** [pyecharts/pyecharts#2180]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

Change tooltips from Chinese to English 
![2023-05-18 23_25_03-Noa – Django Bootstrap 5 Admin   Dashboard Template](https://github.com/pyecharts/pyecharts/assets/116651705/61992379-d813-4a24-b090-d8e730e08634)

**Comment by sunhailin-Leo** [comment]
@pythondatascrape 
* You mean the charts did not change language automatically？
