### ISSUE TITLE
markline_opts 精度丢失

### ISSUE THREAD

**Issue by yoval** [pyecharts/pyecharts#2182]
**问题**
markline_opts 配置后精度丢失

**运行环境（系统环境及 pyecharts 版本）**
pyecharts.__version__:'2.0.1'

**代码及截图**
```python
from pyecharts.charts import Scatter
from pyecharts.commons.utils import JsCode
from pyecharts import options as opts

scatter = Scatter()
scatter.add_xaxis(xaxis_data=[0.222,0.333])
scatter.add_yaxis("测试",[0.555,0.444])



comp_data = {
    "tongbi":0.132706,#大盘同比
    "time":0.677419355 #时间进度
}
#警戒线
scatter.set_series_opts(
    markline_opts=opts.MarkLineOpts(
        data=[opts.MarkLineItem(y=comp_data['tongbi'], name="大盘存量同比" ),
              opts.MarkLineItem(x=comp_data['time'], name="时间进度"),
             ],
        symbol="none" ,#不要箭头
        label_opts=opts.LabelOpts(
            formatter=JsCode("function(params) { return (params.value * 100).toFixed(2) + '%'; }")
         
        )
    ),

)
scatter.render_notebook()
```
![Snipaste_2023-05-25_11-08-21](https://github.com/pyecharts/pyecharts/assets/20494844/097acf05-a5d4-4980-8ba6-128dd7d31558)

警戒线13.27%显示成了13%。

**Comment by sunhailin-Leo** [comment]
@yoval 
* 如果在 Python 里面处理数据精度呢？

**Comment by yoval** [comment]
> @yoval
> 
> * 如果在 Python 里面处理数据精度呢？

删掉 `formatter=JsCode("function(params) { return (params.value * 100).toFixed(2) + '%'; }")`显示的也是0.13，也不是0.1327。
用 {:.2f}% 转成百分数，类型变成了str也不是float，也没法运行了

**Comment by sunhailin-Leo** [comment]
@yoval 
* 这个 `precsion` 参数可以，只要大于` toFixed` 的值就好了
![image](https://github.com/pyecharts/pyecharts/assets/17564655/c0523cce-a66e-43a6-b502-1855fee1e447)
![image](https://github.com/pyecharts/pyecharts/assets/17564655/af43d919-a7fa-49d9-89f0-f4927a025e7f)
