### ISSUE TITLE
flask地图组件功能缺失，颜色没有变化

### ISSUE THREAD

**Issue by SZJhacker** [pyecharts/pyecharts#2183]
后端代码：
```python
    map_chart = Map(init_opts=opts.InitOpts(theme='light'))

    # 添加数据
    map_chart.add("水稻种植数目", data_pair=map_data, maptype="china", is_map_symbol_show=False, aspect_scale=0.85, zoom=1.4,
                    pos_left='15%', pos_right='15%', pos_top='20%', map_value_calculation = "sum")

    # 设置地图样式和配置项
    map_chart.set_series_opts(
        label_opts=opts.LabelOpts(is_show=True, formatter="{b}"))
    # map_chart.set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    map_chart.set_global_opts(
        visualmap_opts=opts.VisualMapOpts(max_=df['Counts'].max(), pos_left='right', range_color=['lightskyblue', 'yellow', 'orangered'])
    )

    return render_template('home.html', map_charts=map_chart.dump_options())
```
前端代码：
```html
<script type="text/javascript" src={{ url_for('v1.static', filename='js/echarts.min.js') }}></script>
<script type="text/javascript" src="https://assets.pyecharts.org/assets/maps/china.js"></script>
<div id="china"  style="width:1000px; height:800px;"></div>
<script type="text/javascript">
    var myChart = echarts.init(document.getElementById('china'));
    
    var option = {{ map_charts | safe }};

    myChart.setOption(option);
</script>
```

**问题**
flask前端显示和在jupyter中调整的不一致，颜色缺失，并且组件功能缺失，怀疑echart引用的js解析和后端pyechart不一致导致的。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 2.0.3

**代码及截图**

![image](https://github.com/pyecharts/pyecharts/assets/32929097/8066b39e-8029-45cf-a904-7367662d3483)

**jupyter中可视化结果**
![image](https://github.com/pyecharts/pyecharts/assets/32929097/0dcce124-f2e5-4e7d-a12f-6fd1a4a1565e)

**Comment by sunhailin-Leo** [comment]
@SZJhacker 
* 你看下你的 `map_data` 的数据，省份的话强制写全称。旧版本是简称的，新版本地图数据为了更严谨改成了全称。
* 例如：【广东】，新版本必须是【广东省】

**Comment by SZJhacker** [comment]
> @SZJhacker
> 
> * 你看下你的 `map_data` 的数据，省份的话强制写全称。旧版本是简称的，新版本地图数据为了更严谨改成了全称。
> * 例如：【广东】，新版本必须是【广东省】

你说的这个我已经解决了，上面那个黄色的名称和下面一样，我使用的china.js没有问题，鼠标悬停，不同省份的数字统计也是显示的，但是颜色变化没有了，侧边的legend只有0这个数字

**Comment by sunhailin-Leo** [comment]
@SZJhacker 
* 你对齐一下 jupyter 和 flask 的静态资源和 pyecharts 的版本

**Comment by SZJhacker** [comment]
> @SZJhacker
> 
> * 你对齐一下 jupyter 和 flask 的静态资源和 pyecharts 的版本

我在jupyter展示地图的时候，利用开发者工具在网络里面捕捉了echarts.js和china.js，然后资源导入访问的就是他们，但还是这个样子

**Comment by sunhailin-Leo** [comment]
@SZJhacker 
* 你是用 2.X 版本的嘛？2.X 版本的静态资源都在 `https://assets.pyecharts.org/assets/v5/***` 下面，多了一级 v5

**Comment by SZJhacker** [comment]
> * https://assets.pyecharts.org/assets/v5/

是的。2.0.3，我在jupyter运行时候捕捉的地址是：
https://assets.pyecharts.org/assets/v5/maps/china.js?v=20230605112423
https://assets.pyecharts.org/assets/v5/echarts.min.js?v=20230605112423

文件也用的相同，但是map.render_notebook显示的正常，但是map.dump_options()传递给前端用echarts初始化之后就不一样了，功能组件缺少，颜色也没有变化。

**Comment by sunhailin-Leo** [comment]
@SZJhacker
* 那这个问题应该是前端的问题了

**Comment by SZJhacker** [comment]
> @SZJhacker
> 
> * 那这个问题应该是前端的问题了

前端的css样式是bootstrap 4，难不成是echarts可视化的时候颜色和bootstrap4的没有对应上？

**Comment by sunhailin-Leo** [comment]
@SZJhacker 
* 跟 css 没关系，应该是你前端的 js 被覆盖了。

**Comment by SZJhacker** [comment]
> @SZJhacker
> 
> * 跟 css 没关系，应该是你前端的 js 被覆盖了。

我的js分别是：
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>

<script type="text/javascript" src="https://assets.pyecharts.org/assets/v5/echarts.min.js"></script>
<script type="text/javascript" src="https://assets.pyecharts.org/assets/v5/maps/china.js"></script>

**Comment by sunhailin-Leo** [comment]
@SZJhacker 
* 我这边也没法确认具体是啥问题哈，但是返回到前端去有问题的话要么就是浏览器 js 缓存，要么就是你前端项目的问题了。

**Comment by SZJhacker** [comment]
> @SZJhacker
> 
> * 我这边也没法确认具体是啥问题哈，但是返回到前端去有问题的话要么就是浏览器 js 缓存，要么就是你前端项目的问题了。

好的，谢谢

**Comment by SZJhacker** [comment]
> @SZJhacker
> 
> * 我这边也没法确认具体是啥问题哈，但是返回到前端去有问题的话要么就是浏览器 js 缓存，要么就是你前端项目的问题了。

为啥关闭评论，这个问题没有被解决啊？
我前段的echarts.js 和 china.js都没有出错，那么大概率就是dump_options压缩的结果没有被echats.js正确解析，这个问题不解决吗？

**Comment by sunhailin-Leo** [comment]
@SZJhacker 
* 1、所有的 `render` 函数都会走 `dump_options` 的方法 ==> [源码](https://github.com/pyecharts/pyecharts/blob/master/pyecharts/charts/base.py#L85-L123)
* 2、你这个问题我这边没有办法去 debug 或者浮现。而且还涉及到你那边服务的前后端分离操作，更加没有办法去定位问题。

**Comment by SZJhacker** [comment]
> @SZJhacker
> 
> * 1、所有的 `render` 函数都会走 `dump_options` 的方法 ==> [源码](https://github.com/pyecharts/pyecharts/blob/master/pyecharts/charts/base.py#L85-L123)
> * 2、你这个问题我这边没有办法去 debug 或者浮现。而且还涉及到你那边服务的前后端分离操作，更加没有办法去定位问题。
找到原因了，range_color前端发现颜色变化的max值参数缺失，后端是通过df['Counts'].max()获取的最大值，传递到前端的时候好像直接是对象传递过去了，而不是最大值，所以出错。
问了chatgpt要到了df['Counts'].max().item()的解决方案。
