### ISSUE TITLE
Multiple word clouds overlap and disregard grid options

### ISSUE THREAD

**Issue by amarba1** [pyecharts/pyecharts#2184]
问题
Cannot have more than one word cloud per page

**运行环境（系统环境及 pyecharts 版本）**
python 3.10.8 + pyecharts 2.03

**代码及截图**

In the code below, neither option 1 or option 2 work
<pre>
from pyecharts import options as opts
from pyecharts.charts import Grid, WordCloud

# Sample data for the word clouds
data1 = [("Word1", 100), ("Word2", 80), ("Word3", 60), ("Word4", 40), ("Word5", 20)]
data2 = [("Word6", 120), ("Word7", 90), ("Word8", 70), ("Word9", 50), ("Word10", 30)]

# Create the first word cloud
wordcloud1 = (
    WordCloud()
    .add("", data1)
    .set_global_opts(title_opts=opts.TitleOpts(title="Word Cloud 1"))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}", font_size=16))
)

# Create the second word cloud
wordcloud2 = (
    WordCloud()
    .add("", data2)
    .set_global_opts(title_opts=opts.TitleOpts(title="Word Cloud 2"))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}", font_size=16))
)

# Option 1 does not work
# Create the grid chart and add the word clouds
#grid = (
#    Grid()
#    .add(wordcloud1, grid_opts=opts.GridOpts(pos_top="10%"))
#    .add(wordcloud2, grid_opts=opts.GridOpts(pos_bottom="10%"))
#)

# Option 2 does not work
# Create the grid chart and add the word clouds with positioning
grid = (
    Grid()
    .add(wordcloud1, grid_opts=opts.GridOpts(pos_top="20%", pos_bottom="60%", pos_right="55%", pos_left="5%"))
    .add(wordcloud2, grid_opts=opts.GridOpts(pos_top="70%", pos_bottom="10%", pos_right="55%", pos_left="5%"))
)

# Render the chart to an HTML file
grid.render("word_clouds.html")
</pre>

**Comment by sunhailin-Leo** [comment]
@amarba1 
* Can you try some configuration in `WordCloud().add` like `pos_left, pos_top, pos_right, pos_bottom`?

**Comment by amarba1** [comment]
I really did try different configurations, but it does not seem to be working. On the contrary if I try the same  pos_left, pos_top, pos_right, pos_bottom with another type of graphs (non word cloud), it shows the tiling properly. Did you try out the code I submitted ?

**Comment by sunhailin-Leo** [comment]
@amarba1 
* You can try this code.
```python
from pyecharts import options as opts
from pyecharts.charts import Grid, WordCloud
# Sample data for the word clouds
data1 = [("Word1", 100), ("Word2", 80), ("Word3", 60), ("Word4", 40), ("Word5", 20)]
data2 = [("Word6", 120), ("Word7", 90), ("Word8", 70), ("Word9", 50), ("Word10", 30)]

# Create the first word cloud
wordcloud1 = (
    WordCloud()
    .add(series_name="wc1", data_pair=data1, pos_top="20%", pos_bottom="60%", pos_left="1%", pos_right="50%")
    .set_global_opts(title_opts=opts.TitleOpts(title="Word Cloud 1"))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}", font_size=16))
)

# Create the second word cloud
wordcloud2 = (
    WordCloud()
    .add(series_name="wc2", data_pair=data1, pos_top="20%", pos_bottom="60%", pos_left="40%")
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Word Cloud 2", pos_left="50%")
    )
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}", font_size=16))
)

grid = (
    Grid(init_opts=opts.InitOpts(width="1280px"))
    .add(wordcloud1, grid_opts=opts.GridOpts())
    .add(wordcloud2, grid_opts=opts.GridOpts())
)

grid.render("issue_2184.html")
```

**Comment by sunhailin-Leo** [comment]
* I tested it was ok, if you have any problems, you can reopen this issue.
