### ISSUE TITLE
这段代码中y轴的文字颜色怎么设置

### ISSUE THREAD

**Issue by betterlch** [pyecharts/pyecharts#2185]
**问题**
y轴的文字颜色怎么设置呢，试了试没发现哪儿能设置

**运行环境（系统环境及 pyecharts 版本）**

windows10
pyecharts==1.9.1

**代码及截图**

```
line = (Line()
            .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
            .add_yaxis('服装统计折线图', y_axis=[5, 20, 36, 10, 75, 90], color='purple')
            .set_series_opts(is_more_utils=True)
            .set_series_opts(label_opts=opts.LabelOpts(color="blue"))
            .set_global_opts(title_opts=opts.TitleOpts(title_textstyle_opts=opts.TextStyleOpts(color="blue")))
            .set_global_opts(xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(color='white'), axisline_opts=opts.AxisLineOpts(linestyle_opts=opts.LineStyleOpts(color='yellow'))))
            .set_global_opts(yaxis_opts=opts.AxisOpts(name='销量', axisline_opts=opts.AxisLineOpts(linestyle_opts=opts.LineStyleOpts(color='pink'))))
            )
```
这里的`服装统计折线图` 这几个字的颜色如何设置

**Comment by sunhailin-Leo** [comment]
@betterlch 
* 你的图呢？🤔

**Comment by betterlch** [comment]
![image](https://github.com/pyecharts/pyecharts/assets/46791163/b0dbe481-46a5-4e92-b7e1-67b4d3ccd8fc)
sry，另一台电脑当时没法传上来，然后摆了

**Comment by sunhailin-Leo** [comment]
@betterlch 
这样子就行了
* `.set_global_opts(legend_opts=opts.LegendOpts(textstyle_opts=opts.TextStyleOpts(color="yellow")))`

**Comment by betterlch** [comment]
> 

好吧，看来是1.9.1版本的问题，当时试了Legend，目前2.0.3正常，感谢！

**Comment by betterlch** [comment]
> @betterlch 这样子就行了
> 
> * `.set_global_opts(legend_opts=opts.LegendOpts(textstyle_opts=opts.TextStyleOpts(color="yellow")))`

看来是1.9.1版本的问题，当时试了Legend来着，2.0.3正常，感谢
