### ISSUE TITLE
tooltip of bar can't be triggered when bar is overlapped by line in pyecharts 2, while it works in pycharts 1.9.x

### ISSUE THREAD

**Issue by smilingsand** [pyecharts/pyecharts#2186]
**问题**
tooltip of bar can't be triggered when bar is overlapped by line in pyecharts 2.0.3, while it works in pyecharts 1.9.x

**运行环境（系统环境及 pyecharts 版本）**
windows 
python 3.9.10
pyecharts 2.0.3

**代码及截图**

    line = Line()
    line.add_xaxis( list(ratioinProfitability1.columns) )
    for s in list(ratioinProfitability1.index.values):
        line.add_yaxis( s, list(ratioinProfitability1.loc[s].map(lambda x:format(100*x,".1f"))), yaxis_index=0, z_level=1,
                            # replace add_yaxis(is_selected) with LegendOpts(selected_map) for pyecharts 2.0.3+ on 20230611.
                            # is_selected=(True if s in ['毛利率','核心利润率','归母净利率'] else False) ,
                        ) 

    line.set_series_opts( label_opts=opts.LabelOpts(is_show=False, formatter="{c}%" ),
                          linestyle_opts=opts.LineStyleOpts(width=1.5),
                          tooltip_opts=opts.TooltipOpts(formatter="{a}: <BR>{c}%"),
                          markline_opts=opts.MarkLineOpts(  is_silent=False, symbol='none',
                                    data=[ opts.MarkLineItem(y=100)],
                                    linestyle_opts=opts.LineStyleOpts(width=0.5, type_='dashed', color='grey'),
                                    label_opts=opts.LabelOpts(is_show=False),
                                 ),
                        )
    line.set_global_opts( # title_opts=opts.TitleOpts(title="盈利能力指标"),
                          yaxis_opts=opts.AxisOpts( name="盈利能力指标", name_location="center", name_rotate=90, name_gap=45 ,
                                                    axislabel_opts=opts.LabelOpts(formatter="{value}%"),
                                                    axisline_opts=opts.AxisLineOpts(is_show=True),
                                                    axistick_opts=opts.AxisTickOpts(is_show=True, is_inside=False),                                      
                                                    splitline_opts=opts.SplitLineOpts(is_show=False),
                                                    #splitline_opts=opts.SplitLineOpts(is_show=True, linestyle_opts=opts.LineStyleOpts(is_show=True,type_='dotted')),
                                                    splitarea_opts=opts.SplitAreaOpts(is_show=True, areastyle_opts=opts.AreaStyleOpts(opacity=opacitySplitArea)),
                                                  ),
                          xaxis_opts=opts.AxisOpts( is_inverse=True,
                                                    axislabel_opts=opts.LabelOpts(rotate=30),
                                                    axisline_opts=opts.AxisLineOpts(on_zero_axis_index=0),
                                                    splitline_opts=opts.SplitLineOpts(is_show=False),
                                                  ),
                          legend_opts=opts.LegendOpts(pos_left='center', pos_right='20%', 
                                                      orient='horizontal', #  align='left', padding=10,
                                                      # replace add_yaxis(is_selected) with LegendOpts(selected_map) for pyecharts 2.0.3+ above on 20230611.
                                                      selected_map={key:(True if key in ['毛利率','核心利润率','归母净利率'] else False) for key in s1} 
                                                      ),
                        )

    # 将ROA、ROE、ROIC作为柱状图
    bar=Bar()
    bar.add_xaxis( list(ratioinProfitability2.columns) )
    # 经测试：被overlap的图的颜色设置，is_selected设置与set_color等都不起效果，因此将set_color改为itemstyle中颜色设置   
    itemColor={ 'ROA':'CornflowerBlue', '归母ROE':'LimeGreen', 'ROIC':'Violet' } 
    for s in list(ratioinProfitability2.index.values):
        bar.add_yaxis( s, list(ratioinProfitability2.loc[s].map(lambda x:format(100*x,".1f"))), yaxis_index=0,
                            # replace add_yaxis(is_selected) with LegendOpts(selected_map) for pyecharts 2.0.3+ on 20230611.
                            # is_selected=(True if s in ['ROA','归母ROE'] else False),
                            category_gap='40%',
                            itemstyle_opts=opts.ItemStyleOpts(color=itemColor[s], opacity=1,),
                     )

    bar.set_series_opts( label_opts=opts.LabelOpts(is_show=False),
                         tooltip_opts=opts.TooltipOpts(formatter="{a}: <BR>{c}%"),
                       )
    bar.set_global_opts( legend_opts=opts.LegendOpts( # replace add_yaxis(is_selected) with LegendOpts(selected_map) for pyecharts 2.0.3+ above on 20230611.
                                                      selected_map={key:(True if key in ['ROA','归母ROE'] else False) for key in s2} 
                                                      ),
                       )

    # 3.2 盈利能力分析 - 图形输出         
    with output.use_scope('scopeProfitability', clear=True):
        # 输出input内容做检查
        #output.put_code(changed)
        #output.put_row( [output.put_text(pin.pin[x]) for x in inputforProfitability ] )
        if vReport==1 :
            output.put_html(line.overlap(bar).render_notebook())             
            output.put_collapse('显示数据',
                output.put_table( [ [s] + list(ratioinProfitability.loc[s].map(lambda x:format(x,".2%")))[::-1] for s in list(ratioinProfitability.index.values) ], 
                    [''] + list(ratioinProfitability.columns)[::-1]
                    )
                ).style(fontforDataDisplay)

**Comment by sunhailin-Leo** [comment]
@smilingsand 
* Have any snapshot or demo codes to let me check this issue.

**Comment by smilingsand** [comment]
@sunhailin-Leo 

here is sample code:


    from pyecharts import options as opts
    from pyecharts.charts import Bar, Line
    from pyecharts.faker import Faker
    
    v_Income = [48.83,61.16,77.65,96.14,128.72,165.35,229.02,393.55,89.64,48.83,61.16,77.65]
    v_CashIncome = [44.76,64.74,79.51,92.7,124.76,168.64,235.43,399.62,96.9,44.76,64.74,79.51]
    v_收现比 = [0.92,1.06,1.02,0.96,0.97,1.02,1.03,1.02,1.08,0.92,1.06,1.02]
    
    bar = (
        Bar()
        .add_xaxis(Faker.months)
        .add_yaxis("营业总收入", v_Income , yaxis_index=1, category_gap='50%', gap=0) 
        .add_yaxis("现金收入", v_CashIncome,yaxis_index=1, category_gap='50%', gap=0) 
        .extend_axis(
            yaxis=opts.AxisOpts(
                axislabel_opts=opts.LabelOpts(formatter="{value}亿元"),
                axisline_opts=opts.AxisLineOpts(is_show=True),                     # requested by 2.0.3
                axistick_opts=opts.AxisTickOpts(is_show=True, is_inside=False),   # requested by 2.0.3                                 
                splitline_opts=opts.SplitLineOpts(is_show=False),                 # requested by 2.0.3
            )
        )
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Overlap-bar+line"),
            yaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(formatter="{value}"),
                                     axisline_opts=opts.AxisLineOpts(is_show=True),                     # requested by 2.0.3
                                     axistick_opts=opts.AxisTickOpts(is_show=True, is_inside=False),   # requested by 2.0.3                                
                                     splitline_opts=opts.SplitLineOpts(is_show=False),                 # requested by 2.0.3
                                    ),
            xaxis_opts=opts.AxisOpts( axisline_opts=opts.AxisLineOpts(on_zero_axis_index=0),
                                      splitline_opts=opts.SplitLineOpts(is_show=False),               # requested by 2.0.3
                                    )
        )
    )
    
    line = Line().add_xaxis(Faker.months)    \
                .add_yaxis( '收现比', v_收现比, yaxis_index=0, 
                            itemstyle_opts=opts.ItemStyleOpts(color='DarkOrange', opacity=1,),
                            z_level=1 ,  # either z_level=1 or z=2 lead to no trigger of bar tooltip, which seems to be overlapped by line canvas, but 1.9.1 works. 
                          ) 
    
    #bar.overlap(line).render_notebook()
    bar.overlap(line).render("overlap_bar_line.html")


I can not attach html files here.  you can run the code above in pyecharts 1.9.1 and pyecharts 2.0.3, and see the difference of them. 
In the html generated by pyecharts 1.9.1, you can move mouse on the bar of '五月' and '六月', then the tooltip of those bars will be shown. 
Howevr, in the html generated by pyecharts 2.0.3, the tooltip of  those bars within the area of line and xaxis are not triggered when mouse move above them.
the cause of this is "**z_level=1**"

**Comment by sunhailin-Leo** [comment]
@smilingsand 
* try this configuration
![image](https://github.com/pyecharts/pyecharts/assets/17564655/bcbb3bad-89b7-45d0-ab5f-5902f7102024)
![image](https://github.com/pyecharts/pyecharts/assets/17564655/d70a5995-ae59-4e14-82d2-5b06595de759)

* I think the reason is Echarts 4 has a different layer design from Echarts 5.
* About the default value, we are following the Echarts configuration document. https://echarts.apache.org/zh/option.html#series-line.z
