### ISSUE TITLE
changes in default axis setting in axisLineOpts, axisTickOpts, and splitLineOpts in pyecharts 2

### ISSUE THREAD

**Issue by smilingsand** [pyecharts/pyecharts#2187]
**问题**
default axis setting in axisLineOpts, axisTickOpts, splitLineOpts, are changed in pyecharts 2, which causes more codes and old code doesn't work as expected.

in pyecharts 1.9.x, you need not set the 'is_show' configuration for axisLine/axisTick/splitLine, since they are set as below in default, 

    axisLineOpt.is_show=True,
    axisTickOpt.is_show=True,
    splitLineOpt.is_show=False,

However, in pyecharts 2.0.3 ( i believe same for all 2.0+), those settings are changed in adverse:

    axisLineOpt.is_show=False/None,
    axisTickOpt.is_show=False/None,
    splitLineOpt.is_show=True,

so for each simple figure, you had to write code to explicitly set the configurations of axisLine/axisTick/splitLine.    

why to make these changes?

**运行环境（系统环境及 pyecharts 版本）**
windows/linux
python 3.9.x
pyecharts 2.0.3

**代码及截图**

    line.set_global_opts( # title_opts=opts.TitleOpts(title="盈利能力指标"),
                          yaxis_opts=opts.AxisOpts( name="盈利能力指标", name_location="center", name_rotate=90, name_gap=45 ,
                                                    axislabel_opts=opts.LabelOpts(formatter="{value}%"),
                                                    axisline_opts=opts.AxisLineOpts(is_show=True),                                 # added for pyecharts 2.0.3
                                                    axistick_opts=opts.AxisTickOpts(is_show=True, is_inside=False),      # added for pyecharts 2.0.3                                
                                                    splitline_opts=opts.SplitLineOpts(is_show=False),                               # added for pyecharts 2.0.3
                                                  ),
                          xaxis_opts=opts.AxisOpts( is_inverse=True,
                                                    axislabel_opts=opts.LabelOpts(rotate=30),
                                                    axisline_opts=opts.AxisLineOpts(on_zero_axis_index=0),
                                                    splitline_opts=opts.SplitLineOpts(is_show=False),                                # added for pyecharts 2.0.3
                                                  ),

**Comment by sunhailin-Leo** [comment]
@smilingsand 
* In `AxisOpts`, we just only change from `splitline_opts = SplitLineOpts(),` to `splitline_opts = SplitLineOpts(is_show=True),` because of the upgrade version from 1.9.x to 2.x.
* pyecharts 2.x version is based on Echarts 5.x, 1.9.x based on Echarts 4.x. So it will cause some API changes.
