### ISSUE TITLE
waterfall works wrong when total is negative 

### ISSUE THREAD

**Issue by smilingsand** [pyecharts/pyecharts#2188]
**问题**
waterfall chart works wrong when out is large to make total in negative. 
please see sample code and result in below.

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.x, 2.x

**代码及截图**
    
      from pyecharts.charts import Bar
      from pyecharts import options as opts
      
      x_data = [f"11月{str(i)}日" for i in range(1, 12)]
      
      #case 1 when out is small
      #y_total = [0, 900, 1200, 900, 900,]
      #y_in = [900, 300, 200, "-", "100"]
      #y_out = ["-", "-", "-", 500, "-"]
    
      #case 2 when out is large to make total in negtive
      y_total = [0, 900, 1200, -600, -600,]
      y_in = [900, 300, 200, "-", "100"]
      y_out = ["-", "-", "-", 2000, "-"]
      
      bar = (
          Bar()
          .add_xaxis(xaxis_data=x_data)
          .add_yaxis(
              series_name="",
              y_axis=y_total,
              stack="总量",
              itemstyle_opts=opts.ItemStyleOpts(color="rgba(0,0,0,0)"),
          )
          .add_yaxis(series_name="收入", y_axis=y_in, stack="总量")
          .add_yaxis(series_name="支出", y_axis=y_out, stack="总量")
          .set_global_opts(yaxis_opts=opts.AxisOpts(type_="value"))
          #.render("bar_waterfall_plot.html")
      )
      
      bar.render_notebook() 

![WF_result](https://github.com/pyecharts/pyecharts/assets/126098205/566e94ce-a4d0-4fe1-8851-018db95f0cac)

**Comment by sunhailin-Leo** [comment]
@smilingsand 
* I test your data on Echarts online editor. The snapshot result is the same as pyecharts. If you think the result have some problem, you can make an issue on Echarts main repo: https://github.com/apache/echarts/issues/new/choose
![image](https://github.com/pyecharts/pyecharts/assets/17564655/a3eec8dd-c3b0-4992-95a1-ded2c67429ee)
