### ISSUE TITLE
关于数据传输问题

### ISSUE THREAD

**Issue by kiki-cheng-zhou** [pyecharts/pyecharts#2189]
**问题**
你好，
请问pyecharts是完全离线的吗？
比如说我在本地可视化了一个csv文件，这个文件是会被上传到云端(?)或者会被其他第二者看到吗？
已经阅读过readme,但是并没有相关记载，希望作者能帮忙解答一下。

谢谢

**Comment by sunhailin-Leo** [comment]
@kiki-cheng-zhou 
* 如果用本地的 js 资源的话，可以做到完全离线的。
* 如果只是引入一个包的，会访问我们仓库自建的 CDN 中的 echarts 相关的静态资源

**Comment by kiki-cheng-zhou** [comment]
感谢回答！！！
