### ISSUE TITLE
运行graph得到和弦图，鼠标悬停在图例上不能正确显示所有同一category下的元素。

### ISSUE THREAD

**Issue by TotoDT2023** [pyecharts/pyecharts#2192]
**问题**
运行graph得到和弦图，鼠标悬停在图例上不能正确显示所有同一category下的元素。

**运行环境（系统环境及 pyecharts 版本）**
win11，pyecharts 2.0.3

**代码及截图**
图表在这里：https://totodt2023.github.io/IMM/
graph = (
    Graph(init_opts=opts.InitOpts(width="1200px", height="900px"))
    .add(
        "",
        nodes=node,
        links=links,
        repulsion=3000,

        tooltip_opts=opts.TooltipOpts(trigger="item",is_show=True,trigger_on="click",is_show_content=True,
                                      formatter="{b}: {c}",is_confine=True,padding=5,),

        layout="force",
        is_rotate_label=True,
        linestyle_opts=opts.LineStyleOpts(color="source", curve=0,opacity=1,width=0.5,type_="dashed"),
        edge_length = 3,
        label_opts=opts.LabelOpts(position="right",is_show=True)        ,
        categories=[{"name": category} for category in  sorted(set(node_categories.values()),key=lambda x: int(x[4:]))],
        is_draggable=True,
    )
    .set_series_opts(label_opts=opts.LabelOpts(position="right"))
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Internal and External Actions"),
        legend_opts=opts.LegendOpts(
            orient="vertical", pos_left="2%", pos_top="10%",selected_mode="multiple")

    )
)

**Comment by sunhailin-Leo** [comment]
@TotoDT2023 
* 能提供一个 categories 里的数据看一下嘛？

**Comment by TotoDT2023** [comment]
@sunhailin-Leo 你好，我想表达的是，鼠标悬停在图例的某一个category上，图表可以显示所有该category下的nodes。现在的图， 我把鼠标放在不同的图例上，显示的都是同一个node。
以下是categories的内容，我觉得应该有opts可以更改，但是试验以后还是不对。
[{'name': 'DOP 1'}, {'name': 'DOP 2'}, {'name': 'DOP 3'}, {'name': 'DOP 4'}, {'name': 'DOP 5'}, {'name': 'DOP 6'}, {'name': 'DOP 7'}, {'name': 'DOP 8'}, {'name': 'DOP 9'}, {'name': 'DOP 10'}, {'name': 'DOP 11'}, {'name': 'DOP 12'}]
另外，Echarts官方的示例，也没有办法在图例上进行悬停筛选。

**Comment by sunhailin-Leo** [comment]
@TotoDT2023 
* 如果需要的话估计要写 js 的回调函数，除此之外目前别无他法~
