### ISSUE TITLE
title 标题设置了，但还是没法显示，查看html里面也没生成这段代码。

### ISSUE THREAD

**Issue by taomou** [pyecharts/pyecharts#2193]
**问题**
bar中设置了title，但是渲染图中没有生成title文字。
查看html，里面也没有。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts2，

**代码及截图**

**Comment by taomou** [comment]
继续补充，当我设置了title后，可以显示，
但如果添加提示框设置
bar.set_global_opts(tooltip_opts=opts.TooltipOpts(trigger='axis'))
然后就冲突了。没有title显示了。

**Comment by sunhailin-Leo** [comment]
@taomou 
* 能给一段示例代码我这边测试下嘛？

**Comment by taomou** [comment]
@sunhailin-Leo 
老师您好。我后面发现了，可能是我没有用链式调用的问题。
我将set_global_opts 下title_opts,xaxis_opts等，分别写成多个：
set_global_opts(title_opts)
set_global_opts(xaxis_opts)
的形式。
将他们组合在一个里面没有问题。
set_global_opts(
title_opts,
xaxis_opts
)

这个应该是我的问题。您看看是否是这样。

**Comment by sunhailin-Leo** [comment]
@taomou 
* `set_global_opts` 尽量写成一个哈，不然的话会以最后一次覆盖所有的配置
