### ISSUE TITLE
sankey图上怎么添加数值

### ISSUE THREAD

**Issue by wuhanlt** [pyecharts/pyecharts#2194]
sankey图没有添加数值的参数，该怎么操作呢？

**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@wuhanlt 
* 不太理解你的问题。最好给个图描述一下吧。。

**Comment by wuhanlt** [comment]
> @wuhanlt
> 
>     * 不太理解你的问题。最好给个图描述一下吧。。
谢谢！
就是在相应的位置能够永久的显示数值，目前只能是鼠标移动到所在位置临时的显示，如下图箭头所指的所示
![sankey](https://github.com/pyecharts/pyecharts/assets/17676972/49417a23-8472-4882-913e-69aec416bc76)

**Comment by sunhailin-Leo** [comment]
@wuhanlt 
* 这个是通过 edgeLabel 配置的，不过现在 pyecharts 没加上去。后续版本更新后，我这边会加上去的~

**Comment by wuhanlt** [comment]
> @wuhanlt
> 
>     * 这个是通过 edgeLabel 配置的，不过现在 pyecharts 没加上去。后续版本更新后，我这边会加上去的~

谢谢大神！
