### ISSUE TITLE
求问pyecharts如何创建下拉框进行筛选？

### ISSUE THREAD

**Issue by Gaogaogaoo** [pyecharts/pyecharts#2195]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by Gaogaogaoo** [comment]
`from pyecharts import options as opts
from pyecharts.charts import Graph
from pyecharts.globals import CurrentConfig, NotebookType
from pyecharts.charts import Page # 导入Page模块

nodes = [
      {"name": "结点1", "symbolSize": 10},
      {"name": "结点2", "symbolSize": 20},
      {"name": "结点3", "symbolSize": 30},
      {"name": "结点4", "symbolSize": 40},
      {"name": "结点5", "symbolSize": 50},
      {"name": "结点6", "symbolSize": 40},
      {"name": "结点7", "symbolSize": 30},
      {"name": "结点8", "symbolSize": 20},
  ]
links = []
for i in nodes:
    for j in nodes:
        links.append({"source": i.get("name"), "target": j.get("name")})

c = (
      Graph(init_opts=opts.InitOpts(chart_id="123"))
      .add("", nodes, links, repulsion=8000)
      .set_global_opts(title_opts=opts.TitleOpts(title="Graph-基本示例"))
  ).render('test0629.html')`

**Comment by Gaogaogaoo** [comment]
> 问题：pyecharts如何创建下拉框进行筛选？
运行环境：windows，pyecharts1.9.1

**Comment by sunhailin-Leo** [comment]
@Gaogaogaoo 
* 下拉框是前端的功能哈，跟 pyecharts 没有关系

**Comment by Gaogaogaoo** [comment]
请问大佬，关系图的节点显示的名字可以改变吗？
场景：加了筛选框，筛选中的节点显示不变，未选中的节点对其名字进行脱敏处理



在 2023-06-30 10:02:39，"LeoSun" ***@***.***> 写道：

@Gaogaogaoo

下拉框是前端的功能哈，跟 pyecharts 没有关系
