### ISSUE TITLE
({"theme": pyecharts.globals.ThemeType.LIGHT})这种方法添加globals.ThemeType没有提示词

### ISSUE THREAD

**Issue by Allfather9** [pyecharts/pyecharts#2196]
**问题**
from pyecharts.globals import ThemeType才有提示词
但是在timeline = pyecharts.charts.Timeline({"theme": pyecharts.globals.ThemeType.LIGHT})这句代码中的字典中只有pyecharts
有提示词，之后global和ThemeType均无提示词需要自己打

**运行环境（系统环境及 pyecharts 版本）**
python3.10，conda环境，pyecharts最新版本

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Allfather9 
* 我觉得你可能不太理解 Python 包结构
* （或许应该用 vim 写代码锻炼一下，过度依赖提示词的坏习惯）
