### ISSUE TITLE
如何设置绘制出的柱形图的最大高度

### ISSUE THREAD

**Issue by Suxiuzhen** [pyecharts/pyecharts#2197]
**问题**
我在pyqt中嵌入了四个pyecharts绘制的柱形图，但是他的大小总是固定的，即使我的数据比较小，导致在页面中总是有ScrollBar出现，我不知道该如何解决它，也没找到解决的方法。

**运行环境（系统环境及 pyecharts 版本）**
系统环境: python3.7.5
pyecharts: 2.0.3

**代码及截图**
代码：
import sys
from PyQt5 import QtWidgets, QtCore, QtWebEngineWidgets
from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.faker import Faker

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setWindowTitle("PyQt5 Layout Example")
        self.setGeometry(100, 100, 800, 600)

        # 创建布局容器
        layout = QtWidgets.QVBoxLayout()

        # 第一行布局
        row1_layout = QtWidgets.QHBoxLayout()
        combo1 = QtWidgets.QComboBox()
        combo1.addItem("Option 1")
        combo1.addItem("Option 2")
        combo2 = QtWidgets.QComboBox()
        combo2.addItem("Option A")
        combo2.addItem("Option B")
        time_picker = QtWidgets.QDateTimeEdit()
        time_picker.setDateTime(QtCore.QDateTime.currentDateTime())

        row1_layout.addWidget(combo1)
        row1_layout.addWidget(combo2)
        row1_layout.addWidget(time_picker)

        # 第二行布局
        row2_layout = QtWidgets.QGridLayout()

        # 创建Pyecharts柱形图
        chart1 = self.create_bar_chart()
        chart2 = self.create_bar_chart()
        chart3 = self.create_bar_chart()
        chart4 = self.create_bar_chart()

        # 将每个格子的HTML代码放入QWebEngineView
        web_view1 = QtWebEngineWidgets.QWebEngineView()
        web_view1.setHtml(chart1)
        web_view2 = QtWebEngineWidgets.QWebEngineView()
        web_view2.setHtml(chart2)
        web_view3 = QtWebEngineWidgets.QWebEngineView()
        web_view3.setHtml(chart3)
        web_view4 = QtWebEngineWidgets.QWebEngineView()
        web_view4.setHtml(chart4)

        # 设置每个格子的位置
        row2_layout.addWidget(web_view1, 0, 0)
        row2_layout.addWidget(web_view2, 0, 1)
        row2_layout.addWidget(web_view3, 1, 0)
        row2_layout.addWidget(web_view4, 1, 1)

        # 将第一行和第二行布局添加到主布局容器中
        layout.addLayout(row1_layout)
        layout.addLayout(row2_layout)

        # 创建一个 QWidget 作为主窗口的中心部件
        central_widget = QtWidgets.QWidget()
        central_widget.setLayout(layout)
        self.setCentralWidget(central_widget)

    def create_bar_chart(self):
        bar = (
            Bar()
            .add_xaxis(Faker.choose())
            .add_yaxis("Series 1", Faker.values(), category_gap="50%", bar_width=20)
            .set_global_opts(
                title_opts=opts.TitleOpts(title="Bar Chart"),
                # toolbox_opts=opts.ToolboxOpts(),
                tooltip_opts=opts.TooltipOpts(
                    is_show=True, trigger="axis", axis_pointer_type="shadow"
                ),
                yaxis_opts=opts.AxisOpts(
                    interval=300
                )
                # graphic_opts=[opts.GraphicGroup(
                #     graphic_item=opts.GraphicItem(
                #         left="10%", top="10%", z=100, bounding="raw", is_ignore=False
                #     ),
                #     children=[
                #         opts.GraphicRect(
                #             graphic_item=opts.GraphicItem(left="center", top="center"),
                #             graphic_shape_opts=opts.GraphicShapeOpts(width=600, height=400),
                #         )
                #     ],
                # )],
            )
            .render_embed()
        )

        return bar

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()
    sys.exit(app.exec_())

截图：
![image](https://github.com/pyecharts/pyecharts/assets/34338690/e49995dc-a553-4edd-a8e2-c180434650bb)

**Comment by Suxiuzhen** [comment]
@sunhailin-Leo 及其他家人们，请帮忙看一下是什么问题，我以前在使用vue+Echarts时没有遇到过此类情况

**Comment by Suxiuzhen** [comment]
解决了，不是用自带方法解决的，我怀疑没有这个方法

**Comment by Vinny1210** [comment]
我在用pyside6做dashboard的时候也遇到了同样的问题，正常的自适应大小应该可以把初始设置的长宽都设为100%就可以，但是如图所示，宽度是自适应了，高度却没有，经过我 的测试发现高度却只有100px,而不是100%，所以才呈现出被压扁的效果。@Suxiuzhen请教一下你是怎么解决整个问题的
![image](https://github.com/pyecharts/pyecharts/assets/132733625/46cc6d2e-68b7-4d28-9a4e-50e611904d5f)
![image](https://github.com/pyecharts/pyecharts/assets/132733625/e7d5d045-41d3-4b9c-a251-ba3e32a41f86)

**Comment by Suxiuzhen** [comment]
![image](https://github.com/pyecharts/pyecharts/assets/34338690/76a0c3de-17d4-45d1-a295-5012b70cc17e)
我是手动替换的，因为生成的html宽高是固定的，注意根据你的布局来动态获取主窗口的宽高来设置这个宽高值

**Comment by Suxiuzhen** [comment]
@Vinny1210
