### ISSUE TITLE
how to format tootlip data ?

### ISSUE THREAD

**Issue by dberardo-com** [pyecharts/pyecharts#2198]
in the javascript version of the API one would pass a custom JS formatter function, but how to achieve this in pyecharts ? 

the use cases are:

* round to 2 decimals 5.5555 --> 5.56
* format in a locale aware way: example --> US 5,555.33 --> EU 5.555,33

these are quite important use cases !!

**Comment by sunhailin-Leo** [comment]
@dberardo-com 
* In pyecharts, we have some arguments like `formatter` in `tooltipOpts, labelOpts...etc`, so you can pass a `JsCode('js code')` to achieve what you want.

**Comment by dberardo-com** [comment]
thanks a lot, i could not find any documentation regarding JsCode ... is there a specific page in the doc?

**Comment by sunhailin-Leo** [comment]
> thanks a lot, i could not find any documentation regarding JsCode ... is there a specific page in the doc?

Like this
![image](https://github.com/pyecharts/pyecharts/assets/17564655/af890f70-edf5-43ab-9b91-e9544b4fd33c)

**Comment by dberardo-com** [comment]
where is JSCode exported from ?

**Comment by dberardo-com** [comment]
ok got it from pyecharts.commons.utils import JsCode
