### ISSUE TITLE
pyecharts不能被pyinstaller打包成exe文件吧。

### ISSUE THREAD

**Issue by nejinn** [pyecharts/pyecharts#220]
![image](https://user-images.githubusercontent.com/31615794/31700225-85ebf574-b3fa-11e7-9d48-3821f6756d5a.png)

我打包了一个exe，检测运行错误，直接就是没有图中那个文件，连图中那个pyecharts的目录都没有。

**Comment by chfw** [comment]
https://github.com/chenjiandongx/pyecharts/blob/master/docs/en-us/doc_for_pyechart_developer.md#why-the-folder-pyechartstemplatesjs-is-empty

**Comment by dongdawang** [comment]
不知道你解决这个问题没。
我遇到同样问题了，当我使用``-F``模式时，出现No such file or directory: ``xxxxx\\Temp\\_MEIxxxxx\\pyecharts\\templates\\js\\echarts\\register.json``的错误，我去源码中看了下，实际上代码中标明时是在当前文件夹下寻找``pyecharts\\templates\\js\\echarts\\register.json``，但是我不明白，也不知道在``-F``模式下程序会寻找_MEIxxxx文件夹下的资源。我最终的解决办法是不使用-F模式，在生成的``dist\\yourapp\\``下放入``pyecharts\\templates``文件夹就可以了，templates文件夹及其下的文件可以在你安装pyecharts包的路径下找到。

**Comment by YanNIU2028** [comment]
可以解决2D的问题，3D即使复制template还是不行

**Comment by paulwinflo** [comment]
> 不知道你解决这个问题没。
> 我遇到同样问题了，当我使用`-F`模式时，出现No such file or directory: `xxxxx\\Temp\\_MEIxxxxx\\pyecharts\\templates\\js\\echarts\\register.json`的错误，我去源码中看了下，实际上代码中标明时是在当前文件夹下寻找`pyecharts\\templates\\js\\echarts\\register.json`，但是我不明白，也不知道在`-F`模式下程序会寻找_MEIxxxx文件夹下的资源。我最终的解决办法是不使用-F模式，在生成的`dist\\yourapp\\`下放入`pyecharts\\templates`文件夹就可以了，templates文件夹及其下的文件可以在你安装pyecharts包的路径下找到。

您好，您的pyecharts程序已经打包成功了么？
