### ISSUE TITLE
多次添加Bar，Y轴坐标错误

### ISSUE THREAD

**Issue by xtsbrose** [pyecharts/pyecharts#2200]
Hello

我碰到一个问题，在向一个grid中添加多次stack bar，bar的y轴起始位置不是总是从0%开始，左上第一个正确，右下第二个从100%开始，第三个左下从200%开始。

win10+ pyecharts 2.0.3

![Screenshot 2023-07-11 123559](https://github.com/pyecharts/pyecharts/assets/122522345/13ad4b82-2231-4b67-80b8-7002ef4b5cd2)

**Comment by sunhailin-Leo** [comment]
@xtsbrose 
* 能提供下代码嘛？只有图的话比较难复现哈～
