### ISSUE TITLE
Gauge scale overlapping

### ISSUE THREAD

**Issue by fergie21** [pyecharts/pyecharts#2201]
Hello,
is there an option to adjust the Gauge so that the numbers don't overlap the scale ?
![image](https://github.com/pyecharts/pyecharts/assets/96333453/d6657c72-a790-4530-8eb8-8906651f4b71)

**Comment by sunhailin-Leo** [comment]
@fergie21 
* What version did you use？
* Can you show me your codes？thx～

**Comment by fergie21** [comment]
`    
        gauge_chart_by_process = Gauge(init_opts=opts.InitOpts(width='600px', height='400px'))
        gauge_chart_by_process.add("", [(f'{self.name}', self.value)],
                                   radius="100%",
                                   start_angle=180,
                                   end_angle=0,
                                   detail_label_opts=opts.GaugeDetailOpts(offset_center=[0, "20%"],
                                                                          font_size=15,
                                                                          color='black',
                                                                          font_weight='bold',
                                                                          formatter=f'{self.value} %',
                                                                          ),
                                   title_label_opts=opts.GaugeTitleOpts(font_size=18,
                                                                        font_weight='bold',
                                                                        color="blue",
                                                                        font_family="Microsoft YaHei",
                                                                        offset_center=[0, "35%"]
                                                                        )
                                   )
        gauge_chart_by_process.set_global_opts(
            legend_opts=opts.LegendOpts(is_show=False),
            tooltip_opts=opts.TooltipOpts(is_show=True, formatter="{a} <br/>{b} : {c}%"),
        )
        gauge_chart_by_process.set_series_opts(
            axisline_opts=opts.AxisLineOpts(
                linestyle_opts=opts.LineStyleOpts(
                    color=[[0.5, "#cc0000"], [0.8, "#e6b800"], [1, "#008000"]], width=20
                )
            )
        )

   `

I am using pyecharts version 2.0.3

**Comment by sunhailin-Leo** [comment]
@fergie21 
* add `axislabel_opts=opts.LabelOpts(distance=25)` this configuration in `add function
