### ISSUE TITLE
tab分页组件

### ISSUE THREAD

**Issue by sherlocklibo** [pyecharts/pyecharts#2202]
**tab分页组件,tab.add添加的个数的有限的，能不能解决**

**python 3.9  pyecharts2.0.3**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@sherlocklibo 
* 哪里有限了？

**Comment by sherlocklibo** [comment]
有限啊，


tab.add()不能超过灰色的条形长度，否则报错“列表超长”


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyecharts/pyecharts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] tab分页组件 (Issue #2202)





 
@sherlocklibo
  
哪里有限了？

**Comment by sunhailin-Leo** [comment]
@sherlocklibo 
* 源码：https://github.com/pyecharts/pyecharts/blob/master/pyecharts/charts/composite_charts/tab.py#L73
* 1、什么叫灰色的条形长度？
* 2、Show me your code...

**Comment by sherlocklibo** [comment]
上方灰色的条形框就是名称填满了，就不能在添加了，您可以试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyecharts/pyecharts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 中午12:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] tab分页组件 (Issue #2202)





 
@sherlocklibo
  
源码：https://github.com/pyecharts/pyecharts/blob/master/pyecharts/charts/composite_charts/tab.py#L73
 
1、什么叫灰色的条形长度？
 
2、Show me your code...

**Comment by sunhailin-Leo** [comment]
@sherlocklibo 图在哪？

**Comment by sherlocklibo** [comment]
我讲明白了吗？您看看能不能解决。
tab.add()分页组件能够添加的图形还是有限的，一旦超过名称灰色条形框长度就报错。



图形是我自己尝试做的，用的tab()分页组件。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyecharts/pyecharts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 中午12:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] tab分页组件 (Issue #2202)





 
@sherlocklibo 图在哪？

**Comment by sherlocklibo** [comment]
tab.add()超过一定个数，报错就是list index out of range


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyecharts/pyecharts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 中午12:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] tab分页组件 (Issue #2202)





 
@sherlocklibo 图在哪？

**Comment by sunhailin-Leo** [comment]
@sherlocklibo 
* 1、我一直不理解你说的灰色条形框是啥，其次你的 issue 也没有贴图，无法理解。
* 2、麻烦贴一下报错的图。

**Comment by sunhailin-Leo** [comment]
@sherlocklibo 别用邮箱回复图片，github 展示不了。如果你上传了的话

**Comment by sherlocklibo** [comment]
我知道问题了，解决了，不是那个问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月14日(星期五) 中午12:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pyecharts/pyecharts] tab分页组件 (Issue #2202)





 
@sherlocklibo 别用邮箱回复图片，github 展示不了。如果你上传了的话

**Comment by sherlocklibo** [comment]
谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月14日(星期五) 中午12:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pyecharts/pyecharts] tab分页组件 (Issue #2202)





 
@sherlocklibo 别用邮箱回复图片，github 展示不了。如果你上传了的话
