### ISSUE TITLE
y轴能否用鼠标拖动调整坐标轴刻度

### ISSUE THREAD

**Issue by sherlocklibo** [pyecharts/pyecharts#2203]
**suggestion:
Y轴能否实现像X轴时间轴组件一样，可以鼠标拖动实现Y轴的坐标轴刻度的放大和缩小**

**python3.9    pyecharts2.0.3**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@sherlocklibo 
* `datazoom` 组件适用于 X/Y 轴的
* https://gallery.pyecharts.org/#/Bar/bar_datazoom_slider_vertical

**Comment by sherlocklibo** [comment]
thanks.
能否同时实现datazoom_opts=opts.DataZoomOpts(orient="vertical"),  datazoom_opts=opts.DataZoomOpts(orient="honrizontal")
横坐标轴和纵坐标轴刻度都能够缩放

**Comment by sherlocklibo** [comment]
thanks:give me a favor.




from pyecharts.charts import Bar
bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.set_global_opts(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; title_opts=opts.TitleOpts(title=BT2),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; datazoom_opts=opts.DataZoomOpts(orient=["vertical",'horionzontal']),) #能否实现同时缩放
bar.render_notebook()







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyecharts/pyecharts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月17日(星期一) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts] y轴能否用鼠标拖动调整坐标轴刻度 (Issue #2203)





 
@sherlocklibo
  
datazoom 组件适用于 X/Y 轴的
 
https://gallery.pyecharts.org/#/Bar/bar_datazoom_slider_vertical

**Comment by sunhailin-Leo** [comment]
@sherlocklibo 
* 有没有一种可能，你传参数有问题呢？
* 源码的数据类型兼容一个或多个的配置。https://github.com/pyecharts/pyecharts/blob/master/pyecharts/types.py#L30

**Comment by sherlocklibo** [comment]
您帮我实现它呗，thank you very much!

**Comment by sunhailin-Leo** [comment]
> 

* 拒绝伸手党

**Comment by sunhailin-Leo** [comment]
> 

* 拒绝伸手党
