### ISSUE TITLE
目前pyecharts能否实现横坐标与纵坐标坐标轴同时缩放？

### ISSUE THREAD

**Issue by sherlocklibo** [pyecharts/pyecharts#2206]
**problem:
目前pyecharts能否实现横坐标与纵坐标坐标轴同时缩放？怎么实现？就是这个简单的问题**

**python3.9  pyecharts**

**
from pyecharts.charts import Bar
bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.set_global_opts(
                    title_opts=opts.TitleOpts(title=BT2),
                    datazoom_opts=opts.DataZoomOpts(orient=["vertical",'horionzontal']),)
bar.render_notebook()**

**Comment by sherlocklibo** [comment]
thank you very much!

**Comment by sunhailin-Leo** [comment]
@sherlocklibo 
* 不懂看 issue ？https://github.com/pyecharts/pyecharts/issues/2203#issuecomment-1637637888

**Comment by sherlocklibo** [comment]
from pyecharts.charts import Bar
bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.set_global_opts(
title_opts=opts.TitleOpts(title=BT2),
datazoom_opts=opts.DataZoomOpts(orient="vertical"),)
bar.render_notebook()

from pyecharts.charts import Bar
bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.set_global_opts(
title_opts=opts.TitleOpts(title=BT2),
datazoom_opts=opts.DataZoomOpts(orient='horionzontal'),)
bar.render_notebook()

第一个代码缩放Y轴
第二个代码缩放X轴，
X轴Y轴能否同时缩放，就是上面两个代码怎么同时实现。

**Comment by sunhailin-Leo** [comment]
@sherlocklibo 
* 你有看我的 `comment` 吗？
* `type hints` 写的很清楚 `datazoom_opts` 对应的类型是：
```python
_DataZoomType = Union[opts.DataZoomOpts, dict]
DataZoom = Union[_DataZoomType, Sequence[_DataZoomType], None]
```

**Comment by sherlocklibo** [comment]
好的，谢谢啦，我刚接触它




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月17日(星期一) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pyecharts/pyecharts] 目前pyecharts能否实现横坐标与纵坐标坐标轴同时缩放？ (Issue #2206)





 
@sherlocklibo
  
你有看我的 comment 吗？
 
type hints 写的很清楚 datazoom_opts 对应的类型是：
  _DataZoomType = Union[opts.DataZoomOpts, dict] DataZoom = Union[_DataZoomType, Sequence[_DataZoomType], None]
