### ISSUE TITLE
flask定时全量更新图表前后端分离Liquid中的add函数不起作用，页面获取不到数据

### ISSUE THREAD

**Issue by choorange** [pyecharts/pyecharts#2207]
<img width="242" alt="Snipaste_2023-07-19_19-31-45" src="https://github.com/pyecharts/pyecharts/assets/62871869/dce355b6-afaa-4f21-8c16-1f1e7ab4c99f">
<img width="504" alt="Snipaste_2023-07-19_19-31-58" src="https://github.com/pyecharts/pyecharts/assets/62871869/e043c0fd-04d2-4161-b95c-9115c303b8ca">
<img width="566" alt="Snipaste_2023-07-19_19-33-00" src="https://github.com/pyecharts/pyecharts/assets/62871869/5857daaf-9895-4e78-9f00-90a18a67e971">
<img width="550" alt="Snipaste_2023-07-19_19-33-16" src="https://github.com/pyecharts/pyecharts/assets/62871869/ba76042a-a7e5-494b-a7d2-3155d8b49a1d">
<img width="385" alt="Snipaste_2023-07-19_19-33-31" src="https://github.com/pyecharts/pyecharts/assets/62871869/77b8dfb4-ecd0-49e7-a9d4-a921570666d3">
<img width="582" alt="Snipaste_2023-07-19_19-38-56" src="https://github.com/pyecharts/pyecharts/assets/62871869/307a1749-318c-49da-b4c3-cd1296ed5734">
<img width="597" alt="Snipaste_2023-07-19_19-39-07" src="https://github.com/pyecharts/pyecharts/assets/62871869/d7444892-ec2a-494d-9c59-1850d8c5ed07">

**Comment by sunhailin-Leo** [comment]
@choorange 
* 有没有一种可能，前后端分离的时候少了个 js 文件呢？
* Liquid 现在不是 echarts 5 的核心图例，需要引入另外的 js 文件才能展示。

**Comment by choorange** [comment]
对的  我添加这个JS后就好了
<img width="665" alt="Snipaste_2023-07-20_09-06-32" src="https://github.com/pyecharts/pyecharts/assets/62871869/87a31774-b540-4c71-81b5-8ed7633f39ae">


我再用Table的时候也是前后端分离会报这个错误
'Table' object has no attribute 'dump_options_with_quotes'
网上没有查到资料，现在pyechart2.0支持了吗

**Comment by sunhailin-Leo** [comment]
@choorange 
* Table 不会支持的哈。因为 Table 本质还是 HTML 的原生标签。既然前后端分离了，那这个事情就应该前端来做，而不是后端。
