### ISSUE TITLE
提示框如何展示图片？

### ISSUE THREAD

**Issue by fun0515** [pyecharts/pyecharts#2208]
**问题**
我尝试在BMap散点图的提示框里展示图片，但图片始终加载不出来。我是通过在TooltipOpts里formatter参数来调用图像对象的<img src=\"./picture.png\" width=\"300\" height=\"300\">。这样是否可行，或者有其他展示图片的方法？

**运行环境（系统环境及 pyecharts 版本）**
Win7，python3.7,pyecharts2.0.3

**代码及截图**
tooltip_opts=opts.TooltipOpts(formatter="<b>{b0}</b><br />立项时间：2019.11<br />投资金额：2百万<br />"
                                                "<img src=\"./picture.png\" width=\"300\" height=\"300\">"),
![微信图片_20230720093124](https://github.com/pyecharts/pyecharts/assets/33153974/4727b6fd-f999-476c-bfd9-15aeceface68)

**Comment by sunhailin-Leo** [comment]
@fun0515 
* 可以看一下浏览器的控制台提示的报错信息吗？

**Comment by fun0515** [comment]
@sunhailin-Leo 谢谢你的回复，我解决问题了。原来'./'指的是html的当前目录，而不是代码的当前目录。我修改路径后现在就能正常显示图片了，谢谢你。
