### ISSUE TITLE
如何指定图例为图片

### ISSUE THREAD

**Issue by Kaiwen-Zhu** [pyecharts/pyecharts#2210]
**问题**
在一张有多条折线的折线图上，我希望将图例设置为图片（各折线图例的图片不同）。我知道在 echarts 中可以指定配置项的 "legend" "data" 字段来实现这一点（如下图），那么请问使用 pyecharts 可以实现吗？
<img width="391" alt="image" src="https://github.com/pyecharts/pyecharts/assets/90447017/82361a1d-a8e5-4757-8ab9-796672d1900d">

**Comment by sunhailin-Leo** [comment]
@Kaiwen-Zhu 
* 这块目前暂时还不行。
    * 主要因为 `legend` 的配置都是通过数据自动组装的。
