### ISSUE TITLE
如何禁用graph中link的鼠标悬停触发

### ISSUE THREAD

**Issue by Pyrokine** [pyecharts/pyecharts#2211]
因为关系图非常复杂，连线非常多，因此我只想要鼠标悬停在label上才触发高亮，想知道该怎么修改
以及，label的value里的内容能换行吗

**Comment by sunhailin-Leo** [comment]
@Pyrokine 
* 1、Label 的 value 用 formatter 写 js 回调函数就可以换行。
* 2、你说的高亮指的是哪一块？可以截图说明一下~

**Comment by Pyrokine** [comment]
> @Pyrokine
> 
> * 1、Label 的 value 用 formatter 写 js 回调函数就可以换行。
> * 2、你说的高亮指的是哪一块？可以截图说明一下~

1、能否详细说明一下
2、Graph中鼠标在节点或者线上悬停时与之关联的节点就会高亮，其他的变透明，我只想当且仅当鼠标悬停在节点上才触发这个事件，如图我指针在test5上面则高亮了关联节点
![2](https://github.com/pyecharts/pyecharts/assets/25692152/cfb3812b-646e-4bdc-93c0-7efe6b61d5d5)

3、有些节点如test2和test10默认就是半透明状态，这种情况怎么解决
![2023-08-07 10-57-08 的屏幕截图](https://github.com/pyecharts/pyecharts/assets/25692152/0c143156-95be-435f-bb1a-70f870f04a58)
4、想调整label的value的padding也是用js吗

**Comment by sunhailin-Leo** [comment]
@Pyrokine 
* Answer 1: 参考：https://gallery.pyecharts.org/#/Bar/stack_bar_percent
* Answer 2: 下一版给 `GraphLink` 的配置加上一些高亮相关的配置
* Answer 3: 这块有复现的 demo 嘛？
* Answer 4: 是内容本身吗？

**Comment by Pyrokine** [comment]
> @Pyrokine
> 
> * Answer 1: 参考：https://gallery.pyecharts.org/#/Bar/stack_bar_percent
> * Answer 2: 下一版给 `GraphLink` 的配置加上一些高亮相关的配置
> * Answer 3: 这块有复现的 demo 嘛？
> * Answer 4: 是内容本身吗？

1、在label_opts上加了formatter但好像没有效果，同时linestyle_opts没有formatter项
2、期待更新，暂时通过修改js屏蔽了事件
3、
虽然下面的demo不能在生成html时就触发bug，但鼠标在上面移动后label的透明度有几率不恢复（若无法触发可以适当缩放一下，中间区域更好触发）
`
from pyecharts import options as opts
from pyecharts.charts import Graph

step_x, step_y = 300, 40


def generate_html():
    graph_nodes, graph_links = [], []

    for i in range(64):
        graph_nodes.append(opts.GraphNode(
            name="this_is_a_very_long_name_" + str(i),
            x=step_x * (i % 4),
            y=step_y * int(i / 4),
            is_fixed=True,
            label_opts=opts.LabelOpts(
                color='black',
                font_size=20,
                position='top',
                distance=10,
                border_width=1,
                border_color='black'
            ),
            symbol_size=00
        ))
        for j in range(64):
            graph_links.append(opts.GraphLink(
                source="this_is_a_very_long_name_" + str(i),
                target="this_is_a_very_long_name_" + str(j),
                symbol=[None, 'arrow']
            ))

    graph = (
        Graph(init_opts=opts.InitOpts(
            width='1700px',
            height='900px',
            renderer='svg'
        ))
        .add(
            '',
            nodes=graph_nodes,
            links=graph_links,
            repulsion=5000,
            is_draggable=False,
        )
        .set_global_opts()
        .render('temp.html')
    )


if __name__ == '__main__':
    generate_html()
`
4、上面demo中的label相对边框的padding

**Comment by sunhailin-Leo** [comment]
@Pyrokine 
* Answer 1、在 `GraphNode` 的 `LabelOpts` 里面写 `formatter` 的回调函数试试？
* Answer 3、我试试看（有可能是 Echarts 的 Bug）
* Answer 4、`padding` 配置目前还没有在 `LabelOpts` 中，我会跟 `2.0.4` 版本一起带着发布。

**Comment by Pyrokine** [comment]
> @Pyrokine
> 
> * Answer 1、在 `GraphNode` 的 `LabelOpts` 里面写 `formatter` 的回调函数试试？
> * Answer 3、~我试试看（有可能是 Echarts 的 Bug）~ ---> 建议提 issue 给 Echarts 官方，我这边本地也发现有这个问题。
> * Answer 4、`padding` 配置目前还没有在 `LabelOpts` 中，我会跟 `2.0.4` 版本一起带着发布。

1、仿照这个[demo](https://gallery.pyecharts.org/#/Boxplot/multiple_categories?id=pyecharts-%e4%bb%a3%e7%a0%81-%e6%95%88%e6%9e%9c)写了下换行，但是<br/>直接输出到页面上了
```
graph_nodes.append(opts.GraphNode(
    name="this_is_a_very_long_name" + str(i),
    value="test",
    x=step_x * (i % 4),
    y=step_y * int(i / 4),
    is_fixed=True,
    label_opts=opts.LabelOpts(
        color='black',
        font_size=20,
        position='top',
        distance=10,
        border_width=1,
        border_color='black',
        formatter=('''
                function(param) { return [
                param.name,
                param.value
             ].join('<br/>'); }
         ''')
    ),
    symbol_size=0
))
```
3、在echarts提issue了

**Comment by sunhailin-Leo** [comment]
@Pyrokine 
* Answer 1：我后面再看看
* Answer 2：提的 issue 号发我下～

**Comment by Pyrokine** [comment]
> @Pyrokine
> 
> * Answer 1：我后面再看看
> * Answer 2：提的 issue 号发我下～

2: https://github.com/apache/echarts/issues/19009

**Comment by sunhailin-Leo** [comment]
@Pyrokine 
* 1、有两个 formatter，一个是 `Label`，一个是 `Tooltip` 的。剩下就是你自己调整了～
```python
from pyecharts import options as opts
from pyecharts.charts import Graph
from pyecharts.commons.utils import JsCode

step_x, step_y = 300, 40


graph_nodes, graph_links = [], []

for i in range(64):
    graph_nodes.append(
        opts.GraphNode(
            name="this_is_a_very_long_name_" + str(i),
            x=step_x * (i % 4),
            y=step_y * int(i / 4),
            is_fixed=True,
            label_opts=opts.LabelOpts(
                color="black",
                font_size=20,
                position="top",
                distance=10,
                border_width=1,
                border_color="black",
                formatter=JsCode("""
                function(param) { 
                    return [param.name, param.value].join('\\n'); 
                }
                """),
            ),
            symbol_size=00,
            value=i * 2,
        )
    )
    for j in range(64):
        graph_links.append(
            opts.GraphLink(
                source="this_is_a_very_long_name_" + str(i),
                target="this_is_a_very_long_name_" + str(j),
                symbol=[None, "arrow"],
            )
        )

graph = (
    Graph(init_opts=opts.InitOpts(width="1700px", height="900px"))
    .add(
        "test",
        nodes=graph_nodes,
        links=graph_links,
        repulsion=5000,
        is_draggable=False,
        tooltip_opts=opts.TooltipOpts(
            formatter=JsCode("""
            function(param) { 
                return param.name + '<br/>' + param.value; 
            }
            """)
        ),
    )
    .set_global_opts()
)
graph.render("issue_2211.html")
```
* 2、Echarts 的 issue 我这边会 follow，等 Echarts 那边修复了以后，我们这边也会同步更新一下渲染使用的 js 文件。

**Comment by Pyrokine** [comment]
> 

1、问题解决
2、提交bug的话需要填写很多东西，我可能没法跟进了
此外，非常感谢能及时回复
