### ISSUE TITLE
Grid.add 方法的grid_right的参数用不了

### ISSUE THREAD

**Issue by acracker** [pyecharts/pyecharts#2212]
pyecharts : 2.0.3

Grid.add 方法的grid_right的参数用不了, 我想把加入的饼图放到邮件应该怎么办?

这么用, 不管用
    grid.add(pie, opts.GridOpts(is_show=True, pos_right="right"))

**Comment by sunhailin-Leo** [comment]
@acracker 
* 饼图的中心坐标不受 `grid` 的控制，它自己有一个 `center` 参数控制的。
