### ISSUE TITLE
如何缩小K线之间的间距？

### ISSUE THREAD

**Issue by lovedancer075** [pyecharts/pyecharts#2213]
**问题**
如何缩小K线之间的间距？K线之间的间距看起来太大了（例如下图黄色的部分），想缩小一些，没有找到相关设置的地方，求告知。。。
![image](https://github.com/pyecharts/pyecharts/assets/117306586/77be79e8-f30b-438d-a34e-64f646d39fbc)

**运行环境（系统环境及 pyecharts 版本）**
2.0.3

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@lovedancer075 
* 下一个版本会加上这个配置：https://echarts.apache.org/zh/option.html#series-candlestick.barWidth

**Comment by an-orange-cat** [comment]
[series-candlestick.barWidth](https://echarts.apache.org/zh/option.html#series-candlestick.barWidth)
这个是指每个K线的宽度，并不是指每个K线之间的间隔哦。
期盼K线间隔的参数上线！ @sunhailin-Leo
