### ISSUE TITLE
3d line 不支持面积填充？

### ISSUE THREAD

**Issue by brealisty** [pyecharts/pyecharts#2214]
**问题**
似乎不支持3d折线图，面积填充。
2d中的面积图主要是因为add_yaxis中的areastyle_opts填充参数配置项
但是line3d中没有此项配置

**运行环境（系统环境及 pyecharts 版本）**
win11
python3.8
pyechart 2.0.3

**Comment by sunhailin-Leo** [comment]
@brealisty 
* Line3D 这块的图，目前 Echarts 支持的还是比较有限。目前也没有别的办法，只能等 Echarts 后续更新
