### ISSUE TITLE
缺少 MapGlobe 对象文档

### ISSUE THREAD

**Issue by onemade** [pyecharts/pyecharts#2215]
**问题**
MapGlobe  只有[范例代码](https://gallery.pyecharts.org/#/MapGlobe/map_globe_base)，未找到详细的说明文档。想知道如何设置3D地球的初始位置、角度及旋转速度，是否可通过程序控制地球中心视点的自动切换？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 2.0.3

**代码及截图**
https://gallery.pyecharts.org/#/MapGlobe/map_globe_base

**Comment by sunhailin-Leo** [comment]
@onemade 
* 麻烦把 issue 更新到 https://github.com/pyecharts/website
