### ISSUE TITLE
Build 2.0.3 cannot import Overlap module.

### ISSUE THREAD

**Issue by wanghao4023030** [pyecharts/pyecharts#2216]
**问题**
无法导入Overlap模块

**运行环境（系统环境及 pyecharts 版本）**
Pyechart 2.0.3
Python 3.9

**代码及截图**
from pyecharts.charts import Bar, Line, Pie,  Scatter, Page, Overlap

**Comment by wanghao4023030** [comment]
![image](https://github.com/pyecharts/pyecharts/assets/23066680/7113058f-66ab-40a2-b984-242aa10f8a48)
![image](https://github.com/pyecharts/pyecharts/assets/23066680/4d745349-adc1-409c-bb16-81a4bd1200b4)

**Comment by sunhailin-Leo** [comment]
@wanghao4023030 
* `overlap` 不需要 `import` 哈。https://gallery.pyecharts.org/#/Overlap/overlap_bar_line
