### ISSUE TITLE
跟Apache ECharts的最新版的例子比起来，目前最新版本的pyecharts在K线方面有2个问题。。

### ISSUE THREAD

**Issue by lovedancer075** [pyecharts/pyecharts#2217]
**问题**
问题一：K线与交易量无法对齐（修改了bar_width、category_gap属性还是无法对齐）
问题二：缺少鼠标的十字星线获得交易量和价格值

注：下图中是Apache ECharts的一个例子：
https://echarts.apache.org/examples/en/editor.html?c=candlestick-brush

**运行环境（系统环境及 pyecharts 版本）**
windows 11  /  python 3.9
version：2.0.3

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/117306586/8847db12-fa56-4397-ad12-6a4bee8802ba)

**Comment by sunhailin-Leo** [comment]
@lovedancer075 
* pyecharts 的哪个例子？

**Comment by lovedancer075** [comment]
通过查看https://gallery.pyecharts.org/#/Candlestick/professional_kline_brush问题一和问题二已经搞定，多谢提示！^_^
