### ISSUE TITLE
page生成html不能移动图表，点击save config没有反应

### ISSUE THREAD

**Issue by jobber-niu** [pyecharts/pyecharts#2218]
**问题**
通过page.render生成的html文件在本地打开时，图标不能移动，且save config点击无反应

**运行环境（系统环境及 pyecharts 版本）**
win11/pycharm 2023.1社区版/
python 3.10/pyecharts 2.0.3
浏览器：edge/google

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/125663741/adec1dae-04ea-423a-8e4d-9327bb390504)
![image](https://github.com/pyecharts/pyecharts/assets/125663741/910af295-2301-4d48-a108-55ef1d73ee9d)

**Comment by sunhailin-Leo** [comment]
@jobber-niu 
* 看一下浏览器的控制台是不是有报错？

**Comment by jobber-niu** [comment]
是的😰
![可视化大屏出错](https://github.com/pyecharts/pyecharts/assets/125663741/3bde91f0-beb1-4574-8c86-6520759e64f7)

**Comment by sunhailin-Leo** [comment]
@jobber-niu 
* 那就把缺少的静态资源补上就好了
