### ISSUE TITLE
如何在pyecharts中实现在地图上指定经纬度绘制饼状图、柱状图、不规则多边形、文本

### ISSUE THREAD

**Issue by MaKangChina** [pyecharts/pyecharts#2219]
**问题**
老师好，请问如何在pyecharts中实现在地图上绘制饼状图、柱状图，在echarts中有实现饼状图的功能，但利用grid形成的图件不能直接对应到具体的坐标点。

**运行环境（系统环境及 pyecharts 版本）**
win10/pycharm 2023.1社区版/
python 3.8/pyecharts 2.0.3

**代码及截图**
想要生成的效果：能够在指定的经纬度放置饼图（柱状图），且随着地图的放大相对位置固定
![image](https://github.com/pyecharts/pyecharts/assets/30001816/14d0c5fb-8360-45d1-a859-fa75c3bb7f3c)
目前基于grid形成的效果，地图缩放时柱状图不随着变化。
![image](https://github.com/pyecharts/pyecharts/assets/30001816/064367bc-9341-4507-a7c9-435de2ec9d43)

**Comment by sunhailin-Leo** [comment]
@MaKangChina 
* 有图 1 的 demo 代码嘛？或者 html 的源文件。

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 有图 1 的 demo 代码嘛？或者 html 的源文件。

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 有图 1 的 demo 代码嘛？或者 html 的源文件。

老师好，我是找别人帮我实现的。直接在html上写的。如下，请查收。


<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Awesome-pyecharts</title>
    <script type="text/javascript" src="./echarts.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/maps/china.js"></script>
</head>
<body>
    <div id="china" class="chart-container" style="width:1000px; height:600px;border:1px solid;"></div>
    <script>
    const data = ['A', 'B', 'C', 'D'].map((t) => {
      return {
        value: Math.round(Math.random() * 100),
        name: 'Category ' + t
      };
    });
    function randomPieSeries(center, radius,data) {
    return {
      type: 'pie',
      coordinateSystem: 'geo',
      tooltip: {
        formatter: '{b}: {c} ({d}%)'
      },
      label: {
        show: false
      },
      labelLine: {
        show: false
      },
      animationDuration: 0,
      radius,
      center,
      data//饼图的数据
    };
  }
  var chart_china = echarts.init(document.getElementById('china'), 'white', {renderer: 'canvas'});
  var option = {
    geo: {
      map: 'china',
      roam: true,
      itemStyle: {
        areaColor: '#e7e8ea'
      }
    },
    tooltip: {},
    legend: {},
    series: [
        //加饼图就按下面的函数格式添加
        //第一个参数为饼图位置，目前还不是经纬度，是坐标,
        //第二个参数为饼图半径
        //第三个参数为饼图所需数据，格式为数组[]，数组元素格式为｛value:xxx, name:yyy｝
      randomPieSeries([100, 33.01077], 15, data),
      randomPieSeries([100, 39.8], 25, [{value:250,name:'ltz'},{value:260,name:'ltz2'}]),
      randomPieSeries([120, 31.5], 30, [{value:100,name:'ltz'},{value:20
[map_pie_chart.zip](https://github.com/pyecharts/pyecharts/files/12331499/map_pie_chart.zip)
0,name:'ltz2'}]),

    ]
   };
     chart_china.setOption(option);
    </script>
</body>
</html>

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 有图 1 的 demo 代码嘛？或者 html 的源文件。

老师好，我是找别人帮我实现的。直接在html上写的。如下，请查收。
[map_pie_chart.zip](https://github.com/pyecharts/pyecharts/files/12331504/map_pie_chart.zip)

**Comment by sunhailin-Leo** [comment]
@MaKangChina
* 下一个版本我会把 Geo 图的 Pie 配置加上。目前没有支持在 Geo 类型上加 Pie 的配置

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 下一个版本我会把 Geo 图的 Pie 配置加上。目前没有支持在 Geo 类型上加 Pie 的配置
> * Ps: 顺带问一下，这种饼图在地图上的需求是什么？🤔
感谢老师！
我是搞油田管理方面的，我们每个油田有产油量产水量（还有油井水井等其他数据），通过这种带有地理信息坐标的饼图会非常清楚地看清楚目前整个区域（例如整个渤海湾、波斯湾）的生产状态。在咱们echarts里面也有这一类的图表（https://echarts.apache.org/examples/zh/editor.html?c=map-usa-pie）。此外，还有3方面的问题请教一下：
1、现在我通过修改html能实现pie的配置，但是柱状图的我确实没有实现。echarts上也没有相关的例子，但我觉得是一类问题。能否一起考虑。
2、能否建立多级的legend控制。例如：我贴图中有两类pie图形，能否设置更高一级别的筛选项，能够直接控制显示那一类。
3、再问问您下一版发布的时间，跟领导同事确定一下这个图件的研究计划。
感谢您的耐心解答！

**Comment by sunhailin-Leo** [comment]
@MaKangChina
* 1、柱状图我到时候试试看.
* 2、多级 legend 这个，目前 echarts 应该是没支持，估计得用 js 函数去控制。
* 3、下一版发布时间最迟月底前，快的话这个周日之前。

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 1、柱状图我到时候试试看.
> * 2、多级 legend 这个，目前 echarts 应该是没支持，估计得用 js 函数去控制。
> * 3、下一版发布时间最迟月底前，快的话这个周日之前。

太感谢了！
多级的这个是想实现gis中的图层概念，因为我们海上油田的开发，有管网、生产平台、输油气线路、还有地下的各类油田分布状态。如果能实现分级控制，就可以做到一张地图上包含非常多的信息，通过多级的筛选显示，对比分析也会大大方便。期待后续有多级的控制，这样geomap就算是做到超级实用了~期待！

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 1、柱状图我到时候试试看.
> * 2、多级 legend 这个，目前 echarts 应该是没支持，估计得用 js 函数去控制。
> * 3、下一版发布时间最迟月底前，快的话这个周日之前。

老师好，还有个功能希望您考虑。就是在地图上绘制不规则多边形。我们地下油藏及矿权都是不规则的多边形（甚至圆形，可以用多段线代替）谢谢

**Comment by sunhailin-Leo** [comment]
@MaKangChina 
* 类似这种？

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 类似这种？https://echarts.apache.org/examples/zh/editor.html?c=map-polygon

是的老师。不规则多边形，且可以填充不同的颜色。不同的多边形可以重叠。。透明度可以设置。

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 类似这种？https://echarts.apache.org/examples/zh/editor.html?c=map-polygon

老师好，跟领导同事讨论还漏了一个，就是在给定的坐标位置添加text文本，类似于这种，直接显示名称，还有悬浮显示相关信息。
https://echarts.apache.org/examples/zh/editor.html?c=geo-svg-map

**Comment by sunhailin-Leo** [comment]
@MaKangChina 
* 饼状图作为实验性更新加入到 verison 2.0.4
* 柱状图目前 Echarts 没有支持。
* 不规则多边形用 `ChartType.Custom` 中的 `renderItem`，编写对应的 Js 代码区展示。
* 文本的话用 `Tooltip` 的 `formatter` 实现哈～ (也是 Js 代码)

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 饼状图作为实验性更新加入到 verison 2.0.4
> * 柱状图目前 Echarts 没有支持。
> * 不规则多边形用 `ChartType.Custom` 中的 `renderItem`，编写对应的 Js 代码区展示。
> * 文本的话用 `Tooltip` 的 `formatter` 实现哈～ (也是 Js 代码)

老师好，这两天在外出差，没来得及跟您沟通，抱歉。柱状图这一块我搜索网络上有一些基于echarts实现了地图上显示。如下，谢谢老师！
https://blog.csdn.net/weixin_43412413/article/details/114281288
https://github.com/zhangqian00/echarts-map-bar
