### ISSUE TITLE
求助为什么出现了2个一模一样的x轴标签框？

### ISSUE THREAD

**Issue by lovedancer075** [pyecharts/pyecharts#2222]
**问题**
求助为什么出现了2个一模一样的x轴标签框？详见下图红色框：

**运行环境（系统环境及 pyecharts 版本）**
windows11 python3.9

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/117306586/6e9a4440-9667-4bc4-b44c-c66011c15f38)

**Comment by sunhailin-Leo** [comment]
@lovedancer075 
* 你的 axispointer 没有合并把？

**Comment by lovedancer075** [comment]
> @lovedancer075
> 
> * 你的 axispointer 没有合并把？

你好，大佬，axispointer怎么合并呢？

**Comment by sunhailin-Leo** [comment]
@lovedancer075 
* 看错了。我看了下 echarts 官方的实例也是这样的哈。暂时没找到啥配置可以弄掉

**Comment by lovedancer075** [comment]
> @lovedancer075
> 
> * 看错了。我看了下 echarts 官方的实例也是这样的哈。暂时没找到啥配置可以弄掉

噢噢好的谢谢
