### ISSUE TITLE
折线图，提示框无法展示更多信息

### ISSUE THREAD

**Issue by brealisty** [pyecharts/pyecharts#2223]
**问题**
折线图提示框默认展示的是：
series_name
x_axis: y_axis
现在我想展示附加的信息，比如：
series_name
x_axis: y_axis - y_name

散点图是可以通过传递二维数组来解决这个问题的：y = [[y轴数值1，其他信息],[y轴数值2， 其他信息]]
再配合jscode处理，即可展示更多信息。

但是折线图，二维数组[[1,'a'], [2,'b']]，或者数组字典，[{key1:value1}, {key2:value2}]，都无法实现，图中将不会存在任何数据。

**运行环境（系统环境及 pyecharts 版本）**
win11
python 3.8.0
pyecharts 2.0.3

**Comment by sunhailin-Leo** [comment]
@brealisty 
* 有 `LineItem` 的配置可以试一下。但是需要给 `TooltipOpts` 和 `LabelOpts` 写一个 Js 的回调进行展示
