### ISSUE TITLE
关系图的节点显示的名字可以改变吗？

### ISSUE THREAD

**Issue by Gaogaogaoo** [pyecharts/pyecharts#2226]
关系图的节点显示的名字可以改变吗？
场景：加了筛选框，筛选中的节点显示不变，未选中的节点对其名字进行脱敏处理

**运行环境（系统环境及 pyecharts 版本）**
python3.6， pyecharts1.9.1

**代码及截图**

**Comment by Gaogaogaoo** [comment]
比如1、2、3三个节点分别属于A、A、B机构，加了筛选框选定A机构后，节点3的名字需要脱敏显示为xxx公司，现在实现之后边就不显示了，如下图所示

期待您的回复







在 2023-08-22 16:48:02，"LeoSun" ***@***.***> 写道：

@Gaogaogaoo

截图描述一下

**Comment by sunhailin-Leo** [comment]
@Gaogaogaoo 
* 你有截图嘛？有截图的话，别用邮件回复。邮件回复 github 这边不会展示截图的。

**Comment by Gaogaogaoo** [comment]
截图已加



在 2023-08-22 17:25:59，"LeoSun" ***@***.***> 写道：

@Gaogaogaoo

你有截图嘛？有截图的话，别用邮件回复。邮件回复 github 这边不会展示截图的。

**Comment by sunhailin-Leo** [comment]
@Gaogaogaoo 
* 我说了。。你有截图的话别用邮件回复。

**Comment by Gaogaogaoo** [comment]
> @Gaogaogaoo
> 
> * 我说了。。你有截图的话别用邮件回复。

就是github上加的截图

**Comment by sunhailin-Leo** [comment]
@Gaogaogaoo 
* 你筛选框是自己实现的嘛？

**Comment by Gaogaogaoo** [comment]
> @Gaogaogaoo
> 
> * 你筛选框是自己实现的嘛？

是的

**Comment by sunhailin-Leo** [comment]
@Gaogaogaoo 
* 那你在筛选框调用的函数中同步刷新掉画图的配置，将你不需要展示的节点过滤掉

**Comment by Gaogaogaoo** [comment]
> @Gaogaogaoo
> 
> * 那你在筛选框调用的函数中同步刷新掉画图的配置，将你不需要展示的节点过滤掉

最后还是想显示这个环路，但是不属于本机构的节点名称需要脱敏

**Comment by sunhailin-Leo** [comment]
@Gaogaogaoo 
* 那针对的就是 node.name 本身嘛。。一样的逻辑

**Comment by Gaogaogaoo** [comment]
直接对node.name进行修改就会出现第二个截图所示的link不显示，是不是如果node.name变了，link就不知道连接哪个节点了？

**Comment by sunhailin-Leo** [comment]
@Gaogaogaoo 
* 那就对 `node.label.formatter` 写回调函数，同时对 `tooltip` 也做相同的操作。
* 效果就是所有数据本身不脱敏，只针对展示的部分做，你这个脱敏也只是前端做的。
