### ISSUE TITLE
How do I add lableLayout options, especially hideOverlap in sunburst chart

### ISSUE THREAD

**Issue by shubhra2** [pyecharts/pyecharts#2227]
**Question**

How do I add lableLayout options, especially hideOverlap for sunburst chart

**Operating environment (system environment and pyecharts version)**

python: 3.9.12
pyecharts version: 2.0.4

**Code and Screenshots**

```
series: {
  labelLayout: {
        hideOverlap: true
      }
}
```
Echarts documentation link: https://echarts.apache.org/en/option.html#series-sunburst.labelLayout.hideOverlap
Example: [hideOverlap example](https://echarts.apache.org/examples/en/editor.html?c=sunburst-simple&code=G4QwTgBAJiAuIQLwQNoCgIQN4cxAdiALYCmAXBAOQBCASpQDS6agA2AruRABxN4QBjABYBLVlDAl8FdP0w45eQqQqUAsgHFGzOW04UAjH0WDR4ydNRYCxLjRKsA9hAASjsCIBej_LBKMIPS4DCABfAF0dTFDjfmtlOwAFAFEAoMMGUzEJKRl421VaEgERADN_TPSIEIiw2Lx8lSpEgEk0kA5gzOFsizybJsoAFRJJAGcRQnbOwzDwuqjsAbsAZQBhaf1q7rMcyxRGu2oOUkJ2TeC5hcUFEwTVFcTtE0COrYAWev4e81zURbiyweAGPnNRRoQwFBnNCIGtiAAHRwXWYxAENIFUFagiCJEDsJwoiAAZjC6MiilCOgp12wOnuVDWAEFnngqgA2eo_PYyRa3RQMygAOWorMUVQATF88Ny-v8XvJMeofAJYD4iTVpYDBSshCQoCIQAINWSXjT-GibujBQB5IVi3RvLifdGyv6yBWHVTUEBQKQmy2epU22DwADuIADWoxgqG7h8aqJEtNJnNeCp_Bpgf5SoAIql6hyubs5R7tQUqNQAJpJna9d1eqgAGRA-CgYyE7FgSaugfLgyFbUqTooUqyv32jcobj1-CEtlY-B7tT7MYrwoA6hq6xP-oK1o4nABzfAVV4zaq96U5_iC2hPaNVIyuksNpVN9hQMMiI8dkDlfAIGICBaD1SYAzTaJqVwbN6XXDRRULEcIAATmLet9j5a112SIUtEfZCAHZozdTCFSWQVcxVEAxj8MAiXeWkXinFwAE9YD1KN0UVQUmx8aEl2HC9NW4ij1yGfFfHVISthqclFlXHj13WIZt3HHkrCVDRWBoo9HDDCCmLXQYNybFY1NIvdxMkecwA8MZDIzPAs2MHNBRaXMHSqABWdDd3lOQbyUdcAClEPRKoXReSyAuYpVqEcPT6Jkrhk0UwKlQkiYAGsiA6EBWMjFLRxTRRIKMpTBhC1Tiu2dTSynRJ2DAMNHGy0ZE1qmp5iczAXNwNz1xae0kOE3ydBistjKOeharHSbGrgKY5qvPk8ybCzX0nPMHFERzry0kKGJ3DSDiVJkhFIGAACNfQY1arReQU1BcB1-CqYkSK23lyKnC6rsII9wGXaNKrsNR2CIW6RADeTKQOwUN0Q88tl8-q30FABpQ9srgIqUa4bze2g6JXLgwYWhqnRIr8061sFYl3lrdHtsFAA1KQRAEM9JQewLsMGQiJTetlkKlF8MJ-oNBSFEAEVYEgHK6iqMplw98afUq5HK3qIH6-RyfBgANLzkIMZ9vm-2LptUEKmQ2rqToarT2F9fKACtwA1s2-biAXweSE2COEgAGL7Jc02MdMXEgEVbWAdI1EO5gUknaUGwYhlm6mzbDiaramsHVEZok0YWpUWlo1troJUvfZtqh3gMZny6xxwxhIbLHFY5ceoR9d3mF2rPpZqzBmx_BCqJUkVzT2Db3XABVczRtkiVOXziPC7EwYmVmgmMlHyP1wAMQKkhQxIYAxAV_asKe9cmQALRFlgxfD_zt_7JIhEcTmAA8uK_UyiQIgCIeY-11pmBS15_aqGZK_A-JILYmEmqJP6hAwJEDrulb-8DiDgBvsiZWuCG6UHhGAMY0kkEiWAbxduEAmT4CPA4RWGpaHS3XHxMYjDmGsJ4Qedgvge4rVIUXKgagRBgAQHxPKQDOGDCKFAA0zD5FxR1EaaRpxOpIKJmIneqxHBdiEBAFs7UIASV_hAi8aVQYGNUGzVsEAhTsFYkrGhKs8FUDZiIKusMzQwPpuuNYNoW4FynHxdgvjr6sFvqIvu987jBKpi8D6H86Z0PXEKdwEZWDZRBugpUKwjEcRrmAERHioHOUCTcPMGxaqfCPmdRGNFRDMLVIJJBjEVywIfoME-DsIrISiqgguhT9xyxIHCdwHQ1EmCnCFI02UqH4BiXEypdipwbkmHRVwIBgD-lEXDOQ6UpwaBZLVMu4TzoJ3jt7C8eiEmPSSRTQZqTkKfQlp_cZ65wSxKvjfaxslPFkNzMUOAzU5m1LvI4AQ2VSjuCgP41MNTVZDRGjQp2GMhptkNIQJErBfF32heuTGNZHZNIiUY6JgLiVosGE2C5SD5rXMFG4SG9ythpSefS8GTKnxYtZuuDcitYB7JalzIQdKvHqCHJiylSpaDdw6BAG0IB8kkJ5TKtQK9dGCrHoY4x-zDm6PruI4U9T5Wt3XLQDoJAfxSs1SrKcQpXoUutYMFwn4VnSoaHAqgQojrBw-Ok0sPzd5jDKaxXE4ANUbPDXYeERA_SdM1voqcagCo8JbLi1RJDNlKmyWADiEBwRgBYamyBxyLT9wHGzMJW8Ik0QgBzIG7jeY9MSQKLJ5Khmh1De6BN3owCODaqwVilabEgvNSfDgHZJhHgKZk8eC6BFGOEUuhRdghQkDDBAKs7g40doLTLXdZSjyOvjcu1YrFpECHYB3ZFZVUV-z6XYG0bq-0hq-Rkrd8DDyQxru2yBJ74JSPAEi0RoGGWtgEDROiT7tYvrITaTGm1G2ZQJGMTllxO3PO7YMRIFyv1cA3tFMZ174E6TAMsiAKxIZEBEN2KDQ7mhmF9A4BEogcOomg0kJjsBI3NQvVC3lqghhMgk2oKspb4zsBE_m1jlANzgEY_gWioxEPQPhkExRcrJT6uPoRkd18U3c17s6oplqBUKt4r6H1TrTn-uGCNEjFBPnka3kpg8_yWEwHWcepTahQFcaJSQ6t6ZekvLsEMIObmSQDrIn-qgTIH2wHAopyjlZPw8cvOmpU7LaLULTRF0mXa5Ds2I-8i8HnRleay-QoQ9l0utiE-W0TMraCSqIPxDrZCfHlsmIaUtJAjSXpKwEnTJKTL8rNmhWzylRuhgC3N4m2myThAANxoEcAidLPgkB0kwGqQ86WEQUBzB2fSFBYBgE4PUBFYA8qXzAP-og2ieECHXWKi7AhQiUBgsYDuHhFYXZ0LAVi4DVBjCEWU2iDoQvzgmGMMHigEX3pR1QfAPh_A6FXDAeAFACcgHqBYP0YAWzXQcCfdwT9RiOFzHjG7d2SCk99CIB9Mgw5UBQiHAApJQcI9QdJU9YKjuQI74B-FUNIg0szpSPee3RVQWBrqhF-_9vHwuQCi5bKxEp4v-CiD9DaA5YAdLnYgLdzgEAAD0tuOK-IgLt_bgFoSKwII4MVHdQFW-cFToCoAxA64VhASYEAESsWKLZQTeOYJoFCJtoAA)

If it is not possible then is there any workaround for hiding low value/overlapping labels?
![image](https://github.com/pyecharts/pyecharts/assets/48879830/81bde627-e427-43ac-83af-a8988f42bf81)

**Comment by sunhailin-Leo** [comment]
@shubhra2 
* I will fix it in next version~
