### ISSUE TITLE
Enhancement: Dynamic markpoint max/min values for Kline chart based on high and low fields

### ISSUE THREAD

**Issue by stiff-c** [pyecharts/pyecharts#2228]
**问题**
I've recently encountered a behavior in the Kline chart that I believe could be enhanced. When using the markpoint feature to dynamically mark the maximum and minimum values on a Kline chart, the library currently defaults to using the open field. This is a bit counterintuitive, as one would typically expect the maximum and minimum values to be derived from the high and low fields respectively.

Current Behavior:

The markpoint for max/min values uses the open field.
Expected Behavior:

The markpoint for max values should ideally use the high field.
The markpoint for min values should ideally use the low field.
I understand that the Kline data is typically organized in the ['open', 'close', 'low', 'high'] order, and the current behavior might be due to this ordering. However, I believe a slight adjustment to prioritize the high and low fields for the max/min markpoint would be more in line with general user expectations.

**运行环境（系统环境及 pyecharts 版本）**
Windows11
Python 3.9
pyecharts 2.0.4

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/101198367/e04566fa-6e0e-467f-9c54-87a9bd3c4502)

#....
v1 = [[round(value, 2) for value in item] for item in df.loc[:, ['open', 'close', 'low', 'high']].values]
t = df.index
v0 = list(t.strftime('%Y%m%d'))
v2 = [int(value) for value in df["vol"].tolist()]

kline = (
    Kline()
    .add_xaxis(v0)
    .add_yaxis(
        "K线图",
        v1,
        markpoint_opts=opts.MarkPointOpts(
            data=[
                opts.MarkPointItem(type_="max", name="最高价", symbol="pin", symbol_size=[80,30]),
                opts.MarkPointItem(type_="min", name="最低阶", symbol="pin", symbol_size=[80,30]),
            ]
        ),
        markline_opts=opts.MarkLineOpts(
            data=[
                opts.MarkLineItem(type_="average", name="平均值")
            ]
        )
    )
    #....
    )
)
#....

**Comment by sunhailin-Leo** [comment]
@stiff-c 
* You can use dict to set MarkPoint like 
```python
opts.MarkPointOpts(data=[{
      "name": "highest value",
      "type": "max",
      "valueDim": "highest"
}])
```
* In the next version, we will add `valueDim` config in `MarkPointItem`
