### ISSUE TITLE
support jupyterlab

### ISSUE THREAD

**Issue by nilday** [pyecharts/pyecharts#223]
希望提供jupyterlab的支持，不仅仅是老的jupyter

**Comment by qindiandadudu** [comment]
是的  jupyterlab应该是下一代jupyter notebook的雏形。往有志之士添加支持 @chfw @nilday @chenjiandongx

**Comment by 416104443** [comment]
render_notebook 函数好像没有了

**Comment by Zeroto521** [comment]
话说，支持jupyter的html文件下载的功能嘛？
* jupyter下
![Uploading 微信截图_20171218174240.png…]()

* 下载为html后
![_20171218174325](https://user-images.githubusercontent.com/25895405/34099718-40d2dce0-e41b-11e7-989e-b07ce5c669f2.png)

耸肩，¯\\_(ツ)_/¯

**Comment by Zeroto521** [comment]
话说，支持 jupyter 的 html 文件下载的功能嘛？
* jupyter
![_20171218174240](https://user-images.githubusercontent.com/25895405/34099788-773c3074-e41b-11e7-8253-a12d93b0fcc2.png)

* 下载为 html 后
![Uploading 微信截图_20171218174325.png…]()

耸肩，¯\(ツ)/¯

**Comment by Zeroto521** [comment]
话说，支持 jupyter 的 html 文件下载的功能嘛？

* jupyter
![](https://user-images.githubusercontent.com/25895405/34099788-773c3074-e41b-11e7-8253-a12d93b0fcc2.png)
*下载为 html 后
![_20171218174325](https://user-images.githubusercontent.com/25895405/34099835-9c70709e-e41b-11e7-93a7-69fbe97be721.png)

耸肩，¯(ツ)/¯

**Comment by chfw** [comment]
```
from pyecharts import online

online()
```
