### ISSUE TITLE
AxisTickOpts中怎么设置X轴不显示原点和最后一个的刻度线，is_show_last 在2.0.3中有没有这个参数，我查的还有2.1.0等版本，但是为什么releast中最新的版本是2.0.4？

### ISSUE THREAD

**Issue by sovereign-stone** [pyecharts/pyecharts#2230]
**问题**
1. AxisTickOpts中怎么设置X轴不显示原点和最后一个的刻度线
2. is_show_last 在2.0.3中有没有这个参数
3. 我查的还有2.1.0等版本，但是为什么releast中最新的版本是2.0.4

**运行环境（系统环境及 pyecharts 版本）**
- pyecharts版本：
  Name: pyecharts
  Version: 2.0.3
  Summary: Python options, make charting easier
- 系统：linux系统，pycharm

**代码及截图**
```
axistick_opts=opts.AxisTickOpts(
                    is_show=True,  # 是否显示刻度线
                    is_inside=False,  # 刻度线是否朝内显示，默认朝外显示
                    length=5,  # 刻度线长度
                    linestyle_opts=opts.LineStyleOpts(width=2, color="red")  # 刻度线样式
                ),
```

**Comment by sunhailin-Leo** [comment]
@sovereign-stone 
* 1、这块 Echarts 也没看到相关的配置
* 2、文档和源码里面没有就没有
* 3、你哪里看到有 2.1.0？

**Comment by sovereign-stone** [comment]
@sunhailin-Leo 
1、我从chatgpt问的，说我的版本太低，需要升级版本，稳定的版本为2.1.0
![image](https://github.com/pyecharts/pyecharts/assets/62974949/7f493ecf-c55c-45c7-8047-8909a2236ba6)

**Comment by sunhailin-Leo** [comment]
@sovereign-stone 
* 你不觉得它在胡说八道嘛？

**Comment by sovereign-stone** [comment]
好吧，知道了，谢谢啦！
