### ISSUE TITLE
dynamically update one chart based on the position/id of the item hovered/clicked from other chart in a Grid

### ISSUE THREAD

**Issue by shubhra2** [pyecharts/pyecharts#2231]
**Question**

How can I recreate this echart example using pyecharts?

**Operating environment (system environment and pyecharts version)**

python: 3.9.12
pyecharts version: 2.0.4

**Code and Screenshots**
[echarts example link](https://echarts.apache.org/examples/en/editor.html?c=dataset-link)

How can I dynamically update the pie chart data based on the position of my cursor hovering/clicking on the line chart as seen in the example?

I can show both line chart and pie chart using pyecharts Grid component but I don't see any way to link both charts from the pyecharts documentation

**Comment by sunhailin-Leo** [comment]
@shubhra2 
* Currently, we can not add js on-function (like on('click', function..) etc) now. 
* I'll consider compatibility with custom manipulation functions in an upcoming release, but it's just experimental and can be problematic.

**Comment by sunhailin-Leo** [comment]
@shubhra2 
* In the new version, we add an API `add_js_events`, so you can try to add js on-function.
* Closed it then waiting for the new version.
