### ISSUE TITLE
使用pandas绘制折线图后无法显示

### ISSUE THREAD

**Issue by Roych13** [pyecharts/pyecharts#2232]
**问题**

源码是这样的：
```
import pyecharts.options as opts
from pyecharts.charts import Line
import pandas as pd

df = pd.read_excel(r'c:\pydemo\line.xlsx')
df
x_label = df['Year'].values.tolist()
line = Line().add_xaxis(x_label)
for col in df.columns[1:]:
    print(col)
    print(df[col].values.tolist())
    line.add_yaxis(
        col, df[col].values.tolist(),
        is_smooth=True)
line.render('line_smooth.html')
```

**运行环境（系统环境及 pyecharts 版本）**
Windows 11，python 3.9.16，VScode， pyecharts 2.03/2.04

**代码及截图**
![微信截图_20230902120447](https://github.com/pyecharts/pyecharts/assets/39145668/0b3c7bea-5c1d-4890-9ae9-9c93e4c18ee2)

最终绘制的图片是这样的：
![成品](https://github.com/pyecharts/pyecharts/assets/39145668/f810a425-d3fc-4ef7-a322-739c13a325e0)

**Comment by Roych13** [comment]
现在看了下，可能是因为X轴（年份）没有转为字符串所致。

**Comment by sunhailin-Leo** [comment]
@Roych13 
* 得用原生数据结构哈~
