### ISSUE TITLE
2.0.2以上版本中is_selected出现失效

### ISSUE THREAD

**Issue by congcong009** [pyecharts/pyecharts#2234]
**问题**
2.0.2及以下没有问题，2.0.3及2.0.4会出现参数识别出错，选中属性无效

**运行环境（系统环境及 pyecharts 版本）**
python3.8、django、pyecharts2.0.3及以上

**代码及截图**

出现报错
TypeError: add_yaxis() got an unexpected keyword argument 'is_selected'

**Comment by sunhailin-Leo** [comment]
@congcong009 
* 哪个图？
