### ISSUE TITLE
pyecharts使用Bmap的API绘制POI散点图，发现定位不准

### ISSUE THREAD

**Issue by codeseeking** [pyecharts/pyecharts#2235]
**问题**
bmap的定位不准，怎么解决

**运行环境（系统环境及 pyecharts 版本）**
python:3.7.0
pyecharts:1.9.1

**代码及截图**
代码截图
![image](https://github.com/pyecharts/pyecharts/assets/33088494/14fc95c4-d321-47d4-99f7-13237b27add0)
结果截图
![image](https://github.com/pyecharts/pyecharts/assets/33088494/f2092932-d97a-4319-b7b8-d81155bdd462)

**Comment by codeseeking** [comment]
> @codeseeking
> 
> * 你的坐标点经纬度是从高德来的还是百度来的？

使用百度地图提供的地点检索api得到的https://lbsyun.baidu.com/index.php?title=webapi/guide/webservice-placeapi

**Comment by sunhailin-Leo** [comment]
@codeseeking 
* 你有申请百度地图的 key 嘛？

**Comment by codeseeking** [comment]
> @codeseeking
> 
> * 你有申请百度地图的 key 嘛？

有的，现在的情况就是数据已经有了，也按照这个Bmap需要的格式传入了数据，对于不在COORDINATES里面的数据，也使用了add_coordinate函数进行了添加，然后绘制出来的结果有问题，我特意拿了这个点去百度拾取系统进行定位，发现这个经纬度能够准确的定位。
![image](https://github.com/pyecharts/pyecharts/assets/33088494/86f16787-f884-403c-bb6e-357f7d95960a)

**Comment by sunhailin-Leo** [comment]
@codeseeking 
* 我这边测试了一下没有复现你的问题，或者你升级到 2.X 试试看。可能是 Echarts V4 和 V5 的差异导致的

**Comment by codeseeking** [comment]
我刚刚已经将pyecharts升级到2.0.4版本，然后使用代码没变，结果依然是如此，这个点的格式是['四川大学华西医院(温江院区)', [103.922656, 30.729111]]，然后下图是我设置的schema：
<img width="389" alt="1693970645138" src="https://github.com/pyecharts/pyecharts/assets/33088494/8f5bb15c-750d-41d8-a089-dafda4d51254">
我看网上有些答案是说要将坐标zhuanhua转化为像素点，不知道是不是这个原因，还是因为这个schema设置的中心点和缩放的问题。
如果可以，能不能发一下你的源码。

**Comment by sunhailin-Leo** [comment]
@codeseeking 
![image](https://github.com/pyecharts/pyecharts/assets/17564655/4c78996a-5358-4a58-8d1a-e5a06757b072)
![image](https://github.com/pyecharts/pyecharts/assets/17564655/1419b3ac-aa76-4138-ab39-4d1e98378bc5)

**Comment by codeseeking** [comment]
@sunhailin-Leo 好的，谢谢，我再排查一下
