### ISSUE TITLE
Tree存在小方框无法隐藏

### ISSUE THREAD

**Issue by qiyueliuhuo23** [pyecharts/pyecharts#2236]
**问题**
Tree图打开之后，在图片最上方存在方框，不知道该怎么隐藏或者删除，如下图所示。翻了一下gallery里面的示例，也都存在这个问题。如果使用toolbox进行树图的保存，该小方框依旧存在。

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/45259966/b9b8971a-dc63-4423-8438-bc3fd5b0a546)

**Comment by sunhailin-Leo** [comment]
@qiyueliuhuo23 
* 哪个版本的？

**Comment by qiyueliuhuo23** [comment]
- 版本是pyecharts 2.0.3
- 通过设置 LegendOpts 的 border_width 为 0，已解决，感谢~

**Comment by sunhailin-Leo** [comment]
@qiyueliuhuo23 
* 后续版本发布后会解决～
