### ISSUE TITLE
地图配置能否增加一个比例尺的设置？

### ISSUE THREAD

**Issue by WEiHJ404** [pyecharts/pyecharts#2237]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@WEiHJ404 
* Echarts 没有相关的配置哈~

**Comment by WEiHJ404** [comment]
那后期可以自己添加吗？

**Comment by sunhailin-Leo** [comment]
@WEiHJ404 
* 这个问题建议和 Echarts 那边去提
