### ISSUE TITLE
Map()自定义地图中坐标点位置不对

### ISSUE THREAD

**Issue by Zuo1ji** [pyecharts/pyecharts#2239]
**问题**
我要做一个四川省各市的地图+成都各县区的地区，然后pyecharts本身并没有这样的地图
于是在http://datav.aliyun.com/portal/school/atlas/area_selector
网站做了一个自定义地图并且从边界生成器下载了Geojson文件。
![image](https://github.com/pyecharts/pyecharts/assets/34649636/03794079-bf4b-455b-9fbe-e50d56f344c4)

使用Map（）作图后，各县市行政中心位置变成了区块的中心而不是行政中心的位置
如何解决这个问题？

**运行环境（系统环境及 pyecharts 版本）**
win10
pyecharts          2.0.4

**代码及截图**

with open('data.json','r',encoding='utf-8') as f:
    geojson=json.load(f)

map=(
    Map()
    .add("",data,maptype="custom_geo_json") 
    .add_geo_json(geo_json=geojson)
)
map.render('mymap.html')

![image](https://github.com/pyecharts/pyecharts/assets/34649636/7cc41a78-86fb-44ec-a2ac-75151ef7e188)

**Comment by sunhailin-Leo** [comment]
@Zuo1ji 
* 你传入了自定义的 geojson，内部坐标点与 geojson 的配置有关。
