### ISSUE TITLE
pyecharts 使用的地图有审图号吗？可以获取到地图的比例尺吗？

### ISSUE THREAD

**Issue by WEiHJ404** [pyecharts/pyecharts#2241]
**问题**
在文章发表的时候需要提供审图号和比例尺，所以能否提供上述的信息？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@WEiHJ404 
* 目前没有 Echarts 没有办法提供哈
