### ISSUE TITLE
Google Colab 无法显示图表

### ISSUE THREAD

**Issue by DaiZack** [pyecharts/pyecharts#2245]
**问题**
Google Colab 无法 用rend_notebook显示图表

**运行环境（系统环境及 pyecharts 版本）**
Google colab
pyecharts == 2.0.4

**代码及截图**
```
from pyecharts.charts import Bar

bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.load_javascript()

bar.render_notebook()
```

![image](https://github.com/pyecharts/pyecharts/assets/45176371/8b653ef9-5b4b-4c07-bdce-890e145f22b6)

**Comment by sunhailin-Leo** [comment]
@DaiZack 
* Colab 的 Notebook 暂时不清楚他怎么去渲染的。目前没办法 debug 哈~
* 或者你那边在渲染的时候，截图看一下 浏览器控制台的一些报错信息

**Comment by DaiZack** [comment]
这个是chrome console 的error:
```VM118:2 Uncaught ReferenceError: require is not defined
    at <anonymous>:2:9
    at wa.eval [as h] (output_binary.js:146:311)
    at ya (output_binary.js:11:141)
    at Aa.next (output_binary.js:11:440)
    at eval (output_binary.js:12:319)
    at new Promise (<anonymous>)
    at Ba (output_binary.js:12:212)
    at z (output_binary.js:12:351)
    at Pi (output_binary.js:146:35)
    at wa.eval [as h] (output_binary.js:145:547)```

<img width="1010" alt="image" src="https://github.com/pyecharts/pyecharts/assets/45176371/41527b79-04a3-4f5a-a857-df37830ee068">

**Comment by sunhailin-Leo** [comment]
@DaiZack 
* 有全一点的截图嘛？

**Comment by DaiZack** [comment]
@sunhailin-Leo  没有什么了就只有这两条一样的
<img width="1425" alt="image" src="https://github.com/pyecharts/pyecharts/assets/45176371/768d743b-e3f6-4465-907c-7b29f89048e8">

Error 展开后如下

<img width="478" alt="image" src="https://github.com/pyecharts/pyecharts/assets/45176371/555c0fe1-bc0f-42cb-bd7f-226d0a901c78">

<img width="437" alt="image" src="https://github.com/pyecharts/pyecharts/assets/45176371/d6da2855-0839-4607-8c12-66464933dce0">

<img width="574" alt="image" src="https://github.com/pyecharts/pyecharts/assets/45176371/024678a7-3f06-4b89-acdb-becae41c2200">

<img width="617" alt="image" src="https://github.com/pyecharts/pyecharts/assets/45176371/61f4776a-893c-48aa-a77f-cbbc088bc277">

**Comment by sunhailin-Leo** [comment]
@DaiZack 
* 你试一下把 `load_javascript` 和 `render_notebook` 放在不同的 cell 中呢？

**Comment by DaiZack** [comment]
这个一开始就试过了, 看其他的issue里就是这么建议的

错误是出现在 `bar.render_notebook()` load_javascript 没有报错

<img width="843" alt="image" src="https://github.com/pyecharts/pyecharts/assets/45176371/a64e3af6-6b9e-461e-b8d9-dbb78b9e63d9">

**Comment by sunhailin-Leo** [comment]
@DaiZack 
* 那这个问题可能是 colab 本身不兼容这种模式渲染了。
* 而且，我看报错信息的那个 `output_binary_js` 也不是 pyecharts 里面的依赖。
* 这个问题估计没办法解决，Colab 的 notebook 好像也不是开源的，没办法去 debug 为啥出这个问题。

**Comment by DaiZack** [comment]
@sunhailin-Leo 可能是不兼容渲染吧, 感觉应该是render.template.macro 的问题
``` {%- macro render_notebook_charts(charts, libraries) -%}
    <script>
        require([{{ libraries | join(', ') }}], function(echarts) {
```

plotly 可以实现, 不过渲染方法不同

https://github.com/plotly/plotly.py/blob/master/packages/javascript/jupyterlab-plotly/src/plotly-renderer.ts

没法debug确实很麻烦. 感谢回复

**Comment by sunhailin-Leo** [comment]
@DaiZack 
* 暂时先关闭了，等后续看看有没有别的办法解决~
