### ISSUE TITLE
LabelOpts 中的 color 能否使用 JS

### ISSUE THREAD

**Issue by zbjdonald** [pyecharts/pyecharts#2246]
**问题**
如何使 x 轴 label 颜色根据 x 值改变颜色？，例如
![image](https://github.com/pyecharts/pyecharts/assets/5664723/509f81c3-359b-4b44-999f-36a629d25c00)

目前查到的是 axislabel_opts 的 LabelOpts 中的 color 可以控制 x 轴 label 颜色，color 能否使用 js 像这样？：
![image](https://github.com/pyecharts/pyecharts/assets/5664723/a8359877-de2e-45d0-bdf6-447b1ba6b7ff)

**运行环境（系统环境及 pyecharts 版本）**
win10，pyecharts 1.9.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@zbjdonald 
* 直接给 `axisLabel` 的 `color` 写回调函数就可以了。
