### ISSUE TITLE
bmap如何设置使用BAIDU_MAP_GETSCRIPT形式，即https://api.map.baidu.com/getscript?v=2.0&ak={}？

### ISSUE THREAD

**Issue by zhanghai4155** [pyecharts/pyecharts#2247]
**问题**
目前bmap默认使用的API形式是BAIDU_MAP_API = "https://api.map.baidu.com/api?v=2.0&ak={}, 
如何切换为：bmapBAIDU_MAP_GETSCRIPT（https://api.map.baidu.com/getscript?v=2.0&ak={}）形式，以避免控制台如下图所示的警告信息。

**运行环境（系统环境及 pyecharts 版本）**
win10 python3.7， pyecharts版本2.0.4

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/28980129/2e276abe-5e57-44dc-8662-89ee643c949e)
![image](https://github.com/pyecharts/pyecharts/assets/28980129/fe1b3d8b-a297-4e2d-b7f3-9a18d1e6f0f0)

**Comment by sunhailin-Leo** [comment]
@zhanghai4155 
* 这个控制台 warning 问题也不大吧？🤔
