### ISSUE TITLE
和示例功能不一样，我这个是计划工时和实际工时进行比较，示例的是和固定值进行比较

### ISSUE THREAD

**Issue by xzzcx** [pyecharts/pyecharts#2249]
和示例功能不一样，我这个是计划工时和实际工时进行比较，示例的是和固定值进行比较

_Originally posted by @xzzcx in https://github.com/pyecharts/pyecharts/issues/2248#issuecomment-1757119222_

**Comment by sunhailin-Leo** [comment]
* 在原 issue 回复。没必要新开一个 issue。
