### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by SongZhuhai** [pyecharts/pyecharts#225]
建议render_embed()方法
提供生成代码可以自适应的策略

**Comment by SongZhuhai** [comment]
建议开一个交流群

**Comment by chenjiandongx** [comment]
@SongZhuhai  参考 https://github.com/chenjiandongx/pyecharts/issues/215

**Comment by babybear1992** [comment]
可否在mark line & point中实现一个automatic sum的feature？这样在选定一个时间轴内的数据时，可以看到更多的insights。
