### ISSUE TITLE
pyecharts在jupyter notebook7.0.5中无法出图

### ISSUE THREAD

**Issue by BankerDian** [pyecharts/pyecharts#2250]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by Saskuediplomat** [comment]
![image](https://github.com/pyecharts/pyecharts/assets/150902221/f48ebe6f-aef1-4ea0-a5c2-18ed5b9b3bb6)
我的是在pycharm中用jupyter出图不完全
