### ISSUE TITLE
pyecharts2.04在jupyter notebook7.0.5中运行代码，无法出图，是空白

### ISSUE THREAD

**Issue by BankerDian** [pyecharts/pyecharts#2251]
**问题**

win10电脑重做了系统，之前使用的是jupyter notebook6.4.6运行pyecharts1.9和2.0+均可

重装后，jupyter notebook6.4和6.5因其自身原因，已经无法成功安装了，所以新安装的用户只能安装7.0+，matplotlib可以正常出图，但pyecharts执行后无法出图，始终为空白，暂无法解决，望提供帮助

**运行环境（系统环境及 pyecharts 版本）**

win10
试过了python3.11 python3.12
pyecharts2.04
jupyter notebook7.0.5

**Comment by lintorrunning** [comment]
I have also encountered this problem and have not yet come up with a solution.

**Comment by sunhailin-Leo** [comment]
@BankerDian 
* 试试 jupyter 7 的其他版本会有问题吗？

**Comment by sunhailin-Leo** [comment]
> I have also encountered this problem and have not yet come up with a solution.

Same jupyter notebook version ？

**Comment by yangrq1018** [comment]
Jupyter notebook 7.0.7, same problem here.

**Comment by sunhailin-Leo** [comment]
> Jupyter notebook 7.0.7, same problem here.

Can you look at the browser console for error messages? If so, please reply with a screenshot.

**Comment by yangrq1018** [comment]
> > Jupyter notebook 7.0.7, same problem here.
> 
> Can you look at the browser console for error messages? If so, please reply with a screenshot.

I reinstalled notebook 7.0.7 and it's working again. I am not sure this is caused by wrong dependencies or just network problem, though. I guess probably network.

**Comment by yangrq1018** [comment]
My bad, it's actually not working on notebook 7.0.X, I have mistaken the versions.
See
![image](https://github.com/pyecharts/pyecharts/assets/25074163/93acbd51-40ca-45d5-8322-1b95adb7458e)

Things are good on the old 6.5.4 version, I will switch back to that.

**Comment by yangrq1018** [comment]
I am not in Jupyter lab, this is still jupyter notebook environment.

**Comment by trungleduc** [comment]
Hi folks, you might want to take a look at https://github.com/trungleduc/ipecharts, I created this Jupyter Widget library to make echarts work natively in notebooks.
