### ISSUE TITLE
Grid组合水球图和饼图

### ISSUE THREAD

**Issue by xzqxzqzzz** [pyecharts/pyecharts#2253]
-![IMG_20231018_225618.jpg](https://github.com/pyecharts/pyecharts/assets/92253816/a035c391-408d-4121-a4d5-de47cafb79b2)
 Grid组合水球图和饼图，无法调整位置？

**Comment by sunhailin-Leo** [comment]
@xzqxzqzzz 
* Grid 本身是用来整合直角坐标系 + 非直角坐标系的。
* 水球和饼图他本身调整位置是有固定参数 center 去控制的，与 Grid 的调整有一些区别。
* 你可以试着调整下两个图各自的 center。Grid 本身是调整图在画布的上下左右的位置，与 center 无关。
