### ISSUE TITLE
建议无法处理数据时报错

### ISSUE THREAD

**Issue by duchengyao** [pyecharts/pyecharts#2254]
data 不接收 numpy array，但不提示报错，对新手不友好。

```
points = [[1,2,3],[3,4,5]]
points=np.array(points)

(
    Scatter3D() 
    .add(
        series_name="",
        data=points,
    )
    .render("3d.html")
)
```

**Comment by sunhailin-Leo** [comment]
@duchengyao 
* 你可以提一个 pr 过来~

**Comment by sunhailin-Leo** [comment]
@duchengyao 
* 后续版本发布后，如果以 `ndarray` 或者 `Series` 作为 axis data 的输入会抛出异常：`ValueError: Can't use non-native data structures as axis data to render chart`

**Comment by Bingchen1512** [comment]
2.0.5版本：当x轴数据为array数值类型（数值未排序），则提示错误；当转换为列表（数值未排序），x轴显示异常，排序后，x轴还是显示异常。
![image](https://github.com/pyecharts/pyecharts/assets/34826324/de370aea-5459-4b6a-bb24-5acaadc1e955)

2.0.4版本：当x轴数据为array数值类型（数值未排序），x轴自动适用数据，显示正常。
