### ISSUE TITLE
如何显示关系图两节点间存在的多条边

### ISSUE THREAD

**Issue by Gaogaogaoo** [pyecharts/pyecharts#2255]
**问题**
关系图两节点之间存在多种关系，如何显示多条边

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 1.9.1，python3.6

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Gaogaogaoo 
* Links 给多个相同的 source 和 target 就可以了
