### ISSUE TITLE
pyecharts 能否只用经度纬度和对应的值这三个数来做图，省略掉前面的地点？

### ISSUE THREAD

**Issue by qczhkj** [pyecharts/pyecharts#2259]
**问题**

pyecharts 能否只用经度纬度和对应的值这三个数来做图，省略掉前面的地点？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts2.04，python3.9

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@qczhkj 
* 暂时不能直接给经纬度和值，不过可以试试 geojson 的方式. `Geo().add_geo_json()`

**Comment by qczhkj** [comment]
非常感谢您的回答！

**Comment by sunhailin-Leo** [comment]
@qczhkj 
![image](https://github.com/pyecharts/pyecharts/assets/17564655/c4279aad-5614-4950-b753-df765dddb238)
* 后续版本会加入这个 `GeoItem` 的配置。

**Comment by sunhailin-Leo** [comment]
@qczhkj 
* 后续版本发布后会解决～

**Comment by qczhkj** [comment]
好的，多谢！！！
