### ISSUE TITLE
南海诸岛如何英文展示。

### ISSUE THREAD

**Issue by SZJhacker** [pyecharts/pyecharts#2260]
**问题**
前端展示中国地图，导入了china.js，修改china.js的省份名称为英文，后端也用英文统计，其他省份也顺利修改。但是china.js里面没有南海诸岛的信息。echarts.min.js里面的南海诸岛信息替换成英文后，前端仍然是中文。请问这个南海诸岛的实现到底是那部分代码控制的？如何替换成英文？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

![image](https://github.com/pyecharts/pyecharts/assets/32929097/9a90f347-92e1-4d73-8975-e255d3fb7b03)

**Comment by sunhailin-Leo** [comment]
@SZJhacker 
* 你是改了 https://github.com/pyecharts/pyecharts-assets 这里面的 echarts.min.js 吗？
* 现在 2.X 版本用的是 assets/v5 里面那个。

**Comment by SZJhacker** [comment]
> @SZJhacker
> 
> * 你是改了 https://github.com/pyecharts/pyecharts-assets 这里面的 echarts.min.js 吗？
> * 现在 2.X 版本用的是 assets/v5 里面那个。

嗯嗯，谢谢已经解决，修改echart.min.js里面两个南海诸岛为英文就行了
