### ISSUE TITLE
`Bar`初始化设置较小尺寸时，部分Label不显示

### ISSUE THREAD

**Issue by keymou** [pyecharts/pyecharts#2262]
**问题**
`Bar`初始化设置较小尺寸时，部分Label不显示

**运行环境（系统环境及 pyecharts 版本）**
操作系统：window 7
python ：3.8.10
pyecharts：2.0.4

**代码及截图**
```
from pyecharts import options as opts
from pyecharts.globals import ThemeType
from pyecharts.charts import Bar

c = (
    Bar(init_opts=opts.InitOpts(
                    width='200px', height='180px', page_title='Line图表', theme=ThemeType.LIGHT
                ),)
    .add_xaxis(['断言', '核心', 'vgware'])
    .add_yaxis("总检查数", [48, 34, 17], stack="stack1")
    .add_yaxis("异常次数", [1, 0, 0], stack="stack1")
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(title_opts=opts.TitleOpts(title=""))
    .render("bar_stack0.html")
)
```
截图：
![image](https://github.com/pyecharts/pyecharts/assets/35944974/7198072d-6e2d-42a3-898d-07fa47e35e59)

**Comment by sunhailin-Leo** [comment]
@keymou 
* 这个取决于 Echarts 对于这个比例的渲染逻辑。
* 可以给 x 轴设置 axislabel_opts 的 interval 为 0，强制展示（有可能样式会变形）

**Comment by keymou** [comment]
> @keymou
> 
> * 这个取决于 Echarts 对于这个比例的渲染逻辑。
> * 可以给 x 轴设置 axislabel_opts 的 interval 为 0，强制展示（有可能样式会变形）

谢谢解答！
