### ISSUE TITLE
Highlight on hover (emphasis)

### ISSUE THREAD

**Issue by buhbuhtig** [pyecharts/pyecharts#2263]
Hi, there's a way to highlight the line when hover (emphasis) ?
Like this: https://echarts.apache.org/examples/en/editor.html?c=line-race
Thx

**Comment by sunhailin-Leo** [comment]
@buhbuhtig 
* (emphasis) This configuration has not been added to the pyecharts configuration yet. It will be updated in a later version.

**Comment by byemaxx** [comment]
Hi, Does Bar3D support the emphasis_opts? I am using v2.0.5, but didn't find it at Bar3d

**Comment by sunhailin-Leo** [comment]
> Hi, Does Bar3D support the emphasis_opts? I am using v2.0.5, but didn't find it at Bar3d

* You can make an issue for Bar3D emphasis_opts feature~
