### ISSUE TITLE
Grid 无法拼接多个 DataZoom

### ISSUE THREAD

**Issue by 3165523246** [pyecharts/pyecharts#2264]
windows11
python 3.7，pyecharts最新版

![b24d172c71a3081134a6c31af820b6c](https://github.com/pyecharts/pyecharts/assets/116544481/4698bc29-c809-465d-9bf9-b35b51ae2f09)
![44668dbdb2390cb57f35d3fec2e8429](https://github.com/pyecharts/pyecharts/assets/116544481/faa0bf18-94ec-4873-9383-795ad1214aec)
![889a7e58731a5afd856ef21eba8a435](https://github.com/pyecharts/pyecharts/assets/116544481/0f075ece-8a12-4495-9a5d-20e64ec81d4b)

**Comment by sunhailin-Leo** [comment]
@3165523246 
* 后续版本发布后会解决～
