### ISSUE TITLE
`chart-container`与浏览器边缘默认`margin`不为0，在暗黑模式下会出现白边的情况，pyecharts 是否支持修改该配置？

### ISSUE THREAD

**Issue by keymou** [pyecharts/pyecharts#2266]
**问题**
容器与浏览器边缘默认存在margin，在暗黑模式下会出现白边的情况，手动修改生成的html `body`标签添加`style="height: 100%; margin: 0"`
可以实现预期效果，请问下当前pyecharts有参数可以设置`margin`吗？

**运行环境（系统环境及 pyecharts 版本）**
python: 3.8.10
pyecharts: 2.0.4
os: window 7

**代码及截图**
生成的html部分代码
```
<body>
    <div id="da08569a84e74731a1a921afde02a210" class="chart-container" style="width:250px; height:180px; "></div>
 ```
 
![image](https://github.com/pyecharts/pyecharts/assets/35944974/2818ce39-bd69-4163-b955-8837c3b57c8a)

**Comment by sunhailin-Leo** [comment]
@keymou 
* 这个暂时没办法调整。目前的解决方案除了你说的手动修改生成的 html，或者是通过传入自定义模版来生成。

**Comment by keymou** [comment]
> @keymou
> 
> * 这个暂时没办法调整。目前的解决方案除了你说的手动修改生成的 html，或者是通过传入自定义模版来生成。

谢谢，翻了下echarts官方文档，也没有相关介绍，只能通过修改`body`标签解决，已经采用自定义模板来解决这个问题。
