### ISSUE TITLE
地图上的点用不同颜色代表该点严重性时，无法将各点连接起来，连接起来的话无法使用不同颜色的点。

### ISSUE THREAD

**Issue by deadpool-liu** [pyecharts/pyecharts#2267]
**问题**

地图上的点用不同颜色代表该点严重性时，无法将各点连接起来，连接起来的话无法使用不同颜色的点。也无法使用overlap将两种情况下的图进行叠加

**运行环境（系统环境及 pyecharts 版本）**
Windows11， 
pyecharts=2.0.4

**代码及截图**
# 试用报告pyecharts进行绘制地图和标点
import pandas as pd
from pyecharts.charts import Map, Geo
from pyecharts import options as opts
import random

from pyecharts.globals import ChartType,SymbolType

map=Geo(init_opts=opts.InitOpts(width="1800px",height='900px'))

map.add_schema(
    maptype="江西",
    itemstyle_opts=opts.ItemStyleOpts(color = '#ECECECFF',border_color = '#ECECECFF')
)
map.set_series_opts(label_opts=opts.LabelOpts(is_show=False))
map.set_global_opts(
    title_opts=opts.TitleOpts(title='江西省变电站',
                              subtitle='受故障影响程度'),
#     visualmap_opts=opts.VisualMapOpts(
# #         max_=100,
# #         min_=0,
#         is_piecewise=True,
# #         range_color=['#8FFF88FF','#FFB37FFF','#DE3333FF']
#     ),
    toolbox_opts = opts.ToolboxOpts()
                   )

# 220kV电站
for i in data:
    map.add_coordinate(i[0], i[1], i[2])
map.add(
    '220kV变电站', 
    [(i[0],random.randint(0, 70)) for i in data],
    type_=ChartType.SCATTER,
        symbol_size=8,# 点大小
#         blur_size=2,
#         point_size=10,
    
    
)

# 500kV电站
for i in data5:
    map.add_coordinate(i[0], i[1], i[2])
map.add('500kV变电站', 
        [(i[0], 0.5) for i in data5],
       type_=ChartType.SCATTER,
        symbol_size=8,# 点大小
#        blur_size=2,
       )
    

# 输电线路
map.add(
    "输电线路",
    data7[:],  #需要显示的元组对
    type_=ChartType.LINES,
    effect_opts=opts.EffectOpts(
        symbol=SymbolType.ARROW , 
        symbol_size=0.1, 
        color="blue"
    ),
    linestyle_opts=opts.LineStyleOpts(curve=0.4, color='#b0e2ff', opacity=0.3),
    is_polyline=True,  # 取消头尾的箭头 
)

map.render('map地图.html') 
# map.render_notebook()
![Uploading 1701085885178.jpg…]()

**Comment by sunhailin-Leo** [comment]
@deadpool-liu 
* 麻烦调整一下 issue 格式和图片
