### ISSUE TITLE
求助 漏斗圖無法呈現 出現問題:<pyecharts.custom.page.Page at 0x8d27b50>

### ISSUE THREAD

**Issue by anbr67** [pyecharts/pyecharts#2268]
**问题**
from pyecharts import Funnel,Grid,Bar,Page
import openpyxl
# 讀取excel數據
workbook = openpyxl.load_workbook('C:\\Users\\Administrator\\Desktop\\漏斗案例數據.xlsx')
sheet = workbook['工作表1']

value1 = []
title1 = sheet['A'][9].value
for cell in (sheet['B'][10:16]): #定位資料位置
    value1.append(cell.value)

value2 = []
title2 = sheet['F'][9].value
for cell in (sheet['G'][10:16]):  #定位資料位置
    value2.append(cell.value)
    
value3 = []
title3 = sheet['K'][9].value
for cell in (sheet['L'][10:16]):   #定位資料位置
    value3.append(cell.value)
    
**运行环境（系统环境及 pyecharts 版本）**

<pyecharts.custom.page.Page at 0x8d27b50>

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/152772158/0790f69a-c9fc-49ca-945b-b6a1c318a6b4)
![image](https://github.com/pyecharts/pyecharts/assets/152772158/6bfa3ffc-55d7-43dc-abd9-f3c0c47d9a0f)

**Comment by sunhailin-Leo** [comment]
@anbr67 
* https://pyecharts.org/#/zh-cn/notebook
