### ISSUE TITLE
ImportError: cannot import name 'options' from 'pyecharts' (D:\Anaconda\lib\site-packages\pyecharts\__init__.py)

### ISSUE THREAD

**Issue by anbr67** [pyecharts/pyecharts#2269]
**问题**
from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.globals import ThemeType

def theme_default() -> Bar:
    c = (
        Bar()
        # 等价于 Bar(init_opts=opts.InitOpts(theme=ThemeType.WHITE))
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values())
        .add_yaxis("商家B", Faker.values())
        .add_yaxis("商家C", Faker.values())
        .add_yaxis("商家D", Faker.values())
        .set_global_opts(title_opts=opts.TitleOpts("Theme-default"))
    )
    return c

**运行环境（系统环境及 pyecharts 版本）**
![image](https://github.com/pyecharts/pyecharts/assets/152772158/b7fe727e-b475-42cb-bcda-66d6e2bfd5d0)

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/152772158/472aa1a8-892e-47f3-8997-16eac24ac8cb)

PS.不好意思，本身是新手還不太懂，函請別將我留的問提訊息刪除，保留下來，謝謝您。

**Comment by sunhailin-Leo** [comment]
@anbr67 
* `pip(3)` 的意思是 `pip 或 pip3`, 有的开发者会存在多套 `pip` 的情况。更新包版本需要执行 `pip install -U pyecharts` 或 `pip3 install -U pyecharts`.
* 建议你先学习基本语法和包管理，别一上来就是复制粘贴代码。

**Comment by anbr67** [comment]
謝謝 @sunhailin-Leo 
我可以請教您一個問題嗎?
漏斗圖的問題出現異常<pyecharts.custom.page.Page at 0x8d27b50>是甚麼意思呢?
謝謝你

**Comment by sunhailin-Leo** [comment]
> 謝謝 @sunhailin-Leo 我可以請教您一個問題嗎? 漏斗圖的問題出現異常<pyecharts.custom.page.Page at 0x8d27b50>是甚麼意思呢? 謝謝你

* 那个不是异常。那个是 jupyter 直接把对象信息输出在页面上了。你缺少一次调用 render 的逻辑。

**Comment by anbr67** [comment]
@sunhailin-Leo 可以請求您幫我看看嗎?
我真的弄了一個晚上，謝謝您
from pyecharts import Funnel,Grid,Bar,Page
import openpyxl
# 讀取excel數據
workbook = openpyxl.load_workbook('C:\\Users\\Administrator\\Desktop\\漏斗案例數據.xlsx')
sheet = workbook['工作表1']

value1 = []
title1 = sheet['A'][9].value
for cell in (sheet['B'][10:16]): #定位資料位置
    value1.append(cell.value)

value2 = []
title2 = sheet['F'][9].value
for cell in (sheet['G'][10:16]):  #定位資料位置
    value2.append(cell.value)
    
value3 = []
title3 = sheet['K'][9].value
for cell in (sheet['L'][10:16]):   #定位資料位置
    value3.append(cell.value)
    
# 畫圖
attr = ["流覽","簡歷", "約面", "到面", "offer","入職"]
funnel1 = Funnel(title1,title_pos='center')
funnel1.add("漏斗",
           attr,
           [int(i/max(value1)*100) for i in value1],
           is_label_show=True,
           label_formatter='{b} {c}%',
           label_pos="outside",
      legend_orient='vertical', legend_pos='left',is_legend_show=False)

funnel2 = Funnel(title2,title_pos='center')
funnel2.add("漏斗",
           attr,
           [int(i/max(value2)*100) for i in value2],
           is_label_show=True,
           label_formatter='{b} {c}%',
           label_pos="outside",
      legend_orient='vertical', legend_pos='left',is_legend_show=False)

funnel3 = Funnel(title3,title_pos='center')
funnel3.add("漏斗",
           attr,
           [int(i/max(value3)*100) for i in value3],
           is_label_show=True,
           label_formatter='{b} {c}%',
           label_pos="outside",
      legend_orient='vertical', legend_pos='left',is_legend_show=False)

page = Page()
page.add(funnel1)
page.add(funnel2)
page.add(funnel3)
page

**Comment by sunhailin-Leo** [comment]
```python
page.load_javascript()
```
换一个 cell
```python
page.render_notebook()
```

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo 請教您要換在那裡呢?>"<

jupyter cell

**Comment by anbr67** [comment]
@sunhailin-Leo 是換系統試試嗎? 還是?

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo 是換系統試試嗎? 還是?

我觉得你先看一看 jupyter 的介绍，先了解一些 jupyter 的基础术语，再来写代码吧~

**Comment by anbr67** [comment]
@sunhailin-Leo 謝謝你的回覆
我可以請託最後一次的忙嗎?
只想將這個漏斗製作出來即可
我剛剛的術語可否請大大幫我修改呢?謝謝您
