### ISSUE TITLE
怎么解决DataZoomOpts隐藏后，依然占用空间的问题？

### ISSUE THREAD

**Issue by c-coming** [pyecharts/pyecharts#2271]
在制作大屏的时候，并不需要太多配置项，所以会一并隐藏。
但是，我发现is_show只是不显示配置项，可是隐藏后的配置项依然会占用空间。
有没办法能让图形占满整个图表？

截图：

![image](https://github.com/pyecharts/pyecharts/assets/39179505/15a801e6-fb1c-49e8-a063-91343905fdac)

**Comment by sunhailin-Leo** [comment]
@c-coming 
* 套一个 Grid 试试？

**Comment by c-coming** [comment]
@sunhailin-Leo Grid能截取图表吗？
我测试了下，Grid好像只能对整个图表进行缩放、移动，并不能截取，只显示部分区域。
示例中，我先画了一个200*400的柱形图，然后加到一个300*300的Grid中，最终显示出来的图表是300*300的。
![image](https://github.com/pyecharts/pyecharts/assets/39179505/6e7563e1-75d9-4b05-93aa-d540cd3c9e51)
```python
from pyecharts.charts import Bar, Grid
from pyecharts import options as opts
# 创建400*400柱状图
bar = Bar(init_opts=opts.InitOpts(width="200px", height="400px"))
# 添加数据系列
bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
# 设置图表的全局配置项
bar.set_global_opts(
    title_opts=opts.TitleOpts(title="柱状图示例"),
    xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=-15)),
    datazoom_opts=opts.DataZoomOpts(is_show=True),
)

# 创建300*300的Grid，图表被调整到300*300
grid = (Grid(init_opts=opts.InitOpts(width="300px", height="300px")).add(
    bar, grid_opts=opts.GridOpts()))

# bar.render_notebook()
grid.render_notebook()
```

**Comment by sunhailin-Leo** [comment]
@c-coming 
* GridOpts 有配置可以调整到边框的距离，你把边框距离调的极限一些试试看

**Comment by c-coming** [comment]
@sunhailin-Leo 谢谢，增加了pos_bottom=25后，的确能达到想要的效果。
![image](https://github.com/pyecharts/pyecharts/assets/39179505/5e5a7c5e-6509-43ae-bf2b-bd6c49d2a0a0)
