### ISSUE TITLE
折线图坐标轴显示正常数据显示不全

### ISSUE THREAD

**Issue by willionTom** [pyecharts/pyecharts#2272]
**问题**
作者你好，我的问题是用Line画折线图数据数据显示不全，同样的数据和参数用Bar画柱状图可以完整显示

**运行环境（系统环境及 pyecharts 版本）**
pyecharts版本：2.0.3
python3.9
window10
IDE：vscode

**代码及截图**
```
line =  Line(init_opts=opts.InitOpts(theme=ThemeType.ROMA,width="600px", height="400px")) 
line.add_xaxis(aar['t'].tolist())
line.add_yaxis("healthcare_total" ,
		aar['healthcare_total'].tolist(),
                label_opts= None,
                #gap=0, # 柱间距
		#itemstyle_opts=opts.ItemStyleOpts(color="#00CD96") # 自定义颜色  
		)

line.set_global_opts(
        title_opts=opts.TitleOpts(title='平均超额收益率',pos_left='center'),

        toolbox_opts=opts.ToolboxOpts(), # 设置操作图表的工具箱功能
        yaxis_opts=opts.AxisOpts(        # 设置Y轴名称、刻度单位
                        axislabel_opts=opts.LabelOpts(formatter="{value} "),
                        name="aar" ), 	                            
        xaxis_opts=opts.AxisOpts(name="时间"), # 设置X轴名称
        legend_opts=opts.LegendOpts(pos_bottom='bottom' )
        
)
line.render('test.html')

```
![image](https://github.com/pyecharts/pyecharts/assets/102823510/cf570733-0969-42ca-8ee4-1afd44410ed9)
（x轴0之后没有显示）
同样的参数用bar画柱形图可以正常显示
![image](https://github.com/pyecharts/pyecharts/assets/102823510/4e3bdad0-2de6-43ea-9fa0-e6f289ed3f76)

```
数据：
 	healthcare_total
-15	-0.0052318601
-14	-0.0083066327
-13	0.019832484
-12	-0.0044902242
-11	-0.0016166857
-10	-0.000922915
-9	0.0072976383
-8	-0.0035888485
-7	0.012785413
-6	0.0041388329
-5	0.00012406922
-4	0.0036568919
-3	0.0027136356
-2	0.0021185589
-1	0.0024635252
0	0.019832149
1	0.046170656
2	-0.024026189
3	0.015566701
4	0.051110856
5	0.026337501
6	0.039315134
7	0.020373806
8	-0.024807544
9	-0.030512055
10	-0.014618685
11	-0.0045505608
12	-0.012263555
13	-0.0064317849
14	0.0018198432
15	0.0066704242

```

**Comment by sunhailin-Leo** [comment]
@willionTom 
* 试下调整 Line 图 X 轴的轴类型参数，改成 category 试试，或者是 value

**Comment by willionTom** [comment]
> @willionTom
> 
> * 试下调整 Line 图 X 轴的轴类型参数，改成 category 试试，或者是 value

改成value有用！
![image](https://github.com/pyecharts/pyecharts/assets/102823510/ddc737bf-e1f5-40bb-94dd-19ff1c07764a)
另外想知道这是什么原理，（为什么条形图不需要这么设置)，以避免后面遇见类似的问题

**Comment by sunhailin-Leo** [comment]
@willionTom 
* 折线图默认用 value 展示，柱状图默认用 category 展示，如果你 x 轴的数据不是数值的话，就会被强转一次。
* 主要还是你 x 轴的数据类型

**Comment by willionTom** [comment]
> @willionTom
> 
> * 折线图默认用 value 展示，柱状图默认用 category 展示，如果你 x 轴的数据不是数值的话，就会被强转一次。
> * 主要还是你 x 轴的数据类型

学到了，感谢！🌹
