### ISSUE TITLE
在同个Grid()下 Map（）影响Line（）的着色

### ISSUE THREAD

**Issue by Updraft095** [pyecharts/pyecharts#2274]
**问题**
我发现当我把地图和折线图放在同一个网格中的时候，地图会影响同一个网格中其他图表的着色。如我上传的图片所示。
地图和柱状图的着色一致其实是挺好的，可以方便柱与地区的对应。
但问题是我折线图的颜色应该由我设施的图例控制，而不是由数值控制。

经过我的测试，只有将地图与折线图添加到同一网格下会出现这个问题，只有柱状图和条形图的时候，它们不会相互影响。

其实在一般情况下，使用Page.DraggablePageLayout可以给条形图另起一个可视化，然后再把它们拖到一块就能解决这个问题。
但是由于我现在需要运用到Tab()来设置选项卡，Tab()和Page()不能同时使用，所以这个方法也没法解决我的问题。

我已经阅读过官网的说明书和各个图表的示例（pyecharts-gallery），现在没有发现解决方案。
如果有我不知道的解决方案，请恕我鲁莽。

**运行环境（系统环境及 pyecharts 版本）**
Pyecharts 版本：2.0.4 
Python 版本：3.11.5

**代码及截图**
![截图](https://github.com/pyecharts/pyecharts/assets/109008917/d5d9d079-31b5-4fb8-b3f2-50ada65a29b4)

**Comment by Updraft095** [comment]
补充说明一下，我很确定这个问题不是tab()或者timeline()引起的。这是因为我把它们去掉只保留gird()也会出现类似的情况。

**Comment by sunhailin-Leo** [comment]
@Updraft095 
* 麻烦提供下 example 进行测试

**Comment by Updraft095** [comment]
from pyecharts.charts import Bar, Grid, Line, Map
from pyecharts import options as opts
import pandas as pd

# 创建示例数据
data = {
    '省份': ['山东省', '河北省', '山西省', '河南省', '江苏省'],
    '2019': [100, 200, 150, 180, 120],
    '2020': [120, 210, 160, 190, 130],
    '2021': [130, 220, 170, 200, 140],
    '2022': [140, 230, 180, 210, 150],
    '2023': [150, 240, 190, 220, 160],
    '2024': [160, 250, 200, 230, 170],
    '2025': [170, 260, 210, 240, 180],
    '2026': [180, 270, 220, 250, 190],
    '2027': [190, 280, 230, 260, 200],
    '2028': [200, 290, 240, 270, 210],
    '2029': [210, 300, 250, 280, 220],
    '2030': [220, 310, 260, 290, 230]
}

province_data = pd.DataFrame(data)
province_list = province_data['省份'].tolist()

# 提取数据
year_list = [str(year) for year in range(2019, 2031)]


#####折线图
line = Line()
line.set_global_opts(
    xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=-45))
)

for province in province_list:
    data_for_province = province_data.loc[province_data['省份'] == province, year_list].values.tolist()[0]
    line.add_xaxis(year_list)
    line.add_yaxis(province, data_for_province, is_smooth=True)

# 固定地图和柱状图的数据为 2019 年
values = province_data['2019'].tolist()

map_chart = (
    Map()
    .add(
        series_name="2019年数据",
        data_pair=list(zip(province_list, values)),
        maptype="china",
        center=[140, 37],
        zoom=1.2
    )
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(max_=max(values)),
    )
)

bar_chart = (
    Bar()
    .add_xaxis(province_list)
    .add_yaxis("2019年数据", values)
    .set_global_opts(title_opts=opts.TitleOpts(title="2019年各省份数据柱状图"))
)


grid = (
    Grid()
    .add(
        bar_chart,
        grid_opts=opts.GridOpts(pos_left="50%", pos_right="22%", pos_top="50%", pos_bottom="15%"),
    )
    .add(
        line,
        grid_opts=opts.GridOpts(pos_left="50%", pos_right="22%", pos_top="10%", pos_bottom="60%"),
    )
    .add(
        map_chart,
        grid_opts=opts.GridOpts(pos_left="5%", pos_right="50%", pos_top="50%", pos_bottom="15%"),
    )
)
grid.render('样例.html')
grid.render_notebook()

**Comment by Updraft095** [comment]
这是一个示例代码，为了排除timeline造成的影响，同时使代码更加简单，我把地图和柱状图的时间固定在2019年。

**Comment by sunhailin-Leo** [comment]
@Updraft095 
* 这个目前没有太好的办法解决。最好还是拆分多张图。Echarts 多图联动比较容易出现这种颜色影响的问题。
* 可以参考一下：
    * https://gallery.pyecharts.org/#/Map/china_gdp_from_1993_to_2018
    * https://gallery.pyecharts.org/#/Map/china_gdp_from_1980
