### ISSUE TITLE
在Geo下使用Timeline，自定义的add_js_funcs未加载到html中

### ISSUE THREAD

**Issue by MaKangChina** [pyecharts/pyecharts#2276]
**问题**
老师好，我在Geo下使用Timeline，自定义的add_js_funcs未加载到html中，举一个例子供您审查。

**运行环境（系统环境及 pyecharts 版本）**
win10+pyecharts2.0.4

**代码及截图**

from pyecharts import options as opts
from pyecharts.charts import Map, Timeline,Geo
from pyecharts.faker import Faker

tl = Timeline()
for i in range(2015, 2020):
    map0 = (
        Geo()
            .add_schema(maptype="china")
            .add("geo", [list(z) for z in zip(Faker.provinces, Faker.values())])
            .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
            .set_global_opts(
            visualmap_opts=opts.VisualMapOpts(), title_opts=opts.TitleOpts(title="Geo-基本示例")
                        )
        .add_js_funcs("""            
        function Test(x, y) 
            {

            }""")
    )
    tl.add(map0, "{}年".format(i))
tl.render("timeline_map.html")
![image](https://github.com/pyecharts/pyecharts/assets/30001816/86bf0e8f-a75c-4acf-aecf-2bab8df10817)

不使用timeline情况下，可以将对应的jscode写入html
![image](https://github.com/pyecharts/pyecharts/assets/30001816/85badd58-7b6a-4359-a164-ce46e332b315)

**Comment by sunhailin-Leo** [comment]
@MaKangChina 
* 有试过在 `tl.add_js_funcs` 吗？

**Comment by MaKangChina** [comment]
> @MaKangChina
> 
> * 有试过在 `tl.add_js_funcs` 吗？

老师好，按照您的指导，再加上tl.add_js_funcs，实现了。谢谢
