### ISSUE TITLE
Add package to conda-forge channel

### ISSUE THREAD

**Issue by Episkiliski** [pyecharts/pyecharts#2277]
**Description**
Add package to conda-forge channel for Windows (x86_64) and osx-arm64 builds. (My company does not allow other channel than conda-forge).

**Suggested solution**
[https://conda-forge.org/docs/maintainer/adding_pkgs.html]([https://conda-forge.org/docs/maintainer/adding_pkgs.html])

Thanks!

**Comment by sunhailin-Leo** [comment]
@Episkiliski 
* It's not that I don't want to provide conda-forge, but the pull-requests are stuck.
* https://github.com/conda-forge/staged-recipes/pull/23709

**Comment by Episkiliski** [comment]
Thanks for the reply @sunhailin-Leo , I see the pull request now. Let's see if the unblock it once and for all.

Thanks for your great work by the way!

**Comment by Episkiliski** [comment]
Hi @sunhailin-Leo , it seems that the pull-request in conda forge is pending to remove some of the maintainers to go through. You migh have missed it.

**Comment by sunhailin-Leo** [comment]
@Episkiliski 
* I'm not sure what kind of proof I need to provide to prove to those maintainers that they agree to be added to the maintainer list. That reply confused me so much that it made me think this eco is ridiculous.

**Comment by Episkiliski** [comment]
I totally agree with you @sunhailin-Leo , this is very frustrating.

**Comment by sunhailin-Leo** [comment]
@Episkiliski 
* After many unsuccessful attempts to communicate with the maintainers of the conda-forge repository, may I suggest that it would be better for our repository to provide a wheel as an installation method?

**Comment by sunhailin-Leo** [comment]
Add wheel file in release doc. https://github.com/pyecharts/pyecharts/releases/tag/v2.0.5
