### ISSUE TITLE
对于x轴有重复点的情况为什么会这么显示

### ISSUE THREAD

**Issue by 2470370075** [pyecharts/pyecharts#2278]
c = (
        Line(init_opts=opts.InitOpts())
        .add_xaxis(["衬衫", "雪纺衫", "雪纺衫"])
        .add_yaxis("商家A", [5, 20, 36,])
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"),)
    )
我的数据是这样的，我的x轴会有相同的点，现在它是这么显示的
![image](https://github.com/pyecharts/pyecharts/assets/39545205/6bd732f0-9925-4f79-b237-5e564618d085)
但是我想让它这么显示
![image](https://github.com/pyecharts/pyecharts/assets/39545205/85bf4b9f-bb26-45ab-8aa3-bb2cbf83cc72)
我知道把相同的点换一个名字就可以了但是有没有其他方法，就是别让它重叠，按顺序分开显示
我发现柱状图是可以这么显示的，即使是有相同的点
![image](https://github.com/pyecharts/pyecharts/assets/39545205/f72d6f3b-80c1-4cc5-97e2-e2ab740d94d6)

python版本：3.9

pyecharts版本： 2.0.4

**Comment by sunhailin-Leo** [comment]
@2470370075 
* 因为 `Line` 图对 `x` 轴和 `y` 轴的数据做了一层数据绑定。
![image](https://github.com/pyecharts/pyecharts/assets/17564655/a238b97e-060a-44b5-a7a6-b387c1c345eb)
