### ISSUE TITLE
在Map()下绘制图示之后, 根据某种品牌自定义颜色后, 使用图例展示, 没有效果, 请问这个如何进行展示, 查看文旦, 好像现在的API和文档的不一致, 是不是没有更新文档

### ISSUE THREAD

**Issue by chinesejunzai12** [pyecharts/pyecharts#2279]
**问题**
在Map()下绘制图示之后, 根据某种品牌自定义颜色后, 使用图例展示, 没有效果, 请问这个如何进行展示, 查看文旦, 好像现在的API和文档的不一致, 是不是没有更新文档

**运行环境（系统环境及 pyecharts 版本）**
pyecharts=2.0.3

**代码及截图**

![image](https://github.com/pyecharts/pyecharts/assets/103180175/f72a89ac-a54b-4e70-8c8e-a4658c4ab9b3)

**Comment by sunhailin-Leo** [comment]
@chinesejunzai12 
* 文档相关的 issue 请提到这边 `https://github.com/pyecharts/website`

**Comment by chinesejunzai12** [comment]
![Snipaste_2024-01-09_11-26-44](https://github.com/pyecharts/pyecharts/assets/103180175/82561592-7b0a-4696-801a-4387adc77d0f)  给到的链接文档中, 目前还是不一致呢
