### ISSUE TITLE
如何根据自定义的颜色显示图例

### ISSUE THREAD

**Issue by chinesejunzai12** [pyecharts/pyecharts#2280]
**问题**
比如有多种品牌: 品牌A, 品牌B, 品牌C, 但是每种品牌在地图上有不用的占比, 比如有品牌A={'山西': 0.2,'北京':0.5,'河北':0.1} ,品牌b={'山东': 0.2,'北京':0.3,'河北':0.6},依次类推, 每种品牌分配一种颜色, 在map()地图上按照占比, 在自定义的颜色上进行着色, 现在这个功能已实现, 现在的问题是, 如何显示这些品牌的颜色, 即图例, 并且图例的颜色就是自定义的颜色且透明度为60%, 查看文档legend或是VisualMapOpts()好像都不能实现这样的功能, 作者有哪些建议的api可以实现

**运行环境（系统环境及 pyecharts 版本）**
pyecharts=2.0.3

**代码及截图**

![image](https://github.com/pyecharts/pyecharts/assets/103180175/c0b45baa-d44f-489c-b948-770e6ab7fd9a)

**Comment by sunhailin-Leo** [comment]
@chinesejunzai12 
* 这个需要写 JsCode 做回调判断了；判断高亮时的颜色显示。
* 示例可以参考一下：https://gallery.pyecharts.org/#/Bar/bar_custom_bar_color

**Comment by chinesejunzai12** [comment]
示例中的颜色在图像中没有很好的体现.
<img width="1015" alt="image" src="https://github.com/pyecharts/pyecharts/assets/103180175/171fcd54-e9ad-4ce7-89b1-51c46675cb33">
比如图中商家A是蓝色颜色, 他的占比按照数量的多少调整颜色的透明度, 商家A就是这种颜色, 而不会因为数据的大小而改成其他颜色, 我想要的是前者调整透明度的效果, 不知作者是否理解我表达的意思.

**Comment by sunhailin-Leo** [comment]
> 示例中的颜色在图像中没有很好的体现. <img alt="image" width="1015" src="https://private-user-images.githubusercontent.com/103180175/296650870-171fcd54-e9ad-4ce7-89b1-51c46675cb33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTk0NTksIm5iZiI6MTcwNTI5OTE1OSwicGF0aCI6Ii8xMDMxODAxNzUvMjk2NjUwODcwLTE3MWZjZDU0LWU5YWQtNGNlNy04OWIxLTUxYzQ2Njc1Y2IzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNjEyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDk2OWFhNzA5MTlmMTIzMzk2MzE2YTZhMGVkZmQxOWJhMWRjMTgyMzU2MWM2ZTNmYjVmODJiNzg0ZjMzYjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ahkf4RVGME0eJnknI6RDniF6Zvp0K01G02Q-7x-Gz4Y"> 比如图中商家A是蓝色颜色, 他的占比按照数量的多少调整颜色的透明度, 商家A就是这种颜色, 而不会因为数据的大小而改成其他颜色, 我想要的是前者调整透明度的效果, 不知作者是否理解我表达的意思.

* 也可以从回调里面改；
* 这种相对定制化的需求，只能去深入了解整个可视化渲染逻辑；然后你才知道具体你要怎么修改，并达到的你的要求。
