### ISSUE TITLE
在Kline Grid当中，多于4张图则无法联动缩放 

### ISSUE THREAD

**Issue by EnjoyLeole** [pyecharts/pyecharts#2282]
在Kline Grid当中，多于4张图则无法联动缩放 
参考下图，可以看到第5张及以后的图标x轴不再缩放
最下面的三条绿线，是用同一个函数和同样数据绘制的，但只有最上面一条会随动

![erro](https://github.com/pyecharts/pyecharts/assets/17866725/ee104a7f-878e-4a16-9df4-791e63443232)

已参考之前的issue添加了如下代码：
kline.set_global_opts(
      axispointer_opts=opts.AxisPointerOpts(
          is_show=True,
          link=[{"xAxisIndex": "all"}],
          label=opts.LabelOpts(background_color="#777"),
      ),）
https://github.com/pyecharts/pyecharts/issues/1500

pyecharts 版本"2.0.2"

**Comment by sunhailin-Leo** [comment]
@EnjoyLeole 
* 这块能提供一下复现的代码吗？以便于我们进行问题的排查

**Comment by EnjoyLeole** [comment]
[kline1.py.txt](https://github.com/pyecharts/pyecharts/files/13999603/kline1.py.txt)
代码如上，自己做了比较多的封装只能整体上传
已经测过，可以复现问题
