### ISSUE TITLE
Texture option for globe map

### ISSUE THREAD

**Issue by wybert** [pyecharts/pyecharts#2283]
I am attempting to use Pyecharts to create a chart similar to an example [I found in the Echarts library](https://echarts.apache.org/examples/en/editor.html?c=globe-echarts-gl-hello-world&gl=1). I noticed that [a similar example exists in Pyecharts gallery](https://gallery.pyecharts.org/#/MapGlobe/map_globe_base). However, when I implemented the code, the resulting chart appears strange to me.
Here is the relevant code snippet I am using:
```python
import pyecharts.options as opts
from pyecharts.charts import MapGlobe
from pyecharts.faker import POPULATION

data = [x for _, x in POPULATION[1:]]
low, high = min(data), max(data)

c = (
    MapGlobe()
    .add_schema()
    # .add(
    #     background_color='#fff',
    #     # maptype="world",
    #     # series_name="World Population",
    #     # data_pair=POPULATION[1:],
    #     # is_map_symbol_show=False,
    #     # label_opts=opts.LabelOpts(is_show=False),
    #     ) 
    .add_globe(
        # background_color='#fff',
        base_texture= "data/world.topo.bathy.200401.jpg",
        height_texture="data/world.topo.bathy.200401.jpg",
        displacement_scale=0.04,
        shading='realistic',
        environment="data/starfield.jpg",            
        # post_effect_opts=

    )
    # .set_global_opts(
    #     visualmap_opts=opts.VisualMapOpts(
    #         min_=low,
    #         max_=high,
    #         range_text=["max", "min"],
    #         is_calculable=True,
    #         # range_color=["lightskyblue", "yellow", "orangered"],
    #     )
    # )
    .render("map_globe.html")
)

```

However the chart looks strange for me.
<img width="749" alt="image" src="https://github.com/pyecharts/pyecharts/assets/5254627/36b2ea20-aa21-44fb-8110-d4859cf18dcf">

My development environment consists of Python 3.11 and Pyecharts version 2.0.4.

Anything I miss?

**Comment by sunhailin-Leo** [comment]
@wybert 
* Since newer versions of the Chrome kernel restrict references to local files. Therefore, this type of issue should first be troubleshooted in the browser console for cross-domain or security alerts;
To resolve such issues, you must either put the html files and static resources under the same domain or start Chrome in an insecure mode.
