### ISSUE TITLE
TooltipOpts map地图中要同时展示gmv, 有人对接供应商数，无人对接供应商数,提示框需要有人对接供应商数，无人对接供应商数

### ISSUE THREAD

**Issue by Xenia-cxm** [pyecharts/pyecharts#2284]
**问题**

TooltipOpts map地图中要同时展示gmv, 有人对接供应商数，无人对接供应商数,提示框需要有人对接供应商数，无人对接供应商数
我看到知乎[pyecharts 之 JsCode 的妙用](https://zhuanlan.zhihu.com/p/133533187)，尝试按里面的方式
我尝试把它gmv, 有人对接供应商数，无人对接供应商数 作为一个lsit（省份，list(gmv, 有人对接供应商数，无人对接供应商数)）放入
map()中并使用formatter=JsCode( "function (x) { console.log(x); return x; }") ，查看返回的参数时null

**运行环境（系统环境及 pyecharts 版本）**

Windows 10
pyecharts                 2.0.4

**代码及截图**

from pyecharts.charts import Map, HeatMap, Grid, Bar, Page
from pyecharts import options as opts
from pyecharts.globals import ThemeType
from pyecharts.commons.utils import JsCode
from pyecharts.faker import Faker

provinces = ['安徽省', '福建省', '甘肃省', '广东省', '广西壮族自治区', '贵州省', '河北省', '河南省', '湖北省', '湖南省', '江苏省', '江西省', '内蒙古自治区',
             '宁夏回族自治区', '山东省', '山西省', '陕西省', '四川省', '天津市', '云南省', '浙江省', '重庆市']
gmv = [2100, 41, 95, 3074, 48, 32, 1862, 978, 833,4397, 67, 206, 0, 23, 50, 1, 61, 524, 3,28, 28, 512]
provider = [45, 2, 3, 54, 8, 2, 44, 10, 11, 27, 4, 16, 1, 1, 5, 2, 2, 26, 1, 5, 3, 9]
n_provider = [36, 1, 1, 24, 0, 0, 38, 4, 6, 23, 0, 1, 0, 0, 0, 0, 2, 23, 0, 3, 2, 6]

# 创建区域图
amount_map = (
    Map(init_opts=opts.InitOpts(width="1200px", height="600px"))
    .add(
        "",
        [list(z) for z in zip(provinces,[list(z) for z in zip(gmv,provider,n_provider)])],
        maptype="china",
        is_map_symbol_show=False,
        is_roam=True,
        itemstyle_opts={
            "normal": {"area_color": "rgba(50, 60, 72, 0.7)", "border_color": "#111"},
            "emphasis": {"label": {"show": True}},
        },
        label_opts=opts.LabelOpts(
            position="right",
            formatter=JsCode(
                "function (x) { console.log(x); return x; }"
            ),
        )
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="中药供应商金额", subtitle="Q4均值:单位万"),
        visualmap_opts=opts.VisualMapOpts(
            min_=min(gmv),
            max_=max(gmv),
            range_text=["High", "Low"],
            is_calculable=True,
            range_color=["#50a3ba", "#eac736", "#d94e5d"],
            # 设置色阶在右侧
            pos_left="left",
        ),
        # 设置图例在右侧
        legend_opts=opts.LegendOpts(pos_left="left"),
    )
     .render("stack_bar_percent.html")
)

![Snipaste_2024-01-15_16-57-02](https://github.com/pyecharts/pyecharts/assets/61578932/0cd6a683-d71f-4824-85bb-24c7204acf36)

**Comment by sunhailin-Leo** [comment]
@Xenia-cxm 
* 试下在 ToolTips 写回调呢？Label 一般只展示地名的
