### ISSUE TITLE
Sankey图的EdgeLabel无法显示具体数值

### ISSUE THREAD

**Issue by BpointA** [pyecharts/pyecharts#2287]
**问题**
在绘制桑基图时，需要在每条边上体现具体的数值，但是无法通过formatter实现。
js中正确的formatter应该是{c}，但pyecharts中输入{c}显示的是undefined。

**运行环境（系统环境及 pyecharts 版本）**
python 3.10.8
pyecharts 2.0.4

**代码及截图**
add中代码如下：
            edge_label_opt=opts.LabelOpts(position="right",

                                  font_size=12,
                                  formatter='{c}',

                                  ),

以下是在echarts(js)中使用formatter={c}的结果
![image](https://github.com/pyecharts/pyecharts/assets/46481277/f91d27f1-5c83-4cb9-8b14-0375d91c12aa)

以下是在pyecharts(js)中使用formatter={c}的结果

![image](https://github.com/pyecharts/pyecharts/assets/46481277/e31d3953-a878-45e2-aa13-4f4f16a2277b)

**Comment by sunhailin-Leo** [comment]
@BpointA 
* 用 JsCode 回调看一下差别？

**Comment by BpointA** [comment]
> @BpointA
> 
> * 用 JsCode 回调看一下差别？
![image](https://github.com/pyecharts/pyecharts/assets/46481277/de9b9973-647e-4bf4-9af7-48aea2127663)
试了一下pyecharts的回调，没有看到value相关的值（但是鼠标移上去是可以看得到值的，不知道是不是只能在tooltip里面看，不能在label里面看？）

**Comment by BpointA** [comment]
> @BpointA
> 
> * 用 JsCode 回调看一下差别？

[
<img width="130" alt="2024-01-23_165527" src="https://github.com/pyecharts/pyecharts/assets/46481277/2e605128-7522-4e73-9154-482f905f2f5b">
](url)

试了一下直接返回全部值，没有看到value相关的信息，但是在tooltip里面又能看得见具体的数值。

**Comment by sunhailin-Leo** [comment]
@BpointA 试下这个代码
```python
nodes = [
        {"name": "category1"},
        {"name": "category2"},
        {"name": "category3"},
        {"name": "category4"},
        {"name": "category5"},
        {"name": "category6"},
    ]

    links = [
        {"source": "category1", "target": "category2", "value": 10},
        {"source": "category2", "target": "category3", "value": 15},
        {"source": "category3", "target": "category4", "value": 20},
        {"source": "category5", "target": "category6", "value": 25},
    ]
    c = (
        Sankey()
        .add(
            "sankey",
            nodes,
            links,
            edge_label_opt=opts.LabelOpts(is_show=True),
            linestyle_opt=opts.LineStyleOpts(opacity=0.2, curve=0.5, color="source"),
            label_opts=opts.LabelOpts(position="right"),
        )
        .set_global_opts(title_opts=opts.TitleOpts(title="Sankey-基本示例"))
    )
```

**Comment by BpointA** [comment]
> @BpointA 试下这个代码
> 
> ```python
> nodes = [
>         {"name": "category1"},
>         {"name": "category2"},
>         {"name": "category3"},
>         {"name": "category4"},
>         {"name": "category5"},
>         {"name": "category6"},
>     ]
> 
>     links = [
>         {"source": "category1", "target": "category2", "value": 10},
>         {"source": "category2", "target": "category3", "value": 15},
>         {"source": "category3", "target": "category4", "value": 20},
>         {"source": "category5", "target": "category6", "value": 25},
>     ]
>     c = (
>         Sankey()
>         .add(
>             "sankey",
>             nodes,
>             links,
>             edge_label_opt=opts.LabelOpts(is_show=True),
>             linestyle_opt=opts.LineStyleOpts(opacity=0.2, curve=0.5, color="source"),
>             label_opts=opts.LabelOpts(position="right"),
>         )
>         .set_global_opts(title_opts=opts.TitleOpts(title="Sankey-基本示例"))
>     )
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/17564655/298959082-c2b8842d-614e-4ca5-ab5a-4fc7b3c80aaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjM2NTksIm5iZiI6MTcwNjA2MzM1OSwicGF0aCI6Ii8xNzU2NDY1NS8yOTg5NTkwODItYzJiODg0MmQtNjE0ZS00Y2E1LWFiNWEtNGZjN2IzYzgwYWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZGM1MDIwOGVhZGZiYmM0OWQwZmNiODNkNTI0ZjY2YWMwN2NjODQ0MzVhYjRkZDAzOGFhYTUxMjQxYzAwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bv6c9vwsuPNFh5GDzZ1nCHaLeL4Nx-9KFWXwQpmo6sQ)

可以了，感谢！
我排查了一下，是我在label_opt中设置了格式={b}，去掉之后就好了。
