### ISSUE TITLE
执行函数：Tab.render()时报错

### ISSUE THREAD

**Issue by SBshenqianye** [pyecharts/pyecharts#2290]
**问题**
运行如下关键代码时报错：
tab = Tab()
tab.add(functionWhichRetrunCharts(), "tabName")
tab.render(filepath)     # 报错报在这一行

随后我降低版本到2.0.3（官方画廊演示版本）尝试新建文件，单独使用官方画廊的示例代码运行，还是报同样的错

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 版本：2.0.3
python版本：3.9.7
系统环境：windows11

**代码及截图**
代码详见官方画廊：
https://gallery.pyecharts.org/#/Tab/tab_base
代码预览：
![image](https://github.com/pyecharts/pyecharts/assets/51922539/65d1aa6c-5e9f-4edd-94d6-8823de967de6)

运行结果图：

![image](https://github.com/pyecharts/pyecharts/assets/51922539/3f61d60d-4d71-4dcc-a313-e53e87b9f75f)

**Comment by sunhailin-Leo** [comment]
@SBshenqianye 
* 我这边还不同环境测试都是没有问题的哈~
