### ISSUE TITLE
Feature Request: Offline Support for Pyecharts

### ISSUE THREAD

**Issue by asimkymk** [pyecharts/pyecharts#2292]
Issue:

Currently, Pyecharts does not support offline operation, which makes it difficult to use in environments without internet connection or where there are data security concerns.

Proposed Solution:

We request the following features to be added to Pyecharts to support offline operation with offline parameter in render functions:

Local echarts.min.js file usage: Pyecharts should support offline operation by embedding an echarts.min.js file in the HTML file. This will allow users to view graphs without being connected to the internet.
Optional dependencies: Pyecharts should make dependencies on certain libraries that require internet connection, such as echarts-gl, optional. This will allow users to use Pyecharts without internet connection when they do not need these libraries.
Environment:

Pyecharts Version: 2.0.4
Operating System: Windows 10
Python Version: 3.8.10
Example Code and Screenshot:

No example code and screenshot are available for this request at this time.

Additional Information:

Offline support for Pyecharts will allow users to use this library in a wider range of scenarios.
This feature is also important for users who have concerns about data security and internet connection access.

**Comment by sunhailin-Leo** [comment]
@asimkymk 
* Maybe you can use local server to deploy~ https://pyecharts.org/#/en-us/assets_host?id=localhost-server
