### ISSUE TITLE
Feautre request: Time support to stacked bar plots?

### ISSUE THREAD

**Issue by alexmassen-hane** [pyecharts/pyecharts#2293]
### Question

Could you please add time support to a stacked bar plot? Only floats or integers are able to be stacked together. 
I am trying to a create a gantt / waterfall like plot but with a collection of many different tasks that have start and end dates and times. Please see the example code snippet below.

If I am missing something, please let me know how I can go about this.

Thanks. 

### Operating environment (system environment and pyecharts version)

- Python v3.10.12
- Pyecharts v2.0.4

### Code and screenshots

```
    data = [
        ("Task 1", "2024-02-14", "2024-02-20"),
        ("Task 2", "2024-02-15", "2024-02-25"),
        ("Task 3", "2024-02-16", "2024-02-23"),
    ]

    chart = (
        Bar()
        .add_xaxis([task[0] for task in data])
        .add_yaxis(
            "title 1",
            [task[1] for task in data],
            stack="total",
            label_opts=opts.LabelOpts(is_show=False),
            itemstyle_opts=opts.ItemStyleOpts(border_color="red", color="red"),
        )
        .add_yaxis(
            "title2",
            [task[2] for task in data],
            stack="total",
            itemstyle_opts=opts.ItemStyleOpts(border_color="blue", color="blue"),
        )
        .set_global_opts(
            yaxis_opts=opts.AxisOpts(
                type_="time",
            ),
        )
    )
```

which looks something like this

![image](https://github.com/pyecharts/pyecharts/assets/104514872/fb26da7f-1d15-42a6-83b7-77c3aaae05a7)

**Comment by sunhailin-Leo** [comment]
@alexmassen-hane 
* https://echarts.apache.org/en/option.html#series-bar.stack
* Not support yet~
