### ISSUE TITLE
pyecharts.map可视化时如何向提示框中添加多组数据？

### ISSUE THREAD

**Issue by W12qq** [pyecharts/pyecharts#2294]
**问题**
我最近在做一个关于全国水稻的空间分布图，是使用pyecharts.map完成的，现在向提示框中添加多组数据，就是鼠标移动到某个省时显示该省的所有数据，比如要显示，产量：3242.32（换行）面积：3445.32，卡这里很久了，找了几天资料，没啥进展，恳请大神相助。多谢！

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 2.0.4

**Comment by sunhailin-Leo** [comment]
@W12qq 
* 用回调函数展示
