### ISSUE TITLE
使用自己构建的主题时，线型、平滑等样式无效

### ISSUE THREAD

**Issue by jzwupeng** [pyecharts/pyecharts#2296]
根据文档中使用自己构建的主题的方法，从[主题构建工具](http://echarts.baidu.com/theme-builder/)创建并下载chalka.js，放到本地资源文件服务器，用以下代码能创建一个html文件，但是除了颜色类属性能正常显示外，其他的线型，坐标轴，平滑等设置均不生效，相关资料较少，目前无法解决，请大神帮忙看看，如何解决？

**运行环境（系统环境及 pyecharts 版本）**
win11，py2.8.8

**代码及截图**
from pyecharts.charts import Line
from pyecharts.faker import Faker
from pyecharts import options as opts

from pyecharts.globals import CurrentConfig
from pyecharts.datasets import register_files
register_files({"chalka": ["themes/chalka", "js"]})
CurrentConfig.ONLINE_HOST = "http://127.0.0.1/assets/"

c = (
    Line(init_opts=opts.InitOpts(theme='chalka'))
    .add_xaxis(Faker.months)
    .add_yaxis("商家A", Faker.months_values())
    .add_yaxis("商家B", Faker.months_values())
    .add_yaxis("商家C", Faker.months_values())
    .add_yaxis("商家D", Faker.months_values())
    .set_global_opts(
        title_opts={"text": "Bar-通过 dict 进行配置", "subtext": "我也是通过 dict 进行配置的"}
    )
)
c.render('page1.html')

![32BA840D-7241-45ea-924C-AD7856D4C10B](https://github.com/pyecharts/pyecharts/assets/36872994/834276b1-3902-4b77-bdcf-4adc51d411ef)

**Comment by jzwupeng** [comment]
主题构建工具的图表样式：
![5CA65097-3F1D-412e-A3FE-6A7EBCF54C26](https://github.com/pyecharts/pyecharts/assets/36872994/ddacfce9-d1ab-46e7-931c-b684dce73ff5)
js文件：
[chalka.txt](https://github.com/pyecharts/pyecharts/files/14355915/chalka.txt)
js无法上传，改为txt

**Comment by sunhailin-Leo** [comment]
@jzwupeng 
* 有没一种可能，曲线的样式配置和主题配置无关呢？

**Comment by sunhailin-Leo** [comment]
@sunhailin-Leo 
* 画图的时候要另外指定，pyecharts 渲染的时候不会去读 js 里面的配置

**Comment by jzwupeng** [comment]
@sunhailin-Leo 
那就是不能自己构建主题了，还是得一个一个指定，要实现换肤就要再做一套？

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo 那就是不能自己构建主题了，还是得一个一个指定，要实现换肤就要再做一套？

* 自定义主题和基础样式（不包括图标配置）实际上分离的。只是你在前端主题构建工具里面是一套的。

**Comment by jzwupeng** [comment]
@sunhailin-Leo 
好的，非常感谢。
