### ISSUE TITLE
How to set bubble marker on all bars in bar chart

### ISSUE THREAD

**Issue by vladimirkovacevic** [pyecharts/pyecharts#2297]
I want to create bar chart visualisation that will have value indicators over every bar in bar chart.
```

bar = Bar().add_xaxis(ds)
    for yxais in scores:
        bar.add_yaxis(*yxais)
        bar.set_global_opts(title_opts=opts.TitleOpts(title=f'Retention percentage'))
        bar.set_series_opts(
            label_opts=opts.LabelOpts(is_show=False),
            markpoint_opts=opts.MarkPointOpts(
                data=[
                    opts.MarkPointItem(type_="max", name="", symbol_size=54),
                    opts.MarkPointItem(type_="min", name="", symbol_size=54),
                    opts.MarkPointItem(type_="average", name="", symbol_size=54),
                ]
            ),
        )
        bar.render(metric + ".html")

```

But, MarkPointItem requires setting "type_" which must be some of max, min or average, but that leaves some of the bars without value above them. How can I set value above every bar in barplot?

**Comment by sunhailin-Leo** [comment]
@vladimirkovacevic 
* Try this code
```python
from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.faker import Faker


xAxis = Faker.choose()
yAxis = Faker.values()
mark_point_datas = []

for i in range(len(xAxis)):
    mark_point_datas.append(opts.MarkPointItem(name=f"{i}", coord=[i, yAxis[i]], value=yAxis[i]))


c = (
    Bar()
    .add_xaxis(xAxis)
    .add_yaxis("商家A", yAxis)
    .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"))
    .set_series_opts(markpoint_opts=opts.MarkPointOpts(data=mark_point_datas))
    .render("issue_2297.html")
)
```

![image](https://github.com/pyecharts/pyecharts/assets/17564655/a35b4122-cdfd-4e60-836d-0f077fe57216)

**Comment by vladimirkovacevic** [comment]
@sunhailin-Leo thank you for detailed response. One more thing, if I have a grouping like in this attached image
<img width="768" alt="bar" src="https://github.com/pyecharts/pyecharts/assets/16796045/ccc919df-f65d-4f78-81b4-bec8f15b23ff">
how can I set coord parameter in MarkPointItem object?

**Comment by sunhailin-Leo** [comment]
@vladimirkovacevic 
* You can try this: `add_yaxis("商家A", yAxis, markpoint_opts=opts.MarkPointOpts(data=mark_point_datas))` instead of ``set_series_opts
