### ISSUE TITLE
script error when using 3D charts in Databricks notebook

### ISSUE THREAD

**Issue by processadd** [pyecharts/pyecharts#2298]
Hi,
When using pyecharts in Databricks notebook, other charts can display correctly, but for 3D charts it always throws "script error". From Chrome:
<img width="795" alt="image" src="https://github.com/pyecharts/pyecharts/assets/27667124/ff067cd7-bbec-454e-9121-b2d5c08c1ea9">
If I open echarts-gl.min.js locally from my VSCode, the chars around echarts-gl.min.js:1:460874 looks like:
```
var Vh={å—æµ·è¯¸å²›:[32,80],å¹¿ä¸œ:[0,-10],é¦™æ¸¯:[10,5],æ¾³é—¨:[-10,10],å¤©æ´¥:[5,5]},Hh={Russia:[100,60],"United States":[-99,38],"United States of America":[-99,38]},
```
Can you please help on how to fix this?
Thanks

**Comment by sunhailin-Leo** [comment]
@processadd 
It looks like a character encoding problem. However, we don't have a Databricks notebook to test for this issue, so we can't fix it at this time.
