### ISSUE TITLE
无法修改地图的长宽比例

### ISSUE THREAD

**Issue by zzhasd** [pyecharts/pyecharts#2303]
**问题**
无法修改地图的长宽比例

**运行环境（系统环境及 pyecharts 版本）**
Name: pyecharts
Version: 2.0.5
Summary: Python options, make charting easier
Home-page: https://github.com/pyecharts/pyecharts
Author: chenjiandongx
Author-email: chenjiandongx@qq.com
License: MIT
Location: /opt/conda/lib/python3.6/site-packages
Requires: jinja2, prettytable, simplejson
Required-by: 

python版本：3.6.4

**代码及截图**
按照官方文档加上长宽比时报错：
c = (
    Map()
    .add(
        "",
        [list(z) for z in zip(地区, 乡绿化覆盖面积)],
        "china", is_map_symbol_show=False,
        aspect_scale=0.75,  #在这里使用了官方文档的配置，但是出现了报错，无法编译
        is_roam=False,
        center=[108.9236111, 37.0408333],
        zoom=1.65,
        label_opts=opts.LabelOpts(is_show=False)
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="2022年绿地覆盖面积（公顷）", pos_left="center"),
        legend_opts=opts.LegendOpts(orient="horizontal", pos_top="bottom", pos_left="center"),
        visualmap_opts=opts.VisualMapOpts(
            max_=15495, 
            min_=0,    
            is_piecewise=True, 
            pieces=[  # 定义分段及其颜色
                {"min": 6000, "max": 15495, "label": '10400-13000', "color": "#d95c3d"},
                {"min": 3000, "max": 6000, "label": '7800-10400', "color": "#f07d57"},
                {"min": 1000, "max": 3000, "label": '5200-7800', "color": "#e6a278"},
                {"min": 500, "max": 1000, "label": '2600-5200', "color": "#fac79b"},
                {"min": 0, "max": 500, "label": '0-2600', "color": "#ffeebf"},
                {"min": -20, "max": -1, "label": '数据缺失', "color": "#eeeeee"},
            ]),
    )
)

c.render_notebook()

![QQ截图20240310202712](https://github.com/pyecharts/pyecharts/assets/132881287/d6497d32-eb22-4931-8cfe-56feadda1e0c)

![QQ截图20240310202742](https://github.com/pyecharts/pyecharts/assets/132881287/42cf1528-56bf-4ce4-bd69-115f0868cac4)

去掉该配置则一切正常：
![QQ截图20240310203010](https://github.com/pyecharts/pyecharts/assets/132881287/6d879c3c-568b-4c2c-9ea3-f7d0a80f25eb)
![QQ截图20240310203019](https://github.com/pyecharts/pyecharts/assets/132881287/fdc4fafb-a194-4be3-8372-ba45aec4e02e)

**Comment by sunhailin-Leo** [comment]
@zzhasd 
* 目前没加这个参数，所以函数没有这个参数肯定会报错的

**Comment by sunhailin-Leo** [comment]
@zzhasd 
* 我这边测试过是没有问题的哈～，你再好好检查一下代码
