### ISSUE TITLE
Map或自定义多边形下钻

### ISSUE THREAD

**Issue by MaKangChina** [pyecharts/pyecharts#2304]
**问题**
老师好，请问能实现在Map或自定义多边形中下钻吗？类似于下面网址的功能，谢谢
https://xiangyuecn.gitee.io/areacity-jsspider-statsgov/assets/geo-echarts.html

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@MaKangChina 
* 下钻得自己写 js 事件的，暂时不支持

**Comment by sunhailin-Leo** [comment]
* 未来增加 dataGroup 的这个配置项，不过一些操作相关的交互得还是得前端进行控制。

**Comment by MaKangChina** [comment]
> * 未来增加 dataGroup 的这个配置项，不过一些操作相关的交互得还是得前端进行控制。

好的好的，感谢老师！
