### ISSUE TITLE
日历图设置name_map='cn'后，调用.render_notebook()仍然显示英文月份和星期

### ISSUE THREAD

**Issue by lisennku** [pyecharts/pyecharts#2305]
**问题**
按照gallery中[更改中文标签](https://gallery.pyecharts.org/#/Calendar/calendar_label_setting)的代码进行验证，去掉保存为HTML文件的语句，增加`c.render_notebook()`，仍然显示中文，但是如果保存到HTML文件，又能正确显示，请问是render_notebook的问题么？

**运行环境（系统环境及 pyecharts 版本）**
jupyterlab  3.6.3
pyecharts  2.0.5

**代码及截图**
代码如下，其中load 和 render位于不同单元格
```python
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB

import datetime
import random
from pyecharts import options as opts
from pyecharts.charts import Calendar


begin = datetime.date(2017, 1, 1)
end = datetime.date(2017, 12, 31)
data = [
    [str(begin + datetime.timedelta(days=i)), random.randint(1000, 25000)]
    for i in range((end - begin).days + 1)
]

c = (
    Calendar()
    .add(
        "",
        data,
        calendar_opts=opts.CalendarOpts(
            range_="2017",
            daylabel_opts=opts.CalendarDayLabelOpts(name_map="cn"),
            monthlabel_opts=opts.CalendarMonthLabelOpts(name_map="cn"),
        ),
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Calendar-2017年微信步数情况(中文 Label)"),
        visualmap_opts=opts.VisualMapOpts(
            max_=20000,
            min_=500,
            orient="horizontal",
            is_piecewise=True,
            pos_top="230px",
            pos_left="100px",
        ),
    )
 # .render("calendar_label_setting.html")
)
c.load_javascript()

c.render_notebook()
```
![image](https://github.com/pyecharts/pyecharts/assets/3314511/43de1391-63d3-49aa-9ebe-2f10aedb0bfd)

**Comment by sunhailin-Leo** [comment]
@lisennku 
* 如果不在 jupyter 中会有这个情况出现嘛？

**Comment by lisennku** [comment]
> @lisennku
> 
> * 如果不在 jupyter 中会有这个情况出现嘛？

我尝试在jupyter环境中调用`.render()`，和在conda命令行中调用`.render()`，在生成的HTML文件中都显示的是中文哈

**Comment by sunhailin-Leo** [comment]
> > @lisennku
> > 
> > * 如果不在 jupyter 中会有这个情况出现嘛？
> 
> 我尝试在jupyter环境中调用`.render()`，和在conda命令行中调用`.render()`，在生成的HTML文件中都显示的是中文哈

那就奇怪了，你用 `render_notebook()` 的时候，看一下浏览器控制台有没有报错信息之类的？

**Comment by sunhailin-Leo** [comment]
@lisennku 
* 用 `ZH` 吧，`cn` 不生效可能是 Echarts 的 bug
![image](https://github.com/pyecharts/pyecharts/assets/17564655/d9b04e4f-ff57-43eb-ba47-c4abff6d3452)

**Comment by lisennku** [comment]
> @lisennku
> 
> * 用 `ZH` 吧：https://echarts.apache.org/zh/option.html#calendar.dayLabel.nameMap
>   ![image](https://private-user-images.githubusercontent.com/17564655/313552014-d9b04e4f-ff57-43eb-ba47-c4abff6d3452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDE4NDcsIm5iZiI6MTcxMDc0MTU0NywicGF0aCI6Ii8xNzU2NDY1NS8zMTM1NTIwMTQtZDliMDRlNGYtZmY1Ny00M2ViLWJhNDctYzRhYmZmNmQzNDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA1NTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZmMzZTkyMzRkNzVkZTAwNDc2OTc4MGNkMjdhODFhMTdiZTZhOTViZGI3OTE3OTA1NTlmM2FiYmZhMjkzMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AreHqoJoMys7Ql1MaiSzrhBuWm_botjyWktsQOrq2vA)

感谢！
之前试过zh，没想到要大写🤦‍♂️
