### ISSUE TITLE
geo生成的html显示纬度数据而非指定数据

### ISSUE THREAD

**Issue by yangq-15256204** [pyecharts/pyecharts#2307]
问题

pyecharts 使用add_coordinate_json添加经纬度坐标，add数据后图中数据维度而不是坐标

运行环境（系统环境及 pyecharts 版本）
pyecharts2.05，python3.11

代码及截图
```python
earthquake = pd.read_csv(earthquake_file_path)
earthquake = earthquake[:2]
earthquake_coordinates = {earthquake['ID'][_] : [earthquake['Longitude'][_], earthquake['Latitude'][_]] for _ in range(len(earthquake))}
json_str = json.dumps(earthquake_coordinates, indent=5)
with open(earthquake_json_path, 'w', encoding='utf-8') as file:
    file.write(json_str)

earthquake_magnitude = earthquake['Magnitude'].astype(float).to_list()
all_data = [list(_) for _ in zip(earthquake['ID'], earthquake['Magnitude'])]

world_map = charts.Geo()
world_map.add_schema(maptype='world')
world_map.add_coordinate_json(earthquake_json_path)
world_map.add('Magnitude', data_pair=all_data)
world_map.render_notebook()
``` 

![image](https://github.com/pyecharts/pyecharts/assets/64117556/0b6df5c7-95d2-44e7-b6d5-fdfc2a589c68)
![image](https://github.com/pyecharts/pyecharts/assets/64117556/f29ec6c2-0939-45b2-9079-22169050a5a9)

**Comment by yangq-15256204** [comment]
渲染之前添加world_map.set_global_opts()即可正常显示
![image](https://github.com/pyecharts/pyecharts/assets/64117556/2b43ec19-6200-48e9-8f16-1c08266e28b6)

**Comment by yangq-15256204** [comment]
通过视觉通道进行筛选时候，鼠标移至非筛选出来的点，也会有提示框。如下图
![image](https://github.com/pyecharts/pyecharts/assets/64117556/44b8c366-2dd5-408b-8f64-e55a5762fb76)

**Comment by sunhailin-Leo** [comment]
> 通过视觉通道进行筛选时候，鼠标移至非筛选出来的点，也会有提示框。如下图 ![image](https://private-user-images.githubusercontent.com/64117556/313650449-44b8c366-2dd5-408b-8f64-e55a5762fb76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzI0MTgsIm5iZiI6MTcxMTUzMjExOCwicGF0aCI6Ii82NDExNzU1Ni8zMTM2NTA0NDktNDRiOGMzNjYtMmRkNS00MDhiLThmNjQtZTU1YTU3NjJmYjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNDYzMTkyY2ZjMTdmZWViMzAyOWU2MGY3MTA5OGJmOGQ2NWViYTU0YmU5Mzc4YmIzMzRlZjE2NDRkMTIxNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6kLpa83OtfkpagM5D9Bh8qLhMAPN90YUkqPQzd9mang)

* 这个目前看来，分组和连续型都会有这个问题。具体为什么 Echarts 这么设计也不太清楚，这块我估计只能通过前端 js 去判断，结果是否在选中的分组中，然后判断是否展示这个 tooltip 了。

**Comment by yangq-15256204** [comment]
> > 通过视觉通道进行筛选时候，鼠标移至非筛选出来的点，也会有提示框。如下图 ![image](https://private-user-images.githubusercontent.com/64117556/313650449-44b8c366-2dd5-408b-8f64-e55a5762fb76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzI0MTgsIm5iZiI6MTcxMTUzMjExOCwicGF0aCI6Ii82NDExNzU1Ni8zMTM2NTA0NDktNDRiOGMzNjYtMmRkNS00MDhiLThmNjQtZTU1YTU3NjJmYjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNDYzMTkyY2ZjMTdmZWViMzAyOWU2MGY3MTA5OGJmOGQ2NWViYTU0YmU5Mzc4YmIzMzRlZjE2NDRkMTIxNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6kLpa83OtfkpagM5D9Bh8qLhMAPN90YUkqPQzd9mang)
> 
> * 这个目前看来，分组和连续型都会有这个问题。具体为什么 Echarts 这么设计也不太清楚，这块我估计只能通过前端 js 去判断，结果是否在选中的分组中，然后判断是否展示这个 tooltip 了。

感谢您的回答，我这边根据需求调整一下。
