### ISSUE TITLE
桑基图中edge_label_opt属性设置文字位置失效

### ISSUE THREAD

**Issue by LongShen3188** [pyecharts/pyecharts#2309]
**python版本3.12，pyecharts版本2.0.5**

**桑基图中edge_label_opt属性设置文字位置失效**

**win11 + pyecharts版本2.0.5**

**代码及截图**
![1711396698793](https://github.com/pyecharts/pyecharts/assets/164940130/6bf1edba-fe08-444f-8466-f029f6100468)
**红框部分不管怎么设置position都无法生效，生成的图表文字都是居中，生成的图像如下：**
![image](https://github.com/pyecharts/pyecharts/assets/164940130/66eb0db6-2291-462d-867f-529af4a20a80)

**Comment by sunhailin-Leo** [comment]
@LongShen3188 你指的是哪一块的文字居中?

**Comment by sunhailin-Leo** [comment]
@LongShen3188 
* EdgeLabel 的 `position` 暂时没用，因为 `Echarts` 目前对这个 `Label` 没有 `position` 的参数。
* 在 `pyecharts` 里面有一些配置项是为了避免过多的增加配置项。
* 如果 `LabelOpts` 中没有你想要的配置项，你也可以用 `dict` 按照 `Echarts` 的配置进行设置：https://echarts.apache.org/zh/option.html#series-sankey.edgeLabel
