### ISSUE TITLE
3d曲面图放在时间轴里无法显示

### ISSUE THREAD

**Issue by Hakuhuhu** [pyecharts/pyecharts#2310]
3d曲面图放在时间轴里无法显示，单独显示都没有问题
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@Hakuhuhu 
* 3D 的图暂时都不太行，后续版本可能会考虑如何去兼容一下

**Comment by sunhailin-Leo** [comment]
@Hakuhuhu 
* Closed it then waiting for new version.
