### ISSUE TITLE
pyecharts支持自定义图吗

### ISSUE THREAD

**Issue by Memodeer** [pyecharts/pyecharts#2311]
我有一个视频，通过pyannote识别出了声纹，我想通过pyecharts呈现话语状况，观察说话情况，不同说话者的高度不同，也就是y值不同，然后随时间画横线
差不多就是这样(如图)
![20240402111817](https://github.com/pyecharts/pyecharts/assets/73208313/62edd1c0-4a2b-42c9-b1ce-d3f62fa46dff)

**Comment by sunhailin-Leo** [comment]
@Memodeer 
* 这个不能叫自定义图吧？用折线图就可以了。
* 本质是上一堆线段，你的 y 轴就是一段相同的折线，x 轴是你的时间。
