### ISSUE TITLE
桑基图中某一层级的顺序能固定吗？

### ISSUE THREAD

**Issue by lllllrc** [pyecharts/pyecharts#2313]
**问题**

如下图，改动 `node_gap` 等一些参数会导致生成的图的顺序发生改变，有时候healthy在中间，有时候在下面，我希望能够按照 sepsis，ICU，healthy的固定顺序排列，请问这个功能能够实现吗？
![image](https://github.com/pyecharts/pyecharts/assets/76392701/d218b7b4-0bd5-49df-8b71-b9421b386169)
![image](https://github.com/pyecharts/pyecharts/assets/76392701/3bf404be-dcca-4246-8470-b379ea627d35)

**Comment by sunhailin-Leo** [comment]
@lllllrc 
* 目前来看好像是没有这类操作，你可以去 Echarts 的仓库问问，或者你看网上有没有相关的实现，然后贴个链接出来。
