### ISSUE TITLE
折线树图不支持

### ISSUE THREAD

**Issue by hellomyheart** [pyecharts/pyecharts#2317]
**问题**

我想画一个和echarts示例中一样的折线树图

https://echarts.apache.org/examples/zh/editor.html?c=tree-polyline

![image](https://github.com/pyecharts/pyecharts/assets/31239692/22f8d677-baf3-4859-8f53-304743c15b58)

但是画出来的效果却不是我想要的

![image](https://github.com/pyecharts/pyecharts/assets/31239692/070482ee-d9ed-4e63-8992-f20fb992afd2)

代码如下：

```py
from pyecharts import options as opts
from pyecharts.charts import Tree

data = [
    {
        "children": [
            {"name": "中文B"},
            {
                "children": [{"children": [{"name": "I"}], "name": "E"}, {"name": "F"}],
                "name": "C",
            },
            {
                "children": [
                    {"children": [{"name": "J"}, {"name": "K"}], "name": "G"},
                    {"name": "H"},
                ],
                "name": "D",
            },
        ],
        "name": "A",
    }
]

c = (
    Tree()
    .add("", data)
    .set_global_opts(
        tooltip_opts=opts.TooltipOpts(trigger="item", trigger_on="mousemove"),
        title_opts=opts.TitleOpts(title="Tree-基本示例")
    )
    .set_series_opts(
        edge_shape="polyline",
        edgeForkPosition="90%",  # 设置边的角度为90度，即直线
        lineStyle=opts.LineStyleOpts(width=2)  # 设置边的样式
    )
)

c.render_notebook()
```

**运行环境（系统环境及 pyecharts 版本）**
python 3.11
pyecharts  2.0.5

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@hellomyheart 
* 你的配置有问题哈：
![image](https://github.com/pyecharts/pyecharts/assets/17564655/a520c9c6-46e4-4c7f-bd72-de2a65e89b59)
![image](https://github.com/pyecharts/pyecharts/assets/17564655/68d26b33-56cf-467f-b877-093ca9c15f0a)

**Comment by hellomyheart** [comment]
> @hellomyheart
> 
> * 你的配置有问题哈：
>   ![image](https://private-user-images.githubusercontent.com/17564655/322350393-a520c9c6-46e4-4c7f-bd72-de2a65e89b59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjA1NzksIm5iZiI6MTcxMzE2MDI3OSwicGF0aCI6Ii8xNzU2NDY1NS8zMjIzNTAzOTMtYTUyMGM5YzYtNDZlNC00YzdmLWJkNzItZGUyYTY1ZTg5YjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1NTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YTkxM2U2NjY5YjE1NTEyZWMwOWUyNWE4ZjVmZjgwOGZmZmYzOTQ4ZTA2NDg2MzY5ZWFhMmExOWJiYjdlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qJ0wgP-3foMgRsEcT253mt2qlgRL7W2_ESYbrsCuhJg)
>   ![image](https://private-user-images.githubusercontent.com/17564655/322350421-68d26b33-56cf-467f-b877-093ca9c15f0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjA1NzksIm5iZiI6MTcxMzE2MDI3OSwicGF0aCI6Ii8xNzU2NDY1NS8zMjIzNTA0MjEtNjhkMjZiMzMtNTZjZi00NjdmLWI4NzctMDkzY2E5YzE1ZjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1NTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYjY1OTQ4MzNhYTYzN2I1N2RmOTFmOWEzMjUzMWRiNDg0YWE3YTk4NDNhOTIxYmJhZjQzNzJmMTg3ZWNmOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Cp7yKYhADjrmIISzauuO5Yx1lt_k23Vlih5eye8NAE)

感谢
