### ISSUE TITLE
jupyterhub中使用时出现require is not defined

### ISSUE THREAD

**Issue by nameljw** [pyecharts/pyecharts#2318]
**问题**
1、jupyterhub中使用时出现require is not defined
2、离线情况下jupyterhub中该如何部署静态服务器资源

**运行环境（系统环境及 pyecharts 版本）**
jupyterhub：2.0.1
pyecharts：2.0.5
python：3.8
linux
在线显示不出图片

**代码及截图**
<img width="800" alt="屏幕截图 2024-04-16 163258" src="https://github.com/pyecharts/pyecharts/assets/94057485/f3f88879-42f0-4548-b34a-76420609daf9">

**Comment by sunhailin-Leo** [comment]
@nameljw 
* https://pyecharts.org/#/zh-cn/assets_host
