### ISSUE TITLE
Kline配置k线图全是红线

### ISSUE THREAD

**Issue by hall130** [pyecharts/pyecharts#2321]
**问题**
2.0.4版本使用kline画k线图时，无论下跌还是上涨都是红色k线

**运行环境（系统环境及 pyecharts 版本）**
python3.8.10  pyecharts==2.0.5，windows11

**代码及截图**
c = Kline(init_opts=opts.InitOpts(width="1000px", height="500px"))
c.add_xaxis(x_data)
c.add_yaxis("", y_data, itemstyle_opts=opts.ItemStyleOpts(color="#FF0000", color0="32CD32"),
           color_by="series")

c.set_global_opts(
    yaxis_opts=opts.AxisOpts(is_scale=True),
    xaxis_opts=opts.AxisOpts(is_scale=True, splitarea_opts=opts.SplitAreaOpts(
                            is_show=True),
                        
    ),
    title_opts=opts.TitleOpts("2021-2024年苹果股票K线图"),
    datazoom_opts=[opts.DataZoomOpts(type_="inside")],
    visualmap_opts=opts.VisualMapOpts( is_show=False, dimension=2, series_index=5, is_piecewise=True,
    pieces=[ {"value": 1, "color": "#00da3c"}, {"value": -1, "color": "#ec0000"}, ], ),

    
    
)

c.load_javascript()
c.render_notebook()

<img width="680" alt="7dcbc2a71aca6a1a885fdffd3d49aaca" src="https://github.com/pyecharts/pyecharts/assets/51234168/c0b5ca92-c3c6-47fa-b03a-8c61cba4154d">

**Comment by silver6wings** [comment]
open close high low 看看是不是这个顺序，顺序错了肯定全是红线，我刚遇到了

**Comment by liuyug** [comment]
这个问题就是 ohlc 顺序错了，echarts 使用 ochl 
为什么设置成这种方式？

**Comment by sunhailin-Leo** [comment]
> 这个问题就是 ohlc 顺序错了，echarts 使用 ochl 为什么设置成这种方式？

是 oclh 哈~
* https://echarts.apache.org/zh/option.html#series-candlestick.data
* [open, close, lowest, highest] （即：[开盘值, 收盘值, 最低值, 最高值]）
* 至于为啥只有 Echarts 的团队能解释了~
