### ISSUE TITLE
3D图坐标轴颜色无法修改

### ISSUE THREAD

**Issue by qiuxiaolong857** [pyecharts/pyecharts#2323]
**问题**
对于3D柱状图等3D形状，没有办法修改3D图的坐标轴颜色以及坐标轴X,Y,Z的数字颜色和大小

**运行环境（系统环境及 pyecharts 版本）**
python3.8 pyecharts1.9.0

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@qiuxiaolong857 
* 有例子嘛？
