### ISSUE TITLE
除权信息

### ISSUE THREAD

**Issue by liuyug** [pyecharts/pyecharts#2324]
kline 图

使用 markpoint 做除权标记

除权信息已经有 x 坐标，但没有 y 坐标，如何动态定位 当前坐标轴的底部，类似股票软件显示 q 标记那样

**Comment by sunhailin-Leo** [comment]
@liuyug 
* 有点没太看明白你的描述~
* 动态的话你不指定 yAxis 的 min，echarts 默认会自动缩放的。如果要自定义的话，可以给 yAxis 的 min 用 js 回调函数填充

**Comment by liuyug** [comment]
markpoint 点
如果使用 coord 方式，需要 X，Y 坐标，但除权信息只有 X坐标，即日期，没有 Y 坐标价格，无法使用这种方式
如果使用 type_ = min 方式, 使用 value_index / value_dim 设置 Y 轴价格，但 X 坐标日期 如何设定？

我想将除权点的 Y 坐标设置到 Y轴最下沿。

**Comment by sunhailin-Leo** [comment]
> markpoint 点 如果使用 coord 方式，需要 X，Y 坐标，但除权信息只有 X坐标，即日期，没有 Y 坐标价格，无法使用这种方式 如果使用 type_ = min 方式, 使用 value_index / value_dim 设置 Y 轴价格，但 X 坐标日期 如何设定？
> 
> 我想将除权点的 Y 坐标设置到 Y轴最下沿。

你这种方式或者看看 markpoint 的配置？https://echarts.apache.org/zh/option.html#series-candlestick.markPoint.data
如果有你想要的方式倒还好，如果没有的话，估计得看 Echarts 怎么支持了。
