### ISSUE TITLE
Windows下render可以指定CRLF为LF么？

### ISSUE THREAD

**Issue by nyssance** [pyecharts/pyecharts#2325]
**问题**

Windows下render默认是CRLF，没有找到设置newline="\n"的地方

**运行环境（系统环境及 pyecharts 版本）**

Windows 11 / pyecharts 2.0.5

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@nyssance 
* 基于什么场景会存在这个问题？

**Comment by nyssance** [comment]
> @nyssance
> 
> * 基于什么场景会存在这个问题？

双系统用户，生成的文件需要保存，mac下生成的文件是LF，windows下生成的是CRLF，内容没改动，但是git就不一样了，因为render是封装了。所以自己要改成LF还要去自己遍历已经生成的文件。

**Comment by sunhailin-Leo** [comment]
> > @nyssance
> > 
> > * 基于什么场景会存在这个问题？
> 
> 双系统用户，生成的文件需要保存，mac下生成的文件是LF，windows下生成的是CRLF，内容没改动，但是git就不一样了。一般的写文件，输出前可以自己把output处理一遍再输出，但pyecharts的render是封装了。所以没法自己前置操作，要改成LF还要去生成后遍历已经生成的文件改。pandas/jinja会留个配置或者参数让用户自己改一下。

* git 也是必须统一用一种的，切换系统势必会影响到格式。
* 你说 jinja 留的配置指的是这个嘛？https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment
    * 如果你说的是 `jinja2.Environment` 的话，目前 `pyecharts 所有 render api` 都有一个 env 参数用来传递 `jinja2.Environment` 的配置哈~

**Comment by nyssance** [comment]
> > > @nyssance
> > > 
> > > * 基于什么场景会存在这个问题？
> > 
> > 
> > 双系统用户，生成的文件需要保存，mac下生成的文件是LF，windows下生成的是CRLF，内容没改动，但是git就不一样了。一般的写文件，输出前可以自己把output处理一遍再输出，但pyecharts的render是封装了。所以没法自己前置操作，要改成LF还要去生成后遍历已经生成的文件改。pandas/jinja会留个配置或者参数让用户自己改一下。
> 
> * git 也是必须统一用一种的，切换系统势必会影响到格式。
> * 你说 jinja 留的配置指的是这个嘛？https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment
>   
>   * 如果你说的是 `jinja2.Environment` 的话，目前 `pyecharts 所有 render api` 都有一个 env 参数用来传递 `jinja2.Environment` 的配置哈~

是的我git用的是统一的，jinja它是这样的
```python
template = env.get_template(template_name)
output = template.render(data=data)
```
jinja的env里面它不管LF还是CRLF，它只管utf8(这个也影响双平台，windows下默认不是utf8)，但是它的output写入文件的时候，我用pathlib的Path`path.write_text(output, newline="\n")`，python给我一个机会去自己处理。
pyecharts的语法如果能类似 chart.render(f"../{html}", newline="\n")，也这样留个参数就能处理了。目前就是同样代码mac和windows下用生成的行尾不同。

**Comment by sunhailin-Leo** [comment]
@nyssance 
* 这个需求比较罕见，我们得考虑一下~ 
* 另外，按你的说法，如果要在项目兼容 mac/linux 和 windows 的话，是不是得输出两种换行模式的文件？这样反而会让开发者感到疑惑吧？
* 如果在多人协作中用 git 模式来开发或者编辑器统一换行模式，这种问题应该不会存在的。

**Comment by nyssance** [comment]
> @nyssance
> 
> * 这个需求比较罕见，我们得考虑一下~
> * 另外，按你的说法，如果要在项目兼容 mac/linux 和 windows 的话，是不是得输出两种换行模式的文件？这样反而会让开发者感到疑惑吧？
> * 如果在多人协作中用 git 模式来开发或者编辑器统一换行模式，这种问题应该不会存在的。

有了参数才能保证输出一种，自己在代码里指定是\n还是\r\n。现在不处理，是mac和windows下同一套代码运行自动输出不同的，是两种。这也是为什么pandas和python官方的write_text都会留一个参数的原因。

**Comment by nyssance** [comment]
具体来说，因为pyecharts已经是python3.6+了，所以把engine.py里的这段
```python
def write_utf8_html_file(file_name: str, html_content: str):
    with open(file_name, "w+", encoding="utf-8") as html_file:
        html_file.write(html_content)
```
改成
```python
from pathlib import Path

def write_utf8_html_file(file_name: str, html_content: str, newline : str | None = None):
    Path(file_name).write_text(html_content, encoding="utf-8", , newline=newline)
```
然后把newline向上一层层都留出来就可以。用户不填，保持现在的默认行为，mac/windows不同行尾。用户填了，就指定。

**Comment by sunhailin-Leo** [comment]
> 具体来说，因为pyecharts已经是python3.6+了，所以把engine.py里的这段
> 
> ```python
> def write_utf8_html_file(file_name: str, html_content: str):
>     with open(file_name, "w+", encoding="utf-8") as html_file:
>         html_file.write(html_content)
> ```
> 
> 改成
> 
> ```python
> from pathlib import Path
> 
> def write_utf8_html_file(file_name: str, html_content: str, newline: str | None = None):
>     Path(file_name).write_text(html_content, encoding="utf-8", newline=newline)
> ```
> 
> 然后把newline向上一层层都留出来就可以。用户不填，保持现在的默认行为，mac/windows不同行尾。用户填了，就指定。

* newline 这个参数只在 3.10 以后才有的 https://docs.python.org/3.10/library/pathlib.html#pathlib.Path.write_text

**Comment by nyssance** [comment]
那就算了，为了这个极小众需求特地再去用复杂方式处理不值得，等哪天不再支持3.10再解决就行了。

**Comment by sunhailin-Leo** [comment]
@nyssance 
* 你的这个需求有个办法可以解决了。
* 大概构造像这样子。`open(file_name, "w+", encoding="utf-8", newline=os.linesep)` 然后我这边做一个全局变量，类似 `CurrentConfig` 的设置，默认取值按照 os.linesep 来就可以了~

**Comment by sunhailin-Leo** [comment]
@nyssance 
* Closed it then waiting for the new version.

**Comment by nyssance** [comment]
> [@nyssance](https://github.com/nyssance)
> 
> * 你的这个需求有个办法可以解决了。
> * 大概构造像这样子。`open(file_name, "w+", encoding="utf-8", newline=os.linesep)` 然后我这边做一个全局变量，类似 `CurrentConfig` 的设置，默认取值按照 os.linesep 来就可以了~

chart.render()的时候，CurrentConfig怎么设置呢？
