### ISSUE TITLE
含可拖拽内容的图是否有保存拖拽后结果的接口

### ISSUE THREAD

**Issue by XuLH98** [pyecharts/pyecharts#2326]
关于关系图Graph，我需要对各个节点的位置分层规划，所以力引导模式不太适用。然而手动指定坐标的话工作量非常大，并且不便于后续修改。拖拽效果可以实现修改结果的可视化但我不确定有没有保存拖拽结果的接口。

在网上搜到了关于Page类多图布局顺序修改前后的配置保存接口使用示例，我想知道Graph是否也有类似的接口供我保存拖拽修改后的图？

**Comment by sunhailin-Leo** [comment]
@XuLH98 
* 这个得看 Echarts 有没有提供，如果没有的话我们这边也没有办法做到
