### ISSUE TITLE
label_opts不生效的问题

### ISSUE THREAD

**Issue by srqcg** [pyecharts/pyecharts#2327]
**问题**
c.set_series_opts(label_opts=opts.LabelOpts(is_show=False))
实际上渲染出来的还是显示标签, 包括其他选项也无效, 比如position='right' 

**运行环境（系统环境及 pyecharts 版本）**
windows, python3.10, pyecharts 2.0.5

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/65230513/7e97e1a1-fd78-472d-9f3f-25b0460bc532)

![image](https://github.com/pyecharts/pyecharts/assets/65230513/a6937af6-8af0-4804-ac43-b2fcade9b2b6)

**Comment by sunhailin-Leo** [comment]
@srqcg 
* 在 set_global_opts 呢？或者在 add_yaxis 的时候设置 label_opts 呢？
