### ISSUE TITLE
中国地图未更新，似乎缺少黑瞎子岛

### ISSUE THREAD

**Issue by FengChendian** [pyecharts/pyecharts#2330]
**问题**
参照[中华人民共和国自然资源部](http://bzdt.ch.mnr.gov.cn/)的标准地图
<img width="680" alt="image" src="https://github.com/pyecharts/pyecharts/assets/37545115/441e3ee5-b836-40b8-9c8d-2164441dc4b4">

<img width="844" alt="image" src="https://github.com/pyecharts/pyecharts/assets/37545115/e76e4140-583a-43d5-bd08-1d0d79df69db">

**运行环境（系统环境及 pyecharts 版本）**

pyecharts 2.0.5

**Comment by sunhailin-Leo** [comment]
@FengChendian 
* Can you provide the geojson file or point out a comparison between the two?

**Comment by sunhailin-Leo** [comment]
@FengChendian 
* Our and amap's map outlines are comparable and there shouldn't be any issues.
![image](https://github.com/pyecharts/pyecharts/assets/17564655/ab250e24-e173-4339-8519-a8492530fe1f)
![image](https://github.com/pyecharts/pyecharts/assets/17564655/64335f8c-8220-4538-94a6-d0fda20db98c)

**Comment by FengChendian** [comment]
> @FengChendian
> 
> * Our and amap's map outlines are comparable and there shouldn't be any issues.
>   ![image](https://private-user-images.githubusercontent.com/17564655/332753833-ab250e24-e173-4339-8519-a8492530fe1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzg4MTQsIm5iZiI6MTcxNjM3ODUxNCwicGF0aCI6Ii8xNzU2NDY1NS8zMzI3NTM4MzMtYWIyNTBlMjQtZTE3My00MzM5LTg1MTktYTg0OTI1MzBmZTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDExNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMGQ1Y2EyZmYwMzlkNWU5YTY4OGJmMWE5MDhjOWExMzI4NGRmZGE0NWNjNDQ2OWFiNmQwNmRkYTg2Yzc2MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZVOQN5qIlUroCvoH070j2STeBfY_6vH08mFtb_a6WU)
>   ![image](https://private-user-images.githubusercontent.com/17564655/332753970-64335f8c-8220-4538-94a6-d0fda20db98c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzg4MTQsIm5iZiI6MTcxNjM3ODUxNCwicGF0aCI6Ii8xNzU2NDY1NS8zMzI3NTM5NzAtNjQzMzVmOGMtODIyMC00NTM4LTk0YTYtZDBmZGEyMGRiOThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDExNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNmVmYWVkMmYzOWMxYmJkOWI5NTdlMGE3YmI1ZDk3ZjE2NDAyMjkzNjQyYjE5ZGQ5ODMyMWI2NDc1YzAxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JmEuuOFSlDyBMad8jACo_D-E2doF8XHQT60kzANwjZs)

Please see Map_world, not Map_china.

Map_china has been updated, But China in Map_world is outdated.

https://gallery.pyecharts.org/#/Map/map_world

<img width="1355" alt="image" src="https://github.com/pyecharts/pyecharts/assets/37545115/dc7f2b28-171c-4170-a1d5-29d81be761e0">

**Comment by sunhailin-Leo** [comment]
@FengChendian 
* 跟 2.0.6 版本同时发布，这边暂时先 close 掉。关注 pyecharts-assets 这边的更新~
