### ISSUE TITLE
我想实现柱状图+甘特图

### ISSUE THREAD

**Issue by nihaoatang** [pyecharts/pyecharts#2331]
**问题**
需求：在每个柱状图上，画一条横线表示另外一组数据
图片样式为：
![1716522822732](https://github.com/pyecharts/pyecharts/assets/83356349/cf026b1a-a0ca-4fb9-ba33-90e226a0a80b)

**Comment by sunhailin-Leo** [comment]
@nihaoatang 
* Bar(stack mode) + custom color

**Comment by nihaoatang** [comment]
OK, thanks, but I can't find a parameter to set the line length in the MarkLineItem class。
`c = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values(), stack="stack1")
    .add_yaxis("商家B", [[-i] for i in Faker.values()], stack="stack1",
               markline_opts=opts.MarkLineOpts(
                   data=[
                       opts.MarkLineItem(x=Faker.choose()[0], y=50, name="最小值", symbol= None,
                                         coord=[10])
                   ]
               ),
               )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False),
                     )
    .set_global_opts(title_opts=opts.TitleOpts(title="Bar-堆叠数据（全部）"))

    .render("bar_stack0.html")

)`
<img width="881" alt="截屏2024-05-27 10 45 41" src="https://github.com/pyecharts/pyecharts/assets/83356349/57012919-17dd-4147-a5ac-86d3e9470639">

**Comment by sunhailin-Leo** [comment]
@nihaoatang 
* https://gallery.pyecharts.org/#/Bar/bar_stack0
* The mark line may not set the length very well, but you can use different colors to implement your needs.

**Comment by nihaoatang** [comment]
thanks
