### ISSUE TITLE
不能画长方形就是矩形

### ISSUE THREAD

**Issue by June-Snow** [pyecharts/pyecharts#2332]
**问题**
想实现画的图上框出来想要的数据，就是定义4个坐标点，画一个长方形或者矩形。看可以下应该没有这个功能，怎么实现这个功能？

**Comment by sunhailin-Leo** [comment]
* Echarts 本身只是数据可视化框架。你这种需求与数据可视化无关，甚至不应该会有这样子的需求。

**Comment by June-Snow** [comment]
这里有一个问题，关键是没有好的方法去画这个长方形

**Comment by June-Snow** [comment]
还有，提供的各种图形，不就是一些常用的，关键标记长方形这种这么常用的居然没有

**Comment by sunhailin-Leo** [comment]
> 还有，提供的各种图形，不就是一些常用的，关键标记长方形这种这么常用的居然没有

与其抱怨这种问题，倒不如你去找 Echarts 提 issue 或者自己想办法用 Canvas
 实现。而且，我们也只负责实现 Echarts 的 python 实现而已。

**Comment by June-Snow** [comment]
不太理解。不打算支持的话，先这样了

**Comment by sunhailin-Leo** [comment]
> 不太理解。不打算支持的话，先这样了

那等你能理解了，再讨论吧…
