### ISSUE TITLE
GL 3D globe

### ISSUE THREAD

**Issue by wybert** [pyecharts/pyecharts#2334]
@sunhailin-Leo I am wondering if Pyecharts support GL 3D globe chats like those listed in Echarts [here](https://echarts.apache.org/examples/en/index.html#chart-type-globe). 
I want get a bar3d chart on globe like [this](https://echarts.apache.org/examples/en/editor.html?c=global-population-bar3d-on-globe&gl=1) listed in Echarts. However, I didn't see any examples like this in pyecharts-gallery.

**Comment by sunhailin-Leo** [comment]
@wybert 
* You can try `Bar3D` with `add_globe` function.
* `Bar3D` based on `ThreeAxisChart`, `ThreeAxisChart` based on `Chart3D`, `Chart3D` have `add_globe` api.

**Comment by wybert** [comment]
It seems like doable. I am not sure how to set their coordinate System.
```python
    (Bar3D()
    .add(
        series_name="Population",
        data=data,
        # xaxis3d_opts=opts.Axis3DOpts(type_="category"),
        # yaxis3d_opts=opts.Axis3DOpts(type_="category"),
        # zaxis3d_opts=opts.Axis3DOpts(type_="value"),
    )
    .add_globe(   )
)
```
<img width="837" alt="image" src="https://github.com/pyecharts/pyecharts/assets/5254627/e649b4b1-0d37-4afc-9411-320d8f5ae0b6">

**Comment by sunhailin-Leo** [comment]
@wybert 
* Let me think about this issue and how to solve it. Maybe it will take a few days~

**Comment by wybert** [comment]
> @wybert
> 
> * Let me think about this issue and how to solve it. Maybe it will take a few days~

Thanks.

**Comment by sunhailin-Leo** [comment]
@wybert 
![image](https://github.com/pyecharts/pyecharts/assets/17564655/bdfd1455-9144-4b57-91cc-e014ee08a7b5)
* I will update the code in the next release.

**Comment by sunhailin-Leo** [comment]
@wybert 
* If you want this feature as soon as possible. You can modify the source code like below:
![image](https://github.com/pyecharts/pyecharts/assets/17564655/9359fd4f-1899-4b7c-97ed-ccfedbc4fcc5)
![image](https://github.com/pyecharts/pyecharts/assets/17564655/d7788197-149e-4aea-a2df-73fd6c34b019)

**Comment by sunhailin-Leo** [comment]
@wybert 
* Closed it then waiting for the new version.
