### ISSUE TITLE
echarts中的DataZoom组件中有一个 zoomOnMouseWheel, 在pyecharts中是不支持的吗?

### ISSUE THREAD

**Issue by chenhaoch** [pyecharts/pyecharts#2335]
**问题**
我是在notebook中显示图表的, 对于图表缩放的功能, 需要禁用鼠标滚动导致的缩放,不然就无法滚动页面了. 
我看了echarts, DataZoom中是有一个zoomOnMouseWheel 来禁用鼠标滚动导致的缩放.  但是我在pyecharts中找不到. 

**运行环境（系统环境及 pyecharts 版本）**

pyecharts 版本  2.0.3

**代码及截图**

**Comment by chenhaoch** [comment]
更新到2.0.5 也不行

**Comment by sunhailin-Leo** [comment]
@chenhaoch 
* 因为这个参数没加~，等下个版本我这边加一下

**Comment by sunhailin-Leo** [comment]
@chenhaoch 
* Closed it then waiting for the new version.
