### ISSUE TITLE
什么时候能支持SVG格式的map?

### ISSUE THREAD

**Issue by sheepcafe** [pyecharts/pyecharts#2336]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@sheepcafe 
* 你的意思是使用自己导入的 map 是 svg 还是渲染成 html 的元素用 svg？

**Comment by sheepcafe** [comment]
我想导入svg格式map，目前好像还不支持

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月06日 11:40 |
| 收件人 | pyecharts/pyecharts ***@***.***> |
| 抄送人 | sheepcafe ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [pyecharts/pyecharts] 什么时候能支持SVG格式的map? (Issue #2336) |

Closed #2336 as completed.

**Comment by sheepcafe** [comment]
echarts在registerMap时有geoMap和SVG 2种方式，pyecharts只支持了一个，后续版本会支持吗？

**Comment by sunhailin-Leo** [comment]
> Author
> ###

其实可以支持。就是有部分代码有点不太好理解~我之前在我自己的环境里面试过。下个版本发布的时候，我会带个例子出来。

**Comment by sunhailin-Leo** [comment]
@sheepcafe 
* 因此 `pyecharts` 默认就会给 `Base` 类加一个 `legend` 块；
* 那么凑巧，我一开始找的那个例子不需要 `legend` 项，所以就得在最后给 `del` 掉那个配置
