### ISSUE TITLE
BarBackgroundStyleOpts中bar_border_radius不支持

### ISSUE THREAD

**Issue by yangq-15256204** [pyecharts/pyecharts#2339]
**问题**
配置了如下图的bar_border_radius从0.1~100，均不会反应在图上，不起作用

**运行环境（系统环境及 pyecharts 版本）**
Windows 11
python 3.11.0
pyecharts 2.0.5

**代码及截图**
'''python
def create_bar(data:pd.DataFrame):
    """
    绘制柱状图展示销售额和利润
    """
    # 筛选数据
    data = data[['子类别', '销售额', '利润']].groupby('子类别').sum().round(2).reset_index()

    bar = charts.Bar()
    bar.add_xaxis(data['子类别'].to_list())
    bar.add_yaxis('销售额', data['销售额'].to_list(), gap=10, label_opts=opts.LabelOpts(False), 
                  is_show_background=True,
                  background_style=opts.BarBackgroundStyleOpts(bar_border_radius=15, color='#2FF', border_width=2, border_type="dotted"))
    bar.add_yaxis('利润', data['利润'].to_list(), gap=0, label_opts=opts.LabelOpts(False))
    bar.set_series_opts(itemstyle_opts=opts.ItemStyleOpts(color=JsCode(BAR_JS_1), border_radius=10), )
    bar.set_global_opts(xaxis_opts=opts.AxisOpts(type_='category', axislabel_opts=opts.LabelOpts(rotate=30)),
                        tooltip_opts=opts.TooltipOpts(trigger="axis", axis_pointer_type="cross"),
                        title_opts=opts.TitleOpts(title='各子类别销售额利润对比', pos_left='center'),
                        legend_opts=opts.LegendOpts(pos_left='85%', orient='vertical', align='right')
                        )
    return bar

create_bar(df).render_notebook()
'''
![image](https://github.com/pyecharts/pyecharts/assets/64117556/0f97e1dd-ada0-44d1-a5df-3d273cbec093)

**Comment by sunhailin-Leo** [comment]
@yangq-15256204 
* 查了下，参数名错了。下个版本修一下。目前暂时可以通过 dict 的方式传参。
* https://echarts.apache.org/zh/option.html#series-bar.backgroundStyle.borderRadius

**Comment by yangq-15256204** [comment]
> @yangq-15256204
> 
> * 查了下，参数名错了。下个版本修一下。目前暂时可以通过 dict 的方式传参。
> * https://echarts.apache.org/zh/option.html#series-bar.backgroundStyle.borderRadius

感谢解答， 祝您一切顺利。

**Comment by sunhailin-Leo** [comment]
@yangq-15256204 
* Closed it then waiting for the new version.
