### ISSUE TITLE
Timeline+添加不同数据的Geo会有混淆情况

### ISSUE THREAD

**Issue by yangq-15256204** [pyecharts/pyecharts#2340]
**问题**
Timeline+添加不同数据的Geo会有混淆情况
Geo包括两类数据分别是*type_=ChartType.SCATTER* 和 *type_=ChartType.SCATTER + type_=ChartType.LINES*
具体表现为：仅展示SCATTER的Geo在LINES后之后，也会显示LINES，但单个Geo显示没有问题。替换SCATTER为EFFECT_SCATTER显示也有问题

**运行环境（系统环境及 pyecharts 版本）**
Window11
Pyecharts2..0.5

**代码及截图**
```python
from pyecharts.charts import Geo, Timeline
from pyecharts import options as opts
from pyecharts.globals import ChartType, SymbolType
import pyecharts
print(pyecharts.__version__)

data = [
    ("南京", "元代"),
    ("南京", "明代"),
    ("苏州", "明代"),
    ("北京", "清代"),
    ("南京", "清代"),
    ("苏州", "清代"),
    ("杭州", "清代"),
    ("南京", "近现代"),
]

timeline = Timeline(init_opts=opts.InitOpts(width="1000px", height="600px"))

for period in reversed(list(set([item[1] for item in data]))):
    cities_in_period = [item[0] for item in data if item[1] == period]
    if len(cities_in_period) > 1:
        lines_in_period = [(city1, city2) for city1 in cities_in_period for city2 in cities_in_period if city1 != city2 and city1 < city2]
    else:
        lines_in_period = []
    
    # 创建地图实例
    c = Geo()
    c.add_schema(maptype="china")
    if lines_in_period:
        c.add("分布", [item for item in data if item[1] == period], type_=ChartType.SCATTER, color="blue", label_opts=opts.LabelOpts(is_show=True))
        c.add("连线", lines_in_period, type_ = ChartType.LINES, linestyle_opts = opts.LineStyleOpts(curve = 0.2))
    else:
        c.add("分布", [item for item in data if item[1] == period], type_=ChartType.SCATTER, color="blue", label_opts=opts.LabelOpts(is_show=True))
    c.set_series_opts(label_opts = opts.LabelOpts(is_show = False))  
    c.set_global_opts(title_opts=opts.TitleOpts(title="China"), toolbox_opts = opts.ToolboxOpts())
    # c.render(f'{period}.html')
    # 添加地图实例到时间线
    timeline.add(c, time_point=period)
# 生成html文件
timeline.render_notebook()
```
![image](https://github.com/pyecharts/pyecharts/assets/64117556/5950fcb5-c182-456e-b3d6-8b05ab51c557)
![image](https://github.com/pyecharts/pyecharts/assets/64117556/0b4c8242-5fc4-4f7c-a0c2-1166d2e13702)
![image](https://github.com/pyecharts/pyecharts/assets/64117556/a6519346-4e27-4c49-80f3-47f59101196f)

**Comment by yangq-15256204** [comment]
其他问题：每个Geo中的series_name设置为源代码中的period时也会有异常
![image](https://github.com/pyecharts/pyecharts/assets/64117556/475bbf0e-7af1-4b3a-9c54-84fca5eaae97)
![image](https://github.com/pyecharts/pyecharts/assets/64117556/0f2ed355-13bd-4d10-a962-d6a76bc64f8f)

**Comment by sunhailin-Leo** [comment]
@yangq-15256204 
* 你这个 `set([item[1] for item in data])` 会导致数据每次画图都不一致的

**Comment by sunhailin-Leo** [comment]
@yangq-15256204 
* 我后面改一下 `GeoChartBase.add` 对于空数据的处理。
* 你要急着用的话改一下 geo.py 中的 `data = self._feed_data(data_pair, type_)`, 改成下面这样子。
![image](https://github.com/pyecharts/pyecharts/assets/17564655/7678630c-9bc5-4819-9a36-8a6aec649b63)
* 然后你在画图的时候就不用 `if` 了。（Ps：你这个 if 应该也是之前出现报错才加的吧？）

**Comment by yangq-15256204** [comment]
> ```python
> 连线", lines_in_period, type_ = ChartType.LINES, linestyle_opts = opts.LineStyleOpts(curve = 0.2))
>     else:
>         c.add("分布", [item for item in data if item[1] == period], type_=ChartType.SCATTER, color="blue", label_opts=opts.LabelOpts(is_show=True))
>     c.set_series_opts(label_opts = opts.LabelOpts(is_show = False
> ```

关于set()每次不一致的问题，我因编码修改过来了。这个还好ww
if的确是因为line数据空出错才加的，尝试了您推荐的修改方式，已经解决，十分感谢。祝顺利。

**Comment by yangq-15256204** [comment]
> @yangq-15256204
> 
> * 我后面改一下 `GeoChartBase.add` 对于空数据的处理。
> * 你要急着用的话改一下 `geo.py` 中的 `data = self._feed_data(data_pair, type_)`, 改成下面这样子。
>   ![image](https://private-user-images.githubusercontent.com/17564655/336709153-7678630c-9bc5-4819-9a36-8a6aec649b63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzEwMDksIm5iZiI6MTcxNzU3MDcwOSwicGF0aCI6Ii8xNzU2NDY1NS8zMzY3MDkxNTMtNzY3ODYzMGMtOWJjNS00ODE5LTlhMzYtOGE2YWVjNjQ5YjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YmI5MmEwN2I1ZmFkYjk2YTM5YTYyN2Q3M2NjYTBiNDc4ZDNmYzVlNDc3MzhhMTRiMjIzOWRkY2Q4Y2MzOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SaPY4b7Pms4cKROo1HvE87vznrjO43q16VJOjYusiOk)
> * 然后你在画图的时候就不用 `if` 了。（Ps：你这个 if 应该也是之前出现报错才加的吧？）

关于set()每次不一致的问题，我因编码修改过来了。这个还好ww
if的确是因为line数据空出错才加的，尝试了您推荐的修改方式，已经解决，十分感谢。祝顺利。

**Comment by yangq-15256204** [comment]
> 其他问题：每个Geo中的series_name设置为源代码中的period时也会有异常 ![image](https://private-user-images.githubusercontent.com/64117556/336698435-475bbf0e-7af1-4b3a-9c54-84fca5eaae97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzEwMDksIm5iZiI6MTcxNzU3MDcwOSwicGF0aCI6Ii82NDExNzU1Ni8zMzY2OTg0MzUtNDc1YmJmMGUtN2FmMS00YjNhLTljNTQtODRmY2E1ZWFhZTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOWM2YjdlMDBhNTU3Yjc3ZmQ4M2RmMWQ2YmM1NDBhZmZkOGM4NTliY2MzYWE1ZjY1MmEzYTM0NjY3NzFjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Svvm2EV-G3lT_cWzskgm6BNhhZHXAPhLAfeTNlzp9o) ![image](https://private-user-images.githubusercontent.com/64117556/336698614-0f2ed355-13bd-4d10-a962-d6a76bc64f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzEwMDksIm5iZiI6MTcxNzU3MDcwOSwicGF0aCI6Ii82NDExNzU1Ni8zMzY2OTg2MTQtMGYyZWQzNTUtMTNiZC00ZDEwLWE5NjItZDZhNzZiYzY0ZjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MmVhYjNjY2RmMWI0NzAzMjQ0OWRjMjUxODk0YmI4MzU1YmI0NWM5ZjlkYTM2ZDAyYWVmZWM1ODJiYzBjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-cSW4jF5xMviYiZVL3ItxVoeBpn5Na1CffHKLbkY_Bc)

但是图例依旧是原来的错误。也麻烦您修改，十分感谢。

**Comment by sunhailin-Leo** [comment]
> > 其他问题：每个Geo中的series_name设置为源代码中的period时也会有异常 ![image](https://private-user-images.githubusercontent.com/64117556/336698435-475bbf0e-7af1-4b3a-9c54-84fca5eaae97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzEwMDksIm5iZiI6MTcxNzU3MDcwOSwicGF0aCI6Ii82NDExNzU1Ni8zMzY2OTg0MzUtNDc1YmJmMGUtN2FmMS00YjNhLTljNTQtODRmY2E1ZWFhZTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOWM2YjdlMDBhNTU3Yjc3ZmQ4M2RmMWQ2YmM1NDBhZmZkOGM4NTliY2MzYWE1ZjY1MmEzYTM0NjY3NzFjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Svvm2EV-G3lT_cWzskgm6BNhhZHXAPhLAfeTNlzp9o) ![image](https://private-user-images.githubusercontent.com/64117556/336698614-0f2ed355-13bd-4d10-a962-d6a76bc64f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzEwMDksIm5iZiI6MTcxNzU3MDcwOSwicGF0aCI6Ii82NDExNzU1Ni8zMzY2OTg2MTQtMGYyZWQzNTUtMTNiZC00ZDEwLWE5NjItZDZhNzZiYzY0ZjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MmVhYjNjY2RmMWI0NzAzMjQ0OWRjMjUxODk0YmI4MzU1YmI0NWM5ZjlkYTM2ZDAyYWVmZWM1ODJiYzBjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-cSW4jF5xMviYiZVL3ItxVoeBpn5Na1CffHKLbkY_Bc)
> 
> 但是图例依旧是原来的错误。也麻烦您修改，十分感谢。

截图看不到哈

**Comment by yangq-15256204** [comment]
> > > 其他问题：每个Geo中的series_name设置为源代码中的period时也会有异常 ![image](https://private-user-images.githubusercontent.com/64117556/336698435-475bbf0e-7af1-4b3a-9c54-84fca5eaae97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzEwMDksIm5iZiI6MTcxNzU3MDcwOSwicGF0aCI6Ii82NDExNzU1Ni8zMzY2OTg0MzUtNDc1YmJmMGUtN2FmMS00YjNhLTljNTQtODRmY2E1ZWFhZTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOWM2YjdlMDBhNTU3Yjc3ZmQ4M2RmMWQ2YmM1NDBhZmZkOGM4NTliY2MzYWE1ZjY1MmEzYTM0NjY3NzFjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Svvm2EV-G3lT_cWzskgm6BNhhZHXAPhLAfeTNlzp9o) ![image](https://private-user-images.githubusercontent.com/64117556/336698614-0f2ed355-13bd-4d10-a962-d6a76bc64f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzEwMDksIm5iZiI6MTcxNzU3MDcwOSwicGF0aCI6Ii82NDExNzU1Ni8zMzY2OTg2MTQtMGYyZWQzNTUtMTNiZC00ZDEwLWE5NjItZDZhNzZiYzY0ZjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MmVhYjNjY2RmMWI0NzAzMjQ0OWRjMjUxODk0YmI4MzU1YmI0NWM5ZjlkYTM2ZDAyYWVmZWM1ODJiYzBjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-cSW4jF5xMviYiZVL3ItxVoeBpn5Na1CffHKLbkY_Bc)
> > 
> > 
> > 但是图例依旧是原来的错误。也麻烦您修改，十分感谢。
> 
> 截图看不到哈

以下为重新贴图
![image](https://github.com/pyecharts/pyecharts/assets/64117556/33454408-c43d-42d6-927f-5be9d2442212)
![image](https://github.com/pyecharts/pyecharts/assets/64117556/9a88738c-67d5-435a-905b-cda6fe6ce66e)

**Comment by sunhailin-Leo** [comment]
@yangq-15256204 
* Closed it then waiting for the new version.
