### ISSUE TITLE
关系图旋转动画关闭无效

### ISSUE THREAD

**Issue by JassineChan** [pyecharts/pyecharts#2343]
**问题**
关系图旋转动画关闭无效
将animation设置为False，仍然有动画，导致卡顿

**运行环境（系统环境及 pyecharts 版本）**
python=3.12.0
pyecharts=2.0.5

**代码及截图**
graph = (
        Graph(init_opts=opts.InitOpts(theme=ThemeType.LIGHT, animation_opts=opts.AnimationOpts(animation=False)))
        .add("", nodes, links, categories,
![image](https://github.com/pyecharts/pyecharts/assets/143376767/d1076c3c-da72-40e3-b32e-451f7a298bab)

**Comment by sunhailin-Leo** [comment]
@JassineChan 
* 动画这个问题，用这个参数：`is_layout_animation=False`

**Comment by JassineChan** [comment]
如果把参数改为is_layout_animation=False就会报错，即该参数会导致关系图的生成失败: `Graph(init_opts=opts.InitOpts(animation_opts=opts.AnimationOpts(is_layout_animation=False)))`。
![image](https://github.com/pyecharts/pyecharts/assets/143376767/eee51e8e-0311-482f-a28f-7d0ba6943a42)

另外，主题的部分，我是把所有静态资源放在本地引用，同时前后端进行分离，前端index.html用div元素放置了多个画布，然后向后端请求图表，后端的图表在init时设置了不同的主题，但是都没有发生变化。
文件目录：
![image](https://github.com/pyecharts/pyecharts/assets/143376767/03b52953-3ea2-4c28-8616-b4f654880d08)
后端代码：
`# APP配置
app = Flask(__name__, static_folder="templates")
CurrentConfig.ONLINE_HOST = "http://127.0.0.1:8000/assets/"`
`line = (
        Line(init_opts=opts.InitOpts(theme=ThemeType.PURPLE_PASSION))
        .add_xaxis(xaxis_data=x_data)`
前端代码：
`<div id="tIS"></div>`
`var tIS = echarts.init(document.getElementById('tIS'), 'white', {renderer: 'canvas'});`
`$.ajax({
                    type: "GET",
                    url: "xxx",
                    dataType: 'json',
                    data: {
                        xxx
                    },
                    success: function(result) {
                        tIS.setOption(result);
                    }
                });`
显示效果：
![image](https://github.com/pyecharts/pyecharts/assets/143376767/0e1b6238-0909-4c65-80ec-b83d19460eb8)

**Comment by sunhailin-Leo** [comment]
@JassineChan 
* `is_layout_animation` 参数看这：https://pyecharts.org/#/zh-cn/basic_charts?id=graph%ef%bc%9a%e5%85%b3%e7%b3%bb%e5%9b%be
* 你 `tIS` 里面还是 white 肯定没变化啊。。你先看看普通一个图生成有主题的和无主题的差异你就懂了

**Comment by JassineChan** [comment]
哦哦哦，我尝试直接生成一个html文件，主题是有生效的，所以是我前端页面的画布设置导致了显示时主题没有发生变化。那我想请教一下这个问题可以怎么解决呢？我需要在前端页面向后端发出请求时生成这个图并在指定的画布中进行渲染，怎么做才能保证在这种情况下主题生效？非常感谢！

**Comment by sunhailin-Leo** [comment]
> 哦哦哦，我尝试直接生成一个html文件，主题是有生效的，所以是我前端页面的画布设置导致了显示时主题没有发生变化。那我想请教一下这个问题可以怎么解决呢？我需要在前端页面向后端发出请求时生成这个图并在指定的画布中进行渲染，怎么做才能保证在这种情况下主题生效？非常感谢！

* 我的意思是你先对比前后端分离在有无主题情况下生成的 html 文件，那样子你就明白前后端分离的时候你需要补充哪些地方来保证主题生效。
* 因为前后端分离不完全是 pyecharts 的核心功能；而且前后端分离有一点点违背 pyecharts 的本意，所以很多情况下没办法很好的去兼容。（毕竟都分离了，对吧。。）

**Comment by JassineChan** [comment]
我明白了，刚才通过对比html代码解决了这个问题。非常感谢，祝好！！！
