### ISSUE TITLE
如何把tooltips的内容动态更新到标题？

### ISSUE THREAD

**Issue by tongaooo** [pyecharts/pyecharts#2353]
**问题**
如何实现这样的功能，
由三个图组合成的grid,
移动鼠标的时候，
tooltips默认文本框不显示，
把每个图的数据内容动态更新到对应的标题

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![image](https://github.com/pyecharts/pyecharts/assets/52041589/07ed3fc8-a467-43fd-9a3a-04f9b99a2358)

**Comment by sunhailin-Leo** [comment]
@tongaooo 
* 可以试试新版本有一个 `add_js_events` 的 `api`，通过 `echarts` 的 `api` 来动态修改 title。例子目前没有，可以自行尝试。

**Comment by tongaooo** [comment]
感谢，我去试试
