### ISSUE TITLE
timeline pie legend 

### ISSUE THREAD

**Issue by wsd141513** [pyecharts/pyecharts#2354]
**问题**
pie图添加到timeline时，图例显示不全，反选无法取消所有，最后一年正常，单个饼图输出也没问题

**运行环境（系统环境及 pyecharts 版本）**
window10,python3.11.5,pyecharts 2.0.5

**代码及截图**

from pyecharts import options as opts
from pyecharts.charts import Pie,Timeline

year_list={2013: {'NAVY': 16766128, 'AF': 15470077, 'ARMY': 9591998, 'MDA': 6224693, 'DARPA': 2817176, 'OSD': 2091252, 'DEFW': 1295978, 'CBDP': 1105803, 'DHP': 672977, 'DTRA': 498194, 'SOCOM': 432465, 'DLA': 296268, 'DISA': 255600, 'NSA': 228696, 'OTE': 189188, 'TJS': 108648, 'DTIC': 55454, 'DHRA': 28946, 'DCMA': 12699, 'DSS': 8866, 'DSCA': 3526, 'WHS': 104, 'IG': 0}, 2014: {'NAVY': 13606274, 'AF': 12550177, 'ARMY': 7765375, 'MDA': 5537221, 'DARPA': 2778656, 'OSD': 2404427, 'DHA': 1552275, 'CBDP': 1111246, 'DTRA': 488882, 'SOCOM': 368662, 'OTE': 246091, 'DLA': 233477, 'DISA': 222192, 'NSA': 215906, 'TJS': 125016, 'DTIC': 56024, 'DHRA': 19410, 'DSCA': 16807, 'DCMA': 13812, 'DSS': 7552, 'WHS': 607, 'DHP': 0}, 2015: {'NAVY': 14817288, 'AF': 12503263, 'ARMY': 7266257, 'MDA': 5647845, 'DARPA': 2915932, 'OSD': 2619089, 'DHA': 1730536, 'CBDP': 1090794, 'SOCOM': 495001, 'DTRA': 487802, 'DLA': 227124, 'DISA': 215982, 'OTE': 208711, 'NSA': 171774, 'TJS': 150372, 'DTIC': 50789, 'DHRA': 19430, 'DSS': 12658, 'DCMA': 12530, 'DSCA': 12386, 'IG': 1400, 'WHS': 612}}

def get_pie(year):
    c = (
        Pie(init_opts=opts.InitOpts(width='1000px',height='600px'))
        .add("", [list(z) for z in zip(year_list[year].keys(),year_list[year].values())])
        .set_global_opts(title_opts=opts.TitleOpts(title=year),
                         legend_opts=opts.LegendOpts(type_='scroll', selected_mode='multiple', is_show=True,
                                                     selector=True,
                                                     orient='vertical', pos_left='right', pos_top='20%',
                                                     selector_button_gap=20)
                         )
        .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
        #.render("pie_base.html")
    )
    return c

timeline = Timeline(init_opts=opts.InitOpts(width='1200px',height='1000px'))
for y in range(2013, 2015):
    timeline.add(get_pie(year=y), time_point=str(y))

timeline.add_schema(is_auto_play=True, play_interval=2000)
timeline.render("finance_pie_2013.html")

**Comment by wsd141513** [comment]
for y in range(2013, 2015):改成for y in range(2013, 2016):可以用3年数据更清晰

**Comment by wsd141513** [comment]
我这个饼图的标签名称并不固定，我打开生成的html文件查看发现，legend图例设置是在baseOption下，是最后一年的图例数据，当前几年数据不一致的时候，就出现了反选缺失的问题，是因为这个设定的原因导致的问题吗

**Comment by wsd141513** [comment]
我在html文件中baseOption下修改了所有标签名称的数据，可以使用了，但这样每次都要手动修改才能生效，如果添加修改baseOption.legend.data数据的选项会更方便些

**Comment by sunhailin-Leo** [comment]
@wsd141513 
* `timeline` 不管是通过 `add` 修改亦或者是 `__check_components` 修改，以及 `replaceMerge` 策略修改都暂时对你这种需求不太好兼容。
* https://echarts.apache.org/zh/option.html#timeline.replaceMerge
* Ps：
    * 一般用 `Timeline` 都会给 `legend` 固定，看不同时间点的变化。
    * 如果 `legend` 不固定的情况下，不应该结合 `Timeline` 来展示，这会丢失横向对比的意义。
