### ISSUE TITLE
Graph图节点间的多边问题

### ISSUE THREAD

**Issue by JassineChan** [pyecharts/pyecharts#2356]
**问题**
在Graph图中，两个节点之间存在多条不同类型的边，即边的source和target均相同，但value不同，这种情况下只会显示一条边。想问一下该库是否支持多边，如果支持的话应该怎么设置？

**运行环境（系统环境及 pyecharts 版本）**
python=3.12.0
pyecharts=2.0.5

**代码及截图**
link1 = { "source": "1", "target": "2", "value": "1"}
link2 = { "source": "1", "target": "2", "value": "2"}
link3 = { "source": "1", "target": "2", "value": "3"}

**Comment by sunhailin-Leo** [comment]
@JassineChan 
* 参考下这个例子：https://github.com/pyecharts/pyecharts/issues/2016

**Comment by JassineChan** [comment]
好的，感谢！！！






| |
陈泽鑫
对话技术研究组
|
|
哈尔滨工业大学社会计算与信息检索研究中心
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月9日 17:35 |
| 收件人 | ***@***.***> |
| 抄送人 | Zexin ***@***.***>,
***@***.***> |
| 主题 | Re: [pyecharts/pyecharts] Graph图节点间的多边问题 (Issue #2356) |

Closed #2356 as completed.
