### ISSUE TITLE
官网无法访问？Jupyter中render_notebook() 图表无法显示

### ISSUE THREAD

**Issue by ouking-y** [pyecharts/pyecharts#2357]
**问题**
以下两个网站都无法访问了
文档：http://pyecharts.org/
示例：http://gallery.pyecharts.org/

另外：
pyecharts在jupyter notebook和jupyter lab中均无法显示了，之前根据文档网站上有个
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB
的设置可以显示，现在也不可以了，请问是有什么改动吗

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 版本 1.9.1
python 版本 3.8.5
jupyter notebook版本 6.1.0
jupyter lab 版本 4.0.5

**代码及截图**

![d02b7cf408d0785fc6a72cca51798cd](https://github.com/pyecharts/pyecharts/assets/62621133/64baf058-8f6e-475d-816b-84d82bc35e52)

![f2e6a90ce43f6bab99c134e8074c904](https://github.com/pyecharts/pyecharts/assets/62621133/71ff03e3-b451-4b12-ba89-f88fdfede13b)
![1b3a3b7f80bee917f176f5dfe0fcaaa](https://github.com/pyecharts/pyecharts/assets/62621133/259f5e3c-11e0-4d33-9a55-23c573ffb901)

**Comment by ouking-y** [comment]
![image](https://github.com/pyecharts/pyecharts/assets/62621133/cc9551e4-e10a-4a6f-87ff-0c42ef23cfcf)

**Comment by sunhailin-Leo** [comment]
@ouking-y 
* 目前用科学可以使用...估计 CDN 受到了一些限制。我们这边看一下～
