### ISSUE TITLE
pie饼图时，set_colors无法更改颜色

### ISSUE THREAD

**Issue by duskkkrua** [pyecharts/pyecharts#2358]
**问题**
1. pie中的set_colors，只改变了pie.options里的colors，没有改变pie.colors，使得pie的colors固定只有初始化的9种。

**运行环境（系统环境及 pyecharts 版本）**
windows，pycharm，Python 3.10.14，pyecharts  2.0.6

**代码及截图**
![1](https://github.com/pyecharts/pyecharts/assets/75160827/e92a45be-cabc-4a85-bae7-aa4a15da9bf7)
![2](https://github.com/pyecharts/pyecharts/assets/75160827/e84ebb0f-5f32-406b-b9e9-5bf58dc1f7ef)
运行结果如下：
![image](https://github.com/pyecharts/pyecharts/assets/75160827/55b43670-2ea0-4f9a-b986-5b9b6c797dcd)

# 数据
    data = [
        ("苹果", 25), ("香蕉", 30), ("橙子", 20), ("葡萄", 15), ("柠檬", 10),
        ("桃子", 5), ("樱桃", 8), ("草莓", 12), ("西瓜", 18), ("蓝莓", 7),
        ("菠萝", 15), ("榴莲", 6), ("芒果", 10), ("柚子", 4), ("橘子", 10),
        ("李子", 8), ("哈密瓜", 14), ("柿子", 9), ("石榴", 6), ("荔枝", 11),
        ("葡萄柚", 9), ("橄榄", 8), ("山竹", 6), ("杨桃", 4), ("车厘子", 7),
        ("百香果", 5), ("牛油果", 3), ("枇杷", 2), ("龙眼", 4), ("榴莲", 6)
    ]
    colors = (
        "#FFFFFF", "#FFD700", "#FF8C00", "#8A2BE2", "#32CD32",
        "#FF69B4", "#C71585", "#FF1493", "#20B2AA", "#1E90FF",
        "#FF4500", "#DA70D6", "#87CEFA", "#40E0D0", "#EE82EE",
        "#8B0000", "#ADFF2F", "#FFA500", "#DC143C", "#FF00FF",
        "#7B68EE", "#4682B4", "#008080", "#7CFC00", "#00FF00",
        "#DAA520", "#BDB76B", "#FFDEAD", "#FFB6C1", "#FFFAFA"
    )
    # 创建饼图
    pie = Pie()
    pie.set_colors(colors=colors)

    # 添加数据
    pie.add(
        "标签数据",
        data,
        center=["25%", "50%"],
        radius=["0%", "50%"],  # 实心饼图
        label_opts=opts.LabelOpts(
            position="outside",
            formatter="{b}: {c} ({d}%)",
            font_size=14,
            font_family="Arial",
            color="#FFFFFF"
        ),
    )

**Comment by sunhailin-Leo** [comment]
@duskkkrua 
* 如果直接 `pie.colors` 修改呢？

**Comment by duskkkrua** [comment]
之前急着用，直接改了一下源代码，改成了这个样子。
![image](https://github.com/user-attachments/assets/d5807d8f-5259-495b-8d0b-f8d38d1d135a)
让初始化的时候可以加载颜色。

不过我记得我试过直接pie.colors = colors来修改，但是没有成功。

**Comment by sunhailin-Leo** [comment]
> 之前急着用，直接改了一下源代码，改成了这个样子。 ![image](https://private-user-images.githubusercontent.com/75160827/348662630-d5807d8f-5259-495b-8d0b-f8d38d1d135a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzczMDcsIm5iZiI6MTcyMTAzNzAwNywicGF0aCI6Ii83NTE2MDgyNy8zNDg2NjI2MzAtZDU4MDdkOGYtNTI1OS00OTViLThkMGItZjhkMzhkMWQxMzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA5NTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNmM3YjUwOWExMDE3NTIwZTI3YjIzOWVhNDUxYzNjYjkzYjdkNDRmNGEzOWQ3YjFkM2JiNTVjYzZhZGQ5YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tlLnWBA99drB6Gmx_-o1Un29K3rNWZAyrM4ESttkYVY) 让初始化的时候可以加载颜色。
> 
> 不过我记得我试过直接pie.colors = colors来修改，但是没有成功。

* 我这边试了set_colors 没问题的
![image](https://github.com/user-attachments/assets/3af50bb2-d800-494a-b61f-cc955b9d1b94)
![image](https://github.com/user-attachments/assets/06a7ca9e-0b90-4c81-b7be-f706f77be953)
