### ISSUE TITLE
使用opts.PieItem定义Pie数据序列时，legend_opts无法同步数据

### ISSUE THREAD

**Issue by yangkai-bj** [pyecharts/pyecharts#2359]
**问题**

使用opts.PieItem定义数据序列时，legend_opts无法同步数据

**运行环境（系统环境及 pyecharts 版本）**
windows

**代码及截图**

data = [
opts.PieItem( name=value[0],value=value[1],
                    tooltip_opts=opts.TooltipOpts(formatter=JsCode(
                        "function(param){" +
                        "return '<span>' + param.name + '&#12288;·&#12288;' + param.seriesName + '</span></span><hr style=background-color:' + param.color + ';>' + param.marker + '<span style=font-weight:bold>' + param.value + '{0}</span><span style=font-weight:bold;margin-left:50px;>' + param.percent + '%</span>';".format(config["Report.unit"]) +
                        "}"
                        )),
                ) for value in data]

            pie.add(serie["name"],data,.....

**Comment by yangkai-bj** [comment]
if len(pie.options["legend"][0]["data"]) == 0:
                pie.options["legend"][0]["data"] = xaxis
                # 由于数据序列采用opts.PieItem,不能与legenOpts同步,因此强制给legend的data赋值

**Comment by sunhailin-Leo** [comment]
@yangkai-bj 
* 麻烦把 issue 排版和问题描述弄清楚一些。。完全看不明白
