### ISSUE TITLE
gauge图的data_pair标签的属性在dark主题下无效。

### ISSUE THREAD

**Issue by Karl8023** [pyecharts/pyecharts#2360]
**问题**

gauge图的data_pair标签的属性在dark主题下无效：字体的颜色还是黑色字体。

**运行环境（系统环境及 pyecharts 版本）**
python: 3.12
pyecharts: 2.0.6
Django: 5.0

**代码及截图**
后台代码：
c = (
        Gauge(init_opts=opts.InitOpts(bg_color="rgba(0, 0, 0, 0)"))
        .add(
            "P-Release Processing",
            [("Ratio", data[0][3] * 100)],  # ”Ratio“在前台是黑色字体
            split_number=5,
            axisline_opts=opts.AxisLineOpts(
                linestyle_opts=opts.LineStyleOpts(
                    color=[(0.3, "#67e0e3"), (0.7, "#37a2da"), (1, "#fd666d")], width=30
                )
            ),
            detail_label_opts=opts.LabelOpts(formatter="{value}%"),
        )
        .set_global_opts(
            legend_opts=opts.LegendOpts(is_show=False),
        )
        .dump_options_with_quotes()
    )

前端代码：
let themeValue = $('body').attr('data-bs-theme') || 'light';

function get_data(obj, api_url) {

        $.ajax({
            type: "GET",
            url: api_url,
            dataType: 'json',
            success: function (result) {
                const chart = echarts.init(document.getElementById(obj), themeValue, {renderer: 'svg'});
                chart.setOption(result.data);

            },
            error: function (xhr, status, error) {
                console.error('请求失败:', status, error);
            }
        });
    }

截图：
![Uploading Annotation 2024-07-09 110016.png…]()

**Comment by Karl8023** [comment]
![Annotation 2024-07-09 110016](https://github.com/pyecharts/pyecharts/assets/174789148/69ca6dac-20fa-4edd-b008-0463a5ae3b09)

**Comment by sunhailin-Leo** [comment]
@Karl8023 
* 字体颜色需要单独配置。这块 Echarts 无论是背景还是深色模式都是如此。
