### ISSUE TITLE
使用带Timeline的Bar图时，会出现多个xaxis标签重复在一起

### ISSUE THREAD

**Issue by Karl8023** [pyecharts/pyecharts#2361]
**问题**
使用带Timeline的Bar图时，会出现多个xaxis标签重复在一起：查看DOM，发现会有多个一样的标签重复在一起。

**运行环境（系统环境及 pyecharts 版本）**
os：Windows 10 Enterprise 22H2
python：3.12
pyecharts：2.0.6
django：5.0

**代码及截图**
后端代码：
def get_count_month_bar(request):
    data = get_data_from_db("mysql", "select * from mm.view_max_count_mon order by file_month;")
    tl = Timeline()
    for i in range(0, len(data)):
        c = (
            Bar(init_opts=opts.InitOpts(bg_color="rgba(0, 0, 0, 0)"))
            .add_xaxis(["Amount"])
            .add_yaxis("VW", [data[i][1]], label_opts=opts.LabelOpts(position="right"))
            .add_yaxis("XPeng", [data[i][2]], label_opts=opts.LabelOpts(position="right"))
            .reversal_axis()
        )
        tl.add(c, data[i][0])
    return JsonResponse({"data": json.loads(tl.dump_options_with_quotes())})

前端代码：
function get_data(obj, api_url) {

        $.ajax({
            type: "GET",
            url: api_url,
            dataType: 'json',
            success: function (result) {
                const chart = echarts.init(document.getElementById(obj), themeValue, {renderer: 'svg'});
                chart.setOption(result.data);

            },
            error: function (xhr, status, error) {
                console.error('请求失败:', status, error);
            }
        });
    }

截图：
![image](https://github.com/pyecharts/pyecharts/assets/174789148/6022a6e2-5959-4aac-a72f-736d2fd365c3)

**Comment by Karl8023** [comment]
补充：图例标签也重复了。

**Comment by sunhailin-Leo** [comment]
@Karl8023 
* 麻烦代码排版一下，然后提供一个可用的代码来进行测试

**Comment by Karl8023** [comment]
[BarWithTimelineTest.zip](https://github.com/user-attachments/files/16138704/BarWithTimelineTest.zip)
您好！我新建了一个项目，里面复现了我的问题。您可以根据requirements.txt安装环境。
python我使用的版本是3.12
访问地址：localhost:8000/index

**Comment by Karl8023** [comment]
![image](https://github.com/pyecharts/pyecharts/assets/174789148/507d93f2-d623-4225-812a-937c4f1aa0bb)

**Comment by Wukhbrian** [comment]
我也遇到了相同的问题，Timeline在add(chart)的过程中会重复y轴的标签，且会改变该单个chart，使得该chart也会增加标签

![微信截图_20240715110731](https://github.com/user-attachments/assets/510d8fde-896b-49a6-adc4-2289b370217b)

**Comment by wykwey** [comment]
我也遇到了这个bug,整出来的玩意,挺难受的
![6e72c60bef802703e2829d9217178bfc](https://github.com/user-attachments/assets/7a95c45b-403f-446f-b485-95a559e08646)
我以为是我的车坏了,谁知道是轮子坏了(笑:

**Comment by sunhailin-Leo** [comment]
> 我也遇到了这个bug,整出来的玩意,挺难受的 ![6e72c60bef802703e2829d9217178bfc](https://private-user-images.githubusercontent.com/73051894/353029872-7a95c45b-403f-446f-b485-95a559e08646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTMzODUsIm5iZiI6MTcyMjI1MzA4NSwicGF0aCI6Ii83MzA1MTg5NC8zNTMwMjk4NzItN2E5NWM0NWItNDAzZi00NDZmLWI0ODUtOTVhNTU5ZTA4NjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDExMzgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NTBkZTNkNmNiYjQ0YzQ2ZWFiMjZlZTZjYWJlNjlmODdhMzIyZDZiZjkzNGQ3N2JiYThlODE5NzgwNjI1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n15p0rgSaipmawVA5jSJj_RD0NItMLPEJFb2SYdD7YU) 我以为是我的车坏了,谁知道是轮子坏了(笑:

之前为了一个需求，修改了一个地方导致的。可以先回退一个版本

**Comment by wykwey** [comment]
> > 我也遇到了这个bug，整出来的玩意，挺难受的 !
> 
> 之前为了一个需求，修改了一个地方导致的。可以先回退一个版本

实际上在2.0.5也有,yaxis重复,xaxis标签消失
这是我的文件
[新建文件夹.zip](https://github.com/user-attachments/files/16412480/default.zip)

,你可以复现一下

**Comment by Kunkka007** [comment]
的确，我现在 mac 使用 2.0.6 版本也是如此。如果要退回版本的话，退回到哪个版本呢？

**Comment by sunhailin-Leo** [comment]
> 的确，我现在 mac 使用 2.0.6 版本也是如此。如果要退回版本的话，退回到哪个版本呢？

2.0.5

**Comment by Kunkka007** [comment]
感谢~



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月3日(周六) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pyecharts/pyecharts] 使用带Timeline的Bar图时，会出现多个xaxis标签重复在一起 (Issue #2361)




  
的确，我现在 mac 使用 2.0.6 版本也是如此。如果要退回版本的话，退回到哪个版本呢？
  
2.0.5

**Comment by qqhxx** [comment]
原来是bug...

**Comment by qqhxx** [comment]
> 补充：图例标签也重复了。

+1.
