### ISSUE TITLE
将词云图的html保存为png，运行成功但是png文件都是空

### ISSUE THREAD

**Issue by ZHJ19970917** [pyecharts/pyecharts#2363]
**问题**

将词云图的html保存为png，运行成功但是png文件都是空 ,什么字也没有
![image](https://github.com/user-attachments/assets/6f78c9c9-10ef-4444-b9a3-f8d632b19c6f)

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 2.0.6

**代码及截图**
    def test_make_jieba_word(self):
        txt = """例如，在上述代码中，length变量被初始化为float('inf')，目的是为了后续在寻找最小覆盖子串的过程中，能够将首次找到的有效子串长度与之比较并更新。由于任何实际的子串长度都是一个有限的正值，
        因此初始时将其设为无穷大可以确保任何找到的子串长度都会比这个初始值小，从而可以正确地记录下最小长度。
        """

        res = ChartUtil.make_jieba_word(txt)
        sorted_data = sorted(res, key=lambda x: x[1], reverse=True)

        def word_cloud() -> WordCloud:
            c = (
                WordCloud()
                .add(
                    series_name="123",
                    data_pair=sorted_data,
                    word_size_range=[50, 100])
            )
            return c
        a = word_cloud()
        make_snapshot(snapshot, a.render(), "./tmp/cloud0.png")

**Comment by sunhailin-Leo** [comment]
@ZHJ19970917 
* 正常渲染成 html 会有问题吗？snapshot 主要还是依赖于一些自动化工具来操作的，会存在一定的不稳定性。
