### ISSUE TITLE
折线图无法正常显示

### ISSUE THREAD

**Issue by tongaooo** [pyecharts/pyecharts#2364]
对折线图每个节点显示自己的名称

**问题**

部分代码：
l1 = (
            Line()
            .add_xaxis(xaxis_data=x_data)
            .add_yaxis(
                "我的数据",
                [list(z) for z in zip(y_datas[0], y_datas_label[0])],
                symbol_size=8,
                is_hover_animation=False,
                linestyle_opts=opts.LineStyleOpts(width=1.5),
                is_smooth=True,
            )

其中 y_datas[0], y_datas_label[0] 为一维数组。

在2.0以前的版本中可以正常显示，
![image](https://github.com/user-attachments/assets/3bf9c76e-5a7b-4502-b963-282a1ee6490b)

2.0以后的版本无法显示折线，提示数据正常。
![image](https://github.com/user-attachments/assets/7aed03a5-f6cc-4e9e-8aa8-32d306bbdc50)

打开生成的html发现：
老版本的数据格式： 
![image](https://github.com/user-attachments/assets/21f0adff-26fd-414a-be31-e06092eaed6a)

新版本的数据格式：
![image](https://github.com/user-attachments/assets/9fbc3ea9-61f6-42a9-9c6c-33670f3a3476)

如果直接对新版本生成的html数据进行修改成老版本的数据格式，可以正常显示。

**运行环境（系统环境及 pyecharts 版本）**
python: 3.6.8
pyecharts: 2.0.6

**代码及截图**
![image](https://github.com/user-attachments/assets/c269eb49-3270-4c2d-a503-f9e0a7f94d2c)

**Comment by sunhailin-Leo** [comment]
@tongaooo 
* 你的老版本指的是哪个版本？
* 可以按照新版本的方式对代码进行修改哈~

**Comment by tongaooo** [comment]
@sunhailin-Leo 
大侠，那我需要实时这样的效果，应该如何调整：
![image](https://github.com/user-attachments/assets/e4ff0b6d-8d00-4465-ba68-27a7d1139c74)

import pyecharts.options as opts
from pyecharts.charts import Line

x_data = ["2020", "2021", "2022", "2023"]
y_data_value = [1,2,3,4]
y_data_label = ["葡萄","柚子","香蕉","牛油果"]


c = (
    Line()
    .add_xaxis(x_data)
    .add_yaxis("商家A", 
               [list(z) for z in zip(y_data_value, y_data_label)],
               label_opts=opts.LabelOpts(formatter="{@[1]}%\n{@[2]}"),
               )
    .set_global_opts(title_opts=opts.TitleOpts(title="Line-基本示例"))
    .render("line_base.html")
)

这个代码，图形显示为空，麻烦帮忙看看怎样修改。
