### ISSUE TITLE
折线图显示问题，求帮忙SOS

### ISSUE THREAD

**Issue by tongaooo** [pyecharts/pyecharts#2365]
@sunhailin-Leo 
大侠，那我需要实时这样的效果，应该如何调整：
![image](https://github.com/user-attachments/assets/e4ff0b6d-8d00-4465-ba68-27a7d1139c74)

import pyecharts.options as opts
from pyecharts.charts import Line

x_data = ["2020", "2021", "2022", "2023"]
y_data_value = [1,2,3,4]
y_data_label = ["葡萄","柚子","香蕉","牛油果"]

c = (
    Line()
    .add_xaxis(x_data)
    .add_yaxis("商家A", 
               [list(z) for z in zip(y_data_value, y_data_label)],
               label_opts=opts.LabelOpts(formatter="{@[1]}%\n{@[2]}"),
               )
    .set_global_opts(title_opts=opts.TitleOpts(title="Line-基本示例"))
    .render("line_base.html")
)

这个代码，图形显示为空，麻烦帮忙看看怎样修改。

_Originally posted by @tongaooo in https://github.com/pyecharts/pyecharts/issues/2364#issuecomment-2242155699_

**Comment by sunhailin-Leo** [comment]
@tongaooo 
* 之前那种方式早不好使了... 而且可视化也不建议那么做，一般都在 Label 或者 Tooltip 里面做复合数据展示。
* 我也只能按照下面这么改，你之前是啥版本能那么弄你也没说...
```python
.add_yaxis(
        "商家A",
        y_data_value,
        label_opts=opts.LabelOpts(formatter=JsCode("""
            function(x) {
              var secondLabel = ['葡萄','柚子','香蕉','牛油果'];
              return x.data[1] + '%' + '\\n' + secondLabel[x.dataIndex];
            }""")),
    )
```

**Comment by tongaooo** [comment]
感谢回复，之前的版本应该是1.0前的版本了
