### ISSUE TITLE
求方程式

### ISSUE THREAD

**Issue by iris-qq** [pyecharts/pyecharts#2367]
有没有人用这个画出图像之后，尝试考虑拿到曲线的表达式，也就是口语中的方程式。我现在的需求是用我的一组数画出来图后，我需要用任意的x，获取对应的y。或者退而求其次找到对应波峰波谷的（x,y）也是可以的，留贴求助。

**Comment by sunhailin-Leo** [comment]
@iris-qq 
* 1、你可以去 Echarts 那边提问，看看它们会不会未来支持你所说的“方程式”画图。
* 2、无论是多复杂的方程式，到最后画图依旧是按照由点到线的方式来画。所以你应该考虑该如何生成点，而不是提出这种无意义的“求助帖”

**Comment by iris-qq** [comment]
不知道是你本人的情商低，还是本来就戾气重。画图是点到线，没错，你pyechart画出来的根本就不是按照拟合函数来的，不懂么？我工作中有这个需求，就是无意义的求助帖了，麻烦你多学学怎么去尊重，技术再好，不会尊重人，依然是一坨。

**Comment by sunhailin-Leo** [comment]
@iris-qq 
* 通篇看上去是你的情商低，戾气比较重吧？
* 首先，issue 都给你分点说明了；其次，你觉得你提的 issue 的标题和描述内容有人能理解吗？空口一说，也不贴代码和图片，那这不是无意义是啥？

**Comment by iris-qq** [comment]
你看不懂整你说明你数学不咋地，你能有点正常的逻辑么，我在这发个贴问下怎么了？用得着你在这阴阳别人，`无意义的求助帖`，你的用词真是让我开了眼了。还有多看看离散数学，`考虑如何生成点`跟我的问题有啥关系？
第一，我的需求是求离散序列的拐点，第二，作为一个member，注意下用词。

**Comment by sunhailin-Leo** [comment]
@iris-qq 
* `无意义的求助帖`：就是说的你这种以纯文本为核心且不贴任何代码和截图的提问帖。
* `考虑如何生成点`：意思就是拐点是要你自己算，而不是可视化工具来帮你算。无论你是用符号变化判断，斜率变化判断亦或者归一化，一阶/二阶导判断，核心都是你自己计算库来算出来的。
* 另外，就你这种高高在上的语气，上来就说别人不懂离散数学还指手画脚的；我觉得你这种人在工作和生活中也不见得受人待见。
* 作为一个 member 也好，maintainer 也好都是对这个项目负责。而且，每个项目的开发者的用词轮不到你来说教。
