### ISSUE TITLE
GraphicText 无法显示文本

### ISSUE THREAD

**Issue by vikkiekang82** [pyecharts/pyecharts#2368]
问题: 调用 GraphicText 时, 文字无法显示.
运行环境: MacOS Sonoma 14.5, python 3.11.5 (3.9也试过), pyecharts 2.05

**代码及截图**
使用官网Graphic - Graphic_rect_bar1 代码,执行结果展示中GraphicRect能显示,但是 GraphicText不显示.尝试更换 font也不行.

<img width="840" alt="Screenshot 2024-08-02 at 14 22 14" src="https://github.com/user-attachments/assets/a200386b-9ab3-48fa-9a4a-dd9125cf82f0">

**Comment by sunhailin-Leo** [comment]
@vikkiekang82 
* GraphicTextStyleOpts 指定一下 fontSize 参数，或者设置为 None 就好了

**Comment by vikkiekang82** [comment]
@sunhailin-Leo 谢谢!!!
