### ISSUE TITLE
v2.0.6版本GraphicText不显示

### ISSUE THREAD

**Issue by tzjason** [pyecharts/pyecharts#2371]
**问题**
在2.0.6版本中GraphicText的字符内容不显示,在2.0.4可以正常显示

**运行环境（系统环境及 pyecharts 版本）**
pyecharts==2.0.6,windows11

**代码及截图**
opts.GraphicText(graphic_item=opts.GraphicItem(left="93%",top="41%",z=100),
                                                       graphic_textstyle_opts=opts.GraphicTextStyleOpts(text=written)

**Comment by sunhailin-Leo** [comment]
https://github.com/pyecharts/pyecharts/issues/2368
