### ISSUE TITLE
折线图同时设置点和线条的颜色时，当有多条折线显示在同一张图上时，其中一条折线图没有线条连接，只有标记点

### ISSUE THREAD

**Issue by fmx1998** [pyecharts/pyecharts#2372]
**问题**
折线图同时设置点和线条的颜色时，当有多条折线显示在同一张图上时，其中一条折线图没有线条连接，只有标记点

**运行环境（系统环境及 pyecharts 版本）**
pyrcharts 版本 2.0.6
python 3.11

**代码及截图**
Line_obj.add_yaxis(
series_name=str(yseries_name),
y_axis=df[y_].tolist(),
itemstyle_opts=opts.ItemStyleOpts(color=linecolor),  # 设置点的颜色
linestyle_opts=opts.LineStyleOpts(width=3, color=linecolor)） # 设置线条颜色
![image](https://github.com/user-attachments/assets/01a5dfff-5f20-4ca2-b39a-f1c29c0365ad)

**Comment by fmx1998** [comment]
而且看起来当有多条曲线时，始终有一条曲线没有连接线，只有标记点
![image](https://github.com/user-attachments/assets/6cca9fc0-33a4-42fa-b062-521f1a48d318)

**Comment by sunhailin-Leo** [comment]
@fmx1998 
* 请提供一个完整复现的 demo 代码

**Comment by fmx1998** [comment]
抱歉，我找到问题原因了，是我加载的数据出现了问题

**Comment by fmx1998** [comment]
抱歉，我找到问题原因了，是我加载的数据出现了问题
