### ISSUE TITLE
Page多图情况下如何渲染时直接把相关JS文件一并存于html文档中用于离线播放

### ISSUE THREAD

**Issue by AssIIWeIICan** [pyecharts/pyecharts#2373]
**问题**
你好，在python3.1.0和最新的pyecharts的编译中，对于一个单独的图片如bar，通过render_opts=opts.RenderOpts(is_embed_js=True)，是可以直接输出其他人离线电脑上可用的html
picture_1 = (
    Bar(render_opts=opts.RenderOpts(is_embed_js=True))
    .add_xaxis(Faker.days_attrs)
    .add_yaxis("商家A", Faker.days_values)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Bar-DataZoom（slider-水平）"),
        datazoom_opts=[opts.DataZoomOpts()],
    )
)
picutre_1.render('test.html')
但是因为我有多个图要输出，所以不得不用到page模块
Page模块里面本身没有render_opts参数可以输入，我在最后的
page_test.render('多图离线摸索5.html',render_opts=opts.RenderOpts(is_embed_js=True))
也没用，输出只有7kb

请帮帮忙指导下该怎么办吧，你们文档里面也没写

**运行环境（系统环境及 pyecharts 版本）**
win11 pyecharts当前最新 python 3.10

**代码及截图**
from pyecharts import options as opts
from pyecharts.charts import Bar,Grid,Line,Liquid,Page,Pie
from pyecharts.faker import Faker

picture_1 = (
    Bar(render_opts=opts.RenderOpts(is_embed_js=True))
    .add_xaxis(Faker.days_attrs)
    .add_yaxis("商家A", Faker.days_values)
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Bar-DataZoom（slider-水平）"),
        datazoom_opts=[opts.DataZoomOpts()],
    )
)
page_test =(
    Page(layout=Page.SimplePageLayout,)
    .add(picture_1)
)

page_test.render('多图离线摸索5.html',render_opts=opts.RenderOpts(is_embed_js=True))

**Comment by sunhailin-Leo** [comment]
@AssIIWeIICan 
* 静态部署：https://pyecharts.org/#/zh-cn/assets_host

**Comment by AssIIWeIICan** [comment]
> @AssIIWeIICan
> 
> * 静态部署：https://pyecharts.org/#/zh-cn/assets_host

但是我这个文件要做90多份不同的，发给各个分公司对应的人。不可能要求他们做。能帮忙在render的时候加个选项把要用的js之类一起装在html里面吗。我看单独的图是可以的，但是page多图不行

**Comment by sunhailin-Leo** [comment]
@AssIIWeIICan 
* 你可以试试手动指定 `CurrentConfig.ONLINE_HOST` 为相对路径。

**Comment by sunhailin-Leo** [comment]
@AssIIWeIICan 
* 另外不建议你把所有 js 都装在 html 里面。这样子的话，你图画的越复杂，启动加载越慢。

**Comment by AssIIWeIICan** [comment]
> @AssIIWeIICan
> 
> * 你可以试试手动指定 `CurrentConfig.ONLINE_HOST` 为相对路径。

请问大佬手动指定这个可以最后把相关的JS都放在html里面吗，因为我自己的电脑什么都好说，但别人的我真没办法

**Comment by AssIIWeIICan** [comment]
> @AssIIWeIICan
> 
> * 另外不建议你把所有 js 都装在 html 里面。这样子的话，你图画的越复杂，启动加载越慢。

给分公司的其实可能最多也就10张以内，关键是得先能做到这一点。请问当前pyecharts里面能多图直接把js封装在里面吗

**Comment by sunhailin-Leo** [comment]
@AssIIWeIICan 
* Page 那块之前没考虑加进去是因为，每个图都加的画，配置会有冲突的。
* 现在你要解决的话，可以试着修改一下 Page 出来的 html。

**Comment by AssIIWeIICan** [comment]
> @AssIIWeIICan
> 
> * Page 那块之前没考虑加进去是因为，每个图都加的画，配置会有冲突的。
> * 现在你要解决的话，可以试着修改一下 Page 出来的 html。

我现在自己能想到的紧急应对方法，就是html生成之后。根据需要的js去html里面把对应的script整个替换掉，把js直接写进去
刚才试了下可行能离线打开，大佬如果可以的话以后可以render里面试着加个参数，这样到了最后一次性带出来好了

**Comment by sunhailin-Leo** [comment]
> > @AssIIWeIICan
> > 
> > * Page 那块之前没考虑加进去是因为，每个图都加的画，配置会有冲突的。
> > * 现在你要解决的话，可以试着修改一下 Page 出来的 html。
> 
> 我现在自己能想到的紧急应对方法，就是html生成之后。根据需要的js去html里面把对应的script整个替换掉，把js直接写进去 刚才试了下可行能离线打开，大佬如果可以的话以后可以render里面试着加个参数，这样到了最后一次性带出来好了

这段时间比较忙，没太多时间去加功能或者修复一些问题。如果针对这个 issue，你可以提供代码上来合并也 ok。

**Comment by AssIIWeIICan** [comment]
> > > @AssIIWeIICan
> > > 
> > > * Page 那块之前没考虑加进去是因为，每个图都加的画，配置会有冲突的。
> > > * 现在你要解决的话，可以试着修改一下 Page 出来的 html。
> > 
> > 
> > 我现在自己能想到的紧急应对方法，就是html生成之后。根据需要的js去html里面把对应的script整个替换掉，把js直接写进去 刚才试了下可行能离线打开，大佬如果可以的话以后可以render里面试着加个参数，这样到了最后一次性带出来好了
> 
> 这段时间比较忙，没太多时间去加功能或者修复一些问题。如果针对这个 issue，你可以提供代码上来合并也 ok。

大佬能指点一下render正式生成html的代码在哪里吗，如果能找到具体的生成html文件的地方或许我能帮帮忙
