### ISSUE TITLE
使用 `type_="time"` 时是否支持毫秒或者微秒时间格式？

### ISSUE THREAD

**Issue by g199209** [pyecharts/pyecharts#2374]
**问题**

使用秒级别的时间格式是正常的：
```
line.add_xaxis([dt.strftime("%Y/%m/%d %H:%M:%S") for dt in df["Time"].tolist()])
```

然而加上微秒后就不正常了：

```
line.add_xaxis([dt.strftime("%Y/%m/%d %H:%M:%S.%f") for dt in df["Time"].tolist()])
```

**代码及截图**

使用 `"%Y/%m/%d %H:%M:%S"`:

<img width="1459" alt="image" src="https://github.com/user-attachments/assets/3cd3257c-5ed7-49fa-b998-19f7de441e56">

使用 `"%Y/%m/%d %H:%M:%S.%f"`:

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/3da5b171-10ae-45d6-bd79-0b63fe8fc599">

-------------

想要使用更高精度时间的主要目的是，需要在鼠标移上去显示的 Tooltip 中看到原始的时间，现在只有秒不太方便，能有方法修改 Tooltip 中的显示也可以。

**Comment by sunhailin-Leo** [comment]
@g199209 
* 试试 `dt.strftime("%Y/%m/%d %H:%M:%S.%f")[:-3]`

**Comment by g199209** [comment]
> @g199209
> 
> * 试试 `dt.strftime("%Y/%m/%d %H:%M:%S.%f")[:-3]`

可以正常工作了。此时有没有什么办法能让 x 轴上的 tooltip 也显示更精确的值？

<img width="256" alt="image" src="https://github.com/user-attachments/assets/e0b55af5-c2ff-4d8e-b272-9b7de4e59cb0">

**Comment by sunhailin-Leo** [comment]
@g199209 
* 目前看 Echarts 那边在不改动代码的情况下最多就是毫秒了。再细的估计得在前端改了。
* 可以看一下 time 相关的说明：https://echarts.apache.org/zh/option.html#series-line.data
