### ISSUE TITLE
我想问一下关于散点图的问题

### ISSUE THREAD

**Issue by wx0x0011** [pyecharts/pyecharts#2375]
**问题**
我尝试读取了我生成的运动员数据文件,去绘制散点图,没有成功,只有点击工具箱的数据视图后才会显示散点

**运行环境（系统环境及 pyecharts 版本）**
python 3.11
pyecharts 2.0.6

**代码及截图**
#python
import pandas as pd
from pyecharts.charts import Scatter
from pyecharts import options as opts

# 读取 CSV 文件
df = pd.read_csv("athletes_data.csv")

# 创建散点图实例
scatter = Scatter()

# 提取数据并转换为 (x, y) 坐标对
male_data = df[df["性别"] == "男"]
female_data = df[df["性别"] == "女"]

male_points = list(zip(male_data["身高(cm)"], male_data["体重(kg)"]))
female_points = list(zip(female_data["身高(cm)"], female_data["体重(kg)"]))

# 添加X轴数据（身高）
scatter.add_xaxis(df["身高(cm)"].tolist())

# 添加Y轴数据（体重），并区分性别
scatter.add_yaxis("男", male_points)
scatter.add_yaxis("女", female_points)

# 设置全局配置项
scatter.set_global_opts(
    title_opts=opts.TitleOpts(title="运动员身高与体重散点图", subtitle="按性别区分"),
    xaxis_opts=opts.AxisOpts(name="身高 (cm)"),
    yaxis_opts=opts.AxisOpts(name="体重 (kg)"),
    toolbox_opts=opts.ToolboxOpts(is_show=True, feature=opts.ToolBoxFeatureOpts(
        save_as_image=opts.ToolBoxFeatureSaveAsImageOpts(is_show=True),
        restore=opts.ToolBoxFeatureRestoreOpts(is_show=True),
        data_view=opts.ToolBoxFeatureDataViewOpts(is_show=True),
        magic_type=opts.ToolBoxFeatureMagicTypeOpts(is_show=True, type_=["line", "bar", "scatter"])
    ))
)

# 渲染图表
scatter.render("athletes_scatter_chart.html")

**Comment by sunhailin-Leo** [comment]
@wx0x0011 
有没有可以稳定复现的代码或者数据提供一下。

**Comment by wx0x0011** [comment]
@sunhailin-Leo 
当然可以,这是代码
```python
import pandas as pd
from pyecharts.charts import Scatter
from pyecharts import options as opts

# 读取 CSV 文件
df = pd.read_csv("athletes_data.csv")

# 创建散点图实例
scatter = Scatter()

# 提取数据并转换为 (x, y) 坐标对
male_data = df[df["性别"] == "男"]
female_data = df[df["性别"] == "女"]

male_points = list(zip(male_data["身高(cm)"], male_data["体重(kg)"]))
female_points = list(zip(female_data["身高(cm)"], female_data["体重(kg)"]))

# 添加X轴数据（身高）
scatter.add_xaxis(df["身高(cm)"].tolist())

# 添加Y轴数据（体重），并区分性别
scatter.add_yaxis("男", male_points)
scatter.add_yaxis("女", female_points)

# 设置全局配置项
scatter.set_global_opts(
    title_opts=opts.TitleOpts(title="运动员身高与体重散点图", subtitle="按性别区分"),
    xaxis_opts=opts.AxisOpts(name="身高 (cm)"),
    yaxis_opts=opts.AxisOpts(name="体重 (kg)"),
    toolbox_opts=opts.ToolboxOpts(is_show=True, feature=opts.ToolBoxFeatureOpts(
        save_as_image=opts.ToolBoxFeatureSaveAsImageOpts(is_show=True),
        restore=opts.ToolBoxFeatureRestoreOpts(is_show=True),
        data_view=opts.ToolBoxFeatureDataViewOpts(is_show=True),
        magic_type=opts.ToolBoxFeatureMagicTypeOpts(is_show=True, type_=["line", "bar", "scatter"])
    ))
)
# 渲染图表
scatter.render("athletes_scatter_chart.html")
```
这是随机生成的数据
[athletes_data.csv](https://github.com/user-attachments/files/17037461/athletes_data.csv)
非常感谢您的帮助

**Comment by sunhailin-Leo** [comment]
@wx0x0011 
* 写成这样子：
```python
xaxis_opts=opts.AxisOpts(name="身高 (cm)", type_="value"),
yaxis_opts=opts.AxisOpts(name="体重 (kg)", type_="value"),
```
![image](https://github.com/user-attachments/assets/e6072dbd-1a9f-469e-b791-32eb5f873fc7)

**Comment by wx0x0011** [comment]
@sunhailin-Leo 非常感谢
