### ISSUE TITLE
datazoom与x轴的距离怎么调呢

### ISSUE THREAD

**Issue by kiiis** [pyecharts/pyecharts#2376]
**问题**
datazoom与x轴的距离怎么调呢？
修改过图表高度，和datazoom的pos_bottom好像都没效果

**运行环境（系统环境及 pyecharts 版本）**
python3.9
pyecharts2.0.6

**代码及截图**
为什么贴不了图？

**Comment by sunhailin-Leo** [comment]
@kiiis 
* 图上传不了可能是你网络的问题
* 针对问题有复现的代码提供一下嘛？
