### ISSUE TITLE
关于仪表盘的问题

### ISSUE THREAD

**Issue by xusuyuan0923** [pyecharts/pyecharts#2379]
**问题**
需要做一个动态的仪表盘，但是网上的资料查不出来，代码放下面，就是刻度由大变小的时候会逆时针旋转，而不是从0开始

**运行环境（系统环境及 pyecharts 版本）**
windows,需要安装pyside6

**代码及截图**
import sys
import random
from PySide6.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget, QPushButton
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtCore import QTimer
from pyecharts.charts import Gauge
from pyecharts import options as opts

class DynamicGauge(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("动态仪表盘")
        self.setGeometry(100, 100, 600, 400)

        self.central_widget = QWidget()
        self.setCentralWidget(self.central_widget)
        self.layout = QVBoxLayout(self.central_widget)

        self.web_view = QWebEngineView()
        self.layout.addWidget(self.web_view)

        self.button = QPushButton("开始动态仪表盘")
        self.button.clicked.connect(self.start_dynamic_gauge)
        self.layout.addWidget(self.button)

        self.timer = QTimer(self)
        self.timer.timeout.connect(self.update_gauge)

        self.gauge = self.create_gauge(50)
        self.web_view.setHtml(self.gauge.render_embed())
        self.timer_started = False

    def start_dynamic_gauge(self):
        if not self.timer_started:
            self.timer.start(1500)  # 每秒更新一次
            self.timer_started = True

    def update_gauge(self):
        new_value = random.randint(0, 100)
        self.gauge.options["series"][0]["data"][0]["value"]=new_value
        self.web_view.setHtml(self.gauge.render_embed())

    def create_gauge(self, value):
        gauge = Gauge()
        gauge.add("速度", [("速度", value)],pointer=opts.GaugePointerOpts(is_show=True),
                  progress =opts.GaugeProgressOpts(is_show=True) )
        gauge.set_global_opts(
            title_opts=opts.TitleOpts(title="仪表盘"),
            tooltip_opts=opts.TooltipOpts(formatter="{a} <br/>{b} : {c}"),
        )
        return gauge

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = DynamicGauge()
    window.show()
    sys.exit(app.exec())

**Comment by xusuyuan0923** [comment]
> @xusuyuan0923
> 
> * 要不你截个 gif 看看，不太理解你描述的情况
我电脑上没有录屏软件，上面有全部的代码，安装一下pyside6就可以运行

**Comment by sunhailin-Leo** [comment]
> > @xusuyuan0923
> > 
> > * 要不你截个 gif 看看，不太理解你描述的情况
> >   我电脑上没有录屏软件，上面有全部的代码，安装一下pyside6就可以运行

* 那我也没太好的方式能够帮到你了~

**Comment by xusuyuan0923** [comment]
> > > @xusuyuan0923
> > > 
> > > * 要不你截个 gif 看看，不太理解你描述的情况
> > >   我电脑上没有录屏软件，上面有全部的代码，安装一下pyside6就可以运行
> 
> * 那我也没太好的方式能够帮到你了~

[仪表盘2.txt](https://github.com/user-attachments/files/17109761/2.txt)

**Comment by xusuyuan0923** [comment]
> > > @xusuyuan0923
> > > 
> > > * 要不你截个 gif 看看，不太理解你描述的情况
> > >   我电脑上没有录屏软件，上面有全部的代码，安装一下pyside6就可以运行
> 
> * 那我也没太好的方式能够帮到你了~

我上传了一份代码，把格式改成.py就可以了，运行一下就知道问题是什么了，就是仪表的指针每次转动都是从0开始变化

**Comment by sunhailin-Leo** [comment]
> > > > @xusuyuan0923
> > > > 
> > > > * 要不你截个 gif 看看，不太理解你描述的情况
> > > >   我电脑上没有录屏软件，上面有全部的代码，安装一下pyside6就可以运行
> > 
> > 
> > 
> > * 那我也没太好的方式能够帮到你了~
> 
> 我上传了一份代码，把格式改成.py就可以了，运行一下就知道问题是什么了，就是仪表的指针每次转动都是从0开始变化

我这边没有相关的依赖哈，如果没有办法提供直观的展示问题的方式，那目前也不能帮到你。
