### ISSUE TITLE
对于treemap图，可不可以鼠标右键得到对应的块的参数名字

### ISSUE THREAD

**Issue by C4712** [pyecharts/pyecharts#2382]
**问题**

对于treemap图，可不可以鼠标右键得到对应的块的参数名字，我想右键点击treemap图时，可以获得点击的那个块的名字，好像没有这个功能。

**运行环境（系统环境及 pyecharts 版本）**
5.5.1

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@C4712 
* 这个需要自己用 js 写全局的事件回调函数了，有个实验性的分支你可以玩玩看：https://github.com/pyecharts/pyecharts/tree/feat/echarts_events

**Comment by C4712** [comment]
好的，非常感谢
