### ISSUE TITLE
No Bar Race ? 也没横向柱状图

### ISSUE THREAD

**Issue by liulang100** [pyecharts/pyecharts#2387]
**问题**
没有BarRace 吗  ,  也没有横向柱状图

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![image](https://github.com/user-attachments/assets/0f511092-506f-42d4-a0bd-fb61476c9957)

**Comment by sunhailin-Leo** [comment]
@liulang100 
* 1、横向一直都有，仔细看文档和示例。
* 2、`BarRace` 需要注入 `js` 代码，对开发门槛有一点要求。

**Comment by liulang100** [comment]
![image](https://github.com/user-attachments/assets/f8cdfdd3-6459-4bb8-9c2d-886358a9add1)
[pyecharts](https://pyecharts.org/) 里面就是文档吧, 然后我的意思是 pyecahrt 里没有直接的横向demo,       2 BarRace如果注入JS 的话, 我们会直接使用 echarts ,python 去注入 JS 脚本.

**Comment by sunhailin-Leo** [comment]
@liulang100 
* 1、横向 `demo` 叫 `reversal_axis`
* 2、要不你先看看 Echarts 实现 BarRace 的逻辑你再想想看需要不要注入 js 哈。

**Comment by liulang100** [comment]
谢谢哥, 刚开始我以为是rotate x Bar,  那个只是旋转了 标签 lable .
