### ISSUE TITLE
解决jupyter notebook中无法显示(空白)的问题

### ISSUE THREAD

**Issue by henryLKJ** [pyecharts/pyecharts#2389]
看到好多人发这个问题，目前已解决，但不知道原理，有时间的大神可以研究下源码

参考官网文档中notebook部分，jupyterlab的设置，用这个设置notebook，怀疑是notebook更新内部逻辑了

新建两个cell，第一个写：
```
from pyecharts.globals import CurrentConfig, NotebookType
from pyecharts.charts import Bar
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB

bar = Bar()
bar.load_javascript()
```

第二个写：
```
from pyecharts.charts import Bar

bar = Bar()
bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
bar.render_notebook()
```

先运行第一个，再运行第二个。只能分两次，合并了就不行

**Comment by sunhailin-Leo** [comment]
@henryLKJ 
* 其实核心是把 `load_javascript` 和 `render_notebook`分别执行就好了

**Comment by tnt1223** [comment]
再提出一个解决方案：如果是通过vscode中使用jupyter的话，可以安装jupyter notebook render这个扩展，再直接调用render_notebook()方法，直接可以显示。
系统win10, python 3.11。
