### ISSUE TITLE
折线图的横坐标起不到索引的作用,以及使用value类型坐标轴不显示图形，详见图片

### ISSUE THREAD

**Issue by Ruiww** [pyecharts/pyecharts#239]
1. 横轴都是工作年限，但是有的组别的数据项是缺失的，未必每一年都有，这样x轴与y值会对应不上，出现问题，如图1所示
![snip20171030_2](https://user-images.githubusercontent.com/32722522/32179676-fa844c18-bdca-11e7-9405-4210e3b7a59f.png)
另外，什么情况下能用'value'类型的坐标轴？
2. xaxis_type= 'value'不显示图形,如图2
![snip20171030_3](https://user-images.githubusercontent.com/32722522/32179686-01b46f86-bdcb-11e7-998c-50dba832bb6c.png)

**Comment by zealotCE** [comment]
目前不支持缺失数据显示的把。毕竟是两个互不关联的list。具体需要 @chenjiandongx

**Comment by chenjiandongx** [comment]
@Ruiww ，@zealotCE 说得对，目前不支持缺失数据显示，还有其实不用刻意把它 x 轴转为字符型，支持传入数值的 list 也是可以的

如下

![image](https://user-images.githubusercontent.com/19553554/32207054-4f4f428e-be34-11e7-8eac-9de0d5555872.png)
