### ISSUE TITLE
怎么去调整html页面中的文字以及图片的清晰度?

### ISSUE THREAD

**Issue by Zwt122544** [pyecharts/pyecharts#2396]
代码如下

`def visual(data_dict):
    """
    转换为字典 大概格式为
    {year:[[国家，gdp],[国家，gdp]]}
    """
    sort_yeardict = data_dict
    timeLine = Timeline({"theme": "light",'width':"1980px","height":"1080px"},)

    for year in sort_yeardict:
        print(year)
        year_data = data_dict[year]
        x_data_contry = []
        y_data_gdp = []
        for contry_gdp in year_data:
            y_data_gdp.append(contry_gdp[1])
            x_data_contry.append(contry_gdp[0])

        bar = Bar()
        x_data_contry.reverse()
        y_data_gdp.reverse()

        bar.add_xaxis(
            x_data_contry
        )
        bar.add_yaxis("GDP", y_data_gdp, label_opts=LabelOpts(position="right"))
        bar.set_series_opts(label_opts=LabelOpts(font_size=8))
        # 反转xy轴
        bar.reversal_axis()
        # label_opts

        # 设置 x 轴标签旋转角度，避免重叠
        bar.set_global_opts(
            title_opts=TitleOpts(title=f"{year} GDP 排行榜"),

            xaxis_opts=AxisOpts(
                axislabel_opts=LabelOpts(
                    rotate=45,  # 设置标签旋转角度
                    interval=0,  # 每个标签都显示
                    font_size =5 # 设置字体大小
                )
            ),
            yaxis_opts=AxisOpts(
                axislabel_opts=LabelOpts(
                    formatter="{value} $",
                    font_size=5 # 设置字体大小

                )
            )
        )

        # 将 bar 添加到时间轴
        timeLine.add(bar, str(year))

    # 设置 Timeline 播放间隔和动画速度
    timeLine.add_schema(
        symbol_size=10,
        play_interval=500,  # 设置为 500ms，比 1000ms 快
        is_timeline_show=True,
        is_auto_play=True,
        is_loop_play=False
    )

    timeLine.render("symbol1.html",width=1400, height=1000)`

**Comment by sunhailin-Leo** [comment]
@Zwt122544 
* 遇到了具体什么问题？
