### ISSUE TITLE
是否有方式在scatter增加自定义标签？

### ISSUE THREAD

**Issue by bucongfan** [pyecharts/pyecharts#2399]
**问题**
请问是否有方式可以在鼠标悬停时增加自定义的标签，像scatter3D的data一样？

谢谢！

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@bucongfan 
* 举个栗子

**Comment by bucongfan** [comment]
<img width="434" alt="image" src="https://github.com/user-attachments/assets/9279aafe-9d69-47e3-a5e1-a310654f78a3">
比如说悬停到这里时，框里能够增加些自己指定的内容，就像在scatter3D中一样：
<img width="676" alt="image" src="https://github.com/user-attachments/assets/7c3eba44-52e5-4e27-91f3-9b1099e87353">
