### ISSUE TITLE
jupyter中calender设置中文不生效

### ISSUE THREAD

**Issue by JumpWill** [pyecharts/pyecharts#2400]
**问题**
相同的代码再Jupyter里月份没有转成中文，render到html就是中文
加了这个也一样
  daylabel_opts=opts.CalendarDayLabelOpts(name_map="cn"),
  monthlabel_opts=opts.CalendarMonthLabelOpts(name_map="cn"),

**运行环境（系统环境及 pyecharts 版本）**
Python 3.10.15 
pyecharts  2.0.7

**代码及截图**
官方代码
https://gallery.pyecharts.org/#/Calendar/calendar_base

**Comment by sunhailin-Leo** [comment]
@JumpWill 
* https://github.com/pyecharts/pyecharts/issues/2305
