### ISSUE TITLE
jupyter lab （pyecharts 2.0.7）菜单栏导出html显示是空白

### ISSUE THREAD

**Issue by linweah** [pyecharts/pyecharts#2404]
**问题**

在jupyter lab 中制图（pyecharts 2.0.7），先load_javascript()后render_notebook()能正常显示输出图，但是通过菜单栏导出html文件输出图显示是空白，然而通过render(".test.html")生成的文件能够正常显示输出图。

如何设置能使得通过菜单栏导出html正常显示

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the render_notebook function in pyecharts/render/engine.py to include JavaScript dependencies when rendering for Jupyter Lab. This should allow the charts to be displayed correctly when exporting to HTML from Jupyter Lab.

You can review changes in this commit: https://github.com/mnmnk43434/pyecharts-pyecharts-2404/commit/f452af378ae41381641fc0d9da86336b44f29a93.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by sunhailin-Leo** [comment]
@linweah 
* 截图看一下，文字描述无法理解。

**Comment by linweah** [comment]
> Hello, we tried to solve the issue.
> 
> This is what we did:
> 
> Modified the render_notebook function in pyecharts/render/engine.py to include JavaScript dependencies when rendering for Jupyter Lab. This should allow the charts to be displayed correctly when exporting to HTML from Jupyter Lab.
> 
> You can review changes in this commit: [mnmnk43434@f452af3](https://github.com/mnmnk43434/pyecharts-pyecharts-2404/commit/f452af378ae41381641fc0d9da86336b44f29a93).
> 
> Caution
> 
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

\pyecharts\render\engine.py:99
    instance = self if isinstance(self, Iterable) else (self,)
    ^
IndentationError: expected an indented block after 'if' statement on line 98

**Comment by linweah** [comment]
> @linweah
> 
> * 截图看一下，文字描述无法理解。

就是文字描述的情况，你可以试一试

**Comment by linweah** [comment]
在jupyter lab 中制图（pyecharts 2.0.7）:
1、通过官方文档，分步先load_javascript()后render_notebook()能在jupyter lab中正常显示输出图（如果没分步输出框就会显示空白）

2、但是将完成后的jupyter lab通过菜单栏导出html文件，打开html文件中输出图显示是空白。

3、如果在jupyter lab 中通过render(".test.html")生成的html文件能够正常显示输出图。

猜测可能的问题是jupyter lab通过菜单栏导出html文件没有加载js，如何能解决呢？希望我的描述足够详尽

**Comment by sunhailin-Leo** [comment]
@linweah 
* 1、分步是必须的，因为需要 jupyterlab 把外部 js/css 加载进去以后才有内容效果。
* 2、如果使用 jupyterlab 的导出有问题的话，这个问题归属于 jupyterlab，没有把导入的 js/css 资源合并进去
* 3、render 调用的还是 python 的内核跑的，菜单栏是 jupyterlab 的前端问题
