### ISSUE TITLE
stack bar overlap line, 折现图会被遮挡

### ISSUE THREAD

**Issue by JaxTester** [pyecharts/pyecharts#2405]
**问题**
stack bar overlap line, 折现图会被遮挡

**运行环境（系统环境及 pyecharts 版本）**
v2.0.4

**代码及截图**
![image](https://github.com/user-attachments/assets/17f5c2cd-3c94-4de5-8b9c-e37b84c3ea8d)
![image](https://github.com/user-attachments/assets/3e142bf5-09b3-4aff-9926-ac5903289a81)

**Comment by sunhailin-Leo** [comment]
@JaxTester 调整 z 轴参数
