### ISSUE TITLE
在百度飞浆中使用render_notebook无法显示图表

### ISSUE THREAD

**Issue by chenhaoch** [pyecharts/pyecharts#2406]
**问题**
在百度的[飞浆](https://aistudio.baidu.com/)中使用pyecharts，`render_notebook()`无法显示图表，`render()`输出html文件后，可以正常打开显示。
看了下console的报错，说是缺少require。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts版本：pyecharts-2.0.7
系统环境：百度的飞浆的ipynb文件

**代码及截图**

```python
from pyecharts.charts import Bar
from pyecharts import options as opts
bar = Bar()
bar.add_xaxis(["A", "B", "C", "D"])
bar.add_yaxis("Series 1", [10, 20, 30, 40])
 
# 在 Jupyter Notebook 中渲染图表
bar.render_notebook()
```

<img width="569" alt="image" src="https://github.com/user-attachments/assets/9bf43312-68c7-4151-9082-201f1833978d" />

**Comment by sunhailin-Leo** [comment]
@chenhaoch 
* 这个具体原因没办法 debug 出来，不过你可以看看 pyecharts 文档里面关于 notebook 的使用说明哈
