### ISSUE TITLE
想问下怎么关闭消息订阅

### ISSUE THREAD

**Issue by michsiu** [pyecharts/pyecharts#2407]
**消息订阅无法关闭**

之前无意中点了消息订阅，但是现在一直关不了，请问要怎么关闭

**运行环境（系统环境及 pyecharts 版本）**
windows
web

**代码及截图**
![image](https://github.com/user-attachments/assets/822e0abe-cbc2-4620-9019-7dd10811176c)

**Comment by sunhailin-Leo** [comment]
@michsiu 
* Change watch mode

**Comment by michsiu** [comment]
> @michsiu 
> 
> * Change watch mode 

Sorry, but would you describe it with more details ?
