### ISSUE TITLE
同样的图表保存为两个文件会出现差异（formatter）

### ISSUE THREAD

**Issue by CuteLicense** [pyecharts/pyecharts#2409]
**问题**
同样的图表保存为两个文件会出现差异

**运行环境（系统环境及 pyecharts 版本）**
Windows 11 
Python 3.8
Version 2.0.7

**代码及截图**
page_sales = page
page_sales.render(file_render_sales)
page.render(file_render)
第一次保存的结果 page_sales 正常
第二次的 page 出现不一致的情况
对比了两个文件 
 "formatter": function(x){if(x.data[1] === 0){return x.data[0].split('-')[2].replace(/^0+/, '') + ' '.repeat(20) + '\n\n';}else{return x.data[0].split('-')[2].replace(/^0+/, '') + ' '.repeat(20) + **'\n\n'**+x.data[1]+'\u4e07';}},

"formatter": function(x){if(x.data[1] === 0){return x.data[0].split('-')[2].replace(/^0+/, '') + ' '.repeat(20) + '';}else{return x.data[0].split('-')[2].replace(/^0+/, '') + ' '.repeat(20) + ''+x.data[1]+'\u4e07';}},

几处 formatter 里面的 '\n\n' 都被消失了

**Comment by sunhailin-Leo** [comment]
@CuteLicense 
* `formatter` 用的开发者传的 JsCode，有可能是你的编辑器给你加上的换行代码格式化。

**Comment by CuteLicense** [comment]
> @CuteLicense
> 
>     * `formatter` 用的开发者传的 JsCode，有可能是你的编辑器给你加上的换行代码格式化。
bar = Bar()
bar.add_xaxis(["A", "B", "C", "D"])
bar.add_yaxis("销量", [10, 20, 30, 40])

bar.set_series_opts(
    label_opts=opts.LabelOpts(
        is_show=True,
        font_size=13, color="white", formatter=JsCode(
            '''function(x){
                        if (x.value > 25){
                            return x.value + '\\n\\n优秀';
                        }else{
                            return x.value;
                        }
                    }''')
    ))
bar.render("bar_1st.html")
bar.render("bar_2nd.html")

上面的测试代码可以复现，编辑器 vscode
效果对比
![图片](https://github.com/user-attachments/assets/c712a6df-d54d-4e6e-9225-880bb447a8d7)

**Comment by sunhailin-Leo** [comment]
@CuteLicense 
* 源码会处理这种换行符：https://github.com/pyecharts/pyecharts/blob/master/pyecharts/charts/base.py#L131
* 因为源码里面是直接 replace 的，所以第二次 render 会把前一次 replace 的结果再 replace 掉
    * 意思就是：`\\n\\n` 第一次 render 会变成 `\n\n`，再 render 就替换没了。
* 解决办法：用函数封装生成逻辑，重新生成图。或者用 copy.deepcopy 深拷贝一个 bar 对象。

**Comment by CuteLicense** [comment]
> @CuteLicense
> 
>     * 源码会处理这种换行符：https://github.com/pyecharts/pyecharts/blob/master/pyecharts/charts/base.py#L131
> 
>     * 因为源码里面是直接 replace 的，所以第二次 render 会把前一次 replace 的结果再 replace 掉
>       
>       * 意思就是：`\\n\\n` 第一次 render 会变成 `\n\n`，再 render 就替换没了。
> 
>     * 解决办法：用函数封装生成逻辑，重新生成图。或者用 copy.deepcopy 深拷贝一个 bar 对象。

谢复。已经用 deepcopy  的方法解决
