### ISSUE TITLE
关于如何更加细化地图的问题（添加到县，区级别）？

### ISSUE THREAD

**Issue by williamliar** [pyecharts/pyecharts#248]
希望可以提供接口解决这一问题

**Comment by chenjiandongx** [comment]
@williamliar 
![image](https://user-images.githubusercontent.com/19553554/32444341-352c6022-c33d-11e7-8e2f-223988e6b6af.png)

这个问题目前有点难解决，是现在的二级城市没办法满足项目需求了吗？百度现在不提供地图的定制下载了。

**Comment by williamliar** [comment]
是的，项目需求要求地图比较小。总而言之，感谢你的回复。谢谢。

**Comment by vowers** [comment]
可以让用户自己添加json格式地图这样吗,我也时希望能有更精细化地图

**Comment by chfw** [comment]
https://github.com/chenjiandongx/pyecharts/blob/master/docs/zh-cn/user-customize-map.md#如何手动添加0197

**Comment by chfw** [comment]
县，区级别估计在2018年实现啦

**Comment by chfw** [comment]
2882 个 [中国县·区地图](https://echarts-maps.github.io/echarts-china-counties-js/pages/index.html)

```
pip install echarts-china-counties-pypkg
```

**Comment by dongrixinyu** [comment]
> 2882 个 [中国县·区地图](https://echarts-maps.github.io/echarts-china-counties-js/pages/index.html)
> 
> ```
> pip install echarts-china-counties-pypkg
> ```

请问可以在地图上一起加载所有的县级地图，构成整个中国地图么？该如何操作呢？
