### ISSUE TITLE
pyecharts 讨论群

### ISSUE THREAD

**Issue by chenjiandongx** [pyecharts/pyecharts#253]
#### 微信二维码

![image](https://user-images.githubusercontent.com/19553554/37194142-c850e902-23a7-11e8-9ec6-d6618c8947f2.png)

**Comment by acefei** [comment]
可以考虑创建一个gitter频道，方便国际友人参与。

**Comment by vowers** [comment]
超过100人了....
可以拉一下我吗
wx:  qujiashi

**Comment by parther** [comment]
可以拉一下我吗
微信号：warningfbi

**Comment by dmxj** [comment]
可以拉我一下吗，微信号：rsk654321

**Comment by chldong** [comment]
微信chldong

**Comment by chenjiandongx** [comment]
拉人好像要先加好友，这就比较麻烦了

**Comment by ilcityfox** [comment]
能再开个吗？加不上了

**Comment by yoxf** [comment]
微信群加不了了

**Comment by Alisssssss** [comment]
求拉 ( 0 ω 0），alicecooperink

**Comment by chenjiandongx** [comment]
群二维码已更新，现在可以扫码进群了。

**Comment by liangchen815** [comment]
zhengliang815 求拉

**Comment by istevenshen** [comment]
二维码已经过期，求拉：shwiyn

**Comment by chenjiandongx** [comment]
@liangchen815 @istevenshen 二维码已更新

**Comment by bjnoodles** [comment]
又过期了，求更新二维码。

**Comment by Sunnie95** [comment]
二维码过期了，可以拉一下吗？微信号： sunnie0630

**Comment by sangyunxin** [comment]
为什么没有QQ群呢？

**Comment by johnsonzhj** [comment]
过期了，能否拉下我, johnsonzhj

**Comment by Ming9527** [comment]
过期了，可以拉我一下吗？微信号:katana_9527

**Comment by Eliminatemusic** [comment]
过期了，可以拉我一下吗  微信号:17310771942

**Comment by chenjiandongx** [comment]
二维码已更新 2018-1-18

**Comment by sangyunxin** [comment]
又过期了，太快了吧

**Comment by parkerzf** [comment]
求拉 parkerzf

**Comment by ariescc** [comment]
求拉 j19976666

**Comment by chenjiandongx** [comment]
二维码已更新 2018-1-29

**Comment by guyongquan** [comment]
又过期了求更新二维码

**Comment by wkhola** [comment]
过期了…………

**Comment by leon332157** [comment]
需要的加我微信2087739264
备注一下加pyecharts群

**Comment by chenjiandongx** [comment]
二维码已更新 2018-2-9

**Comment by py-bin** [comment]
二维码过期了，老大麻烦拉一下，Binzai816，谢谢~

**Comment by CaoChensy** [comment]
还能拉一下嘛。微信caochunhui682830

**Comment by leon332157** [comment]
@py-bin @CaoChensy 加我拉

**Comment by leon332157** [comment]
208739264

**Comment by mashu1158** [comment]
mashu1991求➕

**Comment by huochequan** [comment]
可以拉我一下吗，微信号: sh666479

**Comment by XsLee** [comment]
微信号XsLee99，求加，弄个QQ群吧

**Comment by 2892931976** [comment]
拉我 微信号：chenguochao003

**Comment by chenjiandongx** [comment]
二维码已更新 2018-03-09

**Comment by Magicliang0725** [comment]
二维码已经过期了，求拉，微信：lieving_007,谢谢

**Comment by liugang1109** [comment]
二维码已经过期了

**Comment by leon332157** [comment]
加我拉
微信：2087739264

**Comment by curious1990** [comment]
二维码过期。
为什么不建个 QQ 群呢

**Comment by Live5** [comment]
过期了 能不能拉一下 dongliwu555

**Comment by nanrenne** [comment]
这不是个办法,你需要创建一个不会随时打扰自己的QQ群,而且人数也可以加很多,而且不需要定时更换二维码

**Comment by dataseller** [comment]
这个办法真是愁死人了

**Comment by erikgqp8645** [comment]
大佬，这个过期了

**Comment by DenverZDY** [comment]
求拉进群wx： 13262668525

**Comment by wilsonkrum** [comment]
求拉群， wx:wilsonkrum

**Comment by XueXiangKM** [comment]
二维码又过期了。。期待更新

**Comment by Alice-modesty** [comment]
求拉微信群：18280328215

**Comment by Lsgo** [comment]
cjy24203 拉我进群.谢谢

**Comment by chenjiandongx** [comment]
可以进群讨论

https://github.com/pyecharts/pyecharts/issues/1091

**Comment by shushuma** [comment]
QQ群是1091吗？另外，求大神可否把我的留言删了，好多人邮件我😂发自我的华为手机-------- 原始邮件 --------主题：Re: [pyecharts/pyecharts] pyecharts 讨论群 (#253)发件人：陈键冬 收件人：pyecharts/pyecharts 抄送：shushuma ,Comment 可以进群讨论

#1091

**Comment by chenjiandongx** [comment]
这是个超链接。

**Comment by g1982117** [comment]
请更新群二维码，有问题向请教

**Comment by hl9565** [comment]
还可以进群吗
