### ISSUE TITLE
请问如何改变 Kline 的默认颜色

### ISSUE THREAD

**Issue by kent119** [pyecharts/pyecharts#254]
你好，请问 Kline 的默认颜色可以更改吗？

我画的是 Kline 和 Line 的 Overlap 图，我试了 `label_color` 结果只能更改 Line 的颜色，但是 Kline 还是用默认的颜色表示涨和跌。
请问怎么才能更改Kline的颜色？

**Comment by chenjiandongx** [comment]
Kline 颜色应该是默认的，不能任意修改

**Comment by guyansrg** [comment]
百度echart3里的k线图(http://echarts.baidu.com/demo.html#candlestick-brush)就可以使用自定义颜色，还是挺方便的。

**Comment by faststare** [comment]
how about kwargs in upcolor and downcolor? according to guyansrg echarts itself have custom color on kline/candlestick.

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！https://pyecharts.org/#/zh-cn/rectangular_charts?id=klinecandlestick%EF%BC%9Ak%E7%BA%BF%E5%9B%BE 提供了改变默认颜色的示例
