### ISSUE TITLE
能否增加颜色统一配置？

### ISSUE THREAD

**Issue by JacksonZheng** [pyecharts/pyecharts#255]
现在的颜色配置比较分散，官方提供了主题颜色的[配置功能](http://echarts.baidu.com/theme-builder/) ，能否将颜色配置单独出来，可以用官方的主题定制导出的配置。

**Comment by chenjiandongx** [comment]
实现起来比较麻烦 暂时应该不会考虑这个内容

**Comment by chenjiandongx** [comment]
主题功能已经实现
