### ISSUE TITLE
Geolines是否可以改变国家/地区的颜色？是否可以添加EffectScatter效果？

### ISSUE THREAD

**Issue by weifei0228** [pyecharts/pyecharts#277]
想根据国家/地区的value来改变其区域的颜色（类似map的效果），还有Geolines是否可以添加EffectScatter效果呢？试了下好像不行
参考图形的样子
http://gallery.echartsjs.com/editor.html?c=xr1cyQmoWb

**Comment by chenjiandongx** [comment]
暂时还没考虑到这个方面

**Comment by JasonLeeSJTU** [comment]
强烈呼吁这一功能。 另外能否考虑GeoLines调用Map的结果？ 我想把Map的结果当做背景，给GeoLines使用。

**Comment by chenjiandongx** [comment]
请使用新版 [pyecharts](pyecharts.org)，新版本可以解决该问题
