### ISSUE TITLE
geo.add添加了第一个values数组之后貌似再添加别的数组也不会改变

### ISSUE THREAD

**Issue by applecoode** [pyecharts/pyecharts#279]
起码热力图有这个bug，出现好几次了，添加第一个数组之后，换了别的数组即便是重新生成geo实例再赋值也不能生成新的地图，而且添加多个数组时总是显示第一个数组的图像，在生成的html看数据是多组的，但是总是显示第一组的图像。

**Comment by chenjiandongx** [comment]
@applecoode 能否提供精简的可复现代码并贴上图说明

**Comment by simm13** [comment]
geo1 = Geo("全国各地市春晚关注度".decode('gbk'), "data from baiduindex", title_color="#fff",
           width=1200,
          height=600, background_color='#404a59')
geo1.add("2011", aattr1, value1, visual_range=[0, 1000], visual_text_color="#fff",
        symbol_size=10, is_visualmap=True,is_legend_show=True,legend_selectedmode='single',)
geo1.add("2012", aattr1, value2, visual_range=[0, 1000], visual_text_color="#fff",
        symbol_size=10, is_visualmap=True,is_legend_show=True,legend_selectedmode='single')
geo1.add("2017", aattr1, value3, visual_range=[0, 1000], visual_text_color="#fff",
        symbol_size=10, is_visualmap=True,is_legend_show=True,legend_selectedmode='single')  
geo1.render("map_city.html")

类似这样的，全部显示的是2017系列的数值

**Comment by chenjiandongx** [comment]
FIXED
