### ISSUE TITLE
以下城市望加上

### ISSUE THREAD

**Issue by grb2015** [pyecharts/pyecharts#282]
达州 coordinates is not found
红河哈尼族彝族自治 coordinates is not found
黄冈 coordinates is not found
楚雄彝族自治 coordinates is not found
大理白族自治 coordinates is not found
来宾 coordinates is not found
襄阳 coordinates is not found
抚州 coordinates is not found
晋中 coordinates is not found
吕梁 coordinates is not found
凉山彝族自治 coordinates is not found
眉山 coordinates is not found
丽江 coordinates is not found
临沧 coordinates is not found
普洱 coordinates is not found
文山壮族苗族自治 coordinates is not found
西双版纳傣族自治 coordinates is not found
宣城 coordinates is not found
池州 coordinates is not found
黔西南布依族苗族自治 coordinates is not found
延边朝鲜族自治 coordinates is not found
黔南布依族苗族自治 coordinates is not found
广安 coordinates is not found
商洛 coordinates is not found
白色 coordinates is not found
锡林郭勒 coordinates is not found
中卫 coordinates is not found

**Comment by grb2015** [comment]
这些都是地级市级别的城市。

**Comment by grb2015** [comment]
白色 写错了  是百色

**Comment by grb2015** [comment]
自治的都是州  锡林郭勒盟

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/33802133-2426999a-ddab-11e7-82b2-32af05ef44c3.png)
可能有些需要加上市吧

**Comment by chfw** [comment]
PR么？

**Comment by grb2015** [comment]
好的，我加上'市'再测试试试

**Comment by grb2015** [comment]
又测试了一下，黔南布依族苗族自治州和普洱市找不到了


from pyecharts import Geo

'''
 黔南州  和  普洱市  需要添加

'''
data = [('黔西南布依族苗族自治州', 85), ('北京', 80),('上海市',20),('黔南布依族苗族自治州',20),('普洱市', 85)]

geo = Geo("全国主要城市空气质量", "data from pm2.5", title_color="#fff", title_pos="center",
width=1200, height=600, background_color='#404a59')
attr, value = geo.cast(data)
geo.add("", attr, value, visual_range=[0, 100], visual_text_color="#fff", symbol_size=20, is_visualmap=True)
geo.show_config()
geo.render()

**Comment by grb2015** [comment]
还有襄阳也找不到，也就是还有3个  襄阳市  黔南布依族苗族自治州 和 普洱市

**Comment by chfw** [comment]
这是所有坐标：https://github.com/chenjiandongx/pyecharts/blob/master/pyecharts/constants.py#L39

**Comment by grb2015** [comment]
['鼓楼区','江北区','白云区','新华区','桥西区','海州区','通州区',\
			'桥东区','长安区','西安区','铁西区','青山区','向阳区','和平区','普陀区','河东区','宝山区',\
			'铁东区','城关区','朝阳区','市中区','西湖区','永定区','城中区','南山区','新城区']):  ## (徐州 南京 福州 都有鼓楼区)  (重庆宁波都有江北区)

**Comment by chfw** [comment]
PR, 或者自己解决问题，参照：https://github.com/pyecharts/pyecharts/issues/521
