### ISSUE TITLE
莆田 萍乡   六盘水    上饶    经纬度不正确，地图上显示到别的省了

### ISSUE THREAD

**Issue by grb2015** [pyecharts/pyecharts#283]
'''
测试文件
issue24 : 襄阳不显示
issue25 : 莆田显示到海里了，江西萍乡显示到湖南了，贵州六盘水显示到云南了，江西上饶显示到福建了
'''

from pyecharts import Geo

data = [ ('北京', 80),('上海市',20),('莆田',20),('萍乡', 85), ('六盘水', 66),('襄阳',20),('上饶',20)]

geo = Geo("全国主要城市空气质量", "data from pm2.5", title_color="#fff", title_pos="center",
width=1200, height=600, background_color='#404a59')
attr, value = geo.cast(data)
geo.add("", attr, value, visual_range=[0, 100], visual_text_color="#fff", symbol_size=20, is_visualmap=True)
geo.show_config()
geo.render()

**Comment by chenjiandongx** [comment]
这个其实坐标我没测试过，坐标都是从网上直接 copy 过来的。如果你愿意可以提个 PR 修正这些坐标
