### ISSUE TITLE
如何设置k线中mark_point的颜色？ 同理，如何设置散点的颜色？

### ISSUE THREAD

**Issue by Julinzhou** [pyecharts/pyecharts#284]
### 提 issue 注意事项
0. 先仔细阅读文档中是否有关于您需要解决的问题的解决方法
1. 提 issue 前请先搜搜看以往的 issue 有没有解决了您的问题
2. 如若是不能正常使用的问题，请贴上详细的 pyecharts 版本，使用系统以及 Python 版本
3. 最好详细描述问题，必要时加上**代码+贴图**

**Comment by chenjiandongx** [comment]
试试 label_color  能不能生效吧

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本的 pyecharts 提供了丰富的 MarkLine/MarkPoint 自定义格式
