### ISSUE TITLE
pyecharts 结合 pandas&numpy 新特性的讨论

### ISSUE THREAD

**Issue by chfw** [pyecharts/pyecharts#288]
总结一下 pyecharts 讨论群大家对数据分析的需求：

* 直接用 dataframe, series 画图
* 直接能用 time series 画成 x 轴
* 统计功能的缺失，让大家不得不用 pandas.

从开发者的角度来说，我们倾向于用另外一个项目来完善这些需求，而不影响原本不需要这些功能的用户群体（类似于一个 pyecharts 的插件）。不同群体对库的要求是不一样的。举个例子，数据分析师也许需要的只是最后的数据渲染的结果，为了这个结果有时候是要通过各种库（pandas&numpy）及数学运算得到正确的数据。而另一部分群体即关心结果也关心产生的过程，这个可能就是 web 开发者更注重的内容了吧。

对于软件工程来说，我们谈的都是 epic, feature, user story and tasks. 虽然 pyecharts 快冲破了 1800 star了，比起其他的库(Plotly, Bokeh, bqplot)，还有几步要走。这个是其中一个就是让 pyecharts 和 pandas&numpy 更好的结合，进一步缩短想法到实际产生图标的时间，进一步贴近数据统计方面的需求，量身定制。

开这个 issue 的目的是希望对这方面有需求并且想推动这个 feature 的发展的开发者能够加入到讨论中来，逐步来完善这个项目，目前的初步想法是实现一个工具类，在数据传入 pyecharts 前进行预处理，专门负责 pandas&numpy 数据到 pyecharts 所接受数据的转换。

**Comment by willowj** [comment]
有写一个脚本工具函数 用Grid,Overlap组合  从pd.DF 生成 带成交量、ma的K线图。有兴趣可以看下https://github.com/willowj/python_dataEE

**Comment by chfw** [comment]
有没有人对 dataframe.js, numjs 感兴趣？
