### ISSUE TITLE
求Kline显示K线和成交量得组合写法

### ISSUE THREAD

**Issue by msincenselee** [pyecharts/pyecharts#291]
希望Kline和Volume Bar能够共享X轴，用Overlap是叠加/双坐标轴，不适合。不知道怎么写，求助。

**Comment by anyang001** [comment]
`def draw_info_element(stock_data):
    name = stock_data.loc[0,'name']
    bar = pe.Bar(width=3000)
    overlap = pe.Overlap()
    bar.add('成交量走势',stock_data['date'].tolist(),stock_data['volume'].tolist(),is_datazoom_show=True)
    kline = pe.Kline(width=3000)
    kline.add('{}日K'.format(name),stock_data['date'].tolist(),get_kline_data(stock_data),is_datazoom_show=True)
    overlap.add(bar)
    overlap.add(kline,yaxis_index=1,is_add_yaxis=True)
    return overlap`
这个应该可以

**Comment by anyang001** [comment]
```
def draw(stock_data):
    name = stock_data.loc[0,'name']
    bar = pe.Bar(width=3000)
    bar.add('成交量走势',stock_data['date'].tolist(),stock_data['volume'].tolist(),is_datazoom_show=True)
    kline = pe.Kline(width=3000)
    kline.add('{}日K'.format(name),stock_data['date'].tolist(),get_kline_data(stock_data),is_datazoom_show=True)
    overlap = pe.Overlap()
    overlap.add(bar)
    overlap.add(kline,yaxis_index=1,is_add_yaxis=True)
    return overlap
```
我这个是可以的。

**Comment by anyang001** [comment]
我的width参数的设置，感觉没有用。。。 @chfw

**Comment by msincenselee** [comment]
感谢，你的代码还是叠加在一张图上，我希望分开上下两张图，公用X轴以及它的datazoom。
效果如下：
[https://www.highcharts.com/stock/demo/candlestick-and-volume](url)

**Comment by willowj** [comment]
https://github.com/willowj/python_dataEE

**Comment by wilsonkrum** [comment]
@willowj 感谢你的代码，但是不知道为什么ma line 还是显示不出来

**Comment by msincenselee** [comment]
感谢 @willowj
