### ISSUE TITLE
undefined symbol: TIFFSetWarningHandlerExt

### ISSUE THREAD

**Issue by oliver7l** [pyecharts/pyecharts#294]
python版本2.7
pillow版本4.3.0
pyecharts版本0.3.0
之前pyecharts版本0.1.9.4，用着没问题，今天更新之后，import pyecharts时报出以下错误
python2.7/site-packages/PIL/_imaging.so: undefined symbol: TIFFSetWarningHandlerExt
摸索半天没有找到解决方法，请各位赐教

**Comment by chfw** [comment]
https://github.com/python-pillow/Pillow/issues/543

remove PIL

**Comment by oliver7l** [comment]
我看到这个的
python-pillow/Pillow#543
remove PIL
我当前没有PIL

**Comment by chenjiandongx** [comment]
@oliver7l 请问问题解决了吗
