### ISSUE TITLE
曲线图y轴显示百分数

### ISSUE THREAD

**Issue by evido3s** [pyecharts/pyecharts#295]
有列表，里面元素都已经处理为百分数，如94.32%，怎么在y轴显示啊，没有看到有属性可以设置，请教。

**Comment by evido3s** [comment]
@chenjiandongx  请教下

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/33947031-546a26f2-e05e-11e7-8ad8-5af5809d9884.png)
