### ISSUE TITLE
正式发布 V0.3.1 版本（V0.3.0 的紧急修复版本）

### ISSUE THREAD

**Issue by chenjiandongx** [pyecharts/pyecharts#297]
* ### version 0.3.1
    * [issue#290](https://github.com/chenjiandongx/pyecharts/issues/290) 紧急修复 v0.3.0 版本不能正常显示图形的严重 bug
    * [issue#296](https://github.com/chenjiandongx/pyecharts/issues/296) 修复 Timeline 不能在 notebook 中显示的 bug

**Comment by usernamehastaken** [comment]
在 Anaconda3 中 还是显示不出图形，render的html能显示

**Comment by zgnecah** [comment]
效率。棒

**Comment by liwc1996** [comment]
你好，请问render的结果显示为空白是怎么回事？

**Comment by lysh** [comment]
我的也是显示空白

**Comment by twyeah** [comment]
您好，timeline加入地图控件的时候，应该是legend写错位置了导致带timeline的地图显示有问题

**Comment by chenjiandongx** [comment]
@twyeah 地图加入 timeline 的话，visualmap 不能正常显示，这个问题到现在也很久了。但是 Grid 的是哪里来的？

**Comment by twyeah** [comment]
不好意思 ，grid是我们的前端加的 ，整体来看应该是BaseOption里面少了个series，加上去好像就正常了

**Comment by twyeah** [comment]
"series": [{
						"name": '山西',
						"type": 'map',
						"map": '山西',
						"selectedMode": 'multiple',
						"showLegendSymbol": true,
						"roam": true,
						"left": 0,
						"right": '15%',
						"label": {
							"normal": {
								"show": true
							},
							"emphasis": {
								"show": true
							}
						},
				}],
应该放到Baseoption里面就好了

**Comment by chenjiandongx** [comment]
@twyeah 谢谢你提供的解决方法，晚点会进行测试。

**Comment by twyeah** [comment]
好嘞

**Comment by chenjiandongx** [comment]
@twyeah 能否提供一份正常能正常显示的 html 文件来，我好参照对比。

**Comment by twyeah** [comment]
可以，怎么吧文件给你？

**Comment by chenjiandongx** [comment]
邮件也行，直接上传在回复里也行

**Comment by chenjiandongx** [comment]
@twyeah 好像可以正常显示了

![image](https://user-images.githubusercontent.com/19553554/34333588-55b47246-e979-11e7-81f8-2d5df6360bb9.png)

**Comment by chenjiandongx** [comment]
@twyeah 你指的是这个效果吗

**Comment by twyeah** [comment]
对的

**Comment by twyeah** [comment]
我的html也发过去了，请问改代码哪儿？

**Comment by chenjiandongx** [comment]
@twyeah 我再把 visualmap 的条调一下，不然挡到 timeline 的按钮了。嗯 下个版本开始就可以用了

**Comment by twyeah** [comment]
赞，改起来麻烦么，我自己这边先改下，急着用[捂脸]

**Comment by chenjiandongx** [comment]
两行代码

**Comment by twyeah** [comment]
加在哪儿 加啥呢   多谢！

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/34333685-529cc288-e97a-11e7-9742-51e84f230022.png)

这样看起来就舒服多了

**Comment by twyeah** [comment]
赞一个

**Comment by chenjiandongx** [comment]
timeline.py 文件里面 add 函数最后加上

![image](https://user-images.githubusercontent.com/19553554/34333753-f10e5c60-e97a-11e7-8abb-0354738914bf.png)

**Comment by twyeah** [comment]
刚看到 多谢！

**Comment by twyeah** [comment]
您好，我试了下你的不太成功
我这么改了下也能用
        _tmp_series = copy.deepcopy(chart.options.get('series'))
        _tmp_series[0].pop("data")
        self._option["baseOption"]["series"]=_tmp_series[0]

**Comment by chenjiandongx** [comment]
https://github.com/pyecharts/pyecharts/commit/00b73a62ff90dabc3e2a090d61d4b42ec0ff0851

**Comment by twyeah** [comment]
似乎这样也存在一个问题，往timeline里加Bar和Map组成Grid的时候，如果把Map放在前面添加，那会提示没有xAxis的信息，把Map放前面，那Map的series信息又会丢失（失去visualmap的效果）
