### ISSUE TITLE
请问采用Jupyter Notebook导出为PDF，为什么所有图片都没有显示？

### ISSUE THREAD

**Issue by killer933** [pyecharts/pyecharts#311]
latex文件里面对应的图片的位置的代码是：
\begin{Verbatim}[commandchars=\\\{\}]
{\color{outcolor}Out[{\color{outcolor}10}]:} <pyecharts.charts.bar.Bar at 0x1fc25a18d30>
\end{Verbatim}

**Comment by chfw** [comment]
echarts 4.0 支持svg. 所以pyecharts 0.4.0能把svg加入的话, pdf 输出应该可以有图像。

**Comment by topsun888** [comment]
我是将notebook另存为html格式，图像还是显示不了。

**Comment by MechYZG1004** [comment]
@richardsun-voyager 我也遇到同样的问题。我是离线安装的最新版本，Python版本3.5.2，常见的图形均无法显示。但我用在线pip安装却没有问题

**Comment by chfw** [comment]
With the new solution, here is example output: [test.pdf](https://github.com/pyecharts/pyecharts/files/1813293/test.6.pdf)

<img width="1104" alt="screen shot 2018-03-14 at 22 13 59" src="https://user-images.githubusercontent.com/4280312/37433749-09b6509a-27d5-11e8-848c-921fa33f34db.png">

**Comment by chfw** [comment]
## 导出 PDF 功能

一直以来 PDF 输出的问题困恼着 pyecharts 用户。目前的解决方案是结合 pyecharts-snapshot 来生成静态图片，然后输出。用户需要做两件事情：

第一就是装 [pyecharts-snapshot 0.1.4+ 和 phanomjs-prebuilt](https://github.com/pyecharts/pyecharts-snapshot#installation)

第二就是在 notebook 的最开始添上一下语句。这样就可以输出图片称 PDF 了。

```python
from pyecharts import configure

configure(output_image='png')
```

## 导出的 HTML 文件， 在没有互联网，怎么样打开图片

这个时候， 你也需要装 pyecharts-snapshot 0.1.4+ 。你需要用 `renderer` 参数让 pyecharts 0.4.2+ 生成 svg 图片并且加上下面的语句。

```python
from pyecharts import configure

configure(output_image='svg')
```

同时，请注意，这个配置也是可以输出 PDF 的。可就是输出的图片不仅需要 Inkscape，输出图片效果很不好。所以不推荐用 `output_image='svg'`。

**Comment by February00** [comment]
from pyecharts import configure

configure(output_image='png')
notebook的最开始加入了这句话，snapshot那些也都安装好了

利用bar生成一个图片，生成的结果导出为PDF时还是没显示图片

还是得使用make_a_snapshot才能生成一张图片

**Comment by chfw** [comment]
Pyecharts 0.4.2 还未发布

**Comment by 17864219845** [comment]
> from pyecharts import configure
> 
> configure(output_image='png')
> notebook的最开始加入了这句话，snapshot那些也都安装好了
> 
> 利用bar生成一个图片，生成的结果导出为PDF时还是没显示图片
> 
> 还是得使用make_a_snapshot才能生成一张图片


如何能生成多个，我html 转pdf ，两个图标，转完后只有一个。很是困扰
