### ISSUE TITLE
地图属性多次显示

### ISSUE THREAD

**Issue by Zeroto521** [pyecharts/pyecharts#314]
## 描述
在jupyter上使用map时发现地图属性，会随着再次运行而增加
~~可能与`value`有关~~

![map](https://user-images.githubusercontent.com/25895405/34300368-ac4589ba-e762-11e7-8b71-61bb98d8cf6d.png)

### 测试代码
```python
value = [(116.36, 23.16), (116.46, 23.28), (113.06, 23.02)]
attr = ['潮阳', '澄海', '佛山']
map = pyecharts.Geo("广东地图示例", height=600)
map.add("", attr, value, maptype='广东', is_visualmap=True,
        visual_text_color='#000')
map
```
### 版本号
> pyecharts==0.3.1

**Comment by chenjiandongx** [comment]
https://github.com/pyecharts/pyecharts/issues/192

**Comment by chenjiandongx** [comment]
已修复 #378

**Comment by chenjiandongx** [comment]
FIXED
