### ISSUE TITLE
timeline组件bug

### ISSUE THREAD

**Issue by QTNiCheng** [pyecharts/pyecharts#322]
不知道什么描述，上代码吧
`from pyecharts import Bar, Timeline
from random import randint
attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
bar_1 = Bar("2012 年销量", "数据纯属虚构")
bar_1.add("春季a", attr, [randint(10, 100) for _ in range(6)])
bar_1.add("夏季a", attr, [randint(10, 100) for _ in range(6)])
bar_1.add("秋季a", attr, [randint(10, 100) for _ in range(6)])
bar_1.add("冬季a", attr, [randint(10, 100) for _ in range(6)])

bar_2 = Bar("2013 年销量", "数据纯属虚构")
bar_2.add("春季b", attr, [randint(10, 100) for _ in range(6)])
bar_2.add("夏季b", attr, [randint(10, 100) for _ in range(6)])
bar_2.add("秋季b", attr, [randint(10, 100) for _ in range(6)])
bar_2.add("冬季b", attr, [randint(10, 100) for _ in range(6)])

bar_3 = Bar("2014 年销量", "数据纯属虚构")
bar_3.add("春季c", attr, [randint(10, 100) for _ in range(6)])
bar_3.add("夏季c", attr, [randint(10, 100) for _ in range(6)])
bar_3.add("秋季c", attr, [randint(10, 100) for _ in range(6)])
bar_3.add("冬季c", attr, [randint(10, 100) for _ in range(6)])

bar_4 = Bar("2015 年销量", "数据纯属虚构")
bar_4.add("春季d", attr, [randint(10, 100) for _ in range(6)])
bar_4.add("夏季d", attr, [randint(10, 100) for _ in range(6)])
bar_4.add("秋季d", attr, [randint(10, 100) for _ in range(6)])
bar_4.add("冬季d", attr, [randint(10, 100) for _ in range(6)])

bar_5 = Bar("2016 年销量", "数据纯属虚构")
bar_5.add("春季e", attr, [randint(10, 100) for _ in range(6)])
bar_5.add("夏季e", attr, [randint(10, 100) for _ in range(6)])
bar_5.add("秋季e", attr, [randint(10, 100) for _ in range(6)])
bar_5.add("冬季e", attr, [randint(10, 100) for _ in range(6)], is_legend_show=True)

timeline = Timeline(is_auto_play=True, timeline_bottom=0)
timeline.add(bar_1, '2012 年')
timeline.add(bar_2, '2013 年')
timeline.add(bar_3, '2014 年')
timeline.add(bar_4, '2015 年')
timeline.add(bar_5, '2016 年')
timeline
`
按官方文档的例子，只是把每个条形图的标题换成不一样的。在轮播的时候前四个不会出现标题。还是用git图描述下吧。
![gif](https://user-images.githubusercontent.com/19570475/34593568-993fdd44-f206-11e7-87b1-51d938ee8a88.gif)
前四张轮播图不会出现春夏秋冬abcd，只有最后一张才出现了春夏秋冬e。
大概就是这样吧，描述的不是很清楚，但是看图的话应该能看懂。

**Comment by QTNiCheng** [comment]
对了补充下python的版本
![image](https://user-images.githubusercontent.com/19570475/34593643-31d1aefc-f207-11e7-90b5-26dfaf8b2114.png)
和pyecharts的版本
![image](https://user-images.githubusercontent.com/19570475/34593654-44bf9e02-f207-11e7-9c7a-9811b32c8974.png)

**Comment by chenjiandongx** [comment]
@QTNiCheng 不知道该算是 bug 还是算 feature，目前 Timeline 组件只支持使用一组相同的 legend。

**Comment by QTNiCheng** [comment]
@chenjiandongx  我个人觉得这应该是bug，如果是 feature的话用不同的legend应该不允许吧。希望开发者能支持不同的legend。

**Comment by chenjiandongx** [comment]
@QTNiCheng 
![2018-01-12_21-34-47](https://user-images.githubusercontent.com/19553554/34877304-7e57b71a-f7e0-11e7-935e-0a1084b4b759.gif)
