### ISSUE TITLE
使用notebook的File-download as - html功能,没有把图表嵌入到html里

### ISSUE THREAD

**Issue by FukoH** [pyecharts/pyecharts#324]
python-3.6.2
pyecharts-0.3.1

想把notebook保存成html,但是没有把用pyecharts生成的图表一起保存下来

**Comment by kinegratii** [comment]
详情查看 https://github.com/pyecharts/pyecharts/blob/master/docs/zh-cn/doc_prepare.md#jupyter-notebook-%E8%BE%93%E5%87%BA%E9%97%AE%E9%A2%98

**Comment by sunyinglong** [comment]
@chfw  @kinegratii  大神，我按照文档去做，尝试了各种方法的online模式等等，均不能在我的notebook导出的md文件和html文件显示图片chart，我是python 2.7.13 pyecharts-0.3.1 在jupyter中显示一切正常，但导出后就是无法显示，望解答

**Comment by FukoH** [comment]
@kinegratii   和楼上sunyinglong一样,尝试了仍然没能导出来,调用online()方法,会报一个警告:

` UserWarning: Deprecated since 0.3.0! Please use pyecharts.configure() instead. `

让人有点摸不着头脑

**Comment by chfw** [comment]
0.3.2这warning会消失。本来打算撤销online()的，可以0.3.2发现还是得留下。

**Comment by sunyinglong** [comment]
请问不能导出这个问题，还有其他的设置吗@chfw

**Comment by chfw** [comment]
只有一个设置。
