### ISSUE TITLE
Overlap疑问

### ISSUE THREAD

**Issue by WZP111** [pyecharts/pyecharts#326]
请问：
1、国家间往来的网络关系图，net_graph；
2、世界地图，world_map；
查看pyecharts的说明之后看到有Overlap可以将不同图叠加放在同一张图上，现在我要做的就是将网络关系图对应到世界地图上，但是我试了Overlap后出现了错误，大家有什么好的解决方法吗？

Overlap()代码：
overlap = Overlap()
overlap.add(world_map)
overlap.add(net_graph)
overlap.render()
错误信息：
应该还说xaxis、yaxis未能匹配（手头现在没有具体错误信息，需要的话后续补上）

**Comment by chenjiandongx** [comment]
你这个想法在 Overlap 中暂时是无法实现的，试试看 Geoline 能不能满足你的需求吧

**Comment by WZP111** [comment]
您好，

非常感谢您对我问题的回复，我试了GeoLine然后将其中的maptype设置为world，但是结果并没有像例子中一样出现指向关系，请问这是什么原因？麻烦帮忙解答下，谢谢。

发自我的 iPhone

**Comment by WZP111** [comment]
您好，以下是我利用GeoLine做关于国家关系图的相关代码：
# =========================================
from pyecharts import GeoLines, Style
style = Style(
    title_top="#fff",
    title_pos = "center",
    width=1200,
    height=600,
    background_color="#404a59"
)
data = [
 ['Luxembourg', 'United Kingdom'],
 ['Luxembourg', 'United States'],
 ['Luxembourg', 'China'],
 ['Luxembourg', 'Germany'],
 ['Luxembourg', 'Japan'],
 ['Luxembourg', 'Ireland'],
 ['Luxembourg', 'Italy'],
 ['Luxembourg', 'Canada'],
 ['Luxembourg', 'France'],
 ['Luxembourg', 'Netherlands'],
 ['Luxembourg', 'Spain'],
 ['Luxembourg', 'Dep. Rep. Korea']]
geolines = GeoLines("GeoLines 示例", **style.init_style)
geolines.add("从卢森堡出发", data, maptype = 'world', is_legend_show=False)
geolines.render()
# ==========================================

根据这个以上代码得到的图形只能显示世界地图，但并不能出现从Luxembourg出发的关系指向，针对我出现请您帮忙解答下？

谢谢！

发自我的 iPhone

**Comment by chenjiandongx** [comment]
GeoLine 图不保证所有地区的坐标点都被找到，可以自己使用 geo_cities_coords 为城市或地区指定坐标点，具体请参考文档
