### ISSUE TITLE
timeline组件如何设置与x轴标签的距离？

### ISSUE THREAD

**Issue by QTNiCheng** [pyecharts/pyecharts#327]
当X轴旋转90的度的时候（xaxis_rotate=90），X轴的标签会与timeline组件的按钮重合。
![image](https://user-images.githubusercontent.com/19570475/34661586-9d7ffc50-f485-11e7-8d32-eaa5320ee3a7.png)
当我设置timeline_bottom=-10时，timeline按钮会消失。
![image](https://user-images.githubusercontent.com/19570475/34661621-c984dd52-f485-11e7-9d22-d892bd910000.png)
请问下我改如何才能使得X轴标签与timeline组件按钮不重合。
python环境
![image](https://user-images.githubusercontent.com/19570475/34661638-f9074fa6-f485-11e7-969a-a35ac31dac91.png)
和pyecharts的版本
![image](https://user-images.githubusercontent.com/19570475/34661646-04e6cdec-f486-11e7-8198-aa9e6773f3e0.png)
jupyter notebook版本
![image](https://user-images.githubusercontent.com/19570475/34661674-2e4d157e-f486-11e7-8a6e-ca580de5d00c.png)

**Comment by chenjiandongx** [comment]
推荐使用 Grid ，请查看文档中关于 Grid 的介绍
