### ISSUE TITLE
render是否可以增加保存为图片,gif等的格式

### ISSUE THREAD

**Issue by wlt992** [pyecharts/pyecharts#329]
用的是pyecharts 0.3.1版本，python环境3.5.2，图表render方法目前只能支持保存为html的形式，如果需要图片只能手动打开再下载/截图

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts-snapshot

**Comment by chfw** [comment]
再加一个：https://github.com/chfw/echarts-scrappeteer/tree/master/pyecharts-demo
