### ISSUE TITLE
请问能否加入弦图

### ISSUE THREAD

**Issue by lamapig** [pyecharts/pyecharts#333]
python一直没有太好的绘制弦图的库，echarts里的弦图比较好看，请问能否将弦图加入pyecharts呀？

**Comment by chenjiandongx** [comment]
请问弦图是什么

**Comment by lamapig** [comment]
您好，弦图就是Echarts里的和弦图，类似这种：
http://echarts.baidu.com/echarts2/doc/example/chord1.html
如果能加入那就太好了！Python目前画弦图还没有特别好的包，期待pyecharts能解决这个问题。

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/35311914-ff1165d8-00f3-11e8-89ae-4d62282cca55.png)
找到该路径 把 js 文件拉进去替换原来的

**Comment by lamapig** [comment]
请问这个路径在哪呀？本机搜索没找到。我用的Anaconda3.6版本，mac系统。

**Comment by chenjiandongx** [comment]
mac 系统的话，全局搜索下 nbextension/echarts 这个路径吧，我也没 mac 机器

**Comment by chfw** [comment]
solution 1) 建议找到pyecharts,然后找到pyecharts/templates/js，然后再放echarts.js，再执行下面操作

```
$ jupyter nbextensions install --user [python lib dir]/site-packages/pyecharts/templates/js/echarts
...
Copying: .../echarts/nanao.js -> /.../jupyter/nbextensions/echarts/nanao.js
...
    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable <the entry point>
```

**Comment by chfw** [comment]
2）或者 git clone https://github.com/pyecharts/jupyter-echarts, 把echarts.js 放入 jupyeter-echarts/echarts里面，然后执行：

```
$ jupyter nbextensions install --user jupyter-echarts/echarts
...
```

**Comment by sunhailin-Leo** [comment]
@lamapig 弦图估计只能等 Echarts 4 兼容了，目前 Echarts 4 已经没有对弦图的支持，建议可以去 Echarts 的仓库里头呼吁一下  😆
