### ISSUE TITLE
能否自定义添加配置项？很多Echarts配置项缺失

### ISSUE THREAD

**Issue by kskskska** [pyecharts/pyecharts#334]
Echarts官方配置项中很多参数在pyecharts中没有，能否支持自定义添加配置项呢？能否告知下pyecharts参数是怎么转换为echarts对应配置项的，这样我们就可以自己添加特定配置项了？

**Comment by sz547073165** [comment]
类似x、y、x2、y2的配置等

**Comment by Gavin-J** [comment]
文档中有提到很多通用配置项是怎么添加？，add()中最后一个参数接收的是一个字典，文档中没有给出实例，也没有说明清楚。

**Comment by chfw** [comment]
有的时候，我会用用hack。加完之后可以怎么黑，比如你有一个 map ， 你可以试试这么写： `map._option['series'][0]['itemStyle'] = { 'normal': {'borderColor': 'black'}}`

黑多了就不太好了，应为下一个版本可能会让你的代码失灵。所以建议，黑完之后，发来PR或者写ISSUE，请附上截图.
