### ISSUE TITLE
Geo图一个可以改进的问题

### ISSUE THREAD

**Issue by sunhailin-Leo** [pyecharts/pyecharts#336]
Geo图里面的城市名藏在点下面且修改不了位置

如图：(红圈为鼠标位置)
![1](https://user-images.githubusercontent.com/17564655/34933354-7159199a-fa11-11e7-9b32-9820b5c06723.png)

**Comment by sunhailin-Leo** [comment]
鼠标在点上没问题。
Geo图的问题~
问题主要出现在，鼠标不在点上且在区域内是的一个显示Bug。

**Comment by chfw** [comment]
我想是城市名和蓝点都是用的地区中心点为坐标，所以重叠。
