### ISSUE TITLE
Timeline 显示不全

### ISSUE THREAD

**Issue by Zeroto521** [pyecharts/pyecharts#338]
当展示数据纬度多，数据量大时显示不全
上图
![image](https://user-images.githubusercontent.com/25895405/35099036-7c0db472-fc91-11e7-9944-70a2eaf31d3a.png)

这里有**12个月份**，结果显示**10个月份**。
¯\\_(ツ)_/¯

**Comment by chenjiandongx** [comment]
有没有试过把 width 调大一点

**Comment by Zeroto521** [comment]
随着`width`和`height`变化而变化，结果一样。
甚至加入了`dataZoom`
并没有什么用，¯\\_(ツ)_/¯

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/35140331-d024e832-fd31-11e7-811b-de5dba7e6c9e.png)

**Comment by Zeroto521** [comment]
嘛啊。这我就不知道了，¯\\_(ツ)_/¯ 
可能跟数据量有关吧，
不加`Timeline`不同的堆叠图倒没问题。

**Comment by Johnzjy** [comment]
Timeline 时 pie 的label 也显示不全。

**Comment by zhangyi7456** [comment]
@chenjiandongx Timeline里，"is_visualmap=True"也是不能用的，想用timeline来显示Map地图

**Comment by chenjiandongx** [comment]
![2018-02-06_13-53-11](https://user-images.githubusercontent.com/19553554/35843899-bad1869e-0b45-11e8-8323-b41931490943.gif)

@zhangyi7456

**Comment by zhangyi7456** [comment]
@chenjiandongx 哈哈谢谢大神，这个demo有源码吗，我学习下，自己写的实现不了，我研究下原因

**Comment by chenjiandongx** [comment]
@zhangyi7456 请问你使用的是不是最新版本

**Comment by zhangyi7456** [comment]
@chenjiandongx 是V0.3.1，下面是code
![image](https://user-images.githubusercontent.com/26074889/36007720-8df853d8-0d7e-11e8-9895-8c5507c5e50a.png)

**Comment by chenjiandongx** [comment]
@zhangyi7456 这个问题已经修复好了，下个版本就可以正常使用了

**Comment by chenjiandongx** [comment]
00b73a62ff90dabc3e2a090d61d4b42ec0ff0851

**Comment by chenjiandongx** [comment]
@Zeroto521 升级到 V0.4.1 试试看
