### ISSUE TITLE
echartsgl enabled 3D charts cannot use 'svg' renderer

### ISSUE THREAD

**Issue by chfw** [pyecharts/pyecharts#343]
![screen shot 2018-01-18 at 21 54 58](https://user-images.githubusercontent.com/4280312/35124292-795c522c-fc9d-11e7-81dd-917a3cb884df.png)
![screen shot 2018-01-18 at 21 55 33](https://user-images.githubusercontent.com/4280312/35124296-7bdc0006-fc9d-11e7-89dd-4ae10861a297.png)

**Comment by chenjiandongx** [comment]
FIXED
