### ISSUE TITLE
堆叠图，增加'sum'功能

### ISSUE THREAD

**Issue by Zeroto521** [pyecharts/pyecharts#345]
希望可以在堆叠图中增加一个每列求和的mark功能
![image](https://user-images.githubusercontent.com/25895405/35131774-15812d84-fd03-11e7-883e-a4f8e72da1c2.png)

**Comment by chenjiandongx** [comment]
或许你可以使用在上面追加一条 line 显示数值

![image](https://user-images.githubusercontent.com/19553554/35320802-0c06b1cc-0120-11e8-9f6e-dd4d7a0fdc33.png)
