### ISSUE TITLE
CLI功能增强和js管理

### ISSUE THREAD

**Issue by kinegratii** [pyecharts/pyecharts#347]
基于：

- 目前 pyecharts 使用 [jupyter-pip](https://github.com/jdfreder/jupyter-pip) 安装扩展。
- 正在开发的 pyecharts-cli 也包含了相关*扩展安装*的功能。

建议：

将 jupyter-pip 替换为 pyecharts-cli ，作为 pyecharts 的依赖库。

**Comment by chfw** [comment]
pyecharts 0.3.2 可以吧pyecharts-cli列为依赖库。只是， jupyter-pip 有一部功能是能够内嵌setup.py并运行自定义安装，这部分可以看看如何改动。如果成功的话，那么pip install pyecharts 可以启动pyecharts-cli然后装jupyter-echarts, 这样会是很好的组合：pyecharts 不再需要内嵌jupyter-echarts了。
