### ISSUE TITLE
tooltip_formatter可以增加支持回调函数功能吗

### ISSUE THREAD

**Issue by jjiale** [pyecharts/pyecharts#348]
有在折线图每个点上增加额外信息的需求，目前tooltip_formatter只支持限定的模板变量，若有其他的数据信息，无法添加到tooltip中。比如，横轴是日期，纵轴是温度，想鼠标移上去tooltip中显示当天的降水，目前tooltip_formatter无法支持。

**Comment by kinegratii** [comment]
pyecharts 不支持 js 回调函数的配置参数。
