### ISSUE TITLE
Pyecharts do not support jupyter notebook in pycharm and jupyterlab

### ISSUE THREAD

**Issue by Huqin-China** [pyecharts/pyecharts#351]
1、当前仅可在anaconda的jupyter notebook下正常使用，pycharm内置的notebook功能无法正常渲染图表内容。
2、jupyerlab内也无法显示图表内容。从调试器console来看，主要有以下错误：
requirejs:“JupyterLab does not execute inline JavaScript in html output”

**Comment by chenjiandongx** [comment]
使用 online() 试试看吧

**Comment by chfw** [comment]
jupyterlab 还不支持。 pyecharm 内置 notebook 还没有试过。

**Comment by imelee** [comment]
我用Anaconda 自带的notebook，依然无法显示数据图片

**Comment by chfw** [comment]
jupyterlab does not support inline javascript which is supported by jupyter notebook + nteract.

The way around it is to use `configure(output_image='png')`

![screen shot 2018-05-17 at 22 37 17](https://user-images.githubusercontent.com/4280312/40205188-0131da5e-5a23-11e8-85cb-44c69296e9ec.png)
