### ISSUE TITLE
symbol_size  not working

### ISSUE THREAD

**Issue by youyoude** [pyecharts/pyecharts#354]
pyecharts (0.3.1)
Line 类型中 symbol_size的设置不起作用，导致无法调整symbol的大小，
查看你们的代码，是因为 symbol_size 这个属性没有写进series中去，

echarts 例子如下
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        symbolSize: 20
    }]
};

**Comment by chenjiandongx** [comment]
你的 symbol 指的是 

![image_118](https://user-images.githubusercontent.com/19553554/35320360-731c8afa-011e-11e8-8e6f-3a7054356cee.png)


右边的小圆点还是左边的三角形

**Comment by chenjiandongx** [comment]
左边的是 markpoint_symbol 右边的是 symbol

**Comment by youyoude** [comment]
右边的 symbol

**Comment by chenjiandongx** [comment]
@youyoude 已修复

**Comment by youyoude** [comment]
谢谢！！
