### ISSUE TITLE
离线模式原理

### ISSUE THREAD

**Issue by leon332157** [pyecharts/pyecharts#363]
@chenjiandongx 所以离线模式的原理就是把百度Echarts源码放在HTML里面，然后python写json是吗?

**Comment by chfw** [comment]
离线模式是说没有互联网也可以用python或／和jupyter notebook画图渲染，但不是说没有互联网可以装pyecharts啊。

**Comment by chfw** [comment]
@leon332157 , 你对美国地图感兴趣吗？

**Comment by leon332157** [comment]
@chfw 当然是安装好的情况下啊

**Comment by leon332157** [comment]
@chfw 我只是研究一下原理，刚刚读了Echarts文档，现在又看了看源码，最后明白了，所谓在线模式就是先把echarts源码引然后 var option = {} 这样来？

**Comment by chfw** [comment]
是这样的，我们把这个引用

`<script src="http://cdn.com/echarts/echarts.min.js"></script>`

变成：
```
<script>
/*Baidu echarts*/
....
/*end of echart source file */
</script>
```

**Comment by leon332157** [comment]
@chfw 对啊，那不就是我说的嘛，echarts源码在html里面啊。。。

**Comment by chfw** [comment]
jupyter的离线模式是指我们把echarts 挂在它的本地服务器下

<script src="http://localhost:8888/jupyter-echartsecharts/echarts.min.js"></script>

而不是吧echarts源代码放在html 里面了

jupyter的在线模式是指我们把echarts 挂在Github服务器下（或者用户注定服务器）：

<script src="http://github.com/pyecharts/jupyter-echartsecharts/echarts.min.js"></script>

**Comment by leon332157** [comment]
@chfw 哦，我懂了，我想我说的是网页版的离线模式吧😓
😓
