### ISSUE TITLE
Line的叠加问题

### ISSUE THREAD

**Issue by sunyinglong** [pyecharts/pyecharts#365]
@chfw 各位大神，在本人的操作中，遇到和issue #197类似的问题，不清楚现有pyecharts有无解决方案。首先上代码

```
from pyecharts import  Line
line = Line("外温与pack最大温度的关系")
areas = ["beijing", "qingdao","ningbo"]
for area in areas:
    weather_avg_temp = TemperatureData.loc[TemperatureData["area"] == area].groupby(["weather_temp"],as_index = False)["max_temp"].mean()
    v1 = weather_avg_temp["weather_temp"]
    v2 = weather_avg_temp["max_temp"]
    line.add(area, v1, v2,is_stack = True)
line
```
上述代码主要目的是画北京、青岛、宁波的一个参数与外温的关系。如果在一个图上画出三条曲线，效果如下所示
![](https://i.imgur.com/4ylDC6G.png)

而如果单独画一个城市的曲线（如北京的）

      
![](https://i.imgur.com/802U42I.png)
可以在一条曲线的图中看出北京地区的温度的最低从-10开始，而三条线那个图则其温度则是从1开始。
通过看pyecharts的源码，感觉在一个平面直角坐标系中，多条line堆叠的时候，在x轴上用其index来代替真实值。我想问的是，有没有办法让线像画散点图那样让曲线真实分布在直角坐标系中，而不是通过这种index做替换。

**Comment by chenjiandongx** [comment]
把 北京 放到最后一个 add 进去，看看效果

**Comment by sunyinglong** [comment]
如果北京放下下面，生成的图类似这种
![](https://i.imgur.com/tjpsAsc.png)
实际上等于宁波的坐标出来了偏差，单独的宁波的图如下
![](https://i.imgur.com/2a7GKfk.png)

x坐标轴按北京的来的,因为宁波没有-10这个坐标
所以还是没解决堆叠情况。

**Comment by chenjiandongx** [comment]
堆叠的话 感觉如果 x 轴没对齐的话 有些问题

**Comment by sunyinglong** [comment]
我的理解就是，就是必须得x轴对齐，不能那种在直角坐标系上画是吧

**Comment by chenjiandongx** [comment]
使用 Overlap 画试试看

**Comment by sunyinglong** [comment]
恩，我看下，但是overlap那个原理估计也解决不了这个问题。这个问题目前拿散点图倒是解决了，但总感觉那么似是而非

**Comment by chenjiandongx** [comment]
因为只有一个 x 轴 不对齐的话 真感觉不好整

**Comment by sunyinglong** [comment]
恩，确实是不好做，因为多个x轴不好选基准，下次遇到这种还是画点图吧

**Comment by chenjiandongx** [comment]
嗯 所以是否可以关闭此 ISSUE

**Comment by sunyinglong** [comment]
恩，close吧，那么我的理解是目前团队这个问题没有办法解决，只能通过其他的方式来弄是吧

**Comment by chenjiandongx** [comment]
如果你找到解决方案，欢迎回来反馈或者提交 PR
