### ISSUE TITLE
怎么让输出的图默认是居中的位置，而不是左上角

### ISSUE THREAD

**Issue by xiechenhao** [pyecharts/pyecharts#370]

**Comment by leon332157** [comment]
@xiechenhao 改图的大小

**Comment by xiechenhao** [comment]
@leon332157  哪个参数该啊 没找到啊

**Comment by leon332157** [comment]
你看看文档里面，图表选项里面有个图表大小

**Comment by leon332157** [comment]
http://pyecharts.org/#/zh-cn/charts

**Comment by leon332157** [comment]
画布大小

**Comment by xiechenhao** [comment]
@leon332157  这个调的是大小 不是位置啊

**Comment by leon332157** [comment]
@xiechenhao 你可以用grid

**Comment by leon332157** [comment]
@xiechenhao 能不能把截图发一下

**Comment by chenjiandongx** [comment]
[test_.zip](https://github.com/pyecharts/pyecharts/files/1676443/test_.zip)

解压后打开看一下，内容时候参照  API 文档自定义模板

效果

![2018-01-30_13-13-02](https://user-images.githubusercontent.com/19553554/35549206-61d83618-05bf-11e8-8d38-8da583b5582d.gif)
