### ISSUE TITLE
Parallel, line_width参数失效

### ISSUE THREAD

**Issue by Zeroto521** [pyecharts/pyecharts#371]
## Code
```
from pyecharts import Parallel

schema = ["data", "AQI", "PM2.5", "PM10", "CO", "NO2"]
data = [
        [1, 91, 45, 125, 0.82, 34],
        [2, 65, 27, 78, 0.86, 45,],
        [3, 83, 60, 84, 1.09, 73],
        [4, 109, 81, 121, 1.28, 68],
        [5, 106, 77, 114, 1.07, 55],
        [6, 109, 81, 121, 1.28, 68],
        [7, 106, 77, 114, 1.07, 55],
        [8, 89, 65, 78, 0.86, 51, 26],
        [9, 53, 33, 47, 0.64, 50, 17],
        [10, 80, 55, 80, 1.01, 75, 24],
        [11, 117, 81, 124, 1.03, 45]
]
parallel = Parallel("平行坐标系-默认指示器")
parallel.config(schema) 
parallel.add("parallel", data, is_random=True, line_width=100000)  # line_width = 1000 !!! ¯\\_(ツ)_/¯ 
parallel
```
## 效果，_(:3」∠)_
![-](https://user-images.githubusercontent.com/25895405/35497692-263c67be-0506-11e8-9512-314f3fdc220a.png)

我能说什么好呢，¯\\_(ツ)_/¯

**Comment by leon332157** [comment]
@Zeroto521 你看看js源码的json有没有配置进去

**Comment by leon332157** [comment]
@Zeroto521 帮你看一下

**Comment by leon332157** [comment]
@Zeroto521 找到问题了var lineStyle = {
    normal: {
        width: 100000,
        opacity: 0.5
    }
};
官方文档里有这样一个东西可以设置线条
@chenjiandongx 怎么可以实现这个，其实我感觉可以在json里面这样写：
"series": [
        {
            "type": "parallel",
            "coordinateSystem": "parallel",
            "name": "parallel",
            "lineStyle":{
    normal: {
        width: 100000,
        opacity: 0.5
    }
},

**Comment by leon332157** [comment]
@chenjiandongx 写出来了：
    def __add(self, name, data,line_width=2, **kwargs):#官方默认为2
        """

        :param name:
            系列名称，用于 tooltip 的显示，legend 的图例筛选。
        :param data:
            数据项。数据中，每一行是一个『数据项』，每一列属于一个『维度』。
        :param kwargs:
        """
        self.linewidth=line_width
        self._option.update(
            parallel={
                "left": "5%",
                "right": "13%",
                "bottom": "10%",
                "top": "20%"
            })
        self._option.get('legend')[0].get('data').append(name)
        self._option.get('series').append({
            "type": "parallel",
            "coordinateSystem": "parallel",
            "name": name,
            "data": data,
            "lineStyle":{"normal": {"width": self.linewidth,}}})
        self._config_components(**kwargs)

**Comment by leon332157** [comment]
![1](https://user-images.githubusercontent.com/30728609/35533833-bc2e55ce-050c-11e8-92b3-94d16fe8ce92.jpeg)

**Comment by leon332157** [comment]
@chenjiandongx json数据：
"series": [
        {
            "type": "parallel",
            "coordinateSystem": "parallel",
            "name": "parallel",
            "data": [
                [
                    1,
                    91,
                    45,
                    125,
                    0.82,
                    34
                ],
                [
                    2,
                    65,
                    27,
                    78,
                    0.86,
                    45
                ],
                [
                    3,
                    83,
                    60,
                    84,
                    1.09,
                    73
                ],
                [
                    4,
                    109,
                    81,
                    121,
                    1.28,
                    68
                ],
                [
                    5,
                    106,
                    77,
                    114,
                    1.07,
                    55
                ],
                [
                    6,
                    109,
                    81,
                    121,
                    1.28,
                    68
                ],
                [
                    7,
                    106,
                    77,
                    114,
                    1.07,
                    55
                ],
                [
                    8,
                    89,
                    65,
                    78,
                    0.86,
                    51,
                    26
                ],
                [
                    9,
                    53,
                    33,
                    47,
                    0.64,
                    50,
                    17
                ],
                [
                    10,
                    80,
                    55,
                    80,
                    1.01,
                    75,
                    24
                ],
                [
                    11,
                    117,
                    81,
                    124,
                    1.03,
                    45
                ]
            ],
            "lineStyle": {
                "normal": {
                    "width": 10
                }
            }
        }
    ],

**Comment by leon332157** [comment]
@chenjiandongx 要PR吗

**Comment by chenjiandongx** [comment]
@leon332157 暂时不需要，我要提供完整的 line_style 设置样式。

**Comment by leon332157** [comment]
@chenjiandongx 好的，具体你们实现吧

**Comment by chenjiandongx** [comment]
```
parallel.add("parallel", data, line_width=20, line_opacity=0.5)
parallel.render()
```
![image](https://user-images.githubusercontent.com/19553554/35548011-b21959a2-05b7-11e8-8321-eaca55e14936.png)

**Comment by leon332157** [comment]
@Zeroto521 你可以先用我这个办法急救一下:p

**Comment by leon332157** [comment]
@chenjiandongx 写在文档里？

**Comment by leon332157** [comment]
@chenjiandongx 这个是没改过的代码？

**Comment by chenjiandongx** [comment]
@Zeroto521 已修复

**Comment by Zeroto521** [comment]
Thanks~

**Comment by Zeroto521** [comment]
貌似，还有点问题
![image](https://user-images.githubusercontent.com/25895405/35548791-ba5243b8-05bc-11e8-8ae8-bbd50920bb5c.png)

**Comment by chenjiandongx** [comment]
你这是哪个版本的

**Comment by Zeroto521** [comment]
`fixed-line-style-bug`
刚刚fork的这个分支

**Comment by leon332157** [comment]
@Zeroto521 他说Jupyter

**Comment by Zeroto521** [comment]
> v4.4.0

**Comment by Zeroto521** [comment]
更新版本~~话说，最新版也是 v4.4.0~~也是同样的情况，
¯\\_(ツ)_/¯

**Comment by chenjiandongx** [comment]
最新的 dev 版本还不能实验，还在测试阶段

**Comment by chenjiandongx** [comment]
你先 clone 下 mater 然后 `cherry-pick  e3f0fa7a0557f5707253f` 最后再 `python setup.py install`
