### ISSUE TITLE
Map图按value值设置的颜色

### ISSUE THREAD

**Issue by pythoninessence** [pyecharts/pyecharts#374]
如题，我想把Map里按value值设置颜色，比如value值在100-300区间用某种颜色，300-800区间用另外一种颜色，需要如何设置，谢谢您。

**Comment by chenjiandongx** [comment]
使用 VisualMap 组件

![image](https://user-images.githubusercontent.com/19553554/35547852-a9774594-05b6-11e8-9b55-7e78c02259ae.png)

设置为 True，然后再自己再设置 label_color
