### ISSUE TITLE
markline 可以自定义起始位置和终点位置吗？

### ISSUE THREAD

**Issue by songqiqqq** [pyecharts/pyecharts#376]
您好，阅读文档之后发现markpoint 可以自定义point 的位置，然而却没有找到如何自定义markline的起始点和终点的位置的办法，目前的版本可以实现这个功能吗？急需，求助。

**Comment by leon332157** [comment]
@songqiqqq 具体配置？可以吧文档链接发一下然后 @chenjiandongx 麻烦研究一下

**Comment by leon332157** [comment]
@songqiqqq 我们只需要json数据

**Comment by songqiqqq** [comment]
@leon332157 ，非常感谢您的回复，文档链接是: http://pyecharts.org/#/zh-cn/charts。
其中对于mark_poitnt, 有：

markLine&markPoint：图形标记组件，用于标记指定的特殊数据，有标记线和标记点两种（Bar、Line、Kline）
mark_point -> list
标记点，默认有'min', 'max', 'average'可选。支持自定义标记点，具体使用如下
[{"coord": [a1, b1], "name": "first markpoint"}, {"coord": [a2, b2], "name": "second markpoint"}]
需自己传入标记点字典，共有两个键值对，'coord' 对应为 x y 轴坐标， 'name' 为标记点名称

然而后面的文档中，并没有说明如何支持mark_line的自定义（mark_line的初始点和结束点的坐标）。这个功能目前能实现吗？
另外，我是个新手，不是很理解您说的 ”我们只需要json数据“ 什么意思。

**Comment by leon332157** [comment]
@songqiqqq 就是echarts是个JS库你应该知道，然后它的配置是按照 [JSON](http://www.baidu.com/link?url=jWUI3CHRlcZ1Wtp_m5-50jDS4DBReFmBsCyh3TI4Q83xCr6r_n9rON4tsh4CPy9RE-O_AMTWv7hSQ8GeGMRdQ_) 来保存的，pyecharts就是对这些配置进行封装，然后写入Echart配置项。所以pyecharts需要的就是怎么写这些配置。

**Comment by leon332157** [comment]
@chenjiandongx 这个markline在哪个目录？

**Comment by chenjiandongx** [comment]
@songqiqqq 你好，这个 pyecharts 暂时不支持自定义 markline 的自定义，后续版本会考虑增加这个功能的！

**Comment by chenjiandongx** [comment]
option.py

**Comment by leon332157** [comment]
@chenjiandongx 好的，我看看官网文档是怎么配置的

**Comment by leon332157** [comment]
@songqiqqq 能不能给个例子？对应一下配置项

**Comment by leon332157** [comment]
@songqiqqq 你需要的是这个？
http://echarts.baidu.com/option.html#series-line.markLine

**Comment by songqiqqq** [comment]
@leon332157 
嗯，应该是的，我看到echarts里面是可以设置的。
”
series[i]-line.markLine.data *
标线的数据数组。每个数组项可以是一个两个值的数组，分别表示线的起点和终点，每一项是一个对象，有下面几种方式指定起点或终点的位置。

通过 x, y 属性指定相对容器的屏幕坐标，单位像素，支持百分比。

用 coord 属性指定数据在相应坐标系上的坐标位置，单个维度支持设置 'min', 'max', 'average'。
“

网上找到个例子是这么设置的：
答案对人有帮助，有参考价值1 答案没帮助，是错误的答案，答非所问
方法一：
 markLine: {
                    data:[
                        [
                            {
                                name:'两点之间的线',
                                coord:[0,120]
                            },{
                                coord:[6, 500]
                            }
                        ]
                    ]
                },
                
 方法二：
 markLine: {
            data:[
                [
                    {
                        name: '两个屏幕坐标之间的标线',
                        x: 100,
                        y: 100
                    },
                    {

**Comment by leon332157** [comment]
@songqiqqq 可以把链接给我吗

**Comment by songqiqqq** [comment]
https://segmentfault.com/q/1010000007773996
我再找找有没有更正式点的例子。

**Comment by leon332157** [comment]
@songqiqqq 对，因为官方没有给出例子，简单说了下怎么配置而已

**Comment by leon332157** [comment]
@songqiqqq 请问一下你最后想实现什么效果呢

**Comment by songqiqqq** [comment]
@leon332157 
简单来说我是想能自定义markline的起始位置和终点位置，当然颜色，粗细如果都能控制更好。

我的使用场景是：
使用echarts来可视化量化回测股票的k线图，用kline可视化行情，使用markline选项可以标识出开平仓位置。

**Comment by songqiqqq** [comment]
@leon332157 
@chenjiandongx 
我在echarts上做了个简单的样子，如果能控制线的颜色和粗细就更好了。
非常感谢和你们的交流，目前我尝试用其他办法来解决我这个需求，暂时不能用markline来实现也没问题。

代码如下:
`option = {
    xAxis: {
        data: ['2017-10-24', '2017-10-25', '2017-10-26', '2017-10-27']
    },
    yAxis: {},
    series: [{
        type: 'k',
        data: [
            [20, 30, 10, 35],
            [40, 35, 30, 55],
            [33, 38, 33, 40],
            [40, 40, 32, 42]
        ],
        
         markLine: {
                    data:[
                        [
                            {
                                name:'Long',
                                coord:['2017-10-24',10]
                            },
                            {
                                coord:['2017-10-27',40]
                            }
                        ]
                    ]
                },  
    }]
};
`

![echarts_markline](https://user-images.githubusercontent.com/10583688/35667675-8bff3710-0769-11e8-837f-cd72781e7c69.png)

**Comment by chenjiandongx** [comment]
新版本中将会加入 `mark_line_coords` 用于指定标记线的起点和终点

代码

```python
def test_scatter_markline_coords():
    scatter = Scatter("散点图示例")
    scatter.add("A", v1, v2, mark_line_coords=[[10, 10], [30, 30]])
    scatter.render()
```
![image](https://user-images.githubusercontent.com/19553554/36945586-be5a214e-1feb-11e8-97c8-466fdcf50dc6.png)

**Comment by songqiqqq** [comment]
太漂亮了，辛苦您了，为您点赞！

发件人: 陈键冬
发送时间: 2018年3月4日 20:37
收件人: pyecharts/pyecharts
抄送: songqiqqq; Mention
主题: Re: [pyecharts/pyecharts] markline 可以自定义起始位置和终点位置吗？ (#376)

新版本中将会加入 mark_line_coords 用于指定标记线的起点和终点
代码
def test_scatter_markline_coords():
    scatter = Scatter("散点图示例")
    scatter.add("A", v1, v2, mark_line_coords=[[10, 10], [30, 30]])
    scatter.render()

**Comment by patrickwangqy** [comment]
请问mark_line_coords可以标多条线嘛???

**Comment by wangwei8888** [comment]
1.20版本 在kline中   markline依然无法实现 自定义起点终点
![image](https://user-images.githubusercontent.com/36029972/59203760-d5a07800-8bd1-11e9-9d34-12969027ba91.png)
https://www.echartsjs.com/examples/editor.html?c=candlestick-sh
@chenjiandongx

**Comment by diffguo** [comment]
在2.0.4版本中，pyecharts的kline依然无法实现自定义起点终点
