### ISSUE TITLE
change "kline" to "candlestick"

### ISSUE THREAD

**Issue by nerdDan** [pyecharts/pyecharts#377]
please use "candlestick" in API instead of "kline" which is not proper english.

**Comment by kinegratii** [comment]
Acccording to the [Echarts3 document](http://echarts.baidu.com/option.html#series-candlestick), candlestick is the new alias name for kline.

pyecharts should support new name *candlestick* in the source code, besides the document.

This is a demo usage after this change.

Old alias name:
```
from pyecharts.charts.kline import Kline
```
New alias name

```
from pyecharts.charts.candlestick import Candlestick
```

**Comment by chenjiandongx** [comment]
个人意见，可以在文档中注明 'Candlestick' 为 Kline 的别名已做提醒。因为如果是别名就是表示两个是同个意思，源码只提供一个即可！

**Comment by chfw** [comment]
__init__.py:

```
from pyecharts.charts.kline import Kline

Candlestick = Kline
```

**Comment by chenjiandongx** [comment]
FIXED
