### ISSUE TITLE
English documentation is not showing images

### ISSUE THREAD

**Issue by marciorf** [pyecharts/pyecharts#382]
Sorry I don't understand the guidelines to post here, its all in chinese

But english doc images are all broken: http://pyecharts.org/#/en-us/charts

**Comment by chfw** [comment]
Fewer and fewer English speaking visitor show up so the effort was spent on the Chinese doc. I will pick this up once 0.3.2 is out of the door.

**Comment by marciorf** [comment]
Seriously? Im here since the beggining.
Always unstar and star again so this Project is always at my top 

Please dont abandon english versions

**Comment by faststare** [comment]
are we suppose to use google translate?

**Comment by leon332157** [comment]
@chfw I can help to change if you want to.

**Comment by chfw** [comment]
PR is always welcome but bear in mind that a pr is not guaranteed to pass always as we have code review process.

**Comment by leon332157** [comment]
@chfw Have you updated readme for snapshot in version number and is it updated on pypi?

**Comment by chenjiandongx** [comment]
English document does not maintain anymore

**Comment by chfw** [comment]
@marciorf @faststare @leon332157 , if you may, please help us do proof-reading and PR is welcome.

**Comment by FangyangJz** [comment]
Hope that everyone, especially native language isn't Chinese, still have passion on this excellent project. 
Sorry for being late for almost 7 months.  O(∩_∩)O

**Comment by chfw** [comment]
We were waiting for you to come: @FangyangJz  And I hope more will follow.

**Comment by marciorf** [comment]
Awesome work @FangyangJz !!! 

Thanks!
