### ISSUE TITLE
CITY_NAME_PINYIN_MAP 拼音字典库存储和查询优先级的问题

### ISSUE THREAD

**Issue by kinegratii** [pyecharts/pyecharts#385]
### js库布局
假设环境中有两个 js库。
Js库 js1 

```
{
    "PINYIN_MAP": {},
    "FILE_MAP": {
      "fujian": "fujian"
    },
    "JUPYTER_URL": "/nbextensions/demo_map",
    "JUPYTER_ENTRY": "demo_map/main",
    "JS_FOLDER": "echarts",
    "GITHUB_URL": "https://demo.com/map_library"
}
```

js库 js2

```
{
    "PINYIN_MAP": {
       "福建": "fujian"
    },
    "FILE_MAP": {
      "fujian": "fujian"
    },
    "JUPYTER_URL": "/nbextensions/echarts",
    "JUPYTER_ENTRY": "echarts/main",
    "JS_FOLDER": "echarts",
    "GITHUB_URL": "https://pyecharts.github.io/jupyter-echarts/echarts"
}
```

以上加载顺序为 js1 -> js2

### 代码测试与分析 

第一步，通过 `js_extensions.load_all_extensions` 后,

`conf.CITY_NAME_PINYIN_MAP` 的内容为

```
{
    "福建": "fujian"
}
```

第二步，构建测试代码

```
from pyecharts.charts.map import Map

m = Map()
m.add(map_type='福建')
```

**此时查询`conf.CITY_NAME_PINYIN_MAP` 后 m.js_dependencies = ['fujian']**

第三步，在随后定位 js 过程中是以 fujian 名称为查找键，所以最后定位到 js1 库的 fujian.js 文件，以上结果从直观性来看，不符合结果。**“福建” 这个中文别名名称只在 js2 库出现，最后定位也应当是定位到 js2 库中。**

关键点在于：

`CITY_NAME_PINYIN_MAP`  初始化使用的是 update 操作，后面 js 库的元素会覆盖前者 js 库的内容，而后续确实相反的优先级，会造成查询混乱。

## 改进建议

- CITY_NAME_PINYIN_MAP 这个字典移到各个 js_extension保存，
- 地图Add 时不再查询`CITY_NAME_PINYIN_MAP` ，由js标签执行时确定
- 开放js库自定义顺序，目前是依据 `os.listdirs` 额结果
- 为了兼容以前的版本（能够使用 `map_type='福建'`），目前由 pyecharts 团队的JS库具有最高的优先级，排1,2位

**Comment by chfw** [comment]
现在正在优化 https://github.com/pyecharts/pyecharts/pull/368，可以把这个考虑在内。等PR吧

**Comment by chfw** [comment]
> 为了兼容以前的版本（能够使用 map_type='福建'），目前由 pyecharts 团队的JS库具有最高的优先级，排1,2位

这个还没能做到
