### ISSUE TITLE
想问下想画双向条形图在参数怎么设置？

### ISSUE THREAD

**Issue by xiechenhao** [pyecharts/pyecharts#386]

**Comment by chenjiandongx** [comment]
双向条形图？能否提供效果图

**Comment by xiechenhao** [comment]
@chenjiandongx  [https://pt.sjtu.edu.cn/picbucket/1353_151809740476.jpg](url)

**Comment by dingranhaha** [comment]
同问

**Comment by sunhailin-Leo** [comment]
@xiechenhao @dingranhaha 
* 可以试着将两个 bar 图用 Grid 的形式拼在一起 
* https://gallery.echartsjs.com/editor.html?c=xS1zMjXe2x
