### ISSUE TITLE
Create responsive Echart in Django

### ISSUE THREAD

**Issue by bummm26** [pyecharts/pyecharts#389]
I am trying to make my chart responsive. Unfortunately the only possibility is set the width to a certain value and I can set it to 100% which could help me out. Is there any solution to make my charts responsive? Thank you in advance!

**Comment by chenjiandongx** [comment]
https://github.com/pyecharts/pyecharts/issues/370

**Comment by faststare** [comment]
height page should be customized. the current api gives equal height in page. example chart 1 should be 400 height chart 2 should be 200 height. there no customization on page api unless you hard coded but they still equal height.

**Comment by leon332157** [comment]
@bummm26 I Do you understand Chinese?

**Comment by bummm26** [comment]
Unfortunately I do not understand Chinese. Since my question I solved the problem partly. I tried to set the width="100%" and it worked despite the documentation suggest  to use integer and not string. After this correction when is refresh my page in smaller size my chart change it's size too. Unfortunately I have to refresh the page to change chart's width. Maybe is there any solution to resize the chart continuously when the page narrowing? Thank you in advance for your help.

**Comment by leon332157** [comment]
@bummm26 Yes, I understand that the document might not be very clear. I believe @chenjiandongx @chfw and other contributers worked very hard on the document. We haven't figure out how to use with Django yet.

**Comment by chenjiandongx** [comment]
@bummm26 
This is the demo https://github.com/pyecharts/pyecharts/blob/master/docs/zh-cn/flask.md#%E6%A8%A1%E6%9D%BF%E6%89%A9%E5%B1%95

**Comment by chfw** [comment]
@bummm26 , you will need a custom template as the following. Additional javascript was provided to monitor window.resize event, upon which the echart instance resize accordingly.


```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Proudly presented by ECharts</title>
	{% for jsfile_name in script_list %}
        <script src="{{ host }}/{{ jsfile_name }}.js"></script>
    {% endfor %}
</head>

<body>
  <div id="{{ chart_id }}" style="width:{{ my_width }};height:{{ my_height }}px;"></div>
    <script type="text/javascript">
        window.onload = function() {
			setTimeout(function() {
				var myChart_{{ chart_id }} = echarts.init(document.getElementById('{{ chart_id }}'));
				var option_{{ chart_id }} = {{ my_option|safe }};
				myChart_{{ chart_id }}.setOption(option_{{ chart_id }});
				window.onresize = function() {
					myChart_{{ chart_id }}.resize();
				};
			}, 1000);
		};
    </script>
</body>

</html>
```

will update the en doc later.

**Comment by bummm26** [comment]
@chfw  @chenjiandongx  Your code is refer to Flask and not Django. The example would be very good but in Django I can't set chart_id, so it generate hex id to identify, so I can't refer to it in my template because it generate again after every refresh.
