### ISSUE TITLE
建议增加【是否显示网格线】的配置项

### ISSUE THREAD

**Issue by akarrin** [pyecharts/pyecharts#395]
理由如下：

- 在制作单个图表的时候为了美观的需要，有时不需要网格线

- 在添加了`mark_line`标记线的时候，有时网格线与markLine重叠

- 在制作`Grid`类图表的时候，过多的网格线显得繁杂

**Comment by chenjiandongx** [comment]
理由可以说是十分充分了，下个版本会提供该配置项， is_spliteline_show 可用来控制该线的显示，默认为 True，即显示。可设置为 False 隐藏

以下是效果

![image](https://user-images.githubusercontent.com/19553554/35973717-6efb3dbe-0d11-11e8-8460-811b2431a4e2.png)

**Comment by chenjiandongx** [comment]
FIXED
