### ISSUE TITLE
Scatter3D中加入额外的数据点，并标注固定颜色的问题

### ISSUE THREAD

**Issue by cavities** [pyecharts/pyecharts#397]
Scatter3D中加入额外的数据点，并标注固定颜色的问题；
在Scatter3D.add 中 标注额外点时候无法设置颜色

**Comment by chenjiandongx** [comment]
而外数据点指的是？

**Comment by cavities** [comment]
就是 数据的颜色 比如通过KernelDensity  算出，点的密度 score 分数， 怎么比如这个数值是在 1.0~5.0 之间 该怎么自适应根据颜色对数据进行调整
