### ISSUE TITLE
Add numbers to Axis

### ISSUE THREAD

**Issue by bummm26** [pyecharts/pyecharts#398]
In the JS version there was a possibility to add or educe numbers to the Axis like this:

 ```
 radiusAxis: {
            axisLabel: {
                formatter: function (val) {
                    return (val - 90)*-1  + '°';
                },
                verticalAlign : 'bottom'
            }, 
            interval: 30,
            min: 0,
            max: 90,
```

Unfortunately in the Python version the only editing possibility is adding string. Is there any way to do numerical methods? Thank you in advance for your help!

**Comment by chenjiandongx** [comment]
pyecharts don't support any javascript callbaclk function, because pyecharts pass the data with JSON format.
