### ISSUE TITLE
Geo显示问题

### ISSUE THREAD

**Issue by CaoChensy** [pyecharts/pyecharts#418]
<img width="1094" alt="2018-03-02 20 03 47" src="https://user-images.githubusercontent.com/31162834/36898495-090809be-1e56-11e8-8e62-078cf3837db9.png">
<img width="783" alt="2018-03-02 20 13 31" src="https://user-images.githubusercontent.com/31162834/36898534-33e0d472-1e56-11e8-9e3a-9742999fcc42.png">

用的最新的pyecharts python36

**Comment by chfw** [comment]
`pip install echarts-countries-pypkg`

http://pyecharts.org/#/zh-cn/customize_map?id=如何获得更多地图

**Comment by chfw** [comment]
请仔细阅读发布日志： http://pyecharts.org/#/zh-cn/changelog?id=version-032-20180226
