### ISSUE TITLE
如何在GeoLines中加入数值？

### ISSUE THREAD

**Issue by ileadall42** [pyecharts/pyecharts#419]
![image](https://user-images.githubusercontent.com/27263086/36900088-c5407c78-1e5c-11e8-837b-8a4201e5e5a9.png)
我想自定义最后一个数值，有什么好办法吗？

**Comment by chenjiandongx** [comment]
这个值在源码中被我写死了 :(，因为每个点可能为多条路线的起点或者终点，所以我也不好提供配置项

**Comment by chaoshengt** [comment]
@chenjiandongx 可否用字典的方式实现

**Comment by chenjiandongx** [comment]
#565

**Comment by chenjiandongx** [comment]
版本已更新 v0.5.5
