### ISSUE TITLE
ttributeError: 'Kline' object has no attribute 'custom'

### ISSUE THREAD

**Issue by digdig** [pyecharts/pyecharts#421]
win10
python 3.64
pyecharts 0.3.3

running a sample program in docs, return the error:

```
line 27, in <module>
    kline.custom(line_1.get_series())
AttributeError: 'Kline' object has no attribute 'custom'
```

![image](https://user-images.githubusercontent.com/5459093/36936786-89e60b00-1f44-11e8-9090-540834409f00.png)

![image](https://user-images.githubusercontent.com/5459093/36936789-9a2a7f82-1f44-11e8-9779-19dfc5c1441c.png)

**Comment by chenjiandongx** [comment]
http://pyecharts.org/#/zh-cn/charts?id=grid%ef%bc%9a%e5%b9%b6%e8%a1%8c%e6%98%be%e7%a4%ba%e5%a4%9a%e5%bc%a0%e5%9b%be
