### ISSUE TITLE
增加 Choropleth map - 等值区域图

### ISSUE THREAD

**Issue by chfw** [pyecharts/pyecharts#422]
有了很多地图之后，[Choropleth map - 等值区域图](https://en.wikipedia.org/wiki/Choropleth_map)就变得必须有了。

![choropleth map -](https://user-images.githubusercontent.com/4280312/36940054-a8ac79f4-1f33-11e8-80f3-bfab5f1f5e65.png)

**Comment by chenjiandongx** [comment]
@chfw 详见 viuualMap_enchance branch

**Comment by chfw** [comment]
Choropleth map - 等值区域图 转入 pyexcel-echarts 了
