### ISSUE TITLE
0.3.3版本timeline放入多个Kline后，显示不正常

### ISSUE THREAD

**Issue by usernamehastaken** [pyecharts/pyecharts#427]
适用anaconda3-5.1
=====
kline=Kline()
raw_data=list(zip(df['open'],df['close'],df['low'],df['high']))
raw_data1=list(zip(df['open']+5,df['close']+5,df['low']+5,df['high']+5))
kline.add('1',df.index,raw_data)
kline1=Kline()
kline1.add('2',df.index,raw_data1)
timeline=Timeline()
timeline.add(kline,'a')
timeline.add(kline1,'b')
timeline
===
其中df为储存数据的一个DataFrame

**Comment by usernamehastaken** [comment]
![default](https://user-images.githubusercontent.com/27677764/37031735-de5825a0-217a-11e8-9aaf-59ecec471c1b.PNG)

**Comment by chenjiandongx** [comment]
如若想是想 Timeline 的话，最好请确保横轴数据一致！

**Comment by usernamehastaken** [comment]
@chenjiandongx 上面那个图两个kline的横轴都是df.index，区别在于图2 的k线是在图1的数据上都加5，应该不存在您说的这个问题，而且刚显示的是正常的，但是点箭头换到第二张图 就出现这个状况了

**Comment by usernamehastaken** [comment]
@chenjiandongx 试了0.4.0版本 ，好像渲染有问题

**Comment by usernamehastaken** [comment]
问题已经解决！谢谢！
