### ISSUE TITLE
Overlap叠加Bar的一个问题

### ISSUE THREAD

**Issue by splusz** [pyecharts/pyecharts#429]
python: Python 3.6.1 Anaconda 4.4.0 (64-bit)
pyecharts: 0.3.3

代码如下：
```python
from pyecharts import online,Line,Bar,Overlap
online()
attr = ['A', 'B', 'C', 'D', 'E', 'F']
v1 = [10, 20, 30, 40, 50, 60]
v2 = [-20, 5, -15, 20, 30, 40]

line = Line()
line.add("line", attr, v1,yaxis_min=5, yaxis_max=70)  #当在这里指定的y轴刻度范围不包含原点0时，后面bar的绘制不正常
bar = Bar()
bar.add("bar", attr, v2)

overlap = Overlap()
overlap.add(line)
overlap.add(bar, yaxis_index=1, is_add_yaxis=True)
overlap
```
结果如下：
![image](https://user-images.githubusercontent.com/21697589/37138492-38fa4e64-22e5-11e8-9807-a3f5779531a3.png)

bar图没有以原点为基准进行绘制。上述现象出现的条件是：在代码中line.add()中指定的y轴刻度范围不包含原点0。不指定范围，或指定的范围包括包含原点，则绘制正常。

若叠加的第二个图不是bar，而是另一个line，且line需要填充面积时，也会出现类似的现象。

**Comment by chenjiandongx** [comment]
如果是这样的话，暂时就请不要指定 y 轴数值范围了  :) ，等看看具体是什么问题

**Comment by sunhailin-Leo** [comment]
@splusz 可以用 1.1.0 再次尝试～
