### ISSUE TITLE
v0.4.0 Timeline 显示等问题

### ISSUE THREAD

**Issue by wkhola** [pyecharts/pyecharts#436]
python==2.7 pyecharts==v0.4.0
bar图加上时间轮播之后，图形宽度变窄且不能自适应
![image](https://user-images.githubusercontent.com/32009198/37320040-d1a53dac-26ac-11e8-9c4c-57aff48ae2e3.png)
正常设置下 鼠标移动不能显示标签
![image](https://user-images.githubusercontent.com/32009198/37320231-ae74be10-26ad-11e8-8762-5f30aeed5077.png)

**Comment by chenjiandongx** [comment]
FIXED
