### ISSUE TITLE
安装后无法导入pyecharts

### ISSUE THREAD

**Issue by HXHwow** [pyecharts/pyecharts#446]
### 提 issue 注意事项
pyecharts 0.4.1  python3.6.3  使用系统win10
![image](https://user-images.githubusercontent.com/33168453/37572590-5a0bc996-2b48-11e8-9a21-f2d837f08a9d.png)

pip显示成功安装，但是无法导入，缺少文件，该怎么办呢？

**Comment by chfw** [comment]
是 pillow 没有装好。试试 pip install pillow. 请注意， pillow 和 PIL 不能共处“一室”。 PIL 要被 pip uninstall先，再装 pillow.

**Comment by HXHwow** [comment]
可以了 ！！！ 非常感谢 ！！！ :>!

**Comment by chenjiandongx** [comment]
FIXED
