### ISSUE TITLE
mark_point 鼠标悬停在pin的图标上，显示的横坐标与实际的对不上

### ISSUE THREAD

**Issue by DiamondI** [pyecharts/pyecharts#450]
显示的横坐标似乎和"max"、"min"以及"average"在 mark_point[] 中的位置有关。如果处在第一个位置，那么显示出来的就是第一个横坐标的值，依次类推。

![image](https://user-images.githubusercontent.com/18584660/37639350-fda6bac6-2c4b-11e8-9271-99e638e9d9b8.png)

![image](https://user-images.githubusercontent.com/18584660/37639372-20558890-2c4c-11e8-98a1-75e8e27a43f4.png)

**Comment by chenjiandongx** [comment]
看起来是的，看看要不要给他提供一个 mark_tooltip_formatter 参数来配置，你可以试试

```
tooltip_formatter='{a}: {c}',
```

**Comment by DiamondI** [comment]
所以是b的值弄错了吗

**Comment by chenjiandongx** [comment]
@DiamondI v0.5.7+ 版本

![image](https://user-images.githubusercontent.com/19553554/44008245-b96e9f68-9ed3-11e8-9704-fd13dbb3face.png)
