### ISSUE TITLE
0.3.3以后的K线图不显示提示的【open, close, lowest, highest】了

### ISSUE THREAD

**Issue by 809069790** [pyecharts/pyecharts#452]
0.3.3以后的K线图不显示提示的【open, close, lowest, [highest】了]

**Comment by chenjiandongx** [comment]
这个是 Echarts 本身版本的问题，升级到 Echarts4.0 之后，原来的配置效果不生效了，现在它只支持利用 js 函数来设置成原来的效果，而 pyecharts 是无法传递 js 函数的，

综上所述，无解！

**Comment by chfw** [comment]
echarts 3.6.2:

![wechatimg182](https://user-images.githubusercontent.com/4280312/37690271-c13cd0a6-2ca1-11e8-9c8e-78e19bdbcd57.png)

echarts 4.0.4:
![wechatimg180](https://user-images.githubusercontent.com/4280312/37690274-c3dbb34a-2ca1-11e8-9cc0-7441c284fab3.png)

**Comment by linbozhong** [comment]
Well Done. I search the API documentnot only pyecharts buy also echarts for all night. and Now.  It was fixed finally. tks!

**Comment by Wilson-Fu** [comment]
?
'0.5.5'版本中
kline.add('test',dt.date.values,dt.iloc[:,1:5].values,tooltip_formatter='{b0}{c0}')
只能显示出：
![image](https://user-images.githubusercontent.com/38939718/43153894-264d36aa-8fa5-11e8-913e-bf5503f7f032.png)
总么办，要单独建一条标签数据吗？没有其他简便方式？
