### ISSUE TITLE
Geo（地理坐标系）部分市不能显示

### ISSUE THREAD

**Issue by Cliff2016** [pyecharts/pyecharts#454]
庆阳 coordinates is not found
来宾 coordinates is not found
池州 coordinates is not found
眉山 coordinates is not found
贺州 coordinates is not found
万宁 coordinates is not found
中卫 coordinates is not found
文昌 coordinates is not found
崇左 coordinates is not found
临沧 coordinates is not found
黔西南布依族苗族自治州 coordinates is not found
海东 coordinates is not found
东方 coordinates is not found
宣城 coordinates is not found
广安 coordinates is not found，

这些地方不能显示出来，不知道什么原因
pyecharts (0.4.1)
Python 3.5.2

**Comment by helllma** [comment]
上次也发现了，后来看了下源码，好像是有个json里自己加上地名，和坐标，不过谷歌的坐标和显示出来的貌似有点误差。

**Comment by kinegratii** [comment]
可以将自定义坐标传入 `Geo.geo_cities_coords` 

关于坐标格式需询问 @chfw

**Comment by Cliff2016** [comment]
感谢，这些地方在CITY_GEO_COORDS里是有的，不过因为key只有一个，如“东方市”，“来宾市”等，而没有“东方”或“来宾”
