### ISSUE TITLE
如何在notebook

### ISSUE THREAD

**Issue by HXHwow** [pyecharts/pyecharts#456]
使用 .render_notebook()  无法在jupyter notebook里显示图像
![image](https://user-images.githubusercontent.com/33168453/37721403-4e11dd7e-2d64-11e8-875c-666178bf9378.png)
应该如何在notebook里直接显示图像呢？

**Comment by chfw** [comment]
请读文档

**Comment by chfw** [comment]
http://pyecharts.org/#/zh-cn/jupyter_notebook?id=显示图表
