### ISSUE TITLE
如何把多个图像放到一个echart生成的html里？

### ISSUE THREAD

**Issue by RorschachChan** [pyecharts/pyecharts#458]
我有一个需求，是将公司云存储过去一周的三个数值（比较分别叫A，B，C）作图，但是c值很大，B和A的值是C的几乎是千分之一，所以做在一张柱状图里特别难看----高的高耸入云，低的鼠标都划不着。

所以我打算把C单独做一个图，B和A做到另外一个图里，用html展示出来。那请问如何在一个echart的python脚本里画两个图？我这个脚本应该如何改变？

现在脚本如下:

```
#!/usr/bin/env python
#coding=utf-8
from pyecharts import Bar

attr = ["{}day".format(i) for i in range(1, 8)]
attr = ["Mon", "Feb", "Wed", "Thu", "Fri", "Sat", "Sun"]    #横坐标
v1 = [1.49, 2.09, 4.03, 2.23, 5.26, 7.71, 7.56]
v2 = [0.3, 0.9, 0.2, 0.4, 0.7, 0.7, 0.6]
v3 = [758.15, 753.22, 801.28, 777.99, 828.7, 779.7, 775.6]    #值是随便写的，到时候会从redis里拿

bar = Bar("云存储情况总览", "本图表展示过去一周的云存储情况")
bar.add("A文件", attr, v1, mark_line=["average"], mark_point=["max", "min"])
bar.add("B文件", attr, v2, mark_line=["average"], mark_point=["max", "min"])
bar.add("C文件", attr, v3, mark_line=["average"], mark_point=["max", "min"])
bar.render('/root/test.html')    #生成一个html文件
```

**Comment by kinegratii** [comment]
使用 `Grid` 类即可， 详情可查看 http://pyecharts.org/#/zh-cn/charts?id=grid%ef%bc%9a%e5%b9%b6%e8%a1%8c%e6%98%be%e7%a4%ba%e5%a4%9a%e5%bc%a0%e5%9b%be

**Comment by RorschachChan** [comment]
感谢感谢

**Comment by RorschachChan** [comment]
你好，我按照您说的去试了一下，由于我这个需要在一个html里做两个bar图。

#!/usr/bin/env python
#coding=utf-8
from pyecharts import Bar, Grid

attr = ["杭州区", "深圳区", "北京区", "青岛区"]
v1 = [754.13, 281.34, 2.09, 0.2]
v2 = [768.03, 269.24, 2.09, 0.2]
bar = Bar("A情况总览","本图表展示A文件存储情况",height=2000)
bar.add("今日值", attr, v1, is_stack=True)
bar.add("昨日值", attr, v2, is_stack=True)

attr2 = ["杭州区", "深圳区", "北京区", "青岛区"]
x1 = [3.38, 0.22, 0.31, 0.33]
x2 = [3.38, 0.24, 0.31, 0.38]
bar2 = Bar("B情况总览","本图表展示B文件情况",height=1000)
bar2.add("今日值", attr2, x1, is_stack=True)
bar2.add("昨日值", attr2, x2, is_stack=True)

grid = Grid()
grid.add(bar, grid_bottom="60%", grid_right="60%")
grid.add(bar2, grid_bottom="60%", grid_left="60%")
grid.render('/tmp/grid.html')


发现生成的html，bar的标题是覆盖的...

**Comment by chenjiandongx** [comment]
可以自己调整标题位置，提供参数了，详细请看通用部分文档

**Comment by RorschachChan** [comment]
我解决了标题的问题，但是又有了一个新的问题，又要麻烦您。

就是html的大小好像是固定的，放一个图像的话很美观，但是分上下左右放四个图像进去，每个图像都好小，调整grid_width/height就把图调整出界面了，把文档找了一下，也没有发现能调整整个背景大小的地方，请指点一下。

**Comment by RorschachChan** [comment]
搞定啦~~

**Comment by lianghao6** [comment]
> 搞定啦~~

怎么搞定的啊  我也遇到过这个问题了~~~

**Comment by lianghao6** [comment]
> 搞定啦~~

不用了 我也搞定了 - -在InitOpts里
