### ISSUE TITLE
为scatter和bar进行overlap时出现显示错误

### ISSUE THREAD

**Issue by RocStone** [pyecharts/pyecharts#459]
python 3.5.4, pyechart 0.41

    attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
    v1 = [5, 20, 36, 10, 10, 100]
    line = Line("line - es 示例")
    line.add("", attr, v1, is_random=True)
    es = EffectScatter()
    es.add("", ['衬衫', '裤子', '袜子'], [1, 1, 1], effect_scale=8)
    overlap = Overlap()
    overlap.add(line)
    overlap.add(es)
    overlap.render('组合.html')

如图可见，把鼠标放在第2、第3个点上时，显示的横坐标是羊毛衫和雪纺衫，而不是整整的横坐标裤子和袜子。
![image](https://user-images.githubusercontent.com/13502763/37747259-4b0bfe84-2db9-11e8-83df-1d11ba93d431.png)
![image](https://user-images.githubusercontent.com/13502763/37747269-5436d326-2db9-11e8-939d-7e142e7e2d9c.png)

**Comment by chenjiandongx** [comment]
应该是加上散点图之后，散点图的 tooltip 是按序读取 x 轴的数据，所以只读取了前三个，导致数据没对上

**Comment by chenjiandongx** [comment]
所以 Grid 图最好还是两种图形的 x 坐标轴数据能完全一致，

**Comment by chenjiandongx** [comment]
@RocStone 请更新到 V0.5.7+ 问题已经解决
