### ISSUE TITLE
地理坐标数据改善

### ISSUE THREAD

**Issue by kinegratii** [pyecharts/pyecharts#460]
## 现有功能描述

- `pyecharts.constants.CITY_GEO_COORDS` 提供了一些常用城市坐标
- 用户可以修改上述常量或传入自定义坐标到 `Geo.add(geo_cities_coords)` 以供本图表实例使用

## 问题描述

第一， `constants.CITY_GEO_COORDS` 的可修改特性不符合 constants 的定义
第二，`Geo.geo_cities_coords` 目前定义在 `Geo.add` ，亦即仅作用于单个系列
第三，`geo_cities_coords` 参数为直接完全屏蔽 `CITY_GEO_COORDS` 的数据，如要使用，需额外引入

https://github.com/pyecharts/pyecharts/blob/8659d10e8292d4878bacd405727c5d5d4623f21d/pyecharts/charts/geolines.py#L88-L91

## 改进

- 将 `constants.CITY_GEO_COORDS` 移到新的模块 `data.coordinates`
- 新增访问接口 `get_coordinates(name)` 和 `add_coordinates` ，禁止直接修改原始字典数据 `CITY_GEO_COORDS`
- 新增 `Geo.add_coordinates` 接口，支持对象级别的坐标定义
- 保留现有的 `geo_cities_coords`
- 上述两处的 `add_coordinates` 采用与 `CITY_GEO_COORDS` 合并(dict.update)的策略，而不是完全覆盖
- 新增接口返回所有可用的坐标项目。
- 将无法引用坐标的信息的策略从打印 `"%s coordinates is not found" % _name` 改为 异常 `raise ValueError` （附 #454） 

## 示例

```
g = Geo()
g.add_coordinates({'城市A':[127, 25]}) 
g.add('系列A',['厦门', '城市A'], [45, 3]) # 从 CITY_GEO_COORDS 获取坐标
g.add('系列B', ['福州', '城市A'], [23, 53])
```

**Comment by chenjiandongx** [comment]
个人看法，

* CITY_GEO_COORDS  本身应该是不可以修改，因为一开始的意向是如果用户自己提供了坐标，就按用户自己的来，如果没有就按项目提供的。

* ```新增 Geo.add_coordinates 接口，支持对象级别的坐标定义```。这点我赞成，这样的话不必每个 add() 都需要传参设置

* ```将无法引用坐标的信息的策略从打印 "%s coordinates is not found" % _name 改为 异常 raise ValueError （附 #454）```，可以，这点我也赞同。

* 覆盖原来坐标这个，我的新想法是，如果系统本身提供了，就更新。如果没提供的话，就追加。

* 现阶段的 add() `geo_cities_coords` 先提供 warnings，下下版本废弃。

**Comment by chfw** [comment]
1. CITY_GEO_COORDS 有3000-4000 个坐标，如何查找有木有哪个坐标？目测么？
2. CITY_GEO_COORDS 仅限于中国坐标点，范围是不是需要扩大些？我认为应该是世界所有城市坐标
3. g.add_coordinates({'城市A':[127, 25]})， 这样的字典定义需要升级成 class CityGeoPoint.

```
paris = CityGeoPoint('巴黎’， 48.864716, 2.349014)
g.add_city(paris)
```

**Comment by kinegratii** [comment]
@chfw 

第一点：底层数据结构保持现有的 `{<name>:<coordinate>}` 字典结构，增加 `search` 简单的搜索接口。

```
pyecharts.data.coordinates.search(name='保')
# 返回
{
    '保定': [115.48, 38.85],
    '保山': [99.10, 25.08],
}
```

第二点：`CITY_GEO_COORDS ` 改个名字即可，建议保留现在使用 Python 字典直接存储 的方案。

第三点，没有必要这么做吧，不知你的考量是什么
```

**Comment by chfw** [comment]
@kinegratii 第三点, 用户加的时候， {'巴黎':[48.864716, 2.349014]} 变成了 CityGeoPoint('巴黎’， 48.864716, 2.349014)，可读性更强。

**Comment by chenjiandongx** [comment]
感觉没有必要修改成 class，和 @kinegratii 想法一致，坐标是当时网上找的。

**Comment by chenjiandongx** [comment]
@kinegratii 你的意思是把坐标移动至 新 `data` 模块？@chfw 你的意见呢

**Comment by chfw** [comment]
嗯，确实不是constants. data 模块需要提供 search。

**Comment by lupingcoder** [comment]
我现在想使用这个改进后的功能，就是使用g.add_coordinates这个函数，但是好像并没有这个函数啊，我使用的是0.4.1版本的，请问改进后的源码要去哪里下载呢？

**Comment by chfw** [comment]
@lupingcoder : [0.5.0](https://github.com/pyecharts/pyecharts/blob/master/docs/zh-cn/changelog.md#version-050---20180428)

@all , https://github.com/pyecharts/pyecharts/pull/663 提供了国际城市坐标。
