### ISSUE TITLE
柱状图无法设置渐变

### ISSUE THREAD

**Issue by dubei2** [pyecharts/pyecharts#464]
柱状图单柱子无法设置渐变色。
![image](https://user-images.githubusercontent.com/37291067/37859470-1bff1c38-2f4f-11e8-9578-b163a3c913fe.png)。

**Comment by chenjiandongx** [comment]
这个有 Echarts 实现了的图吗，我可以查看一下配置

**Comment by GCWK** [comment]
http://echarts.baidu.com/examples/editor.html?c=bar-gradient
pyecharts似乎没有渐变色的配置参数

**Comment by stevenyvette** [comment]
@dubei2  你好，请问如何设置配置项得到你图中那样横向的柱状图？

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/40915519-f62455fa-682e-11e8-9437-be254575a178.png)

这看起来是实现了 Echarts 自带的类
