### ISSUE TITLE
为什么不把静态文件安装到 share/jupyter/nbextesions/文件夹呢？

### ISSUE THREAD

**Issue by forbxy** [pyecharts/pyecharts#470]
保持notebook插件安装方式一致感觉很有必要。
特别是像我们这样静态文件都走CDN，打包静态文件比较麻烦~~

**Comment by chfw** [comment]
你误解了。我们做就是你所说的。

> 保持notebook插件安装方式一致感觉很有必要。

用程序装，而不是手动：
https://github.com/pyecharts/pyecharts-jupyter-installer/blob/master/pyecharts_jupyter_installer/jupyter_install.py#L53

> 特别是像我们这样静态文件都走CDN，打包静态文件比较麻烦~~

这个是所有文件：
https://pyecharts.github.io/assets/

这里是用法：
http://pyecharts.org/#/zh-cn/flask?id=step-2-调用-chart_instancerender_embed-方法渲染图表

CDN 正在考虑用 unpkg.com 的 CDN.

**Comment by chfw** [comment]
另外呢， jupyter nbextension 安装有两个模式， 用户模式（--user)和系统模式(--system). pyecharts 选择的是用户模式。

操作系统不一样呢， jupyter 的文件夹也是变化的。 在 MacOS 里， pyecharts 的 jupyter extension 在这里可以找到： /Users/路人甲/Library/Jupyter/nbextensions/

`jupyter --path` 可以列出 jupyter 所有的路径。

**Comment by forbxy** [comment]
因为我装插件从来没用过 --user模式,把装到用户目录的模式都给忘了.....，谢谢提醒。
用用户模式安装会导致共享python环境的其它用户取不到这些静态文件

**Comment by chfw** [comment]
我们是假设一个开发人员。你哪里是多个么？等知道你的具体用法 可以再想更好办法。

目前为止，解决问题有两个方法

1 用 online() , 这样pyecharts 会指向github里的静态文件
2 各个用户自己装一遍

**Comment by forbxy** [comment]
谢谢
我们这边conda环境的安装者和使用者不是一个用户，从而来限制用户装包。
1.用online确实是可以的，一开始用户报告错误我们就是这样处理的
2.其实这个问题的开始是我们准备把notebook所有插件都走CDN，然后我在conda环境的share目录下找不到pyecharts的静态文件。现在找到啦~~
