### ISSUE TITLE
notebook 静态文件请求地址错误

### ISSUE THREAD

**Issue by forbxy** [pyecharts/pyecharts#477]
notebook有个配置，可以让服务运行在子目录下 c.NotebookApp.base_url = '/my'，类似这样的，这么配的话所有服务都是绑定在/my/路由下的，包括static和nbextensions，(jupyterhub环境中notebook就是这样配的)。
所以程序在请求静态文件的时候应该考虑这个配置。变量Jupyter.notebook.base_url

**Comment by chfw** [comment]
忙完 pyecharts 0.5.0 再看看

**Comment by chfw** [comment]
pyecharts 1.0.0 将规避这个问题。其实你也知道了。
