### ISSUE TITLE
render生成的html文件，浏览器打开空白为何？？？

### ISSUE THREAD

**Issue by nealscut** [pyecharts/pyecharts#481]
render生成的html文件，浏览器打开空白为何？？？想把文件贴上来，但是不知道怎样弄
![default](https://user-images.githubusercontent.com/27132689/38463924-ec2c19a4-3b36-11e8-9b99-359a3eb1c502.PNG)

**Comment by chfw** [comment]
Chart with height 没有定义。你是用 pyecharts 做的吗？

**Comment by chfw** [comment]
<img width="496" alt="screen shot 2018-04-08 at 14 10 38" src="https://user-images.githubusercontent.com/4280312/38467917-aaab57c4-3b36-11e8-88fc-52a1b506c24a.png">

pyecharts 显示的 echarts id 是个大长条。而且很明显  style 里没有高度，宽度。

**Comment by nealscut** [comment]
真的，我用了字符串，不是数值，谢谢兄弟们
