### ISSUE TITLE
瀑布图存在问题

### ISSUE THREAD

**Issue by sysuxuhr** [pyecharts/pyecharts#485]
瀑布图存在问题，使用python3， pyecharts-0.4.1.tar.gz，
数据如下：
基准收益	0	                                      -0.008745277589830791
行业选择	-0.008745277589830791	-0.01889603606470769
股票配置	-0.02764131365453848	       -0.0012360801520094888
交叉影响	-0.02887739380654797	       -0.02057862110422337
残差 	-0.04945601491077134	         0.014321678382372527
基金收益	0	                                        -0.034954193093727603

图形如下：
![default](https://user-images.githubusercontent.com/38290682/38625378-ebba9b6e-3ddc-11e8-9f11-a0ccff019005.png)

在残差这一项不对，应从前一项下限作为起点，而不是以0做起点。

**Comment by chenjiandongx** [comment]
没看懂 :(

**Comment by sysuxuhr** [comment]
![brinson_result](https://user-images.githubusercontent.com/38290682/38775296-656722e4-40b1-11e8-863d-b4526da3c9b4.png)
这是我后来做的图，在残差这一项上不同，pyecharts的位置不对。这样清楚了吗？
