### ISSUE TITLE
Map地图不能显示

### ISSUE THREAD

**Issue by chengzhen123** [pyecharts/pyecharts#488]
### 提 issue 注意事项
0. 先仔细阅读文档中是否有关于您需要解决的问题的解决方法
1. 提 issue 前请先搜搜看以往的 issue 有没有解决了您的问题
2. 如若是不能正常使用的问题，请贴上详细的 pyecharts 版本，使用系统以及 Python 版本
3. 最好详细描述问题，必要时加上**代码+贴图**

**Comment by chengzhen123** [comment]
我已经通过以下代码下载了地图
pip install echarts-countries-pypkg
pip install echarts-china-provinces-pypkg
pip install echarts-china-cities-pypkg
但是我用教程总给出的例子，无法显示地图。

例子代码如下：
from pyecharts import Map
value = [155, 10, 66, 78]
attr = [u"福建", u"山东", u"北京", u"上海"]
map = Map(u"全国地图示例", width=1200, height=600)
map.add("", attr, value, maptype='china', is_label_show=True)
map.render(u'E:/pyecharts/map.html')

生成的map.html打开是空白的，什么也没有。
请问我应该怎么解决呢？

**Comment by chfw** [comment]
请告知你的 python 版本，pyecharts 版本，操作系统。

1、运行`pip freeze` 检查所装的pkg包。
2、画个 bar chart 试试

总的来说是 python 环境问题。

**Comment by chengzhen123** [comment]
win10系统，pyecharts的版本是0.4.1，操作系统windows
我用anconda的spyder和jupyter notebook都不能显示
但是我画bar是可以的

**Comment by chengzhen123** [comment]
python 是 2.7

**Comment by chengzhen123** [comment]
运行上面代码时候会报错： No such file or directory: 'C:\\Users\\chengzhen\\Anaconda2\\lib\\site-packages\\echarts_countries_pypkg\\resources\\registry.json'
再次运行上面代码，就不会报错，生成的html是不能显示地图的

**Comment by chfw** [comment]
我认为是Anaconda 下的虚拟环境和 python 全局环境弄出来的问题。

**Comment by chenjiandongx** [comment]
FIXED
