### ISSUE TITLE
Graph里面的symbol可以改变默认的颜色吗？

### ISSUE THREAD

**Issue by labosen** [pyecharts/pyecharts#489]
所用环境Mac，python2.7.14,pyecharts 0.4.1
使用pyecharts的Graph做关系图，symbol的颜色默认都是红色，无法更改，请问有可以改变symbol的颜色吗？
symbolSize虽然有参数，但是设置5和500，感觉绘制的图表没有变化
symbol形状可变，但是-------“？？？大小无法改变，颜色无法改变？？？”<--问题所在

<img width="261" alt="image" src="https://user-images.githubusercontent.com/32669736/38855958-a2dd9926-4257-11e8-8dd3-5b8d664a1081.png">

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/32669736/38856054-eec3b8d4-4257-11e8-94e9-1afa611f0e0d.png">

<img width="783" alt="image" src="https://user-images.githubusercontent.com/32669736/38856089-0b3f9dca-4258-11e8-9bb6-dbfb42f6ed08.png">

<img width="498" alt="image" src="https://user-images.githubusercontent.com/32669736/38856232-77ef01c2-4258-11e8-93db-17bee34987be.png">

**Comment by kinegratii** [comment]
pyecharts 不支持 [series[i]-graph.symbolSize](http://echarts.baidu.com/option.html#series-graph.symbolSize) 
可以使用 [series[i]-graph.data[i]](http://echarts.baidu.com/option.html#series-graph.data)

```
nodes: [{
    name: '1',
    x: 10,
    y: 10,
    value: 10
}, {
    name: '2',
    x: 100,
    y: 100,
    value: 20,
    symbolSize: 20,
    itemStyle: {
        color: 'red'
    }
}]
```

一个完整的例子

```
import networkx as nx
from networkx.readwrite import json_graph

from pyecharts import Graph

g = nx.Graph()

g.add_node('N1', name='Node 1', symbolSize=50)
g.add_node('N2', name='Node 2', symbolSize=20)
g.add_node('N3', name='Node 3', symbolSize=30)
g.add_edge('N1', 'N2')
g.add_edge('N1', 'N3')

g_data = json_graph.node_link_data(g)

print(g_data)

eg = Graph('设备最新拓扑图')
eg.add('Devices', nodes=g_data['nodes'], links=g_data['links'],)
print('symbolSize' in eg.options['series'][0])
# eg.show_config()
eg.render()
```
