### ISSUE TITLE
如何设置html上的图居中

### ISSUE THREAD

**Issue by chengzhen123** [pyecharts/pyecharts#491]
### 提 issue 注意事项
0. 先仔细阅读文档中是否有关于您需要解决的问题的解决方法
1. 提 issue 前请先搜搜看以往的 issue 有没有解决了您的问题
2. 如若是不能正常使用的问题，请贴上详细的 pyecharts 版本，使用系统以及 Python 版本
3. 最好详细描述问题，必要时加上**代码+贴图**

**Comment by chengzhen123** [comment]
render生成的html上的图总是靠左，请问如何让生成的图片居中？

**Comment by Zhenbin24** [comment]
你可以一给图外面加一个div，设置下样式。

**Comment by kinegratii** [comment]
@chengzhen123 

可以使用 **自定义模板** 的高级用法。pyecharts 默认使用内置 *simple_chart.html* 渲染单个图表，不含任何 css 。

simple_charts.html

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ chart.page_title }}</title>
    {{ echarts_js_dependencies(chart) }}
</head>
<body>
    {{ echarts_container(chart) }}
    {{ echarts_js_content(chart) }}
</body>
</html>
```
复制以上代码到同一目录下的 *my_bar_tpl.html* 并添加诸如 boostrap 的 css & js 代码，并在 Python 代码中指定使用这个模板。
```python
bar.render(path='render.html', template_name='my_bar_tpl.html')
```
参考
 - 例子： https://github.com/pyecharts/pyecharts-users-cases/tree/master/advance-usage
- 文档：http://pyecharts.org/#/zh-cn/api
