### ISSUE TITLE
Pip 10 compatibility issues

### ISSUE THREAD

**Issue by lipengyu** [pyecharts/pyecharts#492]
pip install pyecharts
………………………………
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/gm/r2k_qp3s35v53j9msmmzq27w0000gn/T/pip-install-0m_ddcew/jupyter-echarts-pypkg/setup.py", line 8, in <module>
        from pyecharts_jupyter_installer import install_cmd_for
    ModuleNotFoundError: No module named 'pyecharts_jupyter_installer'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gm/r2k_qp3s35v53j9msmmzq27w0000gn/T/pip-install-0m_ddcew/jupyter-echarts-pypkg/setup.py", line 13, in <module>
        pip.main(['install', 'pyecharts-jupyter-installer'])
    AttributeError: module 'pip' has no attribute 'main'

**Comment by haihuiyang** [comment]
I meet this issues too.
my python version is : 
```2.7.14```
pip version is : 
```pip 10.0.0 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip (python 2.7)```
Here is the error log:
```
pip install  pyecharts
Collecting pyecharts
  Using cached https://files.pythonhosted.org/packages/ea/db/e7a14152f5d44d11694f3acbaf55b4f6d40434e646a88fc89d29ea1d73eb/pyecharts-0.4.1.tar.gz
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pyecharts) (5.1.0)
Collecting jinja2 (from pyecharts)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting future (from pyecharts)
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting jupyter-echarts-pypkg==0.1.0 (from pyecharts)
  Using cached https://files.pythonhosted.org/packages/ed/1e/856f74b4a37637fdaa9abb7e6bdafd07b9f305fa0a07b8c46b58a0bf65d6/jupyter-echarts-pypkg-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/28/95c561zd0717v2zh_njmbg7m0000gn/T/pip-install-CIrOrp/jupyter-echarts-pypkg/setup.py", line 13, in <module>
        pip.main(['install', 'pyecharts-jupyter-installer'])
    AttributeError: 'module' object has no attribute 'main'
```

**Comment by chfw** [comment]
Please use pip 9.0.x for now while this problem is being looked at.

**Comment by kinegratii** [comment]
In pip 10, all API has moved to `pip._internal` , and that [`pip.__init__.py`](https://github.com/pypa/pip/blob/master/src/pip/__init__.py) only contains version info.
So use the following code to import origin `main` command.

```python

try:
    pip._internal import main
except ImportError:
    from pip import main
```

As the private module `_internal`, these code may not guaranteed and any change should be concerned.

**Comment by haihuiyang** [comment]
@chfw   when use pip with 9.0.1 has this bug:
```
➜  bin pip install requests
    Collecting requests
      Could not fetch URL https://pypi.python.org/simple/requests/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
      Could not find a version that satisfies the requirement requests (from versions: )
    No matching distribution found for requests
```
and then, I upgrade pip version to 10.0.0, and I when this Pip 10 compatibility issues
finally, I degrade pip to 9.0.3, it's success！anyway, thx～
degrade pip to 9.0.3 : ```pip install pip==9.0.3```

**Comment by chfw** [comment]
jupyter-echarts-pypkg 0.1.1 is released to fix this problem

**Comment by haihuiyang** [comment]
I think pip 10.0.1 fixed compatibility issues,this Here is my operation:
I upgrade pip to 10.0.1:
`➜  ~ pip -V
pip 10.0.1 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip (python 2.7)`
`pip install pyecharts` successful!
then I update jupyter-echarts-pypkg==0.1.1(`pip install -U jupyter-echarts-pypkg`), then `pip install pyecharts` I found this issue:
`pyecharts 0.4.1 has requirement jupyter-echarts-pypkg==0.1.0, but you'll have jupyter-echarts-pypkg 0.1.1 which is incompatible.`
@chfw

**Comment by chfw** [comment]
Will have to wait for pyecharts 0.5.0

**Comment by chfw** [comment]
![screen shot 2018-04-24 at 10 46 49](https://user-images.githubusercontent.com/4280312/39179707-d950dd6a-47ac-11e8-8721-3202bbad0399.png)

**Comment by haihuiyang** [comment]
ok,thx~

**Comment by chfw** [comment]
should be resolved now.
