### ISSUE TITLE
python3.6安装报错

### ISSUE THREAD

**Issue by rwfy2000** [pyecharts/pyecharts#499]
度娘找遍没找到解决办法，大神支支招吧。
python3.6 下安装报这个错：
![baidushurufa_2018-4-24_10-48-55](https://user-images.githubusercontent.com/38677579/39163459-2c2ca5dc-47ad-11e8-90af-e1c2c35c952c.png)

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts/issues/493
