### ISSUE TITLE
Jupyter Notebook - blank

### ISSUE THREAD

**Issue by peng-ye** [pyecharts/pyecharts#500]
I've read the Documents and related Issues, and tried re-installed pyecharts and checked the nbextension list, yet there is still nothing when I called the object in Jupyter Notebook (NoneType).
Will there be a solution for this issue in version 0.5.0?

**Comment by chenjiandongx** [comment]
show me your runtime environment

**Comment by chfw** [comment]
Package installation is incomplete. Please show us pip freeze
