### ISSUE TITLE
markline 标记点不显示标注

### ISSUE THREAD

**Issue by chenjiandongx** [pyecharts/pyecharts#504]
代码

```python
def test_line_user_define_markpoint():
    line = Line("折线图示例")
    line.add(
        "商家A",
        CLOTHES,
        clothes_v1,
        mark_point=["average", {"coord": ["裤子", 10], "name": "这是我想要的第一个标记点"}],
    )
    line.add(
        "商家B",
        CLOTHES,
        clothes_v2,
        is_smooth=True,
        mark_point=[{"coord": ["袜子", 80], "name": "这是我想要的第二个标记点"}],
    )
    line.render()
```

效果如图所示：

![image](https://user-images.githubusercontent.com/19553554/39237357-de64ab90-48ad-11e8-88b4-3baa58d759b7.png)

修复后效果：

![image](https://user-images.githubusercontent.com/19553554/39237379-ef17b50e-48ad-11e8-8952-66b1a8b653c8.png)

**Comment by chenjiandongx** [comment]
FIXED

**Comment by Megattron** [comment]
Markpoint显示的X轴的值有偏差
使用的也是上面的代码，pyecharts版本是v0.5.3  
![2018-05-14 7 01 13 1](https://user-images.githubusercontent.com/17977562/39993706-509c8ba6-57a9-11e8-9883-845ff251695c.png)
这里商家A的max值期望应该是“衬衫”
btw，在另外的使用中，x轴的值为数值的时候，也没能正常显示（期望是具体值，实际显示0），还望指导一下如何使用，感谢
