### ISSUE TITLE
Polar图的radius参数问题

### ISSUE THREAD

**Issue by lyq1250** [pyecharts/pyecharts#507]
数据从excel读取成dataframe，再转成list，无法正确传入radius参数中
代码如下:
data_txt = [i[0] for i in data[['列名']].values]
radius = [data_txt]

**Comment by chenjiandongx** [comment]
![screenshot-pyecharts org-2018 04 27-19-58-52](https://user-images.githubusercontent.com/19553554/39361524-7d1bd328-4a55-11e8-8cb1-eb865c1371b5.png)

**Comment by chenjiandongx** [comment]
```python
data_txt = [float(i[0]) for i in data[['列名']].values]
```
试试

**Comment by chfw** [comment]
用我的 [pyexcel](https://github.com/pyexcel/pyexcel) 就直接是 list

**Comment by chenjiandongx** [comment]
那你就处理成像示例中的一样的数据格式试试看

**Comment by lyq1250** [comment]
求如何实现

**Comment by chenjiandongx** [comment]
```data_txt = [str(i[0]) for i in data[['列名']].values]``` ?

**Comment by lyq1250** [comment]
还是不行 @chenjiandongx

**Comment by chenjiandongx** [comment]
那你试试去了换行符试试看咯
