### ISSUE TITLE
可以切换成dark主题么？

### ISSUE THREAD

**Issue by bty2000** [pyecharts/pyecharts#512]
pyecharts能否切换成dark主题？

**Comment by kinegratii** [comment]
目前暂不支持，可期待后续的版本。

**Comment by chfw** [comment]
![screen shot 2018-05-01 at 16 28 43](https://user-images.githubusercontent.com/4280312/39479322-d421f166-4d5c-11e8-8854-58fe5fd1ff58.png)

@chenjiandongx , with 'dark' theme, the rest of the chart does not change color but the axises got white colors, hence they do not appear in white backgroud...

**Comment by chfw** [comment]
```
# coding=utf-8
from __future__ import unicode_literals

from pyecharts import Scatter


v1 = [10, 20, 30, 40, 50, 60]
v2 = [10, 20, 30, 40, 50, 60]

scatter = Scatter("散点图示例")
scatter.use_dark_theme()  # <-----
scatter.add("A", v1, v2)
scatter.add("B", v1[::-1], v2)
scatter.render()
```
output:

![screen shot 2018-05-01 at 22 43 58](https://user-images.githubusercontent.com/4280312/39495184-35f2e056-4d91-11e8-81b8-c560041fb690.png)

**Comment by kinegratii** [comment]
*dark* is one of themes.So it should not  use `use_dark_theme` to set theme.

```
scatter.use_theme('dark')
# scatter.use_theme('vintage')
```

See more at http://echarts.baidu.com/download-theme.html

**Comment by chfw** [comment]
```
from pyecharts import configure

configure(global_theme='dark')
```

![screen shot 2018-05-02 at 15 39 53](https://user-images.githubusercontent.com/4280312/39529740-4e57db68-4e1f-11e8-8830-1d05e4fdc826.png)

**Comment by chfw** [comment]
let's build one `echarts-themes-pypkg`, which includes 5 more additional themes?

![screen shot 2018-05-02 at 15 43 56](https://user-images.githubusercontent.com/4280312/39529903-af4f4776-4e1f-11e8-9cc6-1f814511fac5.png)

**Comment by chenjiandongx** [comment]
@chfw it will be a awesome feature

**Comment by chfw** [comment]
Cannot believe my eyes. pyecharts have 6 more beautiful themes

## vintage:

![screen shot 2018-05-03 at 00 10 06](https://user-images.githubusercontent.com/4280312/39553641-8e54c766-4e66-11e8-9156-5b8fa13cb9f9.png)

## macarons:

![screen shot 2018-05-03 at 00 13 12](https://user-images.githubusercontent.com/4280312/39553690-cc3adffc-4e66-11e8-8423-eb39b5216329.png)

## infographic
![screen shot 2018-05-03 at 00 13 59](https://user-images.githubusercontent.com/4280312/39553714-eb2e7d74-4e66-11e8-9985-0bb3f5dd6f57.png)

## shine:

![screen shot 2018-05-03 at 00 14 59](https://user-images.githubusercontent.com/4280312/39553751-0f360778-4e67-11e8-8eea-0c2d6e3b91d9.png)


## roma:

![screen shot 2018-05-03 at 00 17 27](https://user-images.githubusercontent.com/4280312/39553828-656680fa-4e67-11e8-8c3c-ff4ec71fb4db.png)

coffee! coffee! please :)

**Comment by bty2000** [comment]
@chfw  why i can only use "dark" theme, other themes dont work?

**Comment by chfw** [comment]
`pip install echarts-themes-pypkg`
