### ISSUE TITLE
visual regression - split line on xaxis is visible

### ISSUE THREAD

**Issue by chfw** [pyecharts/pyecharts#516]
![screen shot 2018-04-28 at 22 01 03](https://user-images.githubusercontent.com/4280312/39400829-c648b644-4b2f-11e8-9ece-bb25da231777.png)

**Comment by chenjiandongx** [comment]
散点图的呢？

#### 现在效果
![image](https://user-images.githubusercontent.com/19553554/39472440-db0c7504-4d7b-11e8-9c83-28429b7efbe8.png)

#### 原先效果
![image](https://user-images.githubusercontent.com/19553554/39472447-decf41f8-4d7b-11e8-8455-2bb37957ef45.png)
