### ISSUE TITLE
关于区县一级的重名问题

### ISSUE THREAD

**Issue by DQinYuan** [pyecharts/pyecharts#521]
我发现在中国有很多重名的区县，比如在重庆市有一个双桥区，在承德市也有一个双桥区，但是在pyecharts的经纬度数据中（pyecharts/pyecharts/datasets/city_coordinates.json），仅仅依靠区县名作为key就能得到一个经纬度，这样是不是不够准确，是不是用 市+区 作为key更加准确一点？

**Comment by chfw** [comment]
是的。福州市鼓楼区, 开封市鼓楼区.

https://github.com/echarts-maps/echarts-china-counties-js

**Comment by kinegratii** [comment]
由于 区划名称 和 行政区划变更 等原因，pyecharts 在 *城市地理数据* 维护方面可能存在不准确、滞后等现象。

**因此在使用这些数据时，应当使用 pyecharts 提供的 API 查询是否含有你所使用的城市数据，并确保正确性。如果没有请自行添加。**
```shell
>>>from pyecharts.datasets.coordinates import search_coordinates_by_keyword
>>>print(search_coordinates_by_keyword('鼓楼区'))
{'鼓楼区': [119.3, 26.08]}
```
画图

```python
from pyecharts import Geo

data = [('祥符区', 45), ('鼓楼区', 35)]
attr, value = geo.cast(data)

geo = Geo('PM 2.5')

geo.add_coordinate('鼓楼区', 114.354723, 34.795234) # 该数据仅在 geo 这个对象有效

geo.add('PM 2.5指数', attr, value, maptype='开封')
```

**Comment by chfw** [comment]
@DQinYuan 你也可以帮大家改
