### ISSUE TITLE
绘制饼图出来的结果，不显示百分比

### ISSUE THREAD

**Issue by Monarch1995** [pyecharts/pyecharts#523]
from pyecharts import Pie

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [11, 12, 13, 10, 10, 10]
pie = Pie("饼图示例")
pie.add("", attr, v1, is_label_show=True)
pie.render()

![360 20180502141627735](https://user-images.githubusercontent.com/26194796/39508146-edd3e9cc-4e13-11e8-9ab6-15f84a560f50.jpg)

**Comment by Monarch1995** [comment]
@chenjiandongx

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/39514658-6c785798-4e2a-11e8-9b52-5e0fd36da0b3.png)

**Comment by chenjiandongx** [comment]
http://pyecharts.org/#/zh-cn/charts?id=%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE%E9%A1%B9
