### ISSUE TITLE
能增加列表功能吗

### ISSUE THREAD

**Issue by Michaelguangg** [pyecharts/pyecharts#524]
有的时候表和图能更加清晰的展示我们的结果，我找了下好像暂时还没有能插入表的功能，所以请问以后是不是会考虑增加漂亮的表的功能呢？

**Comment by chenjiandongx** [comment]
推荐使用 https://github.com/pyexcel/pyexcel @chfw ，来，介绍一下

**Comment by chfw** [comment]
@chenjiandongx ，谢谢提供舞台。

你可以考虑用 pyexcel + pyexcel-handsontable:

![screen shot 2018-05-02 at 16 01 52](https://user-images.githubusercontent.com/4280312/39531038-2d9d2ae2-4e22-11e8-8700-1a287421a5d6.png)

https://github.com/pyexcel-renderers/pyexcel-handsontable

等 pyecharts 这成熟一些， pyexcel-echarts 也是将要出炉的项目：
http://pyexcel-echarts.readthedocs.io/en/latest/charts.html

![screen shot 2018-05-02 at 16 06 07](https://user-images.githubusercontent.com/4280312/39531304-c4d53e86-4e22-11e8-8144-c400115820ee.png)

有具体要求可以提！！
