### ISSUE TITLE
Flask 显示多张图

### ISSUE THREAD

**Issue by bty2000** [pyecharts/pyecharts#529]
Flask框架是否支持单页面多图标显示？thanks!

**Comment by chfw** [comment]
你试过了没有呢？

**Comment by bty2000** [comment]
试过的，提示：AttributeError: 'Page' object has no attribute 'chart_id'
代码如下：
@app.route("/")
def heatmap():
    hm = create_heatmap()
    return render_template('heatmap.html', hm=hm)

def create_heatmap():
	influxETL = InfluxETL()
	page = Page()
	for i in range(len(tags)):
		B_count, B_name = influxETL.query('count', 'name', 'GEM_BCM_LV1', time_window(10), arrow.now())
		bar = Bar("GEM_BCM_LV1",width=450,height=300)
		bar.add("defect delay", B_name, B_count,is_stack=True,bar_category_gap="80%")
	page.add(bar)
	return page
