### ISSUE TITLE
Geo的effectScatter效果鼠标悬停时展示的是纬度，能否优化直接展示设置数据，而不是纬度。

### ISSUE THREAD

**Issue by leilei1881** [pyecharts/pyecharts#547]
1、版本：pyecharts (0.4.1) ，win10 64bit，python3.6.0 64bit
2、代码：
`from pyecharts import Geo

data = [
    ("海门", 9), ("鄂尔多斯", 12), ("招远", 12),
    ("舟山", 12), ("齐齐哈尔", 14), ("盐城", 15)
    ]
geo = Geo("全国主要城市空气质量", "data from pm2.5", title_color="#fff",
          title_pos="center", width=1200,
          height=600, background_color='#404a59')
attr, value = geo.cast(data)
geo.add("", attr, value, type="effectScatter", is_random=True, effect_scale=5)
geo.render(r"e:\my_first_chart.html")`
3、jupyter展示效果：
![default](https://user-images.githubusercontent.com/39149870/39857183-fe2fd9c8-5464-11e8-836d-e34f49b88e6f.png)
4、如果优化Map的展示，增加Geo的effectScatter效果也可以。

**Comment by leilei1881** [comment]
咨询了Mahone_Huang大神后，在0.5.2版本里采用JavaScript 回调函数的方法解决了，图中标记绿色数据的展示，但是标记为红色部分的数字还没有找到好的解决办法，继续关注中。

**Comment by chaoshengt** [comment]
@leilei1881 如何用回调方法解决的呀？：）

**Comment by leilei1881** [comment]
@chaoshengt 采用0.5.2版本的pyecharts就行。

**Comment by chenjiandongx** [comment]
@leilei1881 This is for you

**code**
```python
def formatter_for_tootip(params):
    return params.name + ": " + params.value[2]

def test_geo_china_effectscatter():
    data = [
        ("海门", 9),
        ("鄂尔多斯", 12),
        ("招远", 12),
        ("舟山", 12),
        ("齐齐哈尔", 14),
        ("盐城", 15),
    ]
    geo = Geo("全国主要城市空气质量", "data from pm2.5", **style.init_style)
    attr, value = geo.cast(data)
    geo.add(
        "", attr, value, type="effectScatter", is_random=True, 
        effect_scale=5, tooltip_formatter=formatter_for_tootip, label_formatter="{b}"
    )
    geo.render()
```
**render chart**

![image](https://user-images.githubusercontent.com/19553554/40044356-b48505fc-5859-11e8-9e34-606929d793e2.png)

**Comment by leilei1881** [comment]
@chenjiandongx 谢谢，确实是想要的效果。确认可以关闭此贴。
