### ISSUE TITLE
Geo下使用type='heatmap',时lab消失问题

### ISSUE THREAD

**Issue by chaoshengt** [pyecharts/pyecharts#552]
`geo = Geo("主要城市空气质量", "data from pm2.5", title_color="NavajoWhite",
          title_pos="center", width=1200,
          height=600, background_color='Azure')
attr, value = geo.cast(data)
        
geo.add("", attr,  value, maptype = '河南',visual_range=[0, 200],  geo_normal_color='White',
        #visual_text_color="Yellow", 
        border_color='Grey',is_label_show=True,
        label_text_color='Blue', 
        label_formatter='{b}',
        tooltip_background_color='Green',
        type='heatmap',
        #label_formatter='{b},\n {c}',##既显示地名又显示数值
        #legend_text_color="#eee",
        symbol_size=15, is_visualmap=True)
geo`
如题，当type为默认值是，有地名，
![1](https://user-images.githubusercontent.com/7035642/39956232-fd29ca88-560e-11e8-8a18-c99b3a8401d1.png)

当type='heatmap',时，地名标签消失，
![2](https://user-images.githubusercontent.com/7035642/39956234-049fa2ce-560f-11e8-99ab-929923518818.png)

有什么办法显示地名呢？
PS:显示地名即可，发现鼠标放在地图上时，可以显示地名，怎么能默认直接显示呢？如图
![3](https://user-images.githubusercontent.com/7035642/39956254-597b8394-560f-11e8-8e4b-9455cac09708.png)

谢谢大佬：）

**Comment by chenjiandongx** [comment]
is_label_show=True?

**Comment by chaoshengt** [comment]
@chenjiandongx  感谢关注！：）
`is_label_show=True`是设置过的，代码如下，可以直接运行一下，type='heatmap'时,lab不显示，type是其他模式时，lab是显示的。
`%matplotlib inline

from pyecharts import Geo




data = [("洛阳市", 134),  ("开封市", 136),("郑州市", 200),("新乡市", 147),('许昌市', 148),("漯河市", 152),("南阳市", 153),
    ("鹤壁市", 154),("安阳市", 157),("信阳市", 169),("驻马店市", 175),("三门峡市", 177),("邓州市", 193),
    ("济源市", 194),("商丘市", 229),("周口市", 273),("平顶山市", 279), ('濮阳市', 122),('焦作市', 122)]


geo = Geo("主要城市空气质量", "data from pm2.5", title_color="Black",
          title_pos="center", width=1200,
          height=600, background_color='Azure')
attr, value = geo.cast(data)
        
geo.add("", attr,  value, maptype = '河南',visual_range=[0, 500],  geo_normal_color='White',
        #visual_text_color="Yellow", 
        border_color='Grey',
        label_text_color='Blue', 
        label_formatter='{b}',
        tooltip_background_color='Green',
         type='heatmap',
        is_label_show=True,
        symbol_size=15, 
        is_visualmap=True)
geo`

**Comment by chenjiandongx** [comment]
好像确实这样 请问能不能找个 Echarts heatmap 有显示 label 的示例给我看下 我对比一下参数配置项

**Comment by chaoshengt** [comment]
@chenjiandongx 还真没找到，不过，我发现，当把鼠标放在地图上时，可以显示地名，怎么能设置不用鼠标悬停在地图上，就直接把地名显示出来呢，这样也可以解决问题，如下图：
![1](https://user-images.githubusercontent.com/7035642/39976235-36095a74-5765-11e8-891f-7f81bd84198b.png)

**Comment by chenjiandongx** [comment]
这个好像没办法这样操作
