### ISSUE TITLE
请问能不能实现map+bar的效果，比如这种

### ISSUE THREAD

**Issue by WotaWang** [pyecharts/pyecharts#553]
![6a8aefc79135c5b59f58fb8e5c6fdadc_hd](https://user-images.githubusercontent.com/31446914/39960326-738c6f34-5653-11e8-8132-6d55d73204d5.jpg)

**Comment by Wotamin** [comment]
还有一个小问题就是 Geo 能不能添加一个标记大小随数值大小变化的参数，现在要实现这样的性质只能自己写一个循环

**Comment by chenjiandongx** [comment]
请给出这张图来源好查看它的配置项
