### ISSUE TITLE
jupyter notebook Polar blank

### ISSUE THREAD

**Issue by JoyBeginner** [pyecharts/pyecharts#555]
1. 代码使用示例代码
2. 使用render方法得到的html文件在浏览器中显示也是空白
3. 其余示例没有出现这样的显示问题

#### 相关配置信息:
- **pyecharts** :
    pyecharts                          **0.5.3**                  
    pyecharts-javascripthon            **0.0.5**                    
    pyecharts-jupyter-installer       **0.0.3**   
    jupyter-echarts-pypkg              **0.1.1**
- **OS** :
    ubuntu
- **jupyter** :
    **4.4.0**
- **Python** :
    **2.7**

#### 图示
![screenshot from 2018-05-13 19-52-54](https://user-images.githubusercontent.com/26475063/39967026-72e0a6c4-56e7-11e8-9bef-95205ac52fa6.png)

**Comment by chfw** [comment]
Please have a look at other closed issues related to blank page. It is likely that jupyter-echarts is not installed properly.
https://github.com/pyecharts/pyecharts/issues/503

**Comment by JoyBeginner** [comment]
**Thanks** for your comment!
- Here is the **list info** :

**jupyter-nbextension list**


Known nbextensions:
  config dir:XX/.jupyter/nbconfig
    notebook section
      **echarts/main**  enabled 
      - Validating: OK

I wonder **whether** this can be considered as **installed properly**
Plus :
I **checked** the issues existed before I open this issue but it seems nothing like the problem I am faced with.**Thanks** again!

**Comment by chfw** [comment]
请按这个顺序排查问题：

1）检查这个链接能拿到 echarts.min.js 么？ http://localhost:8888/nbextensions/echarts/echarts.min.js

如果不能，请检查 jupyter-echarts-pypkg 是否装好？在确认你已经装了 jupyter 的情况下，可以卸载 jupyter-echarts-pypkg 然后再装一遍。然后运行 jupyter notebook，再次查看 1）能拿到 echarts.min.js 么？

如果能，请用鼠标右击输出的空白区域，在跳出的菜单处，点击 inspect 。在发展人员窗口里，请抓图 <script>...</script> 的区域.

例子：

<img width="597" alt="screen shot 2017-08-16 at 09 17 29" src="https://user-images.githubusercontent.com/4280312/29354092-4c4eecee-8264-11e7-98bb-06ec1b4c06b6.png">

**Comment by JoyBeginner** [comment]
感谢回复!

- 链接结果 : **能**拿到echarts.main.js(图1)
- 开发人员窗口得到**type error : o is not defined**(图2)
    - error窗口下提示文件位置(图3 图4)
图示 : 
    - 图1
![screenshot from 2018-05-14 09-36-53](https://user-images.githubusercontent.com/26475063/39974327-a55dd0fe-575a-11e8-8e81-51e3d406ee62.png)
    - 图2
![screenshot from 2018-05-14 09-43-34](https://user-images.githubusercontent.com/26475063/39974525-0493ff5c-575c-11e8-8c66-e832d4ab04a1.png)
    - 图3
![screenshot from 2018-05-14 09-51-37](https://user-images.githubusercontent.com/26475063/39975520-ad98dfaa-5761-11e8-9ee9-fef56c16c79f.png)
    - 图4
![screenshot from 2018-05-14 09-51-48](https://user-images.githubusercontent.com/26475063/39975527-b6ee0148-5761-11e8-95e9-1e837be12426.png)

**Comment by JoyBeginner** [comment]
增详细错误位置**图示** :
![screenshot from 2018-05-14 14-35-13](https://user-images.githubusercontent.com/26475063/39981701-40c18e72-5784-11e8-8940-aa79d9c2fe97.png)

**Comment by chenjiandongx** [comment]
我这边也确实出现这个问题

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/39983768-647da452-578b-11e8-9a4d-4533449d950e.png)

问题已经找到，会尽快修复的

**Comment by JoyBeginner** [comment]
Wow!!!
