### ISSUE TITLE
横坐标显示问题

### ISSUE THREAD

**Issue by xiaomintongxue** [pyecharts/pyecharts#560]
横轴按理应该有10个标签，但是没法显示，只显示了5个，怎么回事？如图。
![1](https://user-images.githubusercontent.com/18399572/40005422-7b383218-57ca-11e8-90f5-4eba9102912f.png)

**Comment by chfw** [comment]
increase width.

**Comment by xiaomintongxue** [comment]
具体详细的代码可否示意？刚接触不熟悉，非常感谢。


| |
小江
邮箱：jms_pursuit@163.com
|

签名由 网易邮箱大师 定制

在2018年05月14日 23:17，jaska 写道：

increase width.

**Comment by xiaomintongxue** [comment]
另外标签文字可否由横向改为竖直方向？


| |
小江
邮箱：jms_pursuit@163.com
|

签名由 网易邮箱大师 定制

在2018年05月14日 23:17，jaska 写道：

increase width.

**Comment by chenjiandongx** [comment]
显示不了全部是因为标签名太长，Echarts 默认省略。

可以自己调整 x 轴标签角度，具体查看 http://pyecharts.org/#/zh-cn/charts 通用配置项关于 X 轴部分

**Comment by xiaomintongxue** [comment]
非常感谢，已经查看文档解决了。




| |
小江
邮箱：jms_pursuit@163.com
|

签名由 网易邮箱大师 定制

在2018年05月15日 16:09，陈键冬 写道：

Closed #560.
