### ISSUE TITLE
与geo相关的 No coordinate is specified

### ISSUE THREAD

**Issue by thefullhorizon** [pyecharts/pyecharts#568]
你好 已经按照（geo的坐标 not found 问题 #152）做了设置 但问题还依然存在，请帮忙看下问题
环境：Win10 + Pycharm + python 2.7 + pyecharts0.5.4
代码：
data = [
    ("Hainan", 9),("Shanghai", 12)]
geo = Geo("main cities air quality ", "data from pm2.5", title_color="#fff", title_pos="center", width=1200, height=600, background_color = '#404a59')
attr, value = geo.cast(data)
geo.add("", attr, value, visual_range=[0, 200], visual_text_color="#fff", symbol_size=15, is_visualmap=True)
geo.show_config()
geo.render(render_address)
错误堆栈：
Traceback (most recent call last):
  File "E:/Workspace/Pycharm/pythonlearning/visualization/pyechart_demo.py", line 25, in <module>
    geo.add("", attr, value, visual_range=[0, 200], visual_text_color="#fff", symbol_size=15, is_visualmap=True)
  File "D:\Install\PyCharm\Environment\vir_2.7\lib\site-packages\pyecharts\charts\geo.py", line 47, in add
    self.__add(*args, **kwargs)
  File "D:\Install\PyCharm\Environment\vir_2.7\lib\site-packages\pyecharts\charts\geo.py", line 103, in __add
    _coordinate = self.get_coordinate(_name, raise_exception=True)
  File "D:\Install\PyCharm\Environment\vir_2.7\lib\site-packages\pyecharts\charts\geo.py", line 42, in get_coordinate
    raise ValueError("No coordinate is specified for {}".format(name))
ValueError: No coordinate is specified for Hainan

**Comment by kinegratii** [comment]
正如 trace 所述，pyecharts 默认没有提供城市名称为 “Hainan” 的地理数据，因此在使用过程中会导致异常。
可以自行添加数据，如： 

```
geo.add_coordinate("Hainan", 119.3, 26.08) # 数据仅供示例
```

**Comment by thefullhorizon** [comment]
按照您的回复，追加上Hainan的地理数据信息，重新运行之后，堆栈信息跟之前一摸一样。是这里还要做其他什么操作吗？

**Comment by chfw** [comment]
加上之后就直接用 没有其他操作了

**Comment by chfw** [comment]
当然你可以给提PR 补齐

**Comment by thefullhorizon** [comment]
hello chfw
我的意思是加上geo.add_coordinate("Hainan", 119.3, 26.08) 之后依然报No coordinate is specified for Hainan 这样的错误。
