### ISSUE TITLE
Map/Geo类型无法显示

### ISSUE THREAD

**Issue by hcwang** [pyecharts/pyecharts#571]
在按照[地图自定义篇](http://pyecharts.org/#/zh-cn/customize_map)中安装了全国地图数据包之后，仍然无法显示出地图，尝试了在Jupyter Notebook以及Flask中应用中调用。其中在后者仅显示出“南海诸岛”的图例。

> pip install echarts-china-provinces-pypkg

> from pyecharts import Map
> value = [155, 10, 66, 78, 33, 80, 190, 53, 49.6]
> attr = [
>     "福建", "山东", "北京", "上海", "甘肃", "新疆", "河南", "广西", "西藏"]
> map = Map("Map 结合 VisualMap 示例", width=1200, height=600)
> map.add("", attr, value, maptype='china', is_visualmap=True,
>         visual_text_color='#000')
> map.render()

**Comment by chfw** [comment]
请看 http://pyecharts.org/#/zh-cn/faq
