### ISSUE TITLE
HeatMap中纵坐标显示索引值，而非raw data

### ISSUE THREAD

**Issue by hcwang** [pyecharts/pyecharts#572]
在HeatMap中，使用以下代码进行测试，无论是在Jupyter Notebook还是在Flask应用中，所显示的纵坐标都是其索引值，即0,1,2,3,4,5,6，而不是'Saturday','Friday'字样。

> import random

> from pyecharts import HeatMap
> 
> x_axis = [
>     "12a", "1a", "2a", "3a", "4a", "5a", "6a", "7a", "8a", "9a", "10a", "11a",
>     "12p", "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p", "10p", "11p"]
> y_axis = [
>     "Saturday", "Friday", "Thursday", "Wednesday", "Tuesday", "Monday", "Sunday"]
> data = [[i, j, random.randint(0, 50)] for i in range(24) for j in range(7)]
> heatmap = HeatMap()
> heatmap.add("热力图直角坐标系", x_axis, y_axis, data, is_visualmap=True,
>             visual_text_color="#000", visual_orient='horizontal')
> heatmap.render()

**Comment by chfw** [comment]
pip install --upgrade pyecharts-javascription

**Comment by chenjiandongx** [comment]
版本已更新，修复该问题了。

**Comment by hunterbobo** [comment]
为什么我用的V0.5.9的版本，heatmap的y轴还是显示索引值，x轴是正常的，很奇怪

**Comment by chenghuige** [comment]
> 最新版了，Y轴还是索引值

实验也还是索引值 0.5.11

**Comment by YanNIU2028** [comment]
这个bug在0.5.11里还在，求修复，感谢

**Comment by CN4everxx** [comment]
> 这个bug在0.5.11里还在，求修复，感谢

可以参考这里进行本地修复。

https://github.com/pyecharts/pyecharts/pull/843

**Comment by nicknamehenry** [comment]
请问有pyecharts的QQ或者微信讨论群吗？
