### ISSUE TITLE
新增对 nteract 的支持

### ISSUE THREAD

**Issue by chenjiandongx** [pyecharts/pyecharts#573]

**Comment by chenjiandongx** [comment]
![image_182](https://user-images.githubusercontent.com/19553554/40266807-2c3ddcc2-5b84-11e8-8240-d3398243d4a6.png)

**Comment by chfw** [comment]
再来一个

**Comment by chfw** [comment]
我注意到地图扩展在html的展现形式下还有问题。如果输出图片呢，nteract 是可以展现任何地图的

**Comment by Fankbai** [comment]
@chenjiandongx  每次打开nteract后图像均因为没有缓存而显示空白。能否将生成的图像同时渲染出对应的js保存到本地，下次打开时自动加载。

**Comment by chfw** [comment]
能，但需要时间。如果Pyecharts 能提供 nteract plugin 是可以实现本地有js的。现在用的是 online 模式，通过http的方式获取 js 库
