### ISSUE TITLE
请问jupyter nbextension list中出现 problem

### ISSUE THREAD

**Issue by ch812248495** [pyecharts/pyecharts#580]
**问题**
安装 pyecharts 之后,使用jupyter nbextension list验证环境,结果如下:

Known nbextensions:
  config dir: /Users/ch/.jupyter/nbconfig
    notebook section
      echarts/main  enabled 
      - Validating: problems found:
        - require?  X echarts/main
  config dir: /Users/ch/PycharmProjects/test/venv/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
![image](https://user-images.githubusercontent.com/26186461/40305409-0d6ba27a-5d2d-11e8-936d-183bd6f32861.png)

是不是缺少了 echarts 文件? 我已经多次重装环境都是这个结果,这是我在 jupyter notebook 中图片显示空白的原因吗?(但是生成 html 的文件并没有问题),应该怎么解决呢?

**运行环境（系统环境及 pyecharts 版本）**
Mac os
pyechars 为 pip 安装,应该是最新版
python2.7和3.5都试过,都有这个问题存在

**代码及截图**

**Comment by chenjiandongx** [comment]
重装 notebook -> 重装 pyecharts 没有效果吗？

**Comment by ch812248495** [comment]
我放了两天 jupyter notebook 就突然可以显示图表了...
而且是同一个 session 下, 一个 ipynb可以,另一个就不行了...
还有就是某几种图片显示不出来,比如词云和某个省的地图(但是我使用 flask 和生成 html 图表这两种方法还是没有问题的,我后来用 flask 来做展示了)
总之就是很玄学, 感觉 jupyter 的支持还是有一些不稳定, 可能是对我的电脑而言吧...

**Comment by chfw** [comment]
Jupyter 估计是共享了 data 目录
