### ISSUE TITLE
目前暂不支持jupyterlab吗？

### ISSUE THREAD

**Issue by anyang001** [pyecharts/pyecharts#581]
**问题**
目前暂不支持jupyterlab吗？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![1](https://user-images.githubusercontent.com/31056083/40307219-311f404e-5d34-11e8-81ee-d33532a9f995.png)

**Comment by chfw** [comment]
是的，还不支持。

暂时的解决方案是这个：

如果你在你的代码前面运行这个，就能画出来：

```
from pyecharts import configure

configure(output_image='png')

```

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts/issues/351
