### ISSUE TITLE
Request for Treemap

### ISSUE THREAD

**Issue by plartoo** [pyecharts/pyecharts#582]
First of all, among all the visualization tools I've looked at, ECharts stands out as being the best. Thank you very much for your hard work porting it into Python!

This is not a bug report, but more of a request. ECharts now has 'Treepmap' visualization and I'm wondering if pyecharts team is planning to add that in the near future. Thank you.

**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chenjiandongx** [comment]
#669

**Comment by chenjiandongx** [comment]
请更新到 v0.5.8 使用树图。
