### ISSUE TITLE
pyinstaller打包单文件后运行在import jupyter-echarts-pypkg包时失败

### ISSUE THREAD

**Issue by pathing** [pyecharts/pyecharts#584]
**问题**
根据FAQ里面的提示，我把get_resource_dir()中__file__修改为sys.argv[0]后，可以pyinstaller打包并运行，但是pyinstaller打包单文件后生成的html没有加载到js文件。从log打印上看，是在do_import()  jupyter-echarts-pypkg这个包时failed：failed to import jupyter-echarts-pypkg。请问有解决方法么

**运行环境（系统环境及 pyecharts 版本）**
系统：win7 64bit
python：3.4
pyecharts：0.5.5

**代码及截图**
![image](https://user-images.githubusercontent.com/11513848/40363216-75fdb740-5e01-11e8-8d9e-8c39d526980f.png)

**Comment by pathing** [comment]
暂时解决了，希望贵团队后续可以支持pyinstaller打包

**Comment by bulalala** [comment]
> 暂时解决了，希望贵团队后续可以支持pyinstaller打包

请问你是如何解决的，我也同样遇到打包后无法运行的问题

**Comment by chfw** [comment]
pyecharts 1.0.0 将不需要这个包了。
