### ISSUE TITLE
请问graph最多支持多少个nodes?

### ISSUE THREAD

**Issue by alohau** [pyecharts/pyecharts#585]
超过2500个点后就浏览器就画不出来了

**Comment by chenjiandongx** [comment]
这个没测试过

**Comment by kinegratii** [comment]
该特性和运行环境有关（如浏览器、电脑内存等），请参考 ECharts 相关文档。

**Comment by iry-lee** [comment]
我刚刚跑了一个4000+点的正常啊

**Comment by chfw** [comment]
computer hard settings please?

**Comment by iry-lee** [comment]
you mean win10 8G RAM i5-8250U? or Python3.6 in Pycharm 2018.1.4?
I use more than 4000 nodes to generate a graph, the render.html only spend 1980KB. So I think problem may not in hardware.
I have some problem before, I thought maybe too much nodes. 
But finally, it sames to be some identical elements in nodes[].
