### ISSUE TITLE
箱型图的画法有异议，没有显示异常点。

### ISSUE THREAD

**Issue by LittleWhite-Carry** [pyecharts/pyecharts#586]
**问题**
箱型图的画法有异议。matlab的箱型图和pandas的箱型图都是带有异常点的。这个并没有显示异常点。不知道是刻意设置还是有什么问题。

**运行环境（系统环境及 pyecharts 版本）**
windows10    python3.5    pycharts0.5.6

**代码及截图**

**Comment by chenjiandongx** [comment]
这个只是遵循 Echarts 的画法，可能是 Echarts 没有吧

**Comment by chenjiandongx** [comment]
Echarts 没有的话 pyecharts 也没办法实现。
