### ISSUE TITLE
轴上标签字体过大，导致字体显示不完全

### ISSUE THREAD

**Issue by JingChunzhen** [pyecharts/pyecharts#587]
**问题**
pyecharts  画图 轴上标签字体过大，导致显示不完全， 这个问题要如何解决呢？ 多谢

**运行环境（系统环境及 pyecharts 版本）**
ubuntu16.04
pyecharts (0.3.1)

**截图**
![echarts](https://user-images.githubusercontent.com/17619609/40817949-5d03249a-6587-11e8-8f88-392ad808431e.png)

**Comment by alohau** [comment]
你可以设置一下画布的大小，我之前出现过显示不全的情况但是也显示的七八个字母~

在 2018-06-01 10:36:37，"JCZ" <notifications@github.com> 写道：


问题
pyecharts 画图 轴上标签字体过大，导致显示不完全， 这个问题要如何解决呢？ 多谢

运行环境（系统环境及 pyecharts 版本）
ubuntu16.04
pyecharts (0.3.1)

截图

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/40841868-89566014-65de-11e8-83db-93b0ccdd2b73.png)

**Comment by JingChunzhen** [comment]
这个问题现在已经解决了，可以在生成的html上修改代码
调整grid参数
`"grid": [
        {
            "bottom": "35%"
        },
        {
            "bottom": "35%"
        },
        {
            "bottom": "35%"
        }
    ],`
![barthank](https://user-images.githubusercontent.com/17619609/40877825-a06432a0-66b9-11e8-9e0f-d96749ef48c0.jpg)

谢谢各位了
