### ISSUE TITLE
如何在全国或一个省地图中直接显示出辖区内所有区县的边界和value？

### ISSUE THREAD

**Issue by zhengli8341** [pyecharts/pyecharts#588]
**问题**
如何在全国或一个省地图中直接显示出辖区内所有区县的边界和value
目前可以在全国地图中显示出各个省的边界和对应颜色值，可以在全市地图中显示出所有区县的边界和颜色。

**运行环境（系统环境及 pyecharts 版本）**
windows7，pyecharts最新版本。

**代码及截图**

**Comment by chenjiandongx** [comment]
@zhengli8341 请给出 demo 图的效果，这描述不太好理解。

**Comment by chenjiandongx** [comment]
提问者失联。
