### ISSUE TITLE
jupyterLab 无图显示

### ISSUE THREAD

**Issue by Fankbai** [pyecharts/pyecharts#589]
bar.render()可以渲染出html格式的图，但是没有将图像显示到代码下面的区域中。
![image](https://user-images.githubusercontent.com/10338671/40883423-027deb5a-672f-11e8-9ea8-d26ef1987ffb.png)

**Comment by chfw** [comment]
请看文档。pyecharts 不直接支持 jupyterlab 因为它不允许输出的html 里有 JavaScript. 你如果你改为输出图片会有效果，不过就不能互动了。
