### ISSUE TITLE
对于某些样式有特殊需求，pyecharts目前还没有支持

### ISSUE THREAD

**Issue by GCWK** [pyecharts/pyecharts#590]
**问题**
1. 柱状图、折线图（面积）等不支持渐变色配置。
* http://echarts.baidu.com/examples/editor.html?c=bar-gradient
2. 不支持Tree和Sunburst图 
* http://echarts.baidu.com/examples/#chart-type-tree
* http://echarts.baidu.com/examples/#chart-type-sunburst

**运行环境（系统环境及 pyecharts 版本）**
* ubuntu 16.04
* pyecharts version 0.5.3 

**代码及截图**
无

**Comment by localhost007** [comment]
request for tree

**Comment by chenjiandongx** [comment]
#669

**Comment by chenjiandongx** [comment]
Tree 已经支持，请更新到 V0.5.8 使用

**Comment by chnynf** [comment]
赞，期待sunburst

**Comment by chenjiandongx** [comment]
Sunburst 另开 issue 讨论
