### ISSUE TITLE
overLap中的数据自动给篡改了

### ISSUE THREAD

**Issue by Fankbai** [pyecharts/pyecharts#591]
**问题**
希望在图中同时显示effectscatter和Line绘制激活函数，在测试时可以看出图中仅正确显示出EffectScatter的图像，而Line中的点所对数据发生了变动。

**运行环境（系统环境及 pyecharts 版本）**
* OS: win10;
* App: netract: 0.8.4
* pyechats: 0.55

**代码及截图**
```python
#... ...
reLU6  = torch.nn.ReLU6()
z = torch.arange(-3,10, 1)
y = reLU6(z)


es = pyecharts.EffectScatter("线性激活单元")
es.add("ReLU6",
        z.numpy(),
        y.numpy(),
        effect_scale=3.5,
       effect_period=5,
       symbol="roundRect",
      label_color=["rgb(0,255,0)"])

line = pyecharts.Line("ReLU6","线性激活单元")
print(z.numpy(), y.numpy())
line.add("ReLU",
        z.numpy(),
        y.numpy(),
        label_color = ["rgb(255,255,0)"])

overlap = pyecharts.Overlap()
overlap.add(es)
overlap.add(line)

print(z.numpy(), y.numpy())
overlap
```
Results:
![image](https://user-images.githubusercontent.com/10338671/40896353-04869f60-67e7-11e8-842c-0f6fc89da34c.png)
**EffectScatter对应的数据视图**
![image](https://user-images.githubusercontent.com/10338671/40896375-2164cc10-67e7-11e8-91c9-c1caba0a9b0c.png)
**Line对应的数据视图**
![image](https://user-images.githubusercontent.com/10338671/40896366-18aa4d70-67e7-11e8-8c38-718e31f729fb.png)
**print输出的结果：**
[-3. -2. -1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9.] [0. 0. 0. 0. 1. 2. 3. 4. 5. 6. 6. 6. 6.]
[-3. -2. -1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9.] [0. 0. 0. 0. 1. 2. 3. 4. 5. 6. 6. 6. 6.]

**Comment by chenjiandongx** [comment]
先 add(line)，再 add(es)会不会有这样的情况

**Comment by Fankbai** [comment]
@chenjiandongx  竟然可以绘制，数值也正确了。但出现新的问题，两幅图并没有重叠在一起，原本函数计算的结果值应该使得具有Effect的点应该显示到折线的点上，但现在是分离的。
![image](https://user-images.githubusercontent.com/10338671/40975753-8eb50434-68fe-11e8-9dc2-bd01819fcaa6.png)

**Comment by chenjiandongx** [comment]
@Fankbai 把 pyecharts 更新到 v0.5.7 再试试看
