### ISSUE TITLE
想将label格式化百分比时，显示异常

### ISSUE THREAD

**Issue by caynne** [pyecharts/pyecharts#592]
**问题**

想将label格式化百分比时，部分显示异常.
比如：想将0.07显示成7%时，变成了7.0000000000%

**运行环境（系统环境及 pyecharts 版本）**

macOs  jupyter notebook

**代码及截图**
![2018-06-04 11 39 45](https://user-images.githubusercontent.com/13742300/40897171-0aa04f68-67ec-11e8-8940-1fc4494b0979.png)

**Comment by chenjiandongx** [comment]
代码
![image](https://user-images.githubusercontent.com/19553554/40915217-c9c1690e-682d-11e8-93d2-88621aa26cd5.png)

效果
![image](https://user-images.githubusercontent.com/19553554/40915219-cb29efb4-682d-11e8-85ef-74e86fa77956.png)

**Comment by caynne** [comment]
感谢，已解决
