### ISSUE TITLE
当用Line绘制两条X不同的曲线的时候，其中一条曲线会出错

### ISSUE THREAD

**Issue by cedricporter** [pyecharts/pyecharts#594]
当用Line绘制两条X不同的曲线的时候，其中一条曲线会出错。这个在 matplotlib 里面绘图是正常的。

A_X 是 1，2， 3，但是生成的图片中，A_X 被画到 6，7，8 那里了。

**运行环境（系统环境及 pyecharts 版本）**

Centos 7, Python 3.6, pyecharts 0.55

**代码及截图**

``` python
A_X = [1, 2, 3]
A_Y = [1, 2, 3]

B_X = [6, 7, 8, 10]
B_Y = [9, 10, 11, 12]

line = Line()
line.add("A", A_X, A_Y)
line.add("B", B_X, B_Y)
line
```

![image](https://user-images.githubusercontent.com/1559563/40965887-8d6900de-68e1-11e8-8154-edb2c69647be.png)

**Comment by Fankbai** [comment]
感觉和 #591 我遇到问题类似。

**Comment by chenjiandongx** [comment]
最好确保同一个 X 轴，使用 add 的话，不然就使用多 X 轴

**Comment by rlaaudrlf** [comment]
我的问题是x坐标轴数量不一致但是取值范围是一致的时候显示有误

**Comment by chenjiandongx** [comment]
@rlaaudrlf 还是这个建议
> 最好确保同一个 X 轴，使用 add 的话，不然就使用多 X 轴
