### ISSUE TITLE
为什么柱状图堆叠后Y轴的刻度没有自动调整，结果柱状图超出了容器的高度。

### ISSUE THREAD

**Issue by wxmouse** [pyecharts/pyecharts#595]
**问题**

为什么柱状图堆叠后Y轴的刻度没有自动调整，结果柱状图超出了容器的高度。之前有一段时间倒是正常的。

**运行环境（系统环境及 pyecharts 版本）**

python 3.6 +flask+pyecharts

**代码及截图**
![echart_bar](https://user-images.githubusercontent.com/40047084/41138509-70a2167c-6b14-11e8-9b6f-c3d9df05b18f.jpg)

**Comment by chenjiandongx** [comment]
pyecharts 哪个版本，这边最新 0.5.5 测试没问题

**Comment by Suyobe** [comment]
pyecharts  v1 版本  柱状图堆叠后Y轴的刻度没有自动调整，结果柱状图超出了容器的高度
