### ISSUE TITLE
地图问题

### ISSUE THREAD

**Issue by xlx0010** [pyecharts/pyecharts#596]
**问题**
我在安装完所有的地图扩展包之后，在使用Geo的时候只能输入城市名，输入省份名会报错
而使用Map的时候是正常的。

**运行环境（系统环境及 pyecharts 版本）**
win10, pyecharts0.5.3

**代码及截图**
![image](https://user-images.githubusercontent.com/31838190/41200318-ff04ddac-6cd4-11e8-83de-eb1bea4ec2cf.png)
ValueError: No coordinate is specified for 广东

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/41200520-867bbe74-6cd8-11e8-9378-dc145ef619ea.png)

**Comment by chfw** [comment]
说实话，pyecharts 不支持省的名字，请看下面这个文件：

https://github.com/pyecharts/pyecharts/blob/master/pyecharts/datasets/city_coordinates.json

**Comment by xlx0010** [comment]
可是Map里面用省名就没问题，这是为什么呢？

**Comment by xlx0010** [comment]
@chenjiandongx 哦我忘说了我确实用的是python2
@chfw 可是Map里面用省名就没问题，这是为什么呢？

**Comment by chfw** [comment]
省名是地图名字。
