### ISSUE TITLE
关于词云图SVG格式的问题

### ISSUE THREAD

**Issue by jerry79** [pyecharts/pyecharts#597]
**问题**
词云图我导出了SVG图片，发现词语有重叠，而其他格式，如gif，jpeg等都没有重叠，请问这个是bug吗？附图是gif和svg

**运行环境（系统环境及 pyecharts 版本）**
pycharts 0.5.5
python 2.7
deepin系统

**代码及截图**
Gif

![weekly_report_search_key_2018-01-01](https://user-images.githubusercontent.com/2713806/41327871-ccd328dc-6ef7-11e8-8c02-eee87b0bb03c.gif)

SVG
![image](https://user-images.githubusercontent.com/2713806/41327906-f911c4e4-6ef7-11e8-8a89-3e6ad8154a71.png)

**Comment by chfw** [comment]
font size changed. Only svg picture will take external styles.
