### ISSUE TITLE
x轴

### ISSUE THREAD

**Issue by AlphaSmartDog** [pyecharts/pyecharts#598]
**问题**
如何让刻度按照数值划分，这个图x轴两个格的大小不同，导致这个图失真了

**运行环境（系统环境及 pyecharts 版本）**
windows 10 x64
'0.5.5'

**代码及截图**
 	1*c-100@2.7	1*p-100@3.7	期权组合
84.3	-2.7	12	9.3
96.3	-2.7	0	-2.7
100	-2.7	-3.7	-6.4
102.7	0	-3.7	-3.7
114.7	12	-3.7	8.3

![default](https://user-images.githubusercontent.com/24935017/41354862-a3e8075c-6f52-11e8-9aa3-547d95e88362.png)

**Comment by chenjiandongx** [comment]
@AlphaSmartDog 试试这个

![image](https://user-images.githubusercontent.com/19553554/41360287-fc665df0-6f5e-11e8-9c4a-0f0aceb008ca.png)

**Comment by AlphaSmartDog** [comment]
@chenjiandongx 添加之后，没有什么效果。我想把弄成这样子的，这里应该是直线
![bokeh_plot](https://user-images.githubusercontent.com/24935017/41531531-309f4ddc-7326-11e8-9526-6e34119b0af6.png)

**Comment by AlphaSmartDog** [comment]
@chenjiandongx 请问这个库现在能否解决这个问题？如果不能，这边能否给推荐一个这样类型的库，我之前没有做过这方面的程序，谢谢

**Comment by chenjiandongx** [comment]
@AlphaSmartDog 我按你的数据实现了一下，确实实现不出效果。奇怪的 Echarts 的官方文档跟它实际实现的效果是不同的...

**Comment by AlphaSmartDog** [comment]
OK, thank you.






在2018年06月29 23时36分, "陈键冬"<notifications@github.com>写道:



@AlphaSmartDog 我按你的数据实现了一下，确实实现不出效果。奇怪的 Echarts 的官方文档跟它实际实现的效果是不同的...

**Comment by chenjiandongx** [comment]
@AlphaSmartDog 最新版的 pyecharts 把 Echarts 更新到了最新版，你可以更新试一下

**Comment by AlphaSmartDog** [comment]
好的 明天抽空试一下
