### ISSUE TITLE
Graph 做关系图时，用数据库找出的values做node的name显示不了

### ISSUE THREAD

**Issue by TomHacker** [pyecharts/pyecharts#599]
python 3.5
###########代码################
res=SPO.find({"sub":input})
   print(res)

   nodes=[]
   node={}
   node["name"] = input
   node["symbolSize"] = 20
   # node["symbol"] = "arrow"
   nodes.append(node)
   links=[]

   for index,i in enumerate(res):
       print(i['obj'])
       nodes.append({"name":i["obj"],"symbolSize":10})
#############################################
html 显示为空

把 nodes.append({"name":i["obj"],"symbolSize":10})
改成
  nodes.append({"name"str(index),"symbolSize":10})
html可以显示，但是很明显不符合设计原意。

**Comment by chenjiandongx** [comment]
意思是，

如果使用 index["key"] 这样的形式不能正常显示，直接传入字符串就正常是吗？

**Comment by TomHacker** [comment]
是的。
同时我也发现，不用循环就可以显示了
![image](https://user-images.githubusercontent.com/31693574/41389693-bebde174-6fc4-11e8-8670-d2c62a8a7c07.png)

**Comment by TomHacker** [comment]
在5个可以的，但是我改成10个就不能显示了。
nodes有数量限制？？？？？？？

**Comment by chenjiandongx** [comment]
限制肯定是有，取决于浏览器和你的机器性能，但是 10 个就好像说不过了。要不然你运行我那微博示例的代码？

**Comment by chenjiandongx** [comment]
数据在这里 https://github.com/pyecharts/pyecharts/blob/master/test/fixtures/weibo.json

**Comment by TomHacker** [comment]
可能是机器的问题，一旦我的遍历res的每一个node（name=res[i]['obj']）就不行了
但是同样遍历res的每一个node，只是把name改成str(index)就行了？
真奇怪。。。。。。。。。。。。。。

**Comment by chenjiandongx** [comment]
这样呢
```python
for i in range(5):
    nodes.append({'name': str(res[i]['obj']), 'symbolSize': 10})
```

**Comment by TomHacker** [comment]
不行。
应该是机器的问题，在5个以内可以显示，一旦超出5个，哪怕6个都不行
（下图是5个的例子）
![image](https://user-images.githubusercontent.com/31693574/41390446-37de7dae-6fc8-11e8-9fa6-5cc5d5a08fc1.png)

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/41391048-14e690fe-6fcb-11e8-871b-82d7b8df9e95.png)

还是建议运行下这个示例看看，里面的数据量就挺大的。

**Comment by TomHacker** [comment]
![image](https://user-images.githubusercontent.com/31693574/41392144-70ed6e44-6fd1-11e8-866a-3a259517061d.png)
（大概有35个节点）
html显示如下：
![image](https://user-images.githubusercontent.com/31693574/41392150-833b8ef0-6fd1-11e8-8acb-0d0dc4f44ab7.png)

 查看html页面源码如下：
![image](https://user-images.githubusercontent.com/31693574/41392165-93140c26-6fd1-11e8-8cb7-b18484e619de.png)

**Comment by chenjiandongx** [comment]
把 value 注释了看看。不要 value 了
![image](https://user-images.githubusercontent.com/19553554/41392247-29d7954c-6fd2-11e8-9148-4ab7c893bf4c.png)

**Comment by chenjiandongx** [comment]
感觉是你 value 太大，把图撑开了的样子

**Comment by TomHacker** [comment]
![image](https://user-images.githubusercontent.com/31693574/41392403-e4b947e8-6fd2-11e8-8571-99242f951dd6.png)
改了还是不行（连title都显示不出来）
![image](https://user-images.githubusercontent.com/31693574/41392412-ef3043a2-6fd2-11e8-8936-c69758009df2.png)

**Comment by chenjiandongx** [comment]
, repulsion=8000 指定一下这个试试看？
