### ISSUE TITLE
使用pyecharts-snapshot生成图片png/gif时图例项消失

### ISSUE THREAD

**Issue by chenlianqing** [pyecharts/pyecharts#600]
**问题**
生成html文件后没有问题，但是使用pyecharts-snapshot插件生成png/gif图片时，原来的图形中的表头、图例项、坐标轴标签等都消失了。

**运行环境（系统环境及 pyecharts 版本）**
1、操作系统：Red Hat 4.4.7-16；
2、pyecharts版本：0.5.5；
2、node版本：v10.4.0；
3、phantomjs版本：2.1.1.

**代码及截图**
overlap = Overlap()
overlap.add(line_1, yaxis_index=0)
overlap.add(line_2, is_add_xaxis=False, is_add_yaxis=True, yaxis_index=1)
overlap.render('./project_speed/lines.gif')

<img width="686" alt="default" src="https://user-images.githubusercontent.com/20540340/41398223-3746f9e0-6fe9-11e8-8bfb-f628f14de5bc.png">

**Comment by chfw** [comment]
绘html 的输出有图例吗？

**Comment by chenlianqing** [comment]
谢谢您的回复~ 输出的HTML里是有图例的，是没有问题的，见下图（不好意思数据做了一些处理）：
<img width="792" alt="default" src="https://user-images.githubusercontent.com/20540340/41446990-844b08b6-7085-11e8-98d3-1d09b2028bc1.png">

但是不管是先生成HTML再make_a_snapshot()生成png/gif图片还是直接overlap.render('./project_speed/lines.gif')生成图片，图片里的图例都消失了。

**Comment by chenjiandongx** [comment]
#654

**Comment by chenlianqing** [comment]
好的，非常感谢~ 谢谢您~ @chenjiandongx
