### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by meininghang** [pyecharts/pyecharts#602]
**问题**
无法升级安装

**运行环境（系统环境及 pyecharts 版本）**
 Mac OS 10.14 Beta (18A314h)
Python 3.6.5
pyecharts 0.5.5

**代码及截图**
- 命令：
`pip3 install -U pyecharts`
- error:
`command 'gcc' failed with exit status 1`
- 具体内容：
```
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/zr/4865xftd65bgkyz4xqjxrgs00000gn/T/pip-install-kvtwrnqk/dukpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/zr/4865xftd65bgkyz4xqjxrgs00000gn/T/pip-record-j1837542/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/zr/4865xftd65bgkyz4xqjxrgs00000gn/T/pip-install-kvtwrnqk/dukpy/
```

**Comment by tikkat3** [comment]
@meininghang 人家写明了支持的是 3.4.+

**Comment by chenjiandongx** [comment]
@chfw 检查下

**Comment by meininghang** [comment]
是twisted的问题，已解决。

**Comment by liweiwei1419** [comment]
> > 是twisted的问题，已解决。
> 
> 大兄弟，咋解决的，可以说下吗

我也遇到了同样的问题，在 mac 系统上，看了很多资料都不管用。同问如何解决的呢？

![jietu20181104-151014 2x](https://user-images.githubusercontent.com/7555554/47961314-ca85d800-e043-11e8-9c3f-e75f3b1bdb2e.jpg)

**Comment by RamblerW** [comment]
> > > 是twisted的问题，已解决。
> > 
> > 
> > 大兄弟，咋解决的，可以说下吗
> 
> 我也遇到了同样的问题，在 mac 系统上，看了很多资料都不管用。同问如何解决的呢？
> 
> ![jietu20181104-151014 2x](https://user-images.githubusercontent.com/7555554/47961314-ca85d800-e043-11e8-9c3f-e75f3b1bdb2e.jpg)

我的解决了，需要安装一个xcode的命令行工具，这是链接：https://developer.apple.com/download/more/?name=for%20Xcode，找和你电脑系统版本对应的安装包下载安装，如果还不行的话，再安装一下xcode。
