### ISSUE TITLE
json.dumps(chart.options) 报错pyecharts.echarts.label.EmphasisLabel is not JSON serializable

### ISSUE THREAD

**Issue by ly1102** [pyecharts/pyecharts#604]
**问题**
输出chart.options是可以输出的。
但是如果要变成JSON或者dict传给前端，就会报错。

**运行环境（系统环境及 pyecharts 版本）**
问题仅仅出现在当前最新版本(0.5.5)，用0.4的版本没问题。

**代码及截图**
```python
import json
from pyecharts import Pie

chart = Pie("Bug")
chart.add('', ['1', '2'], [3, 4], is_label_show=True)
json.dumps(chart.options)

# TypeError: <pyecharts.echarts.label.EmphasisLabel object at 0x000001E54B1399B0> is not JSON serializable

```
看样子是新版本引入了自定义回调函数的问题。
解决办法:
```python
import json
from pyecharts import Pie
from pyecharts_javascripthon.api import TRANSLATOR

chart = Pie("Bug")
chart.add('', ['1', '2'], [3, 4], is_label_show=True)
json.dumps(json.loads(TRANSLATOR.translate(chart.options).as_snippet()))

# 不报错了，也能运行了
```

看样子可以优化一下这个获取options的操作emmmm

**Comment by kinegratii** [comment]
这不是 Bug，而是你所使用的方式不正确。
```python
json.dumps(chart.options)
```

获取 options 应该使用以下方法：

https://github.com/pyecharts/pyecharts/blob/29a2ca9089fa93abeea4807daad3b1bd5454b374/pyecharts/base.py#L86-L92

 **原理**


`TRANSLATOR.translate` 在内部已经调用了 `json.dumps` 方法，该方法实现了自定义的 `encoder` ，以针对 `JsonSerializable`  对象（`EmphasisLabel` 继承自该类）的支持。

**Comment by ly1102** [comment]
@kinegratii  这个只是输出了，但是我想要获取到这个配置，然后发送给前端以更新图表的信息。
要不加一个`get_echarts_options()`的方法吧

**Comment by kinegratii** [comment]
@ly1102  `get_echarts_options()` 可以有
