### ISSUE TITLE
import 出错

### ISSUE THREAD

**Issue by liu963l** [pyecharts/pyecharts#607]
![default](https://user-images.githubusercontent.com/20901780/41980790-f1a80f98-7a59-11e8-835e-20e20523745d.png)
为什么import 后会报这个错误啊

**Comment by chfw** [comment]
你当前Python 环境装了几个pyecharts

**Comment by liu963l** [comment]
只有一个呀。我卸载后重新安装pyecharts后又报了这个错误。
![default](https://user-images.githubusercontent.com/20901780/42008475-4dfde6ba-7ab8-11e8-8a5e-e105372332e2.png)

**Comment by chfw** [comment]
👆不用crypto

**Comment by liu963l** [comment]
能详细解释一下吗

**Comment by chfw** [comment]
我的判断是 PYTHON 环境问题。

需要多的解释的话，请给出所有的 STACK TRACE。

**Comment by chenjiandongx** [comment]
重装试试
```
pip uninstall pyecharts
pip install pyecharts -U
```
