### ISSUE TITLE
自定义主题用不了

### ISSUE THREAD

**Issue by tikkat3** [pyecharts/pyecharts#608]
按照给出的flask原始例子
改了主题
代码就一句
use_theme('dark')

我是柱形图
现象，图表加载不出来数据

**Comment by chenjiandongx** [comment]
请确认你已下载了最新版 pyecharts  以及 主题插件包

**Comment by ggtggt** [comment]
我下载的0.5.5的pyecharts根本没法用 各种提示我缺这个模块 缺那个 有个叫metapeserio.xxx的我就下不到了  0.5.4的也是 缺这少那 最后我不换主题了 换回了 0.1.9几那个版本 pyecharts 就又可以用了 python就光下载安装这一点根本比不上R 真浪费时间

**Comment by chenjiandongx** [comment]
你是怎么下载安装的？ pip install pyecharts==0.5.5？

**Comment by ggtggt** [comment]
pip install pyecharts，pip install pyecharts==0.5.5 都试过了 总报错 让我下misrosoft c++14版 下了新的c++ 还是报错 在网上找的说要重安一个dupky的exetension 安了不管用 还是错
然后我就直接下载0.5.5pyecharts 文件 解压到 site-packages文件夹里（这个方法也是网上找的）但是import pyecharts时又说缺javascr....什么的模块 安完又缺另一个 再安了 又缺 0.5.4跟0.5.3也是这个情况 theme的那个插件已经下载了

**Comment by ggtggt** [comment]
你们这个网页回复的时候怎么不能选择想要回复的人啊
还有个问题是 pip install pyecharts 的时候 出过一个错是：require python-version>3.4 可是我下载的可是3.7的最新版本啊。。。

**Comment by chenjiandongx** [comment]
我们没有在 python3.7 上测试过。。。python3.4~3.6 而已

**Comment by ggtggt** [comment]
好吧 昨天刚把3.6的更新成3.7 
快被py搞疯了 抓狂程度不亚于安装sas学生版
还有个问题就是 你们这个网站 竟然没有消息提醒 只能收到邮件 再过来找 个人中心里即使有消息未读也不会显示
