### ISSUE TITLE
折线图图例颜色及标记设置

### ISSUE THREAD

**Issue by xjr7670** [pyecharts/pyecharts#609]
请问下，

![image](https://user-images.githubusercontent.com/7731794/42080813-6c43e6e8-7bb6-11e8-97ed-165ffeb0d61a.png)

如上图所示，可以看到，图例中各个数据系列的颜色（就是那些圈圈横线）是跟下面的折线中的标记颜色相同的，如“计费总收入”这里，图例中显示都是红色，但是实际上在折线图中，它的线条是蓝色的，只有标记是红色。

这样很容易产生误会。而我在官方文档中也找不到有相关的设置项，mark_point相关的也只是特殊项的标记，似乎并不是用于设置折线图线中的标记的，我想问下这个要怎么解决呢？

另外一个就是，折线图中的这些标记（就是默认的那些空心的圈圈）应该要怎么设置呢？我也找不到说明，试了几个，发现只有`symbol_size`这个参数可以正确设置这些标记的大小。这个参数貌似在文档中也没有说到

谢谢

**Comment by chenjiandongx** [comment]
> 如上图所示，可以看到，图例中各个数据系列的颜色（就是那些圈圈横线）是跟下面的折线中的标记颜色相同的，如“计费总收入”这里，图例中显示都是红色，但是实际上在折线图中，它的线条是蓝色的，只有标记是红色。

@xjr7670  不是很明白哈

**Comment by xjr7670** [comment]
不好意思，可能我描述得不够清楚，看下面这个图吧，我做了下标记

![333](https://user-images.githubusercontent.com/7731794/42120384-f04ed592-7c4c-11e8-8a56-bc1bbb0848b2.png)


 标题下面是图例，就是legend，第一个是计费总收入，可以看到图里面我用黄色圈圈出来的地方，这里“计费总收入”的**标记是红色的线和圈**，但是实际上它对应的是下方图里面我标出来的A线，A线这里明显它的**线条颜色是蓝色**的，这样就有不一致的地方了。

因为通常我们都是用颜色匹配图例和线条的，而如果按上方这个图的话，那么计费总收入的红线，它对应的就是B线了，这是不对的。

不知道我讲明白了没有……
多谢解答

**Comment by chenjiandongx** [comment]
把pyecharts版本退回到 0.5.1 试试看

**Comment by chenjiandongx** [comment]
或者更新到最新版 0.5.5 这应该是更新主题时候遗漏的问题 最新版应该解决了 0.5.1 是没有主题的版本 两个都尝试一下吧哈

**Comment by xjr7670** [comment]
两种方式我都试过了，这是我在win10上的环境，我分别在python3.6的ananconda下装了0.5.5的版本，在wsl下的python2.7装了0.5.1的版本，结果一样的

![qq 20180630183349](https://user-images.githubusercontent.com/7731794/42124381-2dc1995e-7c94-11e8-95d8-a62fdfd01c5f.png)


此外，有个情况我没有说到的是，我这里会出现这个问题是因为我在每个line.add的参数里面使用了line_color来改了颜色的。如果不改保留默认颜色，是正常的

![color](https://user-images.githubusercontent.com/7731794/42124427-dbfd8c3a-7c94-11e8-9380-1fd578b1fe4e.png)


现在就是改了线条颜色后，图例没有跟着变

**Comment by chenjiandongx** [comment]
那你修改全局的 label_color 不要改 line_color 试试看

**Comment by xjr7670** [comment]
这样改就可以了。多谢啦

**Comment by chenjiandongx** [comment]
FIXED

**Comment by Dittonal** [comment]
2.0.6版也遇到了这个问题，请问修改全局的 label_color是怎么修改呢

**Comment by Dittonal** [comment]
@xjr7670

**Comment by Dittonal** [comment]
@chenjiandongx
