### ISSUE TITLE
关于options的直接使用and零刻度

### ISSUE THREAD

**Issue by YoLoveLife** [pyecharts/pyecharts#612]
您好 我是一名前后端共同开发者，我希望直接使用pyecharts+db模型生成options直接返回给前端做显示。
但是我看你们的方法**print_echarts_options**是专门使用作调试
是否有方法专门应对我这种使用情况的呢？
我看你们源码 其实print_echarts_options是针对options的字典的内容的解析，options是自己包含一些object需要解析成字典来返回的。
我想自己根据你们的源码深一层做包装直接使用options，但是貌似有点难理解，可以给个思路吗关于我这种使用方式。感谢

**Comment by YoLoveLife** [comment]
我目前的做法是
`
        snippet = TRANSLATOR.translate(charts.options)
        json_results = json.loads((snippet.as_snippet()))
`

**Comment by chfw** [comment]
先看看下面两个例子

https://github.com/pyecharts/pyecharts-users-cases/tree/master/demo-django/myechartsite
https://github.com/pyecharts/pyecharts-users-cases/tree/master/demo-flask

**Comment by YoLoveLife** [comment]
@chfw 例子的意思应该是直接通过pyecharts来生成html**直接注入django的jinja2模板**来做展现。
我是使用Django-restframework来做的前后段分离，所以有所不同。
```python
snippet = TRANSLATOR.translate(charts.options)
json_results = json.loads((snippet.as_snippet()))
```
这样的方式应该会适合想**直接使用数据与pyecharts来构成options**，并且后端数据直接投递给前端访问。
虽然前后段分离还使用后端来处理前端数据感觉有点奇怪，但是能够从数据模型直接生成可供图形化的options还是很棒的。
我个人觉得这个需求可能还是存在的，不知道你们是如何觉得的。
另外还有一个问题：
我在使用pyecharts来构成options的时候，发现呈现的数据的Y轴一直从0刻度开始计算
有什么参数(类似yAxis.scale   |   boolean)可以让Y轴脱离0刻度
目前我的样式是这样的

![监控图形化](https://user-images.githubusercontent.com/24267209/42225095-5038e7c2-7f0e-11e8-95bd-4bccd5d66302.png)

我这边使用了很多的参数去解决这个问题，官方文档中类似的选项好像都没有生效，你们能够提供帮助吗。

**Comment by X-Mars** [comment]
我也是 jango rest framework 、vue   前后端分离，不知道 该怎么做。

**Comment by chenjiandongx** [comment]
options 的话可以试试看直接调用图形实例的 options 属性，如 bar.options

![image](https://user-images.githubusercontent.com/19553554/42623745-3a1dd864-85f6-11e8-870d-7bee924de257.png)

这两个参数应该对第二个问题有帮助
