### ISSUE TITLE
运行文档里回调函数的基本示例时出现 OSError: could not get source code

### ISSUE THREAD

**Issue by jy5380** [pyecharts/pyecharts#614]
**问题**
运行文档里关于回调函数的以下示例时出现
OSError: could not get source code
出错代码：
from pyecharts import Bar

def label_formatter(params):
    return params.value + ' [Good!]'

attr = ["Jan", "Feb"]
v1 = [2.0, 4.9]
bar = Bar("Bar chart", "precipitation and evaporation one year")
bar.add("precipitation", attr, v1, is_label_show=True, label_formatter=label_formatter)
bar.render()

**运行环境（系统环境及 pyecharts 版本）**
系统 win10
python版本 3.7.0
pyecharts版本  0.5.5

**代码及截图**
![image](https://user-images.githubusercontent.com/15127053/42211233-abb18ba0-7ee5-11e8-9537-b056d30eae11.png)

**Comment by chfw** [comment]
python's inspection does not support interpreter. What it means is inspect.py cannot look up the source code from the cli input.

please put all your code in a file and all shall work.

**Comment by jy5380** [comment]
The problem has been solved by your instructions. Thanks for your help!
