### ISSUE TITLE
pyecharts地图，鼠标停留时的悬浮文本能否实现换行显示？

### ISSUE THREAD

**Issue by JuntingYu1996** [pyecharts/pyecharts#615]
**问题**
如下图，我想把同学A和同学B写成两行，但是使用“\n”符号无效，请问有没有办法实现换行呢？

**运行环境（系统环境及 pyecharts 版本）**
win7，python3.6，pyecharts最新版

**代码及截图**
from pyecharts import Geo

def formatter_for_tootip(params):
    return params.value[2]

def plotmap():
    geo = Geo("G1115班本科毕业去向", "Made by YJT", title_color="#fff",
              title_pos="center", width=1366,
              height=768, background_color="#404a59")

    data = [('香港', '同学A 香港大学；同学B 香港科技大学')]
    attr, value = geo.cast(data)

    geo.add("", attr, value, type="effectScatter", is_random=True, maptype='world',
            effect_scale=5, tooltip_formatter=formatter_for_tootip,
            label_formatter="{b}")
    geo.render("test.html")

plotmap()

![default](https://user-images.githubusercontent.com/40770755/42229831-fe6490e8-7f19-11e8-92ac-f5ae69f634b5.png)

**Comment by chfw** [comment]
'同学A 香港大学\n同学B 香港科技大学'

or

'同学A 香港大学<br>同学B 香港科技大学')

**Comment by JuntingYu1996** [comment]
多谢指点，经测试\n无效， <br>有效。原因猜测是tooltip是采用javascript而不是python进行处理。
问题已解决，关闭
