### ISSUE TITLE
toolbox工具箱提示信息

### ISSUE THREAD

**Issue by saler-1** [pyecharts/pyecharts#617]
**问题**
鼠标移动到toolbox工具箱上时，提示信息会与工具箱其他图标相互遮掩；
能单独设置提示信息的位置或者直接将提示信息移到图标另一侧吗?

**运行环境（系统环境及 pyecharts 版本）**
linux pyecharts ==0.5.5

**代码及截图**
![image](https://user-images.githubusercontent.com/8528552/42307331-9dd478aa-8064-11e8-9dd9-d4925f1bd898.png)

**Comment by chenjiandongx** [comment]
echarts 的话这个参数应该可以改

![image](https://user-images.githubusercontent.com/19553554/42623373-47db9d3e-85f5-11e8-9ecc-fceeb88808e3.png)

pyecharts 暂时没有，如果比较着急实现的话可以自己手动修改一下 pyecharts 的源码
![image](https://user-images.githubusercontent.com/19553554/42623396-5b0ca0a6-85f5-11e8-86d4-7579c7c80eb6.png)

**Comment by chenjiandongx** [comment]
无法解决该问题，试了位置调成 上下左右 四个方向均会出现上述问题。Echarts 本身也没有提供更多的参数。
SORRY!

**Comment by saler-1** [comment]
多谢您了~
