### ISSUE TITLE
geo图label_formatter参数失效

### ISSUE THREAD

**Issue by 3570** [pyecharts/pyecharts#618]
**问题**
geo图中，如果不用label_formatter，那么当鼠标移动到城市时，图形上的文本标签是纬度信息，而不是我想要的value。如果设置label_formatter，则不能通过 {c0}, {c1}, {c2} 这种后面加索引的方式表示系列的索引。

**运行环境（系统环境及 pyecharts 版本）**
windows10, pyecharts0.5.5

**代码及截图**
```
geo = Geo("全国主要城市空气质量", "data from pm2.5", title_color="#fff", title_pos="center", 
                  width=1200, height=600, background_color='#404a59')
attr, value = geo.cast(data)
geo.add("", attr, value, visual_range=[0, 200], visual_text_color="#fff", symbol_size=7, 
             is_visualmap=True)
```
i[image1](https://github.com/3570/my-Repository-3570/blob/master/%E7%BA%AC%E5%BA%A6.png)

```
geo = Geo("全国主要城市空气质量", "data from pm2.5", title_color="#fff", title_pos="center", 
                 width=1200, height=600, background_color='#404a59')
attr, value = geo.cast(data)
geo.add("", attr, value, visual_range=[0, 200], visual_text_color="#fff", symbol_size=7, 
             is_visualmap=True, label_formatter="{c2}")
```
i[image2](https://github.com/3570/my-Repository-3570/blob/master/%E5%9B%BE%E5%83%8F%201.png)

**Comment by 3570** [comment]
找到了一个权宜之计：
```
def label_formatter(params):
    return params.value[2]

geo.add("", attr, value,
        label_formatter=label_formatter,
        is_visualmap=True, visual_range=[0, 200], visual_text_color="#fff", symbol_size=10, 
        tooltip_formatter="{b}")
```

**Comment by Apollo1840** [comment]
疑问。。。label_formatter 不是默认显示数据名（城市名）么， 如果想要修改游标内容，应该是改tooltip_formatter吧？

**Comment by chenjiandongx** [comment]
tooltip_formatter 修改起来有什么问题吗

**Comment by xming521** [comment]
应该是label_formatter有问题，默认显示了纬度值，而不是要显示的值，这问题在网站demo里没出现，但在我们自己电脑上出现了问题

**Comment by xming521** [comment]
是label不是tooltip
![image](https://user-images.githubusercontent.com/32786500/43720307-b88271c6-99c2-11e8-9987-89fce52fcdb0.png)
这里默认显示了纬度值，感觉很不正常

**Comment by chenjiandongx** [comment]
@xming521 
![image](https://user-images.githubusercontent.com/19553554/43721504-8e478542-99c5-11e8-93f7-6c7cebcade08.png)

···python
label_formatter="{b}",
tooltip_formatter="{b}",
label_emphasis_textsize=15,
label_emphasis_pos="right",
```
