### ISSUE TITLE
line.add()中修改了linestyle后，legend没有随之变化的问题

### ISSUE THREAD

**Issue by Apollo1840** [pyecharts/pyecharts#619]
你好，最近接触到pyecharts的项目，非常喜欢，表示支持！

在探索中遇到一个问题，我使用的是python3.6下的0.5.5版本。具体修改了line_width, line_color, line_type, 然而在legend中，采用的是默认格式的线， 和希望对应的线并不对应。

简单示例：
line=Line()
line.add(" ", [1,2,3],[1,2,3], line_color="#ff78ff")
line.render()

![echarts](https://user-images.githubusercontent.com/28777429/42501823-3358bd06-843d-11e8-9ecd-44218724e701.png)

p.s 在简单示例中采用label_color替换line_color将得到灰色结果。

**Comment by Apollo1840** [comment]
自问自答一个吧，如手册中所讲，如果想要显示label，可以通过调试label_color来达到目的。
但是label_color现在并不支持str输入，而是[str, str], 两个str分别是line和symbol的color hex code。
例如简单示例中：

line=Line()
line.add(" ", [1,2,3],[1,2,3], label_color=["#ff78ff","#ff78ff"])
line.render()

即可得到正常结果，至于线的其他格式, 如dash, 暂时不明，求接力解答

**Comment by chenjiandongx** [comment]
legend 的颜色只由 label_color 控制而已
