### ISSUE TITLE
关于overlap多图叠加了，时间序列的处理的问题

### ISSUE THREAD

**Issue by hadrianl** [pyecharts/pyecharts#620]
**问题**
各图表的X轴的类型貌似不太一致，设置了x轴是时间的散点图，没有办法与kline，还有时间序列的line图叠加.查看数据发现，散点图的x轴已经转为timestamp，但是kline或者line的x轴仍然是一般时间类型

**运行环境（系统环境及 pyecharts 版本）**
win10， python3.6,  pyeharts0.5.5

**代码及截图**

**Comment by chenjiandongx** [comment]
x 轴的类型只有 字符串类型以及数值类型

**Comment by hadrianl** [comment]
兄dei你别骗我，我可是把散点的xaxis_type设过为'time‘的男人

**Comment by chenjiandongx** [comment]
实际上 time 是不起作用的，因为无法将 Python 的 time/datetime 格式通过 json 转换

**Comment by hadrianl** [comment]
字符串的时间是可以被接受的，从最终的数据来看，应该是被echarts转化成了timestamp了。这时候问题来了，kline传入时间之后,x轴的数据依然还是%Y-%m-%d %H:%M:%S的形式。很蛋疼。独立图表时候没啥子问题，用overlap合并的时候就不行了

**Comment by chenjiandongx** [comment]
overlap 一般只推荐使用相同的 X 轴，如若 X 轴不同，可以尝试使用多 X 轴，具体参考文档

**Comment by hadrianl** [comment]
关键问题就在这里了，实际上我的两个图的x轴都是同一段时间序列，散点最终给我转成timestamp，但是kline却没转。同一个轴两个处理方法，有点凌乱

**Comment by chenjiandongx** [comment]
有没有将 line/kline/scatter 的 X 轴类型设置为一致呢？

**Comment by hadrianl** [comment]
印象中kline和line不能设置类型为time
