### ISSUE TITLE
写了个tornado模版, 可以加到官方文档里吗?

### ISSUE THREAD

**Issue by ityoung** [pyecharts/pyecharts#621]
写了个tornado的模版, 是否需要提个PR合到文档里? 

**代码**
https://github.com/ityoung/pyecharts-tornado-demo.git

**Comment by chenjiandongx** [comment]
@ityoung 可以放在 https://github.com/pyecharts/pyecharts-users-cases 这里

**Comment by ityoung** [comment]
好的 @chenjiandongx 
会的 @chfw
