### ISSUE TITLE
Grid 并列显示散点图和饼图时，如果散点图使用了 is_visual_map=TRUE时，饼图的扇形颜色都显示为同一种

### ISSUE THREAD

**Issue by xiumianti** [pyecharts/pyecharts#622]
**问题**
Grid 并列显示散点图和饼图时，散点图如果使用了 is_visual_map=TRUE时，饼图的颜色会错误，所有的扇形都只能显示为同一种颜色，而饼图的legend则正确显示颜色分配。

**运行环境（系统环境及 pyecharts 版本）**
Mac，jupyter notebook v1.0.0，pyecharts v0.5.5

**代码及截图**
attr = [1,2,3,4,5]
v1 = [102,301,204,501,306]
v2 = [1,2,3,4,5]

scatter = Scatter("散点图1",title_pos='65%',subtitle_text_size=12)
scatter.add("", attr, v1, extra_data= v2, is_visualmap=True,
        visual_dimension=2,  visual_pos=-200, visual_range=[min(v2), max(v2)])
pie = Pie("饼图2", title_pos='15%')
pie.add("",attr, v1, is_label_show=True, center=[25,50], legend_orient='vertical',legend_pos='left',legend_top='25%' )

grid = Grid(width=1000, height=350)
grid.add(scatter,grid_left="55%")
grid.add(pie)
grid

结果如下：
![image](https://user-images.githubusercontent.com/41176290/42670183-ea29bba2-868b-11e8-8191-4065eaa33270.png)

**Comment by xiumianti** [comment]
而且发现，不只是饼图，当Grid 并列显示，2个同时使用了 is_visualmap=TRUE 的 scatter 散点图时，第二个添加到 Gird 中的 is_visualmap 的颜色映射也会出错，显示为同一种颜色

**Comment by chenjiandongx** [comment]
看起来是 Pie 也用了 visualmap 的效果了
