### ISSUE TITLE
jupyter lab compatibility

### ISSUE THREAD

**Issue by pjgao** [pyecharts/pyecharts#623]
jupyter lab已经面向个人用户发布了，请问pyecharts项目有没有兼容jupyter lab的计划呢？

**Comment by chfw** [comment]
没有近期打算。

**Comment by wisfern** [comment]
在用lab了，大佬计划什么时候开始适配lab呢？

**Comment by Huqin-China** [comment]
> 需要给自己jupyter lab 写一个扩展. 然后他们的extension guide 不给力呀

也许可以参考一下plotly的源码，我觉得它最大的特点就是要使用和实现ipython widgets这个模块.这个模块下还可以实现实时更新功能。

**Comment by chenjiandongx** [comment]
#1033 新版本已兼容 lab 环境
