### ISSUE TITLE
保存图片调整分辨率

### ISSUE THREAD

**Issue by xunhs** [pyecharts/pyecharts#624]
**问题**
请问保存图片(output_image)是否可以tif格式？或者保存图片调整图片分辨率？默认保存png格式不清晰。感谢回复！

**运行环境（系统环境及 pyecharts 版本）**
Window10 python3.6 jupyter notebook

**代码及截图**

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts-snapshot/blob/master/pyecharts_snapshot/main.py#L74

try pixcel_ratio = 3 or higher

**Comment by chenjiandongx** [comment]
FIXED
