### ISSUE TITLE
是否需要罗列一下Geo和map图标类型支持的城市名称?

### ISSUE THREAD

**Issue by Ctipsy** [pyecharts/pyecharts#626]
**问题**
爬虫分析城市信息时，经常会碰到
> ValueError: No coordinate is specified for xxxx

的报错，可是又不知道正确的城市名称是什么，或者说是否该城市不被pyecharts支持，因此个人觉得是否有必要在官网补充下城市名称支持目录？

**运行环境（系统环境及 pyecharts 版本）**
win10 64bit  +   pyecharts version:0.0.6
**代码及截图**
![image](https://user-images.githubusercontent.com/31062383/42759535-d7fc2a68-8939-11e8-95b9-80087baa4764.png)

**Comment by chfw** [comment]
here is all pyecharts has: https://github.com/pyecharts/pyecharts/blob/master/pyecharts/datasets/city_coordinates.json

I will try in the future to integrate the following dataset into pyecharts:

https://github.com/echarts-maps/echarts-cities-js

**Comment by Ctipsy** [comment]
thanks a lot!
