### ISSUE TITLE
Geolines不支持is_visualmap地图彩色显示

### ISSUE THREAD

**Issue by robinsun-wondertac** [pyecharts/pyecharts#628]
前面有一个issue也提到了，我看到现在map可以支持地图彩色，geo不行。我觉得这个效果特性还是挺重要的。

**Comment by chenjiandongx** [comment]
好像没见过 Echarts 这样玩

**Comment by robinsun-wondertac** [comment]
谢谢回复 robinsun 邮箱：robinsun@wondertac.com 签名由 网易邮箱大师 定制 在2018年07月27日 10:05，陈键冬 写道： 好像没见过 Echarts 这样玩 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
