### ISSUE TITLE
A question about using pie chart

### ISSUE THREAD

**Issue by Ctipsy** [pyecharts/pyecharts#629]
**问题**
how can i hide some parts in pie chart, when the items are too many?
if there  a   " item A,  item B, ...item Z, other"  setting in pie.add() function?

**运行环境（系统环境及 pyecharts 版本）**
win10+pyecharts0.0.6

**代码及截图**

![default](https://user-images.githubusercontent.com/31062383/42822830-9d3a3d18-8a0e-11e8-87bc-4d47fa470075.png)

for example, i have such demands:
* just show top 10 items in pie charts
* just show the 90%items in pie, and the other items together  will be included in "other"
* hide the label unless i click the corresponding item

looking forward you reply

**Comment by chfw** [comment]
```
# suppose you have the following data array
keys = [ 'beijing', ...]
values = [0.4367',...]

# merge them for sorting
merged_keys_values = zip(keys, values)
# sort them out so that it will be very easy to get top 10
sorted_merged_keys_values = sorted(merged_keys_values, key=lambda x: x[1])
# take top ten
top_ten = sorted_merged_keys_values[:10]
# calculate others
other = sum( [value for _, value in sorted_merged_keys_values[10:]])
# append others to top 10
top_ten.append(['other', other])

# now, back to where we started:
keys, values = zip(*top_ten)

# finally, use keys and values for your plot.
```

**Comment by chfw** [comment]
http://pyecharts.org/#/zh-cn/advanced?id=使用-javascript-事件处理函数

**Comment by Ctipsy** [comment]
thx a lot! @chfw
