### ISSUE TITLE
.js is missing, 'echarts': 'https://pyecharts.github.io/jupyter-echarts/echarts/echarts.min'

### ISSUE THREAD

**Issue by roroyu** [pyecharts/pyecharts#631]
Chrome

    require.config({
        paths: {
            'echarts': '/nbextensions/echarts/echarts.min'
        }
    });

我怎么能临时改下 让 .js 被补上？

.render() is OK

**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by roroyu** [comment]
貌似是因为
https://requirejs.org/docs/errors.html#timeout

没有js是正确的？ 那requirejs 咋办

**Comment by roroyu** [comment]
refresh is OK

**Comment by chfw** [comment]
require.js does not want ".js" suffix.
