### ISSUE TITLE
graph关系图  节点比较多的时候 邻接节点显示的文字内容也被灰化看不清了

### ISSUE THREAD

**Issue by zskyliang** [pyecharts/pyecharts#632]
**问题**
graph关系图  节点比较多的时候 邻接节点显示的文字内容也被灰化看不清了

**运行环境（系统环境及 pyecharts 版本）**
python2.7
 pyecharts-0.5.5

**代码及截图**
graph.add("", nodes, links,label_pos="right",repulsion=len(b),graph_edge_length =len(b),
          graph_repulsion=len(b)*10,line_width=2,graph_gravity=0.2,is_focusnode=True,is_area_show=True,
              line_curve=0.2,line_opacity=0.3,)

![11111](https://user-images.githubusercontent.com/21198518/43065511-a9685892-8e94-11e8-83b8-8d12efc9a13e.png)

**Comment by chenjiandongx** [comment]
label_text_color 应该可以设置文字颜色

**Comment by zskyliang** [comment]
按你说的试过了哈 节点少的时候没有问题（比如100个，显示是正常的） 超过5000个节点好像临接节点文本就被灰化了 文字看不清
label_emphasis_textcolor和label_text_color  这些参数我都试了  解决不了
大神你试下5000个节点以上是不是有这个bug? 还是我配置的不对。。
![image](https://user-images.githubusercontent.com/21198518/43298795-1ec9bcbe-918a-11e8-829a-be65c257abe9.png)
![image](https://user-images.githubusercontent.com/21198518/43298806-39a1394a-918a-11e8-9214-e05dd7320f69.png)
附个对比图

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/43299027-385d95c8-918b-11e8-8922-1bd5e1b0fb24.png)
这个图应该超过这个量级了

**Comment by zskyliang** [comment]
难道要加个类别分组 才能正常显示么？ 我回头试一下吧。 
我就按照默认配置  节点少的时候显示可以正常  节点多的时候就不行了  郁闷 找不到原因。。
