### ISSUE TITLE
不能发现坐标

### ISSUE THREAD

**Issue by stone-syy** [pyecharts/pyecharts#633]
在pycharm上运行一个爬虫的代码，使用了pyecharts生成可视化界面，后来出现报错，报错情况如下：ValueError: No coordinate is specified for 
自己寻求了很多方法都不能解决。
pyecharts版本为0.5.5，Python版本为3.6.5，pycharm版本为2018.1.4
后来自己在网上复制了一段测试代码，可以正常运行，证明我的环境没有问题。
代码片段如下：
![image](https://user-images.githubusercontent.com/41577288/43076306-67ecf59a-8eb6-11e8-8546-3f936e902f90.png)

Traceback (most recent call last):
  File "D:/Python/test1.py", line 91, in <module>
    visual_split_number=4)
  File "D:\untitled2\venv\lib\site-packages\pyecharts\charts\geo.py", line 47, in add
    self.__add(*args, **kwargs)
  File "D:\untitled2\venv\lib\site-packages\pyecharts\charts\geo.py", line 103, in __add
    _coordinate = self.get_coordinate(_name, raise_exception=True)
  File "D:\untitled2\venv\lib\site-packages\pyecharts\charts\geo.py", line 42, in get_coordinate
    raise ValueError("No coordinate is specified for {}".format(name))
ValueError: No coordinate is specified for

**Comment by Juntaran** [comment]
+1

**Comment by wz30** [comment]
可以print下data的内容， 第一个元素莫名是空的 [(''), 4],所以无法找到空元素的坐标

**Comment by stone-syy** [comment]
你好！
      果然就是这个问题，对于这个问题你有什么解决方法吗



shiyouyuan1994@foxmail.com
 
发件人： wz30
发送时间： 2018-07-24 13:43
收件人： pyecharts/pyecharts
抄送： stone-syy; Author
主题： Re: [pyecharts/pyecharts] 不能发现坐标 (#633)
可以print下data的内容， 第一个元素莫名是空的 [(''), 4],所以无法找到空元素的坐标

**Comment by chenjiandongx** [comment]
#637

**Comment by Juntaran** [comment]
各位我已修复了这个代码，可以参考一下

```
# coding=utf-8

'''
    Author: Juntaran
    Email:  Jacinthmail@gmail.com
    Date:   2018/7/23 11:55
'''

from pyecharts import Style
from pyecharts import Geo
import json

#读取城市数据
city = []
with open('target.txt', mode='r', encoding='utf-8') as f:
    rows = f.readlines()
    for row in rows:
        if len(row.split(',')) == 5:
            city.append(row.split(',')[2].replace('\n', ''))

def all_list(arr):
    result = {}
    for i in set(arr):
        result[i] = arr.count(i)
    return result

data = []
for item in all_list(city):
    if (item != ''):
        data.append((item, all_list(city)[item]))
        style = Style(title_color = "#fff", title_pos = "center", width = 1200, height = 600, background_color = "#404a59")

cities = []
with open('city.json', 'r', encoding='utf-8') as f:
    city_data = json.load(f)
    for i in city_data:
        cities.append(i)

ret = []

for i in data:
    if i[0] in cities:
        ret.append(i)

print(ret)

geo = Geo('test', **style.init_style)
attr, value = geo.cast(ret)
geo.add("", attr, value, visual_range=[0, 20], visual_text_color="#fff", symbol_size=20, is_visualmap=True, is_piecewise=True, visual_split_number=4)
geo.render()
```

**Comment by sunyinggang** [comment]
我也遇到了问题，查看了 @chenjiandongx 提供的所有城市信息后，我发现了，对于县级地区，文档给出的都是某某县，而我爬取的地区不带县这个字。比如我爬取了一个地址叫灵石，实际上根据文档应该叫灵石县才可以识别

**Comment by chenjiandongx** [comment]
@sunyinggang 有两个办法解决这个问题

1. 使用 geo_cities_coords 参数来添加地区
2. 直接修改该 https://github.com/pyecharts/pyecharts/blob/master/pyecharts/datasets/city_coordinates.json 文件

**Comment by sunyinggang** [comment]
好的，十分感谢
