### ISSUE TITLE
datazoom目前只能添加一个？

### ISSUE THREAD

**Issue by ygidtu** [pyecharts/pyecharts#634]
**问题**
我有时候作图会需要x轴和y轴各一个datazoom控制条，但是目前看API是只能添加一个么？

**运行环境（系统环境及 pyecharts 版本）**
macOS
pyechars 0.5.5
python 3.6.5 anaconda

**代码及截图**

**Comment by chenjiandongx** [comment]
datazoom_type = 'both'

**Comment by ygidtu** [comment]
但是我用了之前用了both，我的图并没有渲染出双控制条
`
        chart.add(
            cell, x, y,
            is_datazoom_show=True,
            datazoom_type="both",
            datazoom_range=[0, 100],
            label_formatter='{a}: [{c} {b}]'
        )
`

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/43351828-ff28dd06-924a-11e8-87c5-ef5cf1684446.png)

已经新增了该动能，下个版本见

**Comment by ygidtu** [comment]
好勒，点赞

**Comment by ygidtu** [comment]
我今天刚试了一下新的pyecharts，又发现一个问题，datazoom和extra_datazoom不同同时设定为both，如果其中某个为both了，第二个缩放条就出不来。

由于echarts原生代码是支持这中用发的，所以是不是pyecharts里什么地方有问题

**Comment by Nrusher** [comment]
新版本这个接口没有了？
