### ISSUE TITLE
请问如何像echarts一样自定义dataview展现函数呢？

### ISSUE THREAD

**Issue by wse320** [pyecharts/pyecharts#635]
自带的dataview展现样式较为不美观，我打算将其自定义成表格样式，但是翻了开发文档似乎并没有看见在什么地方自定义dataview样式

**运行环境（系统环境及 pyecharts 版本）**
Windows7
pycharm2018.1.2
python2.7
pyecharts 0.5.5

**代码及截图**

**Comment by sunhailin-Leo** [comment]
请给出一下 Echarts 的例子

**Comment by swuecho** [comment]
echarts 代码

```js
let table_html = // your table in html.

      let dataView = {
        show: true,
        readOnly: true,
        optionToContent: function (opt) {
          let dataview = opt.toolbox[0].feature.dataView
          let table =
            '<div style="position:absolute;top: 5px;left: 0px;right: 0px;line-height: 1.4em;text-align:center;font-size:14px;">' +
            dataview.title +
            '</div>'

          table += table_html
          return table
        }
      }
      option.toolbox.feature.dataView = dataView
      return option
```

**Comment by sunhailin-Leo** [comment]
@swuecho 我的意思是看一下图的效果～

**Comment by swuecho** [comment]
效果就是显示 table_html 的内容，而不是显示默认的 tsv。

**Comment by sunhailin-Leo** [comment]
* 默认的 tsv 是什么？
* table_html ，你指的是现在 pyecharts 的 Table 图么？

**Comment by swuecho** [comment]
> * 默认的 tsv 是什么？
默认显示的dataview

> * table_html ，你指的是现在 pyecharts 的 Table 图么？
不是，是用 data 自己生成的table_html. 从  data -> table_html 这一步自己可以定制。这一步完全可以用python 来写。

**Comment by swuecho** [comment]
默认的
<img width="609" alt="Screen Shot 2019-11-08 at 1 36 29 PM" src="https://user-images.githubusercontent.com/666683/68452240-d72ba600-022c-11ea-9c0b-7a0b300e32da.png">

定制的
<img width="551" alt="Screen Shot 2019-11-08 at 1 26 55 PM" src="https://user-images.githubusercontent.com/666683/68452245-dbf05a00-022c-11ea-9aac-a5fca897d5f5.png">

两个图的数据不一样，请忽略。

**Comment by sunhailin-Leo** [comment]
@swuecho 
* 早给图就好啦 😆 让我想了好半天是个啥。。

**Comment by sunhailin-Leo** [comment]
@swuecho 我大概知道要怎么弄，下一版本更新～

**Comment by sunhailin-Leo** [comment]
@swuecho 
* 如果你着急要用的话我给个提示你：
![image](https://user-images.githubusercontent.com/17564655/68452627-0f7fb400-022e-11ea-9e2d-a942245223c6.png)
* 给 `ToolBoxFeatureOpts` 的 `data_view` 传一个 dict 就好了，然后你自定义的 js 代码用 pyecharts 的 JsCode 类型包装一下，应该是没问题的～只要 dict / json 的 key 符合 echarts 的即可。

**Comment by sunhailin-Leo** [comment]
* Echarts Doc: https://www.echartsjs.com/zh/option.html#toolbox.feature.dataView

**Comment by sunhailin-Leo** [comment]
@swuecho 
* 大概就是这块变成 `dict`
![image](https://user-images.githubusercontent.com/17564655/68452748-6f765a80-022e-11ea-8572-9e955766464f.png)

**Comment by swuecho** [comment]
多谢。我是在前端做的，看到这个issue 就凑凑热闹。

**Comment by sunhailin-Leo** [comment]
没事～ 我们也有很多 `echarts` 的配置没有加进去～ 只能不断的扩展～
