### ISSUE TITLE
当‘geo_cities_coords’生效时，Geolines的多例模式出现部分参数失效

### ISSUE THREAD

**Issue by IMYR666** [pyecharts/pyecharts#636]
**问题**
当‘geo_cities_coords’生效时，Geolines的多例模式的label_color字段失效,并且图例的个数也不正确

**运行环境（系统环境及 pyecharts 版本）**
 window10+python 3.6.3

**代码及截图**

`def geolines_demo():
    style = Style(
        title_top="#fff",
        title_pos="center",
        width=1200,
        height=600,
        background_color="#404a59"
    )
    style_geo = style.add(
        is_label_show=True,
        line_curve=0.2,
        line_opacity=0.6,
        legend_text_color="#eee",
        legend_pos="right",
        geo_effect_symbol="plane",
        geo_effect_symbolsize=15,
        geo_effect_color="#123456",
        geo_cities_coords={"自定义1": [125.260335, 43.806909], "自定义2": [114.267795, 30.375808]},
        label_color=['#a6c84c', '#ffa022', '#46bee9'],
        label_pos="right",
        label_formatter="{b}",
        label_text_color="#eee"
    )
    custom_1 = [
        ["自定义1", "上海", 10],
        ["自定义1", "北京", 20],
        ["自定义1", "南京", 30],
        ["自定义1", "重庆", 40],
        ["自定义1", "兰州", 50],
        ["自定义1", "杭州", 60],
    ]
    custom_2 = [
        ["自定义2", "无锡"],
        ["自定义2", "合肥"],
        ["自定义2", "南京"],
        ["自定义2", '西安'],
        ["自定义2", "大理"],
        ["自定义2", "郑州"]
    ]

    geolines = GeoLines("GeoLines 示例", **style.init_style)
    geolines.add("custom_1", custom_1, **style_geo)
    geolines.add("custom_2", custom_2, **style_geo)
    geolines.render("geoline_demo.html")
`

![image](https://user-images.githubusercontent.com/17697010/43129731-a644a480-8f67-11e8-905b-6d0f15ce7e44.png)

**Comment by chenjiandongx** [comment]
已修复
