### ISSUE TITLE
No coordinate is specified for 甘南

### ISSUE THREAD

**Issue by wz30** [pyecharts/pyecharts#637]
**问题**
前提准备： unicode + package(maps)
有些地区名没有坐标（No coordinate is specified for 甘南）
Q1 是库里真的没有吗？？
Q2 怎么查看库里有哪些地区？？

**运行环境（系统环境及 pyecharts 版本）**
window 10 + python 3.6.3+ pyecharts (latest version)

**代码及截图**
![errorechart](https://user-images.githubusercontent.com/27601987/43159001-22993730-8f4f-11e8-8da0-763c0ad2fd74.PNG)

**Comment by chenjiandongx** [comment]
@wz30 

地区的信息都在这里 https://github.com/pyecharts/pyecharts/blob/master/pyecharts/datasets/city_coordinates.json

**Comment by zaishijizhidian** [comment]
我发现城市的city_coordinates.json中有几个特别尴尬的现象：
所有的城市没有添加‘市’，结果报错
No coordinate is specified for  xx
比如，搜索 
广安，搜索结果为0
广安市，搜索结果为 1，
于是我把所有的尝试前面加上“市”
结果还是报同样的错误：
No coordinate is specified for  xx
比如，菏泽市
菏泽，搜索结果为 1
菏泽市，搜索结果为0

该怎么解决这种问题呢？

**Comment by chfw** [comment]
修改 city_coordinates.json ，然后提到 PR
