### ISSUE TITLE
can‘t install echarts-china-counties-pypkg

### ISSUE THREAD

**Issue by 4timespassedCET4** [pyecharts/pyecharts#640]
**问题**

![qq 20180726173726](https://user-images.githubusercontent.com/39053129/43254798-bd1ea86a-90fa-11e8-8681-4e57a1fd3973.png)
使用教程上的命令安装地图包时其他几个都可以，但4.1M的那个省级市级地图资源则会报错，能够下载下来，但是从报错目录上来看好像是缺少什么文件和路径，请问这是怎么回事呢？
另外在juypter中画地图Out也没有任何图片显示出来

**运行环境（系统环境及 pyecharts 版本）**
win10+python3.6.4+pyecharts0.5.5

**代码及截图**

**Comment by chenjiandongx** [comment]
@4timespassedCET4 加上 -U 参数试试

**Comment by 4timespassedCET4** [comment]
![0](https://user-images.githubusercontent.com/39053129/43297462-1d3eeed8-9184-11e8-9740-5ba218be4d82.png)
谢谢回复，不过好像还是不可以

**Comment by chenjiandongx** [comment]
那加上 --no-cache-dir 试试

**Comment by 4timespassedCET4** [comment]
可以下载下来，不过安装还是出现一样的错误

![00](https://user-images.githubusercontent.com/39053129/43297702-683e6246-9185-11e8-9060-4cd6435c0746.png)

**Comment by chenjiandongx** [comment]
你 pip 的版本是多少

**Comment by 4timespassedCET4** [comment]
pip 18.0

**Comment by chenjiandongx** [comment]
python -m pip install pip==10.0.1

**Comment by chenjiandongx** [comment]
更新为 10.0.1 试试

**Comment by 4timespassedCET4** [comment]
0.0好的，我自己在试试吧，谢谢作者回复！

**Comment by 4timespassedCET4** [comment]
@fundviz 谢谢！

**Comment by sunyinggang** [comment]
@4timespassedCET4 你的问题解决了么？？我也遇到了相同的问题，上面的解决办法都不好使，另外 @fundviz 你说的是卸载anaconda环境么，我并没有在我的电脑中找到此文件

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/43324256-41db1142-91e6-11e8-8e23-88c5377aaccf.png)

我都觉得是 python 环境的问题

**Comment by sunyinggang** [comment]
你这个安装成功了，我应该重新安装python么？这会对我之前的项目产生影响么？安装什么样的python环境才算是一个成功的环境 @chenjiandongx

**Comment by chenjiandongx** [comment]
[echarts_china_counties_pypkg-0.0.1-py3-none-any.zip](https://github.com/pyecharts/pyecharts/files/2235968/echarts_china_counties_pypkg-0.0.1-py3-none-any.zip)

下载这个 zip 包，解压后 pip 安装里面的 whl 包试试看

**Comment by chenjiandongx** [comment]
@sunyinggang @4timespassedCET4

**Comment by sunyinggang** [comment]
可以安装成功！thanks @chenjiandongx

**Comment by 4timespassedCET4** [comment]
@chenjiandongx @sunyinggang 你们都可以下这个zip包吗，我的怎么打不开，下载不了0.0

**Comment by sunyinggang** [comment]
可以的 @4timespassedCET4

**Comment by chenjiandongx** [comment]
@4timespassedCET4 你邮箱多少，我发给你测试一下，如果可以的话我就把 pypi 上的包更新一下

**Comment by fundviz** [comment]
我情况是这样的，我最开始家里的电脑用 anaconda的terminal安装echarts-china-counties-pypkg ，死活安装不了，后来我重新安装了python3.7， 然后在win10自带terminal再安装一次就可以了。所以现在的情况是，如果我用anaconda直接run， 是生成不了map的，但是在terminal 直接用Python xxxx 是可以生成的。 但是这样的方法用于我公司的电脑是无效的。。。不过可以确定的是部署环境问题

**Comment by chenjiandongx** [comment]
这个包确实在 anaconda 环境下有问题 你可以试试在 anaconda 环境下安装我上面提供的新包 确认一下有没有问题 我打算更新一下 pypi 上的 whl 包

**Comment by 4timespassedCET4** [comment]
@chenjiandongx 谢谢谢谢，我的邮箱 254712190@qq.com

**Comment by chenjiandongx** [comment]
@4timespassedCET4 发送了

**Comment by 4timespassedCET4** [comment]
@chenjiandongx  whl文件也不行...，ERROE[2], No such file or directory,,应该真是我环境的问题

**Comment by chfw** [comment]
`pip install echarts-china-counties-pypkg==0.0.2`

**Comment by 4timespassedCET4** [comment]
@chfw thanks so much! I finally can install this package!!!

**Comment by chenjiandongx** [comment]
@4timespassedCET4 是文件名过长的问题，把文件名缩短了再打个包就 ok 了

**Comment by chfw** [comment]
能复现了。问题是这样的：

全局环境下，jupyter-notebook已经装上了，可以在虚拟环境下( virtualenv ), jupyter 没有装。也就是说 jupyter 不出现在 `pip freeze`输出中。由于这个原因：所有的 pyecharts 扩展是不会给全局的 jupyter-notebook 装的。同时，很有趣的是，全局和虚拟环境下的 jupyter-notebook 共享所有的扩展。这就照成了一个谜团：jupyter-notebook 可以用，但是就是装不上。
