### ISSUE TITLE
Add line width in graph function to customize the graph (network) edge weight

### ISSUE THREAD

**Issue by Jiannan28** [pyecharts/pyecharts#641]
When creating graph (network), sometimes we need to customize the edge width. The edge width stands for how many times two nodes co-occurrence. For example, node A and B co-occur 100 times and node B and C co-occur 500 times, then the edge (link) width between B and C is five times thicker than A and B. 

However, currently in the graph function (according to the API document), there is no width options.In links, the value option is for edge length but not width.

**Comment by iry-lee** [comment]
I have this problem too...

**Comment by zicoal** [comment]
is this problem solved?
I have the same issue....

**Comment by ZiyuBao** [comment]
LineStyleOpts now has it. In versions later than v1.0
