### ISSUE TITLE
轴标签旋转后显示设置问题

### ISSUE THREAD

**Issue by TheKiteRunning** [pyecharts/pyecharts#643]
**问题**

如果数据量比较多，常用到轴标签旋转功能。此时，如果标签名较长，无法正常显示完全。如果开通datazoom，即使标签名不长，二者也会重合。

顺便：微信不太方便办公用，毕竟更多情况下用电脑，请问有没有考虑开个qq群，谢谢。

**运行环境（系统环境及 pyecharts 版本）**

windows 8.1 64bit
anocanda python 3.6
jupyter notebook 5.0.0
pyecharts version 0.5.5

**代码及截图**

from pyecharts import Bar

```python
bar = Bar("我的第一个图表", "这里是副标题")
bar.add("服装", ["衬衫", "羊毛衫", "雪纺衫长得放不下怎么办", "裤子", "高跟鞋", "袜子"], [5, 20, 36, 10, 75, 90],is_datazoom_show=True,xaxis_rotate=90)
# bar.print_echarts_options() # 该行只为了打印配置项，方便调试时使用
bar
```
![image](https://user-images.githubusercontent.com/24802332/43355213-4a0d2daa-928b-11e8-9daf-6dd76c4a13b6.png)

**Comment by fundviz** [comment]
刚刚遇到一样的问题，太巧了

**Comment by chenjiandongx** [comment]
把角度调成 45 度试试看？

**Comment by chenjiandongx** [comment]
dataZoom 条的位置可以通过 Grid 类来调

**Comment by TheKiteRunning** [comment]
1. 旋转45度只是长度变成原来的0.707，不能适用于所有问题。
2. grid摸了一下，这个类似是matplotlib的subplot对吗？您的意思是类似于建立一个subplot(1,1,1)，然后设置ax的方式来操控dataframe的位置对吧？但是没有看到datazoom position的设置项啊。

谢谢

**Comment by fundviz** [comment]
![frontpage](https://user-images.githubusercontent.com/27722028/43440986-d982142c-94cb-11e8-8f92-7e00b0543964.jpg)
这个是用pyecharts生成的图片，link: https://thepapers.cn

主要是label太长被挡住了

**Comment by chenjiandongx** [comment]
新鲜出炉的文档

![image](https://user-images.githubusercontent.com/19553554/43446784-5be398f4-94dc-11e8-9415-0fa35cb17bdd.png)

![2018-07-31_16-06-50](https://user-images.githubusercontent.com/19553554/43446550-c3756fde-94db-11e8-81fd-b7c202306858.gif)

**Comment by chenjiandongx** [comment]
一直我都只是说可以 Grid 解决，但看起来大家好像都不知道怎么具体操作，就写份 demo 供大家参考

**Comment by fundviz** [comment]
fixed 成功！！

**Comment by chenjiandongx** [comment]
:smile:
