### ISSUE TITLE
Change default color list in graph/network visualisation when using categories

### ISSUE THREAD

**Issue by Jiannan28** [pyecharts/pyecharts#644]
When creating graph/network visualisations with categories, the colors used by different categories on the nodes are defined by the default color list in the javascript generated : 
"color": [
        "#c23531", 
        "#2f4554", 
        "#61a0a8", 
        "#d48265", 
        "#749f83", 
        "#ca8622", 
        "#bda29a", 
        "#6e7074", 
        "#546570", 
        "#c4ccd3", 
        "#f05b72", 
        "#ef5b9c", 
        "#f47920", 
        "#905a3d", 
        "#fab27b", 
        "#2a5caa", 
        "#444693", 
        "#726930", 
        "#b2d235", 
        "#6d8346", 
        "#ac6767", 
        "#1d953f", 
        "#6950a1", 
        "#918597", 
        "#f6f5ec"
    ], 
Can we change the list of colors before generating the javascript file? it will be much more customized.

**Comment by chenjiandongx** [comment]
`label_color` is a global parameter, you can adjust it to change the color lists

**Comment by Jiannan28** [comment]
Thx :+1:  it works perfectly now.
