### ISSUE TITLE
ThemeRiver使用模板类和直接渲染图不一致

### ISSUE THREAD

**Issue by fan1018wen** [pyecharts/pyecharts#647]
在使用pyecharts的过程中，发现ThemeRiver使用模板类和直接render()图形会不一致，模板类会突出一部分，请问是什么原因，data中各部分数据各项数据累计和等于1。
![default](https://user-images.githubusercontent.com/8422667/43394941-eeed5292-942e-11e8-9cb6-c4f8171e69b0.jpg)
![render](https://user-images.githubusercontent.com/8422667/43394943-efe44200-942e-11e8-8d4e-87123190c120.jpg)

代码如下：
        tr = ThemeRiver
        tr.add(‘test'’,data)
        config = PyEchartsConfig(jshost='https://cdn.bootcss.com/echarts/3.6.2')
        env = EchartsEnvironment(pyecharts_config=config)
        
        tpl = env.get_template('tpl_demo.html')
        html = tpl.render(tr=tr)
        write_utf8_html_file('my_tpl_demo2.html', html)#使用模板
        tr.render()#直接渲染

**Comment by chenjiandongx** [comment]
@kinegratii 这问题有点奇怪，你看一下

**Comment by kinegratii** [comment]
@chenjiandongx 好的

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！不再使用模板类啦

**Comment by rayluo** [comment]
@chenjiandongx 然而在新版中应该怎样使用自定义模板呢? 网上找到的转载博文基本上都是基于0.5版. 好不容易找到的[这个](https://pyecharts.org/#/zh-cn/web_flask?id=flask-%e6%a8%a1%e6%9d%bf%e6%b8%b2%e6%9f%93)又依赖于flask. 如果不使用flask应该怎样定制模板呢? Thanks!
