### ISSUE TITLE
想自定義Ｘ軸座標

### ISSUE THREAD

**Issue by Scovin** [pyecharts/pyecharts#648]
**问题**
想請問當Ｘ軸變數很多的時候，有沒有可以自定義Ｘ座標軸？

**运行环境（系统环境及 pyecharts 版本）**
mac 

**代码及截图**

<img width="959" alt="2018-08-01 11 02 24" src="https://user-images.githubusercontent.com/33141724/43498734-d438669c-957a-11e8-917b-e44f29a32c25.png">

**Comment by chenjiandongx** [comment]
@Scovin 可以试一下这个

![image](https://user-images.githubusercontent.com/19553554/43516968-bc1df0d8-95b9-11e8-9867-eb84e0b9be0c.png)

**Comment by Scovin** [comment]
@chenjiandongx 
我有試過，不過還是無法呈現我想要的Ｘ軸標籤
下圖我想用pyecharts呈現
![image](https://user-images.githubusercontent.com/33141724/43557769-dafd6982-9638-11e8-940c-911398007281.png)

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/43558986-8c0954de-963e-11e8-8da0-6c084a553260.png)

你能把你所有具体设置的参数都给出来吗
