### ISSUE TITLE
x轴怎么样设置长度，字符过长就会被合并，x轴只显示部分，怎么解决

### ISSUE THREAD

**Issue by wufan0115** [pyecharts/pyecharts#649]
**问题**

### x轴怎么样设置长度，字符过长就会被合并，x轴只显示部分，怎么解决

**运行环境（系统环境及 pyecharts 版本）**
* win8环境
* 0.56

**代码及截图**
### 代码如下：
attr = ['1111111', '2222222', '33333333', '44444444', '555555555', '66666666', '7777777', '888888', '999999999']    #这样X坐标就是星期
v1 = [35.5, 35.5, 35.5, 35.5, 35.5, 37.0, 37.0, 37.0, 37.0]
v2 = [22.57, 22.58, 26.89, 26.85, 26.72, 30.71, 30.03, 30.01, 29.92]
v3 = [12.93, 12.92, 8.6, 8.65, 8.78, 6.29, 6.97, 6.99, 7.07]

bar = Line("test", "testxxx")        
bar.add("heap_size", attr, v1, label_color=['#B22222'], mark_line=["average"], mark_point=["max", "min"])    
bar.add("heap_alloc", attr, v2, label_color=['#008080'], mark_line=["average"], mark_point=["max", "min"])
bar.add("heap_free", attr, v3, label_color=['#483D8B'], mark_line=["average"], mark_point=["max", "min"])
bar.use_theme("vintage")
bar.render('test2.html')
make_a_snapshot('test2.html', 'snapshot2.png')

###截图如下：
![image](https://user-images.githubusercontent.com/22274031/43507506-eab6c9b6-959f-11e8-9457-e946ee15d315.png)

**Comment by chenjiandongx** [comment]
https://github.com/pyecharts/pyecharts/issues/643 可以参考一下这个

**Comment by wufan0115** [comment]
我找到配置说明了 http://pyecharts.org/#/zh-cn/charts ，问题已解决 在add（）中添加 xaxis_interval=0 参数，强制要求全部显示，但需要控制字符长度，不然容易显示不全。

**Comment by chenjiandongx** [comment]
可以旋转一下角度

**Comment by wufan0115** [comment]
嗯 加了参数 转了90度
