### ISSUE TITLE
echarts.min不加载

### ISSUE THREAD

**Issue by JackyQQQu** [pyecharts/pyecharts#650]
**问题**
echarts.min不加载，在加载文件.jupyter\nbconfig\notebook.json中也没有，
所以http://localhost:8888/nbextensions/echarts/echarts.min.js也是404的，
但是是确认已经安装了jupyter-echarts-pypkg，也卸载重装了几次依然没有反应，
装其他地图库可以正常加载，
导致在jupyter中图表不显示，
不知道该怎么解决。

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 0.5.6
python 3.6.2

**代码及截图**
![image](https://user-images.githubusercontent.com/34271296/43511019-e7ffc1f0-95a9-11e8-87c9-8b5f00e83a95.png)
![image](https://user-images.githubusercontent.com/34271296/43511033-f532daba-95a9-11e8-98e4-6d818f7729ee.png)
![image](https://user-images.githubusercontent.com/34271296/43511054-06c7a698-95aa-11e8-8a97-a4553e6e33b4.png)

**Comment by chfw** [comment]
juypter nbetension list does not contain jupyter-echarts. please re-install jupyter-echarts-pypkg

**Comment by JackyQQQu** [comment]
是的我知道是这个原因，但是upyter-echarts-pypkg和pyecharts本身都卸载重装了很多遍还是这样，不知道为什么

**Comment by chfw** [comment]
在 jupyter-echarts-pypkg 装的时候，在同一个python环境里需要有jupyter notebook.如果没有，就不会给jupyter notebook装扩展。

**Comment by JackyQQQu** [comment]
是在同一个python环境里的，后面我装地图如echarts-countries-pypkg时都可以正常加载，只有这个jupyter-echarts-pypkg不行，我甚至去jupyter里的terminal里重装了两次，其他的地图库都可以正常，只有这个主图表的库不行。。。。

**Comment by chfw** [comment]
`jupyter --path`, 顺便给我个输出

在用户数据的文件夹找nbextensions文件夹，然后寻找 echarts-countries-pypkg, jupyter-echarts-pypkg.

**Comment by JackyQQQu** [comment]
![image](https://user-images.githubusercontent.com/34271296/43516359-f474a186-95b7-11e8-9127-0a7e4b55cfb0.png)
![image](https://user-images.githubusercontent.com/34271296/43516363-fabd6154-95b7-11e8-98ef-1e7b036cc9fb.png)
![image](https://user-images.githubusercontent.com/34271296/43516413-25b5c4dc-95b8-11e8-9e09-c6d20953d364.png)
![image](https://user-images.githubusercontent.com/34271296/43516475-43a98532-95b8-11e8-8966-a88edd8de20c.png)
是这些吗

**Comment by JackyQQQu** [comment]
和装echarts-countries-pypkg同样方法重装jupyter-echarts-pypkg好几次就是不出现在nbextensions里，

**Comment by chfw** [comment]
这个截图说明：jupyter-echarts-pypkg没有被装在jupyter notebook里。如果装上了，会出现在 jupyter/nbextensions文件夹里

请重装 juypter-echarts-pypkg, 然后给我log 看看

**Comment by chenjiandongx** [comment]
@JackyQQQu 你 virtualenv 新建一个虚拟环境，激活，然后试试
```
pip install notebook
pip install pyecharts -U
```

**Comment by JackyQQQu** [comment]
![image](https://user-images.githubusercontent.com/34271296/43517076-173201ee-95ba-11e8-93f5-54347d96032a.png) 刚才重装的截图

**Comment by JackyQQQu** [comment]
图老是传不上去。。。
@chenjiandongx 似乎还是一样
![20180801183745](https://user-images.githubusercontent.com/34271296/43518166-bfea2d40-95bd-11e8-83c7-bfb151a30897.png)
![image](https://user-images.githubusercontent.com/34271296/43518175-c641204a-95bd-11e8-9930-71c35a810dbd.png)

**Comment by chfw** [comment]
先用下面命令救急

```
jupyter nbextension install --user "C:\用户\Data Analysis\AppData\Local\....\site-packages\jupyter_echarts_pypkg\resources\echarts\"

jupyter nbextension enable echarts/main --user
```

我的线下看看能能浮现你的问题。你的pip 版本是多少？

**Comment by chfw** [comment]
绝对路径你得自己填。

**Comment by JackyQQQu** [comment]
@chfw 非常感谢，公司停电了，我没法直接查看，但是周一刚更新了一下pip，所以应该是18.0

**Comment by chfw** [comment]
能复现了。问题是这样的：

全局环境下，jupyter-notebook已经装上了，可以在虚拟环境下( virtualenv ), jupyter 没有装。也就是说 jupyter 不出现在 pip freeze输出中。由于这个原因：所有的 pyecharts 扩展是不会给全局的 jupyter-notebook 装的。同时，很有趣的是，全局和虚拟环境下的 jupyter-notebook 共享所有的扩展。这就照成了一个谜团：jupyter-notebook 可以用，但是就是装不上。

#640

**Comment by JackyQQQu** [comment]
@chfw 不好意思，回复提醒的邮件没看到，你说到‘所有的 pyecharts 扩展是不会给全局的 jupyter-notebook 装的‘，我当时的一个情况是除了jupyter-echarts-pypkg，其他地图的扩展都可以安装并成功加载，不知道为什么。

**Comment by cloudpanl** [comment]
我也出现这种情况，echarts-china-cities-pypkg安装都是成功的，就是jupyter-echarts-pypkg装不上，我是在anaconda的base虚拟环境下装的，jupyter notebook输出的html显示没问题，但是notebook显示的是空白，echarts.min.js打开是404，请问有办法可以解决吗？

(base) C:\Users\Administrator>pip install jupyter-echarts-pypkg
Requirement already satisfied: jupyter-echarts-pypkg in c:\programdata\anaconda3
\lib\site-packages (0.1.2)
Requirement already satisfied: pyecharts-jupyter-installer==0.0.3 in c:\programd
ata\anaconda3\lib\site-packages (from jupyter-echarts-pypkg) (0.0.3)
Requirement already satisfied: lml==0.0.2 in c:\programdata\anaconda3\lib\site-p
ackages (from jupyter-echarts-pypkg) (0.0.2)

但是pip freeze查到有jupyter-echarts-pypkg==0.1.2和jupyter
(base) C:\Users\Administrator>pip freeze |findstr jupy
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyter-echarts-pypkg==0.1.2
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
pyecharts-jupyter-installer==0.0.3

**Comment by chfw** [comment]
try:

`pip install jupyter-echarts-pypkg --no-cache-dir`

pip 会在本地留一个wheel cache。而wheel cache 是不运行 pyecharts-jupyter-installer 的。换句话说，只有从pypi 下载的tar.gz 会给 jupyter 装，pip 产生的 wheel cache 是不会装的。

**Comment by cloudpanl** [comment]
试了，依然报错：
`(base) C:\Users\Administrator>pip install jupyter-echarts-pypkg --no-cache-dir
Requirement already satisfied: jupyter-echarts-pypkg in c:\programdata\anaconda3
\lib\site-packages (0.1.2)
Requirement already satisfied: pyecharts-jupyter-installer==0.0.3 in c:\programd
ata\anaconda3\lib\site-packages (from jupyter-echarts-pypkg) (0.0.3)
Requirement already satisfied: lml==0.0.2 in c:\programdata\anaconda3\lib\site-p
ackages (from jupyter-echarts-pypkg) (0.0.2)`

**Comment by chfw** [comment]
Pip uninstall jupyter-echarts-pypkg first please.

**Comment by cloudpanl** [comment]
解决了，谢谢

**Comment by zxdvd** [comment]
linux系统上，如果安装jupyter pyecharts的不是同一个用户也会出现这个问题，比如我是root用户直接pip全局安装的，然后这些js文件是在`/root/.local/share/jupyter/nbextensions/echarts`下面，但是我是用普通用户启动jupyter的，这样它会在普通用户的`.local/share/jupyter/nbextensions/echarts`目录里找js文件，然后就404了。我从root用户哪里拷贝过去就ok了.

**Comment by chfw** [comment]
是的。在装的时候，jupyter notebook 给两个选择：给当前用户装，和全局装。pyecharts-jupyter-installer 选了前者。
