### ISSUE TITLE
x轴和y轴转换后，y轴刻度显示问题

### ISSUE THREAD

**Issue by Leno730** [pyecharts/pyecharts#653]
**问题**
我用官方的例子测试x轴和y轴转换，但是得出来的结果跟官方文档的不一样，转换后的y轴是随机产生的数值。

**运行环境（系统环境及 pyecharts 版本）**
win7x64
pycharm2017.3
python2.7
pyecharts0.5.6

**代码及截图**
代码：
attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 75, 90]
v2 = [10, 25, 8, 60, 20, 80]
bar = Bar("x 轴和 y 轴交换")
bar.add("商家A", attr, v1)
bar.add("商家B", attr, v2, is_convert=True, yaxis_interval=0)
bar.render(r"test_chart.html")
//预想的结果，Y轴刻度应该显示的是attr里面的内容啊
结果：
![image](https://user-images.githubusercontent.com/19988976/43635041-85959cc2-9740-11e8-82d5-991d41a2107a.png)

**Comment by chenjiandongx** [comment]
@Leno730 Echarts 的锅

https://github.com/apache/incubator-echarts/issues/8807

**Comment by Leno730** [comment]
@chenjiandongx  有什么备选方案可以解决这个问题么？除了降低版本。

**Comment by ldfengl4j** [comment]
pip install jupyter-echarts-pypkg==0.1.1 后生成的网页中数据没问题了，但是在jupyter上显示的依然是数字

**Comment by IanVzs** [comment]
多谢

**Comment by smartsl** [comment]
我也遇到这个问题，降级jupyter-echarts-pypkg从0.1.2到0.1.1后解决

**Comment by chfw** [comment]
0.1.2: echarts 4.1.0
0.1.1: echarts 4.0.4

**Comment by chenjiandongx** [comment]
Notebook 还是不能正常显示标签名称的可以尝试使用一下命令
```
$ pip uninstall jupyter-echarts-pypkg
$ pip install jupyter-echarts-pypkg==0.1.1 -U --no-cache-dir
```

**Comment by gaoyangxiaozhu** [comment]
still not work, as shown in snapshot:

![image](https://user-images.githubusercontent.com/9858245/46122208-1f1a8400-c24a-11e8-8210-07496594c751.png)

@chenjiandongx

**Comment by Allenhui89** [comment]
用 line 的时候，在add中使用方法is_convert=True  发现x、y轴交换之后线条就没有了，请问这是什么原因呢？

**Comment by rosered90** [comment]
> still not work, as shown in snapshot:
> 
> ![image](https://user-images.githubusercontent.com/9858245/46122208-1f1a8400-c24a-11e8-8210-07496594c751.png)
> 
> @chenjiandongx

还是用echarts吧

**Comment by pyqf66** [comment]
官方jupyter-echarts-pypkg已经升级了很久了吧，是不是解决了这个问题呢，另外Pyecharts是否也可以根据这个版本更新一下，其他bug还好，这个bug太致命了

**Comment by zhouweyi** [comment]
@chenjiandongx 
![7H7DITD2~1~F_)02`_{VNT4](https://user-images.githubusercontent.com/48702540/54577363-76015900-4a36-11e9-9796-98c223f7a57e.png)

pip install jupyter-echarts-pypkg==0.1.1后并没有什么用，什么时候可以解决这个问题，有没有什么办法可以处理

**Comment by zhouweyi** [comment]
这个问题的解决办法是：
第一步：pip uninstall pyecharts(即移除自己安装的pyecharts)
第二步:  pip install pyecharts==0.5.6(安装0.5.6版本的pyecharts，默认安装jupyter-echarts-pypkg==0.1.2)
第三步：pip uninstall jupyter-echarts-pypkg(默认安装)
第四步:  pip install jupyter-echarts-pypkg==0.1.1

完成后jupyter上Y轴标签仍会显示索引值，但生成HTML是你想要的标签

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！该问题彻底修复啦
