### ISSUE TITLE
渲染图片缺少数字

### ISSUE THREAD

**Issue by wcc526** [pyecharts/pyecharts#654]
**问题**

![bar](https://user-images.githubusercontent.com/2942718/43640094-108473d4-9751-11e8-98ab-16bd8f7e4aab.png)

渲染图片显示出错

**运行环境（系统环境及 pyecharts 版本）**

centos,最新pyecharts,mac 下显示正常

**代码及截图**

**Comment by SKingMonkey** [comment]
同样遇到

**Comment by chenjiandongx** [comment]
@wcc526 请更新到 V0.5.7+，问题已经解决

![snapshot](https://user-images.githubusercontent.com/19553554/44008300-9feb6cfa-9ed4-11e8-8192-57415eb8bbf7.png)
