### ISSUE TITLE
如何使用当前工程内的自定义主题

### ISSUE THREAD

**Issue by zrhett** [pyecharts/pyecharts#655]
请问，如果有个自定义主题（既不是pyecharts自带主题，也不是 echarts-themes-pypkg 中提供的自定义主题），比如从echarts官网主题构建工具下载的主题文件：westeros.js，放在当前工程文件夹内，如何加载呢？
我尝试了：configure(jshost='当前文件夹', global_theme='westeros')，没有效果。

**Comment by chfw** [comment]
我们还没有想过自定义的主题

**Comment by zrhett** [comment]
主题构建工具地址： http://echarts.baidu.com/theme-builder/
左侧栏可以选择主题方案、修改配置、自定义名称，点下载后得到自定义的主题文件：**.js或**.json。
![image](https://user-images.githubusercontent.com/16285731/43694046-ef4c2c38-9963-11e8-84a9-0012a2dbc460.png)

**Comment by chfw** [comment]
![screen shot 2018-08-11 at 23 51 40](https://user-images.githubusercontent.com/4280312/43996756-a132b474-9dc1-11e8-9a79-b6dc07621028.png)
![screen shot 2018-08-11 at 23 51 20](https://user-images.githubusercontent.com/4280312/43996763-b2d86b10-9dc1-11e8-9b49-65c7ce763328.png)
![screen shot 2018-08-11 at 23 51 05](https://user-images.githubusercontent.com/4280312/43996764-b92c3186-9dc1-11e8-97c4-3986810335ea.png)

**Comment by chenjiandongx** [comment]
@zrhett V0.6.0 可用

![image](https://user-images.githubusercontent.com/19553554/44004972-27170978-9e9e-11e8-92ce-524ff4d20eeb.png)

**Comment by chenjiandongx** [comment]
V0.5.8 已发布，欢迎使用
