### ISSUE TITLE
WordCloud在jupyter notebook中不显示图片

### ISSUE THREAD

**Issue by point6013** [pyecharts/pyecharts#658]
**问题**
WordCloud在jupyter notebook中不显示图片

**运行环境（系统环境及 pyecharts 版本）**
window10，python3.6.2，pyecharts 0.5.6， pyecharts-jupyter-installer 0.0.3，

**代码及截图**

![image](https://user-images.githubusercontent.com/15711752/43812813-a20dd532-9af5-11e8-815e-95384edeb6e8.png)

**Comment by chenjiandongx** [comment]
pip install jupyter-echarts-pypkg==0.1.1

然后重启 notebook 试试

**Comment by chenjiandongx** [comment]
嗯没事 解决了就好
