### ISSUE TITLE
如何设置坐标轴的颜色？

### ISSUE THREAD

**Issue by youyoude** [pyecharts/pyecharts#660]
**问题**
如何设置坐标轴的颜色？想让坐标轴的颜色浅一点

**运行环境（系统环境及 pyecharts 版本）**
Linux  pyecharts (0.3.1)

**代码及截图**

line = Line("折线图示例")
line.add("商家A", attr, v1,
            mark_point=["average", {
                "coord": ["裤子", 10], "name": "这是我想要的第一个标记点"}])
line.add("商家B", attr, v2, is_smooth=True,
            mark_point=[{
                "coord": ["袜子", 80], "name": "这是我想要的第二个标记点"}])
line.render()

**Comment by chenjiandongx** [comment]
指的是坐标轴标签吗

**Comment by youyoude** [comment]
不是， 是 坐标轴本身的颜色。

**Comment by youyoude** [comment]
https://blog.csdn.net/flygoa/article/details/52922266
实现类似这样效果

**Comment by chenjiandongx** [comment]
下个版本开始可以
