### ISSUE TITLE
小数数值精度问题(如何强制显示两位有效数字)

### ISSUE THREAD

**Issue by ldfengl4j** [pyecharts/pyecharts#662]
设置的值为小数时，显示的时候想保留传入时候的精度，即两位有效数字，有办法么。

`from pyecharts import Bar,Grid

attr = ["aa", "bb", "Diabetes Mellitus Requiring Medication", "d", "e", "fff"]
v1 = [5.12, 20.85, 36.69, 10.10, 75.20, 90.36]
v2 = [10.00, 25.45, 8.23, 60.00, 20.50, 80.00]
bar = Bar("x 轴和 y 轴交换")
bar.add("商家A", attr, v1,is_label_show=True,label_pos='right')
bar.add("商家B", attr, v2, is_convert=True,is_label_show=True,label_pos='right')
grid = Grid()
grid.add(bar,grid_left='40%')
grid.render("test.html")
grid`

![image](https://user-images.githubusercontent.com/24808965/43950510-09292068-9cc3-11e8-804b-9e8ad432e56a.png)

**Comment by chenjiandongx** [comment]
代码

```python
from pyecharts_javascripthon.dom import window
from pyecharts import Bar, Grid


def custom_formatter(params):
    return window.parseFloat(params.value).toFixed(2)


attr = ["aa", "bb", "Diabetes Mellitus Requiring Medication", "d", "e", "fff"]
v1 = [5.12, 20.85, 36.69, 10.10, 75.20, 90.36]
v2 = [10.00, 25.45, 8.23, 60.00, 20.50, 80.00]
bar = Bar("x 轴和 y 轴交换")
bar.add(
    "商家A",
    attr,
    v1,
    is_label_show=True,
    label_pos="right",
    label_formatter=custom_formatter,
)
bar.add(
    "商家B",
    attr,
    v2,
    is_convert=True,
    is_label_show=True,
    label_pos="right",
    label_formatter=custom_formatter,
)
grid = Grid()
grid.add(bar, grid_left="40%")
grid.render()
```

效果
