### ISSUE TITLE
天津地图没有蓟县，少了一个区

### ISSUE THREAD

**Issue by youngValiant** [pyecharts/pyecharts#667]
**问题**
生成的天津地图少了蓟县区

**运行环境（系统环境及 pyecharts 版本）**
win7+pyecharts0.5.5

**代码及截图**
from pyecharts import Map

value = [200, 380, 240, 120, 55, 155,
         8, 600, 500, 450,
         75, 55, 25, 555,
         9]
attr = ['和平区', '南开区', '河西区', '河东区', '河北区', '红桥区', 
        '北辰区', '东丽区', '西青区', '津南区', 
        '宝坻区', '静海区', '宁河区', '武清区',
        '滨海新区']
map = Map("a", width=800, height=400)
map.add("", attr, value, maptype='天津', is_visualmap=True,
        visual_text_color='#000')
![10](https://user-images.githubusercontent.com/18154684/43997813-cb07a7da-9e18-11e8-8bff-fb4b8ccd1bc4.png)

实际的天津题图是下面的样子：少了画化红圈的部分
******************************************
![12](https://user-images.githubusercontent.com/18154684/43997822-1346b310-9e19-11e8-8d19-c90ea3d1a069.png)

**Comment by chfw** [comment]
transferred to echarts-china-cities-js.

**Comment by lofty77** [comment]
same question

**Comment by chfw** [comment]
https://github.com/echarts-maps/echarts-china-cities-js/issues/3

**Comment by chfw** [comment]
https://github.com/echarts-maps/echarts-china-cities-js/blob/master/geojson/shape-with-internal-borders/tianjin.geojson
