### ISSUE TITLE
如何精确自定义 Geo/Geolines 坐标

### ISSUE THREAD

**Issue by chenjiandongx** [pyecharts/pyecharts#687]
项目地址：https://github.com/pyecharts/geo-region-coords

### pyecharts 自定义坐标

在 [pyecharts](https://github.com/pyecharts/pyecharts) 中，Geo/Geolines 图需要定义地区坐标，由于全国地区众多且多重名，pyecharts 无法精确度较高的区域坐标。pyecharts 中提供自定义坐标的方式有 4 种：

1. **（推荐）** 使用 `geo_cities_coords` 参数，字典类型，如 {'阿城': [126.58, 45.32],}

    coords.txt
    ```
    "北京": [116.407526, 39.90403],
    "北京东城": [116.416357, 39.928353],
    "北京东城东华门": [116.406708, 39.914219],
    "北京东城东华门多福巷": [116.412747, 39.923014],
    "北京东城东华门银闸": [116.406708, 39.914219],
    "北京东城东华门东厂": [116.406708, 39.914219],
    "北京东城东华门智德": [116.404642, 39.918634],
    "北京东城东华门南池子": [116.40318, 39.907837],
    "北京东城东华门黄图岗": [116.410022, 39.920854],
    "北京东城东华门灯市口": [116.414391, 39.918751],
    ```

    **在 coords.txt 中查找对应关键字,复制到 `geo_cities_coords` 参数即可**

2.  **（推荐）** 使用 `add_coordinate()` 方法提供一个自定义坐标

    本质上 `geo_cities_coords` 内部就是调用 `add_coordinate()` 方法
    ```
    add_coordinate(self, name: six.text_type, longitude: float, latitude: float): -> None

    example:
        add_coordinate("某地", 100.0, 20.0)
    ```

3. **（推荐 V0.5.9+）** 使用 `add_coordinate_json()` 方法提供一个自定义坐标 JSON 文件
    ```
    add_coordinate_json(self, json_file: six.text_type): -> None
 
    example:
        add_coordinate_json("my_coords.json")

    # my_coords.json
    {
        "某地": [100.0, 20.0],
        ...
    }
    ```

4. **（不推荐，这种操作方式一旦 pyecharts 更新，坐标会失效）** *Hack* pyecharts 源代码，对应文件位于 `Lib/site-packages/pyecharts/datasets/city_coordinates.json` 具体路径根据操作系统和 Python 环境而定。

    coords.json
    ```
    [
        {"北京": [116.407526, 39.90403]},
        {"北京东城": [116.416357, 39.928353]},
        {"北京东城东华门": [116.406708, 39.914219]},
        {"北京东城东华门多福巷": [116.412747, 39.923014]},
        {"北京东城东华门银闸": [116.406708, 39.914219]},
        {"北京东城东华门东厂": [116.406708, 39.914219]},
        {"北京东城东华门智德": [116.404642, 39.918634]},
        {"北京东城东华门南池子": [116.40318, 39.907837]},
        {"北京东城东华门黄图岗": [116.410022, 39.920854]},
        {"北京东城东华门灯市口": [116.414391, 39.918751]},
        ...
    ]
    ```

    **在 coords.json 中查找对应关键字，补充到 city_coordinates.json 文件中即可**

**Comment by kinegratii** [comment]
The second solution is a bad practice and should be removed. Hack source code is temporary solution and will be invalid when software is upgraded.So it should not appear in official document. 

`geo.add_coordinate` is the only API to import user's cusom geo data.

https://github.com/pyecharts/pyecharts/blob/2577153563be046dcda83cdf7655481dcdd0950e/pyecharts/charts/geo.py#L22-L31

**Comment by chenjiandongx** [comment]
@kinegratii 接受你的建议，会提供一个方法来接受 json 文件。不过在这之前请先 review geo_coords pr

**Comment by chenjiandongx** [comment]
@kinegratii 已更新，你阅读以下
