### ISSUE TITLE
Issue in date heatmap

### ISSUE THREAD

**Issue by adihat** [pyecharts/pyecharts#689]
The following is the code snippet
![screen shot 2018-08-23 at 8 39 05 pm](https://user-images.githubusercontent.com/30288808/44534206-d5072580-a714-11e8-99f5-18b36437a92e.png)

The following is the error trace:
![screen shot 2018-08-23 at 8 43 57 pm](https://user-images.githubusercontent.com/30288808/44534394-4d6de680-a715-11e8-8052-b8850ec3eeab.png)

Code for heatmap:
Issue is in line 40
![screen shot 2018-08-23 at 8 48 55 pm](https://user-images.githubusercontent.com/30288808/44534700-03393500-a716-11e8-8b36-997072aff958.png)

**Comment by chenjiandongx** [comment]
**is_calendar_heatmap**

**Comment by adihat** [comment]
doesn't raise the exception. The HTML generated doesn't display the heatmap

**Comment by chenjiandongx** [comment]
please update pyecharts to the latest version `pip install pyecharts -U` and try again, it may be work

**Comment by adihat** [comment]
@chenjiandongx  I am on the latest version: 0.5.8

**Comment by chenjiandongx** [comment]
Did you use the above code?

**Comment by adihat** [comment]
Yes

**Comment by chenjiandongx** [comment]
@chfw need help

**Comment by chenjiandongx** [comment]
@adihat ok
