### ISSUE TITLE
树图标签如何设置成射线朝外

### ISSUE THREAD

**Issue by czhoucc** [pyecharts/pyecharts#692]
**问题**
树图布局为radial的时候，label如何全部成射线朝外呢？
就像官方例子那样的配置，
https://ecomfe.github.io/echarts-examples/public/editor.html?c=tree-radial&theme=light

**运行环境（系统环境及 pyecharts 版本）**
pyecharts 0.5.8

**代码及截图**

**Comment by chenjiandongx** [comment]
好像它自己就朝外了

![image](https://user-images.githubusercontent.com/19553554/44617350-5f759380-a893-11e8-9538-101f71443492.png)

**Comment by czhoucc** [comment]
左半边是朝里的呀。希望可以实现和官方例子里一样，所有的标签都呈放射状由圆心向外指。

**Comment by chenjiandongx** [comment]
你给的示例都没配置这个，是不是数据量大它就自己调节了。

关于这个的配置项只有

![image_9](https://user-images.githubusercontent.com/19553554/44624264-bfb01800-a91b-11e8-8c21-0f09a4c2d607.png)

**Comment by czhoucc** [comment]
我试着改过tree_label_position, 都没有效果。
另外如果默认是left的话，你的例子里面不是都在右边吗，好像也不对呀。

**Comment by sunhailin-Leo** [comment]
@czhoucc 可以使用新版再次尝试，如果在配置没有问题的情况下，没有达到你想要的效果，那就是 Echarts 那边的功能问题了。 😄
