### ISSUE TITLE
pip install pyecharts meet error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by Ericyuanhui** [pyecharts/pyecharts#697]
**问题**

安装问题，使用pip install pyecharts 的时候出现了，“error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools” 问题，请教大家如何解决的？

**运行环境（系统环境及 pyecharts 版本）**
系统：win10
python 版本：  python3.7
pyecharts 版本： 未知

**代码及截图**
![image](https://user-images.githubusercontent.com/13159415/44636978-24817600-a9e1-11e8-8e84-1c056bf734da.png)

running build_ext
    building 'dukpy._dukpy' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-iio0e_x5\\dukpy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-e3151h8y\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-iio0e_x5\dukpy\

**Comment by Ericyuanhui** [comment]
solve this problem with this link: https://www.scivision.co/python-windows-visual-c++-14-required/
this method for all windows user.

**Comment by Ericyuanhui** [comment]
so close this issue. thank you.

**Comment by chfw** [comment]
Thanks for the solution. We will added it to FAQ.
