### ISSUE TITLE
Overlapping of labels in bar graph

### ISSUE THREAD

**Issue by adihat** [pyecharts/pyecharts#698]
is there a way to autosize the **size for the labels** in the graph to prevent overlapping?
Screenshot for reference:
![screen shot 2018-08-27 at 8 53 49 am](https://user-images.githubusercontent.com/30288808/44639032-57bf0780-a9d7-11e8-8359-179e8f71cb88.png)

The following arguments are used when initializing the bar graph:
{'width': 480, 'height': 300, 'title_pos': 'center', 'title_text_size': 10, 'subtitle_text_size': 9}

The following arguments are used when add data to bar graph:
{'legend_orient': 'horizontal', 'legend_pos': 'center', 'legend_top': 'bottom', 'legend_text_size': 9,
'is_label_show': True, 'yaxis_label_textsize': 8, 'xaxis_label_textsize': 8, **'label_text_size': 8**}

**The argument label_text_size controls the size of labels. Is there a way to manage the size based on the amount of bars in graph.**

The same applies to donut chart.

**Comment by sunhailin-Leo** [comment]
@adihat `echarts` can`t autosize the label size.
