### ISSUE TITLE
js: Uncaught ReferenceError: echarts is not defined

### ISSUE THREAD

**Issue by kingmo888** [pyecharts/pyecharts#700]
**问题**

使用Pyinstaller打包，包含了模板文件。能够正常生成html，但是无法载入echarts的头部js。
无论是引入js、在线js等。除非模板文件直接内嵌完整js才可使用。

**运行环境（系统环境及 pyecharts 版本）**
win7, anaconda3,所有pyecharts版本。

**代码及截图**

**Comment by chfw** [comment]
请分享你的 html 文件。另外 pyecharts version?

**Comment by kingmo888** [comment]
感谢回复，最新版的pyechars， html文件我没有修改过的时候提示上述错误。
目前临时解决方案是我把head中间的那个js模板函数替换为：
<script type="text/javascript" src="https://cdn.bootcss.com/echarts/3.7.2/echarts.min.js"></script>主要用到的是simple_page.html

**Comment by YanNIU2028** [comment]
楼上的方法可以暂时解决二维图像，3D会报错 
Error: Component series.bar3D not exists. Load it first.
Error: Component series.scatter3D not exists. Load it first.

**Comment by chenjiandongx** [comment]
可以尝试使用 #1033 pyecharts 的 1.0.0 版本，该版本有新的静态资源引用规则
