### ISSUE TITLE
toolbox的标签有没有英语选项

### ISSUE THREAD

**Issue by chnynf** [pyecharts/pyecharts#702]
右侧的toolbox，鼠标放上去的时候都是“下载图片” 之类的提示，我知道echarts里头可以手动改mark：https://github.com/apache/incubator-echarts/issues/1171  改成中文英文都可以

pyecharts允不允许我改呢

![image](https://user-images.githubusercontent.com/37052928/44686660-ec982400-aa1c-11e8-8420-d1dabc432b1e.png)

**Comment by chenjiandongx** [comment]
现在可以了呢，默认为英语了呢，满不满意呢 😄

**Comment by chnynf** [comment]
惊喜加感动，有一点害羞

**Comment by YanNIU2028** [comment]
请问数据视图这个新窗口中，"数据视图"，"关闭"，"刷新"，这3个中文词在哪里可以重写？谢谢

**Comment by huixu123** [comment]
那现在要怎么改回中文
