### ISSUE TITLE
pyecharts 是否支持双y轴？

### ISSUE THREAD

**Issue by February00** [pyecharts/pyecharts#709]
您好，

       请问pyecharts目前是否支持双y轴，因为在文档中没有看到相关内容，
      
       所以来提问，如果支持的话，如何调用？

      恳请得到回答，非常感谢

**Comment by chenjiandongx** [comment]
文档有介绍

![image](https://user-images.githubusercontent.com/19553554/44827265-df5d7e00-ac44-11e8-9586-1c7358fc6afc.png)
