### ISSUE TITLE
ISSUE#572   https://github.com/pyecharts/pyecharts/issues/572  确定修复了吗？为什么最新版本还是有同样的问题？

### ISSUE THREAD

**Issue by shuferly** [pyecharts/pyecharts#712]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by shuferly** [comment]
使用pip install --upgrade pyecharts 已经更新到了pyecharts版本V0.5.9, 但还是有同样的问题。请问是我的更新方式不对吗？还是热力图语法做了改变？那么新的语法应该是怎样的？

**Comment by chenjiandongx** [comment]
@shuferly 

使用下面命令可以解决问题
···
$ pip install jupyter-echarts-pypkg==0.1.1 --no-cache-dir
···
