### ISSUE TITLE
Line with None line_width has incorrect default value

### ISSUE THREAD

**Issue by YasserHassan** [pyecharts/pyecharts#718]
Please check the example below and its result from Jupyter notebook:
```
from pyecharts import Line

attr = ['A', 'B', 'C', 'D', 'E', 'F']
v1 = [1, 2, 3, 4, 5, 6]
v2 = [2, 3, 4, 5, 6, 7]
line = Line()
line.add("line1", attr, v1, line_color='red')
line.add("line2", attr, v2, line_color='red', line_width=None)
line
```
![image](https://user-images.githubusercontent.com/9349772/44876588-ce8f2580-aca1-11e8-927d-f4e3bfe444bd.png)
I would expect that `line_width=None` should have the same effect as omitting `line_width` but currently setting `line_width` to `None` results in a thicker line (the top line "line2").

**Comment by sunhailin-Leo** [comment]
@YasserHassan New version fixed this problem. You can try it. 😄
