### ISSUE TITLE
Add direct option access with auto creation

### ISSUE THREAD

**Issue by YasserHassan** [pyecharts/pyecharts#723]
Direct access to `_option` is important to add and update the options that are not accessible via the API. Dealing with the options dictionary directly is not productive, especially when adding options that do no exist. To make this easier, I suggest adding a function like `set_option(path, value)` to the `Chart` base class where `path` is a JSONPath or XPath-like notation. For example:
```
bar = Bar('Bar Chart')
bar.set_option('/xAxis[0]/axisTick/alignWithLabel', True)
```
If that option already exists int he options dictionary, it will update it with the new value. But if it doesn't exist, it will create any missing part/nodes of it first. For example, if `axisTick` was not created by pyecharts, the method will append `axisTick` and `alignWithLabel` to `_option[xAxis][0]` and give it the value `True`. This can make it easier to bridge the gap between pyecharts and ECharts.

**Comment by chenjiandongx** [comment]
self.options is public variable now
