### ISSUE TITLE
Refactor and Merge pyecharts-javascripthon into pyecharts

### ISSUE THREAD

**Issue by kinegratii** [pyecharts/pyecharts#725]
功能改进建议： 将 [pyecharts-javascripthon](https://github.com/pyecharts/pyecharts-javascripthon) 合并到该代码库。

- pyecharts-javascripthon 涉及到的 **翻译过程** 是 render 的一个必不可少的步骤，它不是一个扩展功能(echarts-themes-pypkg)，也是一个插件(pyecharts-snapshot)。
- 合并之后共同维护，基于 python-to-javascript 翻译功能，整合相关代码。

目前 pyecharts-javascripthon 代码重构基本完成 ，参见 https://github.com/pyecharts/pyecharts/tree/javascripthon-embed 。

**Comment by kinegratii** [comment]
1 目前 javascripthon 也是必须安装的，因此安装门槛的问题并没有真正解决。

2 让 javascripthon 可安装 是 pyecharts 需遵守的原则。但 pyecharts-javascripthon 除了函数翻译，还有是翻译过程和架构，这一点是pyecharts的核心功能之一。pyecharts 也可以直接处理 javascripthon 选择安装问题。。

**Comment by chfw** [comment]
我是想把函数翻译分割出来，这样会移除ms visual studio的需求。那么只有需要用到函数翻译的用户群需要加倍努力。

**Comment by kinegratii** [comment]
Yeah，该功能预计在 v0.6.0 引入。
