### ISSUE TITLE
pyecharts会支持zeppelin吗？

### ISSUE THREAD

**Issue by hLxiao9** [pyecharts/pyecharts#726]
**问题**
zeppelin跟jupyter notebook很像，不知道后续pyecharts会支持zeppelin吗？

**Comment by quqibing** [comment]
同问. 有这个需求

**Comment by sunhailin-Leo** [comment]
@hLxiao9 @quqibing 
* 目前已经有个暂时的解决方案了，暂时文档可以看这边: https://github.com/pyecharts/pyecharts/issues/726
* 文档会在下一个版本中会更新到官方文档中，代码也会在下个版本中支持。
