### ISSUE TITLE
Linux保存png图片中文乱码，html中文没有问题

### ISSUE THREAD

**Issue by huaqi1220** [pyecharts/pyecharts#729]
**问题**
Linux保存png图片中文乱码，html中文没有问题，图片截图中画圈的地方应该有个中文为：‘天’

**运行环境（系统环境及 pyecharts 版本）**
系统环境：Linux，字符集编码为：zh_CN.UTF-8
pyecharts版本为：
pyecharts                   0.5.9  
pyecharts-javascripthon     0.0.6  
pyecharts-jupyter-installer 0.0.3  
pyecharts-snapshot          0.1.7

**代码及截图**
代码：
bar = pyecharts.Bar("Near7天CAddupSubsist(10000W)", width="650px", height='350px')
bar.add(arr_list[1], arr_x, arr_y1, is_label_show=True, label_text_size=15, bar_category_gap='60%',
        xaxis_interval=0, xaxis_rotate=45, yaxis_min=10,legend_top='6%')
bar.render(path='/home/spark/apps/python_project/pyecharts_hist_ccunxu.png')
图片截图：
![image](https://user-images.githubusercontent.com/25601160/44972517-050fbd80-af8c-11e8-9105-797a149b4606.png)

**Comment by chfw** [comment]
Please reference the solution from https://github.com/pyecharts/pyecharts-snapshot/issues/17
