### ISSUE TITLE
您好，Mac python3.6 geo 地图不显示

### ISSUE THREAD

**Issue by jialigit** [pyecharts/pyecharts#734]
**问题**

地图没显示

**运行环境（系统环境及 pyecharts 版本）**
Mac + python3.6+pyecharts0.5.9 

**代码及截图**
#coding=utf-8

from pyecharts import Geo

data = [("海门", 9),("鄂尔多斯", 12),("招远", 12),("舟山", 12),("齐齐哈尔", 14),("盐城", 15),\
("赤峰", 16),("青岛", 18),("乳山", 18),("金昌", 19),("泉州", 21),("莱西", 21),\
    ("日照", 21),("胶南", 22),("南通", 23),("拉萨", 24),("云浮", 24),("梅州", 25)]

geo = Geo("全国主要城市空气质量", "data from pm2.5", title_color="#fff", title_pos="center",\
width=1200, height=600, background_color='#404a59')
attr, value = geo.cast(data)
geo.add("", attr, value, visual_range=[0, 200], visual_text_color="#fff", symbol_size=15, is_visualmap=True)
geo.show_config()
geo.render("geoscatter.html")

<img width="732" alt="echart_geo" src="https://user-images.githubusercontent.com/13768484/45018527-e6c5c280-b05c-11e8-9e4f-9b121acb4ebd.png">

**Comment by chenjiandongx** [comment]
@jialigit 先安装地图扩展

![image](https://user-images.githubusercontent.com/19553554/45021724-dfa2b280-b064-11e8-8cc5-801389cd61bf.png)

**Comment by chfw** [comment]
China map is missing. Please install echarts-countries-pypkg.

**Comment by jialigit** [comment]
@chenjiandongx thanks!!! It worked after install the pypkg mentioned above.

**Comment by chenjiandongx** [comment]
ok
