### ISSUE TITLE
pyecharts 0.5.6-0.5.9之间的版本绘制图形时纵轴不显示文本而显示索引值

### ISSUE THREAD

**Issue by liupanpan525** [pyecharts/pyecharts#742]
本人pyecharts为0.5.9版本，绘制的纵轴为文本的图形，纵轴都不法正常显示，而是显示索引值（如：0，1，2，3，4，5），试了下其他版本，0.5.5版本是可以正常显示的，之后的版本均无法正常显示

**Comment by chenjiandongx** [comment]
https://github.com/pyecharts/pyecharts/issues/653
