### ISSUE TITLE
heatmap y label not correctly displayed

### ISSUE THREAD

**Issue by seekiu** [pyecharts/pyecharts#749]
**问题**

The y label is not correctly displayed in heatmap. Expected behavior is showing the label (category), however it shows the index (integer starting from 0).

**运行环境（系统环境及 pyecharts 版本）**

Windows 10, pyecharts version 0.5.10
Probably system independent.

**代码及截图**

To reproduce:

```python
arr = np.empty([10, 20])
for i in range(10):
    for j in range(20):
        arr[i, j] = i**2 - j

heatmap = pyecharts.HeatMap(height=400, width=500)
heatmap.add(
    'heatmapasdkfjldjflsdjf',
    list('abcdefghij'),
    list('abcdefghijabcdefghij'),
    [[i, j, arr[i, j]] for i in range(10) for j in range(20)],
    is_visualmap=True,
)

heatmap
```

**Temporary fix**

In pyecharts\echarts\axis.py, line 32, change:

```python
        if not isinstance(formatter, types.FunctionType):
            formatter = "{value} " + formatter
        super(YAxisLabel, self).__init__(formatter=formatter, **kwargs)
```

to

```python
        super(YAxisLabel, self).__init__(**kwargs)
```

A related question is why is X axis label defined slightly differently (just above the y part)? Is the temporary fix an ideal solution?

**Comment by simoncos** [comment]
Put my closed issue here.

**问题**

0.5.11下热力图 heatmap 不按设定的y_axis显示label，而是按从0到n的数字形式，0.5.5无此问题。

**运行环境（系统环境及 pyecharts 版本）**

Ubuntu & Mac / 0.5.11

**代码及截图**

```python
        y_axis = NAMES
        heatmap = HeatMap(self.output_name + '\'s Heatmap', width=900, height=900, title_top='20')
        heatmap.add("Scores", x_axis, y_axis, heatmap_data, is_visualmap=True,
                    visual_text_color="#000", visual_orient='horizontal', visual_range=[0, max_score],
                    is_yaxis_inverse=True)
```

0.5.5 结果（属于预期的正常结果）：

NAME_1   --- | ---
NAME_2   --- | ---
NAME_3   --- | ---

0.5.11 结果（纵坐标错误）：

0   --- | ---
1   --- | ---
2   --- | ---

**Comment by simoncos** [comment]
My closed issue can provide more information on this problem.
