### ISSUE TITLE
pip安装pyecharts后import提示找不到pyecharts_snapshot

### ISSUE THREAD

**Issue by eternal-flame-AD** [pyecharts/pyecharts#750]
**问题**
我使用pip安装pyecharts后，在import时会报找不到pyecharts_snapshot，目前看起来功能正常，手动安装后错误消失

**运行环境（系统环境及 pyecharts 版本）**
```
Python 3.7.0 (default, Jul 15 2018, 10:44:58)
[GCC 8.1.1 20180531] on linux
```

**代码及截图**
```
from pyecharts import Bar
```
```
ERROR:lml.utils:failed to import pyecharts_snapshot
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lml/utils.py", line 43, in do_import
    plugin_module = __import__(plugin_module_name)
ModuleNotFoundError: No module named 'pyecharts_snapshot'
```

**Comment by chenjiandongx** [comment]
ok

**Comment by rjwang18** [comment]
I  solved this problem by installing  pyecharts-snapshot  package.
The requirements.txt may needs to add pyecharts-snapshot  package.

**Comment by eternal-flame-AD** [comment]
I think we should keep it as an optional dependency.

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/45480857-9cd78d80-b77c-11e8-996d-1c41414404d4.png)

这不是每个用户都会用到的功能，而且这也不是只是 pip 安装一下这么简单，还要安装 phantomjs

**Comment by rjwang18** [comment]
I met this problem  when I just want to import  pyecharts. And I had try two ways to install  pyecharts while the problem still exists.  I just want to provide a solution to beginners that are eager to use this module.  I hope this problem can be solved quickly  to let more people enjoy this good tool. 
Thank you for developing this good tool.

**Comment by chfw** [comment]
check if pyecharts-snapshot is listed in `pip freeze`

**Comment by dbsxdbsx** [comment]
I met this issue, too. the version is 0.5.11.

**Comment by chfw** [comment]
Pyecharts snapshot is an optional package. I am not sure why you have this import error.

**Comment by dbsxdbsx** [comment]
@chfw ，I guess  the reason is that I use it directly in a python script, but not jupyter notebook.  By the way, how can I show chart with just .py script.  I need to dynamically create and update chart with py script. Is it possible to do so, like matplotlib or pyqtgraph?

**Comment by chfw** [comment]
Can create but not update for now.

**Comment by 1026cy** [comment]
为啥题目命名是中文的，聊着聊着大家啊都say in English了？

**Comment by richy668** [comment]
solve this problem:
         pip3 install pyecharts-snapshot
will be ok.

**Comment by PythonJavascript** [comment]
![2018-12-27 3 37 51](https://user-images.githubusercontent.com/42764920/50469025-158ded00-09ee-11e9-95b0-61723dbe6d6e.png)
我也 met this issue

**Comment by PythonJavascript** [comment]
py文件名字的问题，我已经ok了。。

**Comment by xxyyffyeah** [comment]
还是不行啊，freeze有snapshot ，还是编译不过

**Comment by chfw** [comment]
Run `pip freeze`

pycharm 用的 python env 看不见 pyecharts

**Comment by xxyyffyeah** [comment]
用的是anaconda，找不到pyecharts。
terminal 的pip freeze有，但是原生的也运行不了，可能还是py2状态。

**Comment by chfw** [comment]
Anaconda 的 python，pip 在哪里？

**Comment by xxyyffyeah** [comment]
问题解决了。是这样的，anaconda不存在的包需要pip下载，正常用pip install package,是会进入到conda环境内的，但是之前我都是pip3 install package，在pip freeze会显示，实际上并没用进入conda环境。所以只要重新用pip install package试一遍就行了。
关键：
.
1.安装了anaconda后所有的pip的package会自动进入conda环境。
2.但是需要指令pip install packagename
而不是pip3 install packagename

**Comment by Roc-J** [comment]
使用 pip install pyecharts_snapshot 即可解决，因为pyecharts_snapshot也是第三方库

**Comment by Schwertlilien** [comment]
> 用的是anaconda，找不到pyecharts。
> terminal 的pip freeze有，但是原生的也运行不了，可能还是py2状态。
我用的 anaconda，但我排查了 py2 状态 的问题，还是没有解决

**Comment by xwang757** [comment]
> > 用的是anaconda，找不到pyecharts。
> > terminal 的pip freeze有，但是原生的也运行不了，可能还是py2状态。
> > 我用的 anaconda，但我排查了 py2 状态 的问题，还是没有解决

I have the same problem, not solved

**Comment by 1026cy** [comment]
anacoda的安装命令不是pip，建议你查询一下anacoda的安装命令，或者改用python3，不用anacoda




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xwang757"<notifications@github.com&gt;; 
发送时间: 2020年9月3日(星期四) 凌晨3:02
收件人: "pyecharts/pyecharts"<pyecharts@noreply.github.com&gt;; 
抄送: "cy"<1026790662@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [pyecharts/pyecharts] pip安装pyecharts后import提示找不到pyecharts_snapshot (#750)





   
用的是anaconda，找不到pyecharts。
 terminal 的pip freeze有，但是原生的也运行不了，可能还是py2状态。
 我用的 anaconda，但我排查了 py2 状态 的问题，还是没有解决
   
I have the same problem, not solved
