### ISSUE TITLE
V0.5.11 正式发布啦！！

### ISSUE THREAD

**Issue by chenjiandongx** [pyecharts/pyecharts#756]
* ### version 0.5.11 - 2018.9.9（current）
    
    #### Added
    * [issue#731](https://github.com/pyecharts/pyecharts/issues/731) 新增 `mark_point_raw`, `mark_line_raw` 配置项用于个性化展示标记。
    
    #### Fixed
    * [issue#738](https://github.com/pyecharts/pyecharts/issues/738) 支持设置 Grid, Overlay 和 Timeline 某选项为空 (null)

    #### Removed
    * 移除 pillow 作为默认依赖，需要用到 Scatter.draw 方法的开发者请先自行安装 pillow。

**Comment by chfw** [comment]
Great! pillow is no longer a dependency!! No user get pillow problem at installation! Unit test will run faster without pillow.

**Comment by joylin1984** [comment]
感谢作者的付出！不知道能否添加pyqt的支持呢，pyqt下还没有一个强大的图表库呢。

**Comment by kinegratii** [comment]
@joylin1984 可以使用 [PyQtChart](https://riverbankcomputing.com/software/pyqtchart/intro) 库 ，pyecharts 近期暂无计划支持 pyqt 。
