### ISSUE TITLE
hello,我在今天导入pyecharts的时候出现报错

### ISSUE THREAD

**Issue by SmallSir** [pyecharts/pyecharts#757]
**问题**
是这样的，我正常导入pyecharts，但是出现了报错，我尝试了卸载再安装还是解决不了问题

**运行环境（系统环境及 pyecharts 版本）**
conda 4.5.9
pyecharts 0.5.11

**代码及截图**

![default](https://user-images.githubusercontent.com/20716945/45279131-9ccc5900-b502-11e8-9a70-6c401eece670.PNG)

**Comment by chenjiandongx** [comment]
你是使用 conda 安装的吗？
