### ISSUE TITLE
折线图Line的配置属性is_fill失效，无法显示为area

### ISSUE THREAD

**Issue by gaoyangxiaozhu** [pyecharts/pyecharts#762]
**问题**
折线图（Line）的is_fill属性失效

**运行环境（系统环境及 pyecharts 版本）**
操作系统： window server 2012
浏览器：Google Chrome | 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)
Jupyter-notebook:  5.6.0
pyecharts版本： 0.5.10

**代码及截图**

```python
import pandas as pd
import numpy as np
from pyecharts import Bar, Line

title = 'bar chart'
index =pd.date_range('3/8/2017', periods=6, freq='M')
df1 =pd.DataFrame(np.random.randn(6), index=index)
df2 = pd.DataFrame(np.random.randn(6), index=index)

dtvalue1 = [abs(i[0]) for i in df1.values]
dtvalue2 = [abs(i[0]) for i in df2.values]

_index = [i for i in df1.index.format()]


bar = Bar(title, 'Profit and loss situation')
bar.add('profit', _index, dtvalue1)
bar.add('loss', _index, dtvalue2,is_more_utils = True)

line = Line(title, 'Profit and loss situation')
line.add('profit', _index, dtvalue1 , is_fill=True)
line.add('loss', _index, dtvalue2,is_more_utils = True, 
         tooltip_trigger='axis',
         is_fill=True,
         area_color='#000'
        )
```

![image](https://user-images.githubusercontent.com/9858245/45365204-94f9db00-b60e-11e8-8523-5b233350d3ad.png)

**Comment by chenjiandongx** [comment]
add 中添加 `area_opacity` 区域透明度。1 是完全不透明，0 是完全透明

**Comment by gaoyangxiaozhu** [comment]
thanks, 我有看到这个属性 但是没有去测试。
 我觉得当用户设置**is_fill**为True的情况下，他希望看到的行为应该是不透明填充的，也就是默认**is_fill**为True的情况下，自动设置area_opacity为1。 不然的话，给用户的第一感觉是is_fill失效了。
@chenjiandongx

**Comment by chenjiandongx** [comment]
新版本的话文档我会更新的 取消 is_fill 这个参数，交给用户自己控制。

**Comment by gaoyangxiaozhu** [comment]
嗯嗯 加油

**Comment by weidongysu** [comment]
> 新版本的话文档我会更新的取消is_fill这个参数，交给用户自己控制。
大神你好，折线图通过render_embed()方式传入时，并不能出现阴影，这个怎么解决呀
