### ISSUE TITLE
pycharts 的标签值如何转化为百分比

### ISSUE THREAD

**Issue by sunleokkk** [pyecharts/pyecharts#766]
如题
附图

![image](https://user-images.githubusercontent.com/43232052/45472433-c71e5080-b766-11e8-858c-40ab191d23aa.png)

**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@sunleokkk 用新版可以试试这个博客里面的 JS https://blog.csdn.net/weixin_42348071/article/details/88552845
