### ISSUE TITLE
我看文档中没有经纬度相关的资料，pyecharts可以标点经纬度数据在地图上或者某一城市上吗？

### ISSUE THREAD

**Issue by 1558204459** [pyecharts/pyecharts#767]
您好
我看文档中没有经纬度相关的资料，pyecharts可以标点经纬度数据点在地图上或者某一城市上吗？

**Comment by chfw** [comment]
没有仔细看文档，给您一天再读读。

http://nbviewer.jupyter.org/github/pyecharts/pyecharts-users-cases/blob/master/notebook-users-cases/notebook-user-cases.ipynb

**Comment by 1558204459** [comment]
好的。

**Comment by 1558204459** [comment]
这个就是随意定坐标，不是指个别城市和地点的坐标
Pyecharts 可以实现吗？
