### ISSUE TITLE
图表继承体系梳理与重构

### ISSUE THREAD

**Issue by kinegratii** [pyecharts/pyecharts#768]
这是 pyechart 中所有图表的继承关系：

- Base
  - Chart : 接口 `add(**kwargs)`
    - Bar
    - Geo
    - ...
  - [CompositeChart] : 接口 `add(chart, **kwargs)`
    - Grid
    - Overlap
    - Timeline

备注：

- 以上两处接口的 `kwargs` 传入的参数不同，不可进一步抽象。
- CompositeChart 目前未实现。
- Page 不在继承体系之内

v0.6.x 重构步骤

1. 将 `pyecharts.custom.*` 移到 `pyecharts.charts.composite.*` 包
- 将所有图表类移到 `pyecharts.charts` 包
-  现有的 custom 不符合具体意义，使用 composite 更为合适

2. 将 Page 类移到 `pyecharts.contrib.page` 模块
- Page 不属于继承体系，不宜放入 charts 包
- contrib 定位于 “脚手架” ，位于 “核心层” 之上
- 后续可能与 Report 合并

3. Style 类 重构/保留?
- Style 不属于继承体系，因此不应当继承 Chart
- 目前 Style 仅是简单的参数复用，参数声明
- 解决方案：保留代码 或 移除代码

**Comment by chenjiandongx** [comment]
@chfw @kinegratii  Style 当初继承自 Chart 是为了它的 add 智能补全

**Comment by kinegratii** [comment]
关于 Style ：

1. 智能补全也仅适用于 IDE 编程，无通用性。
2. 不应当继承 Chart ,可以通过 Mixin 方式，实现多继承。比如：

```
- OptionsParamsMixin:
  - Chart
  - Style
```
3. 更为重要的是 Style 和 dict 使用方式相同。

```python 
pie_style = style.add()
pie.add("", ["剧情", ""], [25, 75], center=[10, 30], **pie_style)
```
个人一直不赞成这种占用 `**kwargs` 定义和调用，更推荐以下方式：

```python
pie_style = style.add()
pie.add("", ["剧情", ""], [25, 75], center=[10, 30], style=pie_style)
```

基于以上原因，还是采用废弃 Style 方案。

**Comment by kinegratii** [comment]
关于 `Base.add` 函数：

1. 目前的确不够面向对象化，#735 和 #723 或许是一个研究和重构的方向。
2. 但是上述 issue 所述的内容的 **可行性** 还有待研究，甚至可能不是 pyecharts 所定义的问题领域。Echarts 并未公开其内部具体的数据结构，并且其变化频繁。 pyecharts 可能无法完整准确使用 python 语言描述和翻译这一结构。
3. `add` 函数是pyecharts 到目前为止一个最为核心的功能，因此对其修改应当慎重。

**Comment by chfw** [comment]
add 是不能改，不过并不是说不能再加个新的 add, 比如 `bar.series.add(data, **more_bar_related_options)`

**Comment by chenjiandongx** [comment]
重要接口变动请慎重，还是那句话。

在 **用户友好** 和 **设计模式、面向对象** 之间非要选一个话，建议是前者。毕竟代码是拿来用的，不是拿来看的。
