### ISSUE TITLE
jupyter notebook无法正常显示图

### ISSUE THREAD

**Issue by wqw547243068** [pyecharts/pyecharts#771]
**问题**
执行以下代码，画出来的一片空白，只能render到html文件才行,怎么破？

**运行环境（系统环境及 pyecharts 版本）**

执行环境：centos的server，python 2.7

**代码及截图**
```python
from pyecharts import Bar

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 75, 90]
v2 = [10, 25, 8, 60, 20, 80]
bar = Bar("柱状图数据堆叠示例")
bar.add("商家A", attr, v1, is_stack=True)
bar.add("商家B", attr, v2, is_stack=True)
bar
```
效果图：
![image](https://user-images.githubusercontent.com/3257257/45610596-17f7b700-ba8f-11e8-990d-c4f397e065b2.png)

jupyter notebook配置信息：
![image](https://user-images.githubusercontent.com/3257257/46733402-ca9feb80-ccc2-11e8-9079-ee320309b866.png)

**Comment by chaoshengt** [comment]
@wqw547243068 代码我试过，正常显示，毫无问题呀

**Comment by wqwangchn** [comment]
我也遇到同样问题，查了一天了，还是不解中。。。。

**Comment by wqwangchn** [comment]
@wqw547243068 解决的话分享下，谢谢

**Comment by ltx1171135686** [comment]
@wqwangchn 请教下，和题注一样的问题。win10，python3.5，pycharts最新版,是一样处理吗？

**Comment by wqwangchn** [comment]
@ltx1171135686 可以查看下页面源码，如果看到echarts的bug，基本就是这种问题了。

**Comment by ltx1171135686** [comment]
@wqwangchn 抱歉，我是编程菜鸟。关于查看页面源码是否是F12，看echarts的错误我不理解。可以赐教一下吗？

**Comment by wqw547243068** [comment]
> echarts 找不到了，配置下即可。
> pyecharts.configure(
> jshost='https://cdnjs.cloudflare.com/ajax/libs/echarts/3.7.2/',
> echarts_template_dir=None,
> force_js_embed=None,
> output_image=None,
> global_theme=None
> )

这样吗？还是空白
```python
import pyecharts as pe

pe.configure(
    jshost='https://cdnjs.cloudflare.com/ajax/libs/echarts/3.7.2/',
    echarts_template_dir=None,
    force_js_embed=None,
    output_image=None,
    global_theme=None
)

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 75, 90]
v2 = [10, 25, 8, 60, 20, 80]
bar = pe.Bar("柱状图数据堆叠示例")
bar.add("商家A", attr, v1, is_stack=True)
bar.add("商家B", attr, v2, is_stack=True)
bar
```

**Comment by wqw547243068** [comment]
> @wqw547243068 代码我试过，正常显示，毫无问题呀

有时候有问题，不知道原因

**Comment by wqwangchn** [comment]
@wqw547243068 @ltx1171135686 这个问题我没有细究，估计是默认的echarts的链接有问题，我自己试验了两个机器都可以解决。我的步骤是先‘单独’配置configure，之后重启jupyter(是所有打开的jupyter都要关闭)，然后就可以使用了。 期待这种问题的的完整解释。。

**Comment by ltx1171135686** [comment]
@wqwangchn 哈哈，好的，解决了。非常谢谢。不知道为啥我的notebook浏览器不能联网了。所以还是没好。这时候我突发奇想。去kaggle的kernel试一下。没想到在那里成功了。完美解决问题。再次感谢。 @wqw547243068 希望对你有一点点的帮助

**Comment by wqw547243068** [comment]
> @wqw547243068 @ltx1171135686 这个问题我没有细究，估计是默认的echarts的链接有问题，我自己试验了两个机器都可以解决。我的步骤是先‘单独’配置configure，之后重启jupyter(是所有打开的jupyter都要关闭)，然后就可以使用了。 期待这种问题的的完整解释。。

请问怎么单独配置？我重启了，不管用

**Comment by ltx1171135686** [comment]
@wqwangchn  我出现了一个新的问题。只能画简单的条形图，饼图，折线图，高级一点的3D，水滴还是空白。这是我的consule截图。
![image](https://user-images.githubusercontent.com/32806203/46253750-f3033b00-c4b5-11e8-96eb-4202ac834753.png)

![image](https://user-images.githubusercontent.com/32806203/46253751-031b1a80-c4b6-11e8-9f26-1e6507778ae6.png)

能否赐教？

**Comment by chfw** [comment]
jshost='https://cdnjs.cloudflare.com/ajax/libs/echarts/3.7.2/', 只提供 echarts.min.js

换这个试试："https://pyecharts.github.io/assets/js"

**Comment by chfw** [comment]
请读一下：http://pyecharts.org/#/zh-cn/faq

**Comment by ltx1171135686** [comment]
@wqwangchn 好的，解决了。非常感谢。我曾看过几遍，但是没怎么看懂。以后会常看的。

**Comment by wanmeow** [comment]
我研究这个问题也是折腾了好久，后来发现在jupyter notebook和pyecharts都安装好的情况下，只要在jupyter notebook里运行这段代码就可以

import pyecharts as pe
pe.configure(
    jshost="https://pyecharts.github.io/assets/js",
    echarts_template_dir=None,
    force_js_embed=None,
    output_image=None,
    global_theme=None
)

非常感谢@wqw547243068 @wqwangchn 和@chfw
初来乍到不懂规矩，还望各位多多海涵

**Comment by PeikaiLi** [comment]
> 

module 'pyecharts' has no attribute 'configure'

**Comment by xiaoshuwa** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
