### ISSUE TITLE
在jupyter里显示图表，坐标轴刻度旋转后，图标边缘空间不够显示全部坐标刻度

### ISSUE THREAD

**Issue by chnynf** [pyecharts/pyecharts#775]
我知道可以调整图表的整个大小，但是好像无论什么大小，都不影响坐标轴和边缘的距离。有时候刻度比较长，就显示不下：

![image](https://user-images.githubusercontent.com/37052928/45717799-fbc84880-bb68-11e8-98ca-61a4c4ff87a8.png)

下面到底了，拉不下去，不知道是不是有别的参数可以用来设置？

**Comment by chnynf** [comment]
刚才试了下，好像render了以后打开html 也是下面显示不了的

**Comment by chenjiandongx** [comment]
用 Grid，http://pyecharts.org/#/zh-cn/charts_custom?id=grid%EF%BC%9A%E5%B9%B6%E8%A1%8C%E6%98%BE%E7%A4%BA%E5%A4%9A%E5%BC%A0%E5%9B%BE

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/45725834-412f5900-bbef-11e8-85df-e4d95cb36357.png)
