### ISSUE TITLE
get_echars_options()这个方法好像还没添加

### ISSUE THREAD

**Issue by ly1102** [pyecharts/pyecharts#777]
**问题**
写代码会遇到需要动态切换图表内容的情况，如果手动获取echars_options，会导致json.dumps出错。所以希望大佬加一下这个api。之前都提过issue了

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by kinegratii** [comment]
目前该功能内部正在重构，预计下个版本添加为 Public API

**Comment by chenjiandongx** [comment]
参考 https://pyecharts.org/#/zh-cn/chart_api
