### ISSUE TITLE
django 的比如云词图如何布置？

### ISSUE THREAD

**Issue by 97thjingba** [pyecharts/pyecharts#778]
**问题**
不知道这样的写法对不对

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![image](https://user-images.githubusercontent.com/39749571/45882912-2e30aa80-bde2-11e8-97a9-85d4861d40b1.png)
![image](https://user-images.githubusercontent.com/39749571/45882928-3557b880-bde2-11e8-9354-1a2dcf25d747.png)

**Comment by chenjiandongx** [comment]
不知道对不对？实际效果图呢？

**Comment by 97thjingba** [comment]
pyecharts是不支持我这样直接读取文本的数据的吗

**Comment by chenjiandongx** [comment]
得看看读到的数据是什么
