### ISSUE TITLE
如何使用options方法改变base里面的key值？

### ISSUE THREAD

**Issue by wastee** [pyecharts/pyecharts#779]
**问题**

希望隐藏 toolbox 里面的 data view。
但使用 base._option 可以，base.options 就不可以。

**运行环境（系统环境及 pyecharts 版本）**

OS:                                                  Arch Linux x86_64
Python version:                          Python 3.7.0

pyecharts                                     0.5.11   
pyecharts-javascripthon         0.0.6    
pyecharts-jupyter-installer     0.0.3    
pyecharts-snapshot                  0.1.8  

jupyter                                           1.0.0    
jupyter-client                               5.2.3    
jupyter-console                          5.2.0    
jupyter-core                                 4.4.0
jupyter-echarts-pypkg             0.1.2 

**代码及截图**

```python
bar = Bar(
    title=title,
    width=900,
    height=600,
)

for i, col in enumerate(col_list):
    bar.add(
        name=rt_dict[col],  # 图例名
        x_axis=_index,  # x轴
        y_axis=df_dict[col],  # y轴
        is_stack=False,  # 不堆叠
        is_more_utils=True, # 更多的工具
        bar_category_gap='20%',  # bar间距
        mark_line=['min', 'max'],  # 最高最低线
        legend_selectedmode='single',  # 单选图例
        legend_pos='right',  # 图例贴右
)

bar.options['toolbox']['feature']['dataView']['show'] = False
bar
```
依然有 data view。
但
```python
bar._option['toolbox']['feature']['dataView']['show'] = False
```
就没有了。

请问 bar._option 不是等价於 bar.options 吗？

**Comment by kinegratii** [comment]
1. `bar.options` 是个 **property** ，不支持对其进行直接设置/修改。
2. 可以使用 `_options` 进行 hack ，但请注意这是 **私有API** 。
