### ISSUE TITLE
在 Overlap 中如何分别定义不同 item 的 tooltip ?

### ISSUE THREAD

**Issue by wastee** [pyecharts/pyecharts#780]
**问题**

Overlap 的2种图，只 format 了 Bar 的 tooltip，但 Line 的tooltip也改变了。

当只有 Bar 的时候，tooltip 正常：
![image](https://user-images.githubusercontent.com/22229962/45997265-94167e00-c0d1-11e8-9982-06fa00707172.png)

当只有 Line 的时候，tooltip也正常：
![image](https://user-images.githubusercontent.com/22229962/45997287-a8f31180-c0d1-11e8-8270-557c0c36345f.png)

但当放在 overlap 的时候，Line 的 tooltip就变成只有 bar 的X轴的值，而没有正确的 Line 的。
![image](https://user-images.githubusercontent.com/22229962/45997347-d9d34680-c0d1-11e8-995d-83ff8ab063d2.png)

**运行环境（系统环境及 pyecharts 版本）**

OS: Arch Linux x86_64
Python version: Python 3.7.0

pyecharts 0.5.11
pyecharts-javascripthon 0.0.6
pyecharts-jupyter-installer 0.0.3
pyecharts-snapshot 0.1.8

jupyter 1.0.0
jupyter-client 5.2.3
jupyter-console 5.2.0
jupyter-core 4.4.0
jupyter-echarts-pypkg 0.1.2

**代码及截图**

> df 为 past_df

### Formatter func

```python
def labelfixed_formatter(p):
    return window.parseFloat(p.value).toFixed(2) + '元'
    
def tooltipfixed_formatter(p):
    return p.seriesName + '<br>' + p.marker + p.name + ': ' + window.parseFloat(p.value).toFixed(2) + '元'

##########

def yaxis_percent_formatter(p):
    return p * 100 + '%'

def label_percent_formatter(p):
    return window.parseFloat(p.data[1] * 100).toFixed(2) + '%'

def tooltip_percent_formatter(p):
    return p.seriesName + '<br>' + p.marker + p.name + ': ' + window.parseFloat(p.data[1] * 100).toFixed(2) + '%'
```

### Show

```python
bar = Bar('Title')
line = Line()
overlap = Overlap(width=900, height=600)

bar.add(
    name='cpc',
    x_axis=past_df.index.format(),
    y_axis=past_df.cpc.tolist(),
    
    yaxis_max=50,
    yaxis_formatter='元',

    is_datazoom_show=True,
    is_label_show=True,
    is_splitline_show=False,
    
    label_formatter=labelfixed_formatter,
    tooltip_formatter=tooltipfixed_formatter,
)

line.add(
    name='ctr',
    x_axis=past_df.index.format(),
    y_axis=past_df.ctr.tolist(),
    
    is_label_show=True,
    label_formatter=label_percent_formatter,
    tooltip_formatter=tooltip_percent_formatter,
    yaxis_formatter=yaxis_percent_formatter,
)

overlap.add(bar)
overlap.add(line, is_add_yaxis=True, yaxis_index=1)

overlap._option['toolbox']['feature'].update(
    dataView={
        'show': False,  # 取消dataview
    },
    magicType={
        'show': True,
        'type': ['line', 'bar'],
        'title': {
            'line': '折线图',
            'bar': '柱状图',
        },
    },
)
overlap
# line
# bar
```

-------------

我最后把 trigger 改成 'axis' ，参考这里把2个数值同时显示了。
![image](https://user-images.githubusercontent.com/22229962/45998303-fae96680-c0d4-11e8-9d74-f6044e7262c0.png)
http://echarts.baidu.com/echarts2/doc/example/line6.html
请问 trigger 为 ‘item’ 的时候，是否不能分开 item 的 tooltip 显示？当默认状态下是可以的。

**Comment by yhmickey** [comment]
遇到了同样的问题，overlap后，其中有些tooltip失效了，变成了和其他一样的tooltip，请问有解决方法吗

**Comment by chenjiandongx** [comment]
v1.2.0 后，现在单独的 series 都有 tooltip 配置项了
