### ISSUE TITLE
回调函数里面的 params 的定义是如何知道的？

### ISSUE THREAD

**Issue by wastee** [pyecharts/pyecharts#781]
> 中秋节快乐！

**问题**

例如，想在 tooltips 里定义那个小圆点，就是 params.marker；例如，只保留小数点后两位，就是window.parseFloat(p.value).toFixed(2)。
我该在哪里得到可用的方法呢？如 marker，如 window.parseFloat。

**运行环境（系统环境及 pyecharts 版本）**

OS: Arch Linux x86_64
Python version: Python 3.7.0

pyecharts 0.5.11
pyecharts-javascripthon 0.0.6
pyecharts-jupyter-installer 0.0.3
pyecharts-snapshot 0.1.8

jupyter 1.0.0
jupyter-client 5.2.3
jupyter-console 5.2.0
jupyter-core 4.4.0
jupyter-echarts-pypkg 0.1.2

**代码及截图**

```javascript
  (params: Object|Array) => string
  参数 params 是 formatter 需要的单个数据集。格式如下：
  {
      componentType: 'series',
      // 系列类型
      seriesType: string,
      // 系列在传入的 option.series 中的 index
      seriesIndex: number,
      // 系列名称
      seriesName: string,
      // 数据名，类目名
      name: string,
      // 数据在传入的 data 数组中的 index
      dataIndex: number,
      // 传入的原始数据项
      data: Object,
      // 传入的数据值
      value: number|Array,
      // 数据图形的颜色
      color: string,
  }
```

**Comment by chenjiandongx** [comment]
https://github.com/pyecharts/pyecharts/issues/662
