### ISSUE TITLE
geolines.py中代码少个coordinate_region参数

### ISSUE THREAD

**Issue by jxph025319** [pyecharts/pyecharts#783]
**问题**
geolines.py中110行附近：
            _from_coordinate = self.get_coordinate(
                _from_name, coordinate_region, raise_exception=True
            )
            _to_coordinate = self.get_coordinate(
                _to_name, raise_exception=True
            )

在_to_coordinate 中少传一个参数 coordinate_region 导致国外目标城市默认为中国城市，而报错。

**运行环境（系统环境及 pyecharts 版本）**
python2.7
pyecharts 0.5.11

![Uploading pyecharts_bug.png…]()

**代码及截图**

**Comment by chenjiandongx** [comment]
实际上 pyecharts 并没有提供 `world` 地图的坐标。完整的话需要自己提供！

**Comment by jxph025319** [comment]
你好：
      代码里面是没有传递制定区域的参数，导致目标城市默认使用中国的城市范围导致报错的吧。我装了世界地图的包，调整代码后是可以找到国外城市的。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 陈键冬 <notifications@github.com>
发送时间: Tuesday, September 25, 2018 10:50:58 PM
收件人: pyecharts/pyecharts
抄送: jxph025319; Author
主题: Re: [pyecharts/pyecharts] geolines.py中代码少个coordinate_region参数 (#783)


实际上 pyecharts 并没有提供 world 地图的坐标。完整的话需要自己提供！

―

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！现在不用装地图包啦
