### ISSUE TITLE
在linux下生产jpg图片样式有问题，缺失数字等关键信息

### ISSUE THREAD

**Issue by ChenSen5** [pyecharts/pyecharts#784]
**问题**

生成jpeg的图片样式有问题，如图所示，在mac上是正常的

**运行环境（系统环境及 pyecharts 版本）**
1、操作系统：centos.
2、pyecharts版本：0.5.8；
4、Python：2.7

**代码及截图**

line = Line(job_desc + u'覆盖率', "  min(%s) max(%s) now(%s)" % (min(current_job_coverage_list),max(current_job_coverage_list),coverage),title_pos='center')
	line.add("",current_job_day_list,current_job_coverage_list,mark_point=[ "max", "min"],mark_point_symbol="diamond", mark_point_symbolsize=70,mark_line=["average"],yaxis_min=min(current_job_coverage_list)-2,yaxis_max=max(current_job_coverage_list)+2,is_label_show=True)
line.render(u'%s/%s.jpeg' % (img_dir,job_desc))	
![image](https://user-images.githubusercontent.com/9099096/46017653-947f3b00-c10a-11e8-85bd-be84b49fbc3a.png)

**Comment by chenjiandongx** [comment]
也许是中文乱码了吧

**Comment by ChenSen5** [comment]
> 也许是中文乱码了吧
不是的，我写了一个测试脚本，也是没有显示。

我的代码：
`
#coding=utf-8
from __future__ import unicode_literals
from pyecharts import Line,Bar
from pyecharts.engine import create_default_environment
from pyecharts import configure

# 设置统计图的样式
configure(global_theme='vintage')


line = Line('test', 'desc',title_pos='center')
line.add("",['first','seconde'],[11,22],is_label_show=True)
line.render('coverage_img/test.jpeg')

line = Line('test2', 'desc2',title_pos='center')
line.add("",['first','seconde'],[11,22],is_label_show=True)
line.render('coverage_img/test2.png')

`
![image](https://user-images.githubusercontent.com/9099096/46060513-36983500-c196-11e8-977a-71ac9f2d1d84.png)

**Comment by ChenSen5** [comment]
我找到解决方式了。
通过升级到最新的charts版本并安装yum install bitmap-fonts bitmap-fonts-cjk
参考ISSUE：https://github.com/pyecharts/pyecharts-snapshot/issues/17
