### ISSUE TITLE
x 轴和 y 轴交换 显示错误

### ISSUE THREAD

**Issue by jinxinglu** [pyecharts/pyecharts#785]
**问题**
x 轴和 y 轴交换 显示错误

**运行环境（系统环境及 pyecharts 版本）**
jupyter + pyecharts  0.5.3 

**代码及截图**

<img width="765" alt="screen shot 2018-09-27 at 1 35 01 pm" src="https://user-images.githubusercontent.com/26435943/46125098-2ea1c900-c25a-11e8-86c8-092cad3d33a9.png">

**Comment by gaoyangxiaozhu** [comment]
+1

**Comment by gaoyangxiaozhu** [comment]
![image](https://user-images.githubusercontent.com/9858245/46130519-1b97f480-c26c-11e8-9c99-ced76083d599.png)

**Comment by marcelyz** [comment]
+1

**Comment by sunhailin-Leo** [comment]
暂时的解决办法:
* 修改pyecharts安装包下的 simple_chart.html 
![pyecharts](https://user-images.githubusercontent.com/17564655/48132299-0af88680-e2ce-11e8-8d27-8be7d12e2ce0.png)

* js版本回退到4.1.0一下就解决了

**Comment by chenjiandongx** [comment]
下个版本将会修复，预计于四月发布

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！该问题已修复
