### ISSUE TITLE
当is_label_show=True时，Map无法正确渲染成svg

### ISSUE THREAD

**Issue by SkyShadowCN** [pyecharts/pyecharts#786]
使用Map图时，当is_lable_show为True时，生成的svg文件仅有811字节，打开后显示
“This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.”

**运行环境（系统环境及 pyecharts 版本）**
windows 10
pyecharts 0.5.11
phantomjs 2.1.1

**代码及截图**
```python
from pyecharts import Map

value = [155, 10, 66, 78, 33, 80, 190, 53, 49.6]
attr = [
    "福建", "山东", "北京", "上海", "甘肃", "新疆", "河南", "广西", "西藏"
    ]
map = Map("Map 结合 VisualMap 示例", width=1200, height=600,renderer='svg')
map.add(
    "",
    attr,
    value,
    maptype="china",
    is_visualmap=True,
    visual_text_color="#000",
    is_label_show=True
)
map.render(path='is_label_show_on.svg')
```
![default](https://user-images.githubusercontent.com/17083821/46196422-a1ce3c80-c339-11e8-9751-66926b887747.png)
![default](https://user-images.githubusercontent.com/17083821/46196431-a5fa5a00-c339-11e8-9b99-3fd8003793c6.png)

**Comment by chenjiandongx** [comment]
请使用 v1 版本的 pyecharts
