### ISSUE TITLE
ModuleNotFoundError: No module named 'pyecharts.events'

### ISSUE THREAD

**Issue by Loovelj** [pyecharts/pyecharts#788]
**问题**
ModuleNotFoundError: No module named 'pyecharts.events'

**运行环境（系统环境及 pyecharts 版本）**

win10  python 3.6   pyecharts 0.5.11

使用最新的pip安装，安装完后启动jupyter notebook,操作示例发现报错

**代码及截图**

![image](https://user-images.githubusercontent.com/10558917/46242178-03ed7700-c3f8-11e8-9f39-2ffe7ed9bb1b.png)

**Comment by chfw** [comment]
so, lower version of pyecharts is installed so python is confused which one to use.
