### ISSUE TITLE
画bar,funnel,pie时可以显示。但是话3D,水滴就是一片空白。

### ISSUE THREAD

**Issue by ltx1171135686** [pyecharts/pyecharts#789]
**问题**

上面的饼图是可以执行的。下面的水滴图就是一片空白了。我还试过各种3D图。同样不行。这真是个奇怪的问题。

**运行环境（系统环境及 pyecharts 版本）**
win10
pycharts最新版。

**代码及截图**
![image](https://user-images.githubusercontent.com/32806203/46245224-0910ed00-c41d-11e8-90fa-086c8a9c64ad.png)

![image](https://user-images.githubusercontent.com/32806203/46245239-36f63180-c41d-11e8-9bc2-adcde594c8bf.png)

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！该问题在1.0.0版本中已修复
