### ISSUE TITLE
大量数据X轴显示问题

### ISSUE THREAD

**Issue by fanwz** [pyecharts/pyecharts#791]
**问题**
假设有30000条数据，x轴会有30000个点，设置is_datazoom_show为True，就会变成如下图所示。
想要查看一个小范围内的数值变化，得把下边的滑块缩得很小才行，很难控制移动。能否有好的解决办法？
谢谢

**运行环境（系统环境及 pyecharts 版本）**
Windows 7  ver:0.5.11

**代码及截图**
xaxis = list(range(30000))
yaxis = np.random.randint(5, size=(30000))
linea = Line()
linea.add('a', xaxis, yaxis, is_datazoom_show=True, is_label_show=True)
linea.render()

![image](https://user-images.githubusercontent.com/7878957/46258612-4e5a1b00-c500-11e8-9e63-883c532027b0.png)

**Comment by chenjiandongx** [comment]
暂时没有其他好的办法，或者你可以选择拆分为两个图
