### ISSUE TITLE
docstrings in english

### ISSUE THREAD

**Issue by LionelR** [pyecharts/pyecharts#793]
Translate docstrings in english language, as it's difficult to understand docs in code.

**Comment by chfw** [comment]
Good point. 

So far, we are helped on English docs. You can find the api docs in English. 

Atm, the core team have not gotten Non-Chinese member yet. So English docstrings do not seem important. Coming back to your point, language could be a barrier for Non-Chinese developer to join.

At the end of day, time is needed to convert existing docs and team culture change is also needed.
