### ISSUE TITLE
Tree 树图没有线

### ISSUE THREAD

**Issue by sunleokkk** [pyecharts/pyecharts#794]
**问题**
Tree 树图没有线

**运行环境（系统环境及 pyecharts 版本）**

py3.7

**代码及截图**

![image](https://user-images.githubusercontent.com/43232052/46485347-14558580-c82e-11e8-9e0a-0138f1925aee.png)

**Comment by sunhailin-Leo** [comment]
@sunleokkk 可以尝试新版本的代码。如果依旧出现该问题，请重新提 issue 并附上你的代码，thx～
