### ISSUE TITLE
在jupyter使用pyecharts时，图表显示空白

### ISSUE THREAD

**Issue by liushengyi6** [pyecharts/pyecharts#795]
**问题**
您好，我在jupyter上使用pyechats,图表显示空白。经FAQ排查，http://localhost:8888/nbextensions/echarts/echarts.min.js 能正常访问

**运行环境（系统环境及 pyecharts 版本）**
服务器端：
linux : 4.9.81-35.56.amzn1.x86_64
 jupyter +anaconda2 +python2.7 pyechats 0.5.11

浏览器端
chrome浏览器

**代码及截图**

![image](https://user-images.githubusercontent.com/36978397/46521603-b5861f80-c8b2-11e8-9ad5-5bd144909ca7.png)
![image](https://user-images.githubusercontent.com/36978397/46521653-d6e70b80-c8b2-11e8-9fc1-7f612b7919e0.png)

**Comment by chfw** [comment]
I am sorry that it only supports localhost. for named host or use with ip address, it is not supported. And you will need to use configure(jshost='...').

**Comment by liushengyi6** [comment]
> I am sorry that it only supports localhost. for named host or use with ip address, it is not supported. And you will need to use configure(jshost='https://pyecharts.github.io/assets/js').

![image](https://user-images.githubusercontent.com/36978397/46523074-334c2a00-c8b7-11e8-9afa-e561d78d9125.png)

我尝试配置了下jhost，如上图。仍然没有显示

**Comment by chfw** [comment]
我怀疑 jupyter-echarts-pypkg 没有装上。

```

>>> import jupyter_echarts_pypkg
>>> jupyter_echarts_pypkg.__version__
```

**Comment by liushengyi6** [comment]
> jupyter_echarts_pypkg.__version__

![image](https://user-images.githubusercontent.com/36978397/46566392-0dbf2f00-c950-11e8-9355-f3f775de6ee1.png)

这样是装上了吗？

**Comment by liushengyi6** [comment]
> > jupyter_echarts_pypkg.**version**
> 
> ![image](https://user-images.githubusercontent.com/36978397/46566392-0dbf2f00-c950-11e8-9355-f3f775de6ee1.png)
> 
> 这样是装上了吗？

目前仍然是显示空白

**Comment by liushengyi6** [comment]
> 我怀疑 jupyter-echarts-pypkg 没有装上。
> 
> ```
> 
> >>> import jupyter_echarts_pypkg
> >>> jupyter_echarts_pypkg.__version__
> ```



> > > jupyter_echarts_pypkg.**version**
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/36978397/46566392-0dbf2f00-c950-11e8-9355-f3f775de6ee1.png)
> > 这样是装上了吗？
> 
> 目前仍然是显示空白

有解决方案吗？？急求

**Comment by wqw547243068** [comment]
please refer to this post: [jupyter notebook无法正常显示图](https://github.com/pyecharts/pyecharts/issues/771)
