### ISSUE TITLE
误差棒支持

### ISSUE THREAD

**Issue by Saliva520319** [pyecharts/pyecharts#802]
求问折线图和bar支持误差棒么?或者如何自定义这个东西?
例子:
http://www.echartsjs.com/gallery/editor.html?c=custom-error-bar&theme=light

**Comment by Saliva520319** [comment]
@Saliva520319 S
图片上传总是失败,不好意思.

**Comment by chenjiandongx** [comment]
误差棒不是 Echarts 的标准方法，无实现打算
