### ISSUE TITLE
K线图上增加显示日期

### ISSUE THREAD

**Issue by lamter** [pyecharts/pyecharts#804]
目前的K线图，当鼠标移动到K线上可以显示open, close, high, low。但是没有这根K线对应的日期，很不方便查看。希望可以再增加显示日期

**Comment by chenjiandongx** [comment]
可以自己定义 tooltip_formatter

这里给出源码参考

```
def kline_tooltip_formatter(params):
    text = (
        params[0].seriesName
        + "<br/>"
        + "- open:"
        + params[0].data[1]
        + "<br/>"
        + "- close:"
        + params[0].data[2]
        + "<br/>"
        + "- lowest:"
        + params[0].data[3]
        + "<br/>"
        + "- highest:"
        + params[0].data[4]
    )
    return text
```

**Comment by lamter** [comment]
`kline_tooltip_formatter`的参数`params`是个什么对象？我不能直接在`kline_tooltip_formatter`里面`print`出来，也查不到文档。

**Comment by erikgqp8645** [comment]
大佬你这个是咋解决的啊，求教

**Comment by lamter** [comment]
> 大佬你这个是咋解决的啊，求教
重新定义 `kline_tooltip_formatter` 函数。`x`轴是日期，直接调用`x`轴的值拼接字符串。

```python
def kline_tooltip_formatter(params):
    text = (
        params[0].axisValue
        + "<br/>"
        + "- open:"
        + params[0].data[1]
        + "<br/>"
        + "- high:"
        + params[0].data[4]
        + "<br/>"
        + "- low:"
        + params[0].data[3]
        + "<br/>"
        + "- close:"
        + params[0].data[2]
        + "<br/>"
        + "- volume:"
        + params[0].data[5]
    )
    return text
```

**Comment by erikgqp8645** [comment]
> > 大佬你这个是咋解决的啊，求教
> 
> 重新定义 `kline_tooltip_formatter` 函数。`x`轴是日期，直接调用`x`轴的值拼接字符串。
> 
> ```python
> def kline_tooltip_formatter(params):
>     text = (
>         params[0].axisValue
>         + "<br/>"
>         + "- open:"
>         + params[0].data[1]
>         + "<br/>"
>         + "- high:"
>         + params[0].data[4]
>         + "<br/>"
>         + "- low:"
>         + params[0].data[3]
>         + "<br/>"
>         + "- close:"
>         + params[0].data[2]
>         + "<br/>"
>         + "- volume:"
>         + params[0].data[5]
>     )
>     return text
> ```

多谢大佬
