### ISSUE TITLE
Doc文档中文章链接错误

### ISSUE THREAD

**Issue by lamter** [pyecharts/pyecharts#806]
**问题**
https://github.com/pyecharts/pyecharts/tree/master/docs/zh-cn 
该文档中下方的链接错误，如文档中链接是 https://github.com/pyecharts/pyecharts/blob/master/docs/zh-cn/zh-cn/prepare
但是有效链接是
https://github.com/pyecharts/pyecharts/blob/master/docs/zh-cn/prepare.md

**Comment by chenjiandongx** [comment]
你访问 pyecharts.org 就没这个问题了
