### ISSUE TITLE
支持单独手动安装 pyecharts jupyter 扩展

### ISSUE THREAD

**Issue by kinegratii** [pyecharts/pyecharts#809]
**问题**

1. 目前 jupyter 扩展采用自动模式安装，导致对 jupyter 和 pyecharts 安装顺序有所要求。如果 pyecharts 先于 jupyter 安装，需要重新安装 pyecharts 以解决扩展安装问题。
2. pyecharts-jupyter-installer 库为必要的依赖（ pyecharts --> jupyter-echarts-pypkg --> pyecharts-jupyter-installer），但目前为 *隐式依赖*，不符合项目开发的一般规范，也不利于 pyecharts 离线安装的特殊要求。
3. 目前每个扩展都包含一样的安装器逻辑，在功能和代码均有冗余。

**方案**

1. 将 pyecharts-jupyter-installer 整合到 pyecharts 库，并提供 setup-script 命令行接口。
2. 适应性修改 xxx-pypkg 相关接口。
3. 安装方式
```
pip install pyecharts
pyecharts_cli jupyter_install jupyter-echarts
pip install echarts-china-provinces-pypkg
pyecharts_cli jupyter_install echarts-china-provinces-pypkg
```

**示例**

代码方式安装

```python
install_cmd_for = importlib.import_module('pyecharts_jupyter_installer').install_cmd_for

install_cmd_for('jupyter-echarts','jupyter_echarts_pypkg/resources/echarts')
```

命令行安装

```bash
pyecharts_cli jupyter_install --name jupyter-echarts --path jupyter_echarts_pypkg/resources/echarts
```

**策略**

根据是否修改已有 `pip install Foo` 的逻辑可分为以下两种策略：

第一种：修改变动少；功能有重合
```
1. pip install Foo
  - 安装到 site-packages
  - 安装到 jupyter （如果无jupyter省略）
2. pyecharts_cli jupyter_install Foo （jupyter为前置条件）
  - 安装到 jupyter
```

第二种：功能完全独立；修改变动多

```
1. pip install Foo
  - 安装到 site-packages
2. pyecharts_cli jupyter_install Foo （jupyter为前置条件）
  - 安装到 jupyter
```

由于第一种（目前情况）对于无 jupyter 环境没有视为错误，因此可将其作为过渡策略，同时整个系统也允许两种混合存在。

**Comment by kinegratii** [comment]
**实现**

基于 [click](https://click.palletsprojects.com/en/7.x/) 的多命令工具。
- click 库无其他额外依赖库。
- 能够支持 模块形式命令 和 延迟加载，类似于 Django Commands 的定义规范。

**Comment by chfw** [comment]
Click的缺点是测试费劲。google fire的缺点是依赖太多 但测试方便

**Comment by chfw** [comment]
显性安装是可以绕过本地wheel包不能重启jupyter installer的毛病

**Comment by chfw** [comment]
https://github.com/pyecharts/pyecharts-cli 是用google fire 先前做的模型

**Comment by kinegratii** [comment]
click 测试有一整套的解决方案，https://click.palletsprojects.com/en/7.x/testing/

**Comment by chfw** [comment]
是有单还是很难用！它的解决方案会吞掉stdout 的输出。这样以来 单元测试失败的话，查找原因很痛苦。

**Comment by forbxy** [comment]
搞得复杂了吧，是不是可以按照一般的notebook插件安装

**Comment by kinegratii** [comment]
完全可以按照一般的 notebook 插件安装，本 issue 提供了一共简单的自动安装程序（使用 Notebook API）。
