### ISSUE TITLE
同一张图里的折现图如何比较

### ISSUE THREAD

**Issue by Kwoks2017** [pyecharts/pyecharts#812]
**问题**
发现用`line`的时候 add多个线图之后不能多线图的对比，不知道是否我对`pycharts`的api不熟悉，以前echarts应该是有这个功能的

**运行环境（系统环境及 pyecharts 版本）**
`ubuntu16.04`, `pyecharts0.5.11`

**代码及截图**

**Comment by chenjiandongx** [comment]
能否给出 Echarts demo 的地址？
