### ISSUE TITLE
如何实现echarts中的富文本样式？

### ISSUE THREAD

**Issue by zhnlk** [pyecharts/pyecharts#814]
**问题**
echarts 中 有formatter + rich 的 富文本样式的用法，
不知道pyecharts 现在是否已经支持了？
如果支持，该如何调用呢~？谢谢

**运行环境（系统环境及 pyecharts 版本）**
OS : macOS 10.13.6
pyecharts version : 0.5.11

**代码及截图**

**Comment by chenjiandongx** [comment]
目前暂不支持，以后可能会考虑

**Comment by sunhailin-Leo** [comment]
@zhnlk 在即将发布的新版本已经可以通过 label 的 formatter 设置富文本啦～ 欢迎期待新版本～ 👏
