### ISSUE TITLE
Flask app not served when importing pyecharts

### ISSUE THREAD

**Issue by LionelR** [pyecharts/pyecharts#816]
Example code:
```python
import pyecharts
from flask import Flask

def create_app():
    app = Flask(__name__.split('.')[0])
    return app

    @app.route('/')
    def hello_world():
        return 'Hello, World!'
```
The app is not served, but commenting #import pyecharts gives
`Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)`

**Comment by LionelR** [comment]
Forgot to mention I'm in a fresh venv, with Python 3.6.6
pip list:
```
Package                     Version
--------------------------- -------
Click                       7.0
dukpy                       0.2.2
Flask                       1.0.2
future                      0.16.0
ItsDangerous                1.0.0
javascripthon               0.10
Jinja2                      2.10
jupyter-echarts-pypkg       0.1.2
lml                         0.0.2
macropy3                    1.1.0b2
MarkupSafe                  1.0
Pillow                      5.3.0
pip                         18.1
pyecharts                   0.5.11
pyecharts-javascripthon     0.0.6
pyecharts-jupyter-installer 0.0.3
pyecharts-snapshot          0.1.8
setuptools                  40.4.3
Werkzeug                    0.14.1
wheel                       0.32.2
```

**Comment by LionelR** [comment]
Ok it's not a serving problem, it's a logging problem. 
I'm not using app factory as it must be, so after re-coding:
test2_bp.py
```python
from flask import current_app, Blueprint
test = Blueprint('test', __name__, url_prefix='/test')

@test.route('/')
def index():
    return 'Hello, World!'
```
test2.py
```python
import pyecharts
from flask import Flask
from test2_bp import test

def create_app(info):
    app = Flask(__name__.split('.')[0])
    app.register_blueprint(test)
    return app
```
```
export FLASK_APP=test2
flask run
```
and visiting http://127.0.0.1:5000/test/ gives the good page.

But pyecharts seems to modify in some way the logger, because we don't have the output of the werkzeug logger (* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) ).

If we modify the code, we have back the logs:
```python
import pyecharts
from logging.config import dictConfig

from flask import Flask
from test2_bp import test

def create_app(info):
    app = Flask(__name__.split('.')[0])
    app.register_blueprint(test)

    print(app.logger.handlers[:])
    dictConfig({
        'version': 1,
        'formatters': {'default': {
                'format': '%(levelname)s %(name)s: %(message)s',
        }},
        'handlers': {'wsgi': {
                'class': 'logging.StreamHandler',
                'stream': 'ext://flask.logging.wsgi_errors_stream',
                'formatter': 'default'
        }},
        'root': {
                'level': 'INFO',
                'handlers': ['wsgi']
        }
    })
    app.logger.info('Started')
    
    return app
```
which gives
```
[<StreamHandler <stderr> (NOTSET)>]
INFO werkzeug:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

Now, where it's really strange, it's if we import flask_security AFTER pyecharts at the top of the file:
```python
import pyecharts
import flask_security
from logging.config import dictConfig
```
because the resulting output is:
```
[]
INFO werkzeug:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```
As seen, we lost the default flask handler, relaying to the root logger. This doesn't happen if flask_security is imported BEFORE pyecharts.

**Comment by chfw** [comment]
Unless you prove it, we do not accept that pyecharts has anything to cause flask problem.

Please remove pyecharts from your domain of problem and investigate further.

**Comment by LionelR** [comment]
Listen, if I remove `import pyecharts` the logs come back and I don't have to reconfigure the root logger. 
Just test my previous example

**Comment by chfw** [comment]
https://github.com/chfw/lml/blob/master/lml/__init__.py turns off the logging. So yes you need to configure your own logger.

**Comment by chfw** [comment]
But I don't think it would turn off your logging.

**Comment by LionelR** [comment]
Yes, I runs some tests and there's a problem between Werkzeug (flask dependancy) and one from pyecharts.
If you run this test
```python
import pyecharts
import werkzeug

_logger = None

def _log(type, message, *args, **kwargs):
    global _logger
    if _logger is None:
        import logging
        _logger = logging.getLogger('mylogging')
        if not logging.root.handlers and _logger.level == logging.NOTSET:
            _logger.setLevel(logging.INFO)
            handler = logging.StreamHandler()
            handler.setFormatter(logging.Formatter('%(levelname)s %(name)s >>> %(message)s'))
            _logger.addHandler(handler)
    getattr(_logger, type)(message.rstrip(), *args, **kwargs)

_log(type='info', message='test')
```
No info message will be displayed, but if you comment werkzeug or pyecharts, the message is displayed, as of if we import werkzeug before pyecharts.
Replacing pyecharts by lml and the problem dissapears, so it's another module.
As you say, I'll go to reconfigure the logging, but it's not clear in a production env with Flask :)

**Comment by chfw** [comment]
In production, flask logger is usually configured to log to a file. So log should go as normal.
