### ISSUE TITLE
Map画不出来了，看不到图，不知道怎么回事

### ISSUE THREAD

**Issue by royburns** [pyecharts/pyecharts#819]
**问题**
Map画不出来了，看不到图，不知道怎么回事
看了一下，是有数据的

series0
福建	155
山东	10
北京	66
上海	78
甘肃	33
新疆	80
河南	190
广西	53
西藏	49.6

**运行环境（系统环境及 pyecharts 版本）**
windows10，chrome最新版， pyecharts 0.5.11

**代码及截图**
from pyecharts import Map

value = [155, 10, 66, 78, 33, 80, 190, 53, 49.6]
attr = [
    "福建", "山东", "北京", "上海", "甘肃", "新疆", "河南", "广西", "西藏"
    ]
map = Map("Map 结合 VisualMap 示例", width=1200, height=600)
map.add(
    "",
    attr,
    value,
    maptype="china",
    is_visualmap=True,
    visual_text_color="#000",
)
map.render()

![image](https://user-images.githubusercontent.com/652375/47632689-1d641900-db86-11e8-9020-c5b00728ddeb.png)

**Comment by chfw** [comment]
看常见问题解答

**Comment by royburns** [comment]
多谢，搞定了
