### ISSUE TITLE
图例是否可以默认显示都是灰色的？方便后期点选查看

### ISSUE THREAD

**Issue by greenglan** [pyecharts/pyecharts#820]
**问题**
当图例分类比较多的时候，如下图：
![image](https://user-images.githubusercontent.com/44565836/47636641-04fafb00-db94-11e8-8030-460e3de1bd86.png)

希望可以默认图例显示一开始都是灰色的，后期可以依据查看者的需求点选增加或调整显示查看数据
![image](https://user-images.githubusercontent.com/44565836/47636556-ad5c8f80-db93-11e8-9618-eac08eb1fcd0.png)

不知道现在的版本是否可以支持？

**运行环境（系统环境及 pyecharts 版本）**
python是3.5
![image](https://user-images.githubusercontent.com/44565836/47636992-3b854580-db95-11e8-95b3-8721253292d5.png)

**Comment by chenjiandongx** [comment]
Legend 要不就全部都显示 要不就全部都不显示 看起来没有你想要的效果噢
