### ISSUE TITLE
V0.5.11版本 HeatMap 图纵坐标显示索引值，而非 data 值

### ISSUE THREAD

**Issue by gao-xuejian** [pyecharts/pyecharts#821]
在HeatMap中，使用以下代码进行测试，所显示的纵坐标都是其索引值，即0,1,2,3,4,5,6，而不是'Saturday','Friday'字样。

import random

from pyecharts import HeatMap

x_axis = [
"12a", "1a", "2a", "3a", "4a", "5a", "6a", "7a", "8a", "9a", "10a", "11a",
"12p", "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p", "10p", "11p"]
y_axis = [
"Saturday", "Friday", "Thursday", "Wednesday", "Tuesday", "Monday", "Sunday"]
data = [[i, j, random.randint(0, 50)] for i in range(24) for j in range(7)]
heatmap = HeatMap()
heatmap.add("热力图直角坐标系", x_axis, y_axis, data, is_visualmap=True,
visual_text_color="#000", visual_orient='horizontal')
heatmap.render()

**Comment by zskyliang** [comment]
我0.5.5也有这个问题 升到0.5.11也是一样

**Comment by ezaze** [comment]
目前还没好呀。。。。求解呀~~

**Comment by ezaze** [comment]
找到解决方案了。。把生成的html文件中的“"formatter": "{value} ",” 这行删了。能临时解决这个问题~ 大家可以试试。

**Comment by CN4everxx** [comment]
https://github.com/pyecharts/pyecharts/pull/843

可以参考这个方案修改code。测试有效。

**Comment by chenjiandongx** [comment]
下个版本将会修复，预计于四月发布

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！使用 1.0.0 版本可以解决该问题
