### ISSUE TITLE
K线图和折线图不能同时显示吗？

### ISSUE THREAD

**Issue by leonlee723** [pyecharts/pyecharts#822]
用Overlap，加一个Kline再加一个Line，但不能同时显示在一个图里
默认是Kline显示出来，但Line不显示。点击数据，进入数据窗口后，再点刷新是Line显示出来，Kline不显示了

**Comment by chenjiandongx** [comment]
#830 @leonlee723 可以，使用 Grid

**Comment by usernamehastaken** [comment]
@chenjiandongx 主要是之前好多函数都是用overlap打包了，现在改起来比较麻烦，为什么现在overlap不能这么用了？

**Comment by usernamehastaken** [comment]
而且kline和line放一张图和用grid还是不一样的

**Comment by erikgqp8645** [comment]
我也遇到这个问题了，请问你解决了没有。

**Comment by erikgqp8645** [comment]
https://github.com/pyecharts/pyecharts/issues/854#issue-386072649 我是这样解决的

**Comment by edwardzhang0630** [comment]
我也遇到了同样的问题，overlap.add(kline) overlap.add(line)后 只显示kline，不显示line

![kline_bug](https://user-images.githubusercontent.com/33045925/55140896-1ad91000-5174-11e9-913f-e3c845767395.PNG)

**Comment by edwardzhang0630** [comment]
我定位这个bug一下午，终于找到原因了。。。。。

我的数据是存储在pandas的dataframe中的，
k线图的x_axis是时间

我的时间也是存储在dataframe中，并且直接取出来
datetime = data['datetime']
然后
kline.add('kline', datetime, price)
line.add('line', datetime, line_data)

overlap.add(kline)
overlap.add(line)

overlap.render()

这个时候，k线完全能够显示，但是line不见了。

因为这里的datetime格式是<class 'pandas.core.series.Series'>

需要将datetime的格式改成list就完美解决
datetime = datetime.tolist()
