### ISSUE TITLE
并行显示多张图标是否支持多图关联交互

### ISSUE THREAD

**Issue by mimimiracle** [pyecharts/pyecharts#824]
看了几遍文档好像没有相关的例子，请问在jupyter notebook里生成的“并行显示多张图”是否可以多图关联交互
比如这张图，点击右边环形图上某个类别,或者右边标签的类别，左边的折线图会变换成改类别的数据走势
![35089737-ccc1c01c-fc72-11e7-874d-8ba8b89572eb](https://user-images.githubusercontent.com/31721046/47843583-0aa64a00-ddfb-11e8-9d4c-0114e3783962.png)
习惯了在其他可视化软件里做动态交互的挖掘，很想知道在pyecharts里怎么可以实现，谢谢！

**Comment by chenjiandongx** [comment]
目前 pyecharts 暂不支持自定义多图联动。
