### ISSUE TITLE
add 函数的 docstrings 在 jupyter notebook 中的显示

### ISSUE THREAD

**Issue by xchaoinfo** [pyecharts/pyecharts#825]
目前的 `add` 函数是通过调用 `__add` 函数来实现的，`docstrings` 也在 `__add` 函数中。
这导致无法在 `Jupyter notebook` 中通过 `add? `来快速的查看文档。
这个问题的最简单的解决方案是，将`__add` 函数中的 `docstrings` 移动到 `add` 函数中。

**Comment by chenjiandongx** [comment]
add 根据不同的 Charts，参数它是不同的，

**Comment by xchaoinfo** [comment]
@chenjiandongx  可能我前面的表述不够清楚。
我的主要是思想是，希望能够在 Jupyter Notebook 中方便快速查看 Pyecharts 的 **帮助文档**。
例如在使用 pandas 时候，在 Jupyter notebook 中，可以快速的通过 `pandas.read_table?` 来查看 read_table 的使用方法，以及相关参数。
![image](https://user-images.githubusercontent.com/10547442/47892724-49d4a980-de94-11e8-9b28-d43787746174.png)

**Comment by chenjiandongx** [comment]
pyecharts 的 add 目前的项目结构无法做到这一点哈
