### ISSUE TITLE
关于pyecharts制作地图扩展

### ISSUE THREAD

**Issue by aliwanan** [pyecharts/pyecharts#829]
**问题**
1、制作地图扩展，yh后出现错误如下图，不知project.yml存于何处？
2、如何获得北京市的json（不包含北京市下的区分布）

**运行环境（系统环境及 pyecharts 版本）**
MAC OS 
pyecharts 0.5.9

**代码及截图**

![image](https://user-images.githubusercontent.com/44763871/48037426-26b53d00-e1a7-11e8-8c16-1f50cb83136a.png)

**Comment by chfw** [comment]
少了两个文件。所以，你是第一个用的人。现在修复了。
