### ISSUE TITLE
K线图与柱状图合并后，柱状图显示的数据错误

### ISSUE THREAD

**Issue by maosgithub** [pyecharts/pyecharts#830]
**问题**
K线图与柱状图用Grid合并后，柱状图的数据显示undefined

**运行环境（系统环境及 pyecharts 版本）**
python=3.6.2
pyecharts=0.5.11
**代码及截图**
```
import pandas as pd
from datetime import datetime
from pyecharts import Kline, Bar, Grid

name='stock'
period = '15m'
df = pd.DataFrame(
    columns=['open', 'close', 'low', 'high', 'volume'],
    data=[[55752.3120, 55741.741, 55875.961, 55693.6020, 36006.0],
          [55745.6680, 55616.086, 55773.168, 55616.0860, 21378.0],
          [55618.2810, 55354.407, 55623.213, 55370.4350, 30120.0],
          [55354.4900, 55205.008, 55389.210, 55193.1670, 35978.0]],
    index=[datetime(2018, 1, 2, 9, 15), datetime(2018, 1, 2, 9, 30), datetime(2018, 1, 2, 9, 45),
           datetime(2018, 1, 2, 10)]
)
kline = Kline(name, width=1600, height=800)
kline.add(
    name,
    df.index.format(),
    df[['open', 'close', 'low', 'high']].values,
    is_xaxislabel_align=True,
    xaxis_pos='top',

)
bar = Bar('成交量')
bar.add(
    '成交量',
    df.index.format(),
    df['volume'].values,
    is_xaxislabel_align=True,
    legend_top="70%",
    legend_pos='left',
    xaxis_pos='bottom',
)
grid = Grid()

grid.add(kline, grid_bottom="30%")
grid.add(bar, grid_top="70%")

grid.render()

```
*截图*
![image](https://user-images.githubusercontent.com/27139555/48039739-2883fe00-e1b1-11e8-9665-681b698bae71.png)
柱状图显示的数据错误
![image](https://user-images.githubusercontent.com/27139555/48039768-47829000-e1b1-11e8-9174-b8c90551a514.png)

**Comment by chenjiandongx** [comment]
试试这个

```python
import pandas as pd
from datetime import datetime

from pyecharts import Kline, Bar, Grid

name = "stock"
period = "15m"
df = pd.DataFrame(
    columns=["open", "close", "low", "high", "volume"],
    data=[
        [55752.3120, 55741.741, 55875.961, 55693.6020, 36006.0],
        [55745.6680, 55616.086, 55773.168, 55616.0860, 21378.0],
        [55618.2810, 55354.407, 55623.213, 55370.4350, 30120.0],
        [55354.4900, 55205.008, 55389.210, 55193.1670, 35978.0],
    ],
    index=[
        datetime(2018, 1, 2, 9, 15),
        datetime(2018, 1, 2, 9, 30),
        datetime(2018, 1, 2, 9, 45),
        datetime(2018, 1, 2, 10),
    ],
)
kline = Kline(name)
kline.add(
    name,
    df.index.format(),
    df[["open", "close", "low", "high"]].values,
    is_xaxislabel_align=True,
    xaxis_pos="top",
)

bar = Bar("成交量")
bar.add(
    "成交量",
    df.index.format(),
    df["volume"].values,
    is_xaxislabel_align=True,
    legend_top="70%",
    legend_pos="left",
    xaxis_pos="bottom",
)

grid = Grid(width=1200, height=600)
grid.add(bar, grid_top="70%")
grid.add(kline, grid_bottom="30%")
grid.render()
```

标题还有 legend 就自己作细节调整

**Comment by maosgithub** [comment]
> 试试这个 @maosgithub
> 
> ```python
> import pandas as pd
> from datetime import datetime
> 
> from pyecharts import Kline, Bar, Grid
> 
> name = "stock"
> period = "15m"
> df = pd.DataFrame(
>     columns=["open", "close", "low", "high", "volume"],
>     data=[
>         [55752.3120, 55741.741, 55875.961, 55693.6020, 36006.0],
>         [55745.6680, 55616.086, 55773.168, 55616.0860, 21378.0],
>         [55618.2810, 55354.407, 55623.213, 55370.4350, 30120.0],
>         [55354.4900, 55205.008, 55389.210, 55193.1670, 35978.0],
>     ],
>     index=[
>         datetime(2018, 1, 2, 9, 15),
>         datetime(2018, 1, 2, 9, 30),
>         datetime(2018, 1, 2, 9, 45),
>         datetime(2018, 1, 2, 10),
>     ],
> )
> kline = Kline(name)
> kline.add(
>     name,
>     df.index.format(),
>     df[["open", "close", "low", "high"]].values,
>     is_xaxislabel_align=True,
>     xaxis_pos="top",
> )
> 
> bar = Bar("成交量")
> bar.add(
>     "成交量",
>     df.index.format(),
>     df["volume"].values,
>     is_xaxislabel_align=True,
>     legend_top="70%",
>     legend_pos="left",
>     xaxis_pos="bottom",
> )
> 
> grid = Grid(width=1200, height=600)
> grid.add(bar, grid_top="70%")
> grid.add(kline, grid_bottom="30%")
> grid.render()
> ```
> 
> 标题还有 legend 就自己作细节调整

感谢解答

**Comment by tujian** [comment]
@chenjiandongx grid里的子图可以共享datazoom吗？

**Comment by tujian** [comment]
> @chenjiandongx grid里的子图可以共享datazoom吗？

找到了，设置datazoom “xaxis_index=[0, 1]"就行。
