### ISSUE TITLE
grid后重叠

### ISSUE THREAD

**Issue by 984958198** [pyecharts/pyecharts#836]
**问题**
grid对两个图表合并后， 两个图的标题重叠（因为两个图都设置了 title_pos='center'）
我觉得这很不友好，居中不应该按合并图的长度来算，虽然可以通过参数来调整标题，
但标签这块调整不了 或者不知道怎么调整

**运行环境（系统环境及 pyecharts 版本）**
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
pyecharts                    0.5.11

**代码及截图**

![1541660191 1](https://user-images.githubusercontent.com/9883283/48186511-210c5280-e373-11e8-8d23-fc26181d5363.jpg)

**Comment by chenjiandongx** [comment]
确实是个问题

**Comment by ciciandjojo** [comment]
> 确实是个问题
大佬原来这个问题之前也存在啊，怎么解决啊

**Comment by ciciandjojo** [comment]
> **问题**
> grid对两个图表合并后， 两个图的标题重叠（因为两个图都设置了 title_pos='center'）
> 我觉得这很不友好，居中不应该按合并图的长度来算，虽然可以通过参数来调整标题，
> 但标签这块调整不了 或者不知道怎么调整
> 
> **运行环境（系统环境及 pyecharts 版本）**
> Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
> pyecharts 0.5.11
> 
> **代码及截图**
> 
> ![1541660191 1](https://user-images.githubusercontent.com/9883283/48186511-210c5280-e373-11e8-8d23-fc26181d5363.jpg)

大佬有解决的方法吗

**Comment by 984958198** [comment]
没，直接弃用了grid
