### ISSUE TITLE
交换坐标轴后的bar图的y轴刻度无法正确显示

### ISSUE THREAD

**Issue by wisherg** [pyecharts/pyecharts#840]
交换坐标轴后的bar图的y轴刻度无法正确显示
热力图则直接y轴无法正确显示
pip install jupyter-echarts-pypkg==0.1.1后并没有什么用

**运行环境（系统环境及 pyecharts 版本）**
win8, python3.7  pyecharts版本：'0.5.11'

**代码及截图**
#heatmap也一样

from pyecharts import Bar

attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v2 = [10, 25, 8, 60, 20, 80]
bar = Bar("x 轴和 y 轴交换")
bar.add("商家B", attr, v2, is_convert=True)
bar

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！新版本已修复该问题
