### ISSUE TITLE
关于MAP地图显示问题

### ISSUE THREAD

**Issue by Woniuke** [pyecharts/pyecharts#841]
**问题**
ECharts官网示例中 MAP可以指定边界样式，那么python 中这个参数应该传递给谁呢？

						itemStyle:{
							normal:{
								borderColor:'#A1DFF2',	//地图边界线颜色
								borderWidth:1,	//边界线宽度
								areaStyle:{
									color:'white'
								},
								label:{
									show:true
								}
							}
						}

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chenjiandongx** [comment]
#1033 使用新版本有 itemstyle 配置项
