### ISSUE TITLE
拼接几个省份的地图的问题

### ISSUE THREAD

**Issue by JoeinChina** [pyecharts/pyecharts#845]
**问题**
想画京津冀28个城市的数据可视化，但北京、天津的maptype为城市，自动显示区；河北、河南、山西、山东的maptype为省份，自动显示城市；且用add后多图重叠，不知pyecharts中是否有此类功能？

**运行环境（系统环境及 pyecharts 版本）**
Python3.7 + widows10 + pyecharts 0.5.11

**代码及截图**
![image](https://user-images.githubusercontent.com/23374841/48685788-18c5da00-ebf3-11e8-9f63-101b808cac73.png)

**Comment by JoeinChina** [comment]
![2 26](https://user-images.githubusercontent.com/23374841/48773681-1488e200-ed03-11e8-9e78-f9c68f4204a2.jpg)
用tableau实现了，过后研究下希望通过代码实现，pyecharts工具很优秀！！！

**Comment by tony-tian** [comment]
@chfw 您好，请问这个功能以后会提供吗？

**Comment by chfw** [comment]
会。比如：苏皖浙

https://echarts-maps.github.io/echarts-china-misc-js/preview.html
