### ISSUE TITLE
line图表，保存为html后用浏览器打开不显示数据，点击data view里面的刷新才显示正常

### ISSUE THREAD

**Issue by dachoume** [pyecharts/pyecharts#847]
**问题**
line图表，保存为html后用浏览器打开不显示数据，点击data view里面的刷新才显示正常

**运行环境（系统环境及 pyecharts 版本）**
版本0.5.11
python3.6.2

**代码及截图**
line_rssi = Line()
line_rssi.add('com3',
              k_com3,
              v_com3,
              xaxis_name='秒值时间戳',
              yaxis_name='信号强度',
              is_datazoom_show=True,
              datazoom_type='inside')

line_rssi.add('com4',
              k_com4,
              v_com4,
              xaxis_name='秒值时间戳',
              yaxis_name='信号强度',
              is_datazoom_show=True,
              datazoom_type='inside')

line_rssi.render('ble_2master_rssi_paint/rssi_0.html')
print('画图完成')

![image](https://user-images.githubusercontent.com/26477998/48695072-15dde000-ec19-11e8-9623-f731ad636290.png)
![image-1](https://user-images.githubusercontent.com/26477998/48695086-242bfc00-ec19-11e8-869f-2b5051ca02c6.png)

**Comment by HuangDekai** [comment]
感谢，我也是遇到这个问题

**Comment by weidongysu** [comment]
您好，这个有解决办法了么

**Comment by Sgp-Sling** [comment]
你好，我也遇到同样的问题，特地注册了来反映一下……

**Comment by BlownSnail** [comment]
（特地注册回复）
问题从0.5.6版本开始，第一个方法是安装0.5.5版本：
```pip install pyecharts==0.5.5```
第二个办法是修改pyecharts\charts\line.py，第80行`"data": _data,`修改为`"data": y_axis,`

此bug与[#639](https://github.com/pyecharts/pyecharts/issues/639)有关

**Comment by chenjiandongx** [comment]
下个版本将会修复，预计于四月发布

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！新版本已修复该问题

**Comment by lingburan** [comment]
有没有试过把x轴输入改为str类型

**Comment by weidongysu** [comment]
来信收到，顺祝事祺！
