### ISSUE TITLE
Support changing xAxis type=value in the interface

### ISSUE THREAD

**Issue by hupili** [pyecharts/pyecharts#850]
**问题**

Refer to the first code block and image of [this comment](https://github.com/hupili/python-for-data-and-media-communication-gitbook/issues/104#issuecomment-441278543) for minimum reproducible example.

**运行环境（系统环境及 pyecharts 版本）**

- Mac OSX
- Python 3.7
- pyecharts '0.5.11'

**代码及截图**

Here is a [quick hack on _option](https://github.com/hupili/python-for-data-and-media-communication-gitbook/issues/104#issuecomment-441281638).

Looking forward to supporting type=value in xAxis option.

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！该需求现已实现啦
