### ISSUE TITLE
如何设定x轴坐标范围 

### ISSUE THREAD

**Issue by AlphaSmartDog** [pyecharts/pyecharts#851]
![default](https://user-images.githubusercontent.com/24935017/49142044-e32b9a00-f332-11e8-8e03-7b5cc2020a65.PNG)
如何设置x轴坐标范围为2到3，我不想要0~3这么大的范围

**Comment by VictorGump** [comment]
同问，无法改变坐标轴的起始值，和结束值

**Comment by chenjiandongx** [comment]
#1033 新版本提供 min_, max_ 参数设置 X 轴范围
