### ISSUE TITLE
图例绑定

### ISSUE THREAD

**Issue by congx961** [pyecharts/pyecharts#853]
**问题**
在画折线图的过程中，如何实现图例与线条的绑定及自定义图例？
比如我有三种算法结果，每一种算法（名称一致）包含两条曲线（实线与虚线），我希望实现图例中既有基于名称的图例（对应于相同名称的两条曲线），又有基于线条类型的图例（对应于线条类型）。
请问该如何实现？或者说如何自定义legend并完成与线条的绑定？

**Comment by sunhailin-Leo** [comment]
可以尝试新版本的代码。如果依旧出现该问题，请重新提 issue 并附上你的代码，thx～
