### ISSUE TITLE
calendar graph available?

### ISSUE THREAD

**Issue by lzpons** [pyecharts/pyecharts#856]
Hi,
I would like to display calendar-type graphs [like this one](https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-effectscatter) in Jupyter. 
The closest type I've found in the documentation is the heatmap.

Can it be done or calendar type is not yet implemented?

Thank you for your help
LP

**Comment by lzpons** [comment]
Hi,
anyone has the answer to the question, please?

**Comment by sunhailin-Leo** [comment]
@lzpons Calendar Graph is available in `pyecharts` new version! You can try it 😄

**Comment by lzpons** [comment]
We've tested and it works, 
Great job thanks!
