### ISSUE TITLE
V0.5.11，Line图形错误

### ISSUE THREAD

**Issue by usernamehastaken** [pyecharts/pyecharts#858]
**问题**
V.0.5.11版本
line显示数据错误，电机查看数据后再刷新就正常
**代码及截图**
![image](https://user-images.githubusercontent.com/27677764/49412833-d1217f80-f7a8-11e8-83a9-2654880b96e1.png)

**Comment by chenjiandongx** [comment]
下个版本将会修复，预计于四月发布

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！该问题已修复
