### ISSUE TITLE
adding font properties parameter?

### ISSUE THREAD

**Issue by solelysoar** [pyecharts/pyecharts#860]
**问题**
Is there any font property parameter where I can change the font style in the chart? I searched in the document and issues but didn't find any. It would be of great help when I need to use image generated in my firm slides and keep the font style the same.
Thanks!

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chenjiandongx** [comment]
In pyecharts 1.0.0

![image](https://user-images.githubusercontent.com/19553554/57318406-e0787080-712c-11e9-8344-04a58c0c5ba1.png)
