### ISSUE TITLE
地图支持纯英文

### ISSUE THREAD

**Issue by relengxing** [pyecharts/pyecharts#861]
请问可以支持纯英文的吗，在外企工作，老大不允许出现中文。
国家这个地方只能用中文

<img width="1123" alt="screen shot 2018-12-06 at 16 10 37" src="https://user-images.githubusercontent.com/16727976/49570460-9f0f4980-f971-11e8-9552-746406a6abab.png">

**Comment by chfw** [comment]
还不支持英文。我需要找时间弄上。

**Comment by sunhailin-Leo** [comment]
@relengxing 
* 可以参考这个例子使用 `name_map` 把地图上的中文替换成英文
* 例子：http://gallery.pyecharts.org/#/Geo_Map_BMap/population_density_of_HongKong
