### ISSUE TITLE
是否可以实现画地图显示街道等详细地图信息

### ISSUE THREAD

**Issue by jingwb222** [pyecharts/pyecharts#862]
目前调用Geo, Map画的地图只是区域轮廓，请问如何显示出具体的街道吗，类似官方文档中[实例](http://echarts.baidu.com/examples/editor.html?c=lines-bmap)？谢谢

**Comment by chfw** [comment]
缺的是地图文件。

**Comment by zhuyeqing** [comment]
能才有类似于folium的方式解决么？folium可以使用高德地图

**Comment by zhuyeqing** [comment]
> 缺的是地图文件。

能才有类似于folium的方式解决么？folium可以使用高德地图

**Comment by chenjiandongx** [comment]
可以 下一步将集成百度地图

**Comment by sunhailin-Leo** [comment]
@jingwb222 @zhuyeqing 
* 接下来的新版本将支持 BMap 百度地图，可以支持在地图画图了 👏
