### ISSUE TITLE
WordCloud自定义形状

### ISSUE THREAD

**Issue by pjgao** [pyecharts/pyecharts#863]
请问pyecharts的wordcloud模块能否像python库wordcloud那样指定本地图片来作为shape？

**Comment by chenjiandongx** [comment]
不能指定图片 但可以提供 SVG 图片路径

**Comment by sppsun** [comment]
大佬好==
“不能指定图片 但可以提供 SVG 图片路径”这个可否给出个示例？
谢谢。
