### ISSUE TITLE
如何调整bar新添加的图形的间距？

### ISSUE THREAD

**Issue by pjgao** [pyecharts/pyecharts#864]
如下图所示：
```python
import pyecharts
import pandas as pd
df = pd.DataFrame({'a':[1,2,3,4],'b':[4,6,8,2],'c':[2,4,3,8]})

bar = pyecharts.Bar()
bar.add('a',df.index,df.a,bar_category_gap=30)
bar.add('b',df.index,df.b,bar_category_gap=30)
bar.add('c',df.index,df.c,bar_category_gap=30)
bar
```
![snipaste_2018-12-09_17-34-24](https://user-images.githubusercontent.com/22350313/49696549-02a1ad00-fbe6-11e8-85fb-50e3f0b2690e.png)

**Comment by chenjiandongx** [comment]
各 series 之间的间隔好像没得设置

**Comment by ciciandjojo** [comment]
> 如下图所示：
> 
> ```python
> import pyecharts
> import pandas as pd
> df = pd.DataFrame({'a':[1,2,3,4],'b':[4,6,8,2],'c':[2,4,3,8]})
> 
> bar = pyecharts.Bar()
> bar.add('a',df.index,df.a,bar_category_gap=30)
> bar.add('b',df.index,df.b,bar_category_gap=30)
> bar.add('c',df.index,df.c,bar_category_gap=30)
> bar
> ```
> 
> ![snipaste_2018-12-09_17-34-24](https://user-images.githubusercontent.com/22350313/49696549-02a1ad00-fbe6-11e8-85fb-50e3f0b2690e.png)

目前不是有个直方图吗，直接用哪个就好啦

**Comment by chenjiandongx** [comment]
#1033 请尝试使用新版本的 category_gap 参数

**Comment by pjgao** [comment]
> #1033 请尝试使用新版本的 category_gap 参数

```
attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 75, 90]
v2 = [10, 25, 8, 60, 20, 80]
v3 = [20, 45, 28, 80, 20, 70]


bar = (
    Bar()
    .add_xaxis(attr)
    .add_yaxis("商家A", v1,category_gap=30)
    .add_yaxis("商家B", v2,category_gap=30)
    .add_yaxis("商家C", v3,category_gap=30)
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(title_opts=opts.TitleOpts(title="柱状图数据堆叠示例"))
)

bar.render_notebook()
```
这里改变的好像还是不同x坐标的间距（图中蓝色部分），而不是series的间距（图中黄色部分）

**Comment by chenjiandongx** [comment]
```python
def bar_gap() -> Bar:
    c = (
        Bar()
        .add_xaxis(Faker.choose())
        .add_yaxis("商家A", Faker.values(), gap="0%")
        .add_yaxis("商家B", Faker.values(), gap="0%")
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Bar-不同系列柱间距离"),
        )
    )
    return c
```

![image_227](https://user-images.githubusercontent.com/19553554/57316521-955c5e80-7128-11e9-9f95-adf413015472.png)
