### ISSUE TITLE
Grid上brush组件，Geo、Pie的交互问题

### ISSUE THREAD

**Issue by suyixiao** [pyecharts/pyecharts#865]
**问题**
Geo通过brush组件交互产生Pie饼图，饼图不显示

**运行环境（系统环境及 pyecharts 版本）**
win10
pyecharts 0.5.11

**代码及截图**
from pyecharts import Grid,Geo,Pie
import pyecharts.echarts.events as events

def renderbrush(params):
    global grid
    mainseries=params["batch"][0]["selected"][0]
    piedata=[]
    for i in mainseries["dataIndex"]:
        piedata.append(data[i][1])

    grid._option["series"][1]["data"]=piedata

 

data = [("海门", 9), ("鄂尔多斯", 12), ("招远", 12), ("舟山", 12), ("齐齐哈尔", 14), ("盐城", 15)]

grid=Grid("")
def test_brush():
    #geo
    geo = Geo(
        "全国主要城市空气质量",
        "data from pm2.5",
        title_color="#fff",
        title_pos="center",
        width=1200,
        height=600,
        background_color="#404a59")

    attr, value = geo.cast(data)
    geo.add("", attr, value, 
        type="effectScatter", 
        #is_random=True,
        effect_scale=5) 
    
    grid.add(geo, 
        grid_right="40%",
        grid_top="100%",
        grid_bottom='40%',
        grid_width='30%')
    grid._option["series"][0]["zlevel"]=0
    
    #brush
    grid._option['brush']= {"outOfBrush": {"color": '#abc'},
                           "geoIndex": "all",
                            "throttleType": 'debounce',
                            "throttleDelay": 300,
                            "seriesIndex": 0}
    #pie
    pie = Pie("")
    pie.add("", [],[], 
        center=[80,60],
        radius=[0,30],
        is_legend_show=False,
        is_label_show=True)
    grid.add(pie, grid_right="1%",grid_top="70%") 
    grid._option["series"][1]["zlevel"]=1    
    
    # events
    grid.on(events.BRUSH_SELECTED, renderbrush)
    grid.render("my_test_geo_map.html")

if __name__ == "__main__":
    test_brush()
![default](https://user-images.githubusercontent.com/45647622/49698650-9e8ce200-fc01-11e8-8ae2-c4160dc75cc0.PNG)

**Comment by suyixiao** [comment]
> 单独的 Pie + Geo 能够正常显示吗？

是正常可以显示的~

**Comment by chenjiandongx** [comment]
那你知道 Echarts 上怎么配置才能正常显示吗

**Comment by suyixiao** [comment]
> 那你知道 Echarts 上怎么配置才能正常显示吗

http://www.echartsjs.com/gallery/editor.html?c=scatter-map-brush
我是参考echarts的示例（例见上网址），例中是geo_brush_bar，我尝试的是geo_brush_pie
感觉是renderbrush函数对pie的data的赋值没有完成~

**Comment by chenjiandongx** [comment]
核心还是在于这个

![image](https://user-images.githubusercontent.com/19553554/49717063-c37c6600-fc90-11e8-9975-1254bb1cc46b.png)

这个写好了 才有可能让 Bar/Pie 跟 Geo 联动

**Comment by chenjiandongx** [comment]
因为 Brush 这个 pyecharts 是没有的 我也没有研究和测试过 具体有没有什么坑也不太清楚哈

**Comment by chfw** [comment]
把上面的 javascript 用 python 写不就行了么？

**Comment by suyixiao** [comment]
@chfw  大佬，主要是对js不是特别了解，而且感觉，下面renderbruah函数的写法没问题，纠结，是grid不支持on？

**Comment by FankLi** [comment]
grid.add(geo)
grid.add(bar)

这样为什么会报错呢？
`self._option.get("xAxis").append(_x)
AttributeError: 'NoneType' object has no attribute 'append'`

**Comment by sunhailin-Leo** [comment]
现在新版已经支持 brush 组件了，可以进行尝试
