### ISSUE TITLE
打包后，报错could not get source code

### ISSUE THREAD

**Issue by yhliu-chn** [pyecharts/pyecharts#867]
**问题**
在代码环境下运行一切正常，但通过Pyinstaller打包后，执行时会报错。未升级前较老版本pyecharts不会出这样错误

**运行环境（系统环境及 pyecharts 版本）**
win10
python 3.4.5
pyecharts 0.5.11

**代码及截图**

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！可以使用新版的打包试试看，pyecharts 不提供 pyinstaller 打包保证
