### ISSUE TITLE
数据有缺时，折线图显示不完全

### ISSUE THREAD

**Issue by XuXin09** [pyecharts/pyecharts#868]
**问题**
折线图数据有nan时数据显示不完全。
**说明**：默认没有设置xaxis_interval，如图1，1-52周的数据，x轴只间隔显示，相对应的一些有数据的点没有在图中显示。设置了xaxis_interval=0后，如图2，x轴显示完全，折线达到了想要的效果，但x轴重叠，比较丑，虽然可以调整x轴字体大小，但输出图有一定字体大小的要求，还是要保证看得清。
**需求**：请问这种情况下，有没有x轴标签间隔显示但折线完全显示数据点的方法。

有找到下面这个issue，但其问的是标记点显示，且数据很全，还是有差别的。
https://github.com/pyecharts/pyecharts/issues/231

**运行环境（系统环境及 pyecharts 版本）**
win10
pyecharts 0.5.5

**代码及截图**
数据：
![myei7nc w04f2 b8 y ptio](https://user-images.githubusercontent.com/22385948/49861375-a71a2e00-fe36-11e8-839f-2757c6521445.png)
图1：默认效果，数据点不完全显示
![jw7vj9oox 2l4trn hha](https://user-images.githubusercontent.com/22385948/49861398-b305f000-fe36-11e8-99cb-7e9503ed9f37.png)
图2：设置了xaxis_interval=0后，数据显示完全，但x轴重合。
![c kueyxdxgx_ h _e 8mh](https://user-images.githubusercontent.com/22385948/49861427-c44efc80-fe36-11e8-8c82-07fdd289df89.png)

**Comment by XuXin09** [comment]
@erikgqp8645 
你好~~
图表展示的是机器监测值，就是真实数据来的，填补nan的话（就算补成0），失去了监测的那种感觉。
另外用折线是觉得看“趋势”这种东西比较直观，同时能看到未监测的时间。

**Comment by erikgqp8645** [comment]
> @erikgqp8645
> 你好~~
> 图表展示的是机器监测值，就是真实数据来的，填补nan的话（就算补成0），失去了监测的那种感觉。
> 另外用折线是觉得看“趋势”这种东西比较直观，同时能看到未监测的时间。
@XuXin09 
Nan值应该就是缺失的，我弄得时候都会补全，如果你觉得影响的话，可以试试直方图也不错的。（为什么没有表情包呢）

**Comment by XuXin09** [comment]
@erikgqp8645 谢谢你的建议。但就目前这份数据，还是折线图最符合我想要表达的内容。:smile:（我是表情包）

**Comment by erikgqp8645** [comment]
> @erikgqp8645 谢谢你的建议。但就目前这份数据，还是折线图最符合我想要表达的内容。（我是表情包）

@XuXin09 
好吧，没有解决这个问题哈。
那么我们接下来能否讨论一下这个表情包怎么弄出来的呢？....

**Comment by XuXin09** [comment]
@erikgqp8645  搜下关键字（github，表情包）就有结果了。

我继续等待作者或者其他大神回答。

**Comment by erikgqp8645** [comment]
> @erikgqp8645 搜下关键字（github，表情包）就有结果了。
> 
> 我继续等待作者或者其他大神回答。

多谢啦，祝你很快就能解决

**Comment by chenjiandongx** [comment]
nan 值本身的策略就是不显示
