### ISSUE TITLE
多条折现如何默认隐藏某条？

### ISSUE THREAD

**Issue by kopes18** [pyecharts/pyecharts#869]
![image](https://user-images.githubusercontent.com/2020442/49919812-e1d9a000-fee2-11e8-82b4-bbd604bd8ecc.png)

比如有两条折现，默认只显示1，隐藏2。
Echarts官方文档参考 [http://echarts.baidu.com/option.html#legend.selected](url)

类似问题实现方法 [https://segmentfault.com/q/1010000009205440/a-1020000009207320](url)

好像现在Pyecharts中没有实现此功能：
`
selected: {
    // 选中'系列1'
    '系列1': true,
    // 不选中'系列2'
    '系列2': false
}
`

**Comment by sjk7524068** [comment]
同问这种效果要怎么设置，刚需啊

**Comment by robyyang** [comment]
同问，我需要显示的数据太多了。同时显示的时候特别卡。我只想 根据自己的习惯去筛选。

**Comment by chenjiandongx** [comment]
下个版本将会支持，预计于四月发布

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！已提供 `is_selected` 参数

**Comment by 543090050** [comment]
> #1033 1.0.0 版本发布啦！已提供 `is_selected` 参数

2.0版本没有这个参数了，该如何实现此功能

**Comment by sunhailin-Leo** [comment]
> > #1033 1.0.0 版本发布啦！已提供 `is_selected` 参数
> 
> 2.0版本没有这个参数了，该如何实现此功能

https://gallery.pyecharts.org/#/Bar/bar_is_selected?id=pyecharts-%e4%bb%a3%e7%a0%81-%e6%95%88%e6%9e%9c
