### ISSUE TITLE
如何实现显示大于等于3个y轴

### ISSUE THREAD

**Issue by bulalala** [pyecharts/pyecharts#870]
我用overlap实现时右边的两个y轴重合在一起了

**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@bulalala 
* 示例地址：https://github.com/pyecharts/pyecharts-gallery/blob/master/Bar/multiple_y_axes.py
* 目前这个还在 dev 的分支上，所以如果急切需要的话，需要拉取 dev 分支源码。卸载旧版本，通过源码安装。
