### ISSUE TITLE
默认Y轴 log 数值显示格式问题

### ISSUE THREAD

**Issue by kopes18** [pyecharts/pyecharts#872]
官方的示例会使用逗号将数值分开 [http://www.echartsjs.com/examples/editor.html?c=line-log](url)
![image](https://user-images.githubusercontent.com/2020442/49940966-26cdf880-ff1c-11e8-81a7-4414e7581461.png)
但是我运行的结果并没有默认显示逗号，如图：
![image](https://user-images.githubusercontent.com/2020442/49941015-49601180-ff1c-11e8-901f-7571adb09fe1.png)
如果默认可以显示逗号会方便，请问是否可以将此项默认值修改成和官方一致？

**Comment by sunhailin-Leo** [comment]
@kopes18 
![image](https://user-images.githubusercontent.com/17564655/57219319-48925e00-702a-11e9-929a-202883be8b1f.png)

**Comment by sunhailin-Leo** [comment]
@kopes18 
* 基于 pyecharts 1.0.0 进行绘图，完整代码参考: https://github.com/pyecharts/pyecharts-gallery/blob/master/Line/log_axis.py
