### ISSUE TITLE
是否可以考虑在用snapshot输出图片时给图表增加animation:false属性？

### ISSUE THREAD

**Issue by Marmota-bobak** [pyecharts/pyecharts#875]
**问题**
这样就不需要让phantomjs wait那个几秒钟了

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chenjiandongx** [comment]
snpashot 在 pyecharts 1.0.0 版本中已经成为一个插件，不干涉 pyecharts 的 render 业务逻辑
