### ISSUE TITLE
scatter交互输出只有Y轴

### ISSUE THREAD

**Issue by Wuweilongforapc** [pyecharts/pyecharts#876]
**问题**
应该返回x\y轴坐标，当前仅返回了y轴

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

![image](https://user-images.githubusercontent.com/22075652/50064956-e78afa80-01ee-11e9-8c97-c270be37fa60.png)

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！可以设置 formatter 解决这个问题
