### ISSUE TITLE
Suggestion: optional use of css-html-js-minify

### ISSUE THREAD

**Issue by ffarella** [pyecharts/pyecharts#878]
Hi! In order to reduce the render files as well as _repr_html, why not use css-html-js-minify:
Example:
````python
def _repr_html_(self):
        self.chart_id = uuid.uuid4().hex
        html = super()._repr_html_()
        try:
            from css_html_js_minify import html_minify
            html = html_minify(html, comments=False)
        except ImportError:
            pass
        return html
````

**Comment by chfw** [comment]
Can use. The benefit would be on HTML side. Most of the js files are minimized. the majority of the size are actually from js files themselves.

**Comment by ffarella** [comment]
This minifies also JS!!! (i.e chart options). I reduced my export size by about 5 (huge numpy array for time-series) by using this.
Converting pandas Series and numpy arrays to list adds a lot of whitespace...

**Comment by ffarella** [comment]
Totally unrelated.
I wanted to define options as pure JSstring, without using pyecharts_javascripthon.
I came up with this monkey-patch.


```python
class DefaultJsonEncoder(json.JSONEncoder):

    def default(self, obj):

        if isinstance(obj, types.FunctionType):
            return FUNCTION_TRANSLATOR.feed(obj)

        if isinstance(obj, (datetime.datetime, datetime.date)):
            return obj.isoformat()

        _tpl = getattr(obj, "_tpl", None)
        if _tpl is not None:
            name = f"custom_func_{id(obj)}"
            FUNCTION_TRANSLATOR._func_store.update({name: obj})
            ref_str = FUNCTION_TRANSLATOR.reference_str_format.format(
                name=name)
            FUNCTION_TRANSLATOR._replace_items.append(
                (''.join(['"', ref_str, '"']), obj.render()))
            return ref_str

        if hasattr(obj, 'config'):
            return obj.config

        # Pandas and Numpy lists
        try:
            return obj.astype(float).tolist()

        except Exception:
            try:
                return obj.astype(str).tolist()

            except Exception:
                return super(DefaultJsonEncoder, self).default(obj)


def translate():
    fs = FunctionSnippet()
    for name, func in FUNCTION_TRANSLATOR._func_store.items():
        if name in FUNCTION_TRANSLATOR._shared_function_snippet:
            snippet = FUNCTION_TRANSLATOR._shared_function_snippet.get_snippet(
                name)
        else:
            is_custom = hasattr(func, "_tpl")
            if not is_custom:
                snippet = TranslatorCompatAPI.translate_function(func)
            else:
                snippet = func._results
            FUNCTION_TRANSLATOR._shared_function_snippet.add(snippet, name)
        fs.add(snippet, name)
    return fs


FUNCTION_TRANSLATOR.translate = translate
TRANSLATOR.json_encoder = DefaultJsonEncoder
```

I have modified my Base chart to have this:
```python
    def add_code(self, code, **context):
        context["chart"] = self
        return JSFuncCode(code, **context)
```

with JSFuncCode defined as this:

```python
class JSFuncCode:
    def __init__(self, code, **context):
        self._tpl = Template(self._func_code)
        self._results = None
        self.context = context
    def render(self):
        self._results = self._tpl.render(**self.context)
        return self._results
```

I can use it like this:
```python
axisLabel_formatter = chart.add_code(
"""
function axisLabel_formatter(value, index) {
    {% if chart.js_date_format %}
    var fmt = "{{ chart.js_date_format }}";
    {% else %}
    var fmt = "yyyy-MM-dd\nhh:mm:ss";
    {% endif %}
    return echarts.format.formatTime(fmt, value);
}
"""
)
```

Do you think this would be worth adding this feature? It's helping me a fair bit and I can bypass the JS compiler. Because it is hard to generate a python function from code. Before, I used this horrible hack:


```python
def function_from_code(template, **kwargs):
    temp_dir, func_name = os.path.split(
        tempfile.NamedTemporaryFile(delete=True).name)
    func_name = "function_from_code_" + func_name
    temp_name = os.path.join(temp_dir, func_name + ".py")
    if not isinstance(template, str):
        raise RuntimeError("No template provided")
    template = template.strip()
    assert template.startswith("def {{ __func_name__ }}(")

    tpl = Template(template.strip())
    source_code = tpl.render(__func_name__=func_name, **kwargs)
    func = None
    try:
        with open(temp_name, "w") as fout:
            fout.write(source_code)

        while not os.path.isfile(temp_name):
            time.sleep(0.1)
        spec = importlib.util.spec_from_file_location(func_name, temp_name)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        func = getattr(mod, func_name)
        assert hasattr(func, "__call__")
        func.__name__ = func_name
    except Exception as e:
        raise e
    finally:
        pass
    return func
```

**Comment by chfw** [comment]
Related to your issue, you have made a point there. echarts options could be huge too. 

Regarding to JString, I had a similar call in my mind. ATM, it does not allow user to use pure javascript functions, hence it blocks user from a simple use case: copy-n-pate code from official echarts examples into python code. So your inspiration has its value.  

In order to have your contribution working with existing javascripthon, `JSFuncCode` can be rendered by DefaultJsonEncoder in whichever way it fits well. 

@chenjiandongx @kinegratii , what do you think?

**Comment by ffarella** [comment]
Note that the minify plugin seems to run into some problems with comments in the code. So unittesting is required! But i am not having any problem if i disable the option to remove comments! ;)

**Comment by ffarella** [comment]
If you are interested, I also hacked a way to load user-defined themes (simple new jinja2 template function) so that you don't have to go through the procedure defined in https://github.com/pyecharts/pyecharts/blob/master/docs/en-us/themes.md#use-your-own-built-theme.
It s fairly easy to do it, but would be a nice little addon.

**Comment by kinegratii** [comment]
Yeah,it is a good feature to development.

1. Function => Javascript Statements

Then we can make it more general to js snippet,not not only function.It is just a text handler, any lexer and grammar should be confirm by user.

```python
class JsCode:
    def __init__(self, tpl):
        self.tpl = tpl

# This is a simple core usage.

options = {
    'v1': 'hello',
    'v2':JsCode('Math.random()')
}

result = DefaultJsonEncoder().encode(options)
expect_result = '{ "v1": 'hello', "v2": Math.random()}'
```
2 Add in encoder-level

> JSFuncCode can be rendered by DefaultJsonEncoder in whichever way it fits well.

It is a good principle, related logic can be transparent to the translator.

**Comment by ffarella** [comment]
No need for minification!
Just change the dump parameter to:
`json.dumps(options, indent=None, cls=TRANSLATOR.json_encoder, separators=(',', ':'))`
