### ISSUE TITLE
双轴折线图图例颜色及标记设置（与#609相似但不同的问题）

### ISSUE THREAD

**Issue by weidongysu** [pyecharts/pyecharts#881]

**Comment by weidongysu** [comment]
(https://user-images.githubusercontent.com/41318890/50474228-0d887a00-09fb-11e9-9029-618928f51ba8.jpg)
如图所示，绿色标记的地方并不能自主的设定颜色，
代码如下
#第一条线：设置颜色为#2a6ce8，一切正常
`line = Line('前六结算期申报变化趋势', title_pos='center', height="230px", width='500px', title_text_size="16",background_color='#fff')
    line.add("申报金额", attr, v1,label_color=['#2a6ce8'],is_smooth=True,is_legend_show=True,legend_pos="center", legend_top="10%",
             label_pos='top', line_width="3", is_yaxis_show=True,yaxis_force_interval=10000
             , xaxis_type='category', yaxis_label_textcolor='#999999',xaxis_interval=0, xaxis_rotate='45', is_xaxis_show=True,xaxis_line_color='#999999',yaxis_line_color='#fff',
             xaxis_label_textsize='12', is_xaxislabel_align=False,is_toolbox_show=False)`
##第二条线：设置颜色为#6cbcff，而标记点显示颜色是系统自带的默认颜色，不是指定颜色
`line1.add("申报量", attr, v1, line_color="#6cbcff",label_color=['#6cbcff'],is_smooth=True, is_legend_show=True, legend_pos="center",
             legend_top="10%",label_pos='top', line_width="3", is_yaxis_show=True,yaxis_force_interval=20,is_splitline_show=False
             , xaxis_type='category', yaxis_label_textcolor='#999999',xaxis_interval=0, xaxis_rotate='45', is_xaxis_show=True,xaxis_line_color='#999999',yaxis_line_color='#fff',
             xaxis_label_textsize='12', yaxis_label_textsize='12',is_xaxislabel_align=False, is_toolbox_show=False)
    overlap = Overlap(height="230px", width='500px')
    overlap.add(line)
    overlap.add(line1, is_add_yaxis=True, yaxis_index=1)`

**Comment by ciciandjojo** [comment]
> (https://user-images.githubusercontent.com/41318890/50474228-0d887a00-09fb-11e9-9029-618928f51ba8.jpg)
> 如图所示，绿色标记的地方并不能自主的设定颜色，
> 代码如下
> #第一条线：设置颜色为#2a6ce8，一切正常
> `line = Line('前六结算期申报变化趋势', title_pos='center', height="230px", width='500px', title_text_size="16",background_color='#fff') line.add("申报金额", attr, v1,label_color=['#2a6ce8'],is_smooth=True,is_legend_show=True,legend_pos="center", legend_top="10%", label_pos='top', line_width="3", is_yaxis_show=True,yaxis_force_interval=10000 , xaxis_type='category', yaxis_label_textcolor='#999999',xaxis_interval=0, xaxis_rotate='45', is_xaxis_show=True,xaxis_line_color='#999999',yaxis_line_color='#fff', xaxis_label_textsize='12', is_xaxislabel_align=False,is_toolbox_show=False)`
> ##第二条线：设置颜色为#6cbcff，而标记点显示颜色是系统自带的默认颜色，不是指定颜色
> `line1.add("申报量", attr, v1, line_color="#6cbcff",label_color=['#6cbcff'],is_smooth=True, is_legend_show=True, legend_pos="center", legend_top="10%",label_pos='top', line_width="3", is_yaxis_show=True,yaxis_force_interval=20,is_splitline_show=False , xaxis_type='category', yaxis_label_textcolor='#999999',xaxis_interval=0, xaxis_rotate='45', is_xaxis_show=True,xaxis_line_color='#999999',yaxis_line_color='#fff', xaxis_label_textsize='12', yaxis_label_textsize='12',is_xaxislabel_align=False, is_toolbox_show=False) overlap = Overlap(height="230px", width='500px') overlap.add(line) overlap.add(line1, is_add_yaxis=True, yaxis_index=1)`

我也是遇到同样的问题，不过我是在使用直方图的时候不能改颜色，貌似是由于第一add()内部加了一些东西而导致把后面的样式刷走，你现在有方法解决吗

**Comment by weidongysu** [comment]
我现在也没有好的解决方法，现在将pyecharts的默认颜色改成了第二个折线图的点需要的颜色

**Comment by chenjiandongx** [comment]
#1033 请使用 1.0.0 版本啦，如若不能解决该问题 请再另开 issue

**Comment by szdblaa** [comment]
> 我现在也没有好的解决方法，现在将pyecharts的默认颜色改成了第二个折线图的点需要的颜色

请问怎么改pyecharts的默认颜色？或者调整pyecharts的默认颜色列表
