### ISSUE TITLE
关于雷达图的阴影部分

### ISSUE THREAD

**Issue by godchenghao** [pyecharts/pyecharts#882]
**问题**
雷达图上的阴影无法去除，以前的版本好像没这个阴影？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

以前：
![222](https://user-images.githubusercontent.com/45276259/50531657-e50e9600-0b48-11e9-8314-58e3927e05d3.png)
现在：
![111](https://user-images.githubusercontent.com/45276259/50531659-eb047700-0b48-11e9-91ab-ec0688dba22c.png)

**Comment by sunhailin-Leo** [comment]
@godchenghao 可以用新版的试试了～
