### ISSUE TITLE
如何给热力图配置自定义颜色？能否给出一个例子

### ISSUE THREAD

**Issue by godsonlau** [pyecharts/pyecharts#883]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
* 可以尝试新版本的代码。如果依旧出现该问题，请重新提 issue 并附上你的代码，thx～
* 最好可以去 echarts 找一个例子，并回复～这样有利于我们对例子的补充和问题的解决～
