### ISSUE TITLE
snapshot生成图片横轴文字过长消失

### ISSUE THREAD

**Issue by mzsj** [pyecharts/pyecharts#884]
**问题**
在jupyter notebook 里面显示是正常的，但输出为gif图片就只能显示一部分文字

**运行环境（系统环境及 pyecharts 版本）**
win10 教育版 1709
Name: pyecharts
Version: 0.5.11

**代码及截图**
attr=["加强学习风气的引导","提供更多的选修课","开展丰富的第二课堂活动","提供更多的国内外交流学习的机会","开放更多的自习教室和实验室","改善校园网络、教室设备与服务","提供更多的图书资料"]  
v1=[1077,453,641,659,825,759,340]  
grid = Grid()
bar=Bar("您希望母校在学习环境方面，继续提高改进的是")  
bar.add("人数",attr,v1,is_stack=True,xaxis_rotate= 60,label_text_size=12,xaxis_margin=10,is_legend_show=False)  
bar#bar.render()  
grid.add(bar, grid_bottom="45%")
#bar.render(path="C:/Users/MZ/Desktop/my_first_chart.gif")

![default](https://user-images.githubusercontent.com/26783514/50589667-8471b700-0ec2-11e9-9acf-0147ed1abae8.gif)

保存后的图片如下
![my_first_chart](https://user-images.githubusercontent.com/26783514/50589705-a4a17600-0ec2-11e9-8681-0b69d944c95d.gif)

**Comment by chfw** [comment]
bar#bar.render()
grid.add(bar, grid_bottom="45%")
#bar.render(path="C:/Users/MZ/Desktop/my_first_chart.gif")
grid.render(path="C:/Users/MZ/Desktop/my_first_chart.gif")  # <---
