### ISSUE TITLE
HaetMap的y_axis类目轴显示问题

### ISSUE THREAD

**Issue by aliwanan** [pyecharts/pyecharts#885]
**问题**

HaetMap的y_axis似乎无法显示类目轴，输入类目数据，结果显示的是数值轴.

**运行环境（系统环境及 pyecharts 版本）**
Linux

**代码及截图**
下图是用官网的例子画出的
![image](https://user-images.githubusercontent.com/44763871/50672339-6dda7580-1012-11e9-9f9e-2eff133316ac.png)

![image](https://user-images.githubusercontent.com/44763871/50672242-dd9c3080-1011-11e9-8ce8-1b6426b8e8f1.png)

**Comment by lim-0** [comment]
确实，碰到同样的问题，求解

**Comment by chenjiandongx** [comment]
#1033 新版本已解决该问题
