### ISSUE TITLE
 _is_markline 在设置mark_line_raw的时候根本没法开启

### ISSUE THREAD

**Issue by yutiansut** [pyecharts/pyecharts#886]
我看了下issue  mark_line_raw 和mark_point_raw 是在同一个issue中被提出来的
https://github.com/pyecharts/pyecharts/issues/731 参见 

但是代码中对mark_point_raw的支持看到了 但是写法让人很费解:

1. 参见: echarts的官方demo可以看出, mark_point和mark_line是可以同时存在的
[demo](http://www.echartsjs.com/examples/editor.html?c=candlestick-sh)

但是代码中似乎不允许两个raw同时存在 十分费解

参见代码[code](https://github.com/pyecharts/pyecharts/blob/effcc387217ae80f3b3fccb24dedad7dd392e68b/pyecharts/echarts/option.py#L576)

```python
    if _is_markline:
        if mark_line_raw:
            return {"data": mark_line_raw}
    else:
        if mark_point_raw:
            return {"data": mark_point_raw}

```

这里似乎是写死了 两者不能共存  非常费解这种写法的存在原因

2. 基于刚才的代码, 我们发现如果要想启用mark_line_raw 必须得让_is_markline = True

而找到设置这个true的地方 [code2](https://github.com/pyecharts/pyecharts/blob/effcc387217ae80f3b3fccb24dedad7dd392e68b/pyecharts/echarts/option.py#L687)

```python
@collectfuncs
def mark_line(mark_line=None, **kwargs):
    """ 标记线配置项
    :param mark_line:
        只支持默认的 'min', 'max', 'average'
    :param kwargs:
    """
    return _mark(mark_line, _is_markline=True, **kwargs)


```
你会发现这里似乎根本不允许你用mark_line_raw  也就是说 这个mark_line_raw似乎永远都无法开启, 以为你他只支持默认的mark_line  就很神奇

建议  加个mark_line= 'raw'  选择自己的

以上是两点困惑 @jeasoft @crispgm @sd8089730 @chfw @muxuezi

**Comment by yutiansut** [comment]
看了下test代码 只有关于mark_point_raw的测试部分, 并未发现mark_line_raw的部分

[测试部分](https://github.com/pyecharts/pyecharts/blob/effcc387217ae80f3b3fccb24dedad7dd392e68b/test/test_line.py#L141)

**Comment by yutiansut** [comment]
@chenjiandongx

**Comment by yutiansut** [comment]
@chfw

**Comment by chfw** [comment]
@yutiansut PR?

**Comment by yutiansut** [comment]
@chfw 我先用nodejs去实现了 晚点来pr..

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！新版本支持丰富的 Markline 自定义格式
