### ISSUE TITLE
同名回调函数再次导入无效

### ISSUE THREAD

**Issue by Vodka-Bu** [pyecharts/pyecharts#887]
**问题**
在学习过程中发现用如果在已经传入过的回调函数下修改该回调函数的功能，重新导入是没有效果的，猜测是否是内部在第一次导入的时候生成了转换工具，第二次导入时因为同名没有替换转换工具导致的

**运行环境（系统环境及 pyecharts 版本）**
mac os Mojave 10.14.2 
Python 3.6.7
pyecharts 0.5.11
jupyter notebook

**代码及截图**
第一次导入
```python
from pyecharts import Bar

title = '图表示例'
subtitle = '这是副标题'
series_name = '服装'
attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
data = [5, 20, 36, 10, 75, 90]

def label_formatter(params):
    return params.value + '件'

bar = Bar(title = title, subtitle = subtitle)

bar.add(series_name, x_axis = attr, y_axis = data, 
       is_label_show = True, label_formatter = label_formatter)
```
结果：  
![image](https://user-images.githubusercontent.com/17917262/50943265-b2f52080-14c6-11e9-9854-c66d2dac5a78.png)

第二次在同名回调函数下修改，无效

```python
def label_formatter(params):
    if params.value > 30:
        return params.value + '(高)'
    else:
        return params.value + '(低)'

bar = Bar(title = title, subtitle = subtitle)

bar.add(series_name, x_axis = attr, y_axis = data, 
       is_label_show = True, label_formatter = label_formatter)
```

结果：  
![image](https://user-images.githubusercontent.com/17917262/50943250-a7095e80-14c6-11e9-9568-5a9c86382b4b.png)

第三次修改回调函数名，重新传入有效

```python
def label_format(params):
    if params.value > 30:
        return params.value + '(高)'
    else:
        return params.value + '(低)'

bar = Bar(title = title, subtitle = subtitle)

bar.add(series_name, x_axis = attr, y_axis = data, 
       is_label_show = True, label_formatter = label_format)
```
结果：  
![image](https://user-images.githubusercontent.com/17917262/50943323-ea63cd00-14c6-11e9-8598-a65570b9ea0b.png)

**Comment by chfw** [comment]
就不能取一个新名字吗？

当然，在翻译的时候，确实没有考虑过同名函数的处理。

**Comment by Vodka-Bu** [comment]
可以取啊~只是觉得如果不知道这个问题的话，在调试的时候会感到困扰以为是不是自己的回调函数写错了什么的

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！新版本支持直接传入 JS 代码段啦
