### ISSUE TITLE
同一个值里 显示多个attr

### ISSUE THREAD

**Issue by Clyde-la** [pyecharts/pyecharts#888]
**问题**

例如bar图表 多次add后 输出结果的attr是用的最后一个 希望能改成每组值用不同的attr显示
例如下图 希望 商家A能显示袜子1 商家B能显示袜子2

**运行环境（系统环境及 pyecharts 版本）**

python3.6.0

**代码及截图**
`
from pyecharts import Bar

attr1 = ["衬衫1", "羊毛衫1", "雪纺衫1", "裤子1", "高跟鞋1", "袜子1"]
attr2 = ["衬衫2", "羊毛衫2", "雪纺衫2", "裤子2", "高跟鞋2", "袜子2"]
v1 = [5, 20, 36, 10, 75, 90]
v2 = [10, 25, 8, 60, 20, 80]

bar = Bar("柱状图数据堆叠示例")
bar.add("商家A", attr1, v1, is_label_show=True)
bar.add("商家B", attr2, v2, is_label_show=True)
bar.render()
`
![qq 20190111020207](https://user-images.githubusercontent.com/40606392/50987651-33f2fd00-1545-11e9-902f-0efaa2d70c6d.jpg)

**Comment by sunhailin-Leo** [comment]
@Clyde-la 只能用 x 轴的 axisLabel 的 formatter 做障眼法了。

**Comment by sunhailin-Leo** [comment]
最终 x 轴的每一项大概会变成 `衬衫1 <分隔符> 衬衫2`
