### ISSUE TITLE
how to default 

### ISSUE THREAD

**Issue by hongxiangping** [pyecharts/pyecharts#889]
**问题**
If my bar has several items in legend, so how can I only show the data of the item I want when it inits the bar.
I find how to set(use legend->selected) this in Echarts，But in Pyecharts ，I can't find.

**运行环境（系统环境及 pyecharts 版本）**
Windows 7
python 3.7.1 
Pyecharts 0.5.11

**代码及截图**

**Comment by chenjiandongx** [comment]
In pyecharts 1.0.0

![image](https://user-images.githubusercontent.com/19553554/57318326-a4dda680-712c-11e9-808d-a9833249de99.png)
