### ISSUE TITLE
 No module named pyecharts

### ISSUE THREAD

**Issue by wellmonwu** [pyecharts/pyecharts#893]
**问题**
在jupyter使用pyecharts提示
No module named pyecharts

**运行环境（系统环境及 pyecharts 版本）**
win7 x64, anaconda2, 32, python2.7

pyecharts  0.5.11
**代码及截图**

from pyecharts import Bar

**Comment by chfw** [comment]
1) Have you installed pyecharts?
2) Does it appear in `pip freeze`?

**Comment by wellmonwu** [comment]
已经pip install pyecharts
在pip list里面有

**Comment by chfw** [comment]
那么就是环境不一样！pip 与 jupyter 的python 环境不一样！

data scientist 经常遇到这个问题！！

**Comment by wellmonwu** [comment]
重装了anaconda可以了，用了x64, 5.3.1

**Comment by wellmonwu** [comment]
另外装一下pyecharts-snapshot
