### ISSUE TITLE
Scatter is_convert 无效

### ISSUE THREAD

**Issue by zobnec** [pyecharts/pyecharts#897]
**运行环境（系统环境及 pyecharts 版本）**

版本: pyecharts 0.5.7+ python2.7 

**代码及截图**

`data = [
        [17.3666, 0, 327.708],
        [13.3827, 1, 41.995],
        [9.9209, 2, 35.1],
        [8.1715, 3, 167.785],
        [6.376, 4, 11.5278]
    ]

    x_lst = [v[0] for v in data]
    y_lst = [v[1] for v in data]
    extra_data = [v[2] for v in data]

    sc = Scatter()
    sc.add(
        "scatter",
        x_lst,
        y_lst,
        extra_data=extra_data,
        is_convert=True,
        is_visualmap=True,
        visual_dimension=2,
        visual_orient="horizontal",
        visual_type="size",
        visual_range=[0.1, 400],
        visual_text_color="#000",
        # yaxis_formatter=label_formatter,
    )
    

    sc.render()`

is_convert 无效

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！新版本 Scatter 已提供 `is_convert` 方法
