### ISSUE TITLE
桑基图如何调整节点的顺序和颜色？

### ISSUE THREAD

**Issue by precision2intelligence** [pyecharts/pyecharts#899]
**问题**
最新的Echarts中可以按照Series.data的顺序显示节点，但是在pyecharts中节点的顺序还是不能按照nodes中的顺序一致。请问是什么原因？如何按照自定义的顺序显示节点呢？？
另外，如果想改变节点颜色，除了修改主题外，在哪里可以设置某个节点的颜色为特定值呢？

**运行环境（系统环境及 pyecharts 版本）**
Python3.6+windows
最新版本的pyecharts

**Comment by sunhailin-Leo** [comment]
@precision2intelligence 
* 顺序是跟 links 的顺序有关
* 颜色，可以通过 levels 参数进行修改(1.6.2 后 Sankey 支持 levels 参数配置每一个层的颜色和其他配置)

**Comment by imliuruiqi** [comment]
怎么感觉不是这样，顺序让人摸不透。
求细讲

**Comment by Nuturetree** [comment]
我也遇见了相同的问题，请问大佬解决了吗？
