### ISSUE TITLE
online 模式，使用 pyecharts 官方提供的 assets host，或者部署自己的 remote host。

### ISSUE THREAD

**Issue by chfw** [pyecharts/pyecharts#904]
#892 

插件机制重构

废除现有的插件机制，仅支持两种情况

online 模式，使用 pyecharts 官方提供的 assets host，或者部署自己的 remote host。
local 模式，使用自己本地开启的文件服务提供 assets host，会提供一键启动的脚本，方便部署。

**Comment by Xialichong** [comment]
想请问具体online模式使用官方的host该如何写啊。。。
没看到文档里提到这个

我想把我的jupyter 另存为html，该如何引用render的图?
