### ISSUE TITLE
请问桑基图sankey能否对结点分类显示(有图)？render sankey graph by classifying the same category nodes

### ISSUE THREAD

**Issue by DaToo-J** [pyecharts/pyecharts#910]
**问题：**
请问有没有什么方法：能够在渲染时，将桑基图中不同类的结点加以区分？就像下图这样
（其中，载入的数据集是能够体现出这些结点所属类别的）
Is there any way could render a sankey graph by classifying the same category nodes? just like pics show:
(in fact, the uploaded dataset has classified different nodes)

- 想要得到以下效果图：
(this pic is what I want)
![image](https://user-images.githubusercontent.com/40933166/52044751-d703c900-257d-11e9-94f1-cbfa0bc3b56e.png)

- 但是目前只能得到这样的效果图：
(but I have already get the sankey pic just like this which is not enough)
![image](https://user-images.githubusercontent.com/40933166/52044797-f569c480-257d-11e9-843f-61682dd767c6.png)

- 或者，有没有其他python依赖能够实现这样的功能？
(or, is there any other python libraries could help me to realize this function?)

**Comment by sunhailin-Leo** [comment]
@DaToo-J 
* 跟你 links 的数据顺序有关系
