### ISSUE TITLE
jupyter中如果是maptype=u'某个省份'就可以显示，而当maptype=u'china'时显示空白，但是能输出geo.render的html文件

### ISSUE THREAD

**Issue by zzz1994zzzz** [pyecharts/pyecharts#911]
jupyter中如果是maptype=u'某个省份'就可以显示，而当maptype=u'china'时显示空白，但是二者都能输出geo.render的html文件

**运行环境（系统环境及 pyecharts 版本）**
centos 7，使用jupyter notebook

**代码及截图**

<img width="1177" alt="2019-02-05 4 54 15" src="https://user-images.githubusercontent.com/37324183/52262202-ccbf4180-2966-11e9-82ab-b7671476f27c.png">
<img width="1163" alt="2019-02-05 4 53 56" src="https://user-images.githubusercontent.com/37324183/52262209-d5b01300-2966-11e9-9810-1ad858abf45d.png">

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！现在不用安装地图包啦
