### ISSUE TITLE
gauge 图在grid中不能调整位置

### ISSUE THREAD

**Issue by lyushy** [pyecharts/pyecharts#914]
**问题**
gauge 图在grid中不能调整位置

**运行环境（系统环境及 pyecharts 版本）**
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
(from javascripthon>=0.10; python_version > "3.4"->pyecharts-javascripthon==0.0.6->pyecharts) (1.1.0b2)

**代码及截图**
		firstLeterGauge =Gauge()
		firstLeterGauge.add("一通完成率", "完成率", firstLeterRatio,legend_pos = 800)
		finalLeterGauge =Gauge()
		finalLeterGauge.add("结案完成率", "完成率", finalLeterRatio,legend_pos = 800)
		grid2=Grid(width=1800,height=400)
		grid2.add(firstLeterGauge,grid_left='55%')
		grid2.add(finalLeterGauge,grid_right='55%')

**Comment by lofty77** [comment]
遇到同样的问题

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！Grid 现在只支持直角坐标系图形
