### ISSUE TITLE
数据视图英文标签

### ISSUE THREAD

**Issue by YanNIU2028** [pyecharts/pyecharts#915]
**问题**
你好，请问数据视图这个新窗口中，"数据视图"，"关闭"，"刷新"，这3个中文词在哪里可以重写？谢谢

**运行环境（系统环境及 pyecharts 版本）**
python 3.6
pyecharts 0.5.11

**代码及截图**

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！V1.0.0 版本开始默认为英文
