### ISSUE TITLE
怎么设置点击legend图例后再显示数据？

### ISSUE THREAD

**Issue by sjk7524068** [pyecharts/pyecharts#916]
**问题**
使用overlap同时在一张图里面添加了bar和line，每次打开两个图混在一起不是很美观，请问有什么办法

设置每次打开只显示bar或者只显示line，然后通过点击图例的方式显示更多的数据。

echarts上好像有select的配置项，可以设置默认显示哪些数据，

但是在pyecharts上找不到该配置选项

**运行环境（系统环境及 pyecharts 版本）**
python 3.7
pyecharts 0.5.11

**代码及截图**

**Comment by chenjiandongx** [comment]
下个版本将会支持，预计于四月发布

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！已经提供 `is_selected` 参数
