### ISSUE TITLE
kline 辅图，鼠标悬浮时，无法正确展示数据

### ISSUE THREAD

**Issue by wellmonwu** [pyecharts/pyecharts#918]
**问题**
kline 辅图，鼠标悬浮时，无法正确展示数据
![image](https://user-images.githubusercontent.com/11804664/52993023-a82a9580-344d-11e9-854a-b882cd6ea60c.png)
上图红框应该显示diff的数据，但是显示了开盘价，收盘价等数据

**运行环境（系统环境及 pyecharts 版本）**
notebook, py3, pyecharts 0.5.11

**代码及截图**
#pyecharts文档请见http://pyecharts.org
from pyecharts import Kline, online,Overlap,Scatter,Style,Line,Grid,Bar
import talib
import pyecharts.echarts.events as events
from pyecharts_javascripthon.dom import alert

class Kshow:
    def __init__(self,stock_name,jsPath='https://pyecharts.github.io/assets/'):
        #使用最新的echarts js文件
        online(jsPath)
        #K线
        self.kline=Kline(stock_name)
        #macd line，即dif、dea
        self.macd_line=Line('')
        self.macd_bar=Bar('')
    
    def chart_init(self,data_df,show_BI=True,show_Line=True,show_Center=True):
        #获取K线数据
        def get_K_data(df):
            kdata=df.loc[:,['open','close','low','high']].to_dict('split')['data']
            xaxis=list(df.index.tolist())
            return xaxis,kdata
        #获取MACD数据
        def get_macd_data(df):
            dif=[l[1] for l in df.dif.iteritems()]
            dea=[l[1] for l in df.dea.iteritems()]
            macd_z=[l for l in df[df.macd>=0].macd.iteritems()]
            macd_f=[l for l in df[df.macd<0].macd.iteritems()]
            return dif,dea,macd_z,macd_f
        
        kx,ky=get_K_data(data_df)
        #添加K线，is_datazoom_show显示时间轴，datazoom_range时间轴范围
        self.kline.add('K',kx,ky,
                       is_datazoom_show=True,datazoom_range=[80,100],
                       mark_point=["max"],                        
                       mark_line_symbolsize=0,
                       datazoom_orient="vertical",
#                        mark_line_valuedim="close",
                      )
        #修改K线颜色
        self.kline._option['series'][0]['itemStyle']={'normal':{'color':'#ef232a', 'color0': '#14b143','borderColor': '#ef232a', 'borderColor0': '#14b143'}}
        
        
        def line_formatter(params):
            param = param[0];
            return [
                'Date: ' + param.name + '<hr size=1 style="margin: 3px 0">',
                'Open: ' + param.data[0] + '<br/>',
                'Close: ' + param.data[1] + '<br/>',
                'Lowest: ' + param.data[2] + '<br/>',
                'Highest: ' + param.data[3] + '<br/>'
            ].join('')
        
        def on_click():
            alert("点击事件触发")
        
        dif,dea,macd_z,macd_f=get_macd_data(data_df)
        self.macd_bar.add('macd_z',[t for t,v in macd_z],macd_z,is_datazoom_show=True)
        self.macd_bar.add('macd_f',[t for t,v in macd_f],macd_f,is_datazoom_show=True)
        self.macd_line.add('dif',kx,dif,is_datazoom_show=True, xaxis_type='category',line_width =1,
                           is_symbol_show=False,is_fill=False,)
        self.macd_line.add('dea',kx,dea,is_datazoom_show=True, xaxis_type='category',line_width =1,
                           is_symbol_show=False,is_fill=False,)
        
        self.macd_line.on(events.MOUSE_OVER,on_click)
        
        #这个应该是目前版本pyechart的bug，导致区域填充，删除后只显示线
        del chart.macd_line._option['series'][0]['areaStyle']
        del chart.macd_line._option['series'][1]['areaStyle']
    
    #主图
    def get_main_chart(self,height=600,width=1000):
        overlap = Overlap(height=height,width=height)
        overlap.add(self.kline)
        
        return overlap
    
    #辅图
    def get_macd_chart(self,height=200,width=1000):
        overlap = Overlap(height=height,width=height)
        overlap.add(self.macd_line)
        overlap.add(self.macd_bar)
        return overlap
    
    #获取图，并显示
    def show_chart(self,zoom_start=50,height=600,width=1000):
        grid = Grid(height=height,width =width)
        
        main_ov=self.get_main_chart(height-200,width)
        macd_ov=self.get_macd_chart(200,width)
        
        grid.add(main_ov,grid_top=0,grid_bottom=220)
        grid.add(macd_ov,grid_top=height-200)
        
        grid._option['dataZoom'][0]['xAxisIndex']=[0, 1]
        grid._option['dataZoom'][0]['start']=zoom_start
        grid._option['xAxis'][1]['show']=False
        grid._option['legend'][1]['show']=False
        grid._option['color']=['#145b7d','#e0861a','#ef232a','#14b143'] #DIF，DEA，MACD正，MACD负
        return grid

#股票代码
stock='000001.XSHG'

##juquant API
#名称
stock_name=get_security_info(stock).display_name
#获取dataframe
df=get_price(stock,end_date='2018-06-10',fields=['open','close','high','low'],frequency='1d',count=600)
##juquant API

#计算macd
df['dif'],df['dea'],df['macd']=talib.MACD(df.close.values, 
                                        fastperiod=12 , 
                                        slowperiod=26, 
                                        signalperiod=9 )
#macd最开始一段数据不准，移除
df=df.iloc[100:,:]
#初始化画图函数
chart=Kshow(stock[:6]+' '+stock_name)
#初始化数据
chart.chart_init(df)
#显示图表
chart.show_chart(height=600,width=1000)

**Comment by chenjiandongx** [comment]
#1033 请使用新版本 改问题已修复
