### ISSUE TITLE
为什么生成的网页文件那么大？

### ISSUE THREAD

**Issue by planzq** [pyecharts/pyecharts#919]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
用的都正常，就是问下，为什么生成的网页文件那么大？
我生成的大概都有0.7兆

**Comment by chfw** [comment]
大数据？

**Comment by planzq** [comment]
> 大数据？

不是，就是很简单的，pyecharts提供的例子产生的网页也是700多K，感觉太大了

**Comment by chfw** [comment]
无解。

**Comment by chenjiandongx** [comment]
@planzq 我来回答一下吧

### 引用本地文件
```python
from pyecharts import Bar, online

bar = Bar()
bar.add("", ["1"], [5])
bar.render("render_use_local_file.html")
```

得到的文件大小约为 **5kb**


### 远程引用
```python
from pyecharts import Bar, online

online()

bar = Bar()
bar.add("", ["1"], [5])
bar.render("render_use_remote_ref.html")
```

得到的文件大小约为 **706kb**

所以想要得到小文件 html 请使用远程引用

**Comment by planzq** [comment]
> @planzq 我来回答一下吧
> 
> ### 引用本地文件
> ```python
> from pyecharts import Bar, online
> 
> bar = Bar()
> bar.add("", ["1"], [5])
> bar.render("render_use_local_file.html")
> ```
> 
> 得到的文件大小约为 **706kb**
> 
> ### 远程引用
> ```python
> from pyecharts import Bar, online
> 
> online()
> 
> bar = Bar()
> bar.add("", ["1"], [5])
> bar.render("render_use_remote_ref.html")
> ```
> 
> 得到的文件大小约为 **5kb**
> 
> 所以想要得到小文件 html 请使用远程引用

谢谢 我试试
