### ISSUE TITLE
折线图不显示折线，只有最大值和平均值

### ISSUE THREAD

**Issue by kjxy** [pyecharts/pyecharts#923]
![image](https://user-images.githubusercontent.com/35479340/53160320-ac4be400-3602-11e9-9504-e2863f65af81.png)
如图，本来是日期+数据的，可是生成出来的图片，就没有折线。
代码：
`    def lines(name,code,datetime,price,paths,filename):

        line = Line(name + filename)

        line.add(code, datetime, price, mark_line=["max", "average"])

        filepath = paths + '%s' % code + '-' + '%s.png' % filename

        line.render(filepath)`
读取数据的文件是xls的

**Comment by chenjiandongx** [comment]
请确保 datetime, price 为 int,float,str, bool 等基本类型
