### ISSUE TITLE
能否只生成的有效的图片，而不是一整张完整的图

### ISSUE THREAD

**Issue by mayaren888** [pyecharts/pyecharts#924]
**问题**
能否只生成仪表盘的图，而不是一整张图？

**运行环境（系统环境及 pyecharts 版本）**

win10  pycharm  

**代码及截图**
![snapshot](https://user-images.githubusercontent.com/6006653/53218593-b23fd480-3697-11e9-9ff6-793406ce5247.png)

我只想要这个仪表盘的图，不想要其他的部分，这样既节省空间又简洁。能实现吗？

**Comment by chenjiandongx** [comment]
Sorry，该功能不属于通用特性，不准备实现。
