### ISSUE TITLE
导出的html文件过大

### ISSUE THREAD

**Issue by zenghk** [pyecharts/pyecharts#925]
**问题**
使用for循环向page中添加多个pie时，导出的html文件过大（接近900M），如何减小大小

**运行环境（系统环境及 pyecharts 版本）**
win10,0.5.11

**代码及截图**
pie.add(pie.add("",label,dict['V1_D1'],center=[1,1],radius=[2,0],**pie_style)
dict中的名称以及center是根据规律数值计算的，使用for循环（总共600次调用pie.add）用page.add_chart方法得到的html文件达到860M，但是用pie.add方法一个一个添加的大小约为2M，
![qq 20190222120117](https://user-images.githubusercontent.com/47877427/53219073-92a9ab80-3699-11e9-88aa-e8b9bdd3940b.png)

**Comment by lsaiah** [comment]
建议你生成gif图片，然后以with的方法打开写入到html里，这样会小很多
