### ISSUE TITLE
請問legend的icon要怎麼改成跟line color一樣呢？

### ISSUE THREAD

**Issue by KoChunKai** [pyecharts/pyecharts#927]
line = Line()
line.add("LINE", dates[:10], avg[:10],
		is_symbol_show=False, 
		is_label_emphasis=False, 
		legend_text_color="#00ff00",
		line_color="#00ff00",
		line_width=2)
![echarts](https://user-images.githubusercontent.com/3855917/53280355-1031f200-3754-11e9-89d3-6d316efb2afc.png)

**Comment by shshjun** [comment]
昨天看了一下这个，确实很不爽。
想自己改好，但失败了，不过思路是对的。因为我注意到js代码中，legend.data[去除null后] 和 color 应该是可以一一对应的。

就是在加入到legend清单里面时，如果有名字并且不是None,同时把对应的color加到chart["color"]里面去，最后把这个chart["color"]（如果不是空的话），就取代默认的颜色列表写到后台生成的js数据流里。
比如我只用拆线line, 对应线型的egend名字是"name", 颜色就是 "lineStyle"->"normal"->"color"
其它系列应该可以类似取到。

那么我遇到的问题就是最后写不进去，color:[...]总是系统在chart.py里面的默认列表。

**Comment by KoChunKai** [comment]
這個問題我自行解決了

**Comment by chenjiandongx** [comment]
示例代码
![image](https://user-images.githubusercontent.com/19553554/56251369-e9ee5a00-60e5-11e9-9713-9472c1e1f5e8.png)

效果
![image](https://user-images.githubusercontent.com/19553554/56251344-da6f1100-60e5-11e9-8197-a3d4ec88d8bd.png)

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/56251445-389bf400-60e6-11e9-8eea-fd3ecbe9f899.png)

新版本的默认就是一致的

**Comment by RonaldJEN** [comment]
> 這個問題我自行解決了

您如何解决的?
我也遇到相同问题

**Comment by KoChunKai** [comment]
> > 這個問題我自行解決了
> 
> 您如何解决的?
> 我也遇到相同问题

itemstyle_opts=ItemStyleOpts(color="#46A3FF")
試看看在add_yaxis 裡面使用這個參數

**Comment by RonaldJEN** [comment]
> > > 這個問題我自行解決了
> > 
> > 
> > 您如何解决的?
> > 我也遇到相同问题
> 
> itemstyle_opts=ItemStyleOpts(color="#46A3FF")
> 試看看在add_yaxis 裡面使用這個參數

好的,谢谢您
