### ISSUE TITLE
api文档描述错误，实际情况是echarts_js_content首尾含有script标签

### ISSUE THREAD

**Issue by wstone0011** [pyecharts/pyecharts#928]
**问题**
api文档描述错误，实际情况是echarts_js_content首尾含有script标签，而echarts_js_content_wrap首尾不包含script标签。
http://pyecharts.org/#/zh-cn/api?id=%E6%A8%A1%E6%9D%BF%E5%87%BD%E6%95%B0

**运行环境（系统环境及 pyecharts 版本）**
win10
python2.7
pyecharts 0.5.11

**代码及截图**
{{ echarts_js_content(bar) }}

{{ echarts_js_content_wrap(bar) }}

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！建议使用 1.0.0 版本
