### ISSUE TITLE
Grid 上Line下Line, title会重叠

### ISSUE THREAD

**Issue by xxx975** [pyecharts/pyecharts#929]
**问题**
Grid联合2个Line, legend和title会重叠在一起

**运行环境（系统环境及 pyecharts 版本）**
python 3.61
pyecharts 0.5.5

**代码及截图**
from pyecharts import Line, Grid, __version__

line1 = Line("折线图示例a", title_top="50%")
attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
line1.add(
    "商家A",
    attr,
    [11, 11, 15, 13, 12, 13],
    mark_point=["max", "min"],
    mark_line=["average"],
    is_legend_show=False
)

line2 = Line("折线图示例b", title_top="50%")

line2.add(
    "商家b",
    attr,
    [11, 11, 15, 13, 12, 13],
    mark_point=["max", "min"],
    mark_line=["average"],
    is_legend_show=False
)

grid = Grid()
grid.add(line1, grid_bottom="60%")
grid.add(line2, grid_top="60%")
grid.render()

![lily_2019 02 23 17 23 45](https://user-images.githubusercontent.com/19317570/53284451-c830c080-378f-11e9-8b0d-0d5253cdf839.png)

**Comment by hulining** [comment]
删掉line1初始化时 title_top="50%" 参数即可

**Comment by qiyj001** [comment]
> 删掉line1初始化时 title_top="50%" 参数即可

我有问题想请教，grid  一排显示三张图片  布局如何设置呢？
