### ISSUE TITLE
建议：使用 dataset 组件

### ISSUE THREAD

**Issue by yihengli** [pyecharts/pyecharts#931]
**问题**

目前 pyecharts (0.5.11) 仍然是用注入 series 的方法为图标加入数据。从 Echarts 4.0 开始，官方添加了 dataset 组件可以更便捷的管理数据并且可以多个 components 共享同一份数据。或许重构后的新版(https://github.com/pyecharts/pyecharts/issues/892) 能用上 echarts 的新架构。

Ref: https://www.echartsjs.com/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE

**Comment by lleeoov** [comment]
支持这个功能

**Comment by sunhailin-Leo** [comment]
@yihengli @lleeoov 
* 这个功能将在 1.7.1 中实现
