### ISSUE TITLE
grid不能并行显示三张图片吗？布局怎么调呢

### ISSUE THREAD

**Issue by qiyj001** [pyecharts/pyecharts#933]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@qiyj001 
* 实力不允许 😆  https://www.echartsjs.com/option.html#grid
![image](https://user-images.githubusercontent.com/17564655/57219712-8b086a80-702b-11e9-9f3d-803b61c8318e.png)
