### ISSUE TITLE
关于强制设置坐标轴不均匀刻度的建议

### ISSUE THREAD

**Issue by rainyl** [pyecharts/pyecharts#935]
**问题**
1. 目前强制设置坐标轴刻度间隔只能是均匀间隔，但是有些场景要用不均匀的坐标轴刻度
比如水文频率曲线这样的 [这个是图片链接](http://www.cnhup.com/wp-content/uploads/2010/10/optFitP3-ScreenShot-V2.0-1.png)

2. 折线图下的网格显示
如上图，某些情况希望折线图中既显示x轴网格也希望显示y轴网格，但目前只能显示y轴网格。。

**运行环境（系统环境及 pyecharts 版本）**

manjaro-linux18.02， pycharm2018.3.5，pyecharts v0.5.11

**Comment by bohaiwa** [comment]
请问 这个问题有解决吗？怎么解决的？

**Comment by sunhailin-Leo** [comment]
@rainyl @bohaiwa https://segmentfault.com/a/1190000018437019

**Comment by sunhailin-Leo** [comment]
博客大致内容：给 x 轴或者 y 轴的 axisLabel 自定义回调的 js 函数，然后在 Tooltip 中实现相对应的匹配规则。
