### ISSUE TITLE
生成图片的过程中会在/tmp/ 目录下生成html文件，但是在图片生成后不会把html文件回收

### ISSUE THREAD

**Issue by BlueCatTAT** [pyecharts/pyecharts#937]
**问题**
生成图片的过程中会在/tmp/ 目录下生成html文件，但是在图片生成后不会把html文件回收，很快就把/tmp 打满了

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chenjiandongx** [comment]
下个版本将会修复，预计于四月发布

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！
