### ISSUE TITLE
在Jupyter Notebook中保存图片到本地失败

### ISSUE THREAD

**Issue by CapAllen** [pyecharts/pyecharts#938]
**问题**
已安装Node.js和`phantomjs-prebuilt`还有`pyecharts-snapshot`，但保存图片时依然报错，求助！感谢回答！

**运行环境（系统环境及 pyecharts 版本）**
Windows7  
pyecharts 版本:最新的

**代码及截图**
![图片](https://user-images.githubusercontent.com/35265537/54345091-4b518200-467d-11e9-9baf-ca8aeaabbdcb.png)

**Comment by CapAllen** [comment]
![图片](https://user-images.githubusercontent.com/35265537/54345172-7b008a00-467d-11e9-86e2-c46ed7171bfd.png)

**Comment by chfw** [comment]
No phantomjs found in your Path. :'(

**Comment by CapAllen** [comment]
> 
> 
> No phantomjs found in your Path. :'(

I've added it to the system environment ....

**Comment by chfw** [comment]
IMO no magic in here. Phantomjs is not seen by jupyter, use '%env' to check.

**Comment by CapAllen** [comment]
> 
> 
> IMO no magic in here. Phantomjs is not seen by jupyter, use '%env' to check.

I reboot my computer, and this issue has been solved. awkward..... thx for your reply.

**Comment by chfw** [comment]
Next time I will use ITCrowd's catch phrase: "have you switched your computer off and on?"

**Comment by CapAllen** [comment]
> Next time I will use ITCrowd's catch phrase: "have you switched your computer off and on?"

lol , sorry about this stupid ask
