### ISSUE TITLE
运行案例没有图片也没有空白

### ISSUE THREAD

**Issue by Zhanchenhaha** [pyecharts/pyecharts#939]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

![image](https://user-images.githubusercontent.com/22406470/54346058-59080700-467f-11e9-84d0-6900aa34b796.png)

**Comment by Zhanchenhaha** [comment]
![image](https://user-images.githubusercontent.com/22406470/54346828-b6e91e80-4680-11e9-9537-a9b6ec2413c7.png)
可以生成柱状图了，但没有饼图

**Comment by Zhanchenhaha** [comment]
本人小白，垃圾问题，打扰大家了。

**Comment by chfw** [comment]
你有一年没有看文档了。
