### ISSUE TITLE
GEo问题： No coordinate is specified for 福建省

### ISSUE THREAD

**Issue by Xialichong** [pyecharts/pyecharts#940]
前提准备： unicode + package(maps)
我确认已经安装好所有的地图包，包括省，市的。

运行环境（系统环境及 pyecharts 版本）
Linux + python 3.6.3+ pyecharts (latest versio）

但是一直报错，没有任何省的信息，请问如何解决？
![image](https://user-images.githubusercontent.com/27034820/54405983-493a0280-4713-11e9-845b-e50cad965685.png)

**Comment by gzfrogman** [comment]
去掉“省”字

**Comment by Xialichong** [comment]
ORZ...好哦，我还每个都重新定义坐标了 [捂脸]

感谢感谢

gzfrogman <notifications@github.com> 于2019年3月27日周三 下午11:17写道：
