### ISSUE TITLE
can I change the color of gauge

### ISSUE THREAD

**Issue by sunshinesun555** [pyecharts/pyecharts#941]
**问题**

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@sunshinesun555 
* 新版本已解决这个问题，静候新版本的发布~
* 着急的话可以 clone dev 的代码安装体验 😄 
* PR https://github.com/pyecharts/pyecharts/pull/1036
