### ISSUE TITLE
地图作为React的组建使用

### ISSUE THREAD

**Issue by GolemHerry** [pyecharts/pyecharts#942]
**问题**

如何用python中带有交互方式生成的html文件用于React项目的开发中？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by chfw** [comment]
是个好问题。暂时还没有尝试，可以试试。

**Comment by chfw** [comment]
我想了一下，建议你去看看 https://github.com/apache/incubator-echarts#react-component

用 pyecharts 支持 react 有点强求。或者你可以自己提供 react 组件， pyecharts 提供 options。

**Comment by GolemHerry** [comment]
参考了https://github.com/liekkas/re-echarts 
已经可以在自己的项目里用echarts
