### ISSUE TITLE
pyechart is_convert问题

### ISSUE THREAD

**Issue by zhouweyi** [pyecharts/pyecharts#944]
**问题**
官方显示
![image](https://user-images.githubusercontent.com/48702540/54577669-a1d10e80-4a37-11e9-8ec7-758a4d0f238e.png)

![image](https://user-images.githubusercontent.com/48702540/54577678-b2818480-4a37-11e9-9f1d-f07fac8b3ffc.png)

**运行环境（系统环境及 pyecharts 版本）**
最新版本

**代码及截图**

pip install jupyter-echarts-pypkg==0.1.1 不能解决问题
跪求解决办法，最好详细点，非常感谢

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！该问题再 1.0.0 版本中已修复
