### ISSUE TITLE
grid中添加geo,line,bar报错

### ISSUE THREAD

**Issue by FankLi** [pyecharts/pyecharts#945]
@chenjiandongx 

**self._option.get("xAxis").append(_x)
AttributeError: 'NoneType' object has no attribute 'append'**

**具体代码：
from pyecharts import configure
    from pyecharts import Grid

    configure(global_theme='shine')
    grid = Grid(height=700, width=1440)
    grid.add(geo_line(), grid_right="40%",
             grid_top="100%",
             grid_bottom='40%',
             grid_width='30%')
    grid.add(bar(), grid_width=200, grid_height=200, grid_top=grid_base_pos['grid_top'],
             grid_left=str(int(grid_base_pos['grid_left'].split('%')[0]) + 20) + '%')

    grid.add(pie(), grid_width=200, grid_height=200, grid_top=grid_base_pos['grid_top'],
             grid_left=str(int(grid_base_pos['grid_left'].split('%')[0]) - 10) + '%')
**

这样也会报这个错：
**from pyecharts import configure
    from pyecharts import Grid

    configure(global_theme='shine')
    grid = Grid(height=700, width=1440)
 grid.add(pie(), grid_width=200, grid_height=200, grid_top=grid_base_pos['grid_top'],
             grid_left=str(int(grid_base_pos['grid_left'].split('%')[0]) - 10) + '%')
    grid.add(bar(), grid_width=200, grid_height=200, grid_top=grid_base_pos['grid_top'],
             grid_left=str(int(grid_base_pos['grid_left'].split('%')[0]) + 20) + '%')

   **

##是有什么顺序要求吗？
我想做一个geo上面，放一些透明的chart，以得到大屏可视化效果

谢谢回复～

**Comment by chenjiandongx** [comment]
Grid 中将只支持直角坐标系类图表
