### ISSUE TITLE
grid中添加timeline报错

### ISSUE THREAD

**Issue by xudingjun3131** [pyecharts/pyecharts#948]
因为Timeline中series和options是空的，会导致grid添加报错。请问如何解决？

**Comment by chenjiandongx** [comment]
Grid 中将不再支持 Timeline

**Comment by foolcage** [comment]
所以Timeline和其他图表怎么放在一起?比如一个line,一个timeline里面的饼图,我需要拖动时间看饼图,line保持不变.
