### ISSUE TITLE
桑基图的颜色和节点设置问题

### ISSUE THREAD

**Issue by bsdyfhc** [pyecharts/pyecharts#952]
**问题**
1.能否对桑基图的各个nodes和links单独设置颜色？
2.能否自由添加没有links的nodes并设置它在桑基图中的位置？我试过添加没有links的nodes，但这个nodes的长度几乎是0，因为没有links也就没有value，能否对这种节点单独设置value并设置它在桑基图中的位置？

**运行环境（系统环境及 pyecharts 版本）**
python3.6+win7，pyecharts 0.5.11

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@bsdyfhc 
* 问题1、
   * Echarts 官方 Sankey 边的配置 https://echarts.baidu.com/option.html#series-sankey.lineStyle.color
   * Echarts 官方 Sankey 矩形的配置 https://echarts.baidu.com/option.html#series-sankey.itemStyle.color
   * pyecharts 1.0.0 也能对 line_style 和 item_style 进行配置

* 问题2、
   * 请先去理解一下什么是桑基图:
  `桑基图最明显的特征就是，始末端的分支宽度总和相等，即所有主支宽度的总和应与所有分出去的分支宽度的总和相等，保持能量的平衡。`

**Comment by xigrug** [comment]
还是不明白怎么设置colorbar，让每一个变量都按指定的颜色填充
