### ISSUE TITLE
希望添加去掉折线图legend圆点即折线节点的功能

### ISSUE THREAD

**Issue by evanslight** [pyecharts/pyecharts#955]
**问题**
您好，当折线图symbol为None时，折线图没有节点，但是legend仍然有节点，显示不一致。希望能有相关配置选项，谢谢！

**运行环境（系统环境及 pyecharts 版本）**
windows, ubuntu, centos, python 3.7.2, pyecharts0.5.11

**代码及截图**

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！可以设置 `legend_opts=opts.LegendOpts(is_show=False)` 隐藏 legend
