### ISSUE TITLE
使用Overlap后，line不显示

### ISSUE THREAD

**Issue by edwardzhang0630** [pyecharts/pyecharts#957]
【问题】
使用overlap后，line不显示
kline正常显示，line不见了

我已经定位到原因：

【代码】
import pandas as pd

data = pd.readExcel(file)

datetime = data['datetime']
.......

kline.add('kline', datetime, price)
line.add('line', datetime, line_data)

overlap.add(kline)
overlap.add(line)

overlap.render()

【问题原因】
因为我的数据存储在pandas的dataframe中，当我取出时间：
datetime = data['datetime']
datetime的时间格式为<class 'pandas.core.series.Series'>

这个时候，overlap的kline正常显示，但是line不见了，
当我把他转换成list，就没有问题了。
datetime  = datetime.tolist（）

我觉得，这个问题是否可以修复一下，藏的太深了，搞了我一下午，终于找到了原因。

【截图】
![kline_bug](https://user-images.githubusercontent.com/33045925/55141579-ab642000-5175-11e9-9bec-97274a416030.PNG)

【运行环境（系统环境及 pyecharts 版本）】
win10
python 3.6
pyecharts 0.5.11

**Comment by erikgqp8645** [comment]
你好，我这个转换出来咋还是不行呢。
![image](https://user-images.githubusercontent.com/41559617/55205134-99818c00-520c-11e9-8ea2-0e1b517f7bb2.png)
出来之后还是带引号。然后结果是这样的
![image](https://user-images.githubusercontent.com/41559617/55205157-af8f4c80-520c-11e9-8126-9e6a22c072de.png)

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/55214381-9351d680-5231-11e9-80eb-9a4eb6841457.png)
