### ISSUE TITLE
jupyterhub（注意不是jupyterLab） 中 echarts.min.js 等404了，导致notebook中图表显示空白

### ISSUE THREAD

**Issue by EdwardBlues** [pyecharts/pyecharts#959]
**问题**
多用户的 jupyterhub 的 library_parh 设置本来就非常麻烦，这个 echarts 所需 js 找不到的问题，不知道是不是 linux 用户权限和 library_parh 的问题导致的。

**运行环境（系统环境及 pyecharts 版本）**
centos 7 + jupyterhub 0.9.4 + pyecharts 0.5.11

**代码及截图**
![image](https://user-images.githubusercontent.com/13886374/55214131-b8921500-5230-11e9-913c-3ed0e6ee252f.png)
![image](https://user-images.githubusercontent.com/13886374/55213805-74524500-522f-11e9-9048-fcd1db3b6f43.png)
![image](https://user-images.githubusercontent.com/13886374/55213824-892ed880-522f-11e9-8da1-7b75d6712b5b.png)
![image](https://user-images.githubusercontent.com/13886374/55214328-5259c200-5231-11e9-805b-a55df4daa17b.png)

**Comment by chenjiandongx** [comment]
下个版本开始将抛弃插件的方式，这种问题将不会再出现

**Comment by EdwardBlues** [comment]
> 下个版本开始将抛弃插件的方式，这种问题将不会再出现

期待，那就非常方便了，完全可以抛弃matplotlib。
目前这个问题有什么解决办法吗？

**Comment by chenjiandongx** [comment]
#1033 1.0.0 版本发布啦！

**Comment by EdwardBlues** [comment]
> #1033 1.0.0 版本发布啦！

1.0.0 版本威武！看得出来是很大的改动 :1st_place_medal: 
加上Type Hint就要整个过一遍了
options的写法得适应一下
感恩 :+1:
