### ISSUE TITLE
代码用pyinstaller打包成exe 后在运行时会报错 但如果透过py直接执行不会有此问题

### ISSUE THREAD

**Issue by YokerDan** [pyecharts/pyecharts#960]
**问题**
代码用pyinstaller打包成exe 后在运行时会报错
但如果透过py直接执行不会有此问题
内容如下：
ERROR:lml.utils:failed to import jupyter_echarts_pypkg
Traceback (most recent call last):
  File "site-packages\lml\utils.py", line 43, in do_import
ModuleNotFoundError: No module named 'jupyter_echarts_pypkg'
ERROR:lml.utils:failed to import pyecharts_snapshot
Traceback (most recent call last):
  File "site-packages\lml\utils.py", line 43, in do_import
ModuleNotFoundError: No module named 'pyecharts_snapshot'

**运行环境（系统环境及 pyecharts 版本）**
Windows 10 x64
pyecharts 0.5.11
python 3.7.1

**Comment by chfw** [comment]
pyecharts 1.0.0 会甩到所有插件，估计打包就不再困难了。

**Comment by YokerDan** [comment]
我改了 .spec 得内容把没有缺少的补上
但在执行后出现下面的错误代码
看起来是缺少了 countries_regions_db.json
这个有办法解决吗?
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\zzz~1.HSI\\AppData\\Local\\Temp\\_MEI162962\\pyecharts\\datasets\\countries_regions_db.json'`

**Comment by chfw** [comment]
再补上

**Comment by YokerDan** [comment]
要如何补上？
我不知道要怎么把他在 exe的temp中
有没有个范例？

**Comment by chfw** [comment]
实话实说啊，这个问题不是该问 pyinstaller 项目么？如何把 non-py resource 带到 exe 文件里？

**Comment by YokerDan** [comment]
um...
我懂了 要透过pyinstaller 将档案放入temp 里面
但想问一下要怎么做...初学者不是很懂要怎么做...

**Comment by chfw** [comment]
我也要哭啦。众里寻她千百度，回首她在灯火阑珊处。

**Comment by YokerDan** [comment]
哎呀 我好像成功了 一样是在 spec 里面增加
但 出现了 `json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)`
我晕 这也太硬了吧

**Comment by chfw** [comment]
除了加油之外，帮不上你了。

**Comment by paulwinflo** [comment]
您好，我打包pyecharts时也遇到和您一样的问题，您找到解决的办法了么

**Comment by YokerDan** [comment]
没有，最多就是把缺少的包放进去
但还有json 问题没有解决

**Comment by paulwinflo** [comment]
> 没有，最多就是把缺少的包放进去
> 但还有json 问题没有解决

谢谢您的深夜回复，看您是通过.spec文件来把缺少的包加进去的，您能share下.spec文件么，供小弟参照下

**Comment by YokerDan** [comment]
datas=[('.\\pyecharts\\','.\\pyecharts\\')
			 ,('.\\jupyter_echarts_pypkg\\','.\\jupyter_echarts_pypkg\\')
			 ,('.\\jinja2\\','.\\jinja2\\')
			 ,('.\\pyecharts_javascripthon\\','.\\pyecharts_javascripthon\\')
			 ,('.\\echarts_china_cities_pypkg\\','.\\echarts_china_cities_pypkg\\')
			 ,('.\\echarts_china_counties_pypkg\\','.\\echarts_china_counties_pypkg\\')
			 ,('.\\echarts_china_misc_pypkg\\','.\\echarts_china_misc_pypkg\\')
			 ,('.\\echarts_china_provinces_pypkg\\','.\\echarts_china_provinces_pypkg\\')
			 ,('.\\echarts_countries_pypkg\\','.\\echarts_countries_pypkg\\')
			 ,('.\\echarts_united_kingdom_pypkg\\','.\\echarts_united_kingdom_pypkg\\')],
             hiddenimports=['jupyter_echarts_pypkg','pyecharts_snapshot','echarts-countries-pypkg','echarts-china-provinces-pypkg','echarts-china-cities-pypkg','echarts-china-counties-pypkg','echarts-china-misc-pypkg']

我最多就把没补上的都补上
就是不知道json 问题该如何解决

**Comment by YanNIU2028** [comment]
打包缺少json 文件的解决方法就是:
Step 1 : pyinstaller -D  xxxxx.spec (-D 这里会生成一个dist/xxxxx文件夹，里面有所有需要的包)
Step 2 : 进入 dist/xxxxx 文件夹，把你在Python的"pyecharts"整个文件夹复制过去(里面有你缺少的那些不能被打包的json文件)
Step 3 : 不要问我叫什么名字，问的话，就是雷锋。万分感谢pyecharts，希望下个版本能把打包这个问题解决了。
