### ISSUE TITLE
地图散点图能否实现以symbol_size显示值的大小

### ISSUE THREAD

**Issue by rawenlei** [pyecharts/pyecharts#964]
开发团队，你们好：
在echarts中，可以通过调用函数的方式实现以symbol_size显示value的大小，这样的图看起来很直观。
因为我不懂java，能否帮忙在python中实现类似的效果，感谢。
rawen
rawen0623@live.com
![symbolSize](https://user-images.githubusercontent.com/42257971/55462161-b6f99000-5628-11e9-8095-4a8cc8a84c2b.png)

**Comment by rawenlei** [comment]
感谢你们提供的平台和你们的付出。
上述问题，通过调用visualMap中的is_visualmap=True,visual_type=True和visual_range_size=[]的方式，可以实现在地图上显示值的大小。

**Comment by leereak** [comment]
> 感谢你们提供的平台和你们的付出。
> 上述问题，通过调用visualMap中的is_visualmap=True,visual_type=True和visual_range_size=[]的方式，可以实现在地图上显示值的大小。

您好，能把您实现的代码发我吗，我按照设置，并没有能够改变点的大小

**Comment by rawenlei** [comment]
你好，代码如下，我在发之前试了下，是可以显示大小的，供你参考。
`a={'广东':18,'湖北':18.6,'广西':23.6,'湖南':21.2,'江西':16.7,'江苏':10.3,'河北':18.8,'浙江':10.2,'四川':48.1,'北京':1.7,
       '上海':0.6,'河南':16.7,'山东':15.4,'陕西':20.6,'香港':0.1,'安徽':14.0,'山西':15.7,'福建':12.1,'内蒙古':118,'重庆':8.2,
       '新疆':166,'西藏':122.8,'吉林':18.8,'云南':38.3,'辽宁':14.6,'海南':3.4,'黑龙江':45.5,'青海':72.2,'贵州':17.6}
    geo=Geo('中国各省面积图',title_pos='center',width=1366,height=768,background_color='pink')
    k,v=geo.cast(a)
    geo.add('',k,v,is_visualmap=True,visual_type='size',visual_range_size=[0,100],is_label_show=True,label_text_color='white',label_text_size=10)
    geo.render('中国各省面积图4-28.png')`
![image](https://user-images.githubusercontent.com/42257971/56858782-daf38b80-69b2-11e9-836a-568faccfa79a.png)

**Comment by MeowAlienOwO** [comment]
现在用 BMap 不知怎么实现，用了很蠢的逐个加点+调整 symbol_size 的办法，看文档感觉要用 js 重写渲染逻辑，没有更好的实现吗？
