### ISSUE TITLE
是否可以自定义背景图片？以及polar图中调节填充区域透明度的参数未奏效

### ISSUE THREAD

**Issue by PJohnYu** [pyecharts/pyecharts#966]
我希望给polar图自定义一个背景图，但是不知道如何设置。
另外，我尝试调节透明度的参数area_opacity，在折线图中有效但极坐标系无效

附polar代码
polar.add(
            "",
            data=data,
            render_item=render_item,
            type="custom",
            angle_data=['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW',
                        'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'],
            radius_data=radius,
            is_visualmap=True,
            boundary_gap=False,#角度类目是否在刻度之间
            is_fill=True,
            area_opacity=0.1,
            visual_range=[0, 25],
            is_splitline_show=False, #是否显示轴向线
            opacity=0.1,
            visual_range_text=['', ' unit:Sv'],#修改图例处文本信息
            tooltip_trigger='none',#是否触发信息框
            tooltip_axispointer_type='cross',#十字指示器
            clockwise=True,
            is_datazoom_show=True,
            datazoom_range=[0, 100],
        )
Python初学者，希望得到一些帮助和建议，感谢

**Comment by sunhailin-Leo** [comment]
@PJohnYu 
* 背景图 Echarts 官方也无法设置，所以我们也找不到对应的参数进行设置

**Comment by kiverc** [comment]
> @PJohnYu
> 
> * 背景图 Echarts 官方也无法设置，所以我们也找不到对应的参数进行设置

     "graphic": [{
         "type": "image",
         "id": "logo",
         "left": "auto",
         "top":"30%",
         "style": {
                "image":img,
                width:900}}],添加图表

我记得有这个设置的，添加一张图片
