### ISSUE TITLE
尝试运行example失败

### ISSUE THREAD

**Issue by metaroboman** [pyecharts/pyecharts#970]
**问题**
发现使用方法跟以前不大一样，于是尝试更新了，但是提示已经是最新版。但是现在的example都无法正常运行。

**运行环境（系统环境及 pyecharts 版本）**
macOS Mojave 10.14.3，python3.7, pyecharts 0.5.11

**代码及截图**
<img width="1133" alt="Screen Shot 2019-04-07 at 11 58 09" src="https://user-images.githubusercontent.com/49356546/55678460-c29ccd80-592c-11e9-9743-7f0874ae2699.png">

**Comment by chenjiandongx** [comment]
使用源码安装 
```shell
$ git clone https://github.com/pyecharts/pyecharts.git
$ cd pyecharts
$ pip install -r requirements.txt
$ python setup.py install
```

**Comment by metaroboman** [comment]
感谢，已经解决了。
现在装了selenium后无法保存图片。找的设置Safari的教程都没用，您知不知道怎么设置Safari为selenium的默认浏览器？提示没有chrome，我压根就没装当然没有。

**Comment by tudoulei** [comment]
没有用啊，怎么样都没法import

**Comment by metaroboman** [comment]
你看一下最新的pyecharts是不是安装在你的python运行环境里

**Comment by tudoulei** [comment]
![image](https://user-images.githubusercontent.com/34886368/55681074-a876e580-5954-11e9-8c21-2c61b604479c.png)

**Comment by tudoulei** [comment]
可以import pyecharts但是却导入不了内部库

**Comment by tudoulei** [comment]
用的anaconda里的jupyter进行操作的，pycharm也试了没有用

**Comment by chenjiandongx** [comment]
你是用什么安装的 哪个系统

**Comment by tudoulei** [comment]
使用的win7操作系统，pip install pyecharts 和您上面的方法都试过了，想要pyecharts安装到我的python环境应该怎么做

**Comment by chenjiandongx** [comment]
install.bat

**Comment by tudoulei** [comment]
![image](https://user-images.githubusercontent.com/34886368/55681240-98600580-5956-11e9-8d67-05cbf4fd3892.png)
依然无法import，用了您的方法

**Comment by tudoulei** [comment]
![image](https://user-images.githubusercontent.com/34886368/55681257-d78e5680-5956-11e9-8778-c3e032b119ea.png)
但是奇怪的是，使用cmd的python就可以生成html

**Comment by chenjiandongx** [comment]
你是不是把文件明名为 pyecharts.py 之类的

**Comment by tudoulei** [comment]
没有，是在jupyterlab上进行编写的，
![image](https://user-images.githubusercontent.com/34886368/55681299-56838f00-5957-11e9-8f01-09892d1cf707.png)

**Comment by chenjiandongx** [comment]
重启 jupyter

**Comment by tudoulei** [comment]
依然没有解决，现在在cmd窗口编写代码倒是好使，谢谢您了！

**Comment by chfw** [comment]
试试这个：

<img width="482" alt="Screenshot 2019-04-07 at 11 20 33" src="https://user-images.githubusercontent.com/4280312/55682142-3cca5380-5927-11e9-92e3-68f3060e8aec.png">
<img width="492" alt="Screenshot 2019-04-07 at 11 21 34" src="https://user-images.githubusercontent.com/4280312/55682146-51a6e700-5927-11e9-94f4-8526f5c3b939.png">

**Comment by chfw** [comment]
我的判断是两个 python 路径不一样。一个装了 pyecharts 1.0.0 另一个装了 pyecharts 5.11

**Comment by chfw** [comment]
<img width="370" alt="Screenshot 2019-04-07 at 11 24 46" src="https://user-images.githubusercontent.com/4280312/55682185-cd089880-5927-11e9-814a-4f01e7f4972c.png">

然后看里面的 pyecharts 版本

**Comment by metaroboman** [comment]
我用git安装后也是用命令行没问题，jupyter不行，后来发现git是在一个新地址重新安装，而没有覆盖原来的
我的解决办法是，用git安装的pyecharts文件夹覆盖anaconda文件夹里的python3.7下面的文件包里的pyecharts文件夹。

**Comment by chfw** [comment]
可以用 Pip uninstall pyecharts 直到没有可以卸载的 再去装

**Comment by sunhailin-Leo** [comment]
@metaroboman 
* 目前Safari 不支持 headless 的方式，最好建议使用 chrome. 
* Mac 下的解决方案就是安装一个 Chrome, 然后下一个 ChromeDriver 把 driver 丢到 ```/usr/bin``` 目录下即可.
* ChromeDriver 的下载地址: http://chromedriver.storage.googleapis.com/index.html 
* 查看 Chrome 的版本: 
    * 在 Chrome 浏览器地址栏输入: ```chrome://settings/help```

**Comment by chfw** [comment]
<img width="676" alt="Screenshot 2019-04-07 at 21 33 30" src="https://user-images.githubusercontent.com/4280312/55689485-d839e380-597c-11e9-8773-f2581195c991.png">

renferece: https://www.dev2qa.com/python-how-to-launch-safari-firefox-chrome-in-selenium-webdriver/

**Comment by sunhailin-Leo** [comment]
@chfw 
* Safari 的很多功能都用不了, 包括现在 make_snapshot 里面的 driver.get_log() 在 Safari 里面取不到 selenium 的日志

reference: https://developer.apple.com/documentation/webkit/macos_webdriver_commands_for_safari_12_and_later

**Comment by chfw** [comment]
safari 可以抓屏，细节请看 #973

对我们的 use case 来说， 唯一不足的是 safari 不支持 headless 模式。

https://github.com/SeleniumHQ/selenium/issues/5985

**Comment by chfw** [comment]
先关了。还有问题再说
