### ISSUE TITLE
能否实现在循环监控中刷新

### ISSUE THREAD

**Issue by whwzsm** [pyecharts/pyecharts#971]
**问题**

有时我们需要对一些数据进行动态监控，生成图表，比如每五分钟扫描一次，生成图表。
数据的产生很简单用while就行了，下面用pyechart生成的相应图表也可以自动刷新么？

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
@whwzsm 可以在前端用 js 写定时任务, 去后台加载画图配置

**Comment by whwzsm** [comment]
多谢，您这个是在网页中实现？

**Comment by whwzsm** [comment]
> @whwzsm 可以在前端用 js 写定时任务, 去后台加载画图配置

您好，在IDLE或juypter中有办法实现么

**Comment by sunhailin-Leo** [comment]
@whwzsm juypter 的话我很少用，暂时帮不到你

**Comment by whwzsm** [comment]
> @whwzsm juypter 的话我很少用，暂时帮不到你

在IDLE或pycharm等其他IDE，有办法不?

**Comment by sunhailin-Leo** [comment]
@whwzsm 
* 第一种，通过接口交互
1、构建 Web 项目，接口返回画图的 options
2、构建前端项目，定时从后台的接口获取画图的options 

* 第二种，通过 WebSockets 进行交互
1、前端编写 WebSockets 代码接收后端发送的 options 
2、前端接收到以后进行渲染

**Comment by Macile** [comment]
@whwzsm 遇到了相同的问题，请问一下您找到办法了吗？求一个demo或者代码呗
