### ISSUE TITLE
selenium 需要 Chrome, 但是 MacOS 没有装，奈何

### ISSUE THREAD

**Issue by chfw** [pyecharts/pyecharts#972]
来自
https://github.com/pyecharts/pyecharts/issues/970

和以下相关
https://github.com/pyecharts/pyecharts/issues/892

**Comment by chfw** [comment]
我认为这个snapshot功能需要从 pyecharts 核心剔除，成为一个配件 pyecharts-snapshot-selenium. 虽然我是配件大师啊，以下是我的理由：

1） 虽然 pyecharts-snapshot 以来 phantomjs, 它的输出能力已经很强：png, pdf, gif, svg, raw 等等。
2) selenium 是可以让一部分人摆脱对phantomjs 的依赖，现在我们遇到的是 chrome or safari 的问题。同时，selenium 的这部代码在 Safari 还需要打磨一下。

所以我的建议是：

a. 提出 pyecharts-snapshot 里对 phantomjs 的依赖，变成 snapshot-phantomjs
b. 然后成立 snapshot-selenium, 让愿意用 selenium 的同学去装。
c. 同时可以把 pyecharts-snapshot 并入 pyecharts core, 如果大家别介意 PIL 的话。虽然我一直建议剔除 PIL, 可以直到0.5.x, PIL 还是一个固定依赖。

**Comment by sunhailin-Leo** [comment]
@chfw 
* 1、我觉得 Chrome or Safari 的问题, 已经没什么可讨论的, 毕竟 Selenium 受限于 SafariDriver
* 2、其次, 对于其他 Driver 不支持 headless 模式的，也没有任何必要对其做开发或者增加代码, 毕竟 snapshot 的核心目前是依赖于 headless 这个模式.

**Comment by chfw** [comment]
看具体要求了。如果是在服务器上，没有 X server 的话，headless 是必须的。

要是就要一个图片的话，用 Mac OS 的 Safari 还是好解决的，就冒个窗口，然后消失：
<img width="899" alt="Screenshot 2019-04-07 at 22 18 02" src="https://user-images.githubusercontent.com/4280312/55689958-3cf83c80-5983-11e9-997a-a7d711f48875.png">

**Comment by metaroboman** [comment]
我的报错了，了解为什么吗，大哥们

<img width="1131" alt="Screen Shot 2019-04-08 at 11 08 22" src="https://user-images.githubusercontent.com/49356546/55696255-b5481780-59ee-11e9-967c-5ffccad3f748.png">

**Comment by chenjiandongx** [comment]
不要 browser 参数

**Comment by metaroboman** [comment]
<img width="930" alt="Screen Shot 2019-04-08 at 11 21 15" src="https://user-images.githubusercontent.com/49356546/55696633-7c10a700-59f0-11e9-8527-785b946bce16.png">

**Comment by chenjiandongx** [comment]
你现在拉的是 v2019 分支吗，如果是的话 暂时没适配 safari，你可以先装个 chrome 试试

**Comment by metaroboman** [comment]
ok，是2019。现在不支持phantomjs了？

**Comment by chenjiandongx** [comment]
后面会支持，可能会以插件的形式 pip install pyecharts-phantomjs 之类的 然后也会是相同的参数接口

**Comment by chfw** [comment]
Git checkout safari-support

**Comment by chfw** [comment]
还没有并入。 @chenjiandongx, 没有意见 我就并入了。

**Comment by metaroboman** [comment]
OK，感谢，辛苦了！

**Comment by chfw** [comment]
经过1小时讨论，我们决定生成：

1. snapshot-selenium
2. snapshot-phantomjs
3. snapshot-new-technology...

用户可以选择自己的技术偏好安装。为了减少依赖，要生成 pdf, gif, raw, tiff 的话，需要继续装 PIL

具体介绍有英文版：

https://pyecharts.org/#/en-us/prepare?id=rendering-as-image
