### ISSUE TITLE
官方demo无法运行 

### ISSUE THREAD

**Issue by Rockyzsu** [pyecharts/pyecharts#974]
**问题**
按照最新的官方demo运行以下代码，直接报错，模块不存在

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-43-73ce9080304a> in <module>()
----> 1 from pyecharts.charts import Bar
      2 
      3 bar = Bar()
      4 bar.add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
      5 bar.add_yaxis("商家A", [5, 20, 36, 10, 75, 90])

ImportError: cannot import name 'Bar' from 'pyecharts.charts' (C:\ProgramData\Anaconda3\lib\site-packages\pyecharts\charts\__init__.py)

**运行环境（系统环境及 pyecharts 版本）**

**代码及截图**
![bug](https://user-images.githubusercontent.com/7868260/55707872-3915fa00-5a17-11e9-9a6a-7d81398e69ce.PNG)

**Comment by chenjiandongx** [comment]
sorry, 暂时只支持源码安装 正式版还没发布

**Comment by mark163361** [comment]
我在pycharm中安装了pyecharts，执行案例之后，也是报错cannot import name 'Bar' ，在pycharm中怎么解决这个问题呢？

**Comment by chfw** [comment]
请以这个文档为准：https://05x-docs.pyecharts.org/#/zh-cn/prepare

**Comment by shaooping** [comment]
pip 安装方式 依然没有出正式版吗。。。一直不能用

**Comment by shaooping** [comment]
> pip 安装方式 依然没有出正式版吗。。。一直不能用

对不起我的锅，没有好好学习看文档 用的是0.5版本的from pyecharts import Bar
1.0的文档是 from pyecharts.charts import Bar
