### ISSUE TITLE
底图显示所有下级城市边界的问题

### ISSUE THREAD

**Issue by julywolf** [pyecharts/pyecharts#976]
**问题**
使用pyecharts的做地图的显示的时候，默认只会显示本级和下一级的城市和边界，比如定义地图为“湖北”，就会显示湖北省的省界和17个地级市的市界，如果要在显示湖北的省界和17个地市级的市界的同时，把下一级的县界也进行显示，请问是否可以实现？

**代码及截图**
比如实现下面图片的效果：
![image](https://user-images.githubusercontent.com/40717961/55729439-bd34a580-5a48-11e9-93f0-17e349dd5e01.png)

**Comment by WinWbb** [comment]
应该是可以的
