### ISSUE TITLE
能提供下之前版本的文档吗，现在的文档都是新版本的了

### ISSUE THREAD

**Issue by RaoTianlong** [pyecharts/pyecharts#977]
**能提供下之前版本的文档吗**

**版本0.5.11**

**代码及截图**

**Comment by sunhailin-Leo** [comment]
![image](https://user-images.githubusercontent.com/17564655/55790781-aac17700-5aef-11e9-8bcc-a4e2d027b08a.png)

这么大的字写着... :sweat:

[传送门](http://05x-docs.pyecharts.org/)

**Comment by RaoTianlong** [comment]
> ![image](https://user-images.githubusercontent.com/17564655/55790781-aac17700-5aef-11e9-8bcc-a4e2d027b08a.png)
> 
> @RaoTianlong 首页文档这么大的字写着... 
> 
> [传送门](http://05x-docs.pyecharts.org/)

我瞎了(ಥ _ ಥ)
