### ISSUE TITLE
用papermill或nbconvert命令行运行notebook，得到的结果文件中图无法显示

### ISSUE THREAD

**Issue by dehiker** [pyecharts/pyecharts#978]
**问题**
用[papermill](https://github.com/nteract/papermill)或[nbconvert](https://nbconvert.readthedocs.io/en/latest/execute_api.html)命令行运行notebook，得到的结果文件中图无法显示，全为空白，如
papermill test.ipynb test.ipynb
jupyter nbconvert --execute --to notebook --inplace test.ipynb

请问这是正常结果，还是哪里配置了可以解决？

**运行环境（系统环境及 pyecharts 版本）**
pyecharts==0.5.11

**代码及截图**

**Comment by chfw** [comment]
试试render图片。

**Comment by dehiker** [comment]
使用render方式，图会直接保存成图片，但是在notebook中还是不可见？

当前的应用是命令行自动jupyter notebook来做数据监控，希望运行结果中能直接看到数据图表。不知当前pyecharts是否支持？

**Comment by chenjiandongx** [comment]
并不觉得 Jupyter notebook 来做监控是个好方案，建议还是使用原生 JS 来实现此功能。
