### ISSUE TITLE
class Chart3D add方法的name变量打错了

### ISSUE THREAD

**Issue by liangzhewen97** [pyecharts/pyecharts#981]
使用Scatter3D时报错，提示name没有定义。
原因是class Chart3D下的add方法中LINE 227打错了，应为series_name。

**Comment by sunhailin-Leo** [comment]
@liangkiko 能提供下你的代码以及报错的完整截图吗？ 😄

**Comment by chfw** [comment]
有时间，来个PR也行啊。

**Comment by Fankbai** [comment]
Surface3D()示例代码运行结果。
![image](https://user-images.githubusercontent.com/10338671/55922564-57a50c80-5c34-11e9-8d98-b6ae9e3bd720.png)

**Comment by Fankbai** [comment]
代码"pyecharts/charts/chat.py"中第242行修改为serious_name即可。

**Comment by liangkiko** [comment]
> @liangkiko 能提供下你的代码以及报错的完整截图吗？ 😄

sample里的scatter3D代码：
![image](https://user-images.githubusercontent.com/37006638/55923134-bcf9fd00-5c36-11e9-8fa7-53b70ded6e96.png)
报错：
![image](https://user-images.githubusercontent.com/37006638/55923176-ea46ab00-5c36-11e9-8362-ab25a7104bdf.png)
错误之处：
![image](https://user-images.githubusercontent.com/37006638/55923187-f5014000-5c36-11e9-8b9f-4e70afa27d9f.png)
应为series_name

**Comment by chenjiandongx** [comment]
Fixed
