### ISSUE TITLE
module 'pyecharts' has no attribute 'constants'

### ISSUE THREAD

**Issue by Xialichong** [pyecharts/pyecharts#982]
我之前脑子一热装了一个包

conda install -c damianavila82 rise
这个包可以把jupyter 转换成slides

结果现在import pyecharts就一直报错了，
第一遍是说找不到ducky，第二遍import就报如下的错
AttributeError: module 'pyecharts' has no attribute 'constants'

要哭了，求帮助，555
我看网上的教程，把所有jupyterlab名的package都删了，但还是有这个错…

是不是只能清空所有的pip再安装了

悲剧。。。

**Comment by chfw** [comment]
完蛋了吧。conda 是不是可以创建自己的 python virutal environment? 再建一个不行么？

**Comment by Xialichong** [comment]
我找找资料试试

**Comment by chenjiandongx** [comment]
pip install pyecharts==0.5.11 -U --no-cache-dir

**Comment by Xialichong** [comment]
> pip install pyecharts==0.5.11 -U --no-cache-dir 试试看

X谢谢，没啥用，不过按照上面哥们的方法，另外创建了个环境装好了
