### ISSUE TITLE
bar 里同时更改图片的width和height，在notebook里不显示图

### ISSUE THREAD

**Issue by huangzhenhao90** [pyecharts/pyecharts#983]
**问题**
bar 里同时更改图片的width和height，在notebook里不显示图

**运行环境（系统环境及 pyecharts 版本）**
mac 10.14.4
pyecharts 1.0 

**代码及截图**

![C8BA4595-9C3F-4524-B243-F0297B9F26A6](https://user-images.githubusercontent.com/33592619/55926550-5c71bc80-5c44-11e9-900a-23dc7e433886.png)

**Comment by chenjiandongx** [comment]
试试 width="50px", height="200px"，这两个参数接收的是字符串类型

**Comment by huangzhenhao90** [comment]
> 试试 width="50px", height="200px"，这两个参数接收的是字符串类型

可以了，其实之前也试过这么写，但应该是哪里格式没写对。感谢作者亲自回复！很激动~

**Comment by chenjiandongx** [comment]
😄
