### ISSUE TITLE
example中'overlap_example.py'的error

### ISSUE THREAD

**Issue by jixinyu-hlj** [pyecharts/pyecharts#985]
**问题**
example的'overlap_example.py'文件运行出错，应该是第21行和25行AxiOpts类的参数设置错误，
![Snipaste_2019-04-11_18-12-01](https://user-images.githubusercontent.com/35923157/55949670-bb0b5a80-5c85-11e9-8ef3-d334cd3a0f31.png)

加上LabelOpts就可以了。
![Snipaste_2019-04-11_18-14-07](https://user-images.githubusercontent.com/35923157/55949653-b050c580-5c85-11e9-8887-ca5fcb476a2f.png)

**运行环境（系统环境及 pyecharts 版本）**
pyecharts==1.0.0
win10

**代码及截图**

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/55950474-97e1aa80-5c87-11e9-84ce-3d407396fe3d.png)

已修复
