### ISSUE TITLE
运行示例代码 显示包中没有'prettytable'这个模块

### ISSUE THREAD

**Issue by qingyanker** [pyecharts/pyecharts#987]
**问题**
运行示例代码
显示包中没有'prettytable'这个模块

**运行环境（系统环境及 pyecharts 版本）**
win10   jypter notebook        pyecharts  git hub 最新版

**代码及截图**
from pyecharts.charts import Bar
from pyecharts import options as opts

bar = (
    Bar()
    .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
    .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
    .set_global_opts(title_opts=opts.TitleOpts(title="某商场销售情况"))
)
bar.render()
![image](https://user-images.githubusercontent.com/46557374/56018487-d84b3200-5d34-11e9-8f45-fcaade443361.png)

**Comment by chenjiandongx** [comment]
``pip install -r requirements.txt`
