### ISSUE TITLE
老版代码可以运行 新版代码不能运行

### ISSUE THREAD

**Issue by qingyanker** [pyecharts/pyecharts#988]
**问题**
更新以后官方文档的代码均不能运行
老版的就可以

**运行环境（系统环境及 pyecharts 版本）**
win10 notebook github 最新版pyecharts

**代码及截图**
![image](https://user-images.githubusercontent.com/46557374/56020172-1fd3bd00-5d39-11e9-9ccc-46f5c2ac0732.png)

![image](https://user-images.githubusercontent.com/46557374/56020274-57426980-5d39-11e9-9572-884d7c0d49df.png)

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/56020365-91ac0680-5d39-11e9-994e-a58269c74457.png)

**Comment by chenjiandongx** [comment]
这是一个全新的 pyecharts 版本，不会向下兼容 需要用到旧版的请阅读旧版的文档

**Comment by qingyanker** [comment]
> 这是一个全新的 pyecharts 版本，不会向下兼容 需要用到旧版的请阅读旧版的文档

谢谢 我准备使用新版 但是我从github 手动放到包里面 就会显示这个样子 请问应该怎么安装github上传的版本呢 pip 安装过后就变成这样

**Comment by sunhailin-Leo** [comment]
@qingyanker 项目仓库在前排就有很大的提示语写着使用源码进行安装~

```
$ git clone https://github.com/pyecharts/pyecharts.git
$ cd pyecharts
$ pip install -r requirements.txt
$ python setup.py install
```

**Comment by raymondby** [comment]
用pip uninstall，把旧版本彻底删除
重新通过源码安装最新版本（可能会需要先安装prettytable）

最重要的一点：官方示例代码在源码的example目录里(主页上的示例缺少render)，因为你用的是notebook，所以最后的.render()必须改成render_nootbook()
