### ISSUE TITLE
这是一个全新的 pyecharts 版本，不会向下兼容 需要用到旧版的请阅读旧版的文档

### ISSUE THREAD

**Issue by qingyanker** [pyecharts/pyecharts#989]
这是一个全新的 pyecharts 版本，不会向下兼容 需要用到旧版的请阅读旧版的文档

_Originally posted by @chenjiandongx in https://github.com/pyecharts/pyecharts/issues/988#issuecomment-482473492_

谢谢 我准备使用新版  但是我从github 手动放到包里面 就会显示这个样子 请问应该怎么安装github上传的版本呢 pip 安装过后就变成这样

**Comment by chenjiandongx** [comment]
多看几眼 README 并不难，都写在 README 里

![image](https://user-images.githubusercontent.com/19553554/56020640-2dd60d80-5d3a-11e9-819c-9d9239a83124.png)

**Comment by qingyanker** [comment]
> 这是一个全新的 pyecharts 版本，不会向下兼容 需要用到旧版的请阅读旧版的文档



> 多看几眼 README 并不难，都写在 README 里
> 
> ![image](https://user-images.githubusercontent.com/19553554/56020640-2dd60d80-5d3a-11e9-819c-9d9239a83124.png)

好的 谢谢  我源码安装报错了  才找到这里- -  我再研究一下

**Comment by chenjiandongx** [comment]
或者可以运行 `python install.py`

**Comment by Gotoevil** [comment]
我使用的是python3，所以用的命令是pip3和python3，替换掉readme中安装说明里的pip和python。
因为是初学者，所以python是用brew安装的，然后并没有研究清楚怎么设置环境变量，以使采用命令`python`能够指向`python3`，或者采用命令`pip`能够指向`pip3`。
另外，既然1.0.0版本之后全面拥抱python3了，是否相应的安装命令，也应该采用python3默认的命令呢？

**Comment by sunhailin-Leo** [comment]
@Gotoevil 兄弟，我只是想说为什么一定要在系统环境强制映射 pip 为 pip3 ? 

* 对于 Mac OS 以及 Linux 来说很多系统的依赖和插件还是使用 Python 2.X 版本的，这也是为什么目前所有的 Linux 系统以及 Mac 系统一定会有 Python 2.X 的命令存在。
* 如果你觉得看的不舒服的, 请打开命令行执行 `ln -snf /usr/bin/python /Library/Frameworks/Python.framework/Versions/3.7/bin/python3` (pip 同理)
* 上述命令即切换 `python` 这条命令的软链接

**Comment by chfw** [comment]
建议 python pro 用 pyenv

**Comment by Gotoevil** [comment]
@sunhailin-Leo 嗯，不知道新版本会不会跟python 2.7有不兼容呢？

**Comment by sunhailin-Leo** [comment]
@Gotoevil 你试试就知道是否兼容了 😄

**Comment by chfw** [comment]
不会兼容 2.7
