### ISSUE TITLE
1.0.0版的说明文档中能否详述render的使用方法及相关的设置项

### ISSUE THREAD

**Issue by Gotoevil** [pyecharts/pyecharts#990]
**问题**
1.0.0版的说明文档中能否详述render的使用方法及相关的设置项
我翻阅了配置项（包括全局和系列），没有找到设置render的相关说明，老版的snapshot功能还能否使用？

**运行环境（系统环境及 pyecharts 版本）**
macos 10.14.4
python==3.7.2
pyecharts==1.0.0

**代码及截图**
Demo中渲染的语句为：
`Page().add(*[fn() for fn, _ in C.charts]).render()`

**Comment by sunhailin-Leo** [comment]
* render 的源码点进去看就好了，我觉得没什么特别需要说明的问题吧？
* 文档并不能只是列出了主要的配置项。
* 具体的一些函数的用法，请建议多看看源码～ (Ps: 阅读源码也是对自己能力的提升 😄 )
![image](https://user-images.githubusercontent.com/17564655/56051358-e757d180-5d80-11e9-8739-dabaf4e3fbd7.png)

**Comment by Gotoevil** [comment]
@sunhailin-Leo 感谢指点，我好好看看源代码。这个issue可以关掉了。
