### ISSUE TITLE
pyecharts 添加自定义文字

### ISSUE THREAD

**Issue by shshjun** [pyecharts/pyecharts#991]
**问题**
参考
    https://blog.csdn.net/NRlovestudy/article/details/85240527
之方法一，建议添加一个图层，具体为一个矩形框加上里面的文字，选项可以最少化
定义矩形位置和大小 top left width height
定义边框 line-width line-color
定义矩形底色 fill-color
定义文字大小和颜色 font-color font-size

**运行环境（系统环境及 pyecharts 版本）**
主流浏览器。我自己用win+python27

**代码及截图**
option = {
   
    graphic: [
         {
            type: 'group',
            left: 'center',
            bottom: 130,
            children: [
                {
                    type: 'rect',
                    z: 100,
                    left: 'center',
                    top: 'middle',
                    shape: {
                        width: 190,
                        height: 90
                    },
                    style: {
                        fill: '#fff',
                        stroke: '#555',
                        lineWidth: 2,
                        shadowBlur: 8,
                        shadowOffsetX: 3,
                        shadowOffsetY: 3,
                        shadowColor: 'rgba(0,0,0,0.3)'
                    }
                },
                {
                    type: 'text',
                    z: 100,
                    left: 'center',
                    top: 'middle',
                    style: {
                        fill: '#333',
                        text: [
                            '自定义文字自定义文字',
                            '自定义文字自定义文字',
                            '自定义文字自定义文字',
                            '自定义文字自定义文字',
                            '自定义文字'
                        ].join('\n'),
                        font: '14px Microsoft YaHei'
                    }
                }
            ]
        }
    ],
   
 
};

![image](https://user-images.githubusercontent.com/816453/56045534-00a65100-5d74-11e9-8d26-95736327999f.png)

**Comment by sunhailin-Leo** [comment]
@shshjun 这个 graphic 图层的方法应该会在后续的版本加入。目前 1.0.0 暂时没有这个方法。如果你能够提 PR 我们也非常欢迎！👏 

Ps: 都 9102 年了，改抛弃 Python 2.7 了 😄

**Comment by shshjun** [comment]
another example:
https://www.echartsjs.com/examples/editor.html?c=line-graphic

**Comment by sunhailin-Leo** [comment]
@shshjun 将在 1.1.0 之后的下一个版本中加入这个功能 😄

**Comment by sunhailin-Leo** [comment]
@shshjun 最新版 1.2.0 中已经加入了这个功能了～欢迎使用 😄
