### ISSUE TITLE
堆叠柱状图显示百分比

### ISSUE THREAD

**Issue by Xialichong** [pyecharts/pyecharts#992]
RT， 请问如何在一个堆叠的柱状图上，显示每个的百分比占比？

感激感激

**Comment by sunhailin-Leo** [comment]
Echarts 暂时也无法在堆叠的柱子上显示百分比, 如果要显示的建议在 Tooltip 中配置显示

**Comment by Xialichong** [comment]
> Echarts 暂时也无法在堆叠的柱子上显示百分比, 如果要显示的建议在 Tooltip 中配置显示

谢谢
