### ISSUE TITLE
linux下源码安装出现语法错误

### ISSUE THREAD

**Issue by XuSirSir** [pyecharts/pyecharts#993]
**问题**
linux下源码安装出现语法错误。

**运行环境（系统环境及 pyecharts 版本）**
阿里云ubuntu16.04
virtualenv环境 python3.5.2

**代码及截图**

![image](https://user-images.githubusercontent.com/37569230/56074570-94fdcb80-5de7-11e9-89d4-9603d77a89a0.png)

**Comment by sunhailin-Leo** [comment]
@XuSirSir 这个问题，我这边已经进行了测试。

出现的问题分两类: 
* 第一种是 `self.options: Optional[dict]` --> 这类是的因为 Python 3.5 的语法风格不支持
* 第二种是 `):`  --> 这类是因为项目使用 black 代码格式化工具进行格式化导致的 (black 本身只支持 Python 3.6 以上)

解决方案:
* 第一种：修改源码即可
* 第二种：用 Python 3.6 的环境安装 black， 使用 `black -t py34 {source_file_or_directory}` 进行格式化(注: 实测用 py34 才可以)

Ps：如果你不闲麻烦的话可以自己手动去修改一下，再次安装看看是否成功，并成功运行项目 Demo。Thx! 😄

**Comment by sunhailin-Leo** [comment]
@XuSirSir `black` 的仓库地址 --> https://github.com/ambv/black

**Comment by XuSirSir** [comment]
能很弱的问一下，self.options: Optional[dict] 这种写法代表的什么意思吗，因为没找到相关的。

**Comment by chfw** [comment]
Typehint

**Comment by chenjiandongx** [comment]
新版的 pyecharts 将不再支持 Python3.5
