### ISSUE TITLE
新的Kline显示方式太不合理了....

### ISSUE THREAD

**Issue by raymondby** [pyecharts/pyecharts#994]
如果是有DataZoom的（不论是slider还是inside），就会在改变zoom后造成Kline显示缺失，这个算是Bug吧

**Comment by raymondby** [comment]
我发现问题可能在哪了，DataZoom的拖动是X，Y轴联动的，但是实际应用的需求是：我改变Zoom范围，目的是减少显示的K线数量，Y轴的显示范围是应该根据该部分K线的最大值和最小值进行相应调整

**Comment by chenjiandongx** [comment]
@raymondby 请拉取最新源码重新安装试试看
