### ISSUE TITLE
Django测试demo无法导入Line3D

### ISSUE THREAD

**Issue by XuSirSir** [pyecharts/pyecharts#996]

**Comment by sunhailin-Leo** [comment]
@XuSirSir Please show your code.

**Comment by XuSirSir** [comment]
thank you. I have solved this question. In Django demo,it show from pyecharts import Line3D,but from pyecharts.charts import Line3D is right.

**Comment by sunhailin-Leo** [comment]
@XuSirSir Which version? 0.5.11? or 1.0.0?

**Comment by XuSirSir** [comment]
i don‘t know what is version. beacase i use document by this link("https://05x-docs.pyecharts.org/#/zh-cn/prepare"). But i install pyecharts by source code.

**Comment by sunhailin-Leo** [comment]
@XuSirSir You can use `pip list` (if your are Python3 use `pip3 list`) to check `pyecharts` version.
If you install by source code, i think your are using pyecharts 1.0.0.

**Comment by XuSirSir** [comment]
Yes, my version is 1.0.0.  In order to more test takers avoid this question,i suggest you should revise document(https://05x-docs.pyecharts.org/#/zh-cn/prepare)

**Comment by sunhailin-Leo** [comment]
@XuSirSir 
* This document (https://05x-docs.pyecharts.org/#/zh-cn/prepare) is for version 0.5.11. 
* New document is here (https://pyecharts.org), but Django Document is revising. Thx~

**Comment by sunhailin-Leo** [comment]
@XuSirSir Or maybe you can give us the demo code for new document. Thx~

**Comment by XuSirSir** [comment]
thanks，i willing to try it，because i’m is student. i use pyecharts because of graduation project. But i'm testing pyecharts’   function in Django, if i test success, i very willing to give you the demo for new document about Django.

**Comment by chenjiandongx** [comment]
Django 示例已更新 https://pyecharts.org/#/zh-cn/web_django
