### ISSUE TITLE
0.5.11版本pip安装后没有options目录

### ISSUE THREAD

**Issue by Kewings** [pyecharts/pyecharts#997]
所以，所有的options操作都block了，求快速解决~
![image](https://user-images.githubusercontent.com/29881381/56091479-f99d5100-5ee1-11e9-8322-8a1269f9f4e9.png)

**Comment by sunhailin-Leo** [comment]
@Kewings Please show your code.

**Comment by sunhailin-Leo** [comment]
* 在使用前请认真阅读仓库说明和文档。
![image](https://user-images.githubusercontent.com/17564655/56092865-56a20280-5ef4-11e9-9d57-1042e39624bf.png)

* options 属于 1.0.0 的重构后的产物，0.5.11 不支持。若需要使用 options 方式，请卸载 0.5.11 版本后，使用源码安装 1.0.0 版本。

**Comment by Kewings** [comment]
![image](https://user-images.githubusercontent.com/29881381/56135068-8ae3f480-5fc2-11e9-8e4a-0d2fe9e3815c.png)
![image](https://user-images.githubusercontent.com/29881381/56135210-cda5cc80-5fc2-11e9-8fac-78152d7fdc24.png)

使用了git下了源码，python setup.py install后还是没有options

**Comment by Kewings** [comment]
解决了，看了首页代码，原来是2019的分支
使用2019的分支setup后，已经是1.0.0的版本了。

谢谢。

**Comment by Kewings** [comment]
解决了，看了首页代码，原来是2019的分支
使用2019的分支setup后，已经是1.0.0的版本了。

谢谢。
